### ISSUE TITLE
 Disable invites for 1:1 private DMs/direct chats by default OR ask for 2nd user's consent before actually inviting

### ISSUE THREAD

**Issue by opusforlife2** [matrix-org/synapse#10000]
**Description:**

This is a duplicate of https://github.com/matrix-org/matrix-doc/issues/3197. Since MSCs can take a long time to be merged, I'm hoping that Synapse and other homeservers can implement this ahead of spec.

TL;DR: 2nd user's consent should be obtained before an invite to a 1:1 chat is sent out to a 3rd user.

OR, invite functionality should be disabled for 1:1 chats by default, with extra steps required to enable it.

**Comment by ShadowJonathan** [comment]
> Since MSCs can take a long time to be merged, I'm hoping that Synapse and other homeservers can implement this ahead of spec.

Don't count on it.

**Comment by MTRNord** [comment]
a) Crossposting is not nice b) MSCs exist for a reason and i am 1000% sure nobody is going to bypass it as we had synapse bypass Spec before and it resulted in a terrible minefield for implementing people. Rules exist for a reason and actually doing it like this is quite rude for people taking the time to write and discuss MSCs

**Comment by MTRNord** [comment]
Also point c) Is that this is not sounding like a server only feature but sounds like it needs signaling, UI and UX to work.

**Comment by Half-Shot** [comment]
As @MTRNord said, please do not create multiple issues across multiple orgs for one problem. It will not get this issue looked at any quicker and only serves to irritate all involved. This issue is being tracked over in https://github.com/vector-im/element-web/issues/17314 and you already have maintainers involved there, so please keep the discussion there.

**Comment by opusforlife2** [comment]
Sorry about cross-posting. I came here from https://github.com/vector-im/element-web/issues/17314, and it's not like I know on which level (client/server/spec) the discussions belongs. That is the job of maintainers to decide... and it has been done so.
