### ISSUE TITLE
Debian package: sqlite db, media and logs are world-readable by default

### ISSUE THREAD

**Issue by MRAAGH** [matrix-org/synapse#10008]
The following files and directories are world-readable by default:
- /var/lib/matrix-synapse/
- /var/lib/matrix-synapse/homeserver.db
- /var/lib/matrix-synapse/media/
- /var/log/matrix-synapse/homeserver.log

All of these contain sensitive user information and should not be world-readable!

Installation package: matrix-synapse-py3 from packages.matrix.org
Synapse version: `{"server_version":"1.33.2","python_version":"3.7.3"}`
OS: Debian 10

Related issues:
- #6364 (permissions of homeserver.yaml)
- #1528 (permissions of private key)

**Comment by richvdh** [comment]
I think this is a dup of https://github.com/matrix-org/synapse/issues/2955
