### ISSUE TITLE
[LDAP] Attribute accessed but not always set.

### ISSUE THREAD

**Issue by davidmehren** [matrix-org/synapse#1001]
In `config/ldap.py` the attribute `self.ldap_filter` is only set when `bind_dn` exists in `ldap_config` (see lines 59-68). This leads to an Error in `handlers/auth.py` in line 73 where the attribute is accessed without checking for `bind-dn`.

This can be easily fixed by moving the statement in line 68 of `config/ldap.py` out of the if-statement.

**Comment by mweinelt** [comment]
fixed in e380538b594d4fa55e98818df0061efbdf3cb35b
