### ISSUE TITLE
Application Service URIs not treated as URIs

### ISSUE THREAD

**Issue by martindale** [matrix-org/synapse#10012]
Using URIs in Application Service configuration do not appear to be parsed as URIs, but rather with some kind of custom heuristic.

### Steps to reproduce
- Configure an Application Service using an URI like `https://USERNAME:PASSWORD@somehost.local/services/matrix`
- Observe failed connection to `:PASSWORD@somehost.local`

If this were parsed as a URI, which I believe is the intention, the HTTP client should receive correct `Authorization` headers for the application service. 

### Version information
- **Version**: 1.28.0

- **Install method**:
pip

- **Platform**:
Ubuntu 20.10

**Comment by tulir** [comment]
IMO this should not be fixed as it's incompatible with matrix-org/matrix-doc#2832

**Comment by erikjohnston** [comment]
I think that supporting using `USERNAME:PASSWORD` in application services would conflict with the use of an `access_token`? So even if we did correctly parse the URL we'd likely just reject it.

**Comment by richvdh** [comment]
sounds like this isn't a thing we have a viable usecase for.
