### ISSUE TITLE
Enable bridges/app services to specify a space/create a space

### ISSUE THREAD

**Issue by hanthor** [matrix-org/synapse#10025]
### Description

There is/was a way to register a bridge to add users to a specific community. We need similar functionality in spaces.

### Steps to reproduce

- try to find a variable to set in registration.yml to specify a space to add created rooms to.

**Comment by erikjohnston** [comment]
I'm not sure I totally understand what you mean? Spaces are just rooms, so application services should be able to create them as normal?

**Comment by erikjohnston** [comment]
If you want to just add created rooms to a space you can do it as normal using the AS API, without needing to add anything to the registration.yml?

**Comment by richvdh** [comment]
closing this pending the requested information.
