### ISSUE TITLE
Federation fails when using IPv6 DNS servers

### ISSUE THREAD

**Issue by benhylau** [matrix-org/synapse#1002]
Federation fails with:

> 2016-08-10 22:27:45,916 - synapse.http.matrixfederationclient - 183 - WARNING - POST-4- {GET-O-2} Sending request failed to matrix.org: GET matrix://matrix.org/_matrix/federation/v1/query/profile?field=avatar_url&user_id=%40benhylau%3Amatrix.org: InvalidA
> ddressError - InvalidAddressError: IPv4 port write() called with IPv6 address

Removing my IPv6 DNS servers in **/etc/resolv.conf** fix federation:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# nameserver 2001:4860:4860::8844 <-- comment out
# nameserver 2001:4860:4860::8888 <-- comment out
nameserver 8.8.8.8
```

Seems to be a known issue that has come up in **#matrix:matrix.org** many times.

**Comment by ara4n** [comment]
Yup. the official bug for this is https://matrix.org/jira/browse/SYN-254

**Comment by ara4n** [comment]
...and now fixed on develop by #1696, we believe :)

**Comment by ara4n** [comment]
...except apparently it's still broken on develop :(

**Comment by kyrias** [comment]
@glyph Do you know the state of using IPv6 resolvers in twisted, if there's any work going on regarding it?  Currently twisted's trunk still doesn't work with them.

**Comment by glyph** [comment]
@kyrias I'm afraid I don't understand the question. Twisted's trunk only recently added support for them.  What do you consider an "IPv6 resolver"?

**Comment by kyrias** [comment]
@glyph An IPv6 resolver is a resolver queried over IPv6.

**Comment by glyph** [comment]
@kyrias Oh, so just an IPv6 address for looking up A records, not a resolver that can resolve AAAA records? Huh. In what sense does that not work?  Are you talking about something in `twisted.names`?

**Comment by kyrias** [comment]
@glyph Yes.

    >>> from twisted.names import client
    >>> client.getHostByName('google.com')
    <Deferred at 0x7f1818a1f290 current result: <twisted.python.failure.Failure twisted.internet.error.InvalidAddressError: >>

**Comment by glyph** [comment]
@kyrias This is definitely a serious bug in Twisted. It's been filed here - https://twistedmatrix.com/trac/ticket/8877 - unfortunately that's still fairly recent.  Sorry about that!

**Comment by swift11** [comment]
@glyph Weird: it's a bug with "normal" priority in Twisted...

**Comment by glyph** [comment]
@swift11: Priority is not really used in our bugtracker. You can tell if something is _really_ high priority by whether it gets fixed or not :)

**Comment by reactormonk** [comment]
https://github.com/twisted/twisted/pull/649

**Comment by reactormonk** [comment]
Time to update boys.

**Comment by kyrias** [comment]
The dependency won't be updated when there's a new twisted release. ;P

But awesome work fixing it!

**Comment by ara4n** [comment]
@reactormonk Awesome!! huge thanks for sorting it out :) Will close the bug once we've bumped the dep.

**Comment by glyph** [comment]
Since 16.7 was [full of ghosts](https://twistedmatrix.com/trac/ticket/8963#comment:14), the next release will be 17.1 or 17.2.

**Comment by jython234** [comment]
It looks like 17.1 was just released yesterday, going to try and test it out.

**Comment by ara4n** [comment]
@jython234 let us know how you get on :)

**Comment by jython234** [comment]
It turns out my error was because of incorrect reverse proxy setup, not IPv6. I fixed it and all is well now! This should be fixed, I submitted a pull #1909 which simply bumps the dependency.

**Comment by richvdh** [comment]
so this is fixed by upgrading Twisted to 17.1.0. We should recommend that in the README, but this is fixed.

**Comment by glyph** [comment]
🙌 🎉 The system works!!!🎉🙌

**Comment by ara4n** [comment]
readme-recommendation PR is https://github.com/matrix-org/synapse/pull/2088 ftr. and \o/ for the system working
