### ISSUE TITLE
User cannot see room invite

### ISSUE THREAD

**Issue by djschilling** [matrix-org/synapse#10022]
On my synapse server i have a room with some users in it.
One user was invited to the room, but cannot see the invite in element web.

I can see the invite event in the postgres database

This is the json payload of the invite event:

<img width="591" alt="Bildschirmfoto 2021-05-19 um 18 11 39" src="https://user-images.githubusercontent.com/3503166/118847345-ec779b00-b8cd-11eb-8f0a-f713e5f3cdd9.png">

I also tried using the sync api `/_matrix/client/r0/sync` to see the users plain events but also there the event is not visible.

Other users that are in the room can see that user was invited.

So it seems that there is a problem in the `/_matrix/client/r0/sync` endpoint.

Or am i missing some authorirization thing that a user is not allowed to see his own room invitation?

synapse version: 1.32.2

**Comment by erikjohnston** [comment]
Can you check the `ignored_users` table (to see if the invitee is ignore the inviter) and `rejections` table (to see if the event was rejected) please?

**Comment by djschilling** [comment]
Thanks for your answer that helped.

In the table `ignored_users` there is an entry for the user.

How does that happen and can i savely remove this entry?

the user that was ignored there is an user i use for automation and i think the user accidently made this ignore not knowing what the user was for. Can i prevent this behaviour in the future?

**Comment by erikjohnston** [comment]
> How does that happen and can i savely remove this entry?

Yes, you may have to restart Synapse for it to take effect (due to caches). It's probably easier if the user themselves unignores the person.


> the user that was ignored there is an user i use for automation and i think the user accidently made this ignore not knowing what the user was for. Can i prevent this behaviour in the future?

Alas not. There is an issue open on element web to make it harder to so accidentally (I think other clients now have confirmation boxes?): https://github.com/vector-im/element-web/issues/14633

**Comment by djschilling** [comment]
I deleted the entries from the database and restarted matrix.
The room still does not show up for the person in element web.

Does this only have an affect on new events?

**Comment by erikjohnston** [comment]
Oh, yes, interesting failure mode for invites. They will need to hit the "clear cache" button in their client (e.g. in element web its under Settings > Help & About > Clear cache and reload). 

Alternatively you could rescind and resend the invite.
