### ISSUE TITLE
Space Summary API returns inconsistent results

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#10020]
When querying the `/spaces` API for `!iMZEhwCvbfeAYUxAjZ:t2l.io` you get many results, including 3 children of `!VlNuOBLIKmTCZXtibW:t2l.io`, but when querying the `/spaces` API for `!VlNuOBLIKmTCZXtibW:t2l.io` itself you only get 2 of its children: `!CWLUCoEWXSFyTCOtfL:matrix.org` is missing.

**Comment by clokep** [comment]
Looking into this a bit:

When querying both the root space and the sub-space I see an event that includes `!CWLUCoEWXSFyTCOtfL:matrix.org`, but it is missing from the `rooms` key.

If you join the missing room, it then appears in the room summary. It is being excluded because the `m.room.history_visibility` event has a content of:

```json
{
    "history_visibility": "shared"
}
```

And the API requires you to:

* Be jointed to the room,
* Or for the `history_visibility` to be `world_readable`.

**Comment by t3chguy** [comment]
I didn't get the event for `!CWLUCoEWXSFyTCOtfL:matrix.org` when querying `Crypto`

```json
{
  "rooms": [
    {
      "room_id": "!VlNuOBLIKmTCZXtibW:t2l.io",
      "name": "Crypto",
      "num_joined_members": 32,
      "avatar_url": "mxc://t2l.io/5c97454b12276089187fa0ee5745e087c7c5a290",
      "world_readable": true,
      "guest_can_join": true,
      "creation_ts": 1620858109106,
      "room_type": "m.space"
    },
    {
      "room_id": "!YRyTcRVrJzaHGZrsur:matrix.org",
      "topic": "Discussion between developers designing E2E encryption in Matrix (i.e. the spec, the reference implementations).\u00a0 Please only speak here if you are actively working on this; take other questions to #e2e:matrix.org",
      "canonical_alias": "#e2e-dev:matrix.org",
      "num_joined_members": 84,
      "avatar_url": "mxc://matrix.org/QYoikwpYeXeVkDvQpdcUTnzS",
      "world_readable": true,
      "guest_can_join": true,
      "creation_ts": 1574376648648
    },
    {
      "room_id": "!vlnjqGLpLJlFmBSkfQ:matrix.org",
      "name": "End-to-end crypto in Matrix",
      "topic": "Discussion around implementing and using encryption in Matrix via Olm/Megolm | Spec work and reference impl work in #e2e-dev:matrix.org",
      "canonical_alias": "#e2e:matrix.org",
      "num_joined_members": 661,
      "avatar_url": "mxc://sw1v.org/garZIuJQUDQVpSHiGEirifTB",
      "world_readable": true,
      "guest_can_join": false,
      "creation_ts": 1574381344070
    }
  ],
  "events": [
    {
      "content": {
        "auto_join": false,
        "suggested": true,
        "via": [
          "matrix.org",
          "lant.uk",
          "uhoreg.ca"
        ]
      },
      "origin_server_ts": 1620858205320,
      "room_id": "!VlNuOBLIKmTCZXtibW:t2l.io",
      "sender": "@abuse:matrix.org",
      "state_key": "!YRyTcRVrJzaHGZrsur:matrix.org",
      "type": "m.space.child",
      "unsigned": {
        "replaces_state": "$QNQbMkqLkABf-lojjx67Q8QnKCVaOpcdDKWsfQDDBNU",
        "age": 558611263
      },
      "event_id": "$r7R25UHJelu7m9BejOva4mqkCqncMsr_a917jpEevAM"
    },
    {
      "content": {
        "auto_join": false,
        "suggested": true,
        "via": [
          "matrix.org",
          "t2l.io",
          "neko.dev"
        ]
      },
      "origin_server_ts": 1620858204883,
      "room_id": "!VlNuOBLIKmTCZXtibW:t2l.io",
      "sender": "@abuse:matrix.org",
      "state_key": "!vlnjqGLpLJlFmBSkfQ:matrix.org",
      "type": "m.space.child",
      "unsigned": {
        "replaces_state": "$5PlRkNZrldcM3OFT51QZV5WeMB3fXgPeqrwBToLDQ3E",
        "age": 558611700
      },
      "event_id": "$tFbAnblXZqoMk1G-V7J3UTlxRRE_EC2XjwxYS0CHw5k"
    }
  ]
}
```

is the full response I got

**Comment by clokep** [comment]
> I didn't get the event for `!CWLUCoEWXSFyTCOtfL:matrix.org` when querying `Crypto`

It seems that Element Web makes two requests right after each other, one with `suggested_only` set to `true` and one with no body. The response to the first request matches the above, but the second request has the additional room in the list of `events` (at least that's what I'm seeing). (It still does not include it in `rooms`, unless you're in the room.)

**Comment by t3chguy** [comment]
This is weird, now its started to return the results just fine - I didn't change anything

![image](https://user-images.githubusercontent.com/2403652/118814160-bcb59c80-b8a7-11eb-8c69-af5eb7f3328b.png)

in this they probably get cropped off due to lack of pagination
![image](https://user-images.githubusercontent.com/2403652/118814210-cc34e580-b8a7-11eb-8fd8-c8e605c35e67.png)

Feels like some temporal issue which something unwedged.

**Comment by t3chguy** [comment]
This is a client issue exacerbated by lack of pagination

**Comment by clokep** [comment]
See vector-im/element-web#17387.
