### ISSUE TITLE
after a restart my proxy manager an matrix isn reachable.

### ISSUE THREAD

**Issue by fertigfs** [matrix-org/synapse#10037]
Hi guys after a restart nothing is online...
why it doesnt start automatic?
if i type docker start <container> itś ok.
iḿ a noob in docker.
could someone help my please:)

Please don't file github issues asking for support.

Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.

**Comment by babolivier** [comment]
Hi, as explained in the template that appears at the bottom of your issue, please ask any support question in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) (using a matrix.org account if necessary) since we don't use GitHub issues for support requests :slightly_smiling_face:
