### ISSUE TITLE
_count_known_servers delay

### ISSUE THREAD

**Issue by heftig** [matrix-org/synapse#10030]
https://github.com/matrix-org/synapse/blob/1c6a19002cb56cf93bc920854c81ae88bd7308ac/synapse/storage/databases/main/roommember.py#L88-L95

Is this really supposed to be 1000 seconds? `looping_call` uses milliseconds and `call_later` uses seconds.

**Comment by callahad** [comment]
FWIW, this was introduced almost three years ago in 55d5b3af8863167432017f23cd8a04a0c14c9d23 as part of #5981

**Comment by anoadragon453** [comment]
@heftig You're correct, and that definitely shouldn't be 1,000 seconds :slightly_smiling_face: 

Would you like to PR a fix? Otherwise we can take care of it.

**Comment by heftig** [comment]
> Would you like to PR a fix? Otherwise we can take care of it.

I would if I just had to make a commit with the fix, but your guidelines require a lot more work I don't have time for.

**Comment by anoadragon453** [comment]
Understandable, thanks for bringing it to our attention regardless :slightly_smiling_face:

I've opened a PR to fix this here: https://github.com/matrix-org/synapse/pull/10195
