### ISSUE TITLE
[Feature Request] Allow admin api send_server_notice to use markdown

### ISSUE THREAD

**Issue by Justinzobel** [matrix-org/synapse#10051]
**Description:**

Please allow admin api send_server_notice to use markdown.

For instance:
```
curl -X POST --header "Authorization: Bearer xxxxxxxxxxx" -d "{\"user_id\":\"@user:server\",\"content\":{\"msgtype\":\"m.text.markdown\",\"body\":\"**Planned maintenance** of the Chat (Matrix) instance will be occuring on **May 31st at 00:30 UTC** and will take approximately **2 hours**.\"}}" http://localhost:8008/_synapse/admin/v1/send_server_notice
```

**Comment by dklimpel** [comment]
I did a test. And this not a new feature. It works.
Try this:
```curl -X POST --header "Authorization: Bearer token" -d "{\"user_id\":\"@user:server\",\"content\":{\"msgtype\":\"m.text\", \"body\": \"**bold**\", \"format\": \"org.matrix.custom.html\", \"formatted_body\": \"<strong>bold</strong>\"}}" http://localhost:8008/_synapse/admin/v1/send_server_notice```

You can show the source code of a formated message in Element Web.

**Comment by Justinzobel** [comment]
> Maybe you add a good example to the documentation.
> https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/server_notices.md

PR made, thanks!

**Comment by dklimpel** [comment]
PR: #10067
