### ISSUE TITLE
Provide user-specified STUN server in addition to TURN server

### ISSUE THREAD

**Issue by talent-less** [matrix-org/synapse#10076]
**Description:**

Public stuns are blocked in many netowks and countries. It would be nice to allow users to set up their own stun server and use it in the home server, and prevent clients from using public stuns.

**Comment by richvdh** [comment]
I'm afraid I'm not really following what the usecase is here, or what this would mean from the point of view of synapse and/or the matrix protocol.

I assume you want to have two separate servers: one which only supports STUN, and one which supports TURN (as well)? 

Have you tried listing URIs both servers under `turn_uris` in `homeserver.yaml`? Although this is normally used only for TURN servers, I believe it should also work for STUN.

**Comment by richvdh** [comment]
closing this pending the requested information.
