### ISSUE TITLE
Link preview duplicate url filter considers anchor

### ISSUE THREAD

**Issue by eras** [matrix-org/synapse#10088]
### Description

When sending a URL to a room, a link preview is generated. If the same URL is sent twice, only one preview is generated. However, if the second link is the same but with an `#anchor`, the link preview is generated twice for the same content (I assume Synapse will not consider the anchor at all for the actual preview generation process).

### Steps to reproduce

- Send a URL that produces a link preview twice to a room, but add `#anchor` to the end of the second URL, e.g. `https://github.com/matrix-org/synapse/issues/10088` and `https://github.com/matrix-org/synapse/issues/10088#foo`
- Witness Synapse generating two link preview for the same content

Expected behaviour: only one link preview is generated.

### Version information

- **Homeserver**: matrix.org

**Comment by tulir** [comment]
This is a client-side problem (i.e. element web).

Synapse could optimize caching URL previews by ignoring fragments, but that doesn't really affect what users see.

**Comment by eras** [comment]
Added issue to Element/Web.
