### ISSUE TITLE
One specific user unable to see messages from one other specific user, all other users unaffected 

### ISSUE THREAD

**Issue by kavemang** [matrix-org/synapse#10099]
I have already submitted this in the matrix admin support channel and it got blank stares, I have a hunch something fucky is going on: 

hi folks, im running a private server will small userbase, I have a very weird issue where one specific user in a room cannot see one other specific users messages (its just showing "waiting for message ect")  

- the issue is one way, 
- member A cant see Member B's messages, 
- everyone else can see both members messages and Member B can see Member A's messages

the only thing out of the ordinary is Member A has moderator roll in the one channel this is happening in, in another channel where neither of them have moderator Member A can read Member B's messages

im at my wits end, no one ive talked to has seen this before and I've already tried having member B rejoin the channel 
I can try completely wiping the channel, remaking it and not assigning anyone moderator but if that works there is still some underlying issue im dodging which I don't get at all 

ive also had Member A open a direct message with member B which works fine 
the exact message placeholder that Member A sees is "Waiting for this message, this may take a while." 

both Member A and B are using element on android 

all other members of both channels can see member A and B msgs no problem

**Comment by anoadragon453** [comment]
Hi @kavemang.

Thanks for the info. It would be helpful from a Synapse developer perspective to know whether each user were on the same, or different, homeservers.

As an explanation: "Waiting for this message, this may take a while" means that the received (Member B in this case) has not yet been able to decrypt the message. Sometimes this may take a few moments, but if it takes longer than a minute then something has gone wrong in the process.

Typically this can happen if the sender (Member A) does not have an updated view of the receiver's (Member B's) "devices" (logged in sessions essentially). Has Member B just logged in to this Element Android session?

Are new messages from Member A visible to Member B in the affected room? If not, try having someone in the room type `/discardsession` into Element Web/Android and hitting enter. That should reset the encryption session in the room, which may fix the issue (for new messages).

Additionally, if Member B has any other sessions laying around (an Element Web/Desktop somewhere) bringing both devices online may allow Element Android to decrypt the message (and user sessions can share message keys with each other).

In any case, the best way to report these issues is to have both the message sender (Member A) and the receiver who is unable to view the message (Member B) send debug logs from settings (or shaking the phone), and then creating a new issue on one of the Element repo issue trackers:

* [Element Web](https://github.com/vector-im/element-web/issues/)
* [Element Android](https://github.com/vector-im/element-android/issues/)
* [Element iOS](https://github.com/vector-im/element-ios/issues/)

The logs do not contain any message information - but will tell us when devices are trying to send keys to each other, which may help us track down where things fell apart. Given you have created an issue already, feel free to simply submit debug logs (if possible) and let me know here when you do so. I'll then link them to this issue internally.

I'm going to move this issue to the Element Android repository for now however, as often these issues are on the client side.

**Comment by kavemang** [comment]
Hi, thanks for the details about what the msg means as far as sessions and clients 

my users are laymen and so I can't ask them to make accounts on github, just installing a new app was a stretch for some of them 

Right now I'm having them try a couple things: 

- Member B I am asking to install the desktop version of element and verify their new session in the hopes they reissue decryption keys to member A 

- Member A i am asking to try the /discardsession when they are off work later with the understanding that they will lose previous messages but may gain the ability to see member A messages once they establish a new session 


If neither of these work I will see if they can figure out how to pass me the debug logs and I will add those here perhaps 

Thanks very much for your help and patience

**Comment by anoadragon453** [comment]
Element will send debug logs directly to our internal debug log server, so they shouldn't need to make an account on GitHub. The app will just ask them to provide a short description of the issue. Putting your username or some other identifiable information in so that I can link it to this issue is all they need to do.

Otherwise let me know if they have further issues with the new devices.

**Comment by kavemang** [comment]
Thanks so far member A has submitted the debug log qnd they included my username "kavemang" as well as the letter or name Andrew / A to indicate they are user A in the scenario above

**Comment by kavemang** [comment]
@anoadragon453 

Hi, my member B has just submitted bug log also with the description "for kavemang user B" 

both logs are submitted now, member B also tried clearing session with no luck beforehand

**Comment by kavemang** [comment]
@anoadragon453 

Hi after having user A forget / erase all sessions and start over logging in and verifying a second client afterward the issue is resolved

**Comment by anoadragon453** [comment]
Thanks for the bug reports, I've forwarded them to the right people. Glad to hear it's working now though -- we'll try to figure out what happened initially.

**Comment by kavemang** [comment]
@anoadragon453 Hi, sorry to bug you about this, but do you know who I can send more debug logs to? this issue has returned since a week or two ago, it's the exact same two users but the message is now the following: 



> Due to end-to-end encryption, you might need to wait for someone's message to arrive because the encryption keys were not properly sent to you

**Comment by anoadragon453** [comment]
@kavemang do you know whether either homeserver you guys are on is running Synapse v1.38.0? There was a regression which caused issues with encryption on Element Android: https://github.com/vector-im/element-android/issues/1721#issuecomment-887527850

Although, if you both are on Element Android >1.1.14 things should be working...

The best thing to do is to shake the phone to report a bug, and include https://github.com/vector-im/element-web/issues/2996 in the description (along with any other contextual information you can provide). I would also include https://github.com/matrix-org/synapse/issues/10099 (this issue) for linkability.

**Comment by kavemang** [comment]
@anoadragon453 both users are on the same home server running off docker w watchtower so i think it should always be up to date. I will ask them both to submit another bug report with the specifics above

**Comment by HammyHavoc** [comment]
Encountered this problem today.

I'm running my own Synapse home server, but a user on @matrix.org triggered this warning, but just for one message, which never resolved itself.

However, that same user on @matrix.org was talking to another @matrix.org user, and they only solely get 'Unable to decrypt: The sender's session has not sent us the keys for this message. Re-request encryption keys from your other sessions', bi-directionally. Applies to calls as well as messages.

They're both iOS users.

**Comment by HammyHavoc** [comment]
Addendum: fixed it! They had enabled 'Never send messages to untrusted sessions'. :- )

**Comment by kavemang** [comment]
@HammyHavoc @anoadragon453 

I dont think this is the same issuen my users are on the same homeserver and dont have that encryption option turned on

**Comment by kavemang** [comment]
@anoadragon453 should I give up on this and delete the room and remake it?

**Comment by anoadragon453** [comment]
@kavemang Encryption issues usually aren't related to the room, but the users participating. However, it is interesting that you mention this problem only happening in one room.

You can try running `/discardsession` in the room to ratchet forward to a new encryption session. While this should be happening automatically at least every 24 hours, it still may be worth trying.

**Comment by kavemang** [comment]
@anoadragon453 
after discard session the issue seemed to resolve ty!

 it's now happening in 1:1 DMs however, between me and a user and between that user and another, all on my homeserver (non-federated) 

https://github.com/vector-im/element-android/issues/3916

I've had shake reports done from both of my users experiencing issues
