### ISSUE TITLE
Remove unstable MSC2858 APIs 

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#10103]
Followup to #9627 for APIs defined in https://github.com/matrix-org/matrix-doc/pull/2858

We're aiming to implement this no sooner than the first release in August. By the calendar, that should be Synapse ~~1.38~~ 1.40. Thus, we can implement any time after ~~1.37~~ 1.39 has branched.

Blockers:

- [x] Synapse ~~1.37~~ 1.39 has been branched
- [x] https://github.com/vector-im/element-ios/issues/4362

Tasks:

- [x] Notify client teams of impending change and get sign-off
  - [x] Element iOS
  - [x] Element Android
  - [x] Element Web
- [ ] Disable experimental flag on matrix.org
- [ ] ~~Monitor for a few days~~
- [x] Remove code from `develop`

**Comment by richvdh** [comment]
The first release in August is going to be 1.40, for the record.

**Comment by richvdh** [comment]
MSC2858 support is gated by an experimental flag, so the first step here is probably to turn that off on matrix.org.

**Comment by callahad** [comment]
@richvdh notes that we can check if anyone is calling the _unstable endpoint.

**Comment by callahad** [comment]
@richvdh to do that, and @reivilibre to observer (welcome (back) to the team!)

**Comment by reivilibre** [comment]
I went through the haproxy logs (thanks for your help Rich!) on matrix.org and found that we have roughly between 20 and 100 hits to this unstable API per hour.

I took a sample of one hour on one haproxy and found that all 47 requests were from iPhones.

There is already an issue to switch to the stable API, which I have commented on: https://github.com/vector-im/element-ios/issues/4362 has been opened

**Comment by reivilibre** [comment]
N.B. just for the sake of it, I found https://github.com/vector-im/element-android/issues/3442 — Android has already changed over

**Comment by richvdh** [comment]
The element iOS team expect to have an update in the app store in two weeks, and recommend waiting another week after that, for 95% penetration of the new version.

So, we should be able to revisit this w/c 23rd August.

**Comment by squahtx** [comment]
We checked with the iOS team again and they're seeing 94% adoption of 1.5.1 today, using a possibly more accurate metric(?). We'll give it another week.

**Comment by squahtx** [comment]
Today (2021-09-09), 99.8% of iOS users are on 1.5.0+ according to the iOS team.

Between 2021-09-01 and 2021-09-08 we've also seen a drop in the rate of requests to the deprecated endpoints, from 37/hour to 10/hour.

**Comment by squahtx** [comment]
Now waiting for #10693 to go into an RC and be deployed on matrix.org

**Comment by squahtx** [comment]
Live on matrix.org now.
