### ISSUE TITLE
Docs Website: Existing Table of Contents in markdown documentation

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#10127]
When viewing the [contributing](https://matrix-org.github.io/synapse/develop/development/contributing_guide.html) and [installation](https://matrix-org.github.io/synapse/develop/setup/installation.html) instructions on the new docs website, one finds that a table of contents exists on the page as well as in the sidebar. These table of contents make sense when viewing the documentation on GitHub, but less so when using the docs website which automatically generate one.

It's worth pointing out that GitHub have also started to generate a table of contents for pages, though the feature currently isn't known to the majority of people:

![image](https://user-images.githubusercontent.com/1342360/120791597-4f9f3980-c52c-11eb-8749-0a66958d53fa.png)

We could certainly add some [custom CSS](https://github.com/matrix-org/synapse/tree/develop/docs#configuration-and-theming) to our mdbook instance to hide table of contents on the website, while simultaneously keeping them on GitHub. But I'm leaning more towards the opinion of just telling people to use the website instead if they want a table of contents to browse the docs with (or point them at GitHub's button).

**Comment by richvdh** [comment]
removing the TOCs, and linking to the docs website where possible, sounds good to me.

**Comment by richvdh** [comment]
@anoadragon453 are we agreed that we should just remove the manually-maintained ToCs rather than mess about with magic CSS?

**Comment by anoadragon453** [comment]
@richvdh yep.
