### ISSUE TITLE
synapse/app/admin_cmd.py still using removed storage.presence

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#10128]
synapse/app/admin_cmd.py still using removed storage.presence:
`from synapse.replication.slave.storage.presence import SlavedPresenceStore`

_Originally posted by @vitlav in https://github.com/matrix-org/synapse/issues/9820#issuecomment-854150858_

**Comment by anoadragon453** [comment]
This file is used for the exfiltration of historical data in case of GDPR requests. Definitely something we'd like to have working when required, and we should probably fix it for the next release.
