### ISSUE TITLE
.m.rule.master behavior does not match spec

### ISSUE THREAD

**Issue by jscheel** [matrix-org/synapse#10131]
### Description
According to the pushrules section of the client server spec at https://matrix.org/docs/spec/client_server/r0.6.1#m-rule-master, enabling the `.m.rule.master` should disable all default pushrules, but not any custom overrides. However, enabling this rule also disables custom overrides.

### Steps to reproduce

- enable the `m.rule.master` pushrule
- create a custom override pushrule
- send an event that your custom pushrule should match on

The expected behavior would be for the user-defined pushrule to still fire, but it does not. Looking at the base definition for `.m.rule.master`, it doesn't make sense that the rule would be able to work as the spec describes, because you can't place a custom rule before a default rule, and this default rule will match everything.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:
Not publicly available, but will behave the same regardless

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
v1.32.2

- **Install method**:
Helm chart

- **Platform**:
Running in k8s

**Comment by ShadowJonathan** [comment]
Just for prosperity, could you also test this on matrix.org? (It's running a more recent version of synapse)

**Comment by richvdh** [comment]
this is a problem with the documentation rather than the implementation, since the docs are meant to reflect the implementation: https://github.com/matrix-org/matrix-doc/issues/2707
