### ISSUE TITLE
Why is synapse sending push notifications for read receipts?

### ISSUE THREAD

**Issue by alariej** [matrix-org/synapse#10186]
Is there a reason why read receipts would generate push notifications? I can see this type of notification being sent to my push gateway by the matrix.org server, each time a read receipt is generated in a room:

```
{
  notification: {
    counts: { unread: 0 },
    devices: [{
      app_id: 'com.myapp.android',
      data: { format: 'event_id_only', lang: 'en' },
      pushkey: 'f46MmqaqTPCY...I3kUjCTBlXHt7iQ9Idf',
      pushkey_ts: 1623849036
    }],
    id: '',
    sender: '',
    type: null
  }
}
```
The notification is mostly empty and does not contain any event ID, room ID, sender or type.

I tried disabling push notifications completely (push rule `.m.rule.master` enabled and set with 'dont_notify'), the read receipt notifications still get pushed. I also tested on various clients: no difference observed.

I found this issue which might be related: https://github.com/vector-im/element-web/issues/17263

Should read receipts really trigger push notifications?

**Comment by erikjohnston** [comment]
Unfortunately yes, this is expected, as its used to reset the "badge counts" on the apps (i.e. the number on the app shortcut representing number of unread messages/rooms).

We could potentially add an option for clients to opt out of getting such pushes, but I'm not sure if anyone would use it.

**Comment by alariej** [comment]
I see. Thanks for the info. Perhaps a short note in the Matrix API documentation would be enough.
