### ISSUE TITLE
MSC1711 Upgrade FAQ should be removed from the docs sidebar

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#10216]
This document isn't very relevant going forward. We probably don't need to keep it top-level.

The 1.0 UPGRADE notes already link to it. We should change that link to a github permalink and just remove it from the repo.

**Comment by richvdh** [comment]
honestly most of that doc can probably go away altogether.

**Comment by dklimpel** [comment]
This was fixed by
- #11907
