### ISSUE TITLE
Deleting all media uploaded by specific user

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/synapse#10229]
there should be an option to delete all media uploaded by specific user or deleting a user should delete the uploaded files on the server 

spammers are taking advantage of this issue through using flooding bots to upload bulk data on the server and flood it there should be an options to ban this behavior

**Comment by dklimpel** [comment]
See also #9565

**Comment by clokep** [comment]
Seems to be a duplicate. @githuberyt please search for issues before filing new ones! I've seen a few issues that you've filed multiple of now, it makes it harder to find issues if there are many duplicates.
