### ISSUE TITLE
invite rejections are not sent over federation

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#10222]
Suppose:
 * A and B are in a room (each on a different homeserver)
 * A invites C (on a third homeserver)
 * C rejects the invite (and thus sends a leave event via `send_leave` to A)

The invite rejection *should* be sent out over federation to B, but this does not take place.

**Comment by richvdh** [comment]
This tends to resolve itself fairly quickly because as soon as `A` sends another event, the other homeservers will pull in the missing `leave` via `get_missing_events`. But still, it's messy.

**Comment by ShadowJonathan** [comment]
Thought: isn't this essentially some form of partial mesh routing?
