### ISSUE TITLE
disable access tokens for users 

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/synapse#10230]
is it possible to prevent access token for users on server ? 

i think if the server admin can control this then it will be good option to kick out spammers

**Comment by dklimpel** [comment]
You can deactivate users by API https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html#deactivate-account

**Comment by dklimpel** [comment]
You can also invalidate specific access tokens of an user https://matrix-org.github.io/synapse/develop/admin_api/user_admin_api.html#delete-a-device

**Comment by clokep** [comment]
@githuberyt Please use https://matrix.to/#/#synapse:matrix.org for support questions before filing issues.
