### ISSUE TITLE
Auto-joining a remote autojoin room doesn't work reliably

### ISSUE THREAD

**Issue by benbz** [matrix-org/synapse#10233]
### Description

Users registering on HS B can't auto-join a room on HS A that's listed in `auto_join_rooms` if they are either the 1st user on HS B or if there are no users on HS B that are in the room on HS A.

### Steps to reproduce

- HS A has a public, federatable room with an alias
- HS B sets `auto_join_rooms` to include the room on HS A
- If there are no existing users on HS B:
  - 1st user registers
  - Auto-joining skipped with `Cannot create room alias #HS-A:room-alias it does not match server domain`
- If there are existing users on HS B and no-one on HS B is in this room
  - Registrations after setting `auto_join_rooms` as per the above fail with `Failed to join new user to '#HS-A:room-alias': AssertionError()`
  - This repeats until someone manually joins the room on HS A
  - I believe this is because if there's no local copy of the state, then an invite is assumed - https://github.com/matrix-org/synapse/blob/1c8045f67477599fabc5759205c018e44d770078/synapse/handlers/register.py (Lines 453-471)

The expectation is that `auto_join_rooms` works with any public room local or federated.

### Version information
- **Homeserver**: Any 2 publicly federated servers
- **Version**: 1.36.0
- **Install method**: Docker
- **Platform**: Linux

**Comment by erikjohnston** [comment]
I think https://github.com/matrix-org/synapse/blob/1c8045f67477599fabc5759205c018e44d770078/synapse/handlers/register.py#L455-L469 is the problematic logic here. I think we can fix it by adding a check to see if the host is in the room and the alias is remote.

We also need to handle the case where auto creating auto join is enabled but the alias is remote:
https://github.com/matrix-org/synapse/blob/1c8045f67477599fabc5759205c018e44d770078/synapse/handlers/register.py#L388-L393
