### ISSUE TITLE
certain users can only be deleted with erase: false

### ISSUE THREAD

**Issue by ajs124** [matrix-org/synapse#10240]
### Description
I was purging a few thousand users an appbridge left behind, all with `{ "erase": true }`, but got `{"errcode":"M_UNKNOWN","error":"No row found (profiles)"}` for a few dozen of them.
Without `erase: true`, I could successfully deactivate them.

### Steps to reproduce
- Try to delete users with erase: true
- Observe failure
- Try to delete same users without erase: true
- Observe success

### Version information
- **Homeserver**:
synapse @ helsinki-systems.de
- **Version**:
`{"server_version":"1.36.0","python_version":"3.8.9"}`
- **Install method**:
NixOS module
- **Platform**:
NixOS 21.05

**Comment by dklimpel** [comment]
Do you have informations about this issue from your log file (`homeserver.log`)?

**Comment by ajs124** [comment]
I got this from the journal, for the failed request:
```
synapse.http.server: [POST-199343] <XForwardedForRequest at 0x76f9bed0c6d0 method='POST' uri='/_synapse/admin/v1/deactivate/@[bridged user]' clientproto='HTTP/1.1' site='8080'> SynapseError: 404 - No row found (profiles)
synapse.access.http.8080: [POST-199343] ::ffff:127.0.0.1 - 8080 - {@[me]} Processed request: 0.072sec/-0.000sec (0.016sec, 0.007sec) (0.009sec/0.031sec/14) 57B 404 "POST /_synapse/admin/v1/deactivate/@[bridged user] HTTP/1.1" "curl/7.76.1" [0 dbevts]
```
For the successful request:
```
synapse.handlers.deactivate_account: [user_parter_loop-30710] User parter parting '@[bridged user]'
synapse.handlers.deactivate_account: [user_parter_loop-30710] User parter finished parting '@[bridged user]'
synapse.access.http.8080: [POST-199767] ::ffff:127.0.0.1 - 8080 - {@[me]} Processed request: 0.078sec/-0.000sec (0.024sec, 0.008sec) (0.010sec/0.038sec/16) 37B 200 "POST /_synapse/admin/v1/deactivate/@[bridged user] HTTP/1.1" "curl/7.76.1" [0 dbevts]
```

**Comment by dklimpel** [comment]
It seems that your users have no profile in the database table `profiles`. For whatever reason this is so.

**Comment by ajs124** [comment]
Right. I have a database dump that I could verify this with, if needed, but I'd rather not have to, because it's >50GB.

So, why does this fail then, if there is no profile and is this expected behavior, should this be silently ignored or what should happen here?

**Comment by dklimpel** [comment]
If you try to deactivate a user with `{ "erase": true }`. Synapse try to unset avatar_url and displayname in profile table. If your user has no profile, it goes wrong. 
One solution is that `set_avatar_url` and `set_displayname`  or the `DeactivateAccountHandler` have to catch this exception.

**Comment by dklimpel** [comment]
@ajs124 do you have an answer for https://github.com/matrix-org/synapse/pull/10252#issuecomment-868649876 ?

**Comment by ajs124** [comment]
Not sure. I think in my case it might have been [matrix-appservice-irc](https://github.com/matrix-org/matrix-appservice-irc) somehow screwing up? Although the users not having displaynames would also explain issues I was seeing when using it, at the time. Namely, those (bridged) users being displayed with their matrix ID(?) instead of a proper name.
