### ISSUE TITLE
Kicked user keeps his role

### ISSUE THREAD

**Issue by Hyurt** [matrix-org/synapse#10266]
### Description

User that get kicked from a room with a specific role (moderator) gets back its role when reinvited into the room

### Steps to reproduce

- Create a room
- Invite a user
- Grant him moderator role 
- Kick him from the room
- Reinvite the user into the room
- Check his role
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org

Question is, should a kicked user get his role back or should it be deleted once he's kicked ?
Note, I haven't checked ban but this could be be the same issue if he is unbanned

**Comment by dklimpel** [comment]
I am did a lot of tests.
When a user leaves a room, also if he becomes disabled, he keeps his permission.
I assume that that Synapse need a room admin to degrade the permission. This is not always the case.
What happens: A leave event is created, but the power_levels remain unchanged.

**Comment by clokep** [comment]
I think this sounds more like a spec question than a Synapse bug. I think this is working as designed at the moment?

**Comment by richvdh** [comment]
yes, this is as designed.
