### ISSUE TITLE
Exception 401 Unauthorized while adding new threepids.

### ISSUE THREAD

**Issue by Sr-Preet** [matrix-org/synapse#10262]
Can anyone please help me regarding this issue.
I'm getting Exception 401 Unauthorized while adding new threepids. 
Attaching the screenshot of the log.
![Screenshot (33)](https://user-images.githubusercontent.com/55445693/123623800-80bd1200-d82b-11eb-81a4-5b663b6ed9cc.png)

**Comment by babolivier** [comment]
Please use [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) for support requests :slightly_smiling_face:
