### ISSUE TITLE
followup on asynchronous-federation work

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#10275]
A few things it might be good to think about having landed #10272:

* [x] we disabled a few tests. We should fix and re-enable them.
   * [x] sytest: `Outbound federation will ignore a missing event with bad JSON for room version 6`
     #10345
   * [x] sytest: `Backfilled events whose prev_events are in a different room do not allow cross-room back-pagination` 
     #10292
   * [x] sytest: `Federation rejects inbound events where the prev_events cannot be found`
     #10357
   * [x] complement: `Outbound federation will ignore a missing event with bad JSON for room version 6`
     https://github.com/matrix-org/complement/pull/152
* [x] There's nothing stopping the queues building up almost indefinitely. We need to figure out what to do if a server can't keep up with the inbound traffic. https://github.com/matrix-org/synapse/pull/10390
* We previously had a rudimentary form of this queue which kicked in while we were joining a room over federation (see `room_queues` in `FederationHandler`. I think we should update that code to use the same logic. (parking this for now - we'll revisit it as part of future join work)
* [x] #10295
* [x] The new queues need some monitoring.
* [x] ~~We now only process one event per room at a time.~~ Not expected to be significant

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/sytest/pull/1059 fixes one of the tests.

**Comment by clokep** [comment]
This also seems to be causing a complement test to fail: `TestOutboundFederationIgnoresMissingEventWithBadJSONForRoomVersion6`

**Comment by ShadowJonathan** [comment]
...now *that* is a java-worthy name

**Comment by clokep** [comment]
matrix-org/complement#142 updates complement to match the sytest blacklist applied in #10272.

**Comment by erikjohnston** [comment]
Some more monitoring has been added at https://github.com/matrix-org/synapse/pull/10284 and https://github.com/matrix-org/synapse/pull/10279
