### ISSUE TITLE
Synchronization is stuck after login, can't use Matrix anymore

### ISSUE THREAD

**Issue by kalon33** [matrix-org/synapse#10281]
### Description

When logging in using any clients (various Element versions tested, Pattle too), I can login in, synchronization is started, but it never finishes, and no network trafficking happen after that point. It seems to only affect my account on my Synapse instance, as my wife one and another one I created are not affected.

### Steps to reproduce

Not sure of the steps needed to reproduce the bug to lead to that state, but now every time I connect that happen.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
I don't know what I should look at in my logs, and I have messages from federation... So please ask what would be interesting, and I will provide it.
### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 

spiralo.net (my own one)

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
1.35.1, but it happened before, as I have the problem since April I think.
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
deb package provided by the project
- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Ubuntu 18.04LTS, on a non-virtualized hardware (bare metal). Had no problem with it before, and I'm running Synapse for at least 2 years now on it.

**Comment by babolivier** [comment]
Heya, thanks for reaching out! We're only using GitHub issues for bug reports I'm afraid, so please use [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) or the discussions tab for support requests.

**Comment by kalon33** [comment]
@babolivier Hi, so I got trouble with sync from matrix-synapse in certain conditions, but this is surely not a bug?

**Comment by dontlaugh** [comment]
Something like this recently started happening to me too. Fedora 34 package upgrade from 1.37, and I can't create a new login session. Other users on my personal server are still logged in, but cannot make new sessions.

**Comment by 153** [comment]
I'm getting this from a fresh install. Users can create accounts, and use the session created at that point, but not log into their account after that. I host multiple Matrix servers and tried multiple clients -- this is a Matrix bug @babolivier . I went to the #synapse room and our conclusion is that either Matrix is buggy or my computer is haunted.

**Comment by richvdh** [comment]
If you think you have a bug, please open a new issue, with more details, including logs and screenshots.
