### ISSUE TITLE
Remove /send_relation support

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#10285]
As it [has been removed from MSC 2674](https://github.com/matrix-org/matrix-doc/pull/2674#discussion_r661499773). The code in question is at https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/rest/client/v2_alpha/relations.py#L87

**Comment by richvdh** [comment]
I don't think this needs any extra info from the reporter

**Comment by clokep** [comment]
I was waiting for MSC2675 to merge to take a look at this, didn't realize that MSC2674 was what originally included this. I'll take a look!

**Comment by clokep** [comment]
This was specifically removed from the MSC in [matrix-org/matrix-doc@`db6213b` (#2674)](https://github.com/matrix-org/matrix-doc/pull/2674/commits/db6213b27eb29e055f38c3b5e253910fdbe1574a) from MSC2674.
