### ISSUE TITLE
Cannot add email to my Synapse account / Postfix refused to authenticate using CRAM-MD5

### ISSUE THREAD

**Issue by tfl** [matrix-org/synapse#10280]
During testing my synapse installation I also wanted to add my email address to my account. I have a fully working Postfix environment and I gave it a try. Here are my current smtp settings:

```
email:
  smtp_host: "my SMTP hostname"
  smpt_port: 578
  smtp_user: "my useraccount which works"
  smtp_pass: "correct password"
  require_transport_security: true
```

Here is what Postfix thinks about it:
```

Jun 30 13:28:04 ... postfix/smtpd[125295]: Anonymous TLS connection established from ...: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256
Jun 30 13:28:06 ... postfix/smtpd[125295]: warning: ...: SASL CRAM-MD5 authentication failed: "some random noise here"
Jun 30 13:28:06 ... postfix/smtpd[125295]: disconnect from ... ehlo=2 starttls=1 auth=0/1 quit=1 commands=4/5
```

Why is Synapse trying to use CRAM-MD5? Its not enabled on my system and I am not going to enable it. We have LOGIN, PLAIN and TLS 1.3

My Synapse installation is up-to-date; installed via PIP and virtualenv, Python 3.9.5, Archlinux

**Comment by babolivier** [comment]
Heya, thanks for reaching out! We're only using GitHub issues for bug reports I'm afraid, so please use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) or the discussions tab for support requests.
