### ISSUE TITLE
Add support for e-mail provider blacklist

### ISSUE THREAD

**Issue by jonasled** [matrix-org/synapse#10299]
**Description:**
Hi, I'm thinking about writing a small extension for synapse, to load a blocklist for e-mail provider. This is needed, because at the moment there a massive spam acounts registered on multiple Server using temporary mail provider. It would be nice if I get some feedback about this feature.

**Comment by erikjohnston** [comment]
You can use the module interface to reject or shadown ban registrations depending on email (amongst other things), c.f.: https://matrix-org.github.io/synapse/develop/modules.html
