### ISSUE TITLE
There is no underscore in the character class in the regular expression capture for charset detection in URL previews

### ISSUE THREAD

**Issue by srividyut** [matrix-org/synapse#10307]
### <s>There is no underscore in the character class in the regular expression capture for charset detection</s> >> There is no underscore in the character class in the regular expression capture for charset detection in URL previews
 
[line61](https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/rest/media/v1/preview_url_resource.py#L61)
https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/rest/media/v1/preview_url_resource.py#L61

[line63](https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/rest/media/v1/preview_url_resource.py#L63)
https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/rest/media/v1/preview_url_resource.py#L63

- When used in countries other than Europe and the United States, garbled characters are awkward on web pages that use certain character codes. As you know the names of these character codes, we also use underscores.
- The fix is 2 lines but only 2 character correction.

 <s>`([a-z0-9-]+)` -> `([a-z0-9-_]+)`</s>
(21/07/16 02:00) `([a-z0-9-]+)` -> `([a-z0-9_-]+)`
 <ins datetime="2021-07-16T02:00:00 ">
<p>
(21/07/16 02:00) Hyphens need to be escaped unless they are at the beginning or end. The "Source Editor Screenshot" is also incorrect, so I deleted it.</p></ins>

- When I added an underscore and sent a message including a URL from the client, the content containing the underscore in the name of the character code such as Shift_JIS was displayed without garbled characters.
- [Pull request with the same content](https://github.com/matrix-org/synapse/pull/10306#partial-pull-merging) / Sorry for being a beginner in python.
Ignore this as it seems to be excluded in the test
- Or I read deeply that there may be a deep reason why there is no underscore.

**Comment by richvdh** [comment]
please could you explain what the user-visible symptoms of this issue are?

**Comment by srividyut** [comment]
babolivier, thank you for fixing the wrong grammar.

**Comment by clokep** [comment]
I'm assuming this is to match additional charsets, e.g. both Shift-JIS and Shift_JIS? This should probably be fine. Do you get mojibake without this change?

**Comment by srividyut** [comment]
Sorry for the late reply.
Mr. clokep, in the case of Shift_JIS, mojibake occurred without the changes described above.

### Steps to reproduce

I referred to the following article to find the "sample URL for verification". 

[https://w3techs.com/technologies/overview/character_encoding](https://w3techs.com/technologies/overview/character_encoding)
( The usage rate of Shift_JIS is 0.1%, but it also includes [ITMedia](https://www.itmedia.co.jp/), a media conglomerate. Kakaku.com is also often used. ) 
Below is a screenshot of the WEB client version of "Element" connecting to "Synapse", creating a room and sending some URLs. All the pasted URLs are WEB pages using Shift_JIS. 
(To avoid past cache hits, I chose a different path, the content site is the same)

![mxs-mojibake1](https://user-images.githubusercontent.com/303477/125469898-232ea65e-d363-4c37-9975-c1e28cb93a59.jpg)

When I changed the regex character class, restarted the server and did the same, it looked like the screenshot below. 

![mxs-fixed1](https://user-images.githubusercontent.com/303477/125469925-335299ca-b0b9-4299-8bcf-aaa5a1884f0e.jpg)

### I checked the response header from firefox's web development tool
- https://kakaku.com/
- https://news.nifty.com/
- https://www.jalan.net

It seems that the above two URLs pasted in the verification image did not have a charset definition in the content-type of the HTTP response header.

For the third www.jalan.net, even if the HTTP response header contains "charset = Windows-31J", it is not output properly as a result. (I haven't tracked how it's used, but it's clearly defined in the hash variable in webencodings.labels. [*Equivalent to here](https://github.com/gsnedders/python-webencodings/blob/513de30767127a7b34a7b3218358206b41c6135f/webencodings/labels.py#L213) ) 

If the character code information in the meta tag is a character code name that includes an underscore and the encoding information cannot be obtained in the HTTP header, it will be treated as utf-8, so the characters will be garbled. 

There is a recognition that in the past situation in Japan, in order to avoid the occurrence of problems, the WEB server side tended not to clearly set a specific character set for sending headers. At least in the era when "individual blog operation including servers" became popular, it was seen in many "server setting articles" introduced by individuals. My personal server has the same settings as those. 

I tried my best with machine translation and wrote it desperately, I'm sorry if there is something rude

**Comment by clokep** [comment]
@srividyut Thanks for including the screenshots! That makes it clear what's happening. I think the original PR you had put up (#10306) was correct. You'll just need to:

* Add a newsfile
* Sign-off on your commit
* Run the linting scripts

https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#9-submit-your-patch has a bit more info about this.

**Comment by srividyut** [comment]
There was a mistake not only in the grammar but also in the "fixed code".
It should have been inserted before the hyphen at the end. Of course I will fix it.
