### ISSUE TITLE
Answer/Make Call & Invite To Call On Other Device

### ISSUE THREAD

**Issue by trymeouteh** [matrix-org/synapse#10309]
A feature which can be integrated into clients which will allow someone to accept the call on their phone but instead of accepting the call to be on their phone, it will be answered on their computer.

This way you can have a device like a phone be like a remote and you can answer a call, make a call or invite someone to the call but the call itself will take place on another device such as your computer.

The use case for such a handy feature will be for gaming since overlays in-game can be messy since overlays do not work or all games and a better way to start a voice chat, accept a voice chat or invite someone to a voice chat will be to use another device such as your phone to do this but have the voice chat on your computer that you are gaming on.

This will be handy feature for gamers and can make Matrix a good voice chat platform for gamers.

**Comment by babolivier** [comment]
VoIP is a client-side feature (Synapse is only passing events through in this case). This sounds like a spec issue, so I'd suggest opening an issue on https://github.com/matrix-org/matrix-doc instead.

**Comment by trymeouteh** [comment]
https://github.com/matrix-org/matrix-doc/issues/3268
