### ISSUE TITLE
Docker "generating a config file" step no longer works

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#10312]
Running https://github.com/matrix-org/synapse/blob/e550ab17adc8dd3c48daf7fedcd09418a73f524b/docker/README.md#generating-a-configuration-file in a fresh environment yields:

```
➜  synapse-test docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=my.matrix.host \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate
Config file '/data/homeserver.yaml' already exists. Generating any missing config files.
➜  synapse-test ls
➜  synapse-test 
```

**Comment by babolivier** [comment]
`--mount type=volume` creates/uses a docker module according to https://docs.docker.com/storage/volumes/

If you run `docker volume inspect synapse-data` and then `ls` whatever path it shows as `Mountpoint` (`/var/lib/docker/volumes/synapse-data/_data` in my case) it shows a bunch of files including `homeserver.yaml`. This is pointed out by the readme file (just underneath the `docker run` command):

> The above command will generate a `homeserver.yaml` in (typically) `/var/lib/docker/volumes/synapse-data/_data`. You should check this file, and customise it to your needs.

In your case I can see Synapse logs `Config file '/data/homeserver.yaml' already exists`, which means the file seems to exist in the docker volume as expected, so I'll close this issue.
