### ISSUE TITLE
Remove undocumented `room_alias` key from `/createRoom` response

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#10321]
we should either spec this or remove it.

Presumably it exists to save clients the bother of having to construct their own fully-qualified aliases, but given we don't do the same for other endpoints which create aliases, I'm not convinced it is worthwhile.

I'd therefore be in favour of removing it, but it's worth noting that sytest currently uses it in a non-trivial number of places

**Comment by turt2live** [comment]
The referenced PR has a bit of a troubled history on this. What are you seeing as an end goal for this issue?

**Comment by richvdh** [comment]
IMHO we should stop synapse returning the unspecced field.

**Comment by ShadowJonathan** [comment]
Will that break clients which depend on this behaviour?

**Comment by richvdh** [comment]
> Will that break clients which probably depend on this behaviour?

yes, of course. 

> Do such clients exist?

well, that is the $1M question...

**Comment by turt2live** [comment]
> IMHO we should stop synapse returning the unspecced field.

OH. Github mobile said this issue got transferred *from* synapse *to* matrix-doc, but on web it's clearly the other way around. This makes sense.

**Comment by DMRobertson** [comment]
I have asked the [client developers room here](https://matrix.to/#/!XXSJTvRPInupfUgQVb:matrix.org/$G6Z-sO1OmK912_qFlZTZFaEFSdJ3xfh1vMf7_Mi01_E?via=pixie.town&via=matrix.org&via=element.io).

**Comment by ShadowJonathan** [comment]
`ruma` also doesn't acknowledge this key, dropping it silently.

**Comment by bmarty** [comment]
@DMRobertson I cannot edit your message but for Element Android (actually Android SDK), this is [not in use](https://github.com/vector-im/element-android/blob/main/matrix-sdk-android/src/main/java/org/matrix/android/sdk/internal/session/room/create/CreateRoomResponse.kt#L27)

As iOS, we only use the roomId.

**Comment by DMRobertson** [comment]
No known clients seem to use this field. I think we should remove it.

**Comment by DMRobertson** [comment]
To fix this:

- Remove these lines

https://github.com/matrix-org/synapse/blob/84ddcd7bbfe4100101741a408a91f283a8f742c7/synapse/handlers/room.py#L1019-L1021

- Add a changelog entry ending in `.removal`
- Fixup any test failures

**Comment by thezaidbintariq** [comment]
@clokep can you merge the PR?

**Comment by clokep** [comment]
> @clokep can you merge the PR?

It is in the review queue and will get reviewed by a member of the team.
