### ISSUE TITLE
Markdown Formatting

### ISSUE THREAD

**Issue by duckbrain** [matrix-org/synapse#1033]
If I were to create a pull request to have **markdown formatting** in the synapse web interface, what is the likelihood it would be merged? :smile: 

The only concern I could see is that it may make some unexpected formatting of normal text.

**Comment by ara4n** [comment]
matrix-console has markdown, iirc - the command is /markdown. console is completely obsolete though - please use vector.im as an uptodate web client!

**Comment by duckbrain** [comment]
Thanks, I am having trouble with the vector.im interface because I'm trying to run it on an ARM CPU, but this resolves the issue. Closed.

**Comment by ara4n** [comment]
The main reason that the old matrix-angular-sdk is deprecated by matrix-react-sdk (on which Vector is built) is terrible performance problems with Angular, which would have necessitated a rewrite to fix. So we rewrote in React instead which has served us infinitely better.

There is nothing in Vector which should specifically pose problems on ARM - what are you seeing? Come complain in #vector:matrix.org :)

M
