### ISSUE TITLE
Install instructions point to 404 for postgresql

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#10330]
https://matrix-org.github.io/synapse/develop/setup/installation.html#using-postgresql links to https://matrix-org.github.io/synapse/develop/setup/docs/postgres.html which doesn't go anywhere.

**Comment by dklimpel** [comment]
This issue is solved.

**Comment by richvdh** [comment]
well it will be as soon as we merge release-v1.38 to develop. Thanks @dklimpel !
