### ISSUE TITLE
make_room_admin fails for users that have left a private room

### ISSUE THREAD

**Issue by tomushkin** [matrix-org/synapse#10338]
### Description

Calling  /_synapse/admin/v1/rooms/$room_id/make_room_admin on a private room would invite the user to the room if not already in it. If the user leaves the room, calling make_room_admin a second time fails with:

```
{"errcode":"M_FORBIDDEN","error":"$user not in room $room_id"}
```

### Steps to reproduce

- Call make_room_admin on a private room
- Join the room with the server admin user
- Leave the room
- Call make_room_admin again to get M_FORBIDDEN

The server admin user should be invited to the room again.

### Version information

- **Version**: 1.36.0

- **Install method**: https://packages.matrix.org/debian

- **Platform**: x86_64 / Ubuntu 20.04.1 LTS

**Comment by anoadragon453** [comment]
Upon testing, it seems that the code that determines which local user to send the updated power levels event through naively only checks for users in the existing power levels event. It does not take into account users who are not in that event, nor the fact that the users in that event may not even be joined to the room.

https://github.com/matrix-org/synapse/blob/9e4610cc272fc8e5db39608de83ce48360889e42/synapse/rest/admin/rooms.py#L489-L511

Thus the code is likely attempting to send the updated power levels through the user who was admin'd the first time around - but they're not in the room, hence the error.

It should be updated to filter out users who aren't actually joined to the room.
