### ISSUE TITLE
delete database entries with lost foreign entries

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#1035]
we deleted room history with

    delete from events where room_id='$ROOM' and origin_server_ts < ((strftime('%s', 'now')-560400) *1000 ) and type='m.room.message' order by origin_server_ts

now  lot of entries in the database table `state_groups_state` that refer to an event that was deleted earlyer are lost

These are the tables that should have been pruned:

        #     +
        #     event_backward_extremities
        #     event_content_hashes
        #     event_destinations
        #     event_edge_hashes
        #     event_edges
        #     event_forward_extremities
        #     event_json
        #     event_push_actions
        #     event_reference_hashes
        #     event_search
        #     event_signatures
        #     event_to_state_groups
        #     events
        #     rejections
        #     room_depth
        #     state_groups
        #     state_groups_state

But we did only delete `events`. How do I delete all redundant entries now? (In my case there are still over 200.000 entries in state_groups_state for that room)

**Comment by erikjohnston** [comment]
In general I'd not recommend manually editing the database. However, I think the following should do what you want:

The query in synapse that actually deletes entries from `state_groups_state` is:

```python
        # Get all state groups that are only referenced by events that are
        # to be deleted.
        txn.execute(
            "SELECT state_group FROM event_to_state_groups"
            " INNER JOIN events USING (event_id)"
            " WHERE state_group IN ("
            "   SELECT DISTINCT state_group FROM events"
            "   INNER JOIN event_to_state_groups USING (event_id)"
            "   WHERE room_id = ? AND topological_ordering < ?"
            " )"
            " GROUP BY state_group HAVING MAX(topological_ordering) < ?",
            (room_id, topological_ordering, topological_ordering)
        )
```

https://github.com/matrix-org/synapse/blob/master/synapse/storage/events.py#L1579-L1591

But since you've deleted all the event_ids, I think something like the following get all the state_groups for events that have been deleted:

```sql
SELECT DISTINCT state_group FROM event_to_state_groups WHERE event_id NOT IN (SELECT event_id FROM events);
```

**Comment by erikjohnston** [comment]
(You should also be able to delete the contents of other tables by delete everything with an event_id not in the events table)

However, these queries are likely to be *very* slow.
