### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by heroku-miraheze** [matrix-org/synapse#10364]
### Description

I cannot find more rooms, i cannot send messages, i cannot login, and i can't do anything. Gives an 500 Internal Server Error. I will give you an capture.
![Captura](https://user-images.githubusercontent.com/61781343/125155757-43794e00-e162-11eb-9599-ee6631f64f6c.PNG)

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
Open Element.io, and gives an 500 Internal Server Error.
### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by unbeatable-101** [comment]
I have the same problem

**Comment by heroku-miraheze** [comment]
@unbeatable-101 OK, and i have the same problem here.

**Comment by unbeatable-101** [comment]
https://status.matrix.org/

> An issue is impacting the matrix.org database. Our engineers are investigating and fixing

**Comment by ShadowJonathan** [comment]
https://twitter.com/matrixdotorg/status/1413779165661351936
