### ISSUE TITLE
element is not working with Tor socks proxy using cloudflare

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/synapse#10363]
Hey is there's a fix for this issue element is not working on Tor socks proxy and i use cloudflare on my private server i noticed matrix.org is using cloudflare as well and tor socks proxy work very well on matrix.org so maybe there's a config missing in cloudflare to activate

**Comment by dklimpel** [comment]
Have look in #7088 and #5152

**Comment by anoadragon453** [comment]
@githuberyt I'm not sure whether you're trying to use Tor between Element (the client) and Synapse (the server, through Cloudflare) or Tor between homeservers (federation) instead.

If you mean between the client and server, then I'm afraid this is not the right forum for debugging Cloudflare + Tor issues.

If you mean between homeservers then as @dklimpel says we do have some other issues already which are exploring this concept.

**Comment by clokep** [comment]
> If you mean between homeservers then as @dklimpel says we do have some other issues already which are exploring this concept.

#7088 and #5152, I think.

**Comment by richvdh** [comment]
Yup I'm going to resolve this in favour of those other issues.
