### ISSUE TITLE
SMTP retries are instantaneous and count backwards

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#10378]
```
eledev-synapse_1  | 2021-07-13 01:12:03,141 - twisted - 258 - INFO - sentinel - SMTP Client retrying server. Retry: 4
eledev-synapse_1  | 2021-07-13 01:12:03,142 - twisted - 258 - INFO - sentinel - SMTP Client retrying server. Retry: 3
eledev-synapse_1  | 2021-07-13 01:12:03,143 - twisted - 258 - INFO - sentinel - SMTP Client retrying server. Retry: 2
eledev-synapse_1  | 2021-07-13 01:12:03,144 - twisted - 258 - INFO - sentinel - SMTP Client retrying server. Retry: 1
```

The SMTP server in this setup was emitting Connection Refused back at Synapse. The `Retry` is backwards, and there's only a single millisecond between attempts.

**Comment by richvdh** [comment]
This functionality is in Twisted, so we'd have to fix it there.

**Comment by turt2live** [comment]
the retry count being backwards is probably not super important, but is the delay configurable?

**Comment by richvdh** [comment]
not as far as I know, no.

**Comment by turt2live** [comment]
alright, closing as not actionable.

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/8145
