### ISSUE TITLE
Upload file not working through Windows proxy

### ISSUE THREAD

**Issue by alldayidream** [matrix-org/synapse#10373]
### Description

Unable to send larger files when connecting through the system proxy in Windows. 

When using Element on Windows, and connecting through the system proxy, the status bar for uploading a file does not work, and the file fails to send.

If connecting without a proxy the progress bar works, and the file sends.

### Steps to reproduce

- Element on Windows
- Connect to a homeserver using the system proxy
- In a room upload a file less than the max file size

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver: Yes

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.37.1

- **Install method**:  apt install matrix-synapse-py3
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 20.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by anoadragon453** [comment]
@alldayidream It would be useful to provide debug logs from your Element client so we can see what's going wrong in the background. You can do so by going to Settings -> Help & About -> Send Debug Logs. Mention this GitHub issue and provide a short description.

At the moment I can't say whether this is an Element, Synapse or a Windows issue.

**Comment by richvdh** [comment]
closing this due to lack of info.
