### ISSUE TITLE
test with twisted 21.7.0rc2

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#10372]
Twisted have a new RC out: https://pypi.org/project/Twisted/21.7.0rc1/. Final release is proposed for 2021/07/17. We should check that everything still works before the release happens.

**Comment by richvdh** [comment]
I put up a quick PR to test the CI at #10402, but it's failing lint currently.

**Comment by richvdh** [comment]
this is currently blocked pending another RC from the twisted folks.

**Comment by richvdh** [comment]
twisted 21.7.0rc2 is out now.

**Comment by erikjohnston** [comment]
Twisted 21.7.0rc3 has been deployed to matrix.org's Synapse
