### ISSUE TITLE
SSO with SourceHut

### ISSUE THREAD

**Issue by toastal** [matrix-org/synapse#10371]
**Description:**

SourceHut supports OAuth2.0

Auth docs: https://man.sr.ht/graphql.md#authentication-strategies
Managing person auth token stuff: https://meta.sr.ht/oauth2

**Comment by ShadowJonathan** [comment]
Could you elaborate a bit more? What's this issue supposed to signal? Would you want to have sourcehut SSO support built into synapse? What does the/a regular oauth2 authenticator that wouldn't work with sourcehut?

**Comment by anoadragon453** [comment]
https://man.sr.ht/graphql.md#authentication-strategies details how to authenticate each request to the server once you've authenticated via OAuth2. The relevant documentation for authenticating with SourceHut against Synapse is at https://man.sr.ht/meta.sr.ht/oauth.md.

In theory it *should* work with our OpenID Connect module, which [supports OAuth2.0 identity providers](https://github.com/matrix-org/synapse/blob/master/docs/openid.md). Note that https://man.sr.ht/meta.sr.ht/oauth.md#authorization-endpoint has some information which may require specific tweaks in the OIDC config on the Synapse side.

If you manage to make it work, we'd really appreciate an example configuration layout to add to that document!

**Comment by richvdh** [comment]
I'm going to close this, pending clearer information about the issue.

**Comment by ptman** [comment]
@ddevault I'm not sure what your policy is on github interactions, so sorry if this notify is unwelcome.

What's your view on this, should it just work or is there something that may pose a problem?

**Comment by ddevault** [comment]
We have (or should have) an RFC-compliant OAuth 2.0 implementation now, so I imagine it would just werk. If it does not, bug reports and/or patches welcome.

**Comment by anoadragon453** [comment]
To me, the path forward here is for someone to try this setup in practice, get it working (or find that it doesn't work) and return with documentation (or bug reports) in tow.
