### ISSUE TITLE
Move `update_client_ips` to the background worker

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#10425]
https://github.com/matrix-org/synapse/blob/c0df6bae066fe818bb80d41af65503be7a07275d/synapse/storage/databases/main/client_ips.py#L474-L486

I have a feeling that we wanted to keep this on the main process as it needs to only be run by one, single process. However, this is no longer a concern now that we can dedicate all background work to a single worker through the `run_background_tasks_on: <worker_name>` config option.

This operation has been reported as potentially CPU intensive on some deployments, so moving it off the main process would be a win.

(Also random thought: can this be converted to something that operates entirely in the database (postgres)?)

**Comment by anoadragon453** [comment]
I think all that needs to happen is wrapping the `looping_call` in a conditional for `run_background_tasks_on`:

https://github.com/matrix-org/synapse/blob/c0df6bae066fe818bb80d41af65503be7a07275d/synapse/storage/databases/main/client_ips.py#L435-L452

So something like:

```python
        if hs.config.run_background_tasks:
            self._client_ip_looper = self._clock.looping_call(
                self._update_client_ips_batch, 5 * 1000
            )
```

**Comment by clokep** [comment]
It doesn't look like #8500 has any info on why this wasn't done.

I believe it was because `insert_client_ip` is what caches the IP batch info (by writing to `_batch_row_update`). This gets called by the master process, so it isn't as simple as just saying "run this other code on the background worker" since...that worker will have the in-memory cache updated.

You might be able to send those over replication, but that would be more invasive.

**Comment by anoadragon453** [comment]
@clokep does that imply that IP addresses are only noted in the database for the main process, not any workers?

**Comment by clokep** [comment]
> @clokep does that imply that IP addresses are only noted in the database for the main process, not any workers?

I *think* so but it has been a while since I looked at this. 😄

**Comment by anoadragon453** [comment]
In addition, there's a simple optimisation we could make to the function to likely make it a bit lighter on the database.

Currently we iterate over the list of all IP entries and make one or (more often) 2 separate queries against the database server. This results in both a high amount of DB and CPU usage.

https://github.com/matrix-org/synapse/blob/c0df6bae066fe818bb80d41af65503be7a07275d/synapse/storage/databases/main/client_ips.py#L494-L524

One simple solution we could do is to simply execute a single batch query against the server containing all modifications. We could:

* transform the numerous calls of `simple_upsert_txn` to a single `simple_upsert_many_txn`, which utilises [`txn.execute_batch`](https://www.psycopg.org/docs/extras.html#psycopg2.extras.execute_batch).
* `simple_update_txn` does not (yet) have a `_many` derivative. I'm not sure whether we'd want to create that for this purpose.
