### ISSUE TITLE
Pinning messages

### ISSUE THREAD

**Issue by avdb13** [matrix-org/synapse#10422]
Hi, can you guys please add the ability to pin messages in rooms? I have an organization and it's really frustrating to have to send everyone important messages personally. If you want an example of what I want take a look at Discord. Thanks in regard.

**Comment by ShadowJonathan** [comment]
Message pinning already exists, only its a feature which isn't promoted widely on element, as its design needs some catching up.

That said, this issue isn't a synapse one, I recommend closing this and re-opening it on https://github.com/vector-im/element-web

**Comment by anoadragon453** [comment]
Hi @avdb13. Message pinning is in [the Matrix spec](https://spec.matrix.org/unstable/client-server-api/#mroompinned_events) already and is up to clients to implement.

Note that Element Web already has message pinning functionality, but it is currently hidden behind a Labs flag while some of the remaining kinks are being ironed out.

Please follow https://github.com/vector-im/element-web/issues/6606 as the tracking issue. Closing here as there's nothing for Synapse to do.
