### ISSUE TITLE
An admin API to mass-redact events would be useful

### ISSUE THREAD

**Issue by Yoric** [matrix-org/synapse#10466]
It's easy to write code to redact events from a room. However, when someone decides to leave massive amounts of garbage in a room, that can take a loooong time and be throttled by the server.

In this context, it would be useful to have an admin API that could:
1. receive a (possibly very long) list of events to redact;
2. attempt to redact them all;
3. return a list of of events that could not be redacted, if any.

**Comment by erikjohnston** [comment]
I think this is basically https://github.com/matrix-org/synapse/issues/9809
