### ISSUE TITLE
synapse_http_request_apdex sometimes dips but does not recover despite the host looking healthy

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#10467]
We've seen it happen a few times in EMS where a host will perform badly, bringing down the `synapse_http_request_apdex`, but when the host recovers the apdex does not until the host is restarted.

![image](https://user-images.githubusercontent.com/2072976/126779593-b6d60454-564f-4cf5-9922-57e66ab8ab57.png)

Above is a screenshot of two hosts, one being vector.modular.im and the other being openastronomy.modular.im. This is a graph of `synapse_http_request_apdex:6h`. A bridge is restarted around the time that the bad host starts to dip, which presumably drives down the metric. Over time however the host recovers, and currently the host is using virtually no resources but the metric has not improved.

**Comment by erikjohnston** [comment]
`synapse_http_request_apdex` is not a Synapse thing but a rule in EMS prometheus based on some other metrics (presumably response time). Can you post what the rule is and what the associated response time graphs look like?

**Comment by Half-Shot** [comment]
The rule ends up being:
```
      (
        sum(
          rate(
            synapse_http_server_response_time_seconds_bucket{
              code!~"5..|429",
              le="1.0",
              servlet=~"RoomSendEventRestServlet"
            }[6h]
          )
        ) by (servlet) / 2
        +
        sum(
          rate(
            synapse_http_server_response_time_seconds_bucket{
              code!~"5..|429",
              le="0.25",
              servlet=~"RoomSendEventRestServlet"
            }[6h]
          )
        ) by (servlet) / 2
      ) /
      sum(
        rate(
          synapse_http_server_response_time_seconds_count{
              code!~"429",
              servlet=~"RoomSendEventRestServlet"
          }[6h]
        )
      ) by (servlet)
```

However, looking at the graph for this, I can't see it dipping below 0.8 so I don't know why the alerting fired.

**Comment by Half-Shot** [comment]
I don't think we have enough data to evaluate why it was so low for so long, but I am more sure that this might be an issue with our alerting rules rather than Synapse.
