### ISSUE TITLE
Can not call on with mobile network

### ISSUE THREAD

**Issue by kam2yar** [matrix-org/synapse#10503]
Hi

I installed synapse with docker today, and I have a problem with calling (video, voice)
when I'm using the wifi network. call works fine, but when I'm using my mobile network for call it stays of calling... status and nothing appears.

would you please assist me how I can fix that?
matrix.mamnon.ir

thank you

**Comment by kam2yar** [comment]
i get this on my console
AudioFeed.tsx:67 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22

maybe its about device names, I don't know

**Comment by babolivier** [comment]
Hi, apart from the basic signaling (i.e. relaying call invites and terminations) calls in Matrix happen entirely client-side. So I'd suggest opening an issue on the repo for the client you're having issues with.
