### ISSUE TITLE
Remove message "just for me"

### ISSUE THREAD

**Issue by Wallby** [matrix-org/synapse#10506]
**Description:**

Not sure if this already has been requested (searching for "remove message" did not spot it). I would like to be able to remove a message "just for me" (i.e. similar to how this can also be done in facebook messenger).

**Comment by Wallby** [comment]
On close inspection, perhaps [matrix-doc](https://github.com/matrix-org/matrix-doc) would have been a better place for this request..?

**Comment by ShadowJonathan** [comment]
Yes, because this is essentially a spec change, then matrix-doc is the place to be.

**Comment by Wallby** [comment]
Opened an issue over at matrix-doc.. https://github.com/matrix-org/matrix-doc/issues/3301

This issue can essentially be deleted.
