### ISSUE TITLE
Sync failing with 404 M_NOT_FOUND when the user is invited to a room with an unknown version

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#10525]
### Description

As per the title; tried logging into my matrix.org test account and /sync responded with a 404 over and over again

![image](https://user-images.githubusercontent.com/2403652/128176765-d6cc5d65-8e07-40c5-bea8-ae011b0f5fef.png)

### Version information

- **Homeserver**: matrix.org

I believe the account was `@webdevguru_test17:matrix.org` in case that helps with log spelunking

It might be because the user was in an msc3083 unstable room the server dropped support for. 🔥

**Comment by babolivier** [comment]
So what's happening here is:

* the sync handler loads the list of room memberships for this user
* it sees that the user is invited to the room
* it tries to get the invite event for this room using `get_events`, which eventually calls `_get_events_from_db`
* `_get_events_from_db` retrieves the event and checks the room version against known ones
* the room version isn't known so it ignores it
* `_get_events_from_db` returns no event, so `get_events` raises a 404 error

The check on the room version is here: https://github.com/matrix-org/synapse/blob/bdfde6dca11a9468372b3c9b327ad3327cbdbe4a/synapse/storage/databases/main/events_worker.py#L781-L801

**Comment by callahad** [comment]
Bumping to S-Critical as I'm assuming it blocks development work for @t3chguy (please let us know if it doesn't).

Bricking unstable rooms is one thing, but bricking accounts that have interacted with unstable rooms is quite another, and something I'm keen to see resolved prior to 1.40 going out.

**Comment by t3chguy** [comment]
It isn't blocking my development work, it is one of my ~30 test accounts, just happens to be the one my FF instance defaulted to and confused me why sync was returning 404.

Though if someone created such an unstable room (which Element Android release edition allowed you to do via UI) on their primary account then it'd be S-Critical for them

**Comment by clokep** [comment]
Just to define the impact I believe this will only cause an issue if you have an outstanding invite to an unknown room version, not users who have joined an unknown room version (see #7083).

Just to ensure we're all discussing the same thing:
* "unstable" is a room version that Synapse knows about but is not stable, according to the spec.
* "unknown" or "unsupported" is a room version which Synapse does not know about (and does not know how to interact with).
* "experimental" is generally a synonym for "unstable" but if the spec ever made a stable room version unstable than they would differ ("experimental" would then mean unspecced, e.g. from an MSC or something).
