### ISSUE TITLE
Missing check in user creation task

### ISSUE THREAD

**Issue by TheWayOfTheWarrior** [matrix-org/synapse#10526]
### Description

Server don't check if the user with given username already exist.

### Steps to reproduce

1. Create user with username "abcdef" with displayName "123"
2. User was created.
3. Create user with username "abcdef" with displayName "Hello"
4. There will be only user abcdef with displayName "Hello"

![step1](https://user-images.githubusercontent.com/87245511/128177141-7ada7964-0c7e-4b98-9605-55102319fbeb.png)
![step2](https://user-images.githubusercontent.com/87245511/128177144-cae86a18-1742-4ea1-8c1f-e3dd48209870.png)
![step3](https://user-images.githubusercontent.com/87245511/128177154-34dd056f-028d-4a46-8a8a-35c1cde6c017.png)
![step4](https://user-images.githubusercontent.com/87245511/128177161-9dc7a5af-f581-4ac2-adb1-086d8d1d2ddd.png)

### Version information

Synapse-Admin (0.8.1-8-g5262518)

**Comment by TheWayOfTheWarrior** [comment]
Moved here: https://github.com/Awesome-Technologies/synapse-admin/issues/176

**Comment by dklimpel** [comment]
Related to: #8165

**Comment by TheWayOfTheWarrior** [comment]
@dklimpel Thanks, man!
