### ISSUE TITLE
Redacting MSC2716 related events

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#10521]
What should happen when you redact MSC2716 related events? @erikjohnston does this look sane?

 - "insertion" event
    - Undo the steps we take in [`_handle_insertion_event`](https://github.com/matrix-org/synapse/blob/72935b7c5053af122c8cb5767a3e85a3a0f3a20c/synapse/storage/databases/main/events.py#L1760-L1809)
    - Remove from the `insertion_events` table
    - Remove all of the `insertion_event_edges`
 - "chunk" event
    - Undo the steps we take in [`_handle_chunk_event`](https://github.com/matrix-org/synapse/blob/72935b7c5053af122c8cb5767a3e85a3a0f3a20c/synapse/storage/databases/main/events.py#L1811-L1846)
    - Remove from `chunk_events`
 - "marker" event
    - not merged yet, see https://github.com/matrix-org/synapse/pull/10498
    - Undo the steps we take in `_handle_marker_event`
    - We backfill the insertion event in `_handle_marker_event` but I don't think we need to undo that. If they want to redact the insertion event, they can do that separately. We can just redact the "marker" event as normal with no special logic.

---
  
A more general question but what happens when you redact a redaction? Does it cancel the event being redacted?

**Comment by erikjohnston** [comment]
I think we should probably add those fields to be included in the redacted event, so that the structure of the imported history isn't lost. The idea of redaction is that you can use it to strip out fields from events without affecting anything at the protocol level.

> A more general question but what happens when you redact a redaction? Does it cancel the event being redacted?

I don't think anything happens, as it won't strip out the `redacts` field

**Comment by MadLittleMods** [comment]
> The idea of redaction is that you can use it to strip out fields from events without affecting anything at the protocol level.

Interesting. Didn't realize that was the goal of redacting 👨‍🌾 

Created https://github.com/matrix-org/synapse/pull/10538 to maintain the structural fields around 👍
