### ISSUE TITLE
Remove `trust_identity_server_for_password_resets`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#10545]
The [`trust_identity_server_for_password_resets`](https://github.com/matrix-org/synapse/blob/v1.3.0/docs/sample_config.yaml#L1158-L1169) setting was deprecated in [Synapse 1.4.0](https://github.com/matrix-org/synapse/blob/develop/docs/upgrade.md#upgrading-to-v140), nearly two years ago. We should remove the legacy code which supports that option.

**Comment by richvdh** [comment]
recommend refusing to start if this is set, rather than silently changing behaviour for existing deploys.

**Comment by H-Shay** [comment]
I have a PR up for this but I can leave it in draft until this gets clarified.

**Comment by richvdh** [comment]
I think we should go ahead with this on synapse mainline anyway. DINUM are still on a fork, so if this is a real problem for them we can patch out the change there.

**Comment by babolivier** [comment]
> DINUM are still on a fork, so if this is a real problem for them we can patch out the change there.

I disagree. We're currently trying very hard to bring DINUM's fork closer to Synapse, or at least to stop it from diverging too much, and creating a new point of divergence would be counter-productive. If we remove it from mainline, I'd rather we make sure it's not going to bite them next time they update.

**Comment by babolivier** [comment]
@giomfo and I had a look at Synapse's config for DINUM and it looks like it's be all good to get rid of `trust_identity_server_for_password_resets` :+1:
