### ISSUE TITLE
unable to decrypt - misleading information and process

### ISSUE THREAD

**Issue by damnms** [matrix-org/synapse#10544]
**Description:**

I had some trouble because my server updates automatically. since version .29 synapse introduced a new configuration requirement on apache2 (x-forward-proto) which lead to some errors which i was not aware of.
when in this moment one tried to contact another person on my server (e.g. from @matrix.org to @mysmallhomeserver.com) the key exchange seemed to fail. thats not a big deal because i noticed that error in the logs and followed the migration guide (adding that x proto forward header).
but it was impossible since then to communicate with the person. he was able to read my messages and he has seen that i have seen his messages, but i was unable to read them. 
i had to manually verify him with the emojis - after that it worked. i guess that "broken" key (or no key at all) has been exchanged and was not updated automatically.
i am a technical person and was able to fix that but i guess most people have no idea what to do in that case.

would it be possible to somehow popup a messagebox "the key does not match or is not existent, would you like to verify the other person manually?" and when pressed "yes", popup the emojis for manual verification.

if i should create this in the client instead of synapse, please let me know.

**Comment by babolivier** [comment]
It doesn't sound like there's any way for us to investigate why the key exchange failed, so I don't think there's anything we can do here.

Your question applies to clients, not servers, so yes, create an issue on the repo of the client you're using please.

**Comment by richvdh** [comment]
I would be very surprised if the failures were in any way related to the `x-forwarded-proto` header.

**Comment by damnms** [comment]
> I would be very surprised if the failures were in any way related to the `x-forwarded-proto` header.

i am not sure about that. but that was the first error i got and then i had this wierd behaviour which i never had before. so thought maybe there is a correlation.
