### ISSUE TITLE
Notification settings for spaces

### ISSUE THREAD

**Issue by dakontiva** [matrix-org/synapse#10555]
**Description:**

It would be great if spaces also have notification settings like rooms. After joining a few spaces I was getting constant notifications from various rooms in each space. Currently I had to manually change each rooms notification settings. I think it would be much more convenient if notification settings can be set for whole space. And all subspaces and rooms within that space with default notifications would inherit the notification setting of the the space.

**Comment by babolivier** [comment]
Hey, thanks for opening this. This sounds to me like a Matrix spec issue (since Synapse is only implementing the Matrix spec), so I'd suggest opening a new one on https://github.com/matrix-org/matrix-doc.
