### ISSUE TITLE
update docs/postgres with how to upgrade database

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/synapse#10582]
getting this error, with using new docker image. There should be a cli tool to verify/upgrade the database.

```
    SELECT setval('presence_stream_sequence', (
        SELECT GREATEST(MAX(stream_id), 0) FROM presence_stream
    ));

See docs/postgres.md for more information.
```

https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md

**Comment by richvdh** [comment]
> getting this error

which error?

**Comment by richvdh** [comment]
> There should be a cli tool to verify/upgrade the database.

see #10793.

I'm going to close this, pending clearer information about what the problem is. We can reopen it if you can share the actual error you're seeing.
