### ISSUE TITLE
Add stable support for fallback keys

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#10617]
https://github.com/matrix-org/matrix-doc/pull/2732 has passed FCP and is eligible for stable implementation: this would be a good thing.

**Comment by anoadragon453** [comment]
We should ensure clients are prepared for a switch to the stable API before releasing this.

**Comment by turt2live** [comment]
It should be possible to add it rather than switch for maximum compatibility?

**Comment by anoadragon453** [comment]
Ah yes, that's a good point. We certainly can do.

**Comment by clokep** [comment]
@uhoreg was this fixed by #11541?

**Comment by uhoreg** [comment]
Yes, I believe so.

**Comment by clokep** [comment]
Thanks! I'm going to close this then, unless we need to keep it open to remove any backwards compatibility paths?
