### ISSUE TITLE
Support AS timestamp massaging for state events

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#10634]
[MSC3316](https://github.com/matrix-org/matrix-doc/pull/3316) recommends that `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}` should support a `ts` key for appservices to override the `origin_server_ts` value of an event. This is already supported in Synapse for normal events, as the feature has been in Synapse for a long time (albeit [excluded from the spec](https://matrix.org/docs/spec/application_service/r0.1.2#timestamp-massaging); MSC3316 aims to revive it).

**Comment by lukasdenk** [comment]
@Half-Shot: Does it make sense to include a `ts` key even though [MSC3316](https://github.com/matrix-org/matrix-doc/pull/3316) is not merged yet?

**Comment by Half-Shot** [comment]
Well...it's a weird one. Synapse *already* supports MSC3316 for the `ts` parameter by virtue of the parameter being undocumented for ages. I don't think it's necessarily a bad thing to:

- Treat the existing implementation in Synapse as an unstable feature for MSC3316
- Extend the existing implementation to support state events.

It's perfectly normal to implement unmerged specs, in order to have a proven implementation.

**Comment by lukasdenk** [comment]
Ok, I'll work on it

**Comment by lukasdenk** [comment]
@Half-Shot Ok, I think I found it.

**Comment by anoadragon453** [comment]
I would hope that we wouldn't introduce more stable identifiers for unmerged MSCs where we can if possible. The existing `ts` parameter falls into the category of changes made before we started the concept of unstable prefixes.

I think the lack of an unstable prefix [mentioned in an MSC](https://github.com/matrix-org/matrix-doc/pull/3316/files#diff-932cb38a5794ca30cc777a477aa94a175824cb96833229d1a578d86844c5bd24R49) assumes that Synapse supports `ts` across all relevant endpoints - when it reality that's not the case.

I would prefer if we came up with an unstable prefix, added support for it to `PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}` and then only allow the unstable prefix for `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}` until [MSC3316](https://github.com/matrix-org/matrix-doc/pull/3316) is merged.

**Comment by Half-Shot** [comment]
I think that's quite reasonable. I would probably prefer it if we kept `ts` for the endpoint that already works, to avoid a breaking change (even though it's technically not supported -- a lot of things now use it).

**Comment by anoadragon453** [comment]
Since it was implemented before unstable prefixes, it makes sense to keep it around.

**Comment by lukasdenk** [comment]
@anoadragon453 So does this mean that PR #11866 will only be merged after [MSC3316](https://github.com/matrix-org/matrix-doc/pull/3316) is merged?

**Comment by anoadragon453** [comment]
@lukasdenk no, the MSC will need an implementation anyhow, which #11866 could serve as. #11866 is just blocked on [MSC3316](https://github.com/matrix-org/matrix-doc/pull/3316) gaining an unstable prefix.

But you can probably just use `org.matrix.msc3316.ts` as a placeholder for now and we'll switch it out for whatever the MSC eventually chooses.

**Comment by lukasdenk** [comment]
@anoadragon453 In what context should the `org.matrix.msc3316.ts` placeholder be used?

**Comment by anoadragon453** [comment]
Hi @lukasdenk. Please see an explanation of unstable prefixes here: https://spec.matrix.org/unstable/proposals/#early-release-of-an-mscidea

You'll want to use it in any user-facing query parameters. In this case specifically, you'll want to add `org.matrix.msc3316.ts` as a supported parameter to both `PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}` and `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}`. In the case of `PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}`, both `org.matrix.msc3316.ts` and `ts` would be accepted.
