### ISSUE TITLE
Servername not used in Senderadress in Emailservice

### ISSUE THREAD

**Issue by KlausHans** [matrix-org/synapse#10670]
Hello, 
i've got the problem, that i cant use the email service of synapse.
The log gives the following error:
`<<< 504 5.5.2 <Users@server>: Sender address rejected: need fully-qualified address`
"server" is the name of my server and should be instead "domain.tld" als configured in /etc/matrix-synapse/conf.d/server_name.yaml or /etc/matrix-synapse/homeserver.yaml ("server_name").

I think this is a bug. Or is it?

I've already purged the package and dropped the postgres database. It did not help.

I am using the prebuild package https://matrix-org.github.io/synapse/latest/setup/installation.html#matrixorg-packages
Ubuntu 20.04

Thanks

**Comment by dklimpel** [comment]
You have to set your sender here:
https://github.com/matrix-org/synapse/blob/947dbbdfd1e0029da66f956d277b7c089928e1e7/docs/sample_config.yaml#L2120

 The documentation: https://matrix-org.github.io/synapse/latest/setup/installation.html#email

**Comment by KlausHans** [comment]
Thank you. 
I actually know this part of the documentation. I did not know that <noreply@example.com> is taken for the sender. I just tried it and it works. The documentation is not very clear, i thought notif_from is some sort of greeting in the mail. Its a little bit magic for me, that the <noreply@example.com> part is taken from here.

**Comment by KlausHans** [comment]
Half off-topic: i now have the problem, that the registration confirmation link in the mail is not matrix.domain.tld but only domain.tld which leads to a 404 error of course. If i change the domain of the mail sender to noreply@matrix.example.com it does not change anything.
I have delegation and the reverseproxy properly set up. 
Unfortunately i can't find anything on the internet to this problem. Can you push me once again in the right direction, please, @dklimpel?

**Comment by dklimpel** [comment]
I guess the setting which you are looking for is:
https://github.com/matrix-org/synapse/blob/947dbbdfd1e0029da66f956d277b7c089928e1e7/docs/sample_config.yaml#L87-L94
https://github.com/matrix-org/synapse/blob/947dbbdfd1e0029da66f956d277b7c089928e1e7/docs/sample_config.yaml#L2137-L2143

**Comment by KlausHans** [comment]
Indeed. Thank you very much!
