### ISSUE TITLE
Federation server signature verification failed

### ISSUE THREAD

**Issue by pavlukivan** [matrix-org/synapse#10678]
### Description

I set up my second homeserver, however when trying to invite users from other homeservers, server signature verification fails with a message similar to `M_UNAUTHORIZED: Invalid signature for server matrix.org with key ed25519:a_RXGa: Unable to verify signature for matrix.org: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt`. I couldn't figure out a way to make it work, I even tried recreating the signing key and pruning the server database. Everything works if I make it silently ignore verification errors. Everything works on my first homeserver as well, which uses the same nginx and postgres config. The major difference is new server is using arm and the old one is using x86.

### Steps to reproduce

- create a homeserver
- ???
- profit

### Version information

- **Version**: 1.40.0

- **Install method**: pip

- **Platform**: linux, arm64, oracle linux 8 on oracle cloud with latest updates

**Comment by clokep** [comment]
Could you include the version of Python you're using and do a `pip freeze` and include that output too?

Does it seem like all signatures are failing?

**Comment by richvdh** [comment]
could you give more context as to where you are seeing this error? In a client (if so, share a screenshot)? In a log file (if so, share the exact log lines)?

**Comment by pavlukivan** [comment]
both client and the log file, it fails at https://github.com/matrix-org/synapse/blob/bf72d10dbf506f5ea486d67094b6003947d38fb7/synapse/crypto/keyring.py#L308

**Comment by richvdh** [comment]
please paste the line from the log file.

**Comment by pavlukivan** [comment]
I don't have the logs for connecting to matrix.org anymore, but here's a log from a connection to matrix.pavluk.org https://pastebin.com/0xGw5YvK

**Comment by richvdh** [comment]
@pavlukivan normal reason for that is a misconfiguration in the reverse proxy; see https://github.com/matrix-org/synapse/blob/develop/README.rst#people-can-t-accept-room-invitations-from-me

**Comment by pavlukivan** [comment]
I copied the config from a server when it works, I also used the nginx config from that exact page (with modifications, it simply didn't parse the `~* ^(\/_matrix|\/_synapse\/client)` part)

**Comment by richvdh** [comment]
"misconfiguration" means "modifying the request URI - for example adding `/`s or decoding `%xx` escapes.

If you share your configuration we might be able to help you better.

**Comment by pavlukivan** [comment]
First I tried the sample nginx configuration, nginx couldn't load it so I replaced `~* ^(\/_matrix|\/_synapse\/client)` with `/`. It still didn't work, so I switched to my configuration that works on another server:
```nginx
server {
    listen 80;
    listen [::]:80;
    server_name hostname;
    return 301 https://$host$request_uri;
}

server {
    client_max_body_size 1G;
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 8448 ssl http2 default_server;
    listen [::]:8448 ssl http2 default_server;
    server_name hostname;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/hostname/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/hostname/privkey.pem; # managed by Certbot

    location / {
        proxy_pass         http://127.0.0.1:8008/;

        proxy_set_header   Host             $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header   X-Forwarded-Proto         http;
    }
}
```
and it still didn't work

**Comment by richvdh** [comment]
the problem is the trailing `/ ` on proxy_pass. As https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md#nginx says: "NOTE: Do not add a path after the port in `proxy_pass`, otherwise nginx will canonicalise/normalise the URI."

**Comment by pavlukivan** [comment]
thanks!

**Comment by richvdh** [comment]
@pavlukivan if you have any suggestions for updates to the documentation to stop people making this error, we'd be interested. We've tried to spell it out as clearly as we can, so it's frustrating that it is still biting people.

**Comment by pavlukivan** [comment]
I think it's on me here for not reading closely enough... but maybe adding an explanation comment after the `proxy_pass http://localhost:8008;` would've prevented this
