### ISSUE TITLE
Inviting in a room is possible despite the lack of authorization 

### ISSUE THREAD

**Issue by Florian-Sabonchi** [matrix-org/synapse#10685]
Currently it is possible to invite users to a room with the standard role, but this is only possible in the web version and not in the Android app or the desktop version. This is also possible if the role does not have the authorization for it.

**Comment by MarcelCoding** [comment]
![image](https://user-images.githubusercontent.com/34819524/131264990-d315db57-2271-41bc-996f-2850004513e3.png)
At the time of the invitation, the user was not banned.

I'm no a moderator (pic 3) and can invite users.

**Comment by erikjohnston** [comment]
Sorry for dropping this on the floor a bit. I think this is a UI issue element web (I haven't checked other clients), if the `invite` power level isn't specified in the power levels event it should default to `0`, but element web seems to show it as `Moderator`. The potential confusion here is that the "default" power level event for *newly* created public sets the invite level to `50` (i.e. Moderator).

Reported against web at https://github.com/vector-im/element-web/issues/19187 and https://github.com/vector-im/element-android/issues/4089 on android

**Comment by reivilibre** [comment]
> But we could proceed with the action. Doesn't this mean that there is missing some kind of authentication?

My understanding is that your screenshot (where it shows you need 'Moderator' privileges to invite) is showing a client bug. In reality, it should read 'Default'.

You need to actually change the required permissions (power level) — for example, by setting it to Default and then to Moderator, so that your client is not lying about the actual required power level on the server.

**Comment by MarcelCoding** [comment]
That makes sense. Thanks for this information.

**Comment by Florian-Sabonchi** [comment]
> That makes sense. Thanks for this information.

Hi, i agree with you this makes sense
