### ISSUE TITLE
review the list of blacklisted sytests

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#10696]
Some of the sytests on the blacklist look to be due to bugs that have since been fixed

**Comment by DMRobertson** [comment]
We now think we've got the most frequent flakes squashed in matrix-org/sytest#1142 and matrix-org/sytest#1138.

**Comment by DMRobertson** [comment]
I've had a quick look and I can't see any blacklisted tests that we can rerun.

I found a couple of blacklist entries suspicious: [here](https://github.com/matrix-org/matrix-spec-proposals/pull/2314#issuecomment-1087501407) and [here](https://github.com/matrix-org/matrix-spec/issues/942#issuecomment-1087499098).
