### ISSUE TITLE
Email sending requires Twisted>=21.2.0 as of v1.41.0

### ISSUE THREAD

**Issue by AndrewFerr** [matrix-org/synapse#10709]
### Description

v1.41.0's addition of [a setting to disable TLS for sending email](https://github.com/matrix-org/synapse/commit/74d7336686e7de1d0923d67af61b510ec801fa84) added a dependency on Twisted 21.2.0, as it calls the [`ESMTPSenderFactory`](https://github.com/matrix-org/synapse/commit/74d7336686e7de1d0923d67af61b510ec801fa84#diff-473cfea8f7f9bbb1d4768d5f266d2d6d1dbc5dcc9c0e91afc7811fd6d3b9f16eR66) constructor with `hostname` as a keyword argument. That argument is only supported as of [Twisted 21.2.0](https://github.com/twisted/twisted/blob/twisted-21.2.0/src/twisted/mail/smtp.py#L2212), as it is missing in [Twisted 20.3.0](https://github.com/twisted/twisted/blob/twisted-20.3.0/src/twisted/mail/smtp.py#L2055).

Despite this, Synapse only sets a dependency on [Twisted>=18.9.0](https://github.com/matrix-org/synapse/blob/develop/synapse/python_dependencies.py#L64). If Synapse was installed from source, then upgrading from v1.40.1 via `pip` may not upgrade the version of Twisted used.

If that happens, then whenever Synapse tries to send an email (such as when a user attempts to register an email address with their mxid), it will hit this error:

```
Traceback (most recent call last):
  File "$PWD/synapse/handlers/identity.py", line 413, in send_threepid_validation
    await send_email_func(email_address, token, client_secret, session_id)
  File "$PWD/synapse/push/mailer.py", line 205, in send_add_threepid_mail
    template_vars,
  File "$PWD/synapse/push/mailer.py", line 323, in send_email
    text=plain_text,
  File "$PWD/synapse/handlers/send_email.py", line 157, in send_email
    tls_hostname=self._smtp_host if self._enable_tls else None,
  File "$PWD/synapse/handlers/send_email.py", line 76, in _sendmail
    hostname=tls_hostname,
TypeError: __init__() got an unexpected keyword argument 'hostname'
```

The problem can fixed by upgrading Twisted, which can be done by uninstalling it and then reinstalling Synapse's dependencies.

This could be fixed by updating Synapse's dependencies to explicitly require Twisted>=21.2.0, but it seems excessive to require such a drastic upgrade from the current minimum just for the optional feature of sending emails.

### Steps to reproduce

- Install a development version of Synapse earlier than v1.41.0 from source, following [these instructions](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#4-install-the-dependencies).
- Upgrade the installation with `pip install -Ue ".[all]"`.
- In Element Web, register a new email address with your account in Settings->General.

A non-development installation may hit this problem as well, but I haven't tried it.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Self-hosted installation

- **Version**: v1.41.0

- **Install method**: pip with [development dependencies](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#4-install-the-dependencies)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian 10 armv7l
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by AndrewFerr** [comment]
Thanks for fixing this so quickly!

**Comment by richvdh** [comment]
no problem, thank you for reporting it!
