### ISSUE TITLE
`txn` being redefined in for loop as we are iterating over it

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#10739]
Spurred on by the note in https://github.com/matrix-org/synapse/pull/10734 about `txn` being redefined in for loop as we are iterating over it.

> We were originally iterating over `txn`, which can work, but as `txn` was being used to run a
simple_delete operation inside the loop, it was actually being redefined mid-loop.
>
> https://github.com/matrix-org/synapse/pull/10734

I was curious if there were other cases in the codebase, so I searched for `in txn:` and found one more case. It looks like this would cause a problem if there was an event where the `event_auth_chains` -> `chain_id` was not defined.

https://github.com/matrix-org/synapse/blob/c586d6803a2adebcdd486be2d9eac1f62fd7d4ab/synapse/storage/databases/main/events.py#L578-L588

## Linting

Maybe we should disallow iterating over `txn` directly in favor of using `txn.fetchall()`

**Comment by erikjohnston** [comment]
Oh, good catch. I think its unlikely for that case to ever be hit in practice as its really only used to handle out of band memberships and we likely only have one of those per room anyway. We should still fix it though!

> Maybe we should disallow iterating over `txn` directly in favor of using `txn.fetchall()`

Using `txn` can be considerably faster when there's a lot of rows to process, so I'm not super keen on forbidding it entirely. Ideally mypy would have a way to annotate that we can't reuse txn here, but I don't think its possible.
