### ISSUE TITLE
Invalid signature for server matrix.org with key ed25519:a_RXGa:

### ISSUE THREAD

**Issue by micronator** [matrix-org/synapse#10749]
Hi all,

I am using NethServer-7.9.2009 which is a fork of Centos-7.9
My Matrix-Synapse is on a VM on the LOCAL network 192.168.1.0/24.

At cloudflare.com I have:
● An A record for chat.example.org.
● A MX record for mail.chat.example.org
● All other like www, etc... are CNAME

From my main server attached directly to the internet:
● I redirected all chat.example.org and all its CNAME to LOCAL VM at address 192.168.1.111
● I opened port 8008 and 8448 and redirected them to my LOCAL Matrix-Synapse.
● In /var/www/html/.well-known/matrix/server I have: 
```
{ "m.server": "chat.example.org:443" }

# curl http://localhost:8008/_synapse/admin/v1/server_version
{"server_version":"1.41.0","python_version":"3.6.12"}
```

- The LOCAL VM is running Apache: /etc/httpd/conf.d/a_synapse.conf
```
<VirtualHost *:443>
    SSLEngine on
    ServerName chat.example.org

#####    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    RequestHeader set X-Forwarded-Proto "https"
    AllowEncodedSlashes NoDecode
    ProxyPreserveHost on
    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
    ProxyPass /_synapse/client http://127.0.0.1:8008/_synapse/client nocanon
    ProxyPassReverse /_synapse/client http://127.0.0.1:8008/_synapse/client
</VirtualHost>

<VirtualHost *:8448>
    SSLEngine on
    ServerName chat.example.org
#####    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    RequestHeader set X-Forwarded-Proto "https"
    AllowEncodedSlashes NoDecode
    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
</VirtualHost>
```

https://federationtester.matrix.org reported no error and all looked OK.

I created a Community => "Communauté Example" and a Room "toto" => #toto:chat.example.org
I invited @michelandre:matrix.org
At riot.im, the user michelandre received the invitation.
When he clicked it: "There was an error joining the room"

At riot.im, when I searched for the room #toto:chat.example.org, it is not found, and if tried to join, I received the message:
```
Invalid signature for server matrix.org with key ed25519:a_RXGa: Unable to verify signature for matrix.org: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
```

● On my main server, I tried to add port 8443 and redirecting it to LOCAL and same problem.

I googled quite a lot and found nothing to solve the problem

Any help/suggestion appreciated,

Michel-André

**Comment by joshhubers** [comment]
I am having the same error when trying to join my new homeserver from another server, however under different circumstances.

I started a new install using docker on a Digital Ocean droplet. I have the ports exposed directly with no nginx or proxies and get the same error `Invalid signature for server matrix.org with key ed25519:a_RXGa`

@micronator -- have you seen this issue in your case? https://github.com/matrix-org/synapse/issues/3294

**Comment by richvdh** [comment]
If you're the same person that asked this question in #synapse, then your logs showed that something upstream of your server (Apache, presumably) was replacing `%40` with `@` in the request URI.

**Comment by micronator** [comment]
Hi @richvdh,

You were absolutely right about something replacing %40 with @ etc.

It was the web redirections from my main server to my LOCAL VM server doing it.

I added nocanon in the section of httpd.conf that were the redirectors.

But I have to admit that the error message is quite confusing...

Michel-André
