### ISSUE TITLE
homeserver should be a script

### ISSUE THREAD

**Issue by elopio** [matrix-org/synapse#1075]
The README says that we should run this to set up a homeserver:

`python -m synapse.app.homeserver`

This should be a script, just like synctl. It should be defined in the setup.py so we can call it directly after the project is installed, instead of calling with `python -m` and the module name.

**Comment by hawkowl** [comment]
`python -m` is the preferred way of running Python applications nowadays, especially since it removes the problem of "what Python did I install this with" and "what Python am I running it with".
