### ISSUE TITLE
Admin user ability to watch other users messages?

### ISSUE THREAD

**Issue by rfakit** [matrix-org/synapse#10763]
hi 
duo to security and data mining . I need to see other users messeges in private chat and rooms.
what's your suggestion?
thanks in advanced

**Comment by FSG-Cat** [comment]
Already a thing. Its called go digging in your database.

**Comment by rfakit** [comment]
not great solution

**Comment by rfakit** [comment]
messages if encrypted in database.
any idea to decrypt  it?

**Comment by MTRNord** [comment]
Honestly? Don't

**Comment by FSG-Cat** [comment]
> 
> 
> messages is encrypted in database.
> any idea how to decrypt it?

Pound Sand?

**Comment by vurpo** [comment]
You need to ask the senders of those messages to give them to you

**Comment by vurpo** [comment]
To spell it out for you: the reason those messages are encrypted is because their senders encrypted them specifically so you won't be able to read them. You can't get those messages without their consent, that's how the system is designed

**Comment by MTRNord** [comment]
> 
> 
> To spell it out for you: the reason those messages are encrypted is because their senders encrypted them specifically so you won't be able to read them. You can't get those messages without their consent, that's how the system is designed

And I think most here would agree if that gets a backdoor the network could be considered compromised for security reasons.

**Comment by rfakit** [comment]
where is the  location of key in client android?

**Comment by babolivier** [comment]
As it's been outlined here, encryption backdoors are not something we wish to support in Synapse. A solution for you could be to build a bot that a custom client of yours invites in every room created/joined. Either way, this is out of the scope of the Synapse repository.
