### ISSUE TITLE
Links in previews being cut

### ISSUE THREAD

**Issue by decipher2k** [matrix-org/synapse#10765]
Steps to reproduce:
Send a message to Element through a Synapse server that contains a Youtube link with a hyperlink in the description of the video that exceeds the maximum character count.

Expected behaviour:
the link in the preview being either clickable (thus the maximum character count being exceeded in that case), or completely removed

Actual behaviour:
the hyperlink gets cut. It is in the format http.//www.somecoolhyp... (the rest of the link gets replaced with dots),
thus leading to a 404 page.

Example:
"og:description": "In this presentation, I will demonstrate a setup I use to be more productive with FOSS.All scripts are available at : https://github.com/magnacore/Productivi...",

**Comment by richvdh** [comment]
I'm struggling to understand the description here. Please can you share a screenshot?

**Comment by richvdh** [comment]
possibly related to https://github.com/matrix-org/synapse/issues/9733 / https://github.com/matrix-org/synapse/issues/2752

**Comment by richvdh** [comment]
closing this due to lack of info.
