### ISSUE TITLE
Default webclient is deprecated and needs replaced 

### ISSUE THREAD

**Issue by tiny6996** [matrix-org/synapse#1078]
The matrix-synapse server is is still using deprecated angular-js client.  a possible solution is the vector client can be installed on the server by uncompressing [a tar file from the download page](https://vector.im/packages/) editing the /etc/matrix-synapse/conf.d/webclient.yaml file so it points to directory were the uncompressed tar file. To finish the config.sample.json needs to be edited to contain the current homeserver address.

**Comment by ara4n** [comment]
agreed. dup #1527
