### ISSUE TITLE
Prevent multiple instances of shutting down the same room simultaneously

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#10797]
We had a process attempt to shut down the same room using two, separate calls to the Admin API:

* `DELETE /_synapse/admin/v1/rooms/{roomId}`
* `POST /_synapse/admin/v1/{roomId}/delete`

Both of these method handlers eventually call [RoomShutdownHandler.shutdown_room](https://github.com/matrix-org/synapse/blob/0288e6033b08149867e742283bb0139f10b66b01/synapse/handlers/room.py#L1241), and there doesn't look to be any code that deduplicates requests anywhere.

This lead to a state where two long-running shutdown processes for the same room occurred and choked the main processes' CPU, resulting in the need to restart the main process to recover its performance.

**Comment by dklimpel** [comment]
It is related to #10294

**Comment by dklimpel** [comment]
Perhaps this API should return an ID like the purge room API. https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/purge_history_api.md#purge-status-query
