### ISSUE TITLE
Cannot remove old email address on matrix.org after adding new email

### ISSUE THREAD

**Issue by infoveinx** [matrix-org/synapse#10809]
### Description

Cannot remove old email address after adding a new one on matrix.org.  Using the https://app.element.io browser login.

### Steps to reproduce

- Log into my matrix.org account via https://app.element.io
- Added new email address, and successfully verified it.
- Try to remove old email address
- Get error: Unable to remove contact information. Failed to remove threepid

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **matrix.org**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by anoadragon453** [comment]
Moving discussion to the Sydent repo: https://github.com/matrix-org/sydent/issues/398
