### ISSUE TITLE
Enable back presence feature on matrix.org server

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#10808]
Regarding to this issue closing comment https://github.com/matrix-org/synapse/issues/3971#issuecomment-885760425, most of presence high load problems are solved now, so maybe there is a good time to turn it on back on matrix.org server? 

Because there is a lot of embarrassing questions from users where is a presence feature on Matrix protocol and why it is disabled on "main" matrix.org server...

**Comment by anoadragon453** [comment]
There's still some outstanding performance work for presence which we'd like to see finished before enabling the feature of matrix.org. Namely those mentioned in https://github.com/matrix-org/synapse/issues/9478.

That being said, we do run the feature for another homeserver with around ~100 users internally with no issues.
