### ISSUE TITLE
Recent releases are not signed

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#10818]
It seems that [recent releases](https://github.com/matrix-org/synapse/releases) of Synapse are not being signed any longer. I think this is due to the [release script](https://github.com/matrix-org/synapse/blob/14b8c0476f93ea2ed3134e75733e45aa0ab6f5a5/scripts-dev/release.py) not properly signing the tags, but I'm unsure.

(Note that @anoadragon453 mentioned he has been doing the tags manually so his releases do have signatures on them.)

@erikjohnston mentioned this might be due to already having the necessary keys unlocked or not.

**Comment by erikjohnston** [comment]
We probably need to add an option to: https://github.com/matrix-org/synapse/blob/6878e1065308caf0f79e380b4de1433ab1487a34/scripts-dev/release.py#L279

The docs for the github lib is at https://pygithub.readthedocs.io/en/latest/reference.html
