### ISSUE TITLE
In Synapse Admin API's Rooms query seach_term don't accept non-ASCII characters

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#10841]
### Description

Not all rooms use English characters, but In Synapse Admin API's Rooms query seach_term don't accept non-ASCII characters.

### Steps to reproduce

For example query to search rooms with Russian symbol "ж" using path `/_synapse/admin/v1/rooms?dir=f&from=0&limit=10&order_by=name&search_term=%D0%B6` shows the error:
```json
{
  "errcode":"M_UNKNOWN",
  "error":"Query parameter 'search_term' must be ascii"
}
```
### Version information
- **Synapse Version**:
    "server_version": "1.42.0",
    "python_version": "3.8.10"

**Comment by DMRobertson** [comment]
Thanks for the report. Looks like the call to `parse_string` here

https://github.com/matrix-org/synapse/blob/430241a1e9fd4fbb82d83958b61bbd66c9ba3505/synapse/rest/admin/rooms.py#L128 assumes an encoding of ascii by default. I wonder if it suffices to relax this to `encoding="utf-8"`? [`get_rooms_paginate`](https://github.com/matrix-org/synapse/blob/dc75fb7f0552e6a9903a7c173672c96610219ec0/synapse/storage/databases/main/room.py#L397-L404) claims to accept any string. We'll end up searching based on `room_name LIKE %search_term%'. We strongly recommend [configuring postgres](https://matrix-org.github.io/synapse/latest/postgres.html) to use the C.UTF-8 locale; if so, I think that query might just work?

**Comment by MurzNN** [comment]
For me the raw SQL query works well:
```SQL
SELECT COUNT(*) FROM room_stats_state WHERE "name" LIKE '%ж%';
 count 
-------
    32
(1 row)
# show LC_COLLATE;
 lc_collate 
------------
 C
(1 row)

# SHOW SERVER_ENCODING;
 server_encoding 
-----------------
 UTF8
(1 row)

```
