### ISSUE TITLE
user-directory API wrong limit and limited (off by 1)

### ISSUE THREAD

**Issue by douph1** [matrix-org/synapse#10840]
### Description

https://matrix.org/docs/spec/client_server/latest#user-directory
>Response:
>limited | boolean | Required. Indicates if the result list has been truncated by the limit.

The `limited` response attribut is wrongly reported
If I search for a term with a limit of : 50 this query can return 2 elements and the result is not truncated : ` "limited": false` : ok
But if I limit the search to 1 element. The result show me the **two** elements and respond with  `"limited": true` which is twice wrong as the result is complete and I have asked to limit the response to 1...

If I don't specify `limit` in query I can get 11 response but the doc says :
>The maximum number of results to return. Defaults to 10.

If I use ask to limit to more than 50 the result is truncated at 51 elements.
This hard limit (not configurable)
https://github.com/matrix-org/synapse/blob/bfb4b858a999684ba2459ee4c3aa20270d13062d/synapse/rest/client/user_directory.py#L67
is not documented in the api  (and off by 1)
https://matrix.org/docs/spec/client_server/latest#user-directory

```
curl -s --location --request POST 'https://hostname/_matrix/client/r0/user_directory/search' --header 'Authorization: Bearer mybearer' --header 'Content-Type: application/json' --data-raw '{
  "limit": 20,
  "search_term": "ab"}' | jq
{
  "limited": false,
  "results": [
    {
      "user_id": "@ab61f215-a3ea-442b-8c7c-49cee57aad66:podo-dev",
      "display_name": "ab61f215-a3ea-442b-8c7c-49cee57aad66",
      "avatar_url": null
    },
    {
      "user_id": "@ab32d61e-5774-4716-b1f2-14cb9b07cb00:podo-dev",
      "display_name": "ab32d61e-5774-4716-b1f2-14cb9b07cb00",
      "avatar_url": null
    }
  ]
}
```
return 2 result : ok , `limited : false` : ok

then limit by 1 in query:
```
curl -s --location --request POST 'https://hostname/_matrix/client/r0/user_directory/search' --header 'Authorization: Bearer mybearer' --header 'Content-Type: application/json' --data-raw '{
  "limit": 1,
  "search_term": "ab"}' | jq
{
  "limited": true,
  "results": [
    {
      "user_id": "@ab61f215-a3ea-442b-8c7c-49cee57aad66:podo-dev",
      "display_name": "ab61f215-a3ea-442b-8c7c-49cee57aad66",
      "avatar_url": null
    },
    {
      "user_id": "@ab32d61e-5774-4716-b1f2-14cb9b07cb00:podo-dev",
      "display_name": "ab32d61e-5774-4716-b1f2-14cb9b07cb00",
      "avatar_url": null
    }
  ]
}
```

- return 2 elements instead of 1
- pretend the result is not complete: `"limited": true` .. but this is wrong 

### Version information

This was discover in a old version but the source code of the directory_search and rest api endpoint wich limit to 50(51) does not have change a lot since 

```
apt-cache policy matrix-synapse-py3
matrix-synapse-py3:
  Installé : 1.31.0+bionic1
  Candidat : 1.31.0+bionic1
 Table de version :
 *** 1.31.0+bionic1 500
        500 https://matrix.org/packages/debian bionic/main amd64 Packages

```

Discoverd in our homeserver

```
curl http://localhost:8008/_synapse/admin/v1/server_version
{"server_version":"1.31.0","python_version":"3.6.9"}
```

- **Platform**:
Ubuntu

**Comment by DMRobertson** [comment]
Thanks for the report! We should check to see if this is reproducible with current versions. Speaking of versions, please be aware that we recently released Synapse 1.41.1 which includes security fixes. See [here](https://matrix.org/blog/2021/08/31/synapse-1-41-1-released) for more details.

I remember the user directory storage functions request `limit + 1` elements from the database, to see if there are extra elements that we are going to limit. If so, it sounds like we haven't dropped that extra +1 result from the response.

**Comment by anoadragon453** [comment]
The following was returned from matrix.org running c5ba1d67b1aeb06f656119e8f0480451a8c1e94f today:

```
curl 'https://matrix-client.matrix.org/_matrix/client/r0/user_directory/search' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0' -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer $$$' --data '{"search_term":"mic"}' --silent  | jq .
{
  "limited": true,
  "results": []
}
```

Presumably `limited` should be false.

**Comment by DMRobertson** [comment]
> The following was returned from matrix.org running [c5ba1d6](https://github.com/matrix-org/synapse/commit/c5ba1d67b1aeb06f656119e8f0480451a8c1e94f) today:
> 
> ```
> curl 'https://matrix-client.matrix.org/_matrix/client/r0/user_directory/search' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0' -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer $$$' --data '{"search_term":"mic"}' --silent  | jq .
> {
>   "limited": true,
>   "results": []
> }
> ```
> 
> Presumably `limited` should be false.

This is an unfortunate interaction between the spam checking logic and the database logic.

https://github.com/matrix-org/synapse/blob/b38bdae3a2e5b7cfe862580368b996b8d7dfa50f/synapse/handlers/user_directory.py#L98-L107


 In this example:

- The DB returned `limited: True` because it only produced 10 users, but there was at least one more matching the search query.
- The spam checker excluded all of these users from the results.
- `limited: True` remains in the `results` object.

`limited: True` is still correct in principle here: if you asked the DB to look up say 30 users, the spam checker might have deemed users 11--30 to be acceptable and returned you something. You can imagine a world where we make a second DB query if `len(non_spammy_users) < len(results["results]")`. But I think that's probably overkill.
