### ISSUE TITLE
Request for the last message event on a room

### ISSUE THREAD

**Issue by GeneticHero** [matrix-org/synapse#10858]
**Description:**

I was unable to find the proper way of requesting the last message from a particular room. I have tried using a filtered sync request. This approach kind of works but cannot return the last message event after several join room->sync request->leave room steps. It seems that the last message event goes out of the scope of the sync search request.  
I was looking at this from an IoT standpoint in which a specific variable would be associated with a room. From there, any number of clients could join and request or subscribe to the particular variable.
Is there another way of achieving this outcome? because it seems that something like this would be a nice feature to have.

**Comment by DMRobertson** [comment]
It sounds like eventually the `/sync` response just contains join and leave events, omitting the message events.

I think you probably want to use https://spec.matrix.org/unstable/client-server-api/#get_matrixclientr0roomsroomidmessages with a filter that only listens for events of type `m.room.message`.

**Comment by richvdh** [comment]
I think it should be possible to use `/sync` for this, possibly with a filter.

**Comment by GeneticHero** [comment]
I used the following configuration: 
```
    json filter;

    filter["account_data"] = {};
    filter["account_data"]["not_types"] = {"*"};

    filter["presence"] = {};
    filter["presence"]["not_types"] = {"*"};

    filter["room"] = {};
    filter["room"]["rooms"] = {roomId["room_id"]};

    filter["room"]["state"] = {};
    filter["room"]["state"]["not_types"] = {"*"};

    filter["room"]["timeline"] = {{"limit", 1}};
    filter["room"]["timeline"]["types"] = {"m.room.message"};

    string url = "/_matrix/client/r0/sync?filter=";
    url += filter.dump();
    url += "&access_token=";
    url += guestId["access_token"];
````
This configuration goes out of scope after several calls. Can you suggest an alternative ?

**Comment by richvdh** [comment]
> This configuration goes out of scope after several calls

sorry, what exactly does this mean?

Note that if you pass your filter in as a query-param, you'll need to url-encode it correctly. Possibly that is causing your problem.

(Also, passing an access token as a query param is a very bad practice.)

Anyway, this appears to be a question about using the Client-server API rather than an issue in synapse. I'm afraid we can't provide individual support for how to use the API.

**Comment by DMRobertson** [comment]
> This configuration goes out of scope after several calls.

What does this mean in terms of the response to `/sync`? When "out of scope", does the response body contain no data for that room?

**Comment by GeneticHero** [comment]
After a new message is sent to the room the response of the server with the selected filter is: 
```
{"device_one_time_keys_count":{"signed_curve25519":0},"next_batch":"s6984_3047_0_1_1_1_1_2217_1","org.matrix.msc2732.device_unused_fallback_key_types":[],"rooms":{"join":{"!wUphgXBRJVDnwaBaow:localhost:8000":{"account_data":{"events":[]},"ephemeral":{"events":[]},"org.matrix.msc2654.unread_count":0,"state":{"events":[]},"summary":{},"timeline":{"events":[{"content":{"body":"test-message","msgtype":"m.text"},"event_id":"$ifx6oIksWorMqCYYEOAC36dRg1HeW2GtSIoi_JL8aCo","origin_server_ts":1633456740446,"sender":"@2213:localhost:8000","type":"m.room.message","unsigned":{"age":1737}}],"limited":true,"prev_batch":"t6962-6981_3047_0_1_1_1_1_2217_1"},"unread_notifications":{"highlight_count":0,"notification_count":0}}}}}
```

after a number of calls I get the following response:
```
{"device_one_time_keys_count":{"signed_curve25519":0},"next_batch":"s7038_3079_0_1_1_1_1_2244_1","org.matrix.msc2732.device_unused_fallback_key_types":[]}
```

Sure you cannot provide individual support, I didn't reopened the issue.

**Comment by richvdh** [comment]
Oh, I know what this is. The filter is applied *after* the message limit. (ie: we pull the 20 (?) most recent events in each room, *then* apply the filter).

I'm led to wonder *why* you want to repeatedly load most recent message in the room. Maybe you should be using room state rather than message events.
