### ISSUE TITLE
Media files in `url_cache/` and `url_cache_thumbnails/` should not be stored in storage providers

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#10862]
### Description

Spotted by @richvdh:

Currently media files in `url_cache/` and `url_cache_thumbnails/` get replicated to storage providers.

These files are supposed to be transient, and so should not be stored in any storage providers (eg. S3)

### Version information

- **Homeserver**: matrix.org

**Comment by clokep** [comment]
Or I wonder if they're meant to be deleted when we purge old previews?

https://github.com/matrix-org/synapse/blob/b93259082c7d8d3fe8376a646e130213d90069dc/synapse/rest/media/v1/preview_url_resource.py#L484

**Comment by squahtx** [comment]
Looks like this is a duplicate of #5411, except that issue is about `local_thumbnails/` and `remote_thumbnail/` as well.
Let's keep this issue for the `url_cache` part of #5411 and let the original issue be about the thumbnails.

**Comment by squahtx** [comment]
> Or I wonder if they're meant to be deleted when we purge old previews?

Interesting find!

I'd argue that since url cache data is so short lived, it makes sense to not hand it over to any storage providers:
 * Incurring S3/cloud costs for short lived data seems wasteful (echoing the complaint in #5411)
 * The impact of omitting it from storage providers acting as backups is limited to 24 hours anyway

... or we could add another per-storage provider config option, defaulting to do-not-store?

**Comment by clokep** [comment]
> ... or we could add another per-storage provider config option, defaulting to do-not-store?

I think limiting config is desirable, so best not to do this unless there's a huge benefit!
