### ISSUE TITLE
Add search by room ID and room alias to List Room admin API

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#10874]
**Description:**

Currently the List Room admin API allows filtering rooms only by room name, regarding to https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#list-room-api

> search_term - Filter rooms by their room name. Search term can be contained in any part of the room name. Defaults to no filtering.

But very often we need to find room by it's alias or id substring. Is it hard to add those room fields to `search_term` or as separate query field?

**Comment by clokep** [comment]
I wonder if a better solution would be to expand to [room details API](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#room-details-api) to accept an ID or alias?

I'm not sure what use searching an ID substring would have, although I could see searching an alias substring being useful.

Can you describe a bit more about what would be most useful?

**Comment by MurzNN** [comment]
For example, we use the https://github.com/Awesome-Technologies/synapse-admin tool to manage rooms on server, and need to quickly find room by it's id or alias, but even when typing full id or alias - we receive the empty result.
Yes, searching by exact match of full id or alias will be enough, but if we reuse same `search_term` field - why don't allow search by substring (eg local part of id or alias, without domain)?

**Comment by clokep** [comment]
As I mentioned, if you have the room ID there's already an API that you can use without searching. I think it likely makes more sense to expand that to also support aliases. I think it would be confusing to use a "list" API when you're looking up an exact value.
