### ISSUE TITLE
Same event is synced twice

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#10878]
I've got some client logs and a network response where some old events seem to come down sync and the only reasonable explanation is that some of those events have been synced before to this client. I can provide the logs in private if needed.

This caused https://github.com/vector-im/hydrogen-web/issues/504 in Hydrogen.

**Comment by bwindels** [comment]
Additionally, a member event was duplicated in the sync response, similar to https://github.com/matrix-org/synapse/issues/1995

**Comment by erikjohnston** [comment]
Could this be the same as #9768 ?

**Comment by erikjohnston** [comment]
My hunch is this is is the same as the other issue, unless @bwindels thinks that this was caused by a non-membership event?
