### ISSUE TITLE
Remove type-ignore for `IReactorTCP.connectTCP`'s `hostname` argument

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#10899]
The fix proposed in #10895 for #10851 requires a series temporary `# type: ignore`.

We should remove this as soon as we're able: namely, when twisted release a version which includes [this commit](https://github.com/twisted/twisted/commit/ec7445d6361ce04424b3570a81263dc6760f15de).

**Comment by eshaanagarwal** [comment]
hi ! Is this issue open for contribution ?

**Comment by DMRobertson** [comment]
Hi @eshaanagarwal , a contribution would be welcome, but we can't make progress on this until the twisted project makes a new release. I'll remove the good-first-issue label for now to make that a bit clearer.

**Comment by clokep** [comment]
Note that "new" in this case means a release after 21.7.0 (which is what the current Twisted release is).
