### ISSUE TITLE
Security Audits, self destructing messages and other Enhancements

### ISSUE THREAD

**Issue by Y0ngg4n** [matrix-org/synapse#10921]
**Description:**
It would be nice if matrix would get better in the points that are marked red here: 
https://www.securemessagingapps.com/

For example get an security audit, implement self destructing messages and so on.

**Comment by erikjohnston** [comment]
We've had a security audit of the underlying encryption library: https://matrix.org/blog/2016/11/21/matrixs-olm-end-to-end-encryption-security-assessment-released-and-implemented-cross-platform-on-riot-at-last

For other features I'd suggest opening issues on https://github.com/matrix-org/matrix-doc if there aren't existing issues already.

This isn't really something we can action as a Synapse team, so I'm going to close this for now, but thanks for flagging it :slightly_smiling_face:
