### ISSUE TITLE
"Event not signed by authorising server" when trying to change nickname/avatar in a space-restricted room

### ISSUE THREAD

**Issue by pavlukivan** [matrix-org/synapse#10920]
### Description

I host a homeserver, it has a room with version 9 set to only allow joining for space members, it's upgraded from an old room of version 6. My friend uses the official homeserver, and when he tries to change his per-room avatar it says "Event not signed by authorising server". I am able to reproduce it as well.

### Steps to reproduce

- create a room with space-restricted membership
- join the room with an account on a different homeserver
- try to use /myroomavatar or /myroomnick

### Version information

- **Homeserver**: matrix.org *and* my own (I tested on both)

**Comment by clokep** [comment]
Hm, those checks shouldn't be being applied if the user's previous membership was `join`! I'll take a look.

**Comment by clokep** [comment]
We have a complement test for re-joining the same room (and ensuring it works), but it really should just be sending an updated `m.room.member` event, which is what [Element Web does](https://github.com/matrix-org/matrix-react-sdk/blob/2d1d42b90e8418017348cae1bd17a8a92340fdfb/src/SlashCommands.tsx#L291-L302). Note that they also copy the *entire* previous event and add to it. I think that's probably fine and the server should handle this OK, but not 100% sure.

**Comment by pavlukivan** [comment]
fwiw the steps i listed seem to work no matter the join order, i'm not familiar enough with the synapse codebase to know if that means anything, but just note that it should be fairly easy to reproduce for you as well to check if it's fixed

**Comment by clokep** [comment]
I was able to reproduce, I think what Element Web is doing is fine. The logic is a bit torturous though so haven't solved it yet!

**Comment by clokep** [comment]
Note that #10933 should fix this.

**Comment by clokep** [comment]
Unfortunately the fix just missed Synapse 1.44.0, so will be in 1.45.0. Thanks so much for the detailed report with steps to reproduce! 🎉
