### ISSUE TITLE
Federation broken due to LETS encrypt sept 30 root cert change

### ISSUE THREAD

**Issue by gvansanden** [matrix-org/synapse#10949]
### Steps to reproduce

- Set up latest synapse on Ubuntu 20.04 with lets encrypt
- federate
or

- couple any python application using the official libraries

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

Federation and api calls to matrix fail because the certifcate chain is no longer valid

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.43

- **Install method**: deb
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 20.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by reivilibre** [comment]
How have you configured your TLS?

This sounds like a Let's Encrypt problem; assuming you're pointing Synapse to the `fullchain.pem` file that certbot gives you, it should be a matter of renewing your certificates and getting a new `fullchain.pem` file.

Perhaps you could share your configuration — at least the `listener` section?

Thanks.

**Comment by gvansanden** [comment]
> How have you configured your TLS?
> 
> This sounds like a Let's Encrypt problem; assuming you're pointing Synapse to the `fullchain.pem` file that certbot gives you, it should be a matter of renewing your certificates and getting a new `fullchain.pem` file.
> 
> Perhaps you could share your configuration — at least the `listener` section?

Yes, I should have detailed my setup.  Matrix is running behind a haproxy loadbalancer that did the renewal of the certificates.
This is the listeren
` - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['127.0.0.1', '10.250.0.49']

    resources:
      - names: [client, federation]
        compress: false
`
I switched to a Sectigo certificate and Matrix works in the element app on Android again as well as the integrations in Python.
But federation is still broken, I don't get any rooms to join on other servers (404 error)

**Comment by reivilibre** [comment]
> Matrix is running behind a haproxy loadbalancer that did the renewal of the certificates.

Right, so sorry but this might have to be taken elsewhere — you could try #synapse:matrix.org for support with this.

(You should be able to test the URLs in a web browser, e.g. `https://matrix.example.org/_matrix/federation/v1/version`. If that causes a TLS error, then it's likely not Synapse's fault that it refuses to federate with that server.)

As this concerns your TLS certificate and you're using HAProxy to handle TLS for your homeserver, then it's hard to consider this a Synapse issue — it'd have to be an issue with your HAProxy/Let's Encrypt configuration (or very unlikely: a bug in HAProxy).
