### ISSUE TITLE
LDAP authentication does not work with self-signed certificate

### ISSUE THREAD

**Issue by mvalois** [matrix-org/synapse#10955]
### Description

Since version 1.37, apparently using https://github.com/matrix-org/matrix-synapse-ldap3/pull/89, self-signed certificate LDAP backend do not work even if CA is placed in the system trust store.

### Steps to reproduce

- upgrade to matrix 1.37
- import self-signed certificate : put it in `/usr/local/share/ca-certificates/ldap.crt` and run `update-ca-certificates`
- certificate gets written in `/etc/ssl/certs`
- restart matrix-synapse
- try to authenticate
- observe in the logs : `ldap_auth_provider - 499 - WARNING - sentinel - Error during LDAP authentication: ("('socket ssl wrapping error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)',)",)`
- replacing `_ldap_tls = ldap3.Tls(validate=ssl.CERT_REQUIRED)` to `_ldap_tls = ldap3.Tls()` solve the issue but reduces security
- ldapsearch works with same server and credentials

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: personal homeserver

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.37.0","python_version":"3.7.3"}

- **Install method**: deb package using apt sources from matrix
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian 10
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by reivilibre** [comment]
It's not clear to me that your system actually trusts your LDAP certificate.

I'm not entirely sure about the specifics of self-signed certificates, but my usual approach is to use `minica` (available in the Ubuntu repos, at least), which generates:

* a CA private key — keep it private
* a CA certificate — this is the one you install in your operating systems' trust stores
* some other keys & certificates (signed by the CA certificate) — these are the ones you give to your servers such as your LDAP server, etc

I wonder if you have generated a single certificate, which you have both given to your LDAP server and installed as a CA certificate into your OS...? I don't know if that would work: I would have thought that you need a certificate *signed by* the one in your trust store for it to work.

`openssl s_client -connect myhostnameHere:636` (I think 636 is LDAPS' port number) is a useful tool you can run to connect to your server and check the certificate. Look out for the line `Verify return code: 0 (ok)` — if that doesn't say `0 (ok)` then that's likely not Synapse's fault.

**Comment by mvalois** [comment]
Usually, certificate is accepted by the client if it is trusted, which can be done in 2 ways:

1. the certificate is itself present in the trust store (i.e. ca-certificates)
2. or there is a trust path from this certificate to one or more certificates present in the trust store

I fall into the first case, where ldapsearch binary apparently supports, and matrix-synapse doesn't.

**Comment by reivilibre** [comment]
> 1. the certificate is itself present in the trust store (i.e. ca-certificates)

This is interesting. I was not very aware of this option; I guess I had it in mind that CA certificates and the 'leaf' certificates (I don't know the terminology) were marked differently.

Do you know how other pieces of software handle this case? e.g. if I did that for a HTTPS website and tried Firefox/cURL/etc, would that work? I can't find much information about that; https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list, for example, seems to always be talking about adding the *CA*'s cert to the trust store.

**Comment by mvalois** [comment]
Yes, Firefox does that. This is what happens when you connect to a webpage having a certificate signed by an untrusted PKI (then you have to click 'accept' to trust the leaf certificate).
OpenSSL says : 
```
depth=0 CN = active-directory.local
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = active-directory.local
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = active-directory.local
   i:DC = local, DC = AD, CN =AD-CA
---
```
so yes there is only one certificate, which is in the `ca-certificates` trust store.
You are right, I think ldapsearch uses GnuTLS.

**Comment by reivilibre** [comment]
> Yes, Firefox does that. This is what happens when you connect to a webpage having a certificate signed by an untrusted PKI (then you have to click 'accept' to trust the leaf certificate).

I mean, if you put the leaf certificate straight into your OS store? Firefox asking you to make an exception for a certificate isn't really what I mean (though I guess you are kind of right in that it's basically the same thing, just manual and not using the OS' trust store)

> `verify return:1`

So I see that OpenSSL did not accept your leaf certificate being in the trust store.
This is likely the root cause of Synapse not accepting it either.

I don't know off the top of my head how to try GnuTLS, but I suspect it is different in that it's fine with that.

I don't know if it's possible for Synapse to get OpenSSL to act in the same way as GnuTLS or not :/.

**Comment by mvalois** [comment]
> I mean, if you put the leaf certificate straight into your OS store? 

Firefox doesn't use the OS trust store but has its own bundled one.
> > `verify return:1`
> 
> So I see that OpenSSL did not accept your leaf certificate being in the trust store. This is likely the root cause of Synapse not accepting it either.

Yes, I will investigate that further.
Thank you a lot for your help :)

**Comment by reivilibre** [comment]
I'm going to close because I think this is not something that 'should' be 'fixed'; it's the way OpenSSL works.

I also believe the diagnosis is correct because another user had an issue when using a leaf certificate in the trust store, which went away when putting a CA certificate in the trust store.

**Comment by andersruneson** [comment]
Hi @mvalois 
How did you solve this issue in the end, I got the same problem after upgrading synapse.
Thanks
