### ISSUE TITLE
'apparently some people use access tokens that are not macaroons'

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#10964]
This comment seems stale, since it now seems like we encourage and use `syt_...` tokens by default which are not macaroons?

https://github.com/matrix-org/synapse/blob/8c7a531e277f98ac6b7981b9738649f3a70feb94/synapse/api/auth.py#L417-L418

**Comment by richvdh** [comment]
yes it is. That comment dates from a period where we were trying to move away from random strings as access tokens, towards macaroons. We've long since aborted that plan.
