### ISSUE TITLE
Please mirror your docker images to other registries

### ISSUE THREAD

**Issue by duritong** [matrix-org/synapse#10977]
The docker hub rate limit is affecting fetching the image - it would be nice if the images are also available on other registries such as quay.io where no such limits apply.

**Comment by babolivier** [comment]
We're intentionally being cautious not to add too many release channels as doing so would add more maintenance overhead. However, people from the community should feel free to set up community-driven channels and PR instructions on how to use them to the Synapse install documentation.

**Comment by ibotty** [comment]
Can you reconsider?  It makes consuming that image very hard for people with many computers running behind a single natted gateway.

**Comment by richvdh** [comment]
It might well be worth reconsidering this now that Docker are beginning to ratelimit access.

**Comment by DMRobertson** [comment]
Github apparently offers a registry of sorts, see e.g. https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by callahad** [comment]
Not opposed, but concerned about long-term maintenance... We'd be open to pushing to the GitHub Container Registry, but other solutions like Quay are probably too niche to be worth the fragmentation.

**Comment by reivilibre** [comment]
https://github.com/matrix-org/synapse/pull/11852/files (a PR that adds another docker image that was pushed to GHCR) could be a good source of 'inspiration' for a PR which added the GHCR bits to our existing docker image (i.e. pushing to both).

**Comment by ibotty** [comment]
I don't quiet get why quay is considered niche, but having anything else than dockerhub would be great.

**Comment by clokep** [comment]
#15270 also discussed recent changes Docker is making:

> Docker as a company has taken several moves that leave me concerned about their friendliness to open source projects, and clearly have an aggressive approach to handling their customers. I would feel much safer knowing that matrix.org published images to multiple "official" locations, perhaps including ghcr.io (a feature built into this repository) or ECR public (hosted by AWS and mirroring many images already) so that I can pull from a different source if/when Dockerhub decides to change their policies again.
>
> for reference, dockerhub's latest move adds fees to open source projects. matrix.org may not be affected by this this time, but as an end user i would prefer not to continue to use their services, and redundancy is always a good idea.
>
> [news.ycombinator.com/item?id=35166317](https://news.ycombinator.com/item?id=35166317)

**Comment by DMRobertson** [comment]
Let's make the release CI upload to GHCR as well as dockerhub---it should be straightforward(?!)
