### ISSUE TITLE
SynapseError: 403 - You are not invited to this room

### ISSUE THREAD

**Issue by atomtm** [matrix-org/synapse#11015]
### Description

In order to disable federation on `server_a` and only allow users from `server_b` , I have set `federation_domain_whitelist` on `server_a` homeserver.yaml to `server_b` like so:
```
federation_domain_whitelist:
 - server_b
```
However when a `@user_a:server_a` invites user `@user_b:server_b` into a room, `@user_b:server_b` gets "Failed to join room. You are not invited to this room", and synapse logs on `server_a` reports `SynapseError: 403 - You are not invited to this room`. 
### Steps to reproduce

- on `homeserver.yaml` for `server_a`, whitelist `server_b` using `federation_domain_whitelist`
- create a room on `server_a` and invite `@user_b:server_b`
- try to join the `!room:server_a` using `@user_b:server_b`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
I would expect the `@user_b:server_b` to be able to join `!room:server_a`.
By the way, if I remove everything from `federation_domain_whitelist`, the `@user_b:server_b` can join the room

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.44.0

- **Install method**: package manager apt 
<!-- examples: package manager/git clone/pip  -->

- **Platform**: `Linux Ubuntu5.4.0-88-generic #99-Ubuntu SMP x86_64 GNU/Linux`

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
--> Ubuntu server 20.04, Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz 8 cores, 64gb RAM

**Comment by babolivier** [comment]
Hi, could you paste the logs (at INFO level) that both Synapse instances print when joining the room please? They should allow us for better visibility into what Synapse does and why it might think the user on `server_b` isn't invited.

**Comment by atomtm** [comment]
Do I have to include `server_a` , in `homeserver.yaml` of `server_a` like this : 
```
federation_domain_whitelist:
 - server_b
 - server_a
 ```
??
