### ISSUE TITLE
Changing login method for matrix account

### ISSUE THREAD

**Issue by Baitinq** [matrix-org/synapse#11038]
Hi , is it possible to change the login from google to a normal email-password? I registered with google a while back and I would like to unlink my account from google, but I would like to preserve my username, so thats why I was wondering if there was a way to just change the login method for my account.

Thanks a lot for your help.

**Comment by dklimpel** [comment]
You should take a look here: https://github.com/matrix-org/synapse#support
There is a community.

**Comment by babolivier** [comment]
As @dklimpel points out, we're not using github issues for support requests. Please use one of our support forums mentioned in the link above.
