### ISSUE TITLE
`DELETE /_synapse/admin/v1/rooms/<room_id>` should be an async endpoint

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/synapse#11032]
https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#delete-room-api

Sometimes it takes  while to delete rooms resulting in HTTP timeouts. This endpoint should be made async to mitigate this.

**Comment by clokep** [comment]
We should do something similar to the purge history API where it returns an ID of some sort and you can then use another API to request a status update on that API, see https://matrix-org.github.io/synapse/latest/admin_api/purge_history_api.html

**Comment by clokep** [comment]
Good catch!
