### ISSUE TITLE
Isolated server

### ISSUE THREAD

**Issue by PtDragon** [matrix-org/synapse#11074]
**Description:**

Hello! I did not find a guide about how to create fully isolated server.
I wish to create fully isolated server that will not contact anything outside my network for any reason.

**Comment by dklimpel** [comment]
IMO is the best: do not open your firewall for connections to and from outside.

**Comment by babolivier** [comment]
Hi, we're not using GitHub issues for support requests (only for bug reports and feature requests). Please ask in the support room mentioned here: https://github.com/matrix-org/synapse#support (and open a new issue if the conclusion of the discussion there is that there is a bug in Synapse).
