### ISSUE TITLE
`synapse_storage_transaction_time_bucket` prometheus metric has too high cardinality due to desc label

### ISSUE THREAD

**Issue by daenney** [matrix-org/synapse#11081]
### Description

The `desc` label on `synapse_storage_transaction_time_bucket` results in a very high cardinality metric. For a single instance, there's 248 variants of `desc`, multiplied by 15 buckets. This results in over 3k series for a single host.

Though this might be acceptable if you're only ingesting metrics for a single instance, for Prometheus instances that might be scraping multiple Synapses this quickly becomes a problem.

On one of our internal clusters this is resulting in over a million time series, which is about 5x the amount of time series of the next most problematic timeseries: [`synapse_http_server_response_time_seconds_bucket`](https://github.com/matrix-org/synapse/issues/11082). Though this is not causing storage issues, it causes unnecessarily high CPU load and memory usage ballooning on the ingesters (so we have to run with much bigger instances) and querying these series become problematic.

### Steps to reproduce

- Run lots of Synapse instances
- Scrape them all with a single Prometheus instance
- Prometheus gets sad

### Version information

- **Homeserver**: any
- **Version**: any since this metric got introduced
- **Install method**: unrelated
- **Platform**: unrelated

**Comment by daenney** [comment]
For reference, based on `promtool tsdb analyze` on one of our big clusters:

```
Highest cardinality metric names:
1054110 synapse_storage_transaction_time_bucket
212280 synapse_http_server_response_time_seconds_bucket
78990 synapse_storage_query_time_bucket
75546 synapse_util_caches_cache_evicted_size
```

**Comment by DMRobertson** [comment]
@08d2 noticed this in #12263. Is there anything stopping us from dropping these metrics altogether?

**Comment by richvdh** [comment]
see #11124: turns out that `synapse_storage_transaction_time_count` and `synapse_storage_transaction_time_sum` are useful, so we need to be slightly more intelligent than just ripping them out.

**Comment by richvdh** [comment]
we have found these graphs on our grafana dashboard. They are even discussed in https://matrix-org.github.io/synapse/latest/usage/administration/understanding_synapse_through_grafana_graphs.html#transaction-count-and-transaction-duration. I would not be in favour of removing them.

**Comment by 08d2** [comment]
Sure, dashboards exist which consume them. But do those dashboards actually provide meaningful operational telemetry? The cardinality of this metric is extraordinarily high. It should deliver extraordinary value to justify that cost. Does it?

**Comment by richvdh** [comment]
sorry, I just realised I missed a word in my previous comment. It should read:

> we have found these graphs [very] **useful** on our grafana dashboard.

**Comment by 08d2** [comment]
@richvdh Sweet! What problems have you been able to diagnose and fix? Which servlets have been optimized? Do you have links to issues? If there's data, I'm happy to withdraw my objections.

**Comment by DMRobertson** [comment]
For my own edification:

For each `desc` we are currently produce the following timeseries:
- [`len(DEFAULT_BUCKETS)` = 15](https://github.com/prometheus/client_python/blob/748ffb00600dc25fbd22d37d549578e8e370d996/prometheus_client/metrics.py#L544) cumulative bucket counter series
- a sum counter, of all events seen. (Presumably this identical to the topmost bucket counter when the topmost bucket threshold is `+inf`, as in the default?)
- a count of all events seen.

So I count 17 time series per named database transaction.

If we just want to track the amount of time spent in a type of transaction (e.g. `get_auth_chain_ids`) _across multiple instances of that transaction without knowing how many_, then a single counter would suffice.

If we want to track the mean time a single transaction instance takes, we'd need at least two counters (one for tracking duration, and one for tracking how many txns occur).

Prometheus histograms classify events based on fixed bucket thresholds, whereas Prometheus track the values of a given set of fixed percentiles. (Histogram: "how many requests take < 50ms"? Summary: "How long does it take to serve our quickest 99% of requests?) Or at least, that's how I'm interpreting https://prometheus.io/docs/concepts/metric_types/#histogram.

A histogram that doesn't track any buckets and a summary that doesn't track any quartiles look the same to me.

Additionally, the python client [doesn't support tracking quantiles](https://github.com/prometheus/client_python#summary).

**Comment by DMRobertson** [comment]
Action for this issue, then:
- use a summary instead of a histogram. This should track 8x (17/2) less data per `desc`.

If metrics are still eating up space in the future, we could
- Consider reducing the number of buckets on other histograms, or convert them to summaries
- Gather together related queries under the same `desc`.

**Comment by erikjohnston** [comment]
Summaries have the large downside that you can't aggregate with them, so I'm not generally keen on us using them unless we have a very specific use case in mind.

I think the other two options here are:
1. Drop the histograms entirely and just use counters (note I don't think the dashboards even expose the histogram metrics)
2. Add a flag that we can hide high-cardinality metrics behind, so that we can disable them for people running large fleets of hosts. Ideally we'd make this a config option that we could easily enable/disable (in the same way we do for debug vs info logs)

**Comment by DMRobertson** [comment]
Right, but

- The Python client for prometheus doesn't provide quantiles: we'd literally only be using it for the `_sum` and `_count` counters it provides
- My understanding: you _can_ ask prometheus to merge together quantiles, it's just that they wont' be statistically meaningful.

**Comment by erikjohnston** [comment]
> The Python client for prometheus doesn't provide quantiles: we'd literally only be using it for the `_sum` and `_count` counters it provides

Ugh, right, I guess that is an easy hack to just keep the useful bits. But it'll suck if they ever decide to actually properly implement summaries.

> * My understanding: you _can_ ask prometheus to merge together quantiles, it's just that they wont' be statistically meaningful.

Well yeah, but there's not much point in doing so if you're going to get dodgy answers out.

**Comment by richvdh** [comment]
> > The Python client for prometheus doesn't provide quantiles: we'd literally only be using it for the `_sum` and `_count` counters it provides
> 
> Ugh, right, I guess that is an easy hack to just keep the useful bits. But it'll suck if they ever decide to actually properly implement summaries.

sorry, if our goal is just to get `_sum` and `_count` metrics, why don't we just use a pair of `Counters`, like we do with all other metrics of this kind?

**Comment by DMRobertson** [comment]
That's fair. I can make it two counters. (I only mention summary based on what E said in https://github.com/matrix-org/synapse/pull/11124#issuecomment-946858490)
