### ISSUE TITLE
Addressbook and carddav?

### ISSUE THREAD

**Issue by Thatoo** [matrix-org/synapse#11100]
**Description:**

If Matrix is not only bridged to emails but also to SIP (https://github.com/alangecker/matrix-appservice-pstn), we'll soon be able to use only matrix to communicate with everybody.
In that case, we'll need a tool to manage our contact within matrix client, a kind of address book (first and last name, tel, email, address and matrix ID of course etc....) and matrix clients will need to sync between other matrix client we own on devices and be able to sync with cloud and email app thanks to carddav I guess.

Should synapse integrate a carddav sync system to help matrix client apps to get/retrieve/manage contacts info.

**Comment by koen81** [comment]
Perhaps an integration with Etesync: https://www.etesync.com

**Comment by anoadragon453** [comment]
Before such a system could be implemented in Synapse, it would need to be designed at the protocol level (please file such issues at https://github.com/matrix-org/matrix-spec/issues). Such a design would materialise in the form of [a Matrix Spec Change](https://spec.matrix.org/proposals).

It looks like there may be an issue in that repo that covers this use case: https://github.com/matrix-org/matrix-spec/issues/741. In which case, please direct future discussion there. Thanks!
