### ISSUE TITLE
Hierarchy pagination is limited to 50 items per space

### ISSUE THREAD

**Issue by marcel-klasse** [matrix-org/synapse#11134]
`_matrix/client/unstable/org.matrix.msc2946/rooms/{roomId}/hierarchy` returns a next_batch string for spaces with more than 50 children as expected.
Pparsing the pagination token then only returns 11 rooms in my case, even though there should be much more. The Space in question has 135 space children.
Different spaces return different seemingly random numbers after the second call, but never the actual number.

**To Reproduce**

- call `_matrix/client/unstable/org.matrix.msc2946/rooms({roomId}/hierarchy` for a space with more than 50 children, ideally more than 100

- repeat the call and parse the next_batch string

- wrong number of spaces are returned

**Expected behavior**

- return actual number of spaces and if >50 another next_batch string

tested with v1.43.0

**Comment by squahtx** [comment]
Is the total number of rooms returned for the same space always consistent or does it differ between pagination attempts? Are the same subset of rooms returned every time?

What's the structure of the space with 135 children? ie. how many rooms and subspaces are there in each subspace?

**Comment by squahtx** [comment]
I suspect what's happening here is that only the first 50 children of each subspace are being returned.
@marcel-klasse does this line up with what you're seeing?

**Comment by zv1n** [comment]
I'm seeing this exact issue when trying to migrate a list of rooms from another service over to a matrix server space.

The issue appears to be that the 50 room limit is hard coded [on line 52 in `handlers/room_summary.py`](https://github.com/matrix-org/synapse/blob/1035663833a76196c3e3ba425fd6500c5420bbe2/synapse/handlers/room_summary.py#L52) with the request cap limiting logic appearing [on line 653 in `handlers/room_summary.py`](https://github.com/matrix-org/synapse/blob/1035663833a76196c3e3ba425fd6500c5420bbe2/synapse/handlers/room_summary.py#L653).

The limiting logic appears to come in from PR `Federation API for Space summary` (#9652) where the `max_children` check against `MAX_ROOMS_PER_SPACE` is first introduced into `_summarize_local_room`.

I've tested this on a local test VM. When I set this variable (`MAX_ROOMS_PER_SPACE`) to 100, it works as expected (I have 90 rooms and got 90 rooms).

The easiest solution would seem to be expose this as a configuration variable so individual servers can override the limit as needed, but I figured I'd drop my research in for the synapse team to consider.

Thanks!

**Comment by clokep** [comment]
I've reworded the issue since it isn't really broken, but working as designed. Part of the problem with this code right now is that it is trying to support both the legacy `/spaces` API and the newer `/hierarchy` API so it gets a bit messy. We could likely up the limit of 50 higher, but it likely makes more sense to ensure we can handle arbitrary limits. I would need to look deeper into the code to see how easy that is.
