### ISSUE TITLE
Replace use of `getClientIP` with `getClientAddress`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#11142]
Running unit tests I noticed lots of deprecation warnings:

```
DeprecationWarning: twisted.web.http.Request.getClientIP was deprecated in Twisted 18.4.0; please use getClientAddress instead
  tags.PEER_HOST_IPV6: request.getClientIP(),
```

We are using Twisted >= 18.9:

https://github.com/matrix-org/synapse/blob/40f619eaa54d2391deccec473fc0f655c379e766/synapse/python_dependencies.py#L64

So it should be safe to use the nondeprecated alternative.

The difference [seems to be](https://twistedmatrix.com/documents/21.2.0/api/twisted.web.http.Request.html#getClientIP) getClientIp returns a `str` whereas `getClientAddress` returns an `IAddress`. The documentation says:

> Callers must check the type of the returned address.

which is a bit of a faff. It's probably safe to assume that every where we call it we either get an `IPv4Address` or `IPv6Address`, both of which have a `host` attribute which is probably what we want. I think this needs a little more thought to convince ourselves that's right. But once we do that I'm pretty sure fixing these up will be routine.

**Comment by clokep** [comment]
I seem to have a branch on my computer which does this which I have no memory of?
