### ISSUE TITLE
Some device signatures are missing when doing key/query other federation

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/synapse#11159]
Please refer to this rageshake for full details: https://github.com/matrix-org/element-web-rageshakes/issues/5739

From matrix.org, when doing key/query on a user we can see 2 signatures for the device (device signature and SSK signature)
But when doing from another server the SSK signature is missing

** IMPACT **
=> the user device appears as unverified from federation (red shiel on user and rooms)

**Comment by richvdh** [comment]
we believe this has likely been fixed by #11234. There may be other causes of the same symptoms, however, so please reopen if this is seen again once Synapse v1.47.0 has rolled out.
