### ISSUE TITLE
Synapse uses an unstable prefix for `thirdparty` application service requests

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#11158]
The appservice code has an `APP_SERVICE_PREFIX` constant:

https://github.com/matrix-org/synapse/blob/bf72d10dbf506f5ea486d67094b6003947d38fb7/synapse/appservice/api.py#L52

Which it then uses for any `.../thirdparty/...` request:

https://github.com/matrix-org/synapse/blob/bf72d10dbf506f5ea486d67094b6003947d38fb7/synapse/appservice/api.py#L137-L142

https://github.com/matrix-org/synapse/blob/bf72d10dbf506f5ea486d67094b6003947d38fb7/synapse/appservice/api.py#L172-L176

However, [the spec](https://matrix.org/docs/spec/application_service/r0.1.2) says that these endpoints should have the prefix `/_matrix/app/v1`, not `/_matrix/app/unstable`. This means that if an application service correctly implements the spec, Synapse will 404 when trying to contact it on these endpoints (when e.g. looking up which third-party protocol an application service uses).

**Comment by S7evinK** [comment]
Stumbled over this while trying to update Sytest - https://github.com/matrix-org/sytest/pull/1310

**Comment by DMRobertson** [comment]
We should Just Do This.
