### ISSUE TITLE
Event rejected by dendrite breaks federation with that server

### ISSUE THREAD

**Issue by MayeulC** [matrix-org/synapse#11160]
### Description

This issue is linked to https://github.com/matrix-org/dendrite/issues/1882

Dendrite rejects an event as invalid. It seems that it will also reject all subsequent events in that room.

That's fair, and a dendrite issue. However, synapse's per-server federation queue gets stuck in trying to send these events again and again, which causes federation between these servers to break.

Possible solution would be to rotate events in that federation queue, per-room, especially if rejected.

I am not sure what rejection mechanism is in place. The spec [says](https://matrix.org/docs/spec/server_server/r0.1.4#rejection) that the transaction should not be responded with an error response, so maybe that cycling should be attempted by default?

Note that I could be completely misdirected on that one. Please tell me so if that's the case.

### Steps to reproduce

1. On a synapse server, have someone gain PL > 100 as part of the room creation
2. Invite a dendrite user in that room
3. Observe how the federation between both servers melts down: encryption keys are not forwarded, communication is only possible trough a third party server in the same room.

### Version information

- **Homeserver**: mayeul.net 

- **Version**: 1.42.0

- **Install method**: yunohost

- **Platform**: yunohost (debian bare metal)

#### Dendrite:
```
dentrite | time="2021-08-07T15:48:50.089392580Z" level=info msg="received data from client API server" func="onMessage\n\t" file=" [clientapi.go:89]" room_id="" type=im.vector.setting.breadcrumbs
dentrite | time="2021-08-07T15:48:52.933145593Z" level=info msg="Received transaction \"1628342442615\" from \"$BRIDGESERVER$.tld\" containing 0 PDUs, 1 EDUs" func="Send\n\t" file=" [send.go:206]" req.id=NBSUGY4uu24v req.method=PUT req.path=/_matrix/federation/v1/send/1628342442615
dentrite | time="2021-08-07T15:48:52.944073619Z" level=info msg="Checking event signatures for 14 events of room state" func="Check\n\t" file=" [federationtypes.go:489]" context=missing
dentrite | time="2021-08-07T15:48:52.974127673Z" level=error msg="Event \"$gdzUf8gGUxP3vXlGDTcxRL1UyLISPVW-D8dr5qSKbAc\" is not allowed by its auth events" func="Check\n\t" file=" [federationtypes.go:518]" error="gomatrixserverlib: event with ID \"$gdzUf8gGUxP3vXlGDTcxRL1UyLISPVW-D8dr5qSKbAc\" is not allowed by its auth_events: eventauth: sender with level 100 is not allowed change user level from 100 to 9001 because the new level is above the level of the sender"
dentrite | time="2021-08-07T15:48:52.974234831Z" level=error msg="Event \"$gdzUf8gGUxP3vXlGDTcxRL1UyLISPVW-D8dr5qSKbAc\" is not allowed by its auth events" func="Check\n\t" file=" [federationtypes.go:518]" error="gomatrixserverlib: event with ID \"$gdzUf8gGUxP3vXlGDTcxRL1UyLISPVW-D8dr5qSKbAc\" is not allowed by its auth_events: eventauth: sender with level 100 is not allowed change user level from 100 to 9001 because the new level is above the level of the sender"
dentrite | time="2021-08-07T15:48:52.974483708Z" level=warning msg="Discarding 1 auth/state event(s) due to invalid signatures" func="Check\n\t" file=" [federationtypes.go:526]" context=missing
dentrite | time="2021-08-07T15:48:53.183057018Z" level=error msg="helpers.CheckAuthEvents failed for event, rejecting event" func="processRoomEvent\n\t" file=" [input_events.go:106]" auth_event_ids="[$BWTXyDe2mX149rgVnZ2jaIQX3T27uNgJfp-_daqsFYw $pixruZKarWEuUOcWtQ-CVJEk_-qGdXLoxBxHU_c9cqk $gdzUf8gGUxP3vXlGDTcxRL1UyLISPVW-D8dr5qSKbAc]" error="db.StateEntriesForEventIDs: storage: state event IDs missing from the database (2 != 3)" event_id="$ntLpjV-wGLTitM0oKA40FKm1OJgee_TaT13XRW3TolA"
dentrite | time="2021-08-07T15:48:53.230620706Z" level=error msg="helpers.CheckAuthEvents failed for event, rejecting event" func="processRoomEvent\n\t" file=" [input_events.go:106]" auth_event_ids="[$BWTXyDe2mX149rgVnZ2jaIQX3T27uNgJfp-_daqsFYw $pixruZKarWEuUOcWtQ-CVJEk_-qGdXLoxBxHU_c9cqk $gdzUf8gGUxP3vXlGDTcxRL1UyLISPVW-D8dr5qSKbAc]" error="db.StateEntriesForEventIDs: storage: state event IDs missing from the database (2 != 3)" event_id="$grlSz6tZ0IjRv7qpo4AuSwdNSNzEKLPJqa78IUjbofc"
```

Synapse (much more recent logs):

```
synapse.federation.sender.per_destination_queue - 354 - WARNING - federation_transaction_transmission_loop-21109482- TX [dendrite.example.com] Failed to send transaction: Failed to send request: TimeoutError: User timeout caused connection failure.
synapse.federation.federation_server - 249 - WARNING - PUT-6166836- Received another txn 1634816968887-13 from dendrite.example.com while still processing 1634816968846-13
synapse.federation.federation_server - 249 - WARNING - PUT-6168829- Received another txn 1634817506390-27 from dendrite.example.com while still processing 1634817502881-27
synapse.federation.federation_server - 249 - WARNING - PUT-6168830- Received another txn 1634817506867-27 from dendrite.example.com while still processing 1634817502881-27

```

**Comment by reivilibre** [comment]
Thanks for including your logs. I notice a lot of timeouts when connecting to dendrite.example.org.

I got a little bit distracted by these log entries from March (maybe send a shorter log file next time? :)):
```
2021-03-30 08:38:12,496 - synapse.http.federation.well_known_resolver - 191 - INFO - federation_transaction_transmission_loop-11158951- Response from .well-known: {'m.server': 'matrix.dendrite.example.com:443'}
```
though it's followed up by a DNS lookup problem:
```
2021-03-30 08:40:26,722 - synapse.http.federation.matrix_federation_agent - 290 - INFO - federation_transaction_transmission_loop-11158951- Failed to connect to matrix.dendrite.example.com:443: DNS lookup failed: Couldn't find the hostname 'matrix.dendrite.example.com'.
```

More recently, I see the following:
```
2021-10-05 21:47:39,963 - synapse.http.federation.well_known_resolver - 253 - INFO - federation_transaction_transmission_loop-6725332- Fetching https://dendrite.example.com/.well-known/matrix/server
2021-10-05 21:47:46,416 - synapse.http.federation.well_known_resolver - 197 - INFO - federation_transaction_transmission_loop-6725332- Error parsing well-known for b'dendrite.example.com': Non-200 response 404
2021-10-05 21:48:20,801 - synapse.http.federation.matrix_federation_agent - 362 - INFO - federation_transaction_transmission_loop-6725332- Failed to connect to matrix.dendrite.example.com:8448: User timeout caused connection failure.
```
It looks as though the homeserver has changed from `.well-known` delegation to SRV record delegation (and to port 8448): that strikes me as odd, since I wouldn't expect admins to be moving away from port 443 to port 8448 (since use of port 8448 has largely been a pain).
(Perhaps the SRV record always existed but `.well-known` was working back in March and so the SRV record was being ignored?)

In any case, this seems not to be an issue caused by a rejected event, but by persistent errors in connection.
To my understanding, event rejection will result in a 200 OK response that tells the sending homeserver which events were requested — the homeserver doesn't just drop off the network (this is as Erik mentioned above). :)

Since you've redacted the server name, I can't look at the situation with the DNS and well-known records myself (if you'd be happy sending the server name in a PM to https://matrix.to/#/@reivilibre.element:librepush.net then I am happy to at least have a look).

**Comment by MayeulC** [comment]
Thanks a lot for looking at the logs!

I'm really sorry to have taken some of your time with that issue, we solved it independently yesterday. It is exactly as you say:

A `.well-known` record was previously working, then it suddenly stopped working, and a faulty SRV record was there the whole time.

I've also noticed these `.well-known` entries in the logs, and asked the homeserver owner to fix the record. Connectivity was restored a bit after that was done ~30 hours ago (I see your message is 22 hours old). I'm also going to ask for the `SRV` records to be removed.

**I am still puzzled by the fact that it was federating with matrix.org despite the broken `.well-known` and `SRV` records.**

I redacted the server name due to concerns from its owner, though if you are still interested I can ask them to share it privately.

I also removed the offending appservice a week ago, pending packaging improvements. I'll see if the situation improves when I restore that.

**Comment by erikjohnston** [comment]
> **I am still puzzled by the fact that it was federating with matrix.org despite the broken `.well-known` and `SRV` records.**

It's possible that matrix.org had an open HTTP connection the entire time, and so didn't need to requery `.well-known` and `SRV` records? :shrug:

**Comment by reivilibre** [comment]
Glad it got sorted! :)

**Comment by MayeulC** [comment]
> > **I am still puzzled by the fact that it was federating with matrix.org despite the broken `.well-known` and `SRV` records.**
> 
> It's possible that matrix.org had an open HTTP connection the entire time, and so didn't need to requery `.well-known` and `SRV` records? shrug

For multiple *months*? Given that the other server has about one user? Possible, but I consider it unlikely, especially as the other server had some downtime.

I would have to ask what was the previous configuration, but maybe matrix.org accepted that one (although unlikely, since I'm using synapse too).

Anyway, really sorry for the noise, but I'm glad this was solved too :)
