### ISSUE TITLE
Synapse does enormous expensive queries

### ISSUE THREAD

**Issue by Heidistein** [matrix-org/synapse#11184]
### Description

I have upgraded my OS from fedora 33 to 34, synapse is always on the latest version per auto-updates. Since then after one or two minutes the complete server hangs (on postgres doing IO). 8 cores, 8GB RAM. After four days it is not recovered, requests timeout, server is not useable.

### Steps to reproduce

- run a server for years
- upgrade to fedora34 (I dont see how this is related)
- no profit

### Version information

matrix-synapse-1.45.1-1.fc34.5.noarch from obs.infoserver.lv

Running on a VM, 8 cores, 8GB ram.
When I ask postgres the F it its doing, its running 10 times the same query, with a hidious expensive sort:

```
synapse=# explain WITH RECURSIVE state(state_group) AS ( VALUES(285458::bigint) UNION ALL SELECT prev_state_group FROM state_group_edges e, state s WHERE s.state_group = e.state_group ) SELECT DISTINCT ON (type, state_key) type, state_key, event_id FROM state_groups_state WHERE state_group IN ( SELECT state_group FROM state ) ORDER BY type, state_key, state_group DESC;
                                                  QUERY PLAN
--------------------------------------------------------------------------------------------------------------
 Unique  (cost=37421005.02..38175030.12 rows=40000 width=104)
   CTE state
     ->  Recursive Union  (cost=0.00..59933.02 rows=126231 width=8)
           ->  Result  (cost=0.00..0.01 rows=1 width=8)
           ->  Hash Join  (cost=0.33..5740.84 rows=12623 width=8)
                 Hash Cond: (e.state_group = s.state_group)
                 ->  Seq Scan on state_group_edges e  (cost=0.00..4667.57 rows=252457 width=16)
                 ->  Hash  (cost=0.20..0.20 rows=10 width=8)
                       ->  WorkTable Scan on state s  (cost=0.00..0.20 rows=10 width=8)
   ->  Sort  (cost=37361072.00..37612413.70 rows=100536680 width=104)
         Sort Key: state_groups_state.type, state_groups_state.state_key, state_groups_state.state_group DESC
         ->  Hash Join  (cost=2844.70..7503862.43 rows=100536680 width=104)
               Hash Cond: (state_groups_state.state_group = state.state_group)
               ->  Seq Scan on state_groups_state  (cost=0.00..5854729.60 rows=201073360 width=104)
               ->  Hash  (cost=2842.20..2842.20 rows=200 width=8)
                     ->  HashAggregate  (cost=2840.20..2842.20 rows=200 width=8)
                           Group Key: state.state_group
                           ->  CTE Scan on state  (cost=0.00..2524.62 rows=126231 width=8)
(18 rows)
```

**Comment by w3bb** [comment]
Dealing with a similar problem, after upgrading today there's been a ton of high CPU usage SELECT requests in htop from it.

**Comment by Heidistein** [comment]
Hi!
I did an `analyze` on all tables. That solved it.
For absolute sureness I did a `vacuum full` thereafter (this is slow and disruptive), concluding with a reindex and another analyze.

On October 31, 2021 9:10:51 AM GMT+01:00, welt ***@***.***> wrote:
>Dealing with a similar problem, after upgrading today there's been a ton of high CPU usage SELECT requests in htop from it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matrix-org/synapse/issues/11184#issuecomment-955656097
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by w3bb** [comment]
I've done that already and it didn't help.

**Comment by w3bb** [comment]
Okay so the problem I'm seeing is during a sync. I realised that when my phone attempts to sync that's when the CPU skyrockets. After doing eight million different combinations of reindexing and vacuuming and analyizing it seems to be better, but now it just isn't syncing.

**Comment by w3bb** [comment]
It was because I forgot I turned down the maximum workers to a tiny amount, at its normal amount it's at 100% CPU

**Comment by Heidistein** [comment]
For support I guess you better try joining the synapse admins channels (perhaps with different server), for a bug report best if you open a new one, find out the offending queries plus explain plan, etcetera.
After being down for 4 days it took several hours for me to reach normality. 

On October 31, 2021 10:05:41 AM GMT+01:00, welt ***@***.***> wrote:
>Okay so the problem I'm seeing is during a sync. I realised that when my phone attempts to sync that's when the CPU skyrockets. After doing eight million different combinations of reindexing and vacuuming and analyizing it seems to be better, but now it just isn't syncing.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matrix-org/synapse/issues/11184#issuecomment-955662944
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
