### ISSUE TITLE
Captcha web fallback seems to be broken

### ISSUE THREAD

**Issue by krillefear** [matrix-org/synapse#11218]
### Description
I am still trying to figure out why FluffyChat cant register users on Matrix.org and now I think the captcha web fallback is broken. Unfortunately there is no working captcha plugin yet in flutter so I rely on the web fallback. At first it seems to work but after the whole registration workflow is done, the server responses with: "500 - Internal server error".

I now have found the difference. The response after solving the captcha in the web fallback and then send
```json
// ...
"auth": {"session": "abcd"}
```

was:

```json
      "stages": [
        "m.login.recaptcha",
        "m.login.terms",
        "m.login.email.identity"
      ]
    }
  ],
  "params": {
    "m.login.recaptcha": {
      "public_key": "6LcgI54UAAAAABGdGmruw6DdOocFpYVdjYBRe4zb"
    },
    "m.login.terms": {
      "policies": {
        "privacy_policy": {
          "version": "1.0",
          "en": {
            "name": "Terms and Conditions",
            "url": "https://matrix-client.matrix.org/_matrix/consent?v=1.0"
          }
        }
      }
    }
  },
  "completed": [
    "m.login.recaptcha"
  ],
  "error": "Captcha response is required",
  "errcode": "M_CAPTCHA_NEEDED"
}
```

So while m.login.recaptcha is in the list of completed stages, I see an error "Captcha response is required". That's why I think there seems to be something broken with the captcha web fallback.

### Steps to reproduce

- Try to register with captcha web fallback on matrix.org

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org

- **Version**: matrix.org current instance

- **Platform**: matrix.org

**Comment by erikjohnston** [comment]
Can you give the full request paths and time you made the request please? I'm having a hard time tracking down the request in the logs.

**Comment by krillefear** [comment]
Hi there. My assumption was wrong. The sign up workflow failed because of sending threepidcreds inside of an array which was a spec bug. Now everything works and it was actually not related to the captcha fallback. Therefore this can be closed.
