### ISSUE TITLE
Room creations denied by `user_may_create_room` should cause a `M_FORBIDDEN` error to be returned, not `M_UNKNOWN`

### ISSUE THREAD

**Issue by jaller94** [matrix-org/synapse#11245]
**Description:**
0. Have a Synapse module that prevents you from creating a room.
1. Try to create a room.

## Actual
HTTP 403 on `POST /_matrix/client/r0/createRoom`
```json
{
  "errcode":"M_UNKNOWN",
  "error":"You are not permitted to create rooms"
}
```

The UI is unsure what to tell the user, making it seem like this could succeed on retry:
![](https://user-images.githubusercontent.com/10872136/140289978-832ddcae-1b36-4702-a23a-f520935863d7.png)

## Expected
The Matrix errcode `M_FORBIDDEN` would be more specific and fits the error message.

**Comment by babolivier** [comment]
Slightly related (since it's around error handling): https://github.com/matrix-org/synapse/issues/11031

**Comment by babolivier** [comment]
@jaller94 

>  Have a Synapse module that prevents you from creating a room.

There are a few module callbacks that prevent you from creating a room, could you be more specific here please?

**Comment by reivilibre** [comment]
iirc I saw this behaviour when working on https://github.com/matrix-org/synapse-user-restrictions/ with the `user_may_create_room` spam checker callback.

**Comment by babolivier** [comment]
As per DM, the module uses `user_may_create_room` (and denies room creation by returning `False` upon getting called on that callback).

**Comment by lukasdenk** [comment]
I'll try to fix it :smiley:

**Comment by lukasdenk** [comment]
@jaller94 I fixed the issue in the above PR. Could you please close the issue?

**Comment by DMRobertson** [comment]
@lukasdenk For what it's worth, prefer linking the PR and the issue together as described [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)---that'll automatically close the issue if the PR is merged.
