### ISSUE TITLE
Estimate the impact of MSC2775 (lazy-loading over federation) on a variety of rooms

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#11250]

**Comment by richvdh** [comment]
Initial indications for time for `/join` to complete:

* `#matrix:matrix.org` reduces from 745s (12.5 mins) to 125s (2 mins)
* `#synapse:matrix.org` reduces from 175s (3 mins) to 30s
* a small test room (though with a lengthy auth chain) reduces from 50s to 20s

This does nothing to estimate the time before you can see the room in your client (typically: once `/sync` includes it), nor the time before you can interact with it, but it's a start.
