### ISSUE TITLE
Add admin API for pausing background updates

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#11259]
If a background update is causing issues it is useful to be able to temporarily pause running of the updates via an admin API.

Open question: should this only pause the BG updates until next restart? We want to avoid the situation where the BG updates get paused and then forgotten about, as that would be a massive footgun

**Comment by richvdh** [comment]
other things it would be useful for this API to do:
 * give a status report on the current bg update situation (raw dump of the background_updates table, contents of the `_background_update_performance` dict)
 * possibly, mess about with the bg update timing params
