### ISSUE TITLE
Documentation uses the term "Home Server" in multiple places

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#11264]
The protocol decided long ago that it was "homeserver" (one word). A find & replace all should fix the majority of instances. 

Noticed in the TURN docs.

**Comment by Ashwin-exe** [comment]
Hey!! @turt2live I'm new to open source, if anyone not working on this issue can you assignee me?

**Comment by anoadragon453** [comment]
@Ashwin-exe you have been assigned!

If you need any help with Synapse development, feel free to ask questions in [#synapse-dev:matrix.org](https://matrix.to/#/#synapse-dev:matrix.org)!
