### ISSUE TITLE
Add config settings for background update parameters

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#11260]
It is useful to be able to slow down or speed up background updates, so we should make the targets configurable. Including: target duration, sleep times, min batch size and default batch size.

**Comment by richvdh** [comment]
see  also https://github.com/matrix-org/synapse/issues/11401#issuecomment-975980466: I think we should reduce the default for `MINIMUM_BACKGROUND_BATCH_SIZE` to 1.

**Comment by DMRobertson** [comment]
A module exists for this which makes life easier for EMS, but we still think this is worth doing.

**Comment by H-Shay** [comment]
Fixed by  #11980.
