### ISSUE TITLE
OIDC signin: skip the "Continue to your account" page

### ISSUE THREAD

**Issue by azmeuk** [matrix-org/synapse#11290]
Hi. OIDC login works like a charm. Thank you for this hard work.

I would like the "Continue to your account" page to be automatically skipped on a first login, as it adds up to the consent page of the identity provider with a very similar message. I think this is not clear for the end users what is going on on this screen.

![Screenshot 2021-11-10 at 10-36-50 Continue to your account](https://user-images.githubusercontent.com/60163/141088407-eafbbca4-f290-44c0-acc9-956e09ea2215.png)

I suggest implementing a parameter to skip this screen, turned off by default.

I volunteer to provide a patch if this is OK for you.

What do you think?

**Comment by anoadragon453** [comment]
Hi @azmeuk. The config option you are describing is already available through `sso.client_whitelist` in Synapse's config file. The sample config file contains some documentation on how it works:

https://github.com/matrix-org/synapse/blob/86a497efaa60cf0e456103724c369e5172ea5485/docs/sample_config.yaml#L1974-L1991

If you add the address of your client to the whitelist, then this warning page should not appear.

Out of interest, is there anywhere in the documentation we could improve to make this option more discoverable?

Thanks!

**Comment by azmeuk** [comment]
Thank you. This is exactly the option I needed.
I am not sure where in the documentation should this option be mentionned, but `client_whitelist` only appears in the sample configuration file, so I suppose there is no documentation paragraph about it:

![Screenshot 2021-11-10 at 13-55-00 Welcome and Overview - Synapse](https://user-images.githubusercontent.com/60163/141116822-d877d5e3-d466-4a83-864b-d53e8afd386e.png)

Maybe somewhere [on this page](https://matrix-org.github.io/synapse/latest/openid.html) is a good idea?

**Comment by anoadragon453** [comment]
@azmeuk Glad to hear, and yes this would be good to include on the documentation website. Note that `sso.client_whitelist` actually works for all Single Sign-On authentication methods, not just OIDC. So it should probably live on a generic SSO docs page -- which has yet to be written!

I've created an issue to track this specific addition (https://github.com/matrix-org/synapse/issues/11294), and will now close this one. Thanks!
