### ISSUE TITLE
synapse on `matrix.org` overrides the default templates, making things worse

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11295]
the `matrix.org` deployment of synapse has its own copies of many of the templates, and, as a general rule, they are *worse* than the defaults.

Apart from making things uglier, it also tends to mean people consider the verification emails as spam.

We should check how the overrides differ from the defaults, and remove the overrides where possible.

**Comment by reivilibre** [comment]
E-mail push notifications on matrix.org are Riot-branded, too. This is worse than being Matrix.org branded or Element branded, since it's not a brand that a user would expect to see having access to their messages anymore.

**Comment by richvdh** [comment]
It appears this is no longer the case.
