### ISSUE TITLE
Remove unnecessary use of jquery on the recaptcha page

### ISSUE THREAD

**Issue by dkasak** [matrix-org/synapse#11308]
Currently we use jquery for some very rudimentary operations on the recaptcha page. https://github.com/matrix-org/synapse/blob/73cbb284b932c8b769e8a42ccda0f239a0fb1a71/synapse/res/templates/recaptcha.html#L8-L13

This seems like overkill since they could easily be replaced by `document.getElementById` or `document.querySelector`.

**Comment by Jennyfriel** [comment]
Good day,

 How i submit my registration form??

**Comment by ankur12-1610** [comment]
I'll work on it!

**Comment by GAURAV1-ui** [comment]
Hey, I would love to solve this issue.

**Comment by DMRobertson** [comment]
To do this:

1. Remove the jquery script tags quoted above.
2. Replace the script with

   ```js
   function captchaDone() {
        document.getElementById('registrationForm').submit(); 
   } 
   ```
   assuming that jquery's .submit method is a wrapper around [HTMLFormElement.submit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit). 
3. Ideally: test this works---not sure how that's done though.

**Comment by JeyRathnam** [comment]
Is this still needed? If so, can I work on it?

**Comment by squahtx** [comment]
> Is this still needed? If so, can I work on it?

Yes, feel free to work on it and open a PR.
