### ISSUE TITLE
Docs: Right-hand side navbar doesn't display fully with too many items

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#11338]
e.g. on https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html

![image](https://user-images.githubusercontent.com/5547783/141752948-ebbea056-2b07-4a00-a771-50ed5d81d3f2.png)

The last item should say "Check username availability", but it's hidden under the bottom of the page.

**Comment by MadLittleMods** [comment]
Seems to be fixed now:

![](https://user-images.githubusercontent.com/558581/206564784-6f000437-cbeb-45c9-9ee6-e0176ac0701c.png)
