### ISSUE TITLE
Admin API feature to un-shadowban

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/synapse#11343]
**Description:**

https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#shadow-banning-users appears to only be able to apply the shadow ban, not remove it. And it doesn't appear to be a toggle?

So, the Admin API should get a way to un-shadowban a user.

**Comment by clokep** [comment]
Could probably add a `DELETE` to the same endpoint to unset it.
