### ISSUE TITLE
ldap account creation fails for users with no email

### ISSUE THREAD

**Issue by chrwei** [matrix-org/synapse#1135]
when letting ldap auth create a user, if the user doens't have an email attribute it results in a rather generic "Missing JSON keys" error.

to fix I edited synapse/handlers/auth.py and changed `mail = attrs[self.ldap_attributes['mail']][0]` to 

```
try:
    mail = attrs[self.ldap_attributes['mail']][0]
except KeyError:
    mail = ""
    pass

```

**Comment by kyrias** [comment]
LDAP support was moved out of synapse, so I migrated this issue over to that repo instead.
