### ISSUE TITLE
scripts-dev/complement.sh broke after 13f084e

### ISSUE THREAD

**Issue by Bubu** [matrix-org/synapse#11362]
### Description

It seems like  13f084e broke the complement.sh script included here, it doesn't find any tests to run anymore:

```
Successfully built 41beaabb3d44
Successfully tagged complement-synapse:latest
no Go files in /home/bubu/projects/oss/synapse/complement-master
```

When manually reverting the changes to that file it works again (the actual tests fail somewhere down the line, but that another matter).

### Steps to reproduce

- run `./scripts-dev/complement.sh` from an up-to-date synapse checkout

**Comment by clokep** [comment]
I need this for #10946 so I'm going to look at it.

**Comment by clokep** [comment]
Thanks for the report!
