### ISSUE TITLE
./scripts-dev/complement.sh and GHA complement job diverged

### ISSUE THREAD

**Issue by Bubu** [matrix-org/synapse#11363]
It seems like https://github.com/matrix-org/synapse/commit/684d19a11c3b93c9dd5fb90f43d38aa7e8c6005f added the `msc2716` tag to the complement.sh script but it seems that was never added to the GHA workflow here: https://github.com/matrix-org/synapse/blob/develop/.github/workflows/tests.yml#L377

Consequently that (those?) tests are now failing on develop.

**Comment by clokep** [comment]
@MadLittleMods Do you know if those tests should be passing or not?

**Comment by MadLittleMods** [comment]
I think they would but it looks like the Complement tests are using the `org.matrix.msc2716v4` which hasn't merged to Synapse yet (potentially merged in https://github.com/matrix-org/synapse/pull/11243 or https://github.com/matrix-org/synapse/pull/9445 or not merged at all https://github.com/matrix-org/synapse/pull/11243#discussion_r750816377). Feel free to remove, it's always a juggle trying to add it back when developing a new MSC though.

**Comment by clokep** [comment]
> I don't think the tests are running in CI (GHA) because the command is separate from `complement.sh` though?

Right, but for people developing against Synapse it is frequent to manually run complement commands with this script, so it is best to keep it in a state where it is expected to pass.

**Comment by DMRobertson** [comment]
Is this fixed by https://github.com/matrix-org/synapse/pull/11368?

**Comment by clokep** [comment]
> Is this fixed by #11368

No, I'll do a PR to fix it.
