### ISSUE TITLE
HTTP error 404 when requestToken is called

### ISSUE THREAD

**Issue by david-dumas** [matrix-org/synapse#1137]
I just installed synapse on Ubuntu 16.04 LTS (AWS hosted), when a user is trying to register or reset his password I get the following error:

`2016-09-22 14:50:46,557 - synapse.http.client - 93 - INFO - POST-161- Received response to  POST https://matrix.effilab-local.com/_matrix/identity/api/v1/validate/email/requestToken: 404`

I might have missed something while configuring. I am using postfix as relay.

**Comment by richvdh** [comment]
Are you trying to use your own server as an identity server? If so, you need https://github.com/matrix-org/sydent rather than synapse. Suggest asking for help in https://matrix.to/#/#matrix:matrix.org rather than here.
