### ISSUE TITLE
Docker `generate` has started generating files as `--user`, regardless of `UID`/`GID`

### ISSUE THREAD

**Issue by Yoric** [matrix-org/synapse#11385]
### Description

With previous versions of Synapse, the following command generated a default homeserver.yaml in `/tmp/z` belonging to the current user. This is critical for using Synapse in CI.

```sh
$ mkdir /tmp/z
$ docker run -it --env UID=`id -u` --env GID=`id -g ` --rm
   --mount type=bind,src=synapse-data,dst=/data,src=/tmp/z
   -e SYNAPSE_SERVER_NAME=my.matrix.host
   -e SYNAPSE_REPORT_STATS=yes
   matrixdotorg/synapse:latest generate
$ ls -lah /tmp/z/homeserver.yaml
-rw-r--r-- 1 yoric yoric 91K nov.  18 10:12 z/homeserver.yaml
```

With 1.47.0, the files are created as `root`:

```sh
$ mkdir /tmp/z
$ docker run -it --env UID=`id -u` --env GID=`id -g ` --rm
   --mount type=bind,src=synapse-data,dst=/data,src=/tmp/z
   -e SYNAPSE_SERVER_NAME=my.matrix.host
   -e SYNAPSE_REPORT_STATS=yes
   matrixdotorg/synapse:latest generate
$ ls -lah /tmp/z/homeserver.yaml
-rw-r--r-- 1 root root 91K nov.  18 10:13 z/homeserver.yaml
```

That's not desirable. In particular, in my case, this entirely breaks my ability to run Synapse for integration tests on modules.

### Regression

I believe that the regression was added in the following patch: https://github.com/matrix-org/synapse/commit/0b99d4c8d219aca3f8a0e4f3542bb67dfc016420#diff-d0e0d1fe01e659a4debf8bf6d66912cfafb1aa1d88537f03686f789af4c94c92 .

**Comment by reivilibre** [comment]
For what it's worth, it seems like it only accidentally worked before: the config file defaults to being placed in the data directory (but could be moved elsewhere) and the data directory happened to be `chown`ed *after* generating the config file — now we `chown` *before*.

It seems like the proper answer here is to `chown` the config file explicitly — should be an easy PR if you have time?

**Comment by reivilibre** [comment]
Oh hm, actually it seems like this was a purposeful change:
> The intention was always that the config files get written as the initial user
(normally root)

**Comment by Yoric** [comment]
> Oh hm, actually it seems like this was a purposeful change:
> 
> > The intention was always that the config files get written as the initial user
> > (normally root)

If it is a purposeful change, I don't see any way to make my scripts work, short of running them in a VM. That... is going to make my life complicated.

**Comment by reivilibre** [comment]
> If it is a purposeful change, I don't see any way to make my scripts work, short of running them in a VM. That... is going to make my life complicated.

I think that's a little dramatic; if there's a real need for an extra `CONFIG_UID` flag or something then I'm sure we can come up with something.

However, what's wrong with running your container not as root?

```bash
$ id
uid=1000(rei) gid=1000(rei) groups=1000(rei),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),131(lxd),132(sambashare),135(docker)


$ docker run -it --user rei --env UID=`id -u` --env GID=`id -g ` --rm \
   --mount type=bind,src=synapse-data,dst=/data,src=/tmp/z \
   -e SYNAPSE_SERVER_NAME=my.matrix.host \
   -e SYNAPSE_REPORT_STATS=yes \
   matrixdotorg/synapse:latest generate

Setting ownership on /data to 1000:1000
Creating log config /data/my.matrix.host.log.config
Generating config file /data/homeserver.yaml
Generating signing key file /data/my.matrix.host.signing.key
A config file has been generated in '/data/homeserver.yaml' for server name 'my.matrix.host'. Please review this file and customise it to your needs.

$ ls -lah /tmp/z/homeserver.yaml 
Permissions Size User Date Modified    Name
.rw-r--r--   93k rei  2021-11-18 09:45 /tmp/z/homeserver.yaml
 ```

**Comment by Yoric** [comment]
I'll give it a try.

**Comment by Yoric** [comment]
Ok, this seems to work, as long as I remove

```
--env UID=`id -u` --env GID=`id -g ` 
```

which seem to sometimes cause breakage. I'll investigate further once I have a little time.

**Comment by reivilibre** [comment]
Do you know when those two flags cause breakage? As you can see I tried above and the file seemed to be properly owned by my user with the `--user 1000` flag and the UID, GID environment vars.

**Comment by richvdh** [comment]
Yes, this is a deliberate change.

The intention is that you should not need `UID` or `GID`; rather it is better to use `--user`. Using both together will fail unless the `--user` user has permission to `gosu` to `UID` (which is unlikely unless they are the same user, or `--user` is root)

**Comment by reivilibre** [comment]
> which is unlikely unless they are the same user

Aha, that explains why there was no trouble for me.

**Comment by DMRobertson** [comment]
Given that this was intentional I'm gonig to close this. If this is still causing pain down the line, please do re-open.
