### ISSUE TITLE
Official plugin/app for truenas core/scale

### ISSUE THREAD

**Issue by pszypowicz** [matrix-org/synapse#11384]
**Description:**
It would be beneficial for Synapse to be available as an official plugin/app on TrueNAS platform.

As an example, Nextcloud recently announced official support for **TrueNAS** for both **Core** and **Scale** products.
https://www.ixsystems.com/blog/nextcloud-and-truenas-collaborate-to-help-you-build-your-own-private-cloud/

What is interesting, it's a free option up to 100 users, and then become a paid model:

> The Nextcloud plugin is free for up to 100 users and directly available for download within TrueNAS. Small businesses and extended families can set up their own private clouds in just a few clicks. For larger schools and organizations with more than 100 users, an Enterprise support option is available starting at $8/month per user with no limits on the storage capacity or compute power per user. With the use of TrueNAS HA systems, these organizations will be able to build high-reliability solutions. TrueCommand can be used to manage distributed infrastructure deployments

Synapse does not have at the moment any officially supported way to have a "on premise" installation which is plugin based (that I'm aware of), there are only option for "cloud" managed deployments. But those 2 scenarios appease 2 different user bases and I think it could be a great starting point for corporations and small business for matrix/synapse.

**Comment by DMRobertson** [comment]
> Synapse does not have at the moment any officially supported way to have a "on premise" installation which is plugin based (that I'm aware of) there are only option for "cloud" managed deployments.

I'm not sure what you mean by "plugin" here. A plugin specific to TrueNAS? I think we'd accept such a thing, but it might be better placed as an external project rather than part of Synapse itself.

It's also worth mentioning [this page](https://matrix.org/docs/projects/server/synapse) on matrix.org, which mentions https://github.com/YunoHost-Apps/synapse_ynh and https://git.cloudron.io/cloudron/synapse-app which I both think facilitate plugin-like self-hosting?

**Comment by pszypowicz** [comment]
Thanks for linking the yuno-host and cloudron as they seem to be a good starters. 

I'm rather thinking of so sort of maintained/blessed by vector option for self host. But you are right, the question is if this is a good place to ask for something like this.

**Comment by clokep** [comment]
Official PyPI packages, Debian packages, and Docker images are provided. Any of those can be used to self-host. We leave other formats to downstream packagers who might wish to re-package Synapse. Unfortunately maintaining different packaging formats is extremely time consuming and the Synapse team is unable to support additional formats at this time!

It would be nice to have a comprehensive list of packages somewhere, but I'm not sure one exists. If there are questions on how to re-package Synapse I'd invite joining #synapse-dev:matrix.org to discuss with us.

**Comment by Core-scale** [comment]
[Core-Scale ](https://www.core-scale.com/
)helps you do just that! Best sourced talents from across the globe are made available at your fingertips.

Thank you for your Post very important
