### ISSUE TITLE
Job Profile for user

### ISSUE THREAD

**Issue by MPTA** [matrix-org/synapse#11404]
hello everybody and kindest thanks to synapse team.
i have my own idea to customize the chat app and that is user can update their job and business profile by job categories and location then other users can find him/her via search box to get help as freelancer . 
it is just an image of my idea, i just want to know how can i get help to make to customize the app.

**Comment by dklimpel** [comment]
See:
- #6737
- #2788

**Comment by DMRobertson** [comment]
Thanks for your idea. I think the links that @dklimpel provides cover it well, but for completeness: I think this would be best part of a generic mechanism to add custom data to a user profile, as discussed at https://github.com/matrix-org/matrix-doc/issues/489. I don't think Synapse is the right place for any discussion.
