### ISSUE TITLE
https://packages.matrix.org/debian is cached over-aggressively

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11412]
Cloudflare is caching files under https://packages.matrix.org/debian for up to 4 hours, causing delays for people trying to update, and errors such as:

```
E: Failed to fetch https://packages.matrix.org/debian/dists/bullseye/main/binary-amd64/Packages.gz  Hash Sum mismatch
```

**Comment by ShadowJonathan** [comment]
> There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

**Comment by dbkr** [comment]
We had similar problems on element fwiw: https://github.com/vector-im/element-web/issues/18901 - fixed by telling it not to cache by default and only cache what we wanted it to.

**Comment by richvdh** [comment]
I've added a `Cache-Control: max-age=60` header for everything under `https://localhost/debian/dists`, which should solve this.
