### ISSUE TITLE
undoable account deactivations

### ISSUE THREAD

**Issue by jesopo** [matrix-org/synapse#11419]
**Description:**

from reading https://github.com/matrix-org/synapse/blob/24b61f379ac1fc740e1b569b85363e2a0411883a/docs/admin_api/user_admin_api.md#deactivate-account deactivations currently function akin to an account deletion. it would be beneficial to offer a way to simply prevent a user logging in until further notice, with an additional endpoint to undo this. semantically I'd rename the current API to "account deletion" and introduce a new system to flag an account as unloginable (deactivated), but you could also just introduce a new endpoint for this functionality called "account freeze" or similar

motivation for such a feature is sometimes you need to react fast to *potential* incidents and stop further actions but you'd hedge your bets if the choices are either "leave the account usable" or "permanently delete the account". this is very much also the case if you're looking in to automated abuse mitigation which will sometimes get the call wrong

**Comment by DMRobertson** [comment]
>  it would be beneficial to offer a way to simply prevent a user logging in until further notice, with an additional endpoint to undo this.

Does passing `deactivate: false` to  https://github.com/matrix-org/synapse/blob/24b61f379ac1fc740e1b569b85363e2a0411883a/docs/admin_api/user_admin_api.md#create-or-modify-account help with this?

**Comment by babolivier** [comment]
While this feature isn't currently implemented in Synapse in the exact way you describe it, you can already do this by writing a Synapse module that leverages these callbacks: https://matrix-org.github.io/synapse/latest/modules/account_validity_callbacks.html

For feature names and semantics, this looks to me like an issue with the Matrix spec, which Synapse implements, so I'd suggest opening an issue on https://github.com/matrix-org/matrix-doc

**Comment by babolivier** [comment]
> Does passing `deactivated: false` to  https://github.com/matrix-org/synapse/blob/24b61f379ac1fc740e1b569b85363e2a0411883a/docs/admin_api/user_admin_api.md#create-or-modify-account help with this?

It doesn't prevent the user from logging in again if you don't deactivate the account, so I don't think it does.

**Comment by Yoric** [comment]
> While this feature isn't currently implemented in Synapse in the exact way you describe it, you can already do this by writing a Synapse module that leverages these callbacks: https://matrix-org.github.io/synapse/latest/modules/account_validity_callbacks.html

Interesting. It feels like we should extend `is_user_expired` to return something a bit broader than a boolean, e.g. a Matrix error, to indicate a variety of cases.

> For feature names and semantics, this looks to me like an issue with the Matrix spec, which Synapse implements, so I'd suggest opening an issue on https://github.com/matrix-org/matrix-doc

Is there any Matrix-level API to deactivate accounts?

**Comment by babolivier** [comment]
> Interesting. It feels like we should extend `is_user_expired` to return something a bit broader than a boolean, e.g. a Matrix error, to indicate a variety of cases.

Not sure, in general we usually want to turn errors raised by modules into generic ones to prevent modules from messing up Synapse's error handling and/or other homeservers and clients (in case they try to eg raise a `SynapseError` with a status code that means something specific in the spec, etc). Though it's probably something we can review on a case by case basis. In this case, the intent seems to be to prevent some users from using their account without deactivating them, which is precisely what account validity callbacks are supposed to be handling.

> Is there any Matrix-level API to deactivate accounts?

Yes: https://spec.matrix.org/latest/client-server-api/#post_matrixclientv3accountdeactivate
