### ISSUE TITLE
Is the PUT /sendToDevice API is allowed on generic worker?

### ISSUE THREAD

**Issue by hyossing** [matrix-org/synapse#11432]
Hello,

Is the PUT /sendToDevice API is allowed on generic worker? The [workers.md](https://github.com/matrix-org/synapse/blob/develop/docs/workers.md) does not describe it.

Best Regards
Hyosung Lim

**Comment by dklimpel** [comment]
See: #9044 and #9047

**Comment by babolivier** [comment]
Hi @hyossing, we don't use GitHub issues for support, please use the [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) room for this.
