### ISSUE TITLE
Add a step to `scripts-dev/release.sh` to create and push a `release-v*` branch to sytest

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#11463]
As part of the quest to automate all the things.

* The branch should be created during rc1.
* and pushed to during rc2+ and a full release.

The format of the branch name matches that of Synapse, e.g `release-v1.47`.

**Comment by deepbluev7** [comment]
It would be great to have the same for complement. We did have some trouble in the past matching up branches.

**Comment by DMRobertson** [comment]
This was done in #12978.
