### ISSUE TITLE
/sync is not bundling aggregations for limited rooms

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#11476]
[MSC2675](https://github.com/matrix-org/matrix-doc/pull/2675) says that `/sync` is one of the APIs which should bundle aggregations:

> `GET /sync`, only for room sections in the response where `limited` field is `true`; this amounts to all rooms in the response if the `since` request parameter was not passed, also known as an initial sync.

Currently it always disables bundled aggregations for this endpoint, see #5220.

We should also double check the other endpoints:

* [x] `GET /rooms/{roomId}/messages` -- [see code](https://github.com/matrix-org/synapse/blob/a265fbd397ae72b2d3ea4c9310591ff1d0f3e05c/synapse/handlers/pagination.py#L545-L558)
* [x] `GET /rooms/{roomId}/context` -- [see code](https://github.com/matrix-org/synapse/blob/a265fbd397ae72b2d3ea4c9310591ff1d0f3e05c/synapse/rest/client/room.py#L709-L723) (note that this doesn't bundle them for state events, unclear if this is "fine" or not)
* [x] `GET /rooms/{roomId}/event/{eventId}` -- [see code](https://github.com/matrix-org/synapse/blob/a265fbd397ae72b2d3ea4c9310591ff1d0f3e05c/synapse/rest/client/room.py#L664-L666)
* [ ] `GET /sync`
* [x] `GET /relations` -- see #11087

**Comment by gsouquet** [comment]
Blocks https://github.com/vector-im/element-web/issues/19588

**Comment by gsouquet** [comment]
From my tests on vector.modular.im it appears that `GET /rooms/{roomId}/event/{eventId}` includes the bundled relationship correctly

**Comment by clokep** [comment]
It looks like we include them in all the other places, minus the state events when calling `context`.

**Comment by clokep** [comment]
Reopening due to #11583.
