### ISSUE TITLE
Synapse selects `"preset": "public_chat"` by default, while it should be "private_chat"

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#11498]
### Description

I noticed this while looking at the spec;

While creating rooms [`/createRooms`](https://spec.matrix.org/v1.1/client-server-api/#post_matrixclientv3createroom) recommends, for a default `"preset"`, to use `"private_chat"`, recommending it should look at `"visibility"`, which defaults to `"private"`.

However, synapse creates public_chat rooms when given no options.

I know that the spec is only saying "should" here, but since Dendrite and Conduit also display this behaviour, it could cause confusion that a "known good" server such as Synapse is going against spec here, creating bugs in software where previously there were none.

### Version information

- **Version**: v1.48.0

- **Install method**: Docker

- **Platform**: Linux

**Comment by reivilibre** [comment]
Even our test helpers say it should be private by default (of course the tests in practice rely on them being public):
```python
            is_public: If True, the `visibility` parameter will be set to
                "public". If False, it will be set to "private". If left
                unspecified, the server will set it to an appropriate default
                (which should be "private" as per the CS spec).
```
