### ISSUE TITLE
/createRoom can return an out-of-spec HTTP 502 bad gateway

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#11504]
Which then CF seems to eat the JSON from and replace with its own HTML content.
The spec only defines 200 and 400 response codes for this endpoint: https://spec.matrix.org/v1.1/client-server-api/#post_matrixclientv3createroom

### Steps to reproduce

1. Call /createRoom with an `{ "invite": ["@foo:bar"] }`
2. Observe a 502 response with a somewhat sane body 
![image](https://user-images.githubusercontent.com/2403652/144634710-0a41320d-76ab-4bee-8845-9cf3627820cd.png)
Unless you're on matrix.org
![image](https://user-images.githubusercontent.com/2403652/144634733-080a1b3c-1c16-402f-b911-db8e033510f5.png)

### Version information

- **Homeserver**: matrix.org

**Comment by richvdh** [comment]
dup #5837
