### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by fsa** [matrix-org/synapse#11509]
Double server behavior when federating with other servers. According to the documentation https://github.com/matrix-org/synapse/blob/master/docs/MSC1711_certificates_FAQ.md#configuring-certificates-for-compatibility-with-synapse-100, when using SRV records, you must use a certificate for the main domain, for example, example.com, even if the server is located on matrix.example.net. At the same time, if you create a .well-known/matrix/server, then now the server will require a matrix.example.net certificate. https://federationtester.matrix.org/ expects exactly this behavior when testing.

All of the suggested customization options have their drawbacks:
1. It may be difficult to obtain a certificate using certbot, since example.com does not indicate a matrix matrix.example.net. When obtaining a certificate, you must contact the administrator of the example.com server or use the API, which the DNS provider may not provide.
2. All traffic to the matrix-synapse has to be routed through the main example server, which is irrational and adds an additional point of failure.
3. Requires intervention in the operation of the server on the example.com domain, which can be administered by another person. In addition, the creation of such a record makes the variant with SRV records in the DNS unnecessary, since hardly anyone is currently using matrix synapse 0.34 or older in 2021.

**Comment by squahtx** [comment]
As far as I can tell, the documentation is accurate. The Synapse server only needs a certificate for one domain and these are the only options when using SRV records.

Please reopen the issue if the documentation is actually incorrect.
