### ISSUE TITLE
Room directory is empty

### ISSUE THREAD

**Issue by alexjg** [matrix-org/synapse#1152]
I have a synapse installation running on Ubuntu 16.04. I installed it from the PPA and I've stuck it behind nginx. Generally everything works but I don't see anything when I search for room directories. I'm able to join rooms fine. Am I missing something?

**Comment by erikjohnston** [comment]
The public room list is local to each server. Synapse supports fetching remote servers' public room lists, but this API is new and hasn't made it into many clients yet. It is available on the latest development version of riot web (https://riot.im/develop/)

**Comment by alexjg** [comment]
Ah that makes sense, development version works fine. Thanks.
