### ISSUE TITLE
Account data isn't deleted upon deactivation

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#11539]
We currently don't delete account data when a user is deactivated. This means we retain SSSS, lists of ignored users, etc, in the database. We probably want to delete them.

**Comment by babolivier** [comment]
We'll also probably want a background update to get rid of all of the account data that's been retained for deactivated accounts.

**Comment by richvdh** [comment]
related: #11072

**Comment by JonasKress** [comment]
@babolivier would it be possible to define 'etc.', so this can go through the enterprise sprint?

Some goes for the doc:
https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#deactivate-account

**Comment by babolivier** [comment]
@JonasKress 

> @babolivier would it be possible to define 'etc.', so this can go through the enterprise sprint?

Not really. Account data (or at least the Matrix concept named "account data") is basically freeform JSON with a few types (such as lists of direct rooms, lists of ignored users, SSSS) defined in the spec but that's not an exhaustive list. Note that deleting different types of account data (or deleting account data for a user as a whole) is the same operation. We don't need to implement a different handling for each type when it comes to deleting or redacting them.

BTW, if you're planning for the PSE sprint, heads up I've already opened a ticket for this on Jira: https://element-io.atlassian.net/browse/PSE-224

> Some goes for the doc:
> https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#deactivate-account

I'm not sure what you mean here, the doc looks to me like it describes very exhaustively what happens upon deactivation. If the doc doesn't say that thing X happens upon deactivation then it means it doesn't happen upon deactivation.

**Comment by anoadragon453** [comment]
We should also decide whether the `erase` parameter guards this.

**Comment by anoadragon453** [comment]
> We should also decide whether the `erase` parameter guards this.

For reference: as implemented, user account data is deleted irrespective of whether `erase` is True or False.
