### ISSUE TITLE
`hash_password` should fail if you don't supply a configuration file

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#11548]
https://github.com/matrix-org/synapse/blob/3b8872299aac25a7e3ee5a9e00564105aa6de237/scripts/hash_password#L52-L56

It seems to have some defaults but I somewhat doubt they are actually useful to anyone who generated their homeserver config 'properly'.
I guess it's too late to make it fail in case the current behaviour *is* useful to someone, but I wish it would at least print a warning.

Bit me just now (well, since last night...) as I needed to reset a LP.net user's password, and come to think of it it's not the first time either!

**Comment by richvdh** [comment]
I don't think it would be at all unreasonable to make it fail without a config file.

**Comment by madduck** [comment]
I would find it very beneficial if the situation was clarified a bit more in the manpage:

1. The defaults are 12 and "" and they cannot be changed without invalidating existing passwords;
2. The example YAML file in the manpage should probably be changed to these defaults;
3. The YAML file to use *should* be `homeserver.yaml` or the appropriate file in `conf.d`;
4. `homseserver.yaml` does not need to specify these values, as the defaults will be used in case of absence.

Thanks,
