### ISSUE TITLE
uncommented instances of `logger.isEnabledFor(DEBUG)`

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#11544]
There are several spots in the codebase where we have a conditional guarding a `logger.debug` like the following:

https://github.com/matrix-org/synapse/blob/941ebe49ffc32c6d67b487094a6f8e1c290e93bc/synapse/appservice/api.py#L234-L239

Of course, if debug logging isn't enabled, then a log line will not be emitted regardless.

As such, is this necessary? I suppose it does save some resources as we won't need to carry out the `[event.get("event_id") for event in events]` calculation, but we don't seem to actually follow this as a convention in too many other places around the codebase. Thus it's a bit confusing.

I suppose we could leave them in, but with a comment to justify the need for guarding expensive calculations.

**Comment by richvdh** [comment]
it's a pretty common convention, imho: if there is an expensive calculation which is unneeded without the log line, you can skip it with `logger.isEnabledFor`. There's no other reason to write `logger.isEnabledFor`, so if you see it, you can assume that's what it's doing.

I don't really think we need a comment each time we do it?

**Comment by richvdh** [comment]
(and yes, in this particular case, it's to avoid `[event.get("event_id") for event in events]`, which can be non-trivial in the case of a large list of events)

**Comment by richvdh** [comment]
@anoadragon453 I'm going to go ahead and close this, but feel free to reopen if you want to discuss further.
