### ISSUE TITLE
Prevent adding schema deltas to old `SCHEMA_VERSION`s

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11559]
Once an installation's database has been updated to a given `SCHEMA_VERSION`, any `delta` files which appear in older versions are ignored.

This means we have a ticking timebomb/footgun in which we accidentally merge a PR which adds a `delta` file to an old `SCHEMA_VERSION`, which is then ignored on existing installations. 

Ideally we want to make sure that, once `develop` is updated to a given `SCHEMA_VERSION`, no delta files are added to older versions.

**Comment by reivilibre** [comment]
What woud you suggest? A CI check for that? (main issue is that you can merge a branch on a stale CI check: if my CI passes and you later change `develop`'s `SCHEMA_VERSION`, nothing will alert me to that or stop me merging.)

**Comment by richvdh** [comment]
well yes, therein lies the problem - we'd have to do some research.

One option would be to enable this checky-box, but I think it would rapidly get painful, given we tend to have multiple PRs in flight at any given time:

![image](https://user-images.githubusercontent.com/1389908/145994595-a8fefdbd-3e41-4923-aafd-86ac2010c5ee.png)

So maybe we have to actually run a CI job on develop itself, which diffs against the commit where `SCHEMA_VERSION` was last bumped and checks that nothing has been added to older versions (and files an issue if it has)?

**Comment by clokep** [comment]
I think @richvdh marked this as fixed by #13063.

**Comment by DMRobertson** [comment]
This as followed-up by https://github.com/matrix-org/synapse/pull/15466.
