### ISSUE TITLE
Imgur & Tenor "GIFs" don't appear in URL previews

### ISSUE THREAD

**Issue by nathanielcwm** [matrix-org/synapse#11563]
### Description

When an Imgur or Tenor link is sent into a chat using Element Web and it contains a "GIF" said video does not embed.

### Steps to reproduce

- Send or receive a link to an Imgur or Tenor "GIF" in chat
- Observe that the embed just asks you to open a separate tab to open Imgur or Tenor instead of showing you the video.
![image](https://user-images.githubusercontent.com/22572406/144101220-9f3a34b4-37e7-495c-b4bf-c8929ef00dc1.png)
![image](https://user-images.githubusercontent.com/22572406/144101511-5fd4935c-542f-4a26-9469-f76a6eeafd6a.png)

### Describe how what happens differs from what you expected.
I'd expect the video to be embedded and playable in chat but instead all that is embedded is some text asking for you to open imgur/tenor in a separate tab.

### Version information
- **Homeserver**:
Matrix.org
- **Version**:
Whatever was on matrix.org on December 1st 2021

I was told that this was a homeserver bug when I reported it in vector-im/element-web#19970

Possible dupe of #1278 but I'm not certain.

**Comment by nathanielcwm** [comment]
I believe it was [Tenor](https://tenor.com/view/compelling-argument-ur-mom-gif-23325106) and [Imgur](https://imgur.com/gallery/KOeGTHr)

lol the imgur link wasn't a "GIF", but it appears that was the one I used in the screenshot

**Comment by clokep** [comment]
Thanks, that's helpful! 👍

**Comment by blastrock** [comment]
Note that this used to work before. I suspect #10814 to be the cause. I noticed it broke not long after that, but it may be unrelated.

**Comment by nathanielcwm** [comment]
Shouldn't this be reopened because Imgur was not fixed?

**Comment by clokep** [comment]
> Shouldn't this be reopened because Imgur was not fixed?

They worked fine for me in my testing.

**Comment by nathanielcwm** [comment]
Images do indeed work for me now, videos/GIFs don't appear to be working still.

**Comment by clokep** [comment]
> Images do indeed work for me now, videos/GIFs don't appear to be working still.

Could also be due to #1278?
