### ISSUE TITLE
Synapse users lose access to all rooms after logging out and in again

### ISSUE THREAD

**Issue by ginkel** [matrix-org/synapse#11568]
### Description

I was somewhat uncertain whether this may quailify as a support issue, but considering it involves catastrophic data loss, where the synapse instance is unable to locate rooms despite them being present in the database, I am inclined to open a bug report.

I am operating a Synapse (currently v1.48) instance along with an instance of mxisd. The trouble started when I migrated mxisd to ma1sd and - due to a misconfigured URL - Synapse could no longer reach ma1sd. This caused Element (Android) clients to be logged out.

Upon fixing the configuration error and logging in the client again, I was greeted with a room list that just contains one "Empty room" entry.

I do have a backup of the database and file system of the Matrix instance that pre-dates the configuration glitch.

Unfortunately, restoring it to that state does not remediate the situation, i.e., rooms are still gone.

I verified in the database that rooms are present in the `rooms` table and that the `current_state_events` table contains an `m.room.create` event for those rooms.

In the log I see messages like:

```
Exception: Room !QaxEOpfBhMxtIQrNBv:<redacted> for event $16386208139DWpYC:<redacted> is unknown
```

But what I wrote above about the room being present on the DB holds true for the room mentioned in the error message.

I can't rule out that the underlying problem has been lingering for a while and was only uncovered by the auth issues that logged out some clients. The Synapse instance is > 2 years old, so it has undergone all database migrations that occurred over time as the software evolved.

I'd appreciate your assistance to figure out what may be causing this and to eventually restore access for all users' rooms.

Thanks,
Thilo

P.S.: Most channels were encrypted if that makes any difference

### Steps to reproduce

I am afraid that I do not have clear clear instructions how to reproduce the problem except from what I wrote above.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: My privately hosted homeserver

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: `{"server_version":"1.48.0","python_version":"3.8.12"}`

- **Install method**: Docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Linux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
> Which request's response should contain the rooms of the user?

`/sync`.

I suggest you share your homeserver logs, including the full exception - it's unlikely we'll be able to shed much light without them.

**Comment by ginkel** [comment]
Thanks for your reply! Please find the server log at info level (w/ some IP addresses redacted) at: https://gist.github.com/ginkel/d954e86015f514df9a49a19dc0178806. The login operation starts at time index `2021-12-13 23:04:55,879`.

Please let me know if you need additional details / more verbose logs.

**Comment by ginkel** [comment]
> Please find the server log at info level

I can easily create a log at `DEBUG` level, but I'd welcome any hint which sensitive information I'd need to remove...

**Comment by DMRobertson** [comment]
Thanks @ginkel. I'm surprised to read that restoring the DB from backup didn't resolve the problem. 

Not much to go on in those logs, I'm afraid. No logging in the /sync responses, and they all ended up returning with status 200 OK. If possible, could you try logging out and in again on a client and capturing the server logs at DEBUG level? I'm particularly interested in the logs for the _first_ call to /sync after a login (which should have no `since=` query parameter in the URL, or any sync that doesn't return with a 200 OK.

> I can easily create a log at `DEBUG` level, but I'd welcome any hint which sensitive information I'd need to remove...

Don't have an authoritative answer for you here. You could try emailing them to me (`davidr@element.io`) or sending them over matrix (@dmrobertson:matrix.org), though I appreciate the latter is hard. I can see if there are

**Comment by DMRobertson** [comment]
> `Exception: Room !QaxEOpfBhMxtIQrNBv:<redacted> for event $16386208139DWpYC:<redacted> is unknown`

I also wanted to note that this looks like a room ID for an old room version (it contains a homeserver name). I wonder if that's causing pain somewhere?

**Comment by ginkel** [comment]
> Thanks @ginkel. I'm surprised to read that restoring the DB from backup didn't resolve the problem.

Me too. ;-) I have run the Element Android client in a debugger and AFAICS room membership info gets synced to the client, but somehow has no effect:

![image](https://user-images.githubusercontent.com/174129/146075527-542880f5-91d8-4910-b1b4-5533313877a6.png)

> > I can easily create a log at `DEBUG` level, but I'd welcome any hint which sensitive information I'd need to remove...
> 
> Don't have an authoritative answer for you here. You could try emailing them to me (`davidr@element.io`) or sending them over matrix (`@dmrobertson:matrix.org`), though I appreciate the latter is hard at the moment. I can see if there are any smoking guns.

I sent you the debug log via Matrix.

**Comment by ginkel** [comment]
> > `Exception: Room !QaxEOpfBhMxtIQrNBv:<redacted> for event $16386208139DWpYC:<redacted> is unknown`
> 
> I also wanted to note that this looks like ~a room~ an event ID for an old room version (it contains a homeserver name). I wonder if that's causing pain somewhere?

That room is actually version 1. But v6 rooms (that's the newest I have) have the homeserver name on the room id.

**Comment by DMRobertson** [comment]
> I sent you the debug log via Matrix.

Thanks for this. I don't see an invite as such yet, perhaps your homeserver isn't federating due to this problem? I'll check again tomorrow, but it might be worth forwarding a copy over email too as a fallback.

**Comment by ginkel** [comment]
Interesting. That query comes back empty for my user as well as any other user I tried...

**Comment by richvdh** [comment]
iiinteresting. are you able to DM me? I'm `@richvdh:sw1v.org`.

**Comment by ginkel** [comment]
As it turned out, a database locale problem caused `JOINs` not to work correctly after the restore. This has now been fixed. Thanks for your help!

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/6696
