### ISSUE TITLE
(Message retention policies) on Matrix - Server - With client cache - clean up?

### ISSUE THREAD

**Issue by GizehFire** [matrix-org/synapse#11573]
[Message retention policies](https://github.com/matrix-org/synapse/blob/develop/docs/message_retention_policies.md)

Limitation of the policy

Limiting the policy works fine for me. Have one room set up for a cleanup for every 24 hours. The server does that too, that's good. But, with the client (e.g. element.io Messenger) this only goes away if you log off the client and log in again.

How can I set that the messages are automatically deleted from the client (limitation of the policy)?

**Comment by babolivier** [comment]
Currently message retention policies is still an unstable feature in Matrix, and as such isn't very widely supported in clients. Please follow https://github.com/matrix-org/matrix-doc/pull/1763 for its stabilisation in the Matrix spec.
Clients are capable of implementing unstable features though, so it might be possible for client devs to implement it before the MSC is accepted. However, this repository is for Synapse, which is a server-side application. Please open issues on the repository(ies) for the client(s) you would like to see support for this feature.
