### ISSUE TITLE
Changing power level of a room admin

### ISSUE THREAD

**Issue by schoubi** [matrix-org/synapse#11601]
Hi,

I'm a bit stuck here : 

- we are multiple admins (PL 100) in a room
- we need to change the PL of one of us, whom don't want to leave by itself (!)
- through the GUI (element), there is no such options.
- through the API we tried : 

  - change his PL
  - change his membership from "join" to "leave"
  - simply remove him from room users list
- every time we get the error : "(M_FORBIDDEN: You don't have permission to remove ops level equal to your own)"
- i tried to scrumble across the database to manually change the PL, but no luck...

Is it possible ? Can someone help me ?

**Comment by DMRobertson** [comment]
I don't think this is possible. There's some related discussion at the spec level [here](https://github.com/matrix-org/matrix-doc/issues/652) and see also https://github.com/matrix-org/matrix-doc/pull/3510.

I think your options are:
- make a new room inviting everyone but the rogue admin
- if you control the rogue admin's homeserver, you could
  - read the rogue admin's access token from the database
  - use it to impersonate them, and have them leave the room. This would involve making a client-server API request manually.

Impersonating a user is naughty and a matter of last resort. Their access token can be invalidated at any time if they decide to log out.

For more advice and support, please see the [Synapse admins](https://matrix.to/#/#synapse:matrix.org) room on matrix.org.

**Comment by schoubi** [comment]
That's unfortunate... :worried: Thanks for your detailed answer.
