### ISSUE TITLE
Ability to send server notices to all HS users

### ISSUE THREAD

**Issue by voice06** [matrix-org/synapse#11605]
**Description:**

I have been playing around with this feature and it looks like it presently is geared towards single users. It would be nice if server notices could be send to all users on the server for server-wide announcements, like if the homeserver is going to be down for an extended period of time or some kind of event a admin would wish to announce to the entire homeserver.

Kind of thinking like how wallops or network-wide notices are used on IRC networks.

**Comment by dklimpel** [comment]
duplicate #5501
