### ISSUE TITLE
Synapse allows for wrong system time

### ISSUE THREAD

**Issue by avdb13** [matrix-org/synapse#11626]
### Synapse allows for wrong system time
A few days ago my friends were complaining about my server that was running Synapse's system time being display wrongly. This is a problem because Synapse will send out wrong timestamps to all my contacts.

### Steps to reproduce

- Change the time on the system and restart Synapse.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: gravitation.me

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
- 1.49.2

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
Portage through my own ebuild (which just fetches the source code and builds the programwith the Github release).

- **Platform**:
Gentoo GNU/Linux with 5.10.76-gentoo-r1
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
On my own hardware without virtualization and with the normal installation process.

**Comment by richvdh** [comment]
This is rather hard to do much about - we don't have any way to tell that you've set the system time incorrectly.

Anyway, I'm afraid this is out of scope for us. I recommend running an NTP client on your server.
