### ISSUE TITLE
Inconsistent room membership/room topic when joining from two different homeserver

### ISSUE THREAD

**Issue by varac** [matrix-org/synapse#11628]
### Description

I am on the way to migrate from a shared synapse installation to my own. I noticed that on my own server (server B) I see less members in rooms that on the shared one (A). In one room, I only see one less (28) on server B than on server A (29). That person can't see my messages in the room, and I can't see theirs.

### Steps to reproduce

- Join `#synapse:matrix.org` from server A: 2885 members, topic includes `Current release: 1.49.2`
- Join `#synapse:matrix.org` from server B: 2117 members, topic includes `Current release: 1.49.0`

I'd love to supply more details from the logs but I don't really know what to search for since the logs are huge, especially after joining the synapse admins room. I already tried to get support in `#synapse:matrix.org` but didn't get feedback.

### Version information (server B)

- **Homeserver**: varac.net (https://federationtester.matrix.org/#varac.net)
- **Version**: 1.49.2
- **Install method**: Kubernetes (k3s v1.21.5+k3s2), [synapse helm char](thttps://artifacthub.io/packages/helm/halkeye/synapse) v1.49.0
- **Platform**: Selfhosted Ganeti VM (kvm), Debian buster

**Comment by richvdh** [comment]
Slightly different membership counts aren't entirely unexpected, for reasons related to difficulties validating the signature on events. It's a bit of a surprise that you see a different topic in `#synapse` though.

Please could you search the logs of server B for the `/join` request of `#synapse`, and send the log lines corresponding to that request? https://matrix-org.github.io/synapse/develop/usage/administration/admin_faq.html#how-can-i-find-the-lines-corresponding-to-a-given-http-request-in-my-homeserver-log has some instructions on this.

**Comment by clokep** [comment]
Closing due to lack of response. If you still have the logs in question (or are still seeing inconsistent information) please let us know!
