### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by MrZMZ** [matrix-org/synapse#11636]
### Steps to reproduce
**operating system**：Linux (debian 8.11)

root@cstg:# echo "deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] .......
deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ jessie main 
root@cstg:# sudo apt update
Get:15 https://packages.matrix.org jessie/prerelease Translation-en
Get:16 https://packages.matrix.org jessie/main amd64 Packages
Get:17 https://packages.matrix.org jessie/prerelease amd64 Packages
Get:18 https://packages.matrix.org jessie/main Translation-en
Get:19 https://packages.matrix.org jessie/prerelease Translation-en
Get:20 https://packages.matrix.org jessie/main amd64 Packages
Err https://packages.matrix.org jessie/main amd64 Packages
  HttpError404
Get:21 https://packages.matrix.org jessie/prerelease amd64 Packages
Err https://packages.matrix.org jessie/prerelease amd64 Packages
  HttpError404
Get:22 https://packages.matrix.org jessie/main Translation-en
Ign https://packages.matrix.org jessie/main Translation-en
Get:23 https://packages.matrix.org jessie/prerelease Translation-en
Ign https://packages.matrix.org jessie/prerelease Translation-en
W: Failed to fetch https://packages.matrix.org/debian/dists/jessie/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://packages.matrix.org/debian/dists/jessie/prerelease/binary-amd64/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@cstg:~# sudo apt install matrix-synapse-py3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package matrix-synapse-py3

**Comment by MrZMZ** [comment]
Dependency update failed

**Comment by richvdh** [comment]
We don't support Debian jessie, I'm afraid.

**Comment by MrZMZ** [comment]
> 恐怕我们不支持 Debian jessie。

thanks
