### ISSUE TITLE
Matrix workers do not free up RAM memory (Kubernetes Synapse Setup)

### ISSUE THREAD

**Issue by Fred-Treebal** [matrix-org/synapse#11641]
### Description

- Matrix workers (Kubernetes setup) do not free up RAM memory and tend to always grow bigger (over a few days).
- Kubernetes can not scale down corresponding worker deployments if memory consumption increases continually (we use HPA on memory + cpu)
- Unnecessary worker pods consume database access slots

### Steps to reproduce

- run Matrix with workers under kubernetes and use it for a long enough period

Especially with workers handling sync, room and userdir, as these workers tend to grow bigger over time, their HPA tend to create unnecessary new worker pods as their RAM increases.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:  synapse 1.46 (and earlier versions)

- **Install method**: Kubernetes Deployment
<!-- examples: package manager/git clone/pip  -->


For now, to prevent this we either over allocate memory resources or periodically delete workers biggest pod instances.

A mechanism freeing up unused memory on workers should help Kubernetes properly do its job scaling workers pods up/down.

**Comment by reivilibre** [comment]
There are two aspects to getting memory usage down:
* deleting objects
* running garbage collection

The first suspect with RAM usage growing over time is that your caches are getting entries over time (on startup, they are empty!).

By default, caches will only have entries removed if they grow too large (and you can tweak the size of the caches, e.g. using `CACHE_FACTOR` — consult the documentation for specifics).

I would suggest trying the `expiry_time` option in the `caches` section of the configuration; this will make old cache entries get removed periodically, so the caches can shrink in size too (as long as they're not constantly being refilled by requests).

Of course, there's always a performance trade-off (this can potentially make your caches less effective), but usually if some entries haven't been used in a while, they are unlikely to be used again soon.

If you give this a try, please do report back with your experience!

**Comment by Fred-Treebal** [comment]
Thanks reivilibre, I'll follow your advice and run some tests on cache settings

**Comment by reivilibre** [comment]
I think this should resolve this issue (I've opened an issue #11787 to enable this by default) — if it doesn't then feel free to re-open
