### ISSUE TITLE
Federation TURN infrastracture amount different synapse instance.

### ISSUE THREAD

**Issue by evan0greenup** [matrix-org/synapse#11648]
Consider the following scenario:

Two user, Tom and Jerry are located in US, but they have matrix accounts on the server locate in France.

Both Tom's and Jerry's device are connected to the internet via their own home WiFi router (under NAT). So direct connection is not possible.

For the current settings, if Tom want to make a 1:1 video call with Jerry. He need to relay his data through the TURN server in France. This will not only make it inefficient but also make the connection unstable.

It would be nice to firstly communicate with the STUN server in France (this is one-time interaction), and then the STUN server will provide a public TURN server located in US (between Tom and Jerry in network topology). And let Tom and Jerry relay their connection via this US TURN server.

This design can utilize decentralized resource more efficient.

**Comment by evan0greenup** [comment]
@erikjohnston and @richvdh what are your opinions?

**Comment by richvdh** [comment]
I don't think the STUN protocol has a mechanism to redirect to an alternative TURN server in the way you suggest.

In any case, I think this is out of scope for synapse, which is not a TURN (or even STUN) server.
