### ISSUE TITLE
Delete user permanently 

### ISSUE THREAD

**Issue by foysaliotait** [matrix-org/synapse#11671]
Hi,
I am trying to deactivate or delete users. So I am using the below API to delete the user

```
https://server/_matrix/client/r0/account/deactivate
```

But when I request this API. I get below error

```
{
    "errcode": "M_UNKNOWN",
    "error": "Unknown session ID:  session_id"
}

```

Now I am not sure how to get this session id. 

Can someone point me in the right direction on how to get the session id?

Thanks

**Comment by dklimpel** [comment]
Have a look here:
- https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html#making-an-admin-api-request
- https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#deactivate-account

**Comment by foysaliotait** [comment]
Thanks. I figure out the deactivation part.
Need another help. Is there any API or way to reactivate the deactivated user?

**Comment by dklimpel** [comment]
The information is on the same page: https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account

**Comment by foysaliotait** [comment]
Thanks for your help. And yes i able to done it
