### ISSUE TITLE
New auth rule that only allows someone to post a message in relation to another message

### ISSUE THREAD

**Issue by frandavid100** [matrix-org/synapse#11673]
This feature request is related to [MSC3394](https://github.com/matrix-org/matrix-doc/pull/3394), and necessary for a new generation of social-media focused matrix clients like [Minestrix](https://matrix.to/#/#minestrix:carnot.cc) and [Matrix Art](https://matrix.to/#/#matrix-art:nordgedanken.dev).

These social-media-focused clients use rooms to store posts, and threads to store comments. But because of current limitations in the current permissions system, they have to choose between these two options:

1. Either regular members *can* send messages to the room, and therefore everyone can write posts on your wall...
2. Or they *can't*, and therefore only you can write posts on your wall, but no one can comment them.

A third option is necessary, where only you can write posts on your wall, but regular members of the room can comment those posts. For that we need to have a new permission that lets someone write a message only if it's inside a thread; that is, if that message is in relation to another message.

Apparently this change needs to be implemented by a client before the MSC can be approved, and it needs to be included in Synapse before any clients can implement it. So there's a real need for Synapse to include it.

**Comment by DMRobertson** [comment]
(Editing the description to link to the matrix-doc PR)

**Comment by clokep** [comment]
MSC3394 doesn't seem to include enough technical information to make changes to Synapse. It likely would need some changes to either the Client-Server API or the event authentication code, depending on how it goes though. I'm going to close this pending feedback based on the MSC.

**Comment by frandavid100** [comment]
Hi, Patrick.

I tried to elaborate as much as I could in the MSC. To that end, I added the following:

> Based on existing auth rules, the new auth rule I'm proposing could probably look like this:
> 
>    If type is m.room.message:
>     If the user's power level is higher than the power level for m.room.message events, allow.
>     Otherwise, check the new power level I want to introduce. If it's is higher than the user's power level, reject.
>     Otherwise, if the event doesn't have a relation, reject.
>     Otherwise, allow.
> 
> As an example, let's say I want to set up my room so that only moderators can post top-level messages, but regular users can comment those messages inside a thread. I will set a power level of 50 for the "send messages" permission, and a power level of 0 for the new "send messages to threads" permission.
> 
> When a user tries to send a message:
> 
>   If they are a moderator (PL of 50) they are allowed.
>   Otherwise, if they are a regular user (PL of 0) and the message is inside a thread (it has a relation) they are allowed.
>   Otherwise, they're not allowed.

I would like some feedback on it, and maybe a couple suggestions if you think it needs further improvements.

**Comment by clokep** [comment]
@frandavid100 Let's keep the conversation in one place for now (on the MSC). Once that's in better shape then we can think about implementing it.

**Comment by frandavid100** [comment]
Thanks :-)
