### ISSUE TITLE
[Proposal] Hide "last-seen" details in device list

### ISSUE THREAD

**Issue by marek-lach** [matrix-org/synapse#11688]
**Suggestion**
While the information about last activity must be logged by the server,[ due to Matrix design](https://github.com/matrix-org/matrix-doc/issues/3402), however, the server SHOULD also (preferably) have the option for admins to enable not sending this information further down to the clients, and/or users of clients to display. Servers SHOULD be able to optionally (by an admin setting) to CONCEAL (i.e. just not reveal) last user activity to the client, which'd then not be able to show it.

**Comment by clokep** [comment]
@marek-lach could you elaborate a bit more about why think this is useful?
