### ISSUE TITLE
`get_room_version` doesn't use the cache

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11706]
we have two functions for getting the version of a room from the database, `get_room_version_id` and `get_room_version`. The former gets the raw string, and then caches it to speed up future lookups. The second looks up the raw string, and then consults the list of known room versions to decode it into a `RoomVersion` object. The problem is that it doesn't cache the result, so is generally slower than it should be.

If `get_room_version` needs to exist at all, it should probably just wrap `get_room_version_id`.

**Comment by richvdh** [comment]
seems to be a regression introduced in https://github.com/matrix-org/synapse/pull/10245

**Comment by nicobao** [comment]
Hi!
I am starting working on this issue.

**Comment by lukasdenk** [comment]
I'll work on it
