### ISSUE TITLE
Unit-Testing: Mock vs. Datastore

### ISSUE THREAD

**Issue by pik** [matrix-org/synapse#1171]
Currently Synapse Unit-tests seem to Mock out the Datastore when performing tests e.g. https://github.com/matrix-org/synapse/blob/master/tests/rest/client/v2_alpha/test_filter.py#L30

This means that testing is relying on the programmer to specify the correct errors / responses for each test call to the datastore (e.g. https://github.com/matrix-org/synapse/blob/master/tests/rest/client/v2_alpha/test_filter.py#L46), which means that it's also possible for unit-tests to pass (and test something) which is not reflective of the actual application behavior. 

Were there strong / originally persuasive reasons to Mock out the Datastore while testing, are they still relevant?

**Comment by hawkowl** [comment]
We now use more native datastores than mocks.
