### ISSUE TITLE
Upgrade to mypy==0.931

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#11712]
**Description:**

mypy 0.931 adds some basic [ParamSpec](https://www.python.org/dev/peps/pep-0612/) support, which will allow us to correctly annotate decorators (#11711)

- [x] `mypy-zope` needs upgrading since the current version doesn't declare compatibility with mypy 0.931
- [x] mypy 0.931 flags up a bunch of new type checking errors which need fixing

**Comment by DMRobertson** [comment]
For the first checkbox, I think mypy-zope is on the case, just waiting for a release: 

https://github.com/Shoobx/mypy-zope/commit/01e0a0d3c511640a4f53f4b5dbdc4515cecc3d80
