### ISSUE TITLE
Configuration toggle to fake everyone's presence as online 24/7

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/synapse#11721]
**Description:**

What title says. By faking 24/7 online for everyone, you would hide presence info of everyone without other homeservers or clients knowing the presence is disabled.

**Comment by ShadowJonathan** [comment]
Why is this needed?

**Comment by erkinalp** [comment]
Disabling presence leaks info to clients and other homeservers, as users of clients can detect the fact users of that server (or all servers, if their own homeserver disabled it) is appearing as "no presence".

**Comment by reivilibre** [comment]
Surely an observer can make the inference that you have enabled this proposed fake-presence mode as soon as they notice that all users are always present?
I don't see how this is helping you avoid leaking information; it seems no different to just disabling presence altogether.

Faking presence requires sending traffic and scheduling this to happen automatically will probably lead to a statistically-detectable pattern, if someone is so keen to find out that you're using this feature. (?)

This also begs the question: is there a problem with other users knowing that presence is disabled on your server? It's a common server configuration at the moment anyway...

**Comment by erkinalp** [comment]
> Surely an observer can make the inference that you have enabled this proposed fake-presence mode as soon as they notice that all users are always present?

Strictly speaking, all users of that server could be bots as well and that would still result in the same always online behaviour.

**Comment by reivilibre** [comment]
> > Surely an observer can make the inference that you have enabled this proposed fake-presence mode as soon as they notice that all users are always present?
> 
> Strictly speaking, all users of that server could be bots as well and that would still result in the same always online behaviour.

Well, sure, but if the person you're talking to knows you're a human then they'll know you're not a bot. Or so on.
(N.B. bots don't necessarily always appear as present all the time)

**Comment by clokep** [comment]
I agree with @reivilibre here that I don't see how this is useful beyond just disabling presence.

**Comment by aaronraimist** [comment]
One thing this would do is fix how broken it looks in Element when servers have disabled presence and the Element instance hasn't configured `enable_presence_by_hs_url` https://github.com/vector-im/element-web/issues/4398

But that is probably better handled with https://github.com/matrix-org/matrix-doc/pull/1862 and https://github.com/matrix-org/synapse/pull/5666 or some other solution.
