### ISSUE TITLE
AS events should include `prev_content` field

### ISSUE THREAD

**Issue by benparsons** [matrix-org/synapse#11732]
### Description

AS spec states events should be "formatted as per the Client-Server API", but state events sent to ASes don't include the `prev_content` field.

### Version information

Occurs as of 1.50.

### Ref

Sayeth vdh:

> `ApplicationServiceTransactionWorkerStore.get_new_events_for_appservice` is missing `get_prev_content=True` in its call to `get_events_as_list`

**Comment by totallynotvaishnav** [comment]
Can I work on this issue?
