### ISSUE TITLE
The `state_group_edges` table doesn't have a unique index; can severely impact `WITH RECURSIVE state(state_group) AS ...` query performance if duplicates are somehow introduced

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#11779]
This is similar to, but not the same as, #10301.

The `state_group_edges` table doesn't have a unique index, so it's 'easy' to introduce duplicate rows e.g. by restoring a backup twice (or potentially even due to pure bugs in Synapse).

This query as part of `_get_state_groups_from_groups`:

```sql
WITH RECURSIVE state(state_group) AS ( VALUES(3405820::bigint) UNION ALL SELECT prev_state_group FROM state_group_edges e, state s WHERE s.state_group = e.state_group ) SELECT DISTINCT ON (type, state_key) type, state_key, event_id FROM state_groups_state WHERE state_group IN ( SELECT state_group FROM state ) ORDER BY type, state_key, state_group DESC
```

would be seriously slowed down by the presence of duplicate rows (I seem to think someone mentioned it would return the square of the number of rows it would usually, but I haven't verified that and I can't find that again to reference it).

It may be worth adding a unique index or perhaps having an SQL snippet that administrators can run to recover from this (though I would favour the former — make it hard to do in the first place).

As an aside: `state_group_edges` can potentially contain loops but that shouldn't arise from recovering backups (as far as I know) and it's not so easy to do something about — but worth bearing in mind that it would cause the query to go forever.

**Comment by richvdh** [comment]
> I seem to think someone mentioned it would return the square of the number of rows it would usually, but I haven't verified that and I can't find that again to reference it

This was https://github.com/matrix-org/synapse/issues/5064#issuecomment-946718795. Suppose you've got 4 state groups (A,B,C,D), each linked with edges, and each with (say) one state event. Correct behaviour says you should get 4 events back.

If you double the edges, then you end up checking SG A once, B twice, C four times, D 8 times, for a total of *15* state groups (and hence 15 events). Hence, square.

**Comment by richvdh** [comment]
see also https://github.com/matrix-org/synapse/issues/7772 for my first discovery of this issue.

**Comment by reivilibre** [comment]
That sounds more exponential (2^n - 1) to me (i.e. worse) — if you add an E in the same configuration you'll check it 16 times for this (perhaps artificial) example.

**Comment by richvdh** [comment]
errr good point.

**Comment by richvdh** [comment]
(and given state group chains often run into a hundred links... that's a lot of rows)

**Comment by reivilibre** [comment]
@Half-Shot : to confirm it's caused by duplicate rows, would you mind running this?:

```sql
select COUNT(1) from ( SELECT state_group, prev_state_group FROM state_group_edges GROUP BY state_group, prev_state_group HAVING COUNT(ctid) > 1 ) AS dupes;
```

This ran fairly quickly for me (less than a second for 295k rows in the table) but I can't guarantee whether it will or not for you, but it would be nice to confirm that this is the cause if it works easily.

**Comment by Half-Shot** [comment]
```
synapse=> SELECT COUNT(1) from ( SELECT state_group, prev_state_group FROM state_group_edges GROUP BY state_group, prev_state_group HAVING COUNT(ctid) > 1 ) AS dupes;

 count
-------
     0
(1 row)
```

Bah, looks like I don't have dupes, just regular slowness.

**Comment by reivilibre** [comment]
A community member in the Synapse Admins room today came with an issue where this query was being slow.

Luckily I knew of this issue (and the query I posted two messages above came back with a non-zero result to confirm my hypothesis!).

What went wrong is that they cancelled (^C?) the import of their backup half-way through and later did it again. It's not that difficult a mistake to make.

'Luckily' their Synapse was so completely borked by the slow queries that they came looking for help and the suggested solution was to delete the database and freshly import it again.
(Theoretically we could write a query to fix the issue for *this* table, but there might be other cases in the database that we're not aware of and so restoring from fresh is the ideal course of action, considering there wasn't a risk of data loss since the homeserver was too broken to use anyway).

However in general it would be nice to prevent others from falling into this trap. As evidenced today: it does happen!

**Comment by DMRobertson** [comment]
> What went wrong is that they cancelled (^C?) the import of their backup half-way through and later did it again. It's not that difficult a mistake to make.

Can we (do we not?) wrap the import in a transaction to prevent this kind of thing?

(That said, I'd still rather have uniqueness requirements enforced by the schema)

**Comment by DMRobertson** [comment]
> > Can we (do we not?) wrap the import in a transaction to prevent this kind of thing?
> 
> That depends on what `pgdump` does. I can't say I know off the top of my head :/.

Looks like we'd have to opt-in to it with [`pg_restore --single-transaction`](https://www.postgresql.org/docs/10/app-pgrestore.html). That prevents you from using `--jobs` to parallelise the slow bits though.

**Comment by artemislena** [comment]
That was me… and I used `psql`, not `pg_restore`…

**Comment by chagai95** [comment]
I think I have the same issue, tried the dupes command:
![Screenshot from 2022-03-05 14-36-31](https://user-images.githubusercontent.com/31655082/156885660-c10fa17b-a783-4d0a-b57a-d2be98410c39.png)

I tried a few times to log in and every time it kind of made my server so slow until I restarted it sometimes I had to restart twice until it got back to working normally... I have some bridges configured but I really don't think I have that much trafic on my server...

**Comment by chagai95** [comment]
Maybe using workers will help this?

**Comment by richvdh** [comment]
@chagai95 this issue is about performance problems caused by duplicate entries. As your query shows, you don't have any. Workers are not the right solution to duplicate rows.

**Comment by chagai95** [comment]
Ok thx, so I'll create s new ticket, thx!

**Comment by richvdh** [comment]
I think the work here is to convert the existing index on `state_group_edges.state_group` to a unique index (presumably by creating a new index, and then deleting the old one).

(A technically preferable solution might be to replace the `state_group_edges` table with a nullable `prev_state_group` column on `state_groups` - but that is a pain in the butt to orchestrate.)

This should be a fairly simple thing to do via background updates (the `register_background_index_update` helper exists for this purpose).

**Comment by reivilibre** [comment]
## Useful Queries

### Postgres

#### Diagnosing the condition

```sql
SELECT COUNT(1) from ( SELECT state_group, prev_state_group FROM state_group_edges GROUP BY state_group, prev_state_group HAVING COUNT(ctid) > 1 ) AS dupes;
```

This will return `0` if the table is fine, or a bigger number if there are duplicate rows.

#### Solving the condition

```sql
BEGIN;
DELETE FROM state_group_edges WHERE (ctid, state_group, prev_state_group) IN (
  SELECT row_id, state_group, prev_state_group
  FROM (
    SELECT
      ctid AS row_id,
      MIN(ctid) OVER (PARTITION BY state_group, prev_state_group) AS min_row_id,
      state_group,
      prev_state_group
    FROM state_group_edges
  ) AS t1
  WHERE row_id <> min_row_id
);
COMMIT;
```

If you want some peace of mind, check that `psql` says `DELETE xyz` where `xyz`
matches the number from the first query, before entering `COMMIT`.


### SQLite

#### Diagnosing the condition

```sql
SELECT COUNT(1) from ( SELECT state_group, prev_state_group FROM state_group_edges GROUP BY state_group, prev_state_group HAVING COUNT(rowid) > 1 ) AS dupes;
```

This will return `0` if the table is fine, or a bigger number if there are duplicate rows.

#### Solving the condition

Using the `sqlite3` command-line tool:

```sql
BEGIN;
DELETE FROM state_group_edges WHERE (rowid, state_group, prev_state_group) IN (
  SELECT row_id, state_group, prev_state_group
  FROM (
    SELECT
      rowid AS row_id,
      MIN(rowid) OVER (PARTITION BY state_group, prev_state_group) AS min_row_id,
      state_group,
      prev_state_group
    FROM state_group_edges
  )
  WHERE row_id <> min_row_id
);
COMMIT;
```

If you want some peace of mind, enter `.changes on` first and before you
`COMMIT`, check that the number of `changes` matches the number obtained from
the first query.
