### ISSUE TITLE
support for python 3.10

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11780]
Python 3.10.0 final was released 3 months ago, on 2021-10-04. We should add support for it.

**Comment by richvdh** [comment]
I think this involves:
 * [x] adding 3.10 to the list of distributions we run `trial` tests on (already done in #11595)
 * [ ] building new sytest docker images which include python 3.10, and adding it to the list for CI
 * [ ] updating https://matrix-org.github.io/synapse/develop/setup/installation.html#installing-as-a-python-module-from-pypi to note 3.10 is now supported.

Relatedly, following the y-1 rule suggested at https://github.com/matrix-org/synapse/issues/8674#issuecomment-719990241, it's time to update the docker images to python 3.9.

**Comment by DMRobertson** [comment]
> * adding 3.10 to the list of distributions we run `trial` tests on (already done in

See also https://github.com/matrix-org/synapse/pull/10992/

**Comment by anoadragon453** [comment]
> building new sytest docker images which include python 3.10 (I think we could use Debian 'bookworm' as a basis for this) and adding it to the list for CI

It looks like this last remaining item was done in https://github.com/matrix-org/sytest/pull/1184, and indeed we [now have bookworm images on DockerHub](https://hub.docker.com/layers/matrixdotorg/sytest/bookworm/images/sha256-09d9c6752a25aadd668d492283e70f7858e337df8576009f82e995dda0ef3503).

With that final box ticked, can this issue be closed?

**Comment by richvdh** [comment]
yes, if you open a new one to track:

> Relatedly, following the y-1 rule suggested at https://github.com/matrix-org/synapse/issues/8674#issuecomment-719990241, it's time to update the docker images to python 3.9.

:)
