### ISSUE TITLE
Enable cache time-based expiry by default

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#11787]
The 'new' time-based expiry for caches in Synapse seems to have helped out with memory usage (empirically, based on what people are telling me).
It seems like it would be worth enabling by default so that people don't have to know about this obscure option to get the benefits.

Related: #11641 (it's not obvious that even though Synapse's memory usage only grows by default, it is capable of trimming back down).

**Comment by DMRobertson** [comment]
I'd preach some caution here. We opted out of time-based expiry for a particular cache in #10826. I forget the details (cc @erikjohnston); I'm not sure if we ever convinced ourselves if that change helped?

**Comment by anoadragon453** [comment]
I always advise people to do this - enabling it by default would probably help in the majority of cases.

**Comment by callahad** [comment]
We've been very happy with this on matrix.org for long enough to be confident that this is reasonable to turn on by default.
