### ISSUE TITLE
Changing TLS certificate requires server restart

### ISSUE THREAD

**Issue by WGH-** [matrix-org/synapse#1180]
Honestly, I didn't verify it myself, but that's what I could figure out from the code.

The TLS certificate is loaded here: https://github.com/matrix-org/synapse/blob/9bba6ebaa903a81cd94fada114aa71e20b685adb/synapse/config/tls.py#L27
And then dumped, among other places, here: https://github.com/matrix-org/synapse/blob/9bba6ebaa903a81cd94fada114aa71e20b685adb/synapse/rest/key/v2/local_key_resource.py#L93

Assuming config is read once (which also seems true - https://github.com/matrix-org/synapse/blob/88acb99747c05f43f4563774f498993b27915493/synapse/app/homeserver.py#L270), it means that when TLS certificate is updated (which can be relatively often with Let's Encrypt, once per several months), server needs to be restarted.

It would be better if certificate can be reloaded without server restart. Server can be signalled with SIGHUP/SIGUSR1/SIGUSR2, or something.

**Comment by jrabbit** [comment]
I think this is generalizable also the debian package's systemd unit doesn't have any reload function

**Comment by MacLemon** [comment]
Same goes for the FreeBSD rc.d item. Cannot reload certificate and private keys without fully restarting synapse.

**Comment by richvdh** [comment]
You can now reload certs with a SIGHUP
