### ISSUE TITLE
federation try even if you have leave the rooms 

### ISSUE THREAD

**Issue by Arthurdevid** [matrix-org/synapse#11807]
Sorry in advance if its in wrong place

### Description

Hello, thanks in advance, I joined the big cybersecurity channel with my homeserver, then I left directly because I didn't want to federate with this specific homeserver. so I whitelisted only the servers I wanted to federate but how long do the other servers from the cybersecurity room make requests to try to federate even if i have left the room ? 

### Steps to reproduce

- join a very big room
- direct leave 
- whitelist only the servers you want to federate
- watch all the servers try to federate 

### Version information

latest docker version.

(*) example : 

synapse.federation.transport.server._base - 277 - WARNING - PUT-9733 - authenticate_request failed: 403: Federation denied with cadair.com.

synapse.http.server - 95 - INFO - PUT-9733 - <XForwardedForRequest at 0x7fecebbbb550 method='PUT' uri='/matrix_/federation/v1/send/1643016771382' clientproto='HTTP/1.0' site='8008'> SynapseError: 403 - Federation denied with cadair.com

**Comment by anoadragon453** [comment]
Federating with only a subset of homeservers in a room is likely to cause some breakage, and is not supported.

Did you configure the whitelist before leaving the room? If so, then the non-whitelisted homeserver(s) may not have gotten your leave membership, and will continue to send federation traffic to your homeserver from rooms it believes it shares with you.

Eventually, the other homeserver should get your leave membership event once another event references it.

**Comment by richvdh** [comment]
note that the log line in question is an *outgoing* request, not an incoming one.

**Comment by Arthurdevid** [comment]
> Federating with only a subset of homeservers in a room is likely to cause some breakage, and is not supported.
>  

For other room i have whitelist not this one


> Did you configure the whitelist before leaving the room? If so, then the non-whitelisted homeserver(s) may not have gotten your leave membership, and will continue to send federation traffic to your homeserver from rooms it believes it shares with you.
> 

after 

> Eventually, the other homeserver should get your leave membership event once another event references it.

rejoin and releave ? 




> note that the log line in question is an _outgoing_ request, not an incoming one.

ahh, how to stop my homeserver making this outgoing request ?

**Comment by Arthurdevid** [comment]
I have tried to rejoin and releave and remove my whitelist, i think my server keep trying sending data to the room i have quit ? 

now i have redo my whitelist an this happend the same

other example :


190 - synapse.federation.transport.server._base - 277 - WARNING - PUT-12060 - authenticate_request failed: 403: Federation denied with chat.coupou.eu.
190 - synapse.http.server - 95 - INFO - PUT-12060 - <XForwardedForRequest at 0x7fece492a1c0 method='PUT' uri='/_matrix/federation/v1/send/1642986993480' clientproto='HTTP/1.0' site='8008'> SynapseError: 403 - Federation denied with chat.coupou.eu.

,191 - synapse.access.http.8008 - 424 - INFO - PUT-12060 - 135.125.24.80 - 8008 - {None} Processed request: 0.001sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 74B 403 "PUT /_matrix/federation/v1/send/1642986993480 HTTP/1.0" "Synapse/1.49.0" [0 dbevts]

192 - synapse.federation.transport.server._base - 277 - WARNING - PUT-12061 - authenticate_request failed: 403: Federation denied with matrix.palveluntarjoaja.eu.

192 - synapse.http.server - 95 - INFO - PUT-12061 - <XForwardedForRequest at 0x7feceac793a0 method='PUT' uri='/_matrix/federation/v1/send/1642685828048' clientproto='HTTP/1.0' site='8008'> SynapseError: 403 - Federation denied with matrix.palveluntarjoaja.eu.

 synapse.access.http.8008 - 424 - INFO - PUT-12061 - 51.83.158.85 - 8008 - {None} Processed request: 0.001sec/0.000sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 86B 403 "PUT /_matrix/federation/v1/send/1642685828048 HTTP/1.0" "Synapse/1.50.1" [0 dbevts]

 synapse.federation.transport.server._base - 277 - WARNING - PUT-12062 - authenticate_request failed: 403: Federation denied with envs.net.

 synapse.http.server - 95 - INFO - PUT-12062 - <XForwardedForRequest at 0x7feced19e370 method='PUT' uri='/_matrix/federation/v1/send/1643015029310' clientproto='HTTP/1.0' site='8008'> SynapseError: 403 - Federation denied with envs.net.

 synapse.access.http.8008 - 424 - INFO - PUT-12062 - 144.76.146.18 - 8008 - {None} Processed request: 0.001sec/0.000sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 68B 403 "PUT /_matrix/federation/v1/send/1643015029310 HTTP/1.0" "Synapse/1.50.1" [0 dbevts]

**Comment by squahtx** [comment]
Does the federation traffic drop off after a few days?

**Comment by Arthurdevid** [comment]
> 

No, the same, lot and lot of log messages

**Comment by Arthurdevid** [comment]
> Do you mind letting us know which room it is and your homeserver url?

the cybersecurity room from matrix.org

i can but in more private place. 

The big questions is :
How to stop my homeserver making  federation outgoing request ?

**Comment by squahtx** [comment]
> How to stop my homeserver making federation outgoing request ?

As rich says, clearing the `destination_rooms` table may help. And maybe `destinations` too.

The 2nd log excerpt looks like incoming requests to me. There's not much you can do for those except set up a reverse proxy to filter them out.

When I tested joining and leaving a matrix.org room with my homeserver, incoming requests dropped off pretty fast after other homeservers received the leave event. I did receive a few presence updates after leaving the room, but those could be down to caching or buffering. When other homeservers did not receive the leave event and thought I was still in the room, incoming requests did not drop off.

Have you ever joined #matrix:matrix.org (Matrix HQ) on that homeserver by any chance? That room has known issues to do with membership state.

**Comment by Arthurdevid** [comment]
> > How to stop my homeserver making federation outgoing request ?
> 
> As rich says, clearing the `destination_rooms` table may help. And maybe `destinations` too.
> 
> The 2nd log excerpt looks like incoming requests to me. There's not much you can do for those except set up a reverse proxy to filter them out.
> 
> When I tested joining and leaving a matrix.org room with my homeserver, incoming requests dropped off pretty fast after other homeservers received the leave event. I did receive a few presence updates after leaving the room, but those could be down to caching or buffering. When other homeservers did not receive the leave event and thought I was still in the room, incoming requests did not drop off.
> 
> Have you ever joined #matrix:matrix.org (Matrix HQ) on that homeserver by any chance? That room has known issues to do with membership state.

Thanks,

Where to clear  the destination_rooms table may help. And maybe destinations ? 

And for the matrix:matrix.org, maybe i was trying open channel.

**Comment by squahtx** [comment]
You can use `psql` to clear out the tables. I would take a backup of the tables first using pg_dump:
```sh
pg_dump synapse -t destinations > 20220216_synapse_destinations.sql
pg_dump synapse -t destination_rooms > 20220216_synapse_destination_rooms.sql
```
then:
```sh
psql synapse
DELETE FROM destinations;
DELETE FROM destination_rooms;
\q
```

Replace "synapse" with the name of your database of course.

**Comment by squahtx** [comment]
I'm going to close this now since Synapse appears to be working as intended. As [rich says](https://github.com/matrix-org/synapse/issues/11807#issuecomment-1040613119):
* Synapse will retry sending events, including the final leave event, to all remote homeservers that haven't received them yet, including homeservers that are perpetually down.
* And homeservers that think you're still in the room will continue to send events, presence, etc. I think this is the case with Matrix HQ.

**Comment by Arthurdevid** [comment]
i'm in sqlite3 i think (docker) .

what command i need to do ? Thanks

**Comment by squahtx** [comment]
In that case you can:
1. shut down synapse
2. take a copy of the sqlite database as a backup
3. ```sh
   $ sqlite path/to/synapse.db
   > DELETE FROM destinations;
   > DELETE FROM destination_rooms;
   > ^D
   ```
   Ctrl+D will exit.
4. start synapse again

You might have to install the sqlite3 CLI for step 3.
