### ISSUE TITLE
Federated device list not removing removed devices

### ISSUE THREAD

**Issue by paddycarver** [matrix-org/synapse#11801]
### Description

My friend has an account on matrix.org. I run my own homeserver using Synapse. He has clients with encryption keys that I've verified before, and one client with encryption keys that I've not verified before. He removed some of the clients that I've verified and the one that I haven't. His device list (Room Info -> People -> his name -> N verified sessions in Element desktop) doesn't show the devices he removed, but mine does. And I now get the scary red "unencrypted" badge for the room because there's an unencrypted client in the room, and we can't resolve it because he doesn't have the client anymore.

### Steps to reproduce

- add devices
- sync them to a federated server
- ???? (unclear, some confounding condition here, I assume?)
- remove devices

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: tricuties.com

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.50.1","python_version":"3.7.3"}

(I don't know what version it originally showed up on, but I can confirm it's happening in 1.48.0 and 1.50.1.)

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

Debian packages from the Matrix repository

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

Running as a VM in GCP on debian 10.

**Comment by paddycarver** [comment]
Debugging attempts:

I've verified that requesting the [client-server `/keys/query`](https://spec.matrix.org/v1.1/client-server-api/#post_matrixclientv3keysquery) endpoint for my homeserver returns all the devices I'm seeing in the client. I tried to reproduce the [server-server `/keys/query`](https://spec.matrix.org/v1.1/server-server-api/#post_matrixfederationv1userkeysquery) endpoint on the matrix.org homeserver, but I've been unable so far to get it to accept my authentication header, leading me to suspect I'm not signing the JSON correctly or I'm building the request incorrectly or something.

**Comment by aaronraimist** [comment]
Related: https://github.com/matrix-org/synapse/issues/8631

**Comment by paddycarver** [comment]
I think this is probably a duplicate of #8631, my bad.

**Comment by DMRobertson** [comment]
Nonetheless, thanks for the report @paddycarver. I'm very grateful for your efforts to debug!

The server-server communication seems to be where this is going wrong, and I've added some optional debug logging to try and track this down. See https://github.com/matrix-org/synapse/issues/8631#issuecomment-1020041198 if you'd like to give it a try.
