### ISSUE TITLE
complement test image disables HTTP cert checking

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#11803]
The image we build to run under complement disables HTTP cert checking for federation connections:

https://github.com/matrix-org/complement/blob/master/dockerfiles/synapse/homeserver.yaml#L44-L46

@kegsay suggests we don't do anything about this until https://github.com/matrix-org/complement/issues/65 is fixed

**Comment by kegsay** [comment]
In theory you can now start doing this as of https://github.com/matrix-org/complement/pull/299 - `ca.crt` and `ca.key` are always mounted to the container now, and `COMPLEMENT_CA` is no longer A Thing. The location of these files is subject to change as per https://github.com/matrix-org/complement/issues/233 but for now they sit where they always have: `/ca`.

**Comment by richvdh** [comment]
I had a go at sorting this, but stumbled into https://github.com/matrix-org/complement/issues/355, which is going to be a blocker.
