### ISSUE TITLE
high CPU load by "matrix- _process_incoming_pdus_in_room_inner"

### ISSUE THREAD

**Issue by zxyz** [matrix-org/synapse#11818]
### Description

Since ~ November the 24th last year I'm observing strange metrics in synapse.                                                                                               
This is the day I upgraded synapse from 1.45.1 to 1.46 (that was the only change that day).

CPU load went higher together with some other metrics (I'm referring to the synapse grafana dashboard, see below for screenshots):                                                              

 - DB transactions by total txn time -> matrix- get_auth_chain_difference
 - Number of events in federation staging area
 - Age of oldest event in staging area
 - DB usage by background jobs (including scheduling time) -> matrix- _process_incoming_pdus_in_room_inner

### What I tried:                                                                                                                                                                                   

- I did disable presence in between -> no change
- nothing noticable in the logs (at least for me)
- I compressed state, vacuumed postgres and purged old media files
- no change after container restart or reboot
- no change in between night and day (less users at night)
- no change after several updates

### Version information                                                                                                                                                                         

- Debian 11
- docker  using the amazing `matrix-docker-ansible-deploy` playbook
- in November when it started it was running synapse 1.46 AND postgres 13.x. 
- Current Synapse version is 1.50.2, postgres 14.1. 
- DB storage is on SSDs, 8 CPU cores, 24G RAM
- no room complexity set
                                                                                                                                                                                                
### grafs

![cpu](https://user-images.githubusercontent.com/14958508/150864846-d58435e4-0271-43e0-8675-2bfa6d893e4c.png)

![cpu-usage-background](https://user-images.githubusercontent.com/14958508/150864878-624bf979-99ac-400b-8699-8227e26d7184.png)

- red: matrix- _process_incoming_pdus_in_room_inner
- organge: federation_transaction_transmission_loops
- blue: matrix_persists_events

![cache-misses](https://user-images.githubusercontent.com/14958508/150864956-2f06f588-4d8a-494f-8727-e0804dfa59f5.png)
![avg-db-transaction](https://user-images.githubusercontent.com/14958508/150864993-65b44a76-0c32-4097-a844-e07cad6659d1.png)
- red: "state resolve events"
- violett: perists_events: get new state after events
- orange: resolve state groups for events

![federation-staging](https://user-images.githubusercontent.com/14958508/150865027-91bd59af-1f43-4b8a-a761-d5de1c93533a.png)
![oldest_evnts_in_staging](https://user-images.githubusercontent.com/14958508/150865064-c1449624-96b7-4cc2-999f-a18affe980f8.png)
![resolve_events](https://user-images.githubusercontent.com/14958508/150865092-53a0e480-a8aa-4440-a0af-88708b9ab62e.png)

Please let me know if you'd like to have some other screenshots or information.

Thanks a lot!

**Comment by zxyz** [comment]
actually, there is a day/night difference to be seen:
![xcpu](https://user-images.githubusercontent.com/14958508/151033195-425ba6b0-08a3-4262-9af0-e26ee14a9d57.png)

looks like it correlates with PDU and EDU rates
![xpdu](https://user-images.githubusercontent.com/14958508/151033210-634be65e-17ff-4df9-b724-d495aeef1ee5.png)

I adjusted the cache factor from 0.5 to 1.0.Didn't change  anything.

**Comment by jaywink** [comment]
I'm seeing similar things in EMS land. Four customer hosts, three of them in one particular Libera room. All show similar graphs than the below. All of them seem to start having issues with a large spike in inbound federation, causing things to lock up.

CPU spikes and stays pinned:

![Selection_999(887)](https://user-images.githubusercontent.com/1174866/151333453-ada568a8-a01c-4e48-961c-0d1a8a692e35.png)

Federation spike to start things:
![Selection_999(888)](https://user-images.githubusercontent.com/1174866/151333496-32b9af25-98cd-49cb-aaec-f67c7d574523.png)

Background jobs causing the issue, `_process_incoming_pdus_in_room_inner` and `Lock._renew`

![Selection_999(889)](https://user-images.githubusercontent.com/1174866/151333733-9597e1a1-c49e-43c8-9b85-f2549177ca0a.png)

Database is doing lots of `renew_lock`, confirmed to be the most exhaustive thing on the database server side

![Selection_999(890)](https://user-images.githubusercontent.com/1174866/151333848-2f4b935a-2e45-41e7-a96e-6c7d736b979c.png)

It seems to be persisting something

![Selection_999(893)](https://user-images.githubusercontent.com/1174866/151334229-49c3b899-34a2-4a27-a089-f724a0fd2360.png)

I restarted one of the Synapse's and the "lock" seems to disappear.

![Selection_999(891)](https://user-images.githubusercontent.com/1174866/151334349-282e33c7-b715-48df-88a6-50acf6efe7fe.png)

The lock renew activity disappears, replaced by actually persisting events a few spiky times, then flattening out.

![Selection_999(894)](https://user-images.githubusercontent.com/1174866/151334377-bef190ca-c1db-4386-849c-7e6f7a795602.png)

Something got locked up and it cleared on restart?

All these four customer hosts are Synapse v1.51.0 with an otherwise low amount of activity / users. I've pinged the internal backend room with customer names, should logs be helpful. Times in graphs above are UTC+2.

**Comment by dannycolin** [comment]
> All these four customer hosts are Synapse v1.51.0 with an otherwise low amount of activity / users.

Same here with a self-hosted homeserver on v1.51.0. It prevents any inbound messages to get delivered to my users. They can still send messages to anyone outside tho.

**Comment by clokep** [comment]
What EMS was seeing sounds a little different since I'm assuming @zxyz has restarted the service sometime between this starting?

It might be useful to grep the logs for `biggest rooms for state-res`  after configuring the `synapse.state.metrics` for debug logs. I would hope that would show if it is all due to a single room, but it might not.

**Comment by zxyz** [comment]
Thanks @clokep for the hint. Synapse and also the VM got restarted/upgraded several times.

I let the debug log run over night. There are a 300 entries with `state-res´, here is an excerpt:

```
1 biggest rooms for state-res by DB time: ['!OGEhHVWSdvArJzumhm:matrix.org (159.379s)']
3 biggest rooms for state-res by CPU time: ['!OGEhHVWSdvArJzumhm:matrix.org (86.4182s)
2 biggest rooms for state-res by DB time: ['!OGEhHVWSdvArJzumhm:matrix.org (163.432s)'
1 biggest rooms for state-res by CPU time: ['!OGEhHVWSdvArJzumhm:matrix.org (73.8072s)']
1 biggest rooms for state-res by CPU time: ['!OGEhHVWSdvArJzumhm:matrix.org (64.4513s)']                          
1 biggest rooms for state-res by DB time: ['!OGEhHVWSdvArJzumhm:matrix.org (139.385s)']                          
1 biggest rooms for state-res by CPU time: ['!OGEhHVWSdvArJzumhm:matrix.org (32.9124s)']
1 biggest rooms for state-res by DB time: ['!OGEhHVWSdvArJzumhm:matrix.org (72.2949s)']
```
"!OGEhHVWSdvArJzumhm:matrix.org"  is Matrix HQ if I'm not mistaken.

The other rooms in case of "3 biggest rooms" had much lower values for DB and CPU , not posting them here because I don't know if they're private rooms and I don't want to reveal anything private :).

We were already considering setting "complexity: 200.0" on the server to basically just kick out "Matrix HQ" because of to many resource usage (state...). So maybe I'll try this now.

But with your `synapse.state.metrics` hint I found #8612 and checked for room extremities with 
```
select room_id, count(*) c from event_forward_extremities group by room_id order by c desc limit 20;
```

There are a few rooms with c of 3, 4 and one with 5. But there is one room with a c of **109** (!) (federated room at privacytools.io). My prometheus data goes back 90 days and this c 109 room was there all the time.  This room also has higher state-res than most other in the debug log:

```
689 - DEBUG - sentinel - 2 biggest rooms for state-res by CPU time: ['!OGEhHVWSdvArJzumhm:matrix.org (32.7982s)', '!<ROOMID>:privacytools.io (15.8225s)']
 689 - DEBUG - sentinel - 2 biggest rooms for state-res by DB time: ['!OGEhHVWSdvArJzumhm:matrix.org (78.7121s)', '<ROOMID>:privacytools.io (5.36405s)']
 689 - DEBUG - sentinel - 2 biggest rooms for state-res by CPU time: ['!OGEhHVWSdvArJzumhm:matrix.org (68.9037s)', '!<ROOMID>:privacytools.io (6.03624s)']
 689 - DEBUG - sentinel - 2 biggest rooms for state-res by DB time: ['!OGEhHVWSdvArJzumhm:matrix.org (157.548s)', '!<ROOMID>:privacytools.io (1.8746s)']
 ```
But should/can I do anything about this room?

Thanks a lot, much apprechiated!

**Comment by clokep** [comment]
> "!OGEhHVWSdvArJzumhm:matrix.org" is Matrix HQ if I'm not mistaken.
>
> We were already considering setting "complexity: 200.0" on the server to basically just kick out "Matrix HQ" because of to many resource usage (state...). So maybe I'll try this now. Or are there other options?

Note that I don't believe setting that now will have your users leave Matrix HQ. You would want to delete the room afterward: https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#delete-room-api (please read through that first before just running the commands!)

> But with your `synapse.state.metrics` hint I found #8612 and checked for room extremities with
> 
> ```
> select room_id, count(*) c from event_forward_extremities group by room_id order by c desc limit 20;
> ```
> 
> But should/can I do anything about this room?

See the forward extremities admin APIs: https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#forward-extremities-admin-api, you might want to delete the forward extremities (this pretty much makes an event to simplify the overall DAG, which should help with state res). It mentions reading through #1760 though, we should probably move the important bits of that into our documentation. 😢

**Comment by zxyz** [comment]
thanks a lot @clokep, deleting forward extremities did the trick!  

> Note that I don't believe setting that now will have your users leave Matrix HQ. You would want to delete the room afterward: https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#delete-room-api (please read through that first before just running the commands!)

I set `complexity: 200.0`, restarted synapse but to my surprise I was still able to join Martix HQ (with an account which was never before in the room) which has a complexity > 800 (if I'm correct with states / 500 = complexity). 

Any ideas why this still worked?

Then I deleted the room with:
```
curl --header "Authorization: Bearer <api-token>" -XDELETE 'http://localhost:8008/_synapse/admin/v1/rooms/!OGEhHVWSdvArJzumhm:matrix.org' --data '{"block": true, "purge": true}'
```

Which failed after ~ 15 minutes with `{"errcode":"M_UNKNOWN","error":"Internal server error"}`. I re-ran the command and it finished without output. Trying to join Matrix HQ failed with "Failed to join room This room has been blocked on this server" -> cool!

Re-runing the command again results in `{"kicked_users":[],"failed_to_kick_users":[],"local_aliases":[],"new_room_id":null}`

But the data is still there:

```
SELECT rss.name, s.room_id, count(s.room_id) FROM state_groups_state s
LEFT JOIN room_stats_state rss USING (room_id)
GROUP BY s.room_id, rss.name
ORDER BY count(s.room_id) DESC
LIMIT 1;
```
yields:
```
name          |            room_id             |  count
-----------------------+--------------------------------+----------
                       | !OGEhHVWSdvArJzumhm:matrix.org | 43861911
```

So now I'd have to delete it by hand in the database (hints on how to best do this?)?

> See the forward extremities admin APIs: https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#forward-extremities-admin-api, you might want to delete the forward extremities (this pretty much makes an event to simplify the overall DAG, which should help with state res). It mentions reading through https://github.com/matrix-org/synapse/issues/1760 though, we should probably move the important bits of that into our documentation. cry

I deleted the "forward extremities" in the database with the postgres command from [1] and the CPU load normalized 
as well as "federation staging area events", "oldest events in staging area" and GC collection.

Tbh I still don't understand what "forward extremities" is and wasn't able to enlighten myself with a web research. I'd be really thankful if someone could enlighten me here! :)

Having this documented would be really nice! :bee: 

I'm closing the ticket. Thanks so much for your help @clokep!  :purple_heart: 

[1] https://github.com/matrix-org/synapse/issues/1760#issuecomment-379183539

**Comment by clokep** [comment]
>> Note that I don't believe setting that now will have your users leave Matrix HQ. You would want to delete the room afterward: https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#delete-room-api (please read through that first before just running the commands!)
>
> I set `complexity: 200.0`, restarted synapse but to my surprise I was still able to join Martix HQ (with an account which was never before in the room) which has a complexity > 800 (if I'm correct with states / 500 = complexity). 
>
> Any ideas why this still worked?

The setting only applies to *new* rooms, this allows admins to join rooms that are more complex and still have them work.

> Which failed after ~ 15 minutes with `{"errcode":"M_UNKNOWN","error":"Internal server error"}`.

It probably would have been better to use the `v2` version of that endpoint, which is async.

> But the data is still there:
>
> So now I'd have to delete it by hand in the database (hints on how to best do this?)?

Sounds like something in the purging broke, unfortunately. I don't have any ideas of a good way to poke at that. Most of the tables have a `room_id` column which should make it not too bad though..

> Tbh I still don't understand what "forward extremities" is and wasn't able to enlighten myself with a web research. I'd be really thankful if someone could enlighten me here! :)

I'm glad it worked for you! [Our docs](https://matrix-org.github.io/synapse/latest/development/room-dag-concepts.html#forward-extremity) have a bit of info on what a forward extremity is

> I'm closing the ticket. Thanks so much for your help @clokep!  :purple_heart: 

You're welcome!
