### ISSUE TITLE
`HTTPStatus.*` have started to appear in `Processed request` log lines instead of an integer

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#11812]
An example log line from matrix.org:

```
2022-01-24 08:10:36,396 - synapse.access.http.8080 - 445 - INFO - GET-7050353 - xxx.xxx.xxx.xxx - 8080 - {@redacted:matrix.org} Processed request: 0.296sec/0.003sec (0.007sec, 0.000sec) (0.002sec/0.288sec/2) 36141B HTTPStatus.OK "GET /_synapse/admin/v1/event_reports HTTP/1.1" "aiohttp/0.2.1" [0 dbevts]
```

This seems to currently happening for `EventReportsRestServlet`, `RoomStateRestServlet` and `RoomRestServlet`. Perhaps other endpoints are affected, but none observed in the recent logs on matrix.org.

Notice the `HTTPStatus.OK` in the logs, whereas one would expect `200`. This seems to happen as we simply cast the return code to a `str`:

https://github.com/matrix-org/synapse/blob/10a88ba91cb16ccf757984f0a7d41ddf8b4dc07f/synapse/http/site.py#L410

However, `str(HTTPStatus.OK)` unhelpfully resolves to the str `"HTTPStatus.OK"`...

This could have implications for scripts that parse Synapse logs.

**Comment by DMRobertson** [comment]
Sorry, this has my fingerprints all over it.

**Comment by DMRobertson** [comment]
`code = str(int(self.code))` would work when `self.code: int` or `self.code: HTTPStatus`. Or maybe it's just easier to ditch the status enum unilaterally?

**Comment by babolivier** [comment]
If we're starting to lean towards using `HTTPStatus`, we probably should fix the logging code rather than each individual servlet?

**Comment by anoadragon453** [comment]
`ServletCallback` is currently defined as returning and `int` when returning a status code:

https://github.com/matrix-org/synapse/blob/cbd82d0b2db069400b5d43373838817d8a0209e7/synapse/http/server.py#L202-L207

We could extend this to include `HTTPStatus`, and then update all code that interacts with it to process both correctly.

@babolivier I agree that that would probably be less things to update (and to remember) than doing `int(HTTPStatus.*)` everywhere.

**Comment by DMRobertson** [comment]
> `ServletCallback` is currently defined as returning and `int` when returning a status code:

FWIW note that `IntEnum` instances will inherit from `int`:

```py
>>> import http
>>> isinstance(http.HTTPStatus.OK, int)
True
```

**Comment by richvdh** [comment]
we've had this before, btw: https://github.com/matrix-org/synapse/issues/7017
