### ISSUE TITLE
Help admins using debs from nuking their config when upgrading

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#11841]
It sounds like people often edit `homeserver.yaml` in place. When they update to a newer release, this can get nuked if they're not sure how to interpret dpkg's "you've changed a file that's been update" message. See e.g.

* #11826
* #11238 
  > unfortunately when you search google: "matrix-synapse-py3" "registration_shared_secret"
LITERALLY all the guides have you editing the main homeserver.yaml file.
* #7222

Suggestion:
- rename `homeserver.yaml` to` homeserver.example.yaml`
- make synapse refuse to start if its config file is called `homeserver.yaml.example`
- change docs to say that you need to copy and rename `homeserver.example,yaml`

**Comment by richvdh** [comment]
I think this is basically the same as https://github.com/matrix-org/synapse/issues/8159 ?
