### ISSUE TITLE
Create a manual for config options 

### ISSUE THREAD

**Issue by H-Shay** [matrix-org/synapse#11855]
Currently we keep most of the documentation about config options as comments in the config. This may result in comments becoming out-of-date, useful configuration options being obscured, and is generally a less pleasant reading experience than a manual. It would be nice to move the documentation out of the config file and into a manual.

**Comment by richvdh** [comment]
I think this might be much the same thing as #8159 ?

**Comment by H-Shay** [comment]
You are correct, I will close this in favor of #8159.
