### ISSUE TITLE
Synapse unable to render /sync, uses 5+gib of memory

### ISSUE THREAD

**Issue by rrix** [matrix-org/synapse#1186]
taking this matrix-dev conversation to github issue: https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1477765173343911kcHUe:matrix.org

Here is my synapse log while running /sync: [sync-log.txt](https://github.com/matrix-org/synapse/files/560734/sync-log.txt)

This began happening after upgrading from 0.16.1-rc1 after realizing that I was pulling the wrong docker file. After that, per discussion in matrix-dev at the time, I was having issues with ujson segfaulting due to issues with Alpine linux. Ported my dockerfile to Fedora Container and started it, and was unable to get /sync to go without using a giant pile of RAM, and even then just barely. This week I ported to postgres after noticing my sqlite3 was 40gib (probably from keeping a few noisy IRC channels bridged, and having my RSS and Twitter bots running 24/7) but decided to port to postgres thinking that would at least help the start up times, and maybe the memory usage. It helped the former, but not the latter, and right now I am using my matrix.org HS account

**Comment by rrix** [comment]
I can enable the manhole and poke around, if given some guidance on what to do there, or turn up debug or something.

**Comment by erikjohnston** [comment]
Hmm, interesting. It would be good to know how big the total sync response is, though I guess that is hard if it OOM kills on `/sync`. Do you have any estimates as to how big (in terms of users) the IRC rooms on matrix were? And how many such rooms you had?

**Comment by rrix** [comment]
The largest room I am in is a self-hosted bridge of #emacs on freenode; I've specifically avoided rooms like #matrix:matrix.org because of these types of issues. i can probably craft some non-sync requests to get room members and such from them today

**Comment by rrix** [comment]
bad news, even a heavily filtered /sync is killing the hs

`bash-4.3$ curl -g 'https://fort.kickass.systems/_matrix/client/r0/sync?filter={"room":{"state":{"types":["m.room.member"]},"timeline":{"limit":0,"not_types":["*"]},"ephemeral":{"not_types":["*"]}},"presence":{"not_types":["*"]}}&timeout=30000&access_token={REDACTED}'`

**Comment by rrix** [comment]
apache ended up giving up on me...

```
> Host: fort.kickass.systems
> User-Agent: curl/7.47.1
> Accept: */*
> 
< HTTP/1.1 502 Proxy Error
< Date: Wed, 02 Nov 2016 03:53:34 GMT                                                                                                                                                        
< Server: Apache/2.4.10 (Debian)                                                                                                                                                             
< Content-Length: 510
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/_matrix/client/r0/sync">GET&nbsp;/_matrix/client/r0/sync</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.10 (Debian) Server at fort.kickass.systems Port 443</address>
</body></html>
* Connection #0 to host fort.kickass.systems left intact
```

**Comment by erikjohnston** [comment]
Hmm, looking at the code it appears that we do the filtering quite late in the day, so it probably won't help.

Can you see how big all your state is?:

```sql
SELECT count(*) FROM current_state_events NATURAL JOIN room_memberships;
```

**Comment by ara4n** [comment]
this got solved - it was due to heavily bifurcated state events in the DAG.
