### ISSUE TITLE
Inbound federation worker began spinning CPU after a surge in federation traffic

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#11863]
### Description

After a restart, it became fine again. I couldn't find a specific issue for "federation stops, cpu spins", so here is one.

![image](https://user-images.githubusercontent.com/2072976/151776056-baa10b45-bed4-4750-8549-64ba85ecb5dc.png)
![image](https://user-images.githubusercontent.com/2072976/151776097-2624e14d-62ce-4549-9805-1445b37c5724.png)

### Steps to reproduce

- Have a host
- Have *lots* of incoming traffic because the host runs a major IRC bridge.
- CPU spins itself to death (>100% usage)
- EDU traffic drops to near zero, reports of host feeling "broken".

### Version information

- **Homeserver**: libera.ems.host (Note, this host is only used by the bridge a.k.a all federation traffic, no sync traffic)
- **Version**: 1.50.0
- **Install method**: N/A
- **Platform**: EMS

[link to logs](https://matrix.to/#/!nYKFkxvFZqeALOpMXM:matrix.org/$DsbvGiTRTGJY1OyoK66bWxaoTHyNVUWVbgW0pTBhHaI?via=matrix.org&via=element.io&via=vector.modular.im)

**Comment by clokep** [comment]
I think this has some overlap with #11818, but I'm unsure it is an identical issue. @Half-Shot any idea if this was from the same event? Doesn't seem like it since they're a few days apart.

**Comment by Half-Shot** [comment]
It does seem to be very similar, `synapse-federation-inbound-0 _process_incoming_pdus_in_room_inner`
![image](https://user-images.githubusercontent.com/2072976/152011645-3fcff06f-6e47-43b2-95f5-8600b2d1aa1e.png)

**Comment by erikjohnston** [comment]
@Half-Shot if you still have the data can you post screen shots of the per block metrics please? That should narrow down where in the `_process_incoming_pdus_in_room_inner` code path the CPU and DB is being spent.

**Comment by Half-Shot** [comment]
Sorry, the data will have evaporated by now :(. I'll catch it next time.
