### ISSUE TITLE
Consider relaxing the requirement for synapses to know their own TLS cert

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1189]
On quick discussion with @NegativeMjark, it sounds like there may be a way to just trust the perspectives servers to track the TLS certs of federated servers, rather than the server needing to know it itself.   This would be a major improvement in UX of federation, to avoid server admins have to mess around telling synapse what its own public cert fingerprint is (or providing infrastructure to help automate that).

**Comment by Gwend4l** [comment]
Would indeed be great to be able to more easily put synapse behind a reverse proxy (eg. traefik)

**Comment by aaronraimist** [comment]
This should be fixed now

**Comment by neilisfragile** [comment]
Fixed in > Synapse 0.99.x 
https://github.com/matrix-org/synapse/blob/master/docs/federate.md for more detail
