### ISSUE TITLE
Expose whether a room is a space in the Admin API

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#11904]
Currently there is no way to tell whether a given room is a space or not through Synapse's [Admin API](https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html).

Ideally, this would be exposed in both the [List Room](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#list-room-api) and [Room Details](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#room-details-api) APIs.

I suggest to expose a `type` property which returns the room type. The type would mirror the room's `m.room.create` event's `content.type` property. For a space, as specified by [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772) as `m.space`.

**Comment by lukasdenk** [comment]
Ok, I'll work on it :)

**Comment by dklimpel** [comment]
I am not sure if the information (room vs. space) perhaps should become a attribut/column in `room_stats_state` instead read it every time from the `m.room.create` event.

**Comment by arneja-arnav** [comment]
Is this issue still open? I'd like to work on it as well.

**Comment by dklimpel** [comment]
Yes, it is still open: https://github.com/matrix-org/synapse/pull/11934#discussion_r801479728

**Comment by andrewdoh** [comment]
hi I've made the changes. could someone please check this out: [https://github.com/matrix-org/synapse/pull/13208](pull request)

**Comment by anoadragon453** [comment]
Looks like this was indeed done in https://github.com/matrix-org/synapse/pull/13208 :)
