### ISSUE TITLE
RoomHierarchyRestServlet hammers the DB way too hard

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#11919]
Looking at the resource graphs for the main synapse process on attendees.fosdem.org, by far the largest resources (by 10x) are being consumed by RoomHierarchyRestServlet, which is hammering away at get_room_version at ~75Hz, and averaging 150ms of db time per transaction:

<img width="1998" alt="Screenshot 2022-02-05 at 16 07 34" src="https://user-images.githubusercontent.com/1294269/152649327-b5a2fa42-2e66-4ada-9579-cd2a96dd7b86.png">

Feels like we're missing a cache, given the room hierarchy is hardly going to be changing much, and the room version even less(!)

**Comment by clokep** [comment]
> Looking at the resource graphs for the main synapse process on attendees.fosdem.org

Note that this API is safe to go to workers.

> Feels like we're missing a cache, given the room hierarchy is hardly going to be changing much

The hierarchy depends on the requester, so is a bit hard to cache efficiently.

> and the room version even less(!)

This is #11706 and is a regression. There's a fix at #11808.

**Comment by clokep** [comment]
Maybe related: #11694.

**Comment by clokep** [comment]
I think this was essentially a duplicate of #11706 and not specifically related to the hierarchy endpoint.
