### ISSUE TITLE
One event cannot be read by Synapse because of encodings and raise an error

### ISSUE THREAD

**Issue by anonfloppa** [matrix-org/synapse#11921]
### Description

hello, I found an event that is causing issues in Synapse.

The issue is that Synapse will raise an error when trying to decode the query result in `bg_updates.py` line `136`, I lost the stack from my logs but here is the error generated:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 21: invalid start byte`

#### update:

see this comment below: https://github.com/matrix-org/synapse/issues/11921#issuecomment-1031092418

#### or

Making a call to `_get_state_groups_from_groups` that target the room `!CCRKncVOQamqtSzFBm:matrix.org` should make it throw the error.

Compressing the states of the room with https://github.com/matrix-org/rust-synapse-compress-state should make the appropriate call and fail.

Attempting to delete the room will also fail because of this error.

To dig in the problem I did this:
 - call this API and save the result to a file: `https://matrix.homeserver.tld/_synapse/admin/v1/rooms/!CCRKncVOQamqtSzFBm:matrix.org/state?dir=b&from=0&order_by=id`

- run this command to find the culprit characters: `grep --color='auto' -P -n "[^\x00-\x7F]" dump.json`

### Version information

- **Homeserver**:

another homeserver

- **Version**:

1.51

- **Install method**:

we are using this playbook:
https://github.com/spantaleev/matrix-docker-ansible-deploy

- **Platform**:

deployed on Docker in Ubuntu LTS

**Comment by anonfloppa** [comment]
here is a stack that caused the same error as I reported but this time it's coming from federation. Our homeserver was hit with performance issues a couple days ago and the lag of PDU processing was always at its maximum in grafana. Could they be related? We were monitoring this issue for possible explanations: https://github.com/matrix-org/synapse/issues/11863 . We ended up disabling search and it seemed to have fixed the problem but there is more lag today so I am not sure.

```
Feb 06 13:07:13 localhost matrix-synapse[1894476]: The above exception was the direct cause of the following exception:
Feb 06 13:07:13 localhost matrix-synapse[1894476]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 21: invalid start byte
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     for row in txn:
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/state/bg_updates.py", line 137, in _get_state_groups_from_groups_>
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     r = func(cursor, *args, **kwargs)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 609, in new_transaction
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     return func(db_conn, *args, **kwargs)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 841, in inner_func
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     result = func(conn, *args, **kw)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     raise exception.with_traceback(traceback)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 404, in reraise
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     return function(*args, **kwargs)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     compat.reraise(excValue, excTraceback)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     return func(*args, **kw)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     result = inContext.theWork()  # type: ignore[attr-defined]
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     return await make_deferred_yieldable(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 846, in runWithConnection
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     result = await self.runWithConnection(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 741, in runInteraction
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     res = await self.db_pool.runInteraction(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/state/store.py", line 176, in _get_state_groups_from_groups
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     group_to_state_dict = await self._get_state_groups_from_groups(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/state/store.py", line 278, in _get_state_for_groups
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     group_to_state = await self.stores.state._get_state_for_groups(groups)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/state.py", line 571, in get_state_groups_ids
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     group_to_ids = await self.get_state_groups_ids(room_id, event_ids)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/storage/state.py", line 603, in get_state_groups
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     state_sets_d = await self._state_store.get_state_groups(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation_event.py", line 1481, in _check_for_soft_fail
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     await self._check_for_soft_fail(event, state, origin=origin)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation_event.py", line 991, in _process_received_pdu
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     await self._process_received_pdu(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation_event.py", line 689, in _process_pulled_event
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     await self._process_pulled_event(origin, ev, backfilled=backfilled)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation_event.py", line 636, in _process_pulled_events
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     await self._process_pulled_events(origin, missing_events, backfilled=False)
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation_event.py", line 611, in _get_missing_events_for_pdu
Feb 06 13:07:13 localhost matrix-synapse[1894476]:     await self._get_missing_events_for_pdu(
Feb 06 13:07:13 localhost matrix-synapse[1894476]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation_event.py", line 234, in on_receive_pdu
Feb 06 13:07:13 localhost matrix-synapse[1894476]: Traceback (most recent call last):
Feb 06 13:07:13 localhost matrix-synapse[1894476]: 2022-02-06 18:07:13,684 - synapse.federation.federation_server - 1074 - ERROR - _process_incoming_pdus_in_room_inner-1086 - Failed to hand>

```

**Comment by anonfloppa** [comment]
I did a lot of testing today to try to isolate an example. Here is a small script I did to reproduce the error. I believe it should work against a database that contains the event in the state_groups_state table. Since the room is from matrix, I assume you have the same data:

For reference, the row in my database look like this:
```
2180946 | !CCRKncVOQamqtSzFBm:matrix.org | m.room.member | @_oftc_MoreAxes:matri.org  | $14924279401906786iqqdK:matrix.org
```

```
import psycopg2
db_conn = psycopg2.connect(user="synapse", host="matrix-synapse", password="MY DATABASE PASSWORD", dbname="synapse")
db_conn.autocommit = True
cur = db_conn.cursor()
cur.execute("select * from state_groups_state where state_group = 2180946 and room_id='!CCRKncVOQamqtSzFBm:matrix.org' and type='m.room.member' and event_id='$14924279401906786iqqdK:matrix.org';")
next(cur)
```

The script produce the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 21: invalid start byte
```

**Comment by clokep** [comment]
I looked a bit, but did not see any similar errors on matrix.org. A couple of questions:

* Do you know if this database was originally sqlite and then converted to postgres?
* Can you double check that collate and locale are both set to `C`? (See [here](https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database) and [here](https://matrix-org.github.io/synapse/latest/postgres.html#fixing-incorrect-collate-or-ctype).)

**Comment by anonfloppa** [comment]
> Do you know if this database was originally sqlite and then converted to postgres?
the database was always postgresql, it was not converted from sqlite.

I also encountered this error while running the migration of the database from postgres 13 to 14 using this script https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/maintenance-postgres.md#upgrading-postgresql . The error occured during the importation of the backup in the newly upgraded database:

```
start: '2022-02-06 22:04:54.425670'
  stderr: |-
    ERROR:  invalid byte sequence for encoding "UTF8": 0xc7 0x57
    CONTEXT:  COPY device_inbox, line 14387222
```

> Can you double check that collate and locale are both set to C? (See [here](https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database) and [here](https://matrix-org.github.io/synapse/latest/postgres.html#fixing-incorrect-collate-or-ctype).)

I will check later and come back to you but the database was created with this script https://github.com/spantaleev/matrix-docker-ansible-deploy

**Comment by squahtx** [comment]
> For reference, the row in my database look like this:
> 
> ```
> 2180946 | !CCRKncVOQamqtSzFBm:matrix.org | m.room.member | @_oftc_MoreAxes:matri.org  | $14924279401906786iqqdK:matrix.org
> ```
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 21: invalid start byte
> ```

The "x" in `@_oftc_MoreAxes:matri.org` has gone missing or isn't rendering correctly in your database row.
Coincidentally, the error is complaining about an 0xF8 byte, while the "x" would have been an 0x78. That's a difference of 0x80, or one bit.

I suspect you've got failing RAM or storage, or your database is corrupt.

**Comment by anonfloppa** [comment]
@squahtx that's a very insightful way to explain the problem. Wow! :heart_eyes: 

It make sense that the problem is hardware-related. I run memtester the other day on the server and saw a ton of errors. It seem to be solved for now. I hope our database is not too corrupt.

@clokep for the sake of completion and for everyone coming across this thread I did check the database and it's configured correctly:

```
synapse=# SELECT datcollate FROM pg_database WHERE datname = current_database();
 datcollate 
------------
 C
(1 row)

synapse=# SELECT d.datname, pg_[catalog.pg](http://catalog.pg/)_encoding_to_char(d.encoding) as "Encoding" FROM pg_database d WHERE datname = current_database();
 datname | Encoding 
---------+----------
 synapse | UTF8
(1 row)
```

Gonna be closing this issue now.
