### ISSUE TITLE
Exception during startup - '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by HarlekinSimplex** [matrix-org/synapse#11920]
### Description
Synapse startup fails during initial installation right after the postgresql database schema has been created.

### Steps to reproduce
- Create a new database container
- Drop default database
- Create a new database
createdb -U <dbuser> --encoding=UTF8 --locale=C --template=template0 --owner=<db_owner> <db>
(was require because intial db is created with wrong locale)
- Startup Synapse container
Startup terminated with the following error:
`2022-02-05 20:10:16,457 - synapse.app._base - 195 - ERROR - main - Exception during startup
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 394, in setup
     hs.setup()
   File "/usr/local/lib/python3.8/site-packages/synapse/server.py", line 315, in setup
     self.datastores = Databases(self.DATASTORE_CLASS, self)
   File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/__init__.py", line 80, in __init__
     database = DatabasePool(hs, database_config, engine)
   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 415, in __init__
     self._db_pool = make_pool(hs.get_reactor(), database_config, engine)
   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 111, in make_pool
     connection_pool = adbapi.ConnectionPool(
   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 223, in __init__
     self.min = min(self.min, self.max)
 TypeError: '<' not supported between instances of 'str' and 'int'
  Error during initialisation:
     '<' not supported between instances of 'str' and 'int'

Expected behavior would be same like with sqlight db.
Container should start up without error.

### Version information
PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
Synapse image:
    image: matrixdotorg/synapse:latest, Build Docker on linux, amd64, 2022-01-25 13:57:29

- **Homeserver**:
My own server setup

- **Install method**:
docker-compose

- **Platform**:
Debian GNU/Linux 10 (buster)

**Comment by reivilibre** [comment]
Please can you share your database configuaration (without the password of course! :)).

I suspect that the problem is with `cp_min` and `cp_max`: one of them might be a string?

**Comment by reivilibre** [comment]
@HarlekinSimplex are you still having this issue? / does the above help you out?

**Comment by reivilibre** [comment]
Closing as no response
