### ISSUE TITLE
Add direction parameter to `/relations` api

### ISSUE THREAD

**Issue by ismailgulek** [matrix-org/synapse#11926]
**Description:**

When we load a context around an in-thread event, we want to paginate backwards and forwards from there and load older and newer messages in a thread, respectively. We have a `dir` parameters in `/messages` [api](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidmessages) to paginate in both directions in a room timeline. We need something similar for `/relations api` to achieve the same thing on a thread timeline.

**Comment by clokep** [comment]
This was discussed a little bit in the MSC: https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r770568774

https://github.com/uhoreg/matrix-doc/commit/6a76e5c324da142e7c8a2782cd129b5d89151de6 might be vaguely related to this, but was essentially undone via https://github.com/uhoreg/matrix-doc/commit/bcf7d15fc0ae6b1c01e857ff7487c91af8ea1c21.

[MSC2946 says](https://github.com/matrix-org/matrix-doc/blob/main/proposals/2675-aggregations-server.md#querying-relations) this API is meant to act the same as `/messages`, maybe it was just an oversight that `dir` was not included?

**Comment by clokep** [comment]
[matrix-org/matrix-doc@`8e532ac` (#2675)](https://github.com/matrix-org/matrix-doc/pull/2675/commits/8e532ac1e2cfbf978223aa11e7644e1408c26521) seems to have removed the reference to `dir`, maybe based on the conversation at https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r549214955

**Comment by clokep** [comment]
So the result of this is that this is "as-specced" from MSC2675, but I wrote MSC3715 to add them.
