### ISSUE TITLE
is thera an Admin interface?

### ISSUE THREAD

**Issue by FlyingHarman** [matrix-org/synapse#11932]
**Description:**

Admin account could log on interface instead of command line
for user management, registration rules(email,password rule) etc 
that's so convenience

**Comment by dklimpel** [comment]
Have a look at #2032

**Comment by babolivier** [comment]
Synapse doesn't ship with an admin interface. https://github.com/Awesome-Technologies/synapse-admin exists as an unofficial admin UI for Synapse that uses the admin API.
By the way, we don't use this repository for support requests, as stated in the readme and the issue template, only for bug reports and feature requests. For support requests, please visit [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org).
