### ISSUE TITLE
bot join room to record shared contents, prevent organization content to leak.

### ISSUE THREAD

**Issue by soloturn** [matrix-org/synapse#11947]
following up on #4367, which asks to disable encryption for rooms created on a company homeserver. anybody of you knows examples how to tackle the challenge different, logging in a bot which saves the conversation it receives? so it is transparent to other users this thing records what they do?

**Comment by babolivier** [comment]
Hey @soloturn, and thanks for your interest in Synapse! Heads up we don't use GitHub issues for support requests, only for bug reports and feature requests. For support, I'd highly recommend asking in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org).

**Comment by soloturn** [comment]
i tried to as in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org), but no answer. you mind making it a feature request?

**Comment by babolivier** [comment]
This doesn't really fit as a Synapse feature imo. It would be more something that would exist as its own project as a Matrix bot (Synapse is a Matrix homeserver, not a bot framework).
