### ISSUE TITLE
wheel package required to run thumbnail unit tests on Debian

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#11959]
wpcmalih in #synapse-dev [mentioned](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$wsWhX3xVPWwamKlPub0TjuBBd3MTUqxewUwHC2KZbVc?via=matrix.org&via=element.io&via=vector.modular.im) that the following tests were failing for them:

```
tests.rest.media.v1.test_media_storage.MediaRepoTests_2.test_thumbnail_crop
tests.rest.media.v1.test_media_storage.MediaRepoTests_2.test_thumbnail_repeated_thumbnail
tests.rest.media.v1.test_media_storage.MediaRepoTests_2.test_thumbnail_scale
```

They had `libwebp-dev` installed on their Debian system, and executed the following code:

```
$ python
>>> from PIL import features
>>> print (features.check_module('webp'))
True
```

which indicates webp support was enabled in Pillow (using the same Python environment). But maybe it was somehow using a linked on?

They were receiving the following error:

```
error: invalid command 'bdist_wheel'

Failed to build pillow msgpack jaeger-client matrix-synapse-ldap3 opentracing psycopg2 cffi threadloop thrift click-default-group
flake8 4.0.1 has requirement importlib-metadata<4.3; python_version < "3.8", but you'll have importlib-metadata 4.10.1 which is incompatible.
mypy 0.910 has requirement typed-ast<1.5.0,>=1.4.0; python_version < "3.8", but you'll have typed-ast 1.5.2 which is incompatible.
```

However, installing `wheel` allowed Pillow to build in the python environment, and the tests started to pass.

If I had to guess - the system's Pillow installation was being used before Pillow could be installed in the virtual environment. But that doesn't explain why the tests failed even though webp support was available.

Actions:

* Start with a fresh Debian system
* Try to get the unit tests running with [our given installation instructions](https://matrix-org.github.io/synapse/latest/setup/installation.html#debianubunturaspbian).
* Determine whether any more python dependencies than listed are needed to get the tests running. If more platform-specific dependencies are needed, it'd be nice to update the documentation.

**Comment by clokep** [comment]
Seems related to the conversation at https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$wsWhX3xVPWwamKlPub0TjuBBd3MTUqxewUwHC2KZbVc?via=matrix.org&via=element.io&via=vector.modular.im

**Comment by richvdh** [comment]
should probably add some notes to https://github.com/matrix-org/synapse/blob/master/README.rst#synapse-development

**Comment by richvdh** [comment]
presumably this is no longer a problem, now that we recommend setting up the environment using poetry.
