### ISSUE TITLE
Roles/Labels/tags for members in rooms

### ISSUE THREAD

**Issue by ARtSSt** [matrix-org/synapse#11957]
1. Custom Roles/Labels for member in the Room, supports custom group notifications. 

2. Labels/Tags for content deemed related to a theme to support faster search in long threads with many members. 

Discord has role methods to be able to assign members to sub groups to ping just those necessary for specific topics. 

(@.1) Implement a system to have member roles/labels where all assigned have an @"role" ping for notifications and searchable history around that role/label. 

(@.2) Allow content on a subject to be tagged or labeled to support search in long threads. (much like github labels) (@.2)

**Comment by babolivier** [comment]
Hi @ARtSSt, and thanks for your interest in Synapse!
Most features in Synapse are governed by the [Matrix specification](https://spec.matrix.org), and this would be very much the case for the features you're describing, so a specification change would be required before Synapse could implement such a feature. I'd recommend discussing this in the [`#matrix-spec:matrix.org`](https://matrix.to/#/#matrix-spec:matrix.org) room, which is dedicated to discussions about the Matrix specification.
