### ISSUE TITLE
Module API `user_may_create_room_with_invites` is not documented

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#11958]
Seems to be missing from https://matrix-org.github.io/synapse/latest/modules/spam_checker_callbacks.html

**Comment by Half-Shot** [comment]
Oh I suppose if it's being removed, then it's not worth documenting https://github.com/matrix-org/synapse/pull/11950

**Comment by babolivier** [comment]
Yeah, https://github.com/matrix-org/synapse/pull/11206 removed the deprecation along with deprecating it so people don't feel encouraged to use it.
