### ISSUE TITLE
Consider using the "ignored_users" database table when filtering client events

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#11964]
When ignoring a user, clients modify a `m.ignored_user_list` key in their account data ([spec](https://spec.matrix.org/v1.2/client-server-api/#ignoring-users)). Synapse will detect if this is happening, and modify an equivalent database table named `ignored_users`. The idea is that the database table is faster to read from than digging the value out of account data.

The table is used when calculating bulk push rules:

https://github.com/matrix-org/synapse/blob/10a88ba91cb16ccf757984f0a7d41ddf8b4dc07f/synapse/push/bulk_push_rule_evaluator.py#L212-L216
https://github.com/matrix-org/synapse/blob/af795173bec447da44b65b739d05d0083b02229d/synapse/storage/databases/main/account_data.py#L367-L385

Yet it is not used when ignored users are considered while filtering events for clients (i.e. for `/sync`):

https://github.com/matrix-org/synapse/blob/64ec45fc1b0856dc7daacca7d3ab75d50bd89f84/synapse/handlers/sync.py#L1613-L1634
https://github.com/matrix-org/synapse/blob/4c2096599c9780290703e14df63963e77d058dda/synapse/visibility.py#L89-L91

I'm not sure how much of an optimisation this would really be (as `get_global_account_data_by_type_for_user` is cached on key (`user_id`, `account_data_type`)). In addition, we'd need an index of the `ignorer_user` column, which doesn't currently exist.

On the flip side - it is a nice idea to consolidate where we pull this information from.

**Comment by clokep** [comment]
> On the flip side - it is a nice idea to consolidate where we pull this information from.

I think another nice benefit is that you don't need to do the error checking (of ensuring it is a dict, etc.)

**Comment by clokep** [comment]
I'm going to look at this in light of #11753 poking a bit at ignored users too.
