### ISSUE TITLE
Expose other worker types as console_scripts

### ISSUE THREAD

**Issue by f0x52** [matrix-org/synapse#11993]
[Currently](https://github.com/matrix-org/synapse/blob/develop/setup.py#L154-L159) only the synapse_homeserver (`app.homeserver:main`) and synapse_worker (`app.generic_worker:main`) binaries get generated and added to PATH by setuptools. 
It would be nice to have executables in path to start the other types of workers as well, like `pusher`, `appservice` and `federation_send`.

This could be done through `console_scripts` definitions for each, or a more generic synapse_worker(s) script that allows you to choose the kind of worker you want to start with a flag.

**Comment by richvdh** [comment]
It'd be better to spend this work on getting rid of the dedicated types of workers (https://github.com/matrix-org/synapse/issues/10441).

**Comment by richvdh** [comment]
Agreed, the workers documentation is sorely lacking: https://github.com/matrix-org/synapse/issues/9072.

I'm going to go ahead and close this since it seems the original issue is resolved.
