### ISSUE TITLE
Have a restrictive default limit on user registration

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12002]
something identified as being helpful in countering abuse: most servers have no need to allow large numbers of users to register. The default config could be quite restrictive.

**Comment by GAURAV1-ui** [comment]
i want to review this bug. Please assign me this bug.

**Comment by richvdh** [comment]
Contributions are welcome

**Comment by GAURAV1-ui** [comment]
Can you help me how can I contribute. I am beginner.

**Comment by richvdh** [comment]
An alternative suggestion: refuse to start if registration is enabled without captcha and/or email verification, unless you set an `i want to spam the federation` flag

**Comment by reivilibre** [comment]
Other thoughts: can we 'encourage' use of token-based registration by default?

**Comment by callahad** [comment]
Sounds like what we want to do is refuse to start up with open registration unless ReCaptcha or email verification has been enabled. We also want to provide a config flag to override this for administrators that _want_ to have unrestricted registration, but we should be defaulting to a safe configuration.
