### ISSUE TITLE
Remove legacy structured logging configuration

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#12006]
See [`setup_structured_logging`](https://github.com/matrix-org/synapse/blob/bf72d10dbf506f5ea486d67094b6003947d38fb7/synapse/logging/_structured.py#L136) and the helpers it uses (bits about `drains` and such). There are also some bits in the documentation.

**Comment by clokep** [comment]
Looks like we deprecated this in v1.23.0:  https://matrix-org.github.io/synapse/latest/upgrade.html#structured-logging-configuration-breaking-changes

**Comment by clokep** [comment]
I'm going to re-open this, we should remove the upgrade docs at some point in the future (maybe in 1.56?)

**Comment by MadLittleMods** [comment]
@clokep giving this a ping because [`1.56.0`](https://github.com/matrix-org/synapse/releases/tag/v1.56.0) was just released 🙇

**Comment by clokep** [comment]
Thanks for the reminder!
