### ISSUE TITLE
purge_history api does not delete media

### ISSUE THREAD

**Issue by SPiRiT369** [matrix-org/synapse#12046]
I want to delete old room messages. (unencrypted room)

I use purge_history call (/_synapse/admin/v1/purge_history/<room_id>) and it does the work. However, if the deleted events contain uploaded media - they are removed from the room but not from the disk.

Please fix it so purge_history will also delete files from disk.

A workaround for this issue could be to use the delete media api, but it works on all rooms, and I want to clean history on specific rooms only.

**Comment by dklimpel** [comment]
IMO this is not possible. Purge history deletes also encrypted events. And the server does not know the content / media files of this event.
Also you can use a media in multiple events.

**Comment by SPiRiT369** [comment]
If the room is unencrypted then it's possible to delete those files I think. Because it's possible to list room media via api.

**Comment by dklimpel** [comment]
Related #10176

**Comment by SPiRiT369** [comment]
It is not related. It's for empty rooms. I am speaking about active rooms that I want to clean old messages in them.

**Comment by richvdh** [comment]
The difficulty here is that media is not particularly linked to a specific event (or even room): there is nothing to say a single media url has not been used in multiple places.

This is covered by a range of existing issues, such as https://github.com/matrix-org/synapse/issues/1263, https://github.com/matrix-org/synapse/issues/6832, https://github.com/matrix-org/matrix-doc/issues/701, https://github.com/matrix-org/matrix-doc/pull/2278

**Comment by SPiRiT369** [comment]
Oh @richvdh thank you for this info. I didn't know that it's a duplicate. Sorry for creating another one.
At least it's a known issue. I hope it will be solved somewhere soon. Synapse leaves too much storage junk 😕
Thanks again.
