### ISSUE TITLE
Proxy settings have no effect when Synapse is running as a Docker container.

### ISSUE THREAD

**Issue by YamatoRyou** [matrix-org/synapse#12044]
### Description
This issue prevents iOS devices from receiving push notifications.

### Steps to reproduce
1. Add an environment variable "HTTP_PROXY" to the Synapse container, and fill in the proxy address;
![{A6BEC8A6-4B0D-637C-131C-43F49FD93106}](https://user-images.githubusercontent.com/48104960/154784607-bf32e4e3-fc74-4358-b18c-614d937befcd.png)

2. Restart the Synapse container;
3. Execute the command using the container's shell: `curl https://matrix.org/_matrix/federation/v1/version`
4. Since matrix.org is blocked in my region, curl will output an error at this point;
![{9D0B216B-D6EE-1019-9E60-991DF76E6BFD}](https://user-images.githubusercontent.com/48104960/154784615-e430ee3b-8f19-45da-96c3-13585e250baf.png)

5. To confirm that it is not a proxy server problem, execute the command again using the container's shell, but this time with additional parameters to use the proxy server: `curl --proxy http://127.0.0.1:8081 https://matrix.org/_matrix/federation/v1/version`;
6. At this point curl will output a JSON, indicating that the connection is successful.
![{DF349407-E7CD-FA8C-79F7-235973219477}](https://user-images.githubusercontent.com/48104960/154784623-7f0e9ece-371d-4337-ad42-a2e9d3718db6.png)

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: n/a

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.52.0

- **Install method**: Docker (version 20.10.3, host network)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Synology DSM (Linux kernel 3.10.102 x86_64)
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by cksit** [comment]
Hello, it seems you installed the matrix in Synology DSM? could you mind sharing the installation steps or the reference you used. Such that I can try it by myself?

**Comment by squahtx** [comment]
@YamatoRyou If both `HTTP_PROXY` and `HTTPS_PROXY` are set, does it work?

**Comment by YamatoRyou** [comment]
> @YamatoRyou If both `HTTP_PROXY` and `HTTPS_PROXY` are set, does it work?

I changed `HTTP_PROXY` to `HTTPS_PROXY`, problem solved.
