### ISSUE TITLE
Apparent memory leak with `use_presence` option

### ISSUE THREAD

**Issue by hyossing** [matrix-org/synapse#12053]
Hello,

### Description
GC(Garbage Collection) time increases unbounded for specific config in homeserver.yaml.

```
use_presence: False
```
Our running synapse's `homeserver.yaml` is quite old, so we just keep the `use_presence` options.
Then,

<img width="703" alt="Screen Shot 2022-02-22 at 7 08 10 AM" src="https://user-images.githubusercontent.com/5966376/155034526-e3b74150-fead-47f2-9f38-861f29232710.png">

In my opinion, the gc time increase more as requests are increases.

It is not easy to catch the problem, because It is a kind of aging issue.
- Restarting synapse solve the problem because leaked memory is gone.

So, it took a time to know about it.

If we set the settings to the latest, then the unbounded increase is not appear anymore.
```
# Presence tracking allows users to see the state (e.g online/offline)
# of other local and remote users.
#
presence:
  # Uncomment to disable presence tracking on this homeserver. This option
  # replaces the previous top-level 'use_presence' option.
  #
  # enabled: false

  # Presence routers are third-party modules that can specify additional logic
  # to where presence updates from users are routed.
  #
  presence_router:
    # The custom module's class. Uncomment to use a custom presence router module.
    #
    #module: "my_custom_router.PresenceRouter"

    # Configuration options of the custom module. Refer to your module's
    # documentation for available options.
    #
    #config:
    #  example_option: 'something'
```

### Steps to reproduce
[Archive.zip](https://github.com/matrix-org/synapse/files/8112562/Archive.zip)

1. unzip
2. > yarn install
3. > docker-compose up -d
4. create postgresql database
- CREATE DATABASE synapse ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0
6. access grafana - http://localhost:3000
7. import synapse dashboard and check it does work. - synapse_rev1.json
8. > node synapse-gc-test.js
- Run the script one or two days, then check the GC time increase.

Thanks you.
Hyosung

**Comment by erikjohnston** [comment]
Thanks, do you see an increase in memory usage too? This may be due to caches slowly filling up, so you may see this fixed if you enable time based expiry for caches (which is enabled by default in v1.53.0). Not *all* caches are affected by time based expiry, so please let us know if time based expiry fixes this issue.

**Comment by hyossing** [comment]
Hello,

I'll test the new config `expiry_time` for the GC time issue.

Let you know the result.

Thanks you.

**Comment by hyossing** [comment]
Hello,

I've tested it. 

However,  It is the same.

In my opinion, the `use_presence` options cause the problem.

Please, deprecate the option.

<img width="1444" alt="Screen Shot 2022-03-08 at 3 52 01 PM" src="https://user-images.githubusercontent.com/5966376/157182954-7137c139-3f15-4194-9329-3e41fca16aee.png">

<img width="1425" alt="Screen Shot 2022-03-08 at 3 53 27 PM" src="https://user-images.githubusercontent.com/5966376/157183125-b158b5d2-aaec-4e58-b9ee-46722dfca213.png">

**Comment by erikjohnston** [comment]
Oh, hmm. I wonder if its because we've disabled time based expiry for the caches for `get_users_in_room` and `get_users_who_share_room_with_user`. In the caches section do you see those caches increasing in size?

**Comment by hyossing** [comment]
I didn't see that.

<img width="1424" alt="Screen Shot 2022-03-10 at 4 37 51 AM" src="https://user-images.githubusercontent.com/5966376/157519390-10b1ac22-2e5c-458d-9776-9086d845197a.png">

My test code does just send-to-device and sync to get it.

Only, device_inbox is used.

Thanks you.

**Comment by erikjohnston** [comment]
Oh, that is very interesting. Looks like my assumption that it was due to caches is wrong.

Can i ask what your test code does? Does it create lots of new users? Maybe the data leak is we're storing a presence update for each new user forever?

**Comment by hyossing** [comment]
Hello,

My test code is on the top of the comments in this issue. (Archive.zip)
- https://github.com/matrix-org/synapse/issues/12053#issue-1146291748

I explained how to reproduce the issue.

Thanks you.

**Comment by erikjohnston** [comment]
This is likely fixed by https://github.com/matrix-org/synapse/pull/12213, which is in v1.58.0
