### ISSUE TITLE
Abort startup if unsafe DB locale

### ISSUE THREAD

**Issue by JanZerebecki** [matrix-org/synapse#12055]
### Description

From https://github.com/matrix-org/synapse/issues/10718 :

> > Perhaps instead of a warning that should be made to abort startup unless a new setting `corrup_my_db_silently_on_libc_update: true` is set.
> 
> We're fine going with this approach to at least help people avoid silent corruption... details tbd.

We should probably also add the commands needed to drop the broken data from a DB to https://matrix-org.github.io/synapse/latest/postgres.html#fixing-incorrect-collate-or-ctype and also add:

> We should also probably link to information on how Glibc collation changes can break PostgreSQL. E.g., https://wiki.postgresql.org/wiki/Locale_data_changes

### Steps to reproduce

- have DB use wrong locale
- update libc with locale change
- notice corrupt DB

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? 
- **Homeserver**:

If not matrix.org:
-->
<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: seen e.g. on 1.41.0, but bug exists before and after

- **Install method**: any
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Linux glibc
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by erikjohnston** [comment]
It's worth noting that we should abort for *new* deployments.

But I agree that we may want to start being more aggressive to try and force existing deployments to fix themselves.

**Comment by JanZerebecki** [comment]
It is also worth it for existing deployments, because it happens that this becomes wrong after system upgrades (of the DB machines, not necessarily the same machines that are running synapse), DB upgrades or DB migrations.
My idea was not to force them, but require acknowledgement from an administrator by setting a configuration setting, which we should mention in the error message when aborting. As I know of multiple people, myself included, who didn't catch the warning in the log.

**Comment by johansmitsnl** [comment]
A live upgrade would be done like this?:

```sql
update pg_database set datcollate='C', datctype='C' where datname='synapse';
REINDEX DATABASE synapse;
```

**Comment by callahad** [comment]
It may be worth linking to https://wiki.postgresql.org/wiki/Locale_data_changes and https://wiki.postgresql.org/wiki/Collations which have in-depth treatment of the issues which can occur when glibc updates its locale data, and what to do about them.
