### ISSUE TITLE
Change latest_event format in thread bundled relationship

### ISSUE THREAD

**Issue by gsouquet** [matrix-org/synapse#12085]
We need to send down `ClientEventWithoutRoomID` rather than `ClientEvent` to be consistent with the event format that comes down `/sync` as [discussed in the thread MSC](https://github.com/matrix-org/matrix-doc/pull/3440/files#r812880226)

**Comment by clokep** [comment]
Hm, I think we're not passing forward the `event_format` used to where we serialize this event. Should be straightforward.
