### ISSUE TITLE
Option to have fallback accounts

### ISSUE THREAD

**Issue by TheEvilSkeleton** [matrix-org/synapse#12095]
**Description:**

At the moment, there are no "fallback" accounts on Matrix. So, if your current instance has an outage or other reasons that lead to it being nonoperative, then you'll have to wait until the instance is back up and/or will have to sign in to another account to temporarily chat without your chat history.

I'd like to have an option where you can setup fallback account(s). This makes it a lot more convenient and reliable for the end user because you will still be able to use your account and chat with others without being interrupted. At the moment, I use the `fedora.im` homeserver. If, for example, fedora.im has an outage, then it falls back to matrix.org or another desired instance, making me enjoy the platform without interruption.

**Comment by reivilibre** [comment]
It's not clear what exactly you had in mind when writing about 'fallback accounts', but I think MSC2787: https://github.com/matrix-org/matrix-doc/pull/2787 would probably satisfy your wishes.

As far as I know, it's a prerequisite for usable peer-to-peer Matrix so I would expect to see this eventually, but I couldn't tell you how soon.

**Comment by reivilibre** [comment]
Closing as I think that answers your question — if not, can reopen.

**Comment by TheEvilSkeleton** [comment]
Sorry for not replying, I forgot. This answered my question, you can also mark it as a duplicate.

Thanks!
