### ISSUE TITLE
Redacted events leaked via the latest event in a thread

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#12104]
If the latest event in a thread is redacted, the unredacted content can be leaked via the bundled aggregation (until it is removed from the database).

This only occurs in MSC3440 support is enabled on the server.

**Comment by clokep** [comment]
Reporte dby @ariskotsomitopoulos.

**Comment by ariskotsomitopoulos** [comment]
### Steps to reproduce

1. Send a message
2. Reply to ^ message in a thread
3. Send some more messages in the thread
4. Delete the latest message

MSC3440 **/messages** for **io.element.thread** relations will return the deleted event in the thread summary

**Comment by clokep** [comment]
Thanks! This seems to be due to some sort of cache invalidation issue.
