### ISSUE TITLE
Add tests for or prevent non-member events in `state_events_at_start` in MSC2716 batch sending

### ISSUE THREAD

**Issue by tulir** [matrix-org/synapse#12110]
Synapse 1.53 broke this branch of batch sending: https://github.com/matrix-org/synapse/blob/v1.53.0/synapse/handlers/room_batch.py#L232-L253

#12083 seems to somehow fix it, but the feature should get some tests or be removed entirely.

**Comment by MadLittleMods** [comment]
Closing as https://github.com/matrix-org/synapse/pull/12329 was merged to fix this use case in Synapse and Complement tests added in https://github.com/matrix-org/complement/pull/354
