### ISSUE TITLE
Getting table names.

### ISSUE THREAD

**Issue by gauravsanas88** [matrix-org/synapse#12125]
**Hello, I am implementing an system using matrix-synapse. But I want to know which database tables are used at the time of new user registration on matrix in homeserver.db file.**

**Any idea how can get the same?**

**Comment by reivilibre** [comment]
What are you trying to do?

`users` is the main table touched by registration of a user, but there are other ones too.

I would suggest that poking around the database is discouraged and ideally consider the [Admin API](https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html) for any of the tasks you need.
There are tools around for this kind of thing too; ask in #synapse:matrix.org and I'm sure people will tell you about them.

**Comment by reivilibre** [comment]
Closing due to no response.
