### ISSUE TITLE
`parse_and_validate_server_name(":80")` raises `IndexError` instead of `ValueError`

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#12122]
Currently `parse_server_name("")` raises a ValueError by accident, while `parse_server_name(":80")` returns `("", 80)`.
The latter causes `parse_and_validate_server_name` to raise an IndexError when it tries to inspect the first character of the hostname.

As part of the fix, we should make `parse_server_name` behave consistently. Either `parse_server_name("")` should return `("", None)`, or `parse_server_name(":80")` should raise a ValueError.

I'm mildly in favor of the former, since in all other cases `parse_server_name` behaves like a hostname-port splitter without regard for the validity of the hostname.

https://sentry.matrix.org/sentry/synapse-matrixorg/issues/231342/
https://sentry.matrix.org/sentry/synapse-matrixorg/issues/242910/
https://sentry.matrix.org/sentry/synapse-matrixorg/issues/197400/

**Comment by mmequignon** [comment]
hello, I opened a PR for this here https://github.com/matrix-org/synapse/pull/12167
