### ISSUE TITLE
Stabilize support for MSC3440: thread relation

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#12148]
[MSC3440](https://github.com/matrix-org/matrix-doc/pull/3440) is currently in a final comment period. We'll need to make a few tweaks to stabilize support for it:

* [x] Use the proper serialization configuration: #12085
* [x] Support stable identifiers:
	* `io.element.relation_senders` -> `related_by_senders`
	* `io.element.relation_types` -> `related_by_rel_types`
	* `io.element.thread` -> `m.thread`
* [ ] Remove experimental configuration flag and unstable identifiers.

We'll probably want to overlap support of stable & unstable identifiers for a couple of releases.

See also: #11753.

**Comment by clokep** [comment]
See also a cache invalidation bug with thread summaries: #12104

**Comment by Nira34** [comment]
https://matrix.org/

**Comment by clokep** [comment]
Support for the unstable identifiers will be dropped in v1.58.0. Note that this will cause old clients to fallback to their local-only implementation of unstable threads, but this should be fine since people will eventually update to stable threads / clients.
