### ISSUE TITLE
RC versions of dependencies don't satisfy the run-time dependency checker; `Need Twisted>=18.9.0, but got Twisted==21.7.0rc3` (1.54.0rc1 suspected regression)

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#12176]
When deploying `1.54.0rc1` to matrix.org and some personal homeservers that had an RC of Twisted installed, the dependency checker complained:

`Need Twisted>=18.9.0, but got Twisted==21.7.0rc3`

For some reason it appears that being an RC makes the version insufficient, even though the version is higher. Using the non-RC version works fine.

Possibly fall-out from https://github.com/matrix-org/synapse/pull/12088?

I wonder if the same logic as e.g. `pip` is being used, in that it would never select an RC version as being satisfactory unless it was a hard match?

**Comment by H-Shay** [comment]
Since the fix to this has merged I am going to close this issue.
