### ISSUE TITLE
Tweak Sign In With Apple/SSO copy to make required data explicit

### ISSUE THREAD

**Issue by nadonomy** [matrix-org/synapse#12205]
![d84f2561-607c-45f2-9d43-35c1784e7cca_005](https://user-images.githubusercontent.com/4626865/157723026-0e224f19-2e07-445d-b628-4fec50cd11a7.png)

Above is a screenshot of what users see today after tapping 'Sign In With Apple' (SIWA) in iOS. According to [Apple's guidelines](https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/data-management/), we need to make explicit the data is required vs an optional request.

- [ ] When using SIWA, update the headline copy
         from 'Your account is nearly ready'
         to 'Choose your account name'
- [ ] When using SIWA, update the byline copy
         from 'Check your details before creating an account on server'
         to 'This is required to create your account, and you can't change this later.'
- [ ] When using SIWA, prefill the username with whatever Apple has passed us

**Comment by nadonomy** [comment]
I'd also welcome us changing the copy generically if that's the preferred path to avoid special casing this for one SSO provider.

**Comment by babolivier** [comment]
> I'd also welcome us changing the copy generically if that's the preferred path to avoid special casing this for one SSO provider.

This is a generic page (not special-cased to Apple, the logo is just templated in), so if we change the copy there the change will propagate across all of the SSO providers
