### ISSUE TITLE
Hide local user login via config when using SSO

### ISSUE THREAD

**Issue by decentral1se** [matrix-org/synapse#12214]
**Description:** 

When using SSO as only sign-in method, having the local login confuses users. E.g. on mobile, they need to scroll down and see the "log in with ... " SSO buttons and use those. Overriding templates only for this is inconvenient, especially when using a Docker deployment which relies on mounting in additional files. 

![image](https://user-images.githubusercontent.com/1991377/158067718-7522bdf2-e4c6-4c66-be7c-24e77ebdec5e.png)

In this image the SSO buttons are missing images for unknown reasons... but you get the idea :)) It would be ideal if clients could respond to a "hide local login" config knob and then make that happen on the client side of things. I'm using Element myself.

Following the config in https://matrix-org.github.io/synapse/latest/sample_config.yaml, I think a `hide_local: true/false` might fit under the `sso: ...` stanza as it matches the description of "Additional settings to use with single-sign on systems such as OpenID Connect ...".

**Comment by clokep** [comment]
I think you're trying to disable password logins?

That is already possible in the `password_config` section of the configuration, see https://github.com/matrix-org/synapse/blob/b1989ced00cc0bc6214bfd1a393c7e8f8eda660c/docs/sample_config.yaml#L2152-L2161

**Comment by decentral1se** [comment]
Yes @clokep thanks very much, that was it indeed :partying_face: Apologies for the noise.
