### ISSUE TITLE
`check_username_for_spam`'s documentation incorrectly claims that `avatar_url` and `display_name` are never `None`

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#12245]
### Description

The Synapse documentation claims that the `check_username_for_spam` spam checker callback receives a `userprofile` that is a `Dict[str, str]`. In practice, there can be `None`s in the `userprofile` dict, eg.
```py
{
    avatar_url: None, 
    display_name: None, 
    user_id: '@[redacted]:matrix.org'
}
```

See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/243697/ for examples of `userprofile`s with missing avatars and display names.

`docs/modules/spam_checker_callbacks.md` and `CHECK_USERNAME_FOR_SPAM_CALLBACK` could do with an update.

**Comment by DMRobertson** [comment]
We didn't detect this because the function which fetches the data from the db is annotated to return JsonDict.

I would really like a systematic approach to catch this kind of thing.
