### ISSUE TITLE
Update SSO template headline

### ISSUE THREAD

**Issue by nadonomy** [matrix-org/synapse#12259]
Apologies I missed submitting this while reviewing in GitHub (PEBKAC):

https://github.com/matrix-org/synapse/pull/12210/files/be023cad8c82149a60d30c09c9897392876f036d#diff-6360959f39ea2113790941f7332d3511bf4a9667659e7710c8e60a253b227563

The h1/headline in the SSO template should be 'Choose your account name' not 'Choose your user name'.

**Comment by callahad** [comment]
This is a fixup / refinement to #12210.

Let's get it into the 1.55 final, so we don't have to tweak that text twice in subsequent releases.

**Comment by babolivier** [comment]
Ah, sorry. That was deliberate because an "account name" doesn't mean anything to me as a user (but "user name" does). But fair enough if that doesn't make sense.

**Comment by nadonomy** [comment]
@babolivier For ref we're navigating Apple's review process and so are trying to be exact in the nomenclature in the copy. 

It's my bad for failing to submit the PR comment feedback, and failing to keep an eye on follow up. But, any time we're working on Sign In With Apple I think we'd benefit from in depth discussion/agreement any time we're straying from [the issue requirements](https://github.com/matrix-org/synapse/issues/12205).

In this case, we're betting on the specific combination of 'account name' as meaningful jargon, and 'This is required...' in micro copy to make it explicit the data is required and not optional.

Hopefully this gets us through!

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/pull/12260 was committed to the release branch, then manually merged into develop in 0a59f977a209f5d6698414c5bda1bb109f438127.
