### ISSUE TITLE
synapse_storage_transaction_time metric cardinality is too high

### ISSUE THREAD

**Issue by 08d2** [matrix-org/synapse#12263]
[synapse_storage_transaction_time](https://github.com/matrix-org/synapse/blob/9d21ecf7ceab55bc19c4457b8b07401b0b1623a7/synapse/storage/database.py#L77) is a histogram metric with 15 buckets and a `desc` label that, for my non-federated server, has cardinality on the order of 100. This results in 1500 unique timeseries, handily more than any other service in my infrastructure — I think that's probably not great :) The easiest fix here would be to drop `desc` in favor of a label with less granularity.

**Comment by DMRobertson** [comment]
I think this is covered by #11081.
