### ISSUE TITLE
Can't accept invite to space

### ISSUE THREAD

**Issue by kittykat** [matrix-org/synapse#12309]
### Description

When trying to accept a space invite, it fails with a "Failed to join room. You are not allowed to join this room." error. The specific space that this is happening for is `!aDwXHWxCimolPLadup:matrix.org`

I've tried accepting the invite at e.g. 2022-03-28 09:22:40 UTC

### Steps to reproduce

Not sure what the cause is, but this is what happened in this case:

1. User1 invited user2 to a space
2. User2 tried to accept invite 1-2+ weeks later
3. User2 sees "Failed to join room" error
4. If user1 tries to invite user2 to the space again, user1 sees a "User @user2:server is already invited to the room" error

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org (both users and the space are on there)

**Comment by anoadragon453** [comment]
From what I can see from `matrix.org`s database, the `m.room.join_rules` state event of the room has a join rule of `private` set - which [doesn't currently mean anything](https://spec.matrix.org/v1.2/client-server-api/#mroomjoin_rules). This may be why users are having trouble joining, even if they have an invite?

**Comment by kittykat** [comment]
I was testing spaces on iOS at the time and I didn't do anything odd that I can think of :thinking: 

@gileluard - do you know why "private" may have been set?

**Comment by gileluard** [comment]
@anoadragon453 @kittykat we use a preset `public` or `private` but this may be a mistake. What should be the join_rules for private spaces?

**Comment by gileluard** [comment]
Not that I tried to reproduce this bug with my local synapse and everything's fine.

**Comment by gileluard** [comment]
@kittykat I may have found the issue. The new Room Access screen sets the `m.room.join_rules` to private instead of `invite` I believe.

**Comment by anoadragon453** [comment]
@gileluard That sounds like a likely cause. I'm going to close this issue on the assumption that this was the issue.

@kittykat note that the original space's join rule can be fixed by toggling the Visibility settings in Element Web. Or just edit the `m.room.join_rules` state event manually in devtools.
