### ISSUE TITLE
Add developer docs to explain pagination tokens

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#12305]
Add developer docs to explain pagination tokens.

The comment docs explain general things around the pagination tokens well but when I was confronted with `s2633508_17_338_6732159_1082514_541479_274711_265584_1`, it wasn't obvious to me how to decipher it. I knew the `stream_ordering` (`s2633508`) part but it was really fuzzy what the other numbers were and the comment docs don't explain that part. I only really figured it out while drafting this issue and looking at the code more.

Relevant code:

 - [`RoomStreamToken`](https://github.com/matrix-org/synapse/blob/3c41d87b67d3a62edfc660b4fe8f2545f5dbee4f/synapse/types.py#L418-L597)
 - [`StreamToken`](https://github.com/matrix-org/synapse/blob/3c41d87b67d3a62edfc660b4fe8f2545f5dbee4f/synapse/types.py#L600-L678)
 
 
Relevant endpoints:

 - `/sync`
    - `?since`
    - `next_batch`
    - `prev_batch`
 - `/messages`
    - `?from`
    - `?to`
    - `start`
    - `end`
 - others

## Live tokens (`stream_ordering`)

https://github.com/matrix-org/synapse/blob/3c41d87b67d3a62edfc660b4fe8f2545f5dbee4f/synapse/types.py#L436-L437

ex.

 - `s2633508_17_338_6732159_1082514_541479_274711_265584_1`
    1. `room_key`: `s2633508` -> `2633508` `stream_ordering`
    1. `presence_key`: `17`
    1. `typing_key`: `338`
    1. `receipt_key`: `6732159`
    1. `account_data_key`: `1082514`
    1. `push_rules_key`: `541479`
    1. `to_device_key`: `274711`
    1. `device_list_key`: `265584`
    1. `groups_key`: `1`
 - `s1_33_0_1_1_1_1_7_1`
 - `s843_0_0_0_0_0_0_0_0`

Each number key are concatenated together in this order:

https://github.com/matrix-org/synapse/blob/3c41d87b67d3a62edfc660b4fe8f2545f5dbee4f/synapse/types.py#L636-L649

And represent the position of the various fields in the `/sync` response:

```
{
  "next_batch": "s12_4_0_1_1_1_1_4_1",
  "presence": {
    "events": [
      {
        "type": "m.presence",
        "sender": "@the-bridge-user:hs1",
        "content": {
          "presence": "offline",
          "last_active_ago": 103
        }
      }
    ]
  },
  "device_lists": {
    "changed": [
      "@alice:hs1"
    ]
  },
  "device_one_time_keys_count": {
    "signed_curve25519": 0
  },
  "org.matrix.msc2732.device_unused_fallback_key_types": [],
  "device_unused_fallback_key_types": [],
  "rooms": {
    "join": {
      "!QrZlfIDQLNLdZHqTnt:hs1": {
        "timeline": {
          "events": [],
          "prev_batch": "s10_4_0_1_1_1_1_4_1",
          "limited": false
        },
        "state": {
          "events": []
        },
        "account_data": {
          "events": []
        },
        "ephemeral": {
          "events": []
        },
        "unread_notifications": {
          "notification_count": 1,
          "highlight_count": 0
        },
        "summary": {},
        "org.matrix.msc2654.unread_count": 1
      }
    }
  }
}
```

## Historic tokens (`topological_ordering`/`depth`)

https://github.com/matrix-org/synapse/blob/3c41d87b67d3a62edfc660b4fe8f2545f5dbee4f/synapse/types.py#L437-L439

 - `t175-530_0_0_0_0_0_0_0_0`
    1. `topological_ordering`: `t175` -> `175` (`depth`)
    1. `stream_ordering`: `530`
    1. `presence_key`: `0`
    1. `typing_key`: `0`
    1. `receipt_key`: `0`
    1. `account_data_key`: `0`
    1. `push_rules_key`: `0`
    1. `to_device_key`: `0`
    1. `device_list_key`: `0`
    1. `groups_key`: `0`
    - You will see this from `/messages` probably because the endpoint is scoped to the room and so is `depth`
    - `topological_ordering` which is the same as `depth` in Synapse

## Min-position tokens

This one seems pretty well explained by the comment docs already:

ex. `m56~2.58~3.59`

https://github.com/matrix-org/synapse/blob/3c41d87b67d3a62edfc660b4fe8f2545f5dbee4f/synapse/types.py#L441-L461

**Comment by anoadragon453** [comment]
Thank you for collecting this information. Adding some contextual information about this under the Development -> Internal Documentation section of the [docs website](https://matrix-org.github.io/synapse/latest/) would be useful! These tokens are used in several places, so it may be useful to have a single Paginations Token page to document them, and then having pages about other system that use them (Sync) point to this page if the reader wants to learn more about the tokens.

I am wary of duplicating content between code comments and the documentation though. If we could refine the docstrings in the code, and then point to them in the documentation with a less in-depth explanation, that may strike a good balance?
