### ISSUE TITLE
update release script to be poetry-aware

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#12342]
Follow-on from #11537.

As https://github.com/matrix-org/synapse/pull/12337#discussion_r839426474 notes, the release script will need to be updated to edit pyproject.toml rather than synapse/__init__.py.

**Comment by clokep** [comment]
I think this was done in 730fcda5463144f09ff1b34198c678021469ee28. I'm going to close this, but please reopen if there's more to do @DMRobertson

**Comment by DMRobertson** [comment]
There was also a brief follow-up: https://github.com/matrix-org/synapse/commit/a54d9b0508c17a29f2f02c87054cd8990d476054. But yes, this is done now, thanks!
