### ISSUE TITLE
"Out of band" events are code smell

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#12363]
Coming from https://github.com/vector-im/element-web/issues/16931, Synapse effectively pulls a leave event out of thin air when unable to get the federation server to cooperate with leaving the room.

`RoomMemberMasterHandler._generate_local_out_of_band_leave` (in `synapse.handlers.room_member`) is responsible for generating that event, and I think it's code smell. Not just in general for the codebase, but also for implementing the spec; its generating an event locally that's supposed to come from remote.

However, in above element issue, it seems that including an empty object in the `leave` map is enough to make clients believe that it has left the server. The spec says nothing about any key being mandatory, and so this would be valid according to the spec.

**Comment by richvdh** [comment]
if we remove it, what do you suggest we replace it with?

**Comment by ShadowJonathan** [comment]
Have synapse emit empty objects for left rooms, like suggested in the referenced issue;

```
"leave": {!JAONbqNbxqzpSalYmF:fachschaften.org": {}}
```

**Comment by ShadowJonathan** [comment]
> The spec says nothing about any key being mandatory, and so this would be valid according to the spec.

**Comment by richvdh** [comment]
ok sorry, it's valid, but it's very unclear how clients are expected to interpret it.

**Comment by ShadowJonathan** [comment]
> It also overlooks all the state management internal to synapse. This is a lot of work just to get rid of a "code smell".

Looking through the code more, I believe then the whole idea of "out of band events" can be applied under the same code smell then, because it obscures to the rest of the code that its a normal (accepted) event, while hiding its true nature in the internal metadata.

Instead of generating fake events, why not separate the concern of responding to the client's wishes seperately, and have a special table to handle with queued rejections on its own?

This seems way more cleaner to me, and concretely seperates and "cleans" the pipeline of getting events into the database, only having correctly verified and generated events, instead of internal-only events that aren't supposed to go anywhere, aren't valid, yet can end up in the database anyways.

> but it's very unclear how clients are expected to interpret it.

If it is, then that is a spec clarification issue; https://github.com/matrix-org/matrix-spec/issues/1018

My opinion is that it is, and that any client not following that is not following spec.

**Comment by erikjohnston** [comment]
First off, this isn't really anything to do with out of band events, and instead about generating "fake" events. Out-of-band events, such as invites are perfectly fine. 

In of themselves, "fake events" aren't necessarily bad. It's a perfectly valid way of the server interacting with clients, though it may be beneficial to be able to inform clients that an event is a server-local (i.e. "fake") event. 

I do agree with the fact that the way Synapse handles failing to reject remote invites is a bit of a mess, generating the fake event is a bit of a bode given the DB doesn't really support them. We could spend the time cleaning that up a bit, but it's super unclear to me if that benefit of that outweighs the time spent doing so.

Separately, while I agree rejecting invites is a mess, fixing it requires specifying how it should work in the spec. The fact that the spec allows us to send down an empty `leave` section doesn't mean that we can just make Synapse do that and tell clients how they should interpret it. To do so would be to use Synapse's position in the ecosystem to effectively mandate behaviour, circumventing the MSC process. I *do* think its a plausible suggestion and worth an MSC to flesh it out though.

Given the above, this issue isn't meaningfully actionable. If people want to tidy up Synapse's handling of fake events, then go for it.

**Comment by ShadowJonathan** [comment]
Thanks for the response. I'll take a look at the actions and suggestions you mention another time, but I think for now this is clear enough to - indeed - close this issue.
