### ISSUE TITLE
Users are randomly signed out in batches

### ISSUE THREAD

**Issue by sevmonster** [matrix-org/synapse#12397]
### Description

Very occasionally, multiple users will have multiple devices signed out and will need to sign back in and re-verify. It may be some devices, for some users, or it may be all—this last time it affected every user except for a specific Element web client for one user (but the rest of his devices were affected).

Logs do not show anything interesting.

Only other report I can find of this is https://github.com/matrix-org/synapse/issues/10401. This also [causes the Android version to crash](https://github.com/vector-im/element-android/issues/5701).

### Steps to reproduce

No idea. It has happened 3 or so times over the course of months, there is no obvious commonality between the events.

### Version information
- **Version**: `{"server_version":"1.55.2","python_version":"3.10.2"}`
- **Install method**: Package manager
- **Platform**: Alpine Linux x86_64, proxied with Nginx

**Comment by squahtx** [comment]
Do you have a `session_lifetime` configured in your homeserver.yaml config?

**Comment by sevmonster** [comment]
I feel stupid. I was following along with the example homeserver config as well as some third-party guide to help set up Synapse, and the guide recommended 14 days for *all 4 session/token lifetime configurations*. The example config doesn't explicitly mention that `session_lifetime` is not rolling, so I assumed with the mention of refreshable tokens that it was. Now that I read the official documentation on refresh tokens I see how it's supposed to work.

I imagine unsetting `session_lifetime` will resolve this and it was just a coincidence that we were all logged out at the same time. Thanks.
