### ISSUE TITLE
Consider setting `allow_device_name_lookup_over_federation` to false by default

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#12414]
https://github.com/matrix-org/synapse/blob/7732c4902cab065b5c5451614a54be09280dcb68/docs/sample_config.yaml#L712-L716

It is undoubtedly a boost to user privacy if device names are not sent over federation to other users. Is there any objection to simply having that by the default (rather than sharing device names)?

Device IDs, which are typically used when debugging encryption-related errors, are still shared out of necessity regardless of this option.

**Comment by richvdh** [comment]
Agreed, there doesn't seem to be any reason for this to be enabled by default.

Going one step further, why are we only limiting this to federation lookups? Why do we allow any users to see other users' device names in general?

Seems like we should change this; not going to prioritise it for a fix though.
