### ISSUE TITLE
unable to remove room from space

### ISSUE THREAD

**Issue by markiceman** [matrix-org/synapse#12428]
Synapse: 1.55.0
Element: 1.10.8

I have Space (version 6) with 4 rooms.

I upgraded one room from version 6 to version 9. 

And now:
 - I cannot remove this room from space
 - i cannost join to this room through link from space

Interesting:

- link from space in Mobile App (android) is functional, but this join to archived room version 6.

What now?

**Comment by squahtx** [comment]
This is a bug in Element Web. You can either try removing the room from the space using a different client or use curl to remove the room:
```sh
curl $'https://<homeserver>/_matrix/client/r0/rooms/<space id>/state/m.space.child/<room id>' \
  -X 'PUT' -H "Authorization: Bearer syt_<your access token>" -H "Content-Type: application/json" --data "{}"
```
Your access token can be found in Element Web under Settings > Help & About > Advanced > Access Token.
"!" in the space and room ids should be replaced with "\u0021".
eg.
```sh
curl $'https://matrix.org/_matrix/client/r0/rooms/\u0021fhuUBbrIMGHGaPSbDk%3Amatrix.org/state/m.space.child/\u0021pLQLHMyNhDXQNFeIGr%3Amatrix.org' \
  -X 'PUT' -H "Authorization: Bearer syt_<your access token>" -H "Content-Type: application/json" --data "{}"
```

**Comment by squahtx** [comment]
Filed as https://github.com/vector-im/element-web/issues/21732
