### ISSUE TITLE
Incorrect type annotation in `get_stream_id_for_event_txn`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#12437]
Originally [from this comment thread](https://github.com/matrix-org/synapse/pull/12423#discussion_r846349017).

`StreamWorkerStore.get_stream_id_for_event_txn` is declared to return an `int`. If you call it with `allow_none=True`, it returns `None`, which contravenes the type hints. I think this behaviour is intentional and the type hint is incorrect, judging by how it's used. We only call `get_stream_id_for_event_txn` in two places, both in this function:

https://github.com/matrix-org/synapse/blob/3e0536cd2afb5a640619bd872fc27b068ec3eb9b/synapse/storage/databases/main/event_push_actions.py#L184-L216

In particular line 194 of the quoted source looks like it's expecting `stream_ordering` to be possibly None.

Given the above, I think the right thing to do is

1. change `get_stream_id_for_event_txn` to return `Optional[int]` instead of `int`.
2. Try changing `EventPushActionsWorkerStore` to inherit from `StreamWorkerStore` and removing the type-ignores where we call `get_stream_id_for_event_txn`. Doing so might fail due with DataStore MRO problems (related: #11165 and more generally #11733). If so, that's fine and we can leave things as they are.

**Comment by gautamgiri-dev** [comment]
Hello @DMRobertson I have made some changes as suggested by you followed by some changes based on linting errors thrown by mypy. Could you please review it.. and please assign this issue to me

**Comment by clokep** [comment]
This was fixed in #12716.
