### ISSUE TITLE
Update UPGRADE notes to include more details about v1.57 upgrade failure mode

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#12447]
If you fail to stop the AS worker when upgrading Synapse then the AS worker may refuse to start, spitting out an error message that says to run some SQL.

Is there is a concern that this is still confusing? Do we need to add more words somewhere about what to do?

**Comment by richvdh** [comment]
As I wrote yesterday:

The error message is probably sufficient, but it would be good to extend the upgrade notes to explain that that is what happens if you mess it up, and if you find yourself in that situation you should run the query it suggests.
