### ISSUE TITLE
ModuleApi.http_client --> Too many Authorization headers --> Unauthorized

### ISSUE THREAD

**Issue by NiTRoeSE** [matrix-org/synapse#12471]
### Description

We use the a antispam module to determine if a user is a student or a teacher and decide on this base if the user can invite a another user to a room ( all this to prevent 1:1 messages between students --> its a education environment ) . 
Because a student who wants to chat with another student only gets a message like " we are unable to create your room" i want to send them a message like  (Server Notification) " You have no permissions to invite other students!" I tried it the following way:

With the help of #synapse:matrix.org channel i ended up using the ModuleApi http_client to send the notification, this worked exactly 1 time. In all other cases i get the message `synapse-server   | 2022-04-13 12:17:42,926 - synapse.http.server - 95 - INFO - POST-33 - <XForwardedForRequest at 0x7f95730cdd30 method='POST' uri='/_synapse/admin/v1/send_server_notice' clientproto='HTTP/1.1' site='8008'> SynapseError: 401 - Too many Authorization headers.` with a following `401: Unauthorized`.

If i not submit a header with authorization token i get the exspected "401: Unauthorized" and the message `Too many Authorization headers` is gone.

I think there is something wrong in check from http_client if there are more than once auth headers.

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

I expect that a notification can be send with http_client while passing a valid auth header.

### Version information

- **Homeserver**:

- **Version**:
1.55.2

- **Install method**:

   official docker image 

- **Platform**:
docker-compose stack with synapse, redis, postgres, element

- **Antispam Script**

```

from ldap3 import Server, Connection, ALL
import logging
logger = logging.getLogger("synapse.contrib." + __name__)

class AntiSpamInvites:
    def __init__(self, config, api):
        self._ldap_server = config.get("ldap_server") 
        self._ldap_bind_user = config.get("ldap_bind_user") 
        self._ldap_bind_pw = config.get("ldap_bind_pw")
        self._api_url = config.get("api_url")
        self._api_admin_token = config.get("api_admin_token")
        self.module_api = api
        api.register_spam_checker_callbacks(
            user_may_invite=self.user_may_invite,
        )

    async def user_may_invite(self, inviter_user_id, invitee_user_id, room_id):

        ```
        A lot of other stuff running in this spam module... not related for the problem
        (Things like checking user against ldap etc)

       ```

        headers = {"Authorization": "Bearer {}".format(self._api_admin_token)}
        apiurl_server_notification = self._api_url + '/_synapse/admin/v1/send_server_notice'

        async def send_notification(inviter_user_id, apiurl_server_notification, headers):
            logger.info('[SEND NOTIFICATION]')
            logger.info(headers)

            data = {
                "user_id": inviter_user_id,
                "content": {
                    "msgtype": "m.text",
                    "body": "You simply have no permissions to create a student --> student 1:1 chat."
                }
            }

            #logger.info("[TEST APIURL] - {}".format(apiurl_server_notification))
            #logger.info("[TEST HEADER] - {}".format(headers))
            try:
                await self.module_api.http_client.post_json_get_json(apiurl_server_notification, data, headers)
                #await self.module_api.http_client.post_json_get_json(apiurl_server_notification, data)

            except Exception as e:
                logger.info("[EXCEPTION] {}".format(e))
            logger.info("[TEST AWAIT] ..........")


      await send_notification(inviter_user_id, apiurl_server_notification, headers)
      logger.info("[SPAMMODULE] - sended notification to - student inviter | {}".format(inviter_user_id))
           
 



```

Support via #synapse:matrix.org is the opinion that it should or must work this way. Maybe i doing something wrong and its not a bug but to me it seems like its a bug.

Hope anybody can clarify and or help 
Thanks in advanced.

PS: We have checked headers multiple times, logged it to log file and much more. Following log output to demonstrate:

```

synapse-server   | 2022-04-13 13:22:53,132 - synapse.contrib.invites - 40 - INFO - POST-17 - [SEND NOTIFICATION]
synapse-server   | 2022-04-13 13:22:53,132 - synapse.contrib.invites - 41 - INFO - POST-17 - {'Authorization': 'Bearer syt_bWljaGFlbC5zY2h1bms_WiCLzaoPTPzSoBHbWkon_2'}
synapse-server   | 2022-04-13 13:22:53,149 - synapse.access.http.8008 - 427 - INFO - GET-33 - 172.20.1.1 - 8008 - {@micha.schueler:chat.example.com} Processed request: 0.112sec/0.002sec (0.005sec, 0.000sec) (0.004sec/0.005sec/2) 823B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s718_1329_0_20_173_1_35_34_1 HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.10.9 Chrome/98.0.4758.74 Electron/17.0.0 Safari/537.36" [0 dbevts]
synapse-server   | 2022-04-13 13:22:53,151 - synapse.http.server - 95 - INFO - POST-34 - <XForwardedForRequest at 0x7f379d38d190 method='POST' uri='/_synapse/admin/v1/send_server_notice' clientproto='HTTP/1.1' site='8008'> SynapseError: 401 - Too many Authorization headers.
synapse-server   | 2022-04-13 13:22:53,152 - synapse.access.http.8008 - 427 - INFO - POST-34 - ::ffff:172.50.25.1 - 8008 - {None} Processed request: 0.001sec/0.001sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 71B 401 "POST /_synapse/admin/v1/send_server_notice HTTP/1.1" "Synapse/1.55.2" [0 dbevts]
synapse-server   | 2022-04-13 13:22:53,153 - synapse.replication.tcp.resource - 193 - INFO - replication_notifier-11 - Streaming: events -> 719
synapse-server   | 2022-04-13 13:22:53,155 - synapse.http.client - 446 - INFO - POST-17 - Received response to POST http://10.1.1.20:8008/_synapse/admin/v1/send_server_notice: 401
synapse-server   | 2022-04-13 13:22:53,156 - synapse.contrib.invites - 58 - INFO - POST-17 - [EXCEPTION] 401: Unauthorized
synapse-server   | 2022-04-13 13:22:53,156 - synapse.contrib.invites - 59 - INFO - POST-17 - [TEST AWAIT] ..........
synapse-server   | 2022-04-13 13:22:53,156 - synapse.contrib.invites - 71 - INFO - POST-17 - [SPAMMODULE] - sended notification to - student inviter | @micha.schueler:mzchat.jsp-jena.de
synapse-server   | 2022-04-13 13:22:53,156 - synapse.handlers.room_member - 693 - INFO - POST-17 - Blocking invite due to spam checker



```

**Comment by squahtx** [comment]
I'm not sure how it worked the first time, but the values in the headers dictionary are supposed to be lists of strings/bytes. 
So instead of:
```py
        headers = {"Authorization": "Bearer {}".format(self._api_admin_token)}
```
you might want to try:
```py
        headers = {"Authorization": ["Bearer {}".format(self._api_admin_token)]}
```

**Comment by NiTRoeSE** [comment]
> you might want to try:
> 
> ```python
>         headers = {"Authorization": ["Bearer {}".format(self._api_admin_token)]}
> ```

my hero <3 ... i never saw a auth header in this format but it works :D
problem solved !

Thanks a lot for this hint / solution / help !
