### ISSUE TITLE
`enable_3pid_lookup` is documented in the config sample but not supported anymore

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#12479]
`enable_3pid_lookup` appears in the config sample file but it doesn't look like we read the value or do anything with it. I assume the feature got removed but the documentation never got removed.

**Comment by H-Shay** [comment]
I am confused: it looks like we read this option here: https://github.com/matrix-org/synapse/blob/3ae56d125c95fe6919cdf7892b9e6a6cdba651a4/synapse/config/registration.py#L42 and use the read option here: https://github.com/matrix-org/synapse/blob/3ae56d125c95fe6919cdf7892b9e6a6cdba651a4/synapse/handlers/room_member.py#L91 and here: https://github.com/matrix-org/synapse/blob/3ae56d125c95fe6919cdf7892b9e6a6cdba651a4/synapse/handlers/room_member.py#L1355

Am I missing something here?

**Comment by clokep** [comment]
I concur, this seems to still be used. Thanks for researching @H-Shay!

I'm going to close this, @babolivier are we missing something here?

**Comment by babolivier** [comment]
Not sure why these weren't popping up in my searches, sorry about the noise :/
