### ISSUE TITLE
synapse returns undocumented `device` property from `GET /_matrix/client/v3/pushrules/`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12482]
Synapse's response to a `/pushrules` query looks something like:

```json5
[
  "global": {
    "content": { /*... */ },
    "override": { /*... */ },
    "room": { /*... */ },
    "sender": { /*... */ },
    "underride": { /*... */ }
  },
  "device": {}
]
```

This `device` property is not [specced](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3pushrules) and should be removed.

**Comment by DMRobertson** [comment]
I have asked the client developers' room to double-check that no-one is using this field. https://matrix.to/#/!XXSJTvRPInupfUgQVb:matrix.org/$0adIq-vLha08iT0Hx3Gj-3VGQltT8Db63MptF0FZ-90?via=pixie.town&via=matrix.org&via=element.io
