### ISSUE TITLE
Multiple previously working client instances are unable to connect(hang) following upgrade of homeserver and pgsql

### ISSUE THREAD

**Issue by derzahla** [matrix-org/synapse#12515]
### Description

Element instances that were previously configured on various devices(iOS, android and linux) no longer connect to the homeserver.  The client will just hang forever trying to load.  Stopping the client(updating), clearing all cache, and then attempting to login fresh has the same results. This seems to coincide with a recent homeserver upgrade a few weeks ago that also moved from pgsql 12->13.  

**additionall**:  On my primary linux client which is still functional, I am noticing element/electron pegging the CPU at 100% very often and needing to be manually killed/restarted

### Steps to reproduce

- launch element on devices that used to work without error

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
There are no obvious errors in the client or server logs that have proven to be relevent, but I have been chasing various around presumably unrelated errors for the last week or so, ie. https://github.com/vector-im/element-web/issues/21727 and https://github.com/vector-im/element-web/issues/19218.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->

<!--
 What version of Synapse is running?
You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->

- **Version**: matrix-synapse-1.55.2


- **Install method**: pkg
<!-- examples: package manager/git clone/pip  -->

- **Platform**: FreeBSD 13
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
TrueNAS 13 iocage jail

**Comment by DMRobertson** [comment]
Do you have server logs? Can you track down `/login` requests which correspond to the clients that cannot login?

**Comment by derzahla** [comment]
Yes.  Here is the latest example from today.  Only two lines from the client match '/login' though so not sure how useful it will be

`2022-04-20 11:47:35,984 - synapse.access.http.8008 - 427 - INFO - GET-32133- 10.10.27.1 - 8008 - {None} Processed request: 0.002sec/0.004sec (0.005sec, 0.000sec
) (0.000sec/0.000sec/0) 136B 200 "GET /_matrix/client/r0/login HTTP/1.0" "Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.10.3
 Chrome/98.0.4758.82 Electron/17.0.1 Safari/537.36" [0 dbevts]
2022-04-20 11:47:46,022 - synapse.access.http.8008 - 427 - INFO - POST-32149- 10.10.27.1 - 8008 - {None} Processed request: 0.341sec/0.000sec (0.311sec, 0.000se
c) (0.001sec/0.028sec/5) 204B 200 "POST /_matrix/client/r0/login HTTP/1.0" "Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.10
.3 Chrome/98.0.4758.82 Electron/17.0.1 Safari/537.36" [0 dbevts]
2022-04-20 11:47:46,258 - synapse.access.http.8008 - 427 - INFO -`

**Comment by CalebFenton** [comment]
I also have a problem with hanging after login, but my setup is brand new with only a single admin created. But others are complaining about this problem after an upgrade:
* https://github.com/matrix-org/synapse/issues/12071
* https://github.com/matrix-org/synapse/issues/11779.

**Comment by derzahla** [comment]
Sorry, I dont have any further information to provide.  I ended up just rolling back everything to a 3 week old snapshot.  I did the postgres upgrade to 13 and no problems this time.
