### ISSUE TITLE
user_stats_historical does not exist

### ISSUE THREAD

**Issue by felixx9** [matrix-org/synapse#12525]
docs here: synapse/docs/usage/administration/useful_sql_for_admins.md

or here 

https://matrix-org.github.io/synapse/latest/usage/administration/useful_sql_for_admins.html#show-top-20-users-on-homeserver-by-sent-events-messages-at-last-month

fires a select on table `user_stats_historical`, but this table seem not to exist.
would be a very helpful select, though, if we have a spam problem

**Comment by dklimpel** [comment]
This feature was removed
- #9721
