### ISSUE TITLE
MSC2228 support should be reflected in `/_matrix/client/r0/capabilities`

### ISSUE THREAD

**Issue by EdGeraghty** [matrix-org/synapse#12524]
**Description:**

Hey, I'm trying to implement a [client-side implementation](https://github.com/syphon-org/syphon/pull/660) of [synapse's limited MSC2228 support](https://github.com/matrix-org/synapse/pull/6409).

I feel that homeserver support for this functionality should be exposed under `/_matrix/client/r0/capabilities` (or at least somewhere) because the last thing I want to do in my implementation is completely mislead its users.

**Comment by anoadragon453** [comment]
Adding to to-discuss in order to figure out what the future of this feature looks like in Synapse.

**Comment by EdGeraghty** [comment]
> Adding to to-discuss in order to figure out what the future of this feature looks like in Synapse.

Is there anything I can watch for the conversation? Just https://github.com/matrix-org/matrix-spec-proposals/pull/2228?

**Comment by anoadragon453** [comment]
@EdGeraghty Issues that are added to the To-Discuss column of the board are discussed synchronously on a weekly-basis (team availability withstanding). We'll put the conclusion of that discussion here :slightly_smiling_face:
