### ISSUE TITLE
URL previews should fall back to twitter: and other meta tags if og: prefixes are missing

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#12591]
Moved from https://github.com/vector-im/element-web/issues/1530

> it's up to the server impl to be as smart as it can be using whatever current best practices are to produce nice pretty previews (synthesising appropriate og: tags if none are present).

- ara4n

**Comment by clokep** [comment]
See also #11540.

**Comment by clokep** [comment]
[Se](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)

**Comment by richvdh** [comment]
I think it's unlikely we'd want to do anything particularly custom for twitter?

**Comment by clokep** [comment]
> I think it's unlikely we'd want to do anything particularly custom for twitter?

This is pretty much Twitter's competitor to Open Graph, it isn't specific to twitter.com (the website). I'm unsure how prevalent it is, but I did find it on a couple of sites (Instagram, CNN, etc.)

**Comment by t3chguy** [comment]
meta description is one

e.g

```
<meta name="description" content="This is an example of a
meta description. This will often show up in search results.">

**Comment by clokep** [comment]
If there are known sites that would benefit from this that would be awesome to include. 👍 Unfortunately the original report does not seem to include any!

**Comment by clokep** [comment]
> meta description is one
> 
> e.g
> 
> ```
> <meta name="description" content="This is an example of a
> meta description. This will often show up in search results.">
> ```

This is actually used already:

https://github.com/matrix-org/synapse/blob/053ca5f3ca6b913d2c4bfdc7a77cb4657bc86d68/synapse/rest/media/v1/preview_html.py#L223-L232

**Comment by clokep** [comment]
#13056 should fix this, it parses the `twitter:` meta tags.

The URL preview code has long parsed `<meta name="description" content="...">` and `<meta itemprop="image" content="...">`.

At a quick glance I can't see anything else on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name that would be worth parsing, but if you disagree please open a new issue!
