### ISSUE TITLE
Messages aren't received /out of order and users are unaware 

### ISSUE THREAD

**Issue by guyonabuffallo** [matrix-org/synapse#12598]
A plethora of users using different updated clients are unaware of missing messages or receive messages out of order. Personally using element I've experienced repeating pages on Android while scrolling up. But the broader issue is synapse really needs a heartbeat error check feature or something so users are aware that messages are messed up. This has been an issue for years but now it seems worse than before.

**Comment by H-Shay** [comment]
I am closing this as it isn't a specific, reproducible bug. However, for reference [this](https://github.com/matrix-org/synapse/issues/11499#issuecomment-990060172) comment does shed some light on the difficulties with synchronizing messages/timelines across federation.
