### ISSUE TITLE
Remove (direct) use of `constantly`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#12607]
The entire source tree uses `constantly` in exactly one file, originally added in #6377.

https://github.com/matrix-org/synapse/blob/8a87b4435a736cd42454cad7e57b65ec911f01fa/synapse/storage/databases/main/events_worker.py#L33

https://github.com/matrix-org/synapse/blob/8a87b4435a736cd42454cad7e57b65ec911f01fa/synapse/storage/databases/main/events_worker.py#L153-L160

In other places, we use the stdlib [`enum`](https://docs.python.org/3/library/enum.html?highlight=enum#module-enum) module instead. For instance:

https://github.com/matrix-org/synapse/blob/e24ff8ebe3d4119d377355402245947f7de61c00/synapse/handlers/state_deltas.py#L25-L28

I would like us to use the enum approach and ditch constantly, for three reasons:
1. consistency across the source tree.
2. mypy knows what an enum is; it don't know what a NamedConstant is. E.g. `reveal_type(EventRedactBehaviour.AS_IS)` yields `synapse/handlers/message.py:1407: note: Revealed type is "Any"`.
3. I prefer using a well-known tool from the stdlib rather than the lesser-known constantly.

Task list:

- [ ] replace import of `constantly` with equivalent imports from stdlib `enum`
- [ ] redefine the `EventRedactBehaviour` type in terms of `enum`
- [ ] remove [these lines](https://github.com/matrix-org/synapse/blob/8d156ec0ba17d848581f18aa40ebfd76dda763d4/mypy.ini#L250-L252) from mypy.ini.
- [ ] run the linter script: in particular, run mypy. Fix any errors that show up.

**Comment by andrewdoh** [comment]
hi, id like to work on this please check this PR out I made for the outlined above. @DMRobertson 
https://github.com/matrix-org/synapse/pull/12624
