### ISSUE TITLE
The generated server certificate in Complement images has no Subject Alternative Name

### ISSUE THREAD

**Issue by dkasak** [matrix-org/synapse#12615]
### Description

When constructing a Complement Docker image for Synapse, we generate a server certificate which contains only a Common Name but no Subject Alternative Name (SAN). Dendrite [doesn't like this](https://golang.google.cn/doc/go1.15#commonname), so refuses to communicate with such a Synapse.

I encountered this problem because I'm fiddling with trying to extend Complement to support spinning up federations composed of multiple different HS implementations. Synapse <-> Synapse and Dendrite <-> Dendrite work fine, but Synapse <-> Dendrite configurations currently fail to communicate due to this.

So to solve this, we need to include a SAN in there. Generating a certificate with SAN using `openssl` is [a bit fiddly](https://stackoverflow.com/questions/6194236/openssl-certificate-version-3-with-subject-alternative-name) but doable, though it looks to be impossible to achieve using just the command-line arguments, so we'd need to bundle an `openssl` config file. Another option would be to generate the server certificate using something other than the `openssl` utility, e.g. using Python's `cryptography` package.

**Comment by richvdh** [comment]
> Generating a certificate with SAN using openssl is [a bit fiddly](https://stackoverflow.com/questions/6194236/openssl-certificate-version-3-with-subject-alternative-name) but doable,

You just have to generate a config file like this:

```
.include /etc/ssl/openssl.cnf

[SAN]
subjectAltName=<domain>
```

which is, as you say, fiddly, but very much doable.

It might be worth noting that the *worker-mode* complement image uses Caddy to generate the TLS cert. That solution feels overengineered to me, but perhaps I have Stockholm syndrome with the openssl cmdline.

**Comment by richvdh** [comment]
> It might be worth noting that the worker-mode complement image uses Caddy to generate the TLS cert. That solution feels overengineered to me, but perhaps I have Stockholm syndrome with the openssl cmdline.

this is no longer true as of #12818 :tada:
