### ISSUE TITLE
Ability to set whether a given user is impacted by the mau_trial_days MAU config

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#12617]
It would be useful to say that some users aren't affected by trial_days and should be considered active from the point of their first sync, while also grouping other users into the general MAU pool.

**Comment by H-Shay** [comment]
Just to be clear, you want a config option that allows you to specify a list of users to exclude from the grace period if `mau_trial_days` is enabled?

**Comment by Half-Shot** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/12619
