### ISSUE TITLE
Faster joins: handle gappy `/syncs`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12645]
We need to make sure that we're handling gappy `/syncs` correctly. It would be easy to think that we sent more state to the clients than we did, and we'll need to check this and write tests.

To do this, we'll first have to understand the existing code for tracking which state we have sent to clients. It looks entirely magical.

**Comment by erikjohnston** [comment]
I think the code we care about is here:

https://github.com/matrix-org/synapse/blob/ade30088212091284d066fc31a755a8a21050677/synapse/handlers/sync.py#L923-L978

which basically gets the state at the end of the last sync response and the state at the start of the current sync response, takes the delta, and removes any state events that will appear in the timeline anyway.

One way of fixing this is to somehow set the `state_at_previous_sync` to the empty set if we were still in the process of lazy joining at the time?

**Comment by squahtx** [comment]
I think this is fine. The only state that we might think we sent, but didn't, are `m.room.member` events.

When `lazy_load_members` is off, we want to pretend the room has not been joined yet: #12989
When `lazy_load_members` is on, we:
  1. first decide that we always want to return `m.room.members` in the `/sync` response, by kicking `m.room.member` events out of state-at-the-end-of-the-previous-sync:
     https://github.com/matrix-org/synapse/blob/888a29f4127723a8d048ce47cff37ee8a7a6f1b9/synapse/handlers/sync.py#L2258-L2270
  2. then filter out `m.room.member` events that we have already sent, by checking against an in-memory cache, which we update at the same time:
     https://github.com/matrix-org/synapse/blob/888a29f4127723a8d048ce47cff37ee8a7a6f1b9/synapse/handlers/sync.py#L1012-L1039

so in the following sequence, the gappy `/sync` will include the `m.room.member` event for Bob:
1. Alice joins room
2. `/sync`
3. Bob sends two messages
4. gappy `/sync` with `limit: 1`

**Comment by squahtx** [comment]
Complement test: https://github.com/matrix-org/complement/pull/390

**Comment by squahtx** [comment]
The test has been merged. Please reopen if I've missed anything.
