### ISSUE TITLE
Fix the join-time-monitor

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12641]
The join-time-monitor for faster joins ([graph](https://synapse-performance-test.lab.element.dev/prometheus/graph?g0.expr=performance_join_time_seconds%20and%20performance_join_success%20%3E%200%20and%20(time()%20-%20performance_join_timestamp%20%3C%2030000)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=16d), [repo](https://gitlab.matrix.org/new-vector/backend/join-time-monitor)) is failing more than it's completing.

Need to find out why and make it more robust

**Comment by squahtx** [comment]
Things are still failing on the real deployment because the logs volume is full.

**Comment by squahtx** [comment]
> Things are still failing on the real deployment because the logs volume is full.

The logs are full of error spam about missing database tables, presumably from the stuck job after another test run reset the database. Let's delete the log spam as a one-off.

**Comment by squahtx** [comment]
There's not much more to be done for now, until we see it flake again.

**Comment by richvdh** [comment]
Do we need to do some manual stuff to deploy   https://gitlab.matrix.org/new-vector/backend/join-time-monitor/-/merge_requests/2?

Otherwise yup, let's call it done.

**Comment by squahtx** [comment]
> Do we need to do some manual stuff to deploy https://gitlab.matrix.org/new-vector/backend/join-time-monitor/-/merge_requests/2?

Yes, I can do that. Though it ought to make no difference given the lack of resource limits on the real deployment
