### ISSUE TITLE
Faster joins: audit code paths that do state queries

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12643]
Check that all the code paths that do state queries are happy with partial state. There are a bunch of things that call `get_filtered_current_state_ids` which really aren’t; there may well be others.

**Comment by erikjohnston** [comment]
What do people think of indirecting all calls to `DataStore.get_current_state_ids` and co via the `StateStorage`, and then updating `PartialStateEventsTracker` to also track current state?

The downside to this approach is that it'll be easy for people to muscle memory using `store.get_current_state_ids()` and so bypassing the checks. That is true of the equivalent state group functions today I guess

**Comment by richvdh** [comment]
To summarise what was said in chat:

* when erik says `StateStorage`, he means `StateGroupStorage`.
* `PartialStateEventsTracker` feels like the wrong place (better put it in a separate class)
* indirecting current_state etc through `StateGroupStorage` (and renaming it to `StateStorage`) seems sensible.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/pull/12872  and #12964 will have sorted out a bunch of places that we check `current_state_events`, but someone should go through and audit if there are any other queries

**Comment by richvdh** [comment]
I've been through the things that call methods in `StateGroupWorkerStore` and `RoomMemberWorkerStore` and opened a few issues, but mostly it's just "presence and device lists are going to be a nightmare", and they are covered by #13008 and #12993 respectively. I don't think further staring is going to be particularly fruitful and instead we should just file new issues as we find them.
