### ISSUE TITLE
The `all` extras package group no longer includes `pympler`

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#12648]
As of https://github.com/matrix-org/synapse/pull/12449, the `all` extras package group does not automatically install all of the optional dependencies. Specifically, the `cache_memory` extras group was no longer installed, which meant that without explicitly installing it, it was missing in both the Debian and Docker images we distribute.

The `cache_memory` extras group installs the `pympler` package, which is needed to test the `caches.track_memory_usage` experimental config option. While this is indeed experimental, deployments using the docker images or debian packages can't test it if this dependency is missing.

`systemd` is another optional dependency which is not installed via `all`. It enables the `systemd.journal.JournalHandler` handler as configured in the log config. In the past we have explicitly chosen to exclude this, as it is only needed on systems which use systemd.

However, despite systemd-less versions of Debian in existence, it is needed to configure the above handler on Debian-based Linux distributions with systemd. I'm unsure whether it should be installed on the Docker images (would it be useful to log to systemd on the docker images? I assume they are meant to simply log to stdout?).

(This issue originated from discussion in https://github.com/matrix-org/synapse/pull/12640#discussion_r865801137).

**Comment by DMRobertson** [comment]
Casualty of #12381.

Result of discussion:
- Let's stick it back in to `all`, but not worry about releasing a new docker image with `pympler` present unless someone complains.
- We still want `systemd` to not be in `all`.

We can remove `--extras cache_memory` from the scripts that export requirements from the debian events, while keeping `--extras systemd.
