### ISSUE TITLE
Server notice rooms are created rapidly if triggered by maybe_send_server_notice_to_user

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#12686]
In the case where a server has reached it's MAU limit, the ResourceLimitsServerNotices class is meant to send a notice to users informing them of this. However, it ends up creating a ton of duplicate rooms *and* never actually invites the target for the notice to the room.

- `ServerNoticesManager.get_or_create_notice_room_for_user` is used to create the room for the user but does not invite them, that happens in `maybe_invite_user_to_room` which is called together in [`send_notice`](https://github.com/matrix-org/synapse/blob/2e2d8cc2f9b9af5f8b48d75e22c474e08feca236/synapse/server_notices/server_notices_manager.py#L49)
- `ResourceLimitsServerNotices` is cheeky and calls `ServerNoticesManager.get_or_create_notice_room_for_user` in [`maybe_send_server_notice_to_user`](https://github.com/matrix-org/synapse/blob/e24ff8ebe3d4119d377355402245947f7de61c00/synapse/server_notices/resource_limits_server_notices.py#L55), presumably making the fatal mistake that `get_or_create_notice_room_for_user` does NOT invite users.
- Hence, if your server is over the MAU limit, it's probably calling `ResourceLimitsServerNotices.maybe_send_server_notice_to_user` often, and therefore creating new rooms often.

This is causing some servers to bloat their database with empty rooms, and of course any interfaces polling the admin API for rooms will see a load of extra redundant rooms.

**Comment by babolivier** [comment]
Thanks for investigating @Half-Shot! This looks like it's indeed the culprit, I've opened https://github.com/matrix-org/synapse/pull/12704 to fix this (by making `get_or_create_notice_room_for_user` always check if the user needs inviting).
