### ISSUE TITLE
A room listed in the directory should be accessible

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#12733]
Moved from https://github.com/vector-im/element-web/issues/3983
Related https://github.com/matrix-org/synapse/issues/6735
Related https://github.com/matrix-org/synapse/issues/6346

### Description

> trying to access #testingGuest:matrix.org as a guest from the directory gives the error message '#testingGuest:matrix.org does not exist'. Whatever is the reason for this msg to appear (deleted alias? not accessible to guests?) should be managed in a much nicer way: if something is missing the room should not be in the directory.

> ok I think the bottom line is that the address was removed => when removing the only address of a room there should be a warning saying "we will unlist it" and actually unlist it

> I found this room again, added an address (#testingguestaccess:matrix.org) but not selected it in the drop down (the first added address should be selected by default in the drop down). I was able to join this address directly but still not from the directory.

> I got back, selected the new address (#testingguestaccess:matrix.org) in the drop down and the wrong one (#testingGuest:matrix.org was displayed in the browser.

Note accessible may mean knockable, accessible to a space member, invited, or publicly joinable.

**Comment by richvdh** [comment]
>  '#testingGuest:matrix.org does not exist'. 

seems to be a dup of #6346.
