### ISSUE TITLE
`m.room.encryption` not set, despite room creation set to encyrpted in configuration

### ISSUE THREAD

**Issue by felixx9** [matrix-org/synapse#12735]
### Description

When inviting a Uaser-Account (mxid), which does not exist yet, we have problem, it this account gets created, later.

### Steps to reproduce

- User A wants to invite User B, but accidentially invites User C (which does not have an account / does not exist yet)
- User A does write a lot of confidential stuff into the newly created room
- User C (which might be a completely different person than User B) creates his account
- he sees the invitation & accepts it
- User C can read the whole history, which was meant for User B
- the room is not encrpyted (even though the servers default setting says: encrypt all rooms)

### what I expect

- I would expect, that
  - I see this warning (but I didn't): https://github.com/vector-im/element-web/issues/7137 within Client (e.g. Element)._
  - ![einladung-ohne-user](https://user-images.githubusercontent.com/51174875/168395610-aa1ddd78-d593-4ee7-b5f8-4e9417ccd72f.png)
  - the room is encrypted
  - if not possible due to missing public key (?) of User C: Do not create the room
  - if created an encrypted: User C is not allowed to join, (unless invited again after account creation.)

### Details 

- Homeserver: matrix.yatrix.org

If not matrix.org:
- 
 What version of Synapse is running? > 1.58.1
Element Desktop 1.10.8

**Comment by DMRobertson** [comment]
Thanks for the report.

> * User A wants to invite User B, but accidentally invites User C (which does not have an account / does not exist yet)

This isn't a mistake that Matrix-the-protocol can prevent. Imagine user A had emailed a bunch of secret documents to user C --- there's no way to take those emails back once they've been sent.

However: the fact that you didn't see the warning sounds like a problem in Element Desktop.

> the room is not encrpyted (even though the servers default setting says: encrypt all rooms)

Again, this sounds like it might be a bug in the client. Clients are responsible for sending an `m.room.encrypted` state event, which marks the room as encrypted (telling other clients which encryption algorithm to use).

I'm going to move this issue to the Element-web repo for them to investigate more.

**Comment by DMRobertson** [comment]
> I'm going to move this issue to the Element-web repo for them to investigate more.

I apparently lack the permissions to do this; I've asked @matrix-org/element-web to do this instead.

**Comment by t3chguy** [comment]
You can't move between github orgs

**Comment by DMRobertson** [comment]
> * (even though the servers default setting says: encrypt all rooms)

@felixx9  Can you share the part of your config which sets this?

**Comment by felixx9** [comment]
Hej, thank you for having a look on it. A friend of mine found it - I only reported this behavior.

Actually, sorry, I don't find a setting for having rooms encrypted by default, in my different `homeserver.yaml` files.
But I know, by default the rooms ARE encrypted, and therefore I thought it must be in the config. It probably just is the default.

a) room after invitation of a known account:
![Screenshot from 2022-05-16 17-02-20](https://user-images.githubusercontent.com/51174875/168625083-2f2f67ea-65b6-4e8d-a138-c16a4a44a345.png)

b) invitation of unknown account
![Screenshot from 2022-05-16 17-02-05](https://user-images.githubusercontent.com/51174875/168625721-9090ebe1-d48e-4aab-bab3-f981e305dc72.png)

c) invitation of an accoun
![Screenshot from 2022-05-16 17-15-21](https://user-images.githubusercontent.com/51174875/168626500-d5952077-7982-4e42-91aa-ee0425f5e0ae.png)
t on unknown server

**Comment by DMRobertson** [comment]
It sounds like Synapse is behaving as intended then.  If there is some problem with `encryption_enabled_by_default_for_room_type` in the config, I'm happy for this to be reopened with details of that config.
