### ISSUE TITLE
`allow_device_name_lookup_over_federation` config option may be leaky

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#12750]
@aaronraimist has noted that the implementation of the `allow_device_name_lookup_over_federation` config option may be leaky, as determined by manual testing.

https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$NIF9Q6PAp0X1T6JES3BDVdoxWJa-0fSJdDaX3gJjrHE?via=matrix.org&via=praten.de&via=lingcube.com explains the testing done:
"I was testing was I had allow_device_name_lookup_over_federation: false on my server and then was logging in/out and changing my device names to cause device list updates. I then used Element logged in to accounts on [matrix.org](http://matrix.org/), [mozilla.org](http://mozilla.org/), etc to check my device list and see if the new names were visible."

#9945 implements the option.
#10015 addresses one of the leaks.

**Comment by anoadragon453** [comment]
https://github.com/matrix-org/synapse/pull/14304 addressed another leak.

To all: please open a new issue if a further leak is discovered.
