### ISSUE TITLE
Individual workers will fetch remote server keys without sharing a cache

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#12767]
We don't seem to try fetching server keys from the database when validating federation requests on a worker. This can lead to multiple workers each making a server key request to the same remote homeserver.
  
https://github.com/matrix-org/synapse/blob/e0bb2681340752f2716f1f386139ca37c53f26cd/synapse/crypto/keyring.py#L260-L298

We have a database table where we cache server key responses (`server_keys_json`). I can't think of any reason why we wouldn't use it here?

**Comment by DMRobertson** [comment]
I think this issue was onto something: see https://github.com/matrix-org/synapse/issues/15171
