### ISSUE TITLE
CPU increase on main process after 1.57.1 -> 1.58.1 upgrade (`fetch_events` background task)

### ISSUE THREAD

**Issue by Fizzadar** [matrix-org/synapse#12788]
Two days ago we rolled out `v1.58.1` to production and ever since there's been a substantial CPU increase on the main process doing `fetch_events` background task which I spotted today:

<img width="1615" alt="Screenshot 2022-05-18 at 14 58 24" src="https://user-images.githubusercontent.com/1026154/169133429-57132818-e2e8-4e73-bf0e-d1cd50df598f.png">

There's also an increased memory usage overall which is what led us to discover this. Unsure what this is doing exactly, any pointers?

Wonder if this is related to #12778 at all?

**Comment by bradtgmurray** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/33967/169138164-c1fa00ee-d3c7-4a0d-a903-363efeeaf3eb.png">

Something in Synapse now wants a lot more events, but who?

**Comment by bradtgmurray** [comment]
320186319ac4f1d16f8f964d92db8921a4b1073e and 17d99f758a768b886842cf496ff236fbe3829236 are two new callers of `get_events_as_list` in 1.59, but neither one makes sense I think (one we can't see the `sync_partial_state_room` background job in grafana, the other I think should be running on our worker that's handling /messages requests I think?)

**Comment by babolivier** [comment]
> <img alt="image" width="873" src="https://user-images.githubusercontent.com/33967/169138164-c1fa00ee-d3c7-4a0d-a903-363efeeaf3eb.png">

What caches do the purple and red graphs correspond to?

**Comment by bradtgmurray** [comment]
> What caches do the purple and red graphs correspond to?

Apologies, they're all just `*getEvent*` across multiple restarts of the synapse-0 (main worker) process

**Comment by babolivier** [comment]
I see, thanks. Could you look at the "Cache eviction rate" graph for the `*getEvent* (size)` label and see if it reports many size-related evictions?

**Comment by Fizzadar** [comment]
OK I believe I have got to the bottom of this - leftover from the NULL character fix which meant the update user directory background process was constantly failing and restarting, never updating the stream position.

Reverting the change in https://gitlab.com/beeper/synapse/-/commit/b5874621bea941f1aee59d728a13cbb17a37c438 has now stopped the constant memory growth.

The fetch event calls are still ongoing but I believe this is just the main process running through the huge gap in stream position going the background update, and should clear in the next hour or two. Will confirm and close this out.

**Comment by Fizzadar** [comment]
Confirmed this is now fixed by the above revert!

It would be good to investigate ways to better attribute nested background task CPU (if this had shown as user directory background task CPU it'd be super quick to identify), but will leave that for another issue.
