### ISSUE TITLE
redactions are not sent over federation if we do not have the original event

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12795]
When performing moderation actions, it is useful for moderators be able to send an `m.redaction` even if the original event has not yet been received on the moderator's server.

Currently, this does not work, because such redactions are not sent out over federation.

**Comment by richvdh** [comment]
The reason this happens is that the federation transmit loop calls [`get_all_events_stream`](https://github.com/matrix-org/synapse/blob/15da5e97a137106d0f0afc1b7fa833e153ba6c00/synapse/storage/databases/main/stream.py#L1005), which calls [`get_events_as_list`](https://github.com/matrix-org/synapse/blob/15da5e97a137106d0f0afc1b7fa833e153ba6c00/synapse/storage/databases/main/events_worker.py#L442), which drops any redaction event where we don't yet have the original.

**Comment by DMRobertson** [comment]
I'm guessing the relevant logic is

https://github.com/matrix-org/synapse/blob/b9778673587941277e15b067ad39cdf084f7dde5/synapse/storage/databases/main/events_worker.py#L505-L521

How would one tackle this---a new boolean parameter for `get_events_as_list`'s to ignore this check? Or perhaps a new `redact_behaviour`?

**Comment by H-Shay** [comment]
> it's tempting to say we should just make `_get_events_from_cache_or_db` public and use that.

Is there any reason not to do this?

**Comment by richvdh** [comment]
> > it's tempting to say we should just make `_get_events_from_cache_or_db` public and use that.
> 
> Is there any reason not to do this?

You might consider that it's a "low-level" function, and that having lots of similar-but-different entry points makes a component hard to use correctly.

But still, I think it's the cleanest solution to this problem.
