### ISSUE TITLE
Workers do not support knocks

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#12806]
The docs mention that `^/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)$` and `^/_matrix/client/(api/v1|r0|v3|unstable)/join/` can be handled, but this is notably missing `knock`.

If `/knock` can be handled, can it be added to the docs please? 😇

**Comment by dklimpel** [comment]
At the moment `/knock` can not be handled by `generic_worker`.

https://github.com/matrix-org/synapse/blob/1c910e2216a2f7fa57971ffbdede509fd493ebb0/synapse/app/generic_worker.py#L302-L324

There ist missing the import of `knock` and something like `knock.register_servlets(self, resource) `
