### ISSUE TITLE
Faster joins: Update user directory once state re-sync completes

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#12815]
---

Potentially useful / possible blockers:

- [ ] #14419 — might want to track the stream of un-partial-stated rooms and do a recomputation when it completes

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/blob/7c6b2204d143550d81e5bf9612c4e69fe0866b4c/synapse/handlers/federation.py#L1561-L1570

**Comment by squahtx** [comment]
> Also: what does the directory say _during_ re-sync, and is that ok?

During re-sync, the user directory reflects the current state of the room and excludes all remote users except new joiners.
