### ISSUE TITLE
Help with Keycloak OIDC integration

### ISSUE THREAD

**Issue by DelanoDuarte** [matrix-org/synapse#12827]
Hello, I've configured the matrix server with keycloak oidc and apparently everything seems to work well in terms of integration between the two applications.
The problem happens when we try to perform the login.
There is anything missing on my configuration ? At least on my login response the OIDC seems to appear and the Matrix server is recognizing it.
If any more details are needed, please, let me know.

![Captura de ecrã 2022-05-20, às 18 01 43](https://user-images.githubusercontent.com/14373130/169584758-dbdd9502-93bb-4ffd-b50d-7a8759d04fc0.png)
![Captura de ecrã 2022-05-20, às 18 02 25](https://user-images.githubusercontent.com/14373130/169584766-aace05b1-334f-4975-956c-9363d0624338.png)

**Comment by t3chguy** [comment]
This isn't how SSO Login works. The point of SSO is that you do not send your credentials to a different service (Synapse in this case).

You should be using this API https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3loginssoredirectidpid

**Comment by babolivier** [comment]
Closing this since @t3chguy answered the question. In the future, please use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) for support requests as we mostly use Github issues for bug reports and feature requests.

**Comment by t3chguy** [comment]
FTR if you did want login to work like this you would need a password provider instead - https://matrix-org.github.io/synapse/latest/password_auth_providers.html#:~:text=Password%20auth%20providers%20offer%20a,integrate%20with%20the%20authentication%20system. you could probably make use of https://github.com/ma1uta/matrix-synapse-rest-password-provider *BUT* typically SSO/CAS/OIDC is better
