### ISSUE TITLE
Invites push actions don't get persisted and can't be queried using /notifications if the user doesn't have any pusher registered

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/synapse#12839]
### Description

For invites there exists a special push rule: `.m.rule.invite_for_me`. This rule seems to never get evaluated and added to the event_push_actions table, which then causes /notifications to never return pending invites as notifications.

### Steps to reproduce

- Invite another user
- Search for the invite using the following query: `SELECT * FROM event_push_actions WHERE event_id = '$event'`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

I would like invites to actually show up as notifications!

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: neko.dev

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.59.1

- **Install method**: ebuild
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Gentoo
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by deepbluev7** [comment]
I guess that is explicitly disabled for some reason?!? https://github.com/matrix-org/synapse/blob/116a4c8340b729ffde43be33df24d417384cb28b/synapse/push/bulk_push_rule_evaluator.py#L149

**Comment by babolivier** [comment]
For the paper trail, this was introduced in For the paper trail, this bug was introduced in https://github.com/matrix-org/synapse/commit/ed3979df5faac6d63990f4230662ff8cdcf59584
