### ISSUE TITLE
Need a way to allow non-SSO users to use Key Backup on SSO-using hosts

### ISSUE THREAD

**Issue by tadzik** [matrix-org/synapse#12844]
**Description:**

On a host with both SSO users and non-SSO (e.g. bots) coexisting, it's impossible to use Key Backup as the latter. If we disable password auth (which makes sense when using SSO), even if we use our non-SSO user with its access token, an auth check will still be performed when uploading keys to key backup – and that will fail due to no available auth flow (and a 401) since there is no auth flow that the bot user can use.

Code-wise we end up [here](https://github.com/matrix-org/synapse/blob/67aae05ece9b6e07fedc73f737c0d6db6351d6c7/synapse/rest/client/keys.py#L75-L116) when setting up Key Backup in Element, and then [this](https://github.com/matrix-org/synapse/blob/67aae05ece9b6e07fedc73f737c0d6db6351d6c7/synapse/handlers/auth.py#L389) gives us no available options.

**Comment by richvdh** [comment]
@tadzik: for context, how does a "non-SSO user" get an access token in the first place if password auth is disabled?

Possibly the solution here is just to relax the `_password_enabled` check [here](https://github.com/matrix-org/synapse/blob/v1.59.1/synapse/handlers/auth.py#L396), to allow users to present a password for re-authentication even if passwords are disabled for login?

**Comment by erikjohnston** [comment]
@tadzik do you actually mean this API? I don't think the one you linked actually requires UI auth? https://github.com/matrix-org/synapse/blob/b83bc5fab57b37f75a79d02213d6032c586fd36e/synapse/rest/client/keys.py#L274-L291

**Comment by tadzik** [comment]
> for context, how does a "non-SSO user" get an access token in the first place if password auth is disabled?

@richvdh in this case the user is registered with an admin API, with shared secret registration – which gives us the access_token in the response.

@erikjohnston yeah, that looks about right – I may have mislinked things.

**Comment by erikjohnston** [comment]
> Possibly the solution here is just to relax the `_password_enabled` check [here](https://github.com/matrix-org/synapse/blob/v1.59.1/synapse/handlers/auth.py#L396), to allow users to present a password for re-authentication even if passwords are disabled for login?

I think that is probably fine, the only concern would be for servers that have changed from password to SSO, where this change will potentially show the password box for users that had signed up with a password. I don't think that is a big deal though.

**Comment by richvdh** [comment]
> I think that is probably fine, the only concern would be for servers that have changed from password to SSO, where this change will potentially show the password box for users that had signed up with a password.

possibly the `password_enabled` setting needs more options: `True`, `False`, `"only_for_reauth"`?
