### ISSUE TITLE
Dependencies issue in recent Docker images

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#12854]
[CI](https://github.com/matrix-org/synapse/runs/6566243070?check_suite_focus=true#step:6:1866) complains about a missing on matrix-common and we've seen similar reports about Jinja:

```
Traceback (most recent call last):

  File "/start.py", line 11, in <module>

    import jinja2

ModuleNotFoundError: No module named 'jinja2'
```

**Comment by babolivier** [comment]
Possibly fixed by https://github.com/matrix-org/synapse/pull/12853

**Comment by erikjohnston** [comment]
What was happening was that `poetry.core` package got updated, which combined with our random pinned `poetry` version caused it to think that *all* deps were dev dependencies, and so `poetry export` would write an empty `requirements.txt` and so no deps were actually installed in the final image.
