### ISSUE TITLE
`_run_push_actions_and_persist_event` re-starts a finished logging context when `persist_events_and_notify` raises an exception

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#12987]
When `persist_events_and_notify` raises an exception, we try to clean up push actions in a background task:

https://github.com/matrix-org/synapse/blob/e3163e2e11cf8bffa4cb3e58ac0b86a83eca314c/synapse/handlers/federation_event.py#L1961-L1969

`run_in_background` inherits the current logging context, but since we don't await the background task, we end up closing the logging context before the background task finishes. We ought to either await `remove_push_actions_from_staging` directly, or create a logging context for it.

**Comment by clokep** [comment]
> Actually every call to `run_in_background` where we discard the return value probably has the same issue.

I think `grep -r "  run_in_background" synapse` (note the two spaces before it) would be a quick way to find those. I see a bunch. 😢
