### ISSUE TITLE
Faster joins: send `heroes` to handle nameless rooms

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#12995]

**Comment by richvdh** [comment]
we *will* need to pass through `heroes`, to ensure that rooms without their own name get a useful title ("Bob and 4 others", etc)

**Comment by DMRobertson** [comment]
Is this something we can make progress on today? Does the initial set of state events sent from the resident server include the heroes' membership events?

**Comment by richvdh** [comment]
yes, the latter: we need to extend the response from `/send_join` to include heroes.

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/blob/70b33965065f0e93eaba68e371896149c9405f51/synapse/federation/federation_server.py#L1495-L1528 seems like it's a good place to start.
