### ISSUE TITLE
Faster joins: check compatibility with history import

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13003]
I suspect the MSC2716 code makes incorrect assumptions about whether state is complete at the insertion points.

https://github.com/matrix-org/synapse/blob/7c6b2204d143550d81e5bf9612c4e69fe0866b4c/synapse/handlers/federation_event.py#L778-L785

**Comment by richvdh** [comment]
cc @MadLittleMods

**Comment by MadLittleMods** [comment]
Maybe. We need the full state at the event you insert next to (the `/batch_send?prev_event_id`) to inherit from. See:

 - [`synapse/rest/client/room_batch.py#L139-L145`](https://github.com/matrix-org/synapse/blob/3d1d510fa9d6d46e08b347dd8c803e5dd9b8a5fe/synapse/rest/client/room_batch.py#L139-L145)
 - [`synapse/handlers/room_batch.py#L125-L150` -> `get_most_recent_full_state_ids_from_event_id_list`](https://github.com/matrix-org/synapse/blob/7c6b2204d143550d81e5bf9612c4e69fe0866b4c/synapse/handlers/room_batch.py#L125-L150)

**Comment by richvdh** [comment]
We should just disallow history import for partial-state rooms
