### ISSUE TITLE
Clean up synapse.api.auth.Auth

### ISSUE THREAD

**Issue by sandhose** [matrix-org/synapse#13019]
I'm trying to make sense to what is in [`synapse.api.auth.Auth`](https://github.com/matrix-org/synapse/blob/81608490e364d5a332b06606aba0703f2fb5d0a9/synapse/api/auth.py#L54).
The goal is to extract a clear interface for verifying access tokens, so we can override that more easily for the OIDC work.

I already cleaned up things related to access token verification & macaroons in #12986 

I'm finding a few method types:

 - things related to checking if a user can do something:
   - `check_user_in_room_or_world_readable`
   - `check_can_change_room_list`
   - `check_user_in_room`
   - `is_server_admin`
 - static methods to get the access token in a request
   - `has_access_token`
   - `get_access_token_from_request`
 - methods to get the requester of a request
   - `get_user_by_access_token`
   - `get_user_by_req`
   - `get_appservice_by_req`

There is also `check_auth_blocking`, which only acts as a proxy to `AuthBlocking.check_auth_blocking`.
Note that `is_server_admin` is also a simple proxy to `RegistrationWorkerStore.is_server_admin`.

The other interesting thing I found out is that `check_user_in_room` is called from three places:

 - `check_user_in_room_or_world_readable` (which makes sense)
 - in handlers related to typing notifications (which also makes sense, since you can't send typing notifications in rooms you're not in)
 - in [`rest.client.room.TimestampLookupRestServlet`](https://github.com/matrix-org/synapse/blob/3d1d510fa9d6d46e08b347dd8c803e5dd9b8a5fe/synapse/rest/client/room.py#L1180), which looks like an oversight, and should probably call `check_user_in_room_or_world_readable` instead

Other interesting things about a method: `get_appservice_by_req` is called from three places:

 - [`/register`](https://github.com/matrix-org/synapse/blob/3d1d510fa9d6d46e08b347dd8c803e5dd9b8a5fe/synapse/rest/client/register.py#L488), which seems not necessary, since a few lines bellow it would raise anyway if the appservice does not exist
 - [`DELETE /directory/room/<room_alias>`](https://github.com/matrix-org/synapse/blob/3d1d510fa9d6d46e08b347dd8c803e5dd9b8a5fe/synapse/rest/client/directory.py#L101), for some reason?
 - [`/login`](https://github.com/matrix-org/synapse/blob/3d1d510fa9d6d46e08b347dd8c803e5dd9b8a5fe/synapse/rest/client/login.py#L175), which looks like the only legit place where it is called

So, what I would like to do is:

 - remove the `check_auth_blocking` method, and use directly `AuthBlocking.check_auth_blocking` where it makes sense #13021 
 - move the two static methods as regular functions outside of the class
 - make the `TimestampLookupRestServlet` use `check_user_in_room_or_world_readable` #13062 
 - group and move the permissions checks to their own class
 - remove the usage of `get_appservice_by_req`:
   - #13093 
   - #13094

**Comment by sandhose** [comment]
Another thought: I think it would make sense to make the permissions-related functions pass a `Requester` instead of just a `UserID`. This would help lay the foundations for having restricted access tokens, as the `Requester` would probably have scope informations in it.

**Comment by clokep** [comment]
@sandhose Is this all set? I don't see any remaining work.

**Comment by DMRobertson** [comment]
The only outstanding thing from @sandhose's list is

> * group and move the permissions checks to their own class

which might still be worthwhile?

**Comment by erikjohnston** [comment]
Let's close, if the last remaining item is valuable then lets open a new issue.
