### ISSUE TITLE
`/thumbnail` should return more obvious error when `dynamic_thumbnails` is disabled

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#13016]
**Description:**

Currently `/thumbnail` will return a `404` `M_NOT_FOUND` when `dynamic_thumbnails` is disabled in `homeserver.yaml` (it is [disabled by default](https://github.com/matrix-org/synapse/blob/3d1d510fa9d6d46e08b347dd8c803e5dd9b8a5fe/synapse/config/repository.py#L181)). The response code is pretty confusing because the media does exist, it just can't be dynamically thumbnailed. We should instead return a `400` `M_UNKNOWN` with a friendly error explaining why ([already in spec](https://spec.matrix.org/v1.1/client-server-api/#get_matrixmediav3thumbnailservernamemediaid)).

Maybe this also depends on no `thumbnail_sizes` being defined in `homeserver.yaml` as well.

### Actual

✅ Works: `http://localhost:8008/_matrix/media/r0/download/hs1/tefQeZhmVxoiBfuFQUKRzJxc`

❌ Doesn't load, 404: `http://localhost:8008/_matrix/media/r0/thumbnail/hs1/tefQeZhmVxoiBfuFQUKRzJxc?width=400&height=195&method=scale`

```json
{
  "errcode": "M_NOT_FOUND",
  "error": "Not found [b'hs1', b'tefQeZhmVxoiBfuFQUKRzJxc']"
}
```

This really confused me because obviously the media does exist. The Synapse logs show:

```
2022-06-13 19:15:45,125 - synapse.rest.media.v1.thumbnail_resource - 382 - INFO - GET-319 - Failed to find any generated thumbnails
```

### Expected

When `dynamic_thumbnails` is turned off, `http://localhost:8008/_matrix/media/r0/thumbnail/hs1/tefQeZhmVxoiBfuFQUKRzJxc?width=400&height=195&method=scale` should return `400` `M_UNKNOWN`

> 400: The request does not make sense to the server, or the server cannot thumbnail the content. For example, the client requested non-integer dimensions or asked for negatively-sized images.
>
> *-- https://spec.matrix.org/v1.1/client-server-api/#get_matrixmediav3thumbnailservernamemediaid*

```json
{
  "errcode": "M_UNKNOWN",
  "error": "Cannot find existing thumbnail for the requested content and cannot generate one because `dynamic_thumbnails` is disabled (see `homeserver.yaml`)"
}
```

**Comment by richvdh** [comment]
Confused. If `dynamic_thumbnails` is off, the thumbnails should be generated when the media is uploaded. Why does the thumbnail not exist if the media does?

**Comment by MadLittleMods** [comment]
> Why does the thumbnail not exist if the media does?

Maybe it's an additional separate bug.

I am seeing this behavior with this [`homeserver.yaml` config](https://github.com/matrix-org/matrix-public-archive/blob/839e31a35ea7a654e79c08496bb86a25efc008e0/test/dockerfiles/synapse/homeserver.yaml). There is no `thumbnail_sizes` defined but I assume the [`DEFAULT_THUMBNAIL_SIZES`](https://github.com/matrix-org/synapse/blob/4579445cc54640341ef23cddad9c0518e90be63a/synapse/config/repository.py#L31-L37) should be kicking in?

Whenever media is uploaded, there are no errors in the logs:
```
2022-06-10 17:08:41,464 - synapse.rest.media.v1.media_repository - 210 - INFO - POST-53869 - Stored local media in file '/data/media_store/local_content/oW/ho/GoMjhWIZRVfeGLasLZnQ'
2022-06-10 17:08:41,484 - synapse.rest.media.v1.upload_resource - 104 - INFO - POST-53869 - Uploaded content with URI 'mxc://hs1/oWhoGoMjhWIZRVfeGLasLZnQ'
2022-06-10 17:08:41,486 - synapse.access.http.8008 - 450 - INFO - POST-53869 - ::ffff:172.22.0.1 - 8008 - {@archiver:hs1} Processed request: 0.022sec/0.001sec (0.001sec, 0.000sec) (0.011sec/0.009sec/1) 52B 200 "POST /_matrix/media/v3/upload HTTP/1.1" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" [0 dbevts]
```

This is from running the end-to-end tests at [`test/e2e-tests.js#L206-L233`](https://github.com/matrix-org/matrix-public-archive/blob/952a3acd4a5e25edc72714b7cb68d54e6418cf7a/test/e2e-tests.js#L206-L233). Any additional logging I should try turning on?

**Comment by q234rty** [comment]
Can confirm that currently matrix.org doesn't generate thumbnails in many cases, while servers running synapse 1.60.0 seem to work correctly. Should we move this to a new issue?

**Comment by reivilibre** [comment]
I agree that this seems to be a bug, but I'm not sure I agree entirely with the proposed solution — the wording in the spec makes it sound like the homeserver should return a larger thumbnail in one of the handful of specced sizes.

e.g. requesting 400×195 should give me a 640×480 thumbnail.

I guess this leaves the case where the client requests a thumbnail that is larger than the original, or is larger than the largest specced thumbnail size — maybe 400 would make sense here.

**Comment by MadLittleMods** [comment]
> the wording in the spec makes it sound like the homeserver should return a larger thumbnail in one of the handful of specced sizes.

Agreed 👍 and I think Synapse already does this in all of the [`_select_thumbnail` logic](https://github.com/matrix-org/synapse/blob/a164a46038b0e51142781619db0e6dec8e0c2aaa/synapse/rest/media/v1/thumbnail_resource.py#L385-L513).

But in this case, Synapse isn't generating any thumbnails on upload and we should have a better error message on why that may be. Created https://github.com/matrix-org/synapse/pull/13038 with a proposal. `404` isn't even a specced response anyway but it probably should at least be for a `mediaId` that does not exist.

We can also separately fix up the Synapse bugs which are causing it not to generate the thumbnails -> https://github.com/matrix-org/synapse/issues/13039
