### ISSUE TITLE
List removed community/group worker endpoints in upgrade.md

### ISSUE THREAD

**Issue by olmari** [matrix-org/synapse#13020]
I'd expect to see community worker endpoints that are going to be nuked in Synapse 1.61 ( https://github.com/matrix-org/synapse/pull/12936/files#diff-4eef4606c1f655c8f2b04944a322717d2dfe2a32f6df6df8403dad7ebdd00052 ) to be listed in Synapse upgrade notes at release time.

Reasoning: It is easy to check current state of _existing_ endpoints from workers.md, but opposite is not true, surprisingly hard to determine does one have an endpoint in their config that is _not_ listed on workers.md anymore. So at least upgrade notes should reveal "these endpoints are removed, go check your worker config".

**Comment by olmari** [comment]
Alternate/adjacent idea was to have some kind of "historical endpoints" section on workers.md. While nice idea in itself especially for not so pedantically up to date keeping server admin, I feel upgrade notes is exactly proper place to tell which (worker) endpoints going EOL.

**Comment by olmari** [comment]
Well I can easily copypaste the endpoints, I can do that and write description, I'll leave making doc looking proper to devs :)

**Comment by clokep** [comment]
Related to #11584.
