### ISSUE TITLE
Default `sync_response_cache_duration` can lead to clients never being able to initial sync

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#13027]
### Description

Large accounts or slow servers can mean that the client will retry `/sync` (without `?since`) until it gets a result. However, the server's default cache time for sync responses seemingly went from some number of minutes to zero. This means that the server processes large `/sync` requests in the background but immediately throws away the result if the client gave up waiting and tried a second request.

There should be a non-zero default on the config value.

### Steps to reproduce

- Be in thousands of rooms
- Have a slow-ish server
- Try to sync your account

### Homeserver

t2l.io & t2bot.io

### Synapse Version

1.60.0

### Installation Method

pip (from PyPI)

### Platform

N/A

### Relevant log output

```shell
N/A
```

**Comment by reivilibre** [comment]
This is sounding similar to (maybe the cause of) #12971.

**Comment by erikjohnston** [comment]
> However, the server's default cache time for sync responses seemingly went from some number of minutes to zero. 

I don't believe it has ever been non-zero ftr, at least I can't see any evidence of that in the code.

**Comment by chagai95** [comment]
This was bothering me for a good few months, so happy I found this, thx so much for reporting!

**Comment by turt2live** [comment]
> > However, the server's default cache time for sync responses seemingly went from some number of minutes to zero.
> 
> I don't believe it has ever been non-zero ftr, at least I can't see any evidence of that in the code.

I have vague memory of it being 5 minutes, though that could have been a matrix.org hotfixes thing. Prior to the config setting it was easier to get a successful sync, at least.
