### ISSUE TITLE
No thumbnails generated on upload when using generic `Content-Type: application/octet-stream`

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#13039]
### Description

No thumbnails generated on upload.

Spawning from https://github.com/matrix-org/synapse/issues/13016

### Steps to reproduce

 1. Setup synapse with this [`homeserver.yaml`](https://github.com/matrix-org/matrix-public-archive/blob/0f493a241ebde5741f503fb568e02a378e185f67/test/dockerfiles/synapse/homeserver.yaml) (based on the Complement one)
    - `dynamic_thumbnails: false`
 1. Upload an image (`/upload`)
    - [test image](https://github.com/matrix-org/matrix-public-archive/blob/cead1796b88e6555d4792b63db7288cd721ccf03/test/fixtures/friction_between_surfaces.jpg).
 1. Try to request a full version of the image (`/download`) -> 200 ✔
 1. Try to request a thumbnail of that image (`/thumbnail`) -> 404 ❌

Reproducible in [this end-to-end (e2e) test](https://github.com/matrix-org/matrix-public-archive/blob/952a3acd4a5e25edc72714b7cb68d54e6418cf7a/test/e2e-tests.js#L206-L233) with this [test image](https://github.com/matrix-org/matrix-public-archive/blob/cead1796b88e6555d4792b63db7288cd721ccf03/test/fixtures/friction_between_surfaces.jpg).

### Homeserver

local test instance, [`homeserver.yaml`](https://github.com/matrix-org/matrix-public-archive/blob/0f493a241ebde5741f503fb568e02a378e185f67/test/dockerfiles/synapse/homeserver.yaml)

### Synapse Version

Latest `develop` (2022-06-13) (~1.61.0rc1)

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Windows 10

```
{
  "server_version": "1.61.0rc1",
  "python_version": "3.9.13"
}
```

### Relevant log output

Whenever media is uploaded, there are no errors in the logs (`docker logs -f --tail 10 matrix_public_archive_test_hs1_1`):

```shell
2022-06-10 17:08:41,464 - synapse.rest.media.v1.media_repository - 210 - INFO - POST-53869 - Stored local media in file '/data/media_store/local_content/oW/ho/GoMjhWIZRVfeGLasLZnQ'
2022-06-10 17:08:41,484 - synapse.rest.media.v1.upload_resource - 104 - INFO - POST-53869 - Uploaded content with URI 'mxc://hs1/oWhoGoMjhWIZRVfeGLasLZnQ'
2022-06-10 17:08:41,486 - synapse.access.http.8008 - 450 - INFO - POST-53869 - ::ffff:172.22.0.1 - 8008 - {@archiver:hs1} Processed request: 0.022sec/0.001sec (0.001sec, 0.000sec) (0.011sec/0.009sec/1) 52B 200 "POST /_matrix/media/v3/upload HTTP/1.1" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" [0 dbevts]
```

On `/thumbnail`:

```shell
022-06-13 21:53:34,251 - synapse.rest.media.v1.thumbnail_resource - 311 - DEBUG - GET-4892 - _select_and_respond_with_thumbnail: media_id=mTwomIHqDRUQLrXnMquWOpme desired=400x195 (scale) thumbnail_infos=[]
2022-06-13 21:53:34,251 - synapse.rest.media.v1.thumbnail_resource - 394 - INFO - GET-4892 - Failed to find any generated thumbnails
2022-06-13 21:53:34,252 - synapse.access.http.8008 - 450 - INFO - GET-4892 - ::ffff:172.22.0.1 - 8008 - {None} Processed request: 0.009sec/0.001sec (0.001sec, 0.000sec) (0.001sec/0.000sec/2) 209B 400 "GET //_matrix/media/r0/thumbnail/hs1/
```

**Comment by q234rty** [comment]
I'm not sure what changed but I can no longer reproduce this by uploading the test image in the issue. However, a thumbnail is still not generated when uploading a webp image.

**Comment by louis-goyard** [comment]
I also encountered this issue while uploading pictures (on the matrix.org homeserver) with an erroneous script that uploaded the file with a wrong `Content-Type` in the POST request.

- This correctly uploads the file and generate a thulbnail that can then be served by the /thumbnail route:

```
curl -s -X POST -H "Content-Type: image/webp" --data-binary "@/home/foo/pic.webp" "https://matrix.org/_matrix/media/r0/upload?access_token=$STPKG_TOKEN"
```

- However, this correctly uploads the file but then when trying to get a thumbnail I get a 500 response:  `{"errcode":"M_UNKNOWN","error":"Unexpected Error","mr_errcode":"M_UNKNOWN"}`:

```
curl -s -X POST -H "Content-Type: webp" --data-binary "@/home/foo/pic.webp" "https://matrix.org/_matrix/media/r0/upload?access_token=$STPKG_TOKEN"
```

Tested it with `image/webp`, `image/png`, `image/webp`, `image/gif`.
It seems like the media upload manage to recover from the wrong `Content-Type` given by the user, but the thumbnailer doesn't.

Either way, it causes error later when trying to get the thumbnail for a now valid media, which shouldn't happen.

**Comment by richvdh** [comment]
@MadLittleMods does your test case set the `Content-Type` header? I think not doing so would explain why no thumbnail is generated.

**Comment by q234rty** [comment]
@louis-goyard Can you upload the webp image you used? When I upload a webp w/ `curl -s -X POST -H "Content-Type: image/webp" --data-binary "@/home/foo/pic.webp" "https://matrix.org/_matrix/media/r0/upload?access_token=$STPKG_TOKEN"` a thumbnail is not generated.

**Comment by MadLittleMods** [comment]
> @MadLittleMods does your test case set the `Content-Type` header? I think not doing so would explain why no thumbnail is generated.

@richvdh It's just set to [`application/octet-stream`](https://github.com/matrix-org/matrix-public-archive/blob/952a3acd4a5e25edc72714b7cb68d54e6418cf7a/test/client-utils.js#L190). I guess that makes sense and just feels a little weird if the media works later at full-size or can be dynamically thumbnailed. Probably some way we can auto-detect like the header in the first few bytes if we really want to.

**Comment by louis-goyard** [comment]
> @louis-goyard Can you upload the webp image you used? When I upload a webp w/ `curl -s -X POST -H "Content-Type: image/webp" --data-binary "@/home/foo/pic.webp" "https://matrix.org/_matrix/media/r0/upload?access_token=$STPKG_TOKEN"` a thumbnail is not generated.

I doubt that this is related to the picture uploaded, as this happened to me with every single picture I uploaded. In any case, [here is the file](https://hashi.re/friction.webp).

To be sure, I checked on my homeserver (1.63.0) with and without `dynamic_thumbnails`, and the results were the same as on matrix.org.

Uploading the file with `Content-Type: application/octet-stream` doesn't generate the thumbnail, and when downloading the file it is downloaded as `application/octet-stream`. In this case, not generating a thumbnail seems correct since only images and such should generate one.

**Comment by q234rty** [comment]
I just uploaded the file with the command above at `mxc://matrix.org/QUENpqcRoCxNLvRZVolkZZbt` but there's no thumbnail on https://matrix.org/_matrix/media/r0/thumbnail/matrix.org/QUENpqcRoCxNLvRZVolkZZbt?width=1600&height=64&method=scale

Note how https://matrix.org/_matrix/media/r0/download/matrix.org/QUENpqcRoCxNLvRZVolkZZbt gives the correct mime type `image/webp`; this won't happen if the Content-Type was wrong when uploading the image.
