### ISSUE TITLE
Remove 'Contents' section from the Configuration Manual

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#13053]
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#contents

Seems redundant when we have a Table of Contents sidebar?

Potentially related: https://github.com/matrix-org/synapse/issues/12752. cc @H-Shay.

**Comment by H-Shay** [comment]
What browser are you using? I don't see a table of contents sidebar on Firefox, the greater docs sidebar shows up but that's it...

**Comment by aaronraimist** [comment]
It shows up for me in Firefox. You may not see it because there is a minimum window width before it is shown.

<img width="1589" src="https://user-images.githubusercontent.com/5855073/173689765-50be6fb3-47d0-46cc-a70a-003d238e9473.png">

**Comment by anoadragon453** [comment]
I sometimes notice the ToC not showing up on certain computers as well, and we might want to consider lowering the minimum width.

@H-Shay could I ask what your screen resolution in pixels in? :grin:

**Comment by H-Shay** [comment]
Ah yes when I expanded the window to the entire screen I could see it. My screen resolution is 1920x1080.
