### ISSUE TITLE
ERROR:root:Synapse 1.61.0 needs Jinja2>=3.0, but can't determine Jinja2's version

### ISSUE THREAD

**Issue by Jieiku** [matrix-org/synapse#13105]
### Description

Matrix server has been running fine for about a year, a recent update seems to have somehow broke things..

It would not start and just tries to start over and over crashing in a loop:

Jun 18 20:21:31 Matrix systemd[1]: matrix-synapse.service: Control process exited, code=exited, status=1/FAILURE
Jun 18 20:21:31 Matrix systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jun 18 20:21:31 Matrix systemd[1]: Failed to start Synapse Matrix homeserver.
Jun 18 20:21:31 Matrix systemd[1]: matrix-synapse.service: Consumed 1.355s CPU time.

I stopped the service and entered the virtual environment and tried to start it directly, and this is the error I see:

### `ERROR:root:Synapse 1.61.0 needs Jinja2>=3.0, but can't determine Jinja2's version`

I checked and Jinja2 seems to be fully installed and updated:

```
pip install --upgrade "Jinja2"
Requirement already up-to-date: Jinja2 in ./lib/python3.8/site-packages (3.1.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=2.0 in ./lib/python3.8/site-packages (from Jinja2) (2.1.1)
```

### Steps to reproduce
`/opt/venvs/matrix-synapse/bin/python3.8 -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys`

### Homeserver

self-hosted for 1 year.

### Synapse Version

no longer runs, but should be version 1.61.0

### Installation Method

pip (from PyPI)

### Platform

runs in Ubuntu 20.04 LXC container. (has without issue for about a year)

### Relevant log output

```shell
I understand its difficult without logs, the logs dont show anything useful, I am hoping that somebody else has ran into this and knows the cause.
```

### Anything else that would be useful to know?

Not that I can think of.

**Comment by DMRobertson** [comment]
We have come across something similar before when importlib-metadata and pip disagree on which package version is installed.

Check the site-packages directory in the virtualenv. Can you see dist-info directories for Jinja2? There should be exactly one. I would guess that either
- there are multiple such directories, or
- there is exactly one directory, but its metadata is malformed.

One thing you could try
- uninstall jinja2 with pip
- repeat the installation until it fails (to clean up extra dist-info directories; iirc uninstall will only remove one of these)
- reinstall jinja2

**Comment by DMRobertson** [comment]
Other notes for my own interest:
- the logger says "root" here;
- we could put the advice above in the error message
- there used to bean error message advising people to pip install --upgrade. If there's an upper bound this will be inaccurate. We might be able to give a more precise pip install command.

**Comment by Jieiku** [comment]
Spot On!

```
cd /opt/venvs/matrix-synapse/lib/python3.8/site-packages
ls
jinja2
Jinja2-2.11.2.dist-info
Jinja2-3.0.0.dist-info
Jinja2-3.1.2.dist-info

(matrix-synapse) root@Matrix:/opt/venvs/matrix-synapse/lib/python3.8/site-packages# pip uninstall jinja2
Found existing installation: Jinja2 3.1.2
Uninstalling Jinja2-3.1.2:
  Would remove:
    /opt/venvs/matrix-synapse/lib/python3.8/site-packages/Jinja2-3.1.2.dist-info/*
    /opt/venvs/matrix-synapse/lib/python3.8/site-packages/jinja2/*
Proceed (y/n)? y
  Successfully uninstalled Jinja2-3.1.2
(matrix-synapse) root@Matrix:/opt/venvs/matrix-synapse/lib/python3.8/site-packages# pip uninstall jinja2
Found existing installation: Jinja2 3.0.0
Uninstalling Jinja2-3.0.0:
  Would remove:
    /opt/venvs/matrix-synapse/lib/python3.8/site-packages/Jinja2-3.0.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled Jinja2-3.0.0
(matrix-synapse) root@Matrix:/opt/venvs/matrix-synapse/lib/python3.8/site-packages# pip uninstall jinja2
Found existing installation: Jinja2 2.11.2
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 78, in run
    uninstall_pathset = req.uninstall(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 686, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 535, in from_dist
    for path in uninstallation_paths(dist):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 67, in unique
    for item in fn(*args, **kw):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 85, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/venvs/matrix-synapse/lib/python3.8/site-packages/Jinja2-2.11.2.dist-info/RECORD'
```

For the malformed one that did not uninstall I removed the directory:

`rm -rf Jinja2-2.11.2.dist-info`

Then I reinstalled jinja2:

`pip install jinja2`

Matrix is now back up and running, thanks a ton!

**Comment by DMRobertson** [comment]
@Jieiku glad to hear it. Out of curiosity, is there anything unusual about your installation setup? 
You said that you're using plain pip, which is interesting; we've seen this problem (old dist-info directories lying around) occasionally bite us when using pip via poetry, but not when using pip directly.

**Comment by Jieiku** [comment]
honestly its been running smoothly for over a year, without a hiccup and I have a horrible memory, let me find my notes (I document everything) and I can post how I originally set this up.

**Comment by Jieiku** [comment]
I found my notes. They are 539 lines long, because we setup everything (synapse, sydent, element)

I think this is the part your interested in though (also it seems I was mistaken I used apt to install originally)

### Install Matrix Synapse Py3 Server:
```shell
sudo apt install -y software-properties-common apt-transport-https wget curl lsb-release libpq5

sudo wget -qO /usr/share/keyrings/matrix-org-archive-keyring.gpg https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/matrix-org.list
sudo apt update

sudo apt install -y matrix-synapse-py3
```

**Download the missing template files for matrix-synapse-py3:**
```shell
cd
wget https://github.com/matrix-org/synapse/tarball/develop
sudo tar -xvzf develop
sudo mv matrix-org-synapse*/synapse/res /var/lib/matrix-synapse/res
sudo rm -rf develop matrix-org-synapse*
sudo chown -R matrix-synapse:nogroup /var/lib/matrix-synapse/res
```

**Comment by DMRobertson** [comment]
Thanks, it looks like this was using the matrix.org debian package then. Interesting... I wonder if there is some bug where we don't clean up old dist-info directories after upgrading a package in the vendored virtualenv?

**Comment by Jieiku** [comment]
Well I manage 3 installs of matrix, one of them I update pretty much every single day.(it did not have an issue) The one that had issues I neglected to update for approximately 2 months before updating. Hope that helps.

Also I believe it went from 1.49 to 1.61
