### ISSUE TITLE
Config option to fully delete and remove messages after deleting them in a room

### ISSUE THREAD

**Issue by sla-te** [matrix-org/synapse#13109]
I had found the "janitor" (https://github.com/xwiki-labs/synapse_scripts) repo to do that but as it was strongly advised not to use it I did not. I find the behaviour Telegram has for messages - deleting will immediately hide them from the message log and they are deleted for good - much more appealing.

How can I achieve the same behaviour in my homeserver?

**Comment by DMRobertson** [comment]
> deleting will immediately hide them from the message log 

Clients could choose to do this, but Synapse can't enforce this. (Its job is to tell the client the message has been "deleted" (redacted).

>  they are deleted for good - much more appealing.

Could you expand on this? What do you mean by "deleted for good"?

**Comment by sla-te** [comment]
> Clients could choose to do this, but Synapse can't enforce this. (Its job is to tell the client the message has been "deleted" (redacted).

So is the message fully deleted on the server if we delete it in the client?

https://user-images.githubusercontent.com/22568014/175131763-42b8cbf3-bb73-484a-bee2-e867fc1e9c92.mp4

**Comment by DMRobertson** [comment]
> So is the message fully deleted on the server if we delete it in the client?

Deleting a message in a room does the following:
- The content of the message is deleted by Synapse.
- Synape tells all other homeservers in the room that the event should be deleted.
  - we can't guarantee that this takes place; other servers might be offline, or a malicious server might refuse to delete it. Clients might also refuse to delete the data.
  - it's like email: once it's out there, it's out there. All you can do is request nicely that others delete their copy of a message.
- Some (minimal) metadata of the message (e.g. who sent it, when it was sent) is preserved. This is necessary to allow homeservers to keep synchronising with each other.

I hope that makes sense. See "event redaction" on the matrix spec more details.

**Comment by sla-te** [comment]
Thank you for the thorough explanation, now its all clear.
