### ISSUE TITLE
Device names are returned over federation by `/keys/query` even if `allow_device_name_lookup_over_federation` is false

### ISSUE THREAD

**Issue by RUzOfuz5m** [matrix-org/synapse#13114]
### Description

    allow_device_name_lookup_over_federation: false 

This will still show device names if someone invites you to a room and you have not joined yet.

### Steps to reproduce

- invite someone to a 1:1 chat on a different homeserver with `allow_device_name_lookup_over_federation:` set to false
- Before they join, click on their Bubble to bring up the side menu of their profile.
- expand N sessions
- Look at the name of their sessions.
- Have the user join the 1:1 chat.
- bring up their profile on the side menu again.
- expand N sessions
- The names are no longer visible, you now see the ID.

### Homeserver

matrix.org + another home server

### Synapse Version

{"server_version":"1.61.0","python_version":"3.9.13"}

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

docker pull matrixdotorg/synapse

### Relevant log output

```shell
n/a
```

### Anything else that would be useful to know?

n/a

**Comment by anoadragon453** [comment]
Potentially related: #10015.

**Comment by anoadragon453** [comment]
Looks like this is a result of `on_federation_query_client_keys` making use of `query_local_devices`, which happily returns device names:

https://github.com/matrix-org/synapse/blob/c52abc1cfdd9e5480cdb4a03d626fe61cacc6573/synapse/handlers/e2e_keys.py#L443-L460

https://github.com/matrix-org/synapse/blob/2cc5ea933dbe65445e3711bb3f05022b007029ea/synapse/storage/databases/main/end_to_end_keys.py#L150-L165

One solution would be to add a `return_device_names` boolean argument to `query_local_devices`, and `get_e2e_device_keys_for_cs_api`, which would control whether device names were returned. `on_federation_query_client_keys` could then check the homeserver config and set this option appropriately.
