### ISSUE TITLE
SSO / OIDC Azure AD: E2EE errors after renaming user in Azure AD

### ISSUE THREAD

**Issue by v411e** [matrix-org/synapse#13115]
### Description

We have our Azure AD connected to Synapse via OIDC. The `oidc_providers` config is almost the same as in the [sample config](https://matrix-org.github.io/synapse/latest/openid.html#microsoft-azure-active-directory).

One user changed her last name and therefore we changed the name in Azure AD. Afterwards, this happened:
- The user had E2EE-errors
- The secure key backup was not accepted anymore
- ~~A new account was created for the user~~
 
~~We did not expect this to happen, because the subject-identifier which is referred to in the config as `subject_claim` and defaults to `sub` should not have changed with renaming the user in Azure AD.~~

See [Synapse config_documentation](https://github.com/matrix-org/synapse/blob/develop/docs/usage/configuration/config_documentation.md#oidc_providers)
See [Microsoft OIDC reference](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims)

### Steps to reproduce

- Use Azure AD as SSO provider via OIDC
- Configure it as described in [sample config](https://matrix-org.github.io/synapse/latest/openid.html#microsoft-azure-active-directory)
- Create a user
- Sign into synapse, use the account
- *Everything works fine until now*
- Rename the user in Azure AD

Now:
- ~~A new user is created~~
- The user has E2EE problems
- ~~Sign into the new account does not work via SSO (probably, because old account is still linked to SSO?)~~

### Homeserver

another homeserver

### Synapse Version

1.57.1

### Platform

Docker container

### Relevant log output

```shell
We do not have logs now, but might provide some if needed.
```

### Anything else that would be useful to know?

UPDATE:
A new user was not created. Sign in with the old user still works. Sorry for the irritation.
But this still does not explain, why the user gets E2EE errors once renamed.

**After reading the code below: Do we have to set `allow_existing_users: True` if we want SSO not to fail when renaming a user?**

Code for performing SSO: https://github.com/matrix-org/synapse/blob/d54909956ef616d976b3d9969be994df5b65030a/synapse/handlers/sso.py#L360-L498

Code for mapping external_user_id to matrix user: https://github.com/matrix-org/synapse/blob/d54909956ef616d976b3d9969be994df5b65030a/synapse/handlers/sso.py#L317-L358

Code for checking grandfathers: https://github.com/matrix-org/synapse/blob/d54909956ef616d976b3d9969be994df5b65030a/synapse/handlers/oidc.py#L975-L1002

**Comment by anoadragon453** [comment]
Reading the relevant code, the documentation looks a bit misleading:

> `allow_existing_users`: set to true to allow a user logging in via OIDC to match a pre-existing account **instead of failing**. This could be used if switching from password logins to OIDC. Defaults to false.

It is my understanding that account creation will not fail, but instead a new user will be created -- as you experienced in this issue.

@v411e can you confirm by renaming a test account if enabling `allow_existing_users` gives you the behaviour you expected? This would help confirm my suspicions.

**Comment by v411e** [comment]
We rechecked this and discovered that in fact no new user was created. So everything fine on this part. Sorry for messing this up. :confused: 

But it is still weird, that the user got E2EE errors just after renaming his Azure AD account. We will look into this further and see if we can confirm this with a test user. Otherwise we will close the issue.

Thanks a lot for helping out!

**Comment by richvdh** [comment]
@v411e were you able to reproduce this problem?

**Comment by anoadragon453** [comment]
I'm going to close this as there doesn't appear to have been much activity on it lately and cannot be reproduced. Please reopen/file a new issue if the problem reoccurs!
