### ISSUE TITLE
Synapse supports unspecced `DELETE /directory/list/room/<room ID>` endpoint

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#13111]
Synapse supports a `DELETE  /directory/list/room/<room ID>` endpoint which appears to be unspecced. (It's specced with GET and PUT).

https://github.com/matrix-org/synapse/blob/e24ff8ebe3d4119d377355402245947f7de61c00/synapse/rest/client/directory.py#L157-L166

_Originally posted by @DMRobertson in https://github.com/matrix-org/synapse/issues/13102#issuecomment-1163320590_

DELETE is a shortcut for PUTting private visibility. I'd like to either spec it or remove it.

**Comment by santhoshivan23** [comment]
@DMRobertson The right place to spec it is in **_matrix-spec_** repo right?

**Comment by clokep** [comment]
Part of #8334.

**Comment by richvdh** [comment]
> I think its better to spec it

I don't like having more than one way to do something: it leads to incompatible implementations. If you can do the equivalent with `PUT`, better to remove `DELETE`.

**Comment by DMRobertson** [comment]
> I don't like having more than one way to do something: it leads to incompatible implementations. If you can do the equivalent with `PUT`, better to remove `DELETE`.

Agreed entirely. What I should have said above: we should check to see if any clients use this (i.e. if `matrix.org` has seen a significant number of requests to this endpoint with method DELETE). I hope not, so we can rip this out.

**Comment by richvdh** [comment]
element-web uses `PUT`. No `DELETE` requests to `matrix.org` in the past week. Let's rip it out.

**Comment by DMRobertson** [comment]
There is also an unspecced DELETE on the application-service version of this endpoint.
