### ISSUE TITLE
Use `room_stats_state.room_type` column instead of fetching `m.room.create` event

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13130]
#13031 introduced a `room_type` column in `room_stats_state`. There are now one or two places where we can avoid fetching `m.room.create` events and just use the new column instead.

Searching for `EventContentFields.ROOM_TYPE` or `"room_type"` ought to find them all.

eg. if we make `get_room_with_stats` return `room_type`, we can avoid fetching the `m.room.create` event in `RoomSummaryHandler._build_room_entry`.

**Comment by clokep** [comment]
We do need to wait until the background update finishes, however. I'm unsure if we have a standard way of doing that?

**Comment by clokep** [comment]
> eg. if we make `get_room_with_stats` return `room_type`

Looks like #13208 already did this part! 🎉
