### ISSUE TITLE
Unread counts are broken in 1.62.0rc1

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13138]
Unread counts for rooms are jumping to absurd numbers randomly. Other times they increment correctly.

**Comment by squahtx** [comment]
changes of interest:
- #13005
- #13096
- #13118 
- #13119

**Comment by deepbluev7** [comment]
I think this is still happening. I get random 20 notifications in a room where there are 1 or 1 where there are 0. At first I thought it was a client bug, but I think it is just this still happening with rc2.

**Comment by erikjohnston** [comment]
> I think this is still happening. I get random 20 notifications in a room where there are 1 or 1 where there are 0. At first I thought it was a client bug, but I think it is just this still happening with rc2.

Can you check if there are any pending background schema updates? (By looking at `background_updates` table). Also note that if you were running RC1 then rooms might remain broken until you send another read receipt in the room.

**Comment by erikjohnston** [comment]
This might be: https://github.com/matrix-org/synapse/pull/13168

**Comment by deepbluev7** [comment]
#13168 seems to indeed have fixed it.
