### ISSUE TITLE
Faster joins: improve handling of race where we can fail to persist a client event with partial state after `_sync_partial_state_room` clears the partial state flag for a room

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13173]
Follow on from #12988.

Currently, when we encounter the race in #12988, we send a 429 Too Many Requests back to clients with the expectation that a retry happens.

[@reivilibre notes that some clients may require retries to be manually initiated](https://github.com/matrix-org/synapse/pull/13100#discussion_r912898195), which is not good UX.

We can improve things by doing some of the retries internally in synapse.

---

A handy plot of code paths which create client events:
![graphviz](https://user-images.githubusercontent.com/8349537/174153437-14910861-e202-400e-b3cb-3d6c907e8755.svg)
The 429 gets raised in `EventCreationHandler.handle_new_client_event`. Event contexts are computed in orange methods.

**Comment by squahtx** [comment]
@reivilibre spotted an occurrence of the race during a complement run: https://github.com/matrix-org/synapse/runs/7397381295?check_suite_focus=true#step:4:2049
This one looks like it's on the `_local_membership_update` path

**Comment by reivilibre** [comment]
If we want to just make Complement retry the request, this will do it: https://github.com/matrix-org/complement/pull/414

I don't know if that's something we actually want to do or not?
