### ISSUE TITLE
Unread count keeps showing up for some rooms

### ISSUE THREAD

**Issue by afranke** [matrix-org/synapse#13196]
### Description

A private room I’m in keeps showing a (2) unread message count on client launch, both on Element Web and Android, even after I cleared cache.

### Steps to reproduce

- got some messages in a specific private room
- read them on Element Web (the count disappears)
- left home, started Element Android, the count appeared again for that room but no new message was visible; opening the room here makes the count go away again
- went back home, started Element Web again, the same count was back again.
- read the room again, did a clear cache & reload, the count is back again.

This all happened within the past 24 hours. During that time, I also have had counts appear on direct conversations with no new events while the Web client was running. That is not as reproducible though.

### Homeserver

matrix.org

### Synapse Version

1.61.0

### Platform

:shrug: matrix.org

### Relevant log output

```shell
I don’t have access to that.
```

**Comment by DMRobertson** [comment]
> got some messages in a specific private room

Are you able to share the room ID for debugging?

**Comment by afranke** [comment]
!zMjRxBhQzSpwVQMPLS:gnome.org

**Comment by kittykat** [comment]
I'm getting this issue annoyingly often for `!TxHCEvTmqctXITtVQO:matrix.org` last night and this morning

**Comment by erikjohnston** [comment]
Aha! I think I've spotted the problem. We don't correctly take into account the receipts at:

https://github.com/matrix-org/synapse/blob/a962c5a56de69c03848646f25991fabe6e4c39d1/synapse/storage/databases/main/event_push_actions.py#L1013-L1026

which is usually fine as we will have deleted push actions that have been read, *except* for highlights. Which is why we see the problem in DMs

**Comment by afranke** [comment]
The room I was reporting this for is not a DM **but** the latest message does indeed contain a highlight to me. It has also been edited, hence a (2) count. It checks out. :slightly_smiling_face:
