### ISSUE TITLE
Drop support for calling `/_matrix/client/v3/account/3pid/bind` without an `id_access_token`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13201]
The [spec](https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3account3pidbind) has required an `id_access_token` param for `/account/3pid/bind` ever since it was introduced to the spec in https://github.com/matrix-org/matrix-spec-proposals/pull/2328.

We currently accept requests without an `id_access_token`, and then call `/_matrix/identity/api/v1/3pid/bind`, which was removed from the spec over a year ago ([msc2713](https://github.com/matrix-org/matrix-spec-proposals/pull/2713)).

Instead, we should simply reject any requests that do not pass an `id_access_token`.

**Comment by richvdh** [comment]
I've been unable to find any outgoing requests to `/_matrix/identity/api/v1/3pid/bind` (other than as a fallback when `/_matrix/identity/api/v2/3pid/bind` 404s, see https://github.com/matrix-org/synapse/blob/v1.62.0/synapse/handlers/identity.py#L235-L238) on matrix.org in the last week, so I think we can assume this is unused.

**Comment by richvdh** [comment]
(while we're at it, we should remove that fallback to `/_matrix/identity/api/v1/3pid/bind`)

**Comment by richvdh** [comment]
Part of #9677

**Comment by Vetchu** [comment]
> I've been unable to find any outgoing requests to `/_matrix/identity/api/v1/3pid/bind` (other than as a fallback when `/_matrix/identity/api/v2/3pid/bind` 404s, see https://github.com/matrix-org/synapse/blob/v1.62.0/synapse/handlers/identity.py#L235-L238) on matrix.org in the last week, so I think we can assume this is unused.

I actually see this function used there: https://github.com/matrix-org/synapse/blob/v1.62.0/synapse/rest/client/account.py#L756.

Is this also part of this refactor? 

If so, how should it be handled?
