### ISSUE TITLE
Upgraded to v1.62.0, "Mentions Only" rooms suddenly start having notification counts

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#13219]
### Description

I have most/all of my rooms manually set to Mentions Only, which should mean they don't get notification counts unless I've been mentioned. Somewhat randomly, I've started getting counts on rooms periodically in Element Web, which is powered purely by what is given in `/sync` from the server. The rooms are not consistent, and the problem only persists for a few messages before going back to behaving properly.

I've also noticed that sometimes the badge gets "stuck": even though I've sent and received new messages, it's almost as if my (implied) read receipt isn't enough to clear the unreadness of the room. There's a 40% chance this particular point is a client issue, but worth mentioning in case that 60% chance sparks ideas server-side.

### Steps to reproduce

1. Set a room to Mentions Only
2. Engage in conversation in that room
3. Eventually get a grey badge (indicating unread, unnotified, message count)
4. Continue engaging
5. Badge goes away

### Homeserver

t2l.io

### Synapse Version

v1.62.0

### Installation Method

pip (from PyPI)

### Platform

Ubuntu server, hosted in the ✨cloud✨

### Relevant log output

```shell
Unclear what would be relevant.
```

### Anything else that would be useful to know?

This problem only started happening ~24 hours after I upgraded to v1.62.0 (from v1.61.1). It's happened four times since then though. I updated the same day as the v1.62.0 release.

I don't use the global push rule to set rooms to Mentions Only: when I join a new room, I click the bell on that room and change it there. My default push rules are similar to those of a brand new user: unread messages cause a badge.

The rooms this has been happening in have been in my room list for a long while (years): they are not recent joins. Not sure if relevant, but might be helpful?

**Comment by erikjohnston** [comment]
@turt2live for a given room that has that problem can you select all rows for that room and your user from `event_push_actions` and `event_push_summary` please?

**Comment by erikjohnston** [comment]
> should I also re-run when in the middle of it happening?

Yes please! That data is interesting, but will be more interesting to compare with when its broken

**Comment by turt2live** [comment]
I think I've been seeing https://github.com/matrix-org/synapse/issues/13196 - closing in favour of that.
