### ISSUE TITLE
Upgrade Python version in Docker release

### ISSUE THREAD

**Issue by danger89** [matrix-org/synapse#13234]
**Description:**

Please update the Python version in your Docker container releases to at least Python 3.10 or higher.

I suffer from people who register on my public server, I would like to trace their IP addresses. See also: https://github.com/matrix-org/synapse/issues/12014#issuecomment-1043143104

However, I'm using the Synapse Docker image.

**Latest version:** Python 3.10.5

Thanks in advance.

**Comment by danger89** [comment]
PR created https://github.com/matrix-org/synapse/pull/13237

**Comment by DMRobertson** [comment]
Per https://github.com/matrix-org/synapse/issues/8674#issuecomment-719990241 we have preferred to keep the version of Python at one-less-than CPython stable. (We want to give CPython releases a few weeks at least to shake out any bugs or incompatibilities in the ecosystem).

However we have recently discussed this within the team and would be willing to bump to Python 3.11 now. If someone would like to create a PR doing this we'd gratefully accept this (cc @katlol). https://github.com/matrix-org/synapse/pull/13237/files is an example that would have sufficed for 3.9 -> 3.10

**Comment by katlol** [comment]
@DMRobertson Of course, thank you! I created #14875 for this.
