### ISSUE TITLE
`/state_ids` federation requests causes large memory spikes

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#13246]
Especially if we get some in quick succession, as we will cache the state in memory.

We probably want to add a new (specced) endpoint that allows requesting of *deltas* of state, to reduce the amount of data fetched from the DB.

We could also decide not to cache result of `/state_ids`? But we might get the same request multiple times.

**Comment by MadLittleMods** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/6597
