### ISSUE TITLE
Faster joins: room alias server list may be incomplete

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13287]
If a room alias is added on a server that is doing a faster join, the list of servers associated with the alias may be incomplete until the faster join completes.

**Comment by richvdh** [comment]
Currently we probably return just ourselves, which is useless. We should probably return the list of servers we got from the `/send_join`, which will be good enough.

**Comment by richvdh** [comment]
(This is a bit of an edge-case as it's unlikely someone will add an alias (and then someone else will join through it) during a faster join)

**Comment by DMRobertson** [comment]
> Presumably once we have completed the resync we need to update the alias tables to reflect the full list of servers we now know about?

On reflection, I don't think this is correct. Quoting MSC3706:

```
servers_in_room: A new field of type [string], listing the servers active in the room (ie, those with joined members) before the join.
```

We are trusting the resident server to accurately provide that list of servers in the roomand the state at our join event. The resync gives us the state at that join event, so there shouldn't suddenly be a different set of servers in the room to deal with... if the resident server is well-behaved. (Do we want to check that?)

What I think this means is: we have to react to new servers joining the room after a partial join in exactly the same way as after a full join?
