### ISSUE TITLE
Memory leak in `/sync` when creating `RoomStreamToken`s with no `instance_map`

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13286]
Constructing an empty `frozendict` leaks memory: https://github.com/Marco-Sulla/python-frozendict/issues/60

We do a lot of that during `/sync`, when we create `RoomStreamToken`s with no `instance_map`.

Possibly the cause of #12160?

**Comment by squahtx** [comment]
Also affects `StateFilter`s, since we make use of `frozendict`s there:
https://github.com/matrix-org/synapse/blob/7c6b2204d143550d81e5bf9612c4e69fe0866b4c/synapse/storage/state.py#L47

**Comment by clokep** [comment]
Looks like frozendict v2.3.3 contains the fix. 🎉
