### ISSUE TITLE
Close `ijson` coroutines ourselves instead of letting the GC close them

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13293]
https://github.com/matrix-org/synapse/blob/d9f092285b28f0cdac0d985813a1cabd8ea990b6/synapse/federation/transport/client.py#L928-L930
https://github.com/matrix-org/synapse/blob/d9f092285b28f0cdac0d985813a1cabd8ea990b6/synapse/federation/transport/client.py#L972-L974

These `close()` calls were added in #12875, but I overlooked that we'd only close the first coroutine if it raised an `IncompleteJSONError`.
We need to close _all_ coroutines, even when any of them raise an error.

Until we fix this properly, we'll get unhelpful `Exception ignored in: <generator object utf8_encoder at 0x7f87c9b1ccf0>` errors in sentry without a stack trace or logging context.

**Comment by DMRobertson** [comment]
What's the fix here? Wrap each `close` call in a `try: ... except Exception: pass`?

**Comment by squahtx** [comment]
> What's the fix here? Wrap each `close` call in a `try: ... except Exception: pass`?

I think we'd want to let the exception bubble up still. Maybe something like
```py
exc = None
for c in self._coros:
    try:
        c.close()
    except Exception as e:
        exc = e
if exc is not None:
    raise exc
```
if that doesn't mess up the exception stack traces.

**Comment by DMRobertson** [comment]
(Would https://peps.python.org/pep-0654/'s ExceptionGroups be helpful? Not that this is available to us any time soon.)
