### ISSUE TITLE
Documentation: Clarify contradictory docs about authentication of replication traffic

### ISSUE THREAD

**Issue by haslersn** [matrix-org/synapse#13302]
The [workers documentation](https://github.com/matrix-org/synapse/blob/7bc08f320147a1d80371eb13258328c88073fad0/docs/workers.md) has seemingly contradictory statements about whether replication traffic is authenticated:

> Optionally, a shared secret can be used to authenticate HTTP traffic between workers.

> Under no circumstances should the replication listener be exposed to the public internet; it has no authentication

**Comment by richvdh** [comment]
yeah, the "no authentication" text predates https://github.com/matrix-org/synapse/pull/8853. Mind you, I'm not sure I'd really recommend exposing the HTTP port even if there is a shared secret.

Still, it's definitely incorrect as it stands.

**Comment by haslersn** [comment]
> I'm not sure I'd really recommend exposing the HTTP port

Still, the authentication might influence a decision about whether it's acceptable to have unrelated hosts in the same VLAN or Kubernetes cluster.

**Comment by clokep** [comment]
#13656 is a simple clarification of this, not sure there is more to say?
