### ISSUE TITLE
Ubuntu 21.10 (Impish Indri) has reached end of life as of July 14, 2022

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#13322]
See https://lists.ubuntu.com/archives/ubuntu-announce/2022-July/000281.html

I don't think we have good docs for removing a distribution, but should be the opposite of [gitlab.matrix.org/new-vector/internal/-/wikis/Synapse-Debian-Packages#adding-a-new-distribution](https://gitlab.matrix.org/new-vector/internal/-/wikis/Synapse-Debian-Packages#adding-a-new-distribution).

**Comment by clokep** [comment]
(And for cross-linking, this was added in #10904.)

**Comment by richvdh** [comment]
> I don't think we have good docs for removing a distribution, 

you just need to remove it from the build list: https://github.com/matrix-org/synapse/pull/11961/files.

> but should be the opposite of [gitlab.matrix.org/new-vector/internal/-/wikis/Synapse-Debian-Packages#adding-a-new-distribution](https://gitlab.matrix.org/new-vector/internal/-/wikis/Synapse-Debian-Packages#adding-a-new-distribution).

No, we keep the repository around for old distributions - we just stop publishing to it.
