### ISSUE TITLE
updating to 1.63.1 somehow broke the synapse. 

### ISSUE THREAD

**Issue by mr-blackmore** [matrix-org/synapse#13339]
I was attempting to update my Matrix homeserver like usual.  Then I get asked about replacing my modified homeserver.yaml with the default one. I press no and then the matrix-synapse stopped working.

> Configuration file '/etc/matrix-synapse/homeserver.yaml'
>  ==> Modified (by you or by a script) since installation.
>  ==> Package distributor has shipped an updated version.
>    What would you like to do about it ?  Your options are:
>     Y or I  : install the package maintainer's version
>     N or O  : keep your currently-installed version
>       D     : show the differences between the versions
>       Z     : start a shell to examine the situation
> The default action is to keep your current version.
> *** homeserver.yaml (Y/I/N/O/D/Z) [default=N] ? n
> Installing new version of config file /etc/matrix-synapse/log.yaml ...
> Job for matrix-synapse.service failed because the control process exited with error code.
> See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.
> Processing triggers for man-db (2.8.5-2) ...
> Processing triggers for ntp (1:4.2.8p12+dfsg-4) ...
> Processing triggers for libc-bin (2.28-10+deb10u1) ...
> 

I tried systemctl restart matrix-synapse.service several time with no luck. 

> ● matrix-synapse.service - Synapse Matrix homeserver
>    Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Tue 2022-07-19 14:36:31 UTC; 599ms ago
>   Process: 31963 ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --co
>   Process: 31970 ExecStart=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --confi
>  Main PID: 31970 (code=exited, status=1/FAILURE)
> 
> Jul 19 14:36:31  systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
> Jul 19 14:36:31  systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
> Jul 19 14:36:31  systemd[1]: Failed to start Synapse Matrix homeserver.
> 

Steps to reproduce
Upgrade synapse to v1.63.0 and all of the system packages
Try to start synapse
Version information
Homeserver: cryptofblackmore.xyz
If not matrix.org:

Version: v1.63.0

Install method: package manager (matrix-synapse-py3)

Platform: Debian 10 x64 (buster)

**Comment by DMRobertson** [comment]
Can you show us the logs from synapse please? I think `journalctl -u matrix-synapse` is what you want.

**Comment by mr-blackmore** [comment]
Sure:

> -- Logs begin at Wed 2022-07-20 13:43:39 UTC, end at Wed 2022-07-20 14:33:13 UTC. --
> Jul 20 13:43:39 systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 13.
> Jul 20 13:43:39 systemd[1]: Stopped Synapse Matrix homeserver.
> Jul 20 13:43:39 systemd[1]: Starting Synapse Matrix homeserver...
> Jul 20 13:43:43 matrix-synapse[15624]: This server is configured to use 'matrix.org' as its trusted key server via the
> Jul 20 13:43:43 matrix-synapse[15624]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
> Jul 20 13:43:43 matrix-synapse[15624]: server since it is long-lived, stable and trusted. However, some admins may
> Jul 20 13:43:43 matrix-synapse[15624]: wish to use another server for this purpose.
> Jul 20 13:43:43 matrix-synapse[15624]: To suppress this warning and continue using 'matrix.org', admins should set
> Jul 20 13:43:43 matrix-synapse[15624]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
> Jul 20 13:43:43 matrix-synapse[15624]: --------------------------------------------------------------------------------
> Jul 20 13:43:43 matrix-synapse[15624]: Traceback (most recent call last):
> Jul 20 13:43:43 matrix-synapse[15624]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> Jul 20 13:43:43 matrix-synapse[15624]:     "__main__", mod_spec)
> Jul 20 13:43:43 matrix-synapse[15624]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
> Jul 20 13:43:43 matrix-synapse[15624]:     exec(code, run_globals)
> Jul 20 13:43:43 matrix-synapse[15624]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", li
> Jul 20 13:43:43 matrix-synapse[15624]:     main()
> Jul 20 13:43:43 matrix-synapse[15624]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", li
> Jul 20 13:43:43 matrix-synapse[15624]:     hs = setup(sys.argv[1:])
> Jul 20 13:43:43 matrix-synapse[15624]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", li
> Jul 20 13:43:43 matrix-synapse[15624]:     "You have enabled open registration without any verification. This is a known vector for
> Jul 20 13:43:43 matrix-synapse[15624]: synapse.config._base.ConfigError: You have enabled open registration without any verificatio
> Jul 20 13:43:43 systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
> Jul 20 13:43:43 systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
> Jul 20 13:43:43 systemd[1]: Failed to start Synapse Matrix homeserver.
> Jul 20 13:43:46 systemd[1]: matrix-synapse.service: Service RestartSec=3s expired, scheduling restart.
> Jul 20 13:43:46 systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 14.
> Jul 20 13:43:46 systemd[1]: Stopped Synapse Matrix homeserver.
>

**Comment by DMRobertson** [comment]
> You have enabled open registration without any verification. This is a known vector for

This is the problem. See my comment here: https://github.com/matrix-org/synapse/issues/12702#issuecomment-1123499014

This change was introduced in Synapse 1.56.0, so I'm slightly surprised you're seeing it now. What version did you upgrade _from_?

**Comment by mr-blackmore** [comment]
Hmm... Can't remember what version that I used to have, but I haven't upgraded in a while, so that may explain things.

**Comment by DMRobertson** [comment]
Thanks for confirming! I'm going to close since I expect the linked comment is enough to get things working again. If not, please re-open and we can take another look.
