### ISSUE TITLE
Performance Regression in 1.63

### ISSUE THREAD

**Issue by davidmehren** [matrix-org/synapse#13331]
### Description

After updating to Synapse 1.63.0 today, one of my Synapse instances experiences a noticeable performance regression:
![image](https://user-images.githubusercontent.com/5023650/179831822-1b36d5a3-902d-43b9-bf28-b038eb3ddc62.png)

According to the metrics (snapshot at https://fsr-ops.cs.tu-dortmund.de/dashboard/snapshot/PyUD0nsC3zYGM3AyCOrwWOOWTbdRsXZo?orgId=0) `handle_new_client_event` and `action_for_event_by_user` now consume significantly more CPU and database resources.

https://github.com/matrix-org/synapse/pull/13100 and https://github.com/matrix-org/synapse/pull/13078 seem to have touched these functions for 1.63, so maybe they are the culprit?

### Steps to reproduce

- Update to Synapse 1.63.0
- Observe worse performance in Grafana

### Homeserver

fachschaften.org

### Synapse Version

1.63.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Docker on Ubuntu 20.04 in LXC

### Relevant log output

```shell
I didn't see something relevant in the log output (and there is just too much to paste everything) and the Grafana snapshot is hopefully more helpful than a huge amount of logs.
```

**Comment by squahtx** [comment]
I wonder if it's the default size of the `get_user_in_room_with_profile` cache being too small. Does the "Top 10 cache misses" chart look any different before and after the upgrade?

**Comment by davidmehren** [comment]
@squahtx  that looks like a good guess!
![image](https://user-images.githubusercontent.com/5023650/179834934-af56cbc7-291d-4b37-827b-35905a65bd5a.png)

**Comment by squahtx** [comment]
The size of that cache can be controlled by adding an entry to `per_cache_factors` in the config. The config can then be reloaded by sending SIGHUP to Synapse.

It sounds like the default size for that cache is too small and we should ship with a larger default. I'd be interested in seeing what a good cache factor for your deployment turns out to be.

**Comment by davidmehren** [comment]
I doubled the cache factor from our global default of 1 to 2 and will observe the metrics for a bit. Thanks for the prompt help!

**Comment by davidmehren** [comment]
1.63.1 seems to have fixed the problem, load and event send time is back to normal immediately after upgrading.
