### ISSUE TITLE
"Push key getting rejected" error when synapse is calling sygnal 

### ISSUE THREAD

**Issue by arindampaul1993** [matrix-org/synapse#13340]
### Description

There is an issue when we try to enable push notifications for  element iOS , by setting up our custom matrix/synapse homeserver and sygnal push gateway as a separate component. The sygnal API for push notifications (_matrix/push/v1/notify) works fine when triggered manually through a REST client , but synapse fails to send the same request with the same push key to sygnal's API.

It was working in 1.40.0(synapse) and 0.10.1(sygnal), and occurred when we migrated to 1.49.0(synapse).

### Steps to reproduce

- setup synapse and sygnal
- connect to that as a custom home server from element iOS
- log in as a user
- generate a push notification event for the same user by room mentions/messages or direct messages

### Homeserver

custom synapse home server 

### Synapse Version

1.49.0

### Installation Method

Other (please mention below)

### Platform

Synapse and sygnal are setup from source and are running as docker containers on instances managed in a private cloud platform.

### Relevant log output

```shell
2022-07-13 08:12:00,884 [1] INFO  sygnal.access Handled request: "10.1.200.3" - - [13/Jul/2022:08:12:00 +0000] "POST /_matrix/push/v1/notify HTTP/1.1" 200 62 "-" "PostmanRuntime/7.28.4"
2022-07-13 08:12:00,883 [1] INFO  sygnal.http [d1957f82-d7b5-4e65-a4d7-45de3bf70348] Successfully delivered notifications with 1 rejected pushkeys

2022-07-13 03:17:19,739 - synapse.push.httppusher - 308 - INFO - httppush.process-0 - Pushkey SpPpAaLnegIAERhulTCvIa4kSrvue0VIETNzKm7qoPg= was rejected: removing
2022-07-13 03:17:19,739 - synapse.push.pusherpool - 385 - INFO - httppush.process-0 - Stopping pusher *** / ****:SpPpAaLnegIAERhulTCvIa4kSrvue0VIETNzKm7qoPg=
```

### Anything else that would be useful to know?

Pusher table entry in synapse:

```id |                       user\_name
| access\_token |   profile\_tag    | kind |
app\_id               | app\_display\_name |        device\_
display\_name        |                   pushkey
|      ts       | lang  | data | last\_stream\_ordering | last\_success | failing\_since

## -------------+----------------------+--------------+------

22 | @_**:**_|         1301 | \*\*\*\*\*\* | http | \*\*\*\*\* | \*\*\*\* | \*\*\*\*\*\* | \*\*\*\*\* | 1657699773999 | en-IN | {"url":"\*/\_matrix/push/v1/no
tify","format":"event\_id\_only","default\_payload":{"aps":{"
mutable-content":1,"alert":{"loc-key":"Notification","loc-
args":\[\]}}}} |                 2439 |              |```
```

**Comment by babolivier** [comment]
Heya, I notice you're running Synapse 1.49.0, which is quite an old version of Synapse. Could you check with a more recent version if the issue still happens please?

Also, for some reason it looks like the database output got quite mangled for some reason (quite a few `\`s and line breaks making it difficult to read).

**Comment by richvdh** [comment]
It's odd that sygnal is recording rejected pushkeys without logging *why* they are rejected. I'd also suggest upgrading sygnal to the current version (0.12.0).

**Comment by arindampaul1993** [comment]
We are already using sygnal 0.12.0.
