### ISSUE TITLE
Account validity configuration not documented(?)

### ISSUE THREAD

**Issue by JacksonChen666** [matrix-org/synapse#13369]
There are [multiple](https://matrix-org.github.io/synapse/v1.63/admin_api/account_validity.html) [pages](https://matrix-org.github.io/synapse/v1.63/modules/account_validity_callbacks.html) that talks about account validity, but [nothing in the configuration manual](https://matrix-org.github.io/synapse/v1.63/usage/configuration/config_documentation.html) hints anything related to [`account_validity`](https://github.com/matrix-org/synapse/issues/7292). Perhaps the documentation for such option is missing?

**Comment by dklimpel** [comment]
You can find some information here: https://github.com/matrix-org/synapse/blob/develop/synapse/config/account_validity.py

**Comment by JacksonChen666** [comment]
> You can find some information here: https://github.com/matrix-org/synapse/blob/develop/synapse/config/account_validity.py

I'm seeing [this](https://github.com/matrix-org/synapse/blob/357561c1a2b2da6d1a7ad1e2340217fee18cc2b1/synapse/config/account_validity.py#L46-L48). I guess that pretty much means it's not really intended as a configuration option, but as a module which is documented.

**Comment by babolivier** [comment]
The goal is pretty much to deprecate and remove the build-in account validity implementation (as opposed to supporting account validity modules), but this is currently blocked behind https://github.com/matrix-org/synapse/issues/9944
