### ISSUE TITLE
Docker image build fails on 32 bit Raspberry Pi

### ISSUE THREAD

**Issue by jap** [matrix-org/synapse#13371]
### Description

When trying to build a docker image on a 32 bit raspbian environment, the build fails because it cannot find a proper rust compiler for building the cryptography package. Note that this happens in the initial "poetry" stage, not the second one where the relevent dependencies are in fact installed using `apt`.

The command used was 
```
DOCKER_BUILDKIT=1 docker build --pull --build-arg PYTHON_VERSION=3.9 -f docker/Dockerfile -t synapse:v1.63.1 -t synapse:latest .
```
and the output scrolled of of my screen unfortunately.

### Steps to reproduce

- checkout git
- try to run a build: `DOCKER_BUILDKIT=1 docker build --pull --build-arg PYTHON_VERSION=3.9 -f docker/Dockerfile -t synapse:v1.63.1 -t synapse:latest .`

### Homeserver

n/a

### Synapse Version

1.63.1

### Installation Method

Other (please mention below)

### Platform

Raspi 4, raspbian 32 bits, has recent docker versions

### Relevant log output

```shell
scrolled of the screen unfortunately
```

### Anything else that would be useful to know?

PR incoming

**Comment by anoadragon453** [comment]
The same issue appeared when trying to build [Pyston](https://github.com/pyston/pyston) images for x86/arm: https://github.com/matrix-org/synapse/pull/12850/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR45.

Thanks for working on this!
