### ISSUE TITLE
Making many outbound federation requests takes a lot of CPU and memory

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#13381]
This is *especially* a problem for presence, which talks to lots of servers when there are presence changes to be distributed.

One potential way of tackling this is to have a way of running outbound federation traffic through a proxy (which would need to understand how to resolve matrix server names). This would could also help lots in scenarios where people are running many Synapse's, and having a single process keeping out bound connections could reduce resource usage.

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/synapse/issues/5373 I think?
