### ISSUE TITLE
Only small yaml file

### ISSUE THREAD

**Issue by STR3IKERKRYPTON** [matrix-org/synapse#13389]
|`docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=my.matrix.host \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate`

I use this command from the docker hub page. But I only get this homeserver.yaml file:

![image](https://user-images.githubusercontent.com/87895556/180995806-14b4331f-12eb-4ce5-bfbf-4c1478c8ff52.png)

I wanna use postgres as database and I know that some people get bigger config files with much more default settings like this:
[https://comatrix.eu/setup/matrix_synapse_homeserver/](url)

Does someone know why some people get different yaml files or are these big yaml files just old versions?

**Comment by DMRobertson** [comment]
> are these big yaml files just old versions?

Pretty much. See #13306 and #8159 for context.

For the full reference, see the config manual: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html

I'm going to close this so we can keep discussions of the config file in #13306.
