### ISSUE TITLE
During a new user creation process, by confirming with a wrong password, database locked, server is down.

### ISSUE THREAD

**Issue by Manifoldme** [matrix-org/synapse#13390]
### Description

By only mistyping “confirm password” once, a user ID is taken despite an error return “Password do not match”.

After restarting a server it returned an error “Error during initialisation: database is locked”
Second start, “started synapse.app.homeserver”
The user ID with the mismatched password returns,
“Sending registration request...
ERROR! Received 400 Bad Request
User ID already taken.”

Is there a way to delete such a user-ID to reuse it again?

### Steps to reproduce

register_new_matrix_user -c homeserver.yaml
Enter  a user Name/ID
Password "Right"
Confirm Password "Wrong"

synctl restart

Error during initialisation:
database is locked

### Homeserver

my own homeserver

### Synapse Version

1.63.1

### Installation Method

Debian packages from packages.matrix.org

### Platform

Proxmox - Container - Ubuntu 22.04 - python_version:"3.10.4"

### Relevant log output

```shell
New user localpart [root]: joe
Password: 
Confirm password: 
Make admin [no]: yes
Sending registration request...
ERROR! Received 400 Bad Request
User ID already taken.
```

**Comment by erikjohnston** [comment]
I tried to reproduce and failed, and the code looks like it should bail long before it registers the user if the password is incorrect:

https://github.com/matrix-org/synapse/blob/4f3082d6bf85335d10775a2e869420592189c6b2/synapse/_scripts/register_new_matrix_user.py#L129-L131

Are you sure that the user wasn't added via some other method?

You can't easily delete a user, but you can use the admin API to reset the password: https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#reset-password

**Comment by erikjohnston** [comment]
Didn't actually mean to hit the close button, but if the above doesn't work for you then let us know and we can reopen

**Comment by Manifoldme** [comment]
It was a clean installation first an Ubuntu LXC and then Synapse. (I also made a screenshot in case...)
If it is not reproducible then maybe something went wrong with my installation, and we’re good.
I immediately reinstalled LXC and Synapse from scratch, hence I don’t really need an assistance just wanted to share that issue with developers. 
Thanks for your prompt response and for the usefull admin API to reset the password.
