### ISSUE TITLE
GIL-less Python support

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/synapse#13398]
**Description:**

Synapse currently only correctly works with CPython, which has a GIL. GIL-less Python support needs to be improved, to improve multi-threaded performance further.

Related: #11777

**Comment by erikjohnston** [comment]
This isn't really actionable on our part. If there are particular python interpreters that you think we should support beyond cpython then that is a discussion that can be had, though realistically cpython is going to be what the vast majority of users use so there would have to be a compelling reason for us to put much resource behind such an initiative.
