### ISSUE TITLE
Self-botting facility (self commands)

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/synapse#13396]
**Description:**

Users should be able to define macros/scripts that would output events that would appear as if authored by themselves, with using as input the state of rooms that they are a member. Those self-bots otherwise may be left indistinguishable from normal user action.

Alternatives: Using a maubot/maubot session only replying to self.

**Comment by turt2live** [comment]
This feels like it'd be solved by a bash script or similar. The client-server API already supports passing an access token to a script and letting it create events: a suitable script could do the same with the information provided (or rather, it could get the information it needs).

**Comment by erkinalp** [comment]
The standard API does not support it doing in a manner that the command invocation would not appear to anyone once completed, yet still be uniformly invocable across all the clients of said user.

Expected use cases are similar to that of vector-im/element-web#9145, but executed in the server side.

**Comment by erikjohnston** [comment]
I think this would require spec support, at the very least clients would need to be able to query whether the server supports it etc. As such I think this is more a spec proposal than a Synapse issue/feature.
