### ISSUE TITLE
Disabling historical rooms

### ISSUE THREAD

**Issue by iambeingtracked** [matrix-org/synapse#13401]
**Description:**
I would like it to be possible to disable historical rooms in synapse. I just want to leave a room and forget about it, not leaving a trail of it in historical rooms.

**Comment by erikjohnston** [comment]
Doesn't seem unreasonable as a config option, but I don't think we'd implement it ourselves.

**Comment by richvdh** [comment]
I think this is a client-side feature, isn't it? It's the client choosing to present the list of historical rooms, not the server.

(Though https://github.com/matrix-org/synapse/issues/4720 is related)

**Comment by iambeingtracked** [comment]
Well, this can be removed on the client side, but I'm not entirely sure whether historical rooms are provided by the client or by the server

**Comment by richvdh** [comment]
I don't think Synapse provides a list of historical rooms. (It used to, but has not done so for a long time.)

**Comment by iambeingtracked** [comment]
So in which version was that removed from synapse?

**Comment by richvdh** [comment]
I couldn't say for certain, I'm afraid.

**Comment by iambeingtracked** [comment]
Hmm, can't find it https://github.com/matrix-org/synapse/releases?q=historical&expanded=true

**Comment by anoadragon453** [comment]
Synapse does not notify the client that a room has been forgotten, no. It's up to the client to remove it from the room list. See Element Web's code here:

https://github.com/matrix-org/matrix-react-sdk/blob/5fbeb20df864721e2acbb7bff56ff234abf9e3fb/src/components/structures/MatrixChat.tsx#L1178

Additionally, it appears that historical rooms do not come down in an initial sync, so if you log out and log in again all historical rooms will be lost. This makes it difficult to forget them afterwards!

**Comment by iambeingtracked** [comment]
Okay, I think I should make an issue in https://github.com/vector-im/element-web. Closing the issue.
