### ISSUE TITLE
Support compression in federation responses

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#13415]
Surprisingly we don't support compression on federation traffic (we just ignore `compress: true` on federation resources).

Should be as simple as:

```python
            federation_resource: Resource = TransportLayerServer(self)
            if compress:
                federation_resource = gz_wrap(federation_resource)
            resources.update({FEDERATION_PREFIX: federation_resource})
```

here:

https://github.com/matrix-org/synapse/blob/f30bcbd84a651de59777b2a749850f6ca56ce3f0/synapse/app/homeserver.py#L222-L223

**Comment by BigBlueHundids** [comment]
>.
