### ISSUE TITLE
Announce deprecation of `account_threepid_delegates.email`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13421]
`account_threepid_delegates.email` was removed in #13192 (v1.64.0rc1) but that was reverted in #13406 (v1.64.0rc2).

As part of the release announcement for 1.64.0 final, I would like us to give an unambiguous indication of when it will be removed.

Initially we had hoped to do this in 1.65, but [feedback](https://github.com/matrix-org/synapse/pull/13406#issuecomment-1199115558) is that that is too soon.

**Comment by richvdh** [comment]
I am inclined to compromise on 1.66.

**Comment by richvdh** [comment]
We've agreed as a team to target 1.66.0. We should ensure that this is clearly announced in the release announcement.

**Comment by DMRobertson** [comment]
> We should ensure that this is clearly announced in the release announcement.

See https://matrix.org/blog/2022/08/03/synapse-1-64-released#delegating-email-verification-is-now-deprecated .
