### ISSUE TITLE
Question (Can't join Synapse Admins group)

### ISSUE THREAD

**Issue by DillFrescott** [matrix-org/synapse#13425]
I tried joining the `Synapse Admins` group on matrix. But it wouldn't let me join. It just says `joining...` forever.

So I'm just gonna go ahead and ask the question here.

If I store my matrix homeserver backup using git, will git getting rid of empty directories do any harm with my synapse server if I decide to restore the server from git?

**Comment by DillFrescott** [comment]
Edit: The room joining errored out for some reason.

**Comment by DillFrescott** [comment]
Nevermind apparently its letting me join now...

**Comment by babolivier** [comment]
For future issues, please use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) for support requests.
