### ISSUE TITLE
Saving custom themes

### ISSUE THREAD

**Issue by iambeingtracked** [matrix-org/synapse#13434]
### Description

So, in Element it is possible to enable custom themes, after importing some ones into the client it still has them when using an entirely different client. That makes me think that those themes are saved server side on the account you saved them in. For example, I have an account user0@example.org, I log into element.example.org, enable custom themes in Labs, import some ones into it. Then log off and log in as user1@example.org, those themes aren't there. Then I log in to Element desktop as user0@example.org and those themes are there. The problem is that I can't remove them, so if I import something bad, I can't get rid of it. I'm not sure whether that's intended or no, but I'll consider that as a bug.

### Steps to reproduce

Log into your account with Element and enable "Support adding custom themes" in Labs. Then import some themes and try logging into an another Element instance, you'll see those themes there.

### Homeserver

another homeserver

### Synapse Version

1.61.1 (i need to update)

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Synapse is running in a VM.

### Relevant log output

```shell
not applicable there
```

**Comment by DMRobertson** [comment]
I am guessing that Element is using global [account data](https://spec.matrix.org/v1.3/client-server-api/#client-config) to store the custom theme information. Surprisingly there doesn't seem to be a DELETE endpoint for account data, but I imagine that Element could PUT a value of`null` under the right key to signal "there is no custom theme".

**Comment by DMRobertson** [comment]
It sounds like https://github.com/vector-im/element-web/issues/13221 tracks this.
