### ISSUE TITLE
config documentation mentions non-existent setting `url_preview_language`

### ISSUE THREAD

**Issue by raldone01** [matrix-org/synapse#13433]
### Description

[url_preview_language](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#url_preview_language)
![image](https://user-images.githubusercontent.com/27293675/182246882-3ff1e597-f46e-455c-8028-cf5712b9181b.png)

Is it `url_preview_accept_language` or `url_preview_language`?

### Steps to reproduce

Visit the website and read the documentation under the heading.

### Homeserver

https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#url_preview_language

### Synapse Version

Not applicable

### Platform

Not applicable

### Relevant log output

```shell
Not applicable
```

**Comment by richvdh** [comment]
`url_preview_accept_language`. Would you mind opening a PR to fix this?
