### ISSUE TITLE
retention comes with insufficient warnings

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13475]
it is well-known to corrupt the database via insufficient cache invalidation, yet the config documentation almost recommends it. It needs a big health warning

**Comment by richvdh** [comment]
cf https://github.com/matrix-org/synapse/issues/13476

**Comment by 4nd3r** [comment]
What happens if I decide (because of mentioned risk) to remove `retention: enabled: true` from configuration and many rooms in my HS have retention configured? Is it safe? Please add that to docs also.

**Comment by dklimpel** [comment]
And are there different risks if I delete history e.g. from yesterday or 3 years ago?

**Comment by richvdh** [comment]
> What happens if I decide (because of mentioned risk) to remove retention: enabled: true from configuration and many rooms in my HS have retention configured? Is it safe?

I believe that's fine, yes.

> Please add that to docs also.

Pull requests to improve the documentation are always welcome :innocent:

**Comment by richvdh** [comment]
> And are there different risks if I delete history e.g. from yesterday or 3 years ago?

Yes, there are different risks in the sense that you're less likely to hit one of the problematic races by deleting history from 3 years ago than by deleting history from yesterday.
