### ISSUE TITLE
Docs and warnings refer to nonexistent `custom_templates_directory` setting

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13498]
The [templates](https://matrix-org.github.io/synapse/v1.64/templates.html#templates) documentation, and various warnings emitted by synapse ([example](https://github.com/matrix-org/synapse/blob/v1.64.0/synapse/config/emailconfig.py#L56)) refer to a config setting called `custom_templates_directory`. The correct name is [`custom_template_directory`](https://matrix-org.github.io/synapse/v1.64/usage/configuration/config_documentation.html#templates-and-custom_template_directory).

**Comment by DMRobertson** [comment]
Unfortunate. A warning on startup that the `custom_templates_directory` plural is an unknown key might have helped.
