### ISSUE TITLE
Admin `list-room` API returns integers instead of booleans on SQLite

### ISSUE THREAD

**Issue by jplatte** [matrix-org/synapse#13505]
### Description

According to https://github.com/ruma/synapse-admin-api/issues/14, the `federatable` and `public` fields in the response of the [List room API](https://matrix-org.github.io/synapse/develop/admin_api/rooms.html#list-room-api) return `0` / `1` instead of `true` / `false`, while the example in the linked documentation shows boolean values.

### Steps to reproduce

Use the list room API? 🤷🏼 

### Homeserver

any

### Synapse Version

unknown

### Platform

unknown

### Relevant log output

```shell
-
```

**Comment by jplatte** [comment]
I haven't reproduced this myself, just carried over the bug report in https://github.com/ruma/synapse-admin-api/issues/14. @avp90 can you answer?

**Comment by avp90** [comment]
Yes in my test case it's a SQLite database.
