### ISSUE TITLE
Module API: does not provide a way to invalidate caches in other workers

### ISSUE THREAD

**Issue by MatMaul** [matrix-org/synapse#13513]
Currently if we use `@cached()` on a function on a module there is no cache invalidation happening between workers.

**Comment by MatMaul** [comment]
Currently modules that want to use `@cached()` already can and have to invalidate manually through `cached_function.invalidate()`. This however only invalidates locally, and the invalidation is not replicated through workers. The planned fix involves a new module API that allows to invalidate locally and replicate the invalidation to other workers.

Current WIP can be found here:
https://github.com/matrix-org/synapse/tree/mv/module-cache-invalidation

**Comment by reivilibre** [comment]
+1 to noting that this is intended for modules to invalidate *their own* caches. I was quite scared from the title but the justification makes sense :)
