### ISSUE TITLE
Sudden non-recovering spikes in memory usage

### ISSUE THREAD

**Issue by Fizzadar** [matrix-org/synapse#13550]
I've been trying to debug memory across workers on our synapse install and we've been running with the general assumption the majority of memory usage comes from various caches. I setup a single instance in production with cache memory tracking enabled and as it turns out the jumps we see in memory are not cache:

<img width="974" alt="Screenshot 2022-08-17 at 20 52 51" src="https://user-images.githubusercontent.com/1026154/185232362-ecc3d344-7b8f-4726-a957-ae098f61cf93.png">

Note this instance is a room worker which only serves `/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*` endpoints. I'd like to understand the jump on the left, ~500mb increase in a few second window that doesn't align with any cache increase. This memory never seems to be recovered either.

We see this same pattern on other room workers (without cache memory tracking), sometimes after days of running. Once such a spike occurs GCs often jump from ~1% to 5% CPU time and the only current fix is just to shoot the worker. One example from today:

<img width="990" alt="Screenshot 2022-08-17 at 21 13 08" src="https://user-images.githubusercontent.com/1026154/185233982-5d74337f-c4a7-4444-b6fa-f317a72628d1.png">

**Comment by Fizzadar** [comment]
Major 🤦  - the memory is dropping, but isn't released back to the OS. Somehow I seem to have forgotten that (https://stackoverflow.com/questions/15455048/releasing-memory-in-python).

This does bring up an interesting problem though - caches can't "burst" because the top amount of usage memory will be held until the process dies.

**Comment by anoadragon453** [comment]
@Fizzadar Have you considering using [jemalloc](https://github.com/jemalloc/jemalloc/wiki/Getting-Started) as an alternative malloc implementation for Python? We use it extensively on matrix.org and find that it's much better at releasing memory to the OS.

This used to be [documented here](https://github.com/matrix-org/synapse/tree/release-v1.64#help-synapse-is-slow-and-eats-all-my-ramcpu) in Synapse's README until very recently. Regardless of what that says, it does make a noticeable difference on Python 3. We should probably add a proper page to the documentation.

**Comment by clokep** [comment]
> Edit: Aaaand I've just seen your other issue about using jemalloc 😋

To cross-reference, this seems to be #13571.
