### ISSUE TITLE
Complement test `TestPartialStateJoin/State_rejected_incorrectly` is flaky

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13565]
https://github.com/matrix-org/synapse/runs/7914130880?check_suite_focus=true

**Comment by richvdh** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/13564

**Comment by DMRobertson** [comment]
Has this resurfaced? https://github.com/matrix-org/synapse/actions/runs/3439617166/jobs/5737176807

(may well be the same failure mode that #13564 describes, I've not dug)
