### ISSUE TITLE
Complement test `TestPartialStateJoin/CanReceiveEventsWithMissingParentsDuringPartialStateJoin` is flaky

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13564]
https://github.com/matrix-org/synapse/runs/7915629022?check_suite_focus=true#step:5:6663

**Comment by richvdh** [comment]
sticking this on the faster-joins backlog, since it's a faster-joins test

**Comment by squahtx** [comment]
`CanReceiveEventsDuringPartialStateJoin` and `CanReceiveEventsWithHalfMissingParentsDuringPartialStateJoin` are also flaky, presumably for the same reason.
https://github.com/matrix-org/synapse/runs/7978919099?check_suite_focus=true
https://github.com/matrix-org/synapse/runs/7978705963?check_suite_focus=true

**Comment by richvdh** [comment]
The problem here appears to be that the `/state_ids` request is racing against the current-state calculation:

```
  synapse_main | 2022-08-25 16:45:29,290 - synapse.handlers.federation - 1653 - INFO - sync_partial_state_room-0 - Updating current state for !0:host.docker.internal:46871
  synapse_main | 2022-08-25 16:45:29,312 - synapse.http.server - 169 - INFO - GET-13 - <SynapseRequest at 0x7f994cefe370 method='GET' uri='/_matrix/federation/v1/state_ids/%210:host.docker.internal:46871?event_id=%24bO0OjeuzEcRmdWzNWTJLIKtM2MQy_VET2J1-4bayLBg' clientproto='HTTP/1.0' site='8080'> SynapseError: 403 - Host not in room.
  synapse_main | 2022-08-25 16:45:29,314 - synapse.access.http.8080 - 450 - INFO - GET-13 - ::ffff:127.0.0.1 - 8080 - {host.docker.internal:46871} Processed request: 0.003sec/0.001sec (0.002sec, 0.000sec) (0.000sec/0.000sec/1) 53B 403 "GET /_matrix/federation/v1/state_ids/%210:host.docker.internal:46871?event_id=%24bO0OjeuzEcRmdWzNWTJLIKtM2MQy_VET2J1-4bayLBg HTTP/1.0" "Go-http-client/1.1" [0 dbevts]
  synapse_main | 2022-08-25 16:45:29,324 - synapse.handlers.federation - 1658 - INFO - sync_partial_state_room-0 - Clearing partial-state flag for !0:host.docker.internal:46871
```

We can see that the "updating current state" operation is ongoing as the `state_ids` request arrives. The same is true for the other failures linked above.

So really this is an artifact of https://github.com/matrix-org/synapse/issues/13288, though I might see if we can hack around it for now.

**Comment by DMRobertson** [comment]
Failure on develop: https://github.com/matrix-org/synapse/actions/runs/3272273117/jobs/5383194205

**Comment by babolivier** [comment]
https://github.com/matrix-org/synapse/actions/runs/3659144555/jobs/6214941767 is also a similar failure of this test

**Comment by squahtx** [comment]
> Failure on develop: https://github.com/matrix-org/synapse/actions/runs/3272273117/jobs/5383194205

> https://github.com/matrix-org/synapse/actions/runs/3659144555/jobs/6214941767 is also a similar failure of this test

These last two are 502 Bad Gateway failures, which look like the same class of flake as #14543, where a previous test did not clean up properly.
