### ISSUE TITLE
Count MAU even if limit_usage_by_mau is false

### ISSUE THREAD

**Issue by karlabbott** [matrix-org/synapse#13570]
**Description:**

In EMS, we have found a situation where a customer may want to allow their synapse usage to grow unbounded. In this scenario, they would need to set limit_usage_by_mau to false, but we still would want to collect their MAU, so that we know how many users to bill them for.

As of today, synapse does not count MAU if this is set to false, so this request is to have synapse count MAU even when limit_usage_by_mau is set to false.

**Comment by anoadragon453** [comment]
I think the [mau_stats_only](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#mau_stats_only) config option is what you're looking for?

**Comment by karlabbott** [comment]
That works -- thanks @anoadragon453 !
