### ISSUE TITLE
Service won't started : python3 TypeError

### ISSUE THREAD

**Issue by electro575** [matrix-org/synapse#13572]
Hi all,

I'm on debian bullseye.

I have upgrade matrix-synapse version from "1.61.0 - 1 bpo11 +3" to "1.63.0 - 1 bpo11 +1".

I have check all dependencies of matrix-synapse package.

The problem is the following :

```
python3[2633161]: Traceback (most recent call last):
python3[2633161]: File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
python3[2633161]: mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
python3[2633161]: File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
python3[2633161]: __import__(pkg_name)
python3[2633161]: File "/usr/lib/python3/dist-packages/synapse/__init__.py", line 71, in <module>
python3[2633161]: import synapse.util
python3[2633161]: File "/usr/lib/python3/dist-packages/synapse/util/__init__.py", line 195, in <module>
python3[2633161]: SYNAPSE_VERSION = get_distribution_version_string("matrix-synapse", __file__)
python3[2633161]: TypeError: get_distribution_version_string() takes 1 positional argument but 2 were given
```

All packages come from Debian Bullseye Backports and Main or Security (no Tiers).

Thanks for you're advice.

Have a nice day.

**Comment by dklimpel** [comment]
IMO this looks like an outdated Python package dependency `matrix-common`.

**Comment by electro575** [comment]
I have this version.

python3-matrix-common/bullseye-backports,now 1.2.1-1~bpo11+1

But debian maintainer said to me not reproduced this bug.

**Comment by richvdh** [comment]
please can you report this on the debian bug tracking system; we don't maintain the bullseye-backports packages.
