### ISSUE TITLE
Document how monthly active users is calculated

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#13599]
We document the individual configuration parameters in https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html?highlight=monthly#limit_usage_by_mau, but it would be good to have a separate document stating how the system works at a high level. 

In particular, I'd like to see:

- How activity is calculated.
- How the "trial period" works.
- How users (including deactivated) users may fall out of that activity period.
- When the user limit is reached, what services/endpoints are blocked by the homeserver.

It would be good to have this from the point of view of having something to point at when someone asks how it works.

**Comment by richvdh** [comment]
+1. MAU has always been something of a mystery to me.
