### ISSUE TITLE
Get rid of `worker_main_http_uri`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13642]
`worker_main_http_uri` is used in exactly one place (the handler for `keys/upload/`) to proxy requests through to the main process. Given we already have the "http replication listener", this is needlessly confusing and annoying to configure.

**Comment by realtyem** [comment]
I think I tracked down all the information to give this a shot. 
* Looks like the `worker_main_http_uri` object is populated from the yaml at [workers.py](https://github.com/matrix-org/synapse/blob/develop/synapse/config/workers.py#L158) and added to the `generic_worker` in [`generic_worker.py`](https://github.com/matrix-org/synapse/blob/develop/synapse/app/generic_worker.py#L148) inside a `KeyUploadServlet()`. I think from there it gets processed in the same file(I could find no other references to this variable) as part of [`post_json_get_json()`](https://github.com/matrix-org/synapse/blob/develop/synapse/app/generic_worker.py#L212) where the rest of the (ascii)string for the uri is appended to the request.
* The values needed would be 
  * `scheme` to determine if 'http' or 'https' would be appropriate. I think this can gotten from `config.server.listeners[1].tls`. I think I would have to iterate over all listeners in this section to find the one with a `client` resource. I would need to use this same listener below for `port`.
  * `netloc` to identify if an IP address or hostname is declared. I think I can get this from `config.workers.worker_replication_host` as it should be the same value and be pointing at the homeserver's IP address or hostname(as appropriate).
  * `port` to make sure it's pointed at the actual `client` port and not something else. I think I can get this from the same listener I found for `scheme` and get it from `hs.config.server.listeners[1].port`.

I believe it's a simple string concatenation to put the pieces together and set it either at `worker_main_http_uri` in `workers.py`(referenced above) or factor the config value out altogether and set it in the `KeyUploadServlet()`(again, referenced above) directly. I know which one I would choose.

Does that sound about right? Did I miss anything obvious, easier or a better way?

**Comment by richvdh** [comment]
There are logs of other bits of worker<->worker communication that work via the "http replication API": see the servlets in https://github.com/matrix-org/synapse/blob/15bdb0da522ba902e6a1c55f7f6775faeb47176a/synapse/replication/http. We should use something similar for uploading keys.

**Comment by realtyem** [comment]
I'm sorry, for the moment that kind of thing is beyond me.
