### ISSUE TITLE
/sync with filter as JSON fails

### ISSUE THREAD

**Issue by andreidiaconescu** [matrix-org/synapse#13646]
hello
with the /sync API endpoint 
i try to use the filter not as an id, but as a JSON
"filter": {"room":{"rooms":["!OMulzyGFCfueIWFHSU:[matrix.connectme.anais.tech](http://matrix.connectme.anais.tech/)"]}},
and i get back an error { errcode: 'M_INVALID_PARAM', error: 'Invalid filter ID' }
I have synapse version: {"server_version":"1.61.1","python_version":"3.9.13"}
Is my version too old, does it support using a json instead of a filter id ?

thank you

**Comment by squahtx** [comment]
JSON filters are supposed to work in that Synapse version. Are you able to get logs covering the failing /sync?

**Comment by andreidiaconescu** [comment]
hello,
@clokep 
thank you for the suggestion, it was something like that:
1. first the filter param needs to be a string with json escaped: 
ex: `"filter": "{\"room\":{\"rooms\":[\"!OMulzyGFCfueIWFHSU:matrix.connectme.anais.tech\"]}}"`
2. then the result needs to be url encoded: 
ex: `filter=%7B%22room%22%3A%7B%22rooms%22%3A%5B%22%21OMulzyGFCfueIWFHSU%3Amatrix.connectme.anais.tech%22%5D%7D%7D` 

Maybe the docs could be improved a bit ? (https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3sync)
