### ISSUE TITLE
Configuration manual lacks documentation for a bunch of workers settings

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13643]
The following are all missing:
 * worker_main_http_uri (cf #13642)
 * worker_manhole

Update (dmr 2022-11-14): The following were missing, but then added in #14086:
 * Under "coordinating workers":
   * worker_replication_secret
   * start_pushers 
   * pusher_instances
 * Under "individual worker configuration":
   * worker_app
   * worker_name
   * worker_replication_host
   * worker_replication_http_port
   * worker_listeners
   * worker_daemonize
   * worker_pid_file
   * worker_log_config

**Comment by dklimpel** [comment]
Also missing:

- update_user_directory_from_worker
- notify_appservices_from_worker
- media_instance_running_background_jobs
