### ISSUE TITLE
Is there a project that i can use to simulate a synapse server for development of a bridge without ssh into the server and using docker for debugging?

### ISSUE THREAD

**Issue by XxSNiPxX** [matrix-org/synapse#13663]
**Description:**

If i want to create a bridge and test it out do i have to ssh into the server , nano the files and use the docker logger to debug the data or is there an environment that i could setup and use. 

Thanks.

**Comment by DMRobertson** [comment]
The recommended development environment for Synapse's s described here: https://matrix-org.github.io/synapse/latest/development/contributing_guide.html 

There are some demo servers https://matrix-org.github.io/synapse/latest/development/demo.html which can be used for quick tests.

Synapse itself can be started with `python3 -m synapse.app.homeserver --config-path path/to/homeserver.yaml`.

I hope that gives you enough clues to get started. For other questions, please ask in the [Synapse developers' room](https://matrix.to/#/#synapse-dev:matrix.org) or the [Matrix developers' room](https://matrix.to/#/#matrix-dev:matrix.org).
