### ISSUE TITLE
"Invalid filter json" error message should use an appropriate error code

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#13661]
```json
{
  "errcode": "M_UNKNOWN",
  "error": "Invalid filter JSON"
}
```

From https://github.com/matrix-org/synapse/blob/a6895dd576f96d7fd086fb4128d48ac8a3f098c5/synapse/rest/client/sync.py#L145-L154

We should return `M_NOT_JSON` if the decode fails.

We should probably also defer the `set_timeline_upper_limit` call until `            self.filtering.check_valid_filter(filter_object)` has passed?

**Comment by shraddhafalane** [comment]
I would like to work on it. @DMRobertson could you please elaborate more on defer logic.

**Comment by DMRobertson** [comment]
> I would like to work on it. @DMRobertson could you please elaborate more on defer logic.

I was thinking that we should move lines 148-150 outside of the `try` block, because they do not related to the decoding of JSON. Probably between lines 153 and 154. But this isn't a hugely important change to make.
