### ISSUE TITLE
Make sure `synapse_rate_limit_reject_affected_hosts` does what it says it does

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#13670]
*Spawning from https://github.com/matrix-org/synapse/pull/13541#discussion_r951926322*

---

The `synapse_rate_limit_reject_affected_hosts` gauge is always evaluating to `0`. The [raw data in Prometheus](https://prometheus.matrix.org/graph?g0.expr=synapse_rate_limit_reject_affected_hosts&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h&g0.end_input=2022-08-22%2021%3A21%3A52&g0.moment_input=2022-08-22%2021%3A21%3A52) also shows `0` for reference.

https://grafana.matrix.org/d/dYoRgTgVz/messages-timing?orgId=1&from=1661855196368&to=1661876796368&viewPanel=220

![`synapse_rate_limit_reject_affected_hosts` all 0 in the graph](https://user-images.githubusercontent.com/558581/186021441-c12de1fd-52ef-4503-b05f-28a644e4ae1f.png)

Even though we see individual requests being rejected  (`synapse_rate_limit_reject_total`) which should mean at least `1` host,

![`synapse_rate_limit_reject_total` with some activity in the graph](https://user-images.githubusercontent.com/558581/186021630-93202f39-c88d-4a34-8144-cf958e3643ce.png)

But this could be a mismatch in how the guages were being reported because we were accidentally registering them twice, https://github.com/matrix-org/synapse/issues/13641

---

Now that we fixed the [duplicate metric registering issue](https://github.com/matrix-org/synapse/issues/13641) in https://github.com/matrix-org/synapse/pull/13649 and the fix was put on `matrix.org` this morning, we're seeing both at `0` now. This could mean that the previous rejections we were seeing were all from the `UsernameAvailabilityRestServlet` which we are no longer tracking. And we're not rejecting any requests in the federation servlets.

It is a bit suspicious though. 

![`synapse_rate_limit_reject_affected_hosts` and `synapse_rate_limit_reject_total` being 0 in the graph after `matrix.org` deploy](https://user-images.githubusercontent.com/558581/187489495-1af77b22-a49d-4261-a94a-4d00a179c974.png)

### How can we know if it's right?

In order to confirm that `synapse_rate_limit_reject_affected_hosts` is working, it would be nice to see a non-zero value.

The `reject_limit` is `50` which I think means there has to be more than 50 requests within the 1 second `federation_rc_window_size` to start rejecting.

We do see the rate of slept requests go above 70 sometimes which I would expect to trigger this 🤔

https://grafana.matrix.org/d/dYoRgTgVz/messages-timing?orgId=1&from=1661873701156&to=1661877301156&viewPanel=223

![`synapse_rate_limit_sleep_total` showing spikes above the 50 `reject_limit`](https://user-images.githubusercontent.com/558581/187491374-17305c17-39a2-4ba8-86aa-0a06d645b350.png)

### Dev notes

The `synapse_rate_limit_reject_affected_hosts` metric was originally added in https://github.com/matrix-org/synapse/pull/13541 and updated in https://github.com/matrix-org/synapse/pull/13649

**Comment by DMRobertson** [comment]
Erm, isn't that `sum` is a sum across all workers?

I'm anxious that two different workers might separately decide to rate-limit `example.com`. If so, that'd mean that example.com is double-counted as two hosts in these graphs (I think?)

**Comment by MadLittleMods** [comment]
@DMRobertson Yes but it's the best we can do to count `hosts` AFAIK

**Comment by MadLittleMods** [comment]
Since the deploy, we have at least seen a blip of rejected requests on `matrix.org` but it looks like it wasn't sustained enough to be caught be the 15 second `/collect` interval that the rejected host gauge runs on.

![](https://user-images.githubusercontent.com/558581/188715468-dc3f95e6-8178-47c8-8058-029a1f820c30.png)

Same blip:

![](https://user-images.githubusercontent.com/558581/188715627-f7b83608-15af-4086-b1bd-17a1139bf272.png)

**Comment by MadLittleMods** [comment]
We finally got something to show up on the "Number of hosts being rejected by the rate limiter" graph (the second one the image). But it doesn't correspond to any spikes in the number of rate limit rejected requests 🤔

https://grafana.matrix.org/d/000000012/synapse?orgId=1&from=1664997566912&to=1666293566912&viewPanel=237
![Blips of 1 on the "Number of hosts being rejected by the rate limiter" graph](https://user-images.githubusercontent.com/558581/197038314-ff9db491-e119-4d41-bd63-d1d538e8ac0a.png)

**Comment by MadLittleMods** [comment]
Seeing this more active on other hosts:

![](https://user-images.githubusercontent.com/558581/207175850-f7387d02-c7fa-477f-8643-2230dd81aa11.png)

Going to close as it seems to count something.
