### ISSUE TITLE
documentation incorrectly states that `event_cache_size` is unaffected by `caches.global_factor`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13682]
Afaict, this changed in https://github.com/matrix-org/synapse/pull/8563

**Comment by richvdh** [comment]
(see: https://matrix-org.github.io/synapse/v1.66/usage/configuration/config_documentation.html#event_cache_size)

**Comment by richvdh** [comment]
related: #13681

**Comment by DMRobertson** [comment]
Details: the `event_cache_size` is used here to create an `AsyncLRUCache`

https://github.com/matrix-org/synapse/blob/92c5817e34cb421dbe2c0df275238e84866932a8/synapse/storage/databases/main/events_worker.py#L242-L247

Which passes through to LRUCache:

https://github.com/matrix-org/synapse/blob/41320a0554716aaf7cec6172da98e002c48344c5/synapse/util/caches/lrucache.py#L821-L830

which will scale the max_size by the global factor:

https://github.com/matrix-org/synapse/blob/41320a0554716aaf7cec6172da98e002c48344c5/synapse/util/caches/lrucache.py#L431-L434
