### ISSUE TITLE
Auto-join any new invite from a room admin

### ISSUE THREAD

**Issue by c10b10** [matrix-org/synapse#13705]
Would it be possible to have an endpoint that allows adding users to a room without them having to accept an invite first?

Something similar to [this](https://github.com/matrix-org/synapse/pull/7051), but for room admins.

**Comment by dklimpel** [comment]
This API only sends an invite if the room is not public.
Perhaps something like this helps you: https://github.com/matrix-org/synapse-auto-accept-invite

**Comment by c10b10** [comment]
thank you!
