### ISSUE TITLE
Notifications take a long time

### ISSUE THREAD

**Issue by STR3IKERKRYPTON** [matrix-org/synapse#13711]
### Description

I'm running a matrix homeserver and using the element client on my OnePlus 7 Pro. The server and the client both have the latest version. Every time I'm sending a message to myself and the element client is running in the background I receive the notification within a few seconds. If I close the app the notification takes between 30 and 40 secounds. Is that because my smartphone only fetches the messages from the server every 30 seconds?

### Steps to reproduce

- Close the app on my smartphone
- Sending myself a message to the smartphone
- The notification takes long time

### Homeserver

homeserver

### Synapse Version

1.66.0

### Platform

The host is an ubuntu 20.04 maschine. The homeserver is running in a docker container.

### Relevant log output

```shell
--- no relevant logs ---
```

**Comment by squahtx** [comment]
Notifications for Android are sent via GCM, which pushes notifications to the app. There shouldn't be any polling involved. It's possible that the app is starting in the background when it receives the notification and doing a bunch of avoidable work during those 30-40 seconds.

Do you notice a difference between notifications for encrypted vs unencrypted rooms?

It'd be useful if you can provide INFO level logs covering the sending of a message and the display of the notification. It's likely that the app is making a couple of requests to the homeserver in the background and we can deduce what's happening by the delays between the sending of the message and the app's requests.

**Comment by reivilibre** [comment]
Are you using the F-Droid version of Element Android? If so, then GCM isn't used and messages are indeed polled occasionally.
You might be able to use UnifiedPush as an alternative: https://github.com/vector-im/element-android/blob/develop/docs/unifiedpush.md

or alternatively you can download the Google Play Store version if you have Google Play Services on your phone

**Comment by DMRobertson** [comment]
@STR3IKERKRYPTON are you able to response to @squahtx and @reivilibre's questions above?

> Do you notice a difference between notifications for encrypted vs unencrypted rooms?

> It'd be useful if you can provide INFO level logs covering the sending of a message and the display of the notification. 

(I think Sean is asking for INFO level logs from Synapse here.)

> Are you using the F-Droid version of Element Android?

**Comment by STR3IKERKRYPTON** [comment]
The problem got solved. Thank you for your help.

**Comment by STR3IKERKRYPTON** [comment]
The version I had before was the one from the F-Droid store. I am currently using a different version that uses Google Push Notifications.
