### ISSUE TITLE
Call out changes in Synapse 1.68 requirements when announcing Synapse 1.67

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#13744]
We are making two related changes related to packaging and from-source installations in 1.68:

- Rust: #12595 et al
- Sqlite: #12983

These should be transparent to anyone using our docker images or our debian packages. However, packagers and those installing from source need to be aware of the upcoming need for a Rust compiler and for a slightly more modern SQLite version.

We expect these changes to be uncontroversial, and have sounded out community packagers directly. Nevertheless, when we announce this (in Matrix channels, in a blog post, and maybe in a tweet?) we should call out these changes so that people are given fair warning.

- [x] Mention in [Synapse announcements room](https://matrix.to/#/!iyIlInqJyxXrRmRHFx:matrix.org/$7sdzd_KII1p3kB_0zT_HG1eYMRX4Nm-9ruyM9Di12AM?via=matrix.org&via=privacytools.io&via=tchncs.de)
- [x] Mention in 1.67 blog post https://github.com/matrix-org/matrix.org/pull/1441

**Comment by clokep** [comment]
> - TCP replication: #13647
> - Poetry: #13689 et al

These both landed in v1.67.0rc1 IIRC.

**Comment by DMRobertson** [comment]
Thanks Patrick, I've got myself confused.

**Comment by DMRobertson** [comment]
(Description amended)

**Comment by clokep** [comment]
> Thanks Patrick, I've got myself confused.

All the more reason to call this out explicitly! 🎉

**Comment by DMRobertson** [comment]
When this is done we should close #12983.
