### ISSUE TITLE
Determine if anyone finds the Prometheus console useful enough to justify recording rules that only it uses

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#13758]
In #13756 it became apparent that we have several Prometheus recording rules whose only appearance is in the Prometheus console file here: https://github.com/matrix-org/synapse/blob/develop/contrib/prometheus/consoles/synapse.html

I have never used this and have never seen anyone use this.

@richvdh touched it most recently — do you use it?

If nobody uses it (I wonder if it was 'the answer' before Grafana), I suggest we remove it, or at least remove the recording rules that aren't used anywhere else, in order to cut down on how much useless stuff we record in Prometheus.

**Comment by dklimpel** [comment]
I find the prometheus console / dashboard helpful. It is a way to easily and quickly get to the most important synapse metrics without reading the long and complex Grafana `json` or implementing a Grafana stack. IMO Grafana is more complex and difficult to get started with than prometheus.
But maybe it was just the reason that an overview of the most important metrics of Synpase is missing in the documentation.

**Comment by richvdh** [comment]
I certainly don't use it. I suspect very few people do.

Perhaps a low-effort solution would just be to comment on the recording rules that they aren't needed unless using that console.
