### ISSUE TITLE
/sync directory is sensitive. database flushed!

### ISSUE THREAD

**Issue by alpha856** [matrix-org/synapse#13817]
### Description

Hello,
when i  was work about 1-2 months ago and testing synapse homeserver version 1.63, i have created direcoty /sync in nginx. i am using homeserver with nginx reverse proxy on localhost port 8008. synapse domain is https://chat.xxx.com also in that time was working with https://github.com/Awesome-Technologies/synapse-admin and add / deactive users.
I have set /sync in nginx chat config file to load data from /var/www/html/chat/sync/ . when i have touched it in browser, https://chat.xxx.com/sync, all database flushed!. database was sqlite.
i think if /sync directory is sensitve, you shoud note it on config documents.

### Steps to reproduce

-

### Homeserver

synapse

### Synapse Version

1.63

### Installation Method

Debian packages from packages.matrix.org

### Platform

Debian 11 - VMware Esxi

### Relevant log output

```shell
-
```

**Comment by DMRobertson** [comment]
I'm going to close this as invalid because I don't think this makes sense. However I'd be interested to know what prompted you to do this---is there some kind of guide or tutorial out there which recommends this?

**Comment by alpha856** [comment]
I create /var/www/html/chat/sync directory on disk and want to update other data from it. not related to Synapse and only using Synapse subdomain. but when i browser https://chat.xxx.com/sync, database was crashed and flushed.
i don't work with /_matrix/sync endpoint and only want to setup other /sync link in nginx config for other perpose. but this happened.

**Comment by DMRobertson** [comment]
I don't think this has anything to do with Synapse, and I can't see anything in https://github.com/Awesome-Technologies/synapse-admin which related to a `/sync` URL.

I suggest you double-check your nginx config.
