### ISSUE TITLE
Cross server chats cannot receive messages from one another after expired SSL certificate was renewed manually

### ISSUE THREAD

**Issue by sla-te** [matrix-org/synapse#13821]
### Description

All cross server contacts, do not receive my messages anymore, nor am I receiving messages from them.

### Steps to reproduce

I guess let the SSL certificate expire and then renew it manually?

### Homeserver

martinrouterking.com

### Synapse Version

1.67.0

### Installation Method

pip (from PyPI)

### Platform

Rocky Linux 9.0

### Relevant log output

```shell
I dont see any error, that I would associate with this (to the best of my knowledge). The only warning in the logs I see is:


│2022-09-15 13:42:10,181 - synapse.http.server - 743 - WARNING - GET-182 - Not sending response to request <XForwardedForRequest at 0x7f93940a3550 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=30000&since=s18000_3485│34_12_18712_18279_6_895_13448_0' clientproto='HTTP/1.0' site='8008'>, already disconnected.   
```

In the client I see one request failing with 504 (no response text) in the debug console:
```
https://martinrouterking.com/_matrix/client/r0/sync?filter=1&timeout=30000&since=s18000_348534_12_18712_18279_6_895_13448_0
```
```


### Anything else that would be useful to know?

One thing has changed, compared to before: Now I use stackpaths ssl certificate, so the A entry of the domain goes to their server and they serve via CDN, that may be related to the problem

**Comment by DMRobertson** [comment]
> Now I use stackpaths ssl certificate, so the A entry of the domain goes to their server and they serve via CDN, that may be related to the problem

This sounds suspicious. What does https://federationtester.matrix.org/ say about your homeserver?

Also worth asking in the [Synapse Admins room](https://matrix.to/#/#synapse:matrix.org) for advice (via matrix.org if necessary): it would be good to rule out a config problem before launching a bug investigation.

**Comment by DMRobertson** [comment]
> federation tester gives:
> Get "https://my_server_ip:8448/_matrix/key/v2/server": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

You need to work out what is causing this request to fail and fix it. Without fixing this, other homeservers are unable to communicate with your own.

> Are there any special settings I have to apply in case of using a cdn?

You might need to setup delegation, see https://matrix-org.github.io/synapse/latest/delegate.html?search=#when-do-i-need-delegation. It's difficult to advise in general without knowing the specifics of your configuration---again, that's best handled in the Synapse Admins room.

**Comment by sla-te** [comment]
Alright, so I have now configured in nginx, that /.well-known/matrix/server will return the following:
```
    location /.well-known/matrix/server {
        return 200 '{"m.server": "martinrouterking.com:443"}';
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }
```
