### ISSUE TITLE
Can't join room: Homeserver answers with HTTP 502 (Bad Gateway)

### ISSUE THREAD

**Issue by uranuspucksaxophone** [matrix-org/synapse#13833]
### Description

The following HTTP request fails with HTTP 502: `https://matrix.anonymousland.org/_matrix/client/r0/join/#matrix:matrix.org?server_name=matrix.org`

### Steps to reproduce

- Create a Matrix account with anonymousland.org as homeserver.
- Try to join Matrix HQ (although this issue could happen with other rooms).
- Wait ~10 minutes.
- Get an "Error joining: Internal server error" (Assuming Element client).

### Homeserver

matrix.anonymousland.org

### Synapse Version

{"server_version":"1.66.0","python_version":"3.10.7"}

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

1984 hosting VPS.

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 502 ()

index.js:218 
 POST https://matrix.anonymousland.org/_matrix/client/r0/join/%23matrix%3Amatrix.org?server_name=matrix.org 502
(anonymous)	@	index.js:218
t	@	index.js:179
(anonymous)	@	browser-index.js:34
doRequest	@	http-api.ts:854
requestOtherUrl	@	http-api.ts:729
request	@	http-api.ts:681
authedRequest	@	http-api.ts:624
joinRoom	@	client.ts:3539
await in joinRoom (async)		
u.a.dispatch.action	@	RoomViewStore.tsx:381
i	@	promise.ts:39
joinRoom	@	RoomViewStore.tsx:381
__onDispatch	@	RoomViewStore.tsx:202
e.__invokeOnDispatch	@	FluxStore.js:148
(anonymous)	@	FluxStore.js:79
e._invokeCallback	@	Dispatcher.js:198
e.dispatch	@	Dispatcher.js:174
setTimeout (async)		
dispatch	@	dispatcher.ts:52
(anonymous)	@	RoomView.tsx:1417
Promise.then (async)		
(anonymous)	@	RoomView.tsx:1415
He	@	react-dom.production.min.js:52
We	@	react-dom.production.min.js:52
(anonymous)	@	react-dom.production.min.js:53
Tr	@	react-dom.production.min.js:100
Cr	@	react-dom.production.min.js:101
(anonymous)	@	react-dom.production.min.js:113
Me	@	react-dom.production.min.js:292
(anonymous)	@	react-dom.production.min.js:50
Or	@	react-dom.production.min.js:105
Zt	@	react-dom.production.min.js:75
Xt	@	react-dom.production.min.js:74
t.unstable_runWithPriority	@	scheduler.production.min.js:18
Gi	@	react-dom.production.min.js:122
Re	@	react-dom.production.min.js:292
$t	@	react-dom.production.min.js:73
rageshake.ts:73 Failed to join room: Failed to send_join via any server


(no further log entry on client is produced).
```

### Anything else that would be useful to know?

HS Admin: @d-eathrow

**Comment by DMRobertson** [comment]
Joins to large and/or old rooms are known to be slow. There is a large project underway to speed this up, see https://github.com/matrix-org/synapse/milestone/8.

The logs are appreciated but they look to be from Element-web. We would need server logs to understand why anonymousland.org returned status 502.

**Comment by richvdh** [comment]
the 502 will be simply because the upstream server (most likely matrix.org) took ages to respond to the join request.

Duplicate #1211
