### ISSUE TITLE
Misleading documentation for `user_directory.search_all_users`

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#13852]
The [documentation](https://matrix-org.github.io/synapse/v1.67/usage/configuration/config_documentation.html#user_directory) says:

> Defines whether to search all users visible to your HS when searching the user directory.

It does not make it clear that the users included in that cohort art the users visible by the homeserver _at the time_ the search is performed, i.e. all users who share a room with a user from the homeserver at that time. As opposed to all users the homeserver has ever seen, regardless of whether they share a membership in a room.

While we're doing things around this part of the doc, it has a link to https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/background_updates.html#run which hasn't been linkified - it should probably be turned into a relative link (so that version prefixes in URLs carry over).

**Comment by exitflynn** [comment]
i'd love to work on this issue!

**Comment by babolivier** [comment]
Feel free to open a PR for then :)

**Comment by Abhijnan-Bajpai** [comment]
If this issue is yet to be resolved, could I work on this?

**Comment by tjay27** [comment]
Is this right?

If [user_directory](https://matrix-org.github.io/synapse/v1.67/usage/configuration/config_documentation.html#user_directory)'s  `search_all_users`  is

true - searches all users that share a room with the homeserver at that time.
false -  search results will only contain users visible in public rooms and users sharing a room with the requester at that time

**Comment by tjay27** [comment]
@DMRobertson 
It shows the URL there instead of  `for running background updates` as mentioned in markdown. 
That is what he meant by linkify 

![image](https://user-images.githubusercontent.com/47633397/211351561-ffcacbac-8192-4ebe-9046-993ef4292e8f.png)

**Comment by DMRobertson** [comment]
Looks like https://github.com/matrix-org/synapse/pull/14003 fixed the link.
