### ISSUE TITLE
`have_seen_event` cache is not invalidated when we persist an event

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#13856]
The [`have_seen_event` cache](https://github.com/matrix-org/synapse/blob/2b522cceb6cb4919a3a92e99917e7199d9feaeb1/synapse/storage/databases/main/events_worker.py#L1485-L1530) is not invalidated when we persist an event.

This is evident when a `/messages` request triggers a `/backfill` and it claims that we have the same missing state and auth events each time we `_process_pulled_event` from the backfill response even though we just fetched and persisted those same state and auth events from the previous event we processed.

I see that we have one spot in Synapse where we invalidate the `have_seen_event` cache (besides when we [purge](https://github.com/matrix-org/synapse/blob/2b522cceb6cb4919a3a92e99917e7199d9feaeb1/synapse/storage/databases/main/purge_events.py#L299-L306) [a room](https://github.com/matrix-org/synapse/blob/2b522cceb6cb4919a3a92e99917e7199d9feaeb1/synapse/storage/databases/main/purge_events.py#L483-L485)) but if I add a log line to `_invalidate_caches_for_event`, it never runs in my Complement tests. Does this have a bug where the `CacheInvalidationWorkerStore` stuff never runs in monolith mode?

https://github.com/matrix-org/synapse/blob/2b522cceb6cb4919a3a92e99917e7199d9feaeb1/synapse/storage/databases/main/cache.py#L211-L226

---

Discovered while trying to make Synapse fast enough for [this MSC2716 test for importing many batches](https://github.com/matrix-org/complement/pull/214#discussion_r741678240). As an example, disabling the `have_seen_event` cache saves 10 seconds for each `/messages` request in that MSC2716 Complement test because we're not making as many federation requests for `/state` (speeding up `have_seen_event` itself is related to https://github.com/matrix-org/synapse/issues/13625) 

But this will also make `/messages` faster in general so we can include it in the [faster `/messages` milestone](https://github.com/matrix-org/synapse/milestone/11).

### Dev notes

`have_seen_event` cache originally added in https://github.com/matrix-org/synapse/pull/9953

**Comment by DMRobertson** [comment]
> I see that we have one spot in Synapse where we invalidate the `have_seen_event` cache (besides when we [purge](https://github.com/matrix-org/synapse/blob/2b522cceb6cb4919a3a92e99917e7199d9feaeb1/synapse/storage/databases/main/purge_events.py#L299-L306) [a room](https://github.com/matrix-org/synapse/blob/2b522cceb6cb4919a3a92e99917e7199d9feaeb1/synapse/storage/databases/main/purge_events.py#L483-L485)) but if I add a log line to `_invalidate_caches_for_event`, it never runs in my Complement tests. Does this have a bug where the `CacheInvalidationWorkerStore` stuff never runs in monolith mode?

Seems plausible: they only seem to be called by `process_replication_rows` and `_process_event_stream_row`, both of which are for responding to replication messages only.

**Comment by DMRobertson** [comment]
Not familiar with the event persistence code, but it looks like `persist_event` and `persist_events` end up calling `_persist_event_batch` and then `_persist_events_and_state_updates`. The latter might be a good place to invalidate caches? But thinking a little more, maybe it should be the place that sends out the replication messages. Not sure where those are.

**Comment by clokep** [comment]
I wonder if we should be prefilling the cache in this case instead of invalidating it? Isn't it likely that we're going to immediately use that event if we just persisted it?

**Comment by DMRobertson** [comment]
I had the same thought: if but I wasn't sure how easy it is to do that with the cachedList magic.

**Comment by MadLittleMods** [comment]
Changing the title back to "`have_seen_event` cache is not invalidated when we persist an event" because even though `_invalidate_caches_for_event` was called via events over replication (in worker mode), there is another bug in it where we try to invalidate the `have_seen_event` cache with the wrong key so it still doesn't work, see https://github.com/matrix-org/synapse/pull/13863#discussion_r977053643

**Comment by MadLittleMods** [comment]
Thanks for the input @DMRobertson and @clokep! Really helped ease the pain making the fix in https://github.com/matrix-org/synapse/pull/13863
