### ISSUE TITLE
caching on `have_seen_event` is somewhat broken

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#13865]
*As discovered in https://github.com/matrix-org/synapse/pull/13863#discussion_r977053643 and discussed in [#synapse-dev](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$Mo3uFoylqQURC6kbps0nyw0HHAOwdh4mXY1-DE_Qe28?via=matrix.org&via=element.io&via=beeper.com). Part of https://github.com/matrix-org/synapse/issues/13856*

The [cache](https://github.com/matrix-org/synapse/blob/v1.68.0rc1/synapse/storage/databases/main/events_worker.py#L1527) on `have_seen_event` uses a `TreeCache`, which means the cache is structured as `{room_id: {event_id: result}}`. However, `_have_seen_events_dict` tries to use it with `@cachedList`, which stores entries as `{(room_id, event_id): result}`. As a result, caching is inefficient, and cache invalidation is unreliable.

**Comment by richvdh** [comment]
We suspect this has been the case ever since the cache was added to `have_seen_event` in #9953, but it would be interesting to test this to confirm.

Fixing this probably involves updating `@cachedList` to work correctly with `TreeCache`s?

**Comment by richvdh** [comment]
Relatedly: `have_seen_events` calls `_have_seen_events_dict`, so the thing gets cached twice in the same cache, once as a `room_id -> event_id -> result` tree, and the other as a `(room_id, event_id) -> result`.

**Comment by richvdh** [comment]
(Fortunately, `have_seen_event` is mostly an optimisation, so failure to invalidate is unlikely to have had too much visible effect other than inefficiency.)

**Comment by erikjohnston** [comment]
I think that the usage of `@cachedList` is wrong. It expects to be given the same number of arguments as the underlying cached function, just with *one* of the arguments being an iterable

https://github.com/matrix-org/synapse/blob/cfe486b0410c045e4db12c694ed5388365f5b54b/synapse/storage/databases/main/events_worker.py#L1485-L1488

I think that should actually be:

```python
 @cachedList(cached_method_name="have_seen_event", list_name="event_ids") 
 async def _have_seen_events_dict( 
     self, room_id: str, event_ids: Collection[str],
 ) -> Dict[str, bool]: 
```

**Comment by richvdh** [comment]
oh right, that's quite a lot easier.
