### ISSUE TITLE
Controlled Accounts

### ISSUE THREAD

**Issue by izN8nu6RyeneG5XnBoBgyRMVGH6H43WF** [matrix-org/synapse#13880]
## Description:

Migrating the [Controlled accounts](https://github.com/matrix-org/matrix-spec/issues/797) issue in the spec repo, as it should be tracked as an implementation issue, or at least the use cases do not require support so broad it needs to be in the core spec.

@twouters said:
>I've been looking for a way for my kid to communicate with their classmates/friends in a responsible way (both privacy and security) but my pursuit ended with the sad conclusion that there currently is no such thing.
>[...]
>Child accounts should be restricted in many ways:
> - must be created by an existing account (parent account) and cannot be created on their own.
> - multiple accounts can be assigned as parent accounts, but each parent account should be notified about other parent account actions concerning the child account.
> - all child account communication should be end-to-end encrypted (somewhat, see following point)
> - ~**(controversial)** all parent accounts ~should~ (may) be able to access end-to-end encrypted communication (this might be a bit tricky because if all parent accounts are automatically joined in every room, the children will get the feeling of being continuously watched which is not what I want to achieve)~
> - all child account actions are constrained to non-public spaces. (not sure if that's a thing, I should read up on the current spaces spec)
> - can't join spaces without parental approval.
> - can't accept invites without parental approval (unless specifically allowed in a Space).
> - can't join rooms without parental approval (unless specifically allowed in a Space).

### Enterprise Applications

There was some talk in the original issue about how these would be applicable to other use cases, such as corporate environments:

@ShadowJonathan said:
>[...]
> However, I think the idea for a "controlled account" is an interesting one in-general, whereas such accounts may be controlled by corporate IT - for whatever reason, management or legal compliance - and managed centrally, this could replicate a Slack-like environment, and somewhat bound these accounts to the corporate environment (unless explicitly allowed by "query" (by the user) and "confirmation" (by IT)).
>
> If the above could be implemented somehow, and with nomadic/decentralised accounts, one could possibly hold onto a matrix "identity" in a multitude of ways, getting one at a corp, but "retaining" it even after they left, or joined another corp. This needs more investigation and research, but that'd be a huge boon for corperate/business use of matrix.
>
> A "parental guidance" method could simply derive from such "controlled accounts", then, maybe through the aforementioned "query and confirmation" method, it'd allow kids some agency, but allows parents to set the boundaries with minimal privacy intrusion.
>[...]

@beercanchicken said (emphasis added):
>Great idea. **Addition of an account that can be supervised is a key marketable feature to enterprise.**
>[...]
>I see potential appeal to the supervisory levels of a corporate structure for supporting limited, supervisable accounts. This could translate into enhancing the offerings of EMS (therefore, enhancing potential revenue.)

### Values and Goals

There was some talk about which of these are a "Good Idea™" and consistent with the Matrix foundation's goals:

@SimonBrandner said:
> [...]
> In general, I am not in favour of child accounts and similar (at least partially). That is mainly because I feel like this can be abused. If I were an LGBT kid in a homophobic family this can be very unhelpful, the same can be applied in other cases. But I also understand the need for parents to have some kind of control (probably not the right word here) over what their children are doing.
> 
> I realize that there is much more nuance to this but I feel like the consequence should be considered - these should be entirely configurable, either by the client or by the user (in this case parent).
> [...]

@ShadowJonathan said:
> [...]
> Parentage of this sort should come from a trust feedback loop between the kid and the parent, where the kid trusts the parent's opinion, and the parent trusts the kid to ask them. The approach to monitor their social media usage closely, imo, takes it more to the "but think of the children!" side of parentage, which (imo) is very toxic and probably detrimental to a kid's development.
> [...]

@izN8nu6RyeneG5XnBoBgyRMVGH6H43WF said:
>[...]
>[On] the grounds that the Matrix Manifesto states,
> 
>     The ability to converse securely and privately is a basic human right.
> 
> I vehemently oppose having anything other than E2E encryption be the standard.

### Spec or Implementation

There was some talk about, if the feature were added, whether it belongs in the Matrix core spec, or elsewhere:

@twouters said (emphasis added):
> I agree for the most part. The primary reason for including the snoop permissions is to prevent abuse, but if there's another way to accomplish this (by setting proper boundaries somehow) that would be fine too.
>
> In the example of schools the snooping part could be used as a tool to limit cyber bullying, **so it could become an optional feature instead of a requirement**.

@izN8nu6RyeneG5XnBoBgyRMVGH6H43WF said (emphasis added):
>[...]
>[twouters is] right that the client has to support the feature, but Matrix was never intended to prohibit features not in the specification. In fact, **[Matrix] was designed to be extensible, i.e. to allow people to add additional APIs that wouldn't necessarily be supported by every client** [...]
>
>If you wanna have an implementation detail in Synapse to make it easier for administrators to create controlled [accounts], then **that's a convenience that belongs in Synapse**.

## Why are you posting this here?

As noted above, this should probably be an optional feature, and therefore should not be in the core spec. It might make more sense to implement it in Synapse, then define an extension spec based on Synapse's implementation details if needed.

**Comment by turt2live** [comment]
Let's keep the discussion in the spec for now - it's too early to move it.
