### ISSUE TITLE
web_client_location setting should also be listed on top of the list when someone click on a shared room link

### ISSUE THREAD

**Issue by erinarbleizez** [matrix-org/synapse#13898]
when we set web_client_location it only impact the root access to matrix server but because we put it in the matrix configuration it means that this web_client_location weight more for us admins on our matrix selfhosted server than others and should be put on top of the list of the proposed clients.

their also should be an option to disable that list and when someone enter a shared room through url he is forced to the web_client_location (something more acceptable for companies than giving the guest the choice to enter through app.element.io for example and fail because federation is disable for security concern).

**Comment by DMRobertson** [comment]
> someone click on a shared room link

I think this refers to `matrix.to` links? Those are not served by the homeserver, and so I don't think there's any opportunity to do what you suggest.

Additionally:

> than giving the guest the choice to enter through app.element.io for example and fail because federation is disable for security concern

app.element.io hosts an instance of element-web, and one can use it as a client to log in to any homeserver, e.g.
![image](https://user-images.githubusercontent.com/8614563/192502480-70945645-18e0-44cc-87fd-3fad4f408a91.png)

Federation refers to one server communicating directly with another server; app.element.io is a client.
