### ISSUE TITLE
`Cargo.lock` missing in release tarball of 1.68.0rc2

### ISSUE THREAD

**Issue by NickCao** [matrix-org/synapse#13907]
### Description

`Cargo.lock` should be included in the release tarball for reproducible builds.

### Steps to reproduce

```bash
curl -sL https://github.com/matrix-org/synapse/releases/download/v1.68.0rc2/matrix-synapse-1.68.0rc2.tar.gz | tar tzf - | grep Cargo
```

### Homeserver

not applicable

### Synapse Version

1.68.0rc2

### Platform

not applicable

### Relevant log output

```shell
not applicable
```

**Comment by DMRobertson** [comment]
I think we need a top-level Cargo.lock here? https://github.com/matrix-org/synapse/blob/11ebcc8a3abf24cb49a3022dc335645987fb3f8f/pyproject.toml#L88-L90

**Comment by NickCao** [comment]
As this whole project is a single cargo workspace, there should be one and only one top-level `Cargo.lock` for all member crates.
