### ISSUE TITLE
setuptools_rust should not be a runtime dep

### ISSUE THREAD

**Issue by darix** [matrix-org/synapse#13926]
### Description

This is a build time dep and not a runtime dep. At startup synapse should not check for this anymore.

### Steps to reproduce

try to start synapse without setuptools_rust installed.

### Homeserver

another home server

### Synapse Version

1.68.0

### Installation Method

Other (please mention below)

### Platform

openSUSE Tumbleweed rpm

### Relevant log output

```shell
Sep 28 03:06:30 tengu matrix-synapse[4251]: ERROR:root:Synapse 1.68.0 needs setuptools_rust, but it is not installed
Sep 28 03:06:30 tengu matrix-synapse[4251]: Missing Requirements: "setuptools_rust"
Sep 28 03:06:30 tengu matrix-synapse[4251]: To install run:
Sep 28 03:06:30 tengu matrix-synapse[4251]:     pip install --upgrade --force "setuptools_rust"
```

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/blob/1254eb224749210c03c9698b09bdce73a066acd4/pyproject.toml#L177-L185

Erm wat. Was this meant to be a dev dependency or not @erikjohnston?

**Comment by erikjohnston** [comment]
Argh, that comment is confused.

The problem is that we don't have the ability to set build dependencies, so we have to set it as a "runtime" dependency in pyproject.toml. We could add it as a "dev" dependency, but decided against that as `poetry install --no-dev` would then fail to build in source checkouts

We *could* special case it in Synapse so that it doesn't check that particular dependency.

**Comment by DMRobertson** [comment]
> The problem is that we don't have the ability to set build dependencies

Isn't that what this is trying to do? Or does poetry ignore these?

https://github.com/matrix-org/synapse/blob/1254eb224749210c03c9698b09bdce73a066acd4/pyproject.toml#L309-L311

> We _could_ special case it in Synapse so that it doesn't check that particular dependency.

I'd be fine with this... begrudingly.

**Comment by erikjohnston** [comment]
That's what the first part of the comment is talking about:

> This is for building the rust components during "poetry install", which 
currently ignores the `build-system.requires` directive (c.f. 
https://github.com/python-poetry/poetry/issues/6154). Both `pip install` and 
`poetry build` do the right thing without this explicit dependency.

i.e. if the build requirements are ignored when doing `poetry install`

**Comment by DMRobertson** [comment]
> i.e. if the build requirements are ignored when doing `poetry install`

I would like to once again declare that I hate Python packaging.

**Comment by darix** [comment]
could you advice which lines i should patch to workaround this issue until a fix is ready?

**Comment by DMRobertson** [comment]
> could you advice which lines i should patch to workaround this issue until a fix is ready?

It's difficult to say without knowing how the openSUSE Tumbleweed rpm is built. You could comment out this line for the time being.

https://github.com/matrix-org/synapse/blob/bf9d549e3ad944e1e53a2ecc898640d690bf1eac/synapse/util/check_dependencies.py#L197
