### ISSUE TITLE
Complement `TestPartialStateJoin/Rejects_send_knock_during_partial_join` is flakey(?)

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#13945]
https://github.com/matrix-org/synapse/actions/runs/3149312740/jobs/5120797152

**Comment by squahtx** [comment]
I suspect this is failing for the same reason as https://github.com/matrix-org/synapse/issues/13975.
`!room:hostname:port`s are being reused across different tests.

**Comment by squahtx** [comment]
Closing as a duplicate.
