### ISSUE TITLE
Some Synapse instances have been hammering their database after v1.66.0 -> v1.68.0 update

### ISSUE THREAD

**Issue by jaywink** [matrix-org/synapse#13942]
### Description

Some EMS hosted Synapse instances are hammering their database after upgrading from v1.66.0 to v1.68.0. The host concentrating here on is `ecf6bc70-0bd7-11ec-8fb7-11c2f603e85f-live` (EMS internal host ID, please check with EMS team for real hostnames).

The offensive query is:

```
SELECT c.state_key FROM current_state_events as c
            /* Get the depth of the event from the events table */
            INNER JOIN events AS e USING (event_id)
            WHERE c.type = ? AND c.room_id = ? AND membership = ?
            /* Sorted by lowest depth first */
            ORDER BY e.depth ASC
```

The background update running at the time was `event_push_backfill_thread_id`, if relevant.

Graphs:

IOPS increase at upgrade. The initial plateau at 4K was due to the database being locked to 4K IOPS. Now it has 10K and has consistently continued to hammer the database after ~7 hours since the upgrade.

![Screenshot-20220929153250-367x258](https://user-images.githubusercontent.com/1174866/193037085-6b1d851a-bbde-4030-999e-6808196906d1.png)

Degraded event send times especially when constrained to 4K IOPS, which the host has been running with for a long time fine.

![Screenshot-20220929153504-893x343](https://user-images.githubusercontent.com/1174866/193037462-d6f104d7-dc78-4855-8c3a-0ca9cad8c5ea.png)

Stateres worst-case seems to reflect the database usage, just side effect of a busy db?

![Screenshot-20220929153521-889x343](https://user-images.githubusercontent.com/1174866/193037581-f5f7bc01-06f7-4bdb-8181-30efac8df0e6.png)

DB usage for background jobs had a rather massive spike for notify_interested_appservices_ephemeral right after upgrade.

![Screenshot-20220929154001-1761x547](https://user-images.githubusercontent.com/1174866/193037853-27571e3f-f66e-4ee0-807b-db8f4bae32d4.png)

Taking that away from the graph, we see db usage for background jobs higher since upgrade all around.

![Screenshot-20220929154029-1783x562](https://user-images.githubusercontent.com/1174866/193038025-2dbfa6a4-d999-4e5f-bd68-c1045f09078c.png)

DB transactions:

![Screenshot-20220929154151-1782x569](https://user-images.githubusercontent.com/1174866/193038077-0cd1b7b4-d13e-40c3-8ed8-883fc6de291d.png)

Cache eviction seems to indicate we should raise the `get_local_users_in_room` cache as it is being evicted a lot by size. However, this has been the case pre-upgrade as well.

![Screenshot-20220929154328-888x344](https://user-images.githubusercontent.com/1174866/193038111-f819813c-20e3-481a-82d2-6904fbdfc5b8.png)

Appservice transactions have not changed during this time by a large factor (3 bridges):

![Screenshot-20220929154352-1783x317](https://user-images.githubusercontent.com/1174866/193038552-d909ef6c-5b09-45ce-831f-94943cedb953.png)

A few other hosts manually found:

* 01bbd800-4670-11e9-8324-b54a9efc8abc-live

![image](https://user-images.githubusercontent.com/1174866/193039238-348be5fb-8b55-4dbc-a874-b7a25d90f85b.png)

* db0718c0-2480-11e9-83c4-ad579ecfcc33-live

![image](https://user-images.githubusercontent.com/1174866/193039401-c94228b4-9c7a-4d4e-a480-ad0e71eb7a8a.png)

Day time based changes in traffic have been ruled out, all these issues started on upgrade with no other changes to the hosting or deployment stack. There are probably more hosts affected by the db usage increase.

---

Also discussed in [backend internal](https://matrix.to/#/!SGNQGPGUwtcPBUotTL:matrix.org/$LIb1gBgP0nShFbhRAcQkviy61nVhp8eTwEtJODcdLF4?via=jki.re&via=matrix.org&via=element.io).

### Steps to reproduce

Uprgade from v1.66.0 to v1.68.0.

### Homeserver

ecf6bc70-0bd7-11ec-8fb7-11c2f603e85f-live, 01bbd800-4670-11e9-8324-b54a9efc8abc-live, db0718c0-2480-11e9-83c4-ad579ecfcc33-live

### Synapse Version

v1.68.0

### Installation Method

Other (please mention below)

### Platform

EMS flavour Docker images built from upstream images. Kubernetes cluster.

### Relevant log output

```shell
-
```

**Comment by reivilibre** [comment]
That query was touched recently by #13575.

**Comment by DMRobertson** [comment]
```
$ git log --oneline -S get_users_in_room v1.66.0..v1.68.0
  e124b24ad 1.68.0rc1
  906cead9c Update docstrings to explain the impact of partial state (#13750)
  cdf7fb737 1.67.0rc1
  1a209efdb Update `get_users_in_room` mis-use to get hosts with dedicated `get_current_hosts_in_room` (#13605)
  d58615c82 Directly lookup local membership instead of getting all members in a room first (`get_users_in_room` mis-use) (#13608)
  c807b814a Use dedicated `get_local_users_in_room` to find local users when calculating `join_authorised_via_users_server` of a `/make_jo  in` request (#13606)
```

On the affected hosts we saw that postgres used a heap scan rather than an index scan for the aggressive query. Forcing an index-only scan (SET enable_bitmapscan to off) made the query quicker (500->300ms) for one trial set of parameters. Unclear if those are representitive. Also unclear if the index-only scan used more or less file IO.

But this might be barking up the wrong tree. Are we perhaps calling `get_users_in_room` in more circumstances now? Do we need to up its cache?

**Comment by anoadragon453** [comment]
Note that on matrix.org the cache factor specifically for `get_users_in_room` is between 7 and 20 across most workers. The global cache factor is typically either 1 or 2. This may help explain a discrepancy between matrix.org and these hosts.

**Comment by DMRobertson** [comment]
> That query was touched recently by #13575.

By trying different versions we've confirmed that #13575 contributed to the performance regression, and we haven't seen any evidence of other queries being suddenly more expensive.

We did this by trying 51d732db3b4ab13eb58e937a546abce7968112ef and its parent 4f6de33f4147f745eb808b717666eb4d35a12716 on a test server. (I tried to revert 51d732db3b4ab13eb58e937a546abce7968112ef on top of 1.68.0 for testing, but there were merge conflicts and I wasn't sure how to handle them---could use advice from @MadLittleMods on that one, and on how to proceed here more generally.

Anyway, here's the graph of database IO (bigger = more IO credits available) from the test server.

![image](https://user-images.githubusercontent.com/8614563/193108521-1dec0458-dff7-4e30-9ae2-b59ca1e6eb1f.png)

Seems convincing to me.

**Comment by MadLittleMods** [comment]
Summarizing some more [discussion in backend internal](https://matrix.to/#/!SGNQGPGUwtcPBUotTL:matrix.org/$yarNGUoO9E8SbkKDUiVeEfk5pzx-zYtlZQ5pa1aa3aA?via=jki.re&via=matrix.org&via=element.io):

We don't know exactly what upstream callers are accounting for all of these `get_users_in_room` calls but everything kinda points to this being appservice related.

This also makes sense since one of the affected hosts is Element One which has a lot of bridged appservice users.

I suspect we have some more `get_users_in_room` mis-uses in the appservice code where we should be using `get_local_users_in_room` since the appservice only needs to worry about users on it's own server. Fixing these mis-uses doesn't fix `get_users_in_room` performance itself but using `get_local_users_in_room` would be more performant than whatever we end up changing with `get_users_in_room`.

@clokep pointed out a couple `get_users_in_room` mis-uses already:

 - https://github.com/matrix-org/synapse/blob/7bc08f320147a1d80371eb13258328c88073fad0/synapse/appservice/__init__.py#L175-L177
 - https://github.com/matrix-org/synapse/blob/21eeacc99551febcddcef21db96a2bd82166fc7e/synapse/storage/databases/main/appservice.py#L160-L163
 
I'll work on a PR now to change these over ⏩

**Comment by jaywink** [comment]
> everything kinda points to this being appservice related.

The host I used for testing also has a whatsapp bridge with lots of remote users and a signal bridge. The other host mentioned (db0718c0-2480-11e9-83c4-ad579ecfcc33-live) is a rather large host with a Telegram bridge. Sorry I failed to mention these in the original issue description even though appservices came to mind early on. I failed to realize db0718c0-2480-11e9-83c4-ad579ecfcc33-live has a Telegram bridge and thus didn't feel there was a connection after all.

One other large host I looked at (8e71e000-3607-11ea-8fb7-3d4a5344b740-live) has no appservices. It shows a slight baseline increase in IOPS, though nothing on the levels of the others. This may be why we're not seeing this issue all around in our monitoring stack. However, just want to make the point that it looks like non-appservice hosts are also affected by the changes, though in a much more smaller level.

![Screenshot-20220929210618-876x439](https://user-images.githubusercontent.com/1174866/193209727-20ce2813-2685-41b1-b8c9-878906468bbb.png)

Doesn't look like this is affecting apdex, but it may affect for hosts where the RDS is struggling to provide the extra query weight.

![Screenshot-20220930095852-875x334](https://user-images.githubusercontent.com/1174866/193210128-de1c0df9-9a4e-4f1d-a87a-6367cc3ae292.png)

**Comment by erikjohnston** [comment]
I have to say I'm leaning towards backing out the change to `get_users_in_room` entirely, yeah there are some misuses going around but there are legitimate places we call `get_users_in_room` and I don't see why those won't be as affected by the change.

It's also worth noting that Beeper (cc @Fizzadar) have been trying to rip out all the joins onto the events table for performance reasons. 

I'd vote we add a separate `get_ordered_hosts_in_room` that returns the ordered list of hosts, and only use that when we actually care. That would also allow us in future to be more clever with the ordering of hosts (e.g. by order by perceived health of the remote, etc).

**Comment by erikjohnston** [comment]
But also I should say: I'm surprised the change has caused this much problem, so this is not anyone's fault!

**Comment by Fizzadar** [comment]
As Erik mentioned we (Beeper) also have this issue with RDS x IOPs starvation. Joins seem to be particularly expensive in terms of IOPs (both on index and not). I can't find the source right now but IIRC doing joins effectively acts as an IOPs multiplier which may be why this change hurt so much (x the AS paths utilising the function heavily).
