### ISSUE TITLE
Move from deferred to async ModuleApi methods

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/synapse#13948]
**Description:**

Currently some methods of the `ModuleApi` are still defer coroutines instead of async defs, such as e.g. `check_user_exists` and `register_user`, even tho they really are just wrappers with no additional logic. Since the `ModuleApi` is slowly moving to mostly async, it'd be great to have those methods be async as well, so modules no longer need a deferred wrapper.

**Comment by richvdh** [comment]
yeees, though that will break compatibility with modules that are relying on them returning Deferreds. It's not entirely obvious this is worth the effort right now.

**Comment by johannescpk** [comment]
Yeah, but breaking changes is a thing in software development, generally, right? I wonder tho, would it need a synapse v2, or what's the semver story for `ModuleApi`?

**Comment by richvdh** [comment]
Generally one balances breaking changes with the benefit gained from imposing those changes, otherwise everything would be broken the entire time!

**Comment by johannescpk** [comment]
Hmmm, an alternative would be keeping backwards compatibility via alternative class/method naming/exposing. In my particular use case I'm now relying on `ModuleApi._auth_handler` being present: https://gitlab.com/famedly/company/backend/services/synapse-token-authenticator/-/blob/b26a3d29a94dbf2cf4ae318e4bd9cf07bd86f469/synapse_token_authenticator/token_authenticator.py#L111. Maybe `auth_handler` could be publicly exposed? :thinking:

**Comment by johannescpk** [comment]
> I think modules should generally be able to just call these methods as if they're async though and await them like normal?

Oooh, turns out you're right. It works by just `await`ing the methods. In this case the issue could also be closed since that allows me to just use the public `ModuleApi` methods. Sorry for the noise.

**Comment by clokep** [comment]
No problem! Glad that worked for you!

**Comment by johannescpk** [comment]
Wait, it seems I've used an outdated container instead of the rebuilt one. :facepalm:  It fails with

> synapse.handlers.auth - 2121 - WARNING - POST-4 - Failed to run module API callback <bound method TokenAuthenticator.check_auth of <token_authenticator.TokenAuthenticator object at 0x7f5aadda17c0>>: 'str' object is not callable

unfortunately. I suppose that's the `register_user` call. Would be nice to reopen the issue.

(It worked in the test file, but my mocks are `async` and not deferred)

**Comment by clokep** [comment]
I think you'll need to provide an minimal example of what you're trying to do and what isn't working then.

**Comment by johannescpk** [comment]
https://gitlab.com/famedly/company/backend/services/synapse-token-authenticator/-/blob/b26a3d29a94dbf2cf4ae318e4bd9cf07bd86f469/synapse_token_authenticator/token_authenticator.py#L118-120 is what I'm doing.

Instead I'd like to call a public async API. I could also use synapse's `make_deferred_yieldable`, but I'm not sure how to start the async reactor in the tests, which not work without a running async reactor (not sure if that's the correct term).

Exposing the `auth_handler` in the `ModuleApi` as supported public API would also help.

**Comment by clokep** [comment]
The following should work OK, I think:

```python
        if not user_exists:
            logger.info("User doesn't exist, registering it...")
            await self.api.register_user(
                user_id.localpart, admin=payload.get("admin", False)
            )
```

You can `await` a `Deferred`, but you cannot `yield` an `Awaitable`.

**Comment by johannescpk** [comment]
You are right. I tested by modifying just that call and it works. Not sure what went wrong in https://github.com/matrix-org/synapse/issues/13948#issuecomment-1263649890, probably something else I changed while refactoring the calls.

Thanks for your patience & help.

**Comment by johannescpk** [comment]
> Not sure what went wrong in https://github.com/matrix-org/synapse/issues/13948#issuecomment-1263649890

For completeness sake: I was calling `server_name()`, even though it's just a property. Fixed that and now fully works, also in the tests.
