### ISSUE TITLE
Local room joins are slow

### ISSUE THREAD

**Issue by H-Shay** [matrix-org/synapse#13965]
Local room joins are known to be slow, currently taking anywhere from 266ms-1.7s or more when joining #synapse-dev (as an example room). Ideally this would take less than 300ms on average. More profiling work is needed to determine if there are any obvious changes to the code that will facilitate this. In addition, work on speeding up event persistence (including calculating push rules) would definitely help resolve this issue, although may be out of the immediate scope.  

Next steps:
Add more logging to pin down the cause of slow database transactions:
https://github.com/matrix-org/synapse/issues/13964

**Comment by erikjohnston** [comment]
Local joins are now significantly faster than they were. We still see some slow joins because we sometimes see that there are pauses between a DB transaction completing and the main thread being woken up, but that is a generic issue and not specific to `/join`
