### ISSUE TITLE
DM creation is slow

### ISSUE THREAD

**Issue by H-Shay** [matrix-org/synapse#13963]
DM creation in Synapse is know to be slow, taking up to approximately 1-3s in some traces. Ideally this should not take more than 300ms, although it is unclear if it is possible to get there.  There has been some work done on this issue, namely https://github.com/matrix-org/synapse/pull/13800.

Known next steps:
Investigate whether the membership event in the initial create room events can be added to the batch for bulk persisting:
#13959
Batch up storing state groups for initial room creation events:
#13961
Investigate which other events can be batched for bulk persisting and do so:
#13962

It is unclear if taking these steps will totally resolve the issue. If they do not, it might be necessary to add more logging to determine more precisely where the time is going (especially with regard to database calls), or look at trying to speed up event persistence in general.

**Comment by DMRobertson** [comment]
(Would it be helpful to have a milestone for the faster DMs/faster room creation work?)

**Comment by erikjohnston** [comment]
Once https://github.com/matrix-org/synapse/issues/13961 (PR https://github.com/matrix-org/synapse/pull/14918) has landed this should hopefully be good enough. We'll likely still continue the work fixing up the module API to support batching (which blocks https://github.com/matrix-org/synapse/issues/13959), but that is more being as a tidy up task.
