### ISSUE TITLE
`poetry install` seems to build Rust crate in `debug` mode

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#13990]
We should build it in `release` mode for packages, at the very least.

I *think* wheels are correctly built in release mode

**Comment by erikjohnston** [comment]
I think we should just set `debug=True` in `build_rust.py` to force `poetry install` to always build in release mode. The default behaviour is to use `debug` for "inplace" builds (which is what poetry install does) and otherwise "release" (so poetry build would be fine).

**Comment by DMRobertson** [comment]
> think we should just set `debug=True` in `build_rust.py` to force `poetry install` to always build in release mode.

Err, should this be `debug=False`?

**Comment by erikjohnston** [comment]
Yes :facepalm:
