### ISSUE TITLE
Complement `TestPartialStateJoin/Outgoing_device_list_updates/Device_list_updates_reach_newly_joined_servers_in_partial_state_rooms` is flakey

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#14010]
https://github.com/matrix-org/synapse/actions/runs/3172224388/jobs/5166469780#step:4:2964

```
      client.go:604: [CSAPI] GET hs1/_matrix/client/v3/sync => 200 OK (125.434036ms)
      federation_room_join_partial_state_test.go:1674: @t24alice:hs1's partial state join to !0:host.docker.internal:38237 completed.
      client.go:604: [CSAPI] PUT hs1/_matrix/client/v3/devices/PBJFBBTZIN => 200 OK (18.65378ms)
      federation_room_join_partial_state_test.go:1677: @t24alice:hs1 sent device list update.
      federation_room_join_partial_state_test.go:1534: Complement server received m.device_list_update: {"device_display_name":"A new device name 3","device_id":"PBJFBBTZIN","org.matrix.opentracing_context":"{}","prev_id":[35],"stream_id":38,"user_id":"@t24alice:hs1"}
      federation_room_join_partial_state_test.go:1534: Complement server received m.device_list_update: {"device_display_name":"A new device name 3","device_id":"PBJFBBTZIN","org.matrix.opentracing_context":"{}","prev_id":[36],"stream_id":40,"user_id":"@t24alice:hs1"}
      federation_room_join_partial_state_test.go:1680: @charlie, @derek and @elsie received device list update.
      federation_room_join_partial_state_test.go:1534: Complement server received m.device_list_update: {"device_display_name":"A new device name 3","device_id":"PBJFBBTZIN","org.matrix.opentracing_context":"{}","prev_id":[38],"stream_id":39,"user_id":"@t24alice:hs1"}
  panic: test timed out after 1h0m0s
  
  goroutine 3428 [running]:
  testing.(*M).startAlarm.func1()
  	/opt/hostedtoolcache/go/1.17.13/x64/src/testing/testing.go:1788 +0x8e
  created by time.goFunc
  	/opt/hostedtoolcache/go/1.17.13/x64/src/time/sleep.go:180 +0x31
```

Synapse sent an extra device update, which the test wasn't interested in. I think putting the device update in a channel blocked, and then the test timed out after an hour.

**Comment by squahtx** [comment]
I suspect this has the same cause as https://github.com/matrix-org/synapse/issues/13977.
Because the test did not wait for the partial state join to complete fully, the final device list update happened before the join completed and was re-sent in case it was missed.

This ought to be fixed by https://github.com/matrix-org/complement/pull/487.

**Comment by squahtx** [comment]
This is a pretty annoying failure mode, since it causes complement to take a full hour to time out.

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3232704311/jobs/5293638472

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3329668215/jobs/5507175203 failed after 5 sec

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3337525454/jobs/5524055737

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3345575678/jobs/5541376258 is another 1-hour timeout.

We have a bunch of goroutine stack dumps [here](https://github.com/matrix-org/synapse/actions/runs/3345575678/jobs/5541376258#step:6:3097).

I struggled to understand it (grep for /runner) but it looked like we were blocked (deadlocked?) waiting to receive something over a channel.

**Comment by DMRobertson** [comment]
Kegan advises that we should
- buffer the channels, so that we don't block putting stuff into them
- then move on with our lives.

See conversation starting [here](https://matrix.to/#/!alCakyySsFIAVfZLDL:matrix.org/$Tk4PR9KGtfCJTFLFW0ecytvFYxf3C_36UW9C5F7fRzE?via=matrix.org&via=element.io&via=sw1v.org). I will PR this shortly.

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3602619515/jobs/6070924882

**Comment by DMRobertson** [comment]
(Might be just a generic form of failure with partial joins rather than something wrong with this test)

**Comment by erikjohnston** [comment]
That failure mode should be fixed by https://github.com/matrix-org/complement/pull/582

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/4279170219/jobs/7449734683 seen today
