### ISSUE TITLE
How to change the standard m.widget content.

### ISSUE THREAD

**Issue by bserver** [matrix-org/synapse#14035]
**Description:**
I want to edit the m.widget and have all new users automatically reflect the changes.

**Comment by squahtx** [comment]
Please use the [Synapse Admins Matrix room](https://matrix.to/#/#synapse:matrix.org) for support requests. If you're trying to develop a feature, please use the [Matrix Dev room](https://matrix.to/#/#matrix-dev:matrix.org) for help. Thanks!
