### ISSUE TITLE
Incorrect SQL query construction in `_construct_room_type_where_clause`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14051]
To reproduce:

```
curl -H "Authorization: Bearer $TOKEN" -X POST https://matrix-client.matrix.org/_matrix/client/v3/publicRooms -d '{"filter": {"generic_search_term": "debian-ou", "room_types": [null]}, "third_party_instance_id": "irc-w3c|w3" }'
```

which yields

```
{"errcode":"M_UNKNOWN","error":"Internal server error"}
```

Internal users: [example Sentry traceback](https://sentry.tools.element.io/organizations/element/issues/18958/?project=2&query=is%3Aunresolved&sort=freq&statsPeriod=24h).

I believe the cause is faulty logic in:

https://github.com/matrix-org/synapse/blob/606b2d9009f0a3e70056dec7e9cdccd0c0d7afed/synapse/storage/databases/main/room.py#L208-L224

Suggest:
- unit test to reproduce this
- something like the following:

```python
# within the else block:
conditions = []
args = []
specific_room_types = [value for value in room_types if value is not None]
if None in room_types:
    conditions.append("room_type IS NULL")
if specific_room_types:
    condition, condition_args =make_in_list_sql_clause(..., specific_room_types)
    conditions.append(clause)
    args.append(condition_args)

return f"({ ' OR '.join(conditions) })", args
```

Likely an oversight in #13031.

**Comment by clokep** [comment]
There's a couple of things going wrong here:

* The handling of `[None]` was not quite correct (as you'd end up with the wrong number of arguments).
* The ordering of arguments when providing both a network tuple and room type field was incorrect.
