### ISSUE TITLE
URL preview code causes an internal error when previewing pages with structured `og:image`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14061]
Noticed in [this sentry error](https://sentry.tools.element.io/organizations/element/issues/198/?project=2&query=is%3Aunresolved&sort=freq&statsPeriod=14d).

We try to call `urlparse` here

https://github.com/matrix-org/synapse/blob/303b40b988bc372a81fc1a3cf62d3f5d074970ff/synapse/rest/media/v1/preview_url_resource.py#L631-L653

where image_url is a dictionary

```json
{"href": "https://example.com/cats.jpg"}
```

I don't know how the OG metadata is represented in json, but looking at https://ogp.me/#structured it seems that `og:image` is either a URL string or a struct which may contain a `url` key. Synapse doesn't account for the latter case.

Curiously, the example in the sentry error uses a `href` key which seems bogus, but maybe this is common in the wild.

**Comment by clokep** [comment]
This case is a little more complicated, the data is coming from an oEmbed URL, which returns something like:

```json
{
  "success": true,
  "type": "rich",
  "version": "1.0",
  "provider_name": "FooBar",
  "provider_url": "https://foobar.com",
  "title": "FooBar Blah",
  "author_name": "FooBar",
  "author_url": "https://blah.foobar.com/asdf",
  "height": 600,
  "width": 900,
  "thumbnail_width": 300,
  "thumbnail_height": 200,
  "thumbnail_url": {
    "href": "https://images.foobar.com/images/asdf"
  },
  "html": "<iframe src=\"https://blah.foobar.com/asdf?embed=oembed\" style=\"border: 0; width: 900px; height: 600px;\" allowfullscreen allow=\"autoplay; encrypted-media\"></iframe>"
}
```

I think having an object for `thumbnail_url` is invalid, but will need to rewrite the oEmbed spec: https://oembed.com/

**Comment by clokep** [comment]
At the very least it sounds like the oEmbed code needs some additional validation near:

https://github.com/matrix-org/synapse/blob/15ffc4143c36593bc3d899fad7fb5db00f4d95ea/synapse/rest/media/v1/oembed.py#L170-L172

It might be worth checking briefly if other sites do this? Otherwise I'd be inclined to just ignore the field as 'wrong type'.
