### ISSUE TITLE
Can not post to or modify room

### ISSUE THREAD

**Issue by dvdgsng** [matrix-org/synapse#14071]
### Description

I've one room that "stopped working" out of a sudden. It's not possible to post messages to the room or change any of the settings.

Things I've tried:
* post messages
* change the topic
* change the room picture
* upgrade the room to a new version
* enable e2e encryption
* invite some new users
* add a new published address
* add widgets
* add bots

Every single action failed with **500** and the same error message:

```
errcode: "M_UNKNOWN"
error: "Internal server error"
```

More details:
* Every member in this room is using Element-Web or Element-Android. There are no errors or notifications shown in the UI. The channel It just looks as usual.
* Everyone else in that room is experiencing the same behavior.
* All other rooms & conversations work just fine.

### Steps to reproduce

I wish I could provide any :( 

### Homeserver

matrix.org

### Synapse Version

1.69.0rc1 (matrix-org-hotfixes,dedd4cd061)

### Platform

Don't know, not my HS.

### Relevant log output

```shell
Don't have any.
```

### Anything else that would be useful to know?

Exporting the room worked.

**Comment by DMRobertson** [comment]
Can you share the room ID?

**Comment by dvdgsng** [comment]
Sure! `!MDGXKwTbBmhItGVvGs:matrix.org`

**Comment by dvdgsng** [comment]
Oh wow, that's great news! Subscribed to the other issue and will verify things work again once the fix is deployed.

Thank you!

**Comment by DMRobertson** [comment]
@dvdgsng this should now be fixed on Matrix.org. Is your room now in a working state?

**Comment by dvdgsng** [comment]
Yes! Works. Thank you!
