### ISSUE TITLE
`filter_events_for_client` is time-consuming and expensive

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#14108]
`filter_events_for_client` is time-consuming and expensive.

From this `/messages` request ([full trace](https://gist.github.com/MadLittleMods/c3ace249ce2aec77cb78d19a4f85a776)), it takes 7.83s for 500 events and is one of the biggest time saves left after other `/messages` optimizations we've already made. Most of time is just spent in the database getting the state out.

<img width="1201" alt="/message trace in Jaeger show how slow `filter_events_for_client` is" src="https://user-images.githubusercontent.com/558581/194672746-34a8fd74-e6fe-4108-bf22-cb69a755c5af.png">

---

Related to `filter_events_for_server` being expensive, https://github.com/matrix-org/synapse/issues/3526

**Comment by erikjohnston** [comment]
Interesting. What sort of room is this? For large public rooms (and smaller rooms) it should be really quite fast

**Comment by MadLittleMods** [comment]
@erikjohnston The beeg one `#matrix:matrix.org` 🗿 (the 200k state events probably isn't helping)

**Comment by erikjohnston** [comment]
Huh, but it should only be pulling out a couple of pieces of state (the history visibility mainly). Which should not take that long :/
