### ISSUE TITLE
Add Mastodon OAuth documentation to Synapse OpenID page

### ISSUE THREAD

**Issue by jlestr** [matrix-org/synapse#14147]
**Description:**

I was wondering if it's possible to use [Mastodon OAuth API](https://docs.joinmastodon.org/spec/oauth/) as a SSO login method for Synapse.

If someone has tested it, I'd appreciate if they could document it on the [OpenID doc page](https://github.com/matrix-org/synapse/blob/develop/docs/openid.md) with basic setup syntax. I'd do it myself but I just don't have enough expertise with single sign-on, scopes or the OAuth API in general to write a PR about it. Even so, the API seems to be pretty simple as far as I can tell.

**Comment by clokep** [comment]
It is likely worth asking in https://matrix.to/#/#synapse:matrix.org if anyone has gotten this to work!
