### ISSUE TITLE
Synapse returns legacy field name `knock_state_events` when knocking over federation for backwards-compatibility

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#14151]
Context: https://github.com/matrix-org/synapse/issues/14088

We should remove this field when enough of the federation has upgraded. Impact on older Synapses once this field is removed (from the linked issue):

> If we didn't implement backwards-compatibility, a user on an old Synapse (or knocking on a new Synapse through an old Synapse) would (assuming knocking was implemented in any clients) see only a room ID in their "pending knocks" list, instead of a room name/avatar/any other metadata.

**Comment by anoadragon453** [comment]
Implemented at:

https://github.com/matrix-org/synapse/blob/e4e55f8eef98ab923e7aca2980f7c1bebb3ed34e/synapse/federation/federation_server.py#L829-L833

https://github.com/matrix-org/synapse/blob/e4e55f8eef98ab923e7aca2980f7c1bebb3ed34e/synapse/handlers/federation.py#L792-L795

**Comment by clokep** [comment]
We feel this is ready to implement as it has been longer enough that the proper spec-compliant behavior has been implemented.
