### ISSUE TITLE
Test against PostgreSQL 15

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#14170]
https://www.postgresql.org/docs/15/release-15.html

We should update our CI to test against latest Postgres, which is now 15 instead of 14.

**Comment by clokep** [comment]
I think the steps to do this are:

1. Update the `tests.yml` file and replace `14` with `15`.

**Comment by realtyem** [comment]
Hold off for a bit, newest thing up there is the RC2 version

https://hub.docker.com/_/postgres

**Comment by realtyem** [comment]
Ready now 😄

**Comment by squahtx** [comment]
> I think the steps to do this are:
> 
> 1. Update the `tests.yml` file and replace `14` with `15`.

2. Update `.ci/scripts/calculate_jobs.py` and replace `14` with `15`.
