### ISSUE TITLE
Rooms added via /state/m.space.child/ API not listed in hierarchy 

### ISSUE THREAD

**Issue by Bruno17** [matrix-org/synapse#14196]
### Description

I'm trying to add Rooms to Spaces via the /state/m.space.child/ API, but they are not listed with the /hierarchy Endpoint.
When a Room is added to a Space via the Element Desktop App or the Element web App, which runs the exact same API request, the Room is listed like expected.

is there needed an additional step to get the room added to a space get listed in the hierarchy?
I can't see anything different watching the network tab in the browser console.

I'm calling the API serverside via PHP CURL, but I think, that shouldn't matter

### Steps to reproduce

- run a PUT request like https://matrix.org/_matrix/client/r0/rooms/%21#####%3Amatrix.org/state/m.space.child/%21#####%3Amatrix.org?access_token=##### with params {via: ["matrix.org"], suggested: false}
- try to get the hierarchy with https://matrix.org/_matrix/client/v1/rooms/%#####%3Amatrix.org/hierarchy?access_token=#####&suggested_only=false&limit=20
- the Room is not listed in the hierarchy, only rooms which are added via the Element web or Desktop App
- the Room is listed in the roomlist of the space in the web or Desktop App, but not in the Space overview or in the Space on the Android App
- I can remove the room via the same API request and empty params, no problem. 
- viewing the Space - messages of my API request and the request by the APP, they are exatly the same and looking like that in both cases (stripped):
age : 55962808
content  : {suggested: false, via: ["matrix.org"]}
via : ["matrix.org"]
event_id : #####
origin_server_ts : 1665850613776
room_id : "!#####:matrix.org"
sender : "@#####:matrix.org"
state_key : "!#####:matrix.org"
type : "m.space.child"
user_id : "@#####:matrix.org" 

### Homeserver

matrix.org

### Synapse Version

{"server":{"name":"Synapse","version":"1.69.0rc3 (b=matrix-org-hotfixes,aca3a117a9)"}}

### Platform

matrix.org

### Relevant log output

```shell
see reproduce steps
```

**Comment by DMRobertson** [comment]
```
PUT matrix.org/_matrix/client/r0/rooms/%21#####%3Amatrix.org/state/m.space.child/%21#####%3Amatrix.org?access_token=#####
with params {via: ["matrix.org"], suggested: false}
```

A few things to check here.

1. The URL format is `/rooms/<FIRST ROOM ID>/state/m.space.child/<SECOND ROOM ID>`. The first ID should be the space's room ID; the second should be the child's room ID. Can you confirm they are the correct way round in your request? (We cannot tell from your description as their redacted forms are identical.)
2. Does the user making the request have permission to set that piece of state in the space-room?
3. What response do you get to your PUT request? I.e. what is the HTTP status code and response body?

**Comment by Bruno17** [comment]
I checked everything again.
I can confirm: 
- the space_id and room_id are in the correct order.
- The logged - in user has the needed permission - it is the same user, I'm logged in with element, where it works.
- I get a response with status : 200 and a body with 
data : {event_id: "$UqdjnrWcY0JFgTezyPSS4Vdqq7Q8UqG36iiREi6REr4"}
params : {via: ["matrix.org"], suggested: false}
- the via is valid, it is matrix.org

Like told before, it works adding rooms to that same space with Element and reading the messages of the space via API, I can see the m.space.child messages are **exactly** the same, when done via CURL or done via Element, but only listed when done with Element.
I can also see the room listed under the room-list in that space on the Element desktop App, but not in the hirarchy, not in the spaces overview on Element desktop and not in room-list on the Android App.

I know, that sounds strange and I have no idea, what could be the reason for the different behaviour, when the the exact same API request is send by Element and by CURL with the same response in both cases.

**Comment by Bruno17** [comment]
> It also means that
> 
> >when the the exact same API request is send by Element and by CURL
> 
> was not correct.

yeah. but this wasn't visible anywhere. The response and also the room - messages/states were exactly the same.

**Comment by clokep** [comment]
> The response and also the room - messages/states were exactly the same.

I believe the event content must have been different in *some* way for it to be ignored.

Using https://www.phplayground.com/ I did the following:

```php
<?php
$params = array(
  "via" => array("matrix.org"),
  "suggested" => false
);

print(json_encode($params, JSON_FORCE_OBJECT))
?>
```

Which resulted in:

```json
{"via":{"0":"matrix.org"},"suggested":false}
```

So this is definitely different and wrong. Removing the `JSON_FORCE_OBJECT` returns the correct value:

```json
{"via":["matrix.org"],"suggested":false}
```
