### ISSUE TITLE
Deal with Github Actions deprecation warnings

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14203]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

>  Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

See e.g. https://github.com/matrix-org/synapse/actions/runs/3258600088 (and likely other workflows too)

Node.js 12 actions, `save-state` and `set-output` are all "deprecated and will be disabled soon".

PRs:
- #14216
- https://github.com/matrix-org/setup-python-poetry/pull/11
- https://github.com/matrix-org/backend-meta/pull/13 and the follow-up https://github.com/matrix-org/backend-meta/commit/1a8479c9088301133b58cc77421d5e8df0e0214e
- #14224
- #14249
  - deal with osx 10.15 deprecation, see https://github.com/actions/runner-images/issues/5583 and https://endoflife.date/macos
- #14276
- #14275
- https://github.com/matrix-org/synapse-s3-storage-provider/pull/83
- #14313
- #14351
- #14607
- https://github.com/matrix-org/sytest/pull/1347
- https://github.com/matrix-org/synapse-s3-storage-provider/pull/95 (integration test workflow needs fixing though)
- https://github.com/AustinScola/mypy-cache-github-action/issues/277

**Comment by DMRobertson** [comment]
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ . No deadline as of yet.

**Comment by DMRobertson** [comment]
https://github.com/Swatinem/rust-cache/releases/tag/v2.0.1 helps with some of this.

**Comment by DMRobertson** [comment]
Will need a tweak to https://github.com/AustinScola/mypy-cache-github-action too --- not sure how actively that repo is maintained.

**Comment by erikjohnston** [comment]
There is also the removal of old macos runners that we use to build macos wheels. There are currently brownouts so we should bump this soon, otherwise it breaks building releases.
