### ISSUE TITLE
Clicking on link in password reset e-mail displays 404 nginx error in browser

### ISSUE THREAD

**Issue by erikgieseler** [matrix-org/synapse#14204]
### Description

If we start a password reset via Element and then click on the link in the password reset confirmation email, then a 404 Nginx error is displayed in the browser window.

The link in the email is as follows:
https://chat.slawinski.de/_synapse/client/password_reset/email/submit_token?token=X&client_secret=X&sid=X

The error did not exist in previous Synapse versions.
Since which version the error exists I can not say.

### Steps to reproduce

- Request passwort reset in Element.
- Click on link in reset confirmation email

### Homeserver

chat.slawinski.de

### Synapse Version

1.68

### Installation Method

Debian packages from packages.matrix.org

### Platform

Server: Ubuntu 20.04 LTS
Client: macOS, iOS and Android

### Relevant log output

```shell
Will attach later if needed
```

**Comment by DMRobertson** [comment]
Is the 404 coming from nginx, or it it coming from Synapse and being relayed by nginx?

Can you see any requests for `/_synapse/client` in Synapse's logs?

**Comment by DMRobertson** [comment]
Would guess this is an effect of https://github.com/matrix-org/synapse/pull/13596. Do you have an `email` section in your homeserver config?

**Comment by DMRobertson** [comment]
See also https://github.com/matrix-org/synapse/blob/release-v1.66/docs/upgrade.md#upgrading-to-v1660

**Comment by erikgieseler** [comment]
I already have a working email area in the homeserver configuration, which also works correctly. Otherwise I would not have received the email confirming the password change. 

I think the 404 comes from synapse, which is forwarded by nginx. I'll check the logs tomorrow for "/_synapse/client" entries just to be sure. I'll get back to you tomorrow.

**Comment by erikgieseler** [comment]
I cant see any requests for /_synapse/client in the homeserver.log when i click on the link in the email.
Just the normal /_matrix/client stuff.

**Comment by erikgieseler** [comment]
I found the problem !
In my nginx config "/_synapse/client" was missing in the location section.
I just had "/_matrix" in there. 
Changing the line to "... location ~ ^(/_matrix|/_synapse/client) { ..." was the solution.
See: https://matrix-org.github.io/synapse/latest/reverse_proxy.html
