### ISSUE TITLE
Synapse allows users to create `m.space.child` state events where `via` is a JSON object instead of an array

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14218]
In this situation the state event is silently ignored, causing confusion as in #14196.

**Comment by clokep** [comment]
I think this just fits into the bucket of "we don't do event validation very well"?

See #8445.

**Comment by DMRobertson** [comment]
That's fair. Let's defer to that one then.

**Comment by clokep** [comment]
(Not that I'm against adding this validation to the C-S API, we should...)
