### ISSUE TITLE
Complement `TestKnocking/Users_in_the_room_see_a_user's_membership_update_when_they_knock` is flakey

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14226]
Assuming another lack of read-after-write consistency.

https://github.com/matrix-org/synapse/actions/runs/3273719504/jobs/5386594348

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3359263013/jobs/5567103398

**Comment by squahtx** [comment]
https://github.com/matrix-org/synapse/actions/runs/3392160372/jobs/5638031366

**Comment by babolivier** [comment]
https://github.com/matrix-org/synapse/actions/runs/3675951392/jobs/6217364032

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/4086737084/jobs/7046439712

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/complement/actions/runs/4133212871/jobs/7142843471
