### ISSUE TITLE
The `server_name` parameter of the "Delete media by date and size" is unused and confusing

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#14236]
The ["Delete media by date and size"](https://matrix-org.github.io/synapse/latest/admin_api/media_admin_api.html#delete-local-media-by-date-or-size) admin API takes a `server_name` parameter. This makes it look like we only delete media that were uploaded to the local media repository. However, we only use it to check that it matches the local server's name:

https://github.com/matrix-org/synapse/blob/3dd175b628bab5638165f20de9eade36a4e88147/synapse/rest/admin/media.py#L318-L319

We then proceed to call `delete_old_local_media`, which, confusingly, deletes local media _and_ local copies of remote media. So remote media is deleted even when the `server_name` parameter is set to the local server.

**Comment by dklimpel** [comment]
Dup
* #9284

**Comment by clokep** [comment]
duplicates #9284.
