### ISSUE TITLE
/threads includes thread roots that have no thread attached to it anymore

### ISSUE THREAD

**Issue by justjanne** [matrix-org/synapse#14241]
## Description

/threads includes thread roots that have no thread attached to it anymore due to redactions.

## Steps to reproduce

1. create a thread
2. write replies
3. redact all replies

## Expected Behavior

The /threads endpoint stops including this thread in its response once all responses have been redacted

## Actual Behavior

The /threads endpoint still includes the now empty threads 

## Additional Information

The homeserver correctly removed the bundled relationship from the threads, yet it still includes the roots in the /threads response.

This issue is likely related to the [MSC3856 implementation](https://github.com/matrix-org/synapse/commit/3bbe532abb7bfc41467597731ac1a18c0331f539)

**Comment by clokep** [comment]
In #13394 we changed from looking at the "live" event information to a separate table, I suspect we're not tracking event redactions properly in that table. Things to double check:

* Redacting the "last" event in a thread should replace itself with the (now) last event.
* If there is no events left, the thread should be removed.

**Comment by clokep** [comment]
This will be fixed in 1.70.0rc2.
