### ISSUE TITLE
Keyword notification does not increment highlight_count

### ISSUE THREAD

**Issue by gsouquet** [matrix-org/synapse#14261]
### Description

`highlight_count` is not incremented when receiving a message that contains one of my keywords.

### Steps to reproduce

- Add `yolo` as a keyword
- Login to account A, and send a text message saying `yolo` in an unencrypted room 
- Login to account B

I would expect to see the following in my sync response

```jsonc
unread_notifications: {notification_count: 1, highlight_count: 1}
```

But I did receive

```jsonc
unread_notifications: {notification_count: 1, highlight_count: 0}
```

### Homeserver

threads-dev.lab.element.dev

### Synapse Version

{"server_version":"1.69.0rc4","python_version":"3.9.15"}

### Platform

ROSA

### Relevant log output

```shell
?
```

**Comment by clokep** [comment]
We investigated this a bit and this is (likely) a false positive due to either:

1. A client bug not properly highlighting the message.
2. The user's account not having keywords set to highlight.
