### ISSUE TITLE
Admin API: List Accounts always returning `next_token`

### ISSUE THREAD

**Issue by johannescpk** [matrix-org/synapse#14302]
### Description

Contrary to what the [docs](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#list-accounts) say, the "List Accounts" Admin API endpoint will always return `next_token`.

Affected code seems to be

https://github.com/matrix-org/synapse/blob/86b7d9b8862775353951322d604624e37d428a55/synapse/rest/admin/users.py#L143-L146

### Steps to reproduce

- Have more than 100 users
- Fetch users with query `next_token=100`
- Watch the result contain `next_token: 100`

### Homeserver

local dev

### Synapse Version

v1.70.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Debian

### Relevant log output

```shell
synapse.access.http.8008 - 450 - INFO - GET-13505- 10.250.250.5 - 8008 - {<snip>} Processed request: 0.002sec/0.001sec (0.001sec, 0.000sec                                                                                                                                                     ) (0.000sec/0.001sec/2) 27206B 200 "GET /_synapse/admin/v2/users?order_by=admin&dir=b&next_token=100 HTTP/1.1" "-" [0 dbevts]
```

**Comment by reivilibre** [comment]
> Fetch users with query next_token=100

Just checking: this is meant to be `from=100` — is that the cause of problem you're running into here or is it just an unfortunate mistake when writing the issue?

**Comment by johannescpk** [comment]
Well, that explains it. :facepalm:  Thanks for the fast response.
