### ISSUE TITLE
Mautrix Bridges are not bridging messages since upgrading to version 1.70.0 

### ISSUE THREAD

**Issue by NicolasDerumigny** [matrix-org/synapse#14308]
### Description

Since upgrading to version 1.70.0, mautrix-instagram, mautrix-discord, mautrix-facebook and mautrix-telegram are not bridging mesaging from Matrix to the requested service. Any communication with the bot is also impossible (`help`, `ping`, etc). Maubot is unaffected.

### Steps to reproduce

- install and configure a mautrix-based bridge (instagram, facebook, discord or telegram) on 1.69
- upgrade to 1.70
- send a message from matrix in a bridged channel

### Homeserver

Privately hosted homeserver

### Synapse Version

1.70.0 (Python 3.9.2)

### Installation Method

Synapse is installed with `pip install --upgrade matrix-synapse[all]`, which compiles the project from sources.

### Platform

Bridges are manually installed from their git repo.

Host server is a Raspberry Pi 3 running Debian 11.5.

### Relevant log output

```shell
No logs seems to point to an error.
```

### Anything else that would be useful to know?

Reverting to synapse 1.69 fixes the issue.

**Comment by DMRobertson** [comment]
Likely https://github.com/matrix-org/synapse/pull/14301 --- which should land in a patch release within the next day or two.

**Comment by DMRobertson** [comment]
> Likely fixed by #14301 --- which should land in a patch release within the next day or two.

Additionally: if it is the bug which is fixed by that PR

- every request Synapse makes to the bridges should receive a 403 from the bridge
- downgrading to an older version of the bridge may work with Synapse 1.70.0.

**Comment by NicolasDerumigny** [comment]
Thanks, I'll wait for the patch to land and will update on this issue!

**Comment by voice06** [comment]
Can confirm after upgrading to 1.70.1 appservice-irc is now working again.

**Comment by clokep** [comment]
Based on the thumbs up from @NicolasDerumigny I'm going to assume we can close this!

**Comment by NicolasDerumigny** [comment]
I was updating when I saw the comment. Can confirm it is working fine on 1.70.1, thanks!
