### ISSUE TITLE
Remove Matrix URL in search for other people and rooms

### ISSUE THREAD

**Issue by RoninAngle1** [matrix-org/synapse#14335]
Hi,
 
Is there a way to remove the domain name in search for a user?

When I search for a user in Element, I currently have to search for `@username:<matrix domain>` but would like to just use `@username`.

I know it's possible to search for users on the local server but there is a need to also find users on remote federated servers with other Matrix domains.

Thanks

**Comment by RoninAngle1** [comment]
Hi again
I forgot to say is there a way to auto fill it except removing it too?

**Comment by MadLittleMods** [comment]
@RoninAngle1 Your request was a little hard to understand. I've updated the description but there are a few assumptions so please make sure it's still accurate.

Fundamentally, you can already search for `@username` to find relevant users locally and if you have the [`user_directory.search_all_users`](https://github.com/matrix-org/synapse/blob/develop/docs/usage/configuration/config_documentation.md#user_directory) config set, it will also find any user that your server shares a room in common with.

If you want to prefer results from your local server, can enable the [`user_directory.prefer_local_users`](https://github.com/matrix-org/synapse/blob/develop/docs/usage/configuration/config_documentation.md#user_directory) config option.

If you want to prevent people from finding people that are not known already, you could set [`limit_profile_requests_to_users_who_share_rooms`](https://github.com/matrix-org/synapse/blob/develop/docs/usage/configuration/config_documentation.md#limit_profile_requests_to_users_who_share_rooms). There is also https://github.com/vector-im/element-web/issues/22102

If you're after hiding the domain part of the MXID, that would be something to request in the Element tracker, https://github.com/vector-im/element-web/issues
