### ISSUE TITLE
No database config provided when installing

### ISSUE THREAD

**Issue by phxgz** [matrix-org/synapse#14341]
Description
Dear Synapse,
fresh deployment with PostgreSQL,Failed to restart Synapse service.I have reinstalled many times but same problem.

root@lsjz:~# sudo systemctl restart matrix-synapse
Job for matrix-synapse.service failed because the control process exited with error code.
See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.
root@lsjz:~# journalctl -xe
Nov 01 13:50:37 lsjz.server matrix-synapse[87457]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Nov 01 13:50:37 lsjz.server matrix-synapse[87457]: ------------------------------------------------------------>
Nov 01 13:50:37 lsjz.server matrix-synapse[87457]: Error in configuration:
Nov 01 13:50:37 lsjz.server matrix-synapse[87457]:   No database config provided
Nov 01 13:50:37 lsjz.server PackageKit[83369]: daemon quit
Nov 01 13:50:37 lsjz.server systemd[1]: packagekit.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit packagekit.service has successfully entered the 'dead' state.
Nov 01 13:50:37 lsjz.server systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAIL>
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit matrix-synapse.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
Nov 01 13:50:37 lsjz.server systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit matrix-synapse.service has entered the 'failed' state with result 'exit-code'.
Nov 01 13:50:37 lsjz.server systemd[1]: Failed to start Synapse Matrix homeserver.
-- Subject: A start job for unit matrix-synapse.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit matrix-synapse.service has finished with a failure.
--
-- The job identifier is 7348 and the job result is failed.
Nov 01 13:50:40 lsjz.server systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 26.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit matrix-synapse.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Nov 01 13:50:40 lsjz.server systemd[1]: Stopped Synapse Matrix homeserver.
-- Subject: A stop job for unit matrix-synapse.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A stop job for unit matrix-synapse.service has finished.
--
-- The job identifier is 7435 and the job result is done.
Nov 01 13:50:41 lsjz.server systemd[1]: Starting Synapse Matrix homeserver...
-- Subject: A start job for unit matrix-synapse.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit matrix-synapse.service has begun execution.
--
-- The job identifier is 7435.

root@lsjz:~# systemctl status matrix-synapse.service
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: activating (start-pre) since Tue 2022-11-01 13:52:34 UTC; 724ms ago
Cntrl PID: 88478 (python)
      Tasks: 1 (limit: 1669)
     Memory: 32.2M
     CGroup: /system.slice/matrix-synapse.service
             └─88478 /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-s>

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

Additionally: please use three backticks to enclose big blocks of log output or source code, e.g. 

`````
```
blah
example
foo
```
`````

rather than pasting it directly into an issue.

**Comment by DMRobertson** [comment]
Also additionally: for anyone to have the slightest change of being able to help you, you need to provide logs from Synapse.

**Comment by phxgz** [comment]
ok thx
