### ISSUE TITLE
QR code login function does not appear in the client.

### ISSUE THREAD

**Issue by YamatoRyou** [matrix-org/synapse#14345]
### Description

Synapse has been upgraded to 1.70.1, Element has been upgraded to 1.11.14 RC1.
"Allow a QR code to be shown in session manager to sign in another device" is enabled in the lab.
But the QR code related functions are still not shown.
![{C15CA667-78B7-5949-27F3-0A3F62211B78}](https://user-images.githubusercontent.com/48104960/199299830-e9880a61-80e4-44cc-aa6a-9a16e2796159.png)

### Steps to reproduce

n/a

### Homeserver

Synapse 1.70.1

### Synapse Version

{"server":{"name":"Synapse","version":"1.70.1"}}

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Synology DiskStation Manager 6.2.3.25426 (Linux Kernel 3.10.105 x64)

### Relevant log output

```shell
n/a
```

### Anything else that would be useful to know?

**I posted the same question on #synapse:matrix.org on 10/21/2022, but no reply until today.**
https://matrix.to/#/!ehXvUhWNASUkSLvAGP:matrix.org/$acWryrcahb2x8yuJLpN_GvpiKgXAtE_XJYDfrUNt83U

**Comment by DMRobertson** [comment]
According to the Element-web authors, your homeserver needs to have support for the experimental features MSC3882 and MSC3886 for this to work.  (This is what is meant by "requires compatible homeserver" in the flag description"; it is unfortunate that the client does not check to see if your homeserver is compatible.)

These features are highly experimental in Synapse and need to be opted into.

```
experimental_features:
    msc3882_enabled: true
    msc3886_endpoint: path/to/endpoint
```

I don't know the details of how MSC3886 works or is configured. I suggest you start reading the MSC and in particular here https://pypi.org/project/matrix-http-rendezvous-synapse/.

Be advised: as long as these features are marked as experimental, we (Synapse) make absolutely no stability guarantees about them.

**Comment by hughns** [comment]
After installing the [matrix-http-rendezvous-synapse](https://pypi.org/project/matrix-http-rendezvous-synapse/) module (+ running with `SYNAPSE_ASYNC_IO_REACTOR=1`) a more complete config is:

```yaml
experimental_features:
  msc3882_enabled: true
  # if you want to allow m.login.token issuance without requiring UIA then uncomment this:
  # msc3882_ui_auth: false
  msc3886_endpoint: /_synapse/client/org.matrix.msc3886/rendezvous

modules:
 - module: synapse_rendezvous.SynapseRendezvousModule
   Config: 
     prefix: /_synapse/client/org.matrix.msc3886/rendezvous


listeners:
  - type: http
    experimental_cors_msc3886: True
    # ... rest of the HTTP listener config
```

**Comment by YamatoRyou** [comment]
> After installing the [matrix-http-rendezvous-synapse](https://pypi.org/project/matrix-http-rendezvous-synapse/) module (+ running with `SYNAPSE_ASYNC_IO_REACTOR=1`) a more complete config is:
> 
> ```yaml
> experimental_features:
>   msc3882_enabled: true
>   # if you want to allow m.login.token issuance without requiring UIA then uncomment this:
>   # msc3882_ui_auth: false
>   msc3886_endpoint: /_synapse/client/org.matrix.msc3886/rendezvous
> 
> modules:
>  - module: synapse_rendezvous.SynapseRendezvousModule
>    Config: 
>      prefix: /_synapse/client/org.matrix.msc3886/rendezvous
> 
> 
> listeners:
>   - type: http
>     experimental_cors_msc3886: True
>     # ... rest of the HTTP listener config
> ```

Wait a minute. Here's what I did:

1. Enter the Synapse (Docker container) shell and execute the following command:
`pip install matrix-http-rendezvous-synapse`
2. Start editing `homeserver.yaml` as you gave:
3. `SYNAPSE_ASYNC_IO_REACTOR` I guess it is an environment variable, I configured it as the environment variable of the Docker container.
4. Restart Synapse (Docker container).

Doing this I found that it did work, I would like to archive my steps here.
