### ISSUE TITLE
Full-text-search in Synapse 1.71.0rc1 may be prohibitively expensive (DB IO)

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14354]
From Matrix.org's monitoring:

![image](https://user-images.githubusercontent.com/8614563/199560945-c78da582-8e11-4795-bd29-7d9dc3681b56.png)

In the "Toast table blocks read from disk/buffer" and "Toast index block read from buffer" graphs, there are intermittent blue spikes corresponding to the `event_search` table.

Correlated: peaks in "total txn time" due to `search_rooms`

![image](https://user-images.githubusercontent.com/8614563/199561769-c4afa67a-2060-495a-8df3-159398038027.png)

And federation send PDU lag:

![image](https://user-images.githubusercontent.com/8614563/199562044-b2e52e4b-9f9f-43ad-98f9-f4305caebb03.png)

and event send time:
![image](https://user-images.githubusercontent.com/8614563/199562230-286f4aa0-e37d-497c-aa1b-5d2f20c60ae7.png)

(Above graphs only showing the main process).

The event persister also saw pain at similar times:

![image](https://user-images.githubusercontent.com/8614563/199562486-ebfd9469-e5bb-4296-a3a4-70d15e491c5c.png)

It's a little tricky to interpret these, because the m.org database was updated this morning (2nd Nov 9.30 UTC) and there was some expensive background processing by postgres afterwards. (All times UTC in the graphs.)

Our suspicion is that the changes in #11635 are to blame. I reverted it, #13410 and #14311 on the hotfixes branch (https://github.com/matrix-org/synapse/commit/37307a5ccef8e21313f0631d414806ea551e6a73) and deployed to matrix.org. We haven't seen the event persisters flare up since then... but it's not completely clear that the changed mentioned were the cause.

I think we should (regrettably) back out the changes on the release branch too, before a final 1.71.0 release.

**Comment by DMRobertson** [comment]
I should have added: in the slow query logs, we saw inserts into event search tables that took >=10 seconds.

```
E.g. 2022-11-02 00:40:57.355 UTC [matrix event_persister1] LOG:  duration: 10687.079 ms  statement: 
                    INSERT INTO event_search
```

**Comment by H-Shay** [comment]
Are the inserts slow due to poor indexing, or what else would cause such a slow insert?

**Comment by DMRobertson** [comment]
Consensus: go ahead with this but keep an eye out for performance.
