### ISSUE TITLE
Howto split database and tables?

### ISSUE THREAD

**Issue by Narsiss** [matrix-org/synapse#14362]
We found event_push_action eat most of CPU and RAM in our database(pg). So we want to make a split for database and found this solution in doc:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/5062214/199868565-6f957a5b-eb96-4ee1-b62c-88b709b0929b.png">
But it seems only work for "state":
```
"state": Database that relates to state groups will be stored in this database.

Specifically, that means the following tables:

state_groups
state_group_edges
state_groups_state
And the following sequences:

state_groups_seq_id
"main": All other database tables and sequences.
```

Is there a solution that I can split event_push_action out for database?

**Comment by squahtx** [comment]
> Is there a solution that I can split event_push_action out for database?

There isn't a way to do this unfortunately. Synapse only supports splitting out state, as you've discovered.

A `VACUUM ANALYZE` on the tables of interest may help, if that hasn't been tried yet.
