### ISSUE TITLE
YouTube URL preview breaks links

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/synapse#14366]
### Description

urls in video descriptions get messed up with line breaks. here is a maubot subscribed to some youtube channel rss feed:
![image](https://user-images.githubusercontent.com/2803622/199989019-03f88ba5-ae06-4c94-b6e1-1e5ff76bfa49.png)

yt description:
![image](https://user-images.githubusercontent.com/2803622/199989261-fc0789ab-14c0-4ffc-99ed-f6b8e48eb9d7.png)

### Steps to reproduce

- generate URL preview, e.g. https://www.youtube.com/watch?v=wVEtZTpw9z8

### Homeserver

selfhosted

### Synapse Version

{"server_version":"1.70.1","python_version":"3.9.15"}

### Installation Method

Other (please mention below)

### Platform

matrix-docker-ansible-deploy

### Relevant log output

```shell
n/a
```

**Comment by squahtx** [comment]
The broken URL is actually coming from YouTube.

On https://www.youtube.com/watch?v=wVEtZTpw9z8, we have:
```
<meta name="title" content="O.B.F - LAVA (Full Album)">
<meta name="description" content="&#39;LAVA&#39; OUT NOW https://ampl.ink/lava 🌋🌋🌋BUY THE VINYL https://obf-dubquake-records.bandcamp.com/album/lavaEXPERIENCE THE O.B.F SOUND SYSTEM ON TOUR : http...">
```
Note that lack of space between the URL and the next line of the description.

**Comment by clokep** [comment]
I don't think there's anything we can do here, sounds like a YouTube bug to me?
