### ISSUE TITLE
Some, not all, users of a homeserver cannot see or communicate with all matrix.org users

### ISSUE THREAD

**Issue by ehfd** [matrix-org/synapse#14389]
### Description

We have a presumed issue with federation in Synapse where a few certain (at least five) users, who created an account from a homeserver, in the channel of this homeserver, being unable to see all users from the matrix.org homeserver (no exceptions), and the opposite also happens, where all users from the matrix.org homeservers cannot see the messages of these few users.

This has been tested in multiple environments, Android/iOS/Windows/Mac, etc. by multiple people. Thus this is NOT a client issue.

Most users who created an account from this homeserver can see matrix.org homeserver users just fine.

We have reached out to #synapse:matrix.org and received the following answer from `@travis:t2l.io`, a moderator of the channel.

```
it looks like the events are being flagged as spam for some reason. It's unfortunately something I can't fix, but if you send an email to abuse@matrix.org saying that your server appears to be on the spam rules list then they should be able to help. Feel free to say I pointed you there so the team can track me down for further context.
I'll also mention it to the team internally, but an email from you is much more reliable 🙂 (if they need to ask questions or something)
```

We are sending a weekly reminder to abuse@matrix.org.

This has been months ago and has still not been fixed. I am posting this issue to find if any other homeserver can reproduce the same issue, and whether it is even a spam filter issue.

### Steps to reproduce

- The issue is the following (all rooms here are unencrypted and thus unrelated to E2E except what I wrote about DMs):
- Account A is an account created on matrix.org. Account A can see messages by most, **but somehow not all**, accounts created on the matrix.my-server.com homeserver, in a matrix.my-server.com homeserver room.
- All (every single) accounts created on matrix.org cannot see a certain Account B (we have seen at least 5 of these accounts now) created on the matrix.my-server.com homeserver in all matrix.my-server.com rooms (not yet sure if this still happens outside these rooms).
- Account A can see the "currently typing" tool-tip of Account B, but no messages are visible. Other accounts created on matrix.my-server.com can see Account B fine.
- This consistently happens regardless of room version (6 and 9), and is persistent on multiple Element platforms (Web, Windows, Mac, Android, iOS, etc).
- Therefore, it should be an issue with the homeserver.
- When Account B tries to create a DM room with Account A, Account A cannot join the channel with an error message about "room version mismatch".
- No visible issues occur when Federation Tester is used.
- User verification is also broken across servers - the request comes. but verification acceptance doesn't come back to the requesting user.

### Homeserver

A self-hosted homeserver, will provide exact host id needed

### Synapse Version

1.70.1

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Kubernetes on Containerd, Runs on matrixdotorg/synapse:v1.70.1 Container.
Database is postgres:12 container.
OS of host is Ubuntu 20.04, Kubernetes configured using Ansible.
Hardware is an AMD Epyc server.

### Relevant log output

We can provide this, but we need to ensure a way to redact personal information from the logs. Please provide us a guideline for this.

### Anything else that would be useful to know?

@dimm0 is our sysadmin and will be willing to provide any information associated with this issue.

We are using an SRV configuration instead of .well-known with Let's Encrypt TLS. We can change this to ZeroSSL if required.

**Comment by ehfd** [comment]
One more thing,
![image](https://user-images.githubusercontent.com/8457324/200383078-a7682002-a9e8-4fcf-a4d2-34e28d91c31d.png)
![image](https://user-images.githubusercontent.com/8457324/200383222-ac99558f-e83f-4b9b-bc0e-bd60de139687.png)

All users which show this behavior show this when tagged by another behavior in PC.

**Comment by ehfd** [comment]
+ There are sometimes issue where `Unable to Decrypt: decryption key is withheld` shows in a matrix.org user and a custom homeserver user where the above issue does not happen.

**Comment by squahtx** [comment]
I'll follow up with the team that handles abuse@matrix.org.
Can you let me know the name of the homeserver please?

**Comment by ehfd** [comment]
@squahtx 
matrix.nrp-nautilus.io

**Comment by squahtx** [comment]
Thanks. I've followed up with the team.
Please bump this issue in a few days if you haven't heard anything.

**Comment by ehfd** [comment]
@squahtx Yeah, thank you. Raised this here to see if there is a technical bug or an issue applicable to other homeservers.

**Comment by ehfd** [comment]
```
Sorry for the delay in getting back to you on this. After looking into it for you, it looks like [matrix.nrp-nautilus.io](http://matrix.nrp-nautilus.io/) was added to the spam filter back in June 2021, after malicious users abused a lack of email verification on the server. That appears to have been fixed, so we're removing the block. I don't have a timescale for you at the moment, but I will write back with an update once it has been done.
```

I have received this email. I will update when the issue was lifted and we can see these users again.

**Comment by mcat-ee** [comment]
+1 I am also getting this issue, including extremely weird verification between users on my homeserver and matrix.org

I'll email the address above, however there's also another weird thing:
- matrix.org statuses for affected users (again, not all users are affected) are not synced - those users just appear offline despite having default status settings

(conjecture)
Like the OP, this does not affect all matrix.org users communicating on my homeserver - but this latest affected account is a very new signup, so (if we have been added to the spamlist) maybe we obtained their user data before we were flagged?

**Comment by anonfloppa** [comment]
I am having a very similar issue on my homeserver. Messages from matrix.org are not reaching my homeserver but messages from my homeserver are reaching matrix.org. I tested in a DM between my matrix.org user and my homeserver.  I couldn't find any clue in the logs. I messaged abuse@matrix.org for a possible ACL ban and I am waiting for an answer.

**Comment by dimm0** [comment]
@squahtx the ban is still there

**Comment by turt2live** [comment]
@ehfd as an update, it looks like the unban is with the operations team. 

@anonfloppa as discussed over DM, I think you're seeing a different issue. This issue is them -> matrix.org while yours is matrix.org -> you. 

@mcat-ee your issue also sounds unrelated to this ticket.

**Comment by dimm0** [comment]
> @ehfd as an update, it looks like the unban is with the operations team.

What does this mean? How many month can it take to unban a server?

**Comment by ehfd** [comment]
@turt2live 
We fully remember what happened then at the incident, and we promptly added email verification on that day. Mistake from the team.

We are an National Science Foundation funded public Kubernetes cluster with dozens of universities and laboratories as members.

As such, we are strictly against any such malicious activity and promote public good.

**Comment by ehfd** [comment]
@turt2live 
And as we have potential to scale to thousands or more users, and we operate on real server hardware, we are willing to take, and would like, technical directives from the Matrix team to make this homeserver safer.
I have previously internally suggested to check all the email domains registered in the homeserver and purge any remaining shady accounts, but the API seems to provide ni handy way to do this...

**Comment by turt2live** [comment]
Thank you for the added context - the ticket is currently in the queue and should be dealt with this week. On the internal side, the team has it on their workflow board to address it as soon as they can.

**Comment by erikjohnston** [comment]
The ban should be removed now, let us know if you see any further problems.

**Comment by ehfd** [comment]
+ Is there any way to see the blocked users' messages before the ban was lifted?
