### ISSUE TITLE
Manually set `n_distinct` for `event_search.room_id` to avoid bad Postgres query plans

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#14402]
On matrix.org we discovered that every now and again `event_search` queries would take forever due to using the wrong query plan. This was due to Postgres underestimating the number of room IDs that existed. 

To fix this we should add a schema update with:

```sql
ALTER TABLE event_search ALTER COLUMN room_id SET (n_distinct = -0.01);
```

like we do for `state_groups_state.state_group` already.

**Comment by squahtx** [comment]
> like we do for `state_groups_state.state_group` already.

See #10359 for that fix.
