### ISSUE TITLE
Email notification template used for matrix.org HS regressed

### ISSUE THREAD

**Issue by jryans** [matrix-org/synapse#14421]
### Description

Sometime between 2022-10-31 and 2022-11-04, the matrix.org HS email notification template seemed to regress somehow (at least for my @jryans:matrix.org account).

Here are two example emails in each style for comparison:

## 2022-10-31

<img width="667" alt="image" src="https://user-images.githubusercontent.com/279572/201495488-0b7dc2a2-ce61-411b-befb-edc5e518c1e3.png">

## 2022-11-04

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/279572/201495505-8f1b952d-9da0-4300-999c-6b09c9ee9f3f.png">

I assume the 2022-10-31 style is still the intended one, as it has much nicer visual styling. Perhaps some configuration somewhere needs to be fixed...?

### Steps to reproduce

- Have an account on matrix.org
- Enable email notifications
- Cause an email to be sent

### Homeserver

matrix.org

### Synapse Version

1.71.0rc2 (b=matrix-org-hotfixes,39ea774cff,dirty)

### Platform

N/A

### Relevant log output

```shell
N/A
```

**Comment by DMRobertson** [comment]
Probably #13652?

**Comment by jryans** [comment]
After inspecting the HTML for a bit, it seems like the newer mails are missing the `doctype`, `head`, `body`, etc. elements. 

Perhaps it's because `notif_mail.html` is missing the `{% extends "_base.html" %}` line that most others have...?

**Comment by clokep** [comment]
> Perhaps it's because `notif_mail.html` is missing the `{% extends "_base.html" %}` line that most others have...?

Sounds like this got missed in the refactoring, yes. Thanks for spotting. 👍

**Comment by bmarty** [comment]
OOI in the notice I can see some weird things:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/3940906/202207955-2e63c08f-f068-49f3-ba84-310aa9980ca7.png">

<img width="158" alt="image" src="https://user-images.githubusercontent.com/3940906/202208021-81b4743e-dd6c-4d4b-a39f-738abc7dfa7a.png">
