### ISSUE TITLE
Complement `TestPartialStateJoin/Outgoing_device_list_updates/Device_list_updates_reach_incorrectly_kicked_servers_once_partial_state_join_completes_even_though_remote_server_left_room` is flakey

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#14432]
https://github.com/matrix-org/synapse/actions/runs/3459222583/jobs/5774390689

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3530229696/jobs/5921994080

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3940235658/jobs/6741135112

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3950816604/jobs/6763950004
