### ISSUE TITLE
Long-running `/context` request on `matrix.org` after client disconnected

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#14443]
*Follow-up to https://github.com/matrix-org/matrix-ansible-private/issues/6086 as [mentioned by @reivilibre](https://matrix.to/#/!SGNQGPGUwtcPBUotTL:matrix.org/$PLwm4zDzHdYfK65eklNR7ngCSsl7Op8c66om_CR7qPw?via=jki.re&via=matrix.org&via=element.io),*

There was a `/context` request that ran for 12345.92s (3.4 hours) in Matrix HQ (`!OGEhHVWSdvArJzumhm:matrix.org`) but the client disconnected after 180s (client timeout). This would be a good endpoint candidate to make cancelable (`@cancellable`).

While the `/context` request ran, it also degraded database performance for the whole `client_reader` worker so we could limit the exposure by making it cancel on client disconnect. Plus we're doing work for nothing.

---

 In the same vein as https://github.com/matrix-org/synapse/issues/14290 for `/search`

**Comment by erikjohnston** [comment]
I think this was fixed by https://github.com/matrix-org/synapse/pull/14461
