### ISSUE TITLE
Missing thread_id in m.receipt for events recieved over federation

### ISSUE THREAD

**Issue by gsouquet** [matrix-org/synapse#14459]
### Description

I simulated a conversation between two users in a thread. When a user sees the other party message, it will send a read receipt

```
POST https://matrix-client.matrix.org/_matrix/client/r0/rooms/[ROOM_ID]/receipt/m.read/[EVENT_ID]
```

With a body 

```
{ "thread_id": THREAD_ROOT_ID }
```

When this is processed, the other user will receive the `m.receipt` event down `/sync`. However I notice that the `thread_id` that has been passed in the original request body is missing (highlighted in red below).

```diff
{
  "type": "m.receipt",
  "content": {
    "[EVENT_ID]": {
      "m.read": {
        "@germaingermain:matrix.org": {
          "ts": 1668591503180
-         "thread_id": THREAD_ROOT_ID
        }
      }
    }
  }
}
```

### Steps to reproduce

- Send a read receipt from one client
- Inspect the sync response of the other party

The issue does not occur when the two users are using the threads dev server we have for internal testing.
However the issue seems to happen on matrix.org/element.io, I am unsure whether this happens only over federation or not

### Homeserver

matrix.org

### Synapse Version

1.71.0rc2

### Platform

n/a

### Relevant log output

```shell
n/a
```

**Comment by clokep** [comment]
> The issue does not occur when the two users are using the threads dev server we have for internal testing.
>  However the issue seems to happen on matrix.org/element.io, I am unsure whether this happens only over federation or not

Can you expand on this a bit -- are you only seeing the issue if the users are on different servers?

**Comment by gsouquet** [comment]
I'm unsure whether the issue is with federation, or whether the problem is only on matrix.org and element.io.
I do not have a good way to validate that. 

What I can say is that the same Element Web client works when testing against the threads dev server we have, and is not working when inspecting what comes down `/sync` on my matrix.org account, or element.io account.

**Comment by clokep** [comment]
> I'm unsure whether the issue is with federation, or whether the problem is only on matrix.org and element.io.
> I do not have a good way to validate that.

From discussion with @gsouquet, this is seen with an account on matrix.org and one on element.io.
