### ISSUE TITLE
"Non-overlapping container check" type error in `BulkPushRuleEvaluator`

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#14450]
Running mypy with strict equality checking (via `mypy --strict-equality`) we get the following error:

```
$ mypy --strict-equality
synapse/push/bulk_push_rule_evaluator.py:380: error: Non-overlapping container check (element type: "str", container item type: "Dict[Any, Any]")  [comparison-overlap]
```

It points to this piece of code:

https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/synapse/push/bulk_push_rule_evaluator.py#L379-L382

The complaint is that `actions` is defined as a `Collection[dict]`:

https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/stubs/synapse/synapse_rust/push.pyi#L45-L50

thus `if "notify" in actions:` makes no sense, hence mypy's complaint.

---

The code that actually produces the data structure is in Rust, and returns a vector of `Action`s (which is an Enum):

https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/rust/src/push/evaluator.rs#L90-L103
https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/rust/src/push/mod.rs#L163-L172

Following the definition of `Action`, we see that this should result in a vector of str when sent to python:
https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/rust/src/push/mod.rs#L208-L221

Assuming my Rust->Python foo is sound (please double-check!), my conclusion here is that the type stub is incorrect, and that we should instead have a `Collection[str]` when we reach Python.

I don't believe this has any user-visible impact. Fixing this would just reduce the number of mypy errors (and potentially prevent future bugs!).

**Comment by DMRobertson** [comment]
> please double-check!

my reading of 

```rust
             Action::SetTweak(tweak) => tweak.serialize(serializer), 
             Action::Unknown(value) => value.serialize(serializer), 
```

is that `tweak` will get serialised as a JSON object
https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/rust/src/push/mod.rs#L183-L195

and that `Unknown(value)` is a placeholder for an arbitrary JSON value.

**Comment by anoadragon453** [comment]
@DMRobertson Oh I see. Perhaps what we're looking for is a `Union[dict, str]` then?

**Comment by DMRobertson** [comment]
> @DMRobertson Oh I see. Perhaps what we're looking for is a `Union[dict, str]` then?

That seems consistent with https://github.com/matrix-org/synapse/blob/2d0ba3f89aaf9545d81c4027500e543ec70b68a6/synapse/push/bulk_push_rule_evaluator.py#L306, which is the only place we actually use `actions` directly AFAICS
