### ISSUE TITLE
Complement `Adding a push rule wakes up an incremental /sync` is consistently failing

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14456]
and it's irritating me.

https://github.com/matrix-org/synapse/actions/runs/3472783471/jobs/5804115166 e.g.

From early debugging it looks
- adding the push rule correctly wakes up a user_stream
- the user_stream calls its callback to generate a SyncResult
- we fetch global_account_data and get `{}` for our troubles
- presumably it is supposed to be a nonempty dict?

**Comment by DMRobertson** [comment]
"Flakey" might mean that Synapse is broken.

The tests are about a month old (https://github.com/matrix-org/complement/pull/488).

**Comment by DMRobertson** [comment]
Running a git bisect points the finger at #14376

**Comment by DMRobertson** [comment]
I think that https://github.com/matrix-org/synapse/blob/36097e88c4da51fce6556a58c49bd675f4cf20ab/synapse/storage/databases/main/account_data.py#L357-L359 is now False when it should have been True.

**Comment by Fizzadar** [comment]
Aha great spot @DMRobertson! Wild that this wasn't picked up in the tests earlier!
