### ISSUE TITLE
contrib/grafana still uses legacy metrics

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/synapse#14465]
### Description

After an upgrade from Synapse 1.70.1 to 1.71, some Grafana charts stopped working. Appending `_total` to (most of) the metric names underpinning those charts fixes things.

### Steps to reproduce

- Use the Grafana configuration from contrib/ as of `1.71.0`
- Update Synapse from 1.70.1 to 1.71
- See some graphs going silent

I try to list the things I could find below but not sure it's an exhaustive list:
  - Process Info: Outgoing HTTP request rate (`synapse_http_client_requests`)
  - Event persistence: Memberships/s by Origin (`synapse_storage_events_persisted_events_sep`)
  - Most of Requests (`synapse_http_server_requests_received` in 2 places, `synapse_http_server_in_flight_requests_ru_utime_seconds` in 2 places, `synapse_http_server_in_flight_requests_db_txn_duration_seconds`)
  - Federation: Outgoing EDUs by type (`synapse_federation_client_sent_edus_by_type`)
  - MAU: MAU Limits (`synapse_admin_mau:current` and `synapse_admin_mau:max`)
  - Notifier: both (`synapse_notifier_users_woken_by_stream` and `synapse_handler_presence_get_updates`)
  - Appservices: both (`synapse_appservice_api_sent_events` and `synapse_appservice_api_sent_transactions`)
  - Presence: Presence state transitions (`synapse_handler_presence_state_transition`) and Presence notify reason (`synapse_handler_presence_notify_reason`)

### Homeserver

clup.chat

### Synapse Version

1.71.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Docker containers in an Ubuntu 20.04 VM

### Relevant issue

https://github.com/matrix-org/synapse/issues/11106

**Comment by reivilibre** [comment]
Thanks for your comprehensive report! A few of these I was already aware of but was having trouble getting Grafana to co-operate with exporting them.
Some others, I did not know about, so big thanks for listing them.

I'll get these fixed up in short order :).

**Comment by DMRobertson** [comment]
Thanks, this should be fixed in 1.72 (to be released and merged into develop shortly).
