### ISSUE TITLE
Complement `TestPartialStateJoin/Outgoing_device_list_updates/Device_list_updates_reach_all_servers_in_partial_state_rooms` is flakey

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14475]
https://github.com/matrix-org/synapse/actions/runs/3486081205/jobs/5832198806

cc @squahtx , I don't know if this wants to be added to a milestone or other tracking mechanisms

**Comment by DMRobertson** [comment]
(sorry, this might be covered by other issues---I haven't dug)

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/actions/runs/3602693500/jobs/6070049929

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/4279147281/jobs/7449676195
