### ISSUE TITLE
Deactivating user doesn't remove external IDs

### ISSUE THREAD

**Issue by ptman** [matrix-org/synapse#14485]
### Description

After deactivating a user (and erasing user data) one cannot sign up a new user using the same account on the same OIDC provider because the external_user_id is still left. It needs to be removed as an extra step.

### Steps to reproduce

1. Sign up using e.g. google account
2. Deactivate user
3. Try to sign up again using the same google account

### Homeserver

another homeserver

### Synapse Version

1.68.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Ubuntu, matrix-docker-ansible-deploy

### Relevant log output

```shell
this really doesn't involve log output
```

### Anything else that would be useful to know?

Is this by design?

**Comment by clokep** [comment]
> Is this by design?

Yes, usually if you deactivate a user you do not want that user (that human) on your system. So you don't want future logins to work with the same external login info.

**Comment by clokep** [comment]
(That being said -- it is possible we should give steps of how to do this in the documentation?)

**Comment by ptman** [comment]
What about the user deactivating the account themselves?

**Comment by clokep** [comment]
Duplicate of #11072.
