### ISSUE TITLE
Does  Synapse support the CDN for the static files?

### ISSUE THREAD

**Issue by enesgur** [matrix-org/synapse#14484]
Hello there,

I'm using Synapse's latest version, and I have a question about static content. I need that the synapse server uploads the static content to s3 or digitaloceanspace when someone uploads a picture or voice record. I found https://github.com/matrix-org/synapse-s3-storage-provider and tried it. But it didn't work as I expected.

I don't want to use local storage, just the CDN providers. is that possible now? Maybe I could use FUSE or something like that, but I want to save the traffic from the main servers. 

Do you have any suggestions?

**Comment by squahtx** [comment]
https://github.com/matrix-org/synapse-s3-storage-provider provides a script to cull files in local storage that have not been accessed within a configurable number of days. By setting the threshold to a low value, like 1 day, the files in local storage can be minimized. There's no option to avoid local storage entirely.

Using FUSE to mount an S3 bucket for the media repo sounds like it would work. It's not something the Synapse team have tested. There's no way to avoid hosting or proxying the traffic yourself.
