### ISSUE TITLE
synapse does not escape forward slashes in key IDs when making a federation `key/v2/server/...` request

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14488]
https://github.com/matrix-org/synapse/blob/d8cc86eff484b6f570f55a5badb337080c6e4dcd/synapse/crypto/keyring.py#L857-L874

urllib.parse.quote doesn't escape slashes by default: because it expects to given an entire url path

ouchie

**Comment by DMRobertson** [comment]
As @squahtx says, we should audit other uses of urllib.parse.quote to see if there are other problems like this.

Grep for `((urllib\.)?parse\.)?quote\(`.

**Comment by clokep** [comment]
> As @squahtx says, we should audit other uses of urllib.parse.quote to see if there are other problems like this.
> 
> Grep for `((urllib\.)?parse\.)?quote\(`.

@DMRobertson Did we do this / find anymore?

**Comment by DMRobertson** [comment]
> > As @squahtx says, we should audit other uses of urllib.parse.quote to see if there are other problems like this.
> > Grep for `((urllib\.)?parse\.)?quote\(`.
> 
> @DMRobertson Did we do this / find anymore?

Other than constructing the regex, I haven't done this. It's on my to-do list, but maybe should raise another issue to track it.

**Comment by clokep** [comment]
> Other than constructing the regex, I haven't done this. It's on my to-do list, but maybe should raise another issue to track it.

Done: #14511.
