### ISSUE TITLE
Matrix down and wont connect after restart

### ISSUE THREAD

**Issue by d4amenace** [matrix-org/synapse#14483]
Hello, I am having problems with my matrix server. The connection is down to my element chat, but when I log into my vps and restart server it looks good and running and I can even register new users. what am I missing?

I tried:

```
synctl restart

stopped synapse.app.homeserver

Waiting for processes to exit...

All processes exited

This server is configured to use '[matrix.org](https://matrix.org/)' as its trusted key server via the

'trusted_key_servers' config option. '[matrix.org](https://matrix.org/)' is a good choice for a key

server since it is long-lived, stable and trusted. However, some admins may

wish to use another server for this purpose.



To suppress this warning and continue using '[matrix.org](https://matrix.org/)', admins should set

'suppress_key_server_warning' to 'true' in homeserver.yaml.

--------------------------------------------------------------------------------

started synapse.app.homeserver(homeserver.yaml)
```

Still no connection

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

**Comment by DMRobertson** [comment]
(Also: check your [reverse proxy](https://matrix-org.github.io/synapse/latest/reverse_proxy.html) config and status. Are requests making it to Synapse?)
