### ISSUE TITLE
Unable to set up keys

### ISSUE THREAD

**Issue by Calboni** [matrix-org/synapse#14514]
I'm having problems setting up keys, when a client like element (web/desktop/android) logs in it gets an error "Unable to set up keys" and if it tries to reset the session it gets the error "Unable to query secret storage status". I'm also having problems in trusting sessions.

On the server side the error message is "[21/Nov/2022:12:42:09 +0100] "OPTIONS /_matrix/client/v3/room_keys/version HTTP/1.1" 404 145 "-" "Mozilla/5.0 (Macintosh ; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.14 Chrome/104.0.5112.124 Electron/20.3.2 Safari/537.36"

I didn't change anythings in configuration of server or db, but somethings stop worked.

I don't know how to fix it, can someone help me please?

**Comment by DMRobertson** [comment]
> On the server side the error message is "[21/Nov/2022:12:42:09 +0100] "OPTIONS /_matrix/client/v3/room_keys/version HTTP/1.1" 404 145 "-" "Mozilla/5.0 (Macintosh ; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.14 Chrome/104.0.5112.124 Electron/20.3.2 Safari/537.36"

This doesn't look like a Synapse log line. I am guessing this comes from a reverse proxy? Check your [reverse proxy configuration](https://matrix-org.github.io/synapse/latest/reverse_proxy.html).

More generally, we're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

**Comment by Calboni** [comment]
It was a nginx log, synapse log looks like similar:

2022-11-22 14:12:59,688 - synapse.http.server - 81 - INFO - GET-549245-
<SynapseRequest at 0x7f9056191790 method='GET'
uri='/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device'
clientproto='HTTP/1.0' site=8008> SynapseError: 400 - Unrecognized request
2022-11-22 14:12:59,690 - synapse.access.http.8008 - 282 - INFO -
GET-549245- 127.0.0.1 - 8008 - {None} Processed request: 0.001sec/0.001sec
(0.001sec, 0.000sec) (0.000sec/0.000sec/0) 75B 400 "GET
/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device HTTP/1.0"
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
Element/1.11.14 Chrome/104.0.5112.124 Electron/20.3.2 Safari/537.36" [0
dbevts]

Tried asking on Synapse Admin room with no response before opening a issue
on github.


Il giorno mar 22 nov 2022 alle ore 12:06 David Robertson <
***@***.***> ha scritto:

**Comment by Calboni** [comment]
> > It was a nginx log, synapse log looks like similar:
> 
> They aren't very similar: the two logs refer to different HTTP methods and paths.
> 
>     * OPTIONS /_matrix/client/v3/room_keys/version
> 
>     * GET /_matrix/client/unstable/org.matrix.[msc2697](https://github.com/matrix-org/matrix-spec-proposals/pull/2697).v2/dehydrated_device
> 
> 
> Questions for you:
> 
>     * Are there any other log lines containing `GET-549245`?
> 
>     * Is your homeserver matrix.org? Something self-hosted?
> 
>     * What version of Synapse are you running? Do you have any experimental options turned on? Are you using any Synapse modules?
> 
>     * What database is your synapse configured to use?
> 
> 
> > Tried asking on Synapse Admin room with no response before opening a issue
> > on github.
> 
> Ah, sorry, that's fair enough. Thanks for asking there beforehand. If you do raise an issue, please use the issue templates (which prompt for some of the information requested above).

- Only 2 lines:
# grep GET-549245 homeserver.log
2022-11-22 14:12:59,688 - synapse.http.server - 81 - INFO - GET-549245- <SynapseRequest at 0x7f9056191790 method='GET' uri='/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device' clientproto='HTTP/1.0' site=8008> SynapseError: 400 - Unrecognized request
2022-11-22 14:12:59,690 - synapse.access.http.8008 - 282 - INFO - GET-549245- 127.0.0.1 - 8008 - {None} Processed request: 0.001sec/0.001sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 75B 400 "GET /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.14 Chrome/104.0.5112.124 Electron/20.3.2 Safari/537.36" [0 dbevts]

- Server is self hosted matrix-synapse:
# apt list --installed | grep matrix

matrix-synapse-ldap3/focal,now 0.1.3-4 all [installed]
matrix-synapse/focal,now 1.11.0-1 all [installed]

- How can i check for modules or experimental features?

- Database is postgresql ver 12

I'm sorry for opened a wrong type of template.

**Comment by DMRobertson** [comment]
It is probably easiest for you to use the [debian packages provided by Matrix.org](https://matrix-org.github.io/synapse/latest/setup/installation.html#matrixorg-packages) instead of Ubuntu's packages.

**Comment by Calboni** [comment]
Ok, so the problem is due to outdated version of matrix-synapsi?

What is the correct way to upgrade? Add Matrix repository and update packages?

Thanks

**Comment by DMRobertson** [comment]
> Ok, so the problem is due to outdated version of matrix-synapsi?

I expect so, yes.

> What is the correct way to upgrade? Add Matrix repository and update packages?

Yes, that should do it.

> Is There a upgrade path to follow?

There are upgrade notes at https://github.com/matrix-org/synapse/blob/master/docs/upgrade.md.

Because there is a large jump between your installed and the current stable version (1.11 -> 1.72), I would suggest you are extra careful to

- take a database backup before the upgrade
- upgrade in short steps, e.g. 1.11 -> 1.21 -> 1.31 -> ..., restarting Synapse after each upgrade and checking logs for any errors

**Comment by Calboni** [comment]
> > Ok, so the problem is due to outdated version of matrix-synapsi?
> 
> I expect so, yes.
> 
> > What is the correct way to upgrade? Add Matrix repository and update packages?
> 
> Yes, that should do it.
> 
> > Is There a upgrade path to follow?
> 
> There are upgrade notes at https://github.com/matrix-org/synapse/blob/master/docs/upgrade.md.
> 
> Because there is a large jump between your installed and the current stable version (1.11 -> 1.72), I would suggest you are extra careful to
> 
>     * take a database backup before the upgrade
> 
>     * upgrade in short steps, e.g. 1.11 -> 1.21 -> 1.31 -> ..., restarting Synapse after each upgrade and checking logs for any errors

@DMRobertson Thank you.

**Comment by Calboni** [comment]
great, I followed your instructions and updated matrix without any problem.

Now everything works fine and there are no problems with key set up.

Thanks again for your precious help.

**Comment by DMRobertson** [comment]
@Calboni glad to hear it---many thanks for getting back to me.
