### ISSUE TITLE
Synapse uses deprecated `keyId` path param on `/_matrix/key/v2/server`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#14523]
The spec has deprecated the `keyId` parameter on [`GET /_matrix/key/v2/server`](https://spec.matrix.org/v1.5/server-server-api/#get_matrixkeyv2serverkeyid) since [forever](https://github.com/matrix-org/matrix-doc/pull/1423).

(The reason given for that deprecation was that it is *ignored* on the server side.)

**Comment by DMRobertson** [comment]
Supercedes #14488, I suppose.

(Didn't we discuss this and we thought that Synapse was behaving correctly? Perhaps we were just mistaken?)

**Comment by richvdh** [comment]
yes, we were mistaken. Sorry, I got confused :/
