### ISSUE TITLE
Document how to export user data

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#14530]
**Description:**

There is a command to export user data: `python -m synapse.app.admin_cmd -c <config_file> export-data <user_id>` but as far as I can tell it is not documented anywhere.

**Comment by aceArt-GmbH** [comment]
The data will be exported to a folder under `/tmp`

But as far as I can tell, only room events are exported.
To be GDPR/DSGVO complaint, I think all data needs to be exported. Like the session info (user-agent, ip, ...).

But element already allows one to export their chat and see their session info :thinking:

**Comment by aceArt-GmbH** [comment]
Looking at what the this export provides, this does not seem to be GDPR or DSGVO compliant alone.
It exports only some room events, but not session information or similar

How do server administrators currently provide this data to the user?
Is there a custom script that one can use?
how does matrix.org i.e. do this?

**Comment by squahtx** [comment]
There's no one-click script that will do a GDPR export yet. I hear the way matrix.org handles GDPR requests involves some amount of manual work.

**Comment by aceArt-GmbH** [comment]
https://github.com/philipaconrad/matrix-archiver-sqlite seems to be a potential option as it also exports devices and files

**Comment by ankit-pn** [comment]
Should we need to document it? If yes , then assign this issue to me, i will do it.

**Comment by dklimpel** [comment]
Probably the easiest is if you make a pull request.  Issues are rarely assigned directly.

**Comment by tjay27** [comment]
I'd like to document this, where should this be added?

**Comment by dklimpel** [comment]
Perhaps there: https://matrix-org.github.io/synapse/latest/usage/administration/admin_faq.html

Or an dedicated sub page to https://matrix-org.github.io/synapse/latest/usage/administration/index.html

**Comment by thezaidbintariq** [comment]
#14883
