### ISSUE TITLE
No idea what's going on

### ISSUE THREAD

**Issue by BupAB** [matrix-org/synapse#14609]
**If you are looking for support** please ask in **#synapse:matrix.org**
(using a matrix.org account if necessary). We do not use GitHub issues for
support.

**If you want to report a security issue** please see https://matrix.org/security-disclosure-policy/

**Comment by BupAB** [comment]
GrapheneOS room can't pick up my phone number

**Comment by H-Shay** [comment]
Hello, I am pretty confused by this issue-are you reporting a bug? If so, can you re-open a new issue and use the template provided to impart the information we would need to investigate the bug? If you are asking for support I will direct you to #synapse:matrix.org where you can ask questions and get support.

**Comment by BupAB** [comment]
I've been trying to get the hang of the GrapheneOS site for a couple of
days now: it's the only forum I've encountered where I find navigation
totally unintuitive. The message "No idea what's going on" just meant I
didn't know why this particular window popped up, or what it's for, or what
else to do instead.

Thanks for the link to Matrix: maybe that will help straighten me out.
