### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by sla-te** [matrix-org/synapse#14601]
Hello, is Python 3.11 supported in 1.72?

**Comment by H-Shay** [comment]
It is not officially supported, currently the highest supported version is 3.10.

**Comment by clokep** [comment]
Let's leave this open as a request to officially support it.

Note that #13790 did add tests for this in CI, but I think the Synapse metadata and documentation needs to be updated still.

**Comment by DMRobertson** [comment]
The metadata declares support for anything semver-compatible with 3.7.1: https://github.com/matrix-org/synapse/blob/2a3cd59dd06411a79fb7500970db1b98f0d87695/pyproject.toml#L115-L116

There are gaps in our CI overage for 3.11 that [we decided we're okay with](https://github.com/matrix-org/synapse/issues/13790#issuecomment-1302393505), see the description of https://github.com/matrix-org/synapse/issues/13790

The only other mention I could see is https://github.com/matrix-org/synapse/blob/51e7255fbb684245e664ae9e715bfac77b4dd103/docs/setup/installation.md?plain=1#L203

which is easy to update.

**Comment by DMRobertson** [comment]
> The metadata declares support for anything semver-compatible with 3.7.1:

In particular this means that we show up on PyPI as supporting 3.11 since https://pypi.org/project/matrix-synapse/1.69.0/

**Comment by katlol** [comment]
any plans to [bump the Docker version](https://github.com/matrix-org/synapse/blob/develop/docker/Dockerfile#L23)? Currently pinned 3.9.
