### ISSUE TITLE
`register_new_matrix_user` doesn't fail gracefully if neither `--config` nor `--server-url` is specified

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#14635]
Version: 1.72.0-1
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025662
https://github.com/matrix-org/synapse/commit/a2ce6144479c9f0400517d505c7288f2ab785a95#r92259242

**Comment by richvdh** [comment]
for searching, the error message is:

```
UnboundLocalError: local variable 'config' referenced before assignment
```
