### ISSUE TITLE
Unexplained failure to fetch filter json from db (encoding/locale problem?)

### ISSUE THREAD

**Issue by heqian** [matrix-org/synapse#14652]
### Description

I followed the instructions [here](https://hub.docker.com/r/matrixdotorg/synapse/) and set up Synapse with PostgreSQL 15. After setting up an admin account, I logged in with Element (tried both iOS and macOS clients).

Then, I received this error:
```
Dec 9 11:30:28 PM  2022-12-10 07:30:28,285 - root - 169 - WARNING - GET-1005 - Tried to decode ''\\x7b22726f6f6d223a7b227374617465223a7b226c617a795f6c6f61645f6d656d62657273223a747275657d2c2274696d656c696e65223a7b22756e726561645f7468726561645f6e6f74696669636174696f6e73223a747275657d7d7d'' as JSON and failed
Dec 9 11:30:28 PM  2022-12-10 07:30:28,286 - synapse.http.server - 124 - ERROR - GET-1005 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7fb66e9c5130 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=0&since=s1_2_0_1_1_1_1_8_0' clientproto='HTTP/1.1' site='10000'>
Dec 9 11:30:28 PM  Traceback (most recent call last):
Dec 9 11:30:28 PM    File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
Dec 9 11:30:28 PM      result = context.run(gen.send, result)
Dec 9 11:30:28 PM    File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/filtering.py", line 47, in get_user_filter
Dec 9 11:30:28 PM      return db_to_json(def_json)
Dec 9 11:30:28 PM    File "/usr/local/lib/python3.9/site-packages/synapse/storage/_base.py", line 167, in db_to_json
Dec 9 11:30:28 PM      return json_decoder.decode(db_content)
Dec 9 11:30:28 PM    File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
Dec 9 11:30:28 PM      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 9 11:30:28 PM    File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
Dec 9 11:30:28 PM      raise JSONDecodeError("Expecting value", s, err.value) from None
Dec 9 11:30:28 PM  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I decoded:
`\\x7b22726f6f6d223a7b227374617465223a7b226c617a795f6c6f61645f6d656d62657273223a747275657d2c2274696d656c696e65223a7b22756e726561645f7468726561645f6e6f74696669636174696f6e73223a747275657d7d7d`
and, it is:
`{"room":{"state":{"lazy_load_members":true},"timeline":{"unread_thread_notifications":true}}}`

I looked into the database and found the corresponding record in the `user_filters` table:
`\x5c78376232323732366636663664323233613762323237333734363137343635323233613762323236633631376137393566366336663631363435663664363536643632363537323733323233613734373237353635376432633232373436393664363536633639366536353232336137623232373536653732363536313634356637343638373236353631363435663665366637343639363636393633363137343639366636653733323233613734373237353635376437643764`

It can be decoded to the hex in the error (`\x7b22726f6f6d223a7b227374617465223a7b226c617a795f6c6f61645f6d656d62657273223a747275657d2c2274696d656c696e65223a7b22756e726561645f7468726561645f6e6f74696669636174696f6e73223a747275657d7d7d`), and decoded further to be the text/json (`{"room":{"state":{"lazy_load_members":true},"timeline":{"unread_thread_notifications":true}}}`).

Feels like either the [db_to_json](https://github.com/matrix-org/synapse/blob/3a4f80f8c6f39c5549c56c044e10b35064d8d22f/synapse/storage/_base.py#L146) function didn't decode the `bytea` type correctly, or [add_user_filter](https://github.com/matrix-org/synapse/blob/3a4f80f8c6f39c5549c56c044e10b35064d8d22f/synapse/storage/databases/main/filtering.py#L51) encoded text/json twice.

### Steps to reproduce

- Follow https://hub.docker.com/r/matrixdotorg/synapse/
- Deploy `docker.io/matrixdotorg/synapse:v1.73.0` with PostgreSQL 15
- Login the created admin account with Elements

### Homeserver

myhomeserver

### Synapse Version

{"server_version":"1.73.0","python_version":"3.9.15"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL 15 single server (brand new setup)

### Workers

Single process

### Platform

Docker image deployed on render.com

### Relevant log output

```shell
Dec 9 11:20:01 PM  2022-12-10 07:20:01,516 - root - 169 - WARNING - GET-664 - Tried to decode ''\\x7b22726f6f6d223a7b227374617465223a7b226c617a795f6c6f61645f6d656d62657273223a747275657d2c2274696d656c696e65223a7b22756e726561645f7468726561645f6e6f74696669636174696f6e73223a747275657d7d7d'' as JSON and failed
Dec 9 11:20:01 PM  2022-12-10 07:20:01,516 - synapse.http.server - 124 - ERROR - GET-664 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7fb6704933d0 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=0&since=s1_2_0_1_1_1_1_8_0' clientproto='HTTP/1.1' site='10000'>
Dec 9 11:20:01 PM  Traceback (most recent call last):
Dec 9 11:20:01 PM    File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
Dec 9 11:20:01 PM      result = context.run(gen.send, result)
Dec 9 11:20:01 PM    File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/filtering.py", line 47, in get_user_filter
Dec 9 11:20:01 PM      return db_to_json(def_json)
Dec 9 11:20:01 PM    File "/usr/local/lib/python3.9/site-packages/synapse/storage/_base.py", line 167, in db_to_json
Dec 9 11:20:01 PM      return json_decoder.decode(db_content)
Dec 9 11:20:01 PM    File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
Dec 9 11:20:01 PM      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 9 11:20:01 PM    File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
Dec 9 11:20:01 PM      raise JSONDecodeError("Expecting value", s, err.value) from None
Dec 9 11:20:01 PM  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Anything else that would be useful to know?

I updated the database with:
```
update user_filters
set filter_json=decode('{"room":{"state":{"lazy_load_members":true},"timeline":{"unread_thread_notifications":true}}}', 'escape');
```
The error is now gone and I can use Elements without error now. So, it seems the cause is double-coding.

_No response_

**Comment by H-Shay** [comment]
Were you able to run the commands suggested?

**Comment by heqian** [comment]
I realized that my `Web Service` instance on render.com does not have the ports needed by Synapse open. Close the ticket. Will reopen it if the same issue is reproducible with a different cloud.
