### ISSUE TITLE
Font Awesome Icon for Matrix

### ISSUE THREAD

**Issue by vishalscodes** [matrix-org/synapse#14691]
Kindly make a font awesome icon for Matrix as I want to use it in a project footer.

It would be appreciated if that icon is given for free.

Thank You.

**Comment by squahtx** [comment]
This isn't something we plan to do.

**Comment by HammyHavoc** [comment]
Would be interested in the "why" behind this decision. Several times over the past two years where I've wanted this, but not had it.

**Comment by vishalscodes** [comment]
![Screenshot_2022-12-17-18-03-34-545_com brave browser](https://user-images.githubusercontent.com/104351431/209566376-77d57287-fb78-48fd-889c-3cca056e9b9a.jpg)

See that picture up there? I wish to replicate that design in my own project. So, I need font awesome icons for this (mainly for color uniformity across the icons). The problem is - well, this icon is not there for me to insert.

**Comment by clokep** [comment]
This feels more like a question for matrix-spec or somewhere else, not for a synapse (which is a specific server implementation which implements the Matrix protocol).

**Comment by vishalscodes** [comment]
Here are a few ways through which we can add the matrix icon to our projects:
1. Use a "svg" element:
```
<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M.632.55v22.9H2.28V24H0V0h2.28v.55zm7.043 7.26v1.157h.033a3.312 3.312 0 0 1 1.117-1.024c.433-.245.936-.365 1.5-.365c.54 0 1.033.107 1.481.314c.448.208.785.582 1.02 1.108c.254-.374.6-.706 1.034-.992c.434-.287.95-.43 1.546-.43c.453 0 .872.056 1.26.167c.388.11.716.286.993.53c.276.245.489.559.646.951c.152.392.23.863.23 1.417v5.728h-2.349V11.52c0-.286-.01-.559-.032-.812a1.755 1.755 0 0 0-.18-.66a1.106 1.106 0 0 0-.438-.448c-.194-.11-.457-.166-.785-.166c-.332 0-.6.064-.803.189a1.38 1.38 0 0 0-.48.499a1.946 1.946 0 0 0-.231.696a5.56 5.56 0 0 0-.06.785v4.768h-2.35v-4.8c0-.254-.004-.503-.018-.752a2.074 2.074 0 0 0-.143-.688a1.052 1.052 0 0 0-.415-.503c-.194-.125-.476-.19-.854-.19c-.111 0-.259.024-.439.074c-.18.051-.36.143-.53.282a1.637 1.637 0 0 0-.439.595c-.12.259-.18.6-.18 1.02v4.966H5.46V7.81zm15.693 15.64V.55H21.72V0H24v24h-2.28v-.55z"/></svg>
```
Note that you hav to use the "fill" attribute instead of color for coloring the icon.
``` fill: black; ```
2. Use my Github repository for maximum syntax similarities:
https://github.com/vishalscodes/custom-matrix-fontawesome-icon

**Comment by HammyHavoc** [comment]
> Here are a few ways through which we can add the matrix icon to our projects:
> 
> 1. Use a "svg" element:
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M.632.55v22.9H2.28V24H0V0h2.28v.55zm7.043 7.26v1.157h.033a3.312 3.312 0 0 1 1.117-1.024c.433-.245.936-.365 1.5-.365c.54 0 1.033.107 1.481.314c.448.208.785.582 1.02 1.108c.254-.374.6-.706 1.034-.992c.434-.287.95-.43 1.546-.43c.453 0 .872.056 1.26.167c.388.11.716.286.993.53c.276.245.489.559.646.951c.152.392.23.863.23 1.417v5.728h-2.349V11.52c0-.286-.01-.559-.032-.812a1.755 1.755 0 0 0-.18-.66a1.106 1.106 0 0 0-.438-.448c-.194-.11-.457-.166-.785-.166c-.332 0-.6.064-.803.189a1.38 1.38 0 0 0-.48.499a1.946 1.946 0 0 0-.231.696a5.56 5.56 0 0 0-.06.785v4.768h-2.35v-4.8c0-.254-.004-.503-.018-.752a2.074 2.074 0 0 0-.143-.688a1.052 1.052 0 0 0-.415-.503c-.194-.125-.476-.19-.854-.19c-.111 0-.259.024-.439.074c-.18.051-.36.143-.53.282a1.637 1.637 0 0 0-.439.595c-.12.259-.18.6-.18 1.02v4.966H5.46V7.81zm15.693 15.64V.55H21.72V0H24v24h-2.28v-.55z"/></svg>
> ```
> 
> Note that you hav to use the "fill" attribute instead of color for coloring the icon. `fill: black;` 2. Use my Github repository for maximum syntax similarities: https://github.com/vishalscodes/custom-matrix-fontawesome-icon

Whilst I like the concept, the execution misses why Font Awesome is great as a now-ubiquitous way to add icons to projects with minimal fuss and adding yet more assets to a page load.

Equally, yes, perhaps something for matrix-spec, but it's all under the matrix-org account, so I'm really not sure what the issue is, let alone nuking any idea of plans for it. If anything, adding a Matrix icon to Font Awesome stands to gain further users to Matrix. I know that plenty of people go through everything on Font Awesome whilst looking for interesting stuff to check out.

Mastodon is now on Font Awesome: https://fontawesome.com/icons/mastodon?s=solid&f=brands

In terms of publicly addressable users, apparently Matrix has many more than Mastodon. Makes precious little sense to ignore such an important asset used by so many devs. Font Awesome is fully open source and GPL-friendly. Bizarre.

**Comment by dklimpel** [comment]
Matrix is also listed in https://simpleicons.org/?q=matrix
