### ISSUE TITLE
Document that `icu` is a new, optional native dependency

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#14704]
https://github.com/matrix-org/synapse/pull/14464 added `icu` as a new, optional native dependency to improve user directory search for non-English languages. If the python module is installed, then the new user search code is used, otherwise it will fall back to the old code.

We should:

1. Update our installation instructions for native dependencies to include `icu` / `libicu-dev`.
2. Update the UPGRADE notes to mention the new dependency. (This is the release blocker)
3. Update the [Contributing Guide](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html) to mention installing `icu` / `libicu-dev`, otherwise `poetry install --extras all` will fail to install `pyicu`.

**Comment by clokep** [comment]
See matrix-org/matrix-ios-sdk#1661.
