### ISSUE TITLE
configure_workers_and_start.py regex missing

### ISSUE THREAD

**Issue by smartdone** [matrix-org/synapse#14721]
### Description

if depoly with workers and nginx
login with synapse-admin, api `/_synapse/admin/v1/users/@hello:xxx.xxx/media?dir=b&from=0&limit=50&order_by=created_ts` will response 400

Because the request does not have the correct forwarded media service
in the [https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#LL83C13-L83C51](https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#LL83C13-L83C51) file
The regular expression of media_repository has only one `"^/_synapse/admin/v1/user/.*/media.*$"`

he failed to handle `users` correctly

should be changed to
`"^/_synapse/admin/v1/(user|users)/.*/media.*$"`

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points
---

### Homeserver

https://192.168.31.35

### Synapse Version

curl https://192.168.31.35/_synapse/admin/v1/users/@hello:192.168.31.35/media

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Multiple workers

### Platform

container

### Relevant log output

```shell
{
    "errcode": "M_UNRECOGNIZED",
    "error": "Unrecognized request"
}
```

### Anything else that would be useful to know?

if depoly with workers and nginx
login with synapse-admin, api `https://yourfaces.tk/_synapse/admin/v1/users/@hello:xxx.xxx/media?dir=b&from=0&limit=50&order_by=created_ts` will response 400

Because the request does not have the correct forwarded media service
in the [https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#LL83C13-L83C51](https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#LL83C13-L83C51) file
The regular expression of media_repository has only one `"^/_synapse/admin/v1/user/.*/media.*$"`

he failed to handle `users` correctly

should be changed to
`"^/_synapse/admin/v1/(user|users)/.*/media.*$"`

如果是用worker模式部署，使用nginx反向代理，请求的media带users的时候，就不能正确的被处理
[https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#LL83C13-L83C51](https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#LL83C13-L83C51)这行代码的`"^/_synapse/admin/v1/user/.*/media.*$"`修改为`"^/_synapse/admin/v1/(user|users)/.*/media.*$"`即可正确的被处理

**Comment by clokep** [comment]
I believe this on purpose -- we [do not recommend exposing the admin APIs](https://matrix-org.github.io/synapse/develop/usage/administration/admin_api/index.html#making-an-admin-api-request) to the Internet.

**Comment by smartdone** [comment]
thanks
