### ISSUE TITLE
Hidden `listener` option `tag`

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/synapse#14746]
### Description

I have seen an undocumented config option `tag` / `site_tag` in
https://github.com/matrix-org/synapse/blob/9af2be192a759c22d189b72cc0a7580cd9de8a37/synapse/app/homeserver.py#L86-L88
- Is it used and only not good documented?
  - It is mentioned in [log format](https://matrix-org.github.io/synapse/latest/usage/administration/request_log.html) in column `BBBB`
- Or is it old an deprecated?
- Does it make sense to document it in `listener` documentation?
- And does it have other purposes than replacing the port with the tag in logging?

Origin: #187

**Comment by DMRobertson** [comment]
Thanks for spotting.

> Is it used and only not good documented?

Yes, it's used and poorly documented.

> Or is it old an deprecated?

Not old, not deprecated.

> Does it make sense to document it in listener documentation?

Yes please!

> And does it have other purposes than replacing the port with the tag in logging?

I took a look at the source code: it's only a diagnostic for logging. The option only seems to be used to configure the access logger's name, though I notice that it does get included in structured logging records:
https://github.com/matrix-org/synapse/blob/d8cc86eff484b6f570f55a5badb337080c6e4dcd/synapse/logging/context.py#L604
