### ISSUE TITLE
Configuration - Http Keep Alive Timeout

### ISSUE THREAD

**Issue by hyossing** [matrix-org/synapse#14771]
**Description:**

Hello,

It seems there is no configuration for http keep alive timeout in homeserver.yaml.

Could you provide this feature?

Is there any way to modify the timeout in the synapse source directly?

Also, could you let me know the default timeout for http keep alive.

Thanks you
Hyosung Lim

**Comment by DMRobertson** [comment]
What is your use case here---what problem are you trying to solve? Is this about client-server or server-server (federation) HTTP requests?

I am guessing that you want to reduce client latency on requests by avoiding repeat TCP and TLS handshakes for consecutive requests. If so, that is best handled by your reverse proxy---consult its documentation to see how to serve keep-alive headers.

**Comment by DMRobertson** [comment]
By default, Twisted will keep connections open for [one minute](https://github.com/twisted/twisted/blob/aa3b84c0b6c753e0835966277cdb8042b604695e/src/twisted/web/http.py#L192-L194) if the client makes a HTTP/1.1 request.

**Comment by MadLittleMods** [comment]
Closing as this appears to be something we want the reverse proxy layer to handle and no response from the reporter to figure out their use case ⏩
