### ISSUE TITLE
Matrix.org down! Invalid SSL certificate, can't access anything.

### ISSUE THREAD

**Issue by YellowOnion** [matrix-org/synapse#14782]
### Description

Sorry if this is the wrong place to report, but it's a little hard to find the right place...

I cannot get access to any services, I don't know where else to report this, Element on Mobile and Desktop reporting issues.

![image](https://user-images.githubusercontent.com/364160/210927913-b0f1a6d8-c3f9-4d53-9bca-110683a8b1ac.png)

Status page seems to Ironically, work and report no errors, and not have a link to report issues...

![image](https://user-images.githubusercontent.com/364160/210928304-8971e98f-b241-4902-9d76-b0e0ed624d79.png)

### Steps to reproduce

Visit matrix.org

### Homeserver

matrix.org

### Synapse Version

broken

### Installation Method

I don't know

### Database

N/A

### Workers

I don't know

### Platform

*shrug*

### Relevant log output

```shell
N/A
```

**Comment by YellowOnion** [comment]
Looks like Nixos.org isn't working either, Is this a bug Element, or do I need to authenticate with my home server to get access to other servers? so much for "decentralization"...

**Comment by blank1-Dev** [comment]
https://downforeveryoneorjustme.com/matrix.org

Indeed, I am too facing this issue and thus cannot message my friends. Did the SSL certificate just seriously expire without being renewed on time?

**Comment by blank1-Dev** [comment]
https://status.matrix.org/

Update, they finally updated the status page and are aware.

**Comment by YellowOnion** [comment]
Seems to be working, looks like someone was notified.

**Comment by clokep** [comment]
See matrix-org/matrix.org#1601.
