### ISSUE TITLE
Links not working in config documentation 

### ISSUE THREAD

**Issue by exitflynn** [matrix-org/synapse#14789]
There are links in the config documentation like the one [here](https://matrix-org.github.io/synapse/v1.67/usage/configuration/config_documentation.html#user_directory) that aren't properly linkified. PR #14003 intended to fix that but for some reason that didn't work?

**Comment by dklimpel** [comment]
You have linked to https://matrix-org.github.io/synapse/v1.67/usage/configuration/config_documentation.html#user_directory

PR #14003 is part of a newer version, Synapse 1.69.0.

https://matrix-org.github.io/synapse/v1.69/usage/configuration/config_documentation.html#user_directory

The latest stable documentation is there:
https://matrix-org.github.io/synapse/latest/

**Comment by exitflynn** [comment]
i see, thanks!
