### ISSUE TITLE
Remove legacy singular replication endpoint for resyncing remote user devices

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#14808]
I.e. all the code deprecated in #14716, this is pretty much:

* `user_device_resync` methods (I think? I don't see a reason to have these that just call the `multi_` version)
* `ReplicationUserDevicesResyncRestServlet`

I think that's it. 👍

**Comment by clokep** [comment]
Since #14716 made it into the release branch I think we can pretty much do this whenever.

**Comment by tjay27** [comment]
in _multi_user_device_resync there is a use of `ReplicationUserDevicesResyncRestServlet`
https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/device.py#L935-L938

Should we keep `ReplicationUserDevicesResyncRestServlet` ?

**Comment by clokep** [comment]
> in _multi_user_device_resync there is a use of `ReplicationUserDevicesResyncRestServlet`
>
> Should we keep `ReplicationUserDevicesResyncRestServlet` ?

No need to -- that's part of what we want to remove since it is the fallback path.

**Comment by khandelwalarvind26** [comment]
Hey, I'm a beginner contributor to synapse and found this issue in the good first issues section. Since the PR for this issue hasn't been merged yet, can I work on this issue?

**Comment by tjay27** [comment]
@khandelwalarvind26 
yes, go ahead :D

**Comment by skmanoj322** [comment]
Hey wanted to make my Frist open source contribution so am I in a right place if yes can I start working on this problem
