### ISSUE TITLE
Document how to start Synapse with Poetry

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#14846]
The correct invocation is `poetry run synapse_homeserver -c [your homeserver.yaml]` (or substitute `synapse_homeserver` with `synapse_worker` for workers), however this does not seem to be documented anywhere apart from the `[tool.poetry.scripts]` section of `pyproject.toml`. This makes it more difficult for newcomers to Synapse to figure out how to run it after setting it up, so I think those entrypoints should be mentioned somewhere in Synapse's documentation.

**Comment by thezaidbintariq** [comment]
#14892

**Comment by DMRobertson** [comment]
#15022 also helped here.
