### ISSUE TITLE
Incorrect note displayed on room creation

### ISSUE THREAD

**Issue by NeoTones** [matrix-org/synapse#14878]
### Description

When I create a new private room it displays:
```
name joined the room
name made the room invite only.
name made future room history visible to all room members.
name has allowed guests to join the room.
```

The room is set to private, element is set to not allow guests, encryption is enabled.

It is telling me guests are **allowed**, so it is either a bug, I misunderstand, or I am missing a config setting. Registration is on but only allowed with token.

### Steps to reproduce

Create a new private and encrypted room using Synapse + element versions listed above.

### Homeserver

My own homeserver

### Synapse Version

1.75.0+focal1

### Installation Method

Debian packages from packages.matrix.org

### Database

fresh postgresql (single on same machine as synapse)

### Workers

Single process

### Platform

KVM VPS
Ubuntu 20
Element 1.11.19 (on separate KVM VPS)

### Relevant log output

```shell
NA
```

**Comment by clokep** [comment]
If the room state doesn't match what is displayed than this sounds like an Element bug to me, not a Synapse bug.

**Comment by NeoTones** [comment]
Ok, will close and open on element repo.

**Comment by clokep** [comment]
For cross-linking: vector-im/element-web#24277
