### ISSUE TITLE
Complement `PartialStateJoinSyncsUsingOtherHomeservers` flakey under workers

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14895]
E.g. https://github.com/matrix-org/synapse/actions/runs/3981789030/jobs/6825783235

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3984078783/jobs/6829942041

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/3981789030/jobs/6826729482

Maybe this is just perma failing?

**Comment by squahtx** [comment]
Looks like Synapse with workers may just be slow.
Previously the test expected the homeserver to finish resyncing room state within the 1 second window of a single /sync.
https://github.com/matrix-org/complement/issues/588 replaced the window with a `MustSyncUntil`, which has a looser timeout of 5 seconds by default. I'm going to assume that fixed the flake.
