### ISSUE TITLE
Cannot enable guests

### ISSUE THREAD

**Issue by tio-trom** [matrix-org/synapse#14903]
### Description

I have added `allow_guest_access: true` in my homeserver.yaml. Restarted Synapse. Made sure that a room I am testing with has guests enabled and it is public. This https://chat.trom.tf/#/room/#tromjaro:matrix.trom.tf - yet I cannot join as a guest. What am I doing wrong?

### Steps to reproduce

As mentioned above.

### Homeserver

matrix.trom.tf

### Synapse Version

1.74.0

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL

### Workers

Single process

### Platform

Debian 11. AMD EPYC 7282 16-Core Processor,

### Relevant log output

```shell
I apologize but my log file is 500MB in size I cannot share it all here. If necessary I can upload it to my Nextcloud and share the link.
```

**Comment by squahtx** [comment]
As mentioned [here](https://github.com/vector-im/element-web/issues/13945#issuecomment-817601302), Element Web only provides guests read-only access to rooms. Other clients may allow guests to join rooms.

**Comment by tio-trom** [comment]
> As mentioned [here](https://github.com/vector-im/element-web/issues/13945#issuecomment-817601302), Element Web only provides read-only to guests. Other clients may allow guests to join rooms.

Do we know what clients support guests? Also, don't you need an account anyway to use these clients?

**Comment by squahtx** [comment]
Unfortunately I'm only familiar with Element Web and don't have the answer to that.
There's a list of web clients at https://matrix.org/clients/ which you could try.
