### ISSUE TITLE
Allowing recent version(s) of poetry-core

### ISSUE THREAD

**Issue by icp1994** [matrix-org/synapse#14931]
Hi, due to multiple previous issues with updating poetry-core for synapse it has been upper bounded to v1.3.1 for some time now. To quote the relevant bit from the last discussion: 

> Discussed among the team. We'll constrain to <= 1.3.1 and will raise that upper bound to 1.3.2/1.4.0/another version if a) someone wants to use that version, and b) we can check that it's safe.

Will the team consider allowing (i.e., to check whether it's safe) poetry-core v1.5.0 for synapse v1.77? Or maybe a tracking issue for checking compatibility of latest stable release of poetry-core before a synapse release.

**Comment by DMRobertson** [comment]
For cross-referencing, the quoted comment is https://github.com/matrix-org/synapse/pull/14085#discussion_r989985700, though there was some discussion in https://github.com/matrix-org/synapse/issues/14079.

> Will the team consider allowing (i.e., to check whether it's safe) poetry-core v1.5.0 for synapse v1.77?

We'd likely accept a PR which does this. I'm not sure what version of poetry-core you have in mind, but I couldn't see any obviously scary changes in the 1.4.0 and 1.5.0 [releases](https://github.com/python-poetry/poetry-core/releases).

AFAICS it should be sufficient to change https://github.com/matrix-org/synapse/blob/b8cf480fa951cbebfb180105d1f0ba6966cf051b/pyproject.toml#L323 to include a new upper bound. The tricky bit will be testing that it works fine. Most of our CI uses `poetry install` (with a pinned version of poetry), which I think uses its own pinned version of poetry-core; I don't think CI would test what we want it to. (I think the cibuildwheel jobs will check that the wheel is installable under the latest allowed poetry-core, but it won't run any of the test suites afterwards.)

The best way to sanity-check that there aren't any surprise issues at runtime is probably to
- bump the upper bound
- `pip install /path/to/checkout` in a virtualenv
- run the unit tests. I think `python -m twisted.trial tests` from within the virtualenv should do it?
