### ISSUE TITLE
ModuleNotFoundError: No module named 'synapse.synapse_rust'

### ISSUE THREAD

**Issue by toby63** [matrix-org/synapse#14966]
### Description

The new version of synapse 1.76.0 fails to start.

It seems this is the problem:
`ModuleNotFoundError: No module named 'synapse.synapse_rust'`

### Steps to reproduce

- update from 1.75.0 to 1.76.0
- try to start the service
- service fails to start, while 1.75.0 starts fine.

### Homeserver

my private homeserver

### Synapse Version

1.76.0

### Installation Method

Other (please mention below)

### Database

SQlite

### Workers

Single process

### Platform

Manjaro Linux for ARM on a Raspberry Pi.

### Relevant log output

```shell
Traceback (most recent call last):
synapse[845]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
  __import__(pkg_name)
   File "/usr/lib/python3.10/site-packages/synapse/__init__.py", line 23, in <module>
     from synapse.util.rust import check_rust_lib_up_to_date
   File "/usr/lib/python3.10/site-packages/synapse/util/rust.py", line 20, in <module>
    from synapse.synapse_rust import get_rust_file_digest
 ModuleNotFoundError: No module named 'synapse.synapse_rust'
 synapse.service: Main process exited, code=exited, status=1/FAILURE
```

### Anything else that would be useful to know?

Installed via a slightly edited AUR PKGBUILD file: https://archlinux.org/packages/community/x86_64/matrix-synapse/
No build errors.

Python version installed is: 3.10.9

**Comment by DMRobertson** [comment]
> ModuleNotFoundError: No module named 'synapse.synapse_rust'

This is not a bug in Synapse, but a problem with your installation. Synapse is partly written in Rust; the Rust dynamic library (usually called `synapse_rust.abi3.so`) must be available at import time for Synapse to use.

> Installed via a slightly edited AUR PKGBUILD file: [archlinux.org/packages/community/x86_64/matrix-synapse](https://archlinux.org/packages/community/x86_64/matrix-synapse/)

I'm afraid we cannot support community packages for Synapse. I think your best bet is to contact the maintainers of the AUR package for advice.
