### ISSUE TITLE
Complement ` TestRestrictedRoomsRemoteJoinFailOver` is flakey

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#14986]
https://github.com/matrix-org/synapse/actions/runs/4086884506/jobs/7046775641

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/actions/runs/4109460059/jobs/7091350755

**Comment by squahtx** [comment]
This turned out to not be related to faster room joins.
