### ISSUE TITLE
Modify a rooms powerlevels with the api - improved documentation

### ISSUE THREAD

**Issue by NiTRoeSE** [matrix-org/synapse#15013]
Hi, 

we creating a lot of rooms with a python script.
This script (python) uses requests and talks to the matrix api to do that.

While creating a room ( '/_matrix/client/v3/createRoom' ) its possible to set the powerlevels via 'power_level_content_override' in json payload  for that room and overwrite defaults like powerlevels for users etc.
( This works as expected and documented)

I got a hint in https://matrix.to/#/#synapse:matrix.org that its possible to that for existing rooms via https://spec.matrix.org/v1.5/client-server-api/#put_matrixclientv3roomsroomidstateeventtypestatekey

Maybe i missunderstand something but if i implement that i always get a 404 back from server with following content:

```
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>
```

Implementation in python:
```
apiurl_rooms_state = '{}/_matrix /client/v3/rooms/{}/state/m.room.power_levels/'.format(matrix_host,matrix_room['room_id'])
data = { "invite": 100 }

modify_room = requests.put(apiurl_rooms_state, headers=headers, data=data)
print(modify_room)
print(modify_room.content)
```

It would be create if documentation ca be a bit clearer to figure out how to use this ( sorry i´m no full time programmer)

Some help would be great ( i´m shure that i´m just misunderstand the usage of this apicall)

Thanks in Advanced.

**Comment by dklimpel** [comment]
There is a space in your url. Is this a typo?
`_matrix /client` - behind matrix.

**Comment by NiTRoeSE** [comment]
> There is a space in your url. Is this a typo?
> `_matrix /client` - behind matrix.

Omg .. you are right :) Thanks a lot!

Maybe it's better I leave programming for today. Apparently, I don't see the forest anymore because of all the trees. 

So please forget this "Feature Request" for a better documentation, documentatio is fine so far.
Error 11, 50cm in front of monitor.. ;) 

Have a nice day.

**Comment by DMRobertson** [comment]
Thanks Dirk for spotting this. Glad you could get it resolved.
