### ISSUE TITLE
Reintroduce DB changes from #14979, using SCHEMA_COMPAT_VERSION mechanism

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#15014]
The changes in #14979 

```sql
ALTER TABLE current_state_events ADD COLUMN event_stream_ordering BIGINT;
ALTER TABLE local_current_membership ADD COLUMN event_stream_ordering BIGINT;
ALTER TABLE room_memberships ADD COLUMN event_stream_ordering BIGINT;

INSERT INTO background_updates (update_name, progress_json) VALUES
  ('populate_membership_event_stream_ordering', '{}');
```

Problems:
- the query used by `get_ex_outlier_stream_rows_txn` becomes ambiguous: there are two columns called event_stream_ordering. #14979 disambiguates this, but won't exist in old code.
- the background update doesn't add an ordering, so it might usurp other updates in the queue.

Questions:
- does the new query assume the `populate_membership_event_stream_ordering` background update has completed? How long do we expect it will take?

For 1.77 I
- reverted the PR: https://github.com/matrix-org/synapse/commit/9cd7610f86ab5051c9365dd38d1eec405a5f8ca6
- but kept in the change which disambiguates the columns in the source code anyway: https://github.com/matrix-org/synapse/commit/f10caa73eee0caa91cf373966104d1ededae2aee
- and bump SCHEMA_VERSION: #15036

For the future we should try to land the schema changes gradually (see [guidance](https://matrix-org.github.io/synapse/latest/development/database_schema.html#synapse-schema-versions)) over the next few releases.

**Comment by DMRobertson** [comment]
(cc @Fizzadar)

**Comment by DMRobertson** [comment]
I've updated the description and labels to explain what I did in 1.77.

**Comment by Fizzadar** [comment]
Thank you for catching the compact & handling this @DMRobertson, I'll resubmit using the `SCHEMA_COMPAT_VERSION` next week(ish).

**Comment by DMRobertson** [comment]
No worries @Fizzadar. I think we'd normally hope to land it in stages e.g.:

- disambiguate the query (1.77)
- add the columns, start writing to them, and kick off the background job. (e.g. 1.78)
- require the background job to have completed, and read from the new columns. (e.g. 1.79)

I'm not fully sure when SCHEMA_VERSION and SCHEMA_COMPAT_VERSION should get bumped. The example in the docs is [for removing a column](https://matrix-org.github.io/synapse/latest/development/database_schema.html#synapse-schema-versions), not adding one. There might be some clues in big comment describing SCHEMA_VERSION bumps, see https://github.com/matrix-org/synapse/blob/b4ec4f5e71a87d5bdc840a4220dfd9a34c54c847/synapse/storage/schema/__init__.py#L81 

In fact, judging from https://github.com/matrix-org/synapse/blob/b4ec4f5e71a87d5bdc840a4220dfd9a34c54c847/synapse/storage/schema/__init__.py#L50-L52 maybe I should have bumped the version when disambiguating the query?

(cc @richvdh, does the above sound sensible?)

**Comment by richvdh** [comment]
>  maybe I should have bumped the version when disambiguating the query?

Oh bah, yes you should. Otherwise we have no way to distinguish between a Synapse that is compatible with the new columns, and one which is not.

Can you do it now, before 1.77final?

**Comment by richvdh** [comment]
Re the other comments on `SCHEMA_VERSION`, in particular https://github.com/matrix-org/synapse/blob/b4ec4f5e71a87d5bdc840a4220dfd9a34c54c847/synapse/storage/schema/__init__.py#L82-L88

What we really care about for `SCHEMA_VERSION` is the expectations made by the *python* code. Those three points don't really give us any clues about those expectations. Compare with most of the earlier comments which are more explicit about how the Python is changing, rather than the structure of the database.

Not necessarily saying they need fixing retrospectively; my point is more that they aren't great examples to follow.

**Comment by DMRobertson** [comment]
> > Can you do it now, before 1.77final?
> 
> Will do.

#15036

**Comment by Fizzadar** [comment]
I have now reintroduced this in #15128 with proper schema bump & ordering on the background job. To answer Q's above:

> does the new query assume the populate_membership_event_stream_ordering background update has completed?

No only to use existing columns explicitly.

> How long do we expect it will take?

Probably a while :) Requires iterating over all membership events so a pretty hefty job overall.
