### ISSUE TITLE
Remove authentication requirement for GET /_matrix/media/v3/config

### ISSUE THREAD

**Issue by catfromplan9** [matrix-org/synapse#15029]
**Description:**

Title is pretty self explanatory. I feel like this info is not sensitive at all and it'd be useful to check this to decide if you want to use a server, because if its really low you might rather avoid signing up on that homeserver

**Comment by clokep** [comment]
Unfortunately this change would require an MSC as the spec requires auth on this endpoint: https://spec.matrix.org/v1.5/client-server-api/#get_matrixmediav3config

**Comment by catfromplan9** [comment]
> 

Understood
