### ISSUE TITLE
Problem with presence in 1.76

### ISSUE THREAD

**Issue by korneyda** [matrix-org/synapse#15046]
This problem repeated in version 1.76

_Originally posted by @korneyda in https://github.com/matrix-org/synapse/issues/13601#issuecomment-1424694386_

**Comment by korneyda** [comment]
I have 11 workers and 3 stream_writers in large installation
On 1.76 problem with presence

**Comment by DMRobertson** [comment]
@korneyda we need more information to investigate your report---at the very least, a description of what goes wrong and logs showing the problem. Please open an issue using [the bug report template](https://github.com/matrix-org/synapse/issues/new?assignees=&labels=&template=BUG_REPORT.yml).
