### ISSUE TITLE
Synapse requires auth for `GET /_matrix/client/.../publicRooms`, contrary to spec

### ISSUE THREAD

**Issue by Ah3n0** [matrix-org/synapse#15049]
### Description

GET /_matrix/client/v1/register/m.login.registration_token/validity

![Bildschirm­foto 2023-02-10 um 11 09 49](https://user-images.githubusercontent.com/22989398/218066478-d3383bc1-42f1-40a9-a138-94e1c5636853.png)

### Steps to reproduce

GET Request : url=http://localhost:8008/_matrix/client/v1/register/m.login.registration_token/validity 
 path_url=/_matrix/client/v1/register/m.login.registration_token/validity 
 headers={'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'} 
 body=None 

### Homeserver

own

### Synapse Version

1.73

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Single process

### Platform

K8s Cluster

### Relevant log output

```shell
GET Response : url=http://localhost:8008/_matrix/client/v1/register/m.login.registration_token/validity 
 status=400, reason=Bad Request 
 headers={'Transfer-Encoding': 'chunked', 'Server': 'Synapse/1.73.0', 'Date': 'Fri, 10 Feb 2023 10:09:05 GMT', 'Content-Type': 'application/json', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Headers': 'X-Requested-With, Content-Type, Authorization, Date'} 
 body={"errcode":"M_MISSING_PARAM","error":"Missing string query parameter 'token'"}
```

### Anything else that would be useful to know?

![Bildschirm­foto 2023-02-10 um 11 10 25](https://user-images.githubusercontent.com/22989398/218066823-660e89f6-97a5-4f87-902c-5dca056aa655.png)

**Comment by DMRobertson** [comment]
Please link to the spec rather than post a screenshot of it.

https://spec.matrix.org/v1.5/client-server-api/#get_matrixclientv1registermloginregistration_tokenvalidity

The complaint in the response is that you haven't provided the required query parameter `token`, the registration token to check the validity of. You haven't demonstrated that this endpoint requires authentication.

**Comment by Ah3n0** [comment]
@DMRobertson My bad, it was an other [endpoint](https://spec.matrix.org/unstable/client-server-api/#post_matrixclientv3roomsroomidforget). Sorry for this confusion:

![Bildschirm­foto 2023-02-14 um 13 07 38](https://user-images.githubusercontent.com/22989398/218735545-cd895a01-2f72-48a1-ac22-ce6a2bea9017.png)

![Bildschirm­foto 2023-02-14 um 13 10 19](https://user-images.githubusercontent.com/22989398/218735565-792242b6-63ad-47bc-a003-2ec80d1f97f9.png)

**Comment by DMRobertson** [comment]
Confusingly, the link you have provided is to the `GET .../forget` endpoint, not /publicRooms.

[/publicRooms is specced as requiring auth](https://spec.matrix.org/unstable/client-server-api/#get_matrixclientv3publicrooms) so Synapse is not spec-compliant. I am not clear if Synapse should be changed or if the spec should.

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/blob/1182ae50635db94d3c9c47990a0befcbf6306b62/synapse/rest/client/room.py#L445-L446 is presumably responsible.

**Comment by Ah3n0** [comment]
> Confusingly, the link you have provided is to the `GET .../forget` endpoint, not /publicRooms.
> 
> [/publicRooms is specced as requiring auth](https://spec.matrix.org/unstable/client-server-api/#get_matrixclientv3publicrooms) so Synapse is not spec-compliant. I am not clear if Synapse should be changed or if the spec should.

Link updated to  'GET /_matrix/client/v3/publicRooms'

**Comment by DMRobertson** [comment]
Discussed among the team. We think the spec should mark this as requiring auth.

**Comment by DMRobertson** [comment]
Related: https://github.com/matrix-org/synapse/pull/2421 https://github.com/matrix-org/matrix-spec/issues/145
