### ISSUE TITLE
Unexpected returned keys with values

### ISSUE THREAD

**Issue by Ah3n0** [matrix-org/synapse#15048]
### Description

Spec 4.7 Account registration and management describes the request body key 'inhabit_login'; 'true'. Using this value would avoid returning access_token and device_id. But these key are returned. 

### Steps to reproduce

```
POST Request : url=http://localhost:8008/_matrix/client/v3/register?kind=user 
 path_url=/_matrix/client/v3/register?kind=user 
 headers={'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '201', 'Content-Type': 'application/json'} 
 body=b'{"auth": {"type": "m.login.dummy"}, "device_id": "PUOCZZPU", "inhabit_login": "true", "initial_device_display_name": "RobotFramework-API", "password": "Password-1234", "username": "localuser-RzLf4I6n"}' 
```

### Homeserver

own

### Synapse Version

1.73

### Installation Method

Docker (matrixdotorg/synapse)

### Database

postgreSQL

### Workers

Single process

### Platform

K8s Cluster

### Relevant log output

```shell
POST Response : url=http://localhost:8008/_matrix/client/v3/register?kind=user 
 status=200, reason=OK 
 headers={'Transfer-Encoding': 'chunked', 'Server': 'Synapse/1.73.0', 'Date': 'Fri, 10 Feb 2023 08:57:36 GMT', 'Content-Type': 'application/json', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Headers': 'X-Requested-With, Content-Type, Authorization, Date'} 
 body={"user_id":"@localuser-rzlf4i6n:matrix.local","home_server":"matrix.local","access_token":"syt_bG9jYWx1c2VyLXJ6bGY0aTZu_daeGtGImQoNtXeBzuyzN_0VbOzo","device_id":"PUOCZZPU"}
```

### Anything else that would be useful to know?

![Bildschirm­foto 2023-02-10 um 09 46 13](https://user-images.githubusercontent.com/22989398/218053440-8cd22882-5c60-4aad-96a2-9b3e56e4f565.png)

![Bildschirm­foto 2023-02-10 um 09 46 43](https://user-images.githubusercontent.com/22989398/218053601-3fd03447-9e7b-4207-89f8-39008182b9f7.png)

**Comment by DMRobertson** [comment]
The spec endpoint is https://spec.matrix.org/v1.5/client-server-api/#post_matrixclientv3register .

You have made at least two mistakes here:
- the key is spelt `inhibit_login`, but you provided `inhabit_login` with an `a`.
- you passed `inhabit_login` as the JSON string `"true"`, not the JSON boolean `true`.

You have also publicly exposed a Synapse access token in your screenshot. I recommend logging out of that session to invalid that token immediately.
