### ISSUE TITLE
Declare support for Matrix 1.6

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#15089]
See https://matrix.org/blog/2023/02/14/matrix-v-1-6-release

## Client-Server API

* [x] Add information on standard error responses for unknown endpoints/methods, as per [MSC3743](https://github.com/matrix-org/matrix-spec-proposals/pull/3743).
	* See #14209 and #14599
* [x] Add /rooms/<roomID>/timestamp_to_event endpoint, as per [MSC3030](https://github.com/matrix-org/matrix-spec-proposals/pull/3030).
	* See #14471
* [x] Define hkdf-hmac-sha256.v2 MAC method for SAS verification, as per [MSC3783](https://github.com/matrix-org/matrix-spec-proposals/pull/3783).

## Server-Server API

* [ ] Remove keyId from the server /keys endpoints, as per [MSC3938](https://github.com/matrix-org/matrix-spec-proposals/pull/3938).

## Application Service API

* [x] Add information on standard error responses for unknown endpoints/methods, as per [MSC3743](https://github.com/matrix-org/matrix-spec-proposals/pull/3743).
	* We would only care about this for calling out to AS, but I don't think we call any potentially unknown endpoints so maybe nothing to do? Could future proof by using the same code we do for federation though.

## Identity Service API

* [ ] Add information on standard error responses for unknown endpoints/methods, as per [MSC3743](https://github.com/matrix-org/matrix-spec-proposals/pull/3743).
	* We would only care about this for calling out to IS, but I don't think we call any potentially unknown endpoints so maybe nothing to do? Could future proof by using the same code we do for federation though.

## Push Gateway API

* [ ] Add information on standard error responses for unknown endpoints/methods, as per [MSC3743](https://github.com/matrix-org/matrix-spec-proposals/pull/3743).
	* We would only care about this for calling out to PG, but I don't think we call any potentially unknown endpoints so maybe nothing to do? Could future proof by using the same code we do for federation though.

## Room Versions

* [x] Update the default room version to 10, as per [MSC3904](https://github.com/matrix-org/matrix-spec-proposals/pull/3904).
    * See #14111

**Comment by clokep** [comment]
I've attempted to add some notes about what I think is done, but likely could use double checking. See #14486 for a previous iteration.

**Comment by clokep** [comment]
> Define `hkdf-hmac-sha256.v2` MAC method for SAS verification

The legacy. method (`hkdf-hmac-sha256`) doesn't appear in the Synapse repo at all, so I'm going to assume there's nothing to do here.

**Comment by clokep** [comment]
> Remove keyId from the server /keys endpoints, as per MSC3938.

Up until #14525, which landed in v1.74.0rc1, Synapse sent the key ID when requesting keys. MSC3938 notes that this is a breaking change. Making it such that the key ID / trailing slash is invalid means that Synapse < 1.74.0 will be unable to request keys from Synapse >= 1.xx (whenever this lands). This seems pretty awful, @richvdh did you have any thoughts on how we were hoping to roll this out? I'm not getting a good feel of how much this would break if we just did it now.

**Comment by richvdh** [comment]
Yeah, it's probably premature to rip out support.

I think my intention here was that servers that support *only* spec v1.6 do not need to allow the trailing slash (and of course, they should not include the trailing slash, or the key ID, in outgoing requests), but servers that want to maintain support for earlier versions of the spec still need to permit it.

My suggestion would be to continue to permit key ID or trailing slash, but log a warning. Strictly speaking that makes Synapse non-spec-compliant for v1.6, but I think it's the best we can do for now.

**Comment by clokep** [comment]
> My suggestion would be to continue to permit key ID or trailing slash, but log a warning. Strictly speaking that makes Synapse non-spec-compliant for v1.6, but I think it's the best we can do for now.

That seems reasonable. Looking back, we maybe should have revved the endpoint version. 🤷
