### ISSUE TITLE
Synapse requires auth for GET /_matrix/client/v3/profile/{id}

### ISSUE THREAD

**Issue by Ah3n0** [matrix-org/synapse#15118]
### Description

[Spec](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3profileuserid) does not provide for authentication. But it is needed to use the endpoint.  

### Steps to reproduce

GET /_matrix/client/v3/profile/ without access_token

### Homeserver

own

### Synapse Version

1.73

### Installation Method

Docker (matrixdotorg/synapse)

### Database

postgreSQL

### Workers

Single process

### Platform

K8s

### Relevant log output

```shell
"errcode":"M_MISSING_TOKEN","error":"Missing access token"
```

**Comment by dklimpel** [comment]
Did you checked your configuration?
See: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#require_auth_for_profile_requests

**Comment by Ah3n0** [comment]
> https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#require_auth_for_profile_requests

Good catch. This value is set to true. However, I think ‘require_auth_for_profile_requests’ is required for user registration. This implies a discrepancy between the spec and the endpoint above. We need to check whether the spec or the authentication should be changed to allow requesting this endpoint without access_code.

**Comment by reivilibre** [comment]
> I think require_auth_for_profile_requests is required for user registration

Why do you think this?

--

> This implies a discrepancy between the spec and the endpoint above

Not wrong. Given the security properties, though, I'd be minded to consider this a spec bug: the spec should ideally say that it is *sometimes* required. Some homeservers will have no problems with exposing all their user profiles (maybe) but some definitely would mind!!

**Comment by Ah3n0** [comment]
> > I think require_auth_for_profile_requests is required for user registration
> 
> Why do you think this?
> 
I realized that I was too quick to understand this configuration. It is a precondition for a positive authentication request for this problem. Thank you for the information.
> --

> > This implies a discrepancy between the spec and the endpoint above
> 
> Not wrong. Given the security properties, though, I'd be minded to consider this a spec bug: the spec should ideally say that it is _sometimes_ required. Some homeservers will have no problems with exposing all their user profiles (maybe) but some definitely would mind!!

I agree. So, is there a possibility to manually set up the authentication for this (or for each) endpoint? `require_auth_for_profile_requests ` is set to true. Do I need to watch an other configuration as well in this case?

**Comment by reivilibre** [comment]
> So, is there a possibility to manually set up the authentication for this (or for each) endpoint? require_auth_for_profile_requests is set to true. Do I need to watch an other configuration as well in this case?

I'm not sure what you mean; can you elaborate?
