### ISSUE TITLE
Presence is heavy taking lot of cpu usage

### ISSUE THREAD

**Issue by nishant378** [matrix-org/synapse#15169]
**Using synapse v1.65**
When I try to use presence for less users(for 10-15) it's working fine but when i try to use presence for 1000+ users than cpu usage becomes 100% and my application stop working. When i make **use_presence: false** in homeserver.yaml than application start working.

**homeserver.yaml**
use_presence: true

**workers**
1) generic_worker1.yaml
2) generic_worker2.yaml
3) generic_worker3.yaml
4) generic_worker4.yaml
5) additional1.yaml
6) presence.yaml

**Comment by H-Shay** [comment]
Unfortunately this is a known issue which we are working on: https://github.com/matrix-org/synapse/issues/9478. As such, I am closing this as a duplicate.
