### ISSUE TITLE
dpkg-deb: error: archive '/tmp/apt-dpkg-install-58Z80T/5-matrix-org-archive-keyring_1.1_all.deb' uses unknown compression for member 'control .tar.zst'

### ISSUE THREAD

**Issue by olmari** [matrix-org/synapse#15176]
### Description

Doing normal `apt upgrade` on Debian 11 (bullseye) using matrixorg repository from 1.77.0 -> 1.78.0, the installation fails with:

```
dpkg-deb: error: archive '/tmp/apt-dpkg-install-58Z80T/5-matrix-org-archive-keyring_1.1_all.deb' uses unknown compression for member 'control
.tar.zst', giving up
dpkg: error processing archive /tmp/apt-dpkg-install-58Z80T/5-matrix-org-archive-keyring_1.1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/apt-dpkg-install-58Z80T/5-matrix-org-archive-keyring_1.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Initial searching suggest that Debian 11 dpkg doesn't support zstd compression, support came in for Debian 12, which is still very much alpha.

### Steps to reproduce

- Have Debian 11 / Bullseye as OS
- Use matrixorg provided repository installed Synapse
- Do normal `apt update+upgrade` procedure

### Homeserver

hacklab.fi

### Synapse Version

1.78

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL 14.7, single server.

### Workers

Multiple workers

### Platform

Upcloud VM, Debian 11 / Bullseye.

### Relevant log output

```shell
dpkg: error processing archive /tmp/apt-dpkg-install-58Z80T/5-matrix-org-archive-keyring_1.1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/apt-dpkg-install-58Z80T/5-matrix-org-archive-keyring_1.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by richvdh** [comment]
Apparently dpkg didn't support zstd compression until Debian 12: https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg/669008#669008

(Ubuntu has supported it for a while, iirc)

**Comment by richvdh** [comment]
ftr the solution to this is to add `-Zxz` to https://github.com/matrix-org/pkg-repo-configs/blob/main/build_keyring_deb.sh#L23

**Comment by richvdh** [comment]
(or to build the thing on debian rather than ubuntu)

**Comment by erikjohnston** [comment]
Hopefully should be fixed now
