### ISSUE TITLE
Could not unpickle M_UNRECOGNIZED: MatrixError: [405] Unrecognized request (.../org.matrix.msc2697.v2/dehydrated_device/claim)

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#15178]
### Description

Since upgraded to Synapse v1.78.0 I am getting the below issue: 

```
POST /_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device/claim 405
fetch	@	fetch.ts?76d0:62
requestOtherUrl	@	fetch.ts?76d0:264
request	@	fetch.ts?76d0:205
authedRequest	@	fetch.ts?76d0:156
rehydrateDevice	@	client.ts?5faf:1571
```

```
could not unpickle M_UNRECOGNIZED: MatrixError: [405] Unrecognized request (/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device/claim)
    at parseErrorResponse (webpack-internal:///120:83:12)
    at MatrixHttpApi.requestOtherUrl (webpack-internal:///116:248:
```

This might be a regression again, see ...

https://github.com/matrix-org/synapse/issues/14334
https://github.com/matrix-org/matrix-js-sdk/issues/2809

### Steps to reproduce

See above.

### Homeserver

.

### Synapse Version

.

### Installation Method

pip (from PyPI)

### Database

Both PostgreSQL & SQLITE

### Workers

I don't know

### Platform

.

### Configuration

.

### Relevant log output

```shell
.
```

### Anything else that would be useful to know?

.

**Comment by clokep** [comment]
I think this is due to #14605.
