### ISSUE TITLE
Synapse calls `/r0` for media over federation

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#15196]
https://github.com/matrix-org/synapse/blob/4fc8875876374ec8f97a3b3cc344a4e3abcf769f/synapse/media/media_repository.py#L427

It should be trying the `/v3` endpoint until something like [MSC1902](https://github.com/matrix-org/matrix-spec-proposals/pull/1902) or similar lands. Arguably there should also be a fallback mechanism to try `/r0` when `/v3` fails, per `M_UNRECOGNIZED` in the [standard error codes](https://spec.matrix.org/v1.6/client-server-api/#common-error-codes).

**Comment by clokep** [comment]
This is part of #11474, which also talks about a few other spots.
