### ISSUE TITLE
Failed to find memberships for ["@user:...."] in partial state room !... in the auth events of ["$..."].

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#15221]
https://sentry.tools.element.io/organizations/element/issues/63004/?project=2&query=is%3Aunresolved

When pushing events in partial state rooms down incremental /sync, we try to find the `m.room.member` state event for their sender by digging through their auth events, so that we can present the membership to the client. Events usually have a membership event in their auth events, with the exception of the `m.room.create` event and a user's first join into the room.

When implementing https://github.com/matrix-org/synapse/issues/13477, we forgot to consider the exceptions.

**Comment by DMRobertson** [comment]
What's the impact of this---does this block incremental syncs?

**Comment by squahtx** [comment]
Nope, it's just an error-level log message.
