### ISSUE TITLE
Clarify retry notification code

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/synapse#15226]
When looking into tweaking the backoff behaviour on my server, I came across this code:

https://github.com/matrix-org/synapse/blob/f4fc83ac755b8b06ecab1a31592308b03f8d2a5e/synapse/util/retryutils.py#L252-L262

Specifically the code seems to notify every worker (and master), that a particular destination is up, even when it decided a destination is down and in my opinion should only be writing the new backoff interval to the database. This would be fairly easy to fix by just exiting that function if the retry interval is 0, however I am not familiar enough with Synapse internals to be sure that this doesn't break other stuff. It might also be the case, that this code does something completely different, than I assumed. In any case, I would appreciate if someone could clarify what that code is doing and possibly add a comment, why notifying the other workers is the right thing to do. I would assume this would lead to the backoff incrementing to quickly, but maybe it isn't possible to hit this case.

Originally I asked the question in #synapse and it was suggested to just file an issue to not forget about it: https://matrix.to/#/%23synapse-dev%3Amatrix.org/%24-5RtnWrJbfFjGIH8vKkpgOE7UVt2M9aNK6PThkvMsiI

Additionally we discovered, where that code was added and that someone else asked about this code as well at the time: https://github.com/matrix-org/synapse/pull/12500#discussion_r877166594

I hope this issue makes sense. I don't really know what to do about the code, I am just documenting, that multiple people think it is weird. :)

**Comment by clokep** [comment]
See #16506.
