### ISSUE TITLE
How to use a proxy to access Matrix.org's push API from mainland China

### ISSUE THREAD

**Issue by Simonmxy** [matrix-org/synapse#15236]
I deployed Matrix-synapse-py3 v1.78 by deb mode(not docker) in mainland China, but it cannot access the matrix.org notification push API. I configured the Proxy variable in the Ubuntu20.04 environment. When I Connect to https://matrix.org through wget curl, etc.,
```
< HTTP/2 405
< date: Thu, 09 Mar 2023 17:06:30 GMT
< content-type: text/html; charset=utf-8
< allow: HEAD, POST
< permissions-policy: interest-cohort=()
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 7a54e8aa0bf4a7c3-ICN

<html>
  <head><title>405 - Method Not Allowed</title></head>
  <body>
    <h1>Method Not Allowed</h1>
    <p>Your browser approached me (at /_matrix/push/v1/notify) with the method "GET".  I only allow the methods HEAD, POST here.</p>
  </body>
</html>
```
It looks good but the push process is still blocked,and in the log file:
```
synapse.http.client - 472 - INFO - httppush.process-10658 - Error sending request to POST https://matrix. org/_matrix/push/v1/notify: RequestTimedOutError 504: Timeout connecting to remote server
```
I checked the documentation of Synapse, it told me that the https_proxy variable is supported. 
My proxy service is not on localhost, and the ip is not in "url_preview_ip_range_blacklist"

Is there any way for me to connect to the Push API?

**Comment by Simonmxy** [comment]
> https://matrix-org.github.io/synapse/latest/setup/forward_proxy.html suggests that push should work over a forward proxy. I suggest checking your outbound proxy logs---can you see requests for `https://matrix.org/_matrix/push/v1/notify` reaching the proxy?
> 
> Other than that, your best bet is probably to ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

Yes my logs said:
synapse.http.client - 472 - INFO - httppush.process-10658 - Error sending request to POST https://matrix. org/_matrix/push/v1/notify: RequestTimedOutError 504: Timeout connecting to remote server

Thanks for your helping.I'll try to ask help there.

**Comment by DMRobertson** [comment]
Those are Synapse logs, not your forward proxy's logs.

In any case, I'll let the admins room address your support request.

**Comment by ChesterHachirokuJamie** [comment]
It's probably due to the *GFW*, they're using *DNS hijacking*.\
The matrix.org domain is not accessible from Mainland China.\
Luckily, this domain is behind a CloudFlare CDN, which is pingable from Mainland China.\
So here's the probable fix:
```
echo "104.20.201.37 matrix.org" >> /etc/hosts
```
Where the IP can be obtained from [here](https://ping.pe/matrix.org);
You also need to set this in the homeserver.yaml
```
use_insecure_ssl_client_just_for_testing_do_not_use: true
```
This seems to do the trick for me. But not sure if the use_insecure_ssl thing poses a security threat.

But I also cannot get this to work through my http_proxy, no request from `https://matrix.org/_matrix/push/v1/notify`.

**Comment by Simonmxy** [comment]
> It's probably due to the _GFW_, they're using _DNS hijacking_. The matrix.org domain is not accessible from Mainland China. Luckily, this domain is behind a CloudFlare CDN, which is pingable from Mainland China. So here's the probable fix:
> 
> ```
> echo "104.20.201.37 matrix.org" >> /etc/hosts
> ```
> 
> The IP can be obtained from [here](https://ping.pe/matrix.org); You also need to set this in the homeserver.yaml
> 
> ```
> use_insecure_ssl_client_just_for_testing_do_not_use: true
> ```
> 
> This seems to do the trick for me. But not sure if the use_insecure_ssl thing poses a security threat.
> 
> But I also cannot get this to work through my http_proxy, no request from `https://matrix.org/_matrix/push/v1/notify`.

Thanks for your help,now matrix.org push server response 200 to me,thank you.
