### ISSUE TITLE
Allow endpoint:  _matrix/client/<>/register/available on workers 

### ISSUE THREAD

**Issue by 999lakhisidhu** [matrix-org/synapse#15242]
This endpoint is not working with worker configuration. , it has to be routed through the main process . can we enable it please, on worker configuration as well

**Comment by DMRobertson** [comment]
Are you sure about this? (Which Synapse version are you running?)

The [worker documentation](https://matrix-org.github.io/synapse/latest/workers.html) lists
`^/_matrix/client/(r0|v3|unstable)/register$`  as something that can be handled by a generic worker.

**Comment by 999lakhisidhu** [comment]
@DMRobertson  yes  i am sure , v1.79.0rc1 , i tried with this version
