### ISSUE TITLE
Improve performance of background update `populate_user_directory_process_rooms`

### ISSUE THREAD

**Issue by H-Shay** [matrix-org/synapse#15264]
Relevant code begins here: https://github.com/matrix-org/synapse/blob/335f52d595c2c32e4b512b97e2851bc98b819ca7/synapse/storage/databases/main/user_directory.py#L87

This process can cause excess load on the DB, perhaps need to reconfigure the batch size to make it less resource-intensive.

**Comment by clokep** [comment]
The main issue (from my understanding) is that it reports based on the number of rooms which are processed, but rooms vary in how "expensive" they are. Maybe using something like `rooms * users_in_room` would be better?

That might allow the background update algorithm to process it a bit more reasonably.

**Comment by reivilibre** [comment]
We should use `TRUNCATE` instead of unconditional `DELETE FROM`, which is faster on Postgres (no table scan).

**Comment by clokep** [comment]
Do we think #15316 is enough here or is there more to do?

**Comment by erikjohnston** [comment]
Empirically its doing ~1Hz of room processing on matrix.org, which is going to take months?

We should have a look at what queries its doing etc and see if we can speed it up. We can just turn on DEBUG logging on the background worker to see what its doing.

**Comment by erikjohnston** [comment]
Bah, that sounds slower than it was before :(
