### ISSUE TITLE
Random rollback on room state event(??)

### ISSUE THREAD

**Issue by catfromplan9** [matrix-org/synapse#15307]
### Description

This one is hard to explain but I will try my best. I was in a room, and I spammed too much. Mjolnir banned me (it has a higher power level tham myself). I unbanned myself and reinvited myself to the room. Around 2 hours and everything is going fine. Around that time, I can no longer see new messages or send messages. I do an init sync and the room is gone, it says im banned too. I check on an alt and *some* of the messages I sent after being unbanned the first time have a missing display name and avatar. There is no ban event I can see, but now when I go on my alt into the room info I can see that I am once again banned for the same reason. It is as if the room info rolled back on itself to what it was before and did so without triggering any ban event in the chat. Furthermore, when I changed the power level of my alt using the mjolnir account (it has highest power level in the room) I saw in chat that it had been changed from 100 to 101 but in practice I could not unban my power level 100 main account (same unban glitch i described in other issue occurs despite being power level above the account) and when i went into the room people tab i see my alt that i changed to power level 101 as being power level 100 still. I was able to unban my account by changing it to power level 99 and then unbanning it but wtf? What is going on here? Its seriously confusing me.

### Steps to reproduce

- Make a matrix room
- add mjolnir to it with higher power level than yourself
- spam and get banned by it
- ???
- profit

### Homeserver

Selfhosted homeserver

### Synapse Version

Synapse 1.79.0

### Installation Method

Debian packages from packages.matrix.org

### Database

postgresql, single server, no porting from sqlite, recently lost media repo and restored old backup and also deleted all the remote media caches to fix a bug i should probably also report

### Workers

Single process

### Platform

Debian server, 32gb ram, intel 10th gen cpu, integrated graphics, bare metal

### Relevant log output

```shell
I dont even know where to begin with log output, would this even cause logs?
```

**Comment by catfromplan9** [comment]
Happened again

**Comment by catfromplan9** [comment]
I feel like this is a room issue and that itll continue

**Comment by H-Shay** [comment]
Right, a few questions: what is the name of the room? When you say that it happened again, can you describe exactly what happened - is it exactly the same set of circumstances as the initial report, or another chain of events? Can you provide logs for the time surrounding "it happening again"? Without logs we can't investigate this, and tbh I suspect a state reset which is not possible to diagnose without some spelunking in your DB. But logs would be a good start.

**Comment by catfromplan9** [comment]
> Right, a few questions: what is the name of the room? When you say that it happened again, can you describe exactly what happened - is it exactly the same set of circumstances as the initial report, or another chain of events? Can you provide logs for the time surrounding "it happening again"? Without logs we can't investigate this, and tbh I suspect a state reset which is not possible to diagnose without some spelunking in your DB. But logs would be a good start.

It isnt happening anymore and this only happened thrice, so ill assume it fixed iself, closing this
