### ISSUE TITLE
Synapse 1.80 synapse_rust.abi3.so: invalid file format

### ISSUE THREAD

**Issue by 593kdk32idk32** [matrix-org/synapse#15342]
### Description

Upgrade Synapse to v 1.80 using PIP leads to a broken installation. 

### Steps to reproduce

Have a previous version of Synapse installed like 1.79 using virtualenv and pip. Try and upgrade using normal PIP. 

Try running Synapse after upgrade and see following error. 

```
./bin/synctl --no-daemonize start" (uid: 5084 gid: 5084)
Traceback (most recent call last):
  File "/apps/synapse/./bin/synctl", line 5, in <module>
    from synapse._scripts.synctl import main
  File "/apps/synapse/lib/python3.10/site-packages/synapse/__init__.py", line 24, in <module>
    from synapse.util.rust import check_rust_lib_up_to_date
  File "/apps/synapse/lib/python3.10/site-packages/synapse/util/rust.py", line 20, in <module>
    from synapse.synapse_rust import get_rust_file_digest
ImportError: /apps/synapse/lib/python3.10/site-packages/synapse/synapse_rust.abi3.so: invalid file format
```

### Homeserver

Several different personal homeservers. The upgrade fails consistently. 

### Synapse Version

1.79 upgraded to 1.80

### Installation Method

pip (from PyPI)

### Database

Postgres. Single server. No sqlite or backups involved. 

### Workers

Single process

### Platform

OS: Freebsd 13.1
Synapse was installed and upgraded many times in the same virtualenv environment. 

Initial installation
python3.11 -m venv /home/synapse
source /home/synapse/bin/activate
pip install "matrix-synapse[postgres]"

Typical upgrade
/home/synapse/bin/pip install --upgrade "matrix-synapse[postgres]"

Rust-1.68.0 is installed and available on server. 

### Configuration

It's a basic installation. No extra features. 

### Relevant log output

```shell
./bin/synctl --no-daemonize start" (uid: 5084 gid: 5084)
Traceback (most recent call last):
  File "/apps/synapse/./bin/synctl", line 5, in <module>
    from synapse._scripts.synctl import main
  File "/apps/synapse/lib/python3.10/site-packages/synapse/__init__.py", line 24, in <module>
    from synapse.util.rust import check_rust_lib_up_to_date
  File "/apps/synapse/lib/python3.10/site-packages/synapse/util/rust.py", line 20, in <module>
    from synapse.synapse_rust import get_rust_file_digest
ImportError: /apps/synapse/lib/python3.10/site-packages/synapse/synapse_rust.abi3.so: invalid file format
```
```


### Anything else that would be useful to know?

I've tried doing a force reinstall of all the components using: pip install --upgrade --force-reinstall "matrix-synapse[postgres]"

The upgrade succeeds, bu the error persists.

**Comment by DMRobertson** [comment]
If you do a fresh install of 1.80 into a clean virtualenv, do you see the same error?

**Comment by 593kdk32idk32** [comment]
I tested downgrading to 1.79 and restarting Synapse. That does not fix the issue. I used this command.  

```
pip install matrix-synapse[postgres]==1.79
``` 
 I'll test a clean installation of 1.80 now.

**Comment by 593kdk32idk32** [comment]
A clean installation of 1.80 is also broken. The installation succeeds, but trying to generate a homeserver configuration fails. 

Here's my steps. 

```
python3.11 -m venv /home/synapse
cd /home/synapse
source /home/synapse/bin/activate
pip install "matrix-synapse[postgres]"
```

So far everything succeeds. Next I try and generate a configuration. 

```
python -m python -m synapse.app.homeserver --server-name example.com --config-path homeserver.yaml --generate-config --report-stats=no
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/synapse/lib/python3.11/site-packages/synapse/__init__.py", line 24, in <module>
    from synapse.util.rust import check_rust_lib_up_to_date
  File "/home/synapse/lib/python3.11/site-packages/synapse/util/rust.py", line 20, in <module>
    from synapse.synapse_rust import get_rust_file_digest
ImportError: /home/synapse/lib/python3.11/site-packages/synapse/synapse_rust.abi3.so: invalid file format
```

And here you see the same Rust error again.

**Comment by DMRobertson** [comment]
Can you share the output of `pip install`? You might need to `pip install -v` or `-vv` to get more debugging information. (I'm looking for the logs describing how the Rust part of Synapse was built.)

**Comment by 593kdk32idk32** [comment]
Sure. I did a clean installation using:

```
pip install -vv --log /home/pip.log "matrix-synapse[postgres]"
```

Can I email you the log?

**Comment by DMRobertson** [comment]
I can see that pip is compiling the rust parts of Synapse from scratch:

```
2023-03-28T18:34:38,460   cargo rustc --lib --message-format=json-render-diagnostics --manifest-path rust/Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib
```

But I can't see any other clues as to why python doesn't like the generated shared object. Ideas:

- Has anything about your system changed recently? E.g. a new Rust version?
- Can you use `file` (as in https://en.wikipedia.org/wiki/File_(command)) on the .so to check that it's a sensible binary?
- Are you able to `pip install` Synapse 1.79 into a clean virtualenv?
  - If not, I think I'd suggest installing from a git checkout and doing a `git bisect` to work out where the bad change is.

**Comment by 593kdk32idk32** [comment]
I upgraded Rust to rust-1.68.1 yesterday. So far as I can tell, Rust is working properly. Other programs written in Rust are compiling and running. 

I tried Synapse 1.79 and 1.78 in a clean virtualenv. Both appear to build and install fine. They both error out at runtime with the same Rust error. What's odd is that I have Synapse 1.78.0 running just fine from a previous upgrade/install. This only seems to affect newly installed or upgraded instances. 

This seems to be the issue. 
$ file synapse_rust.abi3.so 
synapse_rust.abi3.so: data

The broken instances show data. The working instances show it as "ELF 64-bit LSB shared object". 

So I guess the question is, why is the rust library broken after a successfully build?

**Comment by squahtx** [comment]
Could you check what actually in synapse_rust.abi3.so, using `hexdump -C synapse/synapse_rust.abi3.so | head` ?

**Comment by DMRobertson** [comment]
> So I guess the question is, why is the rust library broken after a successfully build?

My guess would be:

> I upgraded Rust to rust-1.68.1 yesterday.

If you downgrade rust, does a valid .so get built?

**Comment by 593kdk32idk32** [comment]
Unfortunately no. I was using 1.68 when the issue started. I moved to 1.68.1 and am now upgrading to 1.68.2 to test.

**Comment by DMRobertson** [comment]
> I was using 1.68 when the issue started.

Ahh, sorry, you did say as much when you opened the issue.

Not sure what to recommend here, I'm afraid. The only other suggestion that comes to mind would be to run `pip install matrix-synapse[postgres]` under `strace` (or a BSD equivalent) to see what syscalls get made, and to grep through those for lines including `synapse_rust.abi3.so`. But that might be rather like searching for a needle in a haystack.

**Comment by 593kdk32idk32** [comment]
Not a Matrix/Synapse issue. This was an issue in the environment. Sorry for the noise.

**Comment by DMRobertson** [comment]
Out of curiosity, what was the issue?

**Comment by 593kdk32idk32** [comment]
An issue with the underlying distributed storage that was causing silent corruption during the software build. There were no errors I could see, but the build worked on some of the storage mounts and not others. The difference was the mount settings.
