### ISSUE TITLE
Add Cloudflare Turnstile support

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse#15367]
**Description:**

Cloudflare Turnstile has been more stable, and most importantly, it can be used in some places where Google services are not very applicable (such as mainland China).

**Comment by MomentQYC** [comment]
https://blog.cloudflare.com/turnstile-private-captcha-alternative/

**Comment by t3chguy** [comment]
This should be discussed in https://github.com/matrix-org/matrix-spec/issues/295
