### ISSUE TITLE
Remove support for application service authentication via query params

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#15379]
#13996 added support for MSC2832 to authenticate appservices via a header instead of query parameters. It didn't deprecate or remove the query params authentication for backwards compatibility.

This is unfortunate since passing those will end up in proxy logs, etc. #15317 intends to "deprecate" them and I'd like to disable them by default / remove them, but technically this would mean that Synapse is no longer spec compliant for spec versions < 1.4.

We have a few options for this:

* Don't care about the spec compliant issue and just remove support.
* Add a configuration flag (either in `homeserver.yaml` or an implementation-specific flag in the appservice config file) to enable support for legacy authentication.
* Drop support for Matrix < 1.4.

There's a few other ideas in #15317 too.

Note that #15317 declares the current status-quo until at least Synapse v1.88.0.

**Comment by erikjohnston** [comment]
> * Add a configuration flag (either in `homeserver.yaml` or an implementation-specific flag in the appservice config file) to enable support for legacy authentication.

Let's go with this option, as a compromise.
