### ISSUE TITLE
M_TOO_LARGE: event too large for event m.room.power_levels

### ISSUE THREAD

**Issue by djschilling** [matrix-org/synapse#15384]
We built an app service that manages rooms for our users.
This service sets the power level of the members of chat groups.

We have a room with over 2000 persons in it and want to set the power level of each of these persons, so that only a few of them can write and most can only read. In our application the user can configure if a user can read or write.

To achieve that we use the botIntent like this: `botIntent.sendStateEvent(roomId, 'm.room.power_levels', '', eventContent);`
The eventContent contains all users and their power levels.

In this big group we get the following error: `M_TOO_LARGE: event too large`.

[https://github.com/matrix-org/mjolnir/issues/129](Here) i read that there is an limit as of how big an event can be.
So is there no way to set power levels for so many persons in a chat room?

### Homeserver

chat.church.tools

### Synapse Version

{"server_version":"1.80.0","python_version":"3.8.10"}

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL

**Comment by DMRobertson** [comment]
Yes, Matrix events can be [at most 65536 bytes large](https://spec.matrix.org/v1.6/client-server-api/#size-limits).

> We have a room with over 2000 persons in it and want to set the power level of each of these persons, so that only a few of them can write and most can only read.

>  The eventContent contains all users and their power levels.

You should do this by:

- setting `events_default` to a value (e.g. `25`) greater than `users_default` (which is usually `0`)
- explicitly naming the users who can write in the `users` field
- not including the read-only users in the `users` field.

See https://spec.matrix.org/v1.6/client-server-api/#mroompower_levels for details.


reate an eventContent with `events_default` set to . See https://spec.matrix.org/v1.6/client-server-api/#mroompower_levels

**Comment by djschilling** [comment]
Thanks for the answer. We changed our code, it works now as you suggested.
