### ISSUE TITLE
Cannot connect to my new homeserver through clients

### ISSUE THREAD

**Issue by ptrsuk** [matrix-org/synapse#15390]
Hi,

I recently set up a Matrix homeserver using Synapse, and have been trying to connect to it through Element, but I am getting the error: Unexpected error resolving homeserver configuration. I am also receiving: Get "https://[IP ADDRESS]:8448/_matrix/key/v2/server": context deadline exceeded (Client.Timeout exceeded while awaiting headers) on the Matrix Federation Tester.

The unusual part to me is that I can connect to the domain directly through Chrome and see the message 'It works! Synapse is running', so I'm not sure where I'm going wrong. According to the matrix-synapse logs I am logging these lines when trying to enter the server hostname into Element:

2023-04-04 17:59:20,984 - synapse.access.http.8008 - 460 - INFO - GET-123 - [IP ADDRESS] - 8008 - {None} Processed request: 0.000sec>

Not sure if anyone can help, but would appreciate any possible advice here.

Thanks guys.

**Comment by erikjohnston** [comment]
You'll need to follow the instructions at https://matrix-org.github.io/synapse/latest/federate.html to correctly configure what domain/port Matrix traffic will be sent to you on. By default traffic comes in on port 8448.

Similarly for client traffic you can set up a [`.well-known/client`](https://spec.matrix.org/v1.6/client-server-api/#server-discovery) file to change where matrix clients will connect to.
