### ISSUE TITLE
Invalid app_service_config_files should crash Synapse.

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#15422]
A user managed to pass in a string to the `app_service_config_files` config option (https://github.com/matrix-org/matrix-appservice-irc/issues/1696) and synapse happily "accepted" it with a warning. I think this probably should have crashed Synapse, rather than allowing them to proceed and thinking something might be wrong with the bridge.

**Comment by reivilibre** [comment]
Seems valid to me
