### ISSUE TITLE
Prevent this situations

### ISSUE THREAD

**Issue by JeanPaulLucien** [matrix-org/synapse#15469]
Server should prevent this situation:
![image](https://user-images.githubusercontent.com/24779886/233798818-bd5ed418-3f70-44bc-ad8a-bb9b579200ea.png)

Have fun:
`https://matrix.to/#/!RmbyjciKFOOpRijssE:openintents.modular.im`

**Comment by clokep** [comment]
The homeserver can't really do anything about the event content, especially for encrypted events. This seems like a rendering buf of some sort, probably due to using weird Unicode characters and could be reported to your client if it is causing issues.
