### ISSUE TITLE
`poetry install` over a running instance causes processes to segfault

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#15461]
When we looking into this, we saw that `poetry install` is "editing" the shared object file rather than replacing it.

```
3510767 stat("/home/erikj/synapse/target/debug/libsynapse.so", {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 stat("/home/erikj/synapse/synapse/synapse_rust.abi3.so", {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 stat("/home/erikj/synapse/target/debug/libsynapse.so", {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 stat("/home/erikj/synapse/synapse/synapse_rust.abi3.so", {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 openat(AT_FDCWD, "/home/erikj/synapse/target/debug/libsynapse.so", O_RDONLY|O_CLOEXEC) = 3
3510767 fstat(3, {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 ioctl(3, TCGETS, 0x7ffd23d7be30) = -1 ENOTTY (Inappropriate ioctl for device)
3510767 lseek(3, 0, SEEK_CUR)           = 0
3510767 openat(AT_FDCWD, "/home/erikj/synapse/synapse/synapse_rust.abi3.so", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 4
3510767 fstat(4, {st_mode=S_IFREG|0755, st_size=0, ...}) = 0
3510767 ioctl(4, TCGETS, 0x7ffd23d7be30) = -1 ENOTTY (Inappropriate ioctl for device)
3510767 lseek(4, 0, SEEK_CUR)           = 0
3510767 fstat(3, {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 sendfile(4, 3, [0] => [35088552], 35088552) = 35088552
3510767 sendfile(4, 3, [35088552], 35088552) = 0
3510767 close(4)                        = 0
3510767 close(3)                        = 0
3510767 stat("/home/erikj/synapse/synapse/synapse_rust.abi3.so", {st_mode=S_IFREG|0755, st_size=35088552, ...}) = 0
3510767 chmod("/home/erikj/synapse/synapse/synapse_rust.abi3.so", 0100755) = 0
```

Erik investigated further and ultimately submitted a patch to setuptools-rust: https://github.com/PyO3/setuptools-rust/pull/295. This was accepted, but has yet to be released. 

----

Once a newer setuptools-rust release is available, we should take advantage of this to ensure that we don't accidentally segfault running processes when we actually want to do a rolling restart.

At the moment, setuptools_rust is currently upper-bounded at the current release version:
https://github.com/matrix-org/synapse/blob/ae69d6952576fc77b4beca49181b807e7bd80a1d/pyproject.toml#L366-L371

which will presumably need bumping; confusingly we also have a lower bound here:

https://github.com/matrix-org/synapse/blob/ae69d6952576fc77b4beca49181b807e7bd80a1d/pyproject.toml#L212-L220

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/pull/15512 means that anything using the poetry environment should now include the fix.

**Comment by landryb** [comment]
> #15512 means that anything using the poetry environment should now include the fix.

shouldnt the dependency in https://github.com/matrix-org/synapse/blame/develop/pyproject.toml#L371 be relaxed to accept 1.6.0 now ?

**Comment by DMRobertson** [comment]
Urgh, yes it should. Thank you for spotting.
