### ISSUE TITLE
Stabilize support for MSC3952: intentional mentions

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#15487]
[MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952) has almost passed FCP, we need a plan to stabilize it.

* [ ] Swap unstable prefixes for stable ones.
* [x] ~~Figure out if we can send the new rule down incremental syncs.~~

**Comment by clokep** [comment]
I think in the past we've just punted on this problem, but does there seem like a reasonable way to have clients get notified of a new push rule for incremental syncs?

I think we'd need to do something like push a new row into `push_rules_stream` for each user? This sounds quite expensive, but I think we could do it in the background (with the caveat that for a period of the time the homeserver and client might disagree on the push rules, but this is going to happen anyway with old clients).

What do people think about this?

**Comment by clokep** [comment]
> I think we'd need to do something like push a new row into `push_rules_stream` for each user?

Actually, we might need to add two rows, one for `.m.rule.is_user_mention` and one for `.m.rule.is_room_mention`.

**Comment by clokep** [comment]
@reivilibre had a [few good ideas](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$a6Gb_1WMb9m4AmSA6YeHuDC0e4kjQzTQK_PtZ6vSt5Y?via=matrix.org&via=element.io&via=beeper.com):

* Capture the "latest" push rule stream ID somewhere else and use it in sync.
* Add a "system" stream table that we use for migrations like this.
* Add a row without a `user_id` in `push_rules_stream`.

Other thoughts:

* Stream writers are the only things that should write to stream tables.
* What happens if the server rolls back and then forwards again?
* Double check if clients refresh push rules during start-up.
* Ensure that the new conditions / rules don't break clients dramatically.

**Comment by clokep** [comment]
> > Ensure that the new conditions / rules don't break clients dramatically.
> 
> I asked [client developers](https://matrix.to/#/!XXSJTvRPInupfUgQVb:matrix.org/$Khy_C81E8Lg1uyawgZC1vGLZjLpodasz4gHb4_DRwQ0?via=pixie.town&via=matrix.org&via=element.io) for some help with this. The [matrix-js-sdk treats unknown conditions as "not matching"](https://github.com/matrix-org/matrix-js-sdk/blob/4f67e59692312831e716bbcf610c2827d4a3ae66/src/pushprocessor.ts#L403-L406) which seems like a reasonable way to fallback.

Turns out that we've been leaking the extensible events rules since they were implemented, which have new conditions and nothing has exploded. 😢

**Comment by clokep** [comment]
We'll want to tweak this a bit more [per this comment](https://github.com/vector-im/element-meta/issues/886#issuecomment-1568789102) to handle a better migration path for users from the legacy rules to the stable rules.

**Comment by clokep** [comment]
> We'll want to tweak this a bit more [per this comment](https://github.com/vector-im/element-meta/issues/886#issuecomment-1568789102) to handle a better migration path for users from the legacy rules to the stable rules.

This looks a bit more annoying than expected, since the `push_rule_enable` uses an ID generator we'll need a background update to do it. This is awkward since the user might have notifications from the new rule before the update runs. I can't think of a good way around this though.

Additionally things that won't work well include:

* Users on old clients disabling the legacy rule only.
* Rollback and then rollforward of a deploy (i.e. this would be a 1-time transition).

**Comment by daniellekirkwood** [comment]
We no longer want to migrate existing users. 

@clokep did an analysis of how many folks would need to be migrated and the amount of effort it would take to do so -- I do not believe it's worth it and the outcome of not migrating people is not that bad (they can go back to settings and turn it off). 

Therefore, this is ready to go! 

The meta issue has also been updated FYI: https://github.com/vector-im/element-web/issues/24291

**Comment by daniellekirkwood** [comment]
@pmaier1 I believe that @clokep has completed all the work needed here (especially now we've removed the migration piece) would you help me in identifying next steps to closing this out? It maybe just needs a peer-review?
