### ISSUE TITLE
Inline SQL queries using boolean parameters

### ISSUE THREAD

**Issue by H-Shay** [matrix-org/synapse#15515]
Before SQLite 3.23, `TRUE` and `FALSE` were not recognised as constants by SQLite, and the `IS [NOT] TRUE`/`IS [NOT] FALSE` operators were not supported. While Synapse supported SQLite versions older 3.23 that made it necessary to avoid using `TRUE` and `FALSE` constants in SQL commands. To work around this constraint the boolean operators were passed as parameters like so:

https://github.com/matrix-org/synapse/blob/57aeeb308b39c4fd455682966eabc9c0fa17c65d/synapse/storage/databases/main/purge_events.py#L251-L258

However, Synapse now requires a SQLite version of 3.27.0 or higher if SQLite is configured so we no longer need to do this and futhermore should convert old-style queries in the codebase to use `TRUE`/`FALSE` inline as it is easier to parse/read.

**Comment by TlenekSi** [comment]
Hi! I would like to help with this issue. Can you assign it to me?

**Comment by santhoshivan23** [comment]
@H-Shay I'd like to take this.

**Comment by prithvi009** [comment]
Is this issue still open?

**Comment by clokep** [comment]
> Is this issue still open?

Yes, there's the start of a PR at #15525, however.

**Comment by Attul-Sharma** [comment]
txn.execute(
    "UPDATE events SET outlier = ?"
    " WHERE event_id IN ("
    "    SELECT event_id FROM events_to_purge"
    "    WHERE NOT should_delete"
    ")",
    (1,),  # 1 represents True, 0 represents False
)

**Comment by Attul-Sharma** [comment]
txn.execute(
    "UPDATE events SET outlier = ?"
    " WHERE event_id IN ("
    "    SELECT event_id FROM events_to_purge"
    "    WHERE NOT should_delete"
    ")",
    (1,),  
)
