### ISSUE TITLE
Error starting synapse with systemd or python synctl

### ISSUE THREAD

**Issue by thagoat** [matrix-org/synapse#15546]
### Description

Error upon starting with systemd and synctl.
Error:
Error in configuration at 'a.p.p._.s.e.r.v.i.c.e._.c.o.n.f.i.g._.f.i.l.e.s':
Expected 'None' to be a list of AS config files:
Updated to 1.82.0 
python version 3.11.3
Had the same error running in a docker container

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

### Homeserver

Synapse home server on my hardware

### Synapse Version

1.82.0

### Installation Method

Other (please mention below)

### Database

SQLite

### Workers

Single process

### Platform

Archlinux, native install and docker container

### Relevant log output

```shell
Error in configuration at 'a.p.p._.s.e.r.v.i.c.e._.c.o.n.f.i.g._.f.i.l.e.s':
Expected 'None' to be a list of AS config files:
```

### Anything else that would be useful to know?

Had a massive python update from pacman and the error started after update

**Comment by wuetzchen** [comment]
Hello, 

had a similar issue after upgrading, while my config was like 

```
app_service_config_files:



```
I received the same error message. As I am not using any app services, I simply uncommented this config line, works like a charm now with my Arch installation and packages 

python 3.11.3-1
matrix-synapse 1.82.0-2

**Comment by maxkratz** [comment]
I had the same error after upgrading Synapse to `v1.82.0` but I use Docker to run my Matrix stack. Commenting out the line as proposed by @wuetzchen worked for me. Thank you!

**Comment by thagoat** [comment]
Perfect! Thanks @maxkratz @wuetzchen
Worked like a charm! Looked through my config and missed that line at least 3 times 😂🤣

**Comment by clokep** [comment]
The error checking around this was tightened up a bit in #15425.
