### ISSUE TITLE
Redaction of Events Help Needed

### ISSUE THREAD

**Issue by yeazin** [matrix-org/synapse#15556]
Hi, I am trying to add an event redaction feature.  Whenever user wants to remove certain timestamps events, he/she can do that. But during the development I ve come across a problem.  Whenever I try to remove those events they are being deleted. But after the deletion User cannot add new message to the room. 
When I check the log its saying prev_event_id not found.

That is why I went for the traditional redaction here. But    cant understand process of redaction at some point though i implement correctly. 
.Any idea you can give me to solve the problem.  
It will be a great help if you give me a brief database transection concept here 😇.

**Comment by squahtx** [comment]
We're using GitHub's issue tracker for bug reports and feature requests only. For help with modifying Synapse, there is a #synapse-dev:matrix.org room that you can visit.
