### ISSUE TITLE
GitHub releases made by GitHub actions do not include a body, leading to non-markdown release bodies unless manually fixed

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#15561]
Our `release-artifacts.yml` GitHub action will [optionally create a draft GitHub release](https://github.com/matrix-org/synapse/blob/86d541f37c1bc9197a6f561b31f3aa359740b4bd/.github/workflows/release-artifacts.yml#L199C2-L211) if one doesn't already exist, before attaching the generated assets to it. It appears that when it does so, it does not set the body of the release, which causes GitHub to use the tag message without markdown parsing (which doesn't look great). The solution here is currently to manually copy/paste the tag message into the body of the release, but I'm wondering if we can automate that too (mainly so that we don't forget to it).

One can set the `body` field [as detailed](https://github.com/softprops/action-gh-release#inputs) in [softprops/action-gh-release](https://github.com/softprops/action-gh-release) to set the body of the release when creating or updating it. To set the body of the release, one could thus do the following:

```yaml
with:
  body: $(git tag -l --format='%(contents)' ${GITHUB_REF#refs/tags/})
```

Though note that in the case of attaching assets to an existing release, this would override any existing body.

Also note that the headers of each tag's message appear to be a bit broken:

```
Synapse 1.80.0 (2023-03-28)
      ===========================

No significant changes since 1.80.0rc2.

Synapse 1.80.0rc2 (2023-03-22)
==============================

Bugfixes
--------
...
```

Note the indented `===`s. Click a `...` next to a tag to see for yourself: https://github.com/matrix-org/synapse/tags. This may need to be fixed before this automation becomes useful, else the text we attach to the release may not render correctly.

**Comment by reivilibre** [comment]
Might be worth considering that the right answer is just 'don't do that'; I thought our usual release procedure involved creating the release ourselves (which in turn kicks off this GHA job, to attach the artefacts after the fact!). Is there any reason that workflow was missed or is undesirable?

**Comment by reivilibre** [comment]
The release script *is* the automation for this part of the process. I'm not sure what has happened to lead to this issue but you shouldn't need to be tweaking tags manually. :/
