### ISSUE TITLE
Event not found when joining a roomlink with an event in it.

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/synapse#15568]
### Description

I like giving non Matrix Users the Opportunity looking into Public Matrix Rooms.

The Problem is that since a couple of time linking to an event didn't work anymore despite the Event is there.

Thought that this is an Element Bug because they aren't waiting long enough, but i was told that i am wrong:
https://github.com/vector-im/element-web/issues/25330

Couldn't test it with another Server, because i don't know another matrix server who has guests enabled.

### Steps to reproduce

Where are you starting? What can you see?
    This link should be opened as guest User:
    [https://matrix.to/#/!jqjYAhOIRvqbLqqsQs:matrix.org/$l00waANOlw7k0r\_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?via=matrix.org&via=tchncs.de&via=sils.li](https://matrix.to/#/!jqjYAhOIRvqbLqqsQs:matrix.org/$l00waANOlw7k0r%5C_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?via=matrix.org&via=tchncs.de&via=sils.li)

This is e.G. the link in Element:
https://app.element.io/#/room/!jqjYAhOIRvqbLqqsQs%3Amatrix.org/%24l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?via=matrix.org&via=tchncs.de&via=sils.li

### Homeserver

matrix.org

### Synapse Version

1.83.0rc1

### Installation Method

I don't know

### Database

?

### Workers

Multiple workers

### Platform

-

### Relevant log output

```shell
-
```

**Comment by JokerGermany** [comment]
The message can be found this way:
Call https://app.element.io/#/room/!jqjYAhOIRvqbLqqsQs%3Amatrix.org/%24l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?via=matrix.org&via=tchncs.de&via=sils.li
Scroll until at least 2023-04-01
Call https://app.element.io/#/room/!jqjYAhOIRvqbLqqsQs%3Amatrix.org/%24l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?via=matrix.org&via=tchncs.de&via=sils.li again in the same windows
And then he will show you the correct message

**Comment by MadLittleMods** [comment]
This seems like an Element client bug.

The event exists in the `matrix.org` database and is visible in the Matrix Public archive at https://archive.matrix.org/roomid/jqjYAhOIRvqbLqqsQs:matrix.org/date/2023/03/31?at=$l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0

If you look in the devtools console when [visiting the Element link](https://app.element.io/#/room/!jqjYAhOIRvqbLqqsQs%3Amatrix.org/%24l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?via=matrix.org&via=tchncs.de&via=sils.li), it makes a `GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/!jqjYAhOIRvqbLqqsQs%3Amatrix.org/context/%24l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0?filter=%7B%22lazy_load_members%22%3Atrue%7D` request which is successful and the event is visible in the response as expected. But Element throws a `Failed to load timeline position` error dialog and you can see this error in the devtools console:

```
Error loading timeline panel at !jqjYAhOIRvqbLqqsQs:matrix.org/$l00waANOlw7k0r_UlPt-2rjK-Oy1XDoHc2qEO2bX2X0 Error: No timeline given to initFields
    at n (timeline-window.ts:101:23)
```


---

Closing in favor of https://github.com/vector-im/element-web/issues/25330 which I can also copy these details to
