### ISSUE TITLE
Confusion in the synaptic-gap

### ISSUE THREAD

**Issue by iohm5v8u94bz77b** [matrix-org/synapse#15596]
I entered two rooms (picantly the Matrix-HQ-Forum and the Element-Web/Desktop-Forum) recently. One day later, I was not able to read and write new messages there (my first thought was, I was banned - so I've tried the to contact admins). One admin told me, that it seems to be the consequence of a dirty room-update...

A few days later, I tried to leave both rooms, and to re-enter. But I was still in the "twilight-zone" between in and out. 

The most meaningful error-message was:
"
MatrixError: [404] Not a known room (https://synapse.matrix.digitale-gesellschaft.ch/_matrix/client/r0/rooms/!YTvKGNlinIzlkMTVRl%3Amatrix.org/leave)
".

Finally, I was re-invited in both rooms and after about an hour (in the case of the Matrix-HQ-Foum) of struggling while connecting the forums and server-fetching-errors, it worked then. 

It looked a bit like, my home-server (digitale-gesellschaft.ch) had to be restarted than (because of my requests of the Matrix-HQ-Forum???), before the things began to run...

According to "https://wiki.asra.gr/en:public_servers", a "Synapse 1.66.0" is running at digitale-gesellschaft.ch.

**Comment by MatMaul** [comment]
It may be related to a broken purge, closing for now since it is solved on your side and it would be quite complicated to investigate.
