### ISSUE TITLE
Allow server administrators to modify `account_data`

### ISSUE THREAD

**Issue by villepeh** [matrix-org/synapse#15627]
**Description:**

I’d like if the admin account_data API was extended to allow setting account data. It currently only supports viewing the account data. 

The only way to set account data is currently by using `PUT /_matrix/client/v3/user/{userId}/account_data/{type}` as defined here: [Matrix API](https://matrix.org/docs/api/#put-/_matrix/client/v3/user/-userId-/account_data/-type-) 

I don’t know how many practical uses this would have but I’d need it to add [Stickerpicker](https://github.com/maunium/stickerpicker)  stickers for other users.

As a workaround I’ve simply modified this line on [account_data.py](https://github.com/matrix-org/synapse/blob/4ec40b16ac2436387d5d947308e5dc37857acbf6/synapse/rest/client/account_data.py#L241) 

```python
if user_id != requester.user.to_string():
```
```python
if user_id != requester.user.to_string() and requester.user.to_string() != “@adminaccount:myserver.tld”:
```

https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#account-data

**Comment by reivilibre** [comment]
You can use https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#login-as-a-user in order to issue an access token (temporary, if you'd like) for the user and then use the regular CS API endpoints to manipulate account data.

**Comment by villepeh** [comment]
Ah I can't believe I forgot about that one. Yes, when I first coded a script to do it, the script created access tokens for all users that didn't have the corresponding account_data and then used the CS API to do the rest.

After I had some (unrelated to Synapse) data loss and had to rewrite the script, I just used the hack mentioned in the original post, bypassing the access token generation and admin API completely as it was much easier to write. With the hack it's pretty much the same as using the admin API (if the API endpoint was implemented) since it accepts my access token as well as their own.

**Comment by reivilibre** [comment]
I think I will close this; it's maybe not unreasonable as a request but then it's probably a lot of duplication in the long run to start coping more and more CS API endpoints to the admin API when there is already the 'login as user' escape hatch, which coincidentally means you can then give the access token to and use a normal Matrix client.
