### ISSUE TITLE
[v1.88.0] Remove `worker_replication_*` settings as they are deprecated

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#15655]
See: #15491, https://github.com/matrix-org/synapse/blob/release-v1.84/docs/upgrade.md#upgrading-to-v1840

**Comment by realtyem** [comment]
It's about this time. Can someone fix-up Sytest please?

**Comment by erikjohnston** [comment]
@realtyem What's left to do on this issue?

**Comment by realtyem** [comment]
I believe it's ok to close this.
