### ISSUE TITLE
Avoid `/backfill` when we already have enough messages to return for a `/messages` response

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#15696]
Avoid `/backfill` when we already have enough messages to return for a `/messages` response

As you can see from the trace, if we were somehow smart enough to know not to `/backfill`, we would save ourselves 14s from that 16.42s request. In this example, there is only a single new event out of the 100 returned in the `/backfill` response that is "new" to us and it's one that already has failed pull attempts so we end up skipping it anyway because of expontential backoff. This is definitely a candidate where we didn't need to `/backfill`!

[Full Jaeger trace JSON](https://gist.github.com/MadLittleMods/ac593674b2f620b17338d6ac90e8f762)

![](https://github.com/matrix-org/synapse/assets/558581/550e9e22-4adc-4de9-9837-2e50dc7af73d)

### Questions

What kind of heuristic can we use to know that we have *enough* messages to respond to `/messages` request? In other words, it's fine to have small holes (especially with cases where we've attempted to fill the hole before) but if we're missing a big chunk of history, then we probably should try `/backfill`.

Perhaps we can look at the depth of the continuous set of messages and if there isn't too big of a gap between them, we can consider it good enough. Maybe potentially still trigger a `/backfill` in the background so things can become eventually consistent.

**Comment by clokep** [comment]
I know very little about backfill, so maybe this is a dumb question: do we kick off backfills in the background when we're getting "close" to the end of what we know as a server, or do we wait for it to be requested by a client?
