### ISSUE TITLE
Github pages docs: include Synapse version on the page somewhere other than the URL

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#15692]
I can't see anywhere on https://matrix-org.github.io/synapse/v1.74 which tells you that the docs are for v1.74, nor any kind of version selector to navigate between different versions. Related: https://github.com/matrix-org/matrix-spec/issues/951

**Comment by clokep** [comment]
Related to #11647.

**Comment by Dmytro27Ind** [comment]
@DMRobertson @clokep 
Hello. I'd like to contribute to this issue. Is this issue closed?  If it's still open, can you assign it to me?
I've tried adding version picker to the docs and now it looks like this:

<div style="display: flex;">
  <img src="https://github.com/matrix-org/synapse/assets/68487610/49765821-5073-4c7e-8f0c-db1fc015d46f" alt="ver-picker-1" width="250">
  <img src="https://github.com/matrix-org/synapse/assets/68487610/86e03204-3f75-4de7-8d7c-eb6c3c4da176" alt="ver-picker-2" width="250">
  <img src="https://github.com/matrix-org/synapse/assets/68487610/5345345c-1486-4b9d-8519-f0c5fa0ca703" alt="ver-picker-3" width="250">
</div>

**Comment by DMRobertson** [comment]
The issue is not closed. We prefer to only assign issues to members of the synapse-core team, but this does not stop you from contributing a PR. We would gladly review any proposed changes!
