### ISSUE TITLE
Several thousands occurrences of `Invalid access token in auth: <class 'pymacaroons.exceptions.MacaroonDeserializationException'> cannot determine data format of binary-encoded macaroon.`

### ISSUE THREAD

**Issue by sergiodj** [matrix-org/synapse#15742]
### Description

I've been running my own homeserver for a few days now, and I noticed that there is this barrage of warning messages in the log files for synapse.  I don't know exactly what might be happening; I have joined less than a dozen rooms and they're all relatively small.

### Steps to reproduce

- I'm using the matrix-docker-ansible-deploy project.
- I installed synapse and started using it normally.
- The only non-trivial thing I did recently was to migrate the server from one machine to another.  But I was getting these warning messages before.

### Homeserver

https://matrix.sergiodj.net

### Synapse Version

1.84.1

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Single process

### Platform

Debian 11 GNU/Linux, running on a VPS (Hetzner) with 4GB of RAM and 3 vCPUs.

### Configuration

Nothing special.  I'm running `mautrix-telegram` as well, but that's not a synapse module AFAIK.

### Relevant log output

```shell
Jun 07 16:22:23 matrix matrix-synapse[47412]: 2023-06-07 16:22:23,421 - synapse.api.auth - 448 - WARNING - GET-263096 - Invalid access token in auth: <class 'pymacaroons.exceptions.MacaroonDeserializationException'> cannot determine data format of binary-encoded macaroon.
```

### Anything else that would be useful to know?

Since I restarted my homeserver yesterday, I've seen several thousands of the warnings listed above.

**Comment by sergiodj** [comment]
After some investigation, I found that the problem was happening elsewhere in my infrastructure.  Sorry about the noise.

**Comment by liemlylac** [comment]
What is your problem? What you do to resolve it?
