### ISSUE TITLE
Docs: Bad link on the faster room joins page

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#15756]
In https://matrix-org.github.io/synapse/develop/development/synapse_architecture/faster_joins.html, there's a mention of "MSC706". Two issues with this bit:

* The link goes to MSC3902, which is already linked to in the line above
* https://github.com/matrix-org/matrix-spec-proposals/pull/706 does not seem to be an MSC, it looks like that bit too is a typo meant to refer to MSC3706 instead?

**Comment by anoadragon453** [comment]
I think you're correct, but cc @DMRobertson as the original author of the page for clarity.

**Comment by DMRobertson** [comment]
Yep, it was definitely meant to be 3706; probably just my sausage fingers at fault.
