### ISSUE TITLE
Federation problems with reverse proxy and port 8448

### ISSUE THREAD

**Issue by michelleDeko** [matrix-org/synapse#15771]
Hello,

I installed Matrix on my server today with the domain `matrix.domain.org`. I just realized, that my server isn't federating, so I tried the Matrix Federation tester with `matrix.domain.org`.

Well, it seems like port `8448` isn't reachable. So I tried adding a VirtualHost in the Apache config of Matrix. I then started to search for solutions and found following thread: https://github.com/matrix-org/matrix-federation-tester/issues/93. I tried understanding it, but it seems like I'm missing something. As far as I understood, I somehow need to make a reverse proxy on my domain `domain.org` with port `8448`, redirects to `8008`?

I tried it and it doesn't work. I also should mention that my homepage (`domain.org`) is behind Cloudflare, but my Matrix server is not. 

Here are my two Apache2 configs. One for matrix, one for my "main page".

 - `domain.org`: https://ghostbin.me/648766326d471
 - `matrix.domain.org`: https://ghostbin.me/648765ca08840
 - Matrix config: https://ghostbin.me/64876afd2fd04

Does anyone have tips how I can fix that? I installed Matrix via docker.

**Comment by MatMaul** [comment]
Sorry but we don't do support here, you can ask help in #synapse:matrix.org.
