### ISSUE TITLE
Gracefully drop MSC2716 related tables (incrementally import history)

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/synapse#15786]
Gracefully drop MSC2716 related tables (incrementally import history) in multiple steps/phases.

### Step 1

In one Synapse version, stop writing to any MSC2716 related tables. The normal [steps to gracefully drop a table](https://github.com/matrix-org/synapse/blob/fcc3ca37e1b404981d9a0d6f2708e14407775b97/docs/development/database_schema.md) usually include a step to first switch over reads but keep writing but since this is a experimental feature, we don't need to worry about the feature working we can just stop reading and writing in the same step.

This is being tackled in https://github.com/matrix-org/synapse/pull/15748

### Step 2

In the Synapse release after the first step ships, we can bump `SCHEMA_COMPAT_VERSION` and drop the tables altogether.

Relevant tables to drop:

```sql
-- Drop tables related to MSC2716 since the implementation is being removed
DROP TABLE insertion_events;
DROP TABLE insertion_event_edges;
DROP TABLE insertion_event_extremities;
DROP TABLE batch_events;
```

**Comment by clokep** [comment]
See #16465
