### ISSUE TITLE
Upload limit should not apply over federation

### ISSUE THREAD

**Issue by timokoesters** [matrix-org/synapse#15792]
### Description

There's a lot of confusion when a user on server B can't view media from server A. Often it's caused by the upload limit of server B being too low. But why does the upload limit even apply? The server could just stream the media from server A or cache it for a short duration. It's even worse that clients don't show any indication of this error, they are just stuck showing a loading indicator.

### Steps to reproduce

- Upload video on server A
- Try to watch video on server B with lower upload limit

### Homeserver

fachschaften.org

### Synapse Version

1.85.2

**Comment by richvdh** [comment]
related/nearly a duplicate of https://github.com/matrix-org/synapse/issues/3918

**Comment by timokoesters** [comment]
Ah you're right, I couldn't find that. Unfortunately there hasn't been any update since 2018

**Comment by clokep** [comment]
Sounds like there's agreement this is a duplicate.

**Comment by MadLittleMods** [comment]
Related to https://github.com/matrix-org/synapse/issues/15489
