### ISSUE TITLE
Avoid auto joining of people

### ISSUE THREAD

**Issue by alekslyse** [matrix-org/synapse#15795]
I am not sure what to call this, but I am running a Synapse homeserver, installed with the default [Beeper self-hosted instructions](https://github.com/beeper/self-host/blob/dc95f18826cb0d4cfd204fc5ae4db1094f6495c9/README.md#self-host-install-guide), in other words almost a basic Ansible playbook.

The thing I am experiencing is I for example start a chat in Discord though any app (but in this case testing element), it works well, then suddenly it starts to open new chats with that person, that also got a matrix account, making the messages to be duplicated through more than one "channel". Is it possible to stop this behavior?

In the app this is auto-made: "Tony and one other were invited and joined", so I have to manually leave those chats to not get duplicate messages.

**Comment by MadLittleMods** [comment]
@alekslyse If you're getting joined to any rooms and message are incoming, this feels like it's specific behavior of the bridges you're using.

@Fizzadar @tulir any insight whether this is relevant to Synapse itself?
