### ISSUE TITLE
Version 1.86 breaks Element-IOS: All texts are red

### ISSUE THREAD

**Issue by jacotec** [matrix-org/synapse#15810]
### Description

Synapse version 1.86 causes all texts in Element-IOS to be in red, like you are mentioned (but you aren't).

https://github.com/vector-im/element-ios/issues/7601

This is highly annoying, hoping for a hotfix.

### Steps to reproduce

- Upgrade Synapse from 1.85.2 to 1.86
- All messages in Element-IOS are red now

### Homeserver

Own homeserver

### Synapse Version

1.86.0

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL

### Workers

Single process

### Platform

Ubuntu 22.04 LTS Server

### Relevant log output

```shell
no relevant logs, Synapse itself is running
```

### Anything else that would be useful to know?

![image](https://github.com/matrix-org/synapse/assets/3321655/be5cb1cc-b5b4-4f92-861b-e57041951c18)

**Comment by Johennes** [comment]
The client-side fix for this has been merged with https://github.com/matrix-org/matrix-ios-sdk/pull/1799.

**Comment by MadLittleMods** [comment]
@Johennes Is this a spec bug, Synapse bug? Any more context you've gathered while making the client-side fix?

**Comment by Johennes** [comment]
Oh, this was a pure client issue. Before the fix, the iOS app would skip over push rule conditions it didn't know and continue with the next one.

So in

```
{
    "rule_id": ".m.rule.is_room_mention",
    "default": true,
    "enabled": true,
    "conditions": [
        {
            "kind": "event_property_is",
            "key": "content.m\\.mentions.room",
            "value": true
        },
        {
            "kind": "sender_notification_permission",
            "key": "room"
        }
    ],
    "actions": [
        "notify",
        {
            "set_tweak": "highlight"
        }
    ]
}
```

it skipped over the first condition because it doesn't know `event_property_is` but then still continued with the second condition. When the latter matched, it considered the whole rule matching which effectively made every message a room mention.

**Comment by Johennes** [comment]
The client fix ha been released in a patch last week. So I think we can close this.
