### ISSUE TITLE
Stop automatically creating new rooms

### ISSUE THREAD

**Issue by alekslyse** [matrix-org/synapse#15819]
I have setup matrix with Ansible, quite straightforward setup, but have a couple of issues.

First when talking with a person on discord that also have a Matrix account, Matrix is creating new rooms randomly. This is just happening with the user that also have a matrix account. How is it possible to stop this? See screenshot 

Also all the online stats is grey, even if the user status say online.

Third is it possible to have a notification in the room where someone is typing? (For example “aleks typing…”

![Screenshot_2023-06-23-12-31-09-46](https://github.com/matrix-org/synapse/assets/3678663/ec3f75b4-bdda-4aac-91f9-b78e132fb574)

**Comment by MadLittleMods** [comment]
Feels like this is a duplicate issue of the other issue you created -> https://github.com/matrix-org/synapse/issues/15795

> Also all the online stats is grey, even if the user status say online.

If [presence](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#presence) is disabled on the server, all users will appear offline.

> Third is it possible to have a notification in the room where someone is typing? (For example "aleks typing…")

Typing notifications are sent as ephemeral (EDU) events. It seems like it would be up to your client to generate a notification or not.
