### ISSUE TITLE
Room server thinks user in room, but user's homeserver thinks it's not

### ISSUE THREAD

**Issue by JeanPaulLucien** [matrix-org/synapse#15828]
### Description

Issue was reproduced using the homeservers: `tzchat.org`, `flip.earth`, `asra.gr`.
Task is join to `#test:zemos.net`.
Room are sure we are joined. Room shows nicks in room users list. Client-side does not show room in room list and you can't join because gets 403 error about event.

In fact everybody who really in room are sure these users in room too, because they see their nicks in room. No way to join, because all servers are sure that users in room. I mean users that used server with this issue can't join, room admins shall kick them, but they do not know about this issue.

### Steps to reproduce

1. Have not matrix.org account
2. Try to join #test:zemos.net
3. You get error.
4. Try again.
5. You get 403 error code.

### Homeserver

various

### Synapse Version

any

### Installation Method

I don't know

### Database

I don't know

### Workers

I don't know

### Platform

I don't know

### Relevant log output

```shell
not provided
```

**Comment by MadLittleMods** [comment]
@JeanPaulLucien What is the MXID in question here?

It's unclear what homeservers think that user is in the room vs which do not. Can you please clarify?

`#test:zemos.net` (`!AAAANTUiY1fBZ230:zemos.net`) has `m.room.join_rules` of `public` so I don't see how that could give a a `403 Forbidden` response unless the user is banned or was banned previously and you're running into https://github.com/matrix-org/synapse/issues/1563 which is fixed as of Synapse 1.81.0 (2023-04-11).

When you say `modular.im` as a homeserver, which EMS homeserver are you talking about specifically?

 - [`flip.earth`](https://flip.earth/.well-known/matrix/client): https://matrix.flip.earth/_matrix/federation/v1/version -> `{"server":{"name":"Synapse","version":"1.86.0"}}`
 - [`asra.gr`](https://asra.gr/.well-known/matrix/client) -> https://asra.gr/_matrix/federation/v1/version `{"server":{"name":"Synapse","version":"420*69"}}` (dodgy unclear version)
 
 Given that this is the Construct testing room, are these all Synapse servers we're talking about?

**Comment by H-Shay** [comment]
MXID is shorthand for matrix id, the question (I assume) is: what's the matrix id of the user in question. 

> The first attempt user receives another error code.

What is the first error code/message received?

**Comment by JeanPaulLucien** [comment]
> What is the first error code/message received?

I do not remember.

**Comment by reivilibre** [comment]
Do you have a full error message, not just 403?

**Comment by reivilibre** [comment]
There doesn't seem to be enough information here in order to reproduce or fix this issue right now.

I will close this issue but it can be reopened (or a new issue, linking to this one, opened) if the issue recurs with more information available.

Thank you.
