### ISSUE TITLE
update link to Matrix clients in the Synapse default web page

### ISSUE THREAD

**Issue by mizerek** [matrix-org/synapse#15825]
### Description

after installing synapse via snap, the home page displays a link to the matrix website that is broken:

https://matrix.org/docs/projects/try-matrix-now.html#clients

correct link should be:

https://matrix.org/ecosystem/clients/

### Steps to reproduce

install synapse via apt install matrix-synapse-py3

visit home page

click on incorrect link

get frustrated, google "matrix clients"

click on correct link

### Homeserver

https://synapse.ownyourdata.site/_matrix/static/

### Synapse Version

{"server_version":"1.86.0","python_version":"3.10.6"}

### Installation Method

Other (please mention below)

### Database

i don't know, irrelevant

### Workers

Single process

### Platform

bare metal fresh install ubunutu 22.04 via `apt-get install matrix-synapse-py3 -y`

### Relevant log output

```shell
none
```

### Anything else that would be useful to know?

Century Blvd. in Los Angeles was named that because it would be 100th street. seriously, look at a map.

**Comment by DMRobertson** [comment]
As of matrix-org/matrix.org#1892 the link https://matrix.org/docs/projects/try-matrix-now.html#clients should be fixed.

We should still be good citizens, though, and update Synapse to point to https://matrix.org/ecosystem/clients/ .

**Comment by thibaultamartin** [comment]
A redirect has been added on the website to unbreak it, but it's still worth updating the link to the new "canonical" place :)

**Comment by mizerek** [comment]
> As of [matrix-org/matrix.org#1892](https://github.com/matrix-org/matrix.org/pull/1892) the link https://matrix.org/docs/projects/try-matrix-now.html#clients should be fixed.
> 
> We should still be good citizens, though, and update Synapse to point to https://matrix.org/ecosystem/clients/ .

should it point to Matrix?
