### ISSUE TITLE
email confirmation page has broken Matrix image

### ISSUE THREAD

**Issue by mizerek** [matrix-org/synapse#15829]
### Description

when a user registers on a synapse server and email confirmation is required, the email they receive contains a broken link to an image from matrix.org:

`<img src="https://matrix.org/img/matrix-120x51.png" width="120" height="51" alt="[matrix]" />`

shouldn't this be configurable?

### Steps to reproduce

register for a new account on a synapse server that requires email confirmation.

when you click on the link to confirm your email you're taken to a page that processes the confirmation, then advises you to close the page and continue in your client.

this page refers to a Matrix logo that is not found.

### Homeserver

https://synapse.ownyourdata.site/_matrix/static/

### Synapse Version

1.86

### Installation Method

Debian packages from packages.matrix.org

### Database

whatever default is

### Workers

I don't know

### Platform

ubuntu 22

### Configuration

ootb

### Relevant log output

```shell
there's no log output but here's a link that should recreate the error:

https://synapse.ownyourdata.site/_matrix/client/unstable/registration/email/submit_token?token=1&client_secret=1&sid=1
```

### Anything else that would be useful to know?

nah

**Comment by DMRobertson** [comment]
Presumably a consequence of the matrix.org redesign. Related: #15825.
