### ISSUE TITLE
Windows don't support Synapse?

### ISSUE THREAD

**Issue by best2160187** [matrix-org/synapse#15843]
**Description:**
I am going to add WebAuthN to Synapse server and using Windows 10.
How to install the server on my PC.

Please give me step by step guide.

**Comment by JeanPaulLucien** [comment]
> [Windows](https://matrix-org.github.io/synapse/latest/setup/installation.html#windows)
> Running Synapse natively on Windows is not officially supported.
> 
> If you wish to run or develop Synapse on Windows, the Windows Subsystem for Linux provides a Linux environment which is capable of using the Debian, Fedora, or source installation methods. More information about WSL can be found at https://docs.microsoft.com/en-us/windows/wsl/install for Windows 10/11 and https://docs.microsoft.com/en-us/windows/wsl/install-on-server for Windows Server.

**Comment by clokep** [comment]
As mentioned, Windows is not a supported platform. I think some folks have gotten it running under WSL2, I'm not sure if that would help or not though.

I suspect we would be unlikely to want to officially support Synapse on Windows, but I think we would probably accept simple patches if needed.
