### ISSUE TITLE
Add http header Retry-After to error 429 response

### ISSUE THREAD

**Issue by ThomasHalwax** [matrix-org/synapse#15840]
**Description:**

I'm using [Ky](https://github.com/sindresorhus/ky#retry) to make calls to the Matrix API. Whenever I receive a `rate-limited` error with status code `429` I'm forced to parse the body of the error in order to retrieve the value for `retry_after_ms` before doing the next request.

Ky has a built in retry mechanism and honors the http header [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) that represents either an absolute date/time or a delay in seconds.

Can you please add the appropriate http header to 429 errors? I'm using Synapse v1.82 in a dockerized setup.

Thanks,
Thomas

**Comment by MadLittleMods** [comment]
It looks like this was suggested before in https://github.com/matrix-org/synapse/issues/7138 where it was suggested that this needs to be spec'ed out or in a [MSC](https://github.com/matrix-org/matrix-spec-proposals) before we can move forward. Seems like a nice short MSC to write so we can use the standardized header if you're interested.

Also mentioned in https://github.com/matrix-org/matrix-spec/issues/44#issuecomment-1055643519

**Comment by ThomasHalwax** [comment]
@MadLittleMods I have written a MSC proposal [Use http header Retry-After to enable library-assisted retry handling](https://github.com/matrix-org/matrix-spec-proposals/pull/4041) to introduce the http header `Retry-After`. Would you please read it? It is my first MSC and I would be very happy about feedback.

Thanks!
