### ISSUE TITLE
Build packages for Debian Trixie

### ISSUE THREAD

**Issue by sigwinch28** [matrix-org/synapse#15857]
Please can we publish packages to the apt repository for [Debian Trixie (13)](https://wiki.debian.org/DebianTrixie) which is the current testing release at the time of writing. It became the current testing release on 2023-06-10.

I run debian testing on the server I run synapse on and the change from bookworm to trixie has meant that I now get errors on `apt update`:

```
E: The repository 'https://packages.matrix.org/debian trixie Release' does not have a Release file.
```

**Comment by clokep** [comment]
See #15362 for what needs to be done here.
