### ISSUE TITLE
Cannot upload file to the room

### ISSUE THREAD

**Issue by 2kvasnikov** [matrix-org/synapse#15875]
### Description

Matrix-synapse installed from package on Ubuntu 11. Server placed in isolated LAN without Internet connection. Internal DNS configured and workable
Element client allows me to register my username and password. I am able to chat, sent emoji, make audio and video calls.
I cannot post any file to the room from Android client. It shows, that file uploading in a progress but never finished.
From windows Element client I am able to post files to the same room.

### Steps to reproduce

1. Setup matrix-synapse on the LAN not connected to the Internet
2. Open any chat on Android
3. Upload any file or make photo or record short message
4. File cannot be uploaded

### Homeserver

matrix.protected.local

### Synapse Version

{"server":{"name":"Synapse","version":"1.86.0"}}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

SQLite

### Workers

Single process

### Platform

Debian 11 + docker + Synapse as a container + nginx proxy

### Configuration

enable_registration: true
enable_registration_without_verification: true
trusted_key_servers: []
federation_domain_whitelist:
max_upload_size: 50M

### Relevant log output

```shell
I am not sure how to collect logs on docker.
My logs when I try Synapse from package don't show any errors.
On docker I cannot even find logs. Please advise how to collect it.
```

**Comment by H-Shay** [comment]
> I cannot post any file to the room from Android client.

Just to be clear, are you referring to the element android client - (I am assuming "windows Element client" means the element web client)? If this is the case I would suggest rageshaking and note that the upload is stuck - I am suspicious that this might be an Android client bug, especially since uploads seem to work from other clients.

**Comment by H-Shay** [comment]
As far as how to access the logs in Docker, it looks like the proper incantation is `docker logs synapse`:
https://github.com/matrix-org/synapse/blob/39d131b016673bbd4d3c28095c8838b8c6dc0953/docker/README-testing.md?plain=1#L110-L114. 

If you can provide logs from the exact time that you tried and failed to upload in Android it would help to rule out (or in) and issues from the Synapse side.

**Comment by H-Shay** [comment]
I am going to close this issue for now as it is not actionable without more information, happy to re-open if more information is forthcoming.
