### ISSUE TITLE
Add support for disallowing unencrypted rooms / making all rooms encrypted

### ISSUE THREAD

**Issue by telmich** [matrix-org/synapse#15916]
**Description:**

There are projects with high security requirements that require all data at rest to be encrypted. At the moment it is not possible to configure synapse to force all newly created rooms to be encrypted.

From what I can see there are several events that turn a room into an encrypted room, so it is not trivial to add a middleware in front of synapse to simple filter room creation requests and simple change a flag from `encrypted: false` to `encrypted: true`, but the middleware would need to watch and follow the room creation and check whether it is not changed to encrypted by the following state events.

Thus the proposal is to add a new flag into synapse that either

- a) disallows creating unecrypted rooms (user gets an error, needs to retry with encryption enabled)
- b) automatically encrypts all newly created rooms

I would reason that (b) would be the preferred option, as it reduces the necessary support requests from users and achieves the wanted result in the first place.

**Comment by dklimpel** [comment]
Do you have seen this setting?
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#encryption_enabled_by_default_for_room_type

**Comment by reivilibre** [comment]
Agreed with dklimpel here, I believe this is already possible. If mistaken, let me know and can reopen. :)
