### ISSUE TITLE
Does the chat room have a message sticky function?

### ISSUE THREAD

**Issue by niudin** [matrix-org/synapse#15930]
Please don't file github issues asking for support.
What I need: select a message and press and hold it to have the function of sticking the message to the top
Does the API have this feature now?
Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.

**Comment by DMRobertson** [comment]
The closest thing to what you're describing is either setting a [room topic](https://spec.matrix.org/v1.7/client-server-api/#mroomtopic) or a [pinned message]( https://spec.matrix.org/v1.7/client-server-api/#mroompinned_events). Synapse supports both of these.

How this is exposed in the user interface (e.g. "press and hold") is a decision that clients need to make, not Synapse; you should ask them for advice here.

Additionally: we're using Github's issue tracker for bug reports and feature requests. Per the issue template:

> Please don't file github issues asking for support.
> Instead, please join [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org)
> (from a matrix.org account if necessary), and ask there.

(see also #15894).

**Comment by niudin** [comment]
https://spec.matrix.org/v1.7/client-server-api/#mroompinned_events > Can it
be called through the API interface

David Robertson ***@***.***> 于2023年7月13日周四 18:00写道：
