### ISSUE TITLE
Prototype Linearized Matrix

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#15954]
Prototype the [Internet Draft draft-ralston-mimi-linearized-matrix](https://turt2live.github.io/ietf-mimi-linearized-matrix/draft-ralston-mimi-linearized-matrix.html) as a proposal for the MIMI working group. see the [list of differences from current Matrix](https://github.com/turt2live/ietf-mimi-linearized-matrix/blob/main/mx-differences.md).

Additionally we wish to demonstrate the interoperability of a DAG-capable server interconnecting with a LInearized Matrix network.

Done status: interoperable with the [eigen-server](https://github.com/matrix-org/eigen-server) from scratch implementation of Linearized Matrix:

1. Synapse should be able to act as a hub and pass events to eigen-server acting as a participant
    * Inviting a user on eigen-server.
    * Sending messages to a user on eigen-server.
    * Receiving messages from a user on eigen-server.
    * Sending state events to a user on eigen-server.
    * Receiving state events from a user on eigen-server.
2. Synapse should act as a link between a Linearized Matrix network and the wider Matrix network.
    * Events from a DAG should be linearized and sent to eigen-server
    * (TODO)

**Comment by clokep** [comment]
(Placeholder for v0)

**Comment by clokep** [comment]
Current status is updating this for v02 of the I-D, this is happening on the same [`clokep/lm`](https://github.com/matrix-org/synapse/compare/develop...clokep/lm) branch as before. (Note that I've been rebasing this branch so it likely isn't the best to track.)

My overall goal is to get things working with it being OK if it is a bit hacky. (I.e. I'm not planning for this branch to be a pull request.) Once we're confident in the design and the proposed I-D then we'll want to break this branch up into a bunch of PRs with associated MSCs.

----

* [x] Update hashing algorithm for v02
* [x] Handle content hashes for LPDUs
* [x] Remove references to `m.room.hub` events
* [x] Remove `depth` and `unsigned` on events for LM
* [x] Implement new endpoints:
  * [x] `/invite`
  * [x] `/send`
  * [x] `/event`
  * [x] `/backfill`
  * [x] `/send_join`
  * [x] `/send_leave`
  * [x] `/send_knock`
  * [x] `/device`
* [ ] Call new endpoints
  * [x] `/invite`
  * [x] `/send`
  * [x] `/event`
  * [x] `/backfill`
  * [x] `/send_join`
  * [x] `/send_leave`
  * [x] `/send_knock`
  * [ ] `/device`
* [x] Handle new EDU format
* [ ] Accept LPDUs
  * [ ] `/send`
  * [ ] `/send_join`
  * [ ] `/send_leave`
  * [ ] `/send_knock`
* [ ] Return LPDUs
  * [ ] `/make_join`
  * [ ] `/make_leave`
  * [ ] `/make_knock`
* [x] Fan-out PDUs to any participant servers (i.e. act like a hub)
* [ ] Forward invites between participants (see matrix-org/eigen-server#33)
* [ ] Fix-up device handling logic

**Comment by clokep** [comment]
The testing steps I've been using for this are:

1. Checkout `clokep/lm`
2. Run a local Synapse (mine is at 8480 using the demo scripts): `python -m synapse.app.homeserver --config-path demo/8080/8080.config`
3. Checkout [eigen-server](https://github.com/matrix-org/eigen-server) and get that setup.
4. Run eigen-server `ES_PORT=3000 ES_SIGNING_KEY_PATH=./p3000.signing.key yarn dev:server`
5. Run eigen-server's client: `ES_PORT=3000 yarn dev:client:nobuild` (must wait for step 4 first)
6. Open Element Web
7. Register/login (`@alice:localhost:8480` for me).
8. Create an (unencrypted) room
9. Upgrade the room to get the proper version: `/upgraderoom org.matrix.i-d.ralston-mimi-linearized-matrix.02` in Element Web
10. Join the new room
11. Invite the remote user (eigen-server prints out your username when you start the client): `/invite @<uuid>:localhost:3000`
12. In the eigen-server client accept the invite with `/join <room ID>`
13. Start chatting

**Comment by turt2live** [comment]
backref for https://github.com/matrix-org/synapse/issues/15962 and https://github.com/matrix-org/synapse/issues/15963 as "discovered during LM interop testing". They are both fixed on the `clokep/lm` branch, without tests.

**Comment by clokep** [comment]
I think I'm going to call this "done" for now until a new draft of MIMI comes out.

You can see results in an [This Week in Matrix from August 4, 2023](https://matrix.org/blog/2023/08/04/this-week-in-matrix-2023-08-04/).
