### ISSUE TITLE
Room version 11 & MSC2176: Only preserve entirety of `content` instead of whole event

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#15963]
### Description

At https://github.com/matrix-org/synapse/blob/67f9e5293ea6650b2ec284c0b7503f3f3eade94b/synapse/events/utils.py#L141 the entire event, unredacted, is returned in v11 rooms, which is not what [MSC2176](https://github.com/matrix-org/matrix-spec-proposals/issues/2176) calls for. 

From the MSC (emphasis mine):

> The following are to be added to the list of **subkeys of the content property** which are preserved:
> 
>  * `m.room.create` preserves *all* content. [...]

Therefore, we should be keeping `content` unredacted but otherwise removing other fields.

### Context

This came up as part of Linearized Matrix interop testing. Synapse still includes `origin` on outbound events though under v11 they are supposed to be redacted as they serve no meaningful purpose in modern room versions. Because of the `return` mentioned above, Synapse was *not* redacting `origin` off the create event, but *was* redacting it off all other events. This lead to signature errors when not-Synapse was trying to implement the LM room version (which is v11 plus stuff not relevant here).

**Comment by turt2live** [comment]
https://github.com/matrix-org/synapse/commit/1e77a62c1d011d51a722443ffedeeca3cfb8d440 fixes this without tests (and the conversation mentioned in the commit description is resolved [here](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$yuyN5W5_vWm8_1CyNdW3Na8z7IeSBs8liB2czYuUKII?via=matrix.org&via=libera.chat&via=element.io))

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/15973.
