### ISSUE TITLE
about member send link switch function

### ISSUE THREAD

**Issue by niudin** [matrix-org/synapse#15966]
Please don't file github issues asking for support.
Add a member sending link switch function on the group profile page. When it is turned off, group members cannot send link messages (except administrators). When it is turned on, everyone in the group can send
  Is there this function?
Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.

**Comment by reivilibre** [comment]
Hi there,

As the box should say when you open an issue, please don't use the issue tracker for support questions.

You can more easily find help in the Synapse Admins room: **[#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org)**.

This helps us keep this issue tracker dedicated to bugs and similar issues.

Thank you.
