### ISSUE TITLE
Garbage collect unusable rooms and spaces

### ISSUE THREAD

**Issue by DemiMarie** [matrix-org/synapse#15978]
**Description:**
If a room, space, or other entity has no members, is not visible to anyone who is not currently a member, and has no invites outstanding, then it is not possible for anyone to ever join the room or space.  Therefore, the room or space will never be used again and can be garbage collected.

**Comment by DMRobertson** [comment]
Duplicate of #4720(?)

**Comment by DemiMarie** [comment]
Duplicate of #4720
