### ISSUE TITLE
`/_matrix/client/r0/profile` returns 404 if only displayname is not set

### ISSUE THREAD

**Issue by weeman1337** [matrix-org/synapse#16000]
### Description

If a user has been created without a displayname, requests are sent to `/_matrix/client/r0/profile` return a 404 response.

### Steps to reproduce

- Create a user without displayname but an avatar
- Try to get the profile for the user

Expected: got a response with empty displayname
What happens: 404

### Homeserver

matrix.jamesdemo.ems-support-self-serve.element.io

### Synapse Version

1.84.0

### Installation Method

I don't know

### Database

I don't know

### Workers

I don't know

### Platform

EMS

### Relevant log output

```shell
-
```

### Anything else that would be useful to know?

Link to source https://github.com/matrix-org/synapse/blob/99b7b801c31b9428f9503ad6f83f11804fef048a/synapse/handlers/profile.py#L71

**Comment by t3chguy** [comment]
This matches the spec as I read it https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv3profileuserid

`404 There is no profile information for this user or this user does not exist.`

**Comment by clokep** [comment]
I did some quick testing and there *are* users with a null displayname and a configured avatar, so yeah this seems wrong.
