### ISSUE TITLE
Wrong links to blog categories in docs/development/releases.md

### ISSUE THREAD

**Issue by gitouche-sur-osm** [matrix-org/synapse#16005]
### Description

Hello,

Browsing through the documentation, I noticed both links in https://matrix-org.github.io/synapse/latest/development/releases.html are not correct

https://matrix.org/blog/category/releases 
should be
https://matrix.org/category/releases

and

https://matrix.org/blog/category/security
should be
https://matrix.org/category/security

Source code is at https://github.com/matrix-org/synapse/edit/develop/docs/development/releases.md

### Steps to reproduce

- In a web browsed, open https://matrix-org.github.io/synapse/latest/development/releases.html
- click on [release category of the Matrix blog](https://matrix.org/blog/category/releases) -> Not Found
- click on [security category of the Matrix blog](https://matrix.org/blog/category/security) -> Not Found

### Homeserver

matrix.org

### Synapse Version

develop

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL

### Workers

Single process

### Platform

--

### Relevant log output

```shell
-
```

**Comment by clokep** [comment]
Seems to really be an issue with the new matrix.org website: https://github.com/matrix-org/matrix.org/issues/1955

We should update the URLs, however.

**Comment by laurencegill** [comment]
https://github.com/matrix-org/matrix.org/pull/1958 fixes the matrix.org website for these links
