### ISSUE TITLE
Option to disable certificate validation when sending email

### ISSUE THREAD

**Issue by zusso1** [matrix-org/synapse#16041]
Is there a 'do not verify certificate' option that can be set for other services?
Currently Synapse does not have that setting, so emails cannot be sent on the mail server used.

When we set it to other SMTP servers, we are able to send, so we do not think there is a problem with the Synapse settings.

**Comment by DMRobertson** [comment]
> emails cannot be sent on the mail server used.

This sounds like:

- your SMTP server's certificate isn't trusted by Synapse, and
- you need to configure the machine you're running Synapse on to trust the certificate.

It can be a little tricky to do this if you're running Synaose via a docker container. It's probably best to ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room for help and advice.

Having said that:

> Is there a 'do not verify certificate' option that can be set for other services?

Synapse's config options relating to email are described [here](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#email). There is an `enable_tls` option which can be set to `false`. I am no expert on security, but I would avoid doing this unless you fully control and trust your SMTP server, (plus all of the infrastructure between it and your homeserver).
