### ISSUE TITLE
Upgrading a room (to v11?) produces an invalid `m.room.create` event

### ISSUE THREAD

**Issue by pixlwave** [matrix-org/synapse#16050]
### Description

We've had a report of Element iOS crashing when opening rooms that are v11 (https://github.com/vector-im/element-ios/issues/7633). I've tracked this down to the room's `m.room.create` event missing the `creator` string. The [spec](https://spec.matrix.org/v1.7/client-server-api/#mroomcreate) seems to indicate that this is a required property.

### Steps to reproduce

- Open an existing room (not v11) in Element Web.
- Send `/upgrade 11` into to the room to upgrade it.
- Open the devtools and inspect the `m.room.create` event.
- Notice the required `creator` field isn't present.

### Homeserver

matrix.org

### Synapse Version

{"server_version":"1.89.0rc1 (b=matrix-org-hotfixes,42ec11ae56)","python_version":"3.11.4"}

### Installation Method

I don't know

### Database

I don't know

### Workers

I don't know

### Platform

I don't know

### Relevant log output

```shell
An upgraded room:


{
  "content": {
    "predecessor": {
      "event_id": "$T0Ufk2Egroh__UEYLJTlDij6ocRnr8De-GGKXtJfD2k",
      "room_id": "!WKiEIISPfQzUiDJzhS:matrix.org"
    },
    "room_version": "11"
  },
  "origin_server_ts": 1690970761964,
  "sender": "@iosdevsim:matrix.org",
  "state_key": "",
  "type": "m.room.create",
  "unsigned": {
    "age": 441
  },
  "event_id": "$6aoB9WDmdkN_qxRzq2nde0x5M8F1aKdey0xZ4WeqMsI",
  "room_id": "!OGmXOlBGeoyILdDDkh:matrix.org"
}
```
```


### Anything else that would be useful to know?

Just for comparison, here's a create event for a v9 room

```
{
  "content": {
    "creator": "@iosdevsim:matrix.org",
    "room_version": "9"
  },
  "origin_server_ts": 1669825203254,
  "sender": "@iosdevsim:matrix.org",
  "state_key": "",
  "type": "m.room.create",
  "unsigned": {
    "age": 21145236426
  },
  "event_id": "$d5jYmLHlk3yzz0isn8mL9QpRa87isjUA-35zmtcRQeg",
  "room_id": "!YCpieHsogoKpVyPLWg:matrix.org"
}
```

**Comment by pixlwave** [comment]
Also adding that the same room on Element X shows an unsupported event error:
![Screenshot 2023-08-02 at 11 53 41 am](https://github.com/matrix-org/synapse/assets/6060466/16347d40-47be-4122-b4d1-a79032fc405b)

**Comment by clokep** [comment]
[Room version 11](https://github.com/matrix-org/matrix-spec-proposals/pull/3820) no longer has a `creator` property, see [MSC2175](https://github.com/matrix-org/matrix-spec-proposals/pull/2175). (The [in-progress spec PR](https://github.com/matrix-org/matrix-spec/pull/1604) can be viewed at https://pr1604--matrix-spec-previews.netlify.app/rooms/v11/).

**Comment by clokep** [comment]
(CC @turt2live -- hopefully this isn't a widespread issue for clients.)

**Comment by pixlwave** [comment]
Ah ok, that makes sense now. Thanks 👍
