### ISSUE TITLE
Sending emails not working

### ISSUE THREAD

**Issue by matthk0309** [matrix-org/synapse#16104]
All my configuration attempts lead to nowhere. Element reports `fetch failed`, mail.log ends with `Aug 13 19:58:00 srvXYZ postfix/smtps/smtpd[31183]: connect from localhost[127.0.0.1]` and after that nothing comes, no matter if I specify correct or wrong credentials for the SMTP server.

Do I need special plugins for postfix or do I need to configure postfix additionally? I'm running out of options...

**Comment by matthk0309** [comment]
What else I forgot: matrix-synpase and postfix are running on the same server under different domains. Certificates are ok for both domains (matrix and emails). Let me know if further information is needed.

**Comment by reivilibre** [comment]
Sorry, but there isn't enough information here in this issue to help.

When opening an issue there is an issue template. Please use this template as it saves us the time to ask many of the same questions again and again.

If you have a support question, please take it to #synapse:matrix.org as requested in the issue template.

Thank you.
