### ISSUE TITLE
Metrics for MSC3861 token introspection

### ISSUE THREAD

**Issue by hughns** [matrix-org/synapse#16119]
Off the back of https://github.com/matrix-org/synapse/issues/16087 and given the dependency between Synapse and a MSC3861 OpenID Provider on an ongoing basis, it probably makes sense to expose metrics for:

- number of introspection requests
- response time
- cache hit/miss rates

**Comment by sandhose** [comment]
I would implement this as an histogram around the `synapse.api.msc3861_delegated.MSC3861Delegated#_introspect_token` method.
It should have labels to distinguish at least those states:

 - cache hit
 - cache miss, but non-2xx status code
 - cache miss, and introspection call succeeded

**Comment by erikjohnston** [comment]
Have added a response time histogram in https://github.com/matrix-org/synapse/pull/16131, which is labeled by response `code` (matching other such histograms).

We should already have cache hit/miss counter metrics by default, so I don't think we need any thing else there
