### ISSUE TITLE
Case sensitive search in non-English language

### ISSUE THREAD

**Issue by alz-aiva** [matrix-org/synapse#16130]
### Description

When you search something in russian, the search becomes case-sensitive. It can't find "Привет" if you search "привет".
https://github.com/vector-im/element-web/issues/25994

### Steps to reproduce

What did you expect?
Find "Привет" if you search "привет"

What happened instead?
Found only "привет" when searched "привет", and not "Привет"

### Homeserver

matrix.org

### Synapse Version

{"server":{"name":"Synapse","version":"1.90.0rc1 (b=matrix-org-hotfixes,94d4507d35)"}}

### Installation Method

I don't know

### Database

What matrix.org uses

### Workers

I don't know

### Platform

Matrix.org?

### Relevant log output

```shell
I don't know how to do it
```

### Anything else that would be useful to know?

https://github.com/vector-im/element-web/issues/25994

**Comment by clokep** [comment]
I think this is essentially a duplicate of #901.
