### ISSUE TITLE
Make Rooms Read-Only with Room Power Level in Matrix Synapse

### ISSUE THREAD

**Issue by ardit93** [matrix-org/synapse#16177]
Description:
I would like to request the addition of a feature in Matrix Synapse that allows administrators to make a room read-only by adjusting the room power level. This feature would provide more flexibility and control over room management, especially in scenarios where limiting participant actions is necessary for maintaining a controlled environment.

Use Case:
In various Matrix communities and organizations, there is often a need to restrict room activity to only certain individuals or at specific times. Currently, this requires manual moderation or invites-only configurations. With the proposed feature, administrators would have the ability to set a room's power level in such a way that regular participants can only read messages, preventing them from sending messages, changing room settings, or inviting others.

Feature Implementation:
To implement this feature, I suggest the following changes:

    Room Power Level Settings: Add new power level settings for "Send Messages" and "Change Room Settings." These settings would allow administrators to control who can send messages and modify room settings.

    Read-Only Mode: When "Send Messages" is set to a specific power level (e.g., 0 or a custom level), the room becomes read-only for participants below that power level. They can only read messages but cannot send messages or perform other actions that require higher power levels.

    Documentation Update: Ensure that the feature is well-documented in the Matrix Synapse documentation to guide administrators on how to use this new functionality effectively.

Benefits:

    Enhanced room management and moderation capabilities.
    Improved control over room access and activity.
    Simplified management of read-only rooms for administrative purposes.

Additional Information:
If needed, I'd be willing to collaborate on this feature request, provide further details, or assist with testing and feedback during the development process.

Thank you for considering this feature request. It would greatly improve the versatility and utility of Matrix Synapse for various communities and organizations.

**Comment by clokep** [comment]
This is already possible using the current power-levels (increase the power level required for "Send message" in the room settings). If you're suggesting a new preset, you would need to [open an MSC](https://github.com/matrix-org/matrix-spec-proposals/#matrix-specification-proposals) to modify the Matrix specification.

Please use [#synapse-admins](https://matrix.to/#/#synapse:matrix.org) or your clients support room for support requests.

**Comment by ardit93** [comment]
My bad. This is true for room admin but not for server admins
