### ISSUE TITLE
Your server is unsupported

### ISSUE THREAD

**Issue by Novgor** [matrix-org/synapse#16209]
Hello.
Client version: 1.11.40
Server version:
`root@chat:/etc/matrix-synapse# curl http://localhost:8008/_synapse/admin/v1/server_version
{"server_version":"1.31.0","python_version":"3.5.2"}`

Text error:
`Your server is unsupported
This server is using an older version of Matrix. Upgrade to Matrix v1.1 to use Element without errors.`

What requirements do I have to implement in order to continue connecting as a new client to my server?

best regards

**Comment by cremesk** [comment]
your server version is very outdated. you need to update the synapse version. (current stable release is today 1.91.0)
IIRC matrix v1.1 is supported since version 1.48.0.

**Comment by clokep** [comment]
Your server is extremely old and subject to many known security vulnerabilities. I recommend you upgrade to something modern (1.85.0 I think is the last version that has security fixes).

It looks like 1.54.0 added support for Matrix 1.1 so you'll need at least that version to use new Element Web.

Please use [synapse admins](https://matrix.to/#/%23synapse%3Amatrix.org) for any further support requests.

**Comment by DMRobertson** [comment]
> It looks like 1.54.0 added support for Matrix 1.1

This was https://github.com/matrix-org/synapse/pull/12020.

**Comment by Novgor** [comment]
Thank you very much for your answers. Went to update. It is unfortunate that the message received from the client is not informative in nature and requires your help in understanding.
