### ISSUE TITLE
Purge History API doesn't remove events from database

### ISSUE THREAD

**Issue by 4nd3r** [matrix-org/synapse#1621]
version 0.18.3-1 and postgres. events disappear in client, but stay in database.

**Comment by richvdh** [comment]
works for me.

**Comment by erikjohnston** [comment]
It won't delete local events from the db, but will remove lots of the meta
data about them. So while it doesn't remove all traces of the events, it
does dramatically reduce the on disk space usage.

**Comment by richvdh** [comment]
so notabug?

**Comment by 4nd3r** [comment]
messages content stay in database, so that's bug.

if I delete something I don't want to be there for various reasons, I expect it will be deleted, not just hidden.

**Comment by rubo77** [comment]
@Half-Shot  sais:
>I want to be clear that what your asking is also against the use case of the Prune API.
It's sole purpose is to free up space on the host. It is not intended for redaction. Redaction is a different concept designed for removing events across servers.
https://github.com/matrix-org/synapse/issues/1730#issuecomment-269839453

I will try to create a script that doesn't just prune the rume, but redacts all messages older than X days

see also #1480

**Comment by kythyria** [comment]
> I will try to create a script that doesn't just prune the rume, but redacts all messages older than X days

Aka, a valid reason to patch synapse to deliberately ignore redaction events.

**Comment by rubo77** [comment]
A script to really purge the history would start like this:

```
#!/bin/bash

# this script will purge all messages of a given room older than a definable age

DOMAIN=yourserver.tld
# add this user as admin in your home server:
ADMIN="@username:$DOMAIN"

#choose the room to prune old messages from
ROOM='!cURbafjkfsMDVwdRDQ:matrix.org' # for example: "Matrix HQ"

# choose a time before which the messages should be pruned:
# TIME='2016-08-31 23:59:59'
TIME='3 months ago'

# creates a timestamp from the given time string:
UNIX_TIMESTAMP=$(date +%s%3N --date='TZ="UTC+2" '"$TIME")

BUSY="pragma busy_timeout=20000"
BUFFER=$(sqlite3 homeserver.db "$BUSY;select event_id from events where type='m.room.message' and received_ts<'$UNIX_TIMESTAMP' and room_id='$ROOM' order by received_ts;")

for line in $BUFFER; do
  # use the api to redact those events
  # ...
```

**Comment by rubo77** [comment]
@kythyria: don't you think data parsimony is a desired option for matrix?

I think we should add an option to each room, if redaction really deletes content from database or just flags it as deleted.

In most cases a deletion is not desired, but it should be an option the room admin may choose for each room.

Also I think it should be visible in the room, that users see, that what they write _could_ be redacted, so they cannot rely on the messages to stay there forever.

On the other hand It should also be visible that you have to be careful, because messages written there are _undeleteable_, so you know, that, what you post there stays there _forever_

**Comment by kythyria** [comment]
Or just make the latter warning show all the time, because that's the best you're going to get. You can't actually force anyone to implement redaction correctly.

And no, it's not a desired option when it also allows people to have temper tantrums and wipe everything for no reason. Heck, it's not a desired option for matrix at all as evidenced by the fact that it's _not designed to make redacting easy_.

**Comment by rubo77** [comment]
So summarized:  this is about " Purge History API doesn't remove events from database ", which seems true – and desired

**Comment by kythyria** [comment]
The purge history API doesn't bulk redact. That's not its job. Is this even a bug?

**Comment by 4nd3r** [comment]
imagine a company using synapse for internal communication, so no federation. sometimes they need to wipe all data about certain project, when project ends. that's quite common in some areas. that also includes chat logs, encrypted or not. that's my usecase.

also there can be someone who needs to delete events from database to avoid problems with law enforcment in oppressive regimes. of course, you can use e2e, but without deleting old events your don't have plausible deniability.

i think it's about labeling things correctly - if you enable federation, you lose control over your messages. but if your room (and maybe server) is unfederated, then you should have complete control over your data, that includes ability to delete whatever you wish.

**Comment by kythyria** [comment]
If and **only** if the room is completely unfederated, and the server honours the relevant messages, will redaction do what @rubo77 seems to think it does.

**Comment by robcolbert** [comment]
Is this resolved? Can events and their content be erased? Beyond that, can I set a policy saying, "No message should live past 30 days."?

I am currently evaluating matrix-synapse for use within a private organization that has a 30-day chat retention policy. If I can't enact something like that either through settings or by perhaps contributing the code to do it, then I cannot use matrix-synapse.

It's not even a discussion. It's just a question: Does matrix-synapse have a configurable data retention policy?

**Comment by 4nd3r** [comment]
nope

**Comment by robcolbert** [comment]
@4nd3r thank you for taking the time to save me a lot of it. This process started at the documentation, then into the config files, then into some code, then here.

To devs, if I can maybe make a suggestion: Somewhere important and big in the docs, it can state that matrix does not have configurable data retention. Not even saying should, it's just a line of text you could maybe put somewhere and be explicit about the policy if you feel up to it.

I suppose this is the beauty of socket.io, MongoDB, Redis pub/sub and a tiny bit of Node.js and its crypto module, then.

I mean matrix has a bright future as a federated system of record for public conversations. Sure. But, it has no place inside most corporations and...as has been stated above...within groups that *need* privacy. Lazy deletes and no retention policy mean this tech is literally inappropriate in privacy scenarios. And, that's ironic given it's one of the few with e2e encryption. Shocking, actually.

**Comment by rubo77** [comment]
@robcolbert: if you follow some of the linked issues, you will see that you can really delete messages older than some days but only if your instance is not federated to any other Homeserver.

**Comment by 4nd3r** [comment]
@rubo77 those are "hacks" and not really a feature and because tinkering with synapse db is slippery road, then i rather not use those hacks.

**Comment by rubo77** [comment]
I wasn't referring to database hacks.

The is a purge API in the code, that deletes old messages. And if they are not federated, they are gone

**Comment by 4nd3r** [comment]
what do you mean by "if they are not federated"? federate = false as described [here](https://matrix.org/docs/spec/client_server/r0.2.0.html#m-room-create)?

as far i understand and have tested it, even if the room has no external members and you use [Purge History API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst), then yes, scrollback doesn't work, but the messages are still there, in database and are searchable. purge only removes some meta data.

as @erikjohnston said in https://github.com/matrix-org/synapse/issues/1621#issuecomment-264178528

**Comment by rubo77** [comment]
Is there a reason, why purge is not deleting the messages content?

**Comment by rubo77** [comment]
I added the command to really delete local events and messages, which is what users want to achieve mostly i think in my PR for an example script: https://github.com/matrix-org/synapse/pull/1034
