### ISSUE TITLE
Allow users to bind or unbind additional third-party accounts after registration

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse#16232]
**Description:**

Nowadays, users who register directly or through a third-party OAuth authorization cannot directly bind or unbind third-party accounts, which makes it difficult to manage user sources at a later stage, as well as causing inconvenience to users. In fact, this is perfectly feasible.

**Comment by DMRobertson** [comment]
If I understand correctly: I think you're saying that if e.g. I sign up for an account using a GitHub account, I can't also link that Matrix account to a e.g. GitLab account? My understanding is that's correct, and is a current limitation of the SSO machinery in Synapse. I believe that this area is being actively worked on (e.g. https://github.com/matrix-org/matrix-authentication-service) and this may be improved in the future.

**Comment by MomentQYC** [comment]
> If I understand correctly: I think you're saying that if e.g. I sign up for an account using a GitHub account, I can't also link that Matrix account to a e.g. GitLab account? My understanding is that's correct, and is a current limitation of the SSO machinery in Synapse. I believe that this area is being actively worked on (e.g. https://github.com/matrix-org/matrix-authentication-service) and this may be improved in the future.

I need to correct that it's not just accounts created via third-party OAuth, but accounts registered via username + password as well, that need to be allowed to freely bind or unbind third party accounts

**Comment by MomentQYC** [comment]
After testing, binding or unbinding third-party accounts for manually registered users did not cause bad effects.

**Comment by DMRobertson** [comment]
This feels like the same root cause as https://github.com/matrix-org/synapse/issues/14326?

**Comment by MomentQYC** [comment]
> This feels like the same root cause as #14326?

It doesn't look like it.

**Comment by clokep** [comment]
I think this is essentially #9441.
