### ISSUE TITLE
Distinguish between managing encrypted and unencrypted files

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse#16231]
**Description:**

Considering that people need unencrypted media files for a longer period of time (e.g. avatars, models custom uploaded by Thirdroom) and encrypted media files for a shorter period of time and with low ubiquity, is it desirable to manage the two types of files differently, e.g. with the option to clean up only encrypted files when cleaning up the files via the API?

**Comment by DMRobertson** [comment]
I don't think this is feasible. AFAICS there is no concept of encrypted media as far as the spec is concerned. The spec and Synapse's media repository treats media as opaque byte blobs. (https://spec.matrix.org/v1.8/client-server-api/#sending-encrypted-attachments, https://spec.matrix.org/v1.8/client-server-api/#post_matrixmediav3upload)

**Comment by DMRobertson** [comment]
I suppose we could use some heuristics (like GNU file does) to see if the file is a plaintext piece of media we recognise; or maybe we could track which kinds of rooms (encrypted or not) a piece of media gets used in. But this seems like it would be imprecise and brittle.

**Comment by MomentQYC** [comment]
> I don't think this is feasible. AFAICS there is no concept of encrypted media as far as the spec is concerned. The spec and Synapse's media repository treats media as opaque byte blobs (edit: without any kind of "encrypted" flag).

Is it possible to determine whether a media file is encrypted or not by room type when uploading it?
For example, in a private chat with end-to-end encryption enabled, media files must be end-to-end encrypted.

**Comment by DMRobertson** [comment]
> For example, in a private chat with end-to-end encryption enabled, media files must be end-to-end encrypted.

This is not the case: there nothing in the protocol that prevents you from sending a plaintext media (or message) into an encrypted room.

**Comment by MomentQYC** [comment]
> > For example, in a private chat with end-to-end encryption enabled, media files must be end-to-end encrypted.
> 
> This is not the case: there nothing in the protocol that prevents you from sending a plaintext media (or message) into an encrypted room.

So, if someone wants to implement this feature, does he or she need to start by adding a new specification?
This creates unnecessary wasted storage space.
