### ISSUE TITLE
Banning / Restricting / Redacting / Muting / Filtering / Blocking Out List of Words

### ISSUE THREAD

**Issue by candidexmedia** [matrix-org/synapse#16246]
**Description:**

Hello! I'm not sure if this is the right avenue to submit this request, so please let me know if it should be moved.

## Use Case: What I would like to do?
- As a room owner and/or moderator, I would like the ability to maintain a private list of keywords, terms, phrases that aren't allowed in a room.
- As a user, I would like the ability to mute or filter out certain keywords from all messages

## Why add this feature?
- Alleviate moderation work
- Provide healthier environments for community members, based on the established rules and the purpose of the room
- Conform to an organization's code of conduct
- Stop abusive content at the source, before it reaches the community

## Examples from other services:
Discord Automod: https://support.discord.com/hc/en-us/articles/4421269296535-AutoMod-FAQ

Telegram (public bot): https://botostore.com/c/grep_robot/

Mastodon: https://docs.joinmastodon.org/user/moderating/#filters

Peertube (glavliiit plugin): https://joinpeertube.org/plugins-selection

YouTube: https://support.google.com/youtube/answer/9483359?hl=en#zippy=%2Cblocked-words

## How it could work
**Moderator/owner side:**
Paste, upload a txt file, or type a list of words that could result in a user getting...
- A warning
- Comment held under review for moderation
- Kicked
- Banned

**User side (wishing to mute terms):** 
Much like ignoring a user, messages containing muted terms will not be seen by the user.

**User side (sending banned word in a room):**
"Warning" word: An alert is sent warning the user that they're using terms that are restricted in the room so that they have the chance to rewrite their message

"Hold - moderation" word: User is warned that their message has to be reviewed for moderation

"Kicked/Banned" word: User is automatically kicked or banned once they attempt to send the message.

**Comment by clokep** [comment]
I suspect this would best be positioned as a bot or AS. Otherwise it would likely need spec work for Synapse to support this. In E2EE rooms though the server can't really do much (which points you back to a bot or AS).

I'm going to close this as I don't think it is currently actionable from the Synapse team.
