### ISSUE TITLE
Doc the default federation port as 8448 more obviously

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1627]
Some folks assume federation runs on 443; the config should make it clearer that this is not true - c.f. https://twitter.com/wobscale/status/798314872601620480

**Comment by richvdh** [comment]
It's mentioned at https://github.com/matrix-org/synapse/blob/master/README.rst#setting-up-federation:

> By default, they will treat it as a hostname and try to connect to port 8448

Is that sufficient?

**Comment by aaronraimist** [comment]
The current federation documentation explains it pretty well https://github.com/matrix-org/synapse/blob/master/docs/federate.md
