### ISSUE TITLE
How does an administrator change a user's login password?

### ISSUE THREAD

**Issue by a545254328** [matrix-org/synapse#16287]
I forgot my login password

I want to change password via command just like registering account manually（register_new_matrix_user -c）

**Comment by clokep** [comment]
There's an admin API for modifying user information: https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account

Please use the [synapse admins rooms](https://matrix.to/#/#synapse:matrix.org) for support requests, not this bug tracker.
