### ISSUE TITLE
Debian package has no server_name field in the config after automated install

### ISSUE THREAD

**Issue by simonszu** [matrix-org/synapse#1630]
Hi,

after an initial installation via the debian repository, synapse cannot start. The error is: 

> Missing mandatory `server_name` config option.

I have installed synapse via ansible, there is no way for an interactive install process like the installation documents recommend, so there was no way to add a value for `server_name` during installation.
I fixed it with manually adding this key and a value to homeserver.yaml, but maybe you could add a default value, wich then will be overwritten by the interactive installation process or via dpkg-reconfigure.

**Comment by richvdh** [comment]
> maybe you could add a default value, wich then will be overwritten by the interactive installation process or via dpkg-reconfigure.

It's better that synapse doesn't start at all than it starts with the wrong server name. If you're going to have an interactive step anyway, I'm not quite sure what having a default would buy you.

(debian packaging bugs go in https://github.com/matrix-org/package-synapse-debian/issues for future reference).
