### ISSUE TITLE
Getting Wrong notif_count in event_push_summary table

### ISSUE THREAD

**Issue by gowtham18k** [matrix-org/synapse#16357]
### Description

While using the matrix synapse server if I join a user or if I do any operation in a particular room, the notif_count in the event_push_summary table got increased randomly. Because of that the unread count for a particular room and for a user will be wrong.
<img width="448" alt="image" src="https://github.com/matrix-org/synapse/assets/93001754/093bd41e-2c5f-420f-a079-7edceb85a936">

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

### Homeserver

homeserver

### Synapse Version

1.90.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

No

### Workers

Single process

### Platform

Kubernetes

### Relevant log output

```shell
NA
```

**Comment by DMRobertson** [comment]
> if I do any operation in a particular room, the notif_count in the event_push_summary table got increased randomly. 

Is this one specific room or lots of individual rooms?

> got increased randomly

What do you mean by "random" here? Do the counts increase in a predictable way each time?

The notif count represents the number of events---including e.g. users joining---in a room that the user wants to be aware of. It is separate from the highlight count, which is the number of urgent events the user wants to be aware of. Matrix is quite flexible (via [push rules](https://spec.matrix.org/v1.8/client-server-api/#push-rules)) in what it considers notifiable, so it's not obvious to me that counts going up are a bug.

> Because of that the unread count for a particular room and for a user will be wrong.

Can you be more specific here? What unread count did you expect to see, and what did you actually see on the client? (I.e. how does this manifest to end users?)

**Comment by gowtham18k** [comment]
It is happening in lots of rooms.
notif_count represents no.of events but Let me show what I got
1. It shows the notif_count that I have
<img width="838" alt="1" src="https://github.com/matrix-org/synapse/assets/93001754/74f1c549-a303-4d50-9b12-6c870b00fc49">
2. I'm sending one message to the room using restApi
<img width="1302" alt="3" src="https://github.com/matrix-org/synapse/assets/93001754/fdcbaa35-2059-452d-8b58-4d68a34931af">
3. Here, the count after sending one message to the room
<img width="838" alt="2" src="https://github.com/matrix-org/synapse/assets/93001754/d479c466-14c3-4007-a10f-6b6440dd9f68">

In this case, sending 1 message counts as 1 event right? But the notif_count increased to 16 instead of 1

**Comment by gowtham18k** [comment]
I'm sure that we are simply sending only one message from another user who is present in the same room. There are no more events triggered. The screenshot has been captured within a minute before and after sending one message which is in the second screenshot

**Comment by clokep** [comment]
The `event_push_summary` table doesn't usually show "live" data, it summarizes data every 30 seconds. I'm Are you also taking the data in `event_push_actions` into account? There's likely a single entry in there for the event ID you sent.

Note that the items aren't deleted immediately from `event_push_actions` after rotation, they're deleted after a few days.

**Comment by gowtham18k** [comment]
Yeah, It's right in `event_push_actions` we have a single entry. But the notif_count in `event_push_summary` is showing the wrong count.  Even though we are showing the wrong notification count to the users.  

`The event_push_summary table doesn't usually show "live" data, it summarizes data every 30 seconds. I'm Are you also taking the data in event_push_actions into account? There's likely a single entry in there for the event ID you sent.`

The `event_push_summary` table is used to summarize the events for a single room right? But In this case how the notif_count will come to this number as mentioned earlier?

**Comment by clokep** [comment]
> The `event_push_summary` table is used to summarize the events for a single room right? But In this case how the notif_count will come to this number as mentioned earlier?

Yes, but only up to a point (stored in `event_push_summary_stream_ordering`). If the corresponding entry in `event_push_actions` is after that stream ordering then it is not expected to be in `event_push_summary`.

**Comment by clokep** [comment]
It sounds like this is working as expected then?
