### ISSUE TITLE
Docs placing paragraph in the wrong point

### ISSUE THREAD

**Issue by JacksonChen666** [matrix-org/synapse#16354]
Looking at the `deactivate` parameter in [Create or modify an account (v1.90)](https://matrix-org.github.io/synapse/v1.90/admin_api/user_admin_api.html#create-or-modify-account), you'll see a paragraph after the `deactivate` parameter and it's about the conditions of reactivating a user.

Compare that to [v1.91 documentation](https://matrix-org.github.io/synapse/v1.91/admin_api/user_admin_api.html#create-or-modify-account), the paragraph looks out of place. It's been moved to the `locked` parameter for some reason, probably some oversight in adding the new parameter.

**Comment by clokep** [comment]
This is due to #15870.

**Comment by clokep** [comment]
#16355 should fix it. Thanks!
