### ISSUE TITLE
Federation with matrix is active even though it's disabled

### ISSUE THREAD

**Issue by alexander-potemkin** [matrix-org/synapse#16402]
I self-host Synapse server with no federation on it.

I've noticed the following lines in the logs however:
```
2023-09-29T14:29:54.000Z 2023-09-29 14:29:54,430 - synapse.http.matrixfederationclient - 348 - INFO - federation_transaction_transmission_loop-298 - {PUT-O-316} [matrix.org] Completed request: 200 OK in 0.04 secs, got 11 bytes - PUT matrix-federation://matrix.org/_matrix/federation/v1/send/<...>

2023-09-29T14:40:43.000Z 2023-09-29 14:40:43,369 - synapse.federation.sender.transaction_manager - 121 - INFO - federation_transaction_transmission_loop-299 - TX [matrix.org] {<...>} Sending transaction [<...>], (PDUs: 0, EDUs: 1)
```

I believe that I missed something - how can I make sure that my server is not sending anything anywhere?

**Comment by clokep** [comment]
> I believe that I missed something - how can I make sure that my server is not sending anything anywhere?

How did you disable federation?

**Comment by alexander-potemkin** [comment]
> > I believe that I missed something - how can I make sure that my server is not sending anything anywhere?
> 
> How did you disable federation?

@clokep , I was thinking that if feature is not enabled, it's disabled, so I have no federation enabled or allowed and I was under impression that it's disabling.
Am I wrong?

And in any case, how do I make sure my server is not sending anything anywhere?

**Comment by clokep** [comment]
Federation is enabled by default. Please see the configuration manual: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#federation_domain_whitelist

(In general that page should detail what the defaults are for each option.)

Please use the synapse admins channel for support: https://matrix.to/#/%23synapse:matrix.org

**Comment by alexander-potemkin** [comment]
> Federation is enabled by default. Please see the configuration manual: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#federation_domain_whitelist
> 
> (In general that page should detail what the defaults are for each option.)
> 
> Please use the synapse admins channel for support: https://matrix.to/#/%23synapse:matrix.org

@clokep ,  thank you. Do I hear you correctly, that if `federation_domain_whitelist:` would be presented with no options  at all - just one line in the config (in my case it was deleted), no information shall be delivered to any servers outside?

**Comment by clokep** [comment]
#6401 has some more information on this.

**Comment by alexander-potemkin** [comment]
Thank you. It doesn't seem to offer any solution. I'm sorry, but am I right, that for the moment, there is no way to disable federation with matrix.org, which is enabled and can't be disabled, even if `federation_domain_whitelist:` is set and empty?

**Comment by clokep** [comment]
That is incorrect. The federation whitelist applies to all domains equally.

**Comment by alexander-potemkin** [comment]
Thank you. So with `federation_domain_whitelist:` no more communication with outside servers will be happening and I shall not see the log messages like that anymore, is that correct?

```
2023-09-29T14:29:54.000Z 2023-09-29 14:29:54,430 - synapse.http.matrixfederationclient - 348 - INFO - federation_transaction_transmission_loop-298 - {PUT-O-316} [matrix.org] Completed request: 200 OK in 0.04 secs, got 11 bytes - PUT matrix-federation://matrix.org/_matrix/federation/v1/send/<...>

2023-09-29T14:40:43.000Z 2023-09-29 14:40:43,369 - synapse.federation.sender.transaction_manager - 121 - INFO - federation_transaction_transmission_loop-299 - TX [matrix.org] {<...>} Sending transaction [<...>], (PDUs: 0, EDUs: 1)
```

**Comment by clokep** [comment]
Matrix.org is already trying to contact you as you noted so there's some reason for that. Did one of your users join a public room? You'll need to leave those rooms first or the servers will keep trying to contact you.

**Comment by alexander-potemkin** [comment]
Thank you. It's highly unlikely that anyone has any connection with matrix.org with my self-hosted server, that's why I'm wondering - why my server is reaching out.

Is there some way to double-check that? From the database probably? Or in some other ways?

**Comment by clokep** [comment]
> It's highly unlikely that anyone has any connection with matrix.org with my self-hosted server, that's why I'm wondering - why my server is reaching out.

I really suspect one of your users joined a public room or maybe has a DM with someone on matrix.org.

You can check in the database:

```sql
SELECT * FROM destinations_rooms;
```

**Do not edit this column manually in the database, it will likely corrupt your database and break Synapse.**

Once you have a room ID you can use the admin APIs to [see who's in the room](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#room-details-api) and potentially [shut it down](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#delete-room-api).

**Comment by alexander-potemkin** [comment]
Thank you!
