### ISSUE TITLE
Synapse implements closed MSC2000

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#16415]
### Description

https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#password_config returns error codes defined from MSC2000 which was abandoned and thus should be removed from implementations within 3 months.

### Steps to reproduce

- Enable password_config `policy` MSC2000 implementation
- Register using a password not conforming to the policy

### Homeserver

localhost

### Synapse Version

v1.93.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

pg

### Workers

Single process

### Platform

Docker

### Configuration

```yaml
password_config:
  policy:
    require_digit: true
```

### Relevant log output

```shell
N/A
```

**Comment by erikjohnston** [comment]
This should be mostly magically fixed by us switching to OIDC, at which point we'll rip out all of this code.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/15645 ?
