### ISSUE TITLE
Synapse fails to start after upgrade to 0.18.4

### ISSUE THREAD

**Issue by Gerii** [matrix-org/synapse#1642]
I have installed Synapse via the APT repository on my Ubuntu 16.04 machine. However, since I upgraded to 0.18.4 I can't start the server anymore. The last line in the log says that it is trying to upgrade the database schema.

> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'bcrypt' version u'2.0.0' from '/usr/lib/python2.7/dist-packages/bcrypt/__init__.pyc' to satisfy 'py-bcrypt'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'msgpack' version None from '/usr/lib/python2.7/dist-packages/msgpack/__init__.pyc' to satisfy 'msgpack-python>=0.3.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'frozendict' version None from '/usr/lib/python2.7/dist-packages/frozendict/__init__.pyc' to satisfy 'frozendict>=0.4'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'OpenSSL' version '0.15.1' from '/usr/lib/python2.7/dist-packages/OpenSSL/__init__.pyc' to satisfy 'pyopenssl>=0.14'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'pydenticon' version None from '/usr/lib/python2.7/dist-packages/pydenticon/__init__.pyc' to satisfy 'pydenticon'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'pymacaroons' version '0.9.0' from '/usr/lib/python2.7/dist-packages/pymacaroons/__init__.pyc' to satisfy 'pymacaroons-pynacl'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'service_identity' version '16.0.0' from '/usr/lib/python2.7/dist-packages/service_identity/__init__.pyc' to satisfy 'service_identity>=1.0.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'signedjson' version '1.0.0' from '/usr/lib/python2.7/dist-packages/signedjson/__init__.pyc' to satisfy 'signedjson>=1.0.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'blist' version '1.3.6' from '/usr/lib/python2.7/dist-packages/blist/__init__.pyc' to satisfy 'blist'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'yaml' version '3.11' from '/usr/lib/python2.7/dist-packages/yaml/__init__.pyc' to satisfy 'pyyaml'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'unpaddedbase64' version '1.1.0' from '/usr/lib/python2.7/dist-packages/unpaddedbase64.pyc' to satisfy 'unpaddedbase64>=1.1.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'ujson' version '1.33' from '/usr/lib/python2.7/dist-packages/ujson.x86_64-linux-gnu.so' to satisfy 'ujson'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'nacl' version '1.0.1' from '/usr/lib/python2.7/dist-packages/nacl/__init__.pyc' to satisfy 'pynacl==0.3.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'nacl.bindings' version '1.0.1' from '/usr/lib/python2.7/dist-packages/nacl/__init__.pyc' to satisfy 'pynacl==0.3.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'daemonize' version None from '/usr/lib/python2.7/dist-packages/daemonize.pyc' to satisfy 'daemonize'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'canonicaljson' version '1.0.0' from '/usr/lib/python2.7/dist-packages/canonicaljson.pyc' to satisfy 'canonicaljson>=1.0.0'
> 2016-11-23 12:40:56,844 - synapse.python_dependencies - 114 - INFO - - Using 'twisted' version '16.0.0' from '/usr/lib/python2.7/dist-packages/twisted/__init__.pyc' to satisfy 'Twisted>=15.1.0'
> 2016-11-23 12:40:56,845 - synapse.python_dependencies - 114 - INFO - - Using 'saml2' version None from '/usr/lib/python2.7/dist-packages/saml2/__init__.pyc' to satisfy 'pysaml2>=3.0.0,<4.0.0'
> 2016-11-23 12:40:56,845 - synapse.python_dependencies - 114 - INFO - - Using 'pyasn1' version '0.1.9' from '/usr/lib/python2.7/dist-packages/pyasn1/__init__.pyc' to satisfy 'pyasn1'
> 2016-11-23 12:40:56,845 - synapse.python_dependencies - 114 - INFO - - Using 'PIL' version None from '/usr/lib/python2.7/dist-packages/PIL/__init__.pyc' to satisfy 'pillow'
> 2016-11-23 12:40:56,855 - synapse.app.homeserver - 289 - INFO - - Server hostname: abc.abc.com
> 2016-11-23 12:40:56,855 - synapse.app.homeserver - 290 - INFO - - Server version: Synapse/0.18.4
> 2016-11-23 12:40:56,856 - synapse.app.homeserver - 308 - INFO - - Preparing database: sqlite3...
> 2016-11-23 12:40:56,858 - synapse.storage.prepare_database - 212 - INFO - - Upgrading schema to v38
> 

> sudo service matrix-synapse status
> ● matrix-synapse.service - Synapse Matrix homeserver
>    Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Wed 2016-11-23 12:40:32 CET; 1s ago
>   Process: 6388 ExecStart=/usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ (code=exited, status=1/FAILURE)
>   Process: 6383 ExecStartPre=/usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys (code=exited, status=0/SUCCESS)
>  Main PID: 6388 (code=exited, status=1/FAILURE)
> 
> Nov 23 12:40:32 server systemd[1]: matrix-synapse.service: Unit entered failed state.
> Nov 23 12:40:32 server systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.

**Comment by davidkallie** [comment]
I have a similar issue with FreeBSD, more specifically PyNaCl. In the file 
*synapse/synapse/python_dependencies.py* should pynacl dependency be >= 0.3.0? and not hard set? In the FreeBSD repo pynacl is set to v1.0.1.

I am aware one could use a virtual env, but unless there are api changes then this should be bumped up.

**Comment by jhdulaney** [comment]
This seems to be fixed in 0.27.0-rc2
