### ISSUE TITLE
Unable find the users from openid Connect

### ISSUE THREAD

**Issue by nmanthena18** [matrix-org/synapse#16423]
### Description

I am using openID connect with keycloak, I am unable to find all the users, I can able to find only the user who loggedin atleat once.

### Steps to reproduce

- use the openID connect for the user login
- search user who are not loggedin atleast one time.

### Homeserver

All

### Synapse Version

{"server_version":"1.86.0rc2","python_version":"3.11.6"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

postgres

### Workers

I don't know

### Platform

AWS/Ubuntu

### Relevant log output

```shell
No logs
```

### Anything else that would be useful to know?

Suppose to get all the users from fedarated database.

**Comment by clokep** [comment]
> I can able to find only the user who loggedin atleat once.

Users don't exist on the Synapse side until they've logged. You could pre-populate users using the admin API, but this is mostly working as expected.

**Comment by nmanthena18** [comment]
@clokep its OIDC if we are trying to prepulate the users, after they trying to login its creating new account with username adding 1 at end.

**Comment by clokep** [comment]
> its OIDC if we are trying to prepulate the users, after they trying to login its creating new account with username adding 1 at end.

You need to [properly populate the `external IDs field](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account).

We use GitHub to track bugs, please use [Synapse admins](https://matrix.to/#/#synapse:matrix.org) for additional support.

**Comment by nmanthena18** [comment]
Thanks!
