### ISSUE TITLE
OIDC: pre-OIDC devices have incorrect `last_seen_ts`

### ISSUE THREAD

**Issue by kerryarchibald** [matrix-org/synapse#16448]
### Description
`element.io` sessions authenticated before SSO was enabled have incorrect `last_seen_ts`

### Steps to reproduce

- Have an existing `element.io` device, authenticated via user/pass before SSO was enabled for element.io
- GET /v3/devices, and see that this device has a `last_seen_ts: 1688108976491` (June 30), despite being currently active

### Homeserver

https://element.ems.host/

### Synapse Version

{"server_version":"1.92.3","python_version":"3.11.5"}

### Installation Method

I don't know

### Database

na

### Workers

I don't know

### Platform

.

### Relevant log output

```shell
.
```

**Comment by clokep** [comment]
Is this different than #16084?
