### ISSUE TITLE
Exception user_directory.notify_new_event, synapse.metrics.background_process_metrics

### ISSUE THREAD

**Issue by rajil** [matrix-org/synapse#16445]
### Description

I migrated synapse from Debian instance to a Docker instance. It seems to be working fine, but occasionally throw an exception in the log.

### Steps to reproduce

- Start synapse docker instance

### Homeserver

self hosted

### Synapse Version

1.93.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

Postgres version 12. I restored database from backup.

### Workers

Single process

### Platform

Docker container

### Relevant log output

```shell
synapse-synapse-1  | 2023-10-08 11:48:12,596 - synapse.metrics.background_process_metrics - 247 - ERROR - user_directory.notify_new_event-80 - Background process 'user_directory.notify_new_event' threw an exception
synapse-synapse-1  | Traceback (most recent call last):
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/metrics/background_process_metrics.py", line 245, in run
synapse-synapse-1  |     return await func(*args, **kwargs)
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/user_directory.py", line 173, in process
synapse-synapse-1  |     await self._unsafe_process()
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/user_directory.py", line 239, in _unsafe_process
synapse-synapse-1  |     await self._handle_deltas(deltas)
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/user_directory.py", line 268, in _handle_deltas
synapse-synapse-1  |     await self._handle_room_membership_event(
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/user_directory.py", line 418, in _handle_room_membership_event
synapse-synapse-1  |     await self._track_user_joined_room(room_id, state_key)
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/user_directory.py", line 431, in _track_user_joined_room
synapse-synapse-1  |     await self.store.add_users_in_public_rooms(room_id, (joining_user_id,))
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/user_directory.py", line 805, in add_users_in_public_rooms
synapse-synapse-1  |     await self.db_pool.simple_upsert_many(
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1478, in simple_upsert_many
synapse-synapse-1  |     await self.runInteraction(
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 946, in runInteraction
synapse-synapse-1  |     return await delay_cancellation(_runInteraction())
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1993, in _inlineCallbacks
synapse-synapse-1  |     result = context.run(
synapse-synapse-1  |              ^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
synapse-synapse-1  |     return g.throw(self.type, self.value, self.tb)
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 912, in _runInteraction
synapse-synapse-1  |     result = await self.runWithConnection(
synapse-synapse-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1041, in runWithConnection
synapse-synapse-1  |     return await make_deferred_yieldable(
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/python/threadpool.py", line 244, in inContext
synapse-synapse-1  |     result = inContext.theWork()  # type: ignore[attr-defined]
synapse-synapse-1  |              ^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
synapse-synapse-1  |     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
synapse-synapse-1  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
synapse-synapse-1  |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
synapse-synapse-1  |     return func(*args, **kw)
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
synapse-synapse-1  |     result = func(conn, *args, **kw)
synapse-synapse-1  |              ^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1034, in inner_func
synapse-synapse-1  |     return func(db_conn, *args, **kwargs)
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 774, in new_transaction
synapse-synapse-1  |     r = func(cursor, *args, **kwargs)
synapse-synapse-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1510, in simple_upsert_many_txn
synapse-synapse-1  |     return self.simple_upsert_many_txn_native_upsert(
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1608, in simple_upsert_many_txn_native_upsert
synapse-synapse-1  |     txn.execute_values(sql, args, fetch=False)
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 422, in execute_values
synapse-synapse-1  |     return self._do_execute(
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 485, in _do_execute
synapse-synapse-1  |     return func(sql, *args, **kwargs)
synapse-synapse-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 425, in <lambda>
synapse-synapse-1  |     lambda the_sql, the_values: execute_values(
synapse-synapse-1  |                                 ^^^^^^^^^^^^^^^
synapse-synapse-1  |   File "/usr/local/lib/python3.11/site-packages/psycopg2/extras.py", line 1299, in execute_values
synapse-synapse-1  |     cur.execute(b''.join(parts))
synapse-synapse-1  | psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification
```
```


### Anything else that would be useful to know?

_No response_

**Comment by DMRobertson** [comment]
> synapse-synapse-1  | psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

This should not happen and suggests that something has gone wrong with your database.

Can you please connect to your database and run `\d users_in_public_rooms`, then paste the output here?

**Comment by rajil** [comment]
When i was importing the data into docker instance there was an error message,
```
ERROR:  could not create unique index "users_in_public_rooms_u_idx"
DETAIL:  Key (user_id, room_id)=(@dennis:matrix.phenomenon.cloud, !jZUPVDWqESwCibUpnD:matrix.org) is duplicated.
```
Could this be the reason of the exception?

UPDATE
What i have done now is rather than importing the data into docker, i simply copied the debian postgres database files over to the docker instance. With this i no longer get the python exception. If i try to find the above userid now i get,

```
synapse2=# select * from users_in_public_rooms where user_id='@dennis:matrix.phenomenon.cloud';
             user_id             |             room_id             
---------------------------------+---------------------------------
 @dennis:matrix.phenomenon.cloud | !DzntlyFqDwYZSqoYBV:maunium.net
 @dennis:matrix.phenomenon.cloud | !jZUPVDWqESwCibUpnD:matrix.org
 @dennis:matrix.phenomenon.cloud | !whatsapp-v10:maunium.net
```
There is no duplicate in the database.

**Comment by DMRobertson** [comment]
> Can you please connect to your database and run `\d users_in_public_rooms`, then paste the output here?

Can you please provide this information---for sanity checking that the schema has been correctly ingested into the new database.

> What i have done now is rather than importing the data into docker, i simply copied the debian postgres database files over to the docker instance.

Do you mean that you are running postgres in a docker container too?

Either way, this sounds highly suspicious to me; all of the advice I can find for moving a DB between hosts is to `pg_dump` and then ingest the dump with `psql` or `pg_restore`. If you're going to copy the data directly, I would at least ensure that the source and target postgres versions are the same. Even then, you run the risk of indices becoming unsorted if you're using a [non-C collation](https://matrix-org.github.io/synapse/latest/postgres.html#fixing-incorrect-collate-or-ctype) and the version of libc is different on the two hosts, your [indices can become invalid](https://wiki.postgresql.org/wiki/Locale_data_changes) on the new host and result in errors like this. We saw  this in https://github.com/matrix-org/synapse/issues/16436 just the other day.

My advice would be to pg_dump from your old host, import it into your new host _with collation set to C_ and see if that gets you any further.

**Comment by rajil** [comment]
I have since nuked the imported database and instead as mentioned previously simply copied the files over. 

Yes, postgresql is now running in docker following the official post [compose file](https://github.com/matrix-org/synapse/blob/develop/contrib/docker/docker-compose.yml). The debian and docker instance are running the same postgresql version 12,

Debian
```
postgres=# SELECT version();
                                                                version                                                                 
----------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.16 (Ubuntu 12.16-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
(1 row)
```

Docker
```
postgres=# SELECT version();
                                                      version                                                      
-------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.16 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
(1 row)
```

The database does have the C collation set,
```
postgres=# \l synapse2
                         List of databases
   Name   | Owner  | Encoding | Collate | Ctype | Access privileges 
----------+--------+----------+---------+-------+-------------------
 synapse2 | matrix | UTF8     | C       | C     | 
```

Here is what the  `\d users_in_public_rooms` is in the _copied_ over files database.

```
synapse2=# \d users_in_public_rooms
      Table "public.users_in_public_rooms"
 Column  | Type | Collation | Nullable | Default 
---------+------+-----------+----------+---------
 user_id | text |           | not null | 
 room_id | text |           | not null | 
Indexes:
    "users_in_public_rooms_u_idx" UNIQUE, btree (user_id, room_id)
    "users_in_public_rooms_r_idx" btree (room_id)
  
```

Previously when i was trying export/import the data, i used the following steps,
```
postgres pg_dumpall > synapse.dump
cat ~/synapse.dump |docker exec -i synapse-db-1 psql -U postgres
```

I dont see the need of using import/export, since copied database files is not producing any error.

**Comment by DMRobertson** [comment]
I am very confused about what exactly you did and what exactly went wrong, and in which order. My understanding:

1. Dump original PG database to file with `pg_dumpall`.
2. Create new postgres docker image. Pipe the dump into psql in the container.
3.  This fails with
    > ERROR:  could not create unique index "users_in_public_rooms_u_idx"
DETAIL:  Key (user_id, room_id)=(@dennis:matrix.phenomenon.cloud, !jZUPVDWqESwCibUpnD:matrix.org) is duplicated.
   which suggests that either your original database or your dump is corrupted.
   - > Could this be the reason of the exception?
    Yes.
    - Look inside the dump file---can you see duplicate rows in that table with those values?
    - It would have been very helpful to see what `\d users_in_public_rooms` was on the _old, pre-dump_ database here.
4. Copy database files directly into the postgres docker container. (I hope these are guaranteed to persist, btw.)
5. At this point: does it work, and are there any errors in your Synapse installation when connected to the postgres docker container after (4)?

**Comment by reivilibre** [comment]
```
ERROR: could not create unique index "users_in_public_rooms_u_idx"
DETAIL: Key (user_id, room_id)=(@dennis:matrix.phenomenon.cloud, !jZUPVDWqESwCibUpnD:matrix.org) is duplicated.
```

As another note, this can happen instead if you start restoring a backup, cancel it (e.g. with Ctrl+C) and then start it again without first wiping the database.

**Comment by rajil** [comment]
> I am very confused about what exactly you did and what exactly went wrong, and in which order. My understanding:
Yes, your chronological order is correct.
> 
>     1. Dump original PG database to file with `pg_dumpall`.
> 
>     2. Create new postgres docker image. Pipe the dump into psql in the container.
> 
>     3. This fails with
>        > ERROR:  could not create unique index "users_in_public_rooms_u_idx"
>        > DETAIL:  Key (user_id, room_id)=(@dennis:matrix.phenomenon.cloud, !jZUPVDWqESwCibUpnD:matrix.org) is duplicated.
>        
>        
>        which suggests that either your original database or your dump is corrupted.
>        
>        * > Could this be the reason of the exception?
>          
>          
>          Yes.
>        * Look inside the dump file---can you see duplicate rows in that table with those values?
I tried to use grep on this big database but did not get far. Any specific command you want me to try?
>        * It would have been very helpful to see what `\d users_in_public_rooms` was on the _old, pre-dump_ database here.
Understand, but i not longer has this is in a running postgres session.
> 
>     4. Copy database files directly into the postgres docker container. (I hope these are guaranteed to persist, btw.)
> 
>     5. At this point: does it work, and are there any errors in your Synapse installation when connected to the postgres docker container after (4)?
No errors at all. Everything is working great.

**Comment by DMRobertson** [comment]
> No errors at all. Everything is working great.

Good to hear. It sounds like the explanation in https://github.com/matrix-org/synapse/issues/16445#issuecomment-1757453675 (a cancelled and restarted DB ingestion) is the most likely cause, then. Let's assume that's the case.
