### ISSUE TITLE
publicRooms response is not according to spec

### ISSUE THREAD

**Issue by GalPressman** [matrix-org/synapse#1645]
According to http://matrix.org/docs/spec/client_server/r0.2.0.html#get-matrix-client-r0-publicrooms

The response should contain `start` and `end` for pagination, but in fact the
response contains `next_batch` field.
One of them (spec or code) should be aligned to the other.

**Comment by richvdh** [comment]
This is fixed in the next version of the spec: http://matrix.org/speculator/spec/HEAD/client_server/unstable.html#get-matrix-client-unstable-publicrooms
