### ISSUE TITLE
devices table has case-sensitive user_id which leads to not removing devices from user

### ISSUE THREAD

**Issue by Kokokokoka** [matrix-org/synapse#16474]
### Description

When I was searching  for reasons of device_inbox bloat. I've found that there are many devices in device table which have last_seen null.
those devices had wrong case in user_id f.e. @user:domain  | master signing key   but  @ User:domain | Element Android... 
If one uses admin api to logout device last_seen is set to null but the device is not being removed from devices table. 
iff name is lowercase everything works fine. there seems to be a problem that case-insensitive names start being case sensitive
and a problem that case-sensitive user_ids appeared in devices when they shouldn't.
if i match user_id case from devices, delete devices api it returns: {"errcode":"M_NOT_FOUND","error":"Unknown user"}

### Steps to reproduce

don't know how to reproduce this reliably as I don't know how new devices are being created in table and what leads to this behaviour.
probably this bug could affect other tables too.

### Homeserver

personal

### Synapse Version

1.94

### Installation Method

Debian packages from packages.matrix.org

### Database

postgresql, single instanse

### Workers

Multiple workers

### Platform

debian linux 11

### Configuration

i have device retention in logs and ldap auth

### Relevant log output

```shell
no logs for now
```

### Anything else that would be useful to know?
matrix-synapse-ldap3/oldstable,now 0.1.4+git20201015+a3c7a9f-1 all [installed]

**Comment by clokep** [comment]
See also #3599.

**Comment by Kokokokoka** [comment]
> See also #3599.
I started from this.

briefly:
1. device_inbox size was around 300Gb, 
2. even though there was delete_stale_devices_after: 31d setting
3.  ./synapse/storage/databases/main/devices.py (get_devices_not_accessed since) on line 1418 states:
```
SELECT user_id, device_id
                FROM devices WHERE last_seen < ? AND hidden = FALSE

```
4. the problem is, that it doesn't take in account devices which has NULL as last_seen.
5. one might ask how could one get last_seen NULL for a device?
6. the answer is, that: even though user_id in devices ought to be lowercase, there were user_id's which had different case in devices, even the users table is lowercase for this user (and it all worked somehow, and this looks bad)
7. if one uses admin api to delete stale devices, device_inbox is being cleaned out (300Gb->70Gb)
BUT: those devices are still in devices table, so they are not being deleted (because of different case in name, most likely)
As a result there are problems:
1. last_seen being NULL even it shouldn't be in devices
2. user_id has different case even if it should have the same case (or even stronger it should have only lowercase user_id's)
3. devices not being deleted from devices table
4. device_inbox not being cleaned out

**Comment by Kokokokoka** [comment]
And one more detail:
I was selecting stale devices by getting user_id, device_id pair from:
```
select *, sum(dev_cnt) over () as ttl_filt from (select distinct
        user_id,
        device_id,
        count(*) over (partition by user_id, device_id) as dev_cnt,
        count(*) over (partition by user_id) as user_cnt,
        count(*) over () as ttl
from
        device_inbox di
order by
        user_cnt desc,
        dev_cnt desc)x where dev_cnt > 5000;
```
after deleting those I have found that some of the messages in device_inbox are still being present. 
and there are user_id, device_id pairs which aren't present in devices.
can one clean manually device_inbox if user_id,device_id is not  present in devices?

**Comment by Kokokokoka** [comment]
for now  I want to manually convert user_id to lowercase in devices inbox, probably one could add a trigger before insert which would do lowercase of user_id but it won't solve the bug itself| or changing the type of user_id column to citext (but, in all fairness this should be done by synapse team as a migration). sadly, I don't have enough time finding what causes adding user_id with different case in devices. and I'm afraid that this bug could interfere with other tables too, so it would be better if it would be possible finding the source of the problem and not fixing holes by patching db.

**Comment by clokep** [comment]
>  probably one could add a trigger before insert which would do lowercase of user_id but it won't solve the bug itself

Note that usernames *are* case sensitive, **except** during login *If, and only if, there are not ambiguous users*. It is a bit unclear how these entries could have been added in the first place. Maybe a client issue is involved? But it isn't really clear.

**Comment by Kokokokoka** [comment]
> > probably one could add a trigger before insert which would do lowercase of user_id but it won't solve the bug itself
> 
> Note that usernames _are_ case sensitive, **except** during login _If, and only if, there are not ambiguous users_. It is a bit unclear how these entries could have been added in the first place. Maybe a client issue is involved? But it isn't really clear.

yep, there probably is some client issue as those users are lowercase in users table, but they have case in devices. 
ok. as i don't really know how to debug this further. I want to do this:
1. use logout device on devices which has null in last access ts and which aren't hidden
2. delete rows in device_inbox which are orphaned (no device in devices_
3. delete rows in devices which has last_seen null and hidden is false
will this work? and by work i mean it wouldn't harm the inner synapse logic

**Comment by reivilibre** [comment]
(I notice from the description that LDAP auth is in use. LDAP auth has been sloppy with username cases in the past, so I'd reckon it's worth a look there to see if that might be part of the reason.)

**Comment by erikjohnston** [comment]
Ah, looks like the LDAP provider had a bug around case sensitivity: https://github.com/matrix-org/matrix-synapse-ldap3/pull/163 and https://github.com/matrix-org/matrix-synapse-ldap3/pull/168.

Hopefully that means therefore this issue is fixed (albeit the stale entries in the DB that haven't been cleaned up)?

**Comment by Kokokokoka** [comment]
> Ah, looks like the LDAP provider had a bug around case sensitivity: [matrix-org/matrix-synapse-ldap3#163](https://github.com/matrix-org/matrix-synapse-ldap3/pull/163) and [matrix-org/matrix-synapse-ldap3#168](https://github.com/matrix-org/matrix-synapse-ldap3/pull/168).
> 
> Hopefully that means therefore this issue is fixed (albeit the stale entries in the DB that haven't been cleaned up)?

the question stands still:
can one safely delete those devices and device_inbox. or is there something else that one should do beforehand|additionally?
after this i'll check whether those user_id's appear in devices, or not.
