### ISSUE TITLE
synapse_admin_mau_current always zero

### ISSUE THREAD

**Issue by Tealk** [matrix-org/synapse#16513]
### Description

The metric "synapse_admin_mau_current" always gives me 0 since the installation.

### Steps to reproduce

- Install synapse
- activate metric

### Homeserver

rollenspiel.chat

### Synapse Version

1.94.0

### Installation Method

Debian packages from packages.matrix.org

### Database

PostgreSQL

### Workers

Single process

### Platform

Dieban 12 (Bookworm) as VM on a Proxmox installation.

### Configuration

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation, health]
        compress: false
  # beginning of the new metrics listener
  - port: 9000
    type: metrics
    bind_addresses: ['0.0.0.0']
enable_metrics: true

### Relevant log output

```shell
the following line is repeated again and again, otherwise nothing with metric occurs in the log

2023-10-17 00:03:53,370 - synapse.metrics._gc - 120 - INFO - sentinel - Collecting gc 1
```

**Comment by clokep** [comment]
> The metric "synapse_admin_mau_aktuell" always gives me 0 since the installation.

> synapse_admin_mau_current always zero

Just to confirm, the metric name seems to be `synapse_admin_mau_current`, taking a look at our dashboards it seems to be working OK.

Do you have [`limit_usage_by_mau`](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#limit_usage_by_mau) or [`mau_stats_only`](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#mau_stats_only) enabled in your config?

**Comment by Tealk** [comment]
Yes the variable is "synapse_admin_mau_current", I don't know why I translated it

> Do you have [limit_usage_by_mau](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#limit_usage_by_mau) or [mau_stats_only](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#mau_stats_only) enabled in your config?

no I have not configured these two.

other values in the synapse dashboard are displayed but not the mau.
![image](https://github.com/matrix-org/synapse/assets/12276250/5100fe82-d63e-4cce-9d8e-736eecd059e0)

**Comment by clokep** [comment]
> > Do you have [limit_usage_by_mau](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#limit_usage_by_mau) or [mau_stats_only](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#mau_stats_only) enabled in your config?
> 
> no I have not configured these two.

You must enable one of those in order to enable MAU. After enabling you must restart Synapse (and I think Synapse doesn't re-calculate MAU for 5 minutes after starting).

**Comment by Tealk** [comment]
ok my mistake, now i have the metrics too, sorry.
should it perhaps be included in the promethus instructions?

**Comment by clokep** [comment]
>  should it perhaps be included in the promethus instructions?

Improving the docs is always appreciated! 👍
