### ISSUE TITLE
Friends pinned

### ISSUE THREAD

**Issue by niudin** [matrix-org/synapse#16517]
Please don't file github issues asking for support.

Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.
Do we have a feature to pin friends list to the top?

**Comment by DMRobertson** [comment]
>  Do we have a feature to pin friends list to the top?

Rooms can be [tagged](https://spec.matrix.org/v1.8/client-server-api/#room-tagging) as `m.favourite`. That is likely the closest thing to what you're asking for. Element web exposes this under the `...` menu on a room: 
![image](https://github.com/matrix-org/synapse/assets/8614563/5954350d-1f96-4c62-888e-6e2e2c064687)

Anything else will depend on your client and you should ask their support channels for advice.

> Please don't file github issues asking for support.
