### ISSUE TITLE
Signing releases

### ISSUE THREAD

**Issue by aerusso** [matrix-org/synapse#16556]
**Description:**

Hello! I apologize if this is somewhere, but I cannot seem to find it if it exists.  I would like to cryptographically verify the releases of matrix-synapse.  I can see that the release-tagged commits are signed, but I cannot seem to find public information on which key(s) I should trust signatures from.  Ideally, there would be a link in the readme to some web page on matrix.org listing a public key, and the tags are signed with that key.  Even better if that same pgp key is used to sign everything (packages, release tags, etc.).

Thanks for the great work!

**Comment by clokep** [comment]
The debian packages are signed: https://matrix-org.github.io/synapse/latest/setup/installation.html#matrixorg-packages

Can you provide more info about what sort of install you're using?

**Comment by DMRobertson** [comment]
Is this basically https://github.com/matrix-org/synapse/issues/15994 ?

**Comment by aerusso** [comment]
Oh shoot, yes.  Sorry, I did not mean to open a second issue (I actually completely forgot that I already did that).  I'll go ahead and close since it's a duplicate.
