### ISSUE TITLE
Can't leave rooms

### ISSUE THREAD

**Issue by germain-gg** [matrix-org/synapse#16592]
### Description

I'm trying to leave #element-android:matrix.org and that does not seem to work.

### Steps to reproduce

- Leave the room	

### Homeserver

matrix.org

### Synapse Version

current matrix.org version

### Installation Method

I don't know

### Database

n/a

### Workers

I don't know

### Platform

n/a

### Relevant log output

```shell
Trying to work with @clokep to dig those out.
```

**Comment by erikjohnston** [comment]
Looking at the DBs, I think that you *have* left, but the client has gotten out of sync and thinks you're still in the room? Are you still receiving messages in it?
