### ISSUE TITLE
Feature: Have room security level that prevents users from posting images and/or links

### ISSUE THREAD

**Issue by sanecito** [matrix-org/synapse#16610]
**Description:**

Currently going by Element's room controls there are no room controls on the Server side in place to prevent someone from spamming links (that trigger image previews) or images of a less than ideal nature. For example, CSAM or other material not desirable can be easily spammed. Other social software, like Discourse and others have moderation tools that prevent newly created accounts from engaging in this kind of spam.

**Feature Request:**

Two entries are added to "Permissions" alongside existing entries like "Send Reactions" "Send Messages":

- "Send Files/Images"
- "Send Links"

This puts in place simple preventative controls so that moderators aren't having to spend time with reactive based ones and room members aren't exposed to problematic material

**Comment by reivilibre** [comment]
Thanks for writing in.
We can't really do anything here without some supporting specification work that would allow for this.

I've dug up the following requests in the specification that relate to this:
- https://github.com/matrix-org/matrix-spec/issues/836
- https://github.com/matrix-org/matrix-spec/issues/565

As far as I'm aware they are not being worked on at the moment but someone interested could take on the task of writing up an MSC for it and trying to get it landed.
