### ISSUE TITLE
LDAP - Cannot create user.

### ISSUE THREAD

**Issue by muppeth** [matrix-org/synapse#1662]
I'm testing out the LDAP authentication for synapse. I did ldap3 downgrade as suggested in #1643 
However I now have a problem creating users from ldap. 
Users are properly looked up in LDAP: `INFO - POST-5- User authenticated against LDAP server: ldap://ldap.example.lan:389` and synapse at first tries to login as a user `WARNING - POST-5- Attempted to login as @tester:matrix.lan but they do not exist`. Then as I understand it should try to create missing user which it tries to do: `POST-5- ldap registration filter: (&(cn=tester)(objectClass=person))`, but it fails with this warning: `POST-5- LDAP registration failed, no result.`

Am I missing something?

**Comment by muppeth** [comment]
Is it possible to specify bind mode in homeserver.yaml. I think my problem has something to do with Simple bind not being able to read out all attributes from ldap. Also I've noticed that then using base for example "dc=example,dc=local" instead of more detailed "ou=people,dc=example,dc=local" Search mode finds users in "ou=people,dc=example,dc=local", but simple bind does search directly in "dc=example,dc=local" which results in user not found. (cn=user,dc=example,dc=local instead of cn=user,ou=people,dc=example,dc=local)

I tried specifying the mode in config file (mode: "search") but that does not seem to work, though my understanding is that it ldap_auth_provider should be taking it from the config file: "self.ldap_mode = config.mode"

**Comment by muppeth** [comment]
Did some investigation. Basically my problem is that normal users cannot search directory besides attributes in their own cn. 
Why is user creation not done by bind_dn user who has readonly rights to search the directory?

**Comment by douglas-lee** [comment]
I have the same problem.

**Comment by antil0pa** [comment]
In ldap_aut_provider.py in line 341 and 342 ldap unbind connection in search mode and reconnects in simple mode. By commenting this two lines and replcaing them with 
`return True, conn`
the retrival of attributes continues in search mode

**Comment by muppeth** [comment]
Yes. I confirm that works. I wonder if it may be included in upstream. I think switching to simple bind to register a user is not neccecary.

This also solves the problem of defining base dn (dc=example,dc=com instead of ou=people,dc=example,dc=com) which lets you register users from different ou(s)

**Comment by mweinelt** [comment]
Can you please rebase your issue against the latest version of https://github.com/matrix-org/matrix-synapse-ldap3 and then resubmit the issue over there? The ldap module was externalized.
