### ISSUE TITLE
released matrix-synapse-testutils is outdated

### ISSUE THREAD

**Issue by gnunicorn** [matrix-org/synapse#16630]
### Description

Trying to build a new synapse module using the cookiecutter template. Adding tests using the released `matrix-synapse-testutils` (big thanks for doing that!) but run into the pydantic v2 error ( #16331 ) which is meant to work in the latest matrix-synapse release already (using the compat layer) but as I am pulling in matrix-synapse-testutils it fails. The latest release of that package is 1.80.0 from April leading to pulling in matrix-synapse 1.80 which doesn't have the fix either :( .

Would highly appreciate if a new release of the testutils could be cut by the maintainers! 

### Steps to reproduce

- create new synapse template with cookiecutter
- add dependencies: ```

dependencies = [
  "matrix-synapse >= 1.95.1",
]

[project.optional-dependencies]
dev = [
  "matrix_synapse_testutils",
]
  ```
- See it fail: ```

ERROR: Cannot install matrix-synapse[test]==1.65.0 and synapse-super-invites[dev]==0.1.dev1+g215546d.d20231114 because these package versions have conflicting dependencies.

The conflict is caused by:
    synapse-super-invites[dev] 0.1.dev1+g215546d.d20231114 depends on matrix-synapse>=1.95.1
    matrix-synapse[test] 1.65.0 depends on matrix-synapse 1.65.0 (from https://files.pythonhosted.org/packages/7b/d4/a2e1dc91492aca455fb7507d069b6f75de6cea15c2534d2e2c3c3bb6b23b/matrix_synapse-1.65.0-py3-none-any.whl (from https://pypi.org/simple/matrix-synapse/) (requires-python:>=3.7.1,<4.0.0))

```

### Homeserver

n/a

### Synapse Version

n/a

### Installation Method

pip (from PyPI)

### Database

n/a

### Workers

Single process

### Platform

Arch Linux

### Relevant log output

```shell
n/a
```

**Comment by gnunicorn** [comment]
Workaround until then: adding `"pydantic >=1.7.4, <2"` as a dependency on the local project:
```
dependencies = [
  "matrix-synapse",
  "pydantic >=1.7.4, <2",
  "attrs"
]
```

**Comment by clokep** [comment]
This package is not released by us: https://pypi.org/project/matrix-synapse-testutils/

See https://github.com/julianhille/matrix-synapse-testutils

**Comment by gnunicorn** [comment]
I see. Didn't realize. Thanks for the heads up, @clokep !
