### ISSUE TITLE
RFC: There should be a default push gateway using webpush

### ISSUE THREAD

**Issue by spacekitteh** [matrix-org/synapse#1666]
The current method of providing Matrix notifications is outlined [here](https://matrix.org/docs/spec/push_gateway/unstable.html). That's reasonable for a generic protocol. 

However, many users refuse to have non-free software (e.g. GCM/APNS) on their devices; or an internal network using a Matrix system might restrict internet connectivity. A fallback should be required for these cases. This can be pretty straightforwardly implemented via HTTP/2 (see the IETF RFCs).

So, the instead of having to leave the homeserver, go through an external push gateway, then an external push provider, then to the client (the method in the spec to do it via GCM or APNS), Synapse should have its own webpush implementation (and ideally, it should be included in the matrix push spec). 

Not only will it solve the issues mentioned above, but it means that Riot, for example, no longer has to drain battery life through polling!

Further, it would set a good reference implementation for the matrix push spec

Web push RFC specs: https://datatracker.ietf.org/wg/webpush/documents/

**Comment by dbkr** [comment]
If I'm understanding webpush correctly, the HTTP 2 pull side of it would basically end up looking very similar to the existing sync protocol but over HTTP 2 (and with a filter for just notifications) so I suspect it would make sense to go more in that direction (although that doesn't rule out offering the same with the web push protocol if it would allow compatibility with other things talking web push)

**Comment by WGH-** [comment]
Is it related to Web Push API standard that's being developed for browsers? The one that allows web apps to push notifications even when tab is not open.

**Comment by ara4n** [comment]
webpush != desktop notifs, aiui (there is a separate bug for that).

The idea of having a custom push gateway (like @slp's go one) but using HTTP/2 as the transport is intriguing. i sympathise with Dave that it would overlap a lot with a hypothetical webpush flavour of the actual CS API - and for e2e encrypted notifs we may need to pull in more of the CS API than previously (especially as detecting notifs may have to happen clientside). My hunch is also that we should look at making synapse speak http/2 and use webpush for sync results (and add a filter to only sync notif-relevant data).

Definitely something to think about - we clearly need to overhaul push again.

**Comment by spacekitteh** [comment]
There is this:

http://calendar.perfplanet.com/2016/http2-push-the-details/

**Comment by spacekitteh** [comment]
Related: #1699

**Comment by subiol** [comment]
+1 Matrix protocol needs a push mechanism.

**Comment by Keridos** [comment]
Yup +1

**Comment by bwindels** [comment]
FWIW, I'm adding webpush support to sygnal in https://github.com/matrix-org/sygnal/pull/177. Webpush seems to be confused with HTTP/2 Server Push in this ticket though, web push notifications still leave the homeserver and depending on the platform and browser will get routed over the vendor's push gateway like GCM. It sounds like the author of the ticket would rather want HTTP/2 Server Push rather than web push. Perhaps we should rename the ticket accordingly?

**Comment by bwindels** [comment]
Also see https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1 (which I haven't read entirely) in that HTTP/2 Server Push is so little used that Chromium considered removing support for it, but seems to be holding off for now. Might not be the best thing to build on top though. Not sure what the alternative would be ... HTTP3/Push is mentioned there but that isn't supported anywhere yet.

**Comment by clokep** [comment]
I'm going to close this since WebPush was implemented in matrix-org/sygnal#177 and as @bwindels said this ticket is a bit confusing in terms of also discussing transport layer changes.
