### ISSUE TITLE
E2EE: Error: Duplicate message index, possible replay attack

### ISSUE THREAD

**Issue by aurabindo** [matrix-org/synapse#1669]
Sender : Riot 0.6.3 (Play store)
Receiver : Riot Web 0.9.0

Event Id : `$14808717113401196FlzLb:matrix.org`

In an encrypted text message to a person, a text message was sent to me, and I received errors :
`**Error: Duplicate message index, possible replay attack: cUBU9NTKml6cjij5GsLSufc9EZj5G9IRBU0rvVOegyw|xTAsIyxK3BPq6GllCplYR2CwvbjpCMt6uy8F+yWG7nU|0**
**Error: Duplicate message index, possible replay attack: cUBU9NTKml6cjij5GsLSufc9EZj5G9IRBU0rvVOegyw|xTAsIyxK3BPq6GllCplYR2CwvbjpCMt6uy8F+yWG7nU|1**`

It was an abrupt error. Only two of these errors and the conversation wasn't affected afterwards

**Comment by richvdh** [comment]
@aurabindo: this looks like an issue from the sender's side. I'll raise it on the android project.
