### ISSUE TITLE
E2EE:  Mismatched room_id for inbound group session

### ISSUE THREAD

**Issue by aurabindo** [matrix-org/synapse#1670]
This error was received for a message I sent to an encrypted group from one of my device.
I opened the same group in Riot Web, and I see this error:

`**Error: Mismatched room_id for inbound group session (expected !NmnHdagwJzKENAFywg:matrix.org, was !XLWyWCSLuZXbEICJOL:matrix.org)**`

Event id : `$14809148653745127JvpkR:matrix.org`

But others are able to read it. They are on Android.

**Comment by richvdh** [comment]
Again, looks like an issue on the sender.
