### ISSUE TITLE
"Internal server error" when upgrading a room created with Conduit

### ISSUE THREAD

**Issue by progval** [matrix-org/synapse#16715]
### Description

Upgrading a room created with Conduit returns "Internal server error"

### Steps to reproduce

1. Create a room with Conduit
2. Invite a Synapse user to it, make them admin
3. Make the Synapse user upgrade the room (eg. `/upgraderoom 11` in Eleweb)

Synapse returns `{"errcode":"M_UNKNOWN","error":"Internal server error"}`

### Homeserver

matrix.org and Conduit

### Synapse Version

1.96.1 (b=matrix-org-hotfixes,9c3b906b3a)

### Installation Method

I don't know

### Database

postgresql

### Workers

Multiple workers

### Platform

n/a

### Relevant log output

```shell
Nothing from Conduit.

I tried it on matrix.org, `synapse-trace-id: b6592675a1c241fa`
```

**Comment by erikjohnston** [comment]
Raw stack trace:

```
ValueError: max() arg is an empty sequence
  File "twisted/internet/defer.py", line 2000, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "synapse/util/caches/response_cache.py", line 258, in cb
    return await callback(*args, **kwargs)
  File "synapse/handlers/room.py", line 306, in _upgrade_room
    await self.clone_existing_room(
  File "synapse/handlers/room.py", line 552, in clone_existing_room
    state_default_int, ban, max(event_power_levels.values())
```

Corresponds to: https://github.com/matrix-org/synapse/blob/63d96bfc61fcbf53e9607c63f215d2dde387de29/synapse/handlers/room.py#L552

Sentry link: https://sentry.tools.element.io/organizations/element/issues/85240/?project=2

The power level content is:

`{"users":{"@<redacted>":100,"@<redacted>":100,"@<redacted>":100}}`

So looks like we need to correctly handle an empty/missing `events` key. I think we can change the `max(event_power_levels.values())` to include a `default=0`?
