### ISSUE TITLE
Sentry Alert configuration based on production and development environment

### ISSUE THREAD

**Issue by zeeshanrafiqrana** [matrix-org/synapse#16732]
### Description

Hey Folks!
I hope you all are doing well, I self hosted matrix synpase server. While working with sentry alert i found some time local/ dev environments are also triggering over the same DSN for production.
After taking a look i found that sentry provide us environments option there so that alert will remain in specific group not mixed up and management keep easy for administrator to fix.

I have solution also to specify environments, if someone also face such type of issue i can open contribute here.

Thanks

![image](https://github.com/matrix-org/synapse/assets/76243209/ab0dfbbc-95ec-44db-80f1-2abc6912c3f8)

### Steps to reproduce

Steps to reproduce

- enable sentry configuration in homeserver.yaml
- add dsn and use same dsn over locall, production, development and stage environment
- We need to check there by taking a look on trace to find which domain / ip is throwing the error.

### Homeserver

matrix-server.sociail.com

### Synapse Version

{"server_version":"1.96.0rc1 (b=TSK-577,8fe8534,dirty)"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

Postgres

### Workers

Single process

### Platform

Linux

### Configuration

sentry:
  dsn: "w3e4r5t6y7u8i9o0-"

### Relevant log output

```shell
No Logs.
Sentry Alert related issue
```

### Anything else that would be useful to know?

NA

**Comment by DMRobertson** [comment]
I think we'd accept a PR which adds an `env` field under the `sentry` config and passes it to the sentry-sdk at startup time.
