### ISSUE TITLE
'dynamic_thumbnails' ignores aspect when scaling

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#1677]
Turning on the 'dynamic_thumbnails' option on synapse results in images you see in the riot web client being scaled to the exact dimensions given in the URL query rather than the dimensions acting as a bounding box and aspect-scaling. This makes images look very silly.

**Comment by lukebarnard1** [comment]
There is a PR for the above commit: https://github.com/matrix-org/synapse/pull/1816
