### ISSUE TITLE
ldap3 API has changed in version 2

### ISSUE THREAD

**Issue by superboum** [matrix-org/synapse#1692]
Hi,

I've installed synapse on Debian Stable (Jessie) from the matrix repository.
I've configured `homeserver.yaml` to use my ldap server.

The first time I launched it, it said that ldap3 was not found. I didn't find any documentation on how to install synapse, but I understood that I had to install `ldap3` package with `python-pip`.

When I launched it, I had the following error : 
`AttributeError: 'module' object has no attribute 'AUTH_SIMPLE'`

It appears that python can't find `AUTH_SIMPLE` from `ldap3`. Indeed, when we read the [ldap3 changelog](https://ldap3.readthedocs.io/changelog.html), we see that : 

> 2.0.7 2016.10.27
>  * FIRST RELEASE OF LDAP3 V2
>  * ...
>  * The following older constants in ldap3 have been removed, please use the suggested ones:
>     * AUTH_ANONYMOUS = ANONYMOUS
>     * AUTH_SIMPLE = SIMPLE
>     * AUTH_SASL = SASL 

I've found a workaround by running `pip install ldap3==1.4.7` which is the latest version of ldap3 before the v2.

I don't know what you want to do (update `ldap_auth_provider.py` or keep the old version of ldap3) or even if I missed something (an instruction in the documentation, a `requirement.txt` file) and so this issue should be useless.

I can't start working on a patch (if you want to upgrade to ldap3 v2) before 2 weeks and I'm not sure that this hypothetical fix will work, so everyone wanting to fix this issue is welcome :)

**Comment by mweinelt** [comment]
This was addresed in https://github.com/matrix-org/matrix-synapse-ldap3/commit/f7460ece6b3552810f82d7d1080067080c113c92.
