### ISSUE TITLE
[e2e] Voip call events are outnumbered

### ISSUE THREAD

**Issue by jeangb** [matrix-org/synapse#1703]
I've been reproducing this on riot-android, iOS and web-client.
To reproduce:
- Call a client in a e2e 1:1 room, then hang up a few seconds later
- Badge of missed messages/events on callee device is 3 ou 4, and would be just 1 if the room wasn't encrypted.

Related to:
https://github.com/vector-im/riot-ios/issues/872
https://github.com/vector-im/riot-android/issues/785

**Comment by richvdh** [comment]
I *think* this is the same as #2193
