### ISSUE TITLE
How to manage the accounts and server status etc.

### ISSUE THREAD

**Issue by wjhtinger** [matrix-org/synapse#1708]
Is there any tools to manage the accounts and query server status, just how many accounts in DB and what accounts is online or offline, etc.?

**Comment by aaronraimist** [comment]
Seems like this issue is basically #2032 which came later but got all of the 👍s

**Comment by neilisfragile** [comment]
https://github.com/matrix-org/synapse/pull/4338 lays the ground work for much improved server admin support, once it lands then we need to expose the data via an API which at least provides an easy way to get the data.

Given #2032 I'm going to close this as a dupe
