### ISSUE TITLE
.onion domain homeserver?

### ISSUE THREAD

**Issue by RoPe93** [matrix-org/synapse#171]
If I do not have a domain name can I run Matrix homeserver from .onion domain on desktop pc?

**Comment by erikjohnston** [comment]
No, you won't be able to, alas. Home servers are located via DNS SRV records and must be reachable directly by TCP.

**Comment by ara4n** [comment]
(unless you ran a federation of servers that was only accessible via Tor, i guess)

**Comment by firas440** [comment]
Hi
