### ISSUE TITLE
Files uploaded into chat (media) is accessible by direct link to everybody.

### ISSUE THREAD

**Issue by user318** [matrix-org/synapse#1716]
If file is uploaded to the chat it becomes available with such url:
https://<domain>/_matrix/media/v1/download/<domain>/<hash>
And it can be downloaded by anybody. Even by unauthorised users. And of course it is not verified that user have access to the chat.
I think it should be considered an error.

**Comment by uhoreg** [comment]
Looks like a dup of #1403

**Comment by Half-Shot** [comment]
Wrote a response on #1403

**Comment by user318** [comment]
Yes. Closing this issue then.
