### ISSUE TITLE
Kicked user can still send message to a room

### ISSUE THREAD

**Issue by mytbk** [matrix-org/synapse#1718]
I reported this in #matrix-dev:matrix.org (permalink [1]). I have a room ``#service:matrixim.cc`` on my HS, then use riot-web to login as guest on matrix.org, and join this room. After I kick this guest, it can still send messages, although it can't see the messages I send anymore.

[1] https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$148256321716MHCxa:matrixim.cc

**Comment by ara4n** [comment]
related to https://github.com/matrix-org/synapse/pull/1758?

**Comment by richvdh** [comment]
yup, fixed by #1758
