### ISSUE TITLE
Question regarding filters

### ISSUE THREAD

**Issue by GalPressman** [matrix-org/synapse#1720]
Hello,
I have a question regarding `filters`, as explained in [filtering](http://matrix.org/docs/spec/client_server/r0.2.0.html#filtering).

Let's imagine the following scenario:
My client has joined many rooms, but chose to filter out only one of them.
After a period of time, he changed his filter to include all rooms.
Will he now get the events he missed (from other rooms) while the first filter was active? are those events gone?
I want to use this feature but the spec is not clear enough in my taste, and time doesn't allow me to implement only to find out the actual behavior :).

Thanks for the help.

**Comment by ara4n** [comment]
filter changes apply to the api being used - either /sync (for realtime events) or /messages (for historical ones). changing filter in the middle of a sequence of syncing or scrollbacking won't cause you to suddenly see events from previous requests.

**Comment by GalPressman** [comment]
Thanks for clarifying.
So as far as I understand I can't choose to "postpone" events to a later time for syncing, is that correct?
For example, After receiving many messages to many rooms (without syncing) I would like to sync my rooms one by one. Syncing with the first's room filter will just dismiss all other events?
This wanted functionality should be implemented by the client itself?

**Comment by ara4n** [comment]
Yup. If you are syncing all rooms and then narrow the filter to sync a single room, you will discard events until you broaden the filter again. The solution is to remember the sync token at the point you narrow it, so if you subsequently want to rebroaden again you just start another sync sequence from that token with the wider (or inverse) filter.

**Comment by GalPressman** [comment]
Thanks for the help, now I understand :).
