### ISSUE TITLE
reinstall synapse caused matrix.org refuse my server's request

### ISSUE THREAD

**Issue by LifeNT** [matrix-org/synapse#1721]
I didn't backup my old server keys, and I reinstall my synapse, and the matrix.org  is refuse my server request , how to fix this?

I can't get room info from matrix.org on my home server, can't receive private message from account on matrix.org, when I try to get messages from the day before yesterday, it's give me "Matrix Error: Unauthorized"

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/synapse/issues/1975
