### ISSUE TITLE
synapse service deployment issues

### ISSUE THREAD

**Issue by hy372690150** [matrix-org/synapse#1722]
Hello:
I would like to faster deployment of synapse, some questions please help answer

Configuring synapse:

Cd ~ / .synapse
Python -m synapse.app.homeserver \
     --server-name my.domain.name \
     --config-path homeserver.yaml \
     --generate-config \
     --report-stats = [yes | no]

I would like to ask
1.synapse.app.homeserver What is the meaning of this parameter, I guess it should be connected to your server, synapse can be independent of a separate service

**Comment by Half-Shot** [comment]
``-m synapse.app.homeserver `` is telling python what module to load, which is synapse. This shoudln't need to be changed.
