### ISSUE TITLE
Remote users are failing to part rooms

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1740]
e.g. https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/%24148279203671YatYF:im.nostrodomo.tk and https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1483141791117927meyDz:matrix.org

**Comment by ara4n** [comment]
sounds like this is an artefact of federation breaking due to #1733

**Comment by 4nd3r** [comment]
joined, idled a while and /part - got error _Not a known room_. joining again didn't help neither.
after 15 minutes or so room came to life with lots of messages and after that /part worked.

**Comment by richvdh** [comment]
remote users can part rooms now
