### ISSUE TITLE
allow authenticating against diaspora

### ISSUE THREAD

**Issue by pravi** [matrix-org/synapse#1746]
You can see how prosody is authenticating against diaspora here
https://github.com/Zauberstuhl/gem_diaspora-prosody-config/tree/master/modules

There is also ejabberd-diaspora auth and its in pythos so it may be easy to modify it
https://github.com/bluszcz/ejabberd-diaspora-auth

I'd like to run matrix service from diasp.in and poddery.com if we can get this working. It would also encourage many other diaspora pods (podupti.me has a list of pods) to activate it too making the matrix federation much bigger.

**Comment by pravi** [comment]
https://github.com/matrix-org/matrix-synapse-ldap3 can be used as a reference.

**Comment by necessary129** [comment]
https://git.fosscommunity.in/necessary129/synapse-diaspora-auth would do it hopefully. Can someone review it?

**Comment by pravi** [comment]
Thanks @necessary129  We are running this live on diasp.in, so closing.
