### ISSUE TITLE
Ability to store files in a CDN network or a S3 type server

### ISSUE THREAD

**Issue by sraja415** [matrix-org/synapse#1749]
I use Amazon EC2 but I am unable to store files in S3 server. We need functionality where by we can use the storage of servers in a different place like Google Cloud, Amazon S3 etc. instead of worrying about Hard Disk Capacity.

**Comment by erdii** [comment]
IMO a generic cloud storage backend with the ability to let files expire to keep costs low would be really nice!

**Comment by myfreeweb** [comment]
Yeah, FUSE filesystems are a thing but it would be nice to actually let everyone download directly from the storage service instead of the download being essentially proxied through the homeserver.

[libcloud](https://libcloud.apache.org) supports AWS S3, OpenStack Swift, Google Cloud Storage etc.

**Comment by k3vmcd** [comment]
I'd love to store on Amazon Cloud Drive

**Comment by neilisfragile** [comment]
Fixed in #2767

**Comment by oliverjanik** [comment]
Where's documentation for this?
