### ISSUE TITLE
Have Images and Videos as links for forwards

### ISSUE THREAD

**Issue by sraja415** [matrix-org/synapse#1750]
When I forward a image or video it creates another file occupying storage and increasing costs. This should be reduced by having them as links instead of storing again.

We should also track the creator and he/she alone has the option of deleting it. If deleted by the creator/first uploader, the links should stop working. Video properties should contain the Matrix User ID of the original creator/first uploader.

**Comment by kythyria** [comment]
> If deleted by the creator/first uploader, the links should stop working

That sounds like a good reason to not change the current behaviour.

**Comment by sraja415** [comment]
1. What about the wasted storage. I forward a viral video 5 MB to 300 groups = 1500MB wasted for 1 video. Even Google attempted this for their email forwards. 

Mathew also that it is a good to reduce size. 

2. You send a confidential video/doc/image as a confused young 20 something old..are we saying that his/her life has to be destroyed. Snap chat destroys on read. Just some fo

Sent from my iPhone. Pardon my 
brevity.

**Comment by kythyria** [comment]
> What about the wasted storage. I forward a viral video 5 MB to 300 groups = 1500MB wasted for 1 video. Even Google attempted this for their email forwards. 

Servers can deduplicate if they want to, or you could use a client that reuses the same mxc URI.

>  Snap chat destroys on read.

It claims to. This is a very different thing to actually doing so. It's not possible to build a messaging system that gives that guarantee.

**Comment by Half-Shot** [comment]
Should this be moved to matrix-org/matrix-react-sdk?

**Comment by gonight** [comment]
Can't we add a right-click or some sort of menu option with a 'forward' button that functions as specified? There are use cases where some users (myself, for example) don't care about security, i.e. forwarding the latest 'dank meme' to a friend.

RE: 'who can delete', I would argue that any forwarded/sent image no longer exists as solely tied to the original user. The snapchat 'delete' function is so commonly worked-around (screenshot being the most obvious and basic example) that it's almost a counter-example. Ultimately, users will save data in their possession that they wish to retain. Deletion should work the same in 'forwarded' and 're-sent' files.

Depending on implementation, this seems like a pretty solid method to give users the option to save data on the homeserver they're using, and arguably even the entire network, in a pretty intuitive way without compromising functionality.

**Comment by aaronraimist** [comment]
This was probably supposed to be a Riot issue? Anyway using Riot's forward feature, media isn't duplicated, it references the existing media.
