### ISSUE TITLE
put synapse version in Server header for federation, not the twisted version(!)

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1751]

**Comment by kyrias** [comment]
It seems like this should have worked for a long time, but for some reason hasn't.  On my HS it's started working properly though, which I think is a twisted change.

**Comment by Skons** [comment]
See issue #2324 , federation should not be done by publicly available version numbers.

**Comment by aaronraimist** [comment]
This is probably fixed?

**Comment by richvdh** [comment]
yeah I think so.
