### ISSUE TITLE
synapse breaks when registration_shared_secret contains a backslash

### ISSUE THREAD

**Issue by adnidor** [matrix-org/synapse#1752]
Relevant Stacktrace:
`Traceback (most recent call last):`
`File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main`
`"__main__", fname, loader, pkg_name)`
`File "/usr/lib/python2.7/runpy.py", line 72, in _run_code`
`exec code in run_globals`
`File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 484, in <module>`
`main()`
`File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 479, in main`
`hs = setup(sys.argv[1:])`
`File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 271, in setup`
`config_options,`
`File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 322, in load_or_generate_config`
`generate_keys=generate_keys,`
`File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 341, in read_config_files`
`yaml_config = self.read_config_file(config_file)`
`File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 140, in read_config_file`
`return yaml.load(file_stream)`
`File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load`
`return loader.get_single_data()`
`File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data`
`node = self.get_single_node()`
`File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node`
`document = self.compose_document()`
`File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document`
`node = self.compose_node(None, None)`
`File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node`
`node = self.compose_mapping_node(anchor)`
`File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node`
`item_value = self.compose_node(node, item_key)`
`File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 64, in compose_node`
`if self.check_event(AliasEvent):`
`File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event`
`self.current_event = self.state()`
`File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value`
`if not self.check_token(KeyToken, ValueToken, BlockEndToken):`
`File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token`
`self.fetch_more_tokens()`
`File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 248, in fetch_more_tokens`
`return self.fetch_double()`
`File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 652, in fetch_double`
`self.fetch_flow_scalar(style='"')`
`File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 663, in fetch_flow_scalar`
`self.tokens.append(self.scan_flow_scalar(style))`
`File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 1152, in scan_flow_scalar`
`chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))`
`File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 1226, in scan_flow_scalar_non_spaces`
`"found unknown escape character %r" % ch.encode('utf-8'), self.get_mark())`
`yaml.scanner.ScannerError: while scanning a double-quoted scalar`
`in "/etc/matrix-synapse/homeserver.yaml", line 299, column 29`
`found unknown escape character 'o'`
`in "/etc/matrix-synapse/homeserver.yaml", line 299, column 49`

**Comment by Half-Shot** [comment]
Unless synapse also generates this. I'm tempted to say this isn't a bug. Could you clarify on whether this was user generated or the synapse configuratoratron did this?

**Comment by adnidor** [comment]
No, I generated the secret manually using `pwgen -sy 50` because the debian package doesn't generate one automatically.

It is neither documented that \ isn't a valid character for the secret, nor does it produce a "clean" error message when encountered but crashes with a stacktrace

As I see it, this is definitely a bug with the following possible fixes:
- Patch the code to allow for special characters
- Update the documentation to include valid characters for registration_shared_secret
- Patch the code to not crash, but produce a warning and just not use the shared_secret

**Comment by richvdh** [comment]
homeserver.yaml is, uh, yaml. `\` is a special character in yaml. *Obviously* you're going to have to quote it. The exception comes from the YAML parser, not synapse. I don't think there's much we can plausibly do to improve this.
