### ISSUE TITLE
prev_events are not capped at 10 seemingly

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1759]
Levans left #rust and generated a horrible event: $148356248478NhIOn:safaradeg.net with 23 prev-events (due to accumulating extremities - see #1760) which causes problems for anyone who tries to auth(?) it, e.g. Ralith.  I thought we were capping number of prev_events at 10 to avoid this sort of thing

**Comment by NegativeMjark** [comment]
We limit the prev_events on one of the code paths:

https://github.com/matrix-org/synapse/blob/v0.18.5/synapse/handlers/message.py#L427

However the code path at:

https://github.com/matrix-org/synapse/blob/v0.18.5/synapse/handlers/room_member.py#L291
https://github.com/matrix-org/synapse/blob/v0.18.5/synapse/handlers/room_member.py#L72
https://github.com/matrix-org/synapse/blob/v0.18.5/synapse/handlers/message.py#L225
https://github.com/matrix-org/synapse/blob/v0.18.5/synapse/handlers/message.py#L416

Uses an unlimited number of prev events loaded at:

https://github.com/matrix-org/synapse/blob/v0.18.5/synapse/handlers/room_member.py#L209

**Comment by richvdh** [comment]
This appears to still be the case, ftr.

**Comment by richvdh** [comment]
This got fixed in #3113.
