### ISSUE TITLE
When a user leaves a room, a subsequent join doesn't propagate to other client instances

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1770]
Random hypothesis: the /sync gets wedged doing some enormous state group resolution like the ones in #1761, and is timed out clientside before it can return?

**Comment by ara4n** [comment]
```
Matthew : to be precise, the part does propagate, but the join afterwards does not. Like, if I part/re-join from the riot on my desktop, then 3 hours later power up my laptop and open riot, it believes I'm not in the room.
```

**Comment by vberger** [comment]
To give all possible details (from what I remember):

- two days ago I left #mozilla_#rust:matrix.org and rejoined from a riot.im/develop instance
- the rejoin was troublesome, got a message about the room being "not available"
- reloading (F5) my riot tab displayed me as properly in the room
- now, when I open riot.im/develop on other computers, it believe I'm not in the room
- riot-android properly displays me in the room
- I just tried to join the room from an other riot instance, for 2 second it displayed the message "you are trying to access.... would you like to join...." and before I could click on the "join" link, the room reloaded, appeared in my room list and riot shows believes I'm in
- after reloading riot (F5), it again shows me not in the room

**Comment by richvdh** [comment]
given this hasn't been reported for 3.5 years, and *everything* has changed in the meantime, I'm going to close this.
