### ISSUE TITLE
global name 'SessionExpiredException' is not defined

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1771]
when clicking on old riot email verification links

**Comment by vodik** [comment]
I took a screenshot when I hit it, might as well attach it for you guys:

![1483676089](https://cloud.githubusercontent.com/assets/216803/21709118/80262314-d3ac-11e6-8414-d680482517e7.png)

**Comment by Kegsay** [comment]
Looks like sydent not synapse?

**Comment by dklimpel** [comment]
This is not a Synapse issue.
