### ISSUE TITLE
export metrics that characterise heap spikes

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1779]
as per #1760, synapse's bad RAM usage is due to temporary heap alloc spikes whilst resolving state groups. I'm surprised our metrics don't show this happening more clearly, to judge how bad a problem it is. Can we graph number and size of state group resolutions? and number of events loaded from the store? and even size of the python heap (in the unlikely event of catching a spike in the act)?

**Comment by richvdh** [comment]
we graph a number of these things now.
