### ISSUE TITLE
Filtering: Limit on State Events do not work

### ISSUE THREAD

**Issue by pik** [matrix-org/synapse#1782]
For example the following filter will correctly apply `"limit" : 0` to `timeline` but not to `state`. 

```py3
{ "room": { "timeline" : { "limit" : 0 }, "state": { "limit": 0 }}
```

Since `state` is a graph-traversal it's not necessarily obvious how to add this functionality in a neat way (or if it is a sensible parameter to have). This is relevant for allowing low-bandwidth clients to render a Riot-Web interface (atm `state` event sets are not limited and `/sync` cannot complete). https://github.com/vector-im/riot-web/issues/2737

**Comment by ara4n** [comment]
it's a feature that you can't limit or paginate state currently. i don't think the spec or anywhere else claims that you can.

**Comment by turt2live** [comment]
@ara4n https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-user-userid-filter says that `state` is a `RoomEventFilter`, which takes an optional `limit` parameter.
