### ISSUE TITLE
Attribute Error: EventContext has no attribute "current_state_events"

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/synapse#1785]
At https://github.com/matrix-org/synapse/blob/v0.18.7-rc2/synapse/state.py#L197

`"current_state_events"` is not listed in the `__slots__` at https://github.com/matrix-org/synapse/blob/v0.18.7-rc2/synapse/events/snapshot.py#L18-L27

**Comment by NegativeMjark** [comment]
This causes an error when processing incoming events with a low depth. I dunno how much of an impact it has since old events will need to be backfilled anyway so it's not obvious how much value we gain by processing the ones we receive via the federation send API.

https://github.com/matrix-org/synapse/blob/v0.18.7-rc2/synapse/federation/federation_server.py#L559

**Comment by richvdh** [comment]
allegedly fixed by #1849
