### ISSUE TITLE
Reason key isn't upheld on /kick

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/synapse#1788]
The [kick API](http://matrix.org/docs/spec/client_server/r0.2.0.html#post-matrix-client-r0-rooms-roomid-kick) sez that you can put a `reason` key when kicking, but it looks like the REST servlet never passes the content (and hence can never pass the reason) to `room_member_handler. update_membership`. I believe this is why the JS SDK ends up relying on [the generic state API](http://matrix.org/docs/spec/client_server/r0.2.0.html#put-matrix-client-r0-rooms-roomid-state-eventtype-statekey) instead.

**Comment by richvdh** [comment]
this got fixed in https://github.com/matrix-org/synapse/pull/1917
