### ISSUE TITLE
429 responses are cached

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/synapse#1801]
Requests/responses such as 

`warn: matrix-appservice-bridge [-] PUT http://localhost:8080/_matrix/client/r0/rooms/!mhAdlVvCyQdKdmuIlm%3Alocalhost%3A8480/send/m.room.message/m1484159120283.7 (@_twitter_1344951:localhost:8480) HTTP 429 Error: {"errcode":"M_LIMIT_EXCEEDED","error":"Too Many Requests","retry_after_ms":1480}
`

have been observed running the twitter bridge against a local synapse. These appear to by cached responses and despite the js-sdk retrying after the given number of `retry_after_ms`, what appears to be a cached response.

It would be best not to cache these so that the js-sdk doesn't retry for as long as the request is cached.

**Comment by ara4n** [comment]
It looks like the HttpTransactionCache layer is blindly caching HTTP responses for 30-60mins regardless of whether they are error codes or not.  @erikjohnston/@NegativeMjark is this deliberate?

**Comment by Kegsay** [comment]
Most likely not. I touched it last to convert it to using `ObservableDeferred`s. We should be doing rate limit checks well before then but I guess we don't.

**Comment by Kegsay** [comment]
I have fixed this: https://github.com/matrix-org/synapse/pull/1913
