### ISSUE TITLE
Messages sometimes fail to federate until another message is sent

### ISSUE THREAD

**Issue by VShell** [matrix-org/synapse#1804]
Occasionally, messages from users on other servers in less-busy rooms will fail to appear on my server until another message is sent by that user. This particularly affects me in direct chat rooms with bridged users on matrix.org, and results in confusion when I reply to a message that might be hours old, or when I'm expecting a message and I never get it. I suspect that my server rejects the transaction for some temporary reason, and it isn't retried properly.

**Comment by ara4n** [comment]
This is probably the same as https://github.com/matrix-org/synapse/issues/1386

**Comment by ara4n** [comment]
dup #2528
