### ISSUE TITLE
Does the new 3 minute fed client timeout break things?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1806]
@erikjohnston said that there are some federation requests which can legitimately take a long time. is the emergency 3 minute timeout introduced in https://github.com/matrix-org/synapse/pull/1725 going to cause more problems than it solves?

**Comment by richvdh** [comment]
Possibly, but I can't see the existence of this bug prompting us to go on an expedition to find out. Can we close this, in the expectation that, if it does cause issues, we'll find out and raise another issue accordingly?

**Comment by anoadragon453** [comment]
The conversation has continued in more recently in https://github.com/matrix-org/synapse/issues/8338.

Going to close this issue as there's nothing separately actionable here.
