### ISSUE TITLE
Media repository performance is disasterously slow

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1807]
Uploading from the London office to the London datacenter goes at about 200KB/s max, even with the media repo now on a fastish NFS JBOD.  The media repo has always been weirdly slow - it feels like there's some major thinko in the media repo servlet performance.

**Comment by ara4n** [comment]
...and downloading at 600KB/s.  Makes sharing 50MB presentations unusable :(

**Comment by richvdh** [comment]
related: #1476. I think this has probably been fixed by some rewrite of the media storage layer at some point.
