### ISSUE TITLE
Room invite: invited matrix id with wrong domain return "Internal server error"

### ISSUE THREAD

**Issue by jeangb** [matrix-org/synapse#1819]
This api https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-client-unstable-rooms-roomid-invite
returns "Internal server error" when a matrix id with non existent domain is sent. For example: 

> riotuser99:matrix.orgs

We should return a more user friendly msg.
For the time being this error message is returned to the riot user when he invites a wrong matrix id.

**Comment by richvdh** [comment]
dup #2047
