### ISSUE TITLE
Back pagination is not working for found event

### ISSUE THREAD

**Issue by Mefi100feLL** [matrix-org/synapse#1825]
Hello.
I load the context for the event, found through a search to find a branch that corresponds to this event.
After loading the label, I try to load events before and after found. 
Events after the found loaded successfully. 
And the events before found to loading indefinitely until triggered timeout.

![pagination back](https://cloud.githubusercontent.com/assets/8769179/22063879/275e7688-dd92-11e6-820a-2b155b84412b.png)

**Comment by richvdh** [comment]
Possible this is related to https://github.com/matrix-org/synapse/issues/2504. I can't reproduce it now, so either way, I don't think there's anything else we can do.
