### ISSUE TITLE
key /query API doesn't seem to honour federation retry schedule

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1829]
If you keep hitting a server with /query/wherever.com, it seems to retry every time, rather than honouring the `destinations` table.  Possibly related to #1737 and friends

**Comment by ara4n** [comment]
apparently if you ask it to talk to an HTTP endpoint, it ends up hammering it every few seconds indefinitely :/

**Comment by richvdh** [comment]
I think @erikjohnston is changing how this works via the device list update stream stuff anyway. (Right, Erik?)

**Comment by richvdh** [comment]
Hopefully fixed by #2050
