### ISSUE TITLE
matrix.org melted due to 8 min queries deleting from EPA table

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1839]
e.g. `2017-01-20 13:05:58.104 GMT [matrix] LOG: duration: 462547.065 ms statement: DELETE FROM event_push_actions WHERE user_id = '@sneegert:matrix.org' AND room_id = '!LJdMiciydqJhmdppLS:matrix.org' AND topological_ordering < 543169 AND stream_ordering < 70544893`

**Comment by richvdh** [comment]
I'm guessing this either got fixed or was a transient.
