### ISSUE TITLE
preview_url without CORS?

### ISSUE THREAD

**Issue by almereyda** [matrix-org/synapse#1841]
Our local (still) Vector instance at https://vector.allmende.io displays CORS errors for `preview_url` of our `v0.18.7` homeserver.

![bildschirmfoto von 2017-01-20 20-26-29](https://cloud.githubusercontent.com/assets/1645308/22162370/c1c7be74-df4e-11e6-87a3-208cd45f8b29.png)

But these headers should be appended ¹ , so what is going wrong?

¹ https://github.com/matrix-org/synapse/blob/f5a4001bb116c468cc5e8e0ae04a1c570e2cb171/synapse/rest/media/v1/preview_url_resource.py

**Comment by ara4n** [comment]
CORS normally means that the server served up a 500 error or similar. 
The fact that the error happened to have no CORS is a distraction.

I suspect you need to correctly enable it in the config & deps as per 
https://github.com/matrix-org/synapse#url-previews

**Comment by almereyda** [comment]
Indeed, my omission.

When upgrading `synapse`, it's good to check the configuration against newer `--generate-config` examples.
