### ISSUE TITLE
Problems /invite-ing people into #tools:tomesh.net

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1846]
> benhylau The people experiencing /invite problems:
>
> `@simon:vodik.xyz`
> `@csmith:matrix.org`
>
> When I invite vodik to any room (no matter the room is on which hs) I get an Internal server error
I am able to send an invite to cSmith to #fc00-dev:tomesh.net but he is unable to join. We had ansuz cancel my invitation and invite him again, he hasn't accept, do idk whether that worked.

**Comment by ara4n** [comment]
@erikjohnston can you take a look at the matrix.org logs to see if we can see csmith's side of the problem?

**Comment by benhylau** [comment]
This is the room where all the people having issues are gathered:
https://chat.tomesh.net/#/room/#tools:tomesh.net

**Comment by cschmittiey** [comment]
Just to update I haven't been able to accept either of the two invites into #fc00-dev:tomesh.net.

**Comment by cschmittiey** [comment]
Trying to accept the invites give me a "You are not invited to this room" error, and rejecting them gives me a similar error but with the actual identifier of the room.

**Comment by benhylau** [comment]
Also, the room is public. I am unsure whether the it was private or public when I initially invited @cschmittiey but when @ansuz sent the invite it's definitely already public.

**Comment by richvdh** [comment]
@cschmittiey Is this still a problem?

**Comment by richvdh** [comment]
I'm guessing it's not...

**Comment by cschmittiey** [comment]
@richvdh It actually still is a problem - Those invites are still stuck in my account, I just forgot this issue existed. I've just been ignoring them, I haven't found any kind of way to dismiss the broken invite.

**Comment by cschmittiey** [comment]
I'm happy to troubleshoot and provide feedback as needed, but if it's a minor thing and you'd like to dedicate your time elsewhere, no worries!

**Comment by richvdh** [comment]
so these are invites that you have received from someone else, and you can't accept or reject?

have you tried dismissing them (which may error) and then flushing your client's cache?

is this on your own server or on matrix.org?

**Comment by cschmittiey** [comment]
Correct, I received them from others upthread. I can’t accept nor reject said invites. I’ve tried clearing caches, dismissing them.

The affected account is csmith on the matrix.org home server.

This broken invite persist across clients and has been attached to my account wherever I go for years now.

**Comment by richvdh** [comment]
without digging into it very hard, I'm going to assume this was caused by #1987. I've cleared the outstanding invites on your account; flushing the cache on your client once more should make them go away.
