### ISSUE TITLE
URGENT!!!! Change Password may locked out account

### ISSUE THREAD

**Issue by itree** [matrix-org/synapse#1847]
When changed password and deleting devices.  After logout, can't login again. 

When delete the devices, it accepted the changed password for validation. After that when logged out, then I'm not able to log in again, with both Old Password and Newly Changed Password. 

In short, I'm locked out of my account. This issue is URGENT

**Comment by schnuffle** [comment]
You could try to set your password with sqlite using the hash tool 

- Create a new password hash with scripts/hash_password -p <new_password>
- Shutdown synapse
- Make a copy of the db
- sqlite3 yourdb.sqlite
- UPDATE users SET password_hash='<paste_created_hash>'
WHERE name='<your_name>';

**Comment by KlausHans** [comment]
I've got the same issue.

schnuffle, what do i have to do if i have installed synapse via apt and the matrix repository?
I have no idea where synapse is installed, thus i don't know where the scripts folder is.

**Comment by schnuffle** [comment]
Glad you sorted it yourself, sorry that my SQL description was a bit misleading

**Comment by richvdh** [comment]
guessing it's no longer urgent.
