### ISSUE TITLE
Debian Package: GPG: signatures couldn't be verified 

### ISSUE THREAD

**Issue by itree** [matrix-org/synapse#1855]
Where can we import the pub keys for the debian packages?
i got his errro when I try to install the package. from https://matrix.org/packages/debian/

W: GPG error: https://matrix.org/packages/debian stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY AD0592FE47F0DF61
W: The repository 'https://matrix.org/packages/debian stretch InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by itree** [comment]
keyserver.ubuntu.com seems to have the keys

but not keyring.debian.org, should someone add it?

This is what you need to do to get the key added:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AD0592FE47F0DF61

**Comment by uhoreg** [comment]
keyring.debian.org is only for keys in the Debian keyring (i.e. for Debian Developers and Debian Maintainer keys), so the matrix.org repo signing key will not go in there.

I think the best way to get the key is to do something like: `curl https://matrix.org/packages/debian/repo-key.asc | sudo apt-key add -`

**Comment by ssbarnea** [comment]
Pleaser reopen this bug because installation instructions for Debian do no include these steps, yet.

**Comment by andrewperry** [comment]
The key has moved so you'll have more success with:

`curl https://packages.matrix.org/debian/matrix-org-archive-keyring.asc | sudo apt-key add -`

**Comment by richvdh** [comment]
> `curl https://packages.matrix.org/debian/matrix-org-archive-keyring.asc | sudo apt-key add -`

Please don't do that. Any sources that suggest using `apt-key add` are outdated.

Full instructions are at https://github.com/matrix-org/synapse/blob/master/INSTALL.md#matrixorg-packages
