### ISSUE TITLE
Use a specific user-agent for fetching link previews

### ISSUE THREAD

**Issue by lindner** [matrix-org/synapse#1859]
Synapse fetches with Link Previews with something the default user agent:

Synapse/0.18.7 (b=matrix-org-hotfixes,3c9acde,dirty)

Instead a separate user agent with 'bot' in the name and a link to a page would indicate that these fetches are legitimate.  Something like this:

Synapse-LinkFetchBot/0.18.7 (+http://matrix.org/bot.html)

**Comment by richvdh** [comment]
as noted by #4376, the very specific user agent is also something of a data leak.

**Comment by Mikaela** [comment]
I guess this issue is why all [YouTube Music](https://music.youtube.com/) previews tell:

> Your browser has expired. Update browser.
> YouTube Music is not optimised for your browser. Check updates or use Google Chrome. Download Chrome

*freely translated from original:*

> Selaimesi on vanhentunut. Päivitä selain.
> YouTube Musicia ei ole optimoitu selaimellesi. Tarkista päivitykset tai käytä Google Chromea.Lataa Chrome
