### ISSUE TITLE
/unban broken

### ISSUE THREAD

**Issue by Zenexer** [matrix-org/synapse#1860]
*Moved from https://github.com/matrix-org/matrix-js-sdk/issues/341*

/unban is broken on clients that use `/rooms/{roomId}/state/leave` to unban users instead of `/rooms/{roomId}/unban`.  The user will receive the following error:

> Cannot leave user who was banned

https://github.com/matrix-org/synapse/blob/f0e4bac64e8a4eff8132afcfc8406ce5fac11369/synapse/handlers/room_member.py#L228

The cause is [this line](https://github.com/matrix-org/synapse/blob/f0e4bac64e8a4eff8132afcfc8406ce5fac11369/synapse/handlers/room_member.py#L225): when using the old/alternative method of unbanning users, `action` will be `"leave"` instead of `"unban"`.

However, fixing this without also updating the client(s) will result in the return of https://github.com/vector-im/riot-web/issues/1961, which is likely fixed at the moment.  This is because the server will be unable to differentiate between /kick and /unban.  matrix-js-sdk will need to be updated to use [what I assume is the "new" API call](http://matrix.org/docs/spec/client_server/r0.2.0.html#post-matrix-client-r0-rooms-roomid-kick).

**Comment by richvdh** [comment]
I don't think this bug is valid any more. If it is, please open a new bug stating clearly how synapse doesn't match the spec.
