### ISSUE TITLE
Could you explain the differences between similar components of Matrix.org and IPFS/libp2p in the FAQ or other section in the home page?

### ISSUE THREAD

**Issue by jmithmstr** [matrix-org/synapse#1874]
Could you explain the differences between similar components of Matrix.org and https://github.com/ipfs/ipfs or https://github.com/libp2p/libp2p in the FAQ or other section in the home page?

**Comment by Half-Shot** [comment]
I'd suggest you ask in matrix-org/matrix-doc

**Comment by jmithmstr** [comment]
Moved to: https://github.com/matrix-org/matrix-doc/issues/796
