### ISSUE TITLE
Issue with Debian Update 0.18.7 to 0.19.0

### ISSUE THREAD

**Issue by croulibri** [matrix-org/synapse#1882]
When trying to update Synapse in my Debian Jessie server with Matrix repository I was unable to do it and I receive the following message :
`Les paquets suivants contiennent des dépendances non satisfaites :`
` matrix-synapse : Dépend: python-twisted (>= 16.0.0) mais 15.2.1-1ubuntu1~matrix~jessie1 devra être installé`
`E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».`

Any other found this situation ?
What is the solution on a Debian install ?

Thanks for your advice !

**Comment by 4nd3r** [comment]
python-twisted 16 is available in jessie-backports.

```
# grep backports /etc/apt/sources.list
deb http://ftp.ee.debian.org/debian/ jessie-backports main
# apt-get update
# apt-get install -t jessie-backports python-twisted matrix-synapse
```

**Comment by croulibri** [comment]
Thanks for your answer and sorry for this so trivial question.
I looked at this package in Matrix repo but I forgot to search on backport.
Problem sokved !
