### ISSUE TITLE
Doesn't listen on IPv6 address

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/synapse#1886]
It seems to be only binding to the IPv4 address 0.0.0.0:8448 by default. The bind_address also doesn't support multiple addresses. But it can be worked around by just listing the port multiple times.

**Comment by ara4n** [comment]
`bind_addresses: []` should now take a list of addresses for multiple addresses, and if you bind to `::8448` i think that should include ipv6.

**Comment by kroeckx** [comment]
I'm not sure what you mean, but trying that with the 0.19 release doesn't seem to work.

**Comment by 14mRh4X0r** [comment]
If you set `bind_address` to `'::'`, Synapse will listen on both IPv6 and IPv4 (with default OS settings)

**Comment by kroeckx** [comment]
I want it to listen to a specific IPv6 address

**Comment by richvdh** [comment]
fixed by https://github.com/matrix-org/synapse/pull/2435
