### ISSUE TITLE
'body' not in content

### ISSUE THREAD

**Issue by xuloo** [matrix-org/synapse#1889]
I'm trying out Synapse as a possible solution for chat within an application and i'm having trouble sending messages to a room.

Via the http api i've:

1. created a new user
2. logged the user in
3. created a room
4. joined the user to the room

checking the database i can see the user exists, is a member of the room etc.

all is well so far - however, whatever i send in the body of the PUT request to 

`/_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}`

I receive a 400 response with the message

`{"errcode":"M_UNKNOWN","error":"'body' not in content"}`

The room id is definately correct, eventType is m.room.message and the transactionId is randomly generated for each request so it doesn't clash.

i've tried variations on 

```
{
  "content": {
    "body": "a simple message",
    "msgtype": "m.text"
  }
}
```

to no avail... no matter WHAT content the body of the request contains i ALWAYS receive the 400 with the same message. 

I'm assuming i'm doing something dumb here, but can't work out what. Can anyone shed any light on this?

I'm running Synapse on an Ubuntu Trusty install via Vagrant/VirtualBox from 

`pip install https://github.com/matrix-org/synapse/tarball/master `

as per the setup instructions

**Comment by turt2live** [comment]
The [specification](http://matrix.org/docs/spec/client_server/r0.2.0.html#put-matrix-client-r0-rooms-roomid-send-eventtype-txnid) appears to say sending just `{"body": "a simple message", "msgtype": "m.text"}` is correct (ie: no wrapping 'content' node).

**Comment by xuloo** [comment]
strange, i honestly thought i'd tried this earlier (and some other configurations) but i must not have - just tried again and it works!

thanks for your reply and apologies for wasting your time ;)

**Comment by bpcurse** [comment]
The examples in the API documentation might lead people to think the content node is necessary for simple messages.
https://matrix.org/docs/spec/client_server/latest#m-room-message

Perhaps this should be clarified in the docs.

**Comment by G2G2G2G** [comment]
Now with MSC1767 we're sending the body like 4 times per msg if it's html? Can we just.. not do that and synapse checks for body in the sub content as well? It seems to require the old msg type as well as the new, making there no reason to include the new, currently

**Comment by turt2live** [comment]
Please use the support rooms for questions, and open new issues for recurring bugs. Commenting on old issues such as this is unlikely to get attention, as demonstrated by the 1+ year delay on even seeing the comment above yours.
