### ISSUE TITLE
slack compatible webhooks

### ISSUE THREAD

**Issue by geromueller** [matrix-org/synapse#1894]
Many tools, e.g. jenkins, gogs, support slack compatible webhooks for notifications. It would be create to use these easily. the slack bridge seems overly complicated and does more than just receive messages.

**Comment by ShadowJonathan** [comment]
Should this also be documented over in [matrix-doc](https://github.com/matrix-org/matrix-doc) as a MSC?

**Comment by anoadragon453** [comment]
A feature like this would need to start as an [Matrix Spec Change](https://matrix.org/docs/spec/proposals), yes.

**Comment by ptman** [comment]
My feeling is that this shouldn't be part of synapse or the matrix spec. There's https://github.com/turt2live/matrix-appservice-webhooks that can be used at https://t2bot.io/webhooks/ . And I wrote something similar in less than 200 lines of Go.

**Comment by bhopmann** [comment]
> And I wrote something similar in less than 200 lines of Go.

@ptman I'm interested in your Go code - do you consider sharing it?

**Comment by ptman** [comment]
@bhopmann I think I got rid of it once I found matrix-appservice-webhooks

**Comment by richvdh** [comment]
I'm not quite clear what the feature request is here, but in general I agree with @ptman - it sounds like something that should be done outside synapse.
