### ISSUE TITLE
[Question]How long the media file will be stored in server directory "media_store"?

### ISSUE THREAD

**Issue by wjhtinger** [matrix-org/synapse#1895]
Foverver or has some limitation?

**Comment by Half-Shot** [comment]
Forever. You'll need to manually delete files.

**Comment by aaronraimist** [comment]
Forever unless you decide to remove it https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst

**Comment by anoadragon453** [comment]
> Forever unless you decide to remove it https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst

Note that this doc file has moved to https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/media_admin_api.md#purge-remote-media-api.
