### ISSUE TITLE
synapse_port_db is broken? again.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1902]
FirstError: FirstError[#91, [Failure instance: Traceback: : column sent is of type boolean but expression is of type integerLINE 1: ...io', 77, '@kevin:potatofrom.space', 'WFSQXCEAIN', 0, 1486329...

**Comment by richvdh** [comment]
Isn't this fixed in develop?

**Comment by ara4n** [comment]
yup, pneumaticat's PR got merged.
