### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by alexgleason** [matrix-org/synapse#1910]
If we add a Dockerfile and get this into Docker Hub it will allow people to set up their own Matrix homeserver in like 2 minutes. This is great because it could help speed up adoption. I'm much more comfortable self-hosting when it's containerized. Thanks!

**Comment by mkonersmann** [comment]
This is a duplication of #969. I propose to close the issue at hand in favor of the one that already contains at least a little bit of discussion.

**Comment by alexgleason** [comment]
Fair, thanks for the info!
