### ISSUE TITLE
Create a new account after logout cache issue

### ISSUE THREAD

**Issue by onePinger** [matrix-org/synapse#1919]
Logout of riot in the browser (chrome mac here), click on "Create User" and error states "Please check your email to continue registration." & "Authorisation failed!".

This happens when I am using the same browser I originally created the account with so appears to be a cookie or cache issue that is not getting cleared out after successful initial account creation or when logging out.

**Comment by richvdh** [comment]
sounds like a client-side issue. Suggest discussing this in #riot:matrix.org, assuming you're using riot.
