### ISSUE TITLE
Notifications should be triggered if I am in a different room

### ISSUE THREAD

**Issue by sraja415** [matrix-org/synapse#1920]
When I go into a room say Matrix HQ (be it iOS or Android ) and I get a message for say Matrix Dev or Vector IOS..I should still get a notification. Ideally handled via settings of each room whether such notifications you want get for that room or not. Example I may want to get notifications for Riot iOS even if I am in Matrix HQ.

**Comment by Half-Shot** [comment]
That *should* be configurable already in Riot?

**Comment by richvdh** [comment]
should work; please discuss online if not
