### ISSUE TITLE
API to let people query the current retry schedule of a HS

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1931]
So that folks can see how long to wait until (e.g.) matrix.org is willing to try to send them traffic again

**Comment by dklimpel** [comment]
IMO this is solved by #11407

**Comment by richvdh** [comment]
I'm not sure it is, since that requires admin rights on the queried homeserver - it sounds like @ara4n wanted anyone to be able to query a remote HS.

However, I don't think that's something we should do.
