### ISSUE TITLE
Replace non-free recaptcha_ajax.js

### ISSUE THREAD

**Issue by andrewshadura** [matrix-org/synapse#1932]
Synapse ships minified non-free JavaScript at `synapse/static/client/register/js/recaptcha_ajax.js`.
Please either dynamically load it from Google’s CDN on demand, or replace it by a free alternative.

This is **not** related to the issue #1561.

**Comment by AP-whitehat** [comment]
Hi @andrewshadura 
I don't think this is an issue for the following reasons :
- Google reCAPTCHA is a free service
- The whole point of the **static client** is to be loaded directly instead from the web .
- The REST version of the matrix client (which is the default ) loads the reCAPTCHA from CDN

anyway this would need confirmation from the owners .

**Comment by andrewshadura** [comment]
The service may be provided at no cost, but the JavaScript (which is currently being served by synapse *and* hence is included in the source) is not free software and, I’m afraid, non-redistributable.

**Comment by andrewshadura** [comment]
I understand your point about the static client, but I think you’re aware that the JavaScript I’m talking about isn’t stand-alone, and talks to Google servers when loaded.

**Comment by AP-whitehat** [comment]
Yes you are right ,
I guess this is an issue .

**Comment by APwhitehat** [comment]
@andrewshadura I relooked into this.
My current findings is that the `synapse/static/client/register/js/recaptcha_ajax.js` is unused as far as new user registration is concerned.

**Comment by andrewshadura** [comment]
It’s referred to from [synapse/static/client/register/index.html](https://github.com/matrix-org/synapse/blob/fa1cf5ef34e684b58433119d78dc95923955ff4f/synapse/static/client/register/index.html#L7) and then in [synapse/static/client/register/js/register.js](https://github.com/matrix-org/synapse/blob/fa1cf5ef34e684b58433119d78dc95923955ff4f/synapse/static/client/register/js/register.js#L29).

**Comment by APwhitehat** [comment]
reRecaptcha.js also is being automatically retrieved from Google's CDN.
I able to register new user from the included Client with Recaptcha .
 [Recaptcha](https://github.com/matrix-org/synapse/blob/fa1cf5ef34e684b58433119d78dc95923955ff4f/synapse/static/client/register/js/register.js#L29) is being called from the definition in the Google CDN's js file .

**Comment by andrewshadura** [comment]
No, if you just remove `recaptcha_ajax.js`, nothing is loaded from the CDN.
Also, why have you literally put `s/Replace/Remove/` into the commit message?! I meant since you're not replacing but removing code, you shouldn't say you're replacing it.
