### ISSUE TITLE
A room can become corrupt and no changes allowed to be made

### ISSUE THREAD

**Issue by heyakyra** [matrix-org/synapse#1949]
I thought @ara4n had filed a bug about this long ago, but I can't seem to find it. If it already exists and someone has found it, please merge this!

Example: [#CSI-0140:matrix.org](https://riot.im/app/#/room/#CSI-0140:matrix.org)

Nothing can be posted, users cannot join or leave. I am the only member, so please let me know what I can do to poke around and troubleshoot

**Comment by thekyriarchy** [comment]
seems the room has been purged

**Comment by thekyriarchy** [comment]
Nope, it hasn't been purged, but since no events are able to be saved, the alias doesn't work. Direct linking because matrix.to thinks it is invalid (which in a way i guess it is?): 

https://riot.im/app/#/room/!pOxFwghhNrBdifdFzN:matrix.org

**Comment by richvdh** [comment]
There's something very odd about this room; the 'current state' (and the state at the last event) refers to a non-existent `m.room.join_rules` event `$1473736324134843ktbyv:matrix.org`. I'd guess that an attempt was made to create such an event, but it didn't get persisted, but for some reason it did make it into the 'current state' caches.

I've never seen this anywhere else, and to debug it I'd want to stare at the logs, which are of course long gone. There's a reasonable chance that the bug has been fixed at some point in the last 2 years, so I don't think it's worth keeping this open. Thank you for reporting, though!
