### ISSUE TITLE
`PUT /transactions/1` is sent to appservices, not documented.

### ISSUE THREAD

**Issue by Torxed** [matrix-org/synapse#1966]
Might be me just missing the obvious.
But I can't find anything under X for the following message sent from synapse to my app service:

    PUT /transactions/1?access_token=<token>\r\n
    .. more headers..\r\n
    \r\n
    {"events":[{"age":9425770,"content":{"membership":"join"},"event_id":"$123456678kJr:domain.com","membership":"join","origin_server_ts":1488657512311,"room_id":"!bDweMddQwKUtbsYoeO:domain.com","sender":"@my_bot:domain.com","state_key":"@my_bot:domain_com","type":"m.room.member","unsigned":{"age":9425770},"user_id":"@my_bot:domain.com"}]}

Now, the strange thing is that the IRC client you supply as an example sends a `404 Not Found` response to the server, meaning I guess this is a new feature? Or the server doesn't really expect a reply hence never implemented?

**Comment by Torxed** [comment]
Just found this old post:

 * https://matrix.org/blog/2015/03/02/introduction-to-application-services/

Turns out the payload is valid, standard event data (that part I had already figured out)..
But still, why do the irc bot reply with 404 for `/transactions/`?

**Comment by Torxed** [comment]
If someone can move this over to the [url=https://github.com/matrix-org/matrix-appservice-irc/issues]matrix-appservice-irc[/url] stack instead that'd be awesome.

Aparently you need to respond `HTTP/1.1 200 OK...\r\n{}` at the very least for the server to start issuing data to the appservice. Since the irc bot doesn't do this any more (for some reason), no messages are ever delivered from irc->matrix. matrix->irc works just fine.

**Comment by richvdh** [comment]
github doesn't support moving issues; you'lll need to open a new issue. This sounds like either a spec issue (https://github.com/matrix-org/matrix-doc) or an appservice-irc one.
