### ISSUE TITLE
publicRooms API can be incredibly slow over federation, causing 504s

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#1980]
split out from https://github.com/vector-im/riot-web/issues/3327

**Comment by ara4n** [comment]
@erikjohnston fixed the perf for the non-federated case.

**Comment by erikjohnston** [comment]
I made it faster for all cases, so I would expect it to be as slow over federation as if a client asked for a non-limited public rooms list (which I think the mobile apps do?)

**Comment by ara4n** [comment]
empirically I think this is still very slow?  e.g: disroot->matrix.org from Nils in https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15323461925250swAwa:disroot.org 

> Yeah -- I think it's just so slow that I get no result
I'm not getting any room list from Matrix.org after changing to it in the drop down on the room list page

**Comment by hawkowl** [comment]
This is basically just another manifestation of https://github.com/matrix-org/synapse/issues/4043 and will be fixed by the stats branch. Closing this as a duplicate
