### ISSUE TITLE
yaml.parser.ParserError: while parsing a block mapping   in "/etc/matrix-synapse/homeserver.yaml", line 7, column 1

### ISSUE THREAD

**Issue by madguy02** [matrix-org/synapse#1985]
I am not able to get through this error

**Comment by turt2live** [comment]
From the error message, it looks like your homeserver.yaml file is formatted incorrectly.

Check around line 7 for some strange formatting. Using tabs and spaces in the same file is a relatively common issue (yaml supports tabs *or* spaces, not both).
