### ISSUE TITLE
Requests for media on a CNAME of our server cause a routing loop

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#1991]
... leaking FDs. For example, if I request remote media on `matrix.sw1v.org`, sw1v.org notices the hostname is different to its server_name, so forwards it on to `matrix.sw1v.org` - ie, straight back to itself

**Comment by schnuffle** [comment]
I've at least a workaround to propose that cools down my HS: **Prevent your HS to contact itself**

> -A INPUT -s 127.0.0.1/32 -p tcp -m tcp --dport 8448 -m conntrack --ctstate NEW -j LOG
-A INPUT -s 127.0.0.1/32 -p tcp -m tcp --dport 8448 -m conntrack --ctstate NEW -j REJECT --reject-with icmp-host-prohibited

Before that fix, I needed to restart my HS every 6 hours, right now it's up for 48h  and no FD leaks.

**Comment by richvdh** [comment]
Hopefully fixed by https://github.com/matrix-org/synapse/pull/1992.
