### ISSUE TITLE
Send encryption keys to new clients.

### ISSUE THREAD

**Issue by lhunath** [matrix-org/synapse#2001]
When a user starts to use a new client that wasn't yet part of his account when an encrypted message was sent, that message is unavailable to this new client.  The same is true when a user signs out and back into his account on a client.  This is not acceptable - encrypted messages can easily become lost and inaccessible this way.

There should be a mechanism by which new clients can become eligible to receive the encryption tokens necessary to decrypt old messages.

**Comment by richvdh** [comment]
dup https://github.com/vector-im/riot-web/issues/2286

**Comment by lhunath** [comment]
Isn't this a server-level issue rather than a client issue?

**Comment by richvdh** [comment]
There might need to be some support from the server, but at the end of the day the client will need to do the device verification and encryption necessary to transfer the keys.

Remember that the principle of E2E is that the server cannot be trusted.

**Comment by lhunath** [comment]
Right - makes sense.  I couldn't quite figure out what the best place for this report was as it seems more of a feature that should be part of the "spec" / "api" as opposed to any specific implementation.  That said, I also wasn't sure official matrix dev happened at vector-im.
