### ISSUE TITLE
automatically sanitize missing entry in event_forward_extremities

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#2012]
In the rare case of a database crash or an accidental deletion of entries in the table `event_forward_extremities` (the forward ends of the event graph, for each room) you are not able to use the room any more unless an external user sais something inside that room (which repairs the history through the federated data)

In this case there should be automatically added a new entry in the tabel event_forward_extremities for that room, so the room is usable again.

**Comment by richvdh** [comment]
I don't think it's sensible to start trying to guard against every conceivable mistake an administrator might make in the database.

**Comment by rubo77** [comment]
ok. But I share my solution here:

1.
I created a backup table from a psql-dump we did earlyer, by splitting that dump into smaller files with
http://unix.stackexchange.com/questions/351546/split-a-large-postgresql-dump-into-smaller-files

2. 
I created the backup table:

    CREATE TABLE event_forward_extremities_bak (
     event_id text NOT NULL,
     room_id text NOT NULL
    );

    ALTER TABLE event_forward_extremities_bak OWNER TO "irc-bridge";

3.
created the data for the backup:

    sed s/event_forward_extremities/event_forward_extremities_bak/g event_forward_extremities.sql > event_forward_extremities_bak.sql

4.
imported the data:

    psql --dbname="synapse" <event_forward_extremities_bak.sql

5. 
inserted the data from the backup table into the main table:

    INSERT INTO event_forward_extremities(event_id, room_id) select event_id, room_id from event_forward_extremities_bak where room_id='!GcVTCMTBlioxonJYWO:matrix.eclabs.de';
    INSERT 0 1

**Comment by rubo77** [comment]
Another solution is to just add a new entry into event_forward_extremities for that room by gettint the last event_id from the history of that room and add this as new value:

     INSERT INTO event_forward_extremities(event_id, room_id) values ('$148843969015013bQuUW:matrix.eclabs.de', '!SOTLohXjvBbIlLJHgT:matrix.eclabs.de');
INSERT 0 1

**Comment by joshuaboniface** [comment]
So you're saying that accidental database failures should cause all my rooms to become unusable? That's a pretty big bug...
