### ISSUE TITLE
Bridged rooms with "List in directory" setting unchecked still appear in directory

### ISSUE THREAD

**Issue by afranke** [matrix-org/synapse#2018]
A couple rooms from GIMPNet have been set not to be listed, and they don’t appear in search results, but they still appear when one goes to the directory and switches the network to GIMPNet.

**Comment by richvdh** [comment]
can you give an example room alias please

**Comment by afranke** [comment]
Gee, that’s an old one.

Well GIMPNet is not listed in the combo box of [Riot Web](https://riot.im/app) or RiotX to begin with, so I am not sure how I can reproduce.

**Comment by richvdh** [comment]
yeahh... going to assume it's not a problem any more. sorry for sitting on it for 2.5 years!
