### ISSUE TITLE
Riot froze at a certain time

### ISSUE THREAD

**Issue by lukebarnard1** [matrix-org/synapse#2023]
A Riot instance that had been logged in as `@lb:ldbco.de` for a while (on a laptop that was slept/shutdown a few times) seemed to freeze on last Wednesday. For about a week after Wednesday, the latest messages in each room appeared to have been received by my HS before Thurs Mar 09 2017 (Wednesday and earlier).  Back/forward pagination was working, but the latest events that could be loaded occurred on Wednesday. 

The sync process of the frozen client had logs that looked like
`2017-03-15T20:24:05.700Z I MatrixClient sync state => %s RECONNECTING`
`2017-03-15T20:24:17.370Z E /sync error %s M_UNKNOWN: Room '!CNuYnsgsbanPKasUPz:matrix.org' does not exist`
`2017-03-15T20:24:17.370Z E M_UNKNOWN: Room '!CNuYnsgsbanPKasUPz:matrix.org' does not exist`
repeated forever. So it seems that ldbco.de had lost a particular room and it was somehow causing a sync failure. The room in question was a PM between `@lb:matrix.org` and `@lb:ldbco.de`.

This log shows how Riot rendered the room on the `@lb:matrix.org` account - shown here as 'luke'. 
```
Thu Mar 09 2017
luke joined the room.
luke made future room history visible to all room members.
luke invited luke (@lb:ldbco.de).
luke (@lb:ldbco.de) rejected the invitation.
luke invited luke (@lb:ldbco.de).
luke (@lb:ldbco.de) joined the room.
luke (@lb:ldbco.de) left the room.
luke invited luke (@lb:ldbco.de).
luke (@lb:ldbco.de) joined the room.
luke (@lb:ldbco.de) left the room.
luke invited luke (@lb:ldbco.de).
luke (@lb:ldbco.de) rejected the invitation.
luke invited luke (@lb:ldbco.de).

Fri Mar 10 2017
luke (@lb:ldbco.de) rejected the invitation.
```

Trying to view the same room from Riot logged in as `@lb:ldbco.de` results in the same `M_UNKNOWN: Room '!CNuYnsgsbanPKasUPz:matrix.org' does not exist`.

Somehow, this room was at some point being sent down the `/sync` response, only to stop existing later on, probably due to `@lb:ldbco.de` leaving it.

**Comment by richvdh** [comment]
@lukebarnard1 I'm failing to grok the TL;DR as far as synapse goes? "Riot froze" sounds like a client issue but I think you're saying that synapse did something to upset it?

**Comment by lukebarnard1** [comment]
So apparently I meant that the client appeared to have gotten stuck at a certain point in time (as opposed to becoming unresponsive). This was because it was failing to sync and somehow this affected both sides of this particular room, the ID of which was being spammed in the sync errors.

I'm not sure what I did to get around this because it's no longer a problem...

**Comment by richvdh** [comment]
I'm going to close this, since we don't really know what the problem was from the synapse PoV
