### ISSUE TITLE
Synapse admin UI

### ISSUE THREAD

**Issue by maitrenageur** [matrix-org/synapse#2032]
I try to understand synapse and the matrix behind.
So I'm looking for administration tools e.g.:
a) To delete (hard) accounts on my home server.
b) To setup a expiration of the account validity, if a user had no login within the last two years (as example).
c) To see how many accounts are registered.
d) etc.

thank you.

**Comment by ArchangeGabriel** [comment]
And in d), I’d like to put everything from https://github.com/matrix-org/synapse/issues/2031 regarding deleting/pruning rooms locally while making federated server that my HS is leaving those rooms. ;)

**Comment by davidtrattnig** [comment]
For c) you can do following right now:

```
sqlite3 /var/lib/matrix-synapse/homeserver.db

select * from users;
```

**Comment by richvdh** [comment]
see also https://github.com/vector-im/riot-web/issues/4125

**Comment by almereyda** [comment]
- manually resetting passwords
- test email delivery

**Comment by rubo77** [comment]
What is the satus of this?

Somebody started to work on an admin GUI already?

**Comment by rubo77** [comment]
Seems like here someone started a GUI: https://github.com/aminhusni/Trinity_Matrix_Management_GUI

**Comment by BloodyIron** [comment]
@rubo77 looks like it might be abandoned :(

We really need a GUI method to administrate Matrix/HS stuff like that though...

**Comment by devcline** [comment]
Any news on Admin GUI dev ?

**Comment by awesome-manuel** [comment]
Is the `_matrix/client/r0/admin/register` endpoint that is used by https://github.com/matrix-org/synapse/blob/master/synapse/_scripts/register_new_matrix_user.py included in any offical spec?

**Comment by richvdh** [comment]
`/_matrix/client/r0/admin/` is meant for stuff that's specific to a HS implementation (there's one endpoint which has slipped through the net into the CS spec somehow). Many of the endpoints synapse exposes there (including /register) are documented in synapse/docs/admin_api.

**Comment by RobinVanhove** [comment]
According to vector-im/riot-web#4125

> we're prioritising the riot redesign over this sort of admin interface. contributions from the community would be very welcome on it.

Which is understandable to do in riot with a universal API to every server. 

But it should be reasonable to create something specifically for the synapse server. Connecting directly to the databse

**Comment by ara4n** [comment]
building a web UI is on the horizon in the next ~3 months, one way or another

**Comment by BloodyIron** [comment]
@ara4n any word on target scope of features? :D

**Comment by targodan** [comment]
Being able to use the server notice thingy to send custom messages would be great. (Yes, you can use the manhole now but it's a pain in the nether regions)

**Comment by Luraktinus** [comment]
Hope this WebUI is coming soon

**Comment by awesome-manuel** [comment]
We started to implement an admin UI for synapse: https://github.com/Awesome-Technologies/synapse-admin

**Comment by BloodyIron** [comment]
Nice!

**Comment by awesome-manuel** [comment]
We did a complete rewrite using (react-admin)[https://marmelab.com/react-admin/].
Docker-Container is up-to-date: https://hub.docker.com/r/awesometechnologies/synapse-admin

**Comment by Cam-B** [comment]
> building a web UI is on the horizon in the next ~3 months, one way or another

Is this still on the horizon @ara4n ? I haven't been able to find anything regarding this recently.

**Comment by Cam-B** [comment]
> We did a complete rewrite using (react-admin)[https://marmelab.com/react-admin/].
> Docker-Container is up-to-date: https://hub.docker.com/r/awesometechnologies/synapse-admin

This looks pretty cool. Is this currently the main functional admin gui?

**Comment by gensahil1997** [comment]
> We did a complete rewrite using (react-admin)[https://marmelab.com/react-admin/].
> Docker-Container is up-to-date: https://hub.docker.com/r/awesometechnologies/synapse-admin

How can we get access to the endpoints /matrix and /_synapse/admin ?

**Comment by dklimpel** [comment]
You can use a reverse proxy. The documentation is there: https://matrix-org.github.io/synapse/latest/reverse_proxy.html#synapse-administration-endpoints

**Comment by gensahil1997** [comment]
We are using reverse proxy but for synapse-admin UI it shows failed to
fetch data so how can i fix it.

**Comment by dklimpel** [comment]
You can get support there:
https://github.com/matrix-org/synapse#support
> For support installing or managing Synapse, please join #synapse:matrix.org (from a matrix.org account if necessary) and ask questions there. We do not use GitHub issues for support requests, only for bug reports and feature requests.

And a few closed issues here: https://github.com/Awesome-Technologies/synapse-admin/issues?q=is%3Aissue+fail

**Comment by erikjohnston** [comment]
I don't think we have any plans on adding an admin UI to Synapse any time soon, and https://github.com/Awesome-Technologies/synapse-admin is a good alternative, so I'm going to close this for now.
