### ISSUE TITLE
Sometimes rooms/{roomId}/messages doesn't sort the messages and misses some

### ISSUE THREAD

**Issue by indefini** [matrix-org/synapse#2066]
I try to get the last 10 messages of a room.
They are not sorted (by time) so I though I would do it in the client.
But I noticed that I didn't really get the last 10 ones.
There were newer messages not returned by /messages.

I also saw this problem on the web riot client. With sync there were no problem but after reloading the web client, I saw some newer messages displayed before old ones.

At first I was checking this for an irc channel, but I also saw it in the matrix hq room.
I have the permalink (from the matrix hq room) if I you want me to post them here, tell me.

**Comment by richvdh** [comment]
correct, /messages sorts by the topological ordering of the room; that's not strictly related to the timestamp.

**Comment by indefini** [comment]
Do you mean that the following is not a problem and should stay the same for a user?

With /sync:
Message 1
Message 2
Message 3

With /messages:
Message 2
Message 1
Message 3

With /messages and limit=2
Message 1
Message 3

Is that ok? I was surprised to see the inconsistency  as a user.
This is just an example with 3 messages. in reality I got some messages mixed with other messages from hours before.

**Comment by indefini** [comment]
I don't want to insist but I feel like this is a problem, don't you?
Should I open an issue in riot instead?
I will wait another week.

**Comment by ara4n** [comment]
I would expect a fresh /sync and /messages to return the same order.  This sounds more as if you are specifying different 'from' tokens or something?

**Comment by ara4n** [comment]
reopening to try to give more detail - @erikjohnston perhaps you can help clarify too.

**Comment by richvdh** [comment]
@ara4n: `/sync` returns in stream ordering. `/messages` returns in topological ordering. It's certainly possible for them to return events in different orders.

**Comment by richvdh** [comment]
related #7164
