### ISSUE TITLE
ImportError: No module named psycopg2

### ISSUE THREAD

**Issue by talentedmrripley** [matrix-org/synapse#2071]
After changing settings to try and use a PostgreSQL DB I'm getting the following:

`-- The start-up result is done.
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,490 - twisted - 131 - ERROR - - Traceback (most recent call last):
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,491 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,491 - twisted - 131 - ERROR - -     "__main__", fname, loader, pkg_name)
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,492 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,492 - twisted - 131 - ERROR - -     exec code in run_globals
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,493 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 490, in <module>
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,493 - twisted - 131 - ERROR - -     main()
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,494 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 485, in main
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,494 - twisted - 131 - ERROR - -     hs = setup(sys.argv[1:])
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,495 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 302, in setup
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,495 - twisted - 131 - ERROR - -     database_engine = create_engine(config.database_config)
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,496 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/storage/engines/__init__.py", line 34, in create_engi
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,496 - twisted - 131 - ERROR - -     module = importlib.import_module(name)
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,497 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,497 - twisted - 131 - ERROR - -     __import__(name)
Mar 27 16:29:55 matrix python[3555]: 2017-03-27 16:29:55,498 - twisted - 131 - ERROR - - ImportError: No module named psycopg2
Mar 27 16:29:55 matrix systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 16:29:55 matrix systemd[1]: matrix-synapse.service: Unit entered failed state.
Mar 27 16:29:55 matrix systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.`

I've install psycopg2 with pip.  Trying again only yields:
 
`ripley@matrix:~$ pip install psycopg2
Requirement already satisfied: psycopg2 in ./.local/lib/python2.7/site-packages
`

OS: Ubuntu16.04LTS
Synapse: 0.19.3-1 (From the Debian package repo)

**Comment by schnuffle** [comment]
Do you use the virtualenv in which you installed psycopg2?

**Comment by talentedmrripley** [comment]
I don't think I'm using a virtualenv.  I installed Synapse via the Debian package and then installed psycopg2 using pip, following the instructions from here, https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst

**Comment by talentedmrripley** [comment]
I've doubled checked and I am not using virtualenv.

**Comment by schnuffle** [comment]
okay you installed psycopg2 into thevroot env e.g. /root/.local/....
Under which user does synapse run?

In case it's not root, you need to install it into the env of the user launching synapse

**Comment by talentedmrripley** [comment]
So that got me on the right path.  I didn't install it as root, I installed it as my user, ripley, but the Debian package creates a user matrix-synapse.  Had to change the shell of that account temporarily and then install psycopg2 under its account.  It gave a different error but seems to have started:

```
Mar 31 16:32:49 matrix python[6651]:   File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 238, in _start
Mar 31 16:32:49 matrix python[6651]:     return self.start()
Mar 31 16:32:49 matrix python[6651]:   File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 249, in start
Mar 31 16:32:49 matrix python[6651]:     self.threadpool.start()
Mar 31 16:32:49 matrix python[6651]:   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 153, in start
Mar 31 16:32:49 matrix python[6651]:     self.adjustPoolsize()
Mar 31 16:32:49 matrix python[6651]:   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 306, in adjustPoolsize
Mar 31 16:32:49 matrix python[6651]:     self._team.grow(self.min - self.workers)
Mar 31 16:32:49 matrix python[6651]: exceptions.TypeError: unsupported operand type(s) for -: 'str' and 'int'
Mar 31 16:32:53 matrix systemd[1]: Started Synapse Matrix homeserver.
```

**Comment by schnuffle** [comment]
If the problem is resolved you should close your issue.
