### ISSUE TITLE
complex networks and text mining analytics and visualizations

### ISSUE THREAD

**Issue by ttm** [matrix-org/synapse#2081]
I can tackle this:
https://github.com/matrix-org/GSoC/blob/master/IDEAS.md#matrix-visualisations
by using complex networks and text mining techniques,
because I have developed research on these topics.
Immediate ideas are:
*) Derive network by users interactions and vocabulary usage and deliver some graphical interfaces for exploring these structures.
*) Counting of words, tags, terms and user activity.
*) Maybe focus on the Directed Acyclic Graph as stated in the GSoC proposal.
*) Channels can also benefit from the analyzes.
*) Interactive web interfaces using D3.js

I understand it might be late for coping with GSoC, but if you find it suitable,
I might apply.
My apologies for not making this contact earlier, but I handed my doctorate
dissertation a few days ago and could not concentrate as needed until now.
Some info about my research and software development efforts are gathered here:
https://pastebin.com/iNNuN4fy7
Anyway, this topic might be of use for the Matrix community as a whole and for
developments outside GSoC.

Best Regards!
Renato Fabbri

**Comment by reivilibre** [comment]
If this issue is still relevant, it should probably find another home :)
