### ISSUE TITLE
Extend _AccountHandler proxy object

### ISSUE THREAD

**Issue by slipeer** [matrix-org/synapse#2085]
Extend _AccountHandler proxy (in synapse/handlers/auth.py) object to allow setup additional user data from password auth providers.
For example to setup DisplayName or 3pid from LDAP.
There [TODO mark in matrix-synapse-ldap](https://github.com/matrix-org/matrix-synapse-ldap3/blob/master/ldap_auth_provider.py#L189) which can not be implemented without these changes.

I suggest adding these two methods:

    def set_displayname(self, localpart, displayname):
        """ Setup Display Name from external auth source
        """
        yield self.get_handlers().profile_handler.store.set_profile_displayname(
            localpart, displayname
        )

    def set_3pid(self, user_id, type, threepid)
        """ Setup 3pid from external auth source
        """
        validated_at = self.hs.get_clock().time_msec()
        yield self.get_handlers().profile_handler.store.user_add_threepid(
                        user_id,
                        type,
                        threepid,
                        validated_at,
                        validated_at
                    )

Regarding of email setup: in conjunction with the project [kamax-io/mxisd](https://github.com/kamax-io/mxisd) this will allow to use email as 3pid on local server from the LDAP without additional verification.

**Comment by mweinelt** [comment]
Blocks a pull request for matrix-synapse-ldap3 at https://github.com/matrix-org/matrix-synapse-ldap3/pull/26.

**Comment by richvdh** [comment]
@slipeer can you send a pull request for the changes so that we can see how they fit in?

**Comment by slipeer** [comment]
@richvdh ready: https://github.com/matrix-org/synapse/pull/2119
