### ISSUE TITLE
presence.py: de-dup `hosts_to_states` in `_get_interested_parties`

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#2087]
See https://github.com/matrix-org/synapse/pull/2084 for details

**Comment by erikjohnston** [comment]
This is non-trivial due to that function being a hot path, and so requires caution and testing to ensure that we don't burn too much CPU.

It may be better to dedupe at a later time, e.g. when we're about to send things over federation

**Comment by APwhitehat** [comment]
I'll try looking into this :)

**Comment by richvdh** [comment]
this has all been re-written, so is no longer relevant
