### ISSUE TITLE
after downloading the binary for debian\ubuntu...what next?

### ISSUE THREAD

**Issue by NIXOYE** [matrix-org/synapse#2096]
I want to get synapse running on a server but the "platform specific instructions" aren't very extensive.

**Comment by schnuffle** [comment]
Do you want to install with a .deb package or do you want to install from src using a virtualenv?

[Debian Jessie HOWTO](https://xo.tc/seting-up-matrix-synapse-and-riot-on-debian-8-jessie.html)
[Ubuntu 16.04 HOWTO](https://www.topbug.net/blog/2016/12/05/set-up-synapse-matrix-homeserver-on-ubuntu-16-04/)

The default install uses sqlite, so you might have a look at [PostGres HOWTO](https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst) afterwards and maybe [TURN Server HOWTO](https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.rst)
