### ISSUE TITLE
Instructions on how to create an account are misleading

### ISSUE THREAD

**Issue by yurivict** [matrix-org/synapse#2101]
Here https://matrix.org/docs/guides/faq.html#how-do-i-get-an-account-and-get-started it says that to create an account:

> The quickest way is to pick a client from https://matrix.org/blog/try-matrix-now and sign up.

So I chose one of the clients, tensor, https://github.com/davidar/tensor, and there is no obvious way to create an account there because it only asks for login/password.

Please update the instructions.

**Comment by APwhitehat** [comment]
Tensor project seems to be in Alpha phase right now.
That is likely reason for no create account mechanism.

>The quickest way is to pick a client from https://matrix.org/blog/try-matrix-now and sign up.

implies for the top 4 clients which are shown after this line. They are mature and have less bugs.

Hope this helps.

**Comment by richvdh** [comment]
not a synapse issue: feel free to file this (or better, make a PR) at https://github.com/matrix-org/matrix.org
