### ISSUE TITLE
Key permission errors - using write mode?

### ISSUE THREAD

**Issue by Karunamon** [matrix-org/synapse#2122]
Greetings,

I ran into on this on my machine using LetsEncrypt certificates, whose default configuration lives at `/etc/letsencrypt/live/(domain name)/fullchain.pem`. These files have mode o+r, preventing anyone other than root from writing to them.

The error I got on startup was:

```
 File "/usr/lib/python2.7/dist-packages/synapse/config/tls.py", line 130, in generate_files
   with open(tls_private_key_path, "w") as private_key_file:
  IOError: [Errno 13] Permission denied: '/etc/letsencrypt/live/isengard.tkware.us/privkey.pem'
```

It seems very strange that Synapse would be opening keyfiles with write mode especially considering that `open('file', 'w')` truncates the file if it already exists! Given that this keyfile is shared with other TLS-using applications on the system, this could have been painful for me if it had actually worked.

In any case, I copied the keyfile aside and gave the copy o+w permissions, and there were no further problems.

Just wondering if this is intentional :)

**Comment by richvdh** [comment]
That line should only be executed if the key file doesn't exist: 

```
        if not os.path.exists(tls_private_key_path):
            with open(tls_private_key_path, "w") as private_key_file:
```

- so Synapse will not overwrite a file that exists. It will, however, try to make a key pair if the file does not exist, to make it easier for first time users to get started.

I suspect that in your case, `/etc/letsencrypt/live/isengard.tkware.us/privkey.pem` didn't exist, but `/etc/letsencrypt/live/isengard.tkware.us` did, without write access for the synapse user. In other words, you have configured it to create a file, but not given it permission to do so.

**Comment by Karunamon** [comment]
Makes sense. Thanks!
