### ISSUE TITLE
Error on registration: "Unknown auth stage type"

### ISSUE THREAD

**Issue by KingPrawn22** [matrix-org/synapse#2134]
Hi all.

I'm getting an error when registering a new user. This happens with both the riot.im web-based registration page, and also the Riot desktop app (Windows 10). I choose to use my custom server in the process, enter a username and password and then submit. On submission, I get to a page that has a link to 'Start Authentication'. When clicking this link I get the error, which is as follows:

{"errcode":"M_UNKNOWN","error":"Unknown auth stage type"}

I have registration open, but with Captcha disabled.

If I use the Android app, I can register without problem. The issue only exists when using either the web-based riot.im or the Riot desktop application.

Any help is much appreciated.

**Comment by turt2live** [comment]
Looks like you ran into https://github.com/vector-im/riot-web/issues/3621 which is an issue with Riot. The fix hasn't made it into a release yet, but if you're comfortable with building the app yourself then building the develop branch is your best bet to fix the issue.

**Comment by KingPrawn22** [comment]
Thank you for letting me know. If it's in development then I'll wait for it to be released, since it's not a big deal for the very small setup I have.

**Comment by richvdh** [comment]
not a synapse issue
