### ISSUE TITLE
Stuck federated invites (again)

### ISSUE THREAD

**Issue by grawity** [matrix-org/synapse#2140]
I have an account on `matrix.org`, which has a stuck invite from an IRC gateway at `yochat.biz` (which is no longer active). IIRC, it has been there since early 2016.

Despite #691, #761, and #1599 being marked as "fixed", I _still_ can neither accept nor reject that invite – everything results in "Internal server error" being returned.

**Comment by richvdh** [comment]
@grawity: I will investigate if you can tell me your userid

**Comment by grawity** [comment]
It's `@grawity:matrix.org` I think? I don't know of any other ID.

**Comment by richvdh** [comment]
@grawity: ok, it appears that you're right; this was never fixed. I have reopened #691 to track this.

Meanwhile, I hope I have flushed your stuck invite from the database on matrix.org. If you now flush the caches on your clients, I *hope* it will go away for you.

**Comment by grawity** [comment]
Thanks; used "Clear cache and reload" in Riot and now the invite is gone.

**Comment by richvdh** [comment]
great; closing this as a dup of #691 then. thanks.

**Comment by richvdh** [comment]
<-- idiot

s/#691/#761/
