### ISSUE TITLE
Impossible to get Room Events starting from historical beginning 

### ISSUE THREAD

**Issue by pik** [matrix-org/synapse#2151]
This may solely be a documentation omission, at any rate the `/events` endpoint only specifies the presence of a `from` token string which can be retrieved from [room initial sync](https://matrix.org/docs/spec/client_server/r0.2.0.html#get-matrix-client-r0-rooms-roomid-initialsync)
```
from 	string 	The token to stream from. This token is either from a previous request to this API or from the initial sync API.
```
Also (undocumented) but `limit, dir, to` are parsed as well by the PaginationConfig object. Nevertheless there does not appear to be a way to obtain a `from` token at the start of the historical timeline since the room initial sync is limited to returning recent events (https://github.com/matrix-org/synapse/blob/master/synapse/handlers/initial_sync.py#L396).

**Comment by ShadowJonathan** [comment]
@pik the spec has heavily changed since then, is this still relevant?

If so, could you maybe open up another issue about this in [matrix-doc](https://github.com/matrix-org/matrix-doc)?

**Comment by richvdh** [comment]
@ShadowJonathan sadly I believe @pik is [no longer with us](https://www.niekdejonge.nl/alex-maznev-rip/).

Nevertheless I'll close this issue in favour of https://github.com/matrix-org/matrix-doc/issues/2480.
