### ISSUE TITLE
cancel upload avatar does not return old avatar

### ISSUE THREAD

**Issue by vincentkersten** [matrix-org/synapse#2153]
Hello all,
very fresh to the osx client of riot. Just wanted to let you know, after cancelling the upload of a new picture, an spinning wheel stays, and does not return to old avatar, or blank avatar picture. 

This is about 'Version 0.9.8 (0.9.8)'

**Comment by turt2live** [comment]
This is probably best reported to https://github.com/vector-im/riot-web. Please use the template on riot-web so that whoever looks into it can have as much information as possible.
