### ISSUE TITLE
Administrator guide

### ISSUE THREAD

**Issue by loi219** [matrix-org/synapse#2161]
Hi,
I've installed a synapse server but I didn't find some administrator guide.
Would you write one?

**Comment by richvdh** [comment]
The readme is the best we have so far

are there particular questions you would like to have answered?

**Comment by loi219** [comment]
Like how can I list the users who are using my server?

**Comment by richvdh** [comment]
best way right now is

```
SELECT name from users;
```

on the database

**Comment by loi219** [comment]
Ok, thanks
