### ISSUE TITLE
Synapse occasionally takes a sharp hit on memory consumption 

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#2166]
The server used a lot of memory and eventually spun up the CPU to 100% when it ran low. 
[Grafana](https://half-shot.uk/grafana/dashboard/db/system?orgId=1&from=1493237702543&to=1493245910427)
[Log file](https://half-shot.uk/files/sycap.txt) (~50Mb in size)

**Comment by aventrax** [comment]
Same here with synapse on debian stretch. This happen to me joining large rooms..

**Comment by Half-Shot** [comment]
This isn't really serving any purpose. Closing.
