### ISSUE TITLE
Notifications endpoint not showing messages including my display name

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/synapse#2172]
I noticed that Riot wasn't showing mentions of my display name `{ Adam }` in the notifications tab, so I investigated. Turns out the `/_matrix/client/unstable/notifications` only returns places where my username `@abeckmeyer:matrix.org` was in a message body or old events from when my display name was `Adam`. I'm assuming this is some sort of issue with having the characters `{` and `}` in my display name.

I can provide the json from the request to `/_matrix/client/unstable/notifications`, but I'll need to take a closer look to see if anything needs to be redacted.

**Comment by non-Jedi** [comment]
As an update, after changing display name to `$Adam` to test this further, notifications show up.

**Comment by turt2live** [comment]
There are two separate notification settings: 1 for your display name, and 1 for your MXID. I don't recall the names, however in the latest release of riot (0.9.10), the 'display name' setting is now exposed. 

Not sure if this would have caused the kind of failure you're seeing though.

**Comment by non-Jedi** [comment]
I don't think I changed any settings, but I was able to receive the notification for [this matrix message](https://matrix.to/#/!UcYsUzyxTGDxLBEvLz:matrix.org/$1495720029736bRPyk:krtdex.com), so somehow or the other this issue is resolved.

**Comment by non-Jedi** [comment]
Just checked on this one again. Events that had previously shown up in my notification pane for `{ Adam }` are no longer there; no events mentioning `{ Adam }` are other than [this event](https://matrix.to/#/!UcYsUzyxTGDxLBEvLz:matrix.org/$1495560799544cYISz:krtdex.com) for some reason.

**Comment by richvdh** [comment]
It seems this got missed. Is it still an issue?

**Comment by H-Shay** [comment]
As there has been no response I am going to close this, happy to re-open if necessary.
