### ISSUE TITLE
Locally-rejected invites don't get passed on to the client

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#2181]
After an invite is rejected locally, we don't update the clients about it via /sync

(riot-web bug: https://github.com/vector-im/riot-web/issues/3743)

**Comment by aaronraimist** [comment]
Is there any chance that this will get added to the [holding pen](https://github.com/orgs/matrix-org/projects/8)? This is one of the more annoying user facing bugs still present in Synapse.

**Comment by redsky17** [comment]
I can confirm that I experienced this bug recently as well.  Clearing the cache in Riot web made the stuck invite go away.

**Comment by ara4n** [comment]
cc @neilisfragile

**Comment by wayneoutthere** [comment]
I just had this with most recent version of riot web app.  I had to:
1. clear cache and reload in security/settings
2. go to bottom of  security/settings and apparently (and thankfully) there are 'Bulk Options' which included  'reject all 213 invites' <--- not sure how that even happened as it was one person inviting me... 
3. wait a really long time while it cleared
4. log out
5. Log back in

Unfortunately I had to do a similar activity on my mobile app as well but hopefully these steps help someone

**Comment by aaronraimist** [comment]
I've added a $200 bounty to encourage a community member to work on this important Synapse issue. It expires 2020-01-01. https://freedomsponsors.org/issue/849/locally-rejected-invites-dont-get-passed-on-to-the-client?alert=SPONSOR#description

If a Synapse core team member solves the issue while at work, I will reallocate this bounty to another issue. If a core team member wants to solve this with their community hat on then they can choose to take the bounty.

**Comment by sunshineo** [comment]
Hi @aaronraimist, I made a [Github bot](https://github.com/apps/issue-reward-beta) and a [website](https://www.issuereward.com/) similar to the https://freedomsponsors.org/ you are using. The Github bot can automatically add a comment to every new issue with a link to a website that encourages people to add reward. (It adds a link to existing open issues when you install). It automatically comments on the issue and tag people when anyone gives a reward, claim the rewards, and approve a reward. Automatically label issues with rewards so you know what is really important for your users.

I wonder if you or the owner of this repo would like to try it. It's in beta now, I'm looking for people to give it a try.

**Comment by benbucksch** [comment]
Could this be fixed, please? This causes a very prominent and serious issue in Riot, see https://github.com/vector-im/riot-web/issues/3743#issuecomment-589652386. That bug is literally "front and center", and there is no obvious recourse for a normal end user. I ran into this as a new user after using Riot for only 2 days. It makes a really immature impression of Riot and Matrix.

**Comment by miff2000** [comment]
> I just had this with most recent version of riot web app. I had to:
> 
> 1. clear cache and reload in security/settings
> 2. go to bottom of  security/settings and apparently (and thankfully) there are 'Bulk Options' which included  'reject all 213 invites' <--- not sure how that even happened as it was one person inviting me...
> 3. wait a really long time while it cleared
> 4. log out
> 5. Log back in
> 
> Unfortunately I had to do a similar activity on my mobile app as well but hopefully these steps help someone

This is now here under Help & About:
![image](https://user-images.githubusercontent.com/3526189/76349164-693ddb00-6301-11ea-90c4-1677bf558a43.png)

**Comment by benbucksch** [comment]
That's nice, but it doesn't help affected users, because they don't know that a) clearing the cache is a working workaround for this bug, and b) where to find it (I would never ever look for it in Help). If people end up here in this bug report, they've already wasted a lot of time on this bug. Googling for bug reports is not a proper user interface.

**Comment by btittelbach** [comment]
I can also confirm that, once `locally_rejected` is set for a room in the database, the invite persists very prominently and annoyingly in all other clients, until "clear cache and reload" is used on every client.

I agree that this needs to be fixed urgently.

**Comment by benbucksch** [comment]
Can somebody please fix this serious bug, or is matrix and Riot completely unmaintained?
