### ISSUE TITLE
Pagination Config is insufficient because there is no way to get a Topological Token at the Historical Start 

### ISSUE THREAD

**Issue by pik** [matrix-org/synapse#2184]
Currently the only way to get the first message sent in a room is to parse backwards from a topological token returned by `get_room_events_max_id` - there is no sufficient Pagination Config to obtain the first message if the topological token for the first message is not known (I guess handcrafting a `from_token` from a presumed `topological_ordering=1` might work, but is also subject to break at any time, being solely an internal detail ? )

**Comment by richvdh** [comment]
turning this into a spec issue; https://github.com/matrix-org/matrix-doc/issues/2480
