### ISSUE TITLE
Federation without metadata track

### ISSUE THREAD

**Issue by akreuzkamp** [matrix-org/synapse#2188]
Hi,

I'm writing this to ask you a question about metadata in federated messaging systems and how to avoid them. It's not so much about matrix itself (but might though apply to it) but rather about the concept itself. As I don't know, whom to ask this, I decided to directly address the questions to some experts. :)

All federated communication channels I know (namely e-mail, XMPP and of course Matrix) route the messages through four nodes: `Alice (A) -> Alice's provider (P1) -> Bob's provider (P2) -> Bob`. Thus, even with e2ee, both P1 and P2 know exactly who communicates with whom. As a consequence, Alice has to trust Bob's provider in order to communicate with him. To me, routing the message through P1 seems dispensable.

I wonder, and that's my question, why this indirection is needed. Recently, I've been thinking about a federated messaging system, that would lift the need to trust one's partner's provider, by simply removing the indirection through the own provider:
Alice sends an e2ee-message to Bob's provider (P2) without authenticating herself (possibly though authorizing herself). P2 now knows that someone wrote to Bob, but not who. Bob's device will be able to decrypt the message and thus know who wrote (using e.g. DANE Bob could verify the origin). So far,
Alice didn't gain any privacy. Now Bob replies. He will send an e2ee-message to Alice's provider (P1), again without authentication. Only Alice will be able to decrypt the message and know the author. Here the difference happened. As P2 didn't receive the reply, P2 won't even know, that Bob replied even less
whom he replied to and thus who wrote in the very beginning.

In fact if Alice and Bob shared the same provider, the provider would be able to trace the communication. That means, you'd still have to trust your own provider about the metadata, but never need to trust the provider of others.
As this concept isn't too far-fetched, I'm wondering why I couldn't find any documentation about it and why it seems nobody ever tried to implement it. Are there any obvious design flaws I don't see or any other issues, political or technical reasons? I'm neither experienced in designing network protocols nor
in writing server software, so I will probably never be able to implement such a system. I'm just a privacy aware citizen, hoping to see this kind of communication channel to appear some day.

Thanks in advance for your reply. :)

**Comment by ara4n** [comment]
Have you read http://matrix.org/~matthew/2016-12-22%20Matrix%20Balancing%20Interop%20and%20Privacy.pdf ? This has most of my thoughts on the subject, which seem quite similar to what you're proposing. It's how Pond (and I think Ricochet) does it.

Alpenhorn / Vuvuzela has a more sophisticated similar architecture.

-- 
Matthew Hodgson
Matrix.org

**Comment by akreuzkamp** [comment]
No, I didn't find it yet. It looks like promising input. Thanks, I'll read it and research more about Pond, Ricochet, Alpenhorn, Vuvuzela. :)

**Comment by brandsimon** [comment]
Personally I also like to see only necessary metadata, but I dont like to connect to other servers (IP leak, probably attack surface   if my client is vulnerable, ...). I only want to connect to the server I trust.
I would prefer an onion routing approach.
So A would send a message encrypted for P2 to P1 and tell him to send it to P2, P2 can then decrypt the receiver (Bob).
Neither P1 nor P2 will know that Alice and Bob are communicating.

This could also allow to have more hops in between. `A -> P1 -> random server 1 -> random server 2 -> random server 3 -> P2 -> Bob`
So people dont misuse this to spam servers, it could be beneficial to add an outer hop count or something similar and allow e.g. max 16 hops.

A possible attack is, that Eve could eavesdrop on every server and save the timestamp and package size of each message incoming and outgoing and later match those together. To make this more difficult, there could be random small delays added and random data added to messages. Server which are not busy enough could generate fake data (like Alpenhorn does).

**Comment by richvdh** [comment]
This is a bit woolly and hard to action. Given the relative lack of activity over the last 5 years, I'm going to go ahead and close it.

P2P messaging for Matrix is a topic of active research, and I think it addresses some of the questions raised here.
