### ISSUE TITLE
Room sync: A wrong missed notifications count is received

### ISSUE THREAD

**Issue by giomfo** [matrix-org/synapse#2193]
In an encrypted room, my Riot client (ios) receives a not null count of missed notifications whereas my user (Samy) has sent the last message of the room.

On Riot web, I open the same room by using another room member (Giom). I oberve Samy is the sender of the last message (sent 04/27):
![screen shot 2017-05-05 at 15 55 21](https://cloud.githubusercontent.com/assets/8969772/25748650/15f15190-31ac-11e7-9ef3-960df3fd0f0c.png)

But his read receipt badge is stuck in the room history several months before (01/13):
![screen shot samy](https://cloud.githubusercontent.com/assets/8969772/25748699/40db3cea-31ac-11e7-803e-6378bc25a87f.png)

**Comment by richvdh** [comment]
@giomfo are you still able to reproduce this?

**Comment by richvdh** [comment]
related: #8598

**Comment by richvdh** [comment]
closing for lack of info
