### ISSUE TITLE
Room state never resynchronizes after several OOMs

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2198]
Taken straight from #matrix-dev:matrix.org: https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$14941627314087jmEbk:elynx.fr

```
Hiro Lynx
Heya. I have a friend that has a Matrix instance of which db is corrupted. The instance won’t synchronise some rooms, and it thinks that some users are in or out of rooms where other instances think otherwise.
Is there an easy fix for such a situation?

Max (@max:kamax.io)
Hiro Lynx (@Hiro:elynx.fr): how did it get corrupted exactly?

Hiro Lynx
Not sure. He was using sqlite, had random segfaults due to ujson/musl incompatibility (on ARM processor) and OOM killing because not enough RAM.
Mostly not synapse fault IMO.
(we replaced ujson with json to make Synapse work with musl. This patch is working fine on my system, although I have a x86_64 CPU)

Matthew (@matthew:matrix.org)
in theory it should self-heal, but you may have hit bugs

will need full logs

Kooda[b] (IRC)
This is what I see when trying to send messages to the problematic rooms: http://lxp.fr/p3EQ03eOwA
When I try to leave it: http://lxp.fr/p3ER2eWuFQ
```

**Comment by richvdh** [comment]
presumably this user has either fixed it or gone away.

**Comment by ara4n** [comment]
perhaps; do the symptoms  match the user having been state reset out of the room? reopening because stuff like this is currently biting kde.org and matrix.org (see bridge crew)

**Comment by richvdh** [comment]
>  do the symptoms match the user having been state reset out of the room?

I don't know: the problem is that the bug was reported 2 years ago and hasn't been looked at since, so nobody knows.

> reopening because stuff like this is currently biting kde.org and matrix.org (see bridge crew)

Are those servers showing the same error? If not, it's likely a separate bug. If so, the issue report needs cleaning up up so that we don't have to go spelunking in message logs and paste bins to understand what the problem is.

**Comment by richvdh** [comment]
I'm afraid there's still not enough info here to do anything useful with it.
