### ISSUE TITLE
Room name not set aka (calculateRoomName)

### ISSUE THREAD

**Issue by delijati** [matrix-org/synapse#2204]
It seams that every client in implementing its own `calculateRoomName`:

-  c++ [libmatriclient](https://github.com/Fxrh/libqmatrixclient/blob/6fdadc74c6f090689daad211159930b46a66026d/room.cpp#L788)

- js [matrix-js-sdk](https://github.com/matrix-org/matrix-js-sdk/blob/master/src/models/room.js#L1153)

But as i can see `synapse` has already one https://github.com/matrix-org/synapse/blob/9bba6ebaa903a81cd94fada114aa71e20b685adb/synapse/push/presentable_names.py#L31

I opened a ticket already for that issue in [matrix-python-sdk](https://github.com/matrix-org/matrix-python-sdk/issues/112)

**Comment by aaronraimist** [comment]
Duplicate of #1283
