### ISSUE TITLE
r0 Registration Flow missing type:m.login.password is a regression

### ISSUE THREAD

**Issue by pik** [matrix-org/synapse#2205]
The `api/v1/register` endpoint allowed registration to happen with[ type: m.login.password](https://github.com/matrix-org/synapse/blob/master/synapse/rest/client/v1/register.py#L260). 

 `r0` explicitly does not support this since [_check_password](https://github.com/matrix-org/synapse/blob/master/synapse/handlers/auth.py#L496) only applies to existing users. 

There is now a two-stage process involving a 401 and a `session_id` returned in the 401 error message (I'm actually not convinced using `401` as a step in an Authentication flow is proper use of the HTTP Status code), at any-rate this seems to be inline with the [Interactive Authentication API](http://matrix.org/docs/spec/client_server/r0.2.0.html#user-interactive-authentication-api) - the problem, is that this particular request should be *non-interactive* there are no additional user interaction steps which are required to be taken but the API has simply been made more complicated for flows such as this one. 

There is some documentation missing (https://github.com/matrix-org/matrix-doc/issues/912) but the current flow as inferred from Riot looks like this:

![screenshot from 2017-05-09 09-48-13](https://cloud.githubusercontent.com/assets/10236920/25856794/ac878280-349c-11e7-8d7f-a86b3609c99e.png)

![screenshot from 2017-05-09 09-40-34](https://cloud.githubusercontent.com/assets/10236920/25856732/821571c4-349c-11e7-860a-49bf4b46a868.png)

```#response
{"session":"gpzedCFFjiWIpVBgvbbTVVbH","params":{},"flows":[{"stages":["m.login.dummy"]},{"stages":["m.login.email.identity"]},{"stages":["m.login.msisdn"]},{"stages":["m.login.msisdn","m.login.email.identity"]}]}
```

Note: that the 401 response is absolutely not indicative or informational to a client in any way, there are a number of stages listed - and it's absolutely not clear what was missing from the original request in the first place! In fact we can simply POST afterwards (as Riot does) with `type: m.login.dummy` referencing the `session_id` of the previous `401` response. 

![screenshot from 2017-05-09 09-41-24](https://cloud.githubusercontent.com/assets/10236920/25856755/91e721c4-349c-11e7-8a97-b30d9bd4551d.png)
```
{"access_token":"MDAxNmxvY2F0aW9uIHBpay10ZXN0CjAwMTNpZGVudGlmaWVyIGtleQowMDEwY2lkIGdlbiA9IDEKMDAyMGNpZCB1c2VyX2lkID0gQGdhcjpwaWstdGVzdAowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IGM7dUI7Lkg0dzBUeUBLcEAKMDAyZnNpZ25hdHVyZSAD333N9yVuSLmjCsUrrIEjpg0k8ABmJD6cNlxcdIaPuQo","home_server":"pik-test","user_id":"@gar:pik-test","device_id":"JBLRVMRHED"}
```

To give another idea of how obtuse this is, here for example is what `/register` looked like in  python for the `api/v1` endpoint:

```py3
# Really that's it!
def register_with_password(username, password):
    return api._send("POST", "/register",
        {"type":"m.login.password", "user": username, "password": password})
```

Here is what it would have to look like for if we were going to switch to the `r0` endpoint:
```py3
def r0_register_with_password(username, password):
    session_id = None
    try:
        api._send("POST", "/register",
            {"user": username, "password": password}
        )
    except MatrixRequestError as e:
        # We need to get the session_id out of the 401 error message
        if e.code === 401:
            import json
            content = json.loads(e.content)
            if 'session' in content:
                session_id =  content['session']
            else:
                raise e
    api._send("POST", "/register", {
        "auth": {
            # I have no idea why we use this flow which is normally used for guests
            # or where it is documented
            "type": "m.login.dummy",
            "session": session_id
        }
    })
```

**Comment by dbkr** [comment]
The reason that `m.login.password` is no longer valid is because the username and password are supplied as parameters to the registration request: they are not a means of authentication. Registration was always a two-stage process: previously the client issued a GET to discover supported flows, then a POST, now both requests are POSTs. In either case, the first request could be skipped if the client didn't want to query the available flows (you would just omit the session_id).

Closing this as it appears to be based on a misunderstanding: the doc could probably be clearer but that would be a matrix-doc bug.

**Comment by pik** [comment]
> In either case, the first request could be skipped if the client didn't want to query the available flows 

Yes but not you cannot skip either request, the first request which obtains the flows provides `username` and `password` and the second selects `m.login.dummy` - why can't this simply be supported in one request?

**Comment by dbkr** [comment]
You need supply the username and password in the second request in the same place (ie. `{ "username": "foo", "password": "bar", "auth": {[...]]}`)
