### ISSUE TITLE
Users claimed non-exclusively by an app service don't get notifications

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#2211]
App service users are excluded when generating event_push_actions: this is presumably missing a check for whether the app service user is exclusive, as it makes sense for users claimed exclusively by an app service to not get notifications (arguably) but an app service can be interested in events for normal users, so if you send, say, all events on your HS to an appservice, it will break notifs for everyone.

https://github.com/matrix-org/synapse/blob/master/synapse/storage/push_rule.py#L159

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/blob/0163466d72ae6c9a0930a3b8f25138c50301da2e/synapse/storage/push_rule.py#L159

**Comment by slipeer** [comment]
It may be possible to modify get_if_app_services_interested_in_user function, so that it can distinguish the exclusivity of using the user in appservice?
```
diff -Naur ./synapse-0.21.0-rc2.orig/synapse/storage/appservice.py ./synapse-0.21.0-rc2/synapse/storage/appservice.py
--- ./synapse-0.21.0-rc2.orig/synapse/storage/appservice.py     2017-05-11 09:16:28.825198454 +0300
+++ ./synapse-0.21.0-rc2/synapse/storage/appservice.py  2017-05-11 10:04:50.979659068 +0300
@@ -39,12 +39,15 @@
     def get_app_services(self):
         return self.services_cache

-    def get_if_app_services_interested_in_user(self, user_id):
+    def get_if_app_services_interested_in_user(self, user_id, exclusive=false):
         """Check if the user is one associated with an app service
         """
         for service in self.services_cache:
             if service.is_interested_in_user(user_id):
-                return True
+                if exclusive:
+                    return service.is_exclusive_user(user_id)
+                else:
+                    return True
         return False

     def get_app_service_by_user_id(self, user_id):
diff -Naur ./synapse-0.21.0-rc2.orig/synapse/storage/push_rule.py ./synapse-0.21.0-rc2/synapse/storage/push_rule.py
--- ./synapse-0.21.0-rc2.orig/synapse/storage/push_rule.py      2017-05-11 09:16:28.815198352 +0300
+++ ./synapse-0.21.0-rc2/synapse/storage/push_rule.py   2017-05-11 10:05:10.901861305 +0300
@@ -162,7 +162,7 @@
         local_users_in_room = set(
             u for u in users_in_room
             if self.hs.is_mine_id(u)
-            and not self.get_if_app_services_interested_in_user(u)
+            and not self.get_if_app_services_interested_in_user(u, exclusive=true)
         )

         # users in the room who have pushers need to get push rules run because

```

**Comment by slipeer** [comment]
I make PR with this fix: https://github.com/matrix-org/synapse/pull/2216

**Comment by NilsIrl** [comment]
Isn't this fixed? should the issue be closed?

**Comment by clokep** [comment]
> Isn't this fixed? should the issue be closed?

Good shout. Seems the code [still exists](https://github.com/matrix-org/synapse/blob/68b2611783ab00fdad567654a95492442722c106/synapse/push/bulk_push_rule_evaluator.py#L172-L177) and is still correct after #2233.
