### ISSUE TITLE
add configurable maximums to the number of events requested by /sync and /messages

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2220]
atm we have MAX_LIMIT of 1000 when paginating, but no upper cap on /sync at all, as far as i can see

**Comment by psaavedra** [comment]
Some test done during this Saturday confirmed me a new attact vector for Matrix using the `/sync` (API). The vulnerability is on *Matrix don't set an upper limit for the max number of events to request for a requested room*, this allow the attacker generates huge SQL queries in the server which can degradate the service and lead a DDoS.

**Comment by psaavedra** [comment]
All test passed on https://github.com/matrix-org/synapse/pull/2221.

**Comment by psaavedra** [comment]
Merged https://github.com/matrix-org/synapse/pull/2221
