### ISSUE TITLE
auto remove inactive users older than certain age

### ISSUE THREAD

**Issue by Gibbz** [matrix-org/synapse#2239]
It would be very handy to have an option to automatically remove idle/inactive users older than a certain age. As a room option.

**Comment by Half-Shot** [comment]
This would be a better fit as a bot project, as there could be all sorts of problems with multiple homeservers calculating age.

**Comment by dragetd** [comment]
E.g. in the freenode-federated IRC channels, there are often many inactive accounts in each room.

It would be nice to not have to setup an extra bot but have some server-level option to clean up rooms somehow. =/

**Comment by richvdh** [comment]
dup #1202
