### ISSUE TITLE
status_msg is overwritten when presence is changed (user goes offline)

### ISSUE THREAD

**Issue by jfrederickson** [matrix-org/synapse#2245]
I was testing the status and presence features of Matrix, and noticed this:

```
>>> client.set_status("@sibyl:localhost", "test and stuff")
>>> client.get_status("@sibyl:localhost")
{'user_id': '@sibyl:localhost', 'presence': 'online', 'status_msg': 'test and stuff', 'last_active_ago': 1836, 'currently_active': True}
>>> client.get_status("@sibyl:localhost")
{'user_id': '@sibyl:localhost', 'presence': 'online', 'status_msg': 'test and stuff', 'last_active_ago': 11886, 'currently_active': True}
>>> client.get_status("@sibyl:localhost")
{'user_id': '@sibyl:localhost', 'presence': 'online', 'status_msg': 'test and stuff', 'last_active_ago': 22203, 'currently_active': True}
>>> client.get_status("@sibyl:localhost")
{'user_id': '@sibyl:localhost', 'presence': 'online', 'status_msg': 'test and stuff', 'last_active_ago': 34950, 'currently_active': True}
>>> client.get_status("@sibyl:localhost")
{'user_id': '@sibyl:localhost', 'presence': 'online', 'status_msg': 'test and stuff', 'last_active_ago': 52767, 'currently_active': True}
>>> client.get_status("@sibyl:localhost")
{'user_id': '@sibyl:localhost', 'presence': 'offline', 'last_active_ago': 69343}
```

My status_msg appears to be overwritten when my status changes to "offline" due to inactivity. Needless to say, this makes status_msg not so useful.

This is using matrix-python-sdk (with [my presence changes](https://github.com/matrix-org/matrix-python-sdk/pull/135)), and the only active client at the time for that user was the SDK I was using to enter those function calls above.

**Comment by ShadowJonathan** [comment]
Is this a spec issue? (to specify that `status_msg` shouldn't be touched if it's key is omitted from a status update)

**Comment by deepbluev7** [comment]
I wouldn't say so. There is no status update function called client side. It is simply synapse, that marks the client as offline, because it does not call `/sync` for 5 minutes, which then wipes the `status_msg`. There is no way for clients to prevent that, apart from never going offline.

**Comment by dklimpel** [comment]
Is this issue still relevant?
I cannot reproduce.

I have set a status. Logged out. user goes offline. Status is still existent and has not changed.

**Comment by deepbluev7** [comment]
@dklimpel You probably didn't set a status_msg but an im.vector.status state event. Which is not part of the presence module or even the spec. At least here my status_msg still vanishes regularly, but I last tested it 2 weeks ago.

**Comment by dklimpel** [comment]
> @dklimpel You probably didn't set a status_msg but an im.vector.status state event. Which is not part of the presence module or even the spec. At least here my status_msg still vanishes regularly, but I last tested it 2 weeks ago.

Yes you are right. I did a second check. This is `im.vector.status`.

**Comment by dklimpel** [comment]
IMO it is not a spec issue:
https://matrix.org/docs/spec/client_server/latest#last-active-ago
There are no information about reset `status_msg` whe user is `unavailable `.

**Comment by dklimpel** [comment]
I think in this part Synapse sets `status_msg` to `None` if user is offline.
https://github.com/matrix-org/synapse/blob/8ae0bdca753d2f51b32bc712b66c26f331ec728c/synapse/handlers/presence.py#L1186-L1188
Introduced in #582 with https://github.com/matrix-org/synapse/pull/582/commits/b31ec214a5c2bd674814b2d052200963c5e5cbd7

**Comment by erikjohnston** [comment]
It's not clear to me if this is expected behaviour or not, and I think depends on the use case a bit (e.g. how ephemeral is the status message meant to be?)

**Comment by deepbluev7** [comment]
Imo it is pretty annoying having to manually set the status_msg every morning, but yeah, I guess it depends on the use case. I am fine with not sending it when offline, but having to restore it after going online seems wrong to me.

**Comment by callahad** [comment]
> IMO it is not a spec issue:
> https://matrix.org/docs/spec/client_server/latest#last-active-ago
> There are no information about reset `status_msg` whe user is `unavailable `.

This is compelling: the spec does not require clearing (nor persisting!) the status_msg when state changes, so Synapse's decision to proactively clear the state is arbitrary, and on balance, seems more harmful than allowing it to persist.

Tagging as a bug; patches are welcome.

A patch is likely as simple as removing `if presence != PresenceState.OFFLINE else None` from:

https://github.com/matrix-org/synapse/blob/v1.40.0rc2/synapse/handlers/presence.py#L1186-L1188

(and adding / adjusting some tests)

**Comment by dklimpel** [comment]
I will create a PR. It is not only this one line. :(
