### ISSUE TITLE
Rocket.chat migration

### ISSUE THREAD

**Issue by matejdivecky** [matrix-org/synapse#2249]
Hello, is it possible to export synapse database in format that can be used for rocket.chat? According to https://rocket.chat/docs/administrator-guides/database-migration.
There are 3 solutions to bridge matrix and rocket.chat, but i can't see any support for databse migration.

**Comment by ara4n** [comment]
It should be possible to write a migration script, but I don't know of anyone who has yet.  The bridges don't yet bridge history.
