### ISSUE TITLE
How i can clear message from room? Im really cant find this option

### ISSUE THREAD

**Issue by dnkls** [matrix-org/synapse#2254]
I search in FAQ and search in google , no one dont speak about how clear all masseges from matrix room(((

**Comment by aaronraimist** [comment]
If you are a server admin you can use the [purge history api](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst) to remove stuff from the database.

If you are just a user, you can't delete all messages in a room. You can redact messages but you have to trust other server's and users in the room to actually stop displaying that message. Matrix is kind of like email, once you've sent a message, you can't force someone to delete it.
