### ISSUE TITLE
allow specifying a register url in the server and redirect it from riot app

### ISSUE THREAD

**Issue by pravi** [matrix-org/synapse#2257]
Currently we have registrations directly from app disabled as we use diaspora accounts in diasp.in directly. Register url is https://diasp.in/users/sign_up

Similar is the case for disroot https://user.disroot.org/pwm-disroot/public/NewUser

It would be better if riot could redirect to the sign up url instead of we having to disable registration. It will be much cleaner experience overall.

**Comment by turt2live** [comment]
This seems better reported at https://github.com/vector-im/riot-web

**Comment by pravi** [comment]
But how all the apps will know sign up URL is different? Shouldn't synapse return the sign up URL so all clients will work?

**Comment by pravi** [comment]
I think it will need a change in both synapse and clients.

**Comment by shanavas786** [comment]
It is better to make user registration configurable like user authentication. if a registration provider is used in synapse config registration handler should use it.

**Comment by localguru** [comment]
Any news on that?

**Comment by pravi** [comment]
It is relevant to recently launched librem.one service as well (and any service which uses a common authentication system across multiple services), which uses a separate registration page and users cannot sign up using riot app.

**Comment by neilisfragile** [comment]
We have recently updated support for SAML2 and _some_support for LDAP. Adding more options for auth and registration is something we'd love to do, bandwidth is the only blocker.

**Comment by neilisfragile** [comment]
Though be mindful of https://github.com/matrix-org/synapse/issues/5130

**Comment by galexrt** [comment]
With my changes in #5316 I have Riot showing me a button to login through my **SAML2 SSO** (Keycloak in my case).
Screenshot:
![2019-06-02-235521_946x512_scrot](https://user-images.githubusercontent.com/3718398/58767901-4b815f80-8592-11e9-96d0-7aeb2612546c.png)

Though the PR is currently more or less just focused to get it working for my case of SAML2 SSO auth quickly.

**Comment by richvdh** [comment]
I don't really understand what this issue is asking for. I *think* it's handled by the SSO login flow nowadays.

In any case, I'm going to assume after over 3 years it's no longer particularly relevant and close it.
