### ISSUE TITLE
Remove alias #drupal:matrix.org from #ecobytes-drupal:matrix.allmende.io

### ISSUE THREAD

**Issue by betz** [matrix-org/synapse#2264]
Hi,

For a bigger migration part in getting the main Drupal rooms on matrix, it would be nice to have a main room setup at #drupal:matrix.org but this is alreadt an alias of #ecobytes-drupal:matrix.allmende.io
I have been made admin of #ecobytes-drupal:matrix.allmende.io but i can alter remote addresses.
Matthewn or anyone with the correct rights can step in?
Idea is to remove the remote alias, and start a new #drupal:matrix.org room, which is bridged with IRC and sleck.

Hope to get this starting.

Cheers,
Tom

**Comment by turt2live** [comment]
(pinging @ara4n so he can see this. Hopefully he doesn't hurt me for it ._. )

**Comment by ara4n** [comment]
done
