### ISSUE TITLE
/me command is bypassing mute

### ISSUE THREAD

**Issue by pravi** [matrix-org/synapse#2271]
Even when a user is on mute, their /me command works. This is noticed on telegram bridged groups. Even when the telegram user is on mute, their profile picture changed message is shown.

**Comment by pravi** [comment]
A room where this can be seen https://matrix.to/#/#plus:disroot.org

**Comment by richvdh** [comment]
what do you mean by "on mute" ?

**Comment by t3chguy** [comment]
Also what does `/me` have to do with

> their profile picture changed message is shown.
