### ISSUE TITLE
0.21 leaking fd's

### ISSUE THREAD

**Issue by penguin42** [matrix-org/synapse#2273]
I'm seeing an fd leak since I updated to 0.21; ls -l /proc/2773/fd|wc -l  shows at times a leak of about 20 fd's minute (it does sometimes drop back).

I think this is also the reason behind:
2017-06-11 03:23:09,233 - twisted - 131 - INFO - PUT-5975- Could not accept new connection (EMFILE)

that filled up my homeserver logs and also the reason I couldn't ssh in to the host today.

**Comment by ara4n** [comment]
EMFILE is a symptom rather than a cause of the leak.  Is it still doing it?

**Comment by penguin42** [comment]
I've not been running synapse for a while now so am not sure.

**Comment by neilisfragile** [comment]
Closing, old version of synapse, unclear if problem is persisting for @penguin42
