### ISSUE TITLE
deb package doesnt install /res/templates

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#2284]
None of the files in https://github.com/matrix-org/synapse/tree/master/res/templates get installed by the deb package.

To reproduce:

```
apt-get install matrix-synapse
find / | grep 'notif_mail.html'
```

**Comment by Metzlmane** [comment]
That's why it always crashed when i enabled notifications. Where is the folder normally located?

**Comment by killua-eu** [comment]
@Metzlmane i have no clue where, i've always used the deb packaged version. i'm out on vacation, so cant reproduce, but you can easily by installing synapse with pip install

**Comment by tanius** [comment]
I think @erikjohnston was talking about this problem a year ago, in [this comment](https://github.com/matrix-org/synapse/pull/759#issuecomment-216827055).

**Comment by richvdh** [comment]
https://github.com/matrix-org/package-synapse-debian/issues/37
