### ISSUE TITLE
can't act on invite to inexistent room

### ISSUE THREAD

**Issue by MoritzFago** [matrix-org/synapse#2293]
I was invited to a conversation, but the inviter left the room. Now i can't get rid of the invitation, because on accept i get: `Betreten des Raumes ist fehlgeschlagen (joining failed)
No known servers` and on decline: `Ablehnen der Einladung ist fehlgeschlagen (declaine failed
Not a known room)`

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/4225

**Comment by thekyriarchy** [comment]
was this supposed to be fixed by matrix-org/synapse#2145 ? it still is an issue for me

**Comment by richvdh** [comment]
comments on https://github.com/vector-im/riot-web/issues/4374 suggest this is a dup of https://github.com/matrix-org/synapse/issues/2181
