### ISSUE TITLE
Expire URL media cache

### ISSUE THREAD

**Issue by zzottel** [matrix-org/synapse#2294]
The images that are downloaded for URL previews (table local_media_repository_url_cache) are never deleted from the media store. As far as I've heard, they are not even used anymore if the last preview was more than an hour ago.

In my case, this is about 8000 files and 1 GB of data after about 9 months of Synapse usage, and I'm the only user on my HS that ever saw any URL previews (the others use mobile clients only). This is nearly half the size of regular remote_content, so it's really a considerable amount of uselessly wasted disk space.

Please delete old images from URL previews regularly.

**Comment by zzottel** [comment]
For the meantime, I've created a small script that does the job. You can find it at https://github.com/zzottel/synapse-delurlcache

Use at your own risk! Comments from devs welcome, especially if i did something wrong. :-)

**Comment by rubo77** [comment]
What about the folder `media_store/remote_content/`? 

Could this folder be emptied anyhow? It already uses 2GB space on my server.

**Comment by erikjohnston** [comment]
FTR, in v0.22.0 synapse now stores media in a different directory, and is marked us temporary in the database. It still doesn't delete the data but at least now its segregated which is a useful first step. 

---

@rubo77 https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst lets you do just that :)

**Comment by zzottel** [comment]
Updated delurlcache.pl to work with Synapse 0.22.0 (see comment above for link).

**Comment by zzottel** [comment]
Fixed in Synapse 0.24 by #2478 , thanks!

**Comment by anoadragon453** [comment]
> https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst lets you do just that :)

Note that this doc file has moved to https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/media_admin_api.md#purge-remote-media-api.
