### ISSUE TITLE
Room members list not up to date

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#2295]
So I have this very specific use case where my homeserver was once up only occasionaly (because of virtu issues, apparently), then totally down, then up and running well, and I'm on a room on a homeserver which hasn't been able to reach mine because of routing problems on the provider's side.

So now that my own server is up and running and routing issues has been (almost) resolved, some events from the second homeserver never got synced with mine, including join events from an user (which is the account on matrix.org I was using during the said downtime). My homeserver isn't syncing these events, meaning that now I have an unlisted user speaking on the room and Riot doesn't seem happy with it as the profile picture and name apparently aren't provided (I believe it's Synapse who provide these info, correct me if I'm wrong).

![capture d ecran de 2017-06-21 11-12-28](https://user-images.githubusercontent.com/5547783/27379354-c841d7ee-5672-11e7-8f84-36a357cf5822.png)

(the unknown user here is `@babolivier:matrix.org`)

It would be cool if there was a way to tell Synapse to update the room member list if there's an unknown user speaking, which would typically be the result of some heavy network/communication issue between the two servers (which was the case here)

**Comment by richvdh** [comment]
Synapse won't allow the events into a room if it doesn't think that the user is in the room... which suggests that maybe the client's cache is out of sync with the server.

I think this is probably a symptom of a bug we have elsewhere in the tracker. @babolivier: do you fancy clarifying a bit and/or looking for duplicates?

**Comment by babolivier** [comment]
> Synapse won't allow the events into a room if it doesn't think that the user is in the room... which suggests that maybe the client's cache is out of sync with the server.
> 
> I think this is probably a symptom of a bug we have elsewhere in the tracker. @babolivier: do you fancy clarifying a bit and/or looking for duplicates?

Given the bug is two years old, and that I don't recall seeing it happen anytime over the past year and a half or so, I'm pretty sure it has been fixed. I don't really fancy digging into how or when it would have been fixed, as it could come from either Synapse or Riot Web (and I don't know anything about the latter's codebase currently), so that would likely be quite time consuming for possibly little value, so I'll just close the issue.
