### ISSUE TITLE
WebRTC calls are currently only supported on rooms with two members

### ISSUE THREAD

**Issue by webcluesdev** [matrix-org/synapse#2303]
I just start to setup Synapse setup on my server. It's working fine with one to one calling function. 

I want to make a conference call but it showing me "**WebRTC calls are currently only supported on rooms with two members**" error.

How to resolve it.

Thanks in advance.

**Comment by uhoreg** [comment]
What client are you using?  This sounds more like a client issue than a server issue.

**Comment by webcluesdev** [comment]
Thanks for your response. 

I am using Matrix client for make a call. I need to use it with Android SDK. When I try group calling with Android SDK but it was not working then I try with Matrix Console (Matrix HQ) to make a call from browser. So I facing this error.

Also I try with riot (https://riot.im/app/#/home) android application but It shows same error.

**Comment by webcluesdev** [comment]
This issue is solved by changing federation count in a homeserver config file.

**Comment by siqarian** [comment]
i have same issue..... "WebRTC calls are currently only supported on rooms with two members"

> This issue is solved by changing federation count in a homeserver config file.


in yml  file ? how ?not found federation count ...
Thanks
