### ISSUE TITLE
check_requirements() problem

### ISSUE THREAD

**Issue by ptman** [matrix-org/synapse#2305]
Debian stretch has python-pysaml2 version 3.0.0-2. Which is also missing the `__version__ = '3.0.0'` in the source file. Adding that line does not help however:

    Missing Requirement: Version of 'pysaml2>=3.0.0,<4.0.0' in '/usr/lib/python2.7/dist-packages/saml2/__init__.pyc' is too old. '3.0.0' < '3.0.0,<4.0.0'

I think 3.0.0 should satisfy >=3.0.0,<4.0.0

https://github.com/matrix-org/synapse/blob/4902db1fc978d1c9a3681720cffc4dbb9d72dbea/synapse/python_dependencies.py#L127

**Comment by richvdh** [comment]
Is this still a problem?

**Comment by ptman** [comment]
I have no idea. I've moved to the docker images

**Comment by richvdh** [comment]
guess not then!
