### ISSUE TITLE
Some User Directory use-cases seem flakey

### ISSUE THREAD

**Issue by leonerd** [matrix-org/synapse#2306]
At first this appeared to be a race condition in `sytest`, but I don't think it is.

There are a few integration tests that sometimes fail; e.g.

```
Running tests/52user-directory/01public.pl...
...
  Testing if: Users appear/disappear from directory when history_visibility are changed... 
   | User initially not in directory... OK
   | User appears in directory after history_visibility set to public... OK
   +--- FAIL:
 | Timed out waiting for test at ./run-tests.pl line 542.
 +----------------------
...
```

In current `sytest/develop` this appears to be a race when running it, because it's flaky and variously comes and goes, but adding a `try_repeat_until_success` loop to it just means it either succeeds quickly or times out and fails every attempt. So it feels more like it sometimes succeeds or fails within the synapse itself.

**Comment by hawkowl** [comment]
Fixed by the rewrite in #4537 and removed from the blacklist in #5637.
