### ISSUE TITLE
register_new_matrix_user - impossible to create non-root user non-interactively

### ISSUE THREAD

**Issue by vansickle** [matrix-org/synapse#2310]
This works correctly:

`register_new_matrix_user -c homeserver.yaml -u root -p password -a https://localhost:8448`

But this one:

`register_new_matrix_user -c homeserver.yaml -u user -p password https://localhost:8448`

asks whether user admin or not.

It should be possible at least to set smth like --admin=false

**Comment by richvdh** [comment]
fixed (finally) by #3836

**Comment by keith24** [comment]
For anyone that googled their way here, it's `--no-admin`.
