### ISSUE TITLE
Need api for antvirus file handling

### ISSUE THREAD

**Issue by iav** [matrix-org/synapse#2311]
Need api for handling stored files and filed just in time of uploading.
Need a way to tell user about server rejected file uploading because of antivirus report.

Other case -  correctly enumerate by antivirus scanner all files stored for server or channel, and correctly move it from matrix server file storage to  another file storage, and notify related administrators (file-own chats, servers, users etc).

Maybe some already used antivirus plug in protocols can be used - like milter or icap.

**Comment by hawkowl** [comment]
@ara4n don't we have this for dinsic or something now?

**Comment by dklimpel** [comment]
There is a hook for this case #9311
