### ISSUE TITLE
Matrix does not block mass nick spam

### ISSUE THREAD

**Issue by Svetlana-T** [matrix-org/synapse#2312]
Matrix does not block mass nick spam. Users see it, and users are highlighted by it. Perhaps as an opt-in or an opt-out, and with a customizable number of nicks after which a message is considered spammy, this could be added.

(This issue may affect desktop clients, mobile clients, riot. If any of them have a separate bug tracker, please let me know.)

**Comment by aaronraimist** [comment]
Is this issue just requesting that clients not display a wall of text when lots of nicks get changed? If so then that isn't a Synapse issue and should be filed on the appropriate client. Riot's issue tracker is here https://github.com/vector-im/riot-web/issues

Riot does now have an option to hide join and leave messages.

**Comment by SvetlanaTkachenko** [comment]
No, mass nick spam is defined as a message which contains many nicknames. I agree with you that filtering such messages out can be done client side. If you are not interested in tagging messages as 'possible mass nick spam' in synapse then I would be glad to raise this issue with riot, as you suggested.

**Comment by aaronraimist** [comment]
Oh sorry I see what you mean. Literally someone sending a spam message. This is an appropriate issue for Synapse.

Related: #3637

**Comment by richvdh** [comment]
spam filtering is something that is being handled outside synapse, via modules.
