### ISSUE TITLE
Bug of no notifications for non-exclusive users in AS is still happening

### ISSUE THREAD

**Issue by dtygel** [matrix-org/synapse#2313]
Look at the discussion at https://github.com/matrix-org/synapse/issues/2211 .

There is a fix here: https://github.com/matrix-org/synapse/pull/2216

But it was (maybe accidentally) reverted.

**Comment by slipeer** [comment]
@dtygel it's optimized with this change: https://github.com/matrix-org/synapse/commit/760625acbaef9ae7032ba5e59e91979f454febef

**Comment by slipeer** [comment]
@erikjohnston  your optimization  https://github.com/matrix-org/synapse/commit/760625acbaef9ae7032ba5e59e91979f454febef brake push again!

**Comment by slipeer** [comment]
@dtygel problem in __make_exclusive_regex_ function in synapse/storage/appservice.py
Problem only in 0.22.1 release - in development tree problem fixed: __make_exclusive_regex_ code moved to _AppService_ class initialization. 
I can't find PR that fixes it (very strange for me...) - i made this chnges by hand and all work for  me now.

**Comment by MadLittleMods** [comment]
https://github.com/matrix-org/synapse/issues/2211 is still open and I'm failing to see the difference

Duplicate of https://github.com/matrix-org/synapse/issues/2211
