### ISSUE TITLE
The VoIP conference can't be established on local server deployed LAN without internet access.

### ISSUE THREAD

**Issue by chensixian** [matrix-org/synapse#2314]

**Comment by uhoreg** [comment]
This is due to how video conferencing is implemented in Riot.  It works by inviting a bot from matrix.org, and if the bot can't join the room, then it doesn't work.
So this is a dup of https://github.com/vector-im/riot-web/issues/503, and not really a synapse issue.

**Comment by chensixian** [comment]
thanks.
