### ISSUE TITLE
Plugin or bot for auto-replace text in room messages via regexp rules

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2316]
Is there any way to implement autoreplace text function for all user messages in specifiic room via regexp? Maybe via bot, script or plugin

**Comment by turt2live** [comment]
server-side? I don't think so.

**Comment by uhoreg** [comment]
Why would you want to?  Doing so often leads to [clbuttic mistakes](http://thedailywtf.com/articles/The-Clbuttic-Mistake-).

**Comment by MurzNN** [comment]
I want convert in chatroom messages plain urls of corporate CRM tasks and contacts like `http://crm.homeserver.org/?task=1234` to more useful information with adding task info, assigned user, contact names, etc, something like `<a href="http://crm.homeserver.org/?task=1234">Task owner: Task title text</a>`

**Comment by uhoreg** [comment]
It might be easiest to make a bot that does something similar to the GitHub integration when you write an issue number (e.g. `#2316` or `matrix-org/synapse#2316`) in a room that has GitHub integration enabled.

**Comment by MurzNN** [comment]
Bots add new message to dialog, not changing current user message - this looks not so good, especially when message contains many links. This is workaround, but will be good to have message text replacement ability instead of adding new messages to room via bot.
