### ISSUE TITLE
How can I pre-populate list of people in corporate Matrix server?

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2327]
Our company need to pre-populate list of all employees for each user in company. So new employee must see list of all other employees in "People" list, without manually finding and adding them.

Before our company use XMPP server and I configure shared roster that pre-loads list of all users from LDAP server, so new users see contacts of all employees, grouped by department, and it auto-add new  employee to contact list (roster) for old users too.

Is there any way to do same thing in Matrix Synapse home server?

**Comment by turt2live** [comment]
You'd have to get an access token for those users and impersonate them. Although the user directory stuff on the horizon may work well for your use case.

**Comment by MurzNN** [comment]
@turt2live, thanks for quick answer! Maybe you can provide some example how I can add-remove items in user contact list via command-like script, having user access token?

Also can you point me to description what is user directory stuff and how can I enable it on Matrix homeserver? Thanks!

**Comment by turt2live** [comment]
The user directory hasn't been made yet, but it is being tracked here: https://github.com/vector-im/riot-web/issues/2930

As for the script, it would be convoluted to be honest. Using the API you'd have to invite users and join the rooms, possibly tagging them as 1:1 as well. The interactive API is a good place to start: http://matrix.org/docs/api/client-server/

**Comment by Tesla2k** [comment]
Is there any solution for this yet?

**Comment by neilisfragile** [comment]
The user directory exists and populating of new users can happen via the [admin register_user API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/register_api.rst)

**Comment by Tesla2k** [comment]
Yes I will run my own instance.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by UndeadKernel** [comment]
I was wondering if anybody got something working to address this issue.
I'm also looking to pre-populate the people list of everyone with everyone else.

**Comment by richvdh** [comment]
I'd recommend scripting one of the admin APIs: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#create-or-modify-account or https://github.com/matrix-org/synapse/blob/master/docs/admin_api/register_api.rst#shared-secret-registration.

**Comment by tucnak** [comment]
This is complete marasmus— the inability to have people list of some sort. I mean, there's search so there's obviously _some_ index in place. The next logical step is simply to expose the list itself in some meaningful way and implement a flag for "shared/public people" behaviour.

But apparently, this is considered too specific, or perhaps, too basic, for something like Synapse! Even though this behaviour is considered par for the course for most if not all messaging programs; we've already established that Jabber can do it, all proprietary shit does it, and consistently at that! The lack of roster–kind behaviour is a drag. Currently, the only way around this is to create specific department rooms and populate them with users manually. Then the room itself functions as a list, and we can have #general, too.

Why is this closed?

I don't understand, how a selection from the admin API above is supposed to address the complete lack of rosters at any level and make no mistake that is the real subject of this issue.

PS. My story is that we simply want to keep a coworker directory on our corporate instance, which is already kind of there— you can fetch it— by search. Why isn't there an option to have it exposed is baffling to me.

**Comment by hex-m** [comment]
You can use [ma1sd](https://github.com/ma1uta/ma1sd/blob/master/docs/features/directory.md) to add results from your identity backend to the user-search. The Synapse option `search_all_users` may also fit your use-case.

Having a "contact list" would be a client feature and is thus tracked in the [element-web](https://github.com/vector-im/element-web/issues/4488) issue tracker.

**Comment by BxptisteM** [comment]
Hi, 

Is it still not possible to pre-fill the list of peoples ??
I really need to implement this in my synapse server **asap**...
