### ISSUE TITLE
Matrix to Matrix bridge for connect to slave accounts from master via gateway

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2328]
I am an admin into 3 different companies, So I have 3 separate Matrix home servers with synapse and LDAP auth. On each server I have separate admin accout like `mylogin:companyname.org` and `mysecondlogin:companyname2.org`  from LDAP database, and I want to talk with people of each company via my company credentials from this company (not from other).

Before I use XMPP eJabbberd and solve this problem via configure Jabber2Jabber gateway, so I login via my private master account, and XMPP gateway auto-logins to all slave accounts. So I can talk via my main private account `mylogin@jabber.org` with people of all companies together, and they see me as corporate account (`mylogin@companyname.org` instead of `mylogin@jabber.org`).

Matrix also have gateway-like features via Bridge to IRC, Slack, XMPP, Twitter, etc, but seems at now we can't bridge to other Matrix account.

Will be good to have same behaviour in Matrix synapse server: provide Matrix2Matrix bridge for configure master account, that auto-connects to pre-configure slave accounts, and I talk with people from slave accounts via slave credentials (`@admin:companyname2.org`) and they will not see my master account credentials (`@Murz:matrix.org`).

This will be same behaviour if I run multiple Matrix clients and connect to each slave login manually, but with one instance of Matrix client and without problems with switching between multiple client windows.

**Comment by ShadowJonathan** [comment]
@MurzNN i'm curious, would this in any way be solved by Decentralized User Accounts? (https://github.com/matrix-org/matrix-doc/issues/915)

**Comment by MurzNN** [comment]
Because users of companyname1 want to see me as member of `companyname1.org` domain, not as user of other company (eg `vasya@companyname2.org`), also many companies have LDAP authentication, that will not work with Decentralized User Accounts, even when they will be released.

**Comment by MurzNN** [comment]
As partly workaround can be used https://github.com/elokapina/middleman

**Comment by clokep** [comment]
I'm struggling a bit to see how this is a Synapse issue. It seems that this is either a client issue (where you want a client to allow signing into multiple accounts) or maybe a new type of bridge?

**Comment by shukon** [comment]
Probably more relevant in places like https://github.com/turt2live/matrix-wishlist/issues (or similar)

**Comment by clokep** [comment]
I think there's a few pieces to this:

* Allowing clients to log into multiple accounts should be covered elsewhere.
* Some sort of Jabber2Jabber gateway (this reminds me of an IRC bouncer, which I think is a similar concept) -- this could probably be done as a bridge without Synapse needing to know anything special about it.
* Supporting multiple domains in a single Synapse (I don't think this would solve your issue, but it came to mind and want to cross-link in case someone else ends up here) -- see #8885 

I'm going to close this since I think the implementation of this would want to live outside of Synapse.

> Probably more relevant in places like [https://github.com/turt2live/matrix-wishlist/issues](https://github.com/turt2live/matrix-wishlist/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) (or similar)

Seems this had already been done: turt2live/matrix-wishlist#15.
