### ISSUE TITLE
[Feature request] Implement message threads in Matrix like Slack Threaded messaging

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2329]
Slack introduce Threads in rooms: https://slackhq.com/threaded-messaging-comes-to-slack-417ffba054bd
Will be good to implement same threads feature in Matrix rooms.

**Comment by MurzNN** [comment]
Seems this is not so hard to implement like in Slack - on "create thread" event we must create new room with title from current message, and in current room provide link to new room with this thread (and message counter).

**Comment by turt2live** [comment]
This is also being tracked here: https://github.com/vector-im/riot-web/issues/2349

**Comment by dessalines** [comment]
This is also implemented in mattermost already:

![example](http://www.mattermost.org/wp-content/uploads/2015/10/Untitled-1.png)

**Comment by ara4n** [comment]
We do have label-based threading support in Synapse now, but Riot doesn't expose it yet: matrix-org/matrix-doc#2326 and https://github.com/matrix-org/synapse/pull/6301

**Comment by MadLittleMods** [comment]
Threading was added via [MSC3440](https://github.com/matrix-org/matrix-spec-proposals/pull/3440).

And for a client, this has ended up as Slack-like threading in Element, https://element.io/blog/introducing-threads-in-beta/
