### ISSUE TITLE
Add timestamp selection of events

### ISSUE THREAD

**Issue by sbts** [matrix-org/synapse#2333]
As outlined in 
matrix-org/matrix-doc#946 
It would be desirable to be able to filter on timestamps

**Comment by clokep** [comment]
> matrix-org/matrix-doc#946

This became https://github.com/matrix-org/matrix-spec/issues/248

**Comment by clokep** [comment]
I'm going to close this though -- without an MSC to implement or anything then this is clearly on the spec side to solve.
