### ISSUE TITLE
List abandoned rooms

### ISSUE THREAD

**Issue by saintger** [matrix-org/synapse#2338]
When everybody leaves a room, it is normally not supposed to be accessed anymore. So this room is abandoned.
It would be useful to list such rooms in order to delete/purge them.

**Comment by prathik-kaliyambath** [comment]
Is this issue still being worked on?

**Comment by mathiasblc** [comment]
Hello,

Any updates on this?

**Comment by clokep** [comment]
The additions to the room list admin API in #7225 could be used to find rooms that have no users in them.
