### ISSUE TITLE
Delete a room with associated contents (messages and files)

### ISSUE THREAD

**Issue by saintger** [matrix-org/synapse#2339]
It would be nice to be able to delete room and all associated contents (uploaded files).
For instance when everybody leaves the room, the content is not relevant/useful anymore and can be safely deleted.

Related issue: https://github.com/matrix-org/synapse/issues/2338

**Comment by t3chguy** [comment]
Content is not directly tied to a room, especially after I added the `Forward Event` feature to riot-web, it forwards the event without re-uploading the content demonstrating that Content does not have 1 point of origin, this is especially clear in Dendrite

**Comment by saintger** [comment]
Closing this issue as it is more related to matrix-doc https://github.com/matrix-org/matrix-doc/issues/948
