### ISSUE TITLE
Uploaded files should be associated to a room

### ISSUE THREAD

**Issue by saintger** [matrix-org/synapse#2340]
There is currently no link between an uploaded file and the room where it has been uploaded.

So in theory, everybody have access to all uploaded files (if they are able to guess the random path) and it may be a privacy issue.

And if we want to be able to safely delete uploaded files belonging to abandoned room, a link between the uploaded file and the room has to exist somewhere.

Relevant issues: https://github.com/matrix-org/synapse/issues/2339

**Comment by t3chguy** [comment]
With the coming of Dendrite which has a central de-duplicating media store this will be especially impossible. Also see https://github.com/matrix-org/synapse/issues/2339#issuecomment-313435301

**Comment by uhoreg** [comment]
FTR, the ability for anyone to have access to the uploaded files, even if they are not in the room, is https://github.com/matrix-org/synapse/issues/1403

**Comment by saintger** [comment]
Closing this issue as it is more related to matrix-doc https://github.com/matrix-org/matrix-doc/issues/948
