### ISSUE TITLE
Getting state events for an obviously invalid room ID should complain about the room ID, not guest access

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2347]
`GET https://dev.t2bot.io/_matrix/client/r0/rooms/THIS_IS_OBVIOUSLY_NOT_A_ROOM/state/m.room.power_levels/ (@_webhook:dev.t2bot.io) HTTP 403 Error: {"errcode":"M_GUEST_ACCESS_FORBIDDEN","error":"Guest access not allowed"}`

**Comment by floviolleau** [comment]
Same as #2534?

**Comment by richvdh** [comment]
> Same as #2534?

No, this issue is simply an incorrect error message. There's something else going on in #2534.

**Comment by richvdh** [comment]
I *think* this one got fixed as part of some other work.
