### ISSUE TITLE
room_id missing from response body for rooms/{roomId}/join endpoint

### ISSUE THREAD

**Issue by jplatte** [matrix-org/synapse#2349]
According to [the specification](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-client-unstable-rooms-roomid-join) (both r0.2.0 and unstable) the `rooms/{roomId}/join` endpoint should return the room_id for the room that was joined. This is not actually the case on matrix.org though – the response is just an empty object. I have not checked if this applies to `join/{roomIdOrAlias}` too, but I suspect that it does.

**Comment by her001** [comment]
I just tested `join/{roomIdOrAlias}` in Riot, joining a room that I was invited to both on matrix.org and on another Synapse homeserver. I then joined a public room on matrix.org (no invite). In all cases, the response body was properly formed, with the room_id.

I did not test `rooms/{roomId}/join`.
