### ISSUE TITLE
Mibile/App skins :/

### ISSUE THREAD

**Issue by dnkls** [matrix-org/synapse#2353]
Plz add dark-green (like Linux terminal style) skins for Iphone and Andorid app, and some others skins.

**Comment by turt2live** [comment]
The starting point for this is https://github.com/vector-im/riot-meta/issues/22

This is also not a synapse issue - please post issues in the relevant project as they might get lost.

**Comment by lfaraone** [comment]
@dnkls or a maintainer, can this be closed?
