### ISSUE TITLE
Inability to relinquish/remove/delete some or all aliases on rooms

### ISSUE THREAD

**Issue by heyakyra** [matrix-org/synapse#2360]
Even though I am an admin, I am unable to relinquish aliases. When I try, I get the error "M_FORBIDDEN: You don't have permission to delete the alias."

**Comment by turt2live** [comment]
Is the alias local to your server or from another server?

**Comment by thekyriarchy** [comment]
local

**Comment by richvdh** [comment]
Which API are you calling to delete the alias?
Are you a server admin?

**Comment by thekyriarchy** [comment]
I am not the server admin. I am using the riot web interface.

**Comment by richvdh** [comment]
@heyakyra if this is still a problem: could you share logs from synapse?
