### ISSUE TITLE
synapse_port_db can choke on duplicate keys in the receipts_linearized_uniqueness constraint

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2364]
see https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1499889899583864GahlJ:matrix.org

**Comment by peterhoeg** [comment]
I have a database that was ported from sqlite which randomly throws this error. That link (or rather what it then points to) is no longer available it seems.

**Comment by richvdh** [comment]
I don't think there's enough information here for a useful bug report. If people see something related, please open a new issue clearly describing the symptoms.
