### ISSUE TITLE
Use non-google captchas

### ISSUE THREAD

**Issue by duxovni** [matrix-org/synapse#2368]
I'd like a way to run a matrix server without relying on Google for captchas. It'd be nice if synapse and other matrix servers made it easy to integrate self-hosted captcha systems like https://github.com/emotionLoop/visualCaptcha

**Comment by jomat** [comment]
I also don't want to pester my users with Google, that's why I don't use recaptcha and why I still hesitate to add my HS to the public server list.

**Comment by richvdh** [comment]
dup #1561
