### ISSUE TITLE
Redacted media file is still accessible across bridges

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/synapse#2369]
I sent a media file in IRC-bridged Matrix room, redacted it and expected the file to disappear, but instead the link at IRC continues working.

I originally opened this issue at https://github.com/matrix-org/matrix-appservice-irc/issues/473 where (or in the #irc:matrix.org) room I was told that it's a Synapse issue. I searched for the issues and found https://github.com/matrix-org/synapse/issues/1287 which was said to be related, but that this is a different issue.

**Comment by richvdh** [comment]
I think this is a dup of #1263
