### ISSUE TITLE
There is no OAuth2 password provider

### ISSUE THREAD

**Issue by ansiwen** [matrix-org/synapse#2376]
In order to authenticate against google accounts for example, it would be great to have a password provider for OAuth2.

#2125 got closed without further comment.

**Comment by methuz** [comment]
I have no idea why synapse don't support OAuth2.

**Comment by ara4n** [comment]
because nobody has implemented it yet. #2125 was closed without comment because it was asking whether the feature existed rather than asking for it to exist, i think :/

PRs would be *very* welcome.

**Comment by ptman** [comment]
https://github.com/matrix-org/synapse/pull/7059

**Comment by clokep** [comment]
This was added in #7256.
