### ISSUE TITLE
Key permission error

### ISSUE THREAD

**Issue by f1234k** [matrix-org/synapse#2379]
My issue is exactly the same with the one that is reported [here](https://github.com/matrix-org/synapse/issues/2122):

```
File "/usr/lib/python2.7/dist-packages/synapse/config/tls.py", line 130, in generate_files
with open(tls_private_key_path, "w") as private_key_file:
IOError: [Errno 13] Permission denied: '/etc/letsencrypt/live/--------/privkey.pem'
```

However:

The files actually do exist in the letsencrypt folder. The permissions are OK.

The only thing that may be causing this is that the files are not actually files since certbot is using softlinks in the live folder to point to the archive folder. 

In order to see if that was the issue, I pointed homeserver.yaml directly to the actual files in the archive folder of letsencrypt but the matrix-synapse service still failed to start. 

The "Permission Denied" message persists (this time on the actual files, in the archive folder of letsencrypt).

Notice that the files are fully readable (and writable) by anyone (even though matrix-synapse should not be opening them for writing in any case). In order to make sure that the path actually exists, I copied the path from my homeserver.yaml file and pasted it in a vim command to make sure that there are no typos in the path somewhere: I can directly open the files through vim.

I'm pretty lost as to what may be causing this problem since the default certificate and key are working without issues.

Could there be that synapse is expecting the file to have a specific extension (like crt or key)?

Anyone has any idea what may be causing this?

**Comment by Christilut** [comment]
I just messed around with this... My experience is that soft links do not work and you have to copy the certificate files to the matrix-synapse folder...

Another fun thing: if you mistype the cert.pem filepath then Synapse won't complain and happily start and create its own self-signed certificate which will cause INSECURE_RESPONSE errors.
A `file not found` error would be nice there :)

**Comment by KlausHans** [comment]
I wanted to migrate from my build of the sources to the easy-to-update debian package. With this package i ran in the same issue. The exact same configuration runs flawlessly with my own build.

**Comment by richvdh** [comment]
I'm closing this as I think the underlying problem was a misleading error message, which should be fixed by #2551. Please let us know if you're still having problems.

**Comment by KlausHans** [comment]
This problem is still a thing for me.
`sudo -u matrix-synapse head -n1 /etc/letsencrypt/live/--------/privkey.pem` 
tells me that the permission is denied:
`head: '/etc/letsencrypt/live/rkem.de/privkey.pem' kann nicht zum Lesen geöffnet werden: Keine Berechtigung`

How do i solve this?

**Comment by Jasper-Ben** [comment]
I personally just use a dirty workaround. After updating letsencrypt certificates via cronjob I copy these to /etc/synapse and change ownership and permissions on them. Not pretty, but it gets the job done.

`0 */6 * * * certbot renew -q && cp /etc/letsencrypt/live/matrix.domain.ltd/fullchain.pem /etc/letsencrypt/live/matrix.domain.ltd/privkey.pem /etc/matrix-synapse/ && chown root:matrix-synapse /etc/matrix-synapse/privkey.pem /etc/matrix-synapse/fullchain.pem && chmod 640 /etc/matrix-synapse/fullchain.pem /etc/matrix-synapse/privkey.pem`

**Comment by richvdh** [comment]
@KlausHans you need to give `matrix-synapse` permission to read that file. There should be plenty of resources out there to help you with unix file permissions.

@Jasper-Ben thanks for the tip. You might look at using a certbot `deploy-hook` as a slightly cleaner workaround.

**Comment by satoshinotdead** [comment]
> Softlinks should be fine, but remember that the user running synapse must have permission to read the softlink, and the file it points to, and all the parent directories.
> 
> It looks like you're running this from the debian package, which runs synapse as the `matrix-synapse` user. To help diagnose, try:
> 
> ```
> sudo -u matrix-synapse head -n1 /etc/letsencrypt/live/--------/privkey.pem
> ```
> 
>     * it should show the first line of the key file.

Sorry Sr! Can you give me an example or a simple direction to the correct docs to read about it?  We need to create user/group on server (not contained) first?

Big thanks.
