### ISSUE TITLE
Cannot /unban an admin

### ISSUE THREAD

**Issue by tdussa** [matrix-org/synapse#2383]
I might have come up with a way to paint myself in a corner.

I accidentally banned a user from a private room, then in a misguided effort (as per the known API-change related problems, no clients were able to unban him again) to get him free again, granted him administrator privileges in that room.

Then, as I hadn't gotten anywhere, I started to look into the API and tried to unban the user via curl, using this call:
```
curl -XPOST -d '{"user_id":"@user:matrix.org"}' "https://www.matrix.org/_matrix/client/r0/rooms/$CHANNEL:matrix.org/unban?access_token=$ACCESSTOKEN"
```

This, unfortunately, returned an error code (M_FORBIDDEN) and the error message "You cannot kick user @user:matrix.org."

As this is supposedly the current API call to unban users, I am guessing that I cannot unban a fellow
admin user (although I am not entirely sure why the error message is talking about kicking the user),
which, if correct, would raise the question as to how to unban an admin?

Or am I completely off-track here?

**Comment by richvdh** [comment]
this seems like a misdiagnosis. Any user with the necessary PL to ban a user should be able to unban that user, regardless of the target user's PL.

I suspect something else was going on.

**Comment by mjarr** [comment]
@richvdh
I can confirm this is still an issue as it just happened on my test server.
I created a room as **user**, invited server **admin** and kicked him. Then as **admin** I used Mjolnir's `make admin` command, which resulted in **user** giving **admin** 100 power in that room, but failing to invite him because of the ban. Calling unban as **user** results in `403 Forbidden` with `You cannot kick user @admin:domain.tld.` error message.

**Comment by richvdh** [comment]
ok so the sequence is:

 * ban a user
 * promote that user to admin
 * attempt to unban them

so yeah, that probably fails. Promoting a banned user to admin seems a pretty odd thing to do, but open an issue against the matrix spec if you feel very strongly.

**Comment by tdussa** [comment]
Richard,

I don't know (and frankly, don't care) whether or not the Matrix specs prohibit this sequence of events.  If this sequence is prohibited, then the software should not _allow_ it to be performed; if it is not prohibited, well, then the software should do the proper thing.  Either way, this is a bug IMHO.  (It is obviously debatable whether it this is a bug that requires urgent fixing -- in fact, I would classify this as very low priority.)

Having said that, what *is* the proper way to unban an admin then?
