### ISSUE TITLE
Synapse server went down after ldap integration

### ISSUE THREAD

**Issue by Ajmal-M-A** [matrix-org/synapse#2391]
I have installed Matrix server and all are working fine, Then I tried to integrate matrix to ldap after giving ldap configuration the matrix server went down, it no more listen to the ports 8448 and 8008. Server didn't give any error message while restarting the service. Please help to solve this issue. I didn't make any changes in other configuration files.
=====
ldap_config:
   enabled: true
   server: "ldap://localhost"
   port: 389
   tls: false
   search_base: "ou=Users,dc=example,dc=com"
   search_property: "cn"
   email_property: "email"
   full_name_property: "givenName"
===

**Comment by andersruneson** [comment]
I think the ldap config in the packaged synapse is totally wrong, uncomment that and use https://github.com/matrix-org/matrix-synapse-ldap3 instead.

**Comment by clokep** [comment]
I'm going to close this since it is several years old and I'm guessing this was either figured out or an alternative was used.
