### ISSUE TITLE
Blacklist room ID from federating

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/synapse#2392]
I think that Synapse should somehow have the ability to block specific room IDs, as somehow specified by homeserver administrators, from federating (preventing users from joining it or adding aliases or even preventing the room from having aliases).

Use case would be content illegal in the country where the homeserver is ran and potential legal trouble for homeserver administrator for hosting the room or content in it.

*I think this issue has been discussed previously at Matrix, but I wasn't able to find an issue either from this repository or matrix-docs and when asking I was told to feel free to file it here.*

**Comment by turt2live** [comment]
Would the shutdown room API be suitable for this? https://github.com/matrix-org/synapse/pull/2291

**Comment by allquixotic** [comment]
+1, Would like to see this added.

**Comment by richvdh** [comment]
It's not really what server ACLs do.

/admin/shutdown_room is probably the closest bet currently, though it's a bit of a sledgehammer against a nut.

**Comment by MurzNN** [comment]
For implement blacklisting of room at now we can use https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#delete-room-api for remove current room, and https://github.com/matrix-org/mjolnir tool for prevent new invites from this room to all local users.
