### ISSUE TITLE
Synapse launches even though certificate is expired, without any log message

### ISSUE THREAD

**Issue by MacLemon** [matrix-org/synapse#2394]
Summary:
When launching Synapse it fails to check that the configured certificate hasn't expired and will launch with the expired certificate. (Causing clients to just stall with a spinner upon trying to login.)

Steps to Reproduce:
Let the configured certificate for synapse expire. (Sometimes your Let's Encrypt automation fails…) Restart synapse.

Expected Results:
Synapse should either refuse to launch or at the very least, loudly complain in the logs that it is launching with an expired (or otherwise invalid) certificate which causes client to silently fail at logging in.

Actual Results:
Synapse just launches, ignoring the fact that clients won't be able to connect.

Regression:
n/a

Notes:
Synapse 0.22.1, FreeBSD 11.0p11 (though the OS is irrelevant to this issue.)

**Comment by richvdh** [comment]
I'm not really convinced it's synapse's job to check if a certificate is valid: most other software will happily use an expired certificate if you point it to one.

I also think this is less of an issue now that the recommended configuration for a production deployment is to use a reverse-proxy to terminate your TLS.

In short, I don't think this is a big problem.
