### ISSUE TITLE
Adding new users to default room

### ISSUE THREAD

**Issue by mne1991** [matrix-org/synapse#2398]
Hello,

Is is possible some how to add every new user to a specific room?

**Comment by prathik-kaliyambath** [comment]
Well this is just a vague idea that might be wrong, but you could forcefully call update_membership on activation of the route /register and pass in parameters accordingly so as to invite/join the user.

**Comment by aaronraimist** [comment]
You can do this by using the `auto_join_rooms` config option

```
# Users who register on this homeserver will automatically be joined
# to these rooms
auto_join_rooms:
    - "#example:example.com"
```

**Comment by jaywink** [comment]
As pointed out already, `auto_join_rooms` config option is there, so closing this.
