### ISSUE TITLE
m.room.power_levels cannot restrict m.room.aliases

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2402]
It seems as though the power level check doesn't restrict users from adding additional room aliases. Here's the room configuration used to test:

`m.room.power_levels`:
```
{
  "events_default": 0,
  "invite": 0,
  "state_default": 50,
  "redact": 50,
  "ban": 50,
  "users_default": 0,
  "events": {
    "m.room.avatar": 50,
    "m.room.name": 50,
    "m.room.canonical_alias": 50,
    "m.room.history_visibility": 100,
    "m.room.power_levels": 100,
    "m.room.aliases": 50
  },
  "kick": 50,
  "users": {
    "@travis:t2l.io": 100
  }
}
```

Room members:
* `@travis:t2l.io` - Myself (PL100)
* `@turt2live:matrix.org` - Myself (PL0 - Plain user)

After publishing the `m.room.power_levels` event above, the matrix.org user can still add aliases to the room.

**Comment by prathik-kaliyambath** [comment]
Hi,
I am interested in working on this. Can I have a little more clarity on what the expected behaviour should be? I am new to this. Thanks.

**Comment by turt2live** [comment]
This is actually working as intended, so closing. A proposal for altering how the room directory works is probably best.
