### ISSUE TITLE
Federation: SRV DNS record is ignored if it points to an IPv6 only (AAAA only) host

### ISSUE THREAD

**Issue by rvalles** [matrix-org/synapse#2405]
Despite having an SRV record pointing to the synapse server, trying to federate with matrix.org doesn't work.
I've been able to confirm it connects to the domain's IPv6 address as-is, ignoring the SRV record.
Synapse should honor the SRV record and connect to the host it points to, even if that host doesn't have an A record but an AAAA one.

**Comment by richvdh** [comment]
Fixed in #2462
