### ISSUE TITLE
Cannot join rooms over federation if they include redacted state events

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2406]
@roc:rvalles.net reported that they couldn't join #anime:matrix.org or #cats:matrix.org; looks like both rooms contain redacted state events which fail to pass signature checks (and then cause all the other state in the room to fail, seemingly?).  Logs at https://b.rvalles.net/unsorted/synapse_disaster.log and https://b.rvalles.net/unsorted/synapse_cats_context.log.  Convo at https://scalar-develop.riot.im/riot-web/#/room/#matrix:matrix.org/$15019628743131414mWBjf:matrix.org

**Comment by richvdh** [comment]
I think this has probably been fixed.
