### ISSUE TITLE
Registration of a new user fails

### ISSUE THREAD

**Issue by masscream** [matrix-org/synapse#2411]
Hello, trying to register an user but everytime I get this error, looks like there is something wrong with the certificate. I use the default self signed one.

```
(.synapse)[masscream@serverl .synapse]$ register_new_matrix_user -c homeserver.yaml https://localhost:8448         
New user localpart [masscream]: admin
Password: 
Confirm password: 
Make admin [no]: yes
Sending registration request...
Traceback (most recent call last):
  File "/home/masscream/.synapse/bin/register_new_matrix_user", line 174, in <module>
    register_new_user(args.user, args.password, args.server_url, secret, args.admin)
  File "/home/masscream/.synapse/bin/register_new_matrix_user", line 117, in register_new_user
    request_registration(user, password, server_location, shared_secret, bool(admin))
  File "/home/masscream/.synapse/bin/register_new_matrix_user", line 65, in request_registration
    f = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
```

Even when I put the hostname I use for web access into the server link  - https://localhost:8448 it does not work, but the server is running on localhost, please help.

**Comment by turt2live** [comment]
try `http://localhost:8008` for the URL instead (note the lack of https). This only really applies when using the command you're using.

**Comment by Yavathar** [comment]
Hi, I'm experiencing the same problem. One of my friend, too.
And, if I use a web browser with the link - https://localhost:8448 it shows an error message like "Secure Connection Failed".

If I try http://localhost:8008, it works. But, this is not a solution.
Do anyone have any idea why and how to solve it?

**Comment by masscream** [comment]
Actually, I did a workaround and registered my user through webGUI. So I have not even tried if it works with http localhost. If so, why could not that be a solution? I guess the most important thing is that it works, either way.
 
______________________________________________________________
 > Od: Yavathar <notifications@github.com>
 > Komu: matrix-org/synapse <synapse@noreply.github.com>
 > Datum: 27.09.2017 07:35
 > Předmět: Re: [matrix-org/synapse] Registration of a new user fails (#2411)
 >
Hi, I'm experiencing the same problem. One of my friend, too.
 And, if I use a web browser with the link - https://localhost:8448 <https://localhost:8448> it shows an error message like "Secure Connection Failed".
If I try http://localhost:8008 <http://localhost:8008>, it works. But, this is not a solution.
 Do anyone have any idea why and how to solve it?

**Comment by Yavathar** [comment]
Thanks for reply, masscream.
Because of security, https must work correctly.
Strange thing is that the issue is working correctly in Ubuntu. (I've just installed and tested again.)
And, I'm also sure that in a few days ago it worked correctly in my CentOS 7.

I think this issue needs to be solved.

**Comment by masscream** [comment]
Well of course it must, but I can access the account / server through https then without any problems.... The issue is only when registering.
 
______________________________________________________________
> Od: Yavathar <notifications@github.com>
> Komu: matrix-org/synapse <synapse@noreply.github.com>
> Datum: 27.09.2017 11:01
> Předmět: Re: [matrix-org/synapse] Registration of a new user fails (#2411)
>
Thanks for reply, masscream.
 Because of security, https must work correctly.
 Strange thing is that the issue is working correctly in Ubuntu. (I've just installed and tested again.)
 And, I'm also sure that in a few days ago it worked correctly in my CentOS 7.
I think this issue needs to be solved.

**Comment by guulyfox** [comment]
I also have the same problem. and I don't know how to fix it.
```
Sending registration request...
Traceback (most recent call last):
  File "/root/.synapse/bin/register_new_matrix_user", line 174, in <module>
    register_new_user(args.user, args.password, args.server_url, secret, args.admin)
  File "/root/.synapse/bin/register_new_matrix_user", line 117, in register_new_user
    request_registration(user, password, server_location, shared_secret, bool(admin))
  File "/root/.synapse/bin/register_new_matrix_user", line 65, in request_registration
    f = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
```

**Comment by richvdh** [comment]
I think `CERTIFICATE_VERIFY_FAILED` will only affect `register_new_matrix_user` on versions of python older than 2.7.9. The workaround is, as @turt2live says, to use the http url. 

Alternatively, set up synapse or a reverse-proxy with a valid SSL cert (note that the self-signed one generated by synapse is not suitable for the client port of a production installation).

Alternatively, use a newer version of python, in which case `register_new_matrix_user` will disable the check of the SSL cert.
