### ISSUE TITLE
Check that media repository times out correctly when downloading infinite media sources

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2414]
In theory we have a maximum file size limit when downloading, i /think/, but need to check that it's being upheld correctly for things like https://hookrace.net/time.gif

**Comment by ara4n** [comment]
This is particularly unpleasant if someone pastes a live HTTP stream into a room for obvious reasons.

**Comment by clokep** [comment]
I think #8302 ended up being a duplicate of this, which was fixed by #11784, hopefully.
