### ISSUE TITLE
Typo in table name

### ISSUE THREAD

**Issue by M1dgard** [matrix-org/synapse#2424]
There's a table called *users_in_**pubic**_room*.

---
Keywords to facilitate finding this issue: *pubic, spelling mistake, typo in relation name*

**Comment by richvdh** [comment]
yes there is. Fixing it is too much like hard work.

**Comment by ara4n** [comment]
is this not just a schema update to rename it and changing the queries which reference it?

**Comment by richvdh** [comment]
Yup

**Comment by ara4n** [comment]
in which case i'm reopening as:
 * it's an embarrassing screwup if not technically a bug which doesn't make us look good (cf https://social.wxcafe.net/users/wxcafe/updates/53817 etc)
 * it's not been fixed
 * tracking it as an open bug lets us:
   * gather info on the right fix
   * reduces chance of dups
   * lets someone in the community fix if we don't have bw

**Comment by ara4n** [comment]
hopefully fixed by https://github.com/matrix-org/synapse/pull/2643

**Comment by ara4n** [comment]
merged.
