### ISSUE TITLE
we really need a rageshake script for submitting synapse logs

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2427]

**Comment by reivilibre** [comment]
Possibly a nice-to-have, but hard because there might be PII that needs trimming out, the admins have to trust this mechanism and we seem to have done OK without it for the past 6 years — do we think we still want this?

**Comment by clokep** [comment]
I think we can close this -- we essentially use Sentry for tracking of errors in Synapse.

We depend on admins to let us know if they're seeing issues for privacy reasons, as @reivilibre said.
