### ISSUE TITLE
Clarify recommended setup

### ISSUE THREAD

**Issue by maxidor** [matrix-org/synapse#2438]
_EDIT as to provide guidance to new users - Matrix devs official answer [#1](https://github.com/matrix-org/synapse/issues/2438#issuecomment-327424711) and [#2](https://github.com/matrix-org/synapse/issues/2438#issuecomment-327425464)_

The self-signed certificate of synapse should NOT be replaced and port 8448 should only be used for federation (server traffic) and directly exposed publicly.
For clients connections, a reverse proxy should be reachable publicly with a regular certificate (e.g. Let's Encrypt) on port 443 that goes to the port 8008 of synapse.

**Public TCP 8448**: Servers, original generated self-signed certificate, directly exposing port TCP 8448 of synapse
**Public TCP 443**: Clients, regular certificate (e.g. Let's Encrypt), reversed proxy to port TCP 8008 of synapse

---

The community is currently discussing what is the official recommended setup for synapse in terms of ports and reverse proxying. Here are the three visions:
1. Use a regular (e.g. LTE) certificate on port 8448 and expose that for clients and servers, replacing the self-signed generated one.
2. Use a regular certificate on 443 reversed proxy to 8008 and same cert on 8448, replacing the self-signed generated one.
3. Use a regular certificate on 443 reversed proxy to 8008 and keep the self-signed generated one on 8448

My personal believe is to do go for 3) but it seems many users in the community for for 1) or 2), which I believe is due to misleading documentation for synapse.

Why I think 1) and 2) occurs due to misleading doc:
First mention of 8008 and 8448 is at [Configuring synapse](https://github.com/matrix-org/synapse/blob/c0c31656ff379c0a2ec54e6af450f12bb2f6c2fb/README.rst#configuring-synapse), last paragraph which gives the first misleading advise.
It says 8448 has a self-signed certificate which is fine to test with clients but should be replaced in production but also state that it's fine for Federation. So if you want to connect clients to 8448, you should put a proper certificate - yet doesn't instruct to connect clients to it outside of a testing scope.

The next bit comes with [Connecting to Synapse from a client](https://github.com/matrix-org/synapse/blob/c0c31656ff379c0a2ec54e6af450f12bb2f6c2fb/README.rst#connecting-to-synapse-from-a-client) which says again that the easiest way to try a synapse install is to connect to 8448 but totally ignores the fact it's a self-signed and will be a problem. So you're made to believe you should have changed the certificate.

Then we come to [Using a reverse proxy with Synapse](https://github.com/matrix-org/synapse/blob/c0c31656ff379c0a2ec54e6af450f12bb2f6c2fb/README.rst#using-a-reverse-proxy-with-synapse) which says it will work nicely with clients as you expose 443 and continues by saying clients and servers don't necessarily need to connect to the same port, says and shows a nginx config of 443->8008 for clients.

Finally, several generic points:
- Changing the certificate only matters for clients. Servers don't require anything specific.
- 8448 doesn't work out of the box for clients (due to self-signed) but does for federation
- 443 to a unencrypted 8xxx port is the typical setup with TLS offloading
- 8008 is enabled by default in the config. If 1) was intended, why not just keep 8448?
- if you use 443 for clients, you don't need to give the port when configuring, just put https://example.org - easy for users, easy for admins
- Reverse proxy 443 to 8448 with self-signed certificate might not work out of the box, so you would go for 8008 (and double TLS/SSL would not make much sense)
- synapse README never instructs or even recommends to use 8448 for clients in production, only for testing
- going for 2) means managing two configuration files and two copies of the same certs after each renewal
- The [Server-Server Spec](https://matrix.org/docs/spec/server_server/unstable.html#retrieving-server-keys) talks about caching results of looking up certificates and signing keys, which could cause downtime depending on homeservers implementation/configuiration?
---
**Could the Matrix devs please clearly state what is the recommended setup?**

**Comment by realitygaps** [comment]
https://matrix.org/docs/guides/lets-encrypt.html also seems to suggest putting LE on the synapse server directly is a correct approach

**Comment by ArchangeGabriel** [comment]
I do 3). Excerpt from my config:
```
listeners:
  -
    port: 8448
    bind_addresses:
      - '::'
    type: http
    tls: true
    x_forwarded: false
    resources:
      - names: [federation]
        compress: false

  - port: 8008
    tls: false
    bind_addresses: ['::1','127.0.0.1']
    type: http
    x_forwarded: true
    resources:
      - names: [client]
        compress: true
```

**Comment by turt2live** [comment]
I also use 3, with the difference being I reverse proxy 8448 to point to the federation_reader. It's reverse proxied to make it easier to switch targets more easily, if required.

**Comment by richvdh** [comment]
My recommendation for a "production" setup is option 3, as it means you can have a proper LetsEncrypt cert on port 443 without having to worry about updating the cert used by synapse when it expires (and how that interacts with other servers in the federation).

Certainly the README isn't clear in this respect. That's partly an artefact of the fact it tries to deal with a number of different scenarios, notably somebody trying to set up a "test" instance on a local machine, where having to mess about with reverse-proxies is somewhat overkill. I'm not sure what the best way to address the confusion would be; possibly the README should be broken up into separate documents on topics such as "setting up a local synapse for development/test purposes" and "setting up a production synapse with optional federation". Either way it could do with the attention of a proper technical author rather than the occasional half-hour to from a software dev trying to patch it up.

**Comment by richvdh** [comment]
> Changing the certificate only matters for clients. Servers don't require anything specific.

Yeeeees, but as you have also noted: 

> The Server-Server Spec talks about caching results of looking up certificates and signing keys, which could cause downtime depending on homeservers implementation/configuiration?

yes. Synapse is currently a bit lax in this respect (https://github.com/matrix-org/synapse/issues/1362), but you could easily find yourself with outages if you're not quite careful about how you replace your certificates for federation.

**Comment by aventrax** [comment]
I use the 3) option, and I agree, docs must be coherent..

**Comment by maxidor** [comment]
Also, `homeserver.yaml` talks about replacing the self-signed certificate. That should also be replaced with a proper indication that it should not be in production, only for testing.

```
# You can replace the self-signed certificate that synapse
# autogenerates on launch with your own SSL certificate + key pair
# if you like.  Any required intermediary certificates can be
# appended after the primary certificate in hierarchical order.
```

**Comment by richvdh** [comment]
hopefully improved as of #2468

**Comment by amanusk** [comment]
Could some one please clarify how to setup the reverse proxy using LetsEncrypt with apache?

Between this issue and the readme I am quite confused what goes where. 

I have setup a domain and a have a letsencrypt certificate setup with --apache.

Currently I have a file `/etc/apache2/sites-available/<myserver.com>-le-ssl.conf`

The content of the file is 
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
  ServerName <myserver.com>
  SSLCertificateFile /etc/letsencrypt/live/<myserver.com>/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/<myserver.com>/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf

  SSLProxyEngine On

  <Location /_matrix>
      ProxyPass http://localhost:8008
      ProxyPassReverse http://localhost:8008
  </Location>

</VirtualHost>
</IfModule>
```

configuration in `homeserver.yaml` (no other configuration was changed)
  - port: 8008
    tls: false
    bind_addresses: ['127.0.0.1']
    type: http

    x_forwarded: true

    resources:
      - names: [client, webclient]
        compress: true
      - names: [federation]
        compress: false
```

When trying to connect with `<myserver.com/_matrix>`  I get 

##No Such Resource
No such child resource.

**Comment by maxidor** [comment]
@amanusk In your apache config, amend as such:
```
  <Location /_matrix>
      ProxyPass http://localhost:8008/_matrix
      ProxyPassReverse http://localhost:8008/_matrix
  </Location>
```

**Comment by maxidor** [comment]
then it's fine. If you have more issue, you should open a dedicated issue or come in #matrix:matrix.org

**Comment by maxidor** [comment]
@richvdh FYI I keep seeing several people a week that still do it the wrong way, but I don't have good ideas on how to improve this further short of a full rewrite of the README. Any ideas on that front?

**Comment by ptman** [comment]
I think one very concrete improvement would be:

1. Finish dockerfile/image
2. Use said docker image in production (ideally on matrix.org), so that it's kept up to date and free of bugs
2. write docker-compose.yaml that sets up postgres, synapse, reverse proxy (nginx? traefik? caddy?), turn? This would show ports etc. quite clearly and would make it easy to fire up something to test with

**Comment by maxidor** [comment]
@ptman This is specifically for those NOT using docker images, so from source or distro packages

**Comment by ptman** [comment]
many elements remain: database, synapse, reverse proxy, with config that listens on different ports and proxies traffic to synapse appropriately

**Comment by ptman** [comment]
maybe just add the nginx/caddy configs then?

**Comment by amanusk** [comment]
Adding an apache2 example config when using Lets Encrypt to the README will definitely help

**Comment by richvdh** [comment]
please don't follow the upcloud tutorial, for this reason.

> so yes, indeed a common doc

The need for this is tracked at https://github.com/matrix-org/matrix.org/issues/206
