### ISSUE TITLE
Unexpected property in publicRooms response

### ISSUE THREAD

**Issue by poulad** [matrix-org/synapse#2445]
### Description

Based on [unstable version of API docs](https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-publicrooms), I see another JSON property (`new_rooms`) in response of `publicRooms` when paginating through rooms. where is the doc for it?

```json
{
  /*OtherProps*/
  "new_rooms": false
}
```

I started paginating through public rooms and that property was false, then created a new public room,  kept the same pagination going on to the next batch and property remains false.

### Steps to reproduce

- https://matrix.org/_matrix/client/r0/publicRooms?access_token=TOKEN
- _POST_ request body:

```json
{
	"limit": 1,
	"since": "next_batchTOKEN"
}
```

### Version information

HS: Matrix.org

**Comment by richvdh** [comment]
I don't think this is still an issue.
