### ISSUE TITLE
When i receive a call i have to enter security code to unlock the phone so i can answer the call

### ISSUE THREAD

**Issue by bassazz2007** [matrix-org/synapse#2446]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those here (please be careful to remove any personal or private data):

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
- **Version**:        What version of Synapse is running? 
- **Install method**: package manager/git clone/pip      
- **Platform**:       Tell us about the environment in which your homeserver is operating
                      - distro, hardware, if it's running in a vm/container, etc.

**Comment by turt2live** [comment]
Please file the issue against the appropriate repository (either https://github.com/vector-im/riot-ios or https://github.com/vector-im/riot-android). Additionally, please use the issue template provided.
