### ISSUE TITLE
High CPU usage after joining #matrix

### ISSUE THREAD

**Issue by aventrax** [matrix-org/synapse#2447]
I'm experiencing high cpu usage on my HS after joining large rooms. On the readme I saw the issue about the file handler limits so I increased the hard limit to 16384 but nothing changed. U fortunately leaving the room seems not to solve the issue, I have to stop synapse and import a homeserver.db saved before the room was joined. This seems the only way to recover.
My vps has a xeon 2.4GHz with 2GB of ram, I set the cache value to 0.3 but didn't help.
CPU 70-90%, ram 37%... can you help me? I have the last debian packages.

**Comment by dani** [comment]
I experienced this too, when using SQLite. Everything is OK with PostgreSQL. Joining large rooms still takes some time, but once done, CPU load goes down. 2GB of RAM might be a bit low, on my install, synapse can take ~1GB on its own when joining a few large rooms.

**Comment by aventrax** [comment]
ok, understood. Joining large rooms is not in my whish list. Anyway, shouldn't the cpu load going back low leaving theese rooms? Having to restore an old db looks like a bug somewhere... isn't it?

**Comment by dani** [comment]
Don't know if there's some timeout issue when using SQLite. But since I've switched to PostgreSQL, everything is OK (no more federation traffic once I left all federated rooms)

**Comment by maxidor** [comment]
#matrix is a very old room is a big burden for servers to join, don't expect it to be a 30 sec thing, it can last for a while (count 1h to be safe) after "joining in the client" which is only part of the actual join process in federation.

**Comment by aventrax** [comment]
Ok, I switched to PostgreSQL, anyway I'm keeping myself away from large rooms. Restoring an old db causes issues on my encrypted rooms that I was able to solve only loggin out/in the Riot clients.

**Comment by aventrax** [comment]
Closing this issue. Using PostgreSQL solved my issue.
