### ISSUE TITLE
Missing python-ujson dependency on Ubuntu 16.04 Xenial i386

### ISSUE THREAD

**Issue by abouvier** [matrix-org/synapse#2463]
When I try to install synapse on Ubuntu 16.04 Xenial i386, there is one missing dependency:
```
$ sudo apt install matrix-synapse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 matrix-synapse : Depends: python-ujson but it is not installable
E: Unable to correct problems, you have held broken packages.
```
And indeed, the python-ujson package for Xenial seems absent from https://matrix.org/packages/debian/pool/main/u/ujson/. Maybe because this package is included in the official repo of Ubuntu since Xenial. But it's apparently only available for amd64 architecture as indicated on this page: https://packages.ubuntu.com/fr/xenial/python-ujson. The Matrix repo should therefore provides python-ujson for i386 architecture on Xenial.

**Comment by hawkowl** [comment]
We don't use ujson anymore.
