### ISSUE TITLE
Reclaim room alias as home server admin

### ISSUE THREAD

**Issue by jooize** [matrix-org/synapse#2469]
Imagine a company wants to use the room alias #lounge:company.com, but it's taken by users. How do they remove the alias from the room they have no privileges in?

Possibly relevant:
https://github.com/matrix-org/synapse/issues/2360
https://github.com/matrix-org/synapse/issues/1682

**Comment by richvdh** [comment]
via [the API](https://matrix.org/docs/spec/client_server/r0.2.0.html#delete-matrix-client-r0-directory-room-roomalias), which will work provided you are a server admin on company.com
