### ISSUE TITLE
Can't import 'bcrypt' which is part of 'py-bcrypt' this issue happen on configuring my own matrix home server 

### ISSUE THREAD

**Issue by iruthaya** [matrix-org/synapse#2484]
Hi,

I'm trying to configure my own matrix home server  on EC2 Amazon Linux AMI and  it's have following packages 

1. Python 2.7.12
2. pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
3. bcrypt==3.1.3
4. py-bcrypt==0.4

when i execute  **Configuring synapse**   cmd

    python -m synapse.app.homeserver \
    --server-name mydomainname \
    --config-path homeserver.yaml \
    --generate-config \
    --report-stats=yes

below error throwing 

```
ERROR:root:Can't import 'bcrypt' which is part of 'py-bcrypt'
Traceback (most recent call last):
  File "/home/ec2-user/.synapse/local/lib/python2.7/dist-packages/synapse/python_dependencies.py", line 104, in check_requirements
    module = __import__(module_name)
ImportError: No module named bcrypt
Missing Requirement: Can't import 'bcrypt' which is part of 'py-bcrypt'
To install run:
    pip install --upgrade --force "py-bcrypt"
```

Even i tried the cmd **pip install --upgrade --force "py-bcrypt"**  same error throwing 

Can you please help on this?

Thanks & Regards,

Arun Iruthaya Thomas

**Comment by erikjohnston** [comment]
Odd. Version 0.23.0 (released a few hours ago) should be using the bcrypt module, rather py-bcrypt.

**Comment by iruthaya** [comment]
Hi erikjohnston,

Thanks for ur's immediate reply it's really helpful for me.

Now i'm facing new package dependency issue 

ERROR:root:Can't import 'msgpack' which is part of 'msgpack-python>=0.3.0'
Traceback (most recent call last):
  File "/home/ec2-user/.synapse/local/lib/python2.7/dist-packages/synapse/python_dependencies.py", line 105, in check_requirements
    module = __import__(module_name)
ImportError: No module named msgpack
Missing Requirement: Can't import 'msgpack' which is part of 'msgpack-python>=0.3.0'
To install run:
    pip install --upgrade --force "msgpack-python>=0.3.0"

but my VM have the **(msgpack-python==0.4.8)** package 

Can you please help on this?

Thanks & Regards,

Arun Iruthaya Thomas

**Comment by richvdh** [comment]
sounds like the original problem has been solved
