### ISSUE TITLE
Allow write-only access to a room

### ISSUE THREAD

**Issue by IngoHohmann** [matrix-org/synapse#2485]
I see many use-cases, where only sending into a room is needed:

- Monitoring systems
- IoT devices which ony send messages
- Web-Forms sending into Matrix
- ...

In the spirit of only giving the minimal set of rights, these accounts should only have write-acess, so if someone gets a hold of the used access_token, he will not be able to read messages.

This point is especially important for usage with web-forms.

**Comment by turt2live** [comment]
Set the power level to send messages to be 2.
Set the power level for new users to be 0 (default).
Set the power level of the accounts you want to be able to speak to 2 or higher.

**Comment by IngoHohmann** [comment]
This means normal users would be read-only, 
special users could read and write.

I want users who can send to not be able to read messages in the room.

**Comment by reivilibre** [comment]
This would need something to be specced up. But a workaround might be to use asymmetric crypto so that messages can only be decrypted by a certain client with the keys.
