### ISSUE TITLE
Lock down user account / access_token

### ISSUE THREAD

**Issue by IngoHohmann** [matrix-org/synapse#2486]
When monitoring system, IoT device is used with matrix, there is some possibility, that the access token gets stolen.

Now imagine a monitoring system of BigCorp. Someone getting access to the access_token, could join other rooms and try to impersonate an employee of BigCorp.

If user accounts / access_tokens could be locked down, so that they are not able to get access to other rooms / accept invitations, this would be much harder.

**Comment by reivilibre** [comment]
Synapse modules can do this. OIDC (coming 'soon') will also support more granular scoping of access tokens, so this may be reasonably doable without custom modules too.
