### ISSUE TITLE
CPU Affinity feature breaks Synapse on FreeBSD

### ISSUE THREAD

**Issue by feld** [matrix-org/synapse#2487]
# CPU Affinity breaks on FreeBSD

This feature introduced in commit 10d8b701a1fa585c5fc2d5edcea8d4d02ae360a4 does not work on FreeBSD as the python module required only supports Windows and Linux. We will have to patch out this entire feature/commit in order to package/deploy on FreeBSD. Can this somehow be made completely optional or just removed altogether? I feel there are better ways of handling this such as with systemd perhaps and maybe something also exists on Windows? On FreeBSD the easy solution right now would be to run the software in a jail and control the affinity settings of the jail itself.

Thanks for your consideration. Unfortunately all the world is not a Linux.

**Comment by ara4n** [comment]
doh, this was a thinko - we're on the case.

**Comment by erikjohnston** [comment]
Hmm, it obviously got missed that the python package would simply refuse to be imported on other platforms. The debian packaging has a couple of patches to make it optional, which should work on other systems:

https://github.com/matrix-org/package-synapse-debian/blob/debian/debian/patches/0007-Move-quit_with_error-to-_base.patch
https://github.com/matrix-org/package-synapse-debian/blob/debian/0.23.0-1/debian/patches/0008-Remove-affinity-package-requirement.patch

I'll try and get a hotfix for this out ASAP though

**Comment by ara4n** [comment]
reading the source, it looks like the `affinity` package installs for all platforms... and then only crashes if it's actually utilised on a platform that has no support via this package for CPU affinity.  Isn't the easiest solution just not to turn on the `affinity` option for platforms which don't support it?  (This is what i've been doing on OSX, hence not being bitten by this)

**Comment by erikjohnston** [comment]
Release v0.23.1 makes the dependency entirely optional: https://github.com/matrix-org/synapse/releases/tag/v0.23.1

**Comment by erikjohnston** [comment]
(Rereading the question I missed that it was a packaging rather than running-with-pip issue)
