### ISSUE TITLE
Cap federation transaction number of events

### ISSUE THREAD

**Issue by non-Jedi** [matrix-org/synapse#2496]
Currently transaction size is capped by time but not number of events. Capping number of events would help with things like @turt2live's current issues where t2bot.io is behind by 4 days and can't catch up because it takes too long to process each 20 minute transaction.

**Comment by turt2live** [comment]
Anecdotally this is one of the issues, it seems. I don't know if it is batched by time, but it sure seems like it.

**Comment by turt2live** [comment]
This happened, although I still am not convinced that it has actually solved the problem.
