### ISSUE TITLE
Missing dependency on configure home server

### ISSUE THREAD

**Issue by iruthaya** [matrix-org/synapse#2499]
Hi,

I'm trying to configure my own matrix home server on EC2 Amazon Linux AMI and it's have following packages

   
    1. Python 2.7.12
    2. pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
    3. jsonschema==2.6.0
    4. frozendict==1.2
    5. unpaddedbase64==1.1.0
    6. canonicaljson==1.0.0
    7. signedjson==1.0.0
    8. pymacaroons-pynacl==0.9.3
    9. Twisted==17.9.0
    10. pyOpenSSL==17.3.0
    11. pyasn1==0.1.7
    12.pyasn1-modules==0.1.4
    13. bcrypt==3.1.3
    14. msgpack-python==0.4.8
    And some other packages are also installed in VM

 HomeServer version **0.23.0 and 0.23.1** i had checked both version same issue happened  

 When i execute Configuring synapse cmd

```
 python -m synapse.app.homeserver \
--server-name mydomainname \
--config-path homeserver.yaml \
--generate-config \
--report-stats=yes
```
I am constantly getting the following error

```
ERROR:root:Can't import 'msgpack' which is part of 'msgpack-python>=0.3.0'
Traceback (most recent call last):
  File "/home/ec2-user/.synapse/local/lib/python2.7/dist-packages/synapse/python_dependencies.py", line 107, in check_requirements
    module = __import__(module_name)
ImportError: No module named msgpack
Missing Requirement: Can't import 'msgpack' which is part of 'msgpack-python>=0.3.0'
To install run:
    pip install --upgrade --force "msgpack-python>=0.3.0"
```

Even after installing all the packages in my system.

I tried it by removing the entries one by one in python_dependencies.py  But still I am getting error other than the one I have removed. My sense says that it could be some config / env setting. 

Could anyone please guide me on that.

Thanks & Regards,

Arun Iruthaya Thomas

**Comment by richvdh** [comment]
didn't read the issue template
