### ISSUE TITLE
whatever got deployed on Sept 26 caused synchrotron DB usage to quadruple

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2510]
looks to be a presence fix, which looks to have made synchrotron DB usage get way worse per-block and per-request, and potentially coincides with the resurgence of bug #1981/#2505

**Comment by ara4n** [comment]
<img width="872" alt="screen shot 2017-10-08 at 16 30 18" src="https://user-images.githubusercontent.com/1294269/31318346-8978942c-ac48-11e7-9160-fc6c4f07099f.png">

**Comment by richvdh** [comment]
not a useful issue any more
