### ISSUE TITLE
Purge Remote Media API don't delete anything on Synapse with large remote media content 

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2511]
I have Synapse 0.23.1 homeserver that store many Remote Media files and I want to clean up them.

I try to use [Purge Remote Media API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst) with fresh timestamp (current time in unix timestamp), but result of the command is `"deleted": 0`.

After executing command I see nothing changed: size of `remote_content` folder is same, and `remote_media_cache` database table contains same records with older timestamps. Also no changes in `local_media_repository_url_cache` table.

**Comment by turt2live** [comment]
Just to confirm, was the timestamp given to the API in seconds or milliseconds? It needs to be in milliseconds according to the docs.

(I screwed this up an embarrassing number of times myself, which is why I ask)

**Comment by MurzNN** [comment]
Ow, sorry, I missed that it must be in milliseconds, now works well:
```
{
    "deleted": 271
}
```
And `remote_content` & `remote_thumbnail` folders cleaned up successfully.
But `url_cache` and `url_cache_thumbnails` keep size, seems it not touched via Purge Remote Media API.
