### ISSUE TITLE
Custom Sever Not Running

### ISSUE THREAD

**Issue by expertalex** [matrix-org/synapse#2512]
Hello! I follow this instructions https://www.upcloud.com/support/install-matrix-synapse/ to instant all matrix in my server but it isn't working.

The server is running:
(.synapse) root@Matrix:~/.synapse$ synctl start
synapse.app.homeserver already running

**But: https://<my.domain.name>:8448 didn't work!**

I added the DNS A record to  map <my-ip> to <my.domain.name>

I also correctly added server_name: "<my.domain.name>"

Where is the problem?
Thanks in advance.

**Comment by turt2live** [comment]
You may get more assistance in `#matrix:matrix.org`, but some common things to check for would be:

* Is the port open?
* Is the DNS record pointing to the correct IP?
* Is the server actually running? (try checking the logs to see if it is running)

Although, as I said, `#matrix:matrix.org` has a larger community and would be able to help more.

**Comment by expertalex** [comment]
- The ports are open: 
sudo netstat -tulpn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1868/sshd       
tcp        0      0 0.0.0.0:8448            0.0.0.0:*               LISTEN      8444/python2.7  
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      8444/python2.7  
tcp        0      0 127.0.0.1:29131         0.0.0.0:*               LISTEN      3900/mdsd       
tcp6       0      0 :::22                   :::*                    LISTEN      1868/sshd       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1165/dhclient   

- The DNS A record point to the correct IP address.

- synctl start
synapse.app.homeserver already running
