### ISSUE TITLE
Admin API for purge Synapse url_cache and local_thumbnails storage

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2513]
Synapse have useful [Purge Remote Media API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst) that clean ups `remote_content` and `remote_thumbnail` folders. 
But Synapse `media` storage have another folders that we can cleanup:
- url_cache
- url_cache_thumbnails
- local_thumbnails

Will be good to extend [Purge Remote Media API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst) or provide separate admin API for cleaning up those folders too.

Also will be good to have separate hard option for clearing too old `local_content` too.

**Comment by erikjohnston** [comment]
On develop the url cache should be automatically cleaned up after a couple of days, so manual intervention on that front shouldn't be necessary. This should be included in the next release.

**Comment by Happyfeet01** [comment]
Is it possible to cleanup the folder local_content? My folder is 998 GB big.
