### ISSUE TITLE
<user id> should be removed from /admin/users/<user id> and /admin/users_paginate/<user id>

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2522]
The user ID is only used to verify the server. However, the server and user ID are both discarded immediately so the route can return a full list of users local to the homeserver.

What is the intention of the user ID parameter?

**Comment by richvdh** [comment]
my question exactly: https://github.com/matrix-org/synapse/pull/1784/files/2849d3f29ddedaf35b0e080b02a40f8613fdba90#diff-024d1249ecb0742809d195f50ce4ec77

I kinda wish that #1784 hadn't been merged in its half-finished state. OTOH it did land some useful functionality.

**Comment by richvdh** [comment]
outdated now that #5925 has landed
