### ISSUE TITLE
A room suddenly completely blocked

### ISSUE THREAD

**Issue by floviolleau** [matrix-org/synapse#2534]
### Description

I use my own homeserver.

That happens suddenly with no reasons. Just one day stopped to work.

Other rooms works well except this one. I'm the single admin of that room and I don't know what happens but my room is suddenly totally blocked. No members can join, no current members can write a message in it, I'm unable to write a message, neither change settings of that room.

I can see the last lines of that room but if I want to scroll up in the history, previous upper messages never came.

This is my main room and I checked in the sqlite database. All are in it regarding that room id and I did not saw something special. Nothing is deleted inside the db and I can see event with messages.

Unfortunately I do not have any backup of my DB before that problem.

Who can help me?

### Steps to reproduce

- nothing special

The only relevent error I have in the JS console of riot web is:

```
uncaught exception: M_FORBIDDEN: User @my_user:my.domain.org not in room !MbooMjhEmxOVTWSrdC:my.domain.org (None)
```

**But @my_user:my.domain.org is in the room...**

**Room spec**: 7 users / 1 invite / lots of messages / 2 aliases

### Version information

- **Homeserver**: my homeserver

If not matrix.org:
- **Version**:        Synapse version 0.22.1 
- **Install method**: pip      
- **Platform**: raspbian, raspberry pi, inside python vhost
- **Database schema version number**: V43

**Comment by richvdh** [comment]
Are you sure? Did you clear the cache on your client?

**Comment by floviolleau** [comment]
I have the exact same issue with the mobile app...

**Comment by richvdh** [comment]
yes, but are you sure you are still a member? did you clear the caches?

**Comment by floviolleau** [comment]
How can I check that I'm still a member ?

And yes caches has been cleared.

Thanks for your help :-)

**Comment by richvdh** [comment]
does the room still appear on your clients after you clear the caches?

**Comment by floviolleau** [comment]
Yes. But maybe I did not cleared all caches. Do you have guidelines ?

**Comment by floviolleau** [comment]
Hi,

I just saw that I faced to same problem on a bridge room with that log in addition:
```
Uncaught exception: M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
```

But this log message is very strange...

**Comment by floviolleau** [comment]
Related to #2347?

**Comment by richvdh** [comment]
> Yes. But maybe I did not cleared all caches. Do you have guidelines ?

second button from the bottom in settings in riot-web: 

![image](https://user-images.githubusercontent.com/1389908/31659261-6dcda016-b32b-11e7-8fb9-6d0b7e970f43.png)

> Guest access not allowed

This is probably a [red herring](https://en.wikipedia.org/wiki/Red_herring).

**Comment by floviolleau** [comment]
Okey I did it and it did not changed anything... :-{

**Comment by saintger** [comment]
Can you for instance change the room name ?
If not what is the error message logged on your homeserver (/var/log/syslog).

**Comment by richvdh** [comment]
It sounds like synapse has got comprehensively confused about the state of the room. :/

At this point, the most likely workaround is probably going to be creating a new room.

**Comment by saintger** [comment]
I perhaps got into a similar situation just after the last iOS/Android app update:
https://github.com/matrix-org/synapse/issues/2555

We can delete the room (except of course that there is currently no clean way to delete a room with all associated attachments) but it's a shame to lose all the history.
And of course it would be good to know what happened in order to avoid such a situation for the next app update...

**Comment by floviolleau** [comment]
Yes and I do not want to lose all history. This is a very old room...

But what is strange is that all events with content message are in the database...

**Comment by saintger** [comment]
@floviolleau Can you try to change the room name to see if you got the same problem as me ?
If you got an error, can you check the /var/log/syslog on your homeserver ?

**Comment by floviolleau** [comment]
Hi @saintger,

I cannot change the room name and I have this error:

M_UNKNOWN: Room 'blablabla.org' does not exist

![image](https://user-images.githubusercontent.com/5442973/32219905-0a9935d6-be30-11e7-9a5f-281b559b5b29.png)

**Comment by saintger** [comment]
@floviolleau And what are the error messages on your homeserver ? In /var/log/syslog

**Comment by richvdh** [comment]
without logs, I don't think there's much we can do with this

**Comment by floviolleau** [comment]
Hi,

Problem has been solved recently with a new update from riot sdk I think.

I can access it now.

Thanks
