### ISSUE TITLE
Update synapse to work with python 3

### ISSUE THREAD

**Issue by martmists** [matrix-org/synapse#2537]

**Comment by turt2live** [comment]
See https://github.com/matrix-org/synapse/issues/1149 for some discussion on this.

**Comment by 4nd3r** [comment]
also [dendrite](https://github.com/matrix-org/dendrite)

**Comment by ChrisFernandez** [comment]
yeah is 2017 reason I stay away from python is the silly way its developers stick with 2.x even after more than 5 years of python3 release.. ruby and other libs have not that issue.. not in 5 years. is normal to have 1 year but not 5.. to have to install "extra" python libs etc in distros that have python3 by default is a pain for everyone, for distro manteiners and for users.

**Comment by ara4n** [comment]
sorry; we have no plans to port synapse to python3; all our work is going into dendrite. dup #1149

**Comment by martmists** [comment]
If I update everything to work in Python 3 and made a PR, will it get merged or is this repository unmaintained in it's current state?

**Comment by ara4n** [comment]
A PR to make everything work in Python 3 (including all the dependent bits of Twisted) would absolutely get merged; Python 3 should bring some major performance improvements.  It's just that the core team itself is currently focused on dendrite for landing performance or maintainability improvements.

**Comment by ChrisFernandez** [comment]
@ara4n that makes sense, I can't wait enought for dendrite!  the rant from above is not aim at this proyect  is in general I help with BlackArch and other linux distros and is annoying that still so long after release and the time announced before there are still not a few, but a LOT of mayor proyects that only work on python2.x so you can see how it can bother some of us having to maintain 2 diff builds and 2 QA and packages etc..  in any case I love matrix <3
