### ISSUE TITLE
Thumbnails aspect ratios have broken since https://github.com/matrix-org/synapse/pull/2538

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2548]
@krombel and others are reporting mangled thumbnails since upgrading to a synapse since the media repo changes landed.

**Comment by krombel** [comment]
I think the issue got introduced in [this commit](https://github.com/matrix-org/synapse/commit/0e28281a021101ac199cbf2d0d130190110921bb)
I found a fix (at least the modified code leads to good thumbnails in my test :sunglasses:) and will PR it in a few moments

**Comment by turt2live** [comment]
I've upgraded my server to include that PR and the thumbnails are still awkward.

**Comment by turt2live** [comment]
I thought it was still an issue, but it turns out pip didn't download the right version of develop for some reason.

Updating a couple times cleared the cache and got a working version. Can confirm the OP is now fixed.

**Comment by richvdh** [comment]
apparently fixed
