### ISSUE TITLE
Empty bind ignores IPv6

### ISSUE THREAD

**Issue by pludi** [matrix-org/synapse#2556]
### Description

Empty bind address for federation does not bind to all interfaces

### Steps to reproduce

- Server has both IPv4 and IPv6
- Set the `bind` parameter for the federation port in `homeserver.yaml` to the empty string
- Try to connect to the federation port via IPv6, or use the Federation Tester

Although with an empty `bind` one would expect Synapse to bind on all interfaces, it only binds on all IPv4 interfaces.

### Version information

- **Homeserver**: Self hosted

If not matrix.org:
- **Version**: 0.23.1
- **Install method**: apt Package
- **Platform**: vServer with Debian 8 x86_64, with nginx 1.6.2 as reverse proxy on the client port

### Triage
Duplicate the port configuration for each IPv4 _and_ IPv6 address you want the service to listen on.

**Comment by pludi** [comment]
Still happens with 0.25.1

**Comment by monkz** [comment]
My workaround is to duplicate the listener and using '0.0.0.0' for one and '::' for the other

**Comment by monkz** [comment]
Workaround for me was to use bind_address: '::'.
I've checked with curl. Synapse now serves on both address families.
