### ISSUE TITLE
Keeping track of integrations/bridges

### ISSUE THREAD

**Issue by madduck** [matrix-org/synapse#2571]
This morning, the slack bridge on vector.im went down and then up and then down again for service. All this happened without the knowledge of anyone in our team, until we had finally established that two important messages weren't sent across the bridge.

It's not hard to imagine that it'll be hard to keep track of bridges/integrations in a federated system, but I think it would be a huge win for everyone to be able to do some of the following:

- [ ] maintain status information on integrations, such that clients like Riot can alert room members of the absence of a bridge. For instance, there could be a simple ping-pong base buzz between a bridge and its homeserver, or several homeservers
- [ ] a bridge/protocol-specific way to determine whether the other side is still online. Maybe there's e.g. a slack command like ping that could be sent over the bridge to achieve much the same as the first point, except for when the bridge is up and e.g. slack down. With IRC, this could be a `CTCP` command, etc.
- [ ] replay traffic in a room to the bridge when it comes back
- [ ] replay traffic from the other side of the bridge to the room(s) when it comes back, if this is possible (i.e. not possible with IRC unless there's a buffering bouncer in between already

I've filed this issue to keep track of this idea and to collect thoughts. Hope that's okay.

**Comment by richvdh** [comment]
I think it's unlikely we'll pursue this within Synapse. I know that the bridges teams have many plans for smoother integration.
