### ISSUE TITLE
Dependency ndg-httpsclient does not work with the Vanilla Python, it Requires the PyPy

### ISSUE THREAD

**Issue by martinvahi** [matrix-org/synapse#2580]
It fails to work with pip and requires pip3. 

    ----citation--start----------------------------------------------
    matrix_org_runner@acstorage3334:/home $ pip install  --upgrade ndg-httpsclient
    Collecting ndg-httpsclient
      Using cached ndg_httpsclient-0.4.3-py2-none-any.whl
    Collecting PyOpenSSL (from ndg-httpsclient)
      Using cached pyOpenSSL-17.3.0-py2.py3-none-any.whl
    Collecting pyasn1>=0.1.1 (from ndg-httpsclient)
      Using cached pyasn1-0.3.7-py2.py3-none-any.whl
    Collecting cryptography>=1.9 (from PyOpenSSL->ndg-httpsclient)
      Using cached cryptography-2.1.2.tar.gz
        Complete output from command python setup.py egg_info:
        error in cryptography setup command: Invalid environment marker: python_version < '3'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IVkAti/cryptography/
    matrix_org_runner@acstorage3334:/home $
    ----citation--end------------------------------------------------

The symptoms:

    ----citation--start----------------------------------------------
    matrix_org_runner@acstorage3334:/home $  pip3 install --upgrade ndg-httpsclient
    Downloading/unpacking ndg-httpsclient
      Downloading ndg_httpsclient-0.4.3-py3-none-any.whl
    Downloading/unpacking PyOpenSSL from https://pypi.python.org/packages/24/37/89bf12e53f1d27e8b2c8e5f8f9c7a958a3905f6916a9294a57a9d83fa165/pyOpenSSL-17.3.0-py2.py3-none-any.whl#md5=4217027ddfa4182d7f3b425d0b5eac92 (from ndg-httpsclient)
      Downloading pyOpenSSL-17.3.0-py2.py3-none-any.whl (51kB): 51kB downloaded
    Downloading/unpacking pyasn1>=0.1.1 (from ndg-httpsclient)
      Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB): 63kB downloaded
    Downloading/unpacking cryptography>=1.9 (from PyOpenSSL->ndg-httpsclient)
      Downloading cryptography-2.1.2.tar.gz (441kB): 441kB downloaded
      Running setup.py (path:/tmp/pip-build-g5q5nlr1/cryptography/setup.py) egg_info for package cryptography
        error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
        Complete output from command python setup.py egg_info:
        error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
    
    ----------------------------------------
    Cleaning up...
    Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-g5q5nlr1/cryptography
    Storing debug log for failure in /home/matrix_org_runner/.pip/pip.log
    matrix_org_runner@acstorage3334:/home $ uname -a
    Linux acstorage3334 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
    matrix_org_runner@acstorage3334:/home $ echo $PYTHONUSERBASE
    /home/matrix_org_runner/.mmmv/mmmv_python_pip_storage
    matrix_org_runner@acstorage3334:/home $ echo $PYTHONNOUSERSITE
    /home/matrix_org_runner/.mmmv/mmmv_python_pip_storage
    matrix_org_runner@acstorage3334:/home $
    ----citation--end------------------------------------------------

Hardware: Raspberry Pi 3
Operating system: Raspbian

**Comment by hawkowl** [comment]
This means you need a newer setuptools/pip.
