### ISSUE TITLE
Receiving a lot of unwanted messages, crashing server 

### ISSUE THREAD

**Issue by nioc** [matrix-org/synapse#2583]
### Description

Hello, I tried to join #matrix:matrix.org, but after a long wait it failed.
My problem is, since this moment, I received a lot of messages like this:
````
2017-10-26 18:33:30,267 - synapse.federation.federation_base - 142 - WARNING - PUT-248- Event content has been tampered, redacting $148134001650544ciZgq:matrix.org: 
{
   'origin':'matrix.org',
   'signatures':{
      'matrix.org':{
         'ed25519:auto':'xxx'
      }
   },
   'origin_server_ts':1481340016904   L,
   'sender':'@taursil:matrix.org',
   'event_id':'$148134001650544ciZgq:matrix.org',
   'prev_events':[
      [
         '$148133993850389UFTEZ:matrix.org',
         {
            'sha256':'xxx'
         }
      ]
   ],
   'membership':'join',
   'state_key':'@taursil:matrix.org',
   'unsigned':{
      'age':27695593283      L,
      'replaces_state':'$148133993850389UFTEZ:matrix.org',
      'redacted_by':'$148134018050890eePhV:matrix.org'
   },
   'content':{
      'membership':'join'
   },
   'depth':210884,
   'prev_state':[

   ],
   'room_id':'!cURbafjkfsMDVwdRDQ:matrix.org',
   'auth_events':[
      [
         '$1476538353540jxYua:jki.re',
         {
            'sha256':'xxx'
         }
      ],
      [
         '$1416420717069yeQaw:matrix.org',
         {
            'sha256':'xxx'
         }
      ],
      [
         '$1416420758924gcmew:jki.re',
         {
            'sha256':'xxx'
         }
      ]
   ],
   'hashes':{
      'sha256':'xxx'
   },
   'type':'m.room.member'
}
````
And after a few minutes, CPU is 100%, free memory disappears, disk IOs x 40 :cry: 

### Steps to reproduce

- Try to join a big room
- Wait
- See your server falling

### Version information

- **Homeserver**: Own

If not matrix.org:
- **Version**:        Synapse/0.24.1
- **Install method**: pip
- **Platform**:       Raspbian Stretch (4.9.41 ARM7) on raspberrypi 2

**Comment by turt2live** [comment]
A raspberry pi is almost certainly not going to be able to deal with the load of #matrix:matrix.org in a timely fashion. The requirements of that room are enormous.

The tampered content warnings aren't all that unexpected though.

**Comment by nioc** [comment]
Ok, but is it possible to "unsuscribe" from the room's eventsb(using API or whatever)?
Synapse without federation (few local users) was working great despite the low hardware of raspberry :smile

**Comment by maxidor** [comment]
> Ok, but is it possible to "unsuscribe" from the room's events (using API or whatever)?

Leave the room with all your local users that joined it

**Comment by geromueller** [comment]
This is clearly a bug, either in synapse or in the matrix. It's eating more than 2GB...

**Comment by richvdh** [comment]
yup synapse is a memory hog, and joining big rooms is expensive.
