### ISSUE TITLE
Setting url_preview_enabled: True causes server connectivity issues

### ISSUE THREAD

**Issue by waveyuk** [matrix-org/synapse#2590]
Hi all.
I've seen a similar thread in these boards relating to issues with setting url_preview_enabled: True causing my Matrix homeserver to lose connectivity.  Unfortunately those threads offered no resolution, so I am guessing that the posters had their issues resolved.
Does anyone know what I am doing wrong to cause the server to effectively die by turning this option on? I'd really like to have URL previews working.
Any help greatly appreciated.
Dave

**Comment by ara4n** [comment]
hopefully resolved in #883 (and README is updated on develop)
