### ISSUE TITLE
Empty key in JSON return of the whois endpoint(API)

### ISSUE THREAD

**Issue by aminhusni** [matrix-org/synapse#2600]
Empty key in JSON return of the whois endpoint(API).

`/_matrix/client/r0/admin/whois/{userId}`

Example return:

```
   {
  "user_id": "something_name",
  "devices": {
    "": {
      "sessions": [
        {
          "connections": [
            {
              "ip": "225.225.225.225",
              "user_agent": "something",
              "last_seen": 1504266816737
            }
        }
      ]
    }
  }
}
```

One of the json key is an empty string "". I can't parse the json properly with that empty "" in there. Perhaps it would help if it put "Unknown" or something as device name. Anyway, I don't think device name is also working in the main code of Matrix-Synapse since I have multiple devices using RIOT.im and everything is lumped into a single "" device. 

Issue reference:
https://stackoverflow.com/questions/46985605/how-do-i-call-an-object-property-with-empty-property-name

**Comment by richvdh** [comment]
This is perfectly valid JSON, and looks like expected behaviour if you have a device with an empty ID.
