### ISSUE TITLE
Please close this issue. I do not want to be further associated with it.

### ISSUE THREAD

**Issue by maxidor** [matrix-org/synapse#2603]
*Retired*

**Comment by jevolk** [comment]
### Federation event format returns a client event format
Specification: [5.2 POST /_matrix/client/r0/user/{userId}/filter](https://matrix.org/docs/spec/client_server/r0.2.0.html#post-matrix-client-r0-user-userid-filter)

> event_format | enum
The format to use for events. 'client' will return the events in a format suitable for clients. 'federation' will return the raw event as receieved over federation. The default is 'client'. One of: ["client", "federation"]

Implementation: [rest/client/v2_alpha/sync.py#L333](https://github.com/matrix-org/synapse/blob/master/synapse/rest/client/v2_alpha/sync.py#L333)
```
  def serialize(event):
            # TODO(mjark): Respect formatting requirements in the filter.
            return serialize_event(
                event, time_now, token_id=token_id,
                event_format=format_event_for_client_v2_without_room_id,
                only_event_fields=only_fields,
            )
```

**Comment by her001** [comment]
#2349 also describes a spec violation.

> room_id missing from response body for rooms/{roomId}/join endpoint

This is client-server and present in both stable and unstable. I have an open PR to fix it.

**Comment by maxidor** [comment]
@her001 Thank you, added to the list

**Comment by jplatte** [comment]
#2349 was fixed in #2986, with the fix being released in v0.27.3. Maybe you should convert the list to a [task list](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) so you can tick it off :)

**Comment by maxidor** [comment]
@jplatte thank you for bringing it up. Sadly I don't have time to keep this up-to-date, so I'll close it as it's outdated on several issues and new ones are not listed.

**Comment by ara4n** [comment]
reopening as it's useful for us to track, even if bits are stale.

**Comment by uhoreg** [comment]
ma1uta has also started a list at https://github.com/ma1uta/jeon/blob/master/SpecDiff.md

**Comment by Half-Shot** [comment]
Given we have lost the content forever, I guess this can be closed now? :(

**Comment by ara4n** [comment]
The other content in the comments is still useful, as was the original post, which I'm hoping @maxidor will restore rather than being obstructive.

**Comment by turt2live** [comment]
Here's all the references I could find:
* https://github.com/matrix-org/synapse/issues/3162
* https://github.com/matrix-org/synapse/issues/2986
* https://github.com/matrix-org/synapse/issues/2644
* https://github.com/matrix-org/synapse/issues/2604
* https://github.com/matrix-org/synapse/issues/2602
* https://github.com/matrix-org/synapse/issues/2349

**Comment by turt2live** [comment]
References from matrix-doc:
* https://github.com/matrix-org/matrix-doc/issues/1052
* https://github.com/matrix-org/matrix-doc/issues/1045

**Comment by maxidor** [comment]
Could you **please** make another issue and close this one? People keep contacting me about it and I'm really not interested in further discussing this.

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/3506 - thanks for recording the original list @maxidor.
