### ISSUE TITLE
 Synapse version displays incorrectly through web API. 

### ISSUE THREAD

**Issue by PC-Admin** [matrix-org/synapse#2614]
dpkg says it's version 24.1-1

web API says it's version 23.1: https://perthchat.org/_matrix/federation/v1/version

100% sure dpkg is correct and the API is wrong. Does anyone know why this is happening?

**Comment by turt2live** [comment]
Does restarting synapse fix the issue?

**Comment by PC-Admin** [comment]
Yes that worked!
