### ISSUE TITLE
Ability to 100% disable all federation for a synapse

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2619]
So far we've recommended people who want a non-federated synapse to disable inbound federation by removing the federation listener.  However, in practice it seems that the synapse may will emit outbound federated traffic (e.g. for invites) which will never complete.  Having a config option to cleanly and completely disable federation seems like a no-brainer.  I thought we already had an ancient 2014-vintage bug for this, but can't find it anywhere.

**Comment by bennabiy** [comment]
+1

**Comment by Half-Shot** [comment]
Is this fixed by #2820 @ara4n ?

**Comment by ara4n** [comment]
why yes it is :)

**Comment by kcsrnd** [comment]
What is the procedure, please?

**Comment by krombel** [comment]
@kcsrnd Have you read [my comment](https://github.com/matrix-org/synapse/pull/2820#issuecomment-378206517) on issue #2820?
In short: add `federation_domain_whitelist: <yourServerName>` to your config.
And remove your federation listener

**Comment by kcsrnd** [comment]
I thought I had, somehow I missed your comment at the bottom.  Got it now.  Thanks.

**Comment by oliverjanik** [comment]
Is there a Guide how to setup a separate isolated federation cluster?

**Comment by krombel** [comment]
As of #2820 you can put the following in your config:
```
federation_domain_whitelist:
- chat1.example.com
- chat2.example.com
- <otherServerName>
```
