### ISSUE TITLE
Postgres DB growing...

### ISSUE THREAD

**Issue by aventrax** [matrix-org/synapse#2640]
Hello, once I switched to postgres, the size of /var/lib/postgresql is growing day by day.
I'm using my federated synapse server with 3 users and only 1 (myself) is using rooms but just one, not so busy. All the other traffic is private user2user, but just text (no images or media).
In 2 months my DB is 2.5GB, that's huge for me and it is exausting my VPS free space.

Here a details for my tables used space: https://hastebin.com/eyafomoxox.cs

790MB of public.state_groups_state only.

How can I free up space? I tried vacuuming that table but I gain 3 MB only.
Can you help me? I found  various scripts to purge old rooms and so on, but I'm searching something to simply  purging anything older than 2 months, without having to specify rooms ID or something.
I don't want to waste all that space...

Thanks for your help!

**Comment by richvdh** [comment]
didn't read the issue template

**Comment by rubo77** [comment]
You can use the purge_history api.

I created a script, that pruges multiple rooms: https://gist.github.com/rubo77/5305b76a3805e1b6524ff8e5d5c3d15f

you can adapt it to purge all rooms easily.

note, that freeing space after deleting stuff only gets really freea fter a full vacuum in postgres:

    VACUUM FULL;
