### ISSUE TITLE
rooms table can end up somehow with duplicate rooms

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2642]
Just spent a bunch of time debugging gruenhage.xyz which had somehow ended up with duplicate rows in its `rooms` table:

```
gruenhagesynapse=# select * from rooms where room_id in (select room_id from rooms group by room_id having count(*)>1);                                                                      
               room_id               | is_public |           creator                                                                                                                         
-------------------------------------+-----------+------------------------------
 !TbeWbsZoHbbpjAbNCQ:matrix.org      | f         | 
 !MhJgddNhalZCKBgDvw:matrix.org      | f         | 
 !nGpMxXmMYzyWgoeQPm:matrix.org      | f         | 
 !nGpMxXmMYzyWgoeQPm:matrix.org      | f         | 
 !SkqhNHcGUMzKNUNSKE:matrix.org      | f         | 
 !UcYsUzyxTGDxLBEvLz:matrix.org      | f         | 
 !UcYsUzyxTGDxLBEvLz:matrix.org      | f         | 
 !UcYsUzyxTGDxLBEvLz:matrix.org      | f         | 
 !UcYsUzyxTGDxLBEvLz:matrix.org      | f         | 
```

This should be impossible given the unique pkey constraint:

```
gruenhagesynapse=# \d rooms                                                                                                                                                                  
      Table "public.rooms"                                                                                                                                                                   
  Column   |  Type   | Modifiers 
-----------+---------+-----------
 room_id   | text    | not null
 is_public | boolean | 
 creator   | text    | 
Indexes:
    "rooms_pkey" PRIMARY KEY, btree (room_id)
    "public_room_index" btree (is_public)
```

I don't understand how this could ever happen.  The only explanation I have is:

> postgres of course wouldn't launch, so I went back to 9.6, but accidentally selected the alpine version instead of the debian version, which broke everything. After going back to the right version (9.6 debian) most stuff went back to being fine, but some rooms broke after that

For now I've tried to fix it with the rather minging:

> keep running
> `delete from rooms where ctid in (select min(ctid) from rooms group by room_id having count(*)>1);`
> until you get `DELETE 0` as the response
> (it's just deleting the oldest duplicates until there are only the newest ones left)

But I'd love to know how it's possible for postgres to get into this mess :-/

**Comment by ara4n** [comment]
answer: if you run postgres for Alpine against the datadir of postgres for Debian, terrible things happen and postgres corrupts all its indexes.  the solution is presumably to dump everything and reload the DB from sql.

**Comment by jcgruenhage** [comment]
I'm cleaning up another database which had this problem (which I forgot to fix back in november), just saw that dumping and reloading is mentioned as a solution here, this does not fix it. You have to go through the database and delete everything that has been corrupted and recreate the indexes after that.
