### ISSUE TITLE
shared secret MAC calculation is different between /r0/register and /v1/register

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#2664]
/v1/register uses `user\0password\0admin`. /r0/register just uses `user`. Why are these different?

**Comment by richvdh** [comment]
Tbh if we're sticking to the line that shared-secret registration is synapse-specific, it should probably be on a separate endpoint from /register anyway. It doesn't really fit with the /r0/register semantics.

**Comment by hawkowl** [comment]
v1 shared secret register is gone nowwwwwwwwwwwwwwwww
