### ISSUE TITLE
/logout does not delete device

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#2672]
when /logout is called, the corresponding device should be deleted

**Comment by dbkr** [comment]
Also pusher if it doesn't already

**Comment by richvdh** [comment]
> Also pusher if it doesn't already

Doesn't look like it: https://github.com/matrix-org/synapse/blob/8aee5aa06807210c17ad0e58e4f237fcf2d052f9/synapse/rest/client/v1/logout.py#L40
