### ISSUE TITLE
synapse_port_db - "Database needs to be upgraded" on new postgres

### ISSUE THREAD

**Issue by emrahgunduz** [matrix-org/synapse#2699]
I'm trying to move from SQLite to Postgres.

I'm on Ubuntu 16.04
Installed synapse via APT: `matrix-synapse/unknown,now 0.25.1-1 all [installed]`

I decided to move our installation to Postgres as SQLite database is responding slow for some channels. Checked the `postgres.rst` document, created the user, database and tried to run `synapse_port_db` as shown, but I'm getting the given error. The database is empty, there are no data or tables present. 

It looks like a config of some sort is needed for the script to work, but there are no other arguments for `synapse_port_db`. How can I solve this problem?

```
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 465, in run
    self.setup_db(sqlite_config, sqlite_engine)
  File "/usr/bin/synapse_port_db", line 436, in setup_db
    prepare_database(db_conn, database_engine, config=None)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 66, in prepare_database
    raise UpgradeDatabaseException("Database needs to be upgraded")
UpgradeDatabaseException: Database needs to be upgraded
```

**Comment by richvdh** [comment]
You need to make sure that you are starting from an up-to-date sqlite database. Make sure that you have run synapse 0.25.1 against your sqlite database, so that the schema is upgraded, before you try to migrate it to postgres.

**Comment by deoliroe** [comment]
Hi Richard,

sorry for warming up this issue over 3 years old issue, but i ran in the same situation.
I've followed the guide https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md, created clean postgres db, checked the connection, permissions and created a postgresql enabled configuration for matrix and so on. 

Running on Ubuntu 20.04.2 LTS (up to date as i write), with matrix-synapse-py3 1.26.0+focal1 installed.

```
synapse_port_db -v --sqlite-database /var/lib/matrix-synapse/BKP_homeserver_20210214.db --postgres-config /etc/matrix-synapse/homeserver-postgresql.yaml --curses

Traceback (most recent call last):
  File "/usr/local/bin/synapse_port_db", line 468, in run
    self.setup_db(sqlite_config, sqlite_engine)
  File "/usr/local/bin/synapse_port_db", line 443, in setup_db
    prepare_database(db_conn, database_engine, config=None)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 68, in prepare_database
    raise UpgradeDatabaseException("Database needs to be upgraded")
UpgradeDatabaseException: Database needs to be upgraded
```
@richvdh how can i make sure i am on current sqlite schema version? 
I've checked that i stopped the matrixsynapse server and copied the homeserver.db with a current timestamp Feb 14 13:02 in my used db BKP_homeserver_20210214.db. Therefore im quite shure i ran matrixsynapse v1.26  against this sqlite db file.

But computer still says no and sometimes the're quite right. ;)

Anything i can do to get the migration running?

Many thanks in advance!

Best regards and a healthy time,
Oliver
