### ISSUE TITLE
Jitsi integration with existing server

### ISSUE THREAD

**Issue by webcluesdev** [matrix-org/synapse#2702]
Hello,

I make a custom server of Matrix on my server. Now I want to add Jitsi support for video calling.

I tried with Riot application when I use matrix.org server then it redirects me to jitsi's calling UI and when I use my custom server then it redirects me to traditional UI of the Matrix.

I need some help on the following question:

1) How can I add Jitsi to my custom server?
2) I need to change some code of my existing server or it will work without it?
3) Is there any way to integrate Jitsi into my application without launching new update?
4) If I need to change my server code then in which file I need to make a change?

Thanks in advance..:)

**Comment by richvdh** [comment]
please read the issue template
