### ISSUE TITLE
"auto_join_rooms"  seems not working

### ISSUE THREAD

**Issue by r4dh4l** [matrix-org/synapse#2725]
### Description

I want to use `auto_join_rooms` but is has no effect for new registered users.

### Steps to reproduce

1. I've added https://github.com/matrix-org/synapse/pull/2545 on my `Synapse/0.25.1` to my `homeserver.yaml`, defined in this way:

```
# Users who register on this homeserver will automatically be joined
# to these rooms
auto_join_rooms:
#    - "#example:example.com"
- "#serverinfo:myserver.ddns.net"
- "#helpdesk:myserver.ddns.net"
```

2. After restarting synapse I've added a new user, logged in but didn't see neither `#serverinfo:my.ddns.net` not `#helpdesk:my.ddns.net`.

### Version information

- **Homeserver**: private homeserver
- **Version**: `Synapse/0.25.1`
- **Install method**: pip
- **Platform**: `Linux myserver 4.9.7-sunxi #1 SMP Thu Feb 2 01:52:06 CET 2017 armv7l GNU/Linux

**Comment by turt2live** [comment]
Did you use the built-in script or Riot? It seems to only work if not using the built-in script.

**Comment by saljut7** [comment]
Thanks for your help @turt2live but could you specify what you mean with "buit-in script"? I've just added the option to my `homeserver.yaml`.

**Comment by turt2live** [comment]
The build in script is `register_new_matrix_user` - it doesn't work with this option, but registering new accounts in Riot should work.

**Comment by saljut7** [comment]
Oh I understand. I didn't enable register option via riot on my homeserver because manual says it shouldn't be used without a captcha. Unfortunately the supported captcha uses Google services and if I use Google services for a privacy focused messenger service _for me_ the whole effort maintaining the server makes much less sense.

Anyway: if `auto_join_rooms` does not work with script registered users is this a bug or a "feature"? ;)

**Comment by turt2live** [comment]
Well, there's valid arguments for either in my opinion. To please both sides, an opt-in parameter could be specified so that other registration methods can make use of the parameter (like external authentication systems or automation scripts).

**Comment by msbt** [comment]
Hi there!
Having the same issue here: riot frontend, matrix/synapse backend (different server) using LDAP for authorization but registration is also enabled. Neither (existing LDAP users or newly registered ones) are getting in the channel mentioned in auto_join_rooms. Can I set that in the config.json of riot or is that a synapse issue?

Best regards, M

**Comment by krombel** [comment]
`auto_join_rooms` is only evaluated when registering via "normal register" here:
https://github.com/matrix-org/synapse/blob/3e839e0548684fc27ff6cb3f966162e5194e7487/synapse/rest/client/v2_alpha/register.py#L410-L412

I could not find another appearance of `auto_join_rooms` in the code of synapse.
=> It is not implemented that it works for registrations via
- `register_new_matrix_user` but as well for
- ModuleApi which only uses [`register(localpart=localpart)`](https://github.com/matrix-org/synapse/blob/3e839e0548684fc27ff6cb3f966162e5194e7487/synapse/module_api/__init__.py#L83) which gets implemented [here](https://github.com/matrix-org/synapse/blob/3e839e0548684fc27ff6cb3f966162e5194e7487/synapse/handlers/register.py#L105)

Hopefully sb. takes this notes and implements that so it works for all 3 cases

**Comment by richvdh** [comment]
Any chance somebody could write a sytest for this to make sure it doesn't regress?

**Comment by krombel** [comment]
@r4dh4l Would you retest with v0.28?
The PR #2996 should fix some issues in this regard so I expect this issue to be resolved

**Comment by r4dh4l** [comment]
Sry for my late reply. Didn't manage to retest with 0.28 but today I noticed it works with 0.30 after registering a new user. But it still does not work for existing users.
If "auto_join_rooms" is intended to work only for *new* registered users this issue is fixed otherwise not.

**Comment by turt2live** [comment]
It is only supposed to work for new users. Although there's an argument to be had for whether an additional parameter should be available to always force joins (or prevent leaving).

**Comment by r4dh4l** [comment]
Forcing users to stay in a room provokes resistance... people don't like the feeling to be forced to be in a room.

Anyway: It would be better if auto_join_rooms would effect all users of a server. It is up to the users to stay or to leave.

**Comment by richvdh** [comment]
sounds like it's working as designed
