### ISSUE TITLE
E2E key update between federated servers

### ISSUE THREAD

**Issue by tommyskg** [matrix-org/synapse#2733]
I seem to have some issues in terms of the caching on matrix.org and the removal of old keys/devices that have been deleted from my home server.

Upon the deletion of a key (let's say that I remove a device in Riot), the keys are updated on the home server for users on the same domain. However, on matrix.org the old keys persist along with the new.

Can't seem to find anything else wrong in the federation setup, so I am assuming this is due to some bug (alternative some config that I've missed). Everything else seems to work (starting PMs, exchanging messages, E2E with the new devices).

Is this a known issue that I have missed in the docs?

I find one line in the logs that may be related (however the server is reachable for sure when I do a manual connection to the matrix.org API):

    2017-12-07 10:02:07,475 - synapse.http.outbound - 236 - INFO - POST-222989- {POST-O-1626} [matrix.org] Result: NoRouteError('Network is unreachable',)

**Comment by richvdh** [comment]
this seems like a thing which has likely been fixed (or is otherwise covered by #5441 etc)

**Comment by richvdh** [comment]
oh wait, it's talking about the removal of devices. there was a separate bug for that, which got fixed.
