### ISSUE TITLE
Federation room join status out of sync with broken settings

### ISSUE THREAD

**Issue by impala2** [matrix-org/synapse#2739]
Situation: recently moved server from one place to another, and it became misconfigured.

Tried testing federation by joining #matrix-dev, but didn't seem to work. Later, when I fixed the issue, I started getting messages from the room I previously tried to join but it my web riot client was acting weird and making it look like I was not in the room - servers were probably out of sync. Not sure if getting kicked or using the clear cache button fixed it, but it's working now.

Synapse v0.25.1
Riot-web: v0.13.3

Interestingly enough, the mobile client didn't get any of the messages. So perhaps this is just an issue with the web client.

I'll attach the logs a bit later.

**Comment by richvdh** [comment]
not much to work with here
