### ISSUE TITLE
Need Better Usability for Encryption Verify Handling

### ISSUE THREAD

**Issue by sraja415** [matrix-org/synapse#2742]
The encryption verify process in devices such as iOS and Android need better UI. The current Verify Device process and UI is Unusable and is meant for super advanced users, not for a common man.

Suggestion:
Option 1: When I login to a device send an email or SMS (from HS not from Matrix.org) confirming the device as a Valid Device and store Device ID. Anytime I log out and login, it should decrypt the messages seamlessly and view messages when I re-login via the same device. 

Option 2: Maybe Date of Birth and Secret 6 digit number to be entered when logging into a new device to accept a new device as a Trusted.

Allow me to Manage My Devices in Device Settings to remove any I don't Trust Anymore. 

When I relogin, using a different device, you can show and ask me if the previous devices are OK to be trusted or "My current Login Device is the Only Device I trust" and that should remove all others in the list. 

You can also have something called "Trust This Device Only Once for this login". This will remove the trusted device once I log out of the device.

**Comment by richvdh** [comment]
https://github.com/vector-im/riot-web/issues/2142
