### ISSUE TITLE
Matrix-synapse doesn't start after upgrading to v0.26.0

### ISSUE THREAD

**Issue by nvbln** [matrix-org/synapse#2756]
### Description

The matrix-synapse server didn't successfully start after upgrading to the newest version (0.26.0-1).

### Steps to reproduce

- Install version 0.25.1 of matrix-synapse.
- Upgrade matrix-synapse to version 0.26.0.
- Do `systemctl restart matrix-synapse`.
- Synapse will try to start, but stops after getting several errors (shown below).

![screenshot from 2018-01-07 10-53-17](https://user-images.githubusercontent.com/20875906/34648572-c747fdac-f39b-11e7-9ee9-9103355e318c.png)

Describe how what happens differs from what you expected.

Normally running `apt upgrade` and `systemctl restart matrix-synapse` upgrades and restarts matrix-synapse.
This time however, matrix-synapse stopped while starting up.

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?
On my own homeserver.

If not matrix.org:
- **Version**:        What version of Synapse is running? Upgrading from 0.25.1 to 0.26.0.
- **Install method**: apt from Debian 
- **Platform**:       The homeserver is running on Debian Jessie. It is not in a vm and runs on an old laptop.

**Comment by richvdh** [comment]
those errors look relatively harmless to me. Could you upload the rest of the logs (text, not image, please)?
