### ISSUE TITLE
Can we graph network activity by HTTP endpoint rather than per worker?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2757]

**Comment by ara4n** [comment]
it feels weird that we can track DB activity per transaction, but not HTTP, and i'm finding myself writing perl scripts to fake this - why can't prometheus/grafana do it for me?

**Comment by richvdh** [comment]
I don't understand what you are asking for. The title seems to conflict with your most recent comment.

We graph request count by endpoint:

![image](https://user-images.githubusercontent.com/1389908/34649074-4d75fe76-f39f-11e7-86df-fa2fa37caf85.png)

**Comment by ara4n** [comment]
i missed this because there was a big gap in the problem period. i'm wondering if we should generate the same graph from haproxy instead.

**Comment by ara4n** [comment]
<img width="669" alt="screen shot 2018-01-07 at 12 13 40" src="https://user-images.githubusercontent.com/1294269/34649292-3a1db59e-f3a4-11e7-860e-b59029a557f1.png">

^ gap in question, whereas haproxy had all the right data which would have made the problem much more obvious.

**Comment by richvdh** [comment]
certainly it would be nice to try to aggregate the haproxy logs into monitoring data. That's not a synapse feature.

(It would also be nice if the monitoring didn't stop working as soon as synapse gets a bit busy (ie, the point you most need monitoring), but hey ho.)
