### ISSUE TITLE
String formatting error

### ISSUE THREAD

**Issue by delirious-lettuce** [matrix-org/synapse#2759]
### Description

Trying to raise an `AuthError` will instead raise `TypeError: not all arguments converted during string formatting`. This is caused by a single typo of using `&` instead of `%`.

### Steps to reproduce

https://github.com/matrix-org/synapse/blob/e6b24663e4df18767d3ac9023e97676515824ff8/synapse/event_auth.py#L322

```python
>>> target_user_id = 'TEST_USER_ID'
>>> "You cannot unban user &s." % (target_user_id,)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: not all arguments converted during string formatting
>>> "You cannot unban user %s." % (target_user_id,)
'You cannot unban user TEST_USER_ID.'
```

I didn't submit a pull request because it seems like you guys won't accept it from my GitHub pseudonym, hopefully an issue will do instead!

**Comment by turt2live** [comment]
I've gone ahead and made the 1 character change here: https://github.com/matrix-org/synapse/pull/2761

**Comment by delirious-lettuce** [comment]
@turt2live ,

Thanks!
