### ISSUE TITLE
[Question]How to upgrate a exiting Synapse to a certain version by using pip

### ISSUE THREAD

**Issue by wjhtinger** [matrix-org/synapse#2781]
not the  latest version

**Comment by richvdh** [comment]
not a synapse bug. please ask support queries in [#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org).

**Comment by richvdh** [comment]
not a synapse bug. please ask support queries in [#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org).
