### ISSUE TITLE
Extend User Profile information

### ISSUE THREAD

**Issue by expertalex** [matrix-org/synapse#2788]
Hello. 

There is a way of easily adding additional user information like country or language with will be seen by other users.

I saw in the matrix.org that it is possible but i can't finde any documentation.
https://matrix.org/docs/spec/intro.html#profiles 
> Users may publish arbitrary key/value data associated with their account - such as a human readable display name, a profile photo URL, contact information (email address, phone numbers, website URLs etc).

Can someone send me the link to the api endpoint to do so?

Thanks.

Regards 
Alex

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those here (please be careful to remove any personal or private data):

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
- **Version**:        What version of Synapse is running? 
- **Install method**: package manager/git clone/pip      
- **Platform**:       Tell us about the environment in which your homeserver is operating
                      - distro, hardware, if it's running in a vm/container, etc.

**Comment by richvdh** [comment]
not a synapse bug. please ask for support in [#matrix-dev:matrix.org](https://matrix.to/#/#matrix-dev:matrix.org)

**Comment by ara4n** [comment]
see https://github.com/matrix-org/matrix-doc/issues/489
