### ISSUE TITLE
Room icon size incorrect

### ISSUE THREAD

**Issue by MartijnBraam** [matrix-org/synapse#2799]
### Description

The icons in the riot client for some rooms seemed blurry so I checked the media url and it seems to be returning the wrong size image.

### Steps to reproduce

- Open https://matrix.org/_matrix/media/v1/thumbnail/disroot.org/omImodskspCryApihvRjAtwG?width=48&height=48&method=crop
- See that the requested size is 48x48 but it returns a 32x32 image (the original size is 96x96)

The inverse also happens on this icon:
https://matrix.org/_matrix/media/v1/thumbnail/disroot.org/WaZoGMHggcIsSXmeYWKkgSAz?width=48&height=48&method=crop
that returns an 96x96 image instead.

### Version information

The issue is on matrix.org

**Comment by turt2live** [comment]
This seems like a duplicate of https://github.com/matrix-org/synapse/issues/1222

**Comment by richvdh** [comment]
dup #1222

**Comment by PureTryOut** [comment]
It might be a duplicate, but this issue contains way more info about the problem, with some examples even. Couldn't the info be copied to the other issue aside from closing this one?
