### ISSUE TITLE
synapse wedges when it runs out of FDs

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#2800]
shortly after hitting the FD ulimit, synapse wedges at 100% cpu

**Comment by richvdh** [comment]
it also won't die when you hit it with a SIGTERM - it takes a SIGKILL to kill it

**Comment by ara4n** [comment]
fwiw this was the main failure mode in all the meltdowns of Xmas 2016 (https://github.com/matrix-org/synapse/issues/1858, https://github.com/matrix-org/synapse/issues/1778 etc)

**Comment by richvdh** [comment]
Turns out it is wedged in this loop in twisted: https://github.com/twisted/twisted/blob/trunk/src/twisted/names/client.py#L221

(listenUDP calls udp.Port.startListening calls _bindSocket throws a CannotListenError on failure to call `socket`)

See: https://twistedmatrix.com/trac/ticket/5368.

Given the bug's been open in twisted for 6 years (and if you go back to https://twistedmatrix.com/trac/ticket/816#comment:12, 10 years)... I doubt this is an easy fix.

**Comment by richvdh** [comment]
> fwiw this was the main failure mode in all the meltdowns of Xmas 2016 (#1858, #1778 etc)

yes, though those were more about the fact that we were leaking FDs (and hence hitting this bug); I want to keep this bug about the fact that once we run out of FDs (either because we leak, or because the ulimit was too low) the failure mode is horrible.

**Comment by ara4n** [comment]
This sucks but given bad things are afoot if you're out of FDs anyway, such is life.

**Comment by richvdh** [comment]
https://twistedmatrix.com/trac/ticket/5368 claims to be fixed, so perhaps I was too pessmistic earlier

**Comment by n1trux** [comment]
https://github.com/twisted/twisted/pull/1126 was merged, so this should be re-evaluated.

**Comment by richvdh** [comment]
There are still reports of this happening. possibly there is a similar problem in GAIResolver.

**Comment by alexte** [comment]
I had this 100% freeze with 1.23 with this stack trace today:
2020-11-26 11:36:45,418 - twisted - 254 - CRITICAL -  - Unhandled error in Deferred:
2020-11-26 11:36:45,421 - twisted - 254 - CRITICAL -  - 
Traceback (most recent call last):
  File "/root/synapse/env/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
  File "/root/synapse/env/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
  File "/root/synapse/env/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
  File "/root/synapse/env/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
  File "/root/synapse/env/lib/python3.5/site-packages/twisted/internet/_resolver.py", line 124, in get
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
OSError: [Errno 24] Too many open files

**Comment by alexte** [comment]
[SOLVED]

As mentioned before this looks like an old bug in "twister" which was fixed in: https://github.com/twisted/twisted/pull/1126
Which is in twister-19.7.0.

But if your matrix installation is old enough you might have twister-18.9.0 installed, which is the minimum requirement for synapse-1.23.0.

If you are using pip (in virtuelenv) you can update twister manually with:

pip install --upgrade Twisted

**Comment by Loader009** [comment]
@alexte is this still considered as fixed?

I use the docker container with podman. v1.38.0
ulimit is set to 40000, but according to various sources, I hit at most 200. (Grafana/Prometheus statistics and also lsof.)

```
2021-07-15 18:21:53,019 - twisted - 258 - CRITICAL - sentinel - Unhandled error in Deferred:
2021-07-15 18:21:53,021 - twisted - 258 - CRITICAL - sentinel - 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/_resolver.py", line 141, in get
    return self._getaddrinfo(
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 24] Too many open files
```

**Comment by alexte** [comment]
@Loader009 I think the fix I wrote about (updating the twister library), doesn't apply to the docker version

**Comment by Loader009** [comment]
Not sure if it is the outdated twisted lib, cause it seems up2date...
From within the docker image:
```shell
root@bla:/# pip show twisted
Name: Twisted
Version: 21.2.0
```

I can't see any virtual environment, it is most probably not there.
Thus I think the bug has been reintroduced?

**Comment by richvdh** [comment]
@Loader009 this issue is about a bug where synapse completely stops responding and spins at 100% cpu. Are those the symptoms you are seeing?

If so, could you install [py-spy](https://github.com/benfred/py-spy) and run `py-spy dump --pid <synapse process id>` ?

**Comment by Loader009** [comment]
Synapse responses in my case and there is no 100% cpu usage (sometimes though, but more probably because of low end cpu) - but I see the FD error, connected with the twisted python-lib.

Tried py-spy, but I always get a permission denied (within and outside the docker image).
Even as root and even with kernel.yama.ptrace_scope set to 0 or 1.
Nothing in the journal, I would've expected to see some audit or selinux message.

![screen-2021-07-22-06-58-02](https://user-images.githubusercontent.com/9888311/126591922-64c21f91-b5e5-44e4-b36c-9ea848f0d17a.jpg)
![screen-2021-07-22-06-57-54](https://user-images.githubusercontent.com/9888311/126591928-03026c92-033d-4d42-8a1c-07c88ae1af86.jpg)

There seems to be a correlation of cpu usage and the FD-Errors.

**Comment by richvdh** [comment]
@Loader009 it looks like your problem is entirely unrelated. For some reason your ulimit isn't being applied correctly, but that's off-topic for this issue and very unlikely to be anything specific to Synapse (or Twisted, for that matter).

I'm going to assume *this* issue has been resolved in recent versions of Twisted, and go ahead and close it.

**Comment by Loader009** [comment]
Ok, then I have to open my own issue.
Because `ulimit -n` shows me the correct value (as user and within the docker image), which means that it is applied correctly.
