### ISSUE TITLE
User Interactive auth sessions are only stored in memory, so if you restart server mid-auth, auth will fail

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2811]
This is particularly unpleasant given restarting the server whilst someone is trying to validate 3PIDs during registration will cause their registration to fail.

This is based on looking at https://github.com/matrix-org/synapse/blob/da1010c83acd08648a440d27499a0e3688bb961a/synapse/handlers/auth.py#L832

**Comment by clokep** [comment]
This is fixed by #7302.
