### ISSUE TITLE
List Rooms

### ISSUE THREAD

**Issue by TiagoraVieira** [matrix-org/synapse#2815]
Hi, when i get /_matrix/client/r0/publicRooms always return empty {total_room_count_estimate: 0, chunk: []}. Why this request doesnt work? I need to get all the rooms on my server.

**Comment by turt2live** [comment]
That endpoint is for the room directory. I'm not aware of an endpoint to list all the rooms on the server, so you may have to go to the database.

For reference, support queries are best asked in [#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org).
