### ISSUE TITLE
GPG: signatures couldn't be verified

### ISSUE THREAD

**Issue by bazzly1** [matrix-org/synapse#2822]
### Description
Not able to install, getting the error below. Using instructions from : https://www.hackster.io/matrix-labs/matrix-voice-running-alexa-demo-in-hands-free-mode-404aa3

GPG error: https://apt.matrix.one/raspbian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B16A1706B2DD19C3
W: The repository 'https://apt.matrix.one/raspbian stretch Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

### Steps to reproduce
Add repo and key
curl https://apt.matrix.one/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.matrix.one/raspbian $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/matrixlabs.list
# Update packages and install
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install matrixio-malos libmatrixio-hal-dev

It fails to install

If you can identify any relevant log snippets from _homeserver.log_, please include
those here (please be careful to remove any personal or private data):

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
- **Version**:        What version of Synapse is running? 
- **Install method**: see above     
- **Platform**:       RaspberryPi 3 latest Noobs/Stretch

**Comment by turt2live** [comment]
@bazzly1 This is a different project. I think you're looking for a similarly named project: MATRIX. Their support page is here: https://matrix-io.github.io/matrix-documentation/help/
