### ISSUE TITLE
Media over federation should follow the same federation rules

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2823]
When media is being downloaded from a remote server, it seems to ignore the domain resolution rules for federation (particularly the SRV part).

**Comment by richvdh** [comment]
are you sure? if that were true then nobody would be able to access any media I post (because my homeserver relies on an SRV record)

**Comment by turt2live** [comment]
I swear I tested extensively before posting this issue, but re-testing it now shows that it works. Probably some weird caching problem on my end.

Apologies for the noise.
