### ISSUE TITLE
API support for changing a group member's privilege/admin level.

### ISSUE THREAD

**Issue by pwnage101** [matrix-org/synapse#2855]
### Description

This is a feature request for adding API support for changing a group member's privilege/admin level, so that groups/communities can have multiple admins.  Only admins of the group can elevate other members to admin level.  Currently, it seems that group admins can only do things like invite new (unprivileged) members and kick existing members.

Motivation: I'd like multiple users in a community/group to be able to modify the list of rooms.

I asked on #matrix:matrix.org if this feature was available, to which Matthew answered yes but there are no riot-web UI hookups for it.  After looking at the API and synapse codebase, I am not convinced that such an API exists already.

### Steps to reproduce

Not a bug.

**Comment by turt2live** [comment]
The closest riot-web issue I could find was https://github.com/vector-im/riot-web/issues/5240

**Comment by neilisfragile** [comment]
"After looking at the API and synapse codebase, I am not convinced that such an API exists already."
Agreed, unless @ara4n knows otherwise?

**Comment by Half-Shot** [comment]
I'm sure this is on the roadmap. I'm assuming we will have fine grained power levels like rooms for this.

**Comment by rodrigoaguilera** [comment]
I just been invited to the +drupal:matrix.org community and I noticed it has two users with admin privileges.

Is that possible?

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
