### ISSUE TITLE
Domain unusable after HomeServer DB lost

### ISSUE THREAD

**Issue by nordurljosahvida** [matrix-org/synapse#2859]
### Description

I know it's entirely my fault, but I lost access to my HS's sqlite db when transitioning to psql on a re-instanced VPS, and now my domain is almost unusable. I know it's not an issue, but I'd like to kindly relay Maximus's advice from over in the support room to make the docs clearer about this peculiarity, and ask for a way to track any future progress should there ever be a solution for this.

Thank you very much and sorry for the noise.

### Steps to reproduce

Install, install psql without migrating the db [I know, I know]

All hell breaks loose: https://hastebin.com/tofuvifebu.pl

### Version information

- **Homeserver**: Yes

- **Version**:        Synapse/0.26.0

- **Install method**: APT [https://www.digitalocean.com/community/tutorials/how-to-install-matrix-synapse-on-ubuntu-16-04]

- **Platform**:       Ubuntu 16 VPS

**Comment by neilisfragile** [comment]
@nikksno 
Firstly, well that sucks.

Could you give me a bit more detail on exactly what you did to trigger this? In particular "install psql without migrating the db" - maybe you already did this in a channel, you reference a support channel, if there is relevant scroll back, can you point me at it?

**Comment by nikksno** [comment]
Thanks for your reply, this actually all solved itself after about 2 to 3 days, as other servers realized my keys had changed [I assume] and now everything works again. You can find my conversation over here. Thanks again to the guys who helped me out. I do think there should definitely be an alert on the psql doc saying you **must** migrate the db or enter federation hell for 72H straight, but again, great project and great work being done. Thanks to all.
