### ISSUE TITLE
Provide instructions on how to use Debian package

### ISSUE THREAD

**Issue by rugk** [matrix-org/synapse#2865]
In the Readme you state:
> Matrix provides official Debian packages via apt from http://matrix.org/packages/debian/.

There are no instructions on how to actually use these. Also, it seems you do not offer ARM packages there, do you?

**Comment by neilisfragile** [comment]
Hi @rugk We'll be shortly rewriting our install guides, in the meantime https://www.digitalocean.com/community/tutorials/how-to-install-matrix-synapse-on-ubuntu-16-04 provides step by step guide to use the debian packages

We don't have ARM support, so for now you would need to install from source.

**Comment by richvdh** [comment]
I fixed this in #4526
