### ISSUE TITLE
Schema migration may possibly complete only partially

### ISSUE THREAD

**Issue by spantaleev** [matrix-org/synapse#2879]
I'm running 2 separate instances of the Synapse server.
Both using `v0.26.0` of this Docker image: https://hub.docker.com/r/avhost/docker-matrix

Both on a Postgres 9.6.x server.

The `schema_version` table for both servers says: `version = 46` with `upgraded = t` and `lock = X`.

I've just noticed that **one of those servers** did not really properly complete the v46 database schema migrations.

Some migrations ran, some did not. It's something like this, as far as I could tell by manually looking at the database schema:

- `drop_refresh_tokens.sql` - **did not** run - judging by the fact that there's still a `refresh_tokens` table in my database
- `drop_unique_deleted_pushers.sql` - cannot tell if it ran
- `group_server.sql` - **did not** run - judging by the fact that I don't have the new `is_public` field in my `groups` table
- `local_media_repository_url_idx.sql` - cannot tell if it ran
- `user_dir_null_room_ids.sql` - did run
- `user_dir_typos.sql` - did run

--------

`select * from applied_schema_deltas where version = 46;` says:

```
      46 | 46/drop_refresh_tokens.sql
      46 | 46/group_server.sql
      46 | 46/user_dir_typos.sql
      46 | 46/drop_unique_deleted_pushers.sql
      46 | 46/local_media_repository_url_idx.sql
      46 | 46/user_dir_null_room_ids.sql
```

The fact that a `refresh_tokens` table still exists in my database, however, definitely indicates that `drop_refresh_tokens.sql` hadn't been executed.

I'm not sure how this happened and I don't have any logs, because I've upgraded a long time ago and I don't keep logs for so long.

Seems like there's a possibility that:
- a whole migration set would be marked as completed in `schema_version`
- specific deltas would be marked as executed in `applied_schema_deltas`

.. even in cases where something went wrong in the meantime.

My other Synapse instance is fine and I'm not completely sure what happened with this one to make it like that. I suspect I may have messed with some manual schema migrations at some point in the past, but I'm not sure what I remember there...

I have since applied the missing deltas to my Postgres server manually (pasting into `psql`) and it all seems fine.

If you think there might be a bug causing the above issue to happen, please feel free to pursue or inquire for more information, although me not having logs probably makes it hard.

**Comment by neilisfragile** [comment]
To my knowledge this is not a previously known problem - so the general case is working, but clearly we should be completing migrations cleanly. It's hard make more progress than that without logs though. I'll mark it as a bug that needs investigating, but next steps are unclear.

**Comment by richvdh** [comment]
given we've not seen this in the last two years, I'm going to close it. I don't think we're likely to be able to do anything about it.
