### ISSUE TITLE
Feature Requests: Room->Subroom forums layout, Email, Encrypted Documents

### ISSUE THREAD

**Issue by speakeasy** [matrix-org/synapse#2883]
### Description

I am requesting the ability to make rooms containing rooms to use as forums, as well as a twitter like interface and user profile page + feeds.
I would also like to see a gmail like interface for sending and receiving emails between users (And externally)
Encrypted documents like pirate pad or etherpad, excel, google docs etc.
Private hosting and web of trust for email and docs.

Separately, routing of IP traffic using the same synapse backbone over a web of trust with client modules for IP traffic and trust web based on servers connected to and clients as well. (WoT servers/clients)

Ident server with invite only.

### Steps to reproduce

NA

### Version information

Latest

**Comment by Half-Shot** [comment]
This should probably be moved to https://github.com/vector-im/riot-meta/issues as the features requested are largely client issues. The ones that do relate to synapse should be split into separate issues rather than lumped together as a wishlist.

**Comment by neilisfragile** [comment]
Good shout @Half-Shot I'll close this issue @speakeasy please feel free to resubmit the riot requests individually to https://github.com/vector-im/riot-meta/issues (it would be good to get a bit more detail on exactly what you are proposing) and the remaining synapse specific request here, again greater detail is appreciated.
