### ISSUE TITLE
Spell out that sqlite should only be used for initial experimentation

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#2889]

**Comment by ara4n** [comment]
i'd say this is higher priority than p3; it's the single biggest cause of folks having disasters with synapse

**Comment by richvdh** [comment]
surprisingly, this still doesn't seem to be mentioned in https://github.com/matrix-org/synapse/blob/master/INSTALL.md#setting-up-synapse

**Comment by aaronraimist** [comment]
This is mentioned in the README now but still not in INSTALL.md https://github.com/matrix-org/synapse#using-postgresql

**Comment by aaronraimist** [comment]
I think #7899 fixed this

**Comment by clokep** [comment]
I think so! Thanks!
