### ISSUE TITLE
Config creation problem

### ISSUE THREAD

**Issue by stefanalund** [matrix-org/synapse#29]
I get the following error message when trying to generate a config file:

```
stefan@Stefans-MBP:~/.synapse$ python -m synapse.app.homeserver -c homeserver.yaml --generate-config --server-name=stefanmatrix
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/stefan/Library/Python/2.7/lib/python/site-packages/synapse/app/homeserver.py", line 36, in <module>
    from synapse.crypto import context_factory
  File "/Users/stefan/Library/Python/2.7/lib/python/site-packages/synapse/crypto/context_factory.py", line 17, in <module>
    from twisted.internet._sslverify import _OpenSSLECCurve, _defaultCurveName
ImportError: cannot import name _OpenSSLECCurve
```

**Comment by erikjohnston** [comment]
That's interesting. I don't think we've seen that before; we're looking into what could cause that now. What version of twisted are you using out of interest?

Also, just a note that the --server-name should be set to the domain name other servers can talk to you via (see https://github.com/matrix-org/synapse#setting-up-federation for details). I'll change the help for that option to be slightly more helpful :)

**Comment by stefanalund** [comment]
Twisted version: 13.2.0. 
OS X Version: 10.10.2

**Comment by erikjohnston** [comment]
Interesting, it should have pulled in twisted version 14 or above. How did you install it? If this is a git checkout of the code you will need to run `python setup.py develop --user`.

**Comment by erikjohnston** [comment]
(We should check add a check for this at runtime too)

**Comment by ara4n** [comment]
OSX ships with its own (ancient) version of Twisted, iirc.  So I assume 
the problem here is that the correct dependency wasn't pulled in... or 
that the local-installation one isn't trumping the system one.  As Erik 
says, we'll need to know how you tried to install it.

(Erik: this may be a mismatch between telling people to install directly 
via pip, rather than cloning and then using setup.py)

**Comment by erikjohnston** [comment]
(My understanding was that installation via pip should pull in the correct dependencies?)

**Comment by stefanalund** [comment]
I installed through git and pip, the tried to start the server according to: https://github.com/matrix-org/synapse#running-your-homeserver

**Comment by stefanalund** [comment]
Now testing to --user stuff:
```
stefan@Stefans-MBP:~/Developer/github/synapse (master)$ python setup.py test
running trial
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    """
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/test.py", line 128, in run
    self.distribution.fetch_build_eggs(self.distribution.install_requires)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (pyOpenSSL 0.13.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('pyopenssl>=0.14'))
```

**Comment by stefanalund** [comment]
(After successfully running `python setup.py develop --user`)

**Comment by erikjohnston** [comment]
Hmm, I wonder if the python environment is somehow preferring system installs instead of user installs. If you could check where its pulling in pyopenssl that would be great, If you just run `python` in that directory and do:
> $ import OpenSSL
> $ print OpenSSL.__file__

then that should tell us where its getting pulled in from.

If you're free it might be easier to debug this on #matrix instead?

**Comment by erikjohnston** [comment]
(That should have read `print OpenSSL.__file__`, except markdown formatted it :/ )

**Comment by stefanalund** [comment]
```
>>> import OpenSSL
>>> print OpenSSL.__file__
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL/__init__.pyc
```

**Comment by ara4n** [comment]
Okay, so the problem here is indeed that synapse is picking up the system pyOpenSSL (0.13.1) installed in /System rather than the one that should have been installed into ~/Library/Python/2.7/lib/python/site-packages/pyOpenSSL-0.14-py2.7.egg by python setup.py develop --user.

Can you please paste the results of:
> `import sys`
> `print sys.path`

...and `ls ~/Library/Python/2.7/lib/python/site-packages/pyOpenSSL*`

thanks - and sorry for the hassle with this.  I'm assuming there's some bad interaction between pip & setup.py on yosemite that we're about to discover...

**Comment by stefanalund** [comment]
```
>>> print sys.path
['', '/Users/stefan/Developer/github/synapse', '/Library/Python/2.7/site-packages/pip-6.0.6-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/stefan/Library/Python/2.7/lib/python/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages']
```
and 
```
ls ~/Library/Python/2.7/lib/python/site-packages/pyOpenSSL*
PKG-INFO		dependency_links.txt	requires.txt
SOURCES.txt		installed-files.txt	top_level.txt
```

**Comment by ara4n** [comment]
I'm not sure how this is possible, but somehow your local python libraries don't seem to be on your python path.  if you `export PYTHONPATH=$HOME/Library/Python/2.7/lib/python/site-packages` then hopefully python will start picking up the right libraries!

**Comment by ara4n** [comment]
oh, i lie - the local libraries /are/ there, but the order is wrong; the system ones are taking priority hence the clashing version. again, setting PYTHONPATH should hopefully fix this.

**Comment by stefanalund** [comment]
That did the trick, passing all tests now. 

Must admit it's a bit hard to understand, from reading the README, the difference between installing the server through pip or for local development.

Thanks guys.

**Comment by ara4n** [comment]
Great. We are just fixing the pip/setuptools discrepancy (http://matrix.org/jira/browse/SYN-219).

M

**Comment by ara4n** [comment]
...and have updated the doc for this particular issue as https://github.com/matrix-org/synapse/commit/80e89772.

**Comment by mpi4you** [comment]
Why closed it exists,...
Requirement already satisfied (use --upgrade to upgrade): pillow in ./env/lib/python2.7/site-packages
(env)joni@mpi1:/mpi3/S4/synapse$ python -m synapse.app.homeserver \
>     --server-name=mpi1.kurrola.allowed.org \
>     --config-path=homeserver.yaml \
>     --generate-config
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mpi3/S4/synapse/synapse/app/homeserver.py", line 20, in <module>
    from synapse.storage import prepare_database, UpgradeDatabaseException
  File "synapse/storage/__init__.py", line 31, in <module>
    from .keys import KeyStore
  File "synapse/storage/keys.py", line 20, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 36, in <module>
    from OpenSSL import crypto
ImportError: cannot import name crypto
(env)joni@mpi1:/mpi3/S4/synapse$ 


Tried to install as python to home and trough git,... same error.

joni
