### ISSUE TITLE
Dedupe users in a group when adding appservice users

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2905]
### Description

Otherwise you can end up with double flair:
![image](https://user-images.githubusercontent.com/1190097/36504194-e34e762c-170c-11e8-94ac-9f3b381e2dc8.png)

Up until recently I had a script to manage the group membership before switching to the behaviour introduced in https://github.com/matrix-org/synapse/pull/2686

### Version information

- **Homeserver**: t2bot.io
- **Version**:        0.26.0 (develop) with patches: https://github.com/turt2live/synapse/tree/travis/t2bot.io
- **Install method**: pip
- **Platform**:       containers

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
