### ISSUE TITLE
API /messages no results. Chunk is clear

### ISSUE THREAD

**Issue by psyapathy** [matrix-org/synapse#2906]
Hello!
Help me please with api. I cant get result from /messages of room

I try:
http://myserver:8008/_matrix/client/r0/rooms/!roomid:myserver/messages?access_token=<myaccesstoken>

and result:
start | "t1622-35520_724055_34583_26822_30702_4_240_164_4"
chunk | []
end | "t1622-35520_724055_34583_26822_30702_4_240_164_4"

**Comment by neilisfragile** [comment]
Hi @psyapathy you'd be better off asking for help in #matrix:matrix.org

Closing the issue, since it's not really an issue with Synapse itself
