### ISSUE TITLE
Self Hosted matrix-synapse configuration problems

### ISSUE THREAD

**Issue by raa0x0** [matrix-org/synapse#2908]
Some important stuff:

>We have self hosted riot-web, matrix-synapse with own identify server (ldap based auth).
>VM on VMware Debian 9, installation from package.
> dpkg -l | grep synapse
> ii  matrix-synapse                0.26.0-1                       all          Open federated Instant Messaging and VoIP server
> ii  python-matrix-synapse-ldap3   0.1.2-1                        all          An LDAP3 auth provider for Synapse

Question1:
>Can we block in possibility of room creation if we want only few static room to be available? Or if we server admin?

Question2:
>When auth is on ldap server, if I change value in db (table users, column admin) to 1, user will become server admin?

Question3:
>When all users leave room, room exists but we cant join there anymore and we receiving "internal server error" ("Failed to send to any server." in log of 'federation_client.py').

**Comment by neilisfragile** [comment]
For questions, your best bet to ask in #matrix:matrix.org or #matrix-dev:matrix.org

Q1 - I don't think so
Q2  - Not sure
Q3 - Could you file this is a separate bug with a bit more detail - we shouldn't be 500ing in that scenario
