### ISSUE TITLE
User directory search fails for certain letters

### ISSUE THREAD

**Issue by cuibonobo** [matrix-org/synapse#2931]
### Description

I have enabled the `search_all_users` option for the user directory search (and applied the #2831 patch to fix the internal server error). I've found that the user directory search works very well except when searching for the single letters `a`, `s`, and `t`. Searching for other single letters of the alphabet produces the correct results.

### Steps to reproduce

POST to `https://matrix.floydcounty.tv/_matrix/client/r0/user_directory/search` with the proper authentication and the following JSON body:

```json
{
	"search_term": "t"
}
```

I expect to receive a list of users whose display name or username starts with the letter `t` (there would be at least 10 results on my server). Instead, I get an empty result:

```json
{
    "limited": false,
    "results": []
}
```

POSTing with some other letter, for example `j`, will return a list of users as expected.

The homeserver log doesn't show anything unusual for this particular request.

### Version information

- **Version**: Synapse/0.26.0
- **Install method**: pip      
- **Platform**: Ubuntu 16.04.3 LTS running on a Xen VM

**Comment by turt2live** [comment]
This sounds eerily similar to https://github.com/vector-im/riot-web/issues/4950

**Comment by cuibonobo** [comment]
@turt2live: I think you're onto something!

Here are my results when I search for `wil`:

![screenshot 2018-03-09 15 57 46](https://user-images.githubusercontent.com/391241/37229664-b95b61b0-23b2-11e8-86ad-46bd71cd2781.png)

...and here's what happens when I search for `will`:

![screenshot 2018-03-09 15 58 05](https://user-images.githubusercontent.com/391241/37229687-d23c37e0-23b2-11e8-8396-fcbdb3ce71ac.png)

Seems like the database is filtering search terms for 'common' words.

**Comment by cuibonobo** [comment]
The relevant portion seems to be here: https://github.com/matrix-org/synapse/blob/18e3a16e8b2303e6b638f679b5b8533e329cbe7a/synapse/storage/user_directory.py#L664-L695

Indeed, if I check the English stopwords list (which lives at `/usr/share/postgresql/9.5/tsearch_data/english.stop` on Ubuntu 16.04.3 LTS), the letters `a`, `s`, and `t` are listed, as well as the word `will`.

I did a bit of research and it's possible to do full-text search queries [without using stopwords](https://stackoverflow.com/a/2227235/2001558), but it involves creating a new dictionary, creating a configuration that uses that dictionary, and possibly creating an index for the new configuration. Once all of that is done, the first parameter of `to_tsvector` in the above-referenced lines would change from the default `english` configuration to the name of the configuration with the stopwords removed.

Given all the work that fixing this would involve, I wonder if full-text search is the right solution for user directory searches.

**Comment by awesome-manuel** [comment]
I agree, the full-text search features, like derived words etc. are not really usefull when we search for user names. Should be changed to simple pattern matching in the relevant columns.
@ara4n

**Comment by chagai95** [comment]
This is pretty interesting, is this going to be fixed sometime soon? Is it a lot of work? Seems like a different method should just be used instead of to_tsquery but I'm not sure that's an easy task...

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/8959
