### ISSUE TITLE
Logout returns 200 when given an invalid access_token

### ISSUE THREAD

**Issue by ajberchek** [matrix-org/synapse#2932]
### Description

According to the specification for the [/logout endpoint](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#post-matrix-client-r0-logout), it invalidates an **existing token**. However, when supplied an invalid/non-existent access_token (such as "42") it still returns a 200 status code.   

### Steps to reproduce

- Send a POST to /_matrix/client/r0/logout with an Authorization header containing an invalid access_token (e.g. "Bearer 42")
- Response is a 200 status code

Ideally this should respond with error code  M_UNKNOWN_TOKEN to provide a more verbose error

**Comment by turt2live** [comment]
https://github.com/matrix-org/synapse/pull/2938 claims to have already fixed this issue?

**Comment by erikjohnston** [comment]
Ah, cool
