### ISSUE TITLE
Communication between two servers synapse

### ISSUE THREAD

**Issue by bzhfloriane** [matrix-org/synapse#2935]
I have 2 VM each with a synapse server. I can not create a discussion between these two synapse servers. I get this error when I create a discussion:

```
Error
Internal server error (M_UNKNOWN)
```
And in my logs : 
```
17:05:08,767 - synapse.handlers.profile - 123 - ERROR - POST-669- Failed to get displayname
Traceback (most recent call last):
File "/root/.synapse/lib/python2.7/site-packages/synapse/handlers/profile.py", line 115, in get_displayname
ignore_backoff=True,
ConnectionRefusedError: Connection was refused by other side: 111: 
Connection refused.
```
I am under CentOS7.

**Comment by turt2live** [comment]
Without more information this sounds like your other server is simply not listening for federation.

**Comment by ara4n** [comment]
or CentOS has a firewall on?

**Comment by bzhfloriane** [comment]
No, I stopped the firewalld.

**Comment by bzhfloriane** [comment]
@turt2live Sorry, but how I can fix it ? I don't know how to do ..

**Comment by bzhfloriane** [comment]
@ara4n Do you know why I can't communicate between 2 servers Synapse ?

**Comment by neilisfragile** [comment]
@bzhfloriane if you haven't already done so, you'll get better support for this sort of request by heading to one of the community channels like #matrix:matrix.org

**Comment by bzhfloriane** [comment]
@neilisfragile 
Yes but my second problem is that I can not access any other room like #matrix:matrix.org ..

**Comment by richvdh** [comment]
support issue. Please use a matrix.org account if you can't access the support room from your own server.
