### ISSUE TITLE
I can not federate my server

### ISSUE THREAD

**Issue by bzhfloriane** [matrix-org/synapse#2945]
Hello,

I start installing a Synapse server. I managed to install a Synapse server with different users. Different users of the same server (server-name : `nexus_chat1.nexus`) can communicate with each other. Now, I want these users to be able to communicate with other users of another Synapse server (server-name : `nexus_chat2.nexus`).

I then wanted to follow the [Setting up federation](https://github.com/matrix-org/synapse#setting-up-federation). but I do not understand how to achieve this part:

> To use a SRV record, first create your SRV record and publish it in DNS. This should have the format _matrix._tcp. <Yourdomain.com> <ttl> IN SRV 10 0 <port> <synapse.server.name>.

For my part, when I executed this command: `dig -t srv _matrix._tcp.nexus_chat1.nexus`
I get this: 
`;; ANSWER SECTION:`
`_matrix._tcp.nexus_chat1.nexus. 3599 IN SRV 10 10 0 your-dns-needs-immediate-attention.nexus.`

If anyone can explain to me how to configure a federation ..

**Comment by silkeh** [comment]
An SRV record is only required if the Synapse server name does not match the hostname of the synapse server (eg: hosting the homeserver for `example.com` on the host `matrix.example.com`).

The issues here are:

- Both `nexus_chat1.nexus` and `nexus_chat1.nexus` resolve to `127.0.53.53`. Are these the actual FQDNs on which you can reach your server? Ergo: do you actually have hosts in the `.nexus` TLD?
- The SRV record is clearly not configured to point to your server.
