### ISSUE TITLE
Send EDUs to appservices

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2954]
Spec bug: https://github.com/matrix-org/matrix-doc/issues/1145

The use case being bridging read receipts, typing notifications, etc to another network.

**Comment by anoadragon453** [comment]
Note that some EDUs are now sent after https://github.com/matrix-org/synapse/pull/8437. `ToDevice` messages are still missing however, which are useful for allowing application services to participant in encrypted rooms (among other things).

**Comment by clokep** [comment]
> Note that some EDUs are now sent after https://github.com/matrix-org/synapse/pull/8437. `ToDevice` messages are still missing however, which are useful for allowing application services to participant in encrypted rooms (among other things).

@anoadragon453  it looks like #11215 added support for `ToDevice` messages, does that mean this can now be closed?

**Comment by anoadragon453** [comment]
Yes, I think so. Consider though that they are still behind several experimental feature flags, and are missing important production-ready features such as retrying failed transactions.

But the feature exists and can be tried out today.
