### ISSUE TITLE
Kicking non-existent users not properly rejected

### ISSUE THREAD

**Issue by dkasak** [matrix-org/synapse#2959]
### Description

Kicking a non-existent user doesn't return a 403 as [the spec suggests it should](https://matrix.org/docs/spec/client_server/r0.3.0.html#id206). The server accepts the message and sends out a `"membership": "leave"` event with the `state_key` referring to the non-existent user (possibly including whitespace).

This confuses at least Riot desktop, producing the following outcome even though the user `foo@bar.baz` isn't in the room:

![foo@bar.baz leaves the room, even though he doesn't exist](https://i.imgur.com/x6fG40o.png)

Furthermore, whitespace can be embedded in the `user_id` when executing the kick, making the problem even worse because you can spoof very realistic looking but fake events about real users. For instance, by kicking user `@nonexistent:example.com joined, @realuser:example.com`, you can make Riot produce a message making it appear as if a non-existent user joined and some other real user left the room, while nothing actually happened: ![](https://i.imgur.com/S9RbYvs.png)

### Steps to reproduce

* Send a `POST` to `<server>/_matrix/client/r0/rooms/<room>/kick?access_token=<access_token>` with `{"user_id":"@nonexistent:example.com"}` in the body.

#### Expected:
The server returns a 403 and doesn't send out a "leave" event.

#### Observed: 
The server accepts the event and does send out a "leave" event.

### Version information

This was tested on our homeserver, running Synapse 0.26.0 on FreeBSD 11.1, installed using FreeBSD's `pkg`. The package is `py27-matrix-synapse-0.26.0`.

**Comment by Half-Shot** [comment]
Yep. Reproducible https://matrix.to/#/!UcYsUzyxTGDxLBEvLz:matrix.org/$15204639642978TqoPl:half-shot.uk

**Comment by squahtx** [comment]
Closing this in favour of #7937.
