### ISSUE TITLE
integration with Jisti

### ISSUE THREAD

**Issue by JarodWan** [matrix-org/synapse#2971]
### Description

Dear, at first, thanks for everyone work on the Matrix, it is an amazing system.
currently we are working to deploy Matrix in our private cloud and use it as our Internal Message system, and in the feature , we hope it can work as Collaboration tools

 currently, we meet some problem about integration, for on the blog, there said synapse or maybe can say Riot had integrative with Jisti, and can use as a Widgets. and we found Riot iOS client had a button to enable/disable the feature.

but how to implement it? from synapse server or from some side?
could anybody help give a guide about it?

thanks a lot   

### Version information

- **Install method**:   debian package   
- **Platform**:       virtual machine, ESXi, Ubuntu 16.04.3

**Comment by KuenzelIT** [comment]
Hi,

this issue is quite old but I was just looking for the same information and found that you need an integration server like [Dimension](https://dimension.t2bot.io/).

I assume this issue can be closed.

**Comment by babolivier** [comment]
Yes probably.

Heads up that Riot v1.15.14 (which should be released shortly - rc1 is already available on https://riot.im/staging) will remove the need for an integration manager to use Jitsi with Riot.

**Comment by KuenzelIT** [comment]
> Heads up that Riot v1.15.14 (which should be released shortly - rc1 is already available on https://riot.im/staging) will remove the need for an integration manager to use Jitsi with Riot.

Nice!
