### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by mcat-ee** [matrix-org/synapse#2972]
### Description
The timestamps in the chats do not match up with my local or server time.
How can I configure the timezone for my homeserver?
Cheers!

### Steps to reproduce

N/A

### Version information

- **Homeserver**: My own
- **Version**:        latest
- **Install method**: package manager      
- **Platform**:      Centos, VPS

**Comment by neilisfragile** [comment]
Is the clock on your home server correct?
