### ISSUE TITLE
Nuke room script doesn't completely remove matrix HQ

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#3001]
### Description

It seems like you end up with a corrupt matrix HQ room: every few days, the room reappears in your room list, but not correctly: the room has no name then. It is listed with the roomname just "$some_username and 487 others" or such and the URL is just like `!cURbafjkfsMDVwdRDQ:matrix.org`  .  
You can then leave the room again, but after a few days it will reappear again and again.

### Steps to reproduce

- using **postgresql** use the [nuke-room-from-db.sh](https://github.com/matrix-org/synapse/blob/master/scripts-dev/nuke-room-from-db.sh) script from my PR https://github.com/matrix-org/synapse/pull/2337 on the "Matrix HQ" room
- This seems to really delete the room, and it will first disappear from your room list in Riot
- wait a few days

### Version information

- **Homeserver**: my own homeserver
- **Version**:       0.26.0
- **Install method**: git clone/pip      
- **Platform**:       
  -  Debian squeeze version 9.3
  - Hardware: Intel Core™ i7-6700 Quad-Core (Hetzner EX41S),  running in a XEN vm/container (xen 4.6)
- Version of riot-web: 0.13.5

**Comment by richvdh** [comment]
nuke-room-from-db isn't supported.
