### ISSUE TITLE
Wrong version number for tag v0.27.0-rc1

### ISSUE THREAD

**Issue by schnuffle** [matrix-org/synapse#3004]
### Description

Synapse fails to start:

Mar 15 14:36:31 kolab python2.7: 2018-03-15 14:36:31,344 - twisted - 131 - INFO - - Main loop terminated.
Mar 15 14:38:53 kolab python2.7: Missing Requirement: Unexpected version of 'pynacl==0.3.0' in '/home/synapse/pyenv/lib/python2.7/site-packages/nacl/__init__.pyc'. '1.2.1' != '0.3.0'
Mar 15 14:38:53 kolab python2.7: To install run:
Mar 15 14:38:53 kolab python2.7: pip install --upgrade --force "pynacl==0.3.0"
Mar 15 14:45:12 kolab python2.7: Missing Requirement: Unexpected version of 'pynacl>=0.3.0' in '/home/synapse/pyenv/lib/python2.7/site-packages/nacl/__init__.pyc'. '1.2.1' != '0.3.0'

### Steps to reproduce
.  pyenv/bin/activate
git clone https://github.com/matrix-org/synapse
cd synapse
git checkout v0.27.0-rc1
python synapse/python_dependencies.py | xargs -n1 pip install --upgrade
pip install .

### Patch

diff --git a/synapse/__init__.py b/synapse/__init__.py
index ef8853b..d72d88b 100644
--- a/synapse/__init__.py
+++ b/synapse/__init__.py
@@ -16,4 +16,4 @@
 """ This is a reference implementation of a Matrix home server.
 """
 
-__version__ = "0.26.0"
+__version__ = "0.27.0-rc1"

**Comment by erikjohnston** [comment]
Fixed, thanks!

**Comment by schnuffle** [comment]
Now that was fast, Already thought I had posted the issue to the wrong repo.

Thanx
