### ISSUE TITLE
user_ids aren't escaped when generating urls [sending invites, joining rooms, etc] for federation use.

### ISSUE THREAD

**Issue by walle303** [matrix-org/synapse#3019]
As `/` is an allowed character in user ids, they need to be escaped when generating urls, because right now if you have a `/` in your username and try to join a room or send an invite over federation, synapse generates urls like `.../@user/id/with/forward/slashes/in/it:domain`. 
These, for obvious reasons, do not work. Instead they should be properly escaped, so `.../%40user%id%2Fwith%2Fforward%2Fslashes%2Fin%2Fit%3Adomain` would be used instead, or, at least escape localparts, so `.../@user%2Fid%2Fwith%2Fforward%2Fslashes%2Fin%2Fit:domain` instead.

**Comment by richvdh** [comment]
fixed by #3082
