### ISSUE TITLE
Cannot reject/delete old invite

### ISSUE THREAD

**Issue by Famicoman** [matrix-org/synapse#3021]
### Description

Cannot delete an old invite I've had for probably a year. It's for a global IRC server message as far as I can tell, but I was never able to ever check it out.

I don't want this to appear anymore.

### Steps to reproduce
* Go to invite
* Click "decline"
* Get error: 
```
Failed to reject invite
Room '!xLjWrMzTLjNjSLUXbS:matrix.org' does not exist
```

### Version information

* **Homeserver**: matrix.phillymesh.net
* **Version**: v0.26.1
* **Install method**: pip     
* **Platform**: Debian 8 VPS

**Comment by richvdh** [comment]
Probably a duplicate of https://github.com/matrix-org/synapse/issues/1987 - the bug has since been fixed but people can still have stuck invites from before it was fixed. If it is the same issue, the invite can be cleared by marking the invite as locally rejected in the `local_invites` table. Something like:

```
UPDATE local_invites SET locally_rejected=1 WHERE room_id='!xLjWrMzTLjNjSLUXbS:matrix.org' AND NOT locally_rejected AND replaced_by IS NULL;
```

(then restart synapse, then clear client caches)

**Comment by Famicoman** [comment]
Hmm, something still seems up. After updating the offending record, restarting synapse, and clearing my android client cache, I still have the stuck invite.  

It looks related to the "can't reject invite a third time" issues since I have 3 records for the room id:

```
select * from local_invites where room_id='!xLjWrMzTLjNjSLUXbS:matrix.org'
;
 stream_id |          inviter          |          invitee          |              event_id              |            room_id             | locally_rejected |            replaced_by
-----------+---------------------------+---------------------------+------------------------------------+--------------------------------+------------------+------------------------------------
     20191 | @_rizon_Global:matrix.org | @Famicoman:phillymesh.net | $149512418114912BrcAW:matrix.org   | !xLjWrMzTLjNjSLUXbS:matrix.org |                  | $1495124397751LFBUM:matrix.org
     24150 | @_rizon_Global:matrix.org | @Famicoman:phillymesh.net | $14956302571458665qJFlP:matrix.org | !xLjWrMzTLjNjSLUXbS:matrix.org |                  | $14956381811587072lYVBG:matrix.org
     24476 | @_rizon_Global:matrix.org | @Famicoman:phillymesh.net | $14956573511912712JAgpR:matrix.org | !xLjWrMzTLjNjSLUXbS:matrix.org | 1                |
(3 rows)

(END)
```

I had previously updated the table based on your suggestion with:

```
update local_invites SET locally_rejected=1 where room_id='!xLjWrMzTLjNjSLUXbS:matrix.org' AND replaced_by IS NULL;
```

**Comment by richvdh** [comment]
> Doing local reject and clearing cached worked for me.

then it's *not* the same issue and is in fact #2181

**Comment by Half-Shot** [comment]
I have the same issue where I cannot reject and they aren't rejected locally either.
``select * from local_invites`` shows my two invites without anything in the ``locally_rejected`` column. I'll update them to be locally rejected.

**Comment by aveao** [comment]
richvdh: It wasn't locally rejected until I manually did, similar to Half-Shot's situation.

**Comment by Half-Shot** [comment]
I'm going to have to uncomplain and say the issue was down to a worker that was failing to join the rooms, rather than this issue. Also, sorry to anyone who I have now deleted the invite for. #3333

**Comment by richvdh** [comment]
@Famicoman are you still seeing this problem?

**Comment by Famicoman** [comment]
Worked itself out at some point, closing.
