### ISSUE TITLE
Removing every member from a comminuty leaves behind a dead community

### ISSUE THREAD

**Issue by dragetd** [matrix-org/synapse#3023]
If every member of a community leaves it, the community is still saved on the server and blocks the name. Like this (kind of accidental) test-community I created:
https://riot.im/app/#/group/+bobbycar:matrix.org

I could imagine that there are more ghost-communities on the servers. It would be nice if a community could be purged once it is empty.

**Comment by Kr4ken-9** [comment]
+1, created a test community: https://riot.im/app/#/group/+thanking:matrix.org and I can't reclaim the id.

**Comment by Matombo** [comment]
+1 Just updated my merge request #3401 that would help with this issue.

**Comment by Matombo** [comment]
There is now an api to remove a group https://github.com/matrix-org/synapse/blob/master/docs/admin_api/delete_group.md
What's missing is something that scans the server for empty groups and calls the api automatically.
At he Repo maintainers: Is there intresst in such an automation? Then i would try to code it.

**Comment by anoadragon453** [comment]
I would modify [`delete_group_summary_user`](https://github.com/matrix-org/synapse/blob/54fef094b31e0401d6d35efdf7d5d6b0b9e5d51f/synapse/groups/groups_server.py#L360) to check whether there are any users left after deleting one, and if not then delete the group. Be aware that this function is called both from [the CS API](https://github.com/matrix-org/synapse/blob/4548d1f87e3ff3dc24b0af8f944276137d3228e3/synapse/rest/client/v2_alpha/groups.py#L322) and the [Federation API](https://github.com/matrix-org/synapse/blob/0f87b912aba7e678041632bc9a6d1f7c2d24342c/synapse/federation/transport/server.py#L1299).

However, that would not cover the groups that are already dead and without users. For cleaning those up, I would create a [delta file](https://github.com/matrix-org/synapse/tree/master/synapse/storage/data_stores/main/schema/delta/56) with a line of SQL to delete all groups without any remaining users in them. This will go when Synapse is first run after upgrade to a version containing this delta file.

**Comment by Matombo** [comment]
Just a quick addition, the correct function to modify would be https://github.com/matrix-org/synapse/blob/54fef094b31e0401d6d35efdf7d5d6b0b9e5d51f/synapse/groups/groups_server.py#L745
I will look into it

**Comment by Matombo** [comment]
Can be closed now can't it?

**Comment by dragetd** [comment]
Yep!
