### ISSUE TITLE
It's possible to /sync rooms with partial state.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3028]
I'm sure this is a dup but I can't find the original, but it's still way too easy to end up with your client seeing a room with partial state.

Just had a great instance of this in HQ with brt on the elevate.at HS getting desktop notifs in Riot for a room he wasn't in.  Tapping on the notifs would show a peek into a room with 3 people, none of which were him.  Turns out this was a partial view of #test:matrix.org.  Looks like:

 * There was a state reset that pulled him back into #test:matrix.org
 * The state of #test:matrix.org was then partially synced with his HS
 * The HS synced the partial state to his Riot
 * Riot then failed to recover from this without clearing cache (probably https://github.com/matrix-org/synapse/issues/2735?)

Surely state syncs should always be atomic to stop this sort of mess from happening?

**Comment by richvdh** [comment]
state syncs /are/ atomic. What evidence do you have that this isn't just #2735 ?

**Comment by ara4n** [comment]
the only evidence is that i was surprised that we had only ~3 state events in a room that should have however many thousand.  If it's possible for #2735 to produce this behaviour, then perhaps it's the same thing.

**Comment by richvdh** [comment]
well, the point of #2735 is that synapse will just tell a client the new events that have arrived since your last sync - which may well just be a couple of member events.

Closing as a dup of #2735.
