### ISSUE TITLE
docker repository changed. 

### ISSUE THREAD

**Issue by andreaspeters** [matrix-org/synapse#3039]
Hi,

Silvio stopped to maintain docker-matrix. We (https://github.com/AVENTER-UG/docker-matrix) took it over. It would be nice if you can update the link in your readme to the new docker repository: https://hub.docker.com/r/avhost/docker-matrix/tags/

We done some changes. First, we changed to the smaller "debian:stretch-slim" and second, like u see, we are using tags for our docker images. In a production environment is it very necessary. :-)

To be sure that we maintain the image, you can verify it via a issue in silvios repo. I will give you a answer there. :-)

Have a nice day,
Andreas

**Comment by neilisfragile** [comment]
Thanks Andreas, I can see your details in the Silvio's docker hub. Updated.
