### ISSUE TITLE
matrix synapse installation issue

### ISSUE THREAD

**Issue by ogiright123** [matrix-org/synapse#3040]
i installed and runned  matrix synapse in my own server.
i can register and login in my own server with riot.im  app.
But i cant search users with id , email and phone number.
how does it fix ?
if this is identify server issue, although identify server doesnt exist, users can search another man with id.
is correct?

**Comment by hawkowl** [comment]
There's not enough information here to help. If this is still a problem, drop by #matrix-hq:matrix.org and we can try and help.

**Comment by shibinmp3** [comment]
Hi, I am using centos7 when i run the command synctl1, I am new to python and linux. please help


(synapse) [root@s148-72-210-106 synapse]# sh synctl start
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
/opt/synapse/bin/synctl: line 29: from: command not found
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
/opt/synapse/bin/synctl: line 33: SYNAPSE: command not found
/opt/synapse/bin/synctl: line 35: GREEN: command not found
/opt/synapse/bin/synctl: line 36: YELLOW: command not found
/opt/synapse/bin/synctl: line 37: RED: command not found
/opt/synapse/bin/synctl: line 38: NORMAL: command not found
/opt/synapse/bin/synctl: synctl: line 41: syntax error near unexpected token `('
/opt/synapse/bin/synctl: synctl: line 41: `def pid_running(pid):'
(synapse) [root@s148-72-210-106 synapse]# /opt/synapse/bin/synctl: line 29: from: command not found
bash: /opt/synapse/bin/synctl:: No such file or directory
