### ISSUE TITLE
Federation does not work / Some Questions

### ISSUE THREAD

**Issue by mracreep** [matrix-org/synapse#3057]
### Description

I can't get Federation running. There are a few things i don't understand after reading through the Documentation.

I can login to my server and send messages on it.

Im sorry in advance to create an Issue for that maybe it is just my personal fault, but the Readme file here was the only documentation about matrix/synapse i could find, so i dont know where else to ask.

### Steps to reproduce

I have changed the hostname of my raspberry to "mydomain.com" AND additionally created the SRV-Record. 

I used the standard self-signed Certificate from Synapse and i forwarded Port 8448 to WAN
Port 8008 is not forwarded (Does it need to??)

For checking the SRV-Record i did the following:

dig -t srv _matrix._tcp.mydomain.com

Output (anonymized):
```
...
;; QUESTION SECTION:
;_matrix._tcp.mydomain.com.       IN      SRV

;; AUTHORITY SECTION:
mydomain.com.             1976    IN      SOA     dns1.registrar-servers.com. hostmaster.registrar-servers.com. 2018040304 43200 3600 604800 3601
...
```

It seems that my SRV record does not work properly, right? But i dont know why.

My domain is hosted by namecheap and when setting up the SRV-Record i got the following fields to fill in which i filled like follows:

Service: _matrix
Protocol: _tcp
Priority: 10
Weight: 0
Port: 8448
Target: mydomain.com
TTL: 30 mins

Ist that right this way or not? (Its the first time, im in need of an SRV Record)

**But anyway, it should also work without the SRV because i changed my hostname to mydomain.com, right?**

Addition:

When testing through the Federation tester with "mydomain.com" it says AllChecksOK=true
but when i check it with mydomain.com:8448 it says MatchingServerName=false
but with the default configuration i need it working on port 8448, right?

### Version information

Newest Packages on Debian Jessie (Raspberry PI)

**Comment by krombel** [comment]
What means "changed the hostname"? Is that the server_name config in homeserver.yaml?
If not that info should be irrelevant for synapse.
Is it possible to reach synapse on port 8448 from the internet?
You might use the federationtester to get some tips for resolving your issue. Just open that url:
https://matrix.org/federationtester/api/report?server_name=mydomain.com

**Comment by mracreep** [comment]
@krombel 
* My server_name in the config is equal to "mydomain.com" as well as the hostname of my vm.
*Yes i can reach the Webinterface of Synapse via https://mydomain.com:8448, i also can login and send messages to other users on my server.
* When i use the Federationtester like above it says AllChecksOK.
*But when i add the Port 8448 at the end of the link it says MatchingServerName=false. Could that be the point where i did something wrong?

**Comment by neilisfragile** [comment]
A very good place to get help is #synapse-community:matrix.org - though if you can't federate you'll need to come in through matrix.org (or some other existing homeserver)

If you try there and get don't make progress ping me on @neilj:matrix.org

I'm going to close this, since as you suggest this looks like configuration rather than a Synapse issue.
