### ISSUE TITLE
synapse ignores the app_name setting in homeserver.yaml

### ISSUE THREAD

**Issue by git-minix** [matrix-org/synapse#3064]
### Description

synapse ignores the app_name setting in homeserver.yaml
`homeserver.yaml
email:
   app_name: Matrix`

synapse/push/mailer.py:  
`self.app_name = app_name
...
logger.info("Created Mailer for app_name %s" % app_name)`

homeserver.log: - synapse.push.mailer - 91 - INFO - - Created Mailer for app_name Riot

### Steps to reproduce

- set app_name: Matrix in the email section of homeserver.yaml 
- activate email notification enable_notifs: True
- force a email notification
- check the Mail Header of the sent email

I get in every case [Riot] and not [Matrix] in the email subject of the notification email.

### Version information

- **Version**:        0.27.2-1
- **Install method**: apt-get install (deb https://matrix.org/packages/debian/ jessie main)
- **Platform**:  Debian 8.10

**Comment by krombel** [comment]
As you can see here the setting of "app_name" is only used as a fallback:
https://github.com/matrix-org/synapse/blob/691f8492fb882d4e270993743ff928328a8e97e9/synapse/push/pusher.py#L73-L77

So it might be expectable to be not used

**Comment by git-minix** [comment]
@krombel Thanks for this hint. Looks this is no bug but a feature. Actually, I just wanted to customize the subject in the notification e-mail. Similar to the "notif_from:" setting in homeserver.yaml. For our users the label "[Riot]" in the subject line leads to misunderstandings. I want to avoid a dirty patch in synapse/synapse/push/pusher.py
`multipart_msg['Subject'] = "[matrix] %s" % (summary_text)`

**Comment by richvdh** [comment]
could you host your own Riot and change the `brand` setting?
