### ISSUE TITLE
how to set up synapse autostart when i reboot my system

### ISSUE THREAD

**Issue by sjnhnp** [matrix-org/synapse#3087]
ubuntu16.04, installing from source

after i reboot my system, i always need  Manually start synapse

cd ~/.synapse
source ./bin/activate
synctl start

so how to set up autostart 

thank you

**Comment by krombel** [comment]
Depends on the system you want to use to autostart.
Do you use systemd? Then look [here](https://github.com/matrix-org/synapse/tree/master/contrib/systemd)
When you prefer init.d have a look [here](https://github.com/matrix-org/package-synapse-debian/blob/debian/debian/matrix-synapse.init)

**Comment by sjnhnp** [comment]
@krombel   thankyou

but i dont know how to set up 1 or 2
1、Do you use systemd? Then look here
2、When you prefer init.d have a look here

**Comment by krombel** [comment]
@sjnhnp do one of the following:
For 1: Copy the file to `/etc/systemd/system/$1.service` and adjust the paths.
Then run
```
systemctl daemon-reload
systemctl enable $1
systemctl start $1
```

For 2.: Copy the linked file to `/etc/init.d/$1` and adjust the paths as well if needed
Afterwards it might work with
```
update-rc.d $1
service $1 start
```

**Comment by sjnhnp** [comment]
@krombel  for1 when systemctl start $1

and use ：systemctl status synapse
● synapse.service - Synapse Matrix homeserver
   Loaded: loaded (/etc/systemd/system/synapse.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-04-11 14:34:52 UTC; 2min 16s ago
  Process: 2592 ExecStop=/root/.synapse/synctl stop /root/.synapse/homeserver.yaml (code=exited, status=217/USER)
  Process: 2590 ExecStart=/root/.synapse/python2.7 -m synapse.app.homeserver --config-path=/root/.synapse/homeserver.yaml (code=exited,
 Main PID: 2590 (code=exited, status=217/USER)

**Comment by krombel** [comment]
@sjnhnp The paths are not adjusted correctly. Does every file you refer to really exist?
And is it accessible for the user you set in `synapse.service`?
e.g. I assume `/root/.synapse/synctl` should be `/root/.synapse/bin/synctl` in your case.
As the paths let me assume you want to run synapse as root. This is **not recommended**!
Do yourself a favor and move that somewhere else to be able to run it as a non-root user

Btw: This is a support question - not really an issue with synapse itself. I would suggest closing this issue and asking further questions in [#synapse-community:matrix.org](https://matrix.to/#/#synapse-community:matrix.org)

**Comment by sjnhnp** [comment]
haha thankyou  it is done
