### ISSUE TITLE
Add six as dependency

### ISSUE THREAD

**Issue by NotAFile** [matrix-org/synapse#3089]
Just a quick tracking issue to remember to add six as dependency. It is currently used, but it's just an indirect dependency of many other packages. For clarity, it would be good to add it to the dependencies. I'm not sure how to do it myself, the file is non-standard.

**Comment by richvdh** [comment]
just add it to python_dependencies.py iirc

**Comment by NotAFile** [comment]
There's multiple fields and sometimes they are the same and sometimes they are not and sometimes the versions are pinned and sometimes not. So I'd rather a person familiar with how and why do it.
