### ISSUE TITLE
How to dock AWS S3 storage as where uploaded image and files are placed

### ISSUE THREAD

**Issue by dcb1** [matrix-org/synapse#3119]
### Description

How to dock AWS S3 storage as where uploaded image and files are placed?

I see the configuration in homeserver.yaml as follows:
`media_store_path: "/var/lib/matrix-synapse/media"`

Using local filesystem to store media is not a good idea,
the security and extensibility  are not good, so I want to use AWS S3 or google storage to do this,
but I don't know how to config it.

Anyone can help?
thx!  

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
- **Version**:        0.27.4 
- **Install method**: package manager   
- **Platform**:       ubuntu16

**Comment by krombel** [comment]
Good to know. Thanks for pointing that out @turt2live

**Comment by dcb1** [comment]
Thanks, I will try it!

**Comment by neilisfragile** [comment]
Closing given #1749
