### ISSUE TITLE
Application Service API (PUT transaction) weird behaviour

### ISSUE THREAD

**Issue by oliverjanik** [matrix-org/synapse#3132]
https://matrix.org/docs/spec/application_service/unstable.html

Under `2.2.3.1   PUT /transactions/{txnId}` it says:

```
Response:

Status code 200:

The transaction was processed successfully.

Example

{}
```

It's not very clear that Synapse expects an empty json object back.  I just had a 200 with empty response and it kept re-sending transaction 1.

I guess it's either a Synapse bug or the spec should be clearer?

**Comment by neilisfragile** [comment]
The alternative is to return a 204 No Content - we do it this way (as a convention across the spec) to make it easier to add content in the future without having to change the response code.

**Comment by oliverjanik** [comment]
It makes sense, I just completely missed that {} is an empty json object and it's mandatory.

**Comment by richvdh** [comment]
seems like a spec issue
