### ISSUE TITLE
Enforce Server-Server 4.1 PDU fields

### ISSUE THREAD

**Issue by jevolk** [matrix-org/synapse#3162]
The specification states in [server-server 4.1 PDU fields](https://matrix.org/docs/spec/server_server/unstable.html#pdu-fields):

> depth | Integer | Required. The maximum depth of the prev_events, plus one

Synapse accepts events with depths that are not the maximum depth of the `prev_events`, plus one. The solution is to only accept events with depths that are the maximum depth of the `prev_events`, plus one.

**Comment by richvdh** [comment]
dup #1254, though really we should just not rely on `depth` at all.
