### ISSUE TITLE
Cleaning an Home Server

### ISSUE THREAD

**Issue by ArchangeGabriel** [matrix-org/synapse#3167]
Sorry if I missed information somewhere, but I cannot find how to “clean” an home server.

Basically, I would want to remove:
– communities with no-one inside (basically were created as tests);
– local rooms or copy of federated rooms for which no local user are inside anymore.

Currently I think there is a growing number of “dead rooms” (and associated content) on my HS, and I’d like to get ride of them.

Thanks for your help!

**Comment by krombel** [comment]
@ArchangeGabriel: I do not know any official announced way to do your tasks.
As a (temporary?) solution you might want to use [synapse_janitor](https://github.com/xwiki-labs/synapse_scripts). It at least does the second task.
I do not know any way to cleanup empty communities.

**Comment by ArchangeGabriel** [comment]
This assumes synapse use PostgreSQL, which is not the case for me (synapse stores it DB under `/var/lib/synapse/homeserver.db` and I have no postgresql installed).

**Comment by ArchangeGabriel** [comment]
OTOH I should maybe port my existing DB (which is thus sqlite3) to PostgreSQL anyway, after what I should be able to clean it.

**Comment by neilisfragile** [comment]
Definitely recommend postgres for anything other than very low usage - if you are at the point where you care about clean up, then postgres sounds like a good choice.

**Comment by ArchangeGabriel** [comment]
OK, will do. I’ve also discovered https://github.com/matrix-org/synapse/blob/master/scripts-dev/nuke-room-from-db.sh, but I suppose synapse_janitor is already doing the same thing automatically for all relevant rooms?

Also, are empty communities and “dead” media files (in the sense of not being used by any existing rooms any more) cared of by this?

**Comment by neilisfragile** [comment]
A very quick look at Janitor suggests that it has the same/similar delete logic as the nuke-room-from-db 

neither nuke-room or janitor support purging empty communities I'm afraid.

**Comment by neilisfragile** [comment]
#3187 is a relevant issue to track the gap

**Comment by ArchangeGabriel** [comment]
Hum not really, it’s about deleting rooms from communities, not empty communities.

**Comment by neilisfragile** [comment]
Oh fair point, have created #3206
