### ISSUE TITLE
Support bionic (18.04) in the debian repositories

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3169]
Currently, https://matrix.org/packages/debian/dists/ only has as far as yakkety, which was 3 releases ago. Even if it's not going to add any new package dependencies, it would be a better user experience to include bionic as a deb option so I don't have to manually downgrade it back to yakkety. (Ideally the other's too, but bionic should surely be included as an LTS release)

**Comment by richvdh** [comment]
done, though I have to say I've not given it a lot of testing.
