### ISSUE TITLE
Purge-API - delete old ciphertexts

### ISSUE THREAD

**Issue by ukcb** [matrix-org/synapse#3189]
The cleanup with Purge History API does not work in database tables device_inbox, events, and event_json of type m.room.encrypted. The old encrypted texts are still in the database.

debian stretch and matrix-synapse v0.28.1 with postgresql

**Comment by richvdh** [comment]
it certainly does work on `events` and `event_json`.

**Comment by ukcb** [comment]
@richvdh Yes, I looked again into the database. It probably only affects the table `device_inbox.`

**Comment by richvdh** [comment]
the purge api doesn't apply to device_inbox.

**Comment by richvdh** [comment]
(see also https://github.com/matrix-org/synapse/issues/3599)
