### ISSUE TITLE
IOS notification from Backend 

### ISSUE THREAD

**Issue by saroar** [matrix-org/synapse#3192]
how to setup server so my ios app will get push notification thanks I clone this app https://github.com/vector-im/riot-ios working fine except notification on my ios

**Comment by krombel** [comment]
@saroar You might ask this question in [#riot-ios:matrix.org](https://matrix.to/#/#riot-ios:matrix.org) as that is a client specific question.
The client tells the server an URL of a push-gateway URL which synapse then uses.
