### ISSUE TITLE
static private rooms that always stay private

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#3210]
At the moment, a private room can always be made public later.

To increase acceptance, there should be a way to mark a room's state as static, ie. private with no way to change to public.

**Comment by richvdh** [comment]
by "private room" you mean one that is invite-only?

This would be a change to the spec, so needs filing at matrix-doc really.

**Comment by rubo77** [comment]
I thought especially about rooms between only 2 users where they speak about confidential things.

Maybe there could be a new option for invite-only-if-all-room-members-agree

**Comment by neilisfragile** [comment]
By filing he means creating an issue against https://github.com/matrix-org/matrix-doc

**Comment by rubo77** [comment]
should I restart this issue there as it is?

**Comment by neilisfragile** [comment]
Yes please, I had a look to see if something like this had already been filed (I've heard this request before) but couldn't find anything.

**Comment by rubo77** [comment]
I filed it here: https://github.com/matrix-org/matrix-doc/issues/1246
