### ISSUE TITLE
Redact does not actually redact all content

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3211]
When we redact an event, its content still hangs around in the database.

**Comment by richvdh** [comment]
(we'll be fixing this for GDPR)

**Comment by richvdh** [comment]
There is an argument that the content should only actually be deleted after a delay (configurable by the server admin) so that server admins can see whether the redacted messages were used for offensive/abusive content.

**Comment by richvdh** [comment]
[related: https://github.com/matrix-org/synapse/issues/1263]

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/1287

**Comment by richvdh** [comment]
thanks
