### ISSUE TITLE
Changing parameter in non-federated rooms?

### ISSUE THREAD

**Issue by ArchangeGabriel** [matrix-org/synapse#3216]
Is is possible to change some parameters in (yet) non-federated rooms? I have especially in mind:

– Who can access the room?
– Room name/main address.
– Whether the room is federated or not.

I’ve messed up my initial setup of IRC bridging, but I don’t want to lose the history of the existing rooms. Maybe there is some workaround with deleting the rooms, recreating them and inserting the history back into them?

**Comment by Half-Shot** [comment]
A room that is federation disabled cannot be enabled. You may change the other parameters if you are an admin in the room.

**Comment by ArchangeGabriel** [comment]
OK, I see… In this case admin is the matrix-appservice-irc bridge, so it would require recreating the room I guess. Well anyway I figured they would be other issues on IRC side, so I will just forget about it. Thanks for your input anyway!
