### ISSUE TITLE
Wrong API Endpoint in Upgrade Instructions

### ISSUE THREAD

**Issue by chris-aeviator** [matrix-org/synapse#3219]
### Description

The Upgrade Guide states in order to check the Version number of synapse to use the api endpoint ```_matrix/client/versions ```

### Steps to reproduce

- Goto https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst
- check the Version Query Endpoint
- Version query does not return the current synapse version

Describe how what happens differs from what you expected.

The Version endpoint also appears here in the github issue template and should be corrected to ```/_matrix/federation/v1/version```

### Version information
0.28

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?
another Homeserver
If not matrix.org:
- **Version**:        0.28
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Install method**:  docker-matrix
- **Platform**:       Digitial Ocean Ubuntu 16.04 Droplet

**Comment by richvdh** [comment]
Nope, that's the right endpoint. Note that it requires you to grep for `Server` in the HTTP headers (which your reverse-proxy may be overwriting, if you have one).

The problem with using the federation endpoint is that it may well not be exposed on the client port.

**Comment by chris-aeviator** [comment]
when querying against that endpoint I won't get the right answer. The reply show's me my NGINX Version (when grepping) and a list of version that do not represent my synapse version whereas the federation endpoint gives me the correct nuber.

## reply
```{"versions": ["r0.0.1", "r0.1.0", "r0.2.0", "r0.3.0"]}```

## server header
server: nginx/1.13.8

**Comment by chris-aeviator** [comment]
> which your reverse-proxy may be overwriting, if you have one

yes, I have a reverse-proxy in place  - which is a pretty common scenario IMO. It should be possible to have a way to consitently getting the version number of synapse.

**Comment by richvdh** [comment]
As I said, your reverse-proxy is overwriting it.

I don't say it's ideal, but your suggestion won't work for a lot of people.

**Comment by richvdh** [comment]
closing in favour of https://github.com/matrix-org/synapse/issues/3220
