### ISSUE TITLE
Getting version number of running synapse is unreliable

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3220]
UPGRADE.rst and ISSUE_TEMPLATE.md both suggest inspecting the `Server` header of a REST response to get the running synapse version, which doesn't work for people using a reverse-proxy which overwrites the Server header.

Other popular options include:

* using the federation/v1/version endpoint (doesn't work for those who don't have federation endpoints exposed on the client port)
* reading the logs
* inspecting `synapse/__init__.py`

None of those are foolproof. Maybe we should just add something to the admin api to give the running version number?

**Comment by svmhdvn** [comment]
I can work on this if it's still open

**Comment by neilisfragile** [comment]
hey @svmhdvn great that you want to contribute, suggest you join #synapse-dev:matrix.org and talk to the team before diving in.

**Comment by erikjohnston** [comment]
Fixed by #4772

**Comment by richvdh** [comment]
yeeeahish, though we still ought to update the docs that reference the old way.

**Comment by richvdh** [comment]
gonna close this and open a new one for the docs part
