### ISSUE TITLE
Readme on docker hub is hard to read

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3224]
https://hub.docker.com/r/matrixdotorg/synapse/

It looks like it's taking the RST and interpreting it as markdown. Someone with permissions should probably take out the irrelevant sections and fix it up a little bit.

**Comment by mvgorcum** [comment]
Because it's taking the readme it also contains a lot of information that is not relevant for the docker container (such as the installing from source section).

**Comment by Ezwen** [comment]
According to the Docker Hub documentation, Docker Hub automatically displays the README file found in the same folder as the `Dockerfile`: https://docs.docker.com/docker-hub/builds/#understand-the-build-process

And it seems that Docker Hub supports having a Dockerfile in a dedicated folder, instead of the root folder: https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build

Therefore maybe the `Dockerfile` could be moved to `contrib/docker`?

**Comment by neilisfragile** [comment]
Thanks all for highlighting - let me check with @michaelkaye

**Comment by michaelkaye** [comment]
Hi there; thanks for noticing and letting us know.

I didn't realise that dockerhub overwrote the readme on each build -- we're probably going to have to think carefully about how to version new environment variables in the configuration options section.

For now, I think we should probably push the Dockerfile, README and start.sh into a /docker folder in the root. It makes the command to build a little harder, but I don't think we should consider the docker file part of /contrib/ any more - we're pushing the images to the matrixdotorg account as part of the build process.

**Comment by michaelkaye** [comment]
I've disabled the automatic build for now, and updated the docker description with something more suitable to that purpose - https://hub.docker.com/r/matrixdotorg/synapse/

Once we rearrange we can re-enable the auto-build, and we'll have that done before the next release (so from then on it'll be all fine)

**Comment by ptman** [comment]
If this is indeed the correct issue for automated docker builds: could you please add building docker images for releases to some manual checklist until it is automated?

**Comment by richvdh** [comment]
fixed by #3644
