### ISSUE TITLE
Add server_notices section to Docker configuration template

### ISSUE THREAD

**Issue by Ezwen** [matrix-org/synapse#3284]
Since synapse 0.30, server notices are available, and require to add a few lines into the configuration file as explained here : https://github.com/matrix-org/synapse/blob/master/docs/server_notices.md

However, the configuration file automatically generated in the Docker image does not yet contain such new lines, as can be seen in the current template: https://github.com/matrix-org/synapse/blob/master/contrib/docker/conf/homeserver.yaml

I would suggest to have a default working `server_notices` section in the template, that could maybe be configured through environment variables, similarly to other options.

**Comment by michaelkaye** [comment]
It's worth noting this is possible via setting the `SYNAPSE_CONFIG_PATH` at the moment and passing a homeserver.yaml directly - while environment variables might make this easier, at some point you end up with a more compilcated set of environment variables than just the YAML.

**Comment by kaiyou** [comment]
I am working today on a PR providing environment variables for this.

**Comment by richvdh** [comment]
As @michaelkaye says, I think the correct solution here is to write your own `homeserver.yaml`; I don't think that continuing to add environment variables for every conceivable feature is sustainable, and server_notices are a sufficiently advanced feature that I don't think that they deserve this support.
