### ISSUE TITLE
"Maintenance mode" server notes

### ISSUE THREAD

**Issue by Valodim** [matrix-org/synapse#3286]
It would be very helpful to have a way to leave maintenance notes in a static way, e.g. by placing a static json file under `/_matrix/sync` or whatever endpoint riot typically looks at.

There are two use cases for this:
1) leaving a note to decommission a homeserver more gracefully than connection error / timeout
2) informing users during a maintenance window where an actual synapse server isn't available

My concrete use case is that my homeserver has a downtime due to server problems, and I would be able to divert traffic to inform users of the reasons but I can't actually get synapse up. As is, people get an unhelpful "Connection error" on riot-web or worse, "Riot is using battery" on riot-android.

I reckon this should be simple to spec and implement, and goes a long way towards smoothing over common error modes.

**Comment by r4dh4l** [comment]
Great idea, would like to have this as well!

**Comment by richvdh** [comment]
this is basically https://github.com/matrix-org/synapse/issues/1199 I think

**Comment by Valodim** [comment]
*bump because current events

Can we perhaps get a trivial solution to the exact issue specified here? The solutions referenced in #1199 are way complicated and conflate this simple issue with other mechanims until they are no longer straightforward.

**Comment by eeeeeta** [comment]
Also, as someone who used to run a HS and still gets people hitting their well-known endpoint, it would be nice to be able to put something there that says "server disused" to avoid people continuing to hit it...

**Comment by aaronraimist** [comment]
@eeeeeta that is unrelated to this issue. #3765 is what you want.

**Comment by Valodim** [comment]
I would like to bump and reopen this issue. I needed to do database maintenance today, which caused a while of downtime. Users notice this very quickly and ask me why the server is down.

It would be extremely helpful if there was a way to put a "maintenance message" in a well-known file, that riot shows to users as error while it can't connect. There is a huge difference in reassurance for users between "Connectivity has been lost!" and "Hey, the server is undergoing X and Y, it should be back up shortly. Sorry about that - Your Admin, 2020-05-06 12:15".

This issue is not addressed by #1199, which depends on synapse running!

**Comment by richvdh** [comment]
@Valodim that sounds more like a spec feature then. maybe start a proposal over at matrix-doc?

**Comment by Valodim** [comment]
Ah, that sounds reasonable. Will do, thanks for the hint! :+1:

**Comment by jpeeler** [comment]
@Valodim if you wrote up the proposal, could you put the link here?
