### ISSUE TITLE
How to connect to matrix through a WSGI application like gunicorn

### ISSUE THREAD

**Issue by mkhfring** [matrix-org/synapse#3292]
### Description

How can I use a WSGI application with matrix synapse?

### Version information

- Matrix -synapse

**Comment by NotAFile** [comment]
You can't. Why do you want this? It would make little sense, since synapse is an asynchronous application and wsgi is fundamentally synchronous.

**Comment by mkhfring** [comment]
That makes sense. thanks for your answer.
