### ISSUE TITLE
Inviting anonymous members 

### ISSUE THREAD

**Issue by mkhfring** [matrix-org/synapse#3298]
### Description

It is possible to invite people to the rooms, who don't register to matrix-synapse yet. And if this anonymous member registers in the future, she can see the room's events. 

### Steps to reproduce

- First I registered to matrix synapse  

```
 curl -XPOST -d '{"username":"example", "password":"wordpass", "auth": {"type":"m.login.dummy"}}' "https://localhost:8448/_matrix/client/r0/register"
   {
       "access_token": "MDAxYWxvY2F0aW9uIDE5Mi4xNjguMS45NQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMjhjaWQgdXNlcl9pZCA9IEBleGFtcGxlOjE5Mi4xNjguMS45NQowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25j
       "device_id": "JFRVXTNYVI",
       "home_server": "192.168.1.95",
       "user_id": "@example:192.168.1.95"
   }
```
- Then with this registered user I create a room and invite an anonymous (not yet registered) user to the room 

```
curl -XPOST -d '{"room_alias_name":"example-anonymous", "invite": ["@anonymous:192.168.1.95"]}' "http://192.168.1.95:8008/_matrix/client/r0/createRoom?access_token=MY_ACCESS_TOKEN"
  {
      "room_alias": "#example-anonymous:192.168.1.95",
      "room_id": "!KGplxzYbaUTqCjZunw:192.168.1.95"
  }

```
As it can be seen the room is created and  this anonymous guy is invited to the room without any problem
 
- Then I registered this anonymous guy to matrix-synapse 

```
curl -XPOST -d '{"username":"anonymous", "password":"wordpass", "auth": {"type":"m.login.dummy"}}' "https://localhost:8448/_matrix/client/r0/register"
  {
      "access_token": "MDAxYWxvY2F0aW9uIDE5Mi4xNjguMS45NQowMDEzaWRlbnRpZmllciBrZXkKMDAxMGNpZCBnZW4gPSAxCjAwMmFjaWQgdXNlcl9pZCA9IEBhbm9ueW1vdXM6MTkyLjE2OC4xLjk1CjAwMTZjaWQgdHlwZSA9IGFjY2VzcwowMDIxY2lkIG5v
      "device_id": "VRYQICLLGA",
      "home_server": "192.168.1.95",
      "user_id": "@anonymous:192.168.1.95"
  }
```

- Finally, I get the events for this now registered user (anonymous) 

`curl --globoff -XGET 'https://192.168.1.95:8448/_matrix/client/r0/sync?filter={"room":{"timeline":{"limit":1}}}&access_token=MY_ACCESS_TOKEN'`

As it can be seen below in the result, this user can see the room's events, which seems to be inappropriate. 

```
   "rooms": {
          "invite": {
              "!KGplxzYbaUTqCjZunw:192.168.1.95": {
                  "invite_state": {
                      "events": [
                          {
                              "content": {
                                  "avatar_url": null,
                                  "displayname": "example"
```

### Version information

- **Homeserver**: matrix-synapse

**Comment by richvdh** [comment]
I think this is working as intended.
