### ISSUE TITLE
Extreme high traffic

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/synapse#3301]
So, I noticed that my server had extremely high traffic, and after killing synapse that all went away, and `netstat` still reported quite a few matrix federation requests. After waiting some time and turning synapse back on those federation requests were gone and my traffic was at normal volumes again. This, of course, leads me to believe that this high traffic increase was because of one server trying to sync a lot over. And with increase i mean.....about 900GB over 3h before i noticed and took action.

So, synapse should have some kind of way to detect this abnormal activity and maybe ignore those requests?

**Comment by richvdh** [comment]
this is a bit vague. I suggest getting details of what the requests in question are, from your logs.

**Comment by richvdh** [comment]
I don't think this is very actionable.
