### ISSUE TITLE
Add local and loopback IPv6 addresses to url_preview_ip_range_blacklist

### ISSUE THREAD

**Issue by thegcat** [matrix-org/synapse#3312]
I haven't tested wether the preview spider supports IPv6, but if it does (and probably even if it doesn't so there's no bad surprises when it does) the local and loopback and [ULU/ULA](https://de.wikipedia.org/wiki/IPv6#Unique_Local_Unicast) and so on should be included in the example.

What comes to mind would be `::1/128`, `fe80::/64` and `fc00::/7`.

**Comment by richvdh** [comment]
there is no default blacklist. I presume you mean adding these to the example config?

PR welcome to do so. It should be trivial.

**Comment by thegcat** [comment]
This is what I meant indeed, I can see to provide one in the next few days.
