### ISSUE TITLE
Joining any off-server channel fails

### ISSUE THREAD

**Issue by ansorg** [matrix-org/synapse#3313]
### Description

Yea, this is more of a support request that I place here because I cannot join any channels from my homeserver

from both, the build in frontend and riot.im app, where I'm logged in with my homeserver account, I cannot join channels on other homeservers. 

What part of my configuration could be wrong? 
running 0.30 via docker with nginx in front 

The synapse log shows this
>2018-05-30 17:40:07,213 - synapse.http.matrixfederationclient - 224 - WARNING - POST-653 - {GET-O-8} Sending request failed to matrix.org: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: ResponseNeverReceived:[CancelledError()]

>2018-05-30 17:40:07,213 - synapse.http.outbound - 248 - INFO - POST-653 - {GET-O-8} [matrix.org] Result: ResponseNeverReceived:[CancelledError()]

>2018-05-30 17:40:07,217 - synapse.http.server - 102 - ERROR - POST-696 - Failed handle request via <function _async_render at 0x7f0def30b578>: <SynapseRequest at 0x7f0dec85e8c0 method=POST uri=/_matrix/client/r0/publicRooms?server=matrix.org clientproto=HTTP/1.1 site=8008>: Traceback (most recent call last):
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]

>2018-05-30 17:40:07,218 - synapse.http.server - 404 - WARNING - POST-696 - Not sending response to request <SynapseRequest at 0x7f0dec85e8c0 method=POST uri=/_matrix/client/r0/publicRooms?server=matrix.org clientproto=HTTP/1.1 site=8008>, already disconnected.

>2018-05-30 17:40:07,219 - synapse.access.http.8008 - 131 - INFO - POST-696 - 172.22.0.1 - 8008 - {@jens:mtx.ax9.eu} Processed request: 78376ms (4ms, 0ms) (0ms/0ms/0) 0B 200 "POST /_matrix/client/r0/publicRooms?server=matrix.org HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"

>2018-05-30 17:40:07,221 - synapse.http.server - 102 - ERROR - POST-653 - Failed handle request via <function _async_render at 0x7f0def30b578>: <SynapseRequest at 0x7f0dec6a76c8 method=POST uri=/_matrix/client/r0/publicRooms?server=matrix.org clientproto=HTTP/1.1 site=8008>: Traceback (most recent call last):
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]

>2018-05-30 17:40:07,221 - synapse.http.server - 404 - WARNING - POST-653 - Not sending response to request <SynapseRequest at 0x7f0dec6a76c8 method=POST uri=/_matrix/client/r0/publicRooms?server=matrix.org clientproto=HTTP/1.1 site=8008>, already disconnected.

>2018-05-30 17:40:07,222 - synapse.access.http.8008 - 131 - INFO - POST-653 - 172.22.0.1 - 8008 - {@jens:mtx.ax9.eu} Processed request: 244030ms (15ms, 0ms) (0ms/2ms/1) 0B 200 "POST /_matrix/client/r0/publicRooms?server=matrix.org HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"

**Comment by richvdh** [comment]
sounds like you haven't set up federation correctly. Please do read https://github.com/matrix-org/synapse/blob/master/README.rst#id6, and note that the federation tester currently fails for your domain `mtx.ax9.eu`.

As per the issue template, please don't file bugs here looking for support.
