### ISSUE TITLE
Unable to decrypt previous messages on new devices

### ISSUE THREAD

**Issue by J316** [matrix-org/synapse#3329]
In an encrypted chat or group, if a user is invited after a message was sent, or even if he is already present in the chat, but he adds a new device later in time, that device cannot decrypt previous messages because "the sender didn't share the keys". This happens on all operative systems (I tried Android, iOS, Linux, Windows) and with everyone I tried.

**Comment by ara4n** [comment]
Users cannot currently access keys from before they were joined a room - see https://github.com/vector-im/riot-web/issues/2713 and https://github.com/vector-im/riot-web/issues/2286 (and the overall tracking bug of https://github.com/vector-im/riot-web/issues/6779).

However, when you add a new device to your account, keys should be shared to it automatically - if you verify the new device with existing ones which have the keys (assuming the existing ones are online at some point so they can respond to the keyshare requests) - as per https://github.com/vector-im/riot-web/issues/2286#issuecomment-327744369.

I suggest reopening this over at https://github.com/vector-im/riot-web/issues if needed, as that's where the E2E bugs have ended up getting tracked.
