### ISSUE TITLE
Is the rate we process join/leaves limited by the database?

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3335]
(... and if so, should we be looking at optimising the database schema rather than worrying about python optimisation?)

I noticed the following the other morning (2018/05/31). Up until 08:50 UTC when erik restarted the event creator (and the join backlog was growing):

* event persistence was at 8Hz (12Hz after the restart)
* cpu usage on the master was at 75% (90% after the restart)
* avg db wait time was around 20ms (60ms after the restart, after a peak of 250ms)

The increase in event rate was almost entirely m.room.message from the freenode bridge.

So the question is: why was the cpu usage down at 75%. It could be db contention, except that the db wait time metric points the other way - so I suspect it's going to be something more like db latency - which might bite the irc bridge quite hard given we limit the amount of stuff we let it do in parallel. If the IRC bridge is trying to do more database-intensive work (like processing a lot of joins/parts), then that might cause a lower event throughput and lower CPU usage level than less database-intensive work.

It might be instructive to attempt to confirm or deny this hypothesis by looking at database transaction/scheduling time histograms, or by gathering metrics on the usage level of the db thread pool.

Another approach might be to look in more detail at these join requests that queue up for hours and see what is actually taking the time. Normally whenever I look at them, the majority complete very quickly once they finally get to the top of the queue - so some insights into what is bunging up the queue could be useful.

**Comment by ara4n** [comment]
from memory, when i’ve looked at the join/part backlog in the past; we clear the backlog at about 2Hz but add to it at about 5Hz. If you restart the creator worker after N hours to clear the backlog, the bridge has given up on a bunch of the joins and so its add rate reduces enough to no longer be problematic (leaving the bridge’s membership state out of sync with synapse)

**Comment by richvdh** [comment]
Yes, my point is that by restarting the event creator we shift the balance of events from join/leave to message, thus potentially reducing the amount of database work that is going on.

**Comment by richvdh** [comment]
"yes".
