### ISSUE TITLE
Docker: Variable for which worker(s) to run

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3338]
Use case: Automatically scaling the parts of synapse that can be scaled, such as the event creator and synchrotrons. It would be desirable in this situation to have 1 worker per container.

**Comment by jfrederickson** [comment]
What do you think about this?

* A toggle var like `SYNAPSE_ENABLE_REPLICATION` to enable/disable the replication interface
* `SYNAPSE_REPLICATION_BIND_ADDRESS` defaulting to `127.0.0.1` (Does this even make sense in the context of Docker? I'm not sure... in Kubernetes you might bind to localhost and run all workers in one pod, or use NetworkPolicies to restrict access.)
* `SYNAPSE_TCP_REPLICATION_PORT` defaulting to `9092`
* `SYNAPSE_HTTP_REPLICATION_PORT` defaulting to `9093`

And then for the actual worker configs... does it make sense to try and template them out, or would it be better to just expect them to live in a directory somewhere? The former sounds simpler for administrators to deal with, but I don't know how stable those configs are.

**Comment by turt2live** [comment]
Something like that makes sense, although I did find that with worker setups the config generally becomes more complicated anyways. In the end I actually worked around the issue: https://github.com/t2bot/docker-synapse-worker

**Comment by richvdh** [comment]
As per #5518, we're going to recommend people configure this in a proper config file, as maintaining environment variables for every option is getting unwieldy, hard to maintain, and harder to write documentation for.
