### ISSUE TITLE
why do we check forgottenness when assessing event visibility?

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3350]
There is some code mostly [here](https://github.com/matrix-org/synapse/blob/develop/synapse/visibility.py#L160), which was evolved from code introduced waaay back in the mists of time [here](https://github.com/matrix-org/synapse/pull/385/commits/bed7889703371dca893893d33f67e59e99cda111#diff-fbe8557b26996bcccd7fed85b85e0c9cR95), which checks if the user has "forgotten" a room, in which case we don't let them see an event.

The question is: given you can't forget a room without leaving it (or being banned from it...), why is this check necessary at all?

The associated db query is quite heavy-weight, so if we can safely drop it, that would be good.

**Comment by richvdh** [comment]
discussed this with erik; conclusion was that we couldn't see any reason for this check, and should remove it.

**Comment by richvdh** [comment]
It turns out that we have a sytest which relies on this: https://github.com/matrix-org/sytest/blob/00e30050ccf7eed830638151252934a583e050b6/tests/30rooms/31forget.pl#L186

The test asserts that if you're in a private room, which you leave, forget, and then rejoin, you can't see any history from before you rejoined. Possibly the logic here is that you may not want to leak to anyone looking over your shoulder your prior history in that room?

It feels like a weird edge-case, either way, and it's expensive to support, so I still think we should drop it.

**Comment by krombel** [comment]
@richvdh Can this be closed now?

**Comment by richvdh** [comment]
thanks
