### ISSUE TITLE
Setting an autojoin room seems to be incompatible with the user agreement feature

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#3353]
I created a new matrix account on a server with user agreement enabled (using the migration UX), but I was not autojoined to the room.

Obviously even after I gave my consent I was still not autojoined to the room :(

**Comment by neilisfragile** [comment]
'the room'=='server notices'?

**Comment by Half-Shot** [comment]
The code is rather...simple and tries to join as soon as the rest of registration has been handled, there should probably be some kind of join queue that will wait for consent to be given.

**Comment by ara4n** [comment]
should be fixed by https://github.com/vector-im/riot-web/issues/7168

**Comment by ptman** [comment]
autojoin seems to be handled after consent currently

**Comment by richvdh** [comment]
yeah so this is fixed?

**Comment by ptman** [comment]
AFAICT it's fixed
