### ISSUE TITLE
ImportError: no module named twisted

### ISSUE THREAD

**Issue by eledroos** [matrix-org/synapse#3361]
### Description

I've been following the instructions here: https://www.digitalocean.com/community/tutorials/how-to-install-matrix-synapse-on-ubuntu-16-04

And with `sudo systemctl restart matrix-synapse`, the server fails to start.

### Steps to reproduce

- Install synapse fresh on Ubuntu 16.04 Desktop.
- Attempt to start using `sudo systemctl restart matrix-synapse`

### Version information

- **Homeserver**: Self Host.
- **Version**:        What version of Synapse is running? 
- **Install method**: `sudo apt-get install matrix-synapse`
- **Platform**: Inside Virtual Machine. Dual Core, 4 GB RAM.

![screen shot 2018-06-06 at 5 10 25 pm](https://user-images.githubusercontent.com/6360485/41065493-d23baec0-69ac-11e8-9ef1-6c081e0321d4.png)

**Comment by eledroos** [comment]
Twisted seems to be in fact installed. 
![screen shot 2018-06-06 at 5 13 20 pm](https://user-images.githubusercontent.com/6360485/41065542-f4c5f86a-69ac-11e8-868b-6af0ee7edbbd.png)

**Comment by eledroos** [comment]
Seems to have been fixed: https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15283175933217188ZDutI:matrix.org

**Comment by richvdh** [comment]
I fixed this by dropping the python-prometheus-client from jessie-backports into the xenial repo. It would be nice if the package made the dependency on a more recent prometheus-client more explicit.
