### ISSUE TITLE
readme should include info on docker installation and migration

### ISSUE THREAD

**Issue by benparsons** [matrix-org/synapse#3366]
The readme is included wholesale at https://hub.docker.com/r/matrixdotorg/synapse/, would be useful to mention migration paths from other docker files, as this has come up in #synapse:matrix.org.

**Comment by turt2live** [comment]
somewhat related: #3224 (in terms of improving the readme on docker)

**Comment by benparsons** [comment]
Ah good link. I didn't realise this was already in hand. @jcgruenhage this is what we discussed IRL.
