### ISSUE TITLE
docker image sets log level to warn by default

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3370]
... apparently? that's insane; it ought to be at least INFO

**Comment by michaelkaye** [comment]
Is there something specific we should be storing from running a synapse that means we should not default to only showing WARNING? I'm of a general opinion that not logging if we don't need to is great - there's a certain amount of config and setup needed for users to make docker not just store logs in a ever-growing stdout file (the default json-file driver).

**Comment by richvdh** [comment]
I'd expect us to at least log the requests. It's essentially impossible to debug anything without any logs.

**Comment by hawkowl** [comment]
Fixed in #5547
