### ISSUE TITLE
deactivating a user leaves it in communities. 

### ISSUE THREAD

**Issue by airblag** [matrix-org/synapse#3388]
### Description

I'm having a setup with mxisd, and synapse, using the rest-api to authenticate my users against my LDAP server. 
When a user is removed from LDAP, I also wanna deactivate his/her access to Matrix too. 
The user is leaving all rooms but staying in communities it was part of. I guess it would be more consequent to leave communities at the same time.
### Steps to reproduce

- Create a user
- invite it to a community
- log with this user and join the community and a room
- with an admin token, deactivate his account :

```
curl -s -XPOST "https://mymatrixserver.net/_matrix/client/r0/admin/deactivate/%40testuser%3Amymatrixserver.net?access_token=$token" -d '{}'
```
- @testuser:mymatrixserver.net is then leaving all rooms it was in, and all tokens are revoked, but
the user is staying in all communities it joined/was invited to.

I would expect that the user is also leaving communities when the account is deactivated. 

### Version information

- **Homeserver**: company internal synapse server

If not matrix.org:
- **Version**:        0.31.1-1 (from https://matrix.org/packages/debian stretch InRelease)
- **Install method**: package manager
- **Platform**:  debian stretch lxd container (host is ubuntu 17.04), but I don't think it has any influence :)

**Comment by dklimpel** [comment]
Related to #11539

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
