### ISSUE TITLE
Test using postgresql does not pass

### ISSUE THREAD

**Issue by abcang** [matrix-org/synapse#3398]
### Description

I am currently thinking to extend synapse and set up a home server. Therefore, I attempted to execute the test using postgresql including the extended function. By changing USE_POSTGRES_FOR_TESTS it was possible to run tests using postgresql, but we found that many tests did not work. Are you planning to support testing synapse with postgresql?

### Steps to reproduce

- Change USE_POSTGRES_FOR_TESTS to True
- Add `host` and `user` to args of database_config
- To speed up, change the process of reconfiguring the database as follows

```python
cur = db_conn.cursor()
# Disconnect the connection to avoid "too many clients already" errors
cur.execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE pid != pg_backend_pid() AND datname = 'synapse_test' AND query_start < now() - interval '5 seconds'")
cur.execute("SELECT tablename FROM pg_tables where schemaname='public'")
rows = cur.fetchall()
for r in rows:
    if r[0] != "schema_version" and r[0] != "applied_schema_deltas":
        cur.execute("TRUNCATE TABLE %s CASCADE" % r[0])
    if r[0] == 'federation_stream_position':
        cur.execute("INSERT INTO federation_stream_position (type, stream_id) VALUES ('federation', -1)")
        cur.execute("INSERT INTO federation_stream_position (type, stream_id) SELECT 'events', coalesce(max(stream_ordering), -1) FROM events")
    elif r[0] == 'event_push_summary_stream_ordering':
        cur.execute("INSERT INTO event_push_summary_stream_ordering (stream_ordering) VALUES (0)")
```
- Run command: `PYTHONPATH="." trial tests`

### Version information

- **Version**:  v0.31.1
- **Install method**: git clone

**Comment by NotAFile** [comment]
The unit tests don't have great coverage, you should probably run https://github.com/matrix-org/sytest in addition. I could have sworn there was already an issue about running unit tests on postgres, but I can't find it.

**Comment by abcang** [comment]
Thank you very much. I will try using sytest.
