### ISSUE TITLE
#matrix:matrix.org not usable

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/synapse#3403]
### Description

`#matrix-dev:matrix.org` and `#matrix:matrix.org` both seem in a weird state.

When I try to send a message, I get:
```
User @kurt:roeckx.be not in room !cURbafjkfsMDVwdRDQ:matrix.org (None)
Resend message or cancel message now.
```

Or:
```
User @kurt:roeckx.be not in room !XqBunHwQIXUiqCaoxq:matrix.org (None)
Resend message or cancel message now.
```

When I try to leave the room I get:
```
Failed to leave room
Not a known room
```

When I try to join the room I ussually get:
```
"#matrix:matrix.org is not accessible at this time."
```

Sometimes I get:
```
You are trying to access a room.
Click here to join the discussion!
```
And when I then click, I get:
```
Failed to join room
Internal server error
```

### Version information

- **Homeserver**: roeckx.be

If not matrix.org:
- **Version**: 0.31.2-1
- **Install method**: .deb pacakge
- **Platform**:  debian stable

**Comment by kroeckx** [comment]
For either room I also seem to be unable to get history of the messages other than the the initial ones I get, which are like 15 events on the old `#matrix:matrix.org` and around 40 on `#matrix-dev:matrix.org`

**Comment by ara4n** [comment]
#matrix-dev has been vandalised and not fully fixed yet. #matrix was also vandalised and has been rebuilt as per https://matrix.org/blog/2018/06/14/security-update-synapse-0-31-2/

**Comment by kroeckx** [comment]
After trying it enough times, it worked to join #matrix:matrix.org

**Comment by emdete** [comment]
is this somehow related to #3387?

**Comment by kroeckx** [comment]
I can't find any error message like that in the logs.

**Comment by turt2live** [comment]
Does clearing your client's cache fix the issue? On Riot that would be "Clear Cache and Reload" in your user settings, towards the bottom.

**Comment by kroeckx** [comment]
If I try that, I'm no longer in either channel.

**Comment by kroeckx** [comment]
So I tried joining matrix-dev again, it's currently showing me as being in an empty room. I assume it will sort itself out over time.

**Comment by turt2live** [comment]
#matrix-dev has a few issues, and might not recover nicely. #matrix should be re-joinable though and work just fine.

Because clearing the cache "fixed" the issue, this sounds like a classic case of #1953

**Comment by neilisfragile** [comment]
Am going to close on the assumption that we are looking at an instance of #1953
