### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by dmitrygashnikov** [matrix-org/synapse#3408]
Cannot find a way to make fields: email address and phone number required to be filled for registering new users. Is there are any way to do that?
PS. Sorry for my English.

**Comment by neilisfragile** [comment]
Take a look in homeserver.yaml

# registrations_require_3pid:
#     - email
#     - msisdn

**Comment by neilisfragile** [comment]
Closing. Follow on support best handled in #matrix:matrix.org
