### ISSUE TITLE
a bunch of metrics have been renamed

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3409]
for example, https://github.com/matrix-org/synapse/commit/df9f72d9e5fe264b86005208e0f096156eb03e4b dropped `_protocol` from a bunch of `synapse_replication_tcp_protocol_inbound_*` metrics. This has broken a bunch of graphs

**Comment by neilisfragile** [comment]
Fixed by #3410 ?

**Comment by richvdh** [comment]
ya
