### ISSUE TITLE
we should ignore events for rooms we don't know about

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3422]
just debugged a server who left (in theory) and then nuked curbaf from its DB. however, matrix.org still sends it events from curbaf, resulting in it doing a massive explosion of federation traffic to try to fill in the missing events. surely if the room has been nuked or parted we should ignore spurious events like this.

**Comment by supermamie** [comment]
To nuke the database (after leaving all the rooms) I did 2 things.
1) I ran the janitor script from here : https://github.com/xwiki-labs/synapse_scripts
2) I adapted the nuke script from here : https://github.com/matrix-org/synapse/blob/master/scripts-dev/nuke-room-from-db.sh

I modified the script to delete WHERE room_id LIKE "%matrix.org%"
And I added those lines : 
DELETE FROM received_transactions WHERE origin NOT LIKE '%<my-server>%';
DELETE FROM event_reference_hashes WHERE event_id NOT LIKE '%<my-server>%';
 (I also replaced VACUUM with VACUUM FULL to release disk space)

**Comment by richvdh** [comment]
> surely if the room has been nuked or parted we should ignore spurious events like this.

Well, we do ignore them if it has been parted, thanks to #2490. However, if you nuke it, then it is equivalent to a room you have *never* been in, in which case, we attempt to repopulate the room. Historically this has been viewed as more of a feature than a bug, as it lets people who accidentally drop their database get some semblance of restoration back.

However, I do think that behaviour causes more problems than it solves, and we should in fact ignore events for rooms we've never heard of (except for invites, of course).

**Comment by supermamie** [comment]
Is there a way to properly leave the old matrix hq room ?
I tried to re-join and then properly leave all rooms where I have been, but maybe this one was locked after my nuke and before my join/leave ?

**Comment by MadLittleMods** [comment]
Seems like this was fixed by https://github.com/matrix-org/synapse/pull/4166 which was mentioned here.
