### ISSUE TITLE
JSON warning when leaving or forgetting a room when posting with no body

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3437]
The request still returns 200 OK, but the warnings in the log are annoying. Here's some acceptance test output from another application. It does not post an empty object, which is expected by synapse, but otherwise not required according to the spec.

The acceptance test mixes synapse warnings with it's own output, sorry:
```
[DEBUG] Leaving room:  http://localhost:8008/_matrix/client/r0/rooms/!OBXEcMJhmdaVpKlHob:localhost/leave
2018-06-23 23:08:59,469 - synapse.http.servlet - 176 - WARNING - POST-178- Unable to parse JSON: Expecting value: line 1 column 1 (char 0)
[DEBUG] Forgetting room:  http://localhost:8008/_matrix/client/r0/rooms/!OBXEcMJhmdaVpKlHob:localhost/forget
2018-06-23 23:08:59,524 - synapse.http.servlet - 176 - WARNING - POST-180- Unable to parse JSON: Expecting value: line 1 column 1 (char 0)
```

**Comment by turt2live** [comment]
@hawkowl I'm told this may be of interest to you. I haven't tested the other syntactic sugar routes, but I suspect they fall victim to the same issue :(

**Comment by reivilibre** [comment]
I'm not sure this issue is still valid considering we have the opposite problem today. According to the spec these are meant to have `{}` bodies so it seems like this issue is invalid.
