### ISSUE TITLE
the 10s timeout on get_missing_events introduced in #1744 means an overloaded server can never complete

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3444]
we should probably back out #1744 or up the timeout to 90s or something. currently the federation-reader on matrix.org is so overloaded all calls to get_missing_events take >10s to process, causing a death spiral

**Comment by turt2live** [comment]
related: https://github.com/matrix-org/synapse/issues/3013

**Comment by richvdh** [comment]
cf #3526 for get_missing_events slowness

**Comment by squahtx** [comment]
Going to close this since we raised the timeout to 60 seconds in #3903.
Reopen if 60 seconds turns out to be insufficient.
