### ISSUE TITLE
Use jwt to create access_tokens

### ISSUE THREAD

**Issue by mkhfring** [matrix-org/synapse#3450]
### Description

I want my tokens to be created with jwt and HS256 algorithm. How can I make my server to produce jwt tokens instead of pymacaroons. 
    
- **Platform**:       Ubuntu 16.04.

**Comment by pkoziol** [comment]
What's wrong with Macaroons?

**Comment by erikjohnston** [comment]
We are increasingly moving away from macaroons to access tokens just be opaque strings, so I don't think this would be something we'd want to support.
