### ISSUE TITLE
哪个文件是写第三方服务的？

### ISSUE THREAD

**Issue by liujianliang2018** [matrix-org/synapse#3453]
里面文件太多了，，搞不清，有没有会的

**Comment by krombel** [comment]
Can you translate this issue to english? If not, it will not be possible to handle it. You cannot fix something that you don't understand...

**Comment by uhoreg** [comment]
Google translate says:

> Which file is writing a third-party service?
> There are too many documents inside, it's not clear, there are no

which looks like a somewhat bad translation, but it also looks like this is a question more suited to a Matrix room (maybe #matrix-dev:matrix.org), rather than an issue.  So I'm going to close  this.
