### ISSUE TITLE
Consider improving SYNAPSE_ENABLE_REGISTRATION handling in docker

### ISSUE THREAD

**Issue by pkoziol** [matrix-org/synapse#3458]
### Description

Recently I discovered that my server allowed people to register. It turns out that setting in `docker-compose.yml`:
```
- SYNAPSE_ENABLE_REGISTRATION=no
```
doesn't disable registration. You have to remove variable completly.

I know (now) that [contrib/docker/README.md](../blob/master/contrib/docker/README.md) says to set this variable to enable registration, so one may guess that you should unset variable to disable registration.

I'm not that smart apparently.

### Version information

- **Homeserver**: my private homeserver
- **Version**:        0.31.1
- **Install method**: docker-compose
- **Platform**:       docker

**Comment by turt2live** [comment]
This also tripped me up a couple times. Falsey words should be falsey imo

**Comment by hawkowl** [comment]
As per https://github.com/matrix-org/synapse/issues/5518 , we're going to remove support for the environment variable method of configuration, which will fix this bug by making it more explicit what the configuration is.
