### ISSUE TITLE
Location based search for users

### ISSUE THREAD

**Issue by treinberger** [matrix-org/synapse#3461]
This is no bug report, rather a question on which possibilities exist to design and implement a location-based search for users.

My requirement is to be able to have a function with the input (lat,long,radius) returning an array of users with their defined latitude, longitude in order to be able to visualize search results on a gmap.

latitude and longitude may be statically defined already as custom user profile attributes, so I suspect, the heavy lifting part is to do the search by euclidian distance.

So my questions are:
- is this feature already in place (I didn't see it in the spec)?
- are there plans to implement this feature?
- if not, what would be the recommended way to implement this feature?

**Comment by Half-Shot** [comment]
This probably is better tracked in a client like https://github.com/vector-im/riot-web, but we are currently missing extensible profiles needed to store location about users and then you might need a more powerful way to search the user directory. There is obviously also privacy concerns about an idea.

**Comment by treinberger** [comment]
It's not possible to implement location based user search on the client because you have to transfer all users to the client first and filter then, which is inefficient, bad pattern etc. 

Regarding your privacy concerns: I'd leave the decision to be searchable up to the user. Nevertheless, the ability to search for users within proximity is a very interesting one which can serve many different purposes.

Considering a custom solution developed by my team, which would be the way to go (not on the client)?

**Comment by NotAFile** [comment]
@treinberger synapse is not responsible for user discovery, have a look at https://github.com/matrix-org/sydent. This is also where other user discovery features like email etc. are.

**Comment by neilisfragile** [comment]
Closing, better raised against sydent
