### ISSUE TITLE
Handle multiple domains

### ISSUE THREAD

**Issue by xamanu** [matrix-org/synapse#3468]
Thanks for this great piece of software!

It would be great to have a possibility to add several domains to one instance.

**Comment by xamanu** [comment]
The [FAQ](https://matrix.org/docs/guides/faq.html#what-is-a-mxid) gives actually a good answer to this:

> Matrix user IDs (MXID) are unique user IDs. They are in the format @username:homeserver.tld (this format is used to avoid confusing them with email addresses). They are intended to be fairly hidden (although right now they are not) - instead you will find and identify other users via 3PIDs.

So, there is no need to handle multiple domains on the home server, as identity server should handle the shareable identifiers (like email or phone) and the identity (MXID) of the home server should be unique (and fairly hidden!).

Closing here. Sorry for disturbing.

**Comment by Ezwen** [comment]
Sorry to dig out this issue, I just wanted to add that I would still really enjoy such a feature for at least a few reasons: 
1. having/using an identity server is optional and in such case the domain is a very visible/required piece of information;
2. following the previous point, most clients nowadays show the MXID with a single clic on a user name, or with a hover on a user name, hence it really is a visible piece of information regardless of identity servers;
3. a bonus reason is that if one wants to progressively migrate from one host name to another, it can be useful to be able to temporarily have two different host names for a homeserver without having to set up a second resource-consuming synapse instance next to the first one

my 2 cents :)

**Comment by neilisfragile** [comment]
Hi @Ezwen it's something that needs revisiting. https://github.com/matrix-org/matrix-doc/issues/1228 will make the whole problem go away, but it is not something that will land soon. So we either modify Synapse to work across multiple domains (this is non-trivial because  today it assumes that in all contexts there exists exactly one domain), or double down on https://github.com/matrix-org/matrix-doc/issues/1228 and portability comes for free.

**Comment by Ezwen** [comment]
Interesting, thanks for pointing that out! It looks very promising :)

**Comment by ethoms** [comment]
I ned this also. Currently I run one ejabberd instance for XMPP with 3 domains. Also, we run 3 SIP domains (URI dialing) on a single OpenSIPS server. I want to replace those two independant services with one Matrix service. Riot works well on all platforms wheras XMPP is a problem on iOS and Linphone for Android has never been good enough for user adoption, most of our users just use Whatsapp instead.

We have 3 companies under one roof (shared offices). Internally they act like one company in some capacities, but externally (publicly) they must look like seperate organisations. I only see two options:

1.) Run one instance with one new (made up) domain.
2.) Run three seperate instances (in containers) with each of the real domains.

Option 2 sounds best to me, but I only worry about performance. I suppose I could shared the same TURN server for all and most of the video call performance will not be impacted. The other traffic should not be a problem if the containers are on the same physical host.

P.S. I'm running Synapse in a FreeBSD jail, and it runs like a champ! We only have a few test users so far though.

**Comment by nlemus19** [comment]
I am interested in having multiple domains.

I have an instance ... but I don't know how to create more instances without them colliding and I can register users from each different domain or subdomain.

**Comment by Thatoo** [comment]
I'd like that too

**Comment by hex-m** [comment]
There is an active/open issue about multi-domain support: https://github.com/matrix-org/synapse/issues/8885
