### ISSUE TITLE
cannot start synapse server if freeze synapse to binary with different tools (PyInstaller, cx_freeze or bbfreeze)

### ISSUE THREAD

**Issue by mostafa-v** [matrix-org/synapse#3508]
### Description

Hi, I want to freeyze synapse so that I can install it anywhere without installing python and python packages and run as stand-alone binary. I use three different tools namely PyInstaller, cx_freeze and bbfreeze, but all the same, synapse server cannot get started with the binary from these tools and showing same strange error.

### Steps to reproduce
- pip install pyinstaller
- pyinstaller lib/python2.7/site-packages/synapse/app/synctl.py -n synapse --onefile (or simply pyinstaller bin/synctl -n synapse --onefile)
- ./dist/synapse start 

or

- pip install cx_Freeze==5.0.2
- cxfreeze bin/synctl --target-dir dist
- ./dist/synctl start

or 

- pip install bbfreeze
- bbfreeze bin/synctl
- ./dist/synctl start

Describe how what happens differs from what you expected.

I cannot start synapse with those binaries. It shows the following strange error:

> Starting ...
> usage: synctl [-h] [-w WORKERCONFIG] [-a WORKERCONFIGDIR]
>               {start,stop,restart} [configfile]
> synctl: error: argument action: invalid choice: 'synapse.app.homeserver' (choose from 'start', 'stop', 'restart')
> error starting (exit code: 2); see above for logs

It's the same error for restart command, but stop command works right with all these three binaries. also, with wrong command, it works as expected.

./dist/synctl wrongcommand

> usage: synctl [-h] [-w WORKERCONFIG] [-a WORKERCONFIGDIR]
>               {start,stop,restart} [configfile]
> synctl: error: argument action: invalid choice: 'wrongcommand' (choose from 'start', 'stop', 'restart')

I wonder how right commands (start and restart) changes to  'synapse.app.homeserver' 

Any idea? Am I missing something? or should I do additional task in order to freeze synapse?

**Comment by mostafa-v** [comment]
@krombel Thank you, It was a good help.
I'm trying to freeze synapse/app/homeserver.py
I do not see that error anymore, but when running homeserver, there are some dynamic imports and some non-python files that is needed, and now I'm trying to include them for pyinstaller. I think it will work if I include all of them.

**Comment by neilisfragile** [comment]
Thanks @krombel  for the support, @morteza-araby please take support requests to #matrix:matrix.org

Closing the issue
