### ISSUE TITLE
(Password) Auth Provider not working

### ISSUE THREAD

**Issue by Sgoettschkes** [matrix-org/synapse#3511]
I'm trying to implement a custom auth provider to interact with our own backend to login users. I found https://github.com/kamax-io/matrix-synapse-rest-auth/blob/master/rest_auth_provider.py which works as expected but found the following not possible:

- Implement a custom auth provider for a jwt token
- Implement a custom auth provider which does not use the existing `m.login.password` type

As for the jwt: I have found no way to register an auth provider as a jwt auth provider and override the existing jwt handling

As for a new login type: I am able to register a new type by implementing `get_supported_login_types()` and when doing a GET request against the login endpoint it shows me the custom type. Using the custom type however it fails all the time. From my working through the code it seems that there is no code to call custom auth providers.

Any ideas on how to either overwrite the existing jwt login or to register a new one properly?

**Comment by richvdh** [comment]
Looks like this question has bitrotted a bit; sorry we can't provide support via github.

I don't know how the jwt stuff works; I suspect it doesn't, mostly.

Custom auth providers can be added under the `password_providers` key in the configuration file.
