### ISSUE TITLE
synapse logs drown in logcontext warnings

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3518]
even on simple things like /sync

**Comment by richvdh** [comment]
I'm assuming the warnings in question are like these:

```
2018-07-18 10:48:01,775 - synapse.storage._base - 347 - WARNING - - Running db txn from sentinel context: metrics will be lost
```

**Comment by richvdh** [comment]
(for the record, this was introduced by #3496)

**Comment by richvdh** [comment]
There are actually still a lot of these going on in our production instance. I'm going to reopen this

**Comment by zwieberl** [comment]
After upgrading from 0.33 to 0.34.1.1 (and switching to python3, if that is relevant), I started getting these log-entries every minute (didn't see them before at all). 
The logs are, after the initial startup, empty expect for these messages.

**Comment by richvdh** [comment]
The remaining instances of this on the production server are:

```
synapse.storage._base - 319 - WARNING -  - Starting db txn '_get_joined_users_from_context' from sentinel context
synapse.storage._base - 319 - WARNING -  - Starting db txn 'get_state_group_delta' from sentinel context
synapse.storage._base - 319 - WARNING -  - Starting db txn '_get_state_groups_from_groups' from sentinel context
```

we're only getting a handful of them, so this is now a pretty minor issue.

@zwieberl I imagine you have a different problem and it would be better to open a separate issue including the logs you are seeing.

**Comment by agherzan** [comment]
On 0.99.3.2 I still get:

```
2019-05-13 19:58:26,091 - synapse.storage._base - 401 - WARNING - - Starting db txn 'update_presence' from sentinel context
2019-05-13 19:58:26,091 - synapse.storage._base - 437 - WARNING - - Starting db connection from sentinel context: metrics will be lost
```

**Comment by richvdh** [comment]
looks like PresenceHandler needs its use of logcontexts cleaning up. In particular, `_handle_timeouts` and `_persist_unpersisted_changes` need wrapping with `run_as_background_process`

**Comment by richvdh** [comment]
This is being exacerbated by #5271 currently

**Comment by richvdh** [comment]
and the ones about presence are #4414

**Comment by richvdh** [comment]
given that #4414 and #5271 are now fixed, I'm going to consider this fixed enough to be closed. We should open more granular bugs for any more that are discovered.
