### ISSUE TITLE
fatal python errors in DB transactions only get logged at DEBUG as TXN FAIL

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3519]
e.g. 2018-07-12 11:04:14,292 - synapse.storage._base - 281 - DEBUG - None - [TXN FAIL] {get_devices_by_remote-70} global name 'results' is not defined

**Comment by richvdh** [comment]
I'm pretty certain this is incorrect. we log at DEBUG initially, then retry the txn. When the retries also fail, we throw an exception. it is then up to the caller to log this exception sanely.

**Comment by richvdh** [comment]
closing this pending evidence to the contrary.
