### ISSUE TITLE
FederationRateLimiter's queue works backwards

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3524]
so we end up processing the newest requests first and the oldest ones last. which is silly.

**Comment by Half-Shot** [comment]
Looking at logging from mx.org side, it looks like sending federation gives up with a `ResponseNeverReceived`

``2018-07-13 00:59:47,661 - synapse.http.matrixfederationclient - 222 - WARNING - None - {PUT-O-1064715} Sending request failed to half-shot.uk: PUT matrix://half-shot.uk/_matrix/federation/v1/send/1531394952235/: ResponseNeverReceived:[CancelledError()]``
