### ISSUE TITLE
Server Notices should be sent to all local users

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#3525]
As of now the server notices feature seems[ to only apply to one specific user](https://github.com/matrix-org/synapse/blob/master/docs/server_notices.md#sending-notices) through the manhole.

Due the nature of a server notice, as to be used for announcing maintenance for example, i think it would only make sense to at least give the option to send such a thing to all users located on the homeserver.

**Comment by krombel** [comment]
1. The server_notices feature has currently no interface to be triggered. The manhole is a workaround as it allows direct access to synapse. All there should be done with caution.

2. As the manhole allows all you can extend the command you linked to on your own. The following untested code should work
```
for user_id in hs.get_datastore().get_all_local_users():
    hs.get_server_notices_manager().send_notice(user_id, {'msgtype':'m.text', 'body':'foo'})
```
Note: If you have a lot of users this might cause high load. So you might want to either add some `sleep` command or something else.

**Comment by richvdh** [comment]
thanks for the workaround @krombel. I don't think that we want to add more stuff that can only be used via the manhole, so I'm going to close this for now in favour of #3532
