### ISSUE TITLE
Appservice transactions should be limited in size, spanning multiple transactions if needed

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3536]
After ~7 hours of the appservice sender being down on t2bot.io, it was fixed. As a result, it tried to send a transaction that had 2865 events in it to an appservice. The appservice was behind a reverse proxy with a maximum request size that prevented the giant transaction from making it through.

It would be nice if synapse limited the transaction size to something in the hundreds. Potentially, it'd be event nicer if synapse/the spec reacted the 413 Request Too Large and made efforts to shrink the transaction size.

**Comment by maxidor** [comment]
Directly related: https://github.com/matrix-org/synapse/issues/4231

**Comment by Half-Shot** [comment]
Ftr, this happened again today with the freenode bridge. I'm not sure it's minor anymore.
