### ISSUE TITLE
Add manhole configuration to Docker image

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3558]
This helps mostly with testing, and potentially debugging in larger Docker environments. Having access to synapse's manhole is dangerous although useful when needed.

**Comment by hawkowl** [comment]
As per https://github.com/matrix-org/synapse/issues/5518 , we're going to recommend people configure this in a proper config file, as maintaining environment variables for every option is getting unwieldy, hard to maintain, and harder to write documentation for.
