### ISSUE TITLE
"Running db txn from sentinel context: metrics will be lost" logged at >10Hz

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3560]
This is t2bot.io on 0.33.0rc1.

The warning "Running db txn from sentinel context: metrics will be lost" appears in the logs at an incredible frequency. I'm not sure what causes it, however the problem should be either fixed or the message suppressed. It's making logs hard to read :/

**Comment by richvdh** [comment]
This is a dup of #3518. Closing this one as the fixes are filed against the other
