### ISSUE TITLE
Ambiguous labeling of the `Only people who have been invited` in the Group/Comunity page

### ISSUE THREAD

**Issue by psaavedra** [matrix-org/synapse#3575]
### Description

Ambiguous labeling of the `Only people who have been invited` in the Group/Comunity page (https://server.local/#/group/+c1:matrix-beta.igalia.com

### Steps to reproduce

- Create a room `Anyone who knows the room's link, apart from guests`
- Add it in a Comunity
- The room is listed without the `GUESS CAN JOIN` label

- Create a room `Only people who have been invited`
- Add it in a Community
- The room is listed with the `GUESS CAN JOIN` label (even when they actually cannot join)

Describe how what happens differs from what you expected.

`/_matrix/client/r0/groups/%2Bc1%3Amatrix-beta.igalia.com/rooms?`

For the case of the room is set as `Anyone who knows the room's link, apart from guests`:

```
{"name":"Test","topic":"","join_rule":"public","history_visibility":"shared","guest_access":"forbidden", ...}
```

```
{"total_room_count_estimate": 2, "chunk": [
    ...
    {"name": "Test", "num_joined_members": 1, "room_id": "!hPlUlbYcUQxaiyzxlo:matrix-beta.igalia.com", "guest_can_join": true, "is_public": false, "world_readable": false}
]}
```

For the case of the room is set as `Only people who have been invited`:

```
{"name":"Test","topic":"","join_rule":"invite","history_visibility":"shared","guest_access":"can_join", ...}
```

```
{"total_room_count_estimate": 2, "chunk": [
    ...
    {"name": "Test", "num_joined_members": 1, "room_id": "!hPlUlbYcUQxaiyzxlo:matrix-beta.igalia.com", "guest_can_join": true, "is_public": false, "world_readable": false}
]}
```

I think the API is a bit poor in this meaning and lost the status of the `join_rule` so the UI cannot identify those rooms which are only accessible by invitation (therefore non guess can join). In other case, the `guest_can_join` should have in account the value of the `join_rule` as well

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

both of them: matrix.org and matrix-beta.igalia.com

If not matrix.org:
- **Version**:        What version of Synapse is running? 0.32.2 
- **Install method**: pip      
- **Platform**:    LXC / Debian 9

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
