### ISSUE TITLE
Trailing slashes required on some federation endpoints

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3622]
* [ ] `PUT /send/$txnId`
* [x] ~~`GET /pull`~~ Unused endpoint
* [ ] `GET /event/$eventId`
* [ ] `GET /state/$context`
* [ ] `GET /state_ids/$roomId`
* [ ] `GET /backfill/$context`
* [ ] `GET /groups/$groupId/roles` 
* [ ] `GET /groups/$groupdId/categories`

**Comment by neilisfragile** [comment]
Proposed implementation is for Synapse to be permissive in what it accepts, ensure that its own requests are spec compliant but if the remote end rejects, then retry on the alternative form.

**Comment by anoadragon453** [comment]
So what do people think about removing the `[^/]*` at the end of every servlet's `PATH` variable and instead consolidating it all into BaseFederationServlet, which'll just stick a `[^/]*` at the end of the path, where `[^/]*` means 0 or more `/`s that doesn't count as part of the pattern.

**Comment by anoadragon453** [comment]
Sytest is going to need some changes as well in terms of what it expects (`/` vs no `/`).

**Comment by richvdh** [comment]
reopening this because #4793 got reverted

**Comment by anoadragon453** [comment]
Done in https://github.com/matrix-org/synapse/pull/4935
