### ISSUE TITLE
Inviting users to groups is not idempotent and throws exceptions

### ISSUE THREAD

**Issue by spantaleev** [matrix-org/synapse#3623]
This is somewhat related to #2633 and caused by the changes done in #3128.

Currently, if a user is already invited to a group, subsequent invites (done with a `PUT` to `/_matrix/client/r0/groups/<community-id>/admin/users/invite/<invitee-id>`) would return an HTTP 500 error and would spew some database exceptions in the logs, like:

```
psycopg2.IntegrityError: duplicate key value violates unique constraint "group_invites_g_idx"
```

-------

Since this is a `PUT` request, I believe the invitation handling should be idempotent and the API should just return the same response it returned the first time (`{"state": "invited"}` or whatever).

That is, the above exception (or rather `self.database_engine.module.IntegrityError`) can probably just get swallowed somewhere. Where that should go exactly (`groups/groups_server.py` or `storage/group_server.py`) and how to swallow it from a deferred, I'm not sure.

**Comment by erikjohnston** [comment]
(Though spaces will likely replace communities)

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
