### ISSUE TITLE
Remove prev_state handling

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3635]
It's not used, so it shouldn't be handled (federation_client.py, etc)

**Comment by Half-Shot** [comment]
I want to bump the priority on this: While this isn't specced, it's required that all PDUs over federation include `prev_state` as an empty array or they will be rejected.

This is a problem for anyone trying to make a third-party homeserver.

**Comment by richvdh** [comment]
although this predates #4787, I'm going to close it in favour of that one as #4787 better expresses the urgency.
