### ISSUE TITLE
Documentation on how to use anti-spam

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3637]
I could not find any. It would be really nice if we had some.

**Comment by krombel** [comment]
You need to implement a module which implements the interface which is used by [this file](https://github.com/matrix-org/synapse/blob/f7b133fc267f92734b88000f0f0450b3118ca713/synapse/events/spamcheck.py) and configure it according to this:
https://github.com/matrix-org/synapse/blob/f7b133fc267f92734b88000f0f0450b3118ca713/synapse/config/spam_checker.py#L31-L34

**Comment by Half-Shot** [comment]
I know :). I'm now hacking on https://github.com/matrix-org/antiscam but I think it would be nice to have a rst document somewhere explaining it in greater detail.

**Comment by clokep** [comment]
This was added in #6906.
