### ISSUE TITLE
Can't remove local alias on external room

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#3640]
Hey i have a user here from matrix.org who locked theirself out of a room which before got a telematrix alias from my homeserver.
They wan't to keep the alias which still is assigned to the room at matrix.org.

The only way to remove the alias i found was:
```
curl -H 'Authorization: Bearer <snip>' -X DELETE https://localdomain.de/_matrix/client/r0/directory/room/%23telegram_%3A<snip>:localdomain.de
```
But it fails like:
```
{
    "errcode": "M_UNKNOWN",
    "error": "Room alias must be local"
}
```

Regards

**Comment by richvdh** [comment]
seems like an old bug which is probably fixed.
