### ISSUE TITLE
we really shouldn't accept to_device messages for non-existent devices

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3656]
we sometimes get to_device messages for devices which have been deleted (for example, because clients send key_requests for them. They then just sit in device_inbox and fill up the disk.

**Comment by richvdh** [comment]
related: #3599

**Comment by anoadragon453** [comment]
After some local testing, it looks as if we do ignore `to_device` messages - both from federation and local clients - to devices that don't exist. I believe this line enforces that: 

https://github.com/matrix-org/synapse/blob/6633a4015a7b4ba60f87c5e6f979a9c9d8f9d8fe/synapse/storage/databases/main/deviceinbox.py#L509-L513

However, https://github.com/vector-im/element-web/issues/15638 shows (and I can confirm a similar situation on my own homeserver) that `to_device` messages to public cross-signing keys are being captured and stored forever. They are also the most prevalent for my user in my homeserver's database.

So one of the main problems with `device_inbox` table growth may not be that we're not ignoring messages to unknown devices, as we do seem to be doing so. The cross-signing keys seem to be real devices that exist in the `devices` table.

**Comment by anoadragon453** [comment]
I think this can be closed in favour of https://github.com/matrix-org/synapse/issues/9348.
