### ISSUE TITLE
we never clear out cache_invalidation_stream

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3665]
This table is used to communicate cache invalidations to the workers. Once they've read them, the data therein is redundant, and we should automatically clear it out

**Comment by richvdh** [comment]
As a workaround for this in the meantime, you can clear them out manually from a psql shell:

```sql
-- this will delete invalidations older than 24 hours ago

DELETE FROM cache_invalidation_stream 
WHERE stream_id <= (
  SELECT stream_id FROM cache_invalidation_stream 
    WHERE invalidation_ts < (extract(epoch from now())-(24*3600))*1000 
    ORDER BY stream_id DESC 
    LIMIT 1
  );
```

**Comment by MurzNN** [comment]
Confirm issue, on my homeserver `cache_invalidation_stream` table have 2364467 rows :(
Can I safely clean-up it via proposed workaround sql query?

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/13456
