### ISSUE TITLE
Lock load history

### ISSUE THREAD

**Issue by cavabanga26** [matrix-org/synapse#3671]
Hello! I need that for certain contacts that have a match in the name, when connecting from the client, not all the previous history was loaded, but only a few messages or not loaded at all. Clients communicate with the server using the API, tell me where to make the necessary changes on the server?

**Comment by krombel** [comment]
@cavabanga26 Sorry, but I don't understand, what you want...
Should some contacts be restricted to access room history?
Or is there some issue that some contacts cannot access the history although they should be able to?
Or something else?

**Comment by richvdh** [comment]
I'm afraid I don't really understand what's being asked for here.
