### ISSUE TITLE
register_new_matrix_user talks to https://localhost:8448, whether or not the C-S API is configured there

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3672]
for anyone running with the recommended config of having the C-S API behind a reverse-proxy, or moving things to non-standard ports, this isn't going to work. Given we parse the config file to find the shared secret, why don't we also at least sanity-check that we're connecting to a port with the C-S API exposed?

**Comment by richvdh** [comment]
also: wouldn't `http://localhost:8008` be a more sensible default, since that is where synapse listens with the default configuration?

**Comment by danger89** [comment]
Yes, so the command on Docker would be:

`docker exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml`
