### ISSUE TITLE
Ask for the current password when a new email is associated to the Matrix account

### ISSUE THREAD

**Issue by Edu4rdSHL** [matrix-org/synapse#3688]
### Description

The option to add an email to his account, for which Riot (for example) does not ask for confirmation of the actual password, is a huge security breach. Suppose your session is open on a public computer or someone got access to your computer, anyone can add an email address, confirm it and then change your password and do what he wants. I reported it on #riot:matrix.org and #riot-android:matrix.org in the first place, but they suggested that I report it here.

### Steps to reproduce

1. Leave a Matrix session open in your browser (note that you do not know the current password of the user)
2. Use the "add email address" option in your client (Riot support it), add the email and confirm it.
3. Open https://riot.im/app/#/forgot_password and fill the fields.
4. Confirm the link that was sent.
5. You can now access to the matrix account with the new password.

<!-- If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly. -->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

- **Homeserver**: All synapse homeservers are affected (it's a design issue).

**Comment by mvgorcum** [comment]
Downside of this change would be that if you forgot your password and never registered a mail address but do have a valid access token you can't change your password by adding a mail account.

**Comment by richvdh** [comment]
I'm not sure when this got fixed, but my synapse certainly does ask me for my password before it lets me add a new email address.
