### ISSUE TITLE
Are there plans to move to python 3?

### ISSUE THREAD

**Issue by Rillian-Grant** [matrix-org/synapse#3695]

**Comment by turt2live** [comment]
Yes, it is a huge work in progress that can be tracked here: https://github.com/matrix-org/synapse/pull/3576.

In general questions like this are best asked in the [#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org) channel - there are people there, including the wider community, who are better equipped to answer these kinds of questions.

**Comment by Rillian-Grant** [comment]
Thank you.
