### ISSUE TITLE
Changing 1 room as Direct Chat, the API requires me to pass ALL the rooms which are Direct Chat

### ISSUE THREAD

**Issue by sraja415** [matrix-org/synapse#3711]
When I change a Group to Direct Chat via API, it looks like I need to pass ALL the rooms which are Direct Chats as Parameters. This does not sound right. Why would I need to pass ALL the rooms and IDs for changing 1 Room to Direct Chat. 

Direct Chat "Accept" also does the same thing looks like

example I have A,B,C,D as Direct Chat and X,Y,Z as Rooms/Groups. When I change X to Direct Chat, I have to pass A,B,C,D,X to make just X as a Direct Chat

This is not right. We need to change the API.

**Comment by richvdh** [comment]
this is more of a spec issue. Could you open a bug against matrix-doc instead?

**Comment by sraja415** [comment]
How do I do that? I don't see Label option when I open bugs.

**Comment by t3chguy** [comment]
github.com/matrix-org/matrix-doc
Synapse is just one of many server implementations.
