### ISSUE TITLE
frontend_proxy worker claims it forwards requests to the main process, but it doesn't

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3717]
Having ensured I set up the `worker_main_http_uri` to point to the main process, making a request to something like `/_matrix/client/versions` results in a 400 unrecognized request. There's no evidence that it actually tries to contact the main process (no additional logging in the worker or main process)

**Comment by erikjohnston** [comment]
The frontend proxy only proxies certain paths: https://github.com/matrix-org/synapse/blob/master/docs/workers.rst#synapseappfrontend_proxy, which does not include `/_matrix/client/versions`

**Comment by erikjohnston** [comment]
Oh, the docs are wrong
