### ISSUE TITLE
new_room_user_id should be optional on /shutdown_room so you can remove rooms without repointing users elsewhere

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3761]

**Comment by richvdh** [comment]
this should be a trivial change now that https://github.com/matrix-org/synapse/pull/7613 has landed. @dklimpel any interest in picking it up?

**Comment by dklimpel** [comment]
@richvdh I can do it. But does this make sense? Does the old API still need to be adapted?
Anyone who would like this feature can use the new API. ```POST /_synapse/admin/v1/rooms/<room_id>/delete```

**Comment by richvdh** [comment]
@dklimpel is it possible to shutdown a room without running a `purge` on it?

**Comment by dklimpel** [comment]
No, I'm afraid not, it is not possible to shutdown without ````purge```. I thought it was not a use case.
An alternative would be to add an option for purge room or not for the new api. What would you prefer, modify ````shutdown api``` or ```delete api``` or both?

**Comment by richvdh** [comment]
I think it probably makes more sense to modify the delete api.

**Comment by dklimpel** [comment]
Ok. I'll put it on my to-do list and wait for merging #7953
