### ISSUE TITLE
I updated Ubuntu 16.04 on 8/25 and it broke my installation. 

### ISSUE THREAD

**Issue by ThoughtMonster** [matrix-org/synapse#3766]
After the update, I could no longer post messages from my server, but I was receiving messages from federated servers.

I got frustrated and reinstalled everything, exactly as I had before, and now I can post, and I can receive, but nothing is decrypting.

I'm pretty new to this, and don't even know where to look for the appropriate logs. I know that's annoying. I appreciate any help or suggestions.

**Comment by richvdh** [comment]
`#synapse-community:matrix.org` is a better place to ask for support.

I'm not surprised that things are broken after you reinstalled: https://github.com/matrix-org/synapse/wiki#i-have-a-problem-with-my-server-can-i-just-delete-my-database-and-start-again
