### ISSUE TITLE
Blind Trust Before Verification Process

### ISSUE THREAD

**Issue by maitrenageur** [matrix-org/synapse#3774]
### Description

Is there a way to switch from the device trust verification process into a "blind trust before verification process"? Because for standard users it is more a handicap to fulfill the verification steps, before they can chat.

**Comment by neilisfragile** [comment]
Hi there is no way to do that today, but we're currently reworking the e2e UX and plan to have different modes trading verification / convenience. 

#e2e-dev:matrix.org will have the latest
