### ISSUE TITLE
Add a dockerfile, and publish a working base install to dockerhub

### ISSUE THREAD

**Issue by tracker1** [matrix-org/synapse#378]
It would be nice to see a dockerfile included in the project for easy setup with those running docker... or even a docker compose setup, so that the services (postgres, etc) can run separately.  Maybe during active/early development, not publishing to dockerhub, but definetly a nice to have.

[example via a quick search online](https://hub.docker.com/r/silviof/docker-matrix/~/dockerfile/)

**Comment by almereyda** [comment]
@tracker1 I am soon to push separate images composed at https://github.com/allmende/docker-matrix

**Comment by almereyda** [comment]
The WiP of this lives in https://hub.docker.com/u/allmende/.

**Comment by richvdh** [comment]
dup #969
