### ISSUE TITLE
register_new_matrix_user always creates Admin user

### ISSUE THREAD

**Issue by helmut72** [matrix-org/synapse#3782]
### Description

When creating new users register_new_matrix_user command, every user is an Administrator.

### Steps to reproduce

> register_new_matrix_user  -c homeserver.yaml https://matrix.domain.com
> New user localpart [root]: **user2**
> Password:
> Confirm password:
> Make admin [no]: **no**
> Sending registration request...
> Success.

Then send a chat a message to the user. In the Chat-Room preferences there is a list of all privileged users:
user1:matrix.domain.com is an Administrator
**user2**:matrix.domain.com is an **Administrator**

### Version information

Current and older Synapse versions. Doesn't matter if Synapse is installed with PIP or from a Repository.

**Comment by tulir** [comment]
Room administrators and server administrators are different. Server admins don't have any power over rooms. When you use the "Start chat" button in Riot, it'll set everyone as room admin.

To check if they're server admins, use `SELECT * FROM users WHERE admin=1` in the database.

**Comment by helmut72** [comment]
Ok, sorry. Just checked. Everything is ok. Only one admin. Thanks for explanation.
