### ISSUE TITLE
Project: Chunking

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#3785]
Closed (for now) PRs:

- https://github.com/matrix-org/synapse/pull/3345
- https://github.com/matrix-org/synapse/pull/3343
- https://github.com/matrix-org/synapse/pull/3342
- https://github.com/matrix-org/synapse/pull/3322
- https://github.com/matrix-org/synapse/pull/3321
- https://github.com/matrix-org/synapse/pull/3320

**Comment by ara4n** [comment]
this would/will hopefully fix https://github.com/matrix-org/synapse/issues/1760 (i think), as there will be fewer extremities to resolve if they are hidden inside chunks?

**Comment by ShadowJonathan** [comment]
@anoadragon453 Amber hasn't worked on python for about a year (burnout), the related issues are closed, and this meta-issue doesn't have any other context as far as i can see, can this be closed?

**Comment by anoadragon453** [comment]
The historical state is useful, but indeed I don't think we benefit from having this open currently.

If we decide to work on this again, a new issue with more information about what chunking actually is (tracking connected chunks of the DAG) and what needs to be done would be useful.

**Comment by ShadowJonathan** [comment]
Ahhh, so *thats* what it is! I was confused as to what "chunking" in this context actually meant, if it's compression of long stretches of DAG into just a few database entries, then thats indeed an interesting venue.

I don't have any interest in this at the moment, but i'll remember this idea for other setups and optimisations, possibly.
