### ISSUE TITLE
Edit room directory directly?

### ISSUE THREAD

**Issue by ukcb** [matrix-org/synapse#3787]
I joined a remote room at matrix.org from my homeserver as admin. I don't have permission to list the remote room in the room directory of my homeserver. For this I would have to be a moderator or admin in the remote room. There is no possibility to list a remote room in the room directory as admin of a homeserver. A simple way is missing. An admin should stay an admin.

v0.33.3

**Comment by t3chguy** [comment]
This is completely incorrect. A Server Admin can add any room to their directory, most clients do not expose it as they have no concept of server admin. Direct API calls work just fine.

**Comment by ukcb** [comment]
Ok, maybe it's a bug in riot-web. There the setting for the publication in the room directory is deactivated.

**Comment by t3chguy** [comment]
Yup. Because riot-web has no way of knowing you are a server admin.

**Comment by neilisfragile** [comment]
Closing given vector-im/riot-web/issues/7267
