### ISSUE TITLE
if a join fails because we pick a server who can't manage to send_join, we don't retry

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3811]

**Comment by ara4n** [comment]
or at least if the server's send_join errors with a 403 empirically we don't retry another one.

**Comment by ara4n** [comment]
related to #3013

**Comment by richvdh** [comment]
It's not obvious what we can do here: if the server we attempt to join through gives us a 403, we don't really want to try all the other servers to see if one of them will let us in.

The root problem here is probably https://github.com/matrix-org/synapse/issues/3812: I don't know why we're send_joining through a random server which 403s us.

I'm just going to close this as a dup of #3013
