### ISSUE TITLE
Update instructions for psycopg2 usage to point to psycopg2-binary instead

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3839]
```
federation_sender_1 - 2018-09-10 20:35:40,847 - twisted - 131 - WARNING - None- /home/matrix/.synapse/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: exceptions.UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```

**Comment by hawkowl** [comment]
We need to update the dependencies thing to not hard require psycopg2 :/

**Comment by richvdh** [comment]
Using `psycopg2` where possible rather than `psycopg2-binary` sounds like the right thing to do to me.

It does mean that you need a libpq-dev installed, so opens the #5168 worm-can, but that's a problem we need to solve anyway.

**Comment by xoxys** [comment]
Any suggestions how to deal with psycopg2 in the future?
psycopg2-binary is not detected as a valid dependency for matrix, so we can't use it, but I am running my Database on a different server than Matrix so it is not that simple to build psycopg2 on the matrix server itself.
