### ISSUE TITLE
Negative timings in loglines

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3885]
`2018-09-16 17:47:03,724 - synapse.access.http.8080 - 287 - INFO - GET-7858388 - 80.189.62.205 - 8080 - {@matthew:matrix.org} Processed request: 244.263sec/-64.297sec (0.008sec, 0.000sec) (0.000sec/0.001sec/1) 0B 200! "GET /_matrix/client/r0/groups/%2Bgnosispm%3Amatrix.gnosis.pm/profile? HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36" [0 dbevts]`

-64s, huh?

**Comment by richvdh** [comment]
triple-backticks are a useful thing :-p

And yes, that figure is the time between us finishing the work to prepare the response and the last byte being sent to the client. In this case, the connection dropped 64 seconds before we finished processing it.
