### ISSUE TITLE
Support debian distro

### ISSUE THREAD

**Issue by rzr** [matrix-org/synapse#390]
Until debian is shipping matrix (It will for sure) , community could maintain it on separate branches.

I have a few commit to share , after I imported @erikjohnston packaging files 

https://github.com/rzr/synapse/tree/debian

https://github.com/rzr/matrix-angular-sdk/tree/debian

One packaging is clean for all dependencies too everything could be submitted to debian project.

So the question is , can master project create debian branch to host debian packaging files

I'll keep you updated

ps: I also built it all for ARMv7

**Comment by erikjohnston** [comment]
Heh, I've been spending this morning messing around with debian packaging.

I have created: https://github.com/matrix-org/package-synapse-debian. This is mainly due to the fact that I don't (at least yet) want to pollute the synapse directory with different packaging related config files. This can be reviewed at a later time depending on how things go :)

**Comment by rzr** [comment]
it would help to have one per package , it wont pollute master branch if it is done in separate debian branch to be used with g-b-p ...

I will write a short tutorial how to use those packages ...

Keep in touch

**Comment by erikjohnston** [comment]
A repo per package? That's the current plan :)

I'm more concerned with the extra tagging and branches it seems to like to create and times. And yes, I'm using `gbp`.

Instructions would be great :)

**Comment by rzr** [comment]
Ok I see you took my fix in latest release , thanks...

I made this short howto to make it run on minnowboard :
https://dockr.eurogiciel.fr/blogs/embedded/matrix-debian/

I'll may share a demo image ready to be dumped too and update article next week.

Regards

**Comment by krisak** [comment]
@rzr Thanks realy nice guide! You mention raspberry pi. Your instal doesnt work with raspberry.

`W: Failed to fetch http://matrix.org/packages/debian/dists/jessie/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)`

Does it have to do with ARM? Are the deb packages just for x86?

Thanks

**Comment by 0x004a** [comment]
@krisak Seems like it reading the InRelease file **Architectures: amd64 i386** (no arm).

**Comment by leonerd** [comment]
I don't think the debian build tools support any sort of cross-compiling, so I suspect building for ARM would require actually having some ARM boxes for us to build on. That's something we don't have easy access to in our infrastructure.

However, most of the dependencies are pure python, so the "all" builds for those should work fine. For the remaining few packages that are platform-specific binary, you could always grab our upstream source (using `apt-get source`) then build the package locally (using `debuild -b -uc`)

**Comment by rzr** [comment]
i built it once using apt-build on ARM board
I can do it again if you trust me enough to have them published ;)

**Comment by richvdh** [comment]
I'm not sure what's left to do here. We have debian packages: http://matrix.org/packages/debian/.

**Comment by rzr** [comment]
hint: Try to open a RFP bug on debian.org

**Comment by jvalleroy** [comment]
I see the packaging repository for matrix-synapse. For the other packages on http://matrix.org/packages/debian, are there repositories available?

I have opened an RFP at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=830601. But if you are interested in maintaining these packages within Debian, you could make an ITP and find a sponsor to upload the packages.

**Comment by rzr** [comment]
Thanks, maybe it worth also to check status of each "~matrix" packages too

**Comment by bashrc** [comment]
So are there any arm deb packages for this? Trying to install from source with pip seems highly unreliable.

**Comment by rzr** [comment]
I rebuilt them in the past, and can do it again for you, please tell me which for which target 1st?  like raspbian / rpi2 or rpi0 ?

Related hints

https://www.element14.com/community/people/rzr/blog/2015/11/24/how-to-setup-a-webrtc-gateway-using-matrix-on-minnowmax

**Comment by bashrc** [comment]
armhf

**Comment by kingoftheconnors** [comment]
@rzr What was your technique? I know it's been a few years, but I need to install synapse on my Ubuntu MATE raspberry pi 3b. It always says that `repository 'http://matrix.org/packages/debian bionic InRelease' doesn't support architecture 'armhf'`

Putting the repo in its own component file `/etc/apt/sources.list.d/matrix.org.list` gives the error `malformed entry 1 in list file`

What was your strategy?

**Comment by rzr** [comment]
IIRC I rebuilt on device for arm I have some notes somewhere, is there any wiki where I can share that ?

**Comment by kingoftheconnors** [comment]
I mean, I'm new newbie here. Maybe the wiki for this repo? https://github.com/matrix-org/synapse/wiki
