### ISSUE TITLE
Rename `email.riot_base_url` config option

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#3913]
Since it should work with any url link. We probably also want to make it a template, rather than always appending `#/room/<room_id>`

**Comment by vrongmeal** [comment]
Hey! I'm a newbie here. Would like to contribute. Can someone help me with this?

**Comment by DMRobertson** [comment]
This field has been renamed to `client_base_url` while maintaining the old name as a fallback:

https://github.com/matrix-org/synapse/blob/fa71bb18b527d1a3e2629b48640ea67fff2f8c59/synapse/config/emailconfig.py#L289-L291

The value is not presently a template though.

**Comment by richvdh** [comment]
sounds like the original issue is fixed?

**Comment by DMRobertson** [comment]
I had in mind

> We probably also want to make it a template, rather than always appending #/room/<room_id>

for keeping it open. But if we really want this then we can open a new issue.
