### ISSUE TITLE
Should PUT /directory/room/$alias try to set a canonical alias?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3917]
Currently may clients fail to set a canonical alias when you add one to a room (e.g. Riot/Web), as per the cluster over at https://github.com/vector-im/riot-web/issues/7339.  Rather than expecting all the clients to forget to do this, should the server try to set a canonical alias if the user has power to do so, and if one isn't already set?

Upsides:
 * You'll get consistent results across clients, rather than relying on the client implementers to get it right.

Downsides:
 * It's bit magical
 * What if the user didn't want to mark that alias as canonical?  (What's the use case for that though?)
 * Should DELETE /directory/room/$alias go and try to remove the canonical alias when that alias is deleted?

**Comment by ara4n** [comment]
Conclusion after IRLing is that one could have a helper API called `PUT /.../canonical_alias` which could first try to create the alias if it didn't exist and then create the canonical_alias, but this doesn't really help much given the client could certainly try to figure that out too.  And that in general the interaction between aliases and directories suck, and we should try to figure out how to solve this when that gets solved. Plus it's a spec issue anyway.

So i'm going to fix this clientside for now :|

**Comment by richvdh** [comment]
moving this to a spec issue at https://github.com/matrix-org/matrix-doc/issues/1682, then.
