### ISSUE TITLE
Mail notification triggered by new user is not running

### ISSUE THREAD

**Issue by maitrenageur** [matrix-org/synapse#3935]
### Description

I understand the configuration part "Enable sending emails for notification events“ so far to receive a mail, if a new user is registered.

```
# Enable sending emails for notification events
# Defining a custom URL for Riot is only needed if email notifications
# should contain links to a self-hosted installation of Riot; when set
# the "app_name" setting is ignored.
#
# If your SMTP server requires authentication, the optional smtp_user &
# smtp_pass variables should be used
#
#email:
#   enable_notifs: True
#   smtp_host: "server"
#   smtp_port: 587
#   smtp_user: "user"
#   smtp_pass: "password"
#   require_transport_security: True
#   notif_from: "Your Friendly %(app)s Home Server <noreply@example.com>"
#   app_name: Matrix
#   template_dir: res/templates
#   notif_template_html: notif_mail.html
#   notif_template_text: notif_mail.txt
#   notif_for_new_users: True
#   riot_base_url: "http://localhost/riot"
```

The debugging shows to me the following information: RuntimeError: email.enable_notifs is True but no public_baseurl is set

My simple expectation is, to receive a mail if a new user is available/registered:

1. An attribute like „public_baseurl“ is not a part of the configuration. What does it mean?
2. Which background has the attribute riot_base_url: "http://localhost/riot“? I don’t use a local Riot instance, but it is requested by Synapse, otherwise Synapse will not start.

Thank you

**Comment by richvdh** [comment]
please do come to the riot rooms for support requests.
