### ISSUE TITLE
Spell out clearly in the README that increasing your cache factor may well reduce your overall RAM footprint

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#3939]
We have many instances of people who, on seeing Synapse use too much RAM, reduce their cache factor.

This often makes things even worse, as if they are blowing out the cache then requests slow down and stack up and end up using more RAM overall.   So the solution is actually to increase the factor (typically to 1.0 or 1.5).  This is particularly obvious on underpowered servers like Scaleway ARM VPSs.

See also https://github.com/matrix-org/synapse/issues/3876

**Comment by aaronraimist** [comment]
Should be fixed by #4276
