### ISSUE TITLE
publicRooms API should not return not-federated rooms

### ISSUE THREAD

**Issue by giomfo** [matrix-org/synapse#3950]
I name here "not federated" room, a room which has been created with the creation_content: {m.federate: false}. This option blocks users on other matrix homeservers from joining this room.

The `publicRooms` API should not return the not-federated rooms when the selected server is not the user's homeserver.  

It should also not return rooms which require an invite.

**Comment by anoadragon453** [comment]
So there are two possible solutions to this:

1. Block access to publicRooms on the federation API (preventing other homeservers from querying it)

This would keep users on `e` from being able to see public rooms on `i`.

2. When a room is created as non-federate/set to invite only, don't put it into the `public_rooms` table

This would be the "proper fix", though would require us to prune the DB of all non-federate/invite-only rooms that were put into `public_rooms` earlier.

Thoughts? 1 is the easiest but may not be exactly what we want (hide all `i` servers from `e`).

**Comment by michaelkaye** [comment]
Where block access could be "Limit access to the federation endpoint to only certain IP addresses" and so long as the synapse accepts a rejection neatly we should be OK?

**Comment by anoadragon453** [comment]
So are we going with option 1 then?

**Comment by anoadragon453** [comment]
Fixed in #4746
