### ISSUE TITLE
It should be possible to configure a list of IPs synapse will not make outbound connections to

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#3953]
We have `url_preview_ip_range_blacklist`, but no equivalent for federation requests. The attack surface is of course much smaller, but I still don't like the idea of my synapse going and hitting random HTTP servers within my firewall because someone pointed a DNS record at them. In particular, it's currently possible to make synapse send requests back to itself with a DNS record which resolves to 127.0.0.1

**Comment by richvdh** [comment]
fixed by #5043

**Comment by rubo77** [comment]
Is it possible to blacklist a domain like this? I got thousands of warnings in my log about a domain, that is not reacheable any more

**Comment by anoadragon453** [comment]
@rubo77 We don't support blacklisting a domain (yet), but if you can resolve the DNS to an IP address you should be able to add it to `ip_range_blacklist` to prevent outbound requests.

Alternatively it could be blocked at the firewall level.

**Comment by rubo77** [comment]
I guess there is no use to block a domain, that is not reacheable anyway.

So if I would resolve the domain localy in my `/etc/hosts ` file to a dummy I like 10.13.13.13 and then blacklist that IP, would that work?
