### ISSUE TITLE
member list incorrect

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/synapse#3954]
### Description

On my homeserver (roeckx.be), in the room #megolm:matrix.org, @mujx:matrix.org is not part of the members.

This of course causes problems that he can not read anything I say, because I never send him any keys.

### Version information

- **Homeserver**: roeckx.be

- **Version**: 0.33.5.1-1matrix1
- **Install method**: .deb package, using apt
- **Platform**: Debian stretch

I've just upgraded it, the problem was also there with 0.33.4-1mx1

**Comment by neilisfragile** [comment]
Does clearing your client cache fix the problem for you?

**Comment by kroeckx** [comment]
It does

**Comment by richvdh** [comment]
sounds like a dup of https://github.com/vector-im/riot-web/issues/3846 / https://github.com/matrix-org/synapse/issues/2735 then.
