### ISSUE TITLE
Possible half-solution to #3527

### ISSUE THREAD

**Issue by barudaret** [matrix-org/synapse#3983]
With regard to the issue in #3527 which was never resolved, but rather closed due to its high difficulty... I propose a sort of half-solution.

As it is, the only way to solve this problem afaik is to contact the admin of whatever room broke everything and have them kick you from the room.  Maybe someone can write a script for server admins, so that they can force the server to send a **Leave** event, even though the server doesn't think the user is in that room.

**Comment by barudaret** [comment]
Granted I don't know how all this works.  But I'm just thinking about this since I ran into this problem _again_ today.  And this time, another weird thing happened, where the room's admin says he kicked me from the room, but that kick apparently didn't federate to the other servers, so I'm still stuck in the bad state.

**Comment by jevolk** [comment]
This sounds like a typical synapism, solving the wrong problem with the wrong solution. #3527 shouldn't be a problem in the first place and jumping through hoops by setting leave and kick states to solve it shouldn't be necessary. Once you issue a join event and other servers see it then your state is join and if there is a problem with circulation then circulation should be fixed by this implementation, not the state...

**Comment by jevolk** [comment]
It's as simple as the local server persisting the join event before sending the `/send_join/` knowing that the remote server has this asinine tendency to try and fully circulate it before responding with the `200 OK` (by the way that's called an amplification attack ... watch, one day ...) which synapse/implementations shouldn't be doing anyway.

**Comment by barudaret** [comment]
I agree.  However, even if the backwards join dealio gets fixed, it doesn't solve the problem for those already stuck in that state.  Which, btw, I still am stuck in that state.  I am at a loss, I have no idea how I'll fix the problem as it is right now.  I can neither leave nor get kicked, and all these servers think I'm in that room and my HS is getting mauled.

**Comment by barudaret** [comment]
The good news is that I think I've been able to help isolate what caused the problem.  IIRC before it was thought that this might happen if a room is just too big.  Maybe, but that's not the cause this time, because the room I joined is not big, only 260 users.  Rather, I looked at my server logs and found the exact moment everything went wrong.  I'll upload that here for you all:

[half-shot_log_the-moment-it-all-went-wrong.txt](https://github.com/matrix-org/synapse/files/2430733/half-shot_log_the-moment-it-all-went-wrong.txt)

**Comment by barudaret** [comment]
It all begins on this line:

```
2018-09-28 20:27:29,869 - synapse.federation.federation_base - 186 - WARNING - POST-4368 - Signature check failed for $14956810879831oCJoS:half-shot.uk: 401: Invalid signature for server half-shot.uk with key ed25519:a_YjQO: Unable to verify signature for half-shot.uk
```

And so, at least in this case, the whole thing is thrown off by invalid events in the room, rather than the size of the room.  My server is rejecting those events.

**Comment by barudaret** [comment]
Actually, this looks pretty much exactly the same as #3573

**Comment by barudaret** [comment]
More than likely has something to do with #2806 since the events which are throwing errors are very old, the earliest state events of the room.

**Comment by jevolk** [comment]
> Okay I solved my particular issue. It was pretty much the same as #3573 and very much related to #2806. See #3573 for the solution. But yeah, sorry to sidetrack the thread like that. Back to the main topic: **Force a leave event to fix the inconsistent state? (Y/n)**

Your solution here is to help us develop a better homeserver rather than one developed by Synapse's parent company. We're now working on the Construct over at https://github.com/matrix-construct and [#zemos-test:matrix.org](https://matrix.to/#/#zemos-test:matrix.org) (or #test:zemos.net if it's online).

**Comment by richvdh** [comment]
I'm afraid I don't really understand what is being proposed here:

> With regard to the issue in #3527 which was never resolved, but rather closed due to its high difficulty

#3527 is not closed.

> Maybe someone can write a script for server admins, so that they can force the server to send a Leave event, even though the server doesn't think the user is in that room.

If the server doesn't think the user is in the room, there is no problem. If the server does think the user is in the room, then an admin can kick them.
