### ISSUE TITLE
Initial lazy loading sync can fail with a 404

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#3984]
The returned error is: `Could not find event $EVENT_ID`, without a stack trace. The event in question has been rejected, so we're probably calling `DataStore.get_event` with that event_id. (Though the more interesting question is where it got the event ID from in the first place)

**Comment by erikjohnston** [comment]
The event in question is a canonical alias event, and so a possible offending `get_event` call would be:

https://github.com/matrix-org/synapse/blob/19dc676d1aaf66a45c9a1810132952f7ae3ca2aa/synapse/handlers/sync.py#L575

Though that would imply that the rejected event had somehow gotten into the state.

**Comment by erikjohnston** [comment]
In fact, it explicitly says `allow_none=False`, and then checks if the event returned is `None`...

**Comment by ara4n** [comment]
@erikjohnston - was this fixed by #3986? i haven't seen it in forever.

**Comment by erikjohnston** [comment]
I guess so? Let's go with yes!
