### ISSUE TITLE
Release Synapse v0.33.6

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#3992]

**Comment by ptman** [comment]
Docker tag is still missing. Is there a separate ticket for that?

**Comment by richvdh** [comment]
sorry, good point. We also need to upgrade modular.im.

**Comment by Luzifer** [comment]
The 0.33.6 release commit is used as a tag on DockerHub, so looks like something at DockerHub went wrong in the build…

**Comment by ananace** [comment]
Considering the dates of the build information on docker hub, it feels more likely that they haven't built tags on there for a while. The [broken job on CircleCI](https://circleci.com/gh/matrix-org/synapse/4258) seems like a much more likely candidate for the lack of a pushed tag.

**Comment by richvdh** [comment]
what @ananace said. For reasons I forget, the automated builds didn't work at dockerhub. I've rerun the circleci build, which has worked \o/

**Comment by Ryonez** [comment]
Wait, is there another official docker image?

The one I know of is: https://hub.docker.com/r/avhost/docker-matrix/
Which is listed here: https://matrix.org/docs/projects/server/synapse.html

**Comment by ptman** [comment]
@Ryonez that is not an official image, it is just an image that was available before the official one. Documentation could certainly be updated. Official docker stuff is in https://github.com/matrix-org/synapse/tree/master/docker and the image is https://hub.docker.com/r/matrixdotorg/synapse/

**Comment by Ryonez** [comment]
Good to know thank you. I'll look at switching to it soon.
