### ISSUE TITLE
event reports get lost in a database table

### ISSUE THREAD

**Issue by CHANist** [matrix-org/synapse#4007]
In Client Server API r0.4.0, I found that client can report any inappropriate event to server admins, but in synapse, what it does, seems to store it to the database, and do nothing else. 
I think that a better approach is to create a single room and puts all server admins into this room, and when there are any inappropriate events client sent to the server, it would push to this room, specifying who send the request, the roomId and the inappropriate eventId. So that server admin can have a look at the events. And if it is inappropriate, server admins will have the right to delete the message, or even deactivate the user.

**Comment by richvdh** [comment]
for the record: the reports go into `event_reports`.

**Comment by anoadragon453** [comment]
I think we can close this now that https://github.com/matrix-org/synapse/issues/4007 is a thing.
