### ISSUE TITLE
Joining rooms and backfill are broken if you change your signing key and use the old ID

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4012]
If you create a bunch of state events, and then change the key and use the same ID, it can cause difficulty for new servers trying to join or backfill such rooms, because the signatures appear invalid

**Comment by richvdh** [comment]
also related: https://github.com/matrix-org/matrix-doc/issues/831

**Comment by richvdh** [comment]
The solution to this is to use a better identifier as the key ID (such as a hash of the public key, or the key itself for ed25519), so that servers *can't* claim that two different keys are both called `ed25519:auto`.

**Comment by richvdh** [comment]
dup #3121

**Comment by richvdh** [comment]
#3121 got resolved by #8350, but I'm not sure joining rooms got the same treatment.

**Comment by richvdh** [comment]
Unverifiable events no longer stop you joining a room altogether (though they can still cause inconsistent state, obviously).

**Comment by richvdh** [comment]
> dup [matrix-org/matrix-spec#807](https://github.com/matrix-org/matrix-spec/issues/807)

I wish I knew what this was actually trying to link to. I'm pretty sure it wasn't that.

**Comment by turt2live** [comment]
> > dup [matrix-org/matrix-spec#807](https://github.com/matrix-org/matrix-spec/issues/807)
> 
> I wish I knew what this was actually trying to link to. I'm pretty sure it wasn't that.

Thanks to email history, we've discovered that it's actually https://github.com/matrix-org/synapse/issues/3121

Best guess is github guessed wrong on the numbered reference when 3121 moved from matrix-doc to matrix-spec (evidenced by https://github.com/matrix-org/matrix-doc/issues/3121 becoming https://github.com/matrix-org/matrix-spec/issues/807 )
