### ISSUE TITLE
Synapse v0.33.6 Docker image lacks res/templates

### ISSUE THREAD

**Issue by spantaleev** [matrix-org/synapse#4014]
Ever since #3972 (the first final build of which appears to be `v0.33.6`), the Docker image does not include the `/synapse` directory anymore.

All the code is still in `/usr/local/lib/python2.7/site-packages/synapse` and it works as expected, but `res/templates` is not available anywhere anymore (used to be in `/synapse/res/templates`).

This means that container users (such as [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy)) which want to use the default email templates cannot easily do it anymore.

**Comment by ptman** [comment]
There was some slimming down, maybe it was a bit too agressive

**Comment by spantaleev** [comment]
Seems like this:

```Dockerfile
RUN pip install --prefix="/install" --no-warn-script-location \
        lxml \
        psycopg2 \
        /synapse
```

will not copy any of the files specified in `MANIFEST.in`, thus ignoring the files in `res/`.

Those files would be part of the source distribution archive, but not part of the installed files.

Some more information about it is here: https://stackoverflow.com/questions/3596979/manifest-in-ignored-on-python-setup-py-install-no-data-files-installed

Seems like one solution is to move the `res` directory into `synapse/` (thus making it "package data") and to change `MANIFEST.in` like this:

```diff
-recursive-include res *
+recursive-include synapse/res *
```

Another simple solution might be to just fix the `Dockerfile`, so that it would copy the `res/` directory. However, that's probably fixing a symptom, rather than the actual deeper problem.

Perhaps making `res/` part of the Synapse package data is better, as it will provide email templates for everyone, no matter how they install/use Synapse. Looking at the Archlinux package right now (which also [does a fairly simple installation](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/matrix-synapse) like the above), it does suffer from the same problem - no email templates included. It doesn't feel like there's a good reason to keep them out.

I'm not sure which solution you'd prefer or whether there are any downsides to relocating `res/` like that.

**Comment by richvdh** [comment]
fixed by #4052, I hope

**Comment by spantaleev** [comment]
It does fix it and I can confirm email-sending works!
Thanks for taking care of it so quickly!

**Comment by richvdh** [comment]
well, it turns out that I've made a right old mess of this, as per #4065. @spantaleev: I'm a bit surprised it works for you: could you clarify what your setup is (in particular, what have you set `email_templates` to be)?

**Comment by spantaleev** [comment]
Since the upgrade to 0.33.7rc2, the playbook [no longer defines `email_templates`](https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/6cc528ba5ad784348efedd3de07e16057214cc08) and that seems to work fine. Hmm..

**Comment by richvdh** [comment]
I am mystified :/
