### ISSUE TITLE
Remove locked upsert on e2e_device_keys_json

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4015]
We upsert frequently enough that it stops the postgres autovacuum, which eventually leads to postgres blocking the upserts (which in turn then end up wedging the DB pool)

**Comment by richvdh** [comment]
this happened again last night

**Comment by anoadragon453** [comment]
This good to close now that https://github.com/matrix-org/synapse/pull/4306 is merged?

**Comment by richvdh** [comment]
let's keep it open until #4306 is deployed, since it just took everything out for 15 minutes

**Comment by richvdh** [comment]
fixed by #4306 \o/
