### ISSUE TITLE
README claims a restart isn't required when updating certificate

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4025]
> When updating the SSL certificate, just update the file pointed to by `tls_certificate_path`: there is no need to restart synapse. (You may like to use a symbolic link to help make this process atomic.)

However, empirically this doesn't seem to be the case, and looking at the code it appears the file is only read on start up.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/blob/33716c4aea130a59f704f08f2bd0c32b013a54d4/synapse/crypto/context_factory.py#L44-L49

Seems to be the only place where we read from files after startup, though we *do not* re-read the private key. So it looks like only the certificate chain files and the DH parameters are re-read from disk.

Crucially, the server keys resource still returns the TLS fingerprints cached on startup.

**Comment by richvdh** [comment]
infinite sadness. I have no real idea what made me write this.

**Comment by richvdh** [comment]
fixed in https://github.com/matrix-org/synapse/pull/4343
