### ISSUE TITLE
Messages not being sent over federation

### ISSUE THREAD

**Issue by SylvainCecchetto** [matrix-org/synapse#4029]

**Comment by richvdh** [comment]
As I said, I don't think the StoreError is relevant in this case. can you share logs via PM please.

**Comment by SylvainCecchetto** [comment]
Log sent by Matrix user sy6sy2

**Comment by richvdh** [comment]
For reasons I don't understand (possibly the same as whatever caused #4023), the federation stream position was higher than the most recent stream_ordering:

```
matrix_synapse=> select * from federation_stream_position;
    type    | stream_id
------------+-----------
 federation |        -1
 events     |    101244
(2 lignes)
```

(latest event stream ordering was 101000)
