### ISSUE TITLE
Discordification of Matrix/Synapse/Dendrites (feature request)

### ISSUE THREAD

**Issue by DonaldTsang** [matrix-org/synapse#4030]
I have been a Riot user for about one and a half years, and I would hope for these features to give people a better user experience (features recommended from friends in Discord)
- [ ] Room feature support
    - [ ] Custom server-based and room-based emojis
       - Have custom server emojis downloaded and be usable as a basic feature
    - [ ] Emoji collection sharing
        - Similar to Telegram, Messenger, LINE and Whatsapp, but shareable and if possible, self-hosted or user-hosted
    - [ ] Emoji reaction for texts and files (useful for voting)
    - [ ] Automated (non-manual) key sharing
        - Some people are sick of needing to sharing key every time someone gets in the room, they would like to have auto key sharing once in an E2E room
    - [ ] Multi-room search
- [ ] Community support
    - [x] Community id generation
    - [ ] Community room mass generation
    - [x] Community room searching
    - [ ] Community multi-admin multi-mod support
    - [ ] Community and sub-community sort
- [ ] Role and access support
    - [ ] Mass room invitation by role or community
        - invitation to a server once application is approved
    - [ ] Mass room banning/kicking by role or community
        - for when "unfavorable" behavior by certain users happen
    - [ ] Community room sub-categorization and access
        - for visitor vs club member vs club staff separation
    - [ ] Role application and removal
        - for upgrading users to automatically bring them to certain rooms
    - [ ] Announcement rooms by role
        - rooms that allows viewing but not posting unless it is staff
    - [ ] Reaction allowance by role
       - for voting by certain role but not others
- [ ] audio chat support
    - [ ] self-host SIP room support (tying SIP with server)
    - [ ] self-host  Mumble room support (tying Mumble with server)
    - [ ] Radio/Playlist bot support
- [ ] collaborative support
    - [x] self-host Etherpad/Firepad support (tying *pad with server)
    - [ ] self-host Hackmd support (tying Hackmd with server)

Cross-reference: https://github.com/vector-im/riot-web/issues/7487

**Comment by TheEvilSkeleton** [comment]
Any update on this?

**Comment by Kellegram** [comment]
Would also appreciate an update, especially proper community support is really needed for this to kick off.

**Comment by erikjohnston** [comment]
I'm going to close this in favour of https://github.com/vector-im/element-web/issues/7487. The Synapse team aren't actively driving this either, so having a duplicated meta issue here isn't particularly useful for us :slightly_smiling_face:

**Comment by Kellegram** [comment]
Fair enough.
