### ISSUE TITLE
Add info about the max upload limit when upload fails

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#4037]
If you upload a large file, you get the error message

> Upload Failed
> The file 'verylarge.mp3' exceeds this home server's size limit for uploads

It would help a lot to the user, if the message would tell you the upload limit in this case.

**Comment by richvdh** [comment]
I thought it did (cf https://github.com/matrix-org/matrix-doc/pull/1189 / https://github.com/matrix-org/synapse/pull/3184 / https://github.com/matrix-org/matrix-react-sdk/pull/1876)

**Comment by rubo77** [comment]
not working in riot-web version: 0.16.0 with synapse "0.33.5.1"

**Comment by richvdh** [comment]
@Half-Shot did I imagine this?

**Comment by Half-Shot** [comment]
> @Half-Shot did I imagine this?

@richvdh The react-sdk PR is still awaiting review so this doesn't happen yet.

**Comment by Half-Shot** [comment]
I don't think this needs to be kept open since Riot has the means to tell you the limits, whereas synapse doesn't even generate that error.

**Comment by richvdh** [comment]
yup, so this is a riot bug. thanks Half-Shot.
