### ISSUE TITLE
publicRooms API is repeatedly timing out on basic searches

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#4043]
The PublicRooms API times out due to having to do oodles of state resolution to do even name searches.

original:
presumably due to client_reader being overloaded, or bad caching or whatever. is there something simple we can do like switch it to py3 and triple the size of its caches?

**Comment by richvdh** [comment]
The PR for this is #6019 .

**Comment by richvdh** [comment]
or possibly #5947?

**Comment by richvdh** [comment]
fixed by #6019
