### ISSUE TITLE
Hot-swapping the /sync filter fails silently

### ISSUE THREAD

**Issue by ghost** [matrix-org/synapse#4044]
### Description

There's a regression in how Synapse responds to changing the `/sync` filter whilst using an existing sync token.

### Steps to reproduce

- Call `/sync` with a filter set to ignore all events, and without a sync token
- Next, call `/sync` with the sync token received in the previous step, but with a (different) filter set to accept everything

Describe how what happens differs from what you expected.

- Previously, the second step would return an error as if the sync token didn't exist.

- Currently, the call to /sync succeeds, but no events are ever received, implying that the new filter didn't take.

- (Ideally, in future, one could expect this to just work, but right now this is probably a regression.)

<!-- If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly. -->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

matrix.org

**Comment by clokep** [comment]
> Currently, the call to /sync succeeds, but no events are ever received, implying that the new filter didn't take.

More likely i suspect that there are no more events to see. If you hold onto the sync token, then wait for another event to occur it should be returned.

Anyway, I'm fairly certain changing filters works fine for sync now, so I'm going to close this.
