### ISSUE TITLE
Tag Deletion not working using API when event is broken

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/synapse#4053]
### Description
I have because of creating tags using Quaternion for some rooms broken m.tag events in the rooms account_data. I tried to use the `DELETE /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}` Endpoint to remove the broken events but even after Synapse does return HTTP 200 the tag event is still there. 

So first of all it should NOT return 200 in this case and second it should be able to resolve that (It basicly breaks the usage of my account...).

The account_data generated by creation looks like this:

```
"account_data": {
          "events": [
            {
              "content": {
                "tags": {
                  "m.favourite": {
                    "order": 0.2817608267132813
                  }
                }
              },
              "type": "m.tag"
            },
            {
              "content": {
                "tags": {
                  "m.favourite": {
                    "order": ""
                  },
                  "Freifunk": {
                    "order": ""
                  }
                }
              },
              "type": "m.tag"
            }
          ]
        },
```

### Steps to reproduce

1. Create custom tags using quaternion 0.0.9.2 for a room
2. Try to delete them

### Version information

- **Homeserver**: matrix.ffslfl.net (Private Server)

If not matrix.org:
- **Version**:        0.33.6 
- **Install method**: docker
- **Platform**:       Docker running on Linux

**Comment by MTRNord** [comment]
Just wanted to check: Is this still a thing? :D (I really dont want to break my account again so I dont test it c:)

**Comment by clokep** [comment]
I attempted to reproduce this with something like the following:

```bash
$ curl -H "Authorization: Bearer ${ACCESS_TOKEN}" http://localhost:8080/_matrix/client/r0/user/@test:localhost:8480/rooms/%21UuZfvDAEJYsPhQRdLj%31localhost:8480/tags/foo -X PUT -d '{"order":"foo"}'
{}
```

and then poking around in Riot. I didn't see any issues.

Then deleting with:

```bash
$ curl -H "Authorization: Bearer ${ACCESS_TOKEN}" http://localhost:8080/_matrix/client/r0/user/@test:localhost:8480/rooms/%21UuZfvDAEJYsPhQRdLj%31localhost:8480/tags/foo -X DELETE
{}
$ curl -H "Authorization: Bearer ${ACCESS_TOKEN}" http://localhost:8080/_matrix/client/r0/user/@test:localhost:8480/rooms/%21UuZfvDAEJYsPhQRdLj%31localhost:8480/tags/                               
{
    "tags": {}
}
```

Not 100% sure that matches the behavior of the old Quaternion though.

**Comment by MTRNord** [comment]
I think Quaternion did just a empty string but I guess this should have triggered the same issue as well

**Comment by KitsuneRal** [comment]
As far as I remember Synapse was cooking because of having a string instead of a float, and an empty string was still a string for it. So yes I guess this is no more a problem.

**Comment by MTRNord** [comment]
I will close the issue :) If it ever happens again I guess making a new issue will be better

**Comment by clokep** [comment]
We can always re-open this issue too!

Thanks for coming back to this after over a year!

**Comment by MTRNord** [comment]
It popped up after ranting about possible synapse issue and the plan of writing a fuzzer which would have found this issue :D (I still plan to write a fuzzer for the matrix api)
