### ISSUE TITLE
Docker image is slow to start due to chown command

### ISSUE THREAD

**Issue by scjudd** [matrix-org/synapse#4078]
### Description

When running synapse under docker and setting up the /data directory to be a bind-mount to an AWS EFS file system, the recursive `chown` command that `start.py` executes takes between 5-10 minutes to finish. Synapse doesn't start until this is done.

### Steps to reproduce

- Create EFS file system, mount it from EC2 instance
- Fill EFS volume with lots of files, ideally copying an existing synapse data directory that has been in use for awhile
- Start docker synapse container with EFS volume bind-mounted to /data

I didn't have any sort of log output until after this command finished, so it could have been much simpler to diagnose with a "changing ownership of synapse data files" message. Ideally this shouldn't block synapse from starting.

### Version information

- **Homeserver**: corporate, internal homeserver
- **Version**: v0.33.7
- **Install method**: `docker pull matrixdotorg:v0.33.7`   
- **Platform**: CoreOS, AWS, EFS

**Comment by djmaze** [comment]
I am not sure the chown has to be recursive at all. 

* When starting the container for the first time, the data volume is empty.
* When starting it again, the data inside the volume has already been saved with the correct owner.

So as far as I can see, a non-recursive `chown` on the `/data` directory should be enough.

**Comment by richvdh** [comment]
@kaiyou any reason this is recursive?

Otherwise sounds plausible. A PR would be welcome.

**Comment by scjudd** [comment]
Is there a reason we're using `su-exec` in `start.py` as opposed to the `USER` directive in the `Dockerfile`? It seems to me that we could remove the `chown` entirely and just fail to start if we don't have proper permissions to the contents of our data volume, rather than assume we're being started as a user with permissions to run `chown` in the first place. Thoughts?

**Comment by djmaze** [comment]
> It seems to me that we could remove the chown entirely and just fail to start if we don't have proper permissions to the contents of our data volume

This breaks e.g. docker swarm deployments (like mine) where volumes are automatically created through the stack definition. Manually creating a volume and adjusting its permissions on the server is not a good practice in my opinion. 

Alternatively, creating the `/data` directory in the Dockerfile [before declaring it as a volume](https://devops.stackexchange.com/a/4542) could probably work! At least when used with named volumes as opposed to bind-mounted volumes.

**Comment by scjudd** [comment]
So it seems fundamentally the problem is that you can't _really_ assume anything about the state of the `/data` volume. With a bind-mount volume, any sort of ownership and permissions could be set on the contents and, even with a named volume, it's possible that you brought over something incompatible via `--volumes-from`.

A big recursive `chown` at container boot puts the volume in a known state before starting. The problem is that we've assumed this `chown` isn't expensive, but identified a case where it is.

I think even being able to opt-out of bootstrapping the data volume on launch via a `SKIP_DATA_BOOTSTRAP` environment variable or some such would be an okay compromise. This way it still makes sure permissions are all kosher in the common case but also allows for optimizing for low IO data volumes, if you know what you're doing.

**Comment by scjudd** [comment]
It's complicated. In a non-containerized application, we'd just assume the environment was set up correctly for us to read/write files and wouldn't be able to do anything about it if that weren't true. In a container, we've likely got `root` and _have_ to do a little upfront work to bootstrap the volume. Somewhere in the middle is the right approach.

**Comment by scjudd** [comment]
After iterating on this idea a few times in my head, I think the best solution is what you've suggested. We create `/data` with permissions correct in the `Dockerfile`, _then_ declare it to be a volume. If something out-of-band happens to violate our assumptions about permissions, that should just fail the way it would if we weren't in a container. Does that feel right?

**Comment by djmaze** [comment]
In that case, we should add proper documentation including the command needed for preexisting data / bind-mounted volumes.

**Comment by richvdh** [comment]
This has hopefully been fixed by #5566.
