### ISSUE TITLE
Make Travis CI a bit nicer

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4090]
Currently, it takes forever to run our test suite, which is a bit annoying. Some changes we might want to consider making:

1. Move the builds that take ages to not start last. We probably do want to run pep8/isort first, but equally `packaging` probably doesn't need to run till the end
2. Do we need all the builds? For example do we need to have both `py27` and `py27` old?

**Comment by richvdh** [comment]
I can't really believe that the postgres builds need to take 5 minutes apiece tbh

**Comment by erikjohnston** [comment]
> `py27` and `py27-old` are so that we don't break pip installs (py27) or Debian installs (py27-old).

Do we really need both? I'd have thought just `py27-old` would be enough to catch most issues
