### ISSUE TITLE
Users from other HS can't invite users on my HS

### ISSUE THREAD

**Issue by tleydxdy** [matrix-org/synapse#4098]
I (@tleydxdy:mt.tlebear.win) can create room with or invite people from other HSs, but they cannot invite or start a room with me. Other functions works fine (e2e, video/audio chat, file sharing etc). 
This might be related to #3650, as I found this out during the investigation for that bug.

    Version: currently 0.33.7, happened since 0.33.1, #3650 a while back in 0.31 iirc
    Install method: apt
    Platform: debian 9 VM

**Comment by aaronraimist** [comment]
This I get in Riot when attempting to start a chat with you:
![screen shot 2018-10-26 at 8 18 50 pm](https://user-images.githubusercontent.com/5855073/47598078-6e90c480-d95c-11e8-9807-2b0a2317b212.png)

I don't see anything unusual showing up in my Synapse logs. Can you check your Synapse logs?

**Comment by richvdh** [comment]
this isn't the best place to get support. Try `#synapse:matrix.org`.
