### ISSUE TITLE
Auto Join Room after consent to privacy...

### ISSUE THREAD

**Issue by MparkG** [matrix-org/synapse#4103]
synapse.handlers.register - 227 - ERROR - POST-908- Failed to join new user to '#hallo': ConsentNotGivenError('403: You may not send any messages until you consent to the privacy policy at,)

maybe wait with auto joining till consent is given, or join it anyhow if forced by auto join feature?

**Comment by MparkG** [comment]
Kk thanks

Am 28. Oktober 2018 21:24:06 MEZ schrieb Neil Johnson <notifications@github.com>:
>This will be fixed by #4004
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matrix-org/synapse/issues/4103#issuecomment-433738192

-- 
Max vom Telefon

**Comment by richvdh** [comment]
#4004 has landed so presumably this is fixed
