### ISSUE TITLE
SRV records aren't handled properly

### ISSUE THREAD

**Issue by jcgruenhage** [matrix-org/synapse#4104]
### Description

As described [here in the code](https://github.com/matrix-org/synapse/blob/92faeb2a3fc73bd9307b3192aeacec4afb1aad1a/synapse/http/endpoint.py#L318-L329), load balancing and failover using SRV records doesn't work properly in Synapse.

**Comment by jcgruenhage** [comment]
Update: Load balancing works now, failover doesn't yet.

**Comment by richvdh** [comment]
I think this was fixed in #5864
