### ISSUE TITLE
Do we need the various scripts?

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#4105]
in `scripts/`:
hash_password
move_remote_media_to_new_store.py
sync_room_to_group.pl

in `scripts/dev`:
check_auth.py
check_event_hash.py
check_signature.py
convert_server_keys.py
database-save.sh
definitions.py
dump_macaroon.py
hash_history.py
list_url_patterns.py
make_identicons.pl
sphinx_api_docs.sh
tail-synapse.py

**Comment by richvdh** [comment]
some of them ;-p
