### ISSUE TITLE
Implement cross-signing proposal

### ISSUE THREAD

**Issue by uhoreg** [matrix-org/synapse#4110]
Implement server-side part of https://github.com/matrix-org/matrix-doc/issues/1756. Part of https://github.com/vector-im/riot-meta/issues/222.

- [x] manage master keys
- [x] store and retrieve local signatures
- [x] make sure signatures are properly filtered
- [x] notify users when new signatures need to be fetched
- [x] federate signatures
- [x] sytest everything
- [x] unit test everything

**Comment by uhoreg** [comment]
Main remaining work is cleaning up the code.  We also need to decide whether to use the three-key system or the two-key system, but changing that should not take too long.

**Comment by Thatoo** [comment]
Do you think cross-signing will be implemented in synapse 1.0?

**Comment by neilisfragile** [comment]
@Thatoo While cross signing is nearly ready, we are not expecting it to be there in time for 1.0.

**Comment by Thatoo** [comment]
Good. Too bad for 1.0, it would have been awesome to be able to say "ok guys, matrix is mature for e2e with synapse 1.0".. :-)

**Comment by richvdh** [comment]
@uhoreg can we consider this closed if the synapse side is landed?

**Comment by richvdh** [comment]
see also https://github.com/vector-im/riot-web/issues/9631

**Comment by uhoreg** [comment]
Yes.  Forgot there was an issue here.
