### ISSUE TITLE
Manually batch up `_simple_insert_many_txn`

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4116]
Currently we use `executemany` to insert multiple rows to the DB, but `psycopg2` simply calls `execute` in a loop. This is annoying as when trying to insert hundreds or thousands of rows the RTT to the database can really slow things down.

We should consider manually batching up inserts, as a single insert statement can insert multiple rows.

**Comment by clokep** [comment]
`simple_insert_many_txn` now uses `execute_values` on PostgreSQL and `executemany` (via `execute_batch`) on SQLite:

https://github.com/matrix-org/synapse/blob/a2824465027c9036b98e56a52b53c80ca2aaa71b/synapse/storage/database.py#L1108-L1124

I think we can close this.
