### ISSUE TITLE
synctl should have a `--no-daemonize` option

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4130]
Sometimes it's useful to be able to run synapse in the foreground for debugging. You can do this by running `python -m synapse.app.homeserver` directly, but that means you don't get quite the same environment as synctl gives you, and in any case it's opaque for users.

We should give synctl a `--no-daemonize` option, which makes it run synapse without the `--daemonize` option. 

(It would be an error to try to set `--no-daemonize` and `--all-processes` at the same time)

**Comment by richvdh** [comment]
vaguely related to #1539.

**Comment by richvdh** [comment]
Another time this is useful is for running under systemd: we want to leave all the stdio handling and process management to systemd, but still want the env var munging that `synctl` gives us.

**Comment by dos1701** [comment]
@richvdh if it's still needed I'd like to tackle this one

**Comment by richvdh** [comment]
It'd certainly be helpful. I suggest joining `#synapse-dev:matrix.org` if you have any questions.

**Comment by SohamG** [comment]
Implemented in #5412, issue can be closed
