### ISSUE TITLE
docker-compose.yaml is using the wrong build directory

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#4147]
https://github.com/matrix-org/synapse/commit/0d25724419c43313f9b8345b07aaebe3eeeeee7e#diff-ebacf6f6ae4ee68078bb16454b23247d moved the `Dockerfile` to `./docker` which means it no longer works.

**Comment by alxmhe** [comment]
in the example docker-compose.yml, and if you cloned the synapse repository in the directory as your docker-compose.yml file, you can replace `build: ../..` with :
`
build:
  context: ./synapse
  dockerfile: ./docker/Dockerfile
`

**Comment by richvdh** [comment]
I think maybe this was fixed by #3778?
