### ISSUE TITLE
hash_password doesn't work with python 3

### ISSUE THREAD

**Issue by peterhoeg** [matrix-org/synapse#4159]
### Description

hash_password doesn't work with python 3 while perfectly fine with python 2.

```
peter@dolores:d8ckawjc9q4wz968ysp2mzabi2ykci7v-matrix-synapse-0.33.8/bin $ ./hash_password                                             
  File "/nix/store/d8ckawjc9q4wz968ysp2mzabi2ykci7v-matrix-synapse-0.33.8/bin/.hash_password-wrapped", line 53
    print bcrypt.hashpw(password + password_pepper, bcrypt.gensalt(bcrypt_rounds))
               ^
SyntaxError: invalid syntax
```

### Version information

- **Homeserver**: Own home server
- **Version**:        0.33.8
- **Install method**: package manager
- **Platform**:       NixOS

**Comment by hawkowl** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/4161
