### ISSUE TITLE
Change Terms and Conditions? Legal, Possible ?

### ISSUE THREAD

**Issue by rsacher** [matrix-org/synapse#4171]
I hope, this is the right place to ask:

Is it possible / legal to change the required minimum age of 14 years to say 10 years to use matrix/riot.im services, on a self-hosted server?
Or is this hardcoded in the app (ios, android)?
Where should I look to change this file on our matrix-synapse server?
Background: as a school, we would like to self-host messaging between students and teachers

> You may not use the Website or Services by accepting the terms if: (i) you are not at least 14 years of age and are of legal age to form a binding contract with us; or (ii) you are a person barred from receiving the Services under the laws of the United States or other countries including the country in which you are a resident or from which you use the Services.

**Comment by aaronraimist** [comment]
There are no terms and conditions for Synapse by default. That is just the matrix.org server and riot.im.

If you host your own Synapse server and riot instance then you can choose what you want (ie not have terms and conditions or set your own).

**Comment by jryans** [comment]
The Synapse docs on [consent tracking](https://github.com/matrix-org/synapse/blob/master/docs/consent_tracking.md) explain a bit more about how you can configure this. I believe it may answer most of your questions. The #synapse:matrix.org room might be a good place to discuss further.

**Comment by richvdh** [comment]
yup, this isn't the best place to get support.
