### ISSUE TITLE
Direct chat for users

### ISSUE THREAD

**Issue by cavabanga26** [matrix-org/synapse#4172]
I'm trying to create a direct chat for 2 users - user1 and user2 with API.

1) I create a room as user1 and invite user2, get $room_id:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{  "creation_content": {   
 "invite": ["@user2:domain.local"],   
  "is_direct": "true",
  "preset": "trusted_private_chat",
   "visibility": "private" }' 'http://localhost:8008/_matrix/client/unstable/createRoom?access_token=$user1_token'

2) I accept the invitation to the room on behalf of user2:
curl -XPOST -d '{}' http://localhost:8008/_matrix/client/r0/rooms/$room_id/join?access_token=$user2_token"

In user2, the room is marked as Direct Messages, but in user1 as a group chat. How to fix it? user1 should also be like Direct Messages

**Comment by aaronraimist** [comment]
Joining the room #matrix:matrix.org is probably a better place to get support.

**Comment by turt2live** [comment]
Sorry, I didn't realize that this was also reported here. I've reported the issue as a spec compliance problem: https://github.com/matrix-org/synapse/issues/4173
