### ISSUE TITLE
m.direct not updated on the room creator's account when starting a private chat

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4173]
As per https://matrix.org/docs/spec/client_server/r0.4.0.html#direct-messaging the server should be automatically updating the `m.direct` account data for the creator's account when `is_direct: true` is supplied. Currently, clients have to manually update the account data (Riot does this).

**Comment by reech** [comment]
We create 1:1 rooms programmatically with an application service between userA and userB:

- Create the room
- Get AccountData for userA
- Update AccountData for userA
- Get AccountData for userB
- Update AccountData for userB

5 network requests, which could've been done in 1 since all information is available in the first request. 
Also, the first request strongly suggest it should be done this way : is_direct.

**Comment by ShadowJonathan** [comment]
I'm pretty sure there's a way to instantly update account data from a room creation handler. :wink:

**Comment by reech** [comment]
Yes, excactly that's what we do, but back to the issue:

> the server should be automatically updating the m.direct account data for the creator's account when is_direct: true is supplied

If we should create our own handlers then the documentation should be changed also to include all the other stuff you must do, because this won't help you:

> To start a direct chat with another user, the inviting user's client should set the is_direct flag to /createRoom

**Comment by clokep** [comment]
Looks like we have some special handling for `is_direct`, but don't have this particular bit, see:

https://github.com/matrix-org/synapse/blob/0a00b7ff14890987f09112a2ae696c61001e6cf1/synapse/handlers/room.py#L804-L806

Somewhere in that method we need to call the appropriate method in https://github.com/matrix-org/synapse/blob/0a00b7ff14890987f09112a2ae696c61001e6cf1/synapse/handlers/account_data.py

We'll also want to make sure we add a test for this. (Probably a sytest?)

**Comment by turt2live** [comment]
This is an invalid issue: the spec says no such words, and 2018 Travis probably confused `is_direct` and `m.direct`.
