### ISSUE TITLE
[tip] Easy Database Manager

### ISSUE THREAD

**Issue by devcline** [matrix-org/synapse#4178]
I tested to edit database with some windows editors, but when i save it its corrupted.
in there any online script to manage my database? is it possible or not ?
Maybe i should move to PostgreSQL to easy manage?

thanks

**Comment by richvdh** [comment]
This isn't the right place to ask this question (try `#synapse:matrix.org` for help with administrating synapse), but you should use the `psql` shell. If you aren't comfortable using that, then you probably shouldn't be poking in the database (and we don't really recommend it anyway).
