### ISSUE TITLE
[security] Exposed rooms list

### ISSUE THREAD

**Issue by devcline** [matrix-org/synapse#4186]
When guests and registrations on server are closed
the server is exposed to a https://matrix.org/_matrix/client/r0/publicRooms to show the full list of rooms, with ids , descriptions, avatar and any one also can add a server to their rooms directory config with out any notice.

when is room is set to:
- Publish this room to the public in domain.com room directory?
- Anyone who knows the room's link, apart from guests and Anyone who knows the room's link, including guests
- option is set to not list on matrix servers
- even of option is set "Anyone who knows the room's link, apart from guests"

so anyone can see a "room_id" and generate a link https://matrix.to/#/!XXXXXXXX:domain.com

* it can serve to crawl a private information and a bots attacks
* i was able to join a room with out a registration when the room is set to "Anyone who knows the room's link, apart from guests"
* Removing option "Publish this room to the public in domain.com room directory?" The room is still visible in a community category.
* what option "Block users on other matrix homeservers from joining this room" really for?

The thing that disturbs me its possibility to view rooms when the SERVER is PRIVATE. Really private. I still want to join another public networks, but keep mine private (rooms , not private messages) I want to be able publish room in my rooms directory but not to the world.  For example every person can view all the rooms from the web or rooms list. How to disable this? I think there is something to think about...
thanks

**Comment by richvdh** [comment]
sounds like a dup of #1467/#2419
