### ISSUE TITLE
Lazy loading: the CS API should provide heroes if room name is ""

### ISSUE THREAD

**Issue by manuroe** [matrix-org/synapse#4194]
### Description
Riot clients remove an existing display name by setting an empty string (`""`).
If that happens on live, matrix clients will be likely to compute a display name like "Bob and 3 others" as specced by the room summary.
But if a matrix client does an initial sync, it will give an "Empty room" name to the room because it receives no heroes.

### Steps to reproduce

On a Riot client:
- create a room with people in there
- set a room display name
- remove it
- Do an initial /sync by clearing the cache.

-> The room will be named "Empty room" instead of  "Bob and 3 others" or stg.

**Comment by Half-Shot** [comment]
I kinda wish matrix client's set the name state to either empty content or nulled the name rather than an empty string as it's probably a valid thing in itself to have your room title be empty. However, it's probably not worth trying to change that behaviour now...

**Comment by richvdh** [comment]
I don't think it's practical to fix this without a spec which defines how it is supposed to work, cf #1868.

**Comment by turt2live** [comment]
My interpretation of [MSC688](https://github.com/matrix-org/matrix-doc/issues/688) is that `m.heroes` should include left members only if there are no other joined members - writing spec to say that.

**Comment by babolivier** [comment]
Fixed in #5089
