### ISSUE TITLE
Support HTTPS_PROXY env var for outbound proxy config

### ISSUE THREAD

**Issue by Gribou** [matrix-org/synapse#4198]
### Description

When using homeserver behind a corporate proxy, synapse python don't use proxy global variable.
So when put request to matrix.org are send there's a timeout connection.

*****

INFO - httppush.process-16 - Error sending request to  POST https://matrix.org/_matrix/push/v1/notify: TimeoutError 
2018-11-18 09:26:55,016 - synapse.push.httppusher - 339 - WARNING - httppush.process-16 - Failed to push event $15424483970iGDrt:synapse.mycompagny.fr to @john.doe:synapse.mycompagny.fr/im.vector.app.ios.voip.prod/aQ/0cQk1HFOF2GkU/8Z9k66ZgImmNU4gVFU431tYsLc=
Traceback (most recent call last):
  File "/root/.synapse/lib/python2.7/site-packages/synapse/push/httppusher.py", line 335, in dispatch_push
    resp = yield self.http_client.post_json_get_json(self.url, notification_dict)
TimeoutError: User timeout caused connection failure.

.

*****

**Comment by richvdh** [comment]
>  proxy global variable.

what proxy global variable?

**Comment by Gribou** [comment]
it's the unix global variable htpps_proxy use by the system.

**Comment by Gribou** [comment]
Thx

**Comment by Gribou** [comment]
May be the best way is to use httplib2shim, but i don't know how to do that.

**Comment by agentpurple** [comment]
same issue here. I installed a test server on a vm where I don't have a public IP so I used squid to proxy synapse.
everything works fine exept the push notifications. The log shows exactly the mentioned entry

**Comment by michaelkaye** [comment]
Notes for anyone implementing this: While twisted provides /some/ proxy support as part of `ProxyAgent`, that does not support HTTP CONNECT based proxies, which is the normal method required for connecting to https endpoints

**Comment by richvdh** [comment]
fixed by #6239

**Comment by clokep** [comment]
@abliss Probably worth filing a new issue (if there isn't one already).
