### ISSUE TITLE
creating a room whilst inviting yourself fails with a very ambiguous error (in riot/web at least)

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#4203]

**Comment by richvdh** [comment]
the response from synapse is a 403 with `{"errcode":"M_FORBIDDEN","error":"@richvdh:sw1v.org is already in the room."}`, so this seems to be a client problem.

**Comment by turt2live** [comment]
This is probably https://github.com/vector-im/riot-web/issues/4062 or https://github.com/vector-im/riot-web/issues/7242
