### ISSUE TITLE
Split up README into multiple docs or wiki pages

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#4246]
The README is getting pretty long and should probably be split into either multiple files or GitHub wiki pages.

**Comment by aaronraimist** [comment]
![screen shot 2018-12-03 at 10 41 15 am](https://user-images.githubusercontent.com/5855073/49387638-f69a8480-f6e7-11e8-8eb5-27c77192f987.png)

I made a mockup of what splitting it up into several wiki pages [might look like](https://github.com/aaronraimist/synapse/wiki/Setting-up-a-Synapse-Server) (links are broken) but I'm not sure if that's the right path or if something like https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/README.md is better

Thoughts?

When someone has cloned the repo they don't get the wiki and there isn't great support for relative links as far as I can see. So maybe separate files inside of `docs` is better.

**Comment by richvdh** [comment]
Much of the stuff that was there is now either in UPDATE.md and INSTALL.md, but it's still pretty long.

Generally I think separate files under `docs` would lead to a more coherent set of docs than the wiki.

**Comment by aaronraimist** [comment]
Seems to be in the process of being fixed by https://github.com/matrix-org/synapse/pull/10086
