### ISSUE TITLE
No create event in auth events

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#4251]
In some cases I get this error.

Could this be a side effect of me purging a lot of old messages in that room with the purge API (with option to really delete)

**Comment by richvdh** [comment]
can we have the full stack trace and other relevant logs please

**Comment by rubo77** [comment]
This was a followup of our accidently deleting all entries in event_forward_extremities in 2017.

I fixed that room by manually calling this command: https://github.com/matrix-org/synapse/issues/2012#issuecomment-286786732
