### ISSUE TITLE
matrix flooding with dns srv queries

### ISSUE THREAD

**Issue by MparkG** [matrix-org/synapse#4256]
in matrix log
`2018-12-03 22:04:40,859 - synapse.http.matrixfederationclient - 320 - INFO - federation_transaction_transmission_loop-489- {PUT-O-337} [sheen.host] Sending request: PUT matrix://sheen.host/_matrix/federation/v1/send/SOMENUMBER/`

dns queries log (dnsmasq)
`Dec  3 22:04:57 mgp dnsmasq[52608]: query[SRV] _matrix._tcp.sheen.host from 127.0.0.1
Dec  3 22:04:57 mgp dnsmasq[52608]: forwarded _matrix._tcp.sheen.host to 194.150.168.168`

To me there is nothing wrong with these actions,
however i find the sheer number of queries to lock down my dnsmasq service with this error:
`dnsmasq: Maximum number of concurrent DNS queries reached (max: 150)`

I have set this limit to 300 and it seems to work for now.
Maybe it is desirable to slow down the frequency of queries for a less aggressive style.
(Such that it not becomes necessary to increase default limits.)

**Comment by SimmyD** [comment]
Also get this with Docker

dockerd: time="2018-12-05T08:57:51.707738308+11:00" level=error msg="[resolver] more than 100 concurrent queries from 172.25.0.3:50287"

docker is raising the limit to 1024 in the next release though

**Comment by richvdh** [comment]
Synapse can connect to hundreds of servers at once. Each connection requires several dns lookups. There is some caching but it can still result in a lot of lookups in a short space of time. Essentially, this is expected behaviour.
