### ISSUE TITLE
Use Postgres by default

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#4270]
In preparation for #2917, the Debian package and other default ways of installing Synapse should start using Postgres by default

**Comment by richvdh** [comment]
I'm not convinced that this is a thing that needs to happen in preparation for #2917.

One of the problems with it is that it means that, even to try out synapse, you first have to go and set up a postgres database. Something like #2317, where you are given the option of which db to use (and we can provide appropriate warnings about sqlite), might be better.

**Comment by aaronraimist** [comment]
I'll go ahead and close this in favor of #2317 assuming there will be sufficient information provided about the benefits of Postgres at the time the user makes the decision.
