### ISSUE TITLE
Support MSC 1467 - Soft logout

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4280]
[MSC 1467](https://github.com/matrix-org/matrix-doc/pull/1467) has just been merged, which allows servers to specify how clients should handle 401's with regards to keeping or deleting encryption keys. 

Synapse should implement a mechanism for soft logging out devices or users via the admin API. We may also want to consider what other circumstances we should use soft logout, e.g. unrecognised access tokens, deleting devices, etc

**Comment by richvdh** [comment]
#5660 adds a lifetime to access tokens, after which requests will return a soft_logout 401.

**Comment by richvdh** [comment]
Possibly we need an administrative way of triggering an expiry, but that can be done by poking things into the database, so I'm declaring that to be a separate feature, and calling this fixed by #5660.
