### ISSUE TITLE
Migration to yunohost 3.x broke my synapse server

### ISSUE THREAD

**Issue by stemy2** [matrix-org/synapse#4287]
### Description

My synapse server worked fine on yunohost 2.7, but the migration to yunohost 3.x broke it, and now, it sends me only HTTP 500 errors.

### Steps to reproduce

- Install synapse on yunohost
- Migrate to yunohost 3.x

Describe how what happens differs from what you expected.

For the log, see the file i attached.

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver? On my own homeserver

If not matrix.org:
- **Version**:        What version of Synapse is running? 0.33.8 
- **Install method**: package manager     
- **Platform**:       Yunohost 3.3.3 on Olinuxine LIME 1

**Comment by aaronraimist** [comment]
Doesn't look like you attached any logs. I assume this is something you should bring up https://github.com/YunoHost-Apps/synapse_ynh or in #yunohost:matrix.org

**Comment by stemy2** [comment]
Sorry, i forgot the log, you can find it [here](https://stemy.me/jirafeau/f.php?h=3Tnjs5gb&d=1).

**Comment by richvdh** [comment]
```
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
```

synapse can't talk to your postgres.

**Comment by stemy2** [comment]
So what have i to do ?

**Comment by richvdh** [comment]
fix your postgres, I guess. Sorry, that's not a question we can help you with. Perhaps the yunohost people can help.
