### ISSUE TITLE
m.joined_member_count does not reflect the number of members

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/synapse#4300]
### Description

`m.joined_member_count`, as returned in the room summary, is not equal to the number of joined members, as returned from `/members?membership=join` or `/sync` without lazy-loading. I observe this in `#test:matrix.org` (1310 vs. 1309, respectively) and `#uri-scheme-proposal:matrix.org` (22 vs. 23, respectively). The server is matrix.org; Riot and Quaternion were used to look at the "actual" number of users; `m.joined_member_count` has been retrieved by debugging libQMatrixClient code. Wonder if it's related to #1294 by chance.

**Comment by richvdh** [comment]
dup of #1294 I think.
