### ISSUE TITLE
Share big file within federation

### ISSUE THREAD

**Issue by Thatoo** [matrix-org/synapse#4302]
### Description

I installed synapse without any difficulty thanks to Yunohost (you can find my issue on the yunohost fork of synapse [there](https://github.com/YunoHost-Apps/synapse_ynh/issues/91)) and it works almost perfectly well.
We can chat, voice/video call between members of our server and with members of matrix federation.
I changed max_upload_size: "10M" to max_upload_size: "100M" in
#nano /etc/matrix-synapse/homeserver.yaml
Since that, we can exchange big file up to 100M between members of our server (YES!) and we can also receive big files from members of Federation (YES!).
However, if one of the member of our server wants to send a big file (up to 100M), members of federation can't receive it (I tried only with members of matrix.org).
They see the file, they can click on it but the downloading process stops (does it even start?, I'm not 100% sure but I think it does because I can see a jump in transfer traffic from my yunohost server).
They always got, after some second (10s), the following message {"errcode":"M_UNKNOWN","error":"timeout"}
What can I do to solve that problem?

### Steps to reproduce

I send a 8M file from my own server ID to my matrix.org id. My matrix.org ID can see the file in the room but if I click on it, the download seem to start but never get green and after about 10 seconds, this message display : {"errcode":"M_UNKNOWN","error":"timeout"}

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
Synapse version of my homeserver : 0.33.9

**Comment by richvdh** [comment]
dup #4301 really
