### ISSUE TITLE
Federation: Invalid room state when the user joins an empty remote room

### ISSUE THREAD

**Issue by giomfo** [matrix-org/synapse#4304]
### Description

The room state is invalid when an invited member joins a remote room left by the others member.
Note1: **the room has been created on another homeserver than the member's one**.
Note2: The e2e encryption is **disabled** in this room.

### Steps to reproduce

- Consider 2 users userA and userB, created on 2 different Homeservers.
- userA creates a room, history_visibility is shared (default value)
- userA invites userB
- userA sends some messages
- userA leaves the room
- userB joins by accepting the invite, the room state is invalid **NOK**
   - the room history is empty
   - the userA is displayed in the room members list

Note3: **This issue is not reproduced when userA and userB belong to the same homeserver.**. Indeed when the 2 users belong to the same HS, the join request failed (see  https://github.com/matrix-org/synapse/issues/1533).

**Comment by giomfo** [comment]
The data of the remote rooms are not correctly handled on my HS when I'm not present in the room...

This is a similar to https://github.com/matrix-org/synapse/issues/3515

**Comment by richvdh** [comment]
I think this is the same as #6958.
