### ISSUE TITLE
"Cannot find homeserver" using riot-web

### ISSUE THREAD

**Issue by r4dh4l** [matrix-org/synapse#4320]
This is maybe not a bug report but a support request. I noticed

> **IF YOU HAVE SUPPORT QUESTIONS ABOUT RUNNING OR CONFIGURING YOUR OWN HOME SERVER**: 
> You will likely get better support more quickly if you ask in ** #matrix:matrix.org ** ;)

and tried this but got

> Failed to join room
> ETIMEDOUT

trying to join `#matrix:matrix.org` my home server (as far as I know that is a common problem for very large rooms), that's why I ask for help here.

### Description

Recently I noticed that I can not use https://riot.im/app/ with my homeserver accounts. The Web-App reports

> Cannot find homeserver

Using my homeserver with Riot-Destop/iOS/Android **works** just fine and even riot.im/app/ worked fine in the past.

### Steps to reproduce

1. I open https://riot.im/app/ -> log in
2. I provide my MXID `@user:yuhu.ddns.net` and password
3. I provide my homeserver under "Custom server": `https://yuhu.ddns.net:8448`

Riot-Web reports "Cannot find homeserver". The same is the case when I try, for example, https://matrix.bau-ha.us/#/home so it seems not to be related to a certain riot-web server.

Because using riot-web servers with my homeserver was no problem in the past I wonder if there was a recent change not accepting homeservers anymore that use port `8448` for client connection? I know it is reommended to use a Reverse Proxy but for some setups it is very useful to use port `8448` (in my case: running a homeserver really *at home* with only one public IP address via dynamic DNS and providing a data cloud service as well that already uses port `443`).

### Version information

- **Homeserver**: 

If not matrix.org: See "Steps to reproduce".

- **Version**: Synapse/0.33.9

- **Install method**: pip

- **Platform**: 

```
r4dh4l@vm-synapse:~$ uname -a
Linux vm-synapse 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
r4dh4l@vm-synapse:~$ cat /etc/debian_version 
9.6
```

The VM has 2GB RAM and one CPU.

**Comment by richvdh** [comment]
looks like a riot-web problem to me. It might be worth trying https://riot.im/develop which has some changes to the relevant code. Otherwise, please open a bug in riot-web.
