### ISSUE TITLE
Different Captcha Providers than google

### ISSUE THREAD

**Issue by damnms** [matrix-org/synapse#4324]
**Description:**
I would like to know if there are any plans in implementing another Captcha Provider than google. As for GDPR, this violates a lot, so if it would be possible to install something like that local, it would be really nice!

I would love to have this already implemented in synapse without the need for external software, but it would also be very helpful to have some kind of API, so others can write captcha "servers" and let them talk to synapse.

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-doc/issues/1281
