### ISSUE TITLE
Ability to specify the retention period for user_ips table

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#4352]
We should surely default to 6M or something of user_ips retention, for GDPR compliance etc

**Comment by aaronraimist** [comment]
Related: #4321

**Comment by mweinelt** [comment]
Has this issue been tackled yet? The issue's relationship with GDPR should make the urgency of this issue quite clear, no?

**Comment by erikjohnston** [comment]
Fixed by #6098
