### ISSUE TITLE
Some fields are missing in events of /sync response

### ISSUE THREAD

**Issue by vberger** [matrix-org/synapse#4359]
### Description

Some state events sent in an initial /sync response from synapse are missing the `origin_server_ts` and `event_id`, while the spec lists them as required.

### Steps to reproduce

Attempting to parse the sync response using ruma-client fails because these fields are missing, see https://github.com/ruma/ruma-events/pull/20

### Version information

- **Homeserver**: my personal HS

If not matrix.org:

- **Version**: synapse version 0.34.0

- **Install method**: pip

- **Platform**: Gentoo/Linux in a python3 virtualenv

**Comment by richvdh** [comment]
Note that https://github.com/matrix-org/sytest/blob/develop/tests/31sync/04timeline.pl#L39 tests that `event_id` is present.

**Comment by vberger** [comment]
It specifically affects the `"invite"` rooms in the sync response, here is a json extract. We can see that the 3 first state events don't have these fields.

```json
"invite": {
   "!JnIqzGggEpbkjEPJvc:safaradeg.net":{
      "invite_state":{
         "events":[
            {
               "content":{
                  "join_rule":"invite"
               },
               "sender":"@levans:safaradeg.net",
               "state_key":"",
               "type":"m.room.join_rules"
            },
            {
               "content":{
                  "name":"TEST"
               },
               "sender":"@levans:safaradeg.net",
               "state_key":"",
               "type":"m.room.name"
            },
            {
               "content":{
                  "avatar_url":"mxc://safaradeg.net/TfUUoDkOWpbbIwuIpShznpNp",
                  "displayname":"Levans",
                  "membership":"join"
               },
               "sender":"@levans:safaradeg.net",
               "state_key":"@levans:safaradeg.net",
               "type":"m.room.member"
            },
            {
               "content":{
                  "avatar_url":null,
                  "displayname":null,
                  "membership":"invite"
               },
               "event_id":"$1546954279258alCXG:safaradeg.net",
               "membership":"invite",
               "origin_server_ts":1546954279291,
               "sender":"@levans:safaradeg.net",
               "state_key":"@tabsbot:safaradeg.net",
               "type":"m.room.member",
               "unsigned":{
                  "age":17030,
                  "prev_content":{
                     "membership":"leave"
                  },
                  "prev_sender":"@levans:safaradeg.net",
                  "replaces_state":"$1546954273257NfLye:safaradeg.net"
               }
            }
         ]
      }
   }
}
```

**Comment by richvdh** [comment]
https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-sync says:

> `invite_state`: ... These state events may only have the `sender`, `type`, `state_key` and `content` keys present.

**Comment by richvdh** [comment]
the spec does say "*may* only have", rather than "*will* only have", but yes I'm inclined to agree this is inconsistent and a bug which should be fixed.

**Comment by richvdh** [comment]
could you open a new bug which describes the problem succinctly?

**Comment by vberger** [comment]
Will do
