### ISSUE TITLE
support for MSC1711

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4366]
enforce proper cert checking, with support for a whitelist of domains/netmasks that are exempt, and support for a custom CA trust list.

Blocked on getting people to switch over for now, but we could make it optional.

**Comment by anoadragon453** [comment]
> and support for a custom CA trust list.

Is this going to be in addition to the system's certs or in replacement of? Because I could see people wanting both things.

**Comment by richvdh** [comment]
replacement, in the first instance, I think. You can always add all the system CAs back into the trust list if you want.

**Comment by anoadragon453** [comment]
Can this be closed now that https://github.com/matrix-org/synapse/pull/4967 has been merged?
