### ISSUE TITLE
event creator worker stopped responding for 7 minutes

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4375]
Creating this issue mostly so if it happens again, we can see if there is a pattern:

For 7.5 minutes starting at 18:38 UTC on 2019-01-10, one of the event creator workers on matrix.org was completely unresponsive, with 100% cpu usage and no log output.

A `POST /_matrix/client/r0/rooms/{room}/send/m.room.message/{txnId}` request claimed 446 seconds of CPU time. 

Other processes seemed unaffected.

**Comment by neilisfragile** [comment]
Marking p2, but it's p1000 if it never happens again, and p1 if it happens at all regularly
