### ISSUE TITLE
Security - Too Accurate Synapse Version in the User-Agent Header when fetching URL Previews

### ISSUE THREAD

**Issue by itay-grudev** [matrix-org/synapse#4376]
### Description

The URL Previews feature provides the following `User-Agent` header when fetching a web page:

```
User-Agent: Synapse/0.34.1.1
```

It's a small detail, but sending such accurate version information is a security risk as it informs the corresponding web server of potential security vulnerabilities the homeserver server has.

You should remove the version information or at the very least trim it to the major version only.

For example, look how discrete Firefox is:

```
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
```

**Comment by ptman** [comment]
Isn't there some API endpoint which also reports the home server version? Any way I believe the exact version can be found by doing a couple of requests against the API and looking at differences in results. Basically what Nmap does. But maybe this should be configurable. As in apache? Show none|full|major|minor? Or just letting one specify the agent string in the config?

**Comment by itay-grudev** [comment]
Is the version API required by the Matrix protocol?

**Comment by Half-Shot** [comment]
/matrix/_client/versions is required since it specifies what version of the API your server supports, as well as features. The User-Agent/Server field shouldn't be required.

**Comment by itay-grudev** [comment]
The User-Agent field should be trimmed no matter if any other version information is required in my opinion.

**Comment by gerg5c42g542g2c54g52c** [comment]
> Isn't there some API endpoint which also reports the home server version? Any way I believe the exact version can be found by doing a couple of requests against the API and looking at differences in results. Basically what Nmap does. But maybe this should be configurable. As in apache? Show none|full|major|minor? Or just letting one specify the agent string in the config?

It shouldn't be configurable, because that creates an even more unique User-Agent. It should be simply as generic as possible. Not sending a User-Agent is the best idea.

The fact that other things also leak unnecessary info is not a reason to ignore this issue, but a reason to fix this leak and also similar leaks in other places.

**Comment by richvdh** [comment]
#1859
