### ISSUE TITLE
Unexpected error code for invalid param on "/_matrix/client/r0/publicRooms" endpoint

### ISSUE THREAD

**Issue by poulad** [matrix-org/synapse#4381]
### Description

API returns the error code `M_UNKNOWN` instead of `M_INVALID_PARAM` for an invalid parameter in the request.

### Steps to reproduce

Call _listing public rooms_ endpoint with the invalid type of parameter: string instead of integer for the `limit`.

```sh
curl "https://matrix.org/_matrix/client/r0/publicRooms?limit=NOT_INTEGER"
```
#### Expected Result

```json
{
    "errcode": "M_INVALID_PARAM",
    "error": "Query parameter 'limit' must be an integer"
}
```

#### Actual Result

```json
{
    "errcode": "M_UNKNOWN",
    "error": "Query parameter b'limit' must be an integer"
}
```

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:  matrix.og

**Comment by aaronraimist** [comment]
This was fixed
