### ISSUE TITLE
make sure that the synapse docs are up-to-date about populating tls certificates

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4394]
as part of enforcing msc1711, it's likely that lots more people are going to have to play certbot games. Make sure that the docs about how to do it are right, including whether you have to restart synapse. (Better yet, make it so that you don't have to restart Synapse to pick up new certs.)

**Comment by turt2live** [comment]
A complete guide going into explicit detail about how synapse should be set up with a reverse proxy (for c2s or s2s or both) would be hugely appreciated too.

**Comment by richvdh** [comment]
I think we decided this was done. Better installation docs are a larger subject
