### ISSUE TITLE
docker image uses stale config

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4446]
we tend to forget to update the config in the docker image on updates. Can we generate it automatically instead?

related to #4315

**Comment by richvdh** [comment]
(it's a bit of a pita because the docker config has a bunch of templated stuff. Not entirely sure how best to go about this.)

**Comment by hawkowl** [comment]
Because of https://github.com/matrix-org/synapse/issues/5518 , the best way is to get rid of it altogether. :D
