### ISSUE TITLE
Maintain all releases of matrix debian packages

### ISSUE THREAD

**Issue by oliverjanik** [matrix-org/synapse#4454]
I've installed a version of Synapse on a server from here: https://matrix.org/packages/debian/

Few days have passed and that version is gone, replaced by a newer version...

Would it be possible to keep old packages around for consistency?

**Comment by neilisfragile** [comment]
The main reason not to do so is that with the project is still under rapid development and we often need admins to upgrade to the latest and greatest. 

So in many cases we would actively not want to publish old versions - and this happens frequently enough that it pretty much amounts to the same as the status quo.

**Comment by oliverjanik** [comment]
Which I understand, but in span of 2 days (between installation my on UAT and PROD) the package has changed and has gone from using python 2.7 to venv'ed python 3.5

I just want to be able to install a package that I have tested and confirmed is good. Not a new one which might have new bugs.

Thanks for not closing this immediately and considering the issue.

**Comment by richvdh** [comment]
the old .debs are still on  https://matrix.org/packages/debian/. I'm afraid I don't really understand what this is asking for.

**Comment by richvdh** [comment]
https://matrix.org/packages/debian/pool/main/m/matrix-synapse/: debs all the way back to 0.31

**Comment by oliverjanik** [comment]
Thanks @richvdh apt on ubuntu did not see those. Do you have a tip how to install ?

**Comment by richvdh** [comment]
try giving the url to `apt install` ? Or download it with `wget` and `dpkg -i` ? 

I'm afraid reprepro doesn't currently allow us to list the old versions automatically (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=570623)
