### ISSUE TITLE
Joins and inbound federated invites are not received on /sync

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#4533]

**Comment by ara4n** [comment]
doing an initial sync by flushing cache reveals them however.

**Comment by richvdh** [comment]
presumably related to #4422

**Comment by richvdh** [comment]
to be clear, I'm not actively investigating this until I get more reports of it

**Comment by ara4n** [comment]
@erikjohnston saw a variant of this twice with me this evening - one on jki.re and one on kde.modular.im.  In both instances we were trying to join an IRC portal room: the /join went through fairly rapidly (you could see the user join on the IRC side, and we traced the /join in the logs), and in both instances it looks like the room state never came down the /sync so Riot/Web never believed the room had been joined and sat there spinning.  The only solution was to flush cache.  Meanwhile, Riot/Android correctly saw the room as having been joined.

**Comment by richvdh** [comment]
> @erikjohnston saw a variant of this twice with me this evening - one on jki.re and one on kde.modular.im.

@erikjohnston denies having an account on kde.modular.im, so this is misleading at best...

**Comment by ara4n** [comment]
sorry.  I think @erikjohnston was trying to join ##c++ from jki.re, which failed.  He then *saw* me as `@matthew:kde.org` try to join, uh, somewhere on freenode and have it also fail - sorry, i've already forgotten the room.

But assuming jki.re still has logs for the ##c++ thing it should be recognisable?

**Comment by richvdh** [comment]
This is superficially similar to #4422; however the bug that we found there could only affect worker-mode synapses, and given that this has been seen (iirc) on monolith deployments, there is probably still another bug out there somewhere.

**Comment by richvdh** [comment]
I think I'm going to close this until we have more reports of it happening that we can investigate.
