### ISSUE TITLE
replication wedged after spike in event traffic

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4549]
we received a big spike of 10000 membership events; afterwards replication seemed to get itself into a loop of repeated 'could not keep up' disconnections.

**Comment by turt2live** [comment]
Related: https://github.com/matrix-org/synapse/issues/3495 ?
Related: https://github.com/matrix-org/synapse/issues/2738

**Comment by richvdh** [comment]
I don't think it was due to `send_join` requests, so #3495 is likely different. It could be related to #2738, though in our case the synapse master was pinned to 100% CPU so again it looked a bit different.

**Comment by richvdh** [comment]
![image](https://user-images.githubusercontent.com/1389908/52169709-d9f4ea00-2734-11e9-993e-aed537ed692e.png)

It's all going to replication-REPLICATE-caches

![image](https://user-images.githubusercontent.com/1389908/52169768-b0888e00-2735-11e9-9f9d-d73498c8c5c9.png)

I guess the problem is this big spike in cache invalidation commands

![image](https://user-images.githubusercontent.com/1389908/52169775-c72ee500-2735-11e9-9ecb-bb96dc4c9712.png)

It doesn't actually seem to be making much progess, though

**Comment by richvdh** [comment]
I'm going to assume that this is no longer useful, given replication has been rewritten.
