### ISSUE TITLE
ACME should support being given an alternate hostname

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4552]
For people who don't want to deal with certificate management and also don't have their synapse and webserver in the same place. 

ie: support .well-known delegation from 1708 and ACME.

**Comment by turt2live** [comment]
as a datapoint: I've ended up having to do my own certificate management on 4 homeservers so far. This might be down to all the environments being similar/done differently from what is expected, however the built-in acme stuff just hasn't been useful in my upgrade spree (so far).

**Comment by turt2live** [comment]
Specifically a config option under the acme section for which single server name to acquire a certificate for.

**Comment by richvdh** [comment]
oh, so you want to have:
 * a separate webserver on `example.com` which serves up a .well-known, which delegates to `synapse.example.com`
 * `synapse.example.com` points to the synapse server
 * synapse acquires a certificate for `synapse.example.com` despite having `server_name: example.com`.

Sounds plausible to me, and agreed it sounds useful.

**Comment by turt2live** [comment]
Yup, that. Nothing fancier than that.

**Comment by hawkowl** [comment]
@neilisfragile I think we should scope this for 1.0. Thoughts?

**Comment by babolivier** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/4652 (not sure why GitHub didn't automatically close this issue)

**Comment by jryans** [comment]
> (not sure why GitHub didn't automatically close this issue)

I think the PR has to merge to the default branch of the repo (`master` here) for GH to auto-close, which is not how a lot of our projects work (since new work goes to `develop` instead).
