### ISSUE TITLE
Documentation for what to do when upgrading to 0.99 to be 1.0 ready

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4561]
There's no issue for this yet, so here it is.

**Comment by richvdh** [comment]
neil is working on this in the form of a FAQ.

Also under this umbrella: the UPGRADE.rst notes heavily imply that a self-signed cert will not work on 0.99 and you'll have to replace it before upgrading. This is of course not the case!

**Comment by schildbach** [comment]
I'm willing to "beta test" any 0.34.x1 to 0.99.x upgrade documentation as soon as it's in a roughly complete form.

**Comment by richvdh** [comment]
I think we decided this was done
