### ISSUE TITLE
Make non-expert users be able to host synapse. Write documentation.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [matrix-org/synapse#4568]
Currently I wouldn't recommend anyone who doesn't have too much time and isn't knowledgeable about infosec and sysadmin to host their own Matrix server. The process isn't what it should be and there's no reason for it to be this way. Meanwhile Matrix aspires to have a well balanced ecosystem of smaller servers avoiding the common problem of federation. Something has to be done about this.

There should be a documentation that not only enables a person who's only experience is using Ubuntu to host a Matrix server, but also to secure it up, minimize the data stored on it to the necessary minimum, manage it for years for him/her and friends and understand what they are doing and how they should act if any issues arise.

Documentation:
It should include in depth information on how to set the server up, secure it up, manage it, back it up, restore it, transfer it to another machine/place, configure for various use cases, perform tasks people need, manage logs, proceed in case of security breach, check if all of the above was done properly. This should be minimalistic, well thought-through, self-contained and easy to understand.
If synapse is to continue requiring external projects to operate like reverse proxy, postgres, coturn it should include them in this documentation.
The documentation should be maintained along with the software and be ready when the new software version is released, otherwise it's not user-friendly.

Software:
The Matrix server should be designed in such a way that all of the above is maximally easy and minimalistic. There are many ways to solve these issues like careful design, maintaining multiple versions of the software (one for regular users, one for corporations and experts) or a management utility. The most important of which is design, it should take into account all of these and provide defaults that enable the user to set up a secure, no data retention and reliable server for them and their friends with minimum possible time spent working and learning.

**Comment by richvdh** [comment]
I'm afraid wall-of-text, aspirational bug reports like this aren't terribly helpful. All of your points are valid, but it's hardly new information - we are all very conscious that the installation experience is unsatisfactory. There is no realistic chance of us ever doing everything you want in this issue, so it's just going to get ignored and add to the noise, so I'm afraid I'm going to close it.

There are lots of open issues about documentation (see https://github.com/matrix-org/synapse/labels/docs). If there are *specific* changes that you'd like to see, feel free to open a new issue, or better yet, open a Pull Request.

**Comment by gerg5c42g542g2c54g52c** [comment]
I haven't found an issue dedicated to this. There's no place to discuss about this. There's only an issue about adding backup guidance and if you open it, you can see how useful it is - people shared ways to back it up, this is way more accessible than the same shared in a matrix room (and being forgotten) and can be used to actually write that documentation and test it in the wild.

I think this pretty specifically lists the things to be changed. I guess two first paragraphs could be removed though. Yes, this includes the 'Ideally' things too, but I don't see how this shouldn't be worked on if the project is aiming to not become another centralized decentralized one. This is hardly an installation UX only problem.

I could open separate issues, but there would be a lot of them and I think they would create more mess and get forgotten more easily. The point is to engage community designing this and not spend hours writing text that will be put in the trash. This can also be worked on in software and I'm pretty sure self-hosting doesn't have to be this hard. There was even an attempt to do this by ChatSecure, the person behind it doesn't receive any funding though, but I don't see why this shouldn't be done in the Matrix world, it sounds like an ideal candidate to make this happen.

> ChatSecure Server for Android. Quick to setup, easily provision new devices, secure by default (end-to-end and at-rest), and user friendly.. even for novices! This open source Android XMPP server app will be based on Prosody and will use Orbot’s .onion services to provide universal NAT traversal (even over cell networks).

What are the things that are unlikely to be done and why?

**Comment by richvdh** [comment]
see also https://github.com/matrix-org/matrix.org/issues/206
