### ISSUE TITLE
synctl stop/restart consistently doesn't stop the homeserver

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4574]
Github tells me this is related: https://github.com/matrix-org/synapse/issues/1577

Installed using pip on ubuntu, running 0.99rc4. `synctl stop` says it is stopping the homeserver, however the logs indicate that the server is still processing new requests with no indication of stopping. `synctl restart` has a similar problem in that it blocks for a long while until the server is manually stopped.

Appears to not matter if workers are being used or not: the master process will always hang. Process requires `kill -9`. 

Using python 3.

**Comment by richvdh** [comment]
I think this is a dup of https://github.com/matrix-org/synapse/issues/4331.
