### ISSUE TITLE
version confusion

### ISSUE THREAD

**Issue by PiotrIr** [matrix-org/synapse#4579]
Hi,
I've just upgrade Synapse version to 0.99 today but when I open link in browser:
https://matrix.abc.com/_matrix/client/versions
It shows me:
{"versions": ["r0.0.1", "r0.1.0", "r0.2.0", "r0.3.0"], "unstable_features": {"m.lazy_load_members": true}}

When I use command:
curl -kv https://matrix.abc.com/_matrix/client/versions 2>&1 | grep "Server:"
it shows me:
< Server: nginx/1.14.0 (Ubuntu)

But is look I'm on latest version as:

root@:/home/mxadmin# dpkg -s matrix-synapse-py3 | grep '^Version:'
Version: 0.99.0+bionic1

root@:/home/mxadmin# dpkg -s matrix-synapse | grep '^Version:'
dpkg-query: package 'matrix-synapse' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.

Could you advise how to check the version? Or I just didn't upgrade the matrix correctly?

I have Ubuntu 18.04 and using just repository.

**Comment by Cadair** [comment]
https://matrix.abc.com/_matrix/client/versions Shows the versions of the Client-Server API supported. To check the server version you want to check

[/_matrix/federation/v1/version](https://matrix.org/docs/spec/server_server/r0.1.0.html#get-matrix-federation-v1-version) but it will be on your federation port, so it might be https://matrix.abc.com:8448/_matrix/federation/v1/version depending on what port your federation listener is on.

**Comment by PiotrIr** [comment]
Hi Cadair,
Thank you for your reply, now it shows me 0.99.
I found the test which I was using on the document so I guess it needs to be updated:
https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/3220
