### ISSUE TITLE
Don't upgrade a room if there's already an ongoing upgrade

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#4583]
Basically I tried upgrading a room at a time my server had some lag. Not seeing any kind of feedback in Riot after a short amount of time, I ran `/upgraderoom` a second time, which caused two tombstone events to be sent to the same v1 room, referencing two separate v3 rooms. Additionally, the UI got confused which caused me to left the wrong room, so the upgraded room isn't joinable by anyone.

Before initiating a room upgrade, Synapse should check if there's already an upgrade ongoing for the same room, and return an error if there is.

**Comment by anoadragon453** [comment]
So we put a linearizer in place, which is great, but all it does is make one room upgrade happen after another, rather than preventing the second one from happening at all.

**Comment by anoadragon453** [comment]
Another problem seems to be that we can upgrade a room over and over again, even after it's already been upgraded?

**Comment by jryans** [comment]
> Another problem seems to be that we can upgrade a room over and over again, even after it's already been upgraded.

There seems to be some debate about whether that's a bug or a feature: https://github.com/matrix-org/matrix-doc/issues/1937.

**Comment by anoadragon453** [comment]
Ughhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by anoadragon453** [comment]
After [some discussion](https://matrix.to/#/!yZHTGeDKZUeKaqeTeU:matrix.org/$15586032933465Wqxvm:amorgan.xyz?via=matrix.org&via=amorgan.xyz&via=sw1v.org) we've decided to go with the following solutions to the following use cases:


* Someone upgrades a room and then wants to upgrade the same room again (possibly to fix a botched upgrade)

Allow them to.

* Person A and B upgrading a room at the exact same time

Let the first one received go through and send an error message to the second.

* Person A upgrading a room, thinking something broke, and upgrading the same room again before the first go has completed

Send the same response to the second.

Will update https://github.com/matrix-org/synapse/pull/5051 to reflect this.

**Comment by anoadragon453** [comment]
Closed in #5051
