### ISSUE TITLE
MSC1711_certificates_FAQ - Assuming reverse proxy runs on the same host as Synapse

### ISSUE THREAD

**Issue by mrdemc** [matrix-org/synapse#4588]
If I understand the FAQ correctly, the reverse proxy should connect to the unsecure synapse port to communicate over HTTP, which seems to assume the proxy is connecting locally to synapse. However, if the reverse proxy and the synapse instance are both running on different hosts it should communicate over HTTPS to make sure the communication is still secured. Otherwise the reverse proxy would be (theoretically) vulnerable for MITM and traffic between those hosts could be intercepted using packet sniffers.

I think the FAQ should be updated with the following:
 - Either the reverse proxy should be running on the same host as Synapse, or
 - The reverse proxy should connect to 8448 with a valid certificate for Synapse

**Comment by richvdh** [comment]
The FAQ isn't trying to be all things to all people. If you're intelligent enough to be running reverse-proxies and synapses on different servers, then you're intelligent enough to know not to send HTTP over the public internet. A VPN or a private network is just as valid a solution.

I think trying to put this in the FAQ would overcomplicate it, so I'm going to close this issue. Feel free to propose a PR with alternative wording if you think that you can improve it though.
