### ISSUE TITLE
How to disable recaptcha in registration.

### ISSUE THREAD

**Issue by matrixtempnew** [matrix-org/synapse#4605]
I want to disable the recaptcha while the user register with account. I already disable enable registration recaptcha value to false in homeserver.yml file

**Comment by aaronraimist** [comment]
If you didn't manually setup captcha by following https://github.com/matrix-org/synapse/blob/master/docs/CAPTCHA_SETUP.rst then captchas should be disabled

**Comment by richvdh** [comment]
please go to `#synapse:matrix.org` for support
