### ISSUE TITLE
ERROR - update_client_ips-742- Failed to insert client IP 

### ISSUE THREAD

**Issue by vsatmydynipnet** [matrix-org/synapse#4628]
Hi, running an small homeserver, which was updated to python 3.6 and migrated from sqlite to postgresql 9.5 on freebsd. looks like all runs fine, except this error message in the homeserver log:

synapse.storage.client_ips - 286 - ERROR - update_client_ips-742- Failed to insert client IP (('@matrixbot:ma .... ProgrammingError('there is no unique or exclusion constraint matching the ON CONFLICT specification\n',)

Any help is much appreciated because server is back online again and loosing stuff would be bad.

Thank you!

**Comment by erikjohnston** [comment]
That shouldn't happen, can you post the output of running `\d user_ips` in postgres please?

FTR, user_ips is used for information purposes, so its not the end of the world if it doesn't update for now, though obviously we should get it back up and running

**Comment by vsatmydynipnet** [comment]
Hi, thank you for your info. The \d follows:

You are now connected to database "synapse" as user "pgsql".
synapse=# \d user_ips
      Table "public.user_ips"
    Column    |  Type  | Modifiers 
--------------+--------+-----------
 user_id      | text   | not null
 access_token | text   | not null
 device_id    | text   | 
 ip           | text   | not null
 user_agent   | text   | not null
 last_seen    | bigint | not null
Indexes:
    "user_ips_user_ip" btree (user_id, access_token, ip)

**Comment by vsatmydynipnet** [comment]
Updated to 0.99.1.1 yesterday evening, problem still exists.

**Comment by Protected** [comment]
I am also experiencing this issue. Installed yesterday. Fresh install, non-migrated.

**Comment by fistons** [comment]
Same issue, with a migrated database from sqlite

**Comment by vsatmydynipnet** [comment]
Still experiencing this insert problem. Even its for view/history only it would be really cool if there would be a solution. running on 0.99.1.1 actually. thank you very much.

**Comment by vsatmydynipnet** [comment]
I just updated to 0.99.2. the error is still there.

**Comment by Sharparam** [comment]
Still happening for me as well on v0.99.2.

Output of `\d user_ips`:

```
      Table "public.user_ips"
    Column    |  Type  | Modifiers
--------------+--------+-----------
 user_id      | text   | not null
 access_token | text   | not null
 device_id    | text   |
 ip           | text   | not null
 user_agent   | text   | not null
 last_seen    | bigint | not null
Indexes:
    "user_ips_user_ip" btree (user_id, access_token, ip)
```

The problem seems to be in [the `_update_client_ips_batch_txn` method in `client_ips.py`](https://github.com/matrix-org/synapse/blob/master/synapse/storage/client_ips.py#L340-L367). It's calling [`_simple_upsert_txn`](https://github.com/matrix-org/synapse/blob/master/synapse/storage/_base.py#L637-L682) passing in `(user_id, access_token, ip)` as the "keyvalues".

The problem seems to be that there is no `UNIQUE` index or constraint defined on the table with these columns which means they cannot be used as key values, and the query then fails. At least that's what I can gather (no expert on PostgreSQL or Python).

**Comment by richvdh** [comment]
The correct schema for user_ips is:

```
synapse=# \d user_ips
      Table "public.user_ips"
    Column    |  Type  | Modifiers 
--------------+--------+-----------
 user_id      | text   | not null
 access_token | text   | not null
 device_id    | text   | 
 ip           | text   | not null
 user_agent   | text   | not null
 last_seen    | bigint | not null
Indexes:
    "user_ips_user_token_ip_unique_index" UNIQUE, btree (user_id, access_token, ip)
    "user_ips_device_id" btree (user_id, device_id, last_seen)
    "user_ips_last_seen" btree (user_id, last_seen)
    "user_ips_last_seen_only" btree (last_seen)
```

If you've migrated your database from sqlite, this problem is caused by #4877

**Comment by Sharparam** [comment]
@richvdh Ok, good to know. I've fixed it for `user_ips`, is there a way to fix it for anything else that has the wrong indices?

**Comment by richvdh** [comment]
@huguesdk has very helpfully posted some sql to fix this at https://github.com/matrix-org/synapse/issues/4877#issuecomment-480632068.

**Comment by vsatmydynipnet** [comment]
[Solved] thanks tho richvdh. server was affected by https://github.com/matrix-org/synapse/issues/4877, which only affected matrix.org after the rebuild. After https://github.com/matrix-org/synapse/issues/4877#issuecomment-480632068 all works fine again.

NOTE: Users already logged in all devices and got unable to decrypt must change the device id (settings) of at least one device to start device list syncing.

**Comment by vsatmydynipnet** [comment]
All fine now
