### ISSUE TITLE
problem with url_preview_enabled

### ISSUE THREAD

**Issue by Any0fPe0ple** [matrix-org/synapse#4653]
# Please ask for support in [**#matrix:matrix.org**](https://matrix.to/#/#matrix:matrix.org)
Hello! I have a problem with server configuration parameter url_preview_enabled
After changed   url_preview_enabled:true server can't start.
 syslog:
Feb 15 18:00:20 riot systemd[1]: Starting Synapse Matrix homeserver...
Feb 15 18:00:24 riot python[17623]: Traceback (most recent call last):
Feb 15 18:00:24 riot python[17623]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Feb 15 18:00:24 riot python[17623]:     "__main__", mod_spec)
Feb 15 18:00:24 riot python[17623]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Feb 15 18:00:24 riot python[17623]:     exec(code, run_globals)
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 576, in <module>
Feb 15 18:00:24 riot python[17623]:     main()
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 571, in main
Feb 15 18:00:24 riot python[17623]:     hs = setup(sys.argv[1:])
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 312, in setup
Feb 15 18:00:24 riot python[17623]:     config_options,
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 356, in load_or_generate_config
Feb 15 18:00:24 riot python[17623]:     generate_keys=generate_keys,
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 374, in read_config_files
Feb 15 18:00:24 riot python[17623]:     yaml_config = self.read_config_file(config_file)
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 140, in read_config_file
Feb 15 18:00:24 riot python[17623]:     return yaml.load(file_stream)
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
Feb 15 18:00:24 riot python[17623]:     return loader.get_single_data()
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
Feb 15 18:00:24 riot python[17623]:     node = self.get_single_node()
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
Feb 15 18:00:24 riot python[17623]:     document = self.compose_document()
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
Feb 15 18:00:24 riot python[17623]:     node = self.compose_node(None, None)
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
Feb 15 18:00:24 riot python[17623]:     node = self.compose_mapping_node(anchor)
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
Feb 15 18:00:24 riot python[17623]:     while not self.check_event(MappingEndEvent):
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
Feb 15 18:00:24 riot python[17623]:     self.current_event = self.state()
Feb 15 18:00:24 riot python[17623]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
Feb 15 18:00:24 riot python[17623]:     "expected <block end>, but found %r" % token.id, token.start_mark)
Feb 15 18:00:24 riot python[17623]: yaml.parser.ParserError: while parsing a block mapping
Feb 15 18:00:24 riot python[17623]:   in "/etc/matrix-synapse/homeserver.yaml", line 7, column 1
Feb 15 18:00:24 riot python[17623]: expected <block end>, but found '<block mapping start>'
Feb 15 18:00:24 riot python[17623]:   in "/etc/matrix-synapse/homeserver.yaml", line 290, column 2
Feb 15 18:00:24 riot systemd[1]: matrix-synapse.service: Control process exited, code=exited status=1
Feb 15 18:00:24 riot systemd[1]: Failed to start Synapse Matrix homeserver.
Feb 15 18:00:24 riot systemd[1]: matrix-synapse.service: Unit entered failed state.
Feb 15 18:00:24 riot systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Feb 15 18:00:28 riot systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Feb 15 18:00:28 riot systemd[1]: Stopped Synapse Matrix homeserver.
Feb 15 18:00:28 riot systemd[1]: Starting Synapse Matrix homeserver...
Feb 15 18:00:31 riot python[17631]: Traceback (most recent call last):
Feb 15 18:00:31 riot python[17631]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Feb 15 18:00:31 riot python[17631]:     "__main__", mod_spec)
Feb 15 18:00:31 riot python[17631]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Feb 15 18:00:31 riot python[17631]:     exec(code, run_globals)
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 576, in <module>
Feb 15 18:00:31 riot python[17631]:     main()
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 571, in main
Feb 15 18:00:31 riot python[17631]:     hs = setup(sys.argv[1:])
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 312, in setup
Feb 15 18:00:31 riot python[17631]:     config_options,
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 356, in load_or_generate_config
Feb 15 18:00:31 riot python[17631]:     generate_keys=generate_keys,
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 374, in read_config_files
Feb 15 18:00:31 riot python[17631]:     yaml_config = self.read_config_file(config_file)
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 140, in read_config_file
Feb 15 18:00:31 riot python[17631]:     return yaml.load(file_stream)
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
Feb 15 18:00:31 riot python[17631]:     return loader.get_single_data()
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/constructor.py", line 35, in get_single_data
Feb 15 18:00:31 riot python[17631]:     node = self.get_single_node()
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 36, in get_single_node
Feb 15 18:00:31 riot python[17631]:     document = self.compose_document()
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
Feb 15 18:00:31 riot python[17631]:     node = self.compose_node(None, None)
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
Feb 15 18:00:31 riot python[17631]:     node = self.compose_mapping_node(anchor)
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
Feb 15 18:00:31 riot python[17631]:     while not self.check_event(MappingEndEvent):
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
Feb 15 18:00:31 riot python[17631]:     self.current_event = self.state()
Feb 15 18:00:31 riot python[17631]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
Feb 15 18:00:31 riot python[17631]:     "expected <block end>, but found %r" % token.id, token.start_mark)
Feb 15 18:00:31 riot python[17631]: yaml.parser.ParserError: while parsing a block mapping
Feb 15 18:00:31 riot python[17631]:   in "/etc/matrix-synapse/homeserver.yaml", line 7, column 1
Feb 15 18:00:31 riot python[17631]: expected <block end>, but found '<block mapping start>'
Feb 15 18:00:31 riot python[17631]:   in "/etc/matrix-synapse/homeserver.yaml", line 290, column 2
Feb 15 18:00:31 riot systemd[1]: matrix-synapse.service: Control process exited, code=exited status=1
Feb 15 18:00:31 riot systemd[1]: Failed to start Synapse Matrix homeserver.
Feb 15 18:00:31 riot systemd[1]: matrix-synapse.service: Unit entered failed state.
Feb 15 18:00:31 riot systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Feb 15 18:00:35 riot systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Feb 15 18:00:35 riot systemd[1]: Stopped Synapse Matrix homeserver.
Feb 15 18:00:35 riot systemd[1]: Starting Synapse Matrix homeserver...
Feb 15 18:00:38 riot systemd[1]: Stopped Synapse Matrix homeserver.

Please help me! That I do wrong?

**Comment by turt2live** [comment]
That looks like an invalid YAML file for your homeserver.yaml - double check that you're using spaces, not tabs, and that all the indentation is correct.

**Comment by neilisfragile** [comment]
On the assumption Travis is correct, I am going to close this issue.

**Comment by Any0fPe0ple** [comment]
> 
> 
> That looks like an invalid YAML file for your homeserver.yaml - double check that you're using spaces, not tabs, and that all the indentation is correct.
Thank you!
