### ISSUE TITLE
Docker image treats '-e SYNAPSE_NO_TLS=0' the same as '-e SYNAPSE_NO_TLS=1'

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4663]
... which is kinda confusing

**Comment by prathik-kaliyambath** [comment]
hey,

Can i work on this issue?

**Comment by richvdh** [comment]
sure!

**Comment by neilisfragile** [comment]
@prathik-kaliyambath feel free to join us in #synapse-dev:matrix.org if you have any questions

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I'm taking a crack at it in https://github.com/matrix-org/synapse/pull/4987

**Comment by richvdh** [comment]
this got fixed in #5005
