### ISSUE TITLE
Error removing/deactivating account

### ISSUE THREAD

**Issue by vmario89** [matrix-org/synapse#4679]
Hi, i am running Matrix Synapse and everything seems to be working fine except deleting once created users. I am getting the following error.

I am running the following version on Ubuntu 16 system:
ii  matrix-synapse                     0.34.0.1-0matrix2                        all          transitional package
ii  matrix-synapse-py3                 0.99.1.1+xenial1                         amd64        Open federated Instant Messaging and VoIP server

The endpoint https://matrix.domain.tld/_matrix/identity/api/v1/ is available and returns an empty object as described in https://matrix.org/docs/spec/identity_service/latest.html#get-matrix-identity-api-v1

I am running mxisd Service to deal with own identity. But i had the problem described here **before** that already (using vector.im / matrix.org)

Anyone an idea on how to work around this? Regards and thanks, Mario

> 2019-02-19 14:09:25,513 - synapse.access.http.8008 - 233 - INFO - POST-442- 217.92.209.189 - 8008 - Received request: POST /_matrix/client/r0/account/deactivate
> 2019-02-19 14:09:25,514 - synapse.metrics - 374 - INFO - - Collecting gc 0
> 2019-02-19 14:09:25,833 - synapse.handlers.auth - 266 - INFO - POST-442- Auth completed with creds: {'m.login.password': '@testy:matrix.domain.tld'}. Client dict has keys: ['erase']
> 2019-02-19 14:09:25,840 - synapse.http.client - 265 - INFO - POST-442- Sending request POST https://matrix.domain.tld/_matrix/identity/api/v1/3pid/unbind
> 2019-02-19 14:09:25,933 - synapse.handlers.typing - 89 - INFO - - Checking for typing timeouts
> 2019-02-19 14:09:25,933 - synapse.handlers.presence - 350 - INFO - - Handling presence timeouts
> 2019-02-19 14:09:26,003 - synapse.http.client - 286 - INFO - POST-442- Received response to POST https://matrix.domain.tld/_matrix/identity/api/v1/3pid/unbind: 403
> 2019-02-19 14:09:26,004 - synapse.handlers.identity - 197 - ERROR - POST-442- Failed to unbind threepid on identity server: 403: b'Forbidden'
> 2019-02-19 14:09:26,005 - synapse.handlers.deactivate_account - 82 - ERROR - POST-442- Failed to remove threepid from ID server
> Traceback (most recent call last):
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/identity.py", line 189, in try_unbind_threepid
>     headers,
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
>     result = g.send(result)
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/client.py", line 381, in post_json_get_json
>     raise HttpResponseException(response.code, response.phrase, body)
> synapse.api.errors.HttpResponseException: 403: b'Forbidden'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/deactivate_account.py", line 76, in deactivate_account
>     'address': threepid['address'],
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
>   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/identity.py", line 198, in try_unbind_threepid
>     raise SynapseError(502, "Failed to contact identity server")
> synapse.api.errors.SynapseError: 502: Failed to contact identity server
> 2019-02-19 14:09:26,006 - synapse.http.server - 85 - INFO - POST-442- <XForwardedForRequest at 0x7f2d57dcc4e0 method='POST' uri='/_matrix/client/r0/account/deactivate' clientproto='HTTP/1.1' site=8008> SynapseError: 400 - Failed to remove threepid from ID server

**Comment by vmario89** [comment]
one addition: Error looks the same like in this issue: https://github.com/vector-im/riot-web/issues/7717

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/4540, I guess
