### ISSUE TITLE
"Unbans do not propagate to federated servers" workaround is broken

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4683]
Unbans currently don't work over federation (https://github.com/matrix-org/synapse/issues/1563), and the workaround for the case of the last user of a homeserver being banned no longer works.

Previously, if all your users were banned in a room you could invite (and join) a different user on the homeserver to the room so the server picks up the new room state, unsticking the ban for everyone else. In recent updates (last known working before 0.34, but not in 0.34) this workaround broke and instead the invited user gets "you have not been invited to this room" despite having a valid and known invite event.

Historically, here's what I found out about a room in a similar situation:
> t2bot.io was previously involved in a room, and was subsequently evicted. After some time has passed (lots of time), a re-invite was issued to a previously banned user. This failed because obviously it did. Inviting another t2bot.io user that wasn't ever banned in the room results in "You are not invited to this room"

> As far as I can tell, it's using the wrong auth events for the invite and therefore unable to find the membership event, failing the caller_is_invited check

> The auth events on the actual invite don't appear in debugging, and old events from when the server last participated in the room are being used instead.

> "It using the wrong events" being t2bot.io

The workaround was to use the manhole and run the following (disclaimer: use at your own risk):
```
hs.get_handlers().federation_handler.do_invite_join(['matrix.org'], '!stuck:example.org', '@travis:t2bot.io', {})
```

**Comment by aaronraimist** [comment]
This workaround seems to work again now

**Comment by turt2live** [comment]
\o/ I'm going to close this but we really should fix https://github.com/matrix-org/synapse/issues/1563 :(
