### ISSUE TITLE
joining a federated room yields blank events for past history if past history is not visible

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#4686]
<img width="524" alt="screenshot 2019-02-20 at 01 22 44" src="https://user-images.githubusercontent.com/1294269/53059244-0be4ab00-34ae-11e9-95d3-c97fc06d7576.png">

The events have contents of {}, but moreover we shouldn't be seeing them in /sync at all :/

**Comment by turt2live** [comment]
Related/possible dup of https://github.com/matrix-org/synapse/issues/1943

**Comment by ara4n** [comment]
yeah, dup #1943
