### ISSUE TITLE
Can't remove local address `#chakralinux:matrix.org` on `#chakra:matrix.org` room

### ISSUE THREAD

**Issue by totte** [matrix-org/synapse#4693]
Despite having power 100 ("Admin"), if I try to remove the local address in Firefox it is removed from the list in the "Settings" menu - but there is no output in the room itself. Upon opening "Settings" again, the local address is still there. If I try it in Riot for Android, I get the error message/popup "You don't have permission to delete the alias." (and the local address isn't removed).

I tried at 2019-02-20T1134Z.

**Comment by richvdh** [comment]
correct, room admin does not give you rights to remove an entry from the server's directory.

**Comment by totte** [comment]
So the addresses/aliases are properties of the user who set them, and not the room or its administrators?

**Comment by t3chguy** [comment]
> So the addresses/aliases are properties of the user who set them, and not the room or its administrators?

Who can manage an alias is up to the server to which the alias belongs (the one named in the alias)
Typically this is the user that created it and/or administrators of that given matrix server (not room admins)
