### ISSUE TITLE
Synapse doesn't seem to transfer tags correctly on room upgrade

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#4703]
Using my backup account on matrix.org, I just joined the upgraded version of a room I was in and which had the "favourite" tag, and the upgraded room didn't get that tag.

**Comment by neilisfragile** [comment]
Ought to have been fixed by #4412
@babolivier Did the version of synapse you were running include this fix?

**Comment by babolivier** [comment]
I think so, since that was on matrix.org 5 days ago.

**Comment by anoadragon453** [comment]
Seems to work for me on my homeserver which is just running off latest stable Synapse.

**Comment by anoadragon453** [comment]
Reopen if still an issue :)

**Comment by anoadragon453** [comment]
Apparently still seeing reports of this from @babolivier

**Comment by babolivier** [comment]
Also @CromFr. I wonder if the age of the previous room could be a factor, since I can't repro it on new rooms but has seen it happen a few times on non-new ones?

**Comment by CromFr** [comment]
It may also be a Riot cache issue. I should have tried clearing the cache / restarting Riot before moving the room back to favourite.

I tried to reproduce this on another room but it kept the favourite tag.

**Comment by anoadragon453** [comment]
All notification settings are stored on the server so I don't believe it's a caching issue.

**Comment by babolivier** [comment]
ftr last week I've noticed two upgrades (v3 -> v5 and v1 -> v5) which lead to Synapse not adding the favourite tag for the new rooms.

**Comment by MTRNord** [comment]
Just happened for me in the riot web main room :(

**Comment by richvdh** [comment]
hopefully fixed by #6155
