### ISSUE TITLE
Downgrad "No key for ..."

### ISSUE THREAD

**Issue by jo-so** [matrix-org/synapse#4728]
I'm seeing multiple entries like this in my error log. This isn't an error, it's a notice or at most a warning, but it shouldn't be raised as an *error*, because it's no misbehaviour of synapse nor it's a misconfiguration an admin can do anything about it.

```
synapse.crypto.keyring: [PUT-530-$15509859171161666kUqAZ:matrix.org-$15509857281160656WPvkM:matrix.org-$15509856821160351NByTd:matrix.org] Got Exception when downloading keys for petunientopf.ch: SynapseError 401: No key for petunientopf.ch with id ['ed25519:a_DFAs']
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/crypto/keyring.py", line 658, in _handle_key_deferred
    _, key_id, verify_key = yield verify_request.deferred
synapse.api.errors.SynapseError: 401: No key for petunientopf.ch with id ['ed25519:a_DFAs']
```

### Version information

- **Version**: matrix-synapse-py3 0.99.1.1+stretch1
- **Install method**: Debian package from matrix.org
- **Platform**: amd64, Debian stable

**Comment by richvdh** [comment]
fixed by #5300
