### ISSUE TITLE
Lazy loading: LL members event already known from timeline is send in state 

### ISSUE THREAD

**Issue by ganfra** [matrix-org/synapse#4743]
With LL, I got some weird behavior where I receive member event from state field while I already know this room member from my initial sync.  

To replicate this behavior, 

On Client A - Create a room with 2 people (and make them join respectively)
On Client A - Send some messages
On Client A - Change member name
On Client A - Send a message again
On client B - Make an initial sync
On client A - Send again a message.

On client B we receive from the sync the last room member event already known from initial sync.

It does break some of our logic on client here to manage room state.

**Comment by ara4n** [comment]
duplicate #4237, i think
