### ISSUE TITLE
Registration fallback does not return device_id

### ISSUE THREAD

**Issue by manuroe** [matrix-org/synapse#4756]
which may prevent crypto from working on clients that register with this way.

The issue is at:
https://github.com/matrix-org/synapse/blob/74854a97191191b08101821753c2672efc2a65fd/synapse/static/client/register/js/register.js#L67-L69

The login fallback does not have this issue because it returns the raw CS API response:
https://github.com/matrix-org/synapse/blob/74854a97191191b08101821753c2672efc2a65fd/synapse/static/client/login/js/login.js#L16

**Comment by richvdh** [comment]
This is the least of registration fallback's problems (https://github.com/matrix-org/synapse/issues/7676)
