### ISSUE TITLE
[PATCH] Add env variable to enable URL previews in the generated

### ISSUE THREAD

**Issue by eMPee584** [matrix-org/synapse#4774]
```
From 2cb0189f535becad2a72d69f2998c09f8753a825 Mon Sep 17 00:00:00 2001
From: tii-admin <admin@tii.tu-dresden.de>
Date: Thu, 14 Feb 2019 14:39:01 +0100
Subject: [PATCH] Add env variable to enable URL previews in the generated
 homeserver.yaml

---
 docker/conf/homeserver.yaml | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/docker/conf/homeserver.yaml b/docker/conf/homeserver.yaml
index babd5bef9..f1ac226c9 100644
--- a/docker/conf/homeserver.yaml
+++ b/docker/conf/homeserver.yaml
@@ -112,7 +112,12 @@ thumbnail_sizes:
   height: 600
   method: scale

+{% if SYNAPSE_URL_PREVIEW_ENABLED %}
+url_preview_enabled: True
+{% else %}
 url_preview_enabled: False
+{% endif %}
+
 max_spider_size: "10M"

 ## Captcha ##
-- 
2.11.0
```

**Comment by anoadragon453** [comment]
Could you please submit this as a [Pull Request](https://github.com/matrix-org/synapse/pulls) instead?

**Comment by richvdh** [comment]
we have [previously](https://github.com/matrix-org/synapse/pull/4144#issuecomment-435866742) taken the position that adding hundreds of environment vars to the container setup wasn't scalable.

**Comment by eMPee584** [comment]
@anoadragon453 well the patch can be applied with `git apply`, is that really necessary as the change is very simple?

@richvdh relying on a custom homeserver.yaml would be much more acceptable if there was a way to keep up with any upstream changes of that file. Right now, one would have to rebuild the container with `SYNAPSE_CONFIG_PATH` unset, copy out the generated file, then manually merge it with the custom file. That also doesn't scale nicely.

**Comment by richvdh** [comment]
> @anoadragon453 well the patch can be applied with git apply, is that really necessary as the change is very simple?

Yes. We have a contribution process for a reason; please read CONTRIBUTING.rst and follow it.

> @richvdh relying on a custom homeserver.yaml would be much more acceptable if there was a way to keep up with any upstream changes of that file. Right now, one would have to rebuild the container with SYNAPSE_CONFIG_PATH unset, copy out the generated file, then manually merge it with the custom file. That also doesn't scale nicely.

I'm not sure I follow this; there is no need to change the file once you have one.

Having said that, I am tempted to make an exception for this one because it does seem simple and useful. Still, please open it as a PR.

**Comment by neilisfragile** [comment]
@eMPee584 thanks for the patch  - at the others say, we need you to submit via PR - not least because we need formal sign off from you to include it in the code base.

I'm going to close this ticket in the mean time.

**Comment by eMPee584** [comment]
Ok i will open a PR for the change.

> I'm not sure I follow this; there is no need to change the file once you have one.

Well that may be the state now, but it seems not implausible there will be changes coming at some point in time. Also the generated file does not exactly look beautiful with all the empty lines 😄
