### ISSUE TITLE
Application Service user cannot join rooms on other homeservers without account on origin homeserver

### ISSUE THREAD

**Issue by paulbdavis** [matrix-org/synapse#4778]
### Description

Trying to join a room as an application service's main user is inconsistent. After setting up the registration, but without explicitly creating the main user for the service, the main user for the application service can only join rooms on another home server if another user from that home server is present.

### Steps to reproduce

- Register new application service that attempts to join any room it is invited to. Do not explicitly register the matrix ID for the main application service user
- Create a room on another homeserver and invite the application service main user. This fails with a 404 error `{ "errcode": "M_NOT_FOUND", "error": "Profile was not found" }`
- Disinvite the application service user and invite another user belonging to the same homeserver as the application service
- Re-invite the application service user. The application service user should be able to join (polling may be required as the invite itself may not have synced)
- Explicitly create user for the application service's main user
- Create new room on another homeserver and invite the application service user, it should now be able to join properly

I am not sure if this behavior is intentional, but if so it should be documented in the guide for setting up application services. If not it should be consistent one way or the other.

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org and my personal homeserver

<!-- 
What version of Synapse is running? 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.99.1.1

- **Install method**: https://github.com/spantaleev/matrix-docker-ansible-deploy with manually managed nginx-proxy and certificates
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 18.04 on DigitalOcean
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by MadLittleMods** [comment]
There doesn't seem to be a good workaround for this.

I am running into this in [some tests](https://github.com/matrix-org/matrix-public-archive/pull/31#discussion_r909897666). When trying to explicitly register the application service `sender_localpart`, I get `400 Bad Request: {"errcode":"M_EXCLUSIVE","error":"This user ID is reserved by an application service."}` and I can't easily remove the application service registration file, register the AS user, put the AS registration back, restart Synapse, every time I start up the tests.

**Comment by MadLittleMods** [comment]
Ahh, thinking harder, you can set the profile of the application service user via `PUT /_matrix/client/v3/profile/{userId}/displayname` and `PUT /_matrix/client/v3/profile/{userId}/avatar_url` to get around this.
