### ISSUE TITLE
Cannot remove 3PID in profile while using custom ID server

### ISSUE THREAD

**Issue by tx1683** [matrix-org/synapse#4782]
### Description

I working on having fully self-hosted environment, so after setting up Synapse, I also set up ID server (mxisd) and pointed my client (Riot) to both of them. When I added 3PID in my profile, I was unable to remove it. I worked around the issue by setting ID server to default vector.im, and then removing 3PID. With default ID server it worked as intended.

Current ID system implementation in Synapse is preventing normal usage (adding and then removing) of 3PIDs with custom ID servers. It is forcing user to use centralized services or not use 3PIDs at all.

Possibly related:
https://github.com/matrix-org/synapse/issues/4540
https://github.com/matrix-org/matrix-doc/issues/1194      

### Steps to reproduce

- Run client with custom ID server
- Add 3PID in your profile
- Try to remove it

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Self-hosted

<!-- 
What version of Synapse is running? 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.99.2-py3

- **Install method**: Package from Matrix.org repo
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian Stable x86-64
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
I think this has probably been resolved. If not, please explain new repro steps.
