### ISSUE TITLE
Document shutdown room API

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#4784]
Unless I'm missing something there is no admin api documentation for the shutdown room API https://github.com/matrix-org/synapse/pull/2291

```
curl -XPOST -d '{ "new_room_user_id":"@roomshutdown:raim.ist" }' "https://matrix.raim.ist/_matrix/client/r0/admin/shutdown_room/!room:raim.ist?access_token=
```

This should probably be a separate issue but it seems the user is just auto joined to the new room, they don't get it as an invite or anything so they may not even notice the new room.

Related: #5575

**Comment by awesome-manuel** [comment]
@richvdh can be closed?
