### ISSUE TITLE
Trying to create a room with an existing name and no alias generates an Internal Server Error

### ISSUE THREAD

**Issue by gergelypolonkai** [matrix-org/synapse#479]
I sent:

```
{
    "name": "matrix-glib-sdk-test",
    "preset": "public",
    "topic":"GLib SDK test room"
}
```

I got:

```
{
    "errcode": "M_UNKNOWN",
    "error": "Internal server error"
}
```

If I add `"alias": "matrix-glib-sdk-test"` to the request, I get the correct "Room alias already taken" message.

I’m using the latest `pip install`able version as of date (0.12.0).

**Comment by turt2live** [comment]
I know it's 2 years late, and probably not all that helpful, but the issue is that `public` is not a valid preset. I think the preset you're looking for is `public_chat`.

On synapse 0.29 a KeyError is thrown for the `public` preset, but `public_chat` happily returns me a room ID.

**Comment by gergelypolonkai** [comment]
Sorry for not closing this earlier, i just forgot… Thanks @turt2live, it did work indeed!
