### ISSUE TITLE
let register_new_matrix_user parse correct homeserver url

### ISSUE THREAD

**Issue by f0x52** [matrix-org/synapse#4805]
**edited to reflect positional url argument**
### Description

register_new_matrix user only tries to connect on port 8448 by default. If you set `no_tls: True` in your homeserver.yaml, that won't work and crash fatally.

### Steps to reproduce
-`no_tls: True` in homeserver.yaml
- fill in new user data in `register_new_matrix_user`
- crash without registering
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8448): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8ba14210b8>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Instead, it would be nice to pick up the config setting and try over http port 8008

### Version information

- **Homeserver**: lain.haus

If not matrix.org:

- **Version**: Synapse/0.99.1.1

- **Install method**: pip

- **Platform**: Debian Sid

**Comment by f0x52** [comment]
ah, there's a positional argument for the url. Still would be nicer to get this from the homeserver.yaml

**Comment by richvdh** [comment]
we should probably just use localhost:8008 by default

**Comment by jwhitewick** [comment]
every time I try to create user I get this error message

Traceback (most recent call last):
  File "/opt/synapse/bin/register_new_matrix_user", line 22, in <module>
    main()
  File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 224, in main
    admin, args.user_type)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 138, in register_new_user
    bool(admin), user_type)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 47, in request_registration
    r = requests.get(url, verify=False)
  File "/opt/synapse/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/synapse/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/synapse/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/synapse/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/synapse/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8448): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6712602950>: Failed to establish a new connection: [Errno 111] Connection refused',))

can someone help me??

**Comment by mattssn** [comment]
> every time I try to create user I get this error message
> 
> Traceback (most recent call last):
> File "/opt/synapse/bin/register_new_matrix_user", line 22, in 
> main()
> File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 224, in main
> admin, args.user_type)
> File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 138, in register_new_user
> bool(admin), user_type)
> File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 47, in request_registration
> r = requests.get(url, verify=False)
> File "/opt/synapse/lib/python2.7/site-packages/requests/api.py", line 75, in get
> return request('get', url, params=params, **kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/api.py", line 60, in request
> return session.request(method=method, url=url, **kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
> r = adapter.send(request, **kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8448): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6712602950>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> can someone help me??

I can also confirm I am getting this same error.

**Comment by kingoftheconnors** [comment]
Same. What's going on?

**Comment by adan89lion** [comment]
> every time I try to create user I get this error message
> 
> Traceback (most recent call last):
> File "/opt/synapse/bin/register_new_matrix_user", line 22, in 
> main()
> File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 224, in main
> admin, args.user_type)
> File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 138, in register_new_user
> bool(admin), user_type)
> File "/opt/synapse/lib/python2.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 47, in request_registration
> r = requests.get(url, verify=False)
> File "/opt/synapse/lib/python2.7/site-packages/requests/api.py", line 75, in get
> return request('get', url, params=params, **kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/api.py", line 60, in request
> return session.request(method=method, url=url, **kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
> r = adapter.send(request, **kwargs)
> File "/opt/synapse/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8448): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6712602950>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> can someone help me??

confirm having this same issue. new setup in docker with Ubuntu 18.04.2 LTS. If you need more information I will follow up and provide them here

**Comment by richvdh** [comment]
please stop adding "me too" reports. It's a known bug. The workaround is to specify a valid url for your homeserver on the `register_new_matrix_user` commandline.

**Comment by markodes** [comment]
> please stop adding "me too" reports. It's a known bug. The workaround is to specify a valid url for your homeserver on the `register_new_matrix_user` commandline.

But how do you mean,  to specify a valid url for your homeserver on the `register_new_matrix_user` commandline?

**Comment by NoraCodes** [comment]
I am configured with my homeserver behind Nginx. I had success with:

```bash
sudo register_new_matrix_user -u NewUserName -p new_password -c /etc/matrix-synapse/homeserver.yaml -p https://localhost
```

**Comment by richvdh** [comment]
dup #3672
