### ISSUE TITLE
permission and ownership for file /etc/matrix-synapse/homeserver.yaml

### ISSUE THREAD

**Issue by pexus** [matrix-org/synapse#4806]
marks will be invisible in the report.

-->

### Description
The owner for file /etc/matrix-synapse/homeserver.yaml should be set to matrix-synapse and group and other read permission should be removed since this file contains password for bind and smtp

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 

If not matrix.org:

<!-- 
What version of Synapse is running? 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->

- **Platform**: 
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/4518
