### ISSUE TITLE
Error in deb package ::  matrix-synapse-py3::0.99.2+stretch1::amd64

### ISSUE THREAD

**Issue by tophers** [matrix-org/synapse#4819]
To note, this does not seem to cause an issue with an upgrade, but generates an error with the latest package.

```
Preconfiguring packages ...
/tmp/matrix-synapse-py3.config.BLTxSp: 8: /tmp/matrix-synapse-py3.config.BLTxSp: /opt/venvs/matrix-synapse/lib/manage_debconf.pl: not found
```

Which is odd, because the file does seem to exist after install:

```$ ls -la /opt/venvs/matrix-synapse/lib/manage_debconf.pl
-rwxr-xr-x 1 root root 3145 Mar  1 03:58 /opt/venvs/matrix-synapse/lib/manage_debconf.pl
```

Package info: matrix-synapse-py3::0.99.2+stretch1::amd64 

This does not seem to cause any issues on an upgrade, service started and is running without issue, may impact new installs.

**Comment by richvdh** [comment]
the warning is harmless. Agreed it shouldn't happen though.

**Comment by neilisfragile** [comment]
fixed
