### ISSUE TITLE
Issue with `synapse_config_path`

### ISSUE THREAD

**Issue by relink2013** [matrix-org/synapse#4822]
I'm not sure if there is an issue or if the process is just not well documented. But any time I set the environment variable ```SYNAPSE_CONFIG_PATH``` The container fails to start. I assume this is due to their not being a homeserver.yal file present, however you can't generate a config without the container running. 

If you manually create a config file then the container just throws a bunch of non descriptive errors and stops. 

If this is just user error can we get some clarification on how to properly set this up using a homeserver.yaml

**Comment by richvdh** [comment]
You don't mention it but I assume you're trying to use the docker image.

>  however you can't generate a config without the container running.

you can generate a config by running the docker image with a `generate` argument. For example:

```bash
docker run -it --rm --name synapse -v ~/tmp/data:/data \
    -e SYNAPSE_CONFIG_PATH=/data/homeserver.yaml \
    -e SYNAPSE_SERVER_NAME=my.matrix.host \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate 
```

This doesn't seem to be documented, sadly. A PR to fix https://github.com/matrix-org/synapse/blob/develop/docker/README.md would be much appreciated.

> If you manually create a config file then the container just throws a bunch of non descriptive errors and stops.

well, I suspect that the errors *are* descriptive, but your GUI is mangling them somehow.

**Comment by richvdh** [comment]
docs now updated to include the `generate` option
