### ISSUE TITLE
Missing device list updates

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4827]
We have a situation where: a user Bob on server A creates a bunch of devices, but server B ends up missing a device from the middle (i.e. it has synced older *and* newer devices). This shouldn't happen.

From the logs we see:

1. Server B only did one resync, before the missing device.
2. Server A and server B agree on the last device stream ID for Bob
3. There are no log lines of the form `Pruned %d device list outbound pokes`, suggesting that there were no problems sending the device list updates.

This suggests that B didn't receive or dropped the missing device, and then didn't realise it needed to do a resync.

**Comment by ara4n** [comment]
I wrote a test to try to exercise this at https://github.com/matrix-org/sytest/pull/761 but currently it passes...

**Comment by richvdh** [comment]
I think this is either fixed or a subset of #8631
