### ISSUE TITLE
user search is totally hosed

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4833]
search transactions take multiple minutes, taking out the whole db. Why do we need to store the cross-product of all users in all public rooms?

**Comment by hawkowl** [comment]
to avoid people having to read the code: the cross product is so that we know why users are in the user directory, so that when they leave a room we can find out if they're in any other rooms and purge them from the user directory if not

**Comment by richvdh** [comment]
fixed by #4846?

**Comment by richvdh** [comment]
apparently not. It's not returning any results.

**Comment by hawkowl** [comment]
Searching seems happy, now, due to https://github.com/matrix-org/synapse/pull/4900, https://github.com/matrix-org/synapse/pull/4887, and https://github.com/matrix-org/synapse/pull/4864
