### ISSUE TITLE
Make it visible to the user if a invitation to a room was revoked.

### ISSUE THREAD

**Issue by schiessle** [matrix-org/synapse#4836]
I just had this situation today. I got a invitation to a room. I tried to accept it, but it always timed out. So I contacted the person (who run their own matrix server, my account is in matrix.org) to let them know that something goes wrong. We found out that he invited me by accident and removed the invitation again. But there is no way for me to see that a invitation was revoked. From the recipient point of view it looks like I have a valid invitation and can't accept it for some random reason/bug. I would suggest to either notify the recipient if a invitation was revoked or just remove the invitation completely again to avoid confusions.

I can't even decline/reject it. So now I have the invitation in my list and have no idea how to get rid of it... I could only reject it after the sender send me another invitation.

**Comment by richvdh** [comment]
sounds like a dup of #4808
