### ISSUE TITLE
Move all admin endpoints out of the _matrix namespace and stop putting them there

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4850]
People keep thinking that the admin endpoints are unspecified parts of Matrix, and not a Synapse implementation specific feature. At the very least, move them to `/_matrix/synapse-admin` or something to clearly flag them as Synapse endpoints, not Matrix.

The documentation is not helping with this either: many of the docs say `/_matrix/client/r0/admin/...` which implies that it should exist in r0.x of the spec.

**Comment by richvdh** [comment]
+1

**Comment by erikjohnston** [comment]
I'd vote something like `/_synapse/v1/admin/..`

**Comment by richvdh** [comment]
fixed by #5119
