### ISSUE TITLE
federation_transaction_transmission_loop noisy

### ISSUE THREAD

**Issue by vmario89** [matrix-org/synapse#4876]
Hi, with matrix-synapse 0.99.2+xenial1 i am getting tons of the following messages like this in journalctl:

federation_transaction_transmission_loop-1241- {PUT-O-1135} [meinematrix.zapto.org] Request failed: PUT matrix://meinematrix.zapto.org/_matrix/federation/v1/send/1552916496419/: ConnectionRefusedError('Connection refused',)
federation_transaction_transmission_loop-1166- {PUT-O-1137} [matrix.zippynk.com] Request failed: PUT matrix://matrix.zippynk.com/_matrix/federation/v1/send/1552916496421/: TimeoutError('',)

i am not sure about if i hae to reconfigure to something to reduce this or is it normal behaviour? It's annoying because it makes hard to read the log lines for other issues

**Comment by richvdh** [comment]
normal behaviour.

**Comment by richvdh** [comment]
(you can always adjust your log levels if it is too noisy for you)
