### ISSUE TITLE
Support ACME DNS challenges

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4882]
For people who can't/won't do HTTP challenges.

**Comment by richvdh** [comment]
as in, have synapse run a dns server which you delegate your domain to? Sounds a bit out of scope. Shouldn't you just give up and use certbot/bind/etc at that point?

**Comment by hawkowl** [comment]
@richvdh no -- your ACME stuff will instead go talk to a DNS server (like route53) to set a TXT record, which is then used.

IMO, it's out of scope for built-in ACME support (and also a giant pain in the ass), and certbot supports it -- so maybe it's best to just point people there if DNS-01 fits their installation better.

**Comment by richvdh** [comment]
fair enough.

Anyway, can we agree this is out of scope and close it?

**Comment by clokep** [comment]
We removed support for the build-in ACME stuff, so going to close this.
