### ISSUE TITLE
edit existing message in room

### ISSUE THREAD

**Issue by progserega** [matrix-org/synapse#4884]
Add support to edit exist message for owner.

For example for monitoring systems bot:

1. Occur trouble in system X
2. Monitor software create ticket Y
3. Matrix bot send to matrix-room of tech-support message "ticket Y in system X is NEW state" with matrix-event-id Z
4. Any tech support engineer fix trouble in system X
5. Monitor software close ticket Y
6. Matrix bot modify message with matrix-event-id Z to "ticket Y in system X is CLOSE state"

Steps 3-6 may be occur many times (change NEW->OPEN, OPEN->PROCESS and e.t.c).
This feature (edit message) - can reduce many doubles of some messages with some text. 
This feature is in slack. It is very nice for corporate use.

**Comment by neilisfragile** [comment]
https://github.com/matrix-org/matrix-doc/pull/1695
https://github.com/matrix-org/matrix-doc/issues/441 are related

**Comment by richvdh** [comment]
also https://github.com/vector-im/riot-web/issues/1862

**Comment by richvdh** [comment]
this seems to have been basically implemented.
