### ISSUE TITLE
Transfer rooms on groups when the rooms are upgraded

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4897]
See https://github.com/vector-im/riot-web/issues/7994

This is a bit tricky from a backend perspective as the group server and the server which did the upgrade might not be the same, so the group server needs to watch for upgrades and move things around as needed.

**Comment by turt2live** [comment]
for context to whoever triages this: it is considered extremely high priority for Riot, although it's not something we should realistically be tracking in our backlog.

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6235
