### ISSUE TITLE
Don't federate my data

### ISSUE THREAD

**Issue by ataraxus** [matrix-org/synapse#4907]
I know this is probably not the right place to post this, but since I discovered this #2150 particular issue where I found out, that my data is exposed unauthorized and depending on the particular setting unencrypted to the internet. 

I dug deeper on when and how files and chats get federated and seems to be quite complicated. After seeing these #1918, #2820, #3173 and especially these #1466, #890. it seems to be a hassle to prevent files to be leaked to other servers. 

I lost confidence in that I want to manage this complexity to run a "private" server which can by mistake or default configuration distribute my data/files to random servers. 

It would be nice to have an easy to understand section in the docs and configuration on which data gets when federated and how to disable this. Also regarding #2150 I wonder how the french government sees this issue since it could easily leak data... all the amazon bucket leaks show that just a random file handle doesnt help anything. 

I hope this is just my lack of understanding and everything is fine for all the ones who depend on privacy and encryption. 

All the Best

**Comment by neilisfragile** [comment]
Hi @ataraxus this is definitely not a good place to talk generally how Matrix operates as a protocol. I'd recommend #matrix:matrix.org or #synapse:matrix.org for Synapse specific questions. 

Good intro guides can be found here https://matrix.org/docs/guides/ There are general introductions as well as more specific descriptions of our approach to e2ee.

To answer your specific question about how to prevent your server joining the federation you need to specify ```federation_domain_whitelist``` as an empty array (and firewall incoming requests).

https://github.com/matrix-org/synapse/blob/master/synapse/config/server.py#L333 has more info.
