### ISSUE TITLE
Question about Synapse longterm hdd requirements / content policy

### ISSUE THREAD

**Issue by vmario89** [matrix-org/synapse#4911]
Hi,
i am running a Matrix Server for 2 weeks now and i am going to monitor the daily usage of Megabytes today. I found this calculator (https://docs.google.com/spreadsheets/d/1clrE4WFT7A5NS5AJUdU-mbDZ9rS9fzl6QEbUFJezo7U/edit#gid=0) on the web but i think its really hard to have a good calculation for maybe 2 or 3 years in the future.

I wonder if there is some kind of content policy in synapse. I think it would be cool to have the possibility to say sth. like keep only last 4 weeks of image/video/audio content in a room. So the database / filesystem could be cleaned up to keep only latest attachments. Otherwise i could imagine that a well used Matrix server blows up to 500 GB and more over the time.

What are your experiences / thoughts about that? I was not able to find something fitting in the present documentation.

kind regards, Mario

**Comment by hawkowl** [comment]
We don't currently have any sort of automatic content policy rules in Synapse's built in media-repo (there are alternate implementations that use S3 to back, and that sort of thing, and may have this feature -- but I am not sure, off the top of my head).

One of our first steps is collecting statistics, we have https://github.com/matrix-org/synapse/issues/4337 to track that first part. We'd then likely build off the information exposed by that spec.
