### ISSUE TITLE
Events potentially sent immediately after join don't show up on remote servers

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4914]
A Telegram user joined a public room (!RistbroappQPsmzqnr:matrix.org) and immediately sent a message, however the message never arrived to matrix.org clients. The event appears to have made it to other servers.

The sequence of events is:
* Join: https://matrix.to/#/!RistbroappQPsmzqnr:matrix.org/$1553187330152264cKlPV:t2bot.io?via=matrix.org&via=t2bot.io&via=t2l.io
* Mystery message: https://matrix.to/#/!RistbroappQPsmzqnr:matrix.org/$1553187330152265oPgVN:t2bot.io?via=matrix.org&via=t2bot.io&via=t2l.io
* Message that alerted to the problem: https://matrix.to/#/!RistbroappQPsmzqnr:matrix.org/$1553187429152822fYuhn:t2bot.io?via=matrix.org&via=t2bot.io&via=t2l.io

t2bot.io's DAG appears to support this order of events, and the `prev_events` all reference the expected things. Joining with a server that has never been in the room, the events show up. Even when joining through matrix.org.

Synapse logs from t2bot.io do not reference any of the 3 events as being problematic. 

Not sure how feasible it is to diagnose this, but it sure is strange. This is reportedly not the first time it has happened and is at least the third time.

**Comment by Half-Shot** [comment]
>the message never arrived to matrix.org clients

The message made it to matrix.org, but not to the clients? Even after subsequent messages were posted? 

(I wonder if sync managed to skip over it due the join arriving in a odd order, and therefore it has been lost). Does the message show up if you try to find it via the share link?

**Comment by turt2live** [comment]
I can't actually tell if it made it into a transaction or not, but I would assume not. Permalinks, new users, etc all do *not* show the event.

**Comment by KitsuneRal** [comment]
I'm not sure if it's manifestation of the same bug or not but I see the similar behaviour between a Quotient test client and matrix.org, right now, without other servers being involved at all. In my case it's this client joining a room and immediately sending a few messages to it. Just before, it starts a sync loop at the same time; however it does not receive anything on the just-joined room through sync. Moreover, other clients logged in _under the same user_ don't receive any updates (including the fact of joining) either, while other users (even from the same server) in the room see the activity.

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/matrix-org/synapse/issues/10066 (https://github.com/matrix-org/synapse/issues/6536 was already closed in favor as well)
