### ISSUE TITLE
apt wants to remove matrix-synapse, flagged for autoremove

### ISSUE THREAD

**Issue by makedir** [matrix-org/synapse#4916]
I am using matrix-synapse since over a year now on an Ubuntu 18.04.2 LTS server. Always let it update via apt-get, had no issues so far. Today I noticed this output:

> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

> Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  formencode-i18n ieee-data liblcms2-2 libpq5 libwebpdemux2 libwebpmux3
  **matrix-synapse** python-attr python-automat python-bcrypt python-bs4
  python-canonicaljson python-certifi python-chardet python-click
  python-colorama python-constantly python-daemonize python-dateutil
  python-decorator python-defusedxml python-dnspython python-egenix-mxdatetime
  python-egenix-mxtools python-formencode python-frozendict python-funcsigs
  python-functools32 python-html5lib python-hyperlink python-incremental
  python-jsonschema python-lxml python-mako python-markupsafe python-memcache
  python-mock python-msgpack python-nacl python-netaddr python-olefile
  python-openid python-openssl python-pam python-paste python-pbr
  python-phonenumbers python-pil python-prometheus-client python-psutil
  python-psycopg2 python-pyasn1 python-pyasn1-modules python-pydenticon
  python-pymacaroons-pynacl python-pysaml2 python-requests python-scgi
  python-serial python-service-identity python-signedjson python-simplejson
  python-sortedcontainers python-tempita python-treq python-twisted
  python-twisted-bin python-twisted-core python-tz python-unpaddedbase64
  python-urllib3 python-webencodings python-yaml python-zope.interface xmlsec1
Verwenden Sie »apt autoremove«, um sie zu entfernen.

Why is matrix-synapse listed under the "not needed packages anymore" to remove via "apt autoremove"? Do I see it right, if I would use the "apt autoremove" it would literally ruin my matrix installation and remove it? Anyone could help me here what I should do with this. The server is running fine right now.

> apt list -a --installed matrix-synapse
Auflistung... Fertig
matrix-synapse/unbekannt,unbekannt,now 0.34.0.1-0matrix2 all [installiert,automatisch-entfernbar]
matrix-synapse/bionic,bionic 0.24.0+dfsg-1 all

I am a bit concerned about that output. Seems there was soemthing messed up, and two versions installed? And it wants to remove one of them the newer one? This doesnt look good to me.

/etc/apt/sources.list has this entry for matrix:

> deb https://matrix.org/packages/debian/ bionic main # Bei Aktualisierung zu bionic deaktiviert

**Comment by richvdh** [comment]
This seems to be a question about apt-get, not synapse.

> Die folgenden Pakete wurden automatisch installiert

This means that `matrix-synapse` was installed due to it being a dependency of another package. I can't tell you what that package was, or why it no longer depends on `matrix-synapse`.

You should also note that `matrix-synapse 0.34.0.1-0matrix2` is a transitional package which just depends on `matrix-synapse-py3`. As long as that package is correctly installed, you should be fine.

I also recommend using `apt` rather than `apt-get`.

None of this is a bug in synapse. Please see the issue templates: this is not the place to ask for support.
