### ISSUE TITLE
unable to Setup synapse on local network 

### ISSUE THREAD

**Issue by kavikumarN** [matrix-org/synapse#4918]
When i try to setup matrix synapse on local network by configuring server name as machine ipv4 address (static), it is possible only to get access only within the machine. when i try to access from  another machine in the network it gives an error such as  No response from server.

 ``
My system local ipv4 is 192.168.1.145. 
I have configured this ip  as  "SERVER NAME" while installing  synapse in  homeserver.yaml file. 
``

user a/c registration as follows:

 ``
register_new_matrix_user -c homeserver.yaml http://localhost:8008
``

if i put home server url as  http://localhost:8008 it works in the same machine, if i put 192.168.1.145:8008 from another machine's riot web UI it reflects no response  from server.

I failed to generate SSL certificates for bare IP address, since it works only for domain names. @

**Comment by richvdh** [comment]
see the issue template: this is not a good place to get support.
