### ISSUE TITLE
_matrix/client/r0/publicRooms returns empty list

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#4924]
### Description

On my test server I created two public rooms. They show up in the total_room_count_estimate, but the chunk is an empty array. 

```
$ http localhost:8008/_matrix/client/r0/publicRooms
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, must-revalidate
Content-Encoding: gzip
Content-Type: application/json
Date: Sat, 23 Mar 2019 20:38:18 GMT
Server: Synapse/0.99.2
Transfer-Encoding: chunked

{
    "chunk": [],
    "total_room_count_estimate": 2
}
```

Or see https://matrix.vaizard.xyz/_matrix/client/r0/publicRooms for yourself.

- **Version**:  0.99.2
- **Install method**: apt
- **Platform**: ubuntu 18.04, lxd container

**Comment by neilisfragile** [comment]
@killua-eu we will shortly be shipping a rewrite of how the room directory is populated, should land in the next week or so  - I would expect it to fix this.

https://github.com/matrix-org/synapse/issues/4043 is the tracking issue, but https://github.com/matrix-org/synapse/pull/4338 also related.

**Comment by killua-eu** [comment]
Hi @neilisfragile , just tested it against 0.99.3, still no joy. May I be missing something?

**Comment by reivilibre** [comment]
Are you sure you made it so at least the following are true:

* 'Publish this room to vaizard.xyz's room directory?' is **enabled**.
* Either (or both):
    * Room history is world-readable
    * Anyone can join

**Comment by richvdh** [comment]
Assuming this is either fixed or a config error.
