### ISSUE TITLE
Synapse doesn't send left members as heroes

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/synapse#4926]
As per https://github.com/matrix-org/matrix-doc/issues/688, step 6 implies that names of former members will be sent in `heroes`. This doesn't happen now (not at matrix.org at least), hitting especially hard in case of direct chats (I already have a few indistinguishable "Empty room"s in "People" due to that).

**Comment by neilisfragile** [comment]
https://github.com/matrix-org/synapse/pull/3898

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/5355
