### ISSUE TITLE
media-worker throws "Producer was not unregistered"

### ISSUE THREAD

**Issue by jo-so** [matrix-org/synapse#4933]
### Description

I've configured the media worker as explained in [workers.rst](https://github.com/matrix-org/synapse/blob/master/docs/workers.rst). Sometimes it sends these messages:

```
synapse.rest.media.v1._base: [GET-11] Failed to write to consumer: <class 'Exception'> Consumer asked us to stop producing
twisted: [GET-11] 
RuntimeError: Producer was not unregistered for b'/_matrix/media/v1/thumbnail/matrix.org/zkSkrqEdMEIiBsiGsTjcoaal?width=46&height=46&method=crop'
```

### Version information

- **Version**: 0.99.2+stretch1
- **Install method**: Debian package from marix.org
- **Platform**: Debian stable

**Comment by richvdh** [comment]
should be fixed by #5009
