### ISSUE TITLE
Logging in can cause CPU spike due to device lists

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4934]
@babolivier has this.

Basically, sending the log in request caused synapse to start sending tonnes of outbound device list updates to all the servers he shared a room with. This seems to have caused synapse to use 100% CPU and slowed down the processing of the `/login` request sufficiently for the client to time out, resulting in him not being able to log in.

**Comment by ara4n** [comment]
dup https://github.com/matrix-org/synapse/issues/7721.
