### ISSUE TITLE
Room directory doesn't de-publish tombstoned rooms

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4948]
The new room is published in the directory, but so is the old one. The old one should be pulled from the directory.

Additionally, if the room was published on a homeserver which did *not* perform the upgrade, the old room is left on the directory and the new one is *not* published when the user joins.

Expected behaviour:
* Upgrading a room which is published to your homeserver's directory publishes the new room (works)
* Joining an upgraded room where the old room was published should publish the new room (doesn't work).
* In both cases, the old room is removed from the directory on the servers (doesn't work x2)

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6232
