### ISSUE TITLE
Docker: Environment variable SYNAPSE_SERVER_NAME is mandatory, exiting although config file exists

### ISSUE THREAD

**Issue by simonszu** [matrix-org/synapse#4952]
### Description

Synapse is run via Docker. There is an existing homeserver.yaml file which is mounted into the container. The path is specified via `SYNAPSE_CONFIG_PATH`. 

Every time i change the homeserver.yaml and re-upload it via ansible and restart the container via ansible, i get an error: `Environment variable SYNAPSE_SERVER_NAME is mandatory`
It doesnt matter if i set `SYNAPSE_SERVER_NAME` explicitly via docker env, it has still the same error. Of course, the homeserver.yaml has a `server_name` setting.

Only solution is to delete the container and recreate it. 

### Steps to reproduce

- Install synapse via Docker, a homeserver.yaml file mounted in the Container, and `SYNAPSE_CONFIG_PATH` set. 
- When everything is running, upload a new homeserver.yaml file to the docker host
- Restart the container so that it picks up the new homeserver.yaml

### Version information

- **Homeserver**: matrix.simonszu.de

If not matrix.org:

- **Version**: 
Docker-Tag "latest".
 Image: https://hub.docker.com/r/matrixdotorg/synapse
 Image hash 8258b0d90727. 
Happens on other synapse images as well, e.g. the one from avhost. 

- **Install method**: Docker container, via ansible

- **Platform**: 
Debian Linux in an LXC container on a Debian Hypervisor. The VM has sufficient RAM and storage, and is connected via IPv4 and IPv6. 64bit.

**Comment by richvdh** [comment]
I can't really imagine why this would happen. Can you reproduce it when running docker manually, rather than via ansible?

**Comment by schrek1** [comment]
I have same trouble with Docker on Windows 10, after folowing command:
docker run -it --rm --mount type=volume,src=synapse-data,dst=/data -e SYNAPSE_SERVER_NAME=my.matrix.host -e SYNAPSE_REPORT_STATS=yes matrixdotorg/synapse:latest generate

**Comment by richvdh** [comment]
@schrek1 can you confirm that you are seeing the same error message as the original reporter? "`Environment variable SYNAPSE_SERVER_NAME is mandatory`"

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
@simonszu, if this is still a problem, I will try to reproduce.

**Comment by richvdh** [comment]
I'm assuming it's not a problem, since the reporters seem to have gone away. We can reopen if anyone has any useful information.
