### ISSUE TITLE
Does Synapse ever stop trying to send events to dead servers?

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#4979]
It doesn't seem like Synapse ever stops attempting to send messages to servers which are no longer online. Synapse should figure out that some servers are down and if they are continually down for multiple days then Synapse should stop attempting to send events to the server or back off exponentially. It seems like this could improve performance at least a bit and reduce the amount of logging for people on WARNING.

After #3765 it will be a bit easier to detect dead servers but for now Synapse needs to figure it out in its own.

**Comment by richvdh** [comment]
it does (or at least, is meant to) back off exponentially.

**Comment by aaronraimist** [comment]
I'm going to close this for now then. I haven't done a lot of studying to see if it does or doesn't. It just seems like it doesn't.

**Comment by aaronraimist** [comment]
Replaced by #5113, with data!

**Comment by derzahla** [comment]
Has anyone from the Synapse project provided _any_ guidance yet on this 3 year old issue?  I can't find it.  I manage a homeserver that  has been operating standalone for many months now but it still spans the logs trying to reach out the dozens of external homeservers.  

**How can I make this stop?** 

I have already tried the following:

- removed the federation listener from homeserver.yml
- set the federation whitelist to " "
- purged all old rooms that were left over from federation 
- manually cleared all rows in the "destinations" and "destination_room" database tables

What else needs to be done to STOP all federation activity and remove all record over previously federated servers???
