### ISSUE TITLE
API to allow user to delete a message for only himself.

### ISSUE THREAD

**Issue by hassanAwanAlvi** [matrix-org/synapse#4995]
Right now, I guess, the remove feature in Riot allows you to delete a message for everyone. I need to implement a system in which the system only deletes that text for himself, not for the other person. I don't know how to start implementing this. Need a little help to get started on this. Any help will be appreciated.

**Comment by SoftwareSheriff** [comment]
You could do this completely client side without any additions to the matrix spec. Granted, the "removal" will not persist across all clients unless do something more involved like storing "removed" events [server-side like this](https://matrix.org/docs/spec/client_server/r0.4.0.html#client-config) and not displaying events with IDs that match ones you've previously saved there.

**Comment by neilisfragile** [comment]
I'd see this either as something to implement in a client (I don't see the use case for Riot), or if you want this to work cross client you'd need to get it added to the spec and should raise in the https://github.com/matrix-org/matrix-doc repo. 

It sounds like you are at the beginning of thinking about this - you might find the #matrix-dev:matrix.org channel a good place to flesh out your ideas before going any further.

Closing as this idea is not ready to be a Synapse issue
