### ISSUE TITLE
Allow only admin users to create rooms

### ISSUE THREAD

**Issue by enannos** [matrix-org/synapse#5008]
Hi,

is there an option in the config file to allow only the admin users or some users to create Rooms and invite people?
The problem is that, by default, everyone can create rooms and invite everyone.
In a production environment, it should be possible to allow only specific users to create some new rooms.

Thanks

**Comment by jonesthesubmarine** [comment]
I would like to know this as well.

**Comment by neilisfragile** [comment]
You can manage this by modifying default user power levels - so set it up such that regular users cannot  create rooms and cannot invite others.

This is not a great place to get support, please use #synapse:matrix.org if you have further questions.

**Comment by enannos** [comment]
Hi and thanks for your answer. 

The question is, how to do this. 
We use matrix with a AD connection, the users are authenticated against the active directory schema. And there are some users that are in the internal matrix database that have admin rights. 

But I am unable to find a way to forbid the users from AD from creating rooms. 

I can't find a way to

**Comment by t3chguy** [comment]
Just remember preventing room creation will prevent people from having direct chats between each other as those are rooms also
