### ISSUE TITLE
Captcha Documentation should specify a V2 key

### ISSUE THREAD

**Issue by dkowis** [matrix-org/synapse#5013]
### Description

The documentation for how to set up a captcha needs to specify that a V2 key is required, and possibly the type of key (checkbox, android, background thing)

### Steps to reproduce

- Create a v3 captcha key
- New user registration fails horribly with a SITE ERROR in the captcha dialog
- If domain validation is on, SITE ERROR with invalid domain

You must pick a v2 captcha key (possibly with the checkbox, have only specified one with the checkbox setting). You must also turn off domain validation if you wish to use the riot.im web client. Not sure if you can leave it on using your own hosted riot-web.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: synapse.light.kow.is


<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.34.0.1-0matrix2

- **Install method**: package manager on ubuntu 18.04
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Xen Virtualization, ubuntu 18.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by aaronraimist** [comment]
#5283 fixed this (why didn't the auto close work?)

**Comment by richvdh** [comment]
no idea :/
