### ISSUE TITLE
Synapse triggers letsencrypt ratelimit if it has no write permission for the specified folder

### ISSUE THREAD

**Issue by C4ne** [matrix-org/synapse#5021]
### Description
If Synapse is configured to validate ACME requests but does not have write permissions to the directory the (cert) files should go into, it retries the ACME validation until it gets "ratelimit" errors from letsencrypt.

### Steps to reproduce

- Register a new domain
- Install matrix through the debian apt package repository
- Configure Matrix to use the new domain
- Configure Matrix to respond to ACME request throug nginx
- Configure nginx to forward ACME requests to synapse with an X-Forwarded-For header
- Set tls_certificate_path and tls_private_key_path to a folder which the matrix-synapse user can not write to
- Start synapse, wait a few seconds/minutes to run into the letsencrypt "Duplicate Certificate" limit, see: https://letsencrypt.org/docs/rate-limits/

I expect synapse to stop if it gets a valid certificate but can not save it. Or maybe save it to RAM and wait for wirte permissions instead of generating a new certificate all the time.

### Version information
On a selfhosted server

- **Version**: 
0.34.0.1-0matrix2

- **Install method**: 
official apt debian package resources

- **Platform**: 
Debian 9 on VMWare ESXI 6.7

**Comment by babolivier** [comment]
Closing as Synapse's ACME support has been deprecated and removed.
