### ISSUE TITLE
Synapse suddenly blows memory

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#5029]
Hi there, since the most recent release, my synapse is frequently doing a huge spike in memory usage until it hits the configured 80% limit, where it so far wents stuck.
After restarting, it behaves nicely for about 8-16 hours and then skyrockets in memory usage.
![d2d2d32d](https://user-images.githubusercontent.com/10698140/61560114-a9e39e00-aa6b-11e9-9dd1-e7c20be16eb8.JPG)
![d2d2wq](https://user-images.githubusercontent.com/10698140/61560115-a9e39e00-aa6b-11e9-9804-f2c5f63eb3ca.JPG)

For some reason it doesn't even get oomed.

So far i only used the info loglevel, not debug (sorry) and i cannot determinate any clear error happening before this happens. There is really nothing unusual going on in the info/error log.

I wonder if the spinning harddrives of this server are too slow because i think something similar happened when it ran on a vps (as far as i remember), vs this Kimsufi machine which was fine 'til very recently.
This sadly means that i have no idea how to reproduce, other than running a public synapse with many big rooms on a midrange Kimsufi machine on spinning harddrives (if this has by any chance anything to do with this issue - `Hitachi/HGST Ultrastar 7K4000 7200 rpm`). 

**(Maybe) Notable Settings:**
````
event_cache_size: "25K"
synctl_cache_factor: 0.5
use_presence: False
rc_messages_per_second: 0.2
rc_message_burst_count: 5.0
federation_rc_window_size: 1000
federation_rc_sleep_limit: 10
federation_rc_sleep_delay: 700
federation_rc_reject_limit: 30
federation_rc_concurrent: 2
````
Note: as of recently, these values were pretty much default, except maybe cache factor because i already tried tweaking those for fighting these server freezes before i realized that it keeps hitting the memory limit configured with systemd.

Workers are yet unconfigured.
I am on python3, and Debian 4.9* - i am using the manual installation method.

(Maybe) Notable Systemd file:
```
Restart=on-abort
Environment="SYNAPSE_CACHE_FACTOR=0.3"
LimitNOFILE=49152
WorkingDirectory=/home/synapse/.synapse
ExecStart=/home/synapse/.synapse/bin/python -m synapse.app.homeserver --config-path=/etc/synapse/homeserver.yaml
PIDFile=/run/synapse/synapse.pid
MemoryAccounting=true
MemoryHigh=4G
MemoryMax=80%
```

Would be amazing if we'd be able to fight this problem together.
Just realized - this might be related to #2166.

**Comment by neilisfragile** [comment]
Hi @verymilan @hawkowl is going to be doing some tuning for smaller homeserver instances over the coming weeks which _might_ help track down the RAM spike.

**Comment by verymilan** [comment]
Thanks - i'd like to add, i didn't yet automate the restart when this happens - this time i was a bit late and noticed that it was already falling - the memory usage of synapse was 57% and munin shows me that it was a good bit higher before - i didn't want to wait to see if synapse would become responsive again though as this is no single-user instance... .

**Comment by verymilan** [comment]
I just noticed that at least this time, i've got a number of `could not serialize access due to concurrent update` errors from `DELETE FROM presence_stream` statements in my postgres log... .

**Comment by richvdh** [comment]
Is this still a problem? The most likely cause of a sudden increase in memory usage is events arriving over federation in rooms with large state and complex event graphs, leading to a complex state-resolution.

**Comment by richvdh** [comment]
assuming this is resolved pending further info
