### ISSUE TITLE
INSTALL.md still describes certificate generation with the generation of homeserver.yaml

### ISSUE THREAD

**Issue by j-grim** [matrix-org/synapse#5031]
https://github.com/matrix-org/synapse/issues/4620

In INSTALL.md:

> 
"This command will generate you a config file that you can then customise, but it will also generate a set of keys for you"

Referencing the issue where certs ceased to be auto-generated:
https://github.com/matrix-org/synapse/pull/4509

**Comment by neilisfragile** [comment]
Hi @j-grim the line you quote is referring to server keys used to sign messages (which are generated at that point), rather than CA certs. Unless I am missing something I don't agree that the doc is inaccurate.

**Comment by neilisfragile** [comment]
Closing, will reopen pending reply
