### ISSUE TITLE
Synapse wedges on 100% when doing DNS queries 

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#5034]
I turned on presence again on my server, which then promptly tried to send presence updates to all the servers. It then proceeded to wedge for over 10 minutes, at which point I restarted.

During that time I got the following pyflame:

![image](https://user-images.githubusercontent.com/8428120/55806641-92922d80-5ad8-11e9-9055-6eec544c7277.png)

(Full version: https://jki.re/_matrix/media/v1/download/jki.re/RONFxDxvbgPVuzuUeNHMpsfy/flame.svg)

This shows synapse spending all of its time in `twisted.names.client`, i.e. doing DNS queries. (Further pyflames show the same result, so its not just a blip).

**Comment by hawkowl** [comment]
https://twistedmatrix.com/trac/ticket/9620#ticket has now been merged, and affected users can use Twisted trunk until a release.
