### ISSUE TITLE
User Directory not regenerating

### ISSUE THREAD

**Issue by drseussofporn** [matrix-org/synapse#5036]
Originally, our homeserver was federated and able to connect to the matrix network. I decided to remove federation per another Github issue by just whitelisting the local HS for federation. Following this, the `search_all_users` was set to `true` and I performed the psql command `UPDATE user_directory_stream_pos SET stream_id = NULL;` to regenerate the user directory as I wanted the HS to only search local users and forget about all other users it had encountered during federation. However, after a restart of Synapse the user directory still contains entries for users outside of the local installation. How do I clear these entries and force a regeneration of the user directory?

**Comment by neilisfragile** [comment]
For support please ask in #synapse:matrix.org

**Comment by aaronraimist** [comment]
For the record they already asked about 5 times in `#matrix:matrix.org` and `#synapse:matrix.org` and @ara4n told them to file an issue.

**Comment by neilisfragile** [comment]
Well that's not ideal, right I see, this is from the user_dir docs - fair enough I'll run with it

**Comment by hawkowl** [comment]
@drseussofporn You will need to manually rerun the migration, via https://github.com/matrix-org/synapse/blob/master/synapse/storage/schema/delta/53/user_dir_populate.sql , and restart Synapse.

**Comment by drseussofporn** [comment]
@hawkowl Thank you. That was exactly what I needed.

**Comment by richvdh** [comment]
fixed by #5282, seemingly
