### ISSUE TITLE
SSL verification takes a lot of CPU

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#5038]
When we try and open a bunch of TLS connections we spend a lot of time in [`twisted.internet._sslverify.py:selectCiphers:1799`](https://github.com/twisted/twisted/blob/twisted-18.9.0/src/twisted/internet/_sslverify.py#L1800), which can really kill performance if we need to start talking to a lot of servers at once (e.g. for presence). My instinct is that this shouldn't be half as expensive as it is.

Flame graph: [flame.svg](https://jki.re/_matrix/media/v1/download/jki.re/wFWoGcjAnDeWOKfLUvqIcGuF)

**Comment by erikjohnston** [comment]
That function gets called from the constructor of [`OpenSSLCertificateOptions`](https://github.com/twisted/twisted/blob/twisted-18.9.0/src/twisted/internet/_sslverify.py#L1620), and feels like something we shouldn't need to calculate each time we want to start another connection

**Comment by hawkowl** [comment]
Fix in Twisted is up at https://twistedmatrix.com/trac/ticket/9622#ticket

**Comment by hawkowl** [comment]
Closing this, as it's a Twisted bug, and the patch is available on Twisted's GH for those affected.
