### ISSUE TITLE
Debian package doesn't upgrade: /var/lib/dpkg/info/matrix-synapse-py3.postinst hangs

### ISSUE THREAD

**Issue by axelsimon** [matrix-org/synapse#5052]
### Description

Debian package never finishes upgrading.

Upon further inspection, it appears that the `/var/lib/dpkg/info/matrix-synapse-py3.postinst` script invoked by `/usr/bin/perl -w /usr/sbin/dpkg-reconfigure matrix-synapse-py3 -u` is the culprit, as it never finishes, and hangs on a `read(8,`

I've had this problem for a few versions now. I thought my Synapse was still actually upgrading but in fact it was not. The Debian package manager thinks that a recent version is installed, but Synapse itself reports a different version:
`dpkg -l | grep matrix-synapse`:
```
ii  matrix-synapse-py3               0.99.2+stretch1                amd64        Open federated Instant Messaging and VoIP server
```
but:
`curl https://matrix.jaccu.se/_matrix/federation/v1/version`:
```
{
    "server": {
        "name": "Synapse",
        "version": "0.22.1"
    }
}
```

### Steps to reproduce

- `sudo apt upgrade`
- `/var/lib/dpkg/info/matrix-synapse-py3.postinst` gets invoked
- the upgrade stays there, not going further

Here is a snippet from running `sudo dpkg-reconfigure matrix-synapse-py3 -u` with `strace`:
``` stat("/var/lib/dpkg/info/matrix-synapse-py3.postinst", {st_mode=S_IFREG|0755, st_size=5752, ...}) = 0
geteuid()                               = 0
openat(AT_FDCWD, "/var/lib/dpkg/info/matrix-synapse-py3.postinst", O_RDONLY|O_CLOEXEC) = 3
ioctl(3, TCGETS, 0x7ffc0468f800)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
fstat(3, {st_mode=S_IFREG|0755, st_size=5752, ...}) = 0
read(3, "#!/bin/sh -e\n\n. /usr/share/debco"..., 8192) = 5752
lseek(3, 46, SEEK_SET)                  = 46
lseek(3, 0, SEEK_CUR)                   = 46
close(3)                                = 0
pipe2([3, 7], O_CLOEXEC)                = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
ioctl(3, TCGETS, 0x7ffc0468f8c0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fcntl(7, F_SETFD, FD_CLOEXEC)           = 0
ioctl(7, TCGETS, 0x7ffc0468f8c0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(7, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
pipe2([8, 9], O_CLOEXEC)                = 0
fcntl(8, F_SETFD, FD_CLOEXEC)           = 0
ioctl(8, TCGETS, 0x7ffc0468f8c0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(8, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fcntl(9, F_SETFD, FD_CLOEXEC)           = 0
ioctl(9, TCGETS, 0x7ffc0468f8c0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(9, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
pipe2([10, 11], O_CLOEXEC)              = 0
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
ioctl(10, TCGETS, 0x7ffc0468f8c0)       = -1 ENOTTY (Inappropriate ioctl for device)
lseek(10, 0, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
ioctl(11, TCGETS, 0x7ffc0468f8c0)       = -1 ENOTTY (Inappropriate ioctl for device)
lseek(11, 0, SEEK_CUR)                  = -1 ESPIPE (Illegal seek)
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f49dec1a490) = 23117
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(11)                               = 0
read(10, "", 8192)                      = 0
close(10)                               = 0
close(3)                                = 0
close(9)                                = 0
rt_sigprocmask(SIG_BLOCK, [PIPE], [], 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x557d6c81bce0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f49dee28730}, {sa_handler=0x557d6c81bce0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f49dee28730}, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
read(8, "GET matrix-synapse/report-stats\n", 8192) = 32
write(7, "0 true\n", 7)                 = 7
read(8, "GET matrix-synapse/server-name\n", 8192) = 31
write(7, "0 jaccu.se\n", 11)            = 11
read(8, 0x557d6f286770, 8192)           = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23117, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
read(8,    
```
My knowledge of kernel calls is too limited to say if what comes before should also be included, but there are some things that don't look great:
```
read(8, "INPUT high matrix-synapse/report"..., 8192) = 39         
stat("/etc/perl/Debconf/Element/Noninteractive/Boolean.pmc", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/etc/perl/Debconf/Element/Noninteractive/Boolean.pm", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/Debconf/Element/Noninteractive/Boolean.pmc", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/local/lib/x86_64-linux-gnu/perl/5.28.1/Debconf/Element/Noninteractive/Boolean.pm", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/perl/5.28.1/Debconf/Element/Noninteractive/Boolean.pmc", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/perl/5.28.1/Debconf/Element/Noninteractive/Boolean.pm", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/perl5/5.28/Debconf/Element/Noninteractive/Boolean.pmc", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/lib/x86_64-linux-gnu/perl5/5.28/Debconf/Element/Noninteractive/Boolean.pm", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/share/perl5/Debconf/Element/Noninteractive/Boolean.pmc", 0x7ffc0468f290) = -1 ENOENT (No such file or directory)
stat("/usr/share/perl5/Debconf/Element/Noninteractive/Boolean.pm", {st_mode=S_IFREG|0644, st_size=178, ...}) = 0

```

### Version information

- **Homeserver**: 
(matrix.)jaccu.se:
- target domain `matrix.jaccu.se`
- `server_name`: `jaccu.se`

- **Version**: 
hard to say ;)
`curl -v https://matrix.jaccu.se/_matrix/client/versions`reports:
```
{
    "versions": [
        "r0.0.1",
        "r0.1.0",
        "r0.2.0"
    ]
}
```
- **Install method**: 
Debian package from debian.matrix.org

- **Platform**: 
Debian 9 Stretch (VM )

**Comment by axelsimon** [comment]
I tried something new tonight, as I was looking at `/var/lib/dpkg/info/matrix-synapse-py3.postinst` and trying to figure out why `/usr/bin/perl -w /usr/share/debconf/frontend /var/lib/dpkg/info/matrix-synapse-py3.postinst configure 0.99.3+stretch1` had a child process called `matrix-synapse-`. That end hyphen looked weird, as if it was matrix-synapse-py3 without the end of it.

I decided to shut matrix-synapse-py3 down, wondering if the postinst script was failing to do so (or to restart it), and lo and behold, the `dpkg` command completed and `apt` finished.

While this is interesting and gives an insight as to where the script is failing, unfortunately, I'm left in a weird situation where Debian tells me 0.99.4 is installed:
```
dpkg -l | grep matrix
ii  matrix-synapse-py3               0.99.4+stretch1                amd64        Open federated Instant Messaging and VoIP server
```
but synapse itself reports it's still in v 0.22.1:
```
curl https://matrix.jaccu.se/_matrix/federation/v1/version
"version": "0.22.1"
```

Any insight as to what to do next would be much appreciated. Thanks!

**Comment by axelsimon** [comment]
Something else that might be worth mentioning, I moved from `matrix-synapse` to `matrix-synapse-py3` when the python 3 version came out. This means that, for dpkg, traces of `matrix-synapse` are still on the system, as the full output of below shows:
```
dpkg -l | grep matrix
rc  matrix-synapse                   0.34.0.1-0matrix1              all          Open federated Instant Messaging and VoIP server
ii  matrix-synapse-py3               0.99.4+stretch1                amd64        Open federated Instant Messaging and VoIP server
```

**Comment by richvdh** [comment]
> Here is a snippet from running sudo dpkg-reconfigure matrix-synapse-py3 -u with strace: \<...>

Unfortunately this doesn't tell us a lot other than that the postinst process is hanging, which we already knew. The interesting stuff happens in a subprocess which isn't caught here: you'd need `strace -f`. Or you could edit the postinst file in `/var/lib/dpkg/info/matrix-synapse-py3.postinst` to add `-x`. Still, it sounds like you've solved that problem for now.

> but synapse itself reports it's still in v 0.22.1:

Well, there's only two possible explanations for that. One: `matrix.jaccu.se:443` isn't pointing at the right instance of synapse. Two: synapse hasn't been restarted since the update. To help rule out option 2, try `systemctl restart matrix-synapse` and then check the output of `systemd status matrix-synapse`.

**Comment by richvdh** [comment]
more info needed.
