### ISSUE TITLE
Debian package no longer available

### ISSUE THREAD

**Issue by benhartwich** [matrix-org/synapse#5056]
Hi,

the debian package is no longer available - is there any reason for that?

Regards,

**Comment by jryans** [comment]
The packages were removed after the [security incident](https://matrix.org/blog/2019/04/11/security-incident/). They will be restored after a thorough review and new signing keys are created.

**Comment by neilisfragile** [comment]
@benhartwich Packages can now be found at https://packages.matrix.org/ Packages are signed with fresh & secured GPG keys. Thanks for your patience.
