### ISSUE TITLE
[Support] Fatal error while trying to register a new user through the Client-Server-API

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#5060]
I am getting the below error while trying to register new users through the Cient-Server-API on a local (dev) machine:

`Client error: POST http://localhost:8008/_matrix/client/r0/register?kind=user resulted in a 401 Unauthorized response: {"errcode":"M_MISSING_TOKEN","error":"Invalid Authorization header."} `

The login of the initial user account works fine through the API.

Registration specific settings in homeserver.yaml: 
-- The homeserver registration is enabled ("enable_registration: True").
-- "registration_shared_secret" is set, however, not used in this scenario.
-- "registrations_require_3pid" is commented / disabled.

The following Json is posted: 
`{"kind":"user","auth":{"type":"m.login.dummy"},"username":"myusername","password":"myusername"}`

How do I have to authorize such a registration request? Obviously a token is missing.

**Comment by neilisfragile** [comment]
#synapse:matrix.org is the right place for support, closing this issue since what you describe does not appear to be a bug.

A quick look at your request makes me think you are missing fields in your request - I think you need a session id.

You might find the following useful.
 * https://matrix.org/docs/spec/client_server/r0.4.0.html#user-interactive-authentication-api
 * https://matrix.org/docs/spec/client_server/r0.4.0.html#id196 (to generate the session)

**Comment by menturion** [comment]
@neilisfragile many thanks for your reply.
Yes, that is not a bug. I don't khow how to start a session for the resgistration. I have already read the Client-Server reference and didn't find the missing information. 

You shared the below link to the Client-Server API which seems to be right (missing) info I need for generating a session:  
https://matrix.org/docs/spec/client_server/r0.4.0.html#id196

However, following this link I'm not sure which item you exactly reference.  Could you please paste the header resp. subheader of the Client-Server reference section so that I know which one exactly you mean. Many thanks in advance.

**Comment by neilisfragile** [comment]
https://matrix.org/docs/spec/client_server/r0.4.0.html#user-interactive-api-in-the-rest-api Shows how to generate the session id

**Comment by menturion** [comment]
Thanks! I'll take a look.

**Comment by menturion** [comment]
Update: 
I turns out that it seems to be an issue of the configuration (or something else) and not the API. 
Riot web is prompting "Registration has been disabled" although it is enabled in the homeserver.yaml.

**Comment by menturion** [comment]
Update:
After overcoming some issues I finally got it to request a session ID for an endpoint.
Solved.

Thanks fro your time.
