### ISSUE TITLE
gpg: no valid OpenPGP data found when adding repo key

### ISSUE THREAD

**Issue by jamiew0w** [matrix-org/synapse#5066]
### Description

```
sudo apt install -y lsb-release curl apt-transport-https
echo "deb https://matrix.org/packages/debian `lsb_release -cs` main" |
    sudo tee /etc/apt/sources.list.d/matrix-org.list
curl "https://matrix.org/packages/debian/repo-key.asc" |
    sudo apt-key add -
sudo apt update
sudo apt install matrix-synapse-py3
```

Following official installation steps for ubuntu based systems, failing on curling the key and adding it.

### Steps to reproduce

- follow official install instructions on ubuntnu
- hit error

### Version information

- **Homeserver**: 

- **Version**: n/a

- **Install method**: package manager

- **Platform**: ubuntu 16.04

VM

**Comment by jamiew0w** [comment]
I'm assuming this is going to be related to the keys being revoked on the security issue last week.

**Comment by turt2live** [comment]
Duplicate of https://github.com/matrix-org/synapse/issues/5056
