### ISSUE TITLE
Implement a "room complexity" API to signal to other homeservers how complex a room is

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#5069]
`_matrix/federation/unstable/rooms/<room_id>/complexity`, or so. Returns a "complexity metric", which is right now state_events / 500.

**Comment by jcgruenhage** [comment]
It has been suggested in #test:zemos.net to instead extend `GET /_matrix/federation/v1/query/{queryType}` with a new queryType called room_summary. I think this would be more consistent with the rest of the spec.

**Comment by Half-Shot** [comment]
(this probably needs a companion matrix-doc issue at the very least, and ideally a spec proposal)

**Comment by jcgruenhage** [comment]
@Half-Shot I don't think this is exactly the matrix-doc issue you linked, that is more a generic thing, right

**Comment by Half-Shot** [comment]
Hmm probably right.

**Comment by hawkowl** [comment]
Right now I'm putting this in the `unstable` namespace, as an experiment to see if it gets the desirable user experience. If it works, I think moving it into that spec'd API, post-r0, is where that'll end up.

**Comment by ara4n** [comment]
https://docs.google.com/document/d/1kZngFUTXfPEpx6qvxBwQeQEntZZsENdFX69XSVmDZ54/edit is the proto-MSC for this
