### ISSUE TITLE
Replace the repo key

### ISSUE THREAD

**Issue by loru** [matrix-org/synapse#5075]
**Description:**

[Here](https://github.com/matrix-org/synapse/blob/master/INSTALL.md) in the "Note" you specify the need to drop the key but actually don't provide the new key. Also, you changed the way you provide the key for the repo. Can you use the classic way for apt?

`curl "https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg" | sudo apt-key add -`

**Comment by richvdh** [comment]
> Here in the "Note" you specify the need to drop the key but actually don't provide the new key. 

The instructions say:

`sudo wget -O /usr/share/keyrings/matrix-org-archive-keyring.gpg https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg`

> Can you use the classic way for apt?

You may consider it the classic, but it is deprecated and incorrect. Please see https://wiki.debian.org/DebianRepository/UseThirdParty andhttps://unix.stackexchange.com/a/463140/11281.
