### ISSUE TITLE
Missing fingerprint for debian repository gpg key

### ISSUE THREAD

**Issue by crtxcr** [matrix-org/synapse#5084]
Since the recent security incident, I removed the apt repo source from my server since I couldn't be sure that it's not compromised. I want to add it again following the instructions in https://github.com/matrix-org/synapse/blob/master/INSTALL.md. 

However, I cannot find any official source that lists the fingerprint of the key in question. I have no way of knowing whether the key in question is really the one it's supposed to be. Please add the fingerprint at the very least to the INSTALL.md. 
 
Perhaps relevant is is a rejected pull-request: https://github.com/matrix-org/synapse/pull/4609
I think it is not sufficient that the key is fetched https, especially in light of the recent security incident. I have no problem comparing a simple fingerprint and in fact, I consider the absence of a fingerprint, not the presence, off-putting for (new) users.

**Comment by richvdh** [comment]
> Perhaps relevant is is a rejected pull-request: #4609

It was not rejected. The submitter decided that they did not want to discuss it and requested it be closed. Those are different things.

> Please add the fingerprint at the very least to the INSTALL.md.

Done.
