### ISSUE TITLE
Users with associated email addresses can't deactivate their accounts

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#5097]
To reproduce:
- register a new user `@test.user.32492374987:matrix.org` with an email address `turnip.coleslaw@anticrap.co.uk`
- try and deactivate your account
- see an `unknown error` in the ux, that's actually a 400 `{"errcode":"M_UNKNOWN","error":"Failed to remove threepid from ID server"}`

**Comment by salcedo** [comment]
Getting the same error when trying to deactivate account or remove an associated email address. This is not cool. First there is an exposure - now we can't deactivate and get our data removed from the matrix HS.

**Comment by neilisfragile** [comment]
This is a sydent bug, tracking here https://github.com/matrix-org/sydent/issues/145

**Comment by neilisfragile** [comment]
Closing in favour of matrix-org/sydent#145

@salcedo  we have a temporary workaround live on the vector.im sydent, so you should be able to deactivate now.
