### ISSUE TITLE
 m having issues configuring email notification in homeserver.yaml.

### ISSUE THREAD

**Issue by fredhampton** [matrix-org/synapse#5105]
### Description

I m having issues with turning on email notification in homeserver.yaml.....No matter what changes I make to the Enable sending emails section the log file continues to show  "synapse.push.pusher - 43 - INFO - - email enable notifs: False" . Is there anyway to find out which settings are not working ....the log file does not seem to help with tracking down what the issue is...

### Steps to reproduce

Making changes to Enable sending emails section of homeserver.yaml

<!--
I expect that after configuration the email notifications would work

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 
My homeserver 
If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**:
Latest Debian build 

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->
Package 
- **Platform**: 
Debian
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
Running on bare metal debiab
-->

**Comment by fredhampton** [comment]
With 
journalctl -xe
I receive an error message 
email.enable_notifs is True but required keys are missing

**Comment by Sharparam** [comment]
What does your config file look like? (Make sure to mask any sensitive information before posting it.)

**Comment by richvdh** [comment]
this isn't a support forum I'm afraid.
