### ISSUE TITLE
Tests using tox fails because of latest versions of pip

### ISSUE THREAD

**Issue by DrGlitchMX** [matrix-org/synapse#5107]
### Description

Running tests with tox (e.g. **./test_postgresql.sh**) fails at the setup stage of virtual environments.

### Steps to reproduce

- checkout master
- create virtual python environment: `virtualenv -p python3 env`
- install dependencies: `pip install -e . --no-use-pep517`
- run `./test_postgresql.sh`

Late versions of pip do not play nicely with "editable mode", therefore the parameter `--no-use-pep517` must be provided to allow pip to run with editable mode enabled, nevertheless.

Another issue is further down the line: pip would also get invoked from tox, while the `tox.ini` shipped with tox makes use of the default install command, hence fails for the same reason.

### Expected behavior ###
I would expect the project's tests to run out of the box.

### Version information
tested on 0.99.3, also tested on **master**, FWIW

**Platform**: 
Debian GNU/Linux buster, Kernel version 5.0.9

**Maybe related:**
#4848 

I will gladly supply a fix for this issue, if so desired.

**Comment by babolivier** [comment]
This is fixed in https://github.com/matrix-org/synapse/pull/5098, which hasn't made its way to master or a stable release yet.
