### ISSUE TITLE
Enforcing serverside password complexity requirements

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5112]
Rather than clients all having to do zxcvbn separately, surely the server should be enforcing complexity requirements?

**Comment by dklimpel** [comment]
It is implemented in #5214
Unfortunately only in dinsinc branch.

**Comment by clokep** [comment]
Looks like this was implemented in #7118? That at least adds an endpoint to get the configuration, doesn't just return the complexity of a password though, so...maybe not.

**Comment by richvdh** [comment]
yeah it's not obvious that this is still a useful feature request.
