### ISSUE TITLE
Not working Calls via mobile net 

### ISSUE THREAD

**Issue by laicon188** [matrix-org/synapse#5126]
Hello.

Now we have some problems with voip and video calls.
When I try to call, after answering, the Riot shows that it tries to connect and then it is reset. It happents when I use Mobile internet on my phone. 
The problem started a week ago.
I have already update matrix synapse to version 99.3 and update Riot on my phone.
I tryed to make call between Android-Android, Android-iPhone, iPhone-iPhone but all then failed.

Please, suggest something to solve this problem

**Comment by laicon188** [comment]
Update to a version 0.99.3.2 
Problem not solved.
Noticed that I can make calls vai WiFi, when both phones in the same WiFi network.

**Comment by neilisfragile** [comment]
Hi @laicon188 this doesn't sound like a matrix problem, could you mobile network be blocking certain types of traffic? 

If you really think it _is_ something that can be fixed in matrix the place to get support is #synapse:matrix.org

**Comment by laicon188** [comment]
> 
> 
> Hi @laicon188 this doesn't sound like a matrix problem, could you mobile network be blocking certain types of traffic?
> 
> If you really think it _is_ something that can be fixed in matrix the place to get support is #synapse:matrix.org

I have a stun server on an another server. Stun server was unavaliable and I can't make calls via different networks.

**Comment by bilalbilalsheikh** [comment]
unable to connect call on matrix with different network
