### ISSUE TITLE
Change default room level structure to support owners

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#5131]
Right now default room creation creates a structure with the default levels so that
* Average Joe(0) can join and talk
* Moderator(50) can play King
* Admin(100) can play God.

However it seems that **equal levels cannot demote one another** which may lead to some hard to handle problems, ranging from plainly "the owner wants demote admins" to handlinkg hacked accounts, rogue admins and such.

It seems just logical to define Admin as 90 and Owner as 100, and create the default structure as it is, but using Lvl90 instead of Lvl100, and give creator Lvl100, so s/he can demote admins at will, or promote owners if s/he dare. Also this probably requires read-made level buttons or default commands to change accordingly.

I am not sure whether this is a *synapse*, or a *riot* or a *matrix.org protocol* issue, and I kindly ask you to open, link, move issues or otherwise help this issue to reach the responsible circles.

**Comment by richvdh** [comment]
I think this is https://github.com/matrix-org/matrix-doc/issues/652

**Comment by grinapo** [comment]
No, it is not. That issue is a convoluted and complex discussion of various things, including automagically raised levels, special status and such.

This one is a really simple one: the current level system can support owners. When creating a room the owner is level 100 (or 1000 or anything larger than anything else) and "admin" level is 90 and "moderator" level is 50. 
I am not sure whether this is a Riot or a Synapse question though,

**Comment by richvdh** [comment]
ok, well, it's both. synapse controls the default power levels; riot offers UI for the three common power levels.

Anyway, I don't think we're likely to change it any time soon. To be honest I think it adds a layer of complexity which most people won't find useful.

What we *could* do is expose configuration settings for the default power levels in `homeserver.yaml`. Still, (a) that's a separate thing; and (b) as above, I don't think it's something we're going to rush to do. I think we'd accept a PR doing so, though.
