### ISSUE TITLE
500 on /messages in a room bridged to Freenode

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/synapse#5137]
### Description
Loading messages history in `#konversation:matrix.org` is not working at the moment. As @ara4n suggested it may be a case of a specific broken room due to migration between the two Freenode bridges.

### Steps to reproduce
- Login to a matrix.org user (didn't try other homeservers).
- `/join #konversation:matrix.org` and open the room in any client

Expected: the timeline backlog is filled in with messages.
Actual: the timeline backlog is empty, the client-side logs (Quaternion and Riot Web in my case) reveal that the server consistently responds with 500.

### Version information
- **Homeserver**: matrix.org
- **Platform**: most likely cross-platform but I only tried Windows client-side.

**Comment by MadLittleMods** [comment]
Closing as I assume this is no longer reproducible and logs were never pulled at the time.
