### ISSUE TITLE
Add matrix-synapse-ldap in the Docker image

### ISSUE THREAD

**Issue by henry-nicolas** [matrix-org/synapse#5140]
Dear,

Could you please add matrix-synapse-ldap3 auth-provider in the Docker image?
From the github page, this is installable via pip so just adding it to the Dockerfile should be enough.

Doing so would allow easier integration into existing corporte environments.

Thanks and best regards,

**Comment by richvdh** [comment]
It is included already:

```
$ docker run --rm -it --entrypoint sh matrixdotorg/synapse:v1.0.0 -c '/bin/ls /usr/local/lib/python3.6/site-packages/ldap_auth_provider.py'
/usr/local/lib/python3.6/site-packages/ldap_auth_provider.py
```
