### ISSUE TITLE
User can still use Riot.im after deleted from server

### ISSUE THREAD

**Issue by PedroMarquesEnso** [matrix-org/synapse#5147]
### Steps to reproduce

- Add user to Riot
- Log in via Riot.im (android)
- Chat with other users
- Delete user from Riot 
- User still can answer messages via Riot.im after beeing deleted from server

Is there a way to force a deleted user to logout Riot.im?

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->



<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: riot-v0.12.3

- **Install method**: https://www.vultr.com/docs/create-a-chat-server-using-matrix-synapse-and-riot-on-centos-7

<!-- examples: package manager/git clone/pip  -->

- **Platform**: CentOS Linux release 7.6.1810 (Core) 

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->


Is there a way to force a deleted user to logout Riot.im?

**Comment by t3chguy** [comment]
What steps did you take to delete the user? You probably did not wipe out their access tokens.

**Comment by PedroMarquesEnso** [comment]
Hello,

I used a script:

./remove_user.sh user

#!/bin/bash

cd /tmp

USER="$1"

SQLCMD="
DELETE FROM users WHERE name='@$USER:myserver.com';
DELETE FROM access_tokens WHERE user_id='@$USER:myserver.com';
DELETE FROM user_ips WHERE user_id='@$USER:myserver.com';
DELETE FROM profiles WHERE user_id='$USER';
DELETE FROM presence_stream WHERE user_id='@$USER:myserver.com';
DELETE FROM devices WHERE user_id='@$USER:myserver.com';
DELETE FROM device_lists_stream WHERE user_id='@$USER:myserver.com';
VACUUM;
"

echo $SQLCMD | sudo -u postgres psql synapse


By the way, how to wipe user access tokens?

**Comment by t3chguy** [comment]
`DELETE FROM access_tokens WHERE user_id='@$USER:myserver.com';` in the SQLCMD you posted should already do this

**Comment by turt2live** [comment]
After deleting them, did you restart synapse?

**Comment by PedroMarquesEnso** [comment]
restarting synapse does the trick.

Thank you very much for help guys!!!
Much appreciated.

Best Regards,
Pedro Marques
