### ISSUE TITLE
Cannot register a new user in Synapse (ERROR! 400 Bad request Shared secret registration is not enabled)

### ISSUE THREAD

**Issue by zach-smith97** [matrix-org/synapse#5150]
I have installed matrix synapse on one of my school's hosted VMs following these instructions with the prebuilt debian/ubuntu package: https://github.com/matrix-org/synapse/blob/master/INSTALL.md
The VM is running Ubuntu 18.04.2. After finally getting my homeserver.yaml file configured properly (I had to remove all of the special characters from the file since .yaml files apparently don't support them), I tried running the command `register_new_matrix_user -c homeserver.yaml http://localhost:8008` as shown in the guide, but I keep hitting an error. The error states: "ERROR! Received 400 Bad Request Shared secret registration is not enabled". Now I know have shared secret registration enabled in the homeserver.yaml file, and even generated a secret string to place for the value, but as far as I can tell, I am not even using the shared secret to register the user? I have also tried using the `-k 'my secret code'` option instead of the `-c homeserver.yaml` option, but to no avail. I have also edited the homeserver.yaml file and commented out the registration_shared_secret field altogether, but then the server gives me the error: "No 'registration_shared_secret' defined in config." Before you ask, yes the field `enable_registration` is set to true as well. Has anyone else experienced this issue? I will paste the registration of my homeserver.yaml file code below to see if there are any issues. Apologies for formatting; the # for the commented out lines seems to bold everything. Thanks.

**Edit: Just wanted to add that I've even gone into the register.py file in 
/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/
and taken out the lines of code that spit out this error. I then restarted matrix-synapse, tried to register again, and it still gave me the same error. How is this possible? Is there another instance of code somewhere I'm unaware of that can raise this synapse error?

`## Registration ##
#
# Registration can be rate-limited using the parameters in the "Ratelimiting"
# section of this file.

# Enable registration for new users.
#
enable_registration: true

# The user must provide all of the below types of 3PID when registering.
#
#registrations_require_3pid:
#  - email
#  - msisdn

# Explicitly disable asking for MSISDNs from the registration
# flow (overrides registrations_require_3pid if MSISDNs are set as required)
#
#disable_msisdn_registration: true

# Mandate that users are only allowed to associate certain formats of
# 3PIDs with accounts on this server.
#
#allowed_local_3pids:
#  - medium: email
#    pattern: '.*@matrix\.org'
#  - medium: email
#    pattern: '.*@vector\.im'
#  - medium: msisdn
#    pattern: '\+44'

# If set, allows registration of standard or admin accounts by anyone who
# has the shared secret, even if registration is otherwise disabled.
#
registration_shared_secret: -removed for security-

# Set the number of bcrypt rounds used to generate password hash.
# Larger numbers increase the work factor needed to generate the hash.
# The default number is 12 (which equates to 2^12 rounds).
# N.B. that increasing this will exponentially increase the time required
# to register or login - e.g. 24 => 2^24 rounds which will take >20 mins.
#
#bcrypt_rounds: 12

# Allows users to register as guests without a password/email/etc, and
# participate in rooms hosted on this server which have been made
# accessible to anonymous users.
#
#allow_guest_access: false

# The identity server which we suggest that clients should use when users log
# in on this server.
#
# (By default, no suggestion is made, so it is left up to the client.
# This setting is ignored unless public_baseurl is also set.)
#
#default_identity_server: https://matrix.org

# The list of identity servers trusted to verify third party
# identifiers by this server.
#
# Also defines the ID server which will be called when an account is
# deactivated (one will be picked arbitrarily).
#
#trusted_third_party_id_servers:
#  - matrix.org
#  - vector.im

# Users who register on this homeserver will automatically be joined
# to these rooms
#
#auto_join_rooms:
#  - "#example:example.com"

# Where auto_join_rooms are specified, setting this flag ensures that the
# the rooms exist by creating them when the first user on the
# homeserver registers.
# Setting to false means that if the rooms are not manually created,
# users cannot be auto-joined since they do not exist.
#
#autocreate_auto_join_rooms: true`

**Comment by richvdh** [comment]
sorry, can't read this.

**Comment by richvdh** [comment]
(`#synapse:matrix.org` is a better place to get support)

**Comment by richvdh** [comment]
sorry, I was a bit hasty last night, but the point still stands: it's difficult to prioritise bug reports that are hard to read when there are plenty where people have gone to the effort to make them clear and concise, and I do recommend discussing it with the good people in #synapse:matrix.org to eliminate configuration problems on your side.

If you feel there is a bug here, please edit the description to clearly describe the problem you are having. I suggest using paragraph breaks, and consult github's [guide to markdown](https://guides.github.com/features/mastering-markdown/) to fix the formatting problems.
