### ISSUE TITLE
Could not connect to the integration server

### ISSUE THREAD

**Issue by PedroMarquesEnso** [matrix-org/synapse#5160]
### Steps to reproduce

- Install Matrix Server
- Every room gives error (Could not connect to the integration server)

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: riot-v0.12.3

- **Install method**: https://www.vultr.com/docs/create-a-chat-server-using-matrix-synapse-and-riot-on-centos-7
<!-- examples: package manager/git clone/pip  -->

- **Platform**: CentOS Linux release 7.6.1810 (Core)
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->


I checked homeserver logs and found nothing related to integration server..
This is happening in every room (there's a warning on top).

Any help would be appreciated.

Thanks in advance,
Pedro Marques

**Comment by turt2live** [comment]
Synapse is not an integrations server. An integrations server is a third piece of software which assists users in adding things to rooms (bridges, bots, widgets, etc). The two most popular ones out there are scalar.vector.im (the default) and [Dimension](https://dimension.t2bot.io) (authored by myself).

**Comment by aaronraimist** [comment]
Riot 0.12.3 is super old (and if you are running that old a version of Riot then you are probably running an old version of Synapse). Update Riot to 1.1.0 and Synapse to the latest version.

**Comment by richvdh** [comment]
this doesn't sound like a synapse issue
