### ISSUE TITLE
Pluses in emails during regisration are dropped from new account form

### ISSUE THREAD

**Issue by the-moog** [matrix-org/synapse#5161]
Using gmail, you can do 'user.name+test1@gmail.com' to create instant aliases of emails
Emails go to the same inbox, but Matrix does not know that.
However the + is filtered from the new account form so that it tries to register 'user.name test1@gmail.com' which is not a valid email address.

**Comment by richvdh** [comment]
Are you sure this is a synapse issue? If so, which API endpoint did you use, and what values did you send?

I suspect it is a client issue, in which case I suggest you file a report against the appropriate client with clear reproduction steps. I was unable to reproduce it with riot-web.
