### ISSUE TITLE
Enable Buildkite builds for contributor PRs

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#5162]
- Pull buildkite pipeline out of the file
- Make sure we don't propagate the environment down
- Add a plugin to make a markdown file be an annotation without using the buildkite agent inside the container

**Comment by richvdh** [comment]
Turns out that you can specify `pull/NNNN/head` as the branch to build, which I think will serve our purpose unless/until we go to the faff of setting up burn-after-use agents so that the CI can run automatically.

**Comment by richvdh** [comment]
done!
