### ISSUE TITLE
synaps  behind reverse proxy

### ISSUE THREAD

**Issue by r4a5a88** [matrix-org/synapse#5173]
Hi

I have a setting where most of my Servers are behind an apache reverse proxy in an Internal Network . I followed the instructions to set up synapse server in that network. 

I use this config on my synapse Server
<VirtualHost *:80>
    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
</VirtualHost>

<VirtualHost *:8448>
    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
</VirtualHost>

I use this apache config on my reverse proxy
Alias _matrix /_matrix

	ProxyPass /_matrix http://192.168.13.85/_matrix nocanon
	ProxyPassReverse /_matrix http://192.168.13.85/_matrix 

Apache brings me a 404 Page

No Such Resource

Sorry. No luck finding that resource.

I there a way to set up synapse in such an environment ? 
Does anybody have tips for me ?

**Comment by Half-Shot** [comment]
> Apache brings me a 404 Page
> No Such Resource

What were you trying to access? That sounds like your path wasn't correct. To test it, you can do https://yourdomain.com/_matrix/client/versions

**Comment by r4a5a88** [comment]
Der Test hat geklappt und ich habe eine Seite bekommen.


Aber beim Riot client bekomme ich 
Fehler: Problem bei der Kommunikation mit dem angegebenen Home-Server. (M_UNRECOGNIZED)

**Comment by r4a5a88** [comment]
2tes Problem. ich hab diese meldung in der Apache Log
 "GET /_matrix/_matrix/client/r0/login HTTP/1.1"
Das heist, das ist ne Proxy fehlkonfiguration irgendwo

**Comment by r4a5a88** [comment]
I figured it out. My conf actually worked. 
thanks for the awesome tip
here are my confs for anyperson that need them . 
the riot clients is in the document root

Alias _matrix /_matrix
Alias riot /riot

	ProxyPass /_matrix http://192.168.13.85/_matrix nocanon
	ProxyPassReverse /_matrix http://192.168.13.85/_matrix 

	ProxyPass /riot http://192.168.13.85/riot
	ProxyPassReverse /riot http://192.168.13.85/riot


<VirtualHost *:80>
	#DocumentRoot /var/www/riot/
	
	
	ProxyRequests off
	ProxyPreserveHost On
	ProxyVia full

    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix

	Alias riot /riot
	Alias /riot /var/www/riot/
	
</VirtualHost>

<VirtualHost *:8448>
    
  
    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix

</VirtualHost>
