### ISSUE TITLE
Room directory returns an error

### ISSUE THREAD

**Issue by agherzan** [matrix-org/synapse#5180]
### Description

I installed a home server on which the `Room directory` when using riot-web returns the following error:
```
Riot failed to get the public room list. CORS request rejected: https://<DOMAIN>/_matrix/client/r0/publicRooms?server=matrix.org
```

The POST request returns 405 and the console logs:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<DOMAIN>/_matrix/client/r0/sync?filter=0&timeout=30000&since=s9_83_0_1_1_1_1_6_1. (Reason: CORS request did not succeed).[Learn More]
```

Also:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<DOMAIN>/_matrix/client/r0/publicRooms?server=matrix.org. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).[Learn More]
```

### Steps to reproduce

- install riot and synapse 
- use riot to navigate "Room directory"

### Version information

- **Version**: 0.99.3.2

- **Install method**: docker containers for both riot and synapse

- **Platform**: Synology NAS system.

**Comment by agherzan** [comment]
It seems like it's related to the fact that federate (and client) is behind are behind cloudflare. Are there any known issues in that regards?

**Comment by richvdh** [comment]
> CORS request rejected

this normally means that you had a reverse-proxy (or, in this case, Cloudflare), which timed out the request and returned an error without the CORS headers, which normally means that your server is overloaded and failing to respond. The solution is to find out why your server is overloaded and fix it. You might get some help in #synapse:matrix.org.
