### ISSUE TITLE
expire messages 

### ISSUE THREAD

**Issue by webmind** [matrix-org/synapse#5188]
I would like to see the option to let your messages expire over time so servers are instructed to destroy the messages after expiry and more importantly that you can have a room where all messages expire over time. Sensible times to me could be a day, a week, a month or a year.

So two features:

1) be able to set messages in a room to expire.
2) be able to let your own messages expire.

Where expire means all federated servers are instructed to remove the message.

Thanks

**Comment by Half-Shot** [comment]
This is https://github.com/matrix-org/matrix-doc/pull/1763, which is currently being proposed for Matrix but isn't part of the spec yet, and so isn't supported by synapse yet.

**Comment by cuongnv** [comment]
You can create your own script, put it in your server. And periodically run to redacted all messages with time setup.

**Comment by richvdh** [comment]
closing as a dup of existing issues
