### ISSUE TITLE
Docker Image - Allow to define trusted_third_party_id_servers

### ISSUE THREAD

**Issue by nsteinmetz** [matrix-org/synapse#5194]
**Description:**

You cannot define `trusted_third_party_id_servers` by using environment variables for the docker image - cf https://github.com/matrix-org/synapse/blob/master/docker/conf/homeserver.yaml#L161-L163

So if you want to run your own mxisd server for ex, you can't define it and must edit the yaml file somehow.

We could have something like:

```
trusted_third_party_id_servers:
{% if SYNAPSE_TRUSTED_ID_SERVERS %}
{% for server in SYNAPSE_TRUSTED_ID_SERVERS.split(',') %}    - {{ server }}
{% endfor %}
{% else %}
    - matrix.org
    - vector.im
{% endif %}
```

and as environment variable:

```
SYNAPSE_TRUSTED_ID_SERVERS = id1.example.com,id2.example.com
```

**Comment by hawkowl** [comment]
As per https://github.com/matrix-org/synapse/issues/5518 , we're going to recommend people configure this in a proper config file, as maintaining environment variables for every option is getting unwieldy, hard to maintain, and harder to write documentation for.
