### ISSUE TITLE
Config option to override default room version.

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#5202]
Synapse 1.0 will default to new room version (v4), this means that any new rooms that it creates will be of version v4. 

Generally this is a good thing, but there will be cases where a given server wants to create rooms with old room versions. Perhaps they need to interoperate with another server that for whatever reason cannot upgrade. 

So there needs to be a way to override the room default version and replace it with an older version - even an unstable version.

**Comment by turt2live** [comment]
What is v4 in this context? [MSC2002](https://github.com/matrix-org/matrix-doc/pull/2002) (created after this was opened) or some other v4?

**Comment by anoadragon453** [comment]
@turt2live

v4 - no slashes in event IDs
v5 - key validity + no slashes in event IDs
