### ISSUE TITLE
OPENSIPS 2.4.4 crashes on RHEL 7

### ISSUE THREAD

**Issue by TruptiSh** [matrix-org/synapse#5240]
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

### Version information

- **Homeserver**: 

If not matrix.org:

- **Version**: 

- **Install method**: 

- **Platform**:

**Comment by turt2live** [comment]
What's the error when it crashes? Please fill out the template.

**Comment by richvdh** [comment]
what even is OPENSIPS?

**Comment by richvdh** [comment]
well, I googled it, and I'm not sure what it has to do with synapse, so I'm going to assume this is in the wrong place.
