### ISSUE TITLE
Implement rooms v5

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#5247]
Synapse v1.0 will default to rooms v4, however the intention is that it also ships with rooms v5 which is envisaged to be rooms v4 + https://github.com/matrix-org/synapse/issues/4364

rooms v5 is yet to be MSC'd so does not formally exist at this point, this issue is a place holder.

**Comment by turt2live** [comment]
spec-side tracking issue is https://github.com/matrix-org/matrix-doc/issues/2021 although would recommend tracking progress against either this issue or https://github.com/matrix-org/synapse/issues/4364

**Comment by richvdh** [comment]
done by #5354
