### ISSUE TITLE
logout returns M_UNKNOWN_TOKEN instead of M_MISSING_TOKEN

### ISSUE THREAD

**Issue by taigaka** [matrix-org/synapse#5255]
Using `/_matrix/client/r0/logout` without an access token returns the error

`M_UNKNOWN_TOKEN` `Access Token unknown or expired`

while every other unauthorized request, including `/_matrix/client/r0/logout/all` returns

`M_MISSING_TOKEN` `Missing access token.`

**Comment by aaronraimist** [comment]
This was fixed
