### ISSUE TITLE
Feature request: prevent certain changes to user profiles

### ISSUE THREAD

**Issue by TheLastProject** [matrix-org/synapse#5267]
**Description:**

It would be great if we could disable some user profile changes, like changing the display name, for on servers where this is set by the identity server on login.

**Comment by richvdh** [comment]
Related: #4708

**Comment by neilisfragile** [comment]
I'm trying to think how this would work. 

You could set it on a room level, that way all servers participating would have to respect the rule. 

Or you could do it on a server level (which I _think_ is what you are asking for), but I'm not sure that makes sense if the server then federates with other servers that do not enforce profile change.

**Comment by TheLastProject** [comment]
Well, a server is coupled to an identity server, which is where the accounts will come from. Putting it on the same level as the accounts itself sounds most logical? The use case here is company LDAP accounts and preventing people from impersonating each other within the company.

**Comment by t3chguy** [comment]
> Well, a server is coupled to an identity server, which is where the accounts will come from. Putting it on the same level as the accounts itself sounds most logical? The use case here is company LDAP accounts and preventing people from impersonating each other within the company.

That is not how accounts work.

Identity servers provide identity lookup functionality only (mapping from e-mails and phone numbers to Matrix IDs)

Accounts are stored and owned by their respective homeserver currently, in future they may be more fluid.

**Comment by TheLastProject** [comment]
Well, not to sound rude, but as an administrator I don't really care about that implementation detail, I just want to be able to prevent users from impersonating each other, like how many other messaging platforms such as Rocket Chat will lock usernames to whatever is in LDAP.

Seeing how the homeserver knows the accounts, limiting on homeserver level seems most logical, because we can't expect matrix.org to enforce a lack of nick changes, but you still wouldn't want your employees to change their username when talking to people on matrix.org. You want certainty for the accounts that are managed by your organisation, both for communication inside it and communication with other servers you decided to link to.

**Comment by dklimpel** [comment]
see also: #5241

**Comment by eMPee584** [comment]
Yeah LDAP support is not exactly matrix's strongest feat atm..
@ara4n Isn't the french government using it? No corporate sponsors for it yet?

**Comment by clokep** [comment]
I believe this was fixed by #7096.
