### ISSUE TITLE
Synapse 0.99.3 is freezing for a few days now

### ISSUE THREAD

**Issue by ejpcmac** [matrix-org/synapse#5279]
### Description

A few days ago I noticed that Synapse was taking an huge amount of memory on my server, as I started to get “cannot get swap space” messages.

After a restart, it works as expected for a minute or so. Then it becomes unresponsive (Riot says it is disconnected), consuming 100% CPU and growing its memory consumption slowly, minutes after minutes.

At this point, I also see messages like this in my system logs (FreeBSD):

```
May 26 21:08:41 ejpcmac kernel: sonewconn: pcb 0xfffff8000f6d8570: Listen queue overflow: 76 already in queue awaiting acceptance (124 occurrences)
```

I’ve seen #5264 and #5266, which both relates about an issue that seems similar in 0.99.5.1, but it seems to be the case in 0.99.3 too. Maybe it has something to do with some updates in the federation as a whole? My Synapse instance has been operating properly for months (years?).

I’ve run [this](https://github.com/matrix-org/synapse/issues/1760#issuecomment-356270367) to try if it was solving my problem: it is not.

### Steps to reproduce

- start synapse
- see it freezing after a short time

### Version information

- **Homeserver**: ejpcmac.net (https://matrix.ejpcmac.net/)

If not matrix.org:

- **Version**: 0.99.3

- **Install method**: FreeBSD ports

- **Platform**: FreeBSD 11.2-RELEASE-p10, in a jail

**Comment by neilisfragile** [comment]
Hi @ejpcmac if it's not extremities you could try disabling presence? 

What sort of cache factor are you using, depending on how much RAM you have available it might be worth increasing somewhere around 2-4.

If that doesn't help you, have you joined any large rooms recently, it could be that the extra load has pushed you over a cliff.

The issue tracker is not a great place to get support you are much better off trying #synapse:matrix.org

Best I can tell this is not a general problem, so I am going to close.

**Comment by nipos** [comment]
We're having exactly the same issue with two different and independent servers.
One of them has been available for nearly a year and the CPU usage started to grow rapidly and without any reason a few weeks ago.
The latest update made it a little bit faster again but wasn't a big help.
The other server has been available for one or two months and the CPU usage started to grow rapidly a few days ago.
Additionally the RAM usage on the second server grew that much that we needed to create a SWAP file to prevent the server from crashing completely.
On the second server the update worked great for one day and the CPU load was at 10-15% again like it has always been but then it went up to between 60 and 70% again and we have no idea how we can solve it this time.

**Comment by ejpcmac** [comment]
> Hi @ejpcmac if it's not extremities you could try disabling presence?
>
> What sort of cache factor are you using, depending on how much RAM you have available it might be worth increasing somewhere around 2-4.

@neilisfragile Thank you for your insights, I’ll try this as soon as I get some time to experiment.

> If that doesn't help you, have you joined any large rooms recently, it could be that the extra load has pushed you over a cliff.

No, I’m in large rooms but for a long time now. Nothing has changed recently outside of the general federation changes.

> The issue tracker is not a great place to get support you are much better off trying #synapse:matrix.org

I should create another MatrixID then, since I cannot access it from my server which is freezing. But why not if I struggle at finding a solution.

**Comment by ejpcmac** [comment]
After upgrading to Synapse 0.99.5.2, the issue was still there. I’ve disabled the presence system with success: my instance has been able to catch up the messages. Now, re-enabling presence work as well.

I’m not sure, though, what caused the outage in the first row, since my Synapse instance had been working for quite some time without any issue of this kind.

Thanks for your help.
