### ISSUE TITLE
Move /admin/whois back to /_matrix namespace

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5280]
It's in the spec since forever: https://github.com/matrix-org/matrix-doc/pull/198 / https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-admin-whois-userid

Note: https://github.com/matrix-org/matrix-doc/issues/1474 hints at the section possibly disappearing, but I can't remember what the decision was on this. https://github.com/matrix-org/matrix-doc/issues/1411 wants the "appropriate" APIs to be in the spec (through MSC).

*let the arguments to (not) keep the endpoint in the spec begin*

**Comment by richvdh** [comment]
the `/client/r0` path should still work (for now)?

**Comment by turt2live** [comment]
For now, but not when develop goes mainline

**Comment by richvdh** [comment]
related: #5119

**Comment by richvdh** [comment]
@turt2live I think we agreed this wasn't an issue because the /r0 path isn't going away any time soon. Shout if I'm misremembering.
