### ISSUE TITLE
scripts-dev/check_event_hash.py doesn't work anymore

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5289]
It complains about missing a format_version on the event. See https://github.com/matrix-org/synapse/pull/5281 for a not-too-great fix.

**Comment by richvdh** [comment]
Honestly, I'd be more inclined to get rid of it than fix it. I don't really know what it's supposed to do (it doesn't have a single comment), and it's clearly been forgotten. Is it actually fulfilling a useful purpose?

**Comment by turt2live** [comment]
It was useful to check a hash, but admittedly I've only ever used it twice. Being a dev script, I'd support removing it as it's a clear dust collector

**Comment by richvdh** [comment]
removed in #5548
