### ISSUE TITLE
VOIP calls problem when network changes

### ISSUE THREAD

**Issue by m-shirokov** [matrix-org/synapse#5290]
Hello,
we use VOIP calls functionality in riot.im mobile client
We've found strange behavior , when user changes network on his mobile device 
For example:
1) User 1 calls User 2 (WIFI connected phone) (Audio call) -> they speak -> they close conversation
2) User 2 switches out of WIFI network to 3G network
User 1 calls User 2 (3G connected phone) (Audio call) -> they try to speak, but User 1 can't hear User 2. 
3) User 2 closes riot.im app -> opens it again -> User 1 calls User 2 (3G connected phone) (Audio call) -> they speak. Everyone can hear each other

Seems like there is something like timeout at which client device updates its IP address.
Maybe thi is riot.im mobile client prblem =(

**Comment by neilisfragile** [comment]
Yes please against the appropriate riot repo - I can't do this for you because I don't know if you are using Android or iPhone.
