### ISSUE TITLE
Failure to download image for URL preview should not fail the whole preview

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5298]
Currently Synapse uses OpenGraph to try and find an image. If that fails, it'll pick an image from the DOM. If the image from either fails to download (403, 404, too large, etc) then Synapse should just return a preview without an image. Currently, it instead throws a 502 error instead.

**Comment by akontsevich** [comment]
![изображение](https://user-images.githubusercontent.com/3843657/58655210-47e7a180-8322-11e9-98ab-90c3a20df660.png)
This is preview from Skype, for example. However it is not the only problem: as I mentioned nothing from youtube works, many other sites like this: https://hdrezka-me.me/22654-teni-ischezayut-v-polden-95051943.html, livejournal, etc  - nothing works actually.

**Comment by akontsevich** [comment]
Inserting new youtube link shows preview, however all previous links or on next days links are not previewed. So could be both synapse and client bugs.

**Comment by akontsevich** [comment]
Happen again today for some links, yesterday preview was normal for that link, for example:
https://rezka.ag/series/drama/13646-blokada.html

**Comment by Kevin-Mok** [comment]
I have [a site hosting Twitch emotes](http://twem.tk/) that I used to reference to preview the emote. It was just working the last couple of days but suddenly stopped working. Other previews still work fine, so I'm not sure what happened.

**Comment by akontsevich** [comment]
Issue appeared again. Please fix!

**Comment by akontsevich** [comment]
URL preview is terrible: often show  on strange languages like on screenshot below:
![Screenshot_20191019_192445](https://user-images.githubusercontent.com/3843657/67148248-46ede700-f2a6-11e9-81e6-8430b31959a7.png) - text above should be on Russian. Definitely logic  should be moved to client side!
