### ISSUE TITLE
Room listing & statistics via the Synapse Admin API

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#5326]
We should expose the stats as a part of #4338 in the admin API, so they can be used by things like Modular to provide administrator-level oversight of a server's resources and usage.

**Comment by anoadragon453** [comment]
This is now possible via the [List Room](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#list-room-api) and [Room Details](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#room-details-api) Admin APIs.
