### ISSUE TITLE
If a user offline, why not tell us his "status_msg"?

### ISSUE THREAD

**Issue by calvindc** [matrix-org/synapse#5336]
Line 733 of the file "presence.py", if the user take the initiative to offline,and but his “status_msg” is not null,others won't konw it. After careful consideration I have,you should delete the row 
"msg = status_msg if presence != PresenceState.OFFLINE else None".

**Comment by ShadowJonathan** [comment]
Looks relevant to #2245, would this be a duplicate?

**Comment by clokep** [comment]
Seems to be a duplicate of #2245.
