### ISSUE TITLE
Old, closed rooms reaappear in historical with no way to leave

### ISSUE THREAD

**Issue by the-moog** [matrix-org/synapse#5337]
### Description

Using the Riot/desktop client; Some old, closed test rooms that have no members have just reappeared in 'Historical'.

Usually when you leave a room it goes into historical, then you can press 'forget' to remove the room completely.

Some rooms (tests from ages ago) have just reapeared but there is no way to leave or delete them.  I'd call them 'gost rooms'.  Strangely, going to the room properties and pressing 'Leave room' results in 'No such room'.

Is this intentional behaviour?

### Steps to reproduce
I have no idea how to reproduce this, they just suddenly appeared.

Finally leaving a room should forget it forever, ideally purge it?

### Version information

- **Homeserver**: matrix.bsac240.org.uk

What version of Synapse is running?
Synapse Version: 0.99.5.2
Riot: 1.2.1
mxisd: 1.4.3.2

- **Install method**: 
DEB package

- **Platform**: 
Ubuntu 16.04.6

**Comment by aaronraimist** [comment]
If you are talking about rooms with no forget button that is a Riot bug https://github.com/vector-im/riot-web/issues/9168

**Comment by the-moog** [comment]
I don't think so. They had a forget button, which was pressed at some time in the past, now they are back - like ghosts.

**Comment by cyphar** [comment]
I see this quite often. If you forget the room, it disappears but may reappear again later if you forget a different room (once they re-appear you cannot forget them anymore). Then they possibly disappear (or reappear) after restarts.

**Comment by richvdh** [comment]
I don't think this is an issue any more (or if it is, it's not a synapse bug: afaik Synapse does not report "historical rooms" except at the point you leave). I'm going to close it, but if people are still seeing it, we can reopen.

**Comment by aaronraimist** [comment]
@richvdh Presumably those rooms are also reported when `include_leave` is true 

https://spec.matrix.org/v1.3/client-server-api/#leaving-rooms
> Once a user leaves a room, it will no longer appear in the response to the [/sync](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3sync) API unless it is explicitly requested via a filter with the include_leave field set to true.

**Comment by tommytran732** [comment]
> I don't think this is an issue any more (or if it is, it's not a synapse bug: afaik Synapse does not report "historical rooms" except at the point you leave). I'm going to close it, but if people are still seeing it, we can reopen.

It is still an issue and is likely a synapse bug.Even if you were to install the desktop client on a different machine, those ghost rooms will still show up.
