### ISSUE TITLE
Two-way ignore or block feature

### ISSUE THREAD

**Issue by serra-allgood** [matrix-org/synapse#5365]
Feature request: The addition of a hard block that combines muting the selected user as well as preventing them from seeing my messages. 

Self-moderation is the quickest method of mitigating trolls and harassment. The existing ignore feature prevents the troll from messaging their target, however, the troll can still see messages from the target, allowing them to take screenshots or gathering info to switch to a different channel.

**Comment by reivilibre** [comment]
This would need spec work, which I suspect would raise its own questions; maybe matrix-spec is a better place for this
