### ISSUE TITLE
Deactivation via the admin API doesn't unbind 3pids

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#5375]
`POST /_synapse/admin/v1/deactivate/<user_id>` doesn't unbind the deactivated user's 3PIDs. A fix to this would be to allow for an additional parameter `id_server` in the request's body.

**Comment by turt2live** [comment]
are you sure? I've been getting `id_server_unbind_result: "success"` in all admin-provoked deactivations so far.
