### ISSUE TITLE
Message send time dramatically increased on 1.0.0-rc.1 in large rooms

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5396]
I'm seeing message send times of 1 minute plus in #synapse and similarly sized rooms.

**Comment by turt2live** [comment]
actually I think this might be t2l.io failing to send to matrix.org, and every request on the planet ends up blocking on that timing out.

**Comment by mvgorcum** [comment]
I am seeing increased send time on RC1 on larger rooms, though not of the order of 1 minute. Sending a message in HQ takes me a little less than 10 seconds.

**Comment by turt2live** [comment]
This is a function of https://github.com/matrix-org/synapse/issues/5395 as far as I can tell
