### ISSUE TITLE
Update DockerHub instructions

### ISSUE THREAD

**Issue by FunkenTom** [matrix-org/synapse#5408]
### Description
Instructions on dockerhub seem to be copy-pasted from somewhere else.
These are not related to the docker image at all. 

### Steps to reproduce

- go to https://hub.docker.com/r/matrixdotorg/synapse/

**Comment by neilisfragile** [comment]
Could you be more specific? Which part are you referring to?

**Comment by FunkenTom** [comment]
Actually, it seems like someone already fixed it.
The last time I've visited the docker hub page, all the actually important information like for example the Environment variables were missing and instead of that, it was referring to for example pip.
