### ISSUE TITLE
'apart from guests' doesn't seem to work

### ISSUE THREAD

**Issue by PC-Admin** [matrix-org/synapse#5410]
#perth:perthchat.org is set as 'Anyone who knows the room's link, apart from guests' yet i still get guests coming in all the time.

Seems broken. Going to check my homeserver.yaml now.

Okay guest access is allowed on server "allow_guest_access: True", still seems like a bug that the setting does not override it for a specific room.

**Comment by PC-Admin** [comment]
Ok i set "allow_guest_access: False" then restart synapse and guests are still coming into my rooms, quite strange.

**Comment by richvdh** [comment]
is this still an issue? if so, can you confirm the room id of the affected room, and what its `m.room.guest_access` state is set to?

>Ok i set "allow_guest_access: False" then restart synapse and guests are still coming into my rooms, quite strange.

note that `allow_guest_access` in the synapse config only controls whether new guests can be registered on your server: it has no effect on existing guest users or those on other servers.

**Comment by clokep** [comment]
I'm going to close this -- @PC-Admin if this is still an issue please let us know! Sorry for the really long delay in the initial response.
