### ISSUE TITLE
Federation silently breaks (to users) with error:  "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by unknown-user-9246102101** [matrix-org/synapse#5428]
I am unable to ask for support because my user info returns 401 Unauthorized on REST calls to matrix servers.

I have ran:

# curl 'https://federationtester.matrix.org/api/report?server_name=SNIP'
{
  "WellKnownResult": {
    "m.server": "",
    "result": "No .well-known found"
  },
  "DNSResult": {
    "SRVCName": "",
    "SRVRecords": null,
    "SRVError": {
      "Message": "lookup _matrix._tcp.SNIP on NSSNIP: no such host"
    },
    "Hosts": {
      "SNIP": {
        "CName": "SNIP.",
        "Addrs": [
          "ADDRSNIP"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "ADDRSNIP:8448"
    ]
  },
  "ConnectionReports": {
    "ADDRSNIP:8448": {
      "Certificates": [
        {
          "SubjectCommonName": "CNSNIP",
          "IssuerCommonName": "Let's Encrypt Authority X3",
          "SHA256Fingerprint": "jY8pf8B5rs/f+cmcC8eb9LXmnPvnTw6p574PPV8zAjs",
          "DNSNames": [
            "SNIP",
            "CNSNIP",
            "WWWSNIP"
          ]
        }
      ],
      "Cipher": {
        "Version": "TLS 1.2",
        "CipherSuite": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      },
      "Checks": {
        "AllChecksOK": false,
        "MatchingServerName": true,
        "FutureValidUntilTS": true,
        "HasEd25519Key": true,
        "AllEd25519ChecksOK": true,
        "Ed25519Checks": {
          "ed25519:a_BXbX": {
            "ValidEd25519": true,
            "MatchingSignature": true
          }
        },
        "ValidCertificates": false
      },
      "Errors": [
        {
          "Message": "x509: certificate signed by unknown authority"
        }
      ],
      "Ed25519VerifyKeys": {
        "ed25519:a_BXbX": "HL4rh3GKY4ig6fmgJzkcyO3nq7/0lOVM6Fn6l9eqdoI"
      },
      "Info": {},
      "Keys": {
        "old_verify_keys": {},
        "server_name": "SNIP",
        "signatures": {
          "SNIP": {
            "ed25519:a_BXbX": "ZwUlTbKGuCuczWowwnfX8w5BXrSxlMQEfXd3vgjx8qlKe7tDTxgakpE8pIf/EieT4Zpaj17Uw5hCCbwX+TTDDg"
          }
        },
        "tls_fingerprints": [
          {
            "sha256": "jY8pf8B5rs/f+cmcC8eb9LXmnPvnTw6p574PPV8zAjs"
          }
        ],
        "valid_until_ts": 1560367496623,
        "verify_keys": {
          "ed25519:a_BXbX": {
            "key": "HL4rh3GKY4ig6fmgJzkcyO3nq7/0lOVM6Fn6l9eqdoI"
          }
        }
      }
    }
  },
  "ConnectionErrors": {},
  "Version": {
    "name": "Synapse",
    "version": "0.33.8"
  },
  "FederationOK": false
}

**Comment by aaronraimist** [comment]
See https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst#upgrading-to-v10

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/5429 which has better formatting
