### ISSUE TITLE
wait_for_previous_lookups loops a lot

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#5435]
In the logs I'm seeing a lot of looping:

```
Waiting for existing lookups for [<server>] to complete [loop 1304]
Waiting for existing lookups for [<server>] to complete [loop 1303]
...
```

It looks like it may be racing and just never completing or something? The entire loop happened in a few hundred ms, which feels wrong.

**Comment by richvdh** [comment]
#3825
