### ISSUE TITLE
Problems with the password-reset email feature

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#5444]
I thought it might be worth collecting together the reports we've seen about problems people are having with the password-reset-email feature when they upgrade to Synapse 1.0, so that we can decide what to do about them.

* ~~Docker image doesn't start: #5430 ~~
* ~~More generally, anyone who has set `email` but not `public_baseurl` will find synapse doesn't start~~
* ~~Anyone using a custom `templates_dir` (and has `email` set) will find synapse doesn't start (fixed by https://github.com/matrix-org/synapse/pull/5543)~~
* ~~You now need to `pip install jinja2`: #5431~~
* ~~Poor logging: #5485~~ 
* ~~Requires a template even when disabled: #5496 (?)~~

**Comment by richvdh** [comment]
Another one: the changelog isn't terribly helpful:

"Add ability to perform password reset via email without trusting the identity server. (#5377)": fails to mention that your server will lose the ability to do password resets unless you reconfigure it somewhat.

**Comment by anoadragon453** [comment]
> More generally, anyone who has set email but not public_baseurl will find synapse doesn't start

This is intentional, but I do see it as a problem in the context of the Docker image. Hopefully we can fix that separately.

**Comment by richvdh** [comment]
> More generally, anyone who has set `email` but not `public_baseurl` will find synapse doesn't start

We decided this wasn't a big problem, but did decide to make the error message clearer (#5616)

**Comment by richvdh** [comment]
all done! thanks @anoadragon453
