### ISSUE TITLE
Sending ACL that denies matrix.org bans all homeservers

### ISSUE THREAD

**Issue by BurnyBoi** [matrix-org/synapse#5468]
### Description

I sent an ACL to deny matrix.org, and this ended up banning all servers from participating. It seems to cause "allow: []" to get added to the event, which causes every server to be banned. 

### Steps to reproduce

In Riot, I sent the following state event from dev tools:

```
{
    "content": {
        "allow": [
            "*"
        ],
        "allow_ip_literals": false,
        "deny": [
            "matrix.org"
        ]
    },
    "type": "m.room.server_acl"
}
```

I then see the following in the chat in Riot: "<me> set server ACLs for this room: 🎉 All servers are banned from participating! This room can no longer be used."

If I look at the m.room.server_acl in dev tools, I see this:
```
{
  "type": "m.room.server_acl",
  "sender": "<my mxid>",
  "content": {
    "content": {
      "allow": [
        "*"
      ],
      "allow_ip_literals": false,
      "deny": [
        "matrix.org"
      ]
    },
    "type": "m.room.server_acl",
    "allow": []
  },
  "state_key": "",
  "origin_server_ts": 1560649579360,
  "unsigned": {
    "age": 80
  },
  "event_id": "<event_id>",
  "room_id": "<room_id>"
}
```
(note the ""allow": []" added into the acl.) 

### Version information

This is happening on a self-hosted synapse 1.0. I am able to reproduce this in a new room every time.

**Comment by aaronraimist** [comment]
You are entering it in wrong and ending up with content inside of content.

```
  "content": {
    "content": {
      "allow": [
        "*"
      ],
      "allow_ip_literals": false,
      "deny": [
        "matrix.org"
      ]
    },
    "type": "m.room.server_acl",
    "allow": []
  },
```

Riot should look like this:
![Screen Shot 2019-06-15 at 9 07 02 PM](https://user-images.githubusercontent.com/5855073/59558157-87182280-8fb1-11e9-98b0-06ad9463ae1f.png)

**Comment by BurnyBoi** [comment]
Thank you. I just copied what was in the Client-Server API documentation. I'll remember this going forward!
