### ISSUE TITLE
Purge API - 404 - No Such Resource

### ISSUE THREAD

**Issue by T0MuX** [matrix-org/synapse#5473]
Hi, I'm trying to do some cleaning into the database but the given method doesnt work on my homeserver. I tried the syntax with many different rooms (room_id), with many different events (event_id) and I always get this error message : "404 - No Such Resource". However, I just copy/paste the information from the "View Source" section from the eventi itself into Riot. And my user is admin as well.

### Steps to reproduce

- choose an event in a room, clic on menu, "View source"
- get the event_id, the room_id and the token of actual user (need an admin user)
- run this command on the homeserver itself : 
`curl -X POST 'http://localhost:8008/_synapse/admin/v1/purge_history/<room_id>/<event_id>?access_token=<token>'`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: mux.re

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.99.1.1-1

- **Install method**: classical package management method (pacman on archlinux)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Archlinux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

My server is a VPS hosted at OVH. I don't use container.

**Comment by babolivier** [comment]
Hey, `/_synapse/admin` paths for admin APIs only exist since Synapse 0.99.4 (look for `/_synapse` in the changelog here: https://github.com/matrix-org/synapse/blob/master/CHANGES.md).

Before that, the paths for these endpoints were under `/_matrix/client/r0/admin`, so the right curl command line for your use case would be:

```
 curl -X POST 'http://localhost:8008/_matrix/client/r0/admin/v1/purge_history/<room_id>/<event_id>?access_token=<token>'
```

**Comment by T0MuX** [comment]
Yes, thank you !
It worked directly. :) 

Now I guess I have to update my Synapse.. lol.
