### ISSUE TITLE
/admin/users_paginate is pointless and should be merged into /admin/users

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#5494]
#1784 introduced a (barely-functional, cf #3666) admin API called `/admin/users_paginate`. Apart from other problems with this API (#2522, lack of documentation), the whole thing seems pointless. How is it different to `/admin/users` ?

**Comment by awesome-manuel** [comment]
The pagination API is not 100% compatible to the normal users API. Pagination returns a list of users and the total amount as a separate field whereas the users API just returns a list.

**Comment by richvdh** [comment]
fixed by #5925
