### ISSUE TITLE
Synapse requires a password reset template even if the feature is disabled

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#5496]
If Synapse is configured with `trust_identity_server_for_password_resets` it will still require a password reset email template before starting up (even though it shouldn't need one).

**Comment by anoadragon453** [comment]
Are you sure `trust_identity_server_for_password_resets` wasn't just accidentally put outside of the `email:` config block?

**Comment by babolivier** [comment]
Turns out that was the issue.
