### ISSUE TITLE
Server admins should be able to request 3PIDs for users

### ISSUE THREAD

**Issue by rxl881** [matrix-org/synapse#5497]
Currently 3PID mappings can only be requested (from Synapse or the identity server) by the related users (accounts). It would be very useful to open this up to server administrator accounts so that they can use the APIs to see registered user email addresses.

**Comment by lampholder** [comment]
I can't see any problem with this from a GDPR perspective, seeing as a server admin role is no different from a somebody with direct access to the database.

Obviously, anyone maintaining their own homeserver(s) or using a homeserver provided by a third party should employ information security best practice of 'least privilege' to ensure access to this API (and direct access to the db) is restricted to a minimal set of individuals.

**Comment by dklimpel** [comment]
see also: #6769

**Comment by dklimpel** [comment]
IMO this is solved and can be closed.

**Comment by clokep** [comment]
I agree, looks like this is already possible!
