### ISSUE TITLE
now LL is in CS 0.5, we should remove it from unstable-features in versions?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5528]

**Comment by turt2live** [comment]
reliant on https://github.com/vector-im/riot-web/issues/9966

**Comment by richvdh** [comment]
> reliant on vector-im/riot-web#9966

does this mean that we can never remove it, for fear of breaking old versions of riot?

**Comment by turt2live** [comment]
No, it means we should get our ducks in a row and fix riot, wait X number (where X is small) Riot release cycles, then remove it from synapse.

The correct answer would have been Riot being proactive on this.

**Comment by turt2live** [comment]
ftr, Riot's fix landed today which means it should land in a release in ~2 weeks. I would recommend waiting ~8 weeks before removing it from Synapse, but I'm also not a release coordinator.

**Comment by neilisfragile** [comment]
set a reminder 8 weeks from now

**Comment by turt2live** [comment]
keywords: lazy-loading lazy loading

**Comment by richvdh** [comment]
done by #6877.
