### ISSUE TITLE
synapse allows you to omit the `from` param to /messages, which is non-spec-compliant

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#5538]
Per https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-rooms-roomid-messages, `from` is mandatory, but apparently riot-android does not (always?) set it.

**Comment by ShadowJonathan** [comment]
(Updated spec link, for reference: https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-rooms-roomid-messages)

**Comment by deepbluev7** [comment]
Duplicate of #1445, I'd say.

**Comment by clokep** [comment]
See also [MSC3567](https://github.com/matrix-org/matrix-doc/pull/3567) which looks to standardize the behavior in Synapse.

**Comment by clokep** [comment]
This is now spec compliant.
