### ISSUE TITLE
Issue federating with matrix.org

### ISSUE THREAD

**Issue by JadedCtrl** [matrix-org/synapse#5549]
For some reason, federation doesn't seem to happen with `matrix.org`. No-one on that homeserver can be reached, and no-one on it can reach my homeserver— but every other homeserver (disroot, ponies.im, etc.) seems to work fine. It looks like this has been going on since before the upgrade to 1.0.

The only section of my log that I thought looked relevant is here:

`2019-06-24 05:03:51,215 - synapse.crypto.keyring - 603 - WARNING - PUT-1829 - Key lookup failed from 'matrix.org': Failed to connect to remote server`

That's the only failure I could find in relation to matrix.org— and there are some successful HTTP requests:

`2019-06-24 05:19:36,702 - synapse.http.client - 298 - INFO - phone_stats_home-0 - Received response to PUT https://matrix.org/report-usage-stats/push: 200`

It looks like this might be related to [this issue](https://github.com/matrix-org/synapse/issues/5454), but my logs don't show anything like what that person's do, and the daemon itself doesn't stdout any errors, like theirs does.

Though I did try what [erickjohnston suggested](https://github.com/matrix-org/synapse/issues/5454#issuecomment-504021453), but I'm not sure if the output's of any use.

```
psql (10.5)
Type "help" for help.

synapse=> \d current_state_events
        Table "public.current_state_events"
  Column   | Type | Collation | Nullable | Default
-----------+------+-----------+----------+---------
 event_id  | text |           | not null |
 room_id   | text |           | not null |
 type      | text |           | not null |
 state_key | text |           | not null |
Indexes:
    "current_state_events_event_id_key" UNIQUE CONSTRAINT, btree (event_id)
    "current_state_events_room_id_type_state_key_key" UNIQUE CONSTRAINT, btree (room_id, type, state_key)
```

The homeserver.log is [here](https://coinsh.red/u/2019-06-24-homeserver.log.truncated.txt)

### Version information
- **Homeserver**:  matrix.eunichx.us
- **Version**: 1.0
- **Install method**:  pip3.6
- **Platform**:  OpenBSD 6.4, used with PostgreSQL

**Comment by richvdh** [comment]
your SSL certificate is invalid: https://federationtester.matrix.org/#matrix.eunichx.us. There might be other problems too, but nothing is going to work reliably until you get that fixed.

Please see https://github.com/matrix-org/synapse/blob/master/docs/MSC1711_certificates_FAQ.md.

I suggest joining `#synapse:matrix.org` (from a matrix.org account if necessary), which is a much better place to get support.
