### ISSUE TITLE
Media repo doesn't treat image/jpg as an image

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5554]
image/jpeg is fine though

**Comment by kyrisu** [comment]
Also worth mentioning for posterity that sending a POST request with `curl` (and probably other tools / libraries) without specifying `Content-Type` will not work as it will assume
```
Content-Type: application/x-www-form-urlencoded
```
and won't generate thumbnails for the image (event if the filename has an image extension like *.jpg).

**Comment by turt2live** [comment]
`image/jpg` isn't real: https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg
