### ISSUE TITLE
Synapse starting issue

### ISSUE THREAD

**Issue by shibinmp3** [matrix-org/synapse#5571]
**Hai, when I give synctl start command it is showing errors as follows, I am using Centos7. and I am new to Linux and python. please tell what did i miss. thanks**

(synapse) [root@s148-72-210-106 synapse]# synctl start
bash: /opt/synapse/bin/synctl: Permission denied
(synapse) [root@s148-72-210-106 synapse]# sh synctl start
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
/opt/synapse/bin/synctl: line 29: from: command not found
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
/opt/synapse/bin/synctl: line 33: SYNAPSE: command not found
/opt/synapse/bin/synctl: line 35: GREEN: command not found
/opt/synapse/bin/synctl: line 36: YELLOW: command not found
/opt/synapse/bin/synctl: line 37: RED: command not found
/opt/synapse/bin/synctl: line 38: NORMAL: command not found
/opt/synapse/bin/synctl: synctl: line 41: syntax error near unexpected token `('
/opt/synapse/bin/synctl: synctl: line 41: `def pid_running(pid):'
(synapse) [root@s148-72-210-106 synapse]#

**Comment by richvdh** [comment]
synctl is a python script, not a shell script, so you can't run it with `sh`.

it should have the executable bit set, so `synctl start` should work. you haven't completed the issue report template, so we don't know how you installed it and why it doesn't have this set. you might be able to just do `sudo chmod +x /opt/synapse/bin/synctl`, but I suspect that your installation is somehow broken and you will have other problems.

Also you appear to be trying to run synapse as `root`, which is a *terrible* idea.

Anyway, this is not the place to ask for support. Please see https://github.com/matrix-org/synapse/blob/master/.github/SUPPORT.md.
