### ISSUE TITLE
Populate m.room.aliases when /createRoom is called with a room_alias_name

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5578]

**Comment by t3chguy** [comment]
This seems to already be the case:

`await mxMatrixClientPeg.matrixClient.createRoom({room_alias_name: "testing-room-alias-name"});`
![image](https://user-images.githubusercontent.com/2403652/60766057-bc3cff80-a09b-11e9-9804-2811afaa15e4.png)
![image](https://user-images.githubusercontent.com/2403652/60766059-bfd08680-a09b-11e9-9f2d-08b4049e5d29.png)

**Comment by richvdh** [comment]
yeah, I think this works. @turt2live please reopen if you have a repro case!
