### ISSUE TITLE
room upgrade doesn't transfer non-standard power structure

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#5580]
### Description

A room with nonstandard power structure cannot be upgraded, since the power levels are not moved over. In fact, upgrade results:

```json
{
    "errcode": "M_FORBIDDEN",
    "error": "You don't have permission to add ops level greater than your own"
}
```

### Steps to reproduce

- crate a room with various levels above 100, with owners and members above, too.
- room/.../upgrade  (I have used from v5 to v5)
- kaboom

### Version information

- **Homeserver**:  grin.hu
- **Version**: 1.0.0
- **Install method**: self-hacked debian package
- **Platform**: debian/buster

**Comment by richvdh** [comment]
> crate a room with various levels above 100, with owners and members above, too.

How do you do this?

**Comment by babolivier** [comment]
> How do you do this?

Via the `initial_state` param in the `/createRoom` request (I just successfully granted myself PL 500 in a new room that way).

**Comment by grinapo** [comment]
Related: https://github.com/matrix-org/matrix-doc/issues/2149

@babolivier I have used `power_level_content_override` but it's the same.

**Comment by babolivier** [comment]
Hah, yeah, I forgot that was a thing. Anyway, yes, the max PL is overridable at room creation time.

**Comment by richvdh** [comment]
I'm not convinced this is worthy of a 'security' label

**Comment by anoadragon453** [comment]
Should be fixed by https://github.com/matrix-org/synapse/pull/6237
