### ISSUE TITLE
debian packages get downgraded when you update to buster

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#5590]
... because you end up picking up the matrix-synapse 0.99.x from buster instead of the matrix-synapse virtual package from us. The solution to this is probably to fix #5215

**Comment by zerobulfa** [comment]
Great:

`synapse[25060]: twisted: [] ValueError: Cannot use this database as it is too new for the server to understand`

matrix-synapse-py3 = python 3.5 - Buster = 3.7

any tipps?

greetings,
zb

**Comment by neilisfragile** [comment]
Your server and db are now out of sync because the server has downgraded and the db schema has not - the best thing you can do is upgrade the server to the version you had previously (or better the latest version).

**Comment by richvdh** [comment]
> matrix-synapse-py3 = python 3.5 - Buster = 3.7

no, matrix-synapse-py3 uses the same python as the OS. the buster builds of matrix-synapse-py3 therefore use python 3.7.

> any tipps?

`apt install matrix-synapse-py3`

**Comment by zerobulfa** [comment]
> Your server and db are now out of sync because the server has downgraded and the db schema has not - the best thing you can do is upgrade the server to the version you had previously (or better the latest version).

I don't downgrade from Buster

> > matrix-synapse-py3 = python 3.5 - Buster = 3.7
> 
> no, matrix-synapse-py3 uses the same python as the OS. the buster builds of matrix-synapse-py3 therefore use python 3.7.
> 
> > any tipps?
> 
> `apt install matrix-synapse-py3`

matrix-synapse-py3 : depends on: python3.5 but is not installable

**Comment by richvdh** [comment]
check your apt-sources is configured to use the right distribution. Please can we take this out of this issue; it's off-topic.

**Comment by zerobulfa** [comment]
yeah ok, sry it`s offtopic - delete if u wish. 

will use email

greetings,
zb

**Comment by richvdh** [comment]
buster no longer has a `matrix-synapse`, so I don't think this is an issue any longer. #5215 still needs fixing though.
