### ISSUE TITLE
Aggregations: include sender and origin_server_ts in m.replace aggregations

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#5598]
To be able continue aggregating edits based on an already aggregated event, and to show the tooltip *(Person) edited at hh:mm*, we need the sender and origin_server_ts of the replacing event to be included in the aggregation put in m.relations of the original event when aggregation server-side.

See https://github.com/vector-im/riot-web/issues/9834 and https://github.com/matrix-org/matrix-doc/pull/1849#discussion_r287315866

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/5613
