### ISSUE TITLE
SAS verification requests can take up to 30s to arrrive

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#5600]
i've seen this since the first demos at FOSDEM - on all platforms, it seems that it can take up to 30s for a SAS verif request to be received by the target client. It's like /sync doesn't get woken up. I've seen it when talking to both Riot/Web and RiotX - I don't think it's just matrix.org being slow

**Comment by uhoreg** [comment]
dup of https://github.com/matrix-org/synapse/issues/5148
