### ISSUE TITLE
cURL timeout when sending requests from a client server with a local IP address to a Matrix Synapse server with a local IP address

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#5635]
I have the following setup:

-- 1x client server (https://www.mydomain.com) which has a local (192.168.x.x) and a public IP address.
-- 1x Matrix Synapse v1.1.0 server (https://matrix.mydomain.com) which has a local (192.168.x.x) and a public IP address.
-- Internal network communication/routing is done on the basis of the local IP addresses (shown in the homeserver.log).
-- Reverse Apache proxy according to this https://github.com/matrix-org/synapse/blob/master/docs/reverse_proxy.rst
-- `bind_addresses: ['127.0.0.1']` and `x_forwarded: true` for port 8008 are set in homeserver.yaml.

Issue: 
-- Every cURL request from the client server to the Matrix Synapse server results in a cURL timeout.
-- Every cURL (e.g. /login) requests are processed correctly by Synapse which is shown in the log.
-- However, no value is returned.
-- Requests made by a Riot Web (v1.2.2, with a public IP) work fine.

Question:
-- Does Synapse have an issue with handling local IPs in a local network?

**Comment by richvdh** [comment]
Question:
-- Does Synapse have an issue with handling local IPs in a local network?

Answer: not that we are aware of.

This sounds like misconfiguration rather than a bug. If you'd like help setting up your Synapse installation correctly, #synapse:matrix.org is the place to get support. If you can find more evidence of a bug, feel free to open an issue here.

**Comment by menturion** [comment]
@richvdh 

**Do you know any misconfiguration that results into the above described behaviour?**

I have already discussed this issue in the Matrix Admin community w/o any result.
Currently, I am not aware of any misconfiguration. I think that this issue has been closed quite too fast.

**Comment by menturion** [comment]
@richvdh

Just want to let you know that you were right in your assumption.
Is was a max child processes issue with Nginx PHP-FPM.
