### ISSUE TITLE
Homeserver configuration options to tweak user directory behaviour

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#5648]
I'd like an option, perhaps in homeserver.yaml, to provide a list of regex patterns for the homeserver to exclude from user directory search results.

**Comment by richvdh** [comment]
my feeling is that if a user's displayname shouldn't be presented in the directory, we probably don't want it in rooms either?

**Comment by neilisfragile** [comment]
We should consider if a config regiex is the best approach, or if an API removing specific usernames addresses the same problem?

**Comment by turt2live** [comment]
could also shove this through the spam checker module to let arbitrary decisions to be made.

**Comment by richvdh** [comment]
I'm happy so long as it isn't in homeserver.yaml (which would require redeploying from ansible and restarting synapse)

**Comment by clokep** [comment]
We had a brief discussion about this issue:

> It's to help us with abuse management and essentially we need to be able to block certain user ids from appearing in the directory
> there are a few ideas on how to do this, but we want to avoid any in the homeserver.yaml
> The most promising approach is to extend our current spam checking module - this is part of broader tool called mjolnir. 
> But I think if you can get it to do two things then the issue will be solved:
> * Allow for give regexes to be excluded (I think mjolnir acts on globs)
> * Allow for specific users to be excluded
>
> This will need to apply to the mxid and display name.

I think the first steps here are to understand how spam checking works in Synapse (and Mjolnir) and the connection between those. I'll put some notes in here as I go through it.

**Comment by clokep** [comment]
From taking a look at [Mjolnir](https://github.com/matrix-org/mjolnir/blob/master/synapse_antispam/) and the [spam check code in Synapse](https://github.com/matrix-org/synapse/blob/f0561fcffd172cb0dfe035dcc78f51bdd451c010/synapse/events/spamcheck.py). I believe the work would entail:

1. Synapse:
    1. Extended the interface of `SpamChecker` to include a new method
        1. (`user_appears_in_directory_results` or something, it would take a user ID and display name as parameters)
        2. To be backwards compatible we could have the `SpamChecker` not require this method on the actual spam checking implementation (this actually might be a nice feature for all of the spam checking methods so you don't end up with pass-through code, e.g. [this in Mjolnir](https://github.com/matrix-org/mjolnir/blob/5d8fea07fc2aa70d2a58f21e0b675bf439d0beb5/synapse_antispam/mjolnir/antispam.py#L109-L116)).
    2. Modify `UserDirectoryHandler` to use the above method to filter results before returning from `search_users` (this might be tricky based on the handling of `limit`, unsure).
2. Mjolnir:
    1. Extend the code that builds the ban list to handle a new type (see [`build`](https://github.com/matrix-org/mjolnir/blob/5d8fea07fc2aa70d2a58f21e0b675bf439d0beb5/synapse_antispam/mjolnir/ban_list.py#L32-L73)).
    2. Add the implementation of the method which Synapse will call.

Unclear bits to me:
* Do the commands to modify the banlist need to be modified? (I haven't looked deeply into what commands exist already, will need to talk to @lampholder about what his expected experience is here.)
* Does it make sense to store this data as events, like the ban list is stored?
* Does any of this need any sort of spec changes? (In particular I saw event types of both `org.matrix.room.rule` and `m.room.rule`)

Overall, this seems pretty doable, will be curious for feedback from @richvdh and @turt2live about the architectural changes to Synapse & Mjolnir.

@lampholder would interacting with this as part of Mjolnir meet your needs? Would you expect the same user ban list to be applied or would it need to be a separate list?

**Comment by turt2live** [comment]
Mjolnir's role in this is probably best tracked elsewhere imo. The Synapse side really only needs to worry about supplying the function and calling it at the right time - how the spam checker deals with that is its problem.

To actually answer your questions though:
* Do the commands to modify the banlist need to be modified?
  * No, the commands stay the same.
* Does it make sense to store this data as events, like the ban list is stored?
  * Probably not? 
* Does any of this need any sort of spec changes?
  * No, Mjolnir is already handling the spec changes. And again, Synapse shouldn't concern itself with the details of how Mjolnir operates.

Mjolnir's changes would be minimal. Synapse's changes would also be relatively minimal and generic.

**Comment by clokep** [comment]
> Mjolnir's role in this is probably best tracked elsewhere imo. The Synapse side really only needs to worry about supplying the function and calling it at the right time - how the spam checker deals with that is its problem.

Sure, but I think it is important to see the whole picture to ensure that the architecture will work. The actual work for Mjolnir will happen in the other repository.

> To actually answer your questions though:
> 
>     * Do the commands to modify the banlist need to be modified?
>       
>       * No, the commands stay the same.

Does the current banlist work fully on MXIDs? I'm unsure the current design is flexible enough to also handle display names, which seems to be a requirement for this work.

>     * Does any of this need any sort of spec changes?
>       
>       * No, Mjolnir is already handling the spec changes. And again, Synapse shouldn't concern itself with the details of how Mjolnir operates.

I'm a bit confused by this response. I agree that Synapse shouldn't be concerned about how Mjolnir operates, but I was asking about the Matrix specification (https://matrix.org/docs/spec/). Mjolnir uses events under the `m.room` namespace, which I believe is reserved for events defined in the spec itself.

This question might be a bit obsolete anyway if we're just applying the same banlists to a new endpoint (user directory search).

**Comment by clokep** [comment]
Had a good conversation with @lampholder about this, so I think I understand the background a bit better now. A few results from it were:
* Glob based filtering should work fine.
* Display names are definitely important to filter (as well as MXIDs).

So I think my sticking point right now is the display name part in Mjolnir and if any changes are necessary in there to handle this.

**Comment by clokep** [comment]
I believe this work is done!
