### ISSUE TITLE
riot not showing full size avatar after upgrading riot web and matrix server to latest stable version

### ISSUE THREAD

**Issue by akhilin** [matrix-org/synapse#5663]
matrix version : 1.0.0
riot web: 1.2.2
when clicked on avatar image..showing this one
![image](https://user-images.githubusercontent.com/21128035/61031046-5a063680-a3dc-11e9-94d9-93b41b14d42a.png)

but it's working when re-uploaded avatar.

#vector-im:riot-web
https://github.com/vector-im/riot-web/issues/10133

**Comment by richvdh** [comment]
How did you upgrade synapse? did you somehow delete your local media store?

**Comment by akhilin** [comment]
no.
I checked the database for avatar url when I loaded it its showing full avatar image in browser.
And also avatars loading on ios app.

**Comment by richvdh** [comment]
> only riot web, not showing avatars.

sounds like a riot-web problem then. It might be useful to tell them what URL riot-web is using, and what you think it should be using.
