### ISSUE TITLE
Specific login error message for deactivated users

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#5668]
If a user has been explicitly deactivated they find themselves logged out and unable to log back in other than to be told their password is unrecognised.

To solve this add a flag to users table on deactivation and then return the appropriate error response when the deactivated user tries to log back in so they at least know what has happened.

**Comment by anoadragon453** [comment]
> add a flag to users table on deactivation

We already seem to do this part. https://github.com/matrix-org/synapse/blob/80cc82a4459e4bbc926c6a57ae5e29278c2f9439/synapse/storage/registration.py#L1301-L1307

**Comment by neilisfragile** [comment]
IRL: We will use the deactivate column for a generic 'Login failed, this account has been deactivated.' when someone attempts to login into a deactivated account.

**Comment by anoadragon453** [comment]
This has been fixed in https://github.com/matrix-org/synapse/pull/5674 and https://github.com/matrix-org/synapse/pull/5686 by creating a new error code, `M_USER_DEACTIVATED`, which clients can use to detect when the user they're attempting to authenticate as has been deactivated.
