### ISSUE TITLE
[Feature] Libravatar / ivatar

### ISSUE THREAD

**Issue by jkhgvfgvsth** [matrix-org/synapse#5670]
**Feature**: Support Libravatar / ivatar

I'm not sure if this is the right place to put this, if it is incorrect (moderators) feel free to move this.

_________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by reivilibre** [comment]
would likely need to be done in clients by fetching the correct avatar at registration time and handing it over; HSes can't generally see the e-mail addresses of remote users.
