### ISSUE TITLE
new Synapse requires tls certificate file

### ISSUE THREAD

**Issue by cybermcm** [matrix-org/synapse#5671]
### Description

creating new container requires a tls.key file although tls is set to false

### Steps to reproduce

following the instructions on hub.docker.com, first generate config file and then startup results in 
`synapse.config._base.ConfigError: Error accessing file '/data/xxx.net.tls.key' (config for tls_private_key_path): No such file or directory`

duplicate to https://github.com/matrix-org/synapse/issues/4554 but not solved in my point of view

### Version information

If not matrix.org:

1.1.0

- **Install method**: 

docker-compose

- **Platform**: 

Debian with Docker version 18.09.7, build 2d0083d

**Comment by cybermcm** [comment]
error message due to false environment vars (env vars for generating and running are different)
my fault

**Comment by alecdwm** [comment]
Also ran into this problem.  
For future reference, when running the official docker image, make sure you don't include the `SYNAPSE_SERVER_NAME` environment variable or your configuration will be shadowed by one based on environment variables:

> Legacy dynamic configuration file support
> 
> For backwards-compatibility only, the docker image supports creating a dynamic configuration file based on environment variables. This is now deprecated, but is enabled when the SYNAPSE_SERVER_NAME variable is set (and generate is not given).
> 
> To migrate from a dynamic configuration file to a static one, run the docker container once with the environment variables set, and migrate_config commandline option. For example:
> 
> docker run -it --rm \
>     --mount type=volume,src=synapse-data,dst=/data \
>     -e SYNAPSE_SERVER_NAME=my.matrix.host \
>     -e SYNAPSE_REPORT_STATS=yes \
>     matrixdotorg/synapse:latest migrate_config
> 
> This will generate the same configuration file as the legacy mode used, but will store it in /data/homeserver.yaml instead of a temporary location. You can then use it as shown above at Running synapse.
