### ISSUE TITLE
Cache version string in versionstring.py

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#5672]
### Description

https://github.com/matrix-org/synapse/blob/develop/synapse/federation/transport/server.py#L773

Synapse does not cache it's version string on startup, causing requests to that endpoint to cause 4 git processes to be spawned, even if the code is not deployed via git.

https://github.com/matrix-org/synapse/blob/develop/synapse/util/versionstring.py

While we're at it, we probably don't need to do that caching at each of the places get_version_string is called - perhaps that function saves the response forever (during the lifetime of the python process), this will save us checking git multiple times on startup - we just need to try it that 4 times and that's it.

We also tack on the "Synapse/" in lots of the places that we do this as well, maybe just do that in one place too.

### Version information

- **Version**: develop

- **Install method**: 
git clone

- **Platform**: 
linux

**Comment by richvdh** [comment]
This is actually using a non-trivial amount of cpu time on the master. Given how easy it is to fix, we should do it asap
