### ISSUE TITLE
Optional integration with systemd sd_notify

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#5676]
**Description:**

Using systemd to control synapse is mostly working, however we are currently unable to manage multiple workers in a 100% reliable fashion, as we cannot reliably tell when the master process has finished starting up compared to the worker processes. 

It would be good to integrate with sd_notify such that if configured, synapse could pass READY=1 to systemd on a successful startup. 

https://www.freedesktop.org/software/systemd/man/sd_notify.html

While working on this we could also provide the STATUS= to provide feedback on current state of synapse while starting [eg, if long-running background processes are going, such as DB re-indexing]

**Comment by richvdh** [comment]
>  we cannot reliably tell when the master process has finished starting up compared to the worker processes.

I don't think this matters from the point-of-view of starting the workers?

**Comment by michaelkaye** [comment]
> > we cannot reliably tell when the master process has finished starting up compared to the worker processes.
> 
> I don't think this matters from the point-of-view of starting the workers?

OK; i thought this was why we needed to use synctl at the moment; we need to wait for it to return to ensure that the target has actually started before moving onto dependent tasks - that might have been a bug that we fixed at some point

**Comment by richvdh** [comment]
Yes. The main reasons for synctl afaik are:
* it fiddles with env vars in a way that is tiresome to replicate in systemd
* feedback as to whether the process has successfully started (which this issue would fix)

**Comment by michaelkaye** [comment]
Ah, without synctl, you can use `Type=Simple` and if the process terminates then the service is marked as down; which is the same as this would do - the sending of the notify is an asychronous process, so you still wouldn't get told it failed to start. I think.

**Comment by Valodim** [comment]
I would also welcome this. Python libraries exist for sdnotify, so this should boil down to a single call sending off READY=1 once synapse is up and running.

This will come in handy to make sure appservices launched "after" synapse by systemd will find synapse actually fully initialized, and don't have to connect and fail a couple of times before synapse is done.

**Comment by richvdh** [comment]
fixed by #5676
