### ISSUE TITLE
Stop telling about `Consumer asked us to stop producing`

### ISSUE THREAD

**Issue by jo-so** [matrix-org/synapse#5682]
### Description

I'm having many of these warnings in my log:
```
Jul 14 15:11:38 synapse-media[14028]: synapse.rest.media.v1._base: [GET-546] Failed to write to consumer: <class 'Exception'> Consumer asked us to stop producing
```

Proposed patch: [0001-rest-media-Don-t-complain-about-stopped-request.patch.txt](https://github.com/matrix-org/synapse/files/3389986/0001-rest-media-Don-t-complain-about-stopped-request.patch.txt)

### Version information

- **Version**: 1.0.0-2
- **Install method**: `apt install matrix-synapse`
- **Platform**: Debian/stable

**Comment by richvdh** [comment]
if you've got a proposed patch, please send it as a PR.

In this case, I don't think it's the right fix to the problem. We shouldn't be fixing the symptoms, but rather understanding what the error means and fixing it at source.

**Comment by richvdh** [comment]
related to #4661, though it may be a different instance.
