### ISSUE TITLE
Room Stats: `state_events` and `current_state_events` are never updated following the initial background update.

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#5690]
Clarification: `state_events` & `current_state_events` refer to the columns in `room_stats`

`state_events` ~~should be relatively trivial to update.~~ is going to be dumped.

`current_state_events` may be slightly trickier – ah, but I guess I can increment if the state event doesn't have a previous event – maybe not trickier after all.

**Comment by richvdh** [comment]
is this not the same as #5624?

**Comment by reivilibre** [comment]
> is this not the same as #5624?

No, #5624 concerns rooms missing stats altogether (no rows).

This concerns the fact that stats will not be incrementally updated properly for rooms which are properly registered in the room stats system (`{current_,}state_events` not updated to reflect actual value)

**Comment by reivilibre** [comment]
Note that it has been decided to dump `state_events` as it is not a statistic with known uses right now – and it is slightly troublesome to track. So this issue now focusses on `current_state_events` and will drop `state_events`.

**Comment by erikjohnston** [comment]
Fixed in #5971
