### ISSUE TITLE
Consider moving HHS/DINSIC releases out of this repository

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5696]
It's just noise in #synapse, #matrix-news, and the releases page.

**Comment by richvdh** [comment]
@hawkowl is planning to merge the hhs branch into develop, so those will go away soon I *hope*.

Agreed that it would be good to move dinsic out. @babolivier how about it?

**Comment by babolivier** [comment]
> Agreed that it would be good to move dinsic out. @babolivier how about it?

Makes sense. I guess having a Synapse repo dedicated to dinsic on gitlab.matrix.org would be the right way to do that?

**Comment by babolivier** [comment]
DINSIC has been moved to https://github.com/matrix-org/synapse-dinsic.

@richvdh @hawkowl did something happen with the hhs branch regarding this point? I haven't been following things very closely on this side I'm afraid.

**Comment by richvdh** [comment]
the hope is still for the hhs branch to get merged back into mainline.

**Comment by babolivier** [comment]
Alright, then I'll move the card back into "To Do" and will assign hawkie since she has the conn on that afaik.

**Comment by babolivier** [comment]
As per discussion, and since there's already a plan for the hhs branch, I'll close this issue instead.

**Comment by babolivier** [comment]
@hawkowl just pointed out that the HHSs are already running off mainline now, which I wasn't aware of, so yay!
