### ISSUE TITLE
I have a  problem  when i install synapse

### ISSUE THREAD

**Issue by bluetianx** [matrix-org/synapse#5698]
When i excute commad that pip3 install matrix-synapse-1.1.0.tar.gz, I have a  problem that 
```
Command "/root/synapse/env/bin/python3 /root/synapse/env/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-keewdkxz/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.8.0 wheel" failed with error code 1 in None

```

Addtional:
OS: centos 7
python : Python 3.7.4
pip3   :pip 19.0.3 from /usr/local/python3/lib/python3.7/site-packages/pip (python 3.7)
pip3 list : 
Package    Version
---------- -------
pip        19.0.3 
setuptools 40.8.0 
wheel      0.33.4 
overlay    1.1.0

**Comment by neilisfragile** [comment]
This doesn't seem like a Synapse issue, but if you need support please ask in #synapse:matrix.org
