### ISSUE TITLE
Room version upgrade undocumented

### ISSUE THREAD

**Issue by nja0087** [matrix-org/synapse#5709]
There is currently no documented way to upgrade a room version (typically 1 -> 4 as of writing) which is the new default room version for synapse. This ideally should be in the upgrade notes for Synapse.

**Comment by richvdh** [comment]
The upgrade call is part of the Client-Server API: https://matrix.org/docs/spec/client_server/r0.5.0#id205

**Comment by neilisfragile** [comment]
At this point we are not actively encouraging mods to upgrade their rooms unless they specifically need to (generally only applies to large public rooms). 

Rationale is that we are still ironing out some bugs in the upgrade process and we expect further room versions.

**Comment by PC-Admin** [comment]
an idiot proof version would be appreciated x)

**Comment by nja0087** [comment]
For what it's worth for others reading, I found this purely by chance; you can do `/upgraderoom 4` in riot-web to upgrade a room...

**Comment by PC-Admin** [comment]
@nja0087 you the real MVP here

**Comment by bbigras** [comment]
> You'll also find support for rooms v6. v6 contains some small but important changes to improve the security of the room model. As with all room version upgrades we can't switch to v6 as the default version immediately since we need to build up a critical mass of servers that can support it. So upgrade and watch this space for when we switch over properly.

https://matrix.org/blog/2020/05/28/synapse-1-14-0-released

Is it highly recommended upgrading every room?

Does the upgrade create a new room? Will the history be lost?

If it's recommended for security reasons maybe it could be nice to have a warning in riot-web.

**Comment by squarepupil** [comment]
> Does the upgrade create a new room? Will the history be lost?

I just tested upgrading a room from version 4 to 6 and it did indeed create a new room, which lost the history in the previous room.

**Comment by ChristianTacke** [comment]
It would be nice, if the new room could be populated with the old history. So that the new room has the full history.
As one server does the creation of the new room, it should be able to prepopulate the history?

**Comment by rubo77** [comment]
> It would be nice, if the new room could be populated with the old history. So that the new room has the full history.
> As one server does the creation of the new room, it should be able to prepopulate the history?

I really appreciate this too. But it should be optional

**Comment by richvdh** [comment]
I'm not sure this needs further documentation on the synapse side right now

**Comment by ChristianTacke** [comment]
> > It would be nice, if the new room could be populated with the old history. So that the new room has the full history.
> 
> I really appreciate this too. But it should be optional

@rubo77 Any idea where we can post this idea as a Feature Request? Or has it already been done?

**Comment by heyakyra** [comment]
https://github.com/matrix-org/synapse/issues/5709#issuecomment-513524012
> you can do /upgraderoom 4 in riot-web to upgrade a room...

How can this be done with a custom event in devtools?

**Comment by rubo77** [comment]
> It would be nice, if the new room could be populated with the old history. So that the new room has the full history.
> 
> 
> I really appreciate this too. But it should be optional
> 
> 
> @rubo77 Any idea where we can post this idea as a Feature Request? Or has it already been done?

You should open a new issue here

**Comment by heyakyra** [comment]
Can a space be upgraded?

**Comment by ChristianTacke** [comment]
Okay, filed a new issue for the history population: #10377

**Comment by heyakyra** [comment]
Ticket for space upgrades https://github.com/vector-im/element-web/issues/19208#issuecomment-1451038209
