### ISSUE TITLE
Room statistics: Background Update doesn't properly handle existing room stats

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/synapse#5711]
If you run a room stats background update whilst you have stats for some rooms, then after the background update, you will have stats for all other rooms but not the rooms you originally had stats for.

It should be fixed to properly support this 'incremental'/fix-up update use case, or failing that, discard all stats completely and generate the fresh ones correctly.

**Comment by erikjohnston** [comment]
Fixed in #5971
