### ISSUE TITLE
Run out of stack due to recursion loop in synapse/crypto/keyring.py

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#5723]
Two python backtraces here:

[gdb_traceback.log](https://github.com/matrix-org/synapse/files/3411782/gdb_traceback.log)
[gdb.txt](https://github.com/matrix-org/synapse/files/3411796/gdb.txt)

This seems to be recursing a lot on "_start_key_lookups" and "remove_deferred"

**Comment by richvdh** [comment]
fixed by #5724, I hope
