### ISSUE TITLE
Allow admin users to register new user account

### ISSUE THREAD

**Issue by awesome-manuel** [matrix-org/synapse#5741]
**Description:**

Right now, there are two endpoints that can be used to register a new user:
- `_matrix/client/r0/register`
- `_synapse/admin/v1/register`

The normal endpoint either allows anyone to register a new account (setting `enable_registration`) or an app service or via shared secret. The admin endpoint only allows registration via shared secret.

My request is to allow any user flagged as *admin* to also register a new user, most probably via the admin endpoint. This could be limited via a setting, e.g. `enable_admin_registration` or changing `enable_registration` from `bool` to `enum`.

**Comment by neilisfragile** [comment]
Hi @awesome-manuel can you explain your use case, as you describe admins can already create accounts (with a shared secret) - I want to understand how that limits you.

**Comment by awesome-manuel** [comment]
@neilisfragile we're building a web admin UI for synapse, (see https://github.com/Awesome-Technologies/synapse-admin) and obviously we don't want to put the shared secret into the react application. For the admin UI it should be enough to login with admin account credentials.

**Comment by neilisfragile** [comment]
Right I see, sounds good, thanks for the PR #5742

**Comment by richvdh** [comment]
now done via #6495: thank you!
