### ISSUE TITLE
wrong key/object for email/id based user auth

### ISSUE THREAD

**Issue by eyecreate** [matrix-org/synapse#5748]
When using the docs/spec to build out a client, I ran into an issue when trying to auth using email from id server. 

According to docs, the auth looks like this:

https://github.com/matrix-org/matrix-doc/blob/ad5d46d3317bd3d016ed7bf1e3fb5ce1f8d7fef1/specification/client_server_api.rst#L797

But according to synapse, it should be named this:

https://github.com/matrix-org/synapse/blob/54283f3ed49ce40059e9f0746f2ded08ce3a5b9e/synapse/handlers/auth.py#L454

So the two differences are the key name and whether it should contain an object or array.

**Comment by neilisfragile** [comment]
@eyecreate thanks for raising, given the spec typically uses snake case I would see this as a spec bug and I'll file a bug against the spec accordingly.

**Comment by neilisfragile** [comment]
Closing here and have opened a tracking issue against the spec 
https://github.com/matrix-org/matrix-doc/issues/2207
