### ISSUE TITLE
Soft logout: Add a device_id query parameter on login fallback page

### ISSUE THREAD

**Issue by manuroe** [matrix-org/synapse#5755]
In case of soft logout, we want to be able to log in back using the same device id. That means the fallback page must pass it for us in their login requests.

The proposal is a query param:
```
https://domain/fallback/page/?device_id=[DEVICEID]
```

Note: Riot mobile clients use the fallback page for SSO auth.

**Comment by clokep** [comment]
Reading back through some of the spec it seems that there are two ways to use SSO for login:

1. Go via the [SSO Client login](https://matrix.org/docs/spec/client_server/r0.6.1#sso-client-login) process, which ends up generating a login token which the client then uses to complete login via the normal [`/login` endpoint](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-login).
2. Use the [login fallback](https://matrix.org/docs/spec/client_server/r0.6.1#login-fallback), which calls `window.onLogin` when it is done (so it seems to go through the whole login process itself).

I wanted to confirm / be a bit more specific that we're talking about the second option here -- a request is being made to `/_matrix/static/client/login/`.

If so, it seems that this would require some specification work to include the device ID.

**Comment by clokep** [comment]
And I guess the follow-up to this, are there any [other parameters](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-login) we would want to provide while doing this?

**Comment by clokep** [comment]
From some conversation it seems:
* This is about the `/_matrix/static/client/login/` endpoint
* It was recommended to have this take a query parameter to feed into the login process.

To I think that answers my questions above.

**Comment by clokep** [comment]
Spec PR: matrix-org/matrix-doc#2604
