### ISSUE TITLE
Soft logout: /logout should not return 401 (soft_logout)

### ISSUE THREAD

**Issue by manuroe** [matrix-org/synapse#5756]
The `/logout` endpoint should instead succeed so that the used device_id can be trashed.

Currently, the user keeps a zombie device id after each soft logout.

**Comment by anoadragon453** [comment]
So if I understand this correctly, when you receive a `401; {soft_logout: true}` in a response, you try to `/logout` and get a `401` from that endpoint as well instead of a `200`?

**Comment by anoadragon453** [comment]
Should be fixed by https://github.com/matrix-org/synapse/pull/7443 in v1.14.0.

**Comment by bmarty** [comment]
I confirmed it's fixed. And device is correctly deleted on the homeserver
