### ISSUE TITLE
Setup Util

### ISSUE THREAD

**Issue by JorikSchellekens** [matrix-org/synapse#5765]
# Backend
python - REST api based on [klein](https://github.com/twisted/klein) which produces the configs
by templating the sample config generated by synapse.

# Frontend
React-Redux, es6 and a bunch of other goodies

# It's a setup util
This util is just a very simple initial setup thing. It will walk users through picking a username and setting up ports. It will handhold users looking to use a reverse proxy and delegation. Once it's at this point I would be very happy with the project. There's still plenty of scope for it to become the defacto config util for synapse but that may be for later.

# Federation tester:
It will include some simple utils to test the setup.

# Config editor
We've decided not to allow editing of the yaml files inside the installer.
# Milestones:

- [x] servername setup 
- [x] Ask for consent to send usage stats to matrix.org
- [x] Delegation options
- [x] Reverse Proxy options
- [x] Tls / ACME
- [x] Port configuration
- [x] Template output
- [ ] Database configuration
- [x] YAML dumper
- [ ] Federation testing
- [x] back button

optimisation / env settings

# Other things to think about
- LDAP
- TURN
- Consent tracking
- Admin user
- Email settings
- Advanced listener support
- User related settings
- search related settings
- manhole
- security settings
- advanced settings

**Comment by reivilibre** [comment]
Noting that it might be interesting to include STUN/TURN setup and/or testing in this utility – or perhaps a separate utility.

In my experience, it is tricky to set up (I still haven't managed… even though Wireshark shows promising-looking packets!). If we could make it easier, that'd be *excellent*.

**Comment by JorikSchellekens** [comment]
This is #1536

**Comment by richvdh** [comment]
Tasks left on this according to @erikjohnston:
 * add to CI on synapse to make sure we don't break it
 * release it
 * add it as a dep to synapse so that people can run it

**Comment by richvdh** [comment]
sadly we seem to have abandoned this.
