### ISSUE TITLE
user search does not retrieve all users in system 

### ISSUE THREAD

**Issue by amiraelsayed** [matrix-org/synapse#5777]
if I am logged in using
username : james
password : 123456
users that comes from martix server are

Sameh/@Sameh:domain.com
Walid/@walid:domain.com
madonna/@MADONNA:domain.com

if I am logged in using
username : john
password : 123456
users that comes from martix server are

Sameh/@Sameh:domain.com
Walid/@walid:domain.com
madonna/@MADONNA:domain.com
Habib/@habib:domain.com
elias/@elias:domain.com
nour/@nour:domain.com
wiliam/@wiliam:domain.com

if I am logged in using
username : nour
password : 123456
users that comes from martix server are

john/@john:domain.com
Sameh/@Sameh:domain.com
Walid/@walid:domain.com
madonna/@MADONNA:domain.com
elias/@elias:domain.com
wiliam/@wiliam:domain.com

I am using
getSession(context).eventsApiClient.searchUsers("domain", 100, null, userFoundCallback)
in android matrix sdk

I tried to use swagger api method also

https://domain.com/_matrix/client/r0/user_directory/search

and it is behave the same as android sdk, so I think the problem is not related to android sdk as it is only call the API methis

why that could happen?

**Comment by aaronraimist** [comment]
See https://github.com/matrix-org/synapse/blob/97bf3077550915161765fdd1cf9290d8039a55f9/docs/sample_config.yaml#L1235
