### ISSUE TITLE
Only "silent" notifications for special room on iOS Device

### ISSUE THREAD

**Issue by menzbua** [matrix-org/synapse#5811]
Hi @all,

i have a strange problem with my matrix synapse homeserver. I have a room where my Home Automation devices communicate to. I'm using for that the node-red-contrib-matrixbot. It is working as aspected. The devices can send messages to a special matrix room and i receive the messages. 
The problem is only in that room i did receive only silent messages on my iOS devices. That means that i see that there is an message but no notifcation tone or vibration is happening.
When i send a direct message to my account from the homebot user, vibration and message tone is there.

Is there any way to reset the notification settings on a room?

Thanks a lot
Regards
Manuel

**Comment by zingi** [comment]
![InkedBildschirmfoto 2019-08-05 um 13 15 57_LI](https://user-images.githubusercontent.com/9286499/62460931-acd8d100-b783-11e9-837f-9f1cb6241177.jpg)

I guess you are missing out the advanced notification settings on Riot Desktop. On Riot for iOS there are not all notification settings shown..

**Comment by menzbua** [comment]
Thats it. Now it works. Thanks a lot.

Regards
Manuel
