### ISSUE TITLE
User permission management

### ISSUE THREAD

**Issue by fuyonet** [matrix-org/synapse#5813]
Hi, i am new with matrix. I setup success my server and a riot web/android client.
I would like to use Matrix as a chat in my community of 100,000 members.

To protect users from spam, I have different user levels in my community. 

I want to prevent users from writing to hundreds of others one after the other, or posting wild messages in the main room.

Can I restrict users?

allow me to enter a room but not write messages in it? (with its own field message regarding the user level)

allow me to enter a room but not open private chats?  

Only if another user with the permission to open a private chat should this user be able to answer. etc etc. 

best regards

**Comment by neilisfragile** [comment]
You can control behaviour through power level settings, and then set the power for a given user. So it is possible to have rooms where only a few people can speak but everyone can read. Room admins can edit power level permissions and per user power levels for a specific room.

**Comment by fuyonet** [comment]
Thank you for this note. I have a look in google and find out this:
https://matrix.org/docs/guides/moderation

I have a look with my bad english :D 

Thank you a lot and best regards

**Comment by George2023** [comment]
Which part  can define ACL ? if we want to  have advance ACL what we can do it ?

**Comment by George2023** [comment]
if we would like to have RBAC and ABAC inside Matrix chat how possible such as   member A possible to read and only can attach this and can not do that
