### ISSUE TITLE
Admin API: purge_history doesn't delete local media

### ISSUE THREAD

**Issue by zingi** [matrix-org/synapse#5817]
### Description

When I **purge** the **history** of a room ([with the admin API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst#purge-history-api)) on my homeserver, the locally stored **media** is **not deleted**. 

This is a severe problem for people like me, who try to maintain a small homeserver. I want to purge the history of image-heavy rooms on a regular basis, to free up memory.

In my opinion it makes no sense to keep the pictures in any way anyway (from purged events). Since there is no real reference to them anymore, they are just dangling files, which occupy uselessly memory.

### Steps to reproduce

1. `du -sb /opt/synapse/media_store/` returns **3,331,432,273** Bytes
2. `select count(*) from local_media_repository;` returns 1,577 entires
3. Upload picture to (unencrypted) room
4. `du -sb /opt/synapse/media_store/` returns **3,333,367,545** Bytes
5. `select count(*) from local_media_repository;` returns **1,579** entries
6. Purge History of room (with previously uploaded picture) using:
[POST /_synapse/admin/v1/purge_history/<room_id>[/<event_id>]](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst#purge-history-api)
```javascript
{
    "delete_local_events": true,
    "purge_up_to_ts": 1564822558201 // timestamp after the picture upload
}
```
Purge finishes with no errors and returns a purge_id.
If I call the [purge status query](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst#purge-status-query) it says: 
```javascript
{
  "status": "complete"
}
```
7. `du -sb /opt/synapse/media_store/` _still_ returns **3,333,367,545** Bytes
8. `select count(*) from local_media_repository;` _still_ returns **1,579** entries

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
------------------------------------------------
**From the purge_history admin API, I expect that it**:
- deletes all corresponding message events from the DB _and_
- deletes all corresponding local media from the local_media_repository
  - (simply delete all corresponding stored files: **free up memory**)

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->


<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: personal homeserver with ​restricted federation

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: v1.2.1 [avhost docker](https://hub.docker.com/r/avhost/docker-matrix/tags)

- **Install method**: `docker-compose up -d`
<!-- examples: package manager/git clone/pip  -->

- **Platform**: VPS with Debian 9 64bit
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by neilisfragile** [comment]
The reason that it doesn't just do this today is that it is not straight forward to determine definitively if a given piece of media can be safely removed since it may be referenced by multiple rooms. For instance stickers from a sticker pack are duplicated for each room.

**Comment by zingi** [comment]
I don't quite understand the difficulty here. 
You can distinguish if the media is a sticker if the **msgtype** is **m.sticker**. And an image would be **m.image**. Or not?

**Comment by t3chguy** [comment]
Not in encrypted rooms, if a media is in both unencrypted and encrypted it'd disappear from the encrypted when the unencrypted got purged

**Comment by cryzed** [comment]
We made [synapse-purge](https://github.com/mserajnik/synapse-purge) to purge remote media cache, local media and events in all rooms (both encrypted and unencrypted) until "x seconds ago" for the Synapse server, feel free to use it. It is highly configurable and should work on all instances using a Postgres database.

**Comment by richvdh** [comment]
this is by design. See also #3479.
