### ISSUE TITLE
Read/Write event types based on power level

### ISSUE THREAD

**Issue by alkenerly** [matrix-org/synapse#5821]
**Description:**

Is it possible or how could I implement the ability for users in a room to only be able to send or receive custom event types based on their powerlevel within the room? Like if I wanted only users with power levels over 10 to be able to read certain types of events. 

That would mean that users with a power level of only 5 or whatever wouldn't even be able to receive those special events from the room.

**Comment by neilisfragile** [comment]
I don't think there would be a way to do this out of the box over and above the existing granularity that PLs provide i.e. https://matrix.org/docs/guides/moderation#power-levels has a good break down.

To create the ability to assign custom events specific power levels would something to consider at as a spec issue. I'd recommend asking the question in https://matrix.to/#/#matrix-spec:matrix.org
