### ISSUE TITLE
install synapse on docker with ssl certificate does not work

### ISSUE THREAD

**Issue by amiraelsayed** [matrix-org/synapse#5828]
Hello 

I have installed matrix on docker and it works perfect 
but when I try to change the ssl certificate it gives me error and exit when I start it 

<img width="1067" alt="Screen Shot 2019-08-06 at 11 08 17 PM" src="https://user-images.githubusercontent.com/3120646/62577402-2dd8bb00-b89f-11e9-8b48-6eedbd796a05.png">

here is the configuration that I have changed based on documentation

<img width="623" alt="Screen Shot 2019-08-06 at 11 09 57 PM" src="https://user-images.githubusercontent.com/3120646/62577502-5f518680-b89f-11e9-9db1-c8dda32a4b17.png">

and 
<img width="388" alt="Screen Shot 2019-08-06 at 11 10 07 PM" src="https://user-images.githubusercontent.com/3120646/62577530-6aa4b200-b89f-11e9-952d-6a9eecf64eda.png">

and here is my code to start the service

sudo docker run -d --name synapse \
    --mount type=volume,src=synapse-data,dst=/data \
    -p 8448:8448 \
    matrixdotorg/synapse:latest

can any one advice please why service exit when I start it

**Comment by neilisfragile** [comment]
Can you get any logs out of the container before it exits?

**Comment by openscript** [comment]
Have you tried to specify the config file specifically?

**Comment by toshanmugaraj** [comment]
key & cert may not be in the accessible path. check error log.

**Comment by richvdh** [comment]
closing for lack of response from the reporter
