### ISSUE TITLE
register-a-user instructions are very confusing

### ISSUE THREAD

**Issue by akarelas** [matrix-org/synapse#5829]
[Here](https://github.com/matrix-org/synapse/blob/master/INSTALL.md#registering-a-user) it says I should run `source ~/synapse/env/bin/activate` but the truth is that I should not do that if I've installed synapse through Ubuntu `apt-get install`. Neither should I run `synctl start`.

Someone told me that in the chatroom. But I wasted a lot of time trying to make it work.

I think these instructions should clarify this.

Also this line should point to the right config file, which is not (as the line suggest) `homeserver.yml` at `$HOME`, so I guess that line also needs to be fixed.

There might be other mistakes too, but I don't know.

**Comment by neilisfragile** [comment]
Thanks have modified
