### ISSUE TITLE
Can not add E-Mail nor FON Number

### ISSUE THREAD

**Issue by ralfi** [matrix-org/synapse#5832]
Base:

Docker + ansible based install from Github spantelleev
matrix-synapse: 1.2.1

Symptom: Can not add user E-Mail address (possible reset password) or Phone number

matrix-synapse Log:

synapse.http.server - 108 - ERROR - POST-0847 Failed to handle request via 'EmailThreepidRequestTokenRestServlet': <XForwardedRequest at  0x7fbe1e4f3390 method='POST' uri='_matrix/client/r0/account/3pid/email/requestToken' clientpro='HTTP/1.1' site=8008>

rsp MsisdnThreepid ... for FON number.

/usr/local/lib/python3.7 .... server.py Line 76 rsp. Line 315
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection error

Could it be possible that the entry will be write to wrong destination? IMHO this should be write to my local matrix-synapse database ...

Regards

**Comment by anoadragon453** [comment]
Your logs are a little mangled. Could you post which address refused the connection from your homeserver? If it's https://vector.im / https://matrix.org or another identity server, then it may have just been a hiccup in the network.

Currently registering with an email requires contacting an identity server. We're currently working towards decoupling that in https://github.com/matrix-org/synapse/issues/5751

**Comment by ralfi** [comment]
Hi anyadragon453, i am using my own selfhosted matrix-synapse server based on v1.2.1. I am using the latest docker image for mxisd but i know this is a long story ... But if i wish, how can i use my selfhosted matrix-synapse server (federation works well) with vector.im if i needed?

**Comment by anoadragon453** [comment]
Just set `vector.im` as part of `trusted_third_party_id_servers` in your Synapse's `homeserver.yaml`, and then when logging in/registering have https://vector.im set as your identity server.
