### ISSUE TITLE
No create event in auth events - 3 matrix servers 

### ISSUE THREAD

**Issue by kendosoul** [matrix-org/synapse#5840]
### Steps to reproduce

- set up 3 matrix synapse docker instances
- all listen to different ports 8008, 8009, and 8010 , within the docker instance, everything goes to 8008
 use ngrok to redirect ngrok https endpoints to listen to 8008 8009 8010 respectively. (
- all 3 matrix synapse docker instances share the same postgres database, hosted locally
- docker run them all. 
- I have 3 devices that log in each one of them
- I see messages initially but after more message exchanges, all 3 stop being able to send any. 

### Version information

the most current Riot iOS client available and Riot OSX client

- **Homeserver**: 

locally-hosted on docker

- **Version**: 

- **Install method**: 
1) install Docker

2) docker pull matrixdotorg/synapse

3) ```docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=neo.zeon \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate
```


4) ```docker run -d --name synapse \
    --mount type=volume,src=synapse-data,dst=/data \
    -p 8008:8008 \
    -p 8448:8448 \
    matrixdotorg/synapse:latest
```

5) `docker cp homeserver.yaml  synapse:/data/homeserver.yaml `

6) docker restart synapse

7) to verify `docker logs synapse`

------

to run second instance

1)```docker run -it --rm \
    --mount type=volume,src=synapse2-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=neo.zeon \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate
```


2) ```docker run -d --name synapse2 \
    --mount type=volume,src=synapse2-data,dst=/data \
    -p 8009:8008 \
    -p 8449:8448 \
    matrixdotorg/synapse:latest
```

3) `docker cp homeserver.yaml  synapse2:/data/homeserver.yaml `

4) docker restart synapse2

- **Platform**: 
homeserver is running on an iMAC

**Comment by kendosoul** [comment]
sorry for step 3

docker run -it --rm \
    --mount type=volume,src=synapse-data,dst=/data \
    -e SYNAPSE_SERVER_NAME=neo.zeon \
    -e SYNAPSE_REPORT_STATS=yes \
    matrixdotorg/synapse:latest generate

**Comment by neilisfragile** [comment]
I'm not sure what you are trying to do, but each synapse instance requires a unique name. 

If the goal is to run 3 instances as 1, using the same db etc it will not work, because each master process assumes it is the only one with write access to the db.

This _looks_ like a general support issue rather than an issue with Synapse as a code base - so I am going to close and ask you to direct questions to #synapse:matrix.org
