### ISSUE TITLE
UBUNTU 14:04 - Error In registration of users

### ISSUE THREAD

**Issue by souvikbhattacharyas** [matrix-org/synapse#585]
Hi,
I been successfully able to install and run the Synapses server in Ubuntu 14.04 by following the exact installation process mentioned in the website. But after the same when I am trying to register a user facing one error. I have already enable "enable_registration" attributes to "True". Also not able to open the WebUI but through netstat found server is running on the port.

Python Version : Python 2.7.6

*_Error: *_

(.synapse)root@webrtc:~/.synapse# register_new_matrix_user -c homeserver.yaml https://<IP>:8448
New user localpart [root]: webrtc
Password:
Confirm password:
Sending registration request...
Traceback (most recent call last):
  File "/root/.synapse/bin/register_new_matrix_user", line 154, in <module>
    register_new_user(args.user, args.password, args.server_url, secret)
  File "/root/.synapse/bin/register_new_matrix_user", line 102, in register_new_user
    request_registration(user, password, server_location, shared_secret)
  File "/root/.synapse/bin/register_new_matrix_user", line 57, in request_registration
    f = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

Sometime also getting error like "urllib2.URLError: <urlopen error Tunnel connection failed: 503 Service Unavailable>"

According to google it's due to SSL version so, where should I change in matrix code.

Any help is appreciated..

**Comment by erikjohnston** [comment]
Does using `https://localhost:8448` work? I.e.:

`register_new_matrix_user -c homeserver.yaml https://localhost:8448`

**Comment by souvikbhattacharyas** [comment]
Hi,
With URL now I am able to create users but from terminal the issue remains same. So, can you provide some solution regarding the terminal problem.

**Comment by killua-eu** [comment]
@souvikbhattacharyas, does setting url_preview_enabled: False and restarting your server help? See also my ticket #883

**Comment by richvdh** [comment]
don't understand this bug report, I'm afraid.
