### ISSUE TITLE
Use the v2 lookup API for 3PID invites

### ISSUE THREAD

**Issue by jryans** [matrix-org/synapse#5861]
When processing a 3PID invite, the HS currently looks up the 3PID on the IS using `v1/lookup`.

[MSC2134](https://github.com/matrix-org/matrix-doc/blob/hs/hash-identity/proposals/2134-identity-hash-lookup.md) has defined a `v2/lookup` API that supports using hashed addresses. (More discussion is needed to decide whether the HS should use hash alg `none` and continue to send plain text for this case or instead actually hash the value from HS to IS.)

Since the intention is to remove the v1 IS API down the road, we'll want to do this migration to cover all usages of v1.

**Comment by jryans** [comment]
We believe this is code path is unused by Riot today, as it does the lookup itself, but it seems still important for other client where we don't know how they handle 3PID invites.

**Comment by anoadragon453** [comment]
Done in https://github.com/matrix-org/synapse/pull/5897, https://github.com/matrix-org/synapse/pull/5979
