### ISSUE TITLE
Make dependency on sdnotify optional.

### ISSUE THREAD

**Issue by PMaynard** [matrix-org/synapse#5865]
### Description

Since #5732  was merged sdnotify is a hard dependency.
Make this an optional dependency to allow running on systems which don't use systemd.

### Version information

 1.2.1>

**Comment by richvdh** [comment]
My understanding was that sdnotify was a no-op on such systems

**Comment by PMaynard** [comment]
I was hit with an error, so ended up staying on 1.2.1. I'll give it another try tomorrow.
If you know of any flags I should set, that would help :)

**Comment by richvdh** [comment]
please let us know what error you are seeing.

**Comment by PMaynard** [comment]
I think line 75 in synapse/python_dependencies.py should be moved to the conditional_requirements, so we can use the systemd flag (line 95).

https://github.com/matrix-org/synapse/blob/master/synapse/python_dependencies.py#L75
https://github.com/matrix-org/synapse/blob/master/synapse/python_dependencies.py#L93

@richvdh The error I got was missing sdnotify dependency when building. Since it is not on the system. I'm in the process of updating the synapse package for void-linux from 0.99.3 to 1.3.0. 1.2.1 builds and installs no problem.

**Comment by richvdh** [comment]
> @richvdh The error I got was missing sdnotify dependency when building.

building what? what command are you running, and what is the error text?

**Comment by maxice8** [comment]
Hello, Alpine Linux maintainer for synapse and previous original package of synapse for Void Linux.

I'm commenting here since i'm having the same error and i think making a new issue would just be a duplicate.

All tests fail with the following error (the message changes for each test and when running but the error is the same)

```
tests.storage.test_end_to_end_keys
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/twisted/trial/runner.py", line 531, in loadPackage
    module = modinfo.load()
  File "/usr/lib/python3.7/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python3.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python3.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/builder/aports/testing/synapse/src/synapse-1.3.0/tests/storage/test_event_federation.py", line 18, in <module>
    import tests.unittest
  File "/home/builder/aports/testing/synapse/src/synapse-1.3.0/tests/unittest.py", line 31, in <module>
    from synapse.config.homeserver import HomeServerConfig
  File "/home/builder/aports/testing/synapse/src/synapse-1.3.0/synapse/config/homeserver.py", line 27, in <module>
    from .logger import LoggingConfig
  File "/home/builder/aports/testing/synapse/src/synapse-1.3.0/synapse/config/logger.py", line 27, in <module>
    from synapse.app import _base as appbase
  File "/home/builder/aports/testing/synapse/src/synapse-1.3.0/synapse/app/_base.py", line 23, in <module>
    import sdnotify
builtins.ModuleNotFoundError: No module named 'sdnotify'
```

patching synapse/python_dependencies.py to move sdnotify to CONDITIONAL_REQUIREMENTS doesn't fix this error.

**Comment by richvdh** [comment]
@maxice8:

> `builtins.ModuleNotFoundError: No module named 'sdnotify'`

this suggests that your build script isn't correctly running `setup.py`.

**Comment by richvdh** [comment]
As a workaround to this issue, I'm proposing that we reimplement `sdnotify` in the synapse codebase, since it's pretty trivial: #5871

**Comment by maxice8** [comment]
Also happens at runtime.

![image](https://user-images.githubusercontent.com/30738253/63200883-4728f680-c059-11e9-95f0-4b0c8701210f.png)

**Comment by PMaynard** [comment]
1.3.1 addresses this issue. Thanks @maxice8 and @richvdh
