### ISSUE TITLE
New 100 char display name length limit is too restrictive

### ISSUE THREAD

**Issue by ulope** [matrix-org/synapse#5870]
**Description:**

With d16c6375fe39deaafd70b151e496f5e15fd7b29c a display name length limit of 100 characters was introduced. 

Unfortunately this breaks our ([Raiden Network](https://github.com/raiden-network/raiden)) (admittedly unorthodox) use of the display name field as a way to publish ECDSA (recoverable) signatures. 

Hex encoded those take up 132 chars.

We could switch to base64 encoding (which would just fit) or (mis-)use the avatar_url field but both of those would be backwards incompatible changes at our protocol level which we would like to avoid if possible.

So the question is: Is there a possibility of having this length restriction increased (to say `256`) or better yet be made configurable?

**Comment by turt2live** [comment]
It sounds like you want https://github.com/matrix-org/matrix-doc/issues/489 or https://github.com/matrix-org/matrix-doc/pull/1769 instead

**Comment by aaronraimist** [comment]
It probably should still be configurable though

**Comment by t3chguy** [comment]
How would configurability work with federation?

**Comment by ara4n** [comment]
i suspect we should just bump it to 256

**Comment by aaronraimist** [comment]
I haven’t really looked at how it worked but I had assumed it was only limiting display names on your server’s own users, nothing to do with federation but maybe I’m wrong.
    
  



On Fri, Aug 16, 2019 at 1:08 PM -0400, "Matthew Hodgson" <notifications@github.com> wrote:












i suspect we should just bump it to 256

**Comment by Half-Shot** [comment]
Currently it's a local limit, not over federation.

**Comment by neilisfragile** [comment]
We can bump to 256

The reason that 100 was chosen (over any other finite number) was to give enough space for what we thought would be most profiles, but short enough to make it harder to spread abusive content via profile names (which used to be a thing ...)

**Comment by richvdh** [comment]
fixed by #5906

**Comment by ulope** [comment]
Great! Thanks for the quick turnaround.

Do you have a notion when a new release that includes this change could happen?

**Comment by richvdh** [comment]
releases normally happen every couple of weeks.
