### ISSUE TITLE
public_baseurl spelling confusion

### ISSUE THREAD

**Issue by cueman** [matrix-org/synapse#5887]
### Description

If you do not set public_baseurl and configure synapse for password reset emails, you get an error message that tells you it is missing "public_base_url" - with an extra underscore in there.

I went looking for public_base_url because of this, and then realised it should be public_baseurl.

There are two places where there is a reference to public_base_url, and both should be changed to public_baseurl:

* synapse/config/emailconfig.py
* synapse/rest/well_known.py

### Steps to reproduce

- do not set public_baseurl in homeserver.yaml
- configure synapse for password reset emails
- restart synapse
- logs provide message:

```Password resets emails are configured to be sent from this homeserver due to a partial 'email' block. However, the following required keys are missing: public_base_url```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: private server

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**:  1.3.1 and can be seen in master for tag v1.3.1 and the current tip of branch develop

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->

ubuntu apt install as described here:

* https://github.com/matrix-org/synapse/blob/master/INSTALL.md

- **Platform**:  ubuntu 18.04

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
fixed by #5909
