### ISSUE TITLE
Security Issue docs/ACME.md advises user to do chmod 777

### ISSUE THREAD

**Issue by zem** [matrix-org/synapse#5901]
A user should never be advised to do chmod 777 on the system, as there are always some users who follow the manual. Please fix the documentation. (I have not tested what  authbind manual tells but, chmod 555  should be enough here) 

grep -R 777 *: 

docs/ACME.md:sudo chmod 777 /etc/authbind/byport/80

**Comment by richvdh** [comment]
The document in question is https://github.com/matrix-org/synapse/blob/master/docs/ACME.md#authbind, and the doc in question seems to have come from https://github.com/matrix-org/synapse/pull/4547. @anoadragon453 do you remember the reason for chmod 777 here?

I agree it seems dangerous. @zem we'd welcome a PR.

**Comment by richvdh** [comment]
given we don't support ACME any more, this seems to have fixed itself.
