### ISSUE TITLE
Obsolete documentation terms for Google ReCaptcha Public/Private Keys

### ISSUE THREAD

**Issue by Syonyk** [matrix-org/synapse#5907]
(Tested Aug 24, 2019)

When signing up for Google ReCaptcha keys, the terms "public" and "private" keys are no longer used for "V2 Checkbox" integration as per the requirements for Synapse.

Instead, one is provided a "Site Key" and a "Secret Key".

I believe these correspond to the existing public and private key terms, but the documentation needs updating to refer to the new terms.  A couple lines in the doc and an additional line in homeserver.yaml would be sufficient to clarify the new terms.

**Comment by richvdh** [comment]
apparently this was fixed by #6257
