### ISSUE TITLE
Accounts which are created after invitation are periodically kicking out of the room

### ISSUE THREAD

**Issue by nesnera** [matrix-org/synapse#5908]
### Description

Accounts which are created after invitation are periodically kicking out of the room

### Steps to reproduce

1) Have a room and invite user which have not yet matrix account (by email)
2) When new account is created you can see that he accepted invitation before he do it manually
3) The user accepts the invitation and enters the room. He can read and wirte posts but he is kicked out within tens of minutes (I don't know it exactly, but it happens certainly within an hour)
4) Step three happens repeatedly (It's very bad for getting new users)
It's realy bad for getting new users, I'm afraid. :-/

It's realy bad for getting new users, I'm afraid. :-/

I have already tried to find a solution, but unsuccessfully. I tried:
- reject invitation, create new one and accept it
- kick off user (when looks be a member) and rejoin

Logs being sent: no

### Version information

- **Linux 4.13.12/Fedora 28**: Mozilla Firefox 66.0.4
- room and accounts are at riot.im server

**Comment by richvdh** [comment]
When you say "the user is kicked out of the room": what exactly do you mean by this? what are the symptoms you see?

**Comment by nesnera** [comment]
- User point of view: although the user has accepted the invitation, he must accept it again after some time. This happens repeatedly.
- Room point of view: The user can be seen among members of the room for a while, then only among the invited. This also happens repeatedly.

**Comment by richvdh** [comment]
ok, but who is doing the kicking? Can you share screenshots or something?

**Comment by nesnera** [comment]
I suppose the server did it. Unfortunately my test user has stayed in the room for over a week = I can't take screenshots now.
