### ISSUE TITLE
"Failed to remove threepid from ID server" - SOLVED

### ISSUE THREAD

**Issue by g574** [matrix-org/synapse#5910]
### Description
I tried to deactivate a user and got a "Failed to remove threepid from ID server" message.
Luckily I managed to solve it, I would like to share my experience here.

### Steps to reproduce
I have my own Synapse and Sydent behind a reverse proxy.
Proxy config:
```
  location /_matrix/identity {
    proxy_pass http://localhost:8090/_matrix/identity;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location /_matrix {
    proxy_pass http://localhost:8008/_matrix;
    proxy_set_header X-Forwarded-For $remote_addr;
  }

  location / {
    proxy_pass http://localhost:8008/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
```
I do not use federation, so the 8448 listener is not enabled.
The only `trusted_third_party_id_servers` entry in the homeserver config is my own Sydent. This setup has worked for a couple of months. Sydent is working fine, e.g. users are able to register, reset passwords... etc.

But now I tried to deactivate a user like this:
```
curl -s -XPOST "http://localhost:8008/_matrix/client/r0/admin/deactivate/<username>?access_token=xxxxxxxx" -d '{}'
```
also like this:
```
curl -s -XPOST "http://localhost:8008/_synapse/admin/v1/deactivate/<username>?access_token=xxxxxxxx" -d '{"erase": true}'
```
And I got the "Failed to remove threepid from ID server" message.
I checked the Synapse logs, I saw "Failed to contact identity server" messages.
After a few hours of pulling my hair I realised that something was not right in the Sydent-Synapse there-and-back.
So I added this to the nginx config:
```
  location /_matrix/identity/api/v1/3pid/unbind {
    proxy_pass http://localhost:8008/_matrix/identity/api/v1/3pid/unbind;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
```
+ restarted Nginx
I tried again, and voilà, the user is disabled.

### Version information

- **Homeserver**: 
Synapse: 1.3.1
Sydent: 1.0.3
- **Install method**: 

matrix-synapse-py3 package

- **Platform**: 
Ubuntu

**Comment by richvdh** [comment]
> ```
>  location /_matrix/identity/api/v1/3pid/unbind {
>    proxy_pass http://localhost:8008/_matrix/identity/api/v1/3pid/unbind;
>    proxy_set_header X-Forwarded-For $remote_addr;
>  }
> ```

This doesn't sound the correct solution. ` /_matrix/identity/api/v1/3pid/unbind` is an endpoint which should be handled by the identity server, not the homeserver. I'm surprised it works at all when you point it at synapse.
