### ISSUE TITLE
"M_UNKNOWN","error":"No id_server in creds"

### ISSUE THREAD

**Issue by matrixtempnew** [matrix-org/synapse#5912]
How to resolve this error?, I am using mxisd as identity server.

**Comment by richvdh** [comment]
Please could you give more information about when you are seeing this error?

**Comment by matrixtempnew** [comment]
POST-73 - <XForwardedForRequest at 0x7f16b1429638 method=u'POST' uri=u'/_matrix/client/v2_alpha/register' clientproto=u'HTTP/1.1' site=8448> SynapseError: 400 - No id_server in creds
This error in homeserver.log

**Comment by richvdh** [comment]
sounds like a client bug. What client are you using?

**Comment by matrixtempnew** [comment]
I am using matrix as my homeserver and mxisd as a identity server.

**Comment by richvdh** [comment]
yes, but which matrix *client*? Riot (web/android/iOS)? nheko?

**Comment by matrixtempnew** [comment]
I am using web. @richvdh

**Comment by richvdh** [comment]
OK, can you raise a bug with riot-web please.

**Comment by richvdh** [comment]
(for clarity: I'm pretty sure this will only happen if the client sends a register request with a `three_pid_creds` with no `id_server` field.)
