### ISSUE TITLE
SAAS Availability

### ISSUE THREAD

**Issue by souvikbhattacharyas** [matrix-org/synapse#592]
Hi,
I am planning to deploy Synapses server in Cloud as SAAS. So, please let me know that if Synapses server has that support or not. If not then any work around to solve that. My scenario is given below:
1) Suppose 2 companies exist. Company A & Company B.
2) Now both Company have some users. Company A = A1 & A2 Company B=B1 & B2.
3) Both of the company register to matrix.
4) Now when Company A and it's user will login and they will be able to see the online users related to their own companies only now others companies. The company will be able to create groups share screen only among them.

**Comment by richvdh** [comment]
Please come to https://matrix.to/#/#matrix:matrix.org for support questions.
