### ISSUE TITLE
Use federation blacklist for requests to identity servers

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#5935]
Now that we're getting rid of the concept of trusted identity servers, we need to make sure that people can't try and poke at internal addresses when sending identity server-related requests.

The plan is to reuse the federation blacklist for these requests which by default blocks internal CIDR ranges.

**Comment by anoadragon453** [comment]
@richvdh @erikjohnston Should matrixfederationclient be used for these requests so we get blacklisting for free? Or does that muddy the definition of the client?

**Comment by richvdh** [comment]
Previously, using the MatrixFederationClient would have meant that you'd get .well-known and SRV routing, which you don't want for an IS. But now I'm not so sure. @erikjohnston do your recent changes to the agent mean that https urls skip the federation routing?

**Comment by erikjohnston** [comment]
> do your recent changes to the agent mean that https urls skip the federation routing?

That should be the case, though I haven't tested it.

**Comment by richvdh** [comment]
I guess another question: do we want the options relating to TLS certs to also apply to connections to the IS? (I think we probably do?)

**Comment by anoadragon453** [comment]
> I guess another question: do we want the options relating to TLS certs to also apply to connections to the IS? (I think we probably do?)

Which options were those again? HTTPS being required?

It's possible to use a local http process for validation of 3PIDs so we wouldn't want to force 3PIDs there.

**Comment by anoadragon453** [comment]
Actually now that I think about it since `id_server` is a domain without a protocol, we prefix `https://` in front of it.

So you could still poke local infrastructure but you'd have to do it over https.

**Comment by anoadragon453** [comment]
Would `federation_domain_whitelist` affect this?

**Comment by richvdh** [comment]
fixed by #6000

**Comment by richvdh** [comment]
(which did nothing to address the tls certs stuff: you'll have to use a real cert on your ID server)
