### ISSUE TITLE
Rename disabled users federation wide

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#5949]
**Description:**
There are lots of problems with the current process of disabling an account that could be solved, if there would be a way to rename the account federation wide before disabling it.

That way you could create a new user with the old name and this way other users would not run into  finding the old disabled user of someone again and again.

We would have to think about how to ensure, that the new username with the same name is not interfering with federated servers, that were offline for a while during the period, the user was disabled, renamed and a new user with the same name created.

**Comment by turt2live** [comment]
I'm not sure I understand the problem here. Are you looking to rename the mxid for some reason?

**Comment by rubo77** [comment]
Let's say I decide to disable my Matrix Account @someone:matrix.org "forever".

This is not reversable.

After some time, I decide to use matrix again anyway. But now I cannot use the same ID @someone:matrix.org again.

My request is, that on disable the ID should be renamed to @someone-disabled:matrix.org or such, and this renaming should be federated

**Comment by turt2live** [comment]
This is a thing that needs https://github.com/matrix-org/matrix-doc/issues/1228 then

**Comment by richvdh** [comment]
I think it *is* matrix-org/matrix-doc#1228
