### ISSUE TITLE
enabling acme fails with python type error in version 1.3.1

### ISSUE THREAD

**Issue by ybaumy** [matrix-org/synapse#5951]
### Description

synapse gets a SystemExit: 1 after trying to enable acme

### Steps to reproduce

- enabled acme
- syslog can be found here [https://paste.ubuntu.com/p/48X3DHwtcH/](url)
- homeserver error here [https://paste.ubuntu.com/p/xSsRFcdbng/](url)

> /var/log/matrix-synapse # ll /var/lib/matrix-synapse/data/
total 12
drwxr-xr-x 2 matrix-synapse nogroup 4096 Aug 31 12:00 ./
drwxr-xr-x 5 matrix-synapse nogroup 4096 Aug 31 12:00 ../
-rwxr-xr-x 1 matrix-synapse nogroup 1675 Aug 31 12:00 matrix.key*

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.lost-frequencies.eu

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 1.3.1

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->

- **Platform**: ubuntu 18.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
have you set the `tls_certificate_file` in the config?

**Comment by ybaumy** [comment]
@richvdh that was it.. thanks. will close
