### ISSUE TITLE
Expected IReactorTime, got Reactor instead

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6001]
https://github.com/matrix-org/synapse/blob/f7c873a64355506221648d55d64023c83d43f618/synapse/http/matrixfederationclient.py#L889

`addTimeout` expects an `IReactorTime` as its second parameter, but we give it a Reactor instead.

**Comment by richvdh** [comment]
@anoadragon453 what are the user-visible symptoms of this? is something not working that should?

**Comment by hawkowl** [comment]
`IReactorTime` is the reactor interface for time-based things. Twisted-provided `Clock`s and reactors implement this interface.
