### ISSUE TITLE
SSO mxid creation still leaks email addresses for Google auth0 login?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6038]
I'm seeing users turn up on mozilla's HS with MXIDs of `@foo.bar.gmail.com:mozilla-test.modular.im`. It looks like we're trying to base the mxid on foo.bar@gmail.com, presumably due to google SSO?

**Comment by richvdh** [comment]
this isn't a synapse bug: if anything, it's a configuration error.
