### ISSUE TITLE
Support Client-Server API r0.6

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6045]
We should remove the unstable feature flags that were part of the r0.5.0 release cycle. These are:

* `m.require_identity_server` (https://github.com/matrix-org/synapse/pull/5972)
* `m.id_access_token` (https://github.com/matrix-org/synapse/pull/5974)
* `m.separate_add_and_bind` (https://github.com/matrix-org/synapse/pull/6044)

Clients that rely on these flags should check for Client Server API r0.6.0 support instead.

We should remove all the deprecated endpoints. These are:

* `/account/3pid` - replaced by `/account/3pid/add` and `/account/3pid/bind`
* Others...

**Comment by anoadragon453** [comment]
What about the lazy-loading flag (`m.lazy_load_members`)? :)

**Comment by turt2live** [comment]
LL is dependent on https://github.com/matrix-org/synapse/issues/5528

**Comment by jryans** [comment]
@anoadragon453, does the backend team intend to also remove the unstable API prefix from `3pid/unbind` as part of supporting r0.6.0? This is what the new spec process (from [MSC2324](https://github.com/matrix-org/matrix-doc/pull/2324)) would suggest, but the feature was added before that process appeared, so I am unsure what process will be followed and when clients needs to follow along.

**Comment by jryans** [comment]
From chatting with @neilisfragile, it sounds like we will indeed apply the new spec process here with the 2 month window before removing unstable.

**Comment by turt2live** [comment]
Dropped this down to just r0.6 as .1 is coming out soon.

@anoadragon453 any update on this? It's been well over 2 months and I'm tempted to start shipping air horns with GPS triggers to the UK until this get resolved.

**Comment by turt2live** [comment]
@richvdh why was this closed? It's still an issue.

**Comment by turt2live** [comment]
answer: github mobile is terrible at showing it was closed by a PR.
