### ISSUE TITLE
If the default notary server is used, then warn on start up.

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#6088]
Currently it is necessary for a homeserver to rely on a notary server to maintain a list of server keys across the federation. 

Notary servers need to be stable and long lived, so the current default of 'matrix.org' is a good choice for most admins. However it is not immediately obvious to an admin that their server defaults in this way, and some admins will prefer to require another server be the notary.  

Synapse should warn admins on start up that the notary is matrix.org unless ```perspectives``` or  ```trusted_key_servers```is not explicitly set in homeserver.yml

**Comment by neilisfragile** [comment]
The log line should also make it clear that the software defined default will be removed in future as per #6087

**Comment by neilisfragile** [comment]
actually may as well close in favour of #6087

**Comment by neilisfragile** [comment]
- [ ] add a warning to stderr if you're running on the hardcoded default (and mention that the default will be removed in future)
- [ ] (re)add matrix.org as an explicit un-commented default in homeserver.yaml
- [ ] add a warning to stderr if the config ends up using matrix.org and say "if you don't want to use matrix.org for this, please pick another long-lived reliable server instead"
- [ ] add the suppress_notary_server_warning config option to get rid the warnings if you consciously don't care.

**Comment by neilisfragile** [comment]
https://github.com/matrix-org/synapse/pull/6090

**Comment by richvdh** [comment]
resolved by #6090
