### ISSUE TITLE
Uploading a too large file: wrong error code

### ISSUE THREAD

**Issue by bmarty** [matrix-org/synapse#6109]
When uploading a too large file, synapse responds with a 413 (OK) but with errcode M_UNKNOWN. According to the [spec](https://matrix.org/docs/spec/client_server/latest#post-matrix-media-r0-upload), it should be "M_TOO_LARGE"

Received responseCode: 413
Received responseBody:
`{"errcode":"M_UNKNOWN","error":"Upload request body is too large"}`

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6151
