### ISSUE TITLE
Split workers: AttributeError in client_reader login endpoint w/ password provider

### ISSUE THREAD

**Issue by ulope** [matrix-org/synapse#6113]
### Description

Background:
- Synapse 1.3.1
- Split worker mode
  - In this case the `client_reader` worker with all recommended path regexes being routed to it (in particular the `login` one)
- Custom password provider that calls `account_handler.register()` in `check_password()` under some conditions.

When a user tries to log in and the password_provider calls `account_handler.register()` an `AttributeError: 'ClientReaderSlavedStore' object has no attribute 'update_profile_in_user_dir'` exception is raised.
(Unfortunately I didn't save the full traceback, if required I can reproduce it.)

Removing the `login` regex from the worker and letting it be served from the main homeserver worker resolves the issue.

### Version information

- **Homeserver**: N/A (local testing)
- **Version**: v1.3.1

**Comment by richvdh** [comment]
is this still an issue?

**Comment by richvdh** [comment]
guess not.
