### ISSUE TITLE
Lacking a test for createRoom with list of invitees

### ISSUE THREAD

**Issue by werner291** [matrix-org/synapse#6122]
Currently, the room creation tests do not include any tests at all of the "invite" parameters.

See #4088 this only concerns invalid IDs, but the current Develop branch 500's in the test environment when you add a list of invitees to the room creation request. This is because the mock federation client currently lacks invitation functionality, and does not return actually return an iterable list of signatures.

**Comment by neilisfragile** [comment]
(not really enhancement, but probably the closest label wise)

**Comment by DMRobertson** [comment]
There are a couple of such tests today:

https://github.com/matrix-org/synapse/blob/b9778673587941277e15b067ad39cdf084f7dde5/tests/rest/client/test_rooms.py#L756-L780

There is a sytest test [here](https://github.com/matrix-org/sytest/blob/c75ff0449b5b62bdebfdb9024170988b519628d9/tests/90jira/SYN-205.pl#L1) and complement test [here](https://github.com/matrix-org/complement/blob/4418d2c05009cb0754403a9a8565b8b701633a5b/tests/csapi/apidoc_room_create_test.go#L103).

Suggest we close this. If there's a specific complaint that remains today, we can reopen.
