### ISSUE TITLE
Admin route for detecting if the user is an admin

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#6130]
Currently software abuses `/whois` for checking admin state, though in some cases this is not useful because `/whois` will return a result if the requesting user is the target user. Some implementations get around this by querying a non-existent user to get an empty response if the requesting user is an admin.

A route to just check if the user's access token givens them admin powers would be great.

**Comment by t3chguy** [comment]
maybe /whois/ could simply be extended with an `is_admin` flag, would be useful for other admin tools surely?

**Comment by udaykiranreddykondreddy** [comment]
Hello @turt2live can I work on this?

**Comment by neilisfragile** [comment]
An admin user is a very Synapse orientated concept and putting it in whois would mean adding the concept to the spec for all, I think this would be better housed under the Synapse specific admin namespace

**Comment by t3chguy** [comment]
Whois has a Synapse specific endpoint:
`GET /_synapse/admin/v1/whois/<user_id>`
which is what js-sdk uses

**Comment by turt2live** [comment]
(also the spec is fine with adding more fields to responses, just have to be wary of those fields changing value in the spec)

**Comment by neilisfragile** [comment]
> Whois has a Synapse specific endpoint:
> `GET /_synapse/admin/v1/whois/<user_id>`
> which is what js-sdk uses

Though currently it requires that the caller is an admin, @turt2live I think you are asking for a non-admin endpoint?

**Comment by t3chguy** [comment]
I read through the code and it requires you to be an admin or be requesting the whois on yourself, which is the case is_admin is desired for

**Comment by turt2live** [comment]
I am asking for a way to determine if the access token gives the user Synapse admin rights. Synapse has an if statement where if you `/whois` yourself, you can get your data (good), but that means we can't use that to determine admin state.

**Comment by richvdh** [comment]
could you clarify the usecase here? Why do clients want to know if you are an admin?

**Comment by turt2live** [comment]
So they can show a "Deactivate this user" button.

**Comment by richvdh** [comment]
ok.

I'm not quite clear why #6180 was rejected and have reopened it. That said, I'm not sure it's a great solution to the problem.

**Comment by Harha** [comment]
I'm new to the matrix spec and synapse as a whole, so I just did what was requested in my pull request.

Feel free to suggest better approaches and I'll see what I can do.

**Comment by turt2live** [comment]
This was added in https://github.com/matrix-org/synapse/pull/5914
