### ISSUE TITLE
Allow to login with uppercase or mixed case in username 

### ISSUE THREAD

**Issue by enannos** [matrix-org/synapse#6143]
### Description

We are using the matrix-synapse server with the built-in ldap authentication. 
Our problem is that whenever a user tries to login with his username(written in uppercase or mixed), he gets the error "For security, this session has been signed out. Please sign in again." from RIOT.
We used the mxisd during the past and cannot recall facing these kind of problems. But we had to abandon the mxisd for AD-auth because the project is not maintained anymore. 

### Steps to reproduce
User tries to authenticate(AD) using **N**ame.**L**astname (and not name.lastname)

Logs being sent: no

![grafik](https://user-images.githubusercontent.com/8511600/65969702-8a062880-e465-11e9-9bd1-0dac697a9715.png)

### Version information

- **Version**: 1.3.1

**Comment by neilisfragile** [comment]
If mxisd did what you want then you may find https://github.com/ma1uta/ma1sd solves your problem. 

For more context, MXIDs being lower case only is a spec requirement (rationale here https://matrix.org/docs/spec/appendices#user-identifiers)

**Comment by richvdh** [comment]
right; I think this would be a limitation with matrix-synapse-ldap3 rather than synapse itself.
