### ISSUE TITLE
/_matrix/client/unstable/add_threepid/email/submit_token logs "token" and "client_secret"

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#6157]
### Description

Are these things that should be logged (at the INFO level) or should they show up as `<redacted>`?

```
Oct 03 04:11:23 ubuntu matrix-synapse[20095]: 2019-10-03 04:11:23,310 - synapse.access.http.8008 - 233 - INFO - GET-5508 - 8008 - Received request: GET /_matrix/client/unstable/add_threepid/email/submit_token?token=a...&client_secret=b...&sid=c...
```

### Version information

- **Version**: 1.4.0rc2

**Comment by anoadragon453** [comment]
Thank you for reporting this, we've redacted `client_secret` in #6158 (for v1.4.0) for now and plan to fix this properly with a spec change in the near future.

**Comment by aaronraimist** [comment]
Should this stay open? If something needs to change with the spec do you want to file an issue on matrix-doc?
