### ISSUE TITLE
Change default room version to v5

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#6165]
It’s probably been long enough since Synapse 1.0 right?

**Comment by neilisfragile** [comment]
Yeah agreed

**Comment by neilisfragile** [comment]
https://github.com/matrix-org/synapse/pull/6220

**Comment by richvdh** [comment]
As per #6220: this needs an MSC to change :/

**Comment by aaronraimist** [comment]
MSC 2334 https://github.com/matrix-org/matrix-doc/pull/2334

**Comment by anoadragon453** [comment]
Closed in https://github.com/matrix-org/synapse/pull/6220
