### ISSUE TITLE
Unable to create new users w/o enable registration

### ISSUE THREAD

**Issue by pludi** [matrix-org/synapse#6172]
### Steps to reproduce

- Setup new Server with version 1.4.0
- Try to create an admin user with shared registration hard disabled and no admin user to create an admin token for
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: internal

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.4.0

- **Install method**: Upstream Ubuntu package
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 18.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
yes, you have to enable shared-secret registration to create the first admin user. Disable it once you're done.

**Comment by btittelbach** [comment]
I also stumbled across this issue. Previously, "shared-secret registration" could be enabled by setting "registration_shared_secret:" to a secret string value.
This by-itself is no longer sufficient to enable "shared-secret registration" and there seems to be NO documentation on how to temporarily or permanently enable it.

**Comment by btittelbach** [comment]
I think the misunderstanding comes from the fact that in the most recent changelog there is an entry

> Remove shared-secret registration from /_matrix/client/r0/register endpoint

However, the shared-secret registration is still available via `client/r0/admin/register` endpoint, which is what the `/usr/bin/register_new_matrix_user` script uses.

The script works fine on 1.4 btw. It just need to be given the shared secret and the correct matrix URL
