### ISSUE TITLE
openid connect 

### ISSUE THREAD

**Issue by carlokok** [matrix-org/synapse#6182]
One feature synapse seems to be missing is a simple authentication against a foreign database/website. I know there's CAS and SAML support, but those are huge undertaking, while openid connect can easily be implemented and should suffice for most usecases (it's just oauth2 with an entrypoint after authentication).

https://openid.net/connect/

**Comment by auscompgeek** [comment]
I suppose one way of working around this is to use Auth0 as a SAML IdP.

**Comment by turt2live** [comment]
This should just be the pair of https://matrix.org/docs/spec/client_server/r0.5.0#id199 and https://matrix.org/docs/spec/server_server/r0.1.3#openid ?

Both these endpoints are implemented and supported by synapse - it's how integration managers work.

**Comment by carlokok** [comment]
@turt2live That's the "other way around". That's how clients / integrations authenticate against synapse. I'm talking about how synapse authenticates users. When running as part of an existing community, being able to make users use their existing logins is a huge advantage.

**Comment by friedger** [comment]
Openid connect (with self-issued provider) can help to solve authentication with decentralized identities (like https://github.com/matrix-org/matrix-doc/issues/778)

See recent paper (that came out of RWoT I think): https://self-issued.info/?p=2013

**Comment by phalt** [comment]
I'm looking to use openID to allow my team to quickly login to our matrix instance without having to generate a load of new user accounts. Any progress on this?

**Comment by OvermindDL1** [comment]
I'm also curious in this, I use OpenID Connect for my open source development server and was curious in how to have matrix auth against that, is it not yet possible?

**Comment by ara4n** [comment]
https://github.com/matrix-org/synapse/pull/7256

**Comment by clokep** [comment]
This was added in #7256.
