### ISSUE TITLE
Identity server

### ISSUE THREAD

**Issue by derritter88** [matrix-org/synapse#6183]
Dear team,

according to the newest release notes (1.4.0) Matrix Synapse will not use any third party identity server unless you enable it again.
Also the current public identity servers (vector.im & matrix.im) will no longer allow to use them in December.

That's fine but on the other side the FAQ says:

> Yes - the reference implementation issydent and you can run your own ID server cluster that tracks 3rd party to Matrix ID mappings. This won't be very useful right now, though, and we don't recommend it.

So what should we do?
I run my own hosted Matrix Synapse server and currently I know that the 3rd party service I am using won't be supported in the near future but there is also no current solution.

**Comment by derritter88** [comment]
Also following problem would occure:

You can host your own copy of Sydent, but this will prevent you reaching other users in the Matrix ecosystem via their email address, and prevent them finding you. We therefore recommend that you use one of the centralised identity servers at https://matrix.org or https://vector.im for now.
[https://github.com/matrix-org/synapse/blob/master/README.rst#identity-servers](Github)

In general I would like to see an identity server which features federation.

**Comment by richvdh** [comment]
I don't think this is a synapse bug.

**Comment by derritter88** [comment]
Oh sorry it was never my intention to log a bug - I just wanted to log this as an issue but was unable to create a label for that.

**Comment by root562** [comment]
I am looking for Matrix Identity server to work with my own hosted Synapse server which is not federated. I saw https://github.com/matrix-org/sydent and https://github.com/kamax-matrix/mxisd
What are the differencex between these two? Which one is suitable for me to use?

**Comment by babolivier** [comment]
Hey, for questions or support requests I'd suggest asking them in #synapse:matrix.org, which is our main support channel, as we don't use github issues for support.

**Comment by root562** [comment]
> Hey, for questions or support requests I'd suggest asking them in #synapse:matrix.org, which is our main support channel, as we don't use github issues for support.

Thanks man. I posted there got the answer I wanted.
