### ISSUE TITLE
ldap user can't connect to server company

### ISSUE THREAD

**Issue by HaxepBcex** [matrix-org/synapse#6188]
Hello, have some trouble with one ldap user...
When he tries to connect to the riot server of the company, he receives a message:
"For security, your session has been completed. Please log in again."
Log from server:
`окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,667 - ldap_auth_provider - 133 - INFO -  - User authenticated against LDAP server: ldap://ip:389 - cleartext - user: CN=user_name,OU=domen - not lazy - bound - open - <local: ip:34852 - remote: ip:389> - tls not started - listening - SyncStrategy - internal decoder
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,668 - synapse.storage._base - 496 - WARNING -  - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,668 - synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,671 - synapse.storage._base - 496 - WARNING -  - Starting db txn 'store_device' from sentinel context
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,671 - synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,701 - synapse.storage._base - 496 - WARNING -  - Starting db txn 'is_support_user' from sentinel context
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,702 - synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,709 - synapse.storage._base - 496 - WARNING -  - Starting db txn 'add_access_token_to_user' from sentinel context
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,709 - synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,712 - synapse.storage._base - 496 - WARNING -  - Starting db txn 'get_device' from sentinel context
окт 09 17:36:09 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:09,713 - synapse.storage._base - 535 - WARNING -  - Starting db connection from sentinel context: metrics will be lost
окт 09 17:36:10 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:10,063 - synapse.logging.context - 495 - WARNING - PUT-603034 - Expected logging context sentinel but found POST-603030
окт 09 17:36:10 im-srv01 matrix-synapse[23996]: 2019-10-09 14:36:10,380 - synapse.api.auth - 339 - WARNING - GET-603052 - Unrecognised access token - not in store.
`
what can be done?

**Comment by richvdh** [comment]
This doesn't sound like a synapse bug. I'm afraid we can't offer support via github.

**Comment by enannos** [comment]
I have the same issue and it looks like that it comes from the matrix-synapse.
We are also using the ma1sd AD connector.

**Comment by BlackWolfDEsign** [comment]
use only lower case for username when login via riot... 

synapse requires lower case when registering
