### ISSUE TITLE
Logging broken in Docker image

### ISSUE THREAD

**Issue by Zash** [matrix-org/synapse#6194]
### Description

Synapse in the `matrixdotorg/synapse` Docker image produces debug logs normally in v1.0.0 but after v1.1.0 *only* HTTP request logs.

I believe it is related to the removal of `loggers.synapse.level` in #5547, restoring that restores normal debug logging.

### Steps to reproduce

- `docker run --rm -it -p 8008:8008 -e SYNAPSE_SERVER_NAME=localhost -e SYNAPSE_REPORT_STATS=no -e SYNAPSE_LOG_LEVEL=DEBUG -e SYNAPSE_NO_TLS=true matrixdotorg/synapse:v1.0.0-py3`
- Observe debug logs
- `docker run --rm -it -p 8008:8008 -e SYNAPSE_SERVER_NAME=localhost -e SYNAPSE_REPORT_STATS=no -e SYNAPSE_LOG_LEVEL=DEBUG -e SYNAPSE_NO_TLS=true matrixdotorg/synapse:v1.1.0-py3`
- Observe diminished logs, only HTTP related request logs
- Add `loggers.synapse.level="DEBUG"` to logging config (exact details left as an exercise)
- Run the result
- observe logs again

### Version information

Problem observed 

- **Version**:

`>=1.1.0`

- **Install method**:

Docker.

- **Platform**:

Tested on Docker on Windows and Docker on Debian Linux

**Comment by richvdh** [comment]
Thanks for the report. Hopefully fixed by #6197.
