### ISSUE TITLE
m.room.create event is duplicated in sync response when first syncing a room

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#6204]
### Steps to reproduce

 - have 2 clients open for the same account: client a and client b
 - create a room with client a
 -  sync client b

The sync response for client b contains the new room as expected, but the `m.room.create` appears twice in the timeline.

https://matrix.org/_matrix/media/r0/download/matrix.org/yKvWtslxasYiYmHXhAuguMro is a sync response where the problem is visible, as described.

I can reproduce this on the synapse currently deployed on matrix.org (unsure how to tell which version that is).

I couldn't reproduce locally though on latest develop somehow. The sync response was also weird their for a new room, with multiple sync responses for a room creation, and m.room.create not being the first one ... fwiw.

**Comment by richvdh** [comment]
dup #1995
