### ISSUE TITLE
Ubuntu installation procedure makes signing key and homeserver.yaml world accessible

### ISSUE THREAD

**Issue by mothlyme** [matrix-org/synapse#6208]
At least in the installation for Ubuntu both the config and signing key are in the `/etc/matrix-synapse/` folder which itself has by default the properties `drwxr-xr-x 1 matrix-synapse nogroup`. 
Although it is owned by `matrix-synapse`, setting the permissions to 700 (Only the owner, aka `matrix-synapse` can read or write) results in the server not starting anymore. 
This is a security issue as both config (with the registration key) and the signing key have to be world accessible (although only on the local machine) in order for the homeserver to launch.

**Comment by richvdh** [comment]
this is #1528, for the record
