### ISSUE TITLE
Use Cython (selectively) to speed up things

### ISSUE THREAD

**Issue by TheJJ** [matrix-org/synapse#6209]
I'm not sure if this was already considered, but maybe it would help to speed up things in synapse by implementing performance intensive parts in [Cython](https://cython.org/) code, which integrates seamlessly in the overall Python codebase.

(Something that may also be worth considering if not already done is to use [asyncpg](https://github.com/MagicStack/asyncpg), which basically is a Cython wrapper for the Postgres C API).

**Comment by richvdh** [comment]
sure, sounds like a great idea!

**Comment by hawkowl** [comment]
Cython creates unmaintainable Python, and Python that's a pain to install (especially on non-x86) -- instead we should be using more pure Python and targeting fixing PyPy incompatibilities for performance gains. We should absolutely not include any Cython in the Synapse codebase.
