### ISSUE TITLE
GnuPG / PGP email encryption on automated emails from Matrix/Synapse | Does Synapse require a Server or VPS? or can it run on a web domain?

### ISSUE THREAD

**Issue by life777eternal** [matrix-org/synapse#6210]
Hello, I'm thinking about setting up Synapse as a homeserver and maybe connect it to the matrix federation. My only purpose for it would be to make a secure group on a server for a group of people which I've joined. (by the way, I dislike that the groups on Synapse are called "rooms") if I set it up, everyone in the group would join Riot.im on my server. Also it's mentioned that Synapse is the most widely installed Matrix. Are there any others? 
Does Synapse require a dedicated server or VPS?  or can it run from a web domain? 

Here is my question, I was reading in the documentation that the server can be setup to send email. **Would you be able to add the option for it send encrypted email with GnuPG / PGP after the user provides their public key?** There's already a few applications available that use GnuPG / PGP. Such as [Enigmail](https://enigmail.net) for [Thunderbird,](https://thunderbird.net) [OpenKeyChain](https://openkeychain.org) for Android, & a few others as extensions for Chromium and Firefox. Additionally, Facebook has had encrypted email notifications available for a while now. 

GnuPG / PGP is a circumvention for the inherently insecure email which has been available since 1991. Please see [https://Bjornjohansen.no/secure-email](https://Bjornjohansen.no/secure-email) & [https://Emailselfdefense.fsf.org](https://Emailselfdefense.fsf.org) for information on encrypting email with GnuPG / PGP.  You can even use one of those applications to create a new key pair for the email noted (matrix@matrix.org)

Thank you. 

Use StartPage.com and/or DuckDuckGo.com

**Comment by richvdh** [comment]
Please go to #synapse:matrix.org for support questions.
