### ISSUE TITLE
synapse_port_db not set up to handle boolean redactions and room_stats_state columns

### ISSUE THREAD

**Issue by marvinwankersteen** [matrix-org/synapse#6221]
### Steps to reproduce

- Installed synapse with SQlite database
- I have not more information. The installation is 1-2 years old

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Selfhosted

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: v1.4.0

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**: - Docker: `avhost/docker-matrix:v1.4.0`
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

Today I tried to migrate from SQlite to Postgres and the `synapse_port_db` throws two exceptions:

First one:
```
Traceback (most recent call last):
  File "/usr/local/bin/synapse_port_db", line 539, in runhomeserver.db postgresql
    [self.handle_table(*res) for res in setup_res], consumeErrors=True
twisted.internet.defer.FirstError: FirstError[#21, [Failure instance: Traceback: <class 'psycopg2.errors.DatatypeMismatch'>: column "have_censored" is of type boolean but expression is of type integer
LINE 1: ...<homeserver-url>', '$1522530083418SjkrH:<homeserver-url>', 1, 1522530...
                                                                      ^
HINT:  You will need to rewrite or cast the expression.

/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/bin/synapse_port_db:349:handle_table
/usr/local/lib/python3.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/dist-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/dist-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/usr/local/lib/python3.7/dist-packages/twisted/python/compat.py:464:reraise
/usr/local/lib/python3.7/dist-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/usr/local/bin/synapse_port_db:137:r
/usr/local/bin/synapse_port_db:337:insert
/usr/local/bin/synapse_port_db:171:insert_many_txn
/usr/local/lib/python3.7/dist-packages/synapse/storage/_base.py:154:executemany
/usr/local/lib/python3.7/dist-packages/synapse/storage/_base.py:177:_do_execute
]]
```

Second one:
```
Traceback (most recent call last):
  File "/usr/local/bin/synapse_port_db", line 540, in run
    [self.handle_table(*res) for res in setup_res], consumeErrors=True
twisted.internet.defer.FirstError: FirstError[#71, [Failure instance: Traceback: <class 'psycopg2.errors.DatatypeMismatch'>: column "is_federatable" is of type boolean but expression is of type integer
LINE 1: ...ite', 'shared', 'm.megolm.v1.aes-sha2', NULL, NULL, 1, NULL)
                                                               ^
HINT:  You will need to rewrite or cast the expression.

/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/bin/synapse_port_db:350:handle_table
/usr/local/lib/python3.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/dist-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/dist-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/usr/local/lib/python3.7/dist-packages/twisted/python/compat.py:464:reraise
/usr/local/lib/python3.7/dist-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/usr/local/bin/synapse_port_db:138:r
/usr/local/bin/synapse_port_db:338:insert
/usr/local/bin/synapse_port_db:172:insert_many_txn
/usr/local/lib/python3.7/dist-packages/synapse/storage/_base.py:154:executemany
/usr/local/lib/python3.7/dist-packages/synapse/storage/_base.py:177:_do_execute
]]
```

I fixed it by adding the following lines to the `synapse_port_db`:
```
BOOLEAN_COLUMNS = {
    ..
    ..
    "redactions": ["have_censored"],
    "room_stats_state": ["is_federatable"],
}
```
The script runs without problems and it looks like there are no issues with the clients. Everything looks fine.

Is there more that I could have done?

**Comment by neilisfragile** [comment]
cc @babolivier

**Comment by babolivier** [comment]
Will be fixed in https://github.com/matrix-org/synapse/pull/6102
