### ISSUE TITLE
Possible spec violation? `m.room.message` with empty content field

### ISSUE THREAD

**Issue by hugecheese** [matrix-org/synapse#6225]
When doing my initial `/sync` from the https://matrix.org homeserver, I got back the following event:
```json
{
  "content": {},
  "event_id": "$BPPs0MTfE4y-8F58bmvITRM7rz4YATGtOvBcQhPBWaY",
  "origin_server_ts": 1571015847357,
  "sender": "@bowdown097:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 513533411,
    "redacted_because": {
      "content": {},
      "event_id": "$QjO7JJsn_KmuudfkpSLr-TYOT7BuemfwzsbsIuI5qtc",
      "origin_server_ts": 1571016502195,
      "redacts": "$BPPs0MTfE4y-8F58bmvITRM7rz4YATGtOvBcQhPBWaY",
      "sender": "@bowdown097:matrix.org",
      "type": "m.room.redaction",
      "unsigned": {
        "age": 512878573
      }
    },
    "redacted_by": "$QjO7JJsn_KmuudfkpSLr-TYOT7BuemfwzsbsIuI5qtc"
  }
}
```

[The spec states](https://matrix.org/docs/spec/client_server/r0.5.0#m-room-message) that any event with the type `m.room.message` must always have the `body` and `msgtype` fields.

**Comment by turt2live** [comment]
The event was redacted, so this is expected.

**Comment by hugecheese** [comment]
@turt2live I see, but why aren't the fields marked as optional? If they might not be present because of a redaction, then I don't think they should be marked as **Required**

**Comment by turt2live** [comment]
That's where the spec is a bit unclear: I believe the theory is that the fields are required to *send*, but not *receive*. A redaction affects the event in ways after it has been sent, so it naturally can force the event to lose otherwise required fields.

In practice, implementations should be resilient to malformed event contents.
