### ISSUE TITLE
m.room.join_rules event served in an EventContent

### ISSUE THREAD

**Issue by hugecheese** [matrix-org/synapse#6233]
This event was served by the matrix.org homeserver:
```json
{
  "content": {
    "join_rule": "invite"
  },
  "sender": "@kriposross:matrix.org",
  "state_key": "",
  "type": "m.room.join_rules"
}
```
It was inside the invite state `EventContent` from `/sync`. The full chain would be:
```js
sync.rooms.invite['foo'].invite_state.events[0].content
```
The `EventContent` type does not have any `join_rule` field. It seems as though the `State Event` type was served in the invite state events, even though [the spec states](https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-sync) all invite state events are of the type `StrippedState`.

**Comment by turt2live** [comment]
`EventContent` is just a JSON object, it's content is dependent upon the event type. What does the full sync response look like?

**Comment by hugecheese** [comment]
Well the `EventContent` type is defined three times in the spec, and each time it's the same thing, I assumed this was what it's always supposed to be:
![image](https://user-images.githubusercontent.com/56557725/67236656-b2a39180-f417-11e9-896c-d452cc1459de.png)

If it's not, then why does the spec sometimes refer to state events as `State Event` (like for `sync.rooms.join.state.events`, which is `[State Event]`), but other times as `EventContent`.

Here's a dump of all the invite states (`sync.rooms.invite`): https://pastebin.com/d5bxyfZx. I didn't do the whole `/sync` because it's like 500k lines.

**Comment by hugecheese** [comment]
@turt2live Upon looking further looking into that pastebin I just posted, I realized that this is happening as a `StrippedState` isn't even being served at all:
![image](https://user-images.githubusercontent.com/56557725/67237884-234bad80-f41a-11e9-9fb2-4ec7c88de937.png)

The JSON has fields like `origin_server_ts`, `event_id` and `unsigned`, which are only present in the full state event:
![image](https://user-images.githubusercontent.com/56557725/67237940-424a3f80-f41a-11e9-8b80-a9c0e157a7b0.png)

Maybe the spec is out of date and the invited rooms are actually just full `State Event`'s, rather than `StrippedEvents`'s?

**Comment by turt2live** [comment]
The spec does not define schemas that are unique across all endpoints/events - they are localized to their headings. This means that although EventContent is defined several times, they are contextually only relevant under their respective headings - you cannot mix an EventContent from one event into another endpoint. There is an argument to change this, but that's a different problem.

Extra fields are allowed in JSON, and the pastebin looks spec-compliant to me. I don't believe there's a Synapse issue here.

**Comment by hugecheese** [comment]
@turt2live Spec compliance aside, it's serving a different type of event (`State Event` rather than `Stripped State`) in some cases.

What does this mean for a client? Should I just assume all `StrippedEvent`'s are actually `State Event`'s to potentially get more information?

Also, don't you think it would be a bit clearer if any non-defined `EventContent` was renamed to `object`?

**Comment by turt2live** [comment]
The `EventContent` issue is best dealt with in the spec, not synapse. I have different opinions on that front.

As for clients: you can't assume that it's a state event. It's a stripped event, and Synapse happens to send extra stuff. You can't rely on that extra stuff, whatever it is, being there.

**Comment by hugecheese** [comment]
@turt2live thanks for the info!
