### ISSUE TITLE
Trying to start synapse service - PostgreSQL - undefined symbol: PQencryptPasswordConn

### ISSUE THREAD

**Issue by mikkel1156** [matrix-org/synapse#6244]
When trying to start the matrix-synapse service, it ends up exiting with this error I got from systemctl status:
```
matrix-synapse[10309]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
matrix-synapse[10309]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
matrix-synapse[10309]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
matrix-synapse[10309]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
matrix-synapse[10309]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
matrix-synapse[10309]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/psycopg2/__init__.py", line 50, in <module>
matrix-synapse[10309]:     from psycopg2._psycopg import (                     # noqa
matrix-synapse[10309]: ImportError: /opt/venvs/matrix-synapse/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PQencryptPasswordConn
```
To me it looks like something is wrong with my psycopg2 package/library. Is that correct?

I do not know if this is related to trying to create the server from scratch again. Got it working the first time but it used a matrix subdomain as server_name, so wanting to just use my base domain for representing the server.
Since resources online said I had to start from scratch, I decided to try removing it with `apt purge matrix-synapse-py3` and removing the left over folders such as in `/etc `and `/var/log` - then installing it again afterwards.

The first time around I was using SQLite, but wanted to use PostgreSQL instead so it has been configured to use that in the config from following the docs on here. Config basically looks like this:
```
database:
    name: psycopg2
    args:
        user: "synapse_user"
        pass: "SuperSecretPassword"
        database: "synapse"
        host: "127.0.0.1"
        cp_min: 5
        cp_max: 10
```

I've had no luck trying to Google this error myself.

# Info
Running Synapse version 1.4.1 from matrix.org Debian repo
System: Debian 10.1

**Comment by anoadragon453** [comment]
What version of `psycopg2` are you running? There seems to be a bug with v2.8.2-1 according to [this bug report](https://bugs.archlinux.org/task/62463).
