### ISSUE TITLE
CPU in ReplicationSendEventRestServlet has ~doubled since Oct 11

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6285]
Since matrix.org's synapse was restarted on Oct 11, it seems like ReplicationSendEventRestServlet is using roughly twice as much CPU per request. This makes for quite a noticeable change in CPU usage (even though it's only a few % of a core).

<img width="916" alt="Screenshot 2019-10-29 at 22 28 43" src="https://user-images.githubusercontent.com/1294269/67814333-b67c8700-fa9b-11e9-9fc2-8dd290b3edb2.png">
<img width="1841" alt="Screenshot 2019-10-29 at 22 31 13" src="https://user-images.githubusercontent.com/1294269/67814381-d90ea000-fa9b-11e9-8a4a-728b87465c93.png">

I found this while wondering why the synapse master started taking 20-30% more CPU as of Oct 14th.

**Comment by richvdh** [comment]
our best idea for this was that it came back on a VM with different performance characteristics.
