### ISSUE TITLE
Users can't be found, which registred via LDAP

### ISSUE THREAD

**Issue by Bazis007** [matrix-org/synapse#6290]
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by Bazis007** [comment]
homeserver.py version 1.5.0
Postgress 11
Centos 7

I setup authorization via LDAP. When user login, this user can not be found via search
(_matrix/client/r0/user_directory/search) => {   "limited": false,   "results": [] }
Also sql querry return 0 rows.

But if user change own name, user become searchable.

I think it can be problem in LDAP module in user creation part.

Please, look on screenshot. a.s.polyakov not searchable and neve change own name.
other users was change own name and can be found.

![image](https://user-images.githubusercontent.com/33661355/67852500-91c8f380-fb1d-11e9-857a-3f4bd74132de.png)

**Comment by richvdh** [comment]
this appears to have fallen through the cracks. Closing as it's presumably no longer relevant.
