### ISSUE TITLE
Implement MSC1802 (clean up federation responses)

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6293]
https://github.com/matrix-org/matrix-doc/pull/1802

**Comment by babolivier** [comment]
https://github.com/matrix-org/synapse/pull/6349 has been approved, the only item pending is sytests for it, I'll move this issue back to "In progress" until there's actually something to review.

**Comment by babolivier** [comment]
#6349 and https://github.com/matrix-org/sytest/pull/760 are now merged, the only thing left to test is the `/send_leave` endpoints which I'll do as a second step.

**Comment by babolivier** [comment]
Tests for `/send_leave` are tracked in https://github.com/matrix-org/sytest/issues/770, closing this since MSC1802 is actually implemented in Synapse now.
