### ISSUE TITLE
to_device messages get lost due to to_device stream id not being saved

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#6311]
In schema delta 35, synapse added an entry into the `device_max_stream_id` table (https://github.com/matrix-org/synapse/blob/develop/synapse/storage/data_stores/main/schema/delta/35/device_stream_id.sql). Full schema 54 has now been cut which means this schema delta file isn't being run for new installs as of 1.0 (when full schema 54 was released) so it looks like these synapse installs never get an entry in `device_max_stream_id`. It's written to by an `UPDATE` clause so no entry is created if one doesn't already exist.

It doesn't look like it gets created anywhere else. If not, this means the device stream token resets any time synapse is restarted which causes to_device messages to go missing, causing Unable To Decrypt errors.

Same bug may apply to `appservice_stream` as that appears to do the same thing

**Comment by erikjohnston** [comment]
We probably want to go and audit all tables that expect to have a row in them.

The easiest fix for this is probably to upsert rather than update. Now that we have native upsert support that should not have too much of a performance penalty.

**Comment by anoadragon453** [comment]
A fix for this is available here: https://github.com/matrix-org/synapse/pull/6375 It fixes the schema instead of using an UPSERT.

Closing this one and made another issue for investigating related tables: https://github.com/matrix-org/synapse/issues/6381

**Comment by anoadragon453** [comment]
Err, actually I'll wait until that PR is closed huh.

**Comment by anoadragon453** [comment]
This should be fixed for this specific instance by https://github.com/matrix-org/synapse/pull/6555

`appservice_stream` and others is covered by https://github.com/matrix-org/synapse/blob/8568704d2aaf9257641e0995a73669a40681b1c5/synapse/storage/data_stores/main/schema/full_schemas/54/stream_positions.sql#L2
