### ISSUE TITLE
Ability to translate/set Email Subjects

### ISSUE THREAD

**Issue by MamasLT** [matrix-org/synapse#6324]
Hello.
I have translated Email templates to my language, but the Email subject is hard coded and it cannot be changed. Why is that?
Maybe an option to change Email Subjects in HS config, or other template file would make more sense? 
Also, as far as im aware, templates do not support UTF-8 coding, so symbols of other languages are not displayed properly. is there any way to fix that?

Thank You very much.

**Comment by richvdh** [comment]
dup #6112
