### ISSUE TITLE
No Push Notification on invitations

### ISSUE THREAD

**Issue by ChristianPauly** [matrix-org/synapse#6366]
### Description

I'm working on my own dead simple Push Gateway and it seems like that synapse isn't sending push notifications on new invitations, means m.room.member events.

### Steps to reproduce

- Look at the logs of your push GW
- Send an invitation to a new room
- See that Synapse is sending push notifications on new messages but not on m.room.member events

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: Looks like all current synapse installations

**Comment by ChristianPauly** [comment]
Yesterday I got such a notification. But I can't reproduce it. Sometimes it is working and sometimes not.

**Comment by richvdh** [comment]
ok, we'll need synapse logs demonstrating the incorrect behaviour.

**Comment by ChristianPauly** [comment]
Hey, now the bug seems to be gone. I can't reproduce this anymore and push notifications are received by the GW perfectly. Sorry for that, maybe its not a bug...
