### ISSUE TITLE
Phone numbers and homeserver, Failed handle request via 'MsisdnThreepidRequestTokenRestServlet'

### ISSUE THREAD

**Issue by PhieF** [matrix-org/synapse#6372]
Hi,

I'm having trouble to add phone numbers to my matrix server

I've set this as a config 

account_threepid_delegates:
msisdn: https://matrix.org

as config, when I try to add a phone number, I get an internal server error, but I receive the sms on my phone

Here is the server log https://framabin.org/p/?c3ba6b4751d7fbe6#su0JnnOyZ9aD6Re/oseNMAwrlggoxDhdzXjnzq4xv6o=
any ideas ?

It has the same issue with vector.im 

### Version information

- **Homeserver**: lostpod.me

- **Version**: 0.34.0.1

- **Install method**:
deb 

- **Platform**:
Ubuntu 18.04

**Comment by richvdh** [comment]
> Version: 0.34.0.1

this is *WAY* out of date and unsupported. I don't think it has support for `account_threepid_delegates`, so I don't think you're actually using that version.

The log suggests the problem is that you haven't set a public_baseurl in your config. I've raised #6375 to track the poor behaviour.

**Comment by PhieF** [comment]
err that's the latest deb version :( perhaps they are not the same version but I could get synapse version the _synapse/admin/v1/server_version endpoint doesn't show anything so I took the deb version

**Comment by richvdh** [comment]
> err that's the latest deb version :

then you are looking at the wrong package.

**Comment by richvdh** [comment]
not to 0.34.0.1 it wasn't.

https://packages.matrix.org/debian/pool/main/m/matrix-synapse-py3/: latest is 1.5.1

**Comment by PhieF** [comment]
Yes but I can now get the version through curl and it is  "server_version": "1.5.1"

as I said 0.34.0.1 is the version of the deb package, I couldn't get the version number through curl so I said the only version number I had access to

**Comment by richvdh** [comment]
> as I said 0.34.0.1 is the version of the deb package

no, it's not. Again, you're looking at the wrong package. The package you care about is matrix-synapse-py3.

**Comment by PhieF** [comment]
Hm ok so I might have them both, sorry for the mistake
