### ISSUE TITLE
Correct way to completely disable federation ?

### ISSUE THREAD

**Issue by Graphicscore** [matrix-org/synapse#6395]
I'm looking for almost an hour now but I can't seem to find a correct answer.

What is the correct way to completely disable federation.

I want my synapse server to talk to my clients only. No external clients and no data sharing.

Do I just block port 8443 ? Or do I add an empty whitelist in the config ? What do i have to do

I have seen some comments on issues but they aren't really straight forward.

**Comment by neilisfragile** [comment]
This is related to https://github.com/matrix-org/synapse/issues/2619 which is fixed by https://github.com/matrix-org/synapse/pull/2820

So you need to set an empty list for ```federation_domain_whitelist:``` and then firewall off your end point.

**Comment by neilisfragile** [comment]
I opened https://github.com/matrix-org/synapse/issues/6401 to make this clearer
