### ISSUE TITLE
device list can get out of sync because you don't get m.device_list_updates unless you share a room with that user (causing UISIs)

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6399]
@benbz's server has ended up in a spectacular mess where its device_lists for me & Amandine are several years old - log details in https://github.com/matrix-org/riot-ios-rageshakes/issues/3483.

I have a hunch that what's happened is that:
 * Ben sets up server
 * Temporarily joins some (encrypted?) room, years ago, thus getting a copy of Amandine & my keys
 * Subsequently is in a private room with us which gets upgraded to E2E
 * ...but the upgrade to E2E doesn't trigger a check of our device lists by calling matrix://matrix.org/_matrix/federation/v1/user/keys/query, so the server blindly uses the ancient E2E keys.
 * Amandine & I rarely log in on our main accounts, so we never send new m.device_list_update EDUs from matrix.org, so the device list is never corrected.

This is kinda similar to https://github.com/matrix-org/synapse/issues/4827 or https://github.com/matrix-org/synapse/issues/5433. 

Possible solutions:
 * If you receive a reference to an unrecognised device from a server, you should refresh your cache of that user's devicelist (useful defensive measure anyway)
 * Ensure that device list caches are flushed when you lose contact with a user, or re-populated when you regain contact

**Comment by benbz** [comment]
I set this HS up in late 2017 and I recall that I joined #offtopic:matrix.org for a short while before leaving that room. I didn’t use this HS for anything other than talking to TomL until very recently

**Comment by ara4n** [comment]
from a related Tchap issue: 

> [add_messages_to_device_inbox](https://github.com/matrix-org/synapse-dinsic/blob/c413540fb9e4b6ee2ec975a98676ea56d12249c8/synapse/storage/deviceinbox.py#L218) experienced a database failure and couldn't send a to_device message to another user. Checking whether this function is tolerant to failures and its job retried afterwards may help fix things.
