### ISSUE TITLE
parameter mismatch in register.py _register_email_threepid()

### ISSUE THREAD

**Issue by syamgk** [matrix-org/synapse#6406]
Hit this below error on our homeserver while trying the LDAP integration.

TypeError: _register_email_threepid() takes 4 positional arguments but 5 were given

https://github.com/matrix-org/synapse/blob/9ffcf0f7ba72f16e366f04db6384a9233b1808cb/synapse/handlers/register.py#L260 

I think this should be 
```yield self._register_email_threepid(user_id, threepid_dict, None)```
@hawkowl @anoadragon453 will send a patch if any of you can just validate 

many thanks

**Comment by anoadragon453** [comment]
@syamgk This indeed seems to be a problem. A patch would be very welcome :)

**Comment by syamgk** [comment]
here it is https://github.com/matrix-org/synapse/pull/6441

**Comment by richvdh** [comment]
fixed by #6441
