### ISSUE TITLE
Move /groups from master process

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#6415]
No reason for it to be on master, should help CPU-bound homeservers running in worker mode.

**Comment by richvdh** [comment]
this applies to groups apis other than /groups itself; /joined_groups may be a larger culprit

**Comment by neilisfragile** [comment]
/joined_groups, /publicised_groups, /groups/.../profile, /groups/.../rooms

**Comment by richvdh** [comment]
fixed by #6866 I guess
