### ISSUE TITLE
Error sending threepid validation email ... yield send_email_func(email_address, token, client_secret, session_id) ValueError: unsupported format character 'S' (0x53) at index 7

### ISSUE THREAD

**Issue by plamenh** [matrix-org/synapse#6422]
### Description

Cannot register with an e-mail address.

### Steps to reproduce

- try to register with a supplied e-mail address
- 'An error was encountered when sending the email' error on frontend
- error in the title in backend

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

When trying to supply an e-mail at register, we get the error in the title.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 1.5.1+bionic1

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.5.1+bionic1

- **Install method**: Debian through matrix-synapse repo
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 18.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

I already tried changing the shared_secret (remove '%' from it). Also checked email_address, token, client_secret, and session id, they don't have any strange characters, especially capital 'S'.

**Comment by plamenh** [comment]
I was able to fix it, still believe this is a bug that should be addressed. Problem was in homeserver.yaml:

`notif_from: "%(app) Server <matrix`

changed it to:

`notif_from: "%(app) server <matrix`

and it worked.

Using capital S breaks the email sending, this seems like a very strange bug. Escape it somewhere in code or at least add a comment to the documentation (don't use a Capital S?).

**Comment by richvdh** [comment]
you need `%(app)s`, not `%(app)`

**Comment by plamenh** [comment]
@richvdh Not really. The issue is completely different. I managed to find a workaround (my previous comment), but this is definitely a limitation that at least needs to be documented.

**Comment by richvdh** [comment]
Have you tried writing `notif_from: "%(app)s Server <matrix...` ?

**Comment by plamenh** [comment]
This works:

`"%(app) server <matrix`

Probably your solution works as well. Just saying it's a good idea for it to be documented somehow (here in github or in homeserver.yaml comments).

**Comment by richvdh** [comment]
> This works:
> 
> `"%(app) server <matrix`

are you sure? Have you checked what comes out?

**Comment by richvdh** [comment]
@plamenh does https://github.com/matrix-org/synapse/pull/6423/files#diff-8b49bb218a1d7b96778287934cc311eaR1277 help to clarify that? Feel free to comment on that PR if you have further suggestions

**Comment by plamenh** [comment]
Ok, you might have a point there. What I get in the from field is:

**Matrixerver** instead of **Matrix server**
