### ISSUE TITLE
Admins should be able to list all rooms on the server

### ISSUE THREAD

**Issue by rxl881** [matrix-org/synapse#6424]
**Description:**

It would be incredibly useful for server admins to be able to list all rooms on the server (together with the room names / aliases).

This could be used together with media store APIs etc. to list a breakdown of resource usage per room. It could also be used along with the room shutdown and room purge APIs etc.

It would be good to have this asap., as all of these features are being requested by users.

**Comment by rxl881** [comment]
@neilisfragile -- This is probably my #1 request for Synapse admin API features right now.

**Comment by anoadragon453** [comment]
Since calculating the name for each room isn't trivial, and thus the query may take a long time on a server with many, many rooms, I think it best to make this endpoint support pagination.

Here's a quick design I threw together:

Request:

```
POST /_synapse/admin/v1/get_rooms

{
  "offset": 0,  # default 0
  "limit": 50   # if not provided, no limit will be applied
}
```

Response:

```
{
  "total": 1234  # The total number of rooms
  "rooms": [
    {
      "id": "!abcdefg1234:example.com",  # The ID of the room
      "name": "My Great Room!",          # The name of the room
      "alias": "#greatroom:example.com"  # Optional, main room alias
    },
    { ... }
  ]
}
```

If offset + limit spills over the end of the room list (e.g. offset 0 + limit 50 for 45 total rooms) only 45 rooms will be returned.

**Comment by rxl881** [comment]
Thanks @anoadragon453. This looks good and would definitely be better than nothing. However, for this to be really useful, is it possible to do any sort of server-side sorting of the rooms, e.g. by name or creation date? Also, is it possible to search / filter the results? E.g:

```
{
  "offset": 0,  # default 0
  "limit": 50,   # if not provided, no limit will be applied,
  "sort": {
    "roomName": -1,
  }
  "match: {
    "roomName": "^needle.*"
  }
}
```

**Comment by anoadragon453** [comment]
@rxl881 Heads up that this is how this API has shaped up: https://github.com/matrix-org/synapse/blob/ed5457c28b0a0e17398c403f0ecef26f8678f3e0/docs/admin_api/rooms.md

Let me know what you think.

**Comment by rxl881** [comment]
@anoadragon453 -- That looks absolutely perfect. Thanks!!!

**Comment by anoadragon453** [comment]
This is done in https://github.com/matrix-org/synapse/pull/6720
