### ISSUE TITLE
Delete a room (Admin API)

### ISSUE THREAD

**Issue by rxl881** [matrix-org/synapse#6425]
**Description:**

Server admins are requesting a way to "delete rooms" and it would be good to create some tooling to help with this.

It is possible that this could just be a call to the "room shutdown" API (currently undocumented?) followed by a call to "room purge" admin API? But it would be good to know if this is the correct way to be doing so, and is probably beneficial to combine it in to a single API call?

**Comment by richvdh** [comment]
>   "room shutdown" API (currently undocumented?) 

https://github.com/matrix-org/synapse/issues/4784

I really wish people wouldn't write APIs without documenting them,

**Comment by vapaa** [comment]
is there any progress on this topic?

**Comment by neilisfragile** [comment]
Impl here https://github.com/matrix-org/synapse/pull/2291
Doc'd here https://github.com/matrix-org/synapse/pull/6541

**Comment by aaronraimist** [comment]
@neilisfragile wasn't the request here for a new API that would combine the room shutdown API and the purge room API into one request?

**Comment by neilisfragile** [comment]
@aaronraimist good point, thanks for the catch.

**Comment by awesome-manuel** [comment]
The API should be `DELETE /admin/v1/rooms/<room-id>`
Internally the API should:
- Kick all Users from this room
- Purge room content
- Remove room
