### ISSUE TITLE
Admin room info API

### ISSUE THREAD

**Issue by rxl881** [matrix-org/synapse#6427]
**Description:**

It would be useful for server admins to have access to basic room level stats, e.g.:

* Room complexity / number of state events
* Room version / date of creation
* Number of members
* Encryption status etc.

This is probably linked with https://github.com/matrix-org/synapse/issues/6424, for listing server rooms.

**Comment by aaronraimist** [comment]
Related:  #2338

**Comment by clokep** [comment]
I believe all the requested features are included in #7225.
