### ISSUE TITLE
Include LDAP Support in Docker Image

### ISSUE THREAD

**Issue by DarkRider1768** [matrix-org/synapse#6430]
Hey,

We are currently working on deploying Synapse in our environment but the Docker Image doesn't contain LDAP support (requires a full OS install to get working). We would like to deploy this to our Kubernetes cluster, and have tested it with this setup, but the lack of LDAP is blocking us. We are currently working on building a custom Docker Repo that will allow us to generate our own images but have hit a snag in that deployment.

Can you include the deployment of the LDAP feature in the Dockerfile for future builds? We can't be the only ones who would find this extremely useful.

**Comment by richvdh** [comment]
as far as I'm aware it is included:

```
$ docker run --rm --entrypoint ls matrixdotorg/synapse -l /usr/local/lib/python3.7/site-packages/ldap_auth_provider.py
-rw-r--r--    1 root     root         14525 Nov 26 14:21 /usr/local/lib/python3.7/site-packages/ldap_auth_provider.py
```

what problem are you seeing, exactly?

**Comment by richvdh** [comment]
let's reopen this if we get more information as to what it means.
