### ISSUE TITLE
AdminAPI whois should contain more informations

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#6439]
`GET /_synapse/admin/v1/whois/<user_id>` should contain:
- whether the account is **deactivated** (_deactivated_)
- whether it's a **guest account** (_is_guest_)
- whether it's an **admin account** (_admin_)

(Additionally it would be neat to have an admin api to get the list of all users, or filtered by simple criteria, like *is_guest*, *admin*, *deactivated*.)

**Comment by richvdh** [comment]
You may find that much of this is provided by https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#list-accounts

**Comment by grinapo** [comment]
_Maybe_ this would justify a documentation redirect/mention.

**Comment by richvdh** [comment]
> the users endpoint can't filter on user name

Isn't that what the `user_id` parameter does?

**Comment by grinapo** [comment]
I really should read all the flowing texts and not just the (non-exhaustive, as it turns out) example. You're right. This doc seriously needs some love. I'd like to try to PR it someday....

**Comment by richvdh** [comment]
sounds like this is not a bug.
