### ISSUE TITLE
Wrong display of room visibility in communities

### ISSUE THREAD

**Issue by vmario89** [matrix-org/synapse#6442]
Hi, since all recent Matrix Synapse versions i got this displayed message which i tihnk is wroing/irritating:

Ich habe rooms which contents are only visible for invited people. but including them into community displays "readable for all". But it's not the case.

https://riot.fablabchemnitz.de/#/group/+stadtfabrikanten:matrix.fablabchemnitz.de

![grafik](https://user-images.githubusercontent.com/5631071/69890445-f7172c80-12f5-11ea-8cc8-a3833aed181d.png)
![grafik](https://user-images.githubusercontent.com/5631071/69890447-ff6f6780-12f5-11ea-9ada-9b8d787c7a0d.png)

**Comment by richvdh** [comment]
can you show which API is giving incorrect results, what the results of that API are, and what you think they should be?

**Comment by vmario89** [comment]
Hi. I did not write anything about API. You can see in the screenshot that the room "FabLab Chhemnitz Vostand" is readonly for members and only invited persons can join the room. But its shown as "every body can read" in community. thats confusing because its just not the case

**Comment by richvdh** [comment]
> I did not write anything about API. 

yup, that's the problem. I'm asking you to do a little research to help us solve the issue.

**Comment by richvdh** [comment]
I'm going to close this pending a clearer description of the problem

**Comment by vmario89** [comment]
Hi - sorry for that. I am not a deleloper - i am a user and admin who tries to work with Matrix eco system. to update, configure and deploy the stuff. Researching in code is not the case for me. But i try to describe the problem again and with english screenshots to hopefully better describe:

I got this community:
![grafik](https://user-images.githubusercontent.com/5631071/70849603-1333d580-1e81-11ea-84e8-7a53550c7adb.png)

Clicking into shows:
![grafik](https://user-images.githubusercontent.com/5631071/70849612-2a72c300-1e81-11ea-86fa-31d9aa67dca5.png)

There are three rooms which are labeled with "World readable". and "Guests can join".
![grafik](https://user-images.githubusercontent.com/5631071/70849617-3f4f5680-1e81-11ea-8c03-ae27685c2c7d.png)

One of them definitely dos not fit under that headline: Viewing the room details of "FabLab Chemnitz Vorstand" this room is not allowed to be joined by guests and it is not public, as you can see in the following image:
![grafik](https://user-images.githubusercontent.com/5631071/70849621-50986300-1e81-11ea-918d-6940fc1672a4.png)

so my claim is: the configuration of room privacy does not fit to the label "world readable". Because only invited people can access.

kind regards, Mario

**Comment by richvdh** [comment]
ok. Be aware that communities are an experimental feature so it's unlikely this will be a priority for us to investigate.

**Comment by vmario89** [comment]
problem solved. i just overlooked the correct option for it. its really tedious to find because its too hidden in my opinion: 
![grafik](https://user-images.githubusercontent.com/5631071/71788482-f8d5bd80-3022-11ea-8ea9-bd3d578d1bdf.png)

problem: only the creator of the community is able to change this and to see those options. But at the moment the creator of the community is not able to grant other users the option to manage the community. i think it would make sense to allow other users to configure communities too. So other users would see those general options too.

**Comment by vmario89** [comment]
edit: i think its a problem of the user interface of Riot but it may depend on the protocol implementation too because its a question of general concept?

**Comment by richvdh** [comment]
Sounds like a UI problem. Thanks for letting us know you solved it
