### ISSUE TITLE
while scanning for the next token found character '%' that cannot start any token

### ISSUE THREAD

**Issue by salotaibistc** [matrix-org/synapse#6448]
### Description

I am trying to run Synapse so I created a new homeserver.yaml for me locally and I copied the contents ../docker/conf/homeserver.yaml in it. 

When I try to run synapse using `python3 -m synapse.app.homeserver -c homeserver.yaml` I am faced by the following error:

<img width="454" alt="Screen Shot 2019-12-02 at 3 38 28 PM" src="https://user-images.githubusercontent.com/56390103/69960216-f52db300-1519-11ea-9851-84d666eece24.png">

### Steps to reproduce
- Trying to run Synapse with `python3 -m synapse.app.homeserver -c homeserver.yaml`.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->

- Python3.
- Synapse 1.5.0

<!-- examples: package manager/git clone/pip  -->

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by neilisfragile** [comment]
The docker homeserver.yaml is expecting to be populated by environment variables so you can't use it for non docker use.

If you want to run from source then you need to follow the install instructions [here](https://github.com/matrix-org/synapse/blob/master/INSTALL.md)

For support requests please use our channel rather than the issues list
https://matrix.to/#/#synapse:matrix.org

**Comment by salotaibistc** [comment]
Sorry for disturbing and THANK YOU VERY MUCH!
