### ISSUE TITLE
We should have an admin api to delete local media

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6459]
For various reasons, it is useful to be able to remove pieces of media from the local content repo. Ideally we'd have an API to do this, which also removes any associated thumbnails.

We have the quarantine_media API, but (a) that applies to rooms rather than individual bits of media (#5956), and (b) it doesn't actually delete the media.

It's also somewhat separate to the ability of users to remove their own media (see https://github.com/matrix-org/matrix-doc/issues/790), which again probably wouldn't actually delete the media files (to allow for moderation), and *would* send a deletion request over federation.

It's closely related to #3479, though that is more about finding the media.

**Comment by dklimpel** [comment]
@richvdh I think about it to write this API. What ist to do? Delete files is only on part. Should we also delete events? Or do you have a hint what is to do (DB tables or anything else)?

**Comment by richvdh** [comment]
@dklimpel for this, I was definitely *not* thinking of deleting events that reference the media: not least because that is hard to do reliably.

If I remember rightly, the reason I wanted this was to remove some large videos that someone had uploaded to our server, without correct copyright.

I think that the things we need to delete, beyond the file media itself, are:
 * any rows in the `local_media_repository_thumbnails` / `remote_media_cache_thumbnails` tables, and the corresponding thumbnail files.
 * the row in the `local_media_repository` / `remote_media_cache` tables.

**Comment by anoadragon453** [comment]
This looks to have been completed now in https://github.com/matrix-org/synapse/pull/8519. Thanks @dklimpel!
