### ISSUE TITLE
Voice channel like in Discord

### ISSUE THREAD

**Issue by Per0x** [matrix-org/synapse#6471]
Hi

It would be nice if Matrix integrate this feature. Voice call and video calls should be different than Skype, make it original :)

(This request is a copy of the one from @Majaspic on riot github https://github.com/vector-im/riot-web/issues/3546)

**Comment by ara4n** [comment]
this isn't really a synapse thing but a client & spec thing - vector-im/riot-web#3546 is the right place to track it.

meanwhile https://github.com/vector-im/riot-web/issues/5993 is quite close too.

**Comment by Per0x** [comment]
Sorry, since it requires adding audio codecs, and specific protocols because it won't work in P2P, I thought it was a server issue.

**Comment by ara4n** [comment]
even if it needs an conferencing server, this isn't something synapse would provide - it would be separate like today's jitsi setup.

**Comment by samjco** [comment]
see:
https://github.com/vector-im/riot-web/issues/5993#issuecomment-583277279
https://github.com/vector-im/riot-web/issues/5993#issuecomment-583282283
https://github.com/vector-im/riot-web/issues/5993#issuecomment-587996067

**Comment by hedho** [comment]
How about support of Mumble server for voice channels !!

**Comment by ShadowJonathan** [comment]
@hedho please open an issue in https://github.com/matrix-org/matrix-doc or https://github.com/vector-im/element-web for that suggestion
