### ISSUE TITLE
Link to user_directory SQL commands wrong

### ISSUE THREAD

**Issue by schwukas** [matrix-org/synapse#6474]
Minor thing:

The link to the SQL commands that should be executed after enabling the user_directory in [this piece of documentation](https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md) is dead and should be replaced with [this updated link](https://github.com/matrix-org/synapse/blob/master/synapse/storage/data_stores/main/schema/delta/53/user_dir_populate.sql).

I had people ask several times now in #synapse because they couldn't find it.

Not really worth a PR but I will gladly create one if so desired :slightly_smiling_face:

**Comment by richvdh** [comment]
yes, good spot.

a PR would certainly help with our process. thanks!

**Comment by schwukas** [comment]
I just realized this has been fixed by 24cc31ee967e5c387a137e22b428dcea17fc9fa5 but wasn't yet merged into the master branch. Sorry for the confusion!
