### ISSUE TITLE
Can't create room with initial_state and a state_key that is an mxid

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/synapse#6475]
### Description

When creating a room via the `/createRoom` endpoint and you try to set an `initial_state` with a non-member event that has the state key of an mxid you get `M_FORBIDDEN`: You are not allowed to set others state.

Example:
```
{
  "invite": ["@alice:matrix.org"],
  "initial_state": [
    {
      "type": "com.example.custom",
      "state_key": "@alice:matrix.org",
      "content": {"blah": "blubb"},
    }
  ]
}
```

### Steps to reproduce

- create a room that contains a default state event with the state key of an mxid

### Version information

- **Homeserver**: matrix.org

**Comment by Sorunome** [comment]
Culprit seems to be that [this](https://github.com/matrix-org/synapse/blob/master/synapse/event_auth.py#L372-L375) doesn't check if the event is an `m.room.member` event

**Comment by richvdh** [comment]
https://matrix.org/docs/spec/client_server/r0.6.0#state-event-fields: "With the exception of a few events, state events set with a given user's ID as the state key MUST only be set by that user."
