### ISSUE TITLE
Synapse retries too-large appservice transactions indefinitely

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#6478]
The flow goes more or less like this:

1. The bridge gets behind on transaction traffic.
1. A large number of events build up on the synapse side, and get bundled into one large transaction.
1. Synapse tries to send this transaction, and the bridge responds with a 413 (payload too large). matrix-org bridges are limited to 5MB transactions.
1. This leads to https://github.com/matrix-org/synapse/issues/1834.

(FTR, the txn 355792220 for the `irc-freenode` bridge contained 548 events)

We probably want to limit the number of events send in a transaction on the synapse side, and then ensure the bridge can handle (LIMIT*65k + padding).

**Comment by richvdh** [comment]
#3536
