### ISSUE TITLE
Document that you should increase the max client file upload size in reverse proxy docs

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6485]
We should specify the `client_max_body_size` nginx option and equivalent for other reverse proxies in https://github.com/matrix-org/synapse/blob/master/docs/reverse_proxy.md so people don't get caught up when they can't upload large images (and Synapse doesn't report an error).

Also client developers should interpret the 413 from the reverse proxy as the image is too large...

**Comment by Graphicscore** [comment]
I second this, this was exactly what I needed +1

**Comment by dklimpel** [comment]
This issue can be closed?
See https://github.com/matrix-org/synapse/pull/10122#issuecomment-854982727

There is a note in reverse proxy doc and [config settings](https://github.com/matrix-org/synapse/blob/develop/docs/usage/configuration/config_documentation.md#max_upload_size).

**Comment by clokep** [comment]
Seems like all the relevant info is there. Thanks!
