### ISSUE TITLE
The Debian package doesn't seem to respect DEBIAN_FRONTEND=noninteractive

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#6489]
Running

```
$ DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install matrix-synapse-py3
```

in a script still prompts me for a server name and whether I want to enable stats.

**Comment by richvdh** [comment]
that might be sudo: it won't pass env vars through by default

**Comment by babolivier** [comment]
Right, I tried it as root without sudo, which fixed it.
