### ISSUE TITLE
Room events are only accurate to the second

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#6492]
Anything sent through `PUT /rooms/!rid/send/*` is only accurate to the nearest second - state events are not affected by this. Typically this is only messages, but here's a sample of a room I was looking into:
```
           type            | origin_server_ts
---------------------------+------------------
 m.room.create             |    1566958842599
 m.room.member             |    1566958842690
 m.room.power_levels       |    1566958842768
 m.room.canonical_alias    |    1566958842830
 m.room.join_rules         |    1566958842893
 m.room.history_visibility |    1566958842983
 m.room.name               |    1566958843080
 m.room.member             |    1566958843305
 m.room.aliases            |    1566958846171
 m.room.member             |    1566958846838
 m.room.avatar             |    1566958850278
 m.room.member             |    1566958850760
 m.room.message            |    1566958855000
 m.room.message            |    1566958861180
 m.room.message            |    1566958867000
 m.room.member             |    1566958872501
 m.room.message            |    1566958873000
 m.room.member             |    1566958873361
 m.room.message            |    1566958876000
 m.room.message            |    1566958890000
 m.room.message            |    1566958890000
 m.room.member             |    1566958890935
 m.room.message            |    1566958899000
 m.room.message            |    1566958904000
 m.room.member             |    1566958904260
 m.room.message            |    1566958915000
 m.room.message            |    1566958919000
 m.room.message            |    1566958923000
 m.room.message            |    1566958924000
 m.room.message            |    1566958928000
 m.room.message            |    1566958930000
 m.room.message            |    1566958939000
... etc
```

This is ultimately irrelevant for instant messaging, though for lag detection and the like it's a fairly significant problem: 1 second is a lot of time to be out. Considering state events can record the exact millisecond they were created without penalty, it would be good to have room events do the same.

**Comment by tulir** [comment]
Are you sure you're not looking at a bridged room? I see milliseconds in `origin_server_ts` of normal Matrix messages. My bridges preserve original timestamps, many of which are only second precision.

**Comment by turt2live** [comment]
One of the rooms wasn't bridged, but this one was. Would be nice if the bridges supported milliseconds correctly :(

It's entirely possible the other room is just a fluke

**Comment by tulir** [comment]
> Would be nice if the bridges supported milliseconds correctly :(

Feel free to make a MSC for better timestamp massaging where it preserves both timestamps (source network and bridge time) and preferably history backfilling/insertion too :D

**Comment by turt2live** [comment]
Sounds like you're better equipped for such an MSC. I unfortunately don't have enough time on my hands to put yet another MSC on the backburner.
