### ISSUE TITLE
State reset in a v5 room

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6520]
When current matrix HQ (`!QtykxKocfZaZOUrTwp:matrix.org`) was created, `@aaron:raim.ist` was incorrectly banned.

I later unbanned him (event_id `$VzzqXFV0YpBgpHJhJz8GnurbSXuGAycgyDg5rLj5ksI`).

However, the ban is now back in place. This appears to have happened when `$FEqkc7QX6npeGWhKGGxMfFv6cl9TbQNkQsH3fWZpet0` arrived on 2019-12-09.

Initial investigation suggests that this is due to the fact that the unban is missing the ban from its auth_events.

**Comment by richvdh** [comment]
fixed by #6556, I hope

**Comment by aaronraimist** [comment]
So for #6556 and #6560 to fix my issue, do I need to be like rebanned and then unbanned again?

**Comment by turt2live** [comment]
(have tried this anyways, as it's worth a shot)

**Comment by aaronraimist** [comment]
Ftr: It seems to have worked, at least for now. It took a while for me to get into the room. I tried to join it several times but Riot just showed a loading screen (from other servers it appeared that I had joined). Clearing my cache didn't make the room to show up in Riot but today I restarted Synapse and now I can see the room again.
