### ISSUE TITLE
Can't connect to freenode irc channel ##programming even when authenthicated

### ISSUE THREAD

**Issue by stoiandan** [matrix-org/synapse#6539]
### Description

Using the Riot desktop client, I am unable to join Freenode channels like ##programming.
I've thought it might be because I'm not authenticated. I've tried to that, but still not success.
Every time I try to join, I'm getting kicked instantly with the error message:

> You were kicked from ##programming by @appservice-irc:matrix.org
> Reason: IRC error on ##programming: err_bannedfromchan

### Steps to reproduce

- Open Riot client via web or desktop
- try to join freenode ##programming via command: `/join #freenode_##programming:matrix.org`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
Version 1.5.6 (1.5.6)
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
official dmg
- **Platform**:
macOS (also reproducible on web or Linux, really platform neutral bug )
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by turt2live** [comment]
The channel has likely banned the bridge. This isn't an issue with the bridge, Riot, or Synapse unfortunately.
