### ISSUE TITLE
an internal error occurred during verification, please try again later.

### ISSUE THREAD

**Issue by mrdevrajtyagi** [matrix-org/synapse#6543]
We are getting issue in matrix database when new user signup from App. When new user enter the verification OTP it showing error after entering correct OTP. 

We have no issue with existing users. Also if we create an account then manually in VoIP Switch and Billing then it is working fine. And after manually account creation that user can login perfectly.
But only getting error - "an internal error occurred during verification, please try again later."

(from a matrix.org account if necessary), and ask there.
![WhatsApp Image 2019-12-13 at 14 07 48](https://user-images.githubusercontent.com/55022880/70802262-f9d64f00-1dd6-11ea-957d-6dbb29d532cf.jpeg)

**Comment by richvdh** [comment]
> We are getting issue in matrix database when new user signup from App

which App?

> Also if we create an account then manually in VoIP Switch and Billing then it is working fine.

This sounds like a report for a different product?

**Comment by mrdevrajtyagi** [comment]
We installed Asterisk Billing and matrix in a server for video call and im app.

**Comment by richvdh** [comment]
ok, well what Asterisk does seems unrelated to synapse.

Are you using your own matrix client?

You'll need to share the logs for the failing HTTP request.
