### ISSUE TITLE
Add disk space considerations to Postgres porting instructions

### ISSUE THREAD

**Issue by schildbach** [matrix-org/synapse#6545]
I think on the [SQLite→Postgres porting instructions](https://github.com/matrix-org/synapse/blob/v1.7.0/docs/postgres.md#porting-from-sqlite) some considerations about disk space usage should be added.

My `homeserver.db` was 1.6G and is now almost double in size after migrating to postgres:

```
# du -sh /var/lib/postgresql/
3.1G    /var/lib/postgresql/
```

This means that for following the instructions step-by-step you need `<size of homeserver.db> * 4` space on your harddrive:

- homeserver.db
- homeserver.db.snapshot
- /var/lib/postgresql/

**Comment by HarHarLinks** [comment]
My migration resulted in the following sizes (+24%):
`4.9G    homeserver.db`
`6.1G    /var/lib/postgresql`
