### ISSUE TITLE
uploads_path not being used for in-progress uploads

### ISSUE THREAD

**Issue by dacruz21** [matrix-org/synapse#6567]
### Description

Despite what `homeserver.yaml` implies, Synapse is not storing in-progress uploads in `uploads_path`.

For reference, the comment in the sample `homeserver.yaml` reads: `# Directory where in-progress uploads are stored.`

I am running Synapse in a read-only root filesystem with writes allowed in `/data/uploads`. I have set `uploads_path: "/data/uploads"` in my `homeserver.yaml`. When attempting to upload an image to Synapse, the upload fails and Synapse logs:

```
2019-12-18 21:27:07,667 - synapse.http.site - 203 - WARNING - - Error processing request <XForwardedForRequest at 0x7f99e3fb8c90 method='(no method yet)' uri='(no uri yet)' clientproto='(no clientproto yet)' site=8008>: <class 'FileNotFoundError'> [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
```
(note that `/data/uploads` is not listed as a candidate for temporary uploads in the list at the end of the log)

### Steps to reproduce

- Configure Synapse in a docker container or other host, run as a user without write permissions on `/`
- Allow write access to `/data/uploads`
- Configure `homeserver.yaml` with: `uploads_path: "/data/uploads"`
- Start Synapse, join a room, and upload any image via Riot (or any other client)

The image will fail to upload and a message similar to this will be logged:

```
2019-12-18 21:27:07,667 - synapse.http.site - 203 - WARNING - - Error processing request <XForwardedForRequest at 0x7f99e3fb8c90 method='(no method yet)' uri='(no uri yet)' clientproto='(no clientproto yet)' site=8008>: <class 'FileNotFoundError'> [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
```

`/data/uploads` is not listed as a candidate temporary directory in the error message

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information


<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

In a Docker image of Synapse, not a public homeserver

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.7.0

- **Install method**: `matrixdotorg/synapse` Docker image
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Linux (Docker)
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
well, indeed.

Apparently, `uploads_path` is only used to serve content from an undocumented `/_matrix/content` API. As far as I can tell, this is a vestige of an API that was removed back in 2016: https://github.com/matrix-org/synapse/pull/888

so certainly the documentation for `uploads_path` is completely bogus... but really it needs to just go away.
