### ISSUE TITLE
We should fall back to the default templates if we don't find a particular template in the custom template directory

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6583]
Currently, if you want to change a single template, you have to copy *all* of the templates to a custom location, and set `email.template_dir`. That's a nuisance, and it means that whenever we introduce a new template (as per [Synapse 1.4.0](https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst#upgrading-to-v140)), people have to make sure they manually install the new template.

It also repeatedly confuses people who think that they need to set `template_dir` and do so without realising the implications.

(Also: hiding the `template_dir` setting under `email` when it is used for non-email things is very silly.)

A better approach would be to look in the `template_dir`, and fall back to the default templates if the one we're looking for is missing.

**Comment by anoadragon453** [comment]
Hrm, apparently we already claim in the sample config that we do this:

> If not set, default templates from within the Synapse package will be used.

but we don't, whoops.
