### ISSUE TITLE
docker-compose.yaml in contrib folder is not working with traefik 2

### ISSUE THREAD

**Issue by nbartels** [matrix-org/synapse#6603]
### Description

I tried to get synapse working with traefik2 as reverse proxy. To get it working I used the docker-compose.yml form the contrib folder in this repository and commented all the unnecessary lines. 

After starting the synapse it connects to traefik2 as all my other services do, the ssl certificate is fetched from let's encrypt and it looks fine, but I'm not able to connect with my standalone (or any other) riot.im client. 

In the traefik logs I see the requests are forwarded to synapse but it runs into a timeout. The log message is:

```
time="2019-12-29T20:37:46Z" level=debug msg="'504 Gateway Timeout' caused by: dial tcp <valid and correct ip>:8008: i/o timeout" 
```

I'm did not find any problems in the synapse logs, even changing them to DEBUG was not helpful. Maybe I missed a logger.

### Steps to reproduce

- run traefik2
- use contrib/docker-compose.yml
- correct the setup to the traefik2 entries
- run synapse by calling `docker-compose up -d`
- try to connect with riot.im

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: yes

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.7.2

- **Install method**: docker image
<!-- examples: package manager/git clone/pip  -->

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by mnxzyw** [comment]
Are they in the same networks ？  
>docker-compose networks config

**Comment by nbartels** [comment]
@mnxzyw you saved my day. I missed to add the traefik2 network.
Many thanks.
