### ISSUE TITLE
Document how to write time periods in homeserver.yaml

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#6609]
The time peroids options for options like `redaction_retention_peroid` should be documented. Someone might assume `1m` would mean one month but from reading https://github.com/matrix-org/synapse/blob/f03c877b32c33275f47ead9e1e01d700a8d049c0/synapse/config/_base.py#L119, it looks like it would actually be one minute.

**Comment by scheleon** [comment]
Can I work on it?

**Comment by aaronraimist** [comment]
Sure

**Comment by scheleon** [comment]
Would you please point me to the corresponding doc that needs to be updated or should I write comments in homeserver.yaml instead?
