### ISSUE TITLE
Monitor synapse in zabbix

### ISSUE THREAD

**Issue by RezaBabapour** [matrix-org/synapse#6612]
There is a [tutorial](https://matrix.org/blog/2015/04/23/monitoring-synapse-metrics-with-prometheus/) about monitoring synapse in Prometheus, but I'm using Zabbix as monitoring server, Where can I find performance metrics for sending them to Zabbix.

**Comment by richvdh** [comment]
We don't have any plan to add support for zabbix support. You could probably set up a zabbix service which polls synapse's metrics endpoint, but we wouldn't be able to support you with this.
