### ISSUE TITLE
Cannot add an email address to an account

### ISSUE THREAD

**Issue by doc75** [matrix-org/synapse#6618]
### Context information

I am on a server (synapse + riot-web) hosted on a localhost machine (doing test currently before production deployment).
If I allow user registration, the user can specify a mail address right at account creation from riot-web and the validation is well received and account can be validated.

I want afterwards to control the account created on my server and therefore disable registration.
At account creation using `register_new_matrix_user` it is not possible to set the mail address.
So I want the user to add it later on.

### Description

When adding a mail address to a user that did not specify it at registration (or created with `register_new_matrix_user`) the mail with validation link is received, message when clicking on the link is saying that validation is OK.
But mail address does not appear in preference of the user.

### Steps to reproduce

- create a user without a mail address (directly in riot-web app)
- Login with this user account
- Go to `Preferences > General`
- Set **mail address** and click on `Add`
- Click on the link in the mail you obtain a message saying: `Your email has now been validated, please return to your client. You may now close this window.`
- Go back to the preferences
- The mail address is empty.

If I look the database, I can see that the validation token is still present in the table `threepid_validation_token`

I can also see in the logs that nothing seems to be done in the DB:
```
2020-01-02 22:34:42,427 - synapse.access.http.8008 - 233 - INFO - GET-564 - ::ffff:172.18.0.7 - 8008 - Received request: GET /_matrix/client/unstable/add_threepid/email/submit_token?token=jwLytVDuwcKETAgysDFJNQmnNKFYALWT&client_secret=<redacted>&sid=RJHBkoouBFWbbHHh
2020-01-02 22:34:42,436 - synapse.access.http.8008 - 302 - INFO - GET-564 - ::ffff:172.18.0.7 - 8008 - {None} Processed request: 0.009sec/-0.000sec (0.004sec, 0.000sec) (0.000sec/0.005sec/1) 131B 200 "GET /_matrix/client/unstable/add_threepid/email/submit_token?token=jwLytVDuwcKETAgysDFJNQmnNKFYALWT&client_secret=<redacted>&sid=RJHBkoouBFWbbHHh HTTP/1.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0" [0 dbevts]
```

### Version information

- **Homeserver**: localhost (docker official image)

If not matrix.org:

- **Version**: {"server_version": "1.7.1", "python_version": "3.7.5"}
- **Install method**: docker official image
- **Platform**: docker official image

If more information is needed, let me know.

**Comment by richvdh** [comment]
> I can also see in the logs that nothing seems to be done in the DB:

where do you see that? 

Note that clicking the link in the email doesn't actually add the address, you still need to click the 'continue' button in the client:

![Screenshot_2020-01-12_11-47-50](https://user-images.githubusercontent.com/1389908/72218289-69a03c80-3531-11ea-9b06-523be975c908.png)

The UX here is pretty confusing; suggest raising an issue on the client about it though.

**Comment by doc75** [comment]
Indeed, I found out that it was too complex to use matrix with all those options in the UI and that it would not fit the users need.
I did not have the logs anymore.
I will close this issue as I'll not be able to provide the necessary information from now on.
@richvdh thanks for your time.

**Comment by mascali33** [comment]
Hi,
I get an error when submitting the email `Unrecognized request (Status 400)`
Synapse log says the same error but not much more


Riot makes a request to `/_matrix/client/r0/account/3pid/add` and the server just answer
`SynapseError: 400 - Unrecognized request`

If you need more info let me know

Server version is 1.15.0

Thank you for your time ^-^

**Comment by mascali33** [comment]
My bad, it's the client Riot.im that is unable to add the email, if done on phone it works perfectly

**Comment by babolivier** [comment]
This is a Synapse bug as well, as Synapse doesn't serve these endpoints on the right routes. https://github.com/matrix-org/synapse/pull/7685 fixed this and should be released shortly.

**Comment by richvdh** [comment]
> This is a Synapse bug as well

To be clear: the original issue was user error. The later reports from @mascali33 were completely unrelated.

**Comment by pellywog** [comment]
I'm having exactly the same issue. I registered a new account at riot.im/app, then switched the email, got the confirmation link, clicked on it, it said:
```
Your email has now been validated, please return to your client. You may now close this window.
```
I did not see a button. Tried recent firefox and chromium browser. New email address does not show up in the settings.

**Comment by HammyHavoc** [comment]
> I'm having exactly the same issue. I registered a new account at riot.im/app, then switched the email, got the confirmation link, clicked on it, it said:
> 
> ```
> Your email has now been validated, please return to your client. You may now close this window.
> ```
> 
> I did not see a button. Tried recent firefox and chromium browser. New email address does not show up in the settings.

Having this same problem.

**Comment by HammyHavoc** [comment]
Sorted; didn't realize that I had to click the green button. That's the 7am brain talking! Stay well, everybody.

**Comment by blegat** [comment]
I also missed that green button. I think the issue is the sentence

> Your email has now been validated, please return to your client. You may now close this window.

is confusing as it feels that it says "all done, return to what you were doing before adding this email address" while it should really say "One step done but warning, it's not over yet, return to your client for the next step. You man close this window though"
