### ISSUE TITLE
Report Content to Your Homeserver Administrator function not working

### ISSUE THREAD

**Issue by wuhlheide** [matrix-org/synapse#6631]
### Description

The report content function in riot web does nothing on my private environment. Browser console shows no error, synapse logs show no error.

### Steps to reproduce

- Go in riot, choose a message not from you and not from admin
- Click report content and fill in something
- Modal closes and nothing happens

### What should happen

Homeserver Admin should get a notice

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 71.0 64 bit
- **OS**: Windows 10 1903
- **URL**: Riot Web 1.5.6
- **Synapse**: 1.7.3
- Variable in homeserver.yaml is set to: admin_contact: 'mailto:hugo@habicht.com'

Original postet in https://github.com/vector-im/riot-web/issues/11759

**Comment by richvdh** [comment]
the report goes to a database table: database table. Have you checked there?

I think this is a duplicate of #4007

**Comment by wuhlheide** [comment]
Okey, that goes into event_reports, but what should a admin do with that?
- Better would be that the homeserver admin gets an email or notice in riot
- It is not visible from which user the reportet content was
