### ISSUE TITLE
Prevent upgraded rooms from ever reappearing in the room directory

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#6638]
#4948 happens but it doesn't stop the room from getting state reset back into the directory. The old #synapse:matrix.org is back in the matrix.org room directory.

**Comment by richvdh** [comment]
I don't think this is a state-reset: I think the upgrade of #synapse just (significantly) predates the fix to #4948.

**Comment by aaronraimist** [comment]
Yes it does but I’m pretty sure the old room had been manually removed from from the room directory.

**Comment by richvdh** [comment]
I can't see any evidence of that, from the database.

**Comment by MadLittleMods** [comment]
Still a problem, see https://github.com/matrix-org/synapse/issues/10075
