### ISSUE TITLE
For push display names are interpreted as regex

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#6641]
Specifically, if you specify a display name of `[benpa]` then that will cause the `contains_display_name` to match against the regex `(^|\W)[benpa](\W|$)`, which matches any event with the word "a" in it.

This is because we pass the display name straight into `_glob_matches` and the glob to regex conversion doesn't escape regex characters in the glob. (We also probably don't want to be using display name as a glob)

**Comment by benparsons** [comment]
But I want this name! I blame @uhoreg for giving the idea!

**Comment by uhoreg** [comment]
FWIW, I worked around the issue by turning off notifications on "Messages containing my username".

**Comment by richvdh** [comment]
this is disasterous for performance.

**Comment by clokep** [comment]
Fixed by #7271.
