### ISSUE TITLE
Synapse/Matrix federation

### ISSUE THREAD

**Issue by barto95100** [matrix-org/synapse#6646]
hi all,

I install fresh synapse on debian 9.9

I test to configure federation but don't work:

I have a haproxy with this configuration : 

_acl matrix_front hdr(host) matrix.worldgeekwide.fr
use_backend matrix_backend if matrix_front matrix-path
frontend matrix-federation
      bind :::8448 v4v6 ssl crt /etc/haproxy/certs/worldgeekwide.fr.pem
      default_backend matrix_backend
backend matrix_backend
	server matrix 192.168.1.96:8008_

In my router i NAT the port 443 and 8448 to HAPROXY

In my Provider DNS (OVH) I configure the SRV but, when i test the federation with : https://federationtester.matrix.org/

I have this result  : Connection Errors
Non-200 response 503 from remote server

and json : 

_{
  "WellKnownResult": {
    "m.server": "",
    "result": "No .well-known found"
  },
  "DNSResult": {
    "SRVCName": "_matrix._tcp.worldgeekwide.fr.",
    "SRVRecords": [
      {
        "Target": "matrix.worldgeekwide.fr.",
        "Port": 443,
        "Priority": 10,
        "Weight": 5
      }
    ],
    "SRVError": null,
    "Hosts": {
      "matrix.worldgeekwide.fr.": {
        "CName": "matrix.worldgeekwide.fr.",
        "Addrs": [
          "193.248.158.70"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "193.248.158.70:443"
    ]
  },
  "ConnectionReports": {},
  "ConnectionErrors": {
    "193.248.158.70:443": {
      "Message": "Non-200 response 503 from remote server"
    }
  },
  "Version": {
    "error": "msg=Failed to GET JSON to : \u003chtml\u003e\u003cbody\u003e\u003ch1\u003e503 Service Unavailable\u003c/h1\u003e\nNo server is available to handle this request.\n\u003c/body\u003e\u003c/html\u003e\n\n code=503 wrapped="
  },
  "FederationOK": false
}_

I don't know why don't work ....

thank's for your help :)

**Comment by turt2live** [comment]
It looks like your federation setup or reverse proxy is misconfigured. #synapse:matrix.org on Matrix is going to be a better place to troubleshoot further.

For posts in the room, and here, please use Markdown code blocks so the text is readable.

**Comment by barto95100** [comment]
Ok thank's I'm in #synapse:matrix.org

**Comment by sbhal** [comment]
@barto95100 were you able to find solution. facing similar problem

**Comment by barto95100** [comment]
The SRV don't work I used the oder solution .well-known delegation and work
