### ISSUE TITLE
Room upgrade didn't copy custom state event

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#6669]
@rxl881 recently upgraded the Hosted Homeservers room (`!BKbPlYiKeTXeIOdFoO:vector.modular.im`) however it didn't copy some custom state that we use for the ticketing bot. Specifically, it was the `uk.half-shot.matrix-zammad.roominfo` state event with an empty key. The old event ID is `$157795917764tdkYM:federator.dev`.

**Comment by Half-Shot** [comment]
This is presumably because we don't support that https://github.com/matrix-org/synapse/blob/41546378340e7bc3e0eea4929d463f09f1008f4f/synapse/handlers/room.py#L326-L338

**Comment by richvdh** [comment]
yeah, room upgrades don't copy arbitrary state.
