### ISSUE TITLE
tests.test_phone_home.PhoneHomeStatsTestCase.test_performance_100 fails on Raspberry Pi 2

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6676]
The `tests.test_phone_home.PhoneHomeStatsTestCase.test_performance_100` test fails on a raspberry pi 2.

```
twisted.trial.unittest.FailTest: 107 ~== 100
```

Likely related to performance issues but it seems their homeserver is working well enough otherwise.

Synapse v1.8.0

**Comment by a000a** [comment]
Same on BananaPi M3 with latest develop.
Any suggestions?

```
[FAIL]
Traceback (most recent call last):
  File "/home/bpiusr/.cache/pikaur/build/matrix-synapse-git/src/synapse/tests/test_phone_home.py", line 51, in test_performance_100
    self.assertApproximates(stats["cpu_average"], 100, tolerance=2.5)
  File "/usr/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 564, in assertApproximates
    raise self.failureException(msg or "%s ~== %s" % (first, second))
twisted.trial.unittest.FailTest: 107 ~== 100

tests.test_phone_home.PhoneHomeStatsTestCase.test_performance_100
```

**Comment by richvdh** [comment]
this is code that was added in #6318. It looks like if we moved [this code](https://github.com/matrix-org/synapse/pull/6318/files#diff-01aac508ef38061957e6fb961582e5ceR522-R539) to near the start of the function, it would be more reliable.

Don't think it's affecting anything other than the tests though

**Comment by a000a** [comment]
any idea how i can pass this test, or install synapse ignoring this one?

thanks

**Comment by clokep** [comment]
I'm going to close this since #7634 implements the suggestion above. Please shout if this is still an issue!
