### ISSUE TITLE
Can't join invite-only channel

### ISSUE THREAD

**Issue by pirhszm** [matrix-org/synapse#6684]
### Description
When try to join channel which is invite only, I get - You're already on #channel-name. 
Well this message is somewhat true because I'm already in that channel but with a different nick and client. 

### Steps to reproduce

- Join a channel which is invite-only (make sure you are on invite list of channel) with different nick associated with same account.
- Now invite you yourself pm'ing Chanserv
- It shows, You're already on #channel-name.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.org

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Riot.im on Android and Web
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
I'm struggling to understand your description but from what you say it sounds like it might be an issue with an IRC bridge rather than synapse.

what does "Now invite you yourself pm'ing Chanserv" mean?

**Comment by pirhszm** [comment]
I asked this in matrix channel and Half-Shot suggested to file it here
>Lozenge: Hello when I try to join a freenode channel which is invite only, I get message that I'm already in that channel, but I'm not.
>Half-Shot: Sounds like a client/server bug
You may want to report this in the synapse GitHub repo with more details

I actually use Riot and another IRC client. So that's why I am already in that channel, but not with Riot.

pm'ing Chanserv... means as channel is invite only I have to invite myself to join that channel but as we can't so that by direct command in riot, I PM @freenode_ChanServ:matrix.org.

**Comment by richvdh** [comment]
@Half-Shot can you decode any of this?

**Comment by Half-Shot** [comment]
> I get message that I'm already in that channel, but I'm not.

I read this to be Riot/Synapse failing to join you to the room. What's the precise error string? Screenshot?

**Comment by pirhszm** [comment]
On join I get:
Failed to join room
You are not invited to this room.

When I invite myself by messaging invite #Channel-name to @freenode_ChanServ:matrix.org, it says:
You're already on #Channel-name.

**Comment by richvdh** [comment]
> When I invite myself by messaging invite #Channel-name to @freenode_ChanServ:matrix.org, it says:
> You're already on #Channel-name.

Is this a message from Chanserv, or Riot? are you *sure* that's the exact error message? a screenshot would help us understand what you're talking about.

**Comment by Half-Shot** [comment]
@pirhszm ChanServ will not join your Matrix account to the room. You need to use `@appservice-irc:matrix.org` and ask it to `!join #channelname`.

**Comment by pirhszm** [comment]
> On join I get:
> Failed to join room
> You are not invited to this room.
This message is provided by riot after searching the channel in channel directory.
> When I invite myself by messaging _invite #Channel-name_ to @freenode_ChanServ:matrix.org, it says:
> You're already on #Channel-name.
This one is reply by Chanserv when I invite.

>@pirhszm ChanServ will not join your Matrix account to the room. You need to use @appservice-irc:matrix.org and ask it to !join #channelname.
Yeah but since channel is invite only I need to invite myself first which is not working.

**Comment by richvdh** [comment]
this doesn't sound like a synapse issue.
