### ISSUE TITLE
Move room creation to a worker

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#6695]
It takes up a significant amount of CPU on my synapse for no other reason than volume (as far as I can tell).

**Comment by PC25** [comment]
Hi @turt2live , I would like to work on this issue. Can you guide me a bit on how to achieve this?

**Comment by turt2live** [comment]
I unfortunately do not have the expertise to really help with this. #synapse-dev:matrix.org might have some ideas though.

**Comment by MadLittleMods** [comment]
Related to https://github.com/matrix-org/synapse/issues/6068 and https://github.com/matrix-org/synapse/issues/1545

**Comment by richvdh** [comment]
I think this was fixed by  #10564.

**Comment by turt2live** [comment]
ooh, TIL. Thank you!
