### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by simsasaile** [matrix-org/synapse#670]
Hi,

I am just experimenting with synapse, and it looks quite promising.
Just one questing: Is LDAP-Support planned?

Cheers, Simsa

**Comment by ara4n** [comment]
We have higher priorities currently but patches to add additional auth mechanisms are vey welcome :)

**Comment by simsasaile** [comment]
Thanks to DoubleMalt LDAP-Auth should now been possible: https://github.com/matrix-org/synapse/pull/701

**Comment by simsasaile** [comment]
Hi @DoubleMalt 
Just tried your LDAP-Module for synapse. It seems that I need an PW for my LDAP, is there a possibility to add this config option too?
