### ISSUE TITLE
Profile setter and getter endpoint for processing CUSTOM user profile data

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#6737]
It would be great to have a user profile endpoint for setting and getting CUSTOM user profile data, similar to the existing 'account_data' endpoint (https://matrix.org/docs/spec/client_server/latest#id127), however, with the difference that the profile custom data would be publicy available.

This would allow to enrich the user profiles.

**Comment by richvdh** [comment]
extensible profiles are https://github.com/matrix-org/matrix-doc/issues/489

**Comment by menturion** [comment]
Tanks for the link.
