### ISSUE TITLE
Support Keybase.io proofs in instances

### ISSUE THREAD

**Issue by agharbeia** [matrix-org/synapse#6741]
**Description:**
Keybase is a key directory that maps social media identities to encryption keys (including, but not limited to PGP keys) in a publicly auditable manner. Additionally it offers an end-to-end encrypted chat and cloud storage system, called Keybase Chat and the Keybase filesystem respectively.
-- Wikipedia:Keybase

It would be nice to have the ability to prove one's identity in Matrix.org to feature them in their Keybase profile. For this to happen instances need to support it.

For example, Mastodon has built-in support for Keybase proofs starting with version 2.8.0. Users of both Mastodon and Keybase can choose their Mastodon instance from a drop-down list in the Keybase desktop application and, by following a prescribed procedure, add to their profile in Keybase their identity in a Mastodon instance.

See https://keybase.io/docs/proof_integration_guide

**Comment by richvdh** [comment]
this sounds more like a spec issue than a synapse one tbh.

**Comment by agharbeia** [comment]
Isn't Synapse the reference implementation?

**Comment by richvdh** [comment]
Well yes, but that means synapse's job is to implement the spec. Proposals for additions to the matrix protocol have a process: see https://matrix.org/docs/spec/proposals.

**Comment by agharbeia** [comment]
Thanks.
But to be honest I do not see this as pertaining to the protocol, as it
doesn't affect how clients or servers interact.

I see it as a feature pertaining to usability and user experience. So
various implementations may decide to apply it or not, and it may be a
distinguishing feature.

For example Mastodon implemented this and they are not the ones who make
ActivityPub or GNUSocial, etc. Meanwhile other servers implementing
ActivityPub are not required to do so.

**Comment by richvdh** [comment]
> it doesn't affect how clients or servers interact.

In that case I'm clearly not understanding what you are proposing. Perhaps you could put together a draft proposal.
