### ISSUE TITLE
/_synapse/admin/v1/users/<uid>/admin Fails if user id is URL encoded

### ISSUE THREAD

**Issue by NHAS** [matrix-org/synapse#6752]
### Description

GET /_synapse/admin/v1/users/<user_id>/admin doesnt allow for URL encoded user_ids, as such this disable some UI functionality in riot.im, which is where I first noticed it. As it was giving a 400 error. 

### Steps to reproduce

1. Get valid admin token
2. GET /_synapse/admin/v1/users/%40admin%3amatrix.server/admin
3. View response as error

What should happen is url encoding is causing the regex not to match. Caused by a regex on line:
https://github.com/matrix-org/synapse/blob/c2ba994dbb3f084c2c0cc8492e8a9456ec0f3747/synapse/rest/admin/users.py#L430

That should be:     
```PATTERNS = (re.compile("^/_synapse/admin/v1/users/(?P<user_id>[^/]*)/admin$"),)```

Which removes the "@" symbol requirement. 

### Version information

- **Homeserver**: personal private homeserver, not matrix.org

If not matrix.org:

- **Version**: {"server_version": "1.8.0", "python_version": "3.6.9"}

- **Install method**: Apt package manager, after importing keys as per install instruction

- **Platform**: Ubuntu 18.04, running within a VM, Nginx reverse proxy

Although this is behind the NGINX reverse proxy, I have also tested this via localhost:8008 and it still presents the problem.

**Comment by anoadragon453** [comment]
Fixed in, https://github.com/matrix-org/synapse/pull/6825. Thanks!
