### ISSUE TITLE
'Too Many Requests' error_code  M_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by abhinavkiwi** [matrix-org/synapse#6777]
I have set up a matrix synapse app for messaging, and using its APIs for User account and Chat room activity like user registration, room creation and join the room.

While testing we are getting the "Too Many Requests" error in some of the requests. In testing, we have approx 1000 users. 

below are the full error response:  
  {"errcode"=>"M_LIMIT_EXCEEDED", "error"=>"Too Many Requests", "retry_after_ms"=>750}

I tried by changing the default application configuration to solve this issue but not works.
below are the app configurations:
  federation_rc_reject_limit: 2000
  federation_rc_concurrent: 100

Please suggest to us what should be configurations to handle 1000 concurrent requests.

**Comment by richvdh** [comment]
support requests are best asked in #synapse:matrix.org.
