### ISSUE TITLE
AttributeError: 'ModuleApi' object has no attribute 'hs'

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#6778]
Since Synapse v1.9.0 the below exception is thrown ...
`AttributeError: 'ModuleApi' object has no attribute 'hs'`

for the following line of code ...
`store = yield self.account_handler.hs.get_profile_handler().store`

... which is part of a password provider. The result is that it is no longer possible to login through the password provider. 

Any idea of a quick fix?

**Comment by menturion** [comment]
Just found the fix here https://github.com/matrix-org/synapse/issues/6772
Replaced substring `account_handler.hs` by `account_handler._hs`.

Thanks.

**Comment by turt2live** [comment]
looks like you've solved this
