### ISSUE TITLE
Private Chat Room History is shared

### ISSUE THREAD

**Issue by PeerD** [matrix-org/synapse#6780]
### Description

Synapse defines three templates for rooms: 

```
       RoomCreationPreset.PRIVATE_CHAT: {
            "join_rules": JoinRules.INVITE,
            "history_visibility": "shared",
            "original_invitees_have_ops": False,
            "guest_can_join": True,
        },
        RoomCreationPreset.TRUSTED_PRIVATE_CHAT: {
            "join_rules": JoinRules.INVITE,
            "history_visibility": "shared",
            "original_invitees_have_ops": True,
            "guest_can_join": True,
        },
        RoomCreationPreset.PUBLIC_CHAT: {
            "join_rules": JoinRules.PUBLIC,
            "history_visibility": "shared",
            "original_invitees_have_ops": False,
            "guest_can_join": False,
        },

```

The room history is always set to shared. This results in the following problem:

- User A and User B start a private conversation (with default settings)
- User A and B chat about private/confidential matters
- User A invites User C to the conversation
- User C can see the entire history

This could result in serious Problems for the affected users including security (leaked passwords), bullying (private information being disclosed) etc.

Of course a malicious user could always disclose the content of the private chat. But this can even happen if the users just forgot things they talked about long ago when inviting a third party, especially as they probably do not expect the new user to be able to see everything from the past.

E2E encryption would prevent this, but many users might not use it out of laziness  or other reasons.

### Proposed Fix

This problem could easily be mitigated by setting the `history_visibility` to `invited` for private conversations. Then, user joining later can not read the private conversions prior to their invitation.

With my limited knowledge I don't see any downsides to this, but there might very well be some. Any comments from more experienced matrix devs?

### Steps to reproduce

- Create a private conversation between two users
- Write messages
- Invite a third party

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

All versions as far as I know

**Comment by richvdh** [comment]
I must admit I don't really know why this is the case, but synapse is just following the spec here. If it needs changing that would be a matter for https://github.com/matrix-org/matrix-doc.

**Comment by PeerD** [comment]
Thanks for in input, I was not aware that this was in the spec already. I opened an issue at the spec repo:

matrix-org/matrix-doc#2428

**Comment by richvdh** [comment]
thanks, going to close this for now in favour of the spec issue
