### ISSUE TITLE
Remote aliases aren't moved to new room on room upgrade.

### ISSUE THREAD

**Issue by mvgorcum** [matrix-org/synapse#6784]
**Description:**

**Comment by richvdh** [comment]
Could someone explain like I'm five what exactly the problem is here?

**Comment by mvgorcum** [comment]
I haven't tested all permutations, but this is what I found:

`@exampleuser:server1.com` creates room, adds alias `#alias:server1.com`. `@exampleuser2:server2.com` joins and adds `#alias2:server2.com`.

`@exampleuser:server1.com` upgrades the room to another room version. `#alias:server1.com` gets moved to the new room, but `#alias2:server2.com` does not get moved.

**Comment by anoadragon453** [comment]
@mvgorcum Does the second alias get moved when a user from server2.com joins the upgraded room?

**Comment by anoadragon453** [comment]
Just tested and indeed remote aliases don't ever get moved. We should move them when the server processes the create event for the first time, just like other room attributes.

**Comment by mvgorcum** [comment]
Yeah, if `@exampleuser2:server2.com` joins that doesn't trigger an alias move.

**Comment by richvdh** [comment]
related: #6842

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6946
