### ISSUE TITLE
system alerts keeps reinviting mozilla users despite being empty

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6815]
if mozilla users part the system alerts room, they keep getting reinvited to it (perhaps every time the server restarts)? despite the room being empty

**Comment by babolivier** [comment]
Are we sure it's inviting these users to the same room they left?

From looking at the code, what's the most likely to be happening is that something triggers a server notice to be sent every now and then. In this case, and if a user has left the previous room, Synapse will create a new room and invite the user to it. FWIW the sending of a notice can be triggered either if the user hasn't accepted the latest ToS, if the server's MAU is reached, or if someone sent a notice via the admin API.

I created an account on the homeserver to investigate further when that happens next.

**Comment by babolivier** [comment]
Hmm, I just witnessed it happen with my account, and the System Alerts user isn't sending any message to the new room (which it shouldn't do). I'll investigate further.

**Comment by babolivier** [comment]
Quick update on this issue, I haven't seen it happen on my account over the past month or so. I'll wait until the end of this month, and if it still doesn't happen, I'll close this issue (unless I'm told people are still getting bitten by this, which would mean that I'm just not trying to repro it the right way).

**Comment by babolivier** [comment]
Right, turns out that `get_notice_room_for_user` is cached (with a `@cachedInlineCallbacks()` decorator), which never expires except when the homeserver restarts (which clears all of the caches), which explains why it isn't run on every sync (but, presumably, the first one since the latest restart).

**Comment by babolivier** [comment]
Fixed in #7199
