### ISSUE TITLE
Allow only my server

### ISSUE THREAD

**Issue by deounix** [matrix-org/synapse#6822]
How to allow only my server to join my rooms and speak with my users ???

eg:

1. example1.com is my server
2. matrix.org
3. riot.im

I don't want any users of any domain not in example1.com to talk to my server

**Comment by richvdh** [comment]
I'm afraid we can't offer support over github.

**Comment by richvdh** [comment]
(or over direct message, unless you're prepared to pay New Vector for consultancy.)

**Comment by deounix** [comment]
@richvdh I don't interest in this project anymore.

allowing a single server need so much to be done?

What such a project and support!
