### ISSUE TITLE
Let's encrypt certificates for a SRV record based configuration

### ISSUE THREAD

**Issue by mmequignon** [matrix-org/synapse#6828]
Hi everyone !
I'm trying to install a synapse node and I encounter a little problem. Everythings works well (I'm talking with a friend right now) but I can't search for rooms or people.
I tested my configuration here : https://federationtester.matrix.org/ and it seems that there is a problem with my certificates. FYI here is the domain name : `example.com` and the subdomain where synapse is running is `matrix.example.com`. I created a let's encrypt cert for `matrix.example.com` and I'm trying to follow this part of the doc https://github.com/matrix-org/synapse/blob/master/docs/MSC1711_certificates_FAQ.md#option-3-add-a-well-known-file-to-delegate-your-matrix-traffic. Here is my question : how could I make it works without a example.com dns record pointing to the synapse server address ?

Context : I'm running synapse (v 1.9.1) from NixOs stable.

**Comment by richvdh** [comment]
#synapse:matrix.org is the place for this sort of support.
