### ISSUE TITLE
Server-wide media retention policy

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#6832]
A feature that's both interesting to have and fairly well requested is the ability to configure a media retention policy at the server level.

A first approach would have been to base the TTL of a media on its date of upload, but then we'd likely delete still-in-use avatars, medias used in community descriptions, etc.

Therefore, a preferred approach is to base that TTL on the date it was last accessed at, to ensure we don't delete media that are still being used. FTR, that date of last access is stored by Synapse for both remote and local media, so it's technically doable.

Another thing to consider is that we currently don't have any way in deleting a media in Synapse, so that'd need to be added in.

Also, we'd need to figure out how this feature would handle quarantined media.

cc @rxl881 

Related: https://github.com/matrix-org/synapse/issues/6459, https://github.com/matrix-org/synapse/issues/3479, https://github.com/matrix-org/matrix-doc/issues/790

**Comment by richvdh** [comment]
there are open issues/MSCs around deleting media: we should hunt them down and link them

**Comment by babolivier** [comment]
I can't seem to find any... https://github.com/matrix-org/matrix-doc/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aproposal+media

**Comment by babolivier** [comment]
> there are open issues/MSCs around deleting media: we should hunt them down and link them

I've updated the issue's description with the few issues I could find. I didn't find any MSC relating to that though.

**Comment by richvdh** [comment]
Thanks. [MSC2278](https://github.com/matrix-org/matrix-doc/pull/2278) seems to be the MSC I was thinking of.

**Comment by babolivier** [comment]
After chatting with @neilisfragile and @lampholder about the quarantine concern, the conclusion is that a media retention policy should ignore quarantined media.

**Comment by IF-Adin** [comment]
I would like to add that avatars and room avatars should probably be stored in a different way. They mostly seem to be cached, so they are probably not accessed all that often in smaller groups, which mean they would be purged, too.

May add a tag or something to all user and room Avatars?

**Comment by IF-Adin** [comment]
Nevermind, as it turns out i can not read, you have already thought of that.

**Comment by MamasLT** [comment]
Great points made by babolivier. 

There are few options for dealing with media: 
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/media_admin_api.md

But they don't seem to do the main thing - to delete it on local server. I would agree that there should be a server-wide media retention policy available, that could be set in config in the same way as message retention is now.
The quarantine, as I understand should be done just before deleting the particular media files, so there won't be any issues for clients.
Doing the quarantine and then deleting all media manually (not sure if there is any other way at this time) sounds a bit over complicated. Cheers!

**Comment by NHAS** [comment]
Not sure if this is the correct place to note this. 
However when a general "event" retention policy is applied to a server it doesnt remove media such as images or uploaded files. 
This means there are a large number of files that have no event referencing them. This issue would help somewhat to solve that. However the best solution would be for the server retention policy to delete said media.

**Comment by anoadragon453** [comment]
The `before_ts` parameter of the [Delete Local Media Admin API](https://matrix-org.github.io/synapse/latest/admin_api/media_admin_api.html#delete-local-media-by-date-or-size) should cover this usecase. Setting the `keep_profiles` parameter to `true` ensures that room and user avatars are not removed in the process.

This endpoint calls the [`MediaRepository.delete_old_local_media`](https://github.com/matrix-org/synapse/blob/cbd82d0b2db069400b5d43373838817d8a0209e7/synapse/rest/media/v1/media_repository.py#L887) method. Adding a config option to configure a background job that regularly calls this method with a determined retention period seems plausible to me.

Of course, note that this will only work with media uploaded to Synapse's media repository, rather than using tools such as [matrix-media-repo](https://github.com/turt2live/matrix-media-repo).

**Comment by ptman** [comment]
@reivilibre very good point. I think user and room avatars are also in the media repo (mxc://) so garbage collecting those would cause problems. Any other uses for media that aren't suitable for garbage collection? Access time is better than creation/modification time, but still problematic in many usecases.

**Comment by tastytea** [comment]
> Any other uses for media that aren't suitable for garbage collection?

It would be unfortunate if media from [MSC2545: Image Packs](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md) would get deleted by this.

**Comment by clokep** [comment]
> > Any other uses for media that aren't suitable for garbage collection?
> 
> It would be unfortunate if media from [MSC2545: Image Packs](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md?rgh-link-date=2022-05-02T11%3A52%3A21Z) would get deleted by this.

I filed #12928 about this.
