### ISSUE TITLE
UISIs from pintobyte to arasphere

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6841]
jeremy on pintobyte sent me a E2EE-by-default DM on arasphere, but couldn't decrypt me - even after we both upgraded to 1.10-rc1.

https://github.com/matrix-org/riot-web-rageshakes/issues/2184

**Comment by ara4n** [comment]
i /think/ this was what prompted erik to track down https://github.com/matrix-org/synapse/pull/6848. it may even have caused it.

**Comment by richvdh** [comment]
hurrah, then
