### ISSUE TITLE
rooms/<id>/messages returning error 500

### ISSUE THREAD

**Issue by tanriol** [matrix-org/synapse#6868]
### Description

When I tried to open in Riot a channel I'm in, I found that in some time it stopped loading and in the Firefox network monitor I saw requests to URLs like `https://matrix-client.matrix.org/_matrix/client/r0/rooms/!PcCidzjUKXHKImhTrB%3Amatrix.org/messages?from=t2755454-1250970583_757269739_468480_430019614_270561768_1077824_41756786_21137078_73834&limit=20&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D` returning status code 500 with a body of `{"errcode":"M_UNKNOWN","error":"Internal server error"}`

### Steps to reproduce

Note: I'm not sure how reliable are these steps

- open `#mozilla_#rust:matrix.org`
- try scrolling to messages for 2020-02-05 (before [this one](https://matrix.to/#/!PcCidzjUKXHKImhTrB:matrix.org/$1581027077399386PkTze:matrix.org?via=matrix.org&via=privacytools.io&via=matrix.darkchannel.net))

I'm seeing roughly the following
![Screenshot_20200207_011856](https://user-images.githubusercontent.com/1027034/73984112-fbd90c00-4948-11ea-979b-ab9940adcba9.png)
with the messages failing to load (that "loading" indicator stays there for at least some tens of minutes with good connection)

Open the browser's network monitor in devtools and check for error 500 replies.

I've tried force-reloading Riot and clearing its cache, but it did not help.

### Version information

Observed on `matrix.org` on 2020-02-07

**Comment by richvdh** [comment]
well, boo.

This is essentially https://github.com/matrix-org/synapse/issues/3736, so I'm going to close this as a duplicate. It's somewhat hard to do much about :/.

**Comment by tanriol** [comment]
Ok, thank you for looking at it. May it make sense to add some indication to this error so that it can be distinguished from others?
