### ISSUE TITLE
we should run the 'are_all_users_on_domain' database sanity check before running schema migrations

### ISSUE THREAD

**Issue by aspacca** [matrix-org/synapse#6870]
### Description
When I run a search on my hosted matrix service from any client I see no results.
I can see the correct count but not the actual results

### Steps to reproduce
- Doing a search
- No results showed

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
- I should see the results
### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
`{"server_version": "1.9.1", "python_version": "3.7.3"}`
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
Debian apt repo package
- **Platform**:
Debian 10
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->



I found the query that's run on sqlite for search and I saw it doesn't work properly:
https://github.com/matrix-org/synapse/blob/v1.9.1/synapse/storage/data_stores/main/search.py#L424
https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg71741.html

I then realised that the bultin sqlite3 function is overidden by https://github.com/matrix-org/synapse/blob/v1.9.1/synapse/storage/engines/sqlite.py#L76

my guess is that somehow the function overide is not applied and so the bultin failing rank function is used

**Comment by aspacca** [comment]
I was finally able to identify the issue.
It's totally unrelated to the rank function but rather to the new `local_current_membership` table introduced in `1.9.1` relase and relative db migration.
I use debian sid repo to manage my synapse installation. I observed that since a few version the server name is not anymore defined in `homeserver.yaml` but rather from `conf.d/server_name.yaml`
The systemd unit `ExecStart` is the following
```/usr/bin/python3 -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/```
Over every update of the synapse package the content of `conf.d/server_name.yaml` is replaced with the name of the server coming from `/etc/hostname` and I have to manually change it back the the production server name and restart the systemd service to make it work otherwise the synapse will fail to start due to mismatching server name define in the conf and the one in the db
Apparently even this doesn't stop the migration to be run in background: for the specific case I guess the server name from the configuration was used to populate `local_current_membership` table ending in an empty one sine where was no matching local user for the wrong server name in the db.
This would have been prevented if the migration (especially since it is relying on the server name conf) was not run until the invalid server name configuration was fixed.

**Comment by richvdh** [comment]
I'm afraid I don't quite understand your explanation.

If the problem is that `conf.d/server_name.yaml` is being overwritten, please can you raise that with the maintainers of the debian package?

**Comment by richvdh** [comment]
(title updated for clarification: we use 'database migration' to mean moving from sqlite to postgres)

**Comment by aspacca** [comment]
@richvdh I will clarify better
The problem with the `conf.d/server_name.yaml` overwritten has to be raised with the mantainers of the debian package, and I will do.

But there's another problem and you should be able to reproduce with the following steps:
1. Install matrix 1.9.0 with sqlite defining `server_name: whatever.domain.com`
1. Register some users for the server
1. Shut down the server and change to `server_name: another.domain.com`
1. Upgrade to matrix 1.9.1, it should fail to start because of mismatching between the server name in the db and the one in the config
1. Check in the db the existance of the table `local_current_membership`. It should be there but empty
1. Fix the server name and restart matrix. Now it is working.
1. Use search feature in any client: no results

The problem is that at point 4 the database update for `local_current_membership` was applied even if the server name configuration was invalid
Relying on the `config.server_name` the query that populates the table results in inserting no data: https://github.com/matrix-org/synapse/blob/9bae740527c4621f9f8eb8ca936669f2372c42eb/synapse/storage/data_stores/main/schema/delta/57/local_current_membership.py#L72
Once you fix the server name and restart properly the server the migration is already run and `local_current_membership` will stay empty breaking the search

My fix was to manually delete the table, remove the migration from the db and restart the server with the proper server name

**Comment by richvdh** [comment]
ah I see. Thanks

**Comment by richvdh** [comment]
done in #6982
