### ISSUE TITLE
internal server error when remote room directory is private

### ISSUE THREAD

**Issue by lub** [matrix-org/synapse#6896]
### Description

When querying a remote server room directory which requires authentication, synapse currently just throws a `{errcode: "M_UNKNOWN", error: "Internal server error"}`

It probably makes sense to use a more specific error to indicate to the end user, that it's only possible to query that room directory as user of that server.

### Steps to reproduce

- query `/_matrix/client/r0/publicRooms?server=example.com`, where example.com is a server with a non-public room directory
- get before mentioned generic internal server error

### Version information

- **Homeserver**: imninja.net
- **Version**: 1.10.0rc5

- **Install method**: Docker

- **Platform**: Container

**Comment by richvdh** [comment]
related: #6325 ?

**Comment by anoadragon453** [comment]
@richvdh indeed

Both fixed in https://github.com/matrix-org/synapse/pull/6899

**Comment by lub** [comment]
Sorry, I didn't find the existing issue

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6899
