### ISSUE TITLE
Cannot reject invite: "403: Unknown room"

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6902]
It seems that it's possible for rooms to have no state in `current_state_events` (possibly because the server thinks that everyone has left the room), but also to have no room_version in `rooms` (possibly because the room was created before we populated that as a matter of course).

Users who have invites to that room will then see "Unknown room" when they try to reject the invite. (They will also see an error if they try to accept the invite, since everybody has left).

**Comment by richvdh** [comment]
I'm guessing this is new in 1.10.0 with #6802.

**Comment by anoadragon453** [comment]
Could we:

a. Remove all local invites for a room when it is cleaned up
b. keep track of rooms that were deleted this way and if any remote server asks to join, we can gracefully tell them that it is no longer possible?

**Comment by djschilling** [comment]
Just want to push this here, as i experienced the problem right now.

**Comment by spiraldancing** [comment]
I think I'm seeing the same issue.  I fired up a new Synapse server (twice), works internally but something is wrong with it -- I can send out invites from the new server, but invite recipients can neither accept nor reject them ("Failed to reject invite -- Not a known room").  The result is that I now have several pending Invites in my "regular" Matrix account which I cannot get rid of.

**Comment by richvdh** [comment]
> a. Remove all local invites for a room when it is cleaned up

yeees, except that ship has sailed almost everywhere, given the cleanup happened back in February.

**Comment by reivilibre** [comment]
Is anyone still seeing this? It doesn't sound like this will recur as it happened due to a one-off cleanup job, so unless it's still active I suggest we close the issue.

**Comment by anoadragon453** [comment]
Thanks for letting us know @RandomErrorMessage. Could you file a new bug report with some logs so we can investigate?
