### ISSUE TITLE
Allow fetching all room state events of a given type

### ISSUE THREAD

**Issue by ulope** [matrix-org/synapse#6908]
Related to: #3675

## Requested Feature

Please add an endpoint to query room state events of a given type without having to give a state key as well.

## Background

There already exists the `GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}` endpoint which allows fetching specific `eventTypes` for a room where the `stateKey` is known. 

One use case where the stateKey is (in the general case) not knowable is fetching room aliases. Therefore it's currently necessary to use the generic `GET /_matrix/client/r0/rooms/{roomId}/state/` endpoint which can produce quite large responses for big rooms.

**Comment by richvdh** [comment]
that would be a spec feature first and foremost; matrix-doc is the place to raise it.

Note that your stated usecase would be made redundant by https://github.com/matrix-org/matrix-doc/pull/2432/. (It's not possible to reliably get a list of aliases for a room by looking at the aliases events anyway, see https://github.com/matrix-org/matrix-doc/issues/2262)
