### ISSUE TITLE
Can't get a list of accounts

### ISSUE THREAD

**Issue by csaar95** [matrix-org/synapse#6922]
### Description

I'm trying to get all users ([see doc](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#list-accounts)), `GET /_matrix/client/r0/admin/users` returns following error:
```json
{
  "errcode": "M_UNRECOGNIZED",
  "error": "Unrecognized request"
}
```
`GET /_matrix/client/r0/admin/users/[userId]` is actually working.

I think this could have sth. to do with following issue  #6352.

### Steps to reproduce

- `GET /_matrix/client/r0/admin/users`

### Version information

- **Homeserver**:   yes

- **Version**:
```json
{
  "python_version": "2.7.13",
  "server_version": "1.0.0"
}
```
```json
{
  "unstable_features": {
    "m.lazy_load_members": true
  },
  "versions": [
    "r0.0.1",
    "r0.1.0",
    "r0.2.0",
    "r0.3.0",
    "r0.4.0",
    "r0.5.0"
  ]
}
```

- **Install method**: `pip install https://github.com/matrix-org/synapse/tarball/master`

- **Platform**: Debian 9.11 (ESX VM)

**Comment by richvdh** [comment]
the endpoint is /_synapse/admin/v2/users, not /_matrix/client/r0/admin/users.

**Comment by csaar95** [comment]
I am using the client server api, cause I'm not working on localhost.
Anyway, if a `GET /_synapse/admin/v2/users` on localhost delivers exactly the same error message...

**Comment by richvdh** [comment]
> I am using the client server api, cause I'm not working on localhost.

this shouldn't be a problem. `/_synapse/admin` isn't limited to localhost.

> "server_version": "1.0.0"

I think the endpoint you're after was only added recently. You'll need to upgrade.

**Comment by csaar95** [comment]
Okay, I'll upgrade and let you know if it works.

**Comment by csaar95** [comment]
Upgraded to
```
{
    "python_version": "3.5.3",
    "server_version": "1.10.1"
}
```
- `GET /_synapse/admin/v2/users` is now working as expected, thanks:) But not accessible from other clients.
- `GET /_matrix/client/r0/admin/users` returns the same errormessage as before.
- `GET /_matrix/client/r0/admin/users/@xxx:yyy.zzz.de` actually returns the expected result from `GET /_matrix/client/r0/admin/users`!?

**Comment by richvdh** [comment]
> GET /_matrix/client/r0/admin/users/@xxx:yyy.zzz.de actually returns the expected result from GET /_matrix/client/r0/admin/users!?

I don't know what the expected result is. It's not a documented API, and one of the reasons we introduced `GET /_synapse/admin/v2/users` is that the existing `/_matrix/client/r0/admin/users` didn't have a sensible interface (see also https://github.com/matrix-org/synapse/issues/2522).

You should use `GET /_synapse/admin/v2/users`.

**Comment by csaar95** [comment]
> I don't know what the expected result is.

It delivers, the same result as `GET /_synapse/admin/v2/users`.
I'll set up a proxy referring to localhost:8008, so it's possible to use `/_synapse/admin`. Thanks.
