### ISSUE TITLE
upgrading from before 1.3.0 to 1.10.0 destroys all your rooms

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6923]
the `delete_old_current_state_events` background update clears `current_state_events` of any rooms with no rows where `membership='join'`. But `membership` is only populated by the `current_state_events_membership` update, so this goes badly.

**Comment by richvdh** [comment]
fixed by #6924

**Comment by sandhose** [comment]
Because the FreeBSD port is still on 1.10.0, I ran into this when I upgraded. Is there a way to recover from this? I'm the only user of my homeserver, there are not a lot of rooms to restore

**Comment by sandhose** [comment]
I kinda got my HS running again. What I did is:

 - backup my database before doing anything
 - update the room_version in the rooms table to be `1` when the field was NULL to get past [this error](https://github.com/matrix-org/synapse/blob/d9239b52571c7e07fa9b035de1ad46bb602ed163/synapse/handlers/message.py#L466)
 - try to rejoin all the rooms[^1]
 - delete the entries in `current_state_events` for rooms I could not manage to join
 - re-join those rooms

Right now I'm figuring out other conflicts in the database, mainly in *_historical tables

[^1]: basically something like this:

```
curl -X GET 'https://HS/_matrix/client/r0/joined_rooms' | jq -r '.joined_rooms[]' | while read r
do 
  curl -X POST "https://HS/_matrix/client/r0/join/$r"
done
```
