### ISSUE TITLE
purge room cause can't receive push

### ISSUE THREAD

**Issue by yangjinecho** [matrix-org/synapse#6926]
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by yangjinecho** [comment]
for version 1.9.0, if a and b in a room, a send a message then purge room(all data), after that  b send message , a can't get push notification.

**Comment by aaronraimist** [comment]
A deleted the room. Why would they get push notifications?

**Comment by yangjinecho** [comment]
i am sorry, it is purge_history api, not purge room.

**Comment by aaronraimist** [comment]
Do you have logs from when this is happening? I doubt push notifications are connected to if the history has been purged previously or not.

**Comment by yangjinecho** [comment]
receipts_linearized table and events table has problem，if purge history，the last read event id in receipts_linearized table removed in events table，then cause the bug.
