### ISSUE TITLE
Test "Local and remote users' homeservers remove a room from their public directory on upgrade" is flakey

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6932]
Just had this test flake out on me locally. Ran once and it failed, ran again and it passed.

We should blacklist it for now.

**Comment by anoadragon453** [comment]
This test is currently [getting skipped](https://buildkite.com/matrix-dot-org/synapse/builds/7151#def36d1e-a094-4e63-b83a-54ae99d0d28b/136-608) and I'm not sure why.

**Comment by richvdh** [comment]
presumably because "/upgrade creates a new room" failed?

**Comment by anoadragon453** [comment]
By why did that test fail and no cause CI to break?

Anyways, it's not happening on other branches' CI runs.

**Comment by richvdh** [comment]
because it's in the worker-blacklist

**Comment by richvdh** [comment]
> Anyways, it's not happening on other branches' CI runs.

in which case I assume the other tests aren't being skipped?

**Comment by anoadragon453** [comment]
> because it's in the worker-blacklist

Ahhh, that's it.

**Comment by anoadragon453** [comment]
> because it's in the worker-blacklist

Ahhh, that's it.

**Comment by anoadragon453** [comment]
I haven't seen this one flake out for a long while. It is however currently skipped in worker tests as `/upgrade creates a new room` is blacklisted for workers, which this test relies on.

If any test needs investigating, it's that one in worker mode.
