### ISSUE TITLE
The `replacement_room` in a room upgrade is not immediately joinable

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#6935]
I upgraded a room from matrix.org and the bridge (which lives on gnome.org) inside the room tried to handle the upgrade (it does this by trying to join the `content.replacement_room` as soon as it sees the upgrade event). The bridge tried to join `!HbIRFiVYbAwQBbobIc:matrix.org` and got a response of `{\"errcode\":\"M_UNKNOWN\",\"error\":\"Failed to make_join via any server\"}`.

Given this is a fresh room, I wouldn't have expected the room join to time out. The error seems to be a result of the remote side failing rather than gnome.org being too slow, so I am curious as to how this happened.

**Comment by richvdh** [comment]
does the bridge give a `server_name` argument when joining the replacement room? The need to do so is mentioned at https://github.com/matrix-org/matrix-doc/blob/master/proposals/1501-room-version-upgrades.md#client-changes-needed, though doesn't seem to have made it into the spec.

**Comment by richvdh** [comment]
closing this for now, because I think it's a client-side problem.

**Comment by turt2live** [comment]
> ... though doesn't seem to have made it into the spec.

https://github.com/matrix-org/matrix-doc/issues/2400
