### ISSUE TITLE
email settings error

### ISSUE THREAD

**Issue by MamasLT** [matrix-org/synapse#6955]
Hello. Im running newest Synapse on Ubuntu 18.04.
I have recently updated it and decided to update the homeserver.yaml config file manually, according to the one provided here:
https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml

There were some parts changed and rewritten recently.
I have changed and adjusted the email section as well, added all my previous settings, and deleted the template keys (because they are no longer present in new config). All these:

notif_template_html: notif_mail.html
notif_template_text: notif_mail.txt

expiry_template_html: notice_expiry.html
expiry_template_text: notice_expiry.txt

password_reset_template_html: password_reset.html
password_reset_template_text: password_reset.txt

registration_template_html: registration.html
registration_template_text: registration.txt

add_threepid_template_html: add_threepid.html
add_threepid_template_text: add_threepid.txt

password_reset_template_success_html: password_reset_success.html
password_reset_template_failure_html: password_reset_failure.html

registration_template_success_html: registration_success.html
registration_template_failure_html: registration_failure.html

add_threepid_success_html: add_threepid_success.html
add_threepid_failure_html: add_threepid_failure.html

But server doesnt start anymore, saying this:

"Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 639, in <module>
    main()
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 634, in main
    hs = setup(sys.argv[1:])
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 319, in setup
    "Synapse Homeserver", config_options
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/_base.py", line 617, in load_or_generate_config
    config_dict, config_dir_path=config_dir_path, data_dir_path=data_dir_path
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/_base.py", line 639, in parse_config_dict
    data_dir_path=data_dir_path,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/_base.py", line 254, in invoke_all
    res[name] = getattr(config, func_name)(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/emailconfig.py", line 264, in read_config
    % (", ".join(["email." + k for k in missing]),)
RuntimeError: email.enable_notifs is True but required keys are missing: email.notif_template_html, email.notif_template_text"

I added back all of those missing lines, but the problem is stil the same. So I don't understand what is the issue with this new config file, that I copied and why my server doesn't start anymore.

Also there seems to be strange issues, when errors appear only because there is an extra space before the parameter, even though all I did is just removed the # inf front of it. This might be a bug of some sort.

Thanks

**Comment by MamasLT** [comment]
Couple more issues with email settings:

1) The Synapse does not start and gives me an error:
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/etc/matrix-synapse/homeserver.yaml", line 1370, column 3
expected <block end>, but found '<block mapping start>'
  in "/etc/matrix-synapse/homeserver.yaml", line 1379, column 4

if i just uncomment the smtp_user: and smtp_pass: lines.

I have to delete one more extra space, for the error to go away- THIS IS CLEARLY A BUG or a disconection from the given default config.

2) In the new email config, it says:

# The port on the mail server for outgoing SMTP. Defaults to 25.
  #
  #smtp_port: 587

So one would assume, that this key doesn't need to be uncommented, if one wants to use port 25. Right? WRONG!
If I wont uncomment the port settings the Synapse gives me error:
RuntimeError: Password resets emails are configured to be sent from this homeserver due to a partial 'email' block. However, the following required keys are missing: email.smtp_port

Weird right?

I have commented out the #enable_notifs: true
and now server starts. It also loads the templates as normal from my email template folder.

Clearly something is very wrong here...

**Comment by richvdh** [comment]
the right place to get support for this kind of thing is `#synapse:matrix.org`. Note that indentation is important in yaml so we can't see what's going wrong when you paste it like this.

If, after discussion in #synapse:matrix.org, you think there is a bug, please open a new issue summarising it as succinctly as possible.

I'm going to close this for now.

**Comment by richvdh** [comment]
> Also there seems to be strange issues, when errors appear only because there is an extra space before the parameter, even though all I did is just removed the # inf front of it. This might be a bug of some sort.

It sounds like expected behaviour: again, indentation is important in yaml.

**Comment by MamasLT** [comment]
> the right place to get support for this kind of thing is `#synapse:matrix.org`. Note that indentation is important in yaml so we can't see what's going wrong when you paste it like this.
> 
> If, after discussion in #synapse:matrix.org, you think there is a bug, please open a new issue summarising it as succinctly as possible.
> 
> I'm going to close this for now.

Are you serious? I was told to open this in Synapse channel, thats why I did it.
And how come you don't see an issue, when config doesn't match Synapse behaviour? ITS DOESN'T WORK. It requires keys for email config, that are NOT PRESENT in your new config. 
So werid..

**Comment by richvdh** [comment]
(eventually turned into #6960 and #6961)

**Comment by zietsmand** [comment]
Hi @MamasLT 
How do you view the Python errors? I am also having trouble with the `email:` configuration yet my output is only:
```
ubuntu@ip-172-31-35-61:/etc/matrix-synapse$ sudo service matrix-synapse restart
Job for matrix-synapse.service failed because the control process exited with error code.
See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.
```
Which is pretty difficult to debug what properties in the `homeserver.yaml` is misconfigured.
