### ISSUE TITLE
Add ability for a user to change their password without invalidating their other devices

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6963]
https://github.com/matrix-org/synapse/pull/2722 ([relevant commit](https://github.com/matrix-org/synapse/commit/ad7e570d07e498e7a9395800650aeef0f9fbc914)) changed things so devices of a user (other than the one making the request) are deleted upon a password change.

It'd be nice if a user was able to change their password without resetting all of their devices (in the case that they just want a different, maybe more secure password, rather than their account being hacked).

**Comment by aaronraimist** [comment]
Also add that option to the admin API https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#reset-password

**Comment by richvdh** [comment]
@neilisfragile to discuss the UX implications of this with @lampholder

**Comment by neilisfragile** [comment]
After irl, we want the option to specify via the API but default to the current behaviour. So exactly as @lampholder describes above.

The idea being that the client can support ' I've been hacked, delete all devices!!!' flow along side a 'oh I just want to update my password' flow.

**Comment by clokep** [comment]
Done in #7085.
