### ISSUE TITLE
Error processing request XForwardedForRequest ... Unable to connect to server

### ISSUE THREAD

**Issue by c7hm4r** [matrix-org/synapse#6973]
### Description

Synapse logs errors like these:

```
daemon.info matrix-synapse[27526]:
  Error processing request <XForwardedForRequest at 0x0123456789af method='GET'
  uri='/_matrix/client/r0/sync?filter=0&timeout=30000&since=s012_34567_890_123_456_7_8901_234_5'
  clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'>
  Unable to connect to server.
```

### Steps to reproduce

1. Configure Nginx as reverse proxy for Synapse providing TLS.
2. Start Synapse and Nginx
3. Stop Nginx
4. → Some errors are logged
5. Start Nginx
6. → No errors appear anymore

### Remarks

Is it safe to have Synapse running while the reverse proxy is not running in general?

### Version information

- **Homeserver**: Own
- **Version**: 1.11.0+bionic1
- **Install method**: Debian package from matrix.org
- **Platform**: Ubuntu 18.04 on KVM VPS

**Comment by richvdh** [comment]
when federating, "unable to connect to server" lines are expected since, particularly in large rooms, there will often be unreachable servers.
