### ISSUE TITLE
Instructions/script for sorting out the mess caused by #6923

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6980]
A surprising number of people seem to be being bitten by #6923. We should probably try to figure out how to help these people

**Comment by richvdh** [comment]
It sounds like relatively few people have been affected by this, and I don't think we're going to do anything about it

**Comment by gollux** [comment]
Still, some are (like me). Do you have any hints on how to fix the mess? (In my case, it's several dozens of rooms, so I could fix that manually if I knew how.)

**Comment by richvdh** [comment]
oh gosh. well, you need to rebuild `current_state_events` for those rooms. 

The *correct* way to do this is:
 * for each `event_forward_extremities` value for each room, establish the room state at that event via `event_to_state_groups`, `state_groups_state` and `state_group_edges`. 
 * Use the state-resolution algorithm to resolve those sets of state
 * that gives the state which ought to go in `current_state_events` for that room

You could simplify that by just picking the most recent forward extremity and using the state at that event - but you'd still have to walk the state_groups tables.

We could approximate it still further by just looking for the most recent event for each `(type, state_key)` pair in the room. Something like:

For each affected room, look for distinct `(type, state_key)` pairs in `state_events`. For each pair, join `state_events` to `events` on `event_id` and look for the event with the highest `topological_ordering`. 

Left join on `room_memberships` to get the `membership` value for `m.room.member` events. (it should be NULL for other event types)

That should give you a set of `room_id, type, state_key, event_id, membership` values which you can insert into `current_state_events`.

**Comment by gollux** [comment]
I reconstructed `current_state_events` as you suggested, but it did not help. I am still getting errors "User <user> not in room <room>, and room previews are disabled." in Synapse log. I compared the `current_state_events` between a simple room which works and one which doesn't and they look very similar. Could there be anything else I have to recalculate?

**Comment by richvdh** [comment]
I assume you restarted synapse after updating the tables?

**Comment by gollux** [comment]
Yes.

**Comment by richvdh** [comment]
oh, you probably also need to update `local_current_membership`.

**Comment by gollux** [comment]
`local_current_membership` looks correctly for the room I am testing.
