### ISSUE TITLE
1.11 returns a different error code for /initialSync than 1.10

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#6992]
For years (decades?) Synapse has always returned `M_GUEST_ACCESS_FORBIDDEN` for `/initialSync` when the room isn't peekable, however 1.11 changed that to be `M_FORBIDDEN` .

The spec is, per usual, not very helpful here. Guest access errors seem most relevant given you aren't in the room yet and are in fact acting as a guest.

**Comment by richvdh** [comment]
yeah, this fell out of #6949. Note that peeking (https://matrix.org/docs/spec/client_server/r0.6.0#id116) and being a guest user (https://matrix.org/docs/spec/client_server/r0.6.0#guest-access) are different things, so I consider the new behaviour correcter.

**Comment by richvdh** [comment]
(in particular: it's possible for a room to permit guest access and not peeking, in which case it becomes obvious that `M_GUEST_ACCESS_FORBIDDEN` is a silly error code for this situation.)

**Comment by turt2live** [comment]
oh right, guest accounts. I wonder how I forgot about that...

It's a bit confusing how a change to aliases changed peeking, but I imagine it's something to do with shared code? Either way it kinda just helps justify why we need/should have CI that runs regression tests in Riot against current+develop Synapse: https://github.com/vector-im/riot-web/issues/12545
