### ISSUE TITLE
Consider deprecating the `age` property of events

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#6999]
Currently most C-S API endpoints include an `unsigned["age"]` property in each event. This is somewhat annoying to populate on the server (see #6998). Could we kill it off?

**Comment by turt2live** [comment]
ftr the spec says it's optional, but I believe at least riot relies on it existing for voip stuff when the client's time is wrong (but that could probably be made a problem for the user to deal with instead of us relying on the server's time)

**Comment by richvdh** [comment]
see also #8429: it probably doesn't even work.

**Comment by richvdh** [comment]
It seems like nowadays, it's actually specced.
