### ISSUE TITLE
docker image doesn't support tls 1.3

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7000]
for some reason, we build the docker image against libressl rather openssl, and libressl don't yet support tls1.3: https://github.com/libressl-portable/portable/issues/228.

That means that any docker-based synapse is going to fail to talk to a server which requires tls1.3 - which is becoming increasingly common.

**Comment by richvdh** [comment]
(also worth noting here that because the docker image is based on alpine linux, we cannot use the manylinux `cryptography` wheels which use a statically-linked openssl)

**Comment by maquis196** [comment]
testing today, not sure this is a problem anymore;

`
openssl s_client -connect localhost:8448 -tls1_3

Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
`
Was going to look at replacing libressl with openssl in our alpine dockerfile but alas, the above works. (tested with - Digest: sha256:71ee09081211)

**Comment by richvdh** [comment]
> testing today, not sure this is a problem anymore;

I'm not quite sure how that happened, but either way it should have been fixed by #7839.
