### ISSUE TITLE
Consider removing profile information upon deactivation

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#7005]
There's roughly three major uses of deactivation:
1. I'm done with this service, "delete" my account.
2. I'm an EU citizen and would like to be forgotten.
3. I'm a server admin and this individual doesn't need an account on my server anymore (abuse mitigation).

For cases 2 and 3 we can reasonably expect that the profile for that user should also be deleted/forgotten so that when it is queried down the line it isn't served to people/servers. The first case wouldn't really care I imagine.

**Comment by anoadragon453** [comment]
@turt2live What do you think about only removing the user's avatar when `"erase": true` is set in the request?

**Comment by turt2live** [comment]
Can that include the display name too?

**Comment by clokep** [comment]
Seems like it was, let's close it?
