### ISSUE TITLE
Email address is not automatically added to user profile when logging in with SAML2

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7023]
As part of the SAML2 login flow, we normally get an email address back from the SAML2 provider. We should take this address and add it to the homeserver account for use in things like notifications and potential binding with an IS.

(would need to be configurable: some people would rather not have this information automatically added to matrix accounts.)

**Comment by richvdh** [comment]
This is exacerbated by #5667, which means that there is no way to add an email address to your account after login (since https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-account-3pid-add requires UIA)

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/synapse/issues/7023
