### ISSUE TITLE
make the develop branch the default

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7025]
the use of a non-default develop branch is inconsistent with common practice in git.

* In the synapse 1.12 release notes, we will announce our intention change the default branch.
* Once synapse 1.13 is released, we will make `develop` our default branch
* [ ] maybe? update CONTRIBUTING.rst

**Comment by evitalis** [comment]
Is there a reference for this being common? I tend to see `dev` or `develop` branches on a large number of projects and `master` is usually meant to be stable and tied to releases. Just curious of the rationale, so I can keep up on things.

**Comment by richvdh** [comment]
it's just our experience of what other projects do (particularly those hosted in github). Feedback from contributors and new team members has consistently been that they find it surprising that the default branch is not the development tip. Our CONTRIBUTING.rst and PR template have to call it out specifically, and we still see a good number of PRs made against `master` initially.

To be clear: the main concern is whether the default branch should track the last release, or be the development tip. Whether that default branch is called `master` or `develop` is pretty incidental.

**Comment by babolivier** [comment]
This checklist should also probably include "update the CI" since there's definitely some stuff in the pipeline, in the tox files, in the SyTest Dockerfiles and some scripts on the Synapse side that assume that `develop` is the default branch to run stuff against.

**Comment by neilisfragile** [comment]
The most important thing to do is ensure that the default branch be the development tip.

So let's at least aim for consistency across major projects in the eco-system and make develop the default branch and have master track the most recent stable release - much as the riot repos do today.

**Comment by clokep** [comment]
Just an update: we released 1.13.0 today.

**Comment by richvdh** [comment]
and I've now set `develop` to be the default branch. It may be that CONTRIBUTING could do with a clarification, but I don't think it's actually wrong, so I'm calling this done
