### ISSUE TITLE
Is it possible to change the storage to a mysql database

### ISSUE THREAD

**Issue by FreeManNumOne** [matrix-org/synapse#7031]
Is it possible to change the storage to a mysql database

**Comment by FreeManNumOne** [comment]
We want to use synapse , but we are more familiar with mysql !

**Comment by richvdh** [comment]
sorry, mysql is not supported, and we don't have plans to add support.

**Comment by FreeManNumOne** [comment]
thank you much !

**Comment by richvdh** [comment]
dup #2112
