### ISSUE TITLE
It is not exist easy way to check what Synapse version currently installed and running.

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [matrix-org/synapse#7032]
**Description:**

It is not exist easy way to check what Synapse version currently installed and running.
It will be nice to have something to have opportunity to check or at least document it

**Comment by richvdh** [comment]
had you used the template when submitting this bug report, you've have seen it tells you how to find the current synapse version.

It's also documented at https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst:

![image](https://user-images.githubusercontent.com/1389908/75874903-97f01900-5e0a-11ea-9031-8e298f95bc3c.png)

**Comment by jpVm5jYYRE1VIKL** [comment]
then your documentation is bad organized. I tried to search in goodle and not found how to check version. In accordance with your advice need to read whole documentation files to find this solution.

**Comment by richvdh** [comment]
noted. PRs to improve the documentation would be welcome.
