### ISSUE TITLE
authentication via LDAP is still broken

### ISSUE THREAD

**Issue by git-minix** [matrix-org/synapse#7038]
### Description

Also with matrix-synapse version 1.11.0+stretch1 the LDAP auth is broken 

see closed issue https://github.com/matrix-org/synapse/issues/6772 and the hotfix from erikjohnston

### Steps to reproduce
Open Riot Web
Log in with any existing user
Error message: Fehler: Problem bei der Kommunikation mit dem angegebenen Home-Server. (M_UNKNOWN)

### Version information
matrix-synapse version 1.11.0+stretch1
Debian 9.12 

- **Install method**:
apt install

The old Hotfix works 
```
diff --git a/synapse/module_api/__init__.py b/synapse/module_api/__init__.py
index d680ee95e..80298ecee 100644
--- a/synapse/module_api/__init__.py
+++ b/synapse/module_api/__init__.py
@@ -37,6 +37,7 @@ class ModuleApi(object):
 
     def __init__(self, hs, auth_handler):
         self._hs = hs
+        self.hs = hs
 
         self._store = hs.get_datastore()
         self._auth = hs.get_auth()

```
Is there a permanent solution? I have expected that this old critical bug (since version 1.9) is fixed in the recent versions.

**Comment by git-minix** [comment]
```
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v1/login.py", line 150, in on_POST
    result = await self._do_other_login(login_submission)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v1/login.py", line 281, in _do_other_login
    identifier["user"], login_submission
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/auth.py", line 622, in validate_login
    is_valid = yield provider.check_password(qualified_user_id, password)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/rest_auth_provider.py", line 82, in check_password
    store = yield self.account_handler.hs.get_profile_handler().store
AttributeError: 'ModuleApi' object has no attribute 'hs'

```

**Comment by richvdh** [comment]
As #7038 explained, the permanent fix is for the external password providers to stop using internal parts of synapse: this is a bug in ma1sd, not synapse.

as #7038 also explains, it looks like a temporary patch has been made in ma1sd's master branch, but that has not been released yet. Also note that it's still using internal parts of the synapse, so it is likely to break again as synapse evolves.

**Comment by eMPee584** [comment]
> Also note that it's still using internal parts of the synapse, so it is likely to break again as synapse evolves.
Any ideas how to bend that proper?

**Comment by biotenshu** [comment]
Old Hotfix is not working anymore. Any another workaround?

`Aug  5 12:40:47 localhost matrix-synapse[8964]: 2020-08-05 12:40:47,522 - synapse.rest.client.v1.login - 195 - INFO - POST-0 - Got login request with identifier: {'type': 'm.id.user', 'user': 'user'}, medium: None, address: None, user: None
Aug  5 12:40:47 localhost matrix-synapse[8964]: 2020-08-05 12:40:47,522 - rest_auth_provider - 47 - INFO - POST-0 - Got password check for @user:matrix.localdomain.local
Aug  5 12:40:47 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.http.undertow.handler.auth.RestAuthHandler - Requested to check credentials for @user:matrix.localdomain.local
Aug  5 12:40:47 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.auth.AuthManager - Attempting authentication with store LdapAuthProvider
Aug  5 12:40:47 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Performing auth for @user:matrix.localdomain.local
Aug  5 12:40:47 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Checking possible match, DN: uid=user,ou=People,dc=localdomain,dc=local
Aug  5 12:40:47 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Attempting authentication on LDAP for uid=user,ou=People,dc=localdomain,dc=local
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Authentication successful for uid=user,ou=People,dc=localdomain,dc=local
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - DN uid=user,ou=People,dc=localdomain,dc=local is a valid match
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Processing 3PIDs for profile
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Processing 3PID type email
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - #011Attribute mail has 1 value(s)
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Processing 3PID type msisdn
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - #011Attribute mobile has 0 value(s)
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - Found 1 3PIDs
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.auth.AuthManager - @user:matrix.localdomain.local was authenticated by LdapAuthProvider, publishing 3PID mappings, if any
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.auth.AuthManager - Processing io.kamax.matrix.ThreePid@9b4477d3 for @user:matrix.localdomain.local
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-47] INFO io.kamax.mxisd.invitation.InvitationManager - Looking up possible pending invites for email:user@localdomain.local
Aug  5 12:40:48 localhost matrix-synapse[8964]: 2020-08-05 12:40:48,161 - rest_auth_provider - 63 - INFO - POST-0 - User @user:matrix.localdomain.local authenticated
Aug  5 12:40:48 localhost matrix-synapse[8964]: 2020-08-05 12:40:48,163 - rest_auth_provider - 77 - INFO - POST-0 - User @user:matrix.localdomain.local already exists, registration skipped
Aug  5 12:40:48 localhost matrix-synapse[8964]: 2020-08-05 12:40:48,163 - rest_auth_provider - 80 - INFO - POST-0 - Handling profile data
Aug  5 12:40:48 localhost matrix-synapse[8964]: 2020-08-05 12:40:48,163 - synapse.http.server - 83 - ERROR - POST-0 - Failed handle request via 'LoginRestServlet': <XForwardedForRequest at 0x7f09c534f080 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.1' site=8008>
Aug  5 12:40:48 localhost matrix-synapse[8964]: Traceback (most recent call last):
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Aug  5 12:40:48 localhost matrix-synapse[8964]:     result = g.send(result)
Aug  5 12:40:48 localhost matrix-synapse[8964]: StopIteration: {}
Aug  5 12:40:48 localhost matrix-synapse[8964]: During handling of the above exception, another exception occurred:
Aug  5 12:40:48 localhost matrix-synapse[8964]: Traceback (most recent call last):
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Aug  5 12:40:48 localhost matrix-synapse[8964]:     result = g.send(result)
Aug  5 12:40:48 localhost matrix-synapse[8964]: StopIteration: {}
Aug  5 12:40:48 localhost matrix-synapse[8964]: During handling of the above exception, another exception occurred:
Aug  5 12:40:48 localhost matrix-synapse[8964]: Traceback (most recent call last):
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Aug  5 12:40:48 localhost matrix-synapse[8964]:     result = g.send(result)
Aug  5 12:40:48 localhost matrix-synapse[8964]: StopIteration: @user:matrix.localdomain.local
Aug  5 12:40:48 localhost matrix-synapse[8964]: During handling of the above exception, another exception occurred:
Aug  5 12:40:48 localhost matrix-synapse[8964]: Traceback (most recent call last):
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 228, in _async_render_wrapper
Aug  5 12:40:48 localhost matrix-synapse[8964]:     callback_return = await self._async_render(request)
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 399, in _async_render
Aug  5 12:40:48 localhost matrix-synapse[8964]:     callback_return = await raw_callback_return
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 169, in on_POST
Aug  5 12:40:48 localhost matrix-synapse[8964]:     result = await self._do_other_login(login_submission)
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 287, in _do_other_login
Aug  5 12:40:48 localhost matrix-synapse[8964]:     identifier["user"], login_submission
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/auth.py", line 723, in validate_login
Aug  5 12:40:48 localhost matrix-synapse[8964]:     is_valid = await provider.check_password(qualified_user_id, password)
Aug  5 12:40:48 localhost matrix-synapse[8964]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/rest_auth_provider.py", line 85, in check_password
Aug  5 12:40:48 localhost matrix-synapse[8964]:     store = await self.account_handler._hs.get_profile_handler().store  # for synapse >= 1.9.0
Aug  5 12:40:48 localhost matrix-synapse[8964]: TypeError: object DataStore can't be used in 'await' expression
Aug  5 12:40:48 localhost matrix-synapse[8964]: 2020-08-05 12:40:48,165 - synapse.access.http.8008 - 310 - INFO - POST-0 - - - 8008 - {None} Processed request: 0.643sec/0.000sec (0.004sec, 0.003sec) (0.001sec/0.001sec/1) 55B 500 "POST /_matrix/client/r0/login HTTP/1.1" "mxisd/2.4.0" [0 dbevts]
Aug  5 12:40:48 localhost ma1sd[6332]: [XNIO-1 task-46] INFO io.kamax.mxisd.auth.AuthManager - http status = 500
`
