### ISSUE TITLE
force join for admin api

### ISSUE THREAD

**Issue by Tjeri** [matrix-org/synapse#7049]
You can force users to auto join on registration, but currently there is no option to make users auto join any other rooms.

It would be nice to be able to have the users auto accept invites or just directly put users in rooms without needing the step over invite.
This should probably go over the admin api.

**Comment by dklimpel** [comment]
@Tjeri you can use the new API from #7051 and close the issue.

**Comment by clokep** [comment]
Sounds like this is solved then! @Tjeri if the changes in #7051 don't solve your problem, please re-open this issue! 👍 Thanks @dklimpel!

**Comment by c10b10** [comment]
Any way to replicate this functionality for Room admins? ie. make it so users invited will automatically join without having to accept an invitation first?
