### ISSUE TITLE
Support for more architectures

### ISSUE THREAD

**Issue by schnaitterm** [matrix-org/synapse#7060]
This package, being python, should be pretty easy to package as an all/noarch package, at least for Debian and the like.  Is there as specific reason for the following case statement in `debian/build_virtualenv`?

```
case `dpkg-architecture -q DEB_HOST_ARCH` in
    amd64)
        export CFLAGS=-march=x86-64
        ;;
esac
```

As in, would something break if this were to be removed?  The gcc defaults when `-march` isn't specified should be generic enough.  If we take this out, we can then change the `Architecture: amd64` line in `debian/control` to `Architecture: all`.  I hacked this when building it myself on system Z (S390x) and it seems to be working fine.

**Comment by richvdh** [comment]
ftr: case statement in question is: https://github.com/matrix-org/synapse/blob/08815566bca79d001ad1bf58b2b082e435b6e5df/debian/build_virtualenv#L27-L31

**Comment by richvdh** [comment]
my understanding (see https://github.com/matrix-org/synapse/pull/4285#discussion_r240742468) is that if `-march` is not specified, then gcc will use instructions appropriate to the build server, which might prevent the built binaries from being used on other amd64 platforms. I was under the impression that it was common for debian package builds to specify `-march`, but I'm certainly no expert in the matter.

I'm not really following why this is causing you a problem though. If your `DEB_HOST_ARCH` is anything other than `amd64`, the `case` statement should do nothing?

**Comment by richvdh** [comment]
closing this pending more info
