### ISSUE TITLE
coturn server Relay  not work

### ISSUE THREAD

**Issue by wjhtinger** [matrix-org/synapse#7062]
I set a coturn server according to the turn-howto.md.  I use riot-android do the test and the STUN work well. But in some networks, STUN not success, but the Relay not work too. That means TURN not work, right?

So, what wrong with my server? How can I debug the problem?

**Comment by wjhtinger** [comment]
My coturn log as below:

0: log file opened: /var/log/turn_13151_2020-03-11.log
0: Config file found: /root/../etc/turnserver.conf
0:
RFC 3489/5389/5766/5780/6062/6156 STUN/TURN Server
Version Coturn-4.5.1.1 'dan Eider'
0:
Max number of open files/sockets allowed for this process: 4096
0:
Due to the open files/sockets limitation,
max supported number of TURN Sessions possible is: 2000 (approximately)
0:

==== Show him the instruments, Practical Frost: ====

0: TLS supported
0: DTLS supported
0: DTLS 1.2 supported
0: TURN/STUN ALPN supported
0: Third-party authorization (oAuth) supported
0: GCM (AEAD) supported
0: OpenSSL compile-time version: OpenSSL 1.0.2k-fips  26 Jan 2017 (0x100020bf)
0:
0: SQLite is not supported
0: Redis is not supported
0: PostgreSQL is not supported
0: MySQL is not supported
0: MongoDB is not supported
0:
0: Default Net Engine version: 3 (UDP thread per CPU core)

=====================================================

0: Domain name:
0: Default realm:
0:
CONFIG ERROR: Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
0:
CONFIGURATION ALERT: you did specify the long-term credentials usage
 but you did not specify the default realm option (-r option).
                Check your configuration.
0: WARNING: cannot find certificate file: turn_server_cert.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because certificate file is not set properly
0: WARNING: cannot find private key file: turn_server_pkey.pem (1)
0: WARNING: cannot start TLS and DTLS listeners because private key file is not set properly
0: NO EXPLICIT LISTENER ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering listener addresses: =========
0: Listener address to use: 127.0.0.1
0: Listener address to use: 103.39.213.189
0: Listener address to use: 10.39.213.189
0: Listener address to use: ::1
0: =====================================================
0: Total: 2 'real' addresses discovered
0: =====================================================
0: NO EXPLICIT RELAY ADDRESS(ES) ARE CONFIGURED
0: ===========Discovering relay addresses: =============
0: Relay address to use: 103.39.213.189
0: Relay address to use: 10.39.213.189
0: Relay address to use: ::1
0: =====================================================
0: Total: 3 relay addresses discovered
0: =====================================================
0: pid file created: /var/run/turnserver.pid
0: IO method (main listener thread): epoll (with changelist)
0: Wait for relay ports initialization...
0:   relay 103.39.213.189 initialization...
0:   relay 103.39.213.189 initialization done
0:   relay 10.39.213.189 initialization...
0:   relay 10.39.213.189 initialization done
0:   relay ::1 initialization...
0:   relay ::1 initialization done
0: Relay ports initialization done
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=0 created
0: IO method (general relay thread): epoll (with changelist)
0: turn server id=1 created
0: Total General servers: 2
0: IO method (auth thread): epoll (with changelist)
0: IO method (auth thread): epoll (with changelist)
0: IO method (admin thread): epoll (with changelist)

**Comment by worldowner** [comment]
I can confirm that it works quite randomly. Sometimes it's enough to clear cache from android client, sometimes restart of coturn + clear cache fixes the issue.

**Comment by wjhtinger** [comment]
I have done many tests, the Relay always fail, No exceptions. So I think there must be some wrong.

**Comment by wjhtinger** [comment]
> 
> 
> I can confirm that it works quite randomly. Sometimes it's enough to clear cache from android client, sometimes restart of coturn + clear cache fixes the issue.

I have done many tests, the Relay always fail, No exceptions. So I think there must be some wrong.

**Comment by worldowner** [comment]
How did you configure your synapse for STUN? Maybe you use TLS there while you don't have it in coturn.

**Comment by wjhtinger** [comment]
> 
> 
> How did you configure your synapse for STUN? Maybe you use TLS there while you don't have it in coturn.

I just follow the turn-howto.md to configure, just as below:

## Turn ##

# The public URIs of the TURN server to give to clients
turn_uris: [ "turn:xxxx.com:3478?transport=udp", "turn:xxxx.com:3478?transport=tcp" ]
turn_uris: [ "turn:xxxx.com:3478?transport=udp", "turn:xxxx.com:3478?transport=tcp" ]

# The shared secret used to compute passwords for the TURN server
turn_shared_secret: "7BMcc1B2IRh5ZSzIWcAZcjuC7h0XArUprznfJFfJXjs9xrmSMeYUM8ljSnMfj86m"

# The Username and password if the TURN server needs them and
# does not use a token
#turn_username: "TURNSERVER_USERNAME"
#turn_password: "TURNSERVER_PASSWORD"

# How long generated TURN credentials last
turn_user_lifetime: 86400000

**Comment by richvdh** [comment]
I don't think this is a synapse bug. You might find people in `#synapse:matrix.org` who can help configuring your system.
