### ISSUE TITLE
Constant high load on IO writes for postgres setup

### ISSUE THREAD

**Issue by RuralYak** [matrix-org/synapse#7071]
# Description

Postgress 12 db constantly produce high rate of IO writes to state_groups_state adding ~ 10000 new records per second. So the number of records for some rooms could reach 100M

### Steps to reproduce

- join active room (Synapse Admin for example)
- observe number of records for it

```
select count(1) from state_groups_state where room_id='!mjbDjyNsRXndKLkHIe:matrix.org';
count
```
ER: Growth of the table state_groups_state should be reasonable: 1K/ day for a single room
AR: Abnormal number of new rows resulting in constant disk writes could reach 10K/sec
![image](https://user-images.githubusercontent.com/25221496/76563693-24cb5000-6465-11ea-865d-33102f8fe685.png)
### Version information

synapse version: 
curl http://localhost:8008/_synapse/admin/v1/server_version
{
    "python_version": "3.7.6",
    "server_version": "1.11.1"
}
postgress: 12.2 (Debian 12.2-2.pgdg100+1))

- **Install method**:
docker image matrixdotorg/synapse:latest
sha256:0ca8c818316529cca0dd12fc26157e31f593763a4e13eaf55ebe3e71b906583b

- **Platform**:
 Kernel Version: 4.15.0-88-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.488GiB
 Docker Server Version: 19.03.7

# Logs
[server_logs.zip](https://github.com/matrix-org/synapse/files/4326416/server_logs.zip)

**Comment by richvdh** [comment]
how long has this been going on for? is it sustained or temporary? how many entries do you have in `state_groups_state` for `!mjbDjyNsRXndKLkHIe:matrix.org` ?

The "duplicate key" errors in your logs are concerning; I don't know if they are related or not. In any case, can you show the results of:

```sql
select * from event_relations where event_id='$eQ4C_QgZsdEsZbTKuzYmVey2XcpBqceIMHBZmEytXPE';
```

and

```sql
select * from events where event_id='$eQ4C_QgZsdEsZbTKuzYmVey2XcpBqceIMHBZmEytXPE';
```

**Comment by RuralYak** [comment]
> how long has this been going on for? 
Its been like that approximately a month

> is it sustained or temporary? 
it sustains on 32-35GB size of db

> how many entries do you have in `state_groups_state` for `!mjbDjyNsRXndKLkHIe:matrix.org` ?
```
select count(1) from state_groups_state where room_id='!mjbDjyNsRXndKLkHIe:matrix.org';
946525
```
> The "duplicate key" errors in your logs are concerning; I don't know if they are related or not. In any case, can you show the results of:
> 
> ```sql
> select * from event_relations where event_id='$eQ4C_QgZsdEsZbTKuzYmVey2XcpBqceIMHBZmEytXPE';
> ```
```
$eQ4C_QgZsdEsZbTKuzYmVey2XcpBqceIMHBZmEytXPE | $Ppa_FOF9mGnx9W0yxzxDqDE6oVqb4CWJWp4S2RYcBrE | m.replace     |
```
> 
> and
> 
> ```sql
> select * from events where event_id='$eQ4C_QgZsdEsZbTKuzYmVey2XcpBqceIMHBZmEytXPE';
> ```
```
174126 |                58361 | $eQ4C_QgZsdEsZbTKuzYmVey2XcpBqceIMHBZmEytXPE | m.room.message | !mjbDjyNsRXndKLkHIe:matrix.org |         |                   | t         | f       | 58361 |    15815182214
62 | 1581518223704 | @chichuks:matrix.org | f
```

**Comment by richvdh** [comment]
sorry, we seem to have dropped this. is it still an issue?
