### ISSUE TITLE
What means realm=turn.myserver.org?

### ISSUE THREAD

**Issue by jcabrerazuniga** [matrix-org/synapse#7072]
I am a bit confused here. Do we need to replace:

   turn.myserver.org

with some string related to our homeserver?

Since there is a web site using myserver.org I believe I shouldn’t touch this line.

Am I missing something?

**Comment by vastroh** [comment]
Yes, you must specify a real domain name (it is not necessary to allocate a subdomain for TURN).

**Comment by jcabrerazuniga** [comment]
So, if my server can be found using:

     mymatrixserver.sports.mystation.edu

then should I use

 realm = turn.mymatrixserver.sports.mystation.edu ?

Thx

**Comment by richvdh** [comment]
this is not the place for support in configuring a turnserver.

**Comment by jcabrerazuniga** [comment]
I am not asking about support for the tunserver.... Please, read well! I am asking about how it needs to be configured to be used with Synapse... so basically this is about Synapse!

**Comment by richvdh** [comment]
it's not the place for ask for support in how to configure synapse, either. try `#synapse:matrix.org`.

**Comment by jcabrerazuniga** [comment]
Thanks for the link,.but your answer about what can be asked here is very ambiguous. Configuration issues (as your docs do not document this quite well) could easily be confused as app issues. And this link mentions: https://github.com/matrix-org/sypnapse. If my memory serves I came to this github link from the one you just gave me. Thanks anyway.

**Comment by richvdh** [comment]
if you have a concrete, actionable suggestion for an improvement in the app, feel free to file an issue. If you have questions along the lines of "how do I use this app", then you are better off talking in real-time to people with experience of it.

**Comment by jcabrerazuniga** [comment]
I wouldn't be asking this question if your docs were clear. I work at a place where we consider important to have good documentation for our apps and we are thankful for reported errors regarding those docs. Good documentation helps a lot with the quality of any application. This means to be professional.

**Comment by richvdh** [comment]
yes, good documentation is important. Once you figure out the answer to your question perhaps you can help us by submitting a PR to improve them.
