### ISSUE TITLE
youtube.com/embed URL doesn't give a useful preview

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#7081]
**Description:**

<img width="905" src="https://user-images.githubusercontent.com/5855073/76707645-fc3e9280-66be-11ea-88e9-491fbadd2a81.png">

It would be nice to get an image for youtube.com/embed/... URLs

**Comment by richvdh** [comment]
it would be nice, but I don't see how we could do it short of special-casing `/embed` URLs and rewriting them to the regular URL. The HTML that gets served on the `/embed` URL is just a javascript vomit, unlike the regular page which contains `og` meta-tags which link tot he preview, etc.

**Comment by aaronraimist** [comment]
Probably best to solve this on the bot end then
