### ISSUE TITLE
Setting account_validity to diabled crashes synapse

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/synapse#7082]
### Description

When disabling account_validity checking by setting enabled to false, synapse barfs while parsing the config file with the following error: `AttributeError: 'AccountValidityConfig' object has no attribute 'renew_email_subject'`.

See also #6199 for an example with a full backtrace.

### Steps to reproduce

- configure account_validity
- instead of setting `enabled: true`, use `enabled: false`
- try to start synapse

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: neko.dev

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.11

- **Install method**: custom ebuild
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Gentoo
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by giomfo** [comment]
thx @deepbluev7 
FYI this will be fixed by PR #7074

**Comment by anoadragon453** [comment]
#7074 has been merged.

**Comment by deepbluev7** [comment]
Well, that was fast, thanks!
