### ISSUE TITLE
Rooms with unsupported versions are shown as blank rooms

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7083]
In the last ~4-5 days

`!VXChyxVNCBsWeSGcaN:sw1v.org`
`!eKTrlepAvBEhUIyoQV:jki.re`
`!bNAPsppHlSHCDvMRhh:abolivier.bzh`

**Comment by ara4n** [comment]
(i haven't actually looked at my /sync response, but riot shows them to be entirely blank v1 rooms)

**Comment by neilisfragile** [comment]
I also can't see ```!eKTrlepAvBEhUIyoQV:jki.re```

**Comment by erikjohnston** [comment]
All three of those rooms use experimental room versions that have since been removed from synapse, I think its basically expected for those to go pop.

**Comment by neilisfragile** [comment]
Right and it just about works okay when people have cached history, but switching over to a new client (like Riot electron) has this problem.

**Comment by richvdh** [comment]
I'm going to suggest we triage this alongside other synapse bugs rather than treat it as a crisis.

**Comment by clokep** [comment]
#7209 also points to some errors during initial sync for unknown room versions.

**Comment by richvdh** [comment]
suggestion is that for now we exclude such rooms from initial /sync responses, thus hiding them on clients. (you'll have to flush your client cache, but we can live with that)

In future, if we drop production room versions (eg v1) we'll need to do better than this, but this will do as a first step.

**Comment by ara4n** [comment]
how do I get back into these rooms, though? i can't seem to participate in them enough to follow the tombstone to the new version...

**Comment by richvdh** [comment]
you don't. The whole point is that they were experimental room versions that are no longer supported. I guess you get someone to manually invite you to the new room.

**Comment by anoadragon453** [comment]
Worth noting that deleting the room from `rooms` and the events from `events` and `events_json` clears them right up.

**Comment by erikjohnston** [comment]
Currently `/purge_rooms` fails to delete these rooms, as users are in them. Might be worth fixing it so that it works?

**Comment by jryans** [comment]
Personally, I would at least like to be able to leave these unsupported rooms, but currently even that is not possible... 😢 

Currently, the `/leave` request gives a 400 error with `M_UNSUPPORTED_ROOM_VERSION`. The unfortunate symptom of this is that the unleavable room is permanently at the top of my room list... 😭

**Comment by clokep** [comment]
> Personally, I would at least like to be able to leave these unsupported rooms, but currently even that is not possible... 😢

The technical reason behind this is that Synapse doesn't know how to resolve state in those rooms.

**Comment by anoadragon453** [comment]
Can we just generate a local out-of-band leave event for the client, just as we do when rejecting an invite/rescinding a knock from a room that we're not in and cannot contact?

https://github.com/matrix-org/synapse/blob/96f6293de51c2fcf530bb6ca3705cf596c19656f/synapse/handlers/room_member.py#L1404-L1425

It just generates a leave event that's propagated to the client, but not into the room proper.

**Comment by richvdh** [comment]
even out-of-band leaves go through state res...

**Comment by richvdh** [comment]
I think? maybe not, actually. Might be worth a go. (but then, I still think it would be easier just to exclude unsupported rooms from `/sync`.)

**Comment by clokep** [comment]
> I think? maybe not, actually. Might be worth a go. (but then, I still think it would be easier just to exclude unsupported rooms from `/sync`.)

I'm fairly certain they do, we still generate an event which requires a known room version (and it also requires auth/prev events).
