### ISSUE TITLE
Events going missing from incremental /syncs

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7084]
I've had several instances in the last 4-5 days where messages and/or state have gone missing from my clients.  It's unclear whether these are clientside or serverside bugs, but in combination with https://github.com/matrix-org/synapse/issues/7083 and https://github.com/matrix-org/synapse/issues/7065 i'm wondering there are synapse-side regressions going on.

These have all happened in v5 rooms, as far as I know.

Concretely:
 * https://github.com/matrix-org/riot-ios-rageshakes/issues/3976
 * https://github.com/matrix-org/riot-web-rageshakes/issues/2375

Also, https://github.com/vector-im/riot-web/issues/7843 seems to be a grabbag of "my client got out of sync with the server somehow".  However, some of these seem to be "a chunk of my history went missing" and i don't know why - which could point at synapse providing unreliable sync responses.

**Comment by ara4n** [comment]
Conclusion: i'll look at the rageshakes to try to infer whether this is clientside or serverside before team synapse looks further.

**Comment by richvdh** [comment]
going to close this pending further info.
