### ISSUE TITLE
Limit concurrent creation of events in a room

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#7086]
When Synapse generates new events it ensures that they have a max of ten `prev_events`. This has the effect that if more than ten events get generated for a room concurrently (i.e. they get generated before the other events are persisted) then we'll end up with more than ten events as forward extremities. A single subsequent event will therefore not clear out all the forward extremities, and so if synapse tries to generate more than ten events concurrently for a long period of time the number of forward extremities will grow.

This has happened on matrix.org where a bridged freenode room ended up having ~1.6k extremities. (This then had performance implications as all events had ten extremities, and so state res happened a lot).

**Comment by richvdh** [comment]
> all events had ten extremities

events don't have extremities. `prev_events`, maybe?

**Comment by erikjohnston** [comment]
This is done. There is a bug for worker mode in #7792
