### ISSUE TITLE
Invite rejection fails due to ACL ban

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#7090]
### Steps to reproduce

- register spammer account on spammer server, create spam room
- invite Victim into SpamRoom
- ACL BAN Victim, VictimServer in room
- Victim invite_reject (room leave) gets 403 forbidden from spammer_server
- invite stays on forever (locally rejected in local db)

**Comment by richvdh** [comment]
does the invite go away when you clear the cache (making this a duplicate of #2181)?

**Comment by grinapo** [comment]
It did. Plain reload didn't help, but clear-cache made it to go away. 
Thanks.
