### ISSUE TITLE
OpenSSL Error about Certificated Authenticity Breaking Federation

### ISSUE THREAD

**Issue by JonQuan1** [matrix-org/synapse#7098]
### Description

I am unable to federate with any instance on the Matrix network. My system is fully up to date, and all my SSL certificates are still valid

When looking at the logs I notice this error repeated over and over:

```
Mar 17 23:36:46 archserver synapse[1269341]: 2020-03-17 23:36:46,242 - synapse.http.matrixfederationclient - 485 - WARNING - renew_attestations-15 - {POST-O-137} [[cencored]] Request failed: POST matrix://[cencored]: RequestTransmissionFailed:[Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])]

Mar 17 23:36:46 archserver synapse[1269341]: 2020-03-17 23:36:46,242 - synapse.groups.attestations - 202 - WARNING - renew_attestations-15 - Failed to renew attestation of '@[cencored]' in '+[cencored]': Failed to send request: RequestTransmissionFailed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]
```

### Steps to reproduce

I don't know exactly what caused this bug, it just spontaneously occurred

### Version information

- ** Only My Homeserver**:

- **Version**:
1.11.0-1
- **Install method**:
Followed the Arch Wiki

- **Platform**:
Arch Linux on a Dell OptiPlex 7010

**Comment by neilisfragile** [comment]
It looks like your certificate has not renewed. What is the output of https://federationtester.matrix.org/ ?

**Comment by JonQuan1** [comment]
> It looks like your certificate has not renewed. What is the output of https://federationtester.matrix.org/ ?

It was a certificate issue. Apparently when i went to replace and renew certificates one domain wasn't pointing to my server which caused the entire process to abort, but the certbot tool didn't even bother to mention that it had failed
