### ISSUE TITLE
we seem to be returning the wrong error code when adding an undefined alias to canonical_alias

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7105]
we're returning a 404 with `{errcode: "M_NOT_FOUND", error: "Room alias #megolm:sw1v.org not found"}`; https://github.com/matrix-org/matrix-doc/pull/2432#discussion_r388457807 suggests a different conclusion.

The upshot is that the error message in riot is unhelpful:
![Peek 2020-03-19 09-38](https://user-images.githubusercontent.com/1389908/77053780-c18e7000-69c6-11ea-8b5b-ee6ba3bfc63e.gif)

**Comment by richvdh** [comment]
related to #6898

**Comment by clokep** [comment]
@richvdh I believe this is working as expected. The validation code throw three errors:
1. `M_INVALID_PARAM` if the form of the alias is wrong.
2. `M_NOT_FOUND` if the alias is completely unknown.
3. `M_BAD_ALIAS` if the alias is found, but does not point to this room.

I think this matches the comment you pointed to, when taking into account the context of the conversation above it.

Note that the logic for this was implemented in #6971, although it is a bit hard to see:
1. `M_INVALID_PARAM` is raised from `RoomAlias.from_string()`
2. `M_NOT_FOUND` is raised via `directory_handler.get_association()`
3. `M_BAD_ALIAS` is raised directly.

**Comment by clokep** [comment]
This was fixed in #7109.
