### ISSUE TITLE
video user timeout

### ISSUE THREAD

**Issue by xsq0718** [matrix-org/synapse#7132]
### Description

[root@izbp1czplot2hq98jaybtdz matrix]# journalctl -fu matrix-synapse
-- Logs begin at Wed 2020-03-11 23:37:00 CST. --
Mar 19 14:37:25 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:37:25,106 - synapse.http.site - 203 - WARNING - GET-2613 - Error processing request <XForwardedForRequest at 0x7fbd40b43310 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_333_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 19 14:37:25 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:37:25,115 - synapse.http.server - 465 - WARNING - GET-2613 - Not sending response to request <XForwardedForRequest at 0x7fbd40b43310 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_333_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
Mar 19 14:39:58 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:39:58,940 - synapse.http.site - 203 - WARNING - GET-2642 - Error processing request <XForwardedForRequest at 0x7fbd4093f6d0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_341_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 19 14:39:58 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:39:58,949 - synapse.http.server - 465 - WARNING - GET-2642 - Not sending response to request <XForwardedForRequest at 0x7fbd4093f6d0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_341_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
Mar 19 14:44:49 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:44:49,911 - synapse.http.site - 203 - WARNING - GET-2669 - Error processing request <XForwardedForRequest at 0x7fbd4011dbd0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_349_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 19 14:44:49 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:44:49,919 - synapse.http.server - 465 - WARNING - GET-2669 - Not sending response to request <XForwardedForRequest at 0x7fbd4011dbd0 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s130_349_16_66_84_1_1_17_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
Mar 19 14:45:42 izbp1czplot2hq98jaybtdz matrix-synapse[21747]: 2020-03-19 06:45:42,545 - synapse.push.httppusher - 387 - WARNING - httppush.process-91 - Failed to push event $fl4-y-uY3dNQZg9_PZ8cD5pOs_dGtlKs2gFPwBPGnak to @test4:mydomain/im.vector.app.ios.voip.prod/kEias6zIYvjR4fr0YZG2GXiqLnwuRhKGQKxD87PEGV4=: <class 'twisted.internet.error.TimeoutError'> User timeout caused connection failure.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
matrixdotorg/synapse   v1.11.1
- **Install method**:
docker pull matrixdotorg/synapse:1.11.1
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
CentOS Linux release 7.4.1708 (Core) 
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
please can you use triple-backticks to format the logs legibly, and explain more clearly what the symptoms are. none of the log lines above look inherently wrong.

**Comment by xsq0718** [comment]
```
Mar 24 18:29:32 iz8vbi4t4rsi4jttn2hmjyz matrix-synapse[15541]: 2020-03-24 10:29:32,400 - synapse.push.httppusher - 423 - WARNING - http_pusher.on_new_receipts-24 - Failed to send badge count to @batest:hy110.tonkor.com/im.vector.app.ios.voip.prod/5ukWBEwGWb7xzDjJcvBZe7aZj1n2hiZ1aC9XBYYxXqw=: <class 'twisted.internet.error.TimeoutError'> User timeout caused connection failure.
Mar 24 18:30:10 iz8vbi4t4rsi4jttn2hmjyz matrix-synapse[15541]: 2020-03-24 10:30:10,134 - synapse.http.site - 203 - WARNING - GET-1763 - Error processing request <XForwardedForRequest at 0x7fede32ac310 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s119_230_6_75_45_1_1_27_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Mar 24 18:30:10 iz8vbi4t4rsi4jttn2hmjyz matrix-synapse[15541]: 2020-03-24 10:30:10,144 - synapse.http.server - 465 - WARNING - GET-1763 - Not sending response to request <XForwardedForRequest at 0x7fede32ac310 method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s119_230_6_75_45_1_1_27_1&timeout=30000' clientproto='HTTP/1.0' site=8008>, already disconnected.
```

@batest  is IOS device，not can  IOS call Android video or Android call IOS video ，IOS device is twisted.internet.error.TimeoutError
ios app version 0.10.4, OS 12.4.1
android app version 0.9.9

**Comment by richvdh** [comment]
ok, this sounds like an issue with your turn server, not a synapse bug.

The log lines above are completely unrelated to video calling.

You might be able to get some support in `#synapse:matrix.org`, but you'll need to be much clearer about what you've tried so far and what errors you are seeing on the client.
