### ISSUE TITLE
email_notif_for_new_users is ignored when creating new users via the Admin API

### ISSUE THREAD

**Issue by florianjacob** [matrix-org/synapse#7135]
### Description

I created a few uses via the [Synapse Admin API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/README.rst) using the new `threepids` option to assign email addresses. I noticed though that the new users don't receive push notifications via the configured email address, despite having the `notif_for_new_users` configuration option set.

### Steps to reproduce

- run a synapse server with setting `notif_for_new_users: true` (the default) and a working email configuration
- Create a new user via the [“Create or modify Account”](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#create-or-modify-account) Admin API
```
PUT /_synapse/admin/v2/users/testuser
{
    "password": "testuser_password",
    "threepids": [
        {
            "medium": "email",
            "address": "testuser@example.org"
        }
    ]
}
```

- login as testuser
- see that the email address is present in the user settings
- see that email notifications for the address however are disabled in the user notification settings

### Relevant Code Sections in v1.12.0

- [notif_for_new_users setting](https://github.com/matrix-org/synapse/blob/v1.12.0/docs/sample_config.yaml#L1506)

- [email_notif_for_new_users check on interactive registration](https://github.com/matrix-org/synapse/blob/v1.12.0/synapse/handlers/register.py#L630)

- [missing check in user admin API somewhere around here](https://github.com/matrix-org/synapse/blob/v1.12.0/synapse/rest/admin/users.py#L275)

### Version information

- **Homeserver**: self-hosted

- **Version**: 1.12.0

- **Install method**: package manager

- **Platform**: NixOS 19.03

**Comment by clokep** [comment]
Looks like this is probably an oversight. The code sections you pointed out look reasonable, any chance of putting those changes up as a PR?
