### ISSUE TITLE
Use Retry-After header in addition to retry_after_ms

### ISSUE THREAD

**Issue by sents** [matrix-org/synapse#7138]
**Description:**

When exceeding the rate limit synapse sends a `429, M_LIMIT_EXCEEDED` response with the json-attribute `retry_after_ms`. There seems to be a standard response header for this: [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After)
Using this header in addition to the retry_after_ms attribute would make it easier to handle the retries in common http libraries.

**Comment by anoadragon453** [comment]
Nice idea! Though this is more of an issue for the [Matrix Specification repo](https://github.com/matrix-org/matrix-doc/) than Synapse. Once it's cleared in the spec it can be added to Synapse :)

**Comment by sents** [comment]
Ok, then I will open this issue in the spec repo. Thank you!
