### ISSUE TITLE
homeserver.yaml variable to specify self hosted jitsi-server

### ISSUE THREAD

**Issue by zaggynl** [matrix-org/synapse#7166]
As per subject.
For privacy and to take load off public jitsi-meet servers.

**Comment by olmari** [comment]
I'd say most correct place would be client .well-known, so every client would know what to do, as Jitsi is still after all client widget more than homeserver feature as is... But in any way, some method for clients to know what Jitsi server to use, that doesn't require configuring client config itself, which is impossible for mobile clients and so on.

**Comment by richvdh** [comment]
closing this in favour of https://github.com/matrix-org/matrix-doc/issues/2488. We'd need to figure out how/if this would fit into the matrix protocol before it could be implemented in synapse.
