### ISSUE TITLE
IOS calls not working

### ISSUE THREAD

**Issue by myoussef89** [matrix-org/synapse#7168]
I tried to test from android > android on different networks and its working with the turn server,
when I try from android > IOS or from IOS > IOS  on the same network it's working.
when I try from android > IOS or from IOS > IOS on different networks it's not working.

did anyone faced like an issue before, or any clue for that?

Android 9
IOS13.4
synapse:v0.31.1

**Comment by Half-Shot** [comment]
First off, you are running Synapse 0.31.1 which is unsupported and very old. You should try updating (carefully) to [a newer release](https://github.com/matrix-org/synapse/releases).

Secondly. This isn't the support place for mobile apps. See: https://github.com/vector-im/riot-ios

**Comment by myoussef89** [comment]
thanks
