### ISSUE TITLE
"register user" admin api is incorrectly blocked if the MAU limit has been reached

### ISSUE THREAD

**Issue by Twi1ightSparkle** [matrix-org/synapse#7175]
### Description
If the server has a MAU user limit, you can add unlimited users accounts. But you cannot add accounts if MAU is rached

### Steps to reproduce

- reach mau limit
- add new user account

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information
v1.12.0

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: At least all Modular servers

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)

- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Container

**Comment by anoadragon453** [comment]
It's expected that a normal user cannot register, however it's likely not expected that one cannot register new users through the Admin API.

If we want to make that change, `check_auth_blocking` should probably not be run here if the call is coming through the Admin API:

https://github.com/matrix-org/synapse/blob/326c893d24e0f03b62bd9d1136a335f329bb8528/synapse/handlers/register.py#L166

**Comment by dklimpel** [comment]
Is it a solution to test if `address` is `null`?
Like here:
https://github.com/matrix-org/synapse/blob/326c893d24e0f03b62bd9d1136a335f329bb8528/synapse/handlers/register.py#L164
https://github.com/matrix-org/synapse/blob/9bae740527c4621f9f8eb8ca936669f2372c42eb/synapse/handlers/register.py#L420-L432

The call from admin API has no address.

**Comment by richvdh** [comment]
there's some debate on what is the right wait to fix this inconsistency...

**Comment by richvdh** [comment]
ok, sounds like we're agreed that the MAU limit should not apply to the admin api.
