### ISSUE TITLE
Security breach: an unencrypted messages is sent to encrypted room

### ISSUE THREAD

**Issue by 532910** [matrix-org/synapse#7180]
Just updated synapse to 1.12.0-1~bpo10+1, debian buster-backports.

And just received an unencrypted message from another user on my homeserver (the message send from riot for android), on my side it looks so:

desktop version:
![image](https://user-images.githubusercontent.com/14617699/78017807-83ddff80-7355-11ea-813f-9e548404ac53.png)

android:
![image](https://user-images.githubusercontent.com/14617699/78018044-de775b80-7355-11ea-981d-6e14ee57a565.png)

The room is encrypted:
![image](https://user-images.githubusercontent.com/14617699/78018158-0ff02700-7356-11ea-9793-d54293ea37cc.png)

![image](https://user-images.githubusercontent.com/14617699/78018514-b2100f00-7356-11ea-95bc-c8012afa1831.png)

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-doc/issues/884
