### ISSUE TITLE
CAS authentication

### ISSUE THREAD

**Issue by souvikbhattacharyas** [matrix-org/synapse#719]
Hi,
In matrix configuration I found CAS integration mechanism is already present but I have few questions.

After CAS auhtentication is integrated user will not be able to register in Matrix rather they will be authenticated to the CAS server and through CAS authentication they will logged in to Matrix. During Matrix registration it accepts few parameter like Email,Name but in CAS authentication parameters only name option is specified in required attributes. How to store email and other details in Matrix. 

Do you have any documentation regarding CAS integration of Matrix.

Also do we have LDAP support.

**Comment by richvdh** [comment]
Please come to https://matrix.to/#/#matrix:matrix.org for support questions.
