### ISSUE TITLE
Bridge for BigBlueButton?

### ISSUE THREAD

**Issue by fooness** [matrix-org/synapse#7215]
Would it be possible to integrate [BigBlueButton](https://docs.bigbluebutton.org/dev/api.html) as was also done with [Jitsi](https://matrix.org/blog/2017/08/23/introducing-matrix-widgets)?

**Comment by clokep** [comment]
Thanks for your interest in Matrix! Synapse doesn't directly integrate with Jitsi, I would suggest filing an issue at https://github.com/vector-im/riot-web
