### ISSUE TITLE
Error in synchrotron worker doc

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/synapse#7216]
Error in URLs of synapse.app.synchrotron in documentation:
https://github.com/matrix-org/synapse/blob/master/docs/workers.md
```
    ^/_matrix/client/(v2_alpha|r0)/sync$
    ^/_matrix/client/(api/v1|v2_alpha|r0)/events$
    ^/_matrix/client/(api/v1|r0)/initialSync$
    ^/_matrix/client/(api/v1|r0)/rooms/[^/]+/initialSync$
```

Should be:
```
    ^/_matrix/client/(v2_alpha|r0)/sync
    ^/_matrix/client/(api/v1|v2_alpha|r0)/events
    ^/_matrix/client/(api/v1|r0)/initialSync
    ^/_matrix/client/(api/v1|r0)/rooms/[^/]+/initialSync
```

See: https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-sync

**Comment by clokep** [comment]
@dklimpel The only difference I see is the ending `$`, I believe those are necessary for the regular expressions to be matched properly -- what issue are they causing for you?

**Comment by dklimpel** [comment]
The ending `$` is the end of the requestet URL. But in real it is not the end.
For example:
`/_matrix/client/r0/sync?filter=66696p746572&since=s72594_4483_1934&full_state=false&set_presence=offline&timeout=30000`
The end is behind `30000` and not behind `sync`.
The examaple URL mismatch with the regex in documentation.

**Comment by clokep** [comment]
The `$` is meant to match the end of the path, e.g. it ensures that `/_matrix/client/r0/sync` is matched, but not `/_matrix/client/r0/sync/foo`. I believe that web servers are only targeting the path with those regular expressions, not including the query parameters.

Are you seeing something different? If so, can you please provide some more info about your setup (what web server / reverse proxy).

**Comment by dklimpel** [comment]
Second test with nginx was successfully.

**Comment by clokep** [comment]
Thanks for re-testing! 👍
