### ISSUE TITLE
Synapse Homeserver deleted local messages when using purge API

### ISSUE THREAD

**Issue by jakem72360** [matrix-org/synapse#7217]
### Description

I recently tried to reduce the size of my `homeserver.db` file by issuing
requests to Synapse's Purge History API. After restarting Synapse, all of the
messages in the purged rooms (including my locally sent messages), have been
deleted. This was confirmed by manually inspecting the SQLite database.
Scrolling up to the point of deletion in Riot, yields no results. A loading
spinner shows momentarily, then stops.

### Steps to reproduce

- Retrieve a list of the room IDs to which your user is a member using the client-server API.
- Iterate the list and issue requests using the following shell snippet
`cat <list file> | while read i; do curl -X POST "https://<server>/_synapse/admin/v1/purge_history/$i?access_token=<token>" -d "{\"purge_up_to_ts\":$(date -d '-2 days' +%s)000}"; done`
- Stop Synapse using `systemctl stop synapse`, or a relevant init command
- Run `sqlite3 /var/lib/synapse/homeserver.db 'VACUUM;'`
- Restart Synapse

According to the API docs, the above actions should only remove locally cached
messages, however, **ALL** messages have up to two days have been removed from
the homeserver including locally sent messages between users on the affected
server.

Majority of messages (including my own), still exist in the database of a
sister-server, that is a participant in the majority of rooms on the affected
server. Is there any way to transfer them to the database of the affected
server?

### Version information

- **Homeserver**: personal homeserver

- **Version**:
```
{
    "python_version": "3.8.2",
    "server_version": "1.11.1"
}
```

- **Install method**: Arch Linux Repos

- **Platform**:
Arch Linux running inside a VMWare VM.

**Comment by clokep** [comment]
@jakem72360 Could you provide logs for the period of time around when you purged the rooms? Thanks.

**Comment by jakem72360** [comment]
@clokep [Here is a complete copy of the log](https://files.catbox.moe/z83irk.xz) (with domains redacted). The logging verbosity was low, so I doubt they contain any significant information.

**Comment by richvdh** [comment]
Hi @jakem72360; unfortunately it's unlikely we'll be able to investigate it without at least INFO-level logs. Please could you turn INFO-level logging back on and reproduce it?

**Comment by richvdh** [comment]
closing this pending the info needed to debug.
