### ISSUE TITLE
Raise default power level for enabling e2ee support to 100

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#7229]
Currently moderators (PL 50) can enable e2ee which seems like a lot of responsibility given doing so is an irreversible action.

Instead it would be better to limit it to admins with PL 100.

I'm not proposing that existing rooms are changed retrospectively.

**Comment by anoadragon453** [comment]
Fixed in https://github.com/matrix-org/synapse/issues/7229
