### ISSUE TITLE
Need Basic Install/Config Instructions

### ISSUE THREAD

**Issue by snakyjake1** [matrix-org/synapse#7244]
Might anyone have the **most** simple basic install/config instructions?

I'm setting this up on a private network.  No firewall.  No domain.  I want to get it running on HTTP, and once I get that far, configure for HTTPS.

I tried https://riot.im/app/#/login, and tried using http://192.168.1.176 as the home URL. 
Error:  Cannot reach homeserver

I figure I'm missing a few steps in the install/config.

Confusing areas:
1) Install was asking for a domain.  I don't have one, but gave it something.  Now I don't remember what I gave it, or how to change it.
2) homeserver.yaml.  The instructions were confusing, because I'm not sure it was relevant to me.  

Thanks.
Ubuntu LXD container.

**Comment by richvdh** [comment]
we've done our best to make https://github.com/matrix-org/synapse/blob/master/INSTALL.md as easy to follow as possible. With respect, running synapse does require a basic level of experience of system administration; if you find it challenging, you may wish to consider paying someone to host synapse for you.

> I tried https://riot.im/app/#/login, and tried using http://192.168.1.176 as the home URL.
Error: Cannot reach homeserver

You can't use an http url from an https website. You will need to set up TLS before you can use it from riot.im.
