### ISSUE TITLE
Split homeserver.yaml into multiple files

### ISSUE THREAD

**Issue by BoarderEB** [matrix-org/synapse#7246]
The homeserver.yaml is currently 1827 lines long. With this length it is very difficult to get an overview of the config.

Therefore, a division into a conf.d directory for the overview would be very helpful.

**Comment by richvdh** [comment]
The sample config is split into sections (admittedly this could be done more consistently and more clearly). I'm not convinced that splitting it into multiple files would make it much easier to get an overview.

**Comment by BoarderEB** [comment]
When writing a wiki, reference is always made to homeserver.yaml. 

So is there it not possibility to give finished configurations to the users, as copy, edit and paste for individual configuration of sections. 

I jump through the file with /search all the time and only hope to find what I'm looking for. 1827 lines is to long.

**Comment by richvdh** [comment]
> So there is no useful possibility to give finished configurations to the users. 

what is stopping you doing this? If you want to tell your users to use multiple files instead of a single homeserver.yaml, you are free to do so.

**Comment by BoarderEB** [comment]
Ok perfect, then I probably overlooked the function how to create a conf.d. Is there a reference? Then it shouldn't be a problem to split it up by standard.

**Comment by richvdh** [comment]
How much of a reference do you need? you can give multiple `-c` arguments, or point it to a directory containing multiple `*.yaml` files.

I'm closing this now as it sounds like it's been resolved.

**Comment by BoarderEB** [comment]
Solved really? You mean that a user should first learn system startup and how act with services? So instead of making it easier, it gets more difficult.

I suspect that the basic problem is not clear to you. If you want to configure a matrix for the first time, you have to get an overview of almost 2000 rows. No problem for a matrix programmer. You know the conf. 

But it is extremely difficult for someone to set up the Matrix for the first time. It is not for nothing that a conf.d is now created for almost every project.  

Hey, I can handle. It was well-intentioned advice on my part. However, I think this is not just a nice to have for the spread of the project.

Easy to configure = easy to use.

**Comment by richvdh** [comment]
> I suspect that the basic problem is not clear to you.

indeed it's not. I'm still unclear what you are actually asking us to do. Are you asking me to split the [sample config](https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml) into separate files? or something else?

**Comment by BoarderEB** [comment]
That's right, 

The best would be a conf.d directory with the different sections in individual files. Like:

/etc/matrix-synapse/conf.d/user.yaml
/etc/matrix-synapse/conf.d/mail.yaml
/etc/matrix-synapse/conf.d/ldap.yaml

1. If you are a new user and want to do the first configuration. You have to read almost 2000 lines to do this. This is very daunting  and leads to errors

2. Even someone who has made Linux server configurations several times first looks at a 2000 line file like a pig in the clockwork. At first glance you have no orientation. It starts with searching and hope that you can find the right one. Again, this oversized config leads to errors.

3. A division also forces programmers to think about the configuration. How it would be best.

Does **registrations_require_3pid: email** really belong to account_validity although there are dependencies on **e-mail: **? 

This is just an example, but it should show that also a programmer do it usually better with a conf.d directory.

**Comment by richvdh** [comment]
> That's right,

> The best would be a conf.d directory with the different sections in individual files. Like:
> 
> /etc/matrix-synapse/conf.d/05-user.yaml
> /etc/matrix-synapse/conf.d/05-mail.yaml
> /etc/matrix-synapse/conf.d/05-ldap.yaml

These two statements are in conflict. If you're talking about things in `/etc/`, then that's not the sample config, which is the documentation I linked to. I still think you're being unclear about what you actually want us to do. Of course, normal does not put anything in `/etc`. Perhaps you're talking about something specific to the debian packaging?

> If you are a new user and want to do the first configuration. You have to read almost 2000 lines to do this.

I don't really agree. Most of that file can be ignored, and the installation instructions tell you which bits you need to change to get started.

Perhaps there would be value in changing the behaviour of `--generate-config` so that it omitted sections you don't normally need.

> A division also forces programmers to think about the configuration. How it would be best.

The implementation of the sample configuration is already divided up into separate python modules. I agree that the file needs to be better organised, but I don't see why splitting it into separate files would force programmers to do any better at that organisation than they currently do.

**Comment by BoarderEB** [comment]
>These two statements are in conflict.

I talking about this packages: **https://matrix.org/**packages/debian Version 0.34.0.1
The config is in current in one file /etc/matrix-synapse/homeserver.yaml

> Perhaps there would be value in changing the behaviour of --generate-config so that it omitted sections you don't normally need.

https://github.com/matrix-org/synapse/blob/master/INSTALL.md#installing-from-source

If I follow this and your answer I can define the config file and which sections. It was not about where they are. In /etc/ or in a subfolder of Matrix. However, there is always one configuration file.

I find the detailed description and all configuration options as generated examples very good. That's how it should be!

> the sample configuration is already divided up into separate python modules

Perfect, then this is roughly done what I wanted to show with my general execution of a conf.d instead of a file not only to Matrix.

> I agree that the file needs to be better organiSed

**Then we are together.** My suggestion would be a conf.d. which would bring the better  organization. And additionally for example that a copy-edit-paste of a 04-XXX.yaml is possible.

If I see the right, there is "only" lack of a good selection process.

Thank again you for your attention and stay healthy.

**Comment by richvdh** [comment]
> I talking about this packages: https://matrix.org/packages/debian

for the love of god. Why didn't you say so in the first place? I asked you if you were talking about the sample config, and you said "yes", but apparently you were actually talking about the default configuration which is shipped with the debian package. 

>  Version 0.34.0.1

We're currently on 1.12.3.

> However, there is always one configuration file.

Again, there is nothing stopping you using more than one configuration file if you prefer to organise your configuration that way.

I feel like I've spent more than enough time on this conversation. You have consistently failed to make it clear what you are talking about, and I don't have the time to spend another three days discussing it with you.

**Comment by BoarderEB** [comment]
I think that is the newest Version that matrix ship. If different versions are displayed for different shipping. Then I'm sorry. If I hadn't used the latest I would have said it.

[code]
apt-cache policy matrix-synapse
matrix-synapse:
  Installiert:           0.34.0.1-0matrix2
  Installationskandidat: 0.34.0.1-0matrix2
  Versionstabelle:
 *** 0.34.0.1-0matrix2 500
        500 https://matrix.org/packages/debian bionic/main amd64 Packages
        500 https://matrix.org/packages/debian bionic/main i386 Packages
        100 /var/lib/dpkg/status
[/code]

> but apparently you were actually talking about the default configuration which is shipped with the debian package.

They are the same
https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml

> Again, there is nothing stopping you using more than one configuration file if you prefer to organise your configuration that way.
Yes, we are going in circles. Startup, etc. I've already replied to that. INo argument is (/wants) understood after my detailed explanation.

> I feel like I've spent more than enough time on this conversation.
Really friendly. Testing, writing reports and instructions is a waste of time for you. You are a very big one.
