### ISSUE TITLE
search users (to chat with) on owned matrix server

### ISSUE THREAD

**Issue by pantafanta** [matrix-org/synapse#7250]
Hi everybody, thanks in advance for the support!

I've up and running synapse matrix server. From Riot site (using recaptcha) my users are able to make a registration. They use Riot on android and IOS. 

Everything works properly, but we'rent able to search each other: when I'm looking for other user (in the search area, for example @paperino) I can't see anyone...

On the homeserver.yaml, I've tryed as below
user_directory:
  enabled: true
  search_all_users: true

My goal is to have the complete list of users on my server...

**Comment by dklimpel** [comment]
Do you have tried this?
https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md

**Comment by clokep** [comment]
> Everything works properly, but we'rent able to search each other: when I'm looking for other user (in the search area, for example @paperino) I can't see anyone...

Can you clarify wherein Riot you're searching for other users? I believe this setting is used in the modals to:
* Starting a direct message
* Inviting a user to a channel

**Comment by richvdh** [comment]
closing pending information as to what this means
