### ISSUE TITLE
Cross signing key updates fail on workerised synapse

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#7252]
When an EDU comes in with updated cross-signing keys for a user, it's handled by the federation_inbound worker which lacks the ability to write the keys to the db. Stack trace: https://gist.github.com/dbkr/d93c32abab600ff3c7a240c0de0f1d61

@erikjohnston sez:
 > ah, looks like we're incorrectly registering an edu handler on workers when it should only happen on master

This affects ability to cross-sign to/from matrix.org so is time-sensitive.

**Comment by jryans** [comment]
@dbkr Does this also mean affected users would need re-create their keys after a fix is found, or do the keys keep coming in over federation until you save them correctly...?

**Comment by dbkr** [comment]
I'm not 100% sure: I suspect there is more to this because the keys should also get written into the cache when the client does a `/keys/query`. Suggest we re-test once this if fixed.

**Comment by anoadragon453** [comment]
Unfortunately the above fix doesn't seem to be the silver bullet we thought it would be.

**Comment by richvdh** [comment]
so the `Failed to handle edu` error (with stack trace) is still happening?

**Comment by dbkr** [comment]
I believe this bug is now fixed (ie. the stack trace is no longer appearing and the EDU is getting through) but the riot-web bug https://github.com/vector-im/riot-web/issues/12973 is still a problem. Closing this and opening https://github.com/matrix-org/synapse/issues/7276 for the wider problem.
