### ISSUE TITLE
Add support for hCaptcha

### ISSUE THREAD

**Issue by xmstspider** [matrix-org/synapse#7258]
**Description:**
To remove dependency on one G* company, I would like to use [hCaptcha](https://www.hcaptcha.com/) instead of reCaptcha.

Would it be possible to add support for hCaptcha?

Thanks

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-doc/issues/1281,
https://github.com/vector-im/riot-web/issues/3606

**Comment by xmstspider** [comment]
Thanks, I did not see any match when I created the ticket
