### ISSUE TITLE
Calls failing from outside firewall

### ISSUE THREAD

**Issue by mowtheair** [matrix-org/synapse#7273]
I have a matrix/synapse setup running on debian 10 with Riot.im app on iOS.  When I try to initiate a phone call from outside of my firewall, it connects with no audio, then fails.  App simply says "error".  Internally on the LAN behind the firewall all is well - voice, video, etc.  Chat and general site access are fine from external clients, just the voice and video having an issue. The only thing I see that looks strange to me in the logs is the following:
2020-04-14 10:07:30,213 - synapse.http.site - 203 - WARNING - GET-2344 - Error processing request <XForwardedForRequest at 0x7f21... method='GET' uri='/_matrix/client/r0/sync?filter=0&since=s353_714_4_170_99_1_87_32_1&timeout=30000' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.

I think it might be firewall related, but am not sure.  Any help would be greatly appreciated!  Thanks in advance.

this is the installation procedure I followed:
https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi

**Comment by clokep** [comment]
I'd suggest checking with the #synapse:matrix.org channel for server operators. This doesn't seem to be an issue with Synapse itself.

**Comment by mowtheair** [comment]
Thanks.  I'll do that now.
