### ISSUE TITLE
matrix-synapse fails to start on ubuntu 20.04

### ISSUE THREAD

**Issue by weebl2000** [matrix-org/synapse#7288]
Upgraded to Ubuntu 20.04 and matrix-synapse-py3 package does not want to start.

matrix-synapse[41198]: ModuleNotFoundError: No module named 'distutils.util'.

Tried installing it in the venv, but same error occurs.

**Comment by clokep** [comment]
@weebl2000 I'd suggest trying to ask in the #synapse:matrix.org.

Is there a larger stack trace you can show? It also be interesting to include the version of the package and python.

**Comment by anoadragon453** [comment]
Try recreating your virtual environment? If the system python updated you'll want to update your virtualenv to match.

**Comment by richvdh** [comment]
We don't build packages for ubuntu 20.04 yet; attempting to use packages from a different distribution will certainly cause errors like this.

Now that it's hit RC, I guess we should start building packages for it. It probably makes sense to do so as part of the next release.

**Comment by richvdh** [comment]
#7293
