### ISSUE TITLE
Public room list not updated when disabling stats

### ISSUE THREAD

**Issue by amesser** [matrix-org/synapse#7294]
### Description
When setting "report_stats: false" in homeserver.yaml, newly created rooms which are set to public visible and with local alias do not show up in servers room list. Also existing rooms switched to "public" wont show up.

I think the problem is, that the room list depends on sql tables room_stats_*. But these tables are only updated when set "report_stats: true"

### Version information

- v1.12.3 
- running on private homeserver 
- installed via package manager (Ubuntu Bionic + Matrix deb repo)

**Comment by amesser** [comment]
Maybe same problem as of  #6529

**Comment by clokep** [comment]
> I think the problem is, that the room list depends on sql tables room_stats_*. But these tables are only updated when set "report_stats: true"

I'm assuming you found this by poking at the code? Can you point out the dependency?

Is the public room just not showing up in federation or even for other local users?

I'm unable to reproduce this in my local demo setup.

**Comment by amesser** [comment]
I was pointed by a user of our (private) matrix server onto this. As far as I understand the code, the public room list returned by REST api is generated in https://github.com/matrix-org/synapse/blob/0d775fcc2d0c7b6a07dad5430256d4d6c75a9f0d/synapse/handlers/room_list.py#L145 which by itself calls https://github.com/matrix-org/synapse/blob/0d775fcc2d0c7b6a07dad5430256d4d6c75a9f0d/synapse/storage/data_stores/main/room.py#L146 where the SQL query contains two inner joins:
```
            INNER JOIN room_stats_state USING (room_id)
            INNER JOIN room_stats_current USING (room_id)
```
I have tried that query manually on our server (using psql command)  and found that the returned list did not contain the entries for the newly created rooms. Digging further I discovered that neither room_stats_state nor room_stats_current contained an entry for the rooms. Having removed the inner join parts the query returned also the new rooms (of course without the information contained in these tables)

**Comment by clokep** [comment]
@amesser It looks to me like whether those tables are filled in or not depends on the `stats_enabled` flag, not the `report_stats` flag. Do you by any chance have `stats_enabled` disabled?

See https://github.com/matrix-org/synapse/blob/f5ea8b48bd57c19dae126a5cc631dc79cf5ce332/synapse/handlers/stats.py#L56-L61

**Comment by amesser** [comment]
Ah I'm sorry. You're right it happens when setting `stats.enabled: false`. It is not related to the `report_stats` flag. Still, not sure if it is expected, that the room list isn't updated at all in this case. Does it make sense to add at least a hint in documentation that this behavior will occur?

**Comment by clokep** [comment]
This is expected. I think it is already documented, the comment above it says: "Used in populating the room directory."

https://github.com/matrix-org/synapse/blob/v1.12.0/docs/sample_config.yaml#L1683-L1695
