### ISSUE TITLE
If your server is unreachable, attempts to join rooms over federation fail with an obscure error

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7298]
If your server is unreachable (so that the resident server cannot contact yours to retrieve your signing key), then attempts to join rooms over federation fail with

> No key for <server> with ids in [<key_id>]

I mean, wtf does that even mean?

**Comment by richvdh** [comment]
This is closely related to #4858

**Comment by Aang23** [comment]
Also a problem on my just-installed homeserver. It did join after a few hours, but never loads properly.

**Comment by mat-l** [comment]
@richvdh  I have updated https://github.com/matrix-org/synapse/issues/4858 with my additional error message that lead to the error message `No key for with ids in [<key_id>]`
do you already know, how to fix this error or what does it mean?

**Comment by richvdh** [comment]
removed reports from unrelated problems. If you need support please take it to #synapse:matrix.org rather than posting on issues which appear superficially related.

**Comment by reivilibre** [comment]
I don't see this string mentioned in the source anymore, suspect it may be stale.

**Comment by richvdh** [comment]
The error message went away in #8398
