### ISSUE TITLE
Device updates for own user when not in a room seems to have regressed

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#7301]
Both Nad and Dave were able to repro this case, see https://matrix.to/#/!HhZHxURiCDviGNNPnc:matrix.org/$KbLO8GeJFjO4kT8JEp--nrYF8GWOiEVstYHDRmVE9mQ?via=matrix.org&via=vector.modular.im&via=uhoreg.ca

Regression of https://github.com/matrix-org/synapse/pull/7160

**Comment by richvdh** [comment]
not so much regressed as not-yet-fixed on master

**Comment by richvdh** [comment]
now back-ported to the release-v1.12.4 branch.
