### ISSUE TITLE
Docker image permissions wrong when conf_dir is configured

### ISSUE THREAD

**Issue by awesome-michael** [matrix-org/synapse#7304]
The docker start script sets the permissions for the data_dir folder (https://github.com/matrix-org/synapse/blob/0d775fcc2d0c7b6a07dad5430256d4d6c75a9f0d/docker/start.py#L173)
but it does not set permissions for the config_dir. Most of the time these two are the same but when config_dir is configured to another directory the permissions are wrong.

Please add another line that sets permissions for the config_dir as well.

**Comment by clokep** [comment]
@awesome-manuel Thanks for filing this issue, any chance you could put up a PR with the fix?

**Comment by maquis196** [comment]
So PR added above which fixes this edge case.

**Comment by richvdh** [comment]
it's not obvious to me that the synapse process should have permission to write to the config dir? they are supposed to be static files.

**Comment by maquis196** [comment]
Could the edge case only be when we run the generate docker command?

**Comment by richvdh** [comment]
as above: I don't think it's correct to give synapse write access to the config dir.
