### ISSUE TITLE
Multiple different "duplicate key value violates unique constraint" errors

### ISSUE THREAD

**Issue by rihardsk** [matrix-org/synapse#7305]
### Description
I've got multiple `psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint` errors of different kinds in my logs.
```
journalctl -u matrix-synapse.service --since="today" | grep "psycopg2.errors.UniqueViolation: duplicate key" | sort | uniq
          psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "event_reference_hashes_event_id_algorithm_key"
          psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "event_search_event_id_idx"
          psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "event_to_state_groups_event_id_key"
          psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "redactions_event_id_key"
          psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "remote_media_cache_media_origin_media_id_key"
```

Here are the full logs [duplicate-key-errors.redacted.log.gz](https://github.com/matrix-org/synapse/files/4499922/duplicate-key-errors.redacted.log.gz).

I think some of the errors might be due to an unresolved corruption in my database due to `LC_COLLATE` being set to `'UTF-8'` previously, which resulted in duplicate entries as described in 
https://github.com/matrix-org/synapse/issues/6696#issuecomment-575280941. I attempted to fix the corruption by:

0. leaving all of the rooms that my single user on the homeserver had joined and running the [`synapse_janitor.sql`](https://github.com/xwiki-labs/synapse_scripts/blob/a9188ff175ae581610f92d58ea6eac9a114d854b/synapse_janitor.sql) script,
1. backing up the synapse db,
2. dropping it,
3. recreating it with `LC_CTYPE` and `LC_COLLATE` settings changed from `'UTF-8'` to `'C'`,
4. importing the backup,
5. deleting duplicate rows in tables that were being complained about in the indexing step
6. and then exporting and importing the database again,
7. re-creating the missing indexes (added this step as a resolution to an earlier issue i had - #7282).

I noticed that some of the errors appeared upon joining the Matrix HQ room and trying to load history. The history wouldn't load past some recent point (there's a `Failed to backfill from matrix.org` error which seems to be related). I had joined the room previously and had left it before attempting the database cleanup procedure listed above.

### Version information

- **Homeserver**: my private homeserver

- **Version**: 1.12.1, but the original errors (before running the sql script) were also present on 1.9.1

- **Install method**: NixOS

- **Platform**: latest NixOS master branch (commit 01c8795673ecff6272895a085e9fe1ffa3b33620) running on a rockpro64 sbc (with a custom patched kernel).

**Comment by richvdh** [comment]
> leaving all of the rooms that my single user on the homeserver had joined and running the synapse_janitor.sql script,

If you're going to paste random scrips you find on the internet into your database... well, good luck with that.

In this case the *specific* problem is that you have removed rows from `events` without removing the corresponding rows from those other tables, but honestly I'd have zero confidence in any of the rest of your database being valid. Have you got a backup from before you deleted half of the database?

This isn't a bug in synapse, so I'm going to close this.

**Comment by rihardsk** [comment]
I was under the impression that the [xwiki-labs/synapse-scripts](https://github.com/xwiki-labs/synapse_scripts ) project, which `synapse_janitor.sql` is part of, was at least semi-officially endorsed by `synapse` developers. `synapse-scripts` are mentioned in the [synapse wiki](https://github.com/matrix-org/synapse/wiki/Synapse-database-maintenance-tools#synapse_janitorsql), in the [matrix.org faq](https://matrix.org/faq/#where-can-i-find-tools-to-get-starting-maintaining-a-synapse-installation%3F) and are linked to in the [matrix.org projects section](https://matrix.org/docs/projects/other/synapse-scripts). Plus somebody at the `#synapse:matrix.org` room suggested i'd try using it as an attempt to combat general synapse slowness and database bloat (i had made a comment on it on a separate issue https://github.com/matrix-org/synapse/issues/7156#issuecomment-609087775; leaving all rooms and running `synapse_janitor.sql` and `vacuum full` on the db did help returning the db to a manageable size).

I don't have a backup of the db right before i ran the `synapse_janitor.sql` script because the size of the `state_groups_state` (28 GB) table at that time made it hard to do. I do have an earlier backup which i used to migrate away from AWS to my own hardware some 5 months ago. Is it generally safe to restore to a backup that far back?

Is there an alternative to restoring to a backup? Would deleting the rows, containing the keys that are being complained about in the error logs, from the respective tables help or would it just lead to different problems?

**Comment by richvdh** [comment]
I'm sorry that the matrix.org faq linked to it; I've asked that it be removed. Everything else you list is community maintained rather than endorsements by the synapse developers.

If you restore an old backup... well, you may lose some data, and you'll have to recreate any user sessions, but it's probably better than trying to patch up a broken database.

**Comment by rihardsk** [comment]
Restoring to the 5 month old backup worked nicely. Thank you and sorry for the trouble :)
