### ISSUE TITLE
Password provider requires more API

### ISSUE THREAD

**Issue by integrics** [matrix-org/synapse#7307]
I'm configuring Synapse to authenticate from an external web service using this guide:

https://github.com/kamax-matrix/matrix-synapse-rest-password-provider

I've set the following in homeserver.yaml:

password_providers:
   - module: "rest_auth_provider.RestAuthProvider"
     config:
     endpoint: "http://127.0.0.1"

This is failing because Synapse is making other requests to the web service. From the web server's logs:

GET /_matrix/client/versions HTTP/1.1" 404

Is it really necessary to implement more of the API? If so, which functions need to be provided, and what are they expected to return?

Synapse is version 1.11.0-1. The client is the riot.im web app. The web server is Apache 2.4.41-4ubuntu3. Everything is running on the same machine, my laptop, running Ubuntu 20.04 beta.

**Comment by richvdh** [comment]
synapse does not make requests to `/_matrix/client/versions`, and although `matrix-synapse-rest-password-provider` is written by a third-party, I'd be surprised if it made those requests either.  I suspect you are misunderstanding where those requests are coming from: it is typically called by matrix clients, implying that you have pointed a matrix client at your web service.
