### ISSUE TITLE
Metrics (esp. synapse_notifier_users) and workers

### ISSUE THREAD

**Issue by eMPee584** [matrix-org/synapse#7312]
### Description
Is the assumption correct that `synapse_notifier_users` should reflect the number of active user devices at a given time?
Since activating workers, `synapse_notifier_users` has turned to 0.0, leaving us without this vital measure of server activity.. With 7k+ users atm... :sweat_smile: :sweat_drops: 
Here's a dump of our [metrics.gz](https://github.com/matrix-org/synapse/files/4506690/metrics.gz)..

### Steps to reproduce

- enable workers
- check http://localhost:9100/_synapse/metrics
- see `synapse_notifier_users 0.0`
- wonder

### Version information
- **Homeserver**: https://matrix.tu-dresden.de
- **Version**: python_version: 3.7.7, server_version: 1.12.3
- **Install method**: https://github.com/spantaleev/matrix-docker-ansible-deploy
- **Platform**: debian buster VM

**Comment by babolivier** [comment]
Hey there, from which worker are you trying to retrieve this metric? From what I can see, only the synchrotron seems to be updating it, so any other worker (or the master process) will be returning 0.0.

To retrieve metrics from a worker, just add the following to its configuration file, under the `worker_listeners` section:

```yaml
 - type: metrics
   bind_address: ''
   port: 9101
```

(feel free to edit the `bind_address` and `port` parameters however you want as long as the resulting listener is accessible from prometheus/beamium/etc.)

**Comment by eMPee584** [comment]
Ok thanks for the pointer.. we were receiving the URL from the main homeserver process..
so different workers provide different metrics fragment? :thinking: 
And what about multiple synchrotrons, will they each have their own stats?

**Comment by babolivier** [comment]
Gah, sorry, I missed your reply.

> so different workers provide different metrics fragment?

Yes, different workers will handle different data and thus they'll all expose different timeseries.

>  And what about multiple synchrotrons, will they each have their own stats?

Yup.

The general rule here is that if you want to monitor a cluster of workers you should monitor every worker, not only the master. This isn't clear in the documentation so I've opened https://github.com/matrix-org/synapse/pull/7357 to address that.

I'm going to close this issue now. If you have further comments or questions, feel free to join #synapse:matrix.org and share them there, as it is our main support channel :)
