### ISSUE TITLE
frontend_proxy worker should be able to handle OPTIONS for /_matrix/media requests

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#7313]
**Description:**

The frontend proxy worker is able to handle HTTP OPTIONS requests for everything except the media repo. If it could also handle these requests (and any future api endpoints), we would be able to route all http options requests to the worker in config, without having to keep a seperate map for OPTIONS requests, compared to GET or PUT.

Currently requests return a 404.

**Comment by anoadragon453** [comment]
Hm, I see the frontend_proxy proxies all CS API endpoints and does some special handling of key upload and presence endpoints, but nowhere do I see it specifically handle OPTIONS requests.

**Comment by michaelkaye** [comment]
I don't believe it specifically has code to handle OPTIONS; but it does handle everything except media_repo, and there must be something causing it to 404 those media_repo requests - though this might be configuration or something rather than explicit code changes in that worker.

**Comment by richvdh** [comment]
@anoadragon453: OPTIONS is handled at https://github.com/matrix-org/synapse/blob/release-v1.12.4/synapse/http/server.py#L353. Note that it will only apply to paths where a `JsonResource` has been configured.

`JsonResource`s for the worker apps are registered at https://github.com/matrix-org/synapse/blob/032e5a2acaa26511a00801eedd71e35d21c791fa/synapse/app/generic_worker.py#L484. Note that it will not register a JsonResource for `/media` unless the `media` listener is configured. 

ISTR there is a problem with configuring two workers to both have a media listener (like they both end up trying to do background jobs) so I don't think we can just add `media` to the list of enabled listeners.

**Comment by anoadragon453** [comment]
So, is the fix to tell people to only run one media worker? Or can something be done to eliminate the bg job conflict?

Could this the background job you're referring to?

https://github.com/matrix-org/synapse/blob/caec7d4fa0041697b7714e638477772f0a827ff6/synapse/rest/media/v1/media_repository.py#L107-L109

**Comment by richvdh** [comment]
> So, is the fix to tell people to only run one media worker? 

we do already do that, I think. The fix to this issue is, well, to make frontend_proxy workers accept OPTIONS requests for media repo endpoints.

> Could this the background job you're referring to?

Possibly. I think it might have been a cleanup job. I wouldn't propose trying to change it now.
