### ISSUE TITLE
Make links to external instance versions of images accessible

### ISSUE THREAD

**Issue by Soundtoxin** [matrix-org/synapse#7329]
**Description:**
I am primarily using chat.weho.st is my matrix instance. The file size limit is 10MB. I work with it, I'm used to it. Many of my friends are on matrix.org which has either no limit or just a really big one. Sometimes they post a picture (often from a high quality camera) that is over 10MB. On my end the image never shows up, I can't access it, if I click the download link it shows me a file-size error in another tab. However, the link to the matrix.org version of the image is public. I just can't see it myself. I have another account on matrix.org. If I log in there and see the image, I can copy/paste the link and then open it from the other side. I also confirmed it doesn't just work because I'm signed into matrix.org as well by opening it with mpv+youtube-dl, demonstrating authentication is not needed. Basically, why can't I just access that link from my weho.st account? Why do I get a different link if it's just not going to work anyway? 
FYI I am using Riot in a web browser for both instances.

Apologies in advance if this isn't the place / category to file this under. Feel free to move/remake anything.
A good example of this sort of thing being implemented is on the activitypub-based fediverse. I see local versions of posts and images, but I can also hit a button to view the version from the source instance, so there is a precedent for something like this.

https://chat.weho.st/_matrix/media/r0/download/matrix.org/gbVznlYjOOfEupMmKduusCYX
![2020-04-22-232719_grim](https://user-images.githubusercontent.com/3146494/80059192-f1aebe80-84f0-11ea-9084-7c8d203d6746.png)
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/gbVznlYjOOfEupMmKduusCYX
![2020-04-22-232747_grim](https://user-images.githubusercontent.com/3146494/80059195-f5424580-84f0-11ea-918e-9fec1e08ec91.png)

**Comment by babolivier** [comment]
The server seems to be doing the right thing here by refusing to download media that would be too large and take up too much disk space on the machine.

It seems to me like this should be a client issue, by processing correctly `M_TOO_LARGE` errors (and e.g. show a link to the media on the homeserver, or an error message) instead of trying to act as if it actually downloaded the media. Since you seem to be using Riot Web/Desktop, I'd suggest opening an issue on https://github.com/vector-im/riot-web.
