### ISSUE TITLE
logout/delete specific devices/session

### ISSUE THREAD

**Issue by rozahp** [matrix-org/synapse#7330]
**Description:**

I administer a matrix homeserver and sometimes login myself and others from different clients and types to test users and rooms. As some rooms are encrypted, this tends to be cumbersome when there are alot of devices to verify. How can one delete some of this devices/sessions?

I would like an API that can deactivate/logout/delete certain/specific session/devices per user. That would be very helpfull for a serveradmin. 

Regards.

**Comment by babolivier** [comment]
In terms of verification, we're very very very close now to shipping cross-signing, which is a feature that means you'll only need to verify users now, not devices, which means you'll only verify a user once, regardless of whether they have only 1 device or 10 of them. On top of that, Riot won't prompt you by default about unverified devices in a room, but will show a warning icon if someone you have verified has a device they haven't verified. See a tour of that feature in a talk we gave at last FOSDEM: https://fosdem.org/2020/schedule/event/matrix/

Would that remove your need for such an API?

**Comment by rozahp** [comment]
Well, I have been running weechat and there you have /olm verify username * to verify all the devices. This API you mentioned would of course make life better for us all. But, hence synapse is keeping track of logins/devices/ip-adresses per user. To keep it simple: i would like as an administrator be able to not just "verify" or "blacklist" but also "delete" and/or "view" more info about the device such as associated information from the database. Even as a user I want to know: has someone stolen my identity and verify that is not the case. 

Thanks for reading/listening to my issue and query!

**Comment by babolivier** [comment]
> i would like as an administrator be able to not just "verify" or "blacklist" but also "delete" and/or "view" more info about the device such as associated information from the database

Right, I understand better what you mean here, thanks for the details :)

> Even as a user I want to know: has someone stolen my identity and verify that is not the case.

With the new cross-signing feature you'd need to verify by yourself every new device that connects to your account, and if you don't then people who have verified you in the past will be warned about it (in the form of your green shield turning red with an exclamation mark - see the talk I've linked in my previous comment which outlines all of this). This will be the case for Riot as soon as cross-signing is released (so probably next week or the week after that), and I wouldn't be surprised to see the weechat plugin following closely after that.

**Comment by rozahp** [comment]
I just want to add to this discussion.

Today I looked at the request/response for this uri: 
https://matrix.example.com/_matrix/client/unstable/keys/query

Request:
```
{
    "device_keys": {
        "@myuser:matrix.example.com": {}
    },
    "token": "SOME_TOKEN_STRING"
}
```
The response was a list of several devices+keys and other stuff that I have used previously and maybe will never use again.

As good administrator that want to keep things neet and tidy and reduce server load, listing and deleting old/unused/obsolete devices and sessions, would be of a great help.

Thanks for a good discussion on this topic. And also thanks for a awesome program. I hope more countries like France will take matrix at heart! :-)

**Comment by dklimpel** [comment]
Do you looking for:
* https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-devices
`GET /_matrix/client/r0/devices`
* https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-delete-devices
`POST /_matrix/client/r0/delete_devices`

?
Used by an admin for every local user?

When a devices will be deleted, the keys will be deleted automatically.
https://github.com/matrix-org/synapse/blob/cb6fd280af4858e2ad5ff2d68b56a5e0021395ea/synapse/handlers/device.py#L317-L347

**Comment by rozahp** [comment]
Thanks for the hint. To list all devices and users and get information is not any problem, just extract them from the API or the DB. But testing the API with curl in the terminal I have not been able to delete devices. The answer I always get is:

```
curl -X DELETE 'http://127.0.0.1:8008/_matrix/client/r0/devices/'$DEVICE'?access_token='$TOKEN$'

HTTP/1.1 401 Unauthorized
Server: Synapse/1.12.3
....

{
    "flows": [
        {
            "stages": [
                "m.login.password"
            ]
        }
    ],
    "params": {},
    "session": "xxxxxx"
}]
```

**Comment by dklimpel** [comment]
There is no admin API for this use case at the moment.

**Comment by rozahp** [comment]
> There is no admin API for this use case at the moment.

Thanks for clearing that up!! I don't have to bang my head to the wall ... :exploding_head:
