### ISSUE TITLE
Unable to restrict room creation to admin only

### ISSUE THREAD

**Issue by DarkRider1768** [matrix-org/synapse#7331]
Hey all!

Went through and configured a homeserver for testing before I roll it out at work. I'm mirroring the work environment for the test as close as possible to make sure I catch as many gotchas as possible. Well, I hit a big one and I'm glad I found it now rather than later.

We are doing auth via LDAP. As we are an enterprise environment, the upper levels of management are going to want room creation limited to just us admins. Unfortunately, I haven't been able to find a combination of settings that prevent nonadmin users from creating rooms. There is an option to restrict Group creation to admin accounts but that does not seem to impact the creation of rooms.

Any advice on how we can lock this down for management?

**Comment by Half-Shot** [comment]
There isn't currently a config option to enable/disable room creation to only admins. You could use a SpamChecker plugin (documented at https://github.com/matrix-org/synapse/blob/master/docs/spam_checker.md) if you wanted to write a script to do it (and possibly make it dynamic though LDAP).

Be warned that disabling the ability to create rooms will mean users won't be able to create DM rooms either, so only admins can DM users, users won't be able to start chats with other users or admins.

**Comment by babolivier** [comment]
> You could use a SpamChecker plugin (documented at https://github.com/matrix-org/synapse/blob/master/docs/spam_checker.md) if you wanted to write a script to do it (and possibly make it dynamic though LDAP).

The SpamChecker isn't async, so it wouldn't be possible to check whether the user is admin, or even to check against the LDAP backend.

I'd suggest instead looking around a `ThirdPartyEventRules` module, which is async and even has a `on_create_room` method called on every room creation request, which arguments include both a `config` dict of the room's parameter (including e.g. whether the room is a direct chat) and a `is_requester_admin` boolean that's true if he user is a server admin.

Unfortunately, this feature is a bit under-documented, so the only doc would be the docstring of the `ThirdPartyEventRules` docstring: https://github.com/matrix-org/synapse/blob/99fcc96289f673f96f2d180a84df84f6b8a85521/synapse/events/third_party_rules.py

The documentation of what the `on_create_room` method should look like in the plugin can be found here: https://github.com/matrix-org/synapse/blob/99fcc96289f673f96f2d180a84df84f6b8a85521/synapse/events/third_party_rules.py#L68-L78

And an example of such a plugin (albeit maybe a bit complex) can be found here: https://github.com/matrix-org/synapse-dinsic/blob/dinsic/synapse/third_party_rules/access_rules.py

**Comment by babolivier** [comment]
I'm going to consider this issue fixed given a clear and doable solution has been proposed. If you have more questions, feel free to join #synapse:matrix.org (which is the main support channel for Synapse) and ask them there :)
