### ISSUE TITLE
Running redis mode (on develop) causes high CPU usage

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#7334]
The CPU graph for my set of workers:
![image](https://user-images.githubusercontent.com/2072976/80088648-b5ad4500-8554-11ea-856a-598be8418a02.png)

The GC graph:
![image](https://user-images.githubusercontent.com/2072976/80088694-c493f780-8554-11ea-8941-d0ed26e2afb1.png)

Something has changed between 1.12.3 and 2e3b9a0fcb81b539e155004ded8017ee9923eecc that has caused this to skyrocket.

Otherwise, the homeserver seems to *work* in terms of federating and sending messages. It's just obsessed with GCing right now.

Memory usage has remained a bit low:

![image](https://user-images.githubusercontent.com/2072976/80088879-04f37580-8555-11ea-8e19-ede4f8d4a002.png)

**Comment by Half-Shot** [comment]
CPU usage by requests:

![image](https://user-images.githubusercontent.com/2072976/80089143-661b4900-8555-11ea-831d-372ad87a2c42.png)

**Comment by erikjohnston** [comment]
I suspect its due to the fact that it seems to be sending out about 1kHz of `REMOTE_SERVER_UP` commands from each process. Possibly there is a loop going on?

**Comment by Half-Shot** [comment]
Switching off Redis (but running the same commit) seemed to reduce CPU, and stop spamming `REMOTE_SERVER_UP`.

**Comment by erikjohnston** [comment]
I believe the cause of this is if the fact in current TCP mode if a worker detects a remote server has come back online it sends a `REMOTE_SERVER_UP` to master, which then proxies to other workers. When running with redis the master process still echoes the command back, which leads to an infinite loop as redis will echo it back to master again.

**Comment by Half-Shot** [comment]
I can confirm #7352 fixes the issue for me.
