### ISSUE TITLE
More AssertionErrors from replication_notifier

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7340]
we have a function `db_query_to_update_function` which wraps a database query function so that it can be used as an update_function for replication streams. It relies on the wrapped function returning no more than the number of rows asked for. #7337 found and fixed one instance where this was not the case, but we should check if there are any more.

**Comment by richvdh** [comment]
as per https://github.com/matrix-org/synapse/issues/7351#issuecomment-621435281, at least the `federation` and `account_data` streams are broken. I think we should just go through each of the streams and check their behaviour, before this stuff bites us again.

**Comment by babolivier** [comment]
Removing the release blocker label as https://github.com/matrix-org/synapse/pull/7378 mitigates it, leaving this issue open as it looks like this issue needs more investigation.

**Comment by erikjohnston** [comment]
#7740 has cleaned this up a lot
