### ISSUE TITLE
SSO CAS login issue

### ISSUE THREAD

**Issue by ravindrsharma99** [matrix-org/synapse#7342]
SSO login: CAS based
http://127.0.0.1:8008/_matrix/client/r0/login/cas/ticket?redirectUrl=http:localhost:8080&ticket=ST-EjKJv6WmUZPVoCoHTG8jFugJ38g0u

Response:
{
"errcode": "M_UNAUTHORIZED",
"error": "Invalid CAS response"
}
Please help .

Homeserver.yaml:

cas_config:
enabled: true
server_url: "http://localhost:8000/cas"
service_url: "CAS"
displayname_attribute: name
#required_attributes:

**Comment by turt2live** [comment]
Please wait patiently in #synapse:matrix.org for help, or provide more information.

**Comment by ravindrsharma99** [comment]
@turt2live  what other information do you need?
