### ISSUE TITLE
synapse doesn't start with openssl-1.1.1

### ISSUE THREAD

**Issue by ctsde-markus** [matrix-org/synapse#7353]
### Description

synapse doesn't start with openssl-1.1.1 library (Undefined symbol "OPENSSL_no_config")

### Steps to reproduce

- Install FreeBSD 11.3
- set ```DEFAULT_VERSIONS+= ssl=openssl``` in ```/etc/make.conf```
- install packages 
  - bash
  - bash-completion
  - vim-console (optional)
  - screen (optional)
  - openssl
  - ca_root_nss
  - freetype2
  - giflib
  - jbigkit
  - jpeg-turbo
  - libltdl
  - libsodium
  - nginx
  - nspr
  - nss
  - png
  - postgresql96-server
  - postgresql96-contrib
  - python36
  - py36-virtualenv
  - py36-psycopg2
  - tiff
  - turnserver
  - webp
  - xmlsec1

run the following commands as root to install synapse:

```
pw groupadd synapse
pw useradd synapse -m -g synapse
sh
virtualenv-36 -p python3.6 /home/synapse/env
. /home/synapse/env/bin/activate
# prompt shows (env)
pip install --upgrade pip
pip install --upgrade setuptools
pip install matrix-synapse[all]
exit
```

Setup the installation by creating a reasonable homeserver.yaml and try to start synapse with:

```
/usr/home/synapse/env/bin/python3.6 -m synapse.app.homeserver --daemonize -c /path/to/homeserver.yaml
```

I then get:

```
Starting synapse.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 39, in <module>
    import synapse.config.logger
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/config/logger.py", line 32, in <module>
    from synapse.app import _base as appbase
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 27, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory
  File "/usr/home/synapse/env/lib/python3.6/site-packages/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/home/synapse/env/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/home/synapse/env/lib/python3.6/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/usr/home/synapse/env/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/home/synapse/env/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/home/synapse/env/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "OPENSSL_no_config"
```

### Version information

- **Homeserver**: my own homeserver

If not matrix.org: 1.12.4 (but also happend in 1.11.x) crucial for my problem was the upgrade of openssl library to 1.1.1 where "OPENSSL_no_config" was removed but synapse still tries to use it(?)

- **Version**: 1.12.4 (but also in 1.11.x)

- **Install method**: pip

- **Platform**: FreeBSD 11.3

**Comment by ctsde-markus** [comment]
I'm now switching back to my last working snapshot before the upgrade to at least have a running synapse server.

**Comment by babolivier** [comment]
That's very weird - my own homeserver is currently running 1.12.4 and the installed version of OpenSSL is 1.1.1:

```
brendan@errol:~$ dpkg -l openssl
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  openssl                 1.1.1-1ubuntu2.1 amd64            Secure Sockets Layer toolkit - cryptographic utility
brendan@errol:~$ 
```

Maybe it's the `cryptography` module that's out of date.

Could you fish out the version of that module with:

```
cat /usr/home/synapse/env/lib/python3.8/site-packages/cryptography/__about__.py | grep __version__
```

so we can check if that version supports OpenSSL 1.1.1?

**Comment by ctsde-markus** [comment]
Thx! It has to be FreeBSD 11.3 specific. A friend runs synapse on a FreeBSD 12.1 without any issues. He uses the openssl-1.1.1d from base.

On FreeBSD 11.3 on the other hand base has openssl-1.0.2s but i use openssl-1.1.1h from ports in /usr/local/lib. cryptography is correctly linked but i guess it somehow stumbles over openssl from base to determine how to initialize or so.

So, i guess it's not a synapse issue and i close this for now as i have to upgrade to FreeBSD 12.1 anyways soon.

**Comment by ctsde-markus** [comment]
Just to let you know: i compiled all ports with openssl from FreeBSD base (with 11.3 currently openssl-1.0.2s) and it works like a charm. Seems on FreeBSD there is some glitch when base and ports openssl differ too much. Never had such an issue with anything else so far.

But it's for sure NOT a synapse issue.

**Comment by babolivier** [comment]
Good to know, thanks for reporting!
