### ISSUE TITLE
Can't configure 3pid requirement for registration.

### ISSUE THREAD

**Issue by ivoryblade** [matrix-org/synapse#7354]
Hello! I'm deploying my first synapse homeserver and I'm stuck with email configuration. I've configured smtp settings and template dir (I've downloaded res/templates directory and placed in /var/lib/matrix-synapse). But when I activate 
`registrations_require_3pid: 
      - email`
I got error in logs
`synapse.config._base.ConfigError: Configuration requires email address at registration, but email validation is not configured`
What am I missing in my config? I've tried to enable account validation but got same error....
Synapse version is 1.12.3+bionic1.
My config in attachment.
[homeserver-2.txt](https://github.com/matrix-org/synapse/files/4539423/homeserver-2.txt)

**Comment by babolivier** [comment]
Hey, it looks like the indentation is wrong on the email settings in your config file. For example, the `smtp_[...]` settings are at the same indentation level as `email` (which is the top level), whereas they should be one level deeper. See https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml#L1611-L1715 for docs about the `email` section.

If you have more questions, or it still doesn't work, please head over to #synapse:matrix.org, which is our main support channel.

**Comment by ivoryblade** [comment]
> Hey, it looks like the indentation is wrong on the email settings in your config file. For example, the `smtp_[...]` settings are at the same indentation level as `email` (which is the top level), whereas they should be one level deeper. See https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml#L1611-L1715 for docs about the `email` section.
> 
> If you have more questions, or it still doesn't work, please head over to #synapse:matrix.org, which is our main support channel.

Thank you!!!! When I uncommented those lines the synapse didn't start at all telling me there errors in config so I removed indentation... I've copied indent from working lines and email config is working fine now! I've tried to ask at #synapse:matrix.org but nobody noted indent...
