### ISSUE TITLE
Expose Power Level Defaults

### ISSUE THREAD

**Issue by TheDiscordian** [matrix-org/synapse#7362]
As described in #5131 (tbh not really sure why that issue can't be used, the history for that issue will be relevant here...) it's very easy for a new user or an experienced user to make a mistake an promote someone else to admin along-side them. If this was done in error, it cannot be corrected without the new admin's cooperation.

There seems to be some debate over the usefulness of having owners default to a higher power level than admins (100 for owners, 90 for admins), which quite frankly I find silly/absurd. Just about every other service offers this distinction, and it's quite jarring and very easy to make a mistake on Matrix with the current defaults, but I digress.

The compromise to solve the problems highlighted above is to expose the default power levels for the roles Moderator, Administrator, and Room Creator inside of `homeserver.yaml`. A server owner could then change the default admin power level to 90. This would allow someone to create a room at power level 100, and reasonably expect to not put themselves in the position highlighted above (can't remove admin) unless they specify "custom" and type in 100. This is because when they select the Administrator option while promoting, the user's new power level would be just 90, below the owner's, instead of 100.

I thought this would be mostly a UI thing, and less a Synapse thing, but I clearly don't understand everything that's happening here. I'd be happy to help though.

**Comment by babolivier** [comment]
Hey, and thanks for your suggestion. As you mentioned, it would probably be a UI feature, as it's the client that decides which power level to use for which role. The Matrix spec [mentions](https://matrix.org/docs/spec/client_server/latest#permissions) a mapping ("0 User - 50 Moderator - 100 Admin"), but only as a suggestion.

I'd suggest opening an issue on the repo of the Matrix client you're using to suggest this feature.

**Comment by TheDiscordian** [comment]
@babolivier thank you very much for pointing me in the right direction! I'm using Riot in general as in the Riot web client, the Linux desktop client, and the mobile Android client. Where would be best to place the issue, before investigating into potential solutions? Or should I be making several tickets targeted at the individual clients?

**Comment by babolivier** [comment]
There's https://github.com/vector-im/riot-meta that centralises the issues for all Riot clients.
