### ISSUE TITLE
per-block cpu and db usage metrics are no longer reported accurately

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7370]
this is a regression introduced by #7120.

**Comment by richvdh** [comment]
The symptoms of this bug are basically this:

![image](https://user-images.githubusercontent.com/1389908/81014436-c2834000-8e54-11ea-978e-1d62fe08d304.png)

(no, we didn't magically make those processes 3 times as efficient).

Those graphs chart the CPU usage used by `with Measure()` blocks, which are implemented via LoggingContexts. I think the basic problem is that, as of [this change](https://github.com/matrix-org/synapse/pull/7120/files#diff-984b645db421f3b1c753de557bed4ea5R380-R381), the CPU usage stats are moved to the parent LoggingContext each time we switch away from the LoggingContext for the Measure block (ie, when it starts a blocking operation such as a database transaction); previously this happened only when the Measure block was all done and dusted [here](https://github.com/matrix-org/synapse/pull/7120/files#diff-984b645db421f3b1c753de557bed4ea5L349) - ie, after Measure had added the CPU usage to its prometheus stats.

The problem is that I made that change for quite a good reason - which was that I was annoyed that LoggingContexts which did most of their work inside a child LoggingContext didn't report any CPU usage until the child finished (when it would suddenly report 5000% CPU usage).

**Comment by richvdh** [comment]
Basically, I think we need to get rid of that `self._resource_usage.reset()`, and instead just add the delta to the parent context. But if we do that, we need to make sure that `add_database_transaction` and co are propagated correctly.

**Comment by clokep** [comment]
I'm going to see if I can figure this out.

**Comment by clokep** [comment]
Done in #7426
