### ISSUE TITLE
matrix-synapse cannot stop nor restart.

### ISSUE THREAD

**Issue by jumezurike** [matrix-org/synapse#7371]
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by jumezurike** [comment]
I am not able to start this server successfully on ubuntu 18.4. I am getting 
sudo systemctl restart matrix-synapse
Job for matrix-synapse.service failed because the control process exited with error code.
See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.

As I try to run it. I noticed that it doesn't stop once started. Take a look here. 

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      13391/nginx: master
tcp        0      0 127.0.0.1:8008          0.0.0.0:*               LISTEN      18154/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13391/nginx: master
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      604/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1089/sshd
tcp6       0      0 :::443                  :::*                    LISTEN      13391/nginx: master
tcp6       0      0 ::1:8008                :::*                    LISTEN      18154/python
tcp6       0      0 :::80                   :::*                    LISTEN      13391/nginx: master
tcp6       0      0 :::22                   :::*                    LISTEN      1089/sshd
udp        0      0 127.0.0.53:53           0.0.0.0:*                           604/systemd-resolve
udp        0      0 172.31.39.99:68         0.0.0.0:*                           581/systemd-network

This is very frustrating you know.

**Comment by babolivier** [comment]
Hi there, as the SystemD output tells you, you can see more info on what's happening by running `systemctl status matrix-synapse.service`. Note that there could be multiple reasons for Synapse not starting (as with any piece of software), so it's not possible to determine why it's wedged just with the info you provided here.

Also, as it is outlined in big bold capital letters in the template you've used to open this issue, we don't use GitHub issues for support. Please head over to `#synapse:matrix.org` (with a matrix.org account if necessary) and ask your question there, both core team members and community members should be around to assist you (though not immediately, if you don't get an answer there within the minute please be patient).

**Comment by jumezurike** [comment]
I am not sure where to ask this questions....Can you just help if you can this is not a difficult problem I am using this for a COVID SEMINAR.


Josiah J. UmezurikeIT Consultant | PC-Integral, Inc.
www.pc-integral.com
Cell:(763)568-4836
----------------------------------------------------------------------This email is privileged and confidential and is intended for the recipient. If you have received this email and are not the intended recipient please disregard it. If you have intercepted this communication without our authorization, consent or knowledge, you are in violation of both State and Federal Laws which govern private communication and will be prosecuted to the fullest extent of the law. 

    On Thursday, April 30, 2020, 4:12:02 AM EDT, Brendan Abolivier <notifications@github.com> wrote:  
 
 


Hi there, as the SystemD output tells you, you can see more info on what's happening by running systemctl status matrix-synapse.service. Note that there could be multiple reasons for Synapse not starting (as with any piece of software), so it's not possible to determine why it's wedged just with the info you provided here.

Also, as it is outlined in big bold capital letters in the template you've used to open this issue, we don't use GitHub issues for support. Please head over to #synapse:matrix.org (with a matrix.org account if necessary) and ask your question there, both core team members and community members should be around to help you (though not immediately, if you don't get an answer there within the minute please be patient).

**Comment by babolivier** [comment]
> I am not sure where to ask this questions

As I said, please ask these questions in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org), which is our main support channel.

**Comment by jumezurike** [comment]
I went there there is no provision for asking questions.Matrix.org

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Matrix.org

Matrix.org
 |

 |

 |




Josiah J. UmezurikeIT Consultant | PC-Integral, Inc.
www.pc-integral.com
Cell:(763)568-4836
----------------------------------------------------------------------This email is privileged and confidential and is intended for the recipient. If you have received this email and are not the intended recipient please disregard it. If you have intercepted this communication without our authorization, consent or knowledge, you are in violation of both State and Federal Laws which govern private communication and will be prosecuted to the fullest extent of the law. 

    On Thursday, April 30, 2020, 10:55:49 AM EDT, Brendan Abolivier <notifications@github.com> wrote:  
 
 



I am not sure where to ask this questions


As I said, please ask these questions in #synapse:matrix.org, which is our main support channel.
