### ISSUE TITLE
User directory doesn't show display names based on the requester's view

### ISSUE THREAD

**Issue by giambr1** [matrix-org/synapse#7383]
I run a debian server with a friend.
I have installed synapse following https://github.com/spantaleev/matrix-docker-ansible-deploy/ .
I have configured the bridge https://github.com/tulir/mautrix-telegram again through the playbook.
I had some problem related to private telegram contacts sharing between our two accounts on the server.
https://github.com/tulir/mautrix-telegram/issues/459 addresses the details of my problem. It has been suggested the issue is related more to synapse than the bridge itself.

**Comment by babolivier** [comment]
Hi and thanks for your report.

I think I understand how it's a Synapse issue. For the record, in this case it seems to be that the display name shown for a user in the user directory doesn't always match the requester's view of what that username should be, which could end up leaking personal info.

**Comment by richvdh** [comment]
this sounds like something we probably already have an issue for, ftr

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/synapse/issues/5677
