### ISSUE TITLE
Deletion of user account not possible.

### ISSUE THREAD

**Issue by derritter88** [matrix-org/synapse#7386]
Please don't file github issues asking for support.

Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
(from a matrix.org account if necessary), and ask there.

**Comment by babolivier** [comment]
Hi, as already mentioned in the template you've used to open this issue:

> Please don't file github issues asking for support.
> 
> Instead, please join [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org)
> (from a matrix.org account if necessary), and ask there.

**Comment by derritter88** [comment]
Sorry, my fault - I have already checked at the synapse channel but hit enter button so it created a new issue.

**Comment by richvdh** [comment]
related: #1707
