### ISSUE TITLE
create_group called on TransportLayerClient

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7390]
https://github.com/matrix-org/synapse/blob/de2d267375069c2d22bceb0d6ef9c6f5a77380e3/synapse/handlers/groups_local.py#L307-L309

`TransportLayerClient` nor any parent class has a `create_group` method. It looks like this might be a typo for `self.groups_server_handler.create_group`, however the arguments do not match the function signature.

**Comment by clokep** [comment]
We had a brief previous conversation about this: https://github.com/matrix-org/synapse/pull/7363#discussion_r417960554

@anoadragon453 also said:
> You know, I've been seeing tracebacks in my server logs for years related to group attestation. I bet this is it.

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
