### ISSUE TITLE
Ability to set default power levels via Config

### ISSUE THREAD

**Issue by cnvandijk** [matrix-org/synapse#7391]
**Description:**
This is essentially #4401 with a broader scope.

On an unfederated private homeserver, it can be useful to be able to tweak the permission model to e.g. allow all users to change the room name, add widgets etc. It is also often a requirement to disable e2e encryption. By exposing the default power levels via config, private homeservers would not need to resort to patching, such as in https://github.com/matrix-org/synapse/issues/4367#issuecomment-452772632.

**Comment by richvdh** [comment]
dup #6660
