### ISSUE TITLE
write some words about redis

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7402]

**Comment by richvdh** [comment]
redis is an alternative to direct tcp connections to the master: rather than all the workers connecting to the master, all the workers and the master connect to redis, which relays replication commands between processes. this can give a significant cpu saving on the master and will be a prerequisite for operation gemini work.

1. Install redis following the normal procedure for your distro - eg `apt install redis-server` for debian/ubuntu
2. check it's running and accessible: you should be able to `echo PING | nc -q1 localhost 6379` and get a response of `+PONG`.
3. Add config to homeserver.yaml:
    ```yaml
    redis:
      enabled: true
    ```
    Optional parameters which can go alongside `enabled` are `host`, `port`, `password`, `dbid`. If you don't know if you need the last two, you probably don't.
4. That's it. Restart master and all workers.
5. the `type: replication` listener documented in https://github.com/matrix-org/synapse/blob/master/docs/workers.md#configuration is now redundant. (the `type: http` one is still needed).

Question: should we put this in the sample config yet?

**Comment by DemiMarie-parity** [comment]
If we support AF_UNIX connections as well as TCP connections, a performance boost can be expected.

**Comment by richvdh** [comment]
done in #7446.

**Comment by richvdh** [comment]
@DemiMarie-parity txredisapi doesn't support unix-domain sockets afaict and it's not entirely obvious to me that the performance boost would be anything other than trivial

**Comment by jkhsjdhjs** [comment]
@richvdh txredisapi supports unix domain socket since at least 2013: https://github.com/IlyaSkriblovsky/txredisapi#features

**Comment by Dual-0** [comment]
Is adding redis via unix socket possible in the future? Do we need a new issue/feature_request?

**Comment by ShadowJonathan** [comment]
I'd recommend filing a new issue for that.
