### ISSUE TITLE
UIA stage m.login.password requires too many keys

### ISSUE THREAD

**Issue by Sorunome** [matrix-org/synapse#7405]
The UIA stage `m.login.password` requires too many arguments. You have to send an additional `user` key not defined in the spec (as things moved to `identifier`).

So, according to spec you have to send as auth dict:
```
{
  "type": "m.login.password",
  "identifier": {
    "type": "m.id.user",
    "user": "<user_id or user localpart>"
  },
  "password": "<password>",
  "session": "<session ID>"
}
```

But in reality you have to send
```
{
  "type": "m.login.password",
  "identifier": {
    "type": "m.id.user",
    "user": "<user_id or user localpart>"
  },
  "user": "<user_id or user localpart>",
  "password": "<password>",
  "session": "<session ID>"
}
```
Failure to do so will result in synapse just sending `{"errcode":"M_MISSING_PARAM","error":""}` as reply (not very descriptive).

### Version information
- **Version**:
```
sorunome@sorunome-desktop ~ $ curl http://localhost:8008/_synapse/admin/v1/server_version
{
    "python_version": "3.8.2",
    "server_version": "1.12.4 (b=master,204664d1a)"
}
```

- **Install method**: git

- **Platform**: archlinux

**Comment by richvdh** [comment]
#5665
