### ISSUE TITLE
Can't connect to room #neb:matrix.org

### ISSUE THREAD

**Issue by atomtm** [matrix-org/synapse#7407]
### Description

Trying to connect to `#neb:matrix.org` from my homeserver and I get : 

![image](https://user-images.githubusercontent.com/6628454/80966801-e24b4180-8e1d-11ea-9ed2-0d1c469d73c2.png)

 From Riot developer tools I get : `Failed to load resource: the server responded with a status of 502 (Bad Gateway)` 
and the address it is trying to access is:
`chat.avlikos.gr/_matrix/client/r0/join/%23neb%3Amatrix.org`

### Steps to reproduce
- on a room enter `/join #neb:matrix.org`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
This was identified on my homeserver . Same does not apply from my `matrix.org` account

- **Version**: 
1.12.4

- **Install method**: 
pip 


- **Platform**: 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"

**Comment by richvdh** [comment]
#2956
