### ISSUE TITLE
renew_attestations uses a lot of CPU

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7411]
I had to slow it down on matrix.org: https://github.com/matrix-org/synapse/commit/14bb4cff99ddd8b5eb1816c5405d52a8f13e29d6. We should probably make that permanent

**Comment by richvdh** [comment]
release blocker because it's important for matrix.org

**Comment by clokep** [comment]
(This seems to partially revert #7344.)

**Comment by richvdh** [comment]
> (This seems to partially revert #7344.)

yes, it removes the magic needed for tracking logcontexts across parallel jobs, because we no longer run the jobs in parallel.

**Comment by anoadragon453** [comment]
With https://github.com/matrix-org/synapse/issues/7411 merged, I believe this can be closed.

**Comment by richvdh** [comment]
> With #7411 merged, I believe this can be closed.

itym #7442

**Comment by richvdh** [comment]
this was basically a dup of #5936
