### ISSUE TITLE
synchrotron logs are full of 'Discarding RDATA for unconnected stream federation'

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7412]
this may be fixed in some of erik's forthcoming work, but if not we need to do https://github.com/matrix-org/synapse/commit/105cadbc9afd89be72762160d53c9f782b9be133

**Comment by richvdh** [comment]
release blocker because it overloads the synchrotrons

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/7421
