### ISSUE TITLE
assertionerrors from dummy event sending process

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7414]
after I lowered the threshold for dummy events (#7413) the logs started filling up with assertionerrors with little clue as to which assertion was failing. I'm fairly sure that wasn't due to my hackery, so this must be an underlying issue. I'd like us to understand the problem here.

**Comment by babolivier** [comment]
@richvdh Did these errors come with stacktraces? If so, it might be useful to include that her.

**Comment by richvdh** [comment]
hoping someone else can go and find them ;)

**Comment by anoadragon453** [comment]
We've decided to close this for now as this is no longer occurring on matrix.org. We can reopen and investigate if it comes back.
