### ISSUE TITLE
check_auth_blocking is burning 5% CPU

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7419]
mostly because it looks up a load of config settings on each call, each of which is reasonably expensive. we don't even use auth_blocking on matrix.org. it needs to be made less inefficient.

**Comment by richvdh** [comment]
this needs to land on a real branch before we can redeploy matrix.org.

**Comment by anoadragon453** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/7420
