### ISSUE TITLE
Room power levels for community members

### ISSUE THREAD

**Issue by jonsutherland** [matrix-org/synapse#7424]
**Description:**

It would be useful to be able to set power levels for community members for a room.  So if a user is a member of a community, I should be able to set all community members for a room to have moderator level permissions for a room, or give community members elevated power levels for a room. 

Something like setting a rooms m.room.power_levels but with +community_name@homeserver.url groupId you're setting power levels for?

**Comment by babolivier** [comment]
Hey, and thanks for your suggestion!

It doesn't sound like a Synapse issue to me, more like a spec one, so I'd suggest you open this issue on https://github.com/matrix-org/matrix-doc
