### ISSUE TITLE
Ignore sending PUSH notifications for muted rooms

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#7432]
At now, as I understand, Synapse sends PUSH notifications for all new messages, even if room is muted. This way unnecessary eats battery&traffic on mobile devices, because users not often reads muted rooms. So sending only one first PUSH for make room "bold" on new unread message is enough for most users. 

Can we add feature to disable sending unnecessary PUSH notifications to devices from muted rooms? Related Riot issue is https://github.com/vector-im/riot-web/issues/7438

**Comment by babolivier** [comment]
Synapse only sends notifications for rooms that it's configured to do so. Messages in muted rooms shouldn't cause notifications to be sent.

Are you saying you're seeing push notifs for muted rooms?

**Comment by babolivier** [comment]
Also the client figures out whether to bold a room from data it receives through sync, not push notifications. I don't remember the specifics, but I believe the Riot mobile clients sync when you're using them as well as whenever they receive a push notif (which, again, should only be sent when a message is sent to a room configured to notify you).

**Comment by MurzNN** [comment]
The main problem is that RiotX eats too much battery between 24 hours, even if I not use it and don't receive any new message from not muted rooms in this day. And I understand, that this is because it wakes up on PUSH'es from muted rooms. 

Is there any ways to debug or count sent push notifications to device on server/client side?

**Comment by MurzNN** [comment]
I found this in Synapse logs:
```
Processing 1 unprocessed push actions for @user:homeserver.org
```
So seems yes, on Synapse side all works well. I close issue.

**Comment by babolivier** [comment]
Cool then :)
For the record, the issue about RiotX being very hungry on the battery is https://github.com/vector-im/riotX-android/issues/536
