### ISSUE TITLE
UISIs between mozilla.org and matrix.org

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7456]
Around 19:15 UK time on May 7th 2020 the mozilla.org server had a glitch with its federation sender and sync 4 restarting:

![image](https://user-images.githubusercontent.com/1294269/81404608-d917e880-912d-11ea-8b4c-0f56c1863f47.png)

E2EE messages sent from mozilla.org users to matrix.org users in that timeframe were undecryptable and never recovered, which feels very worrying.  https://github.com/vector-im/riot-web/issues/13587 is the Riot side of it.

**Comment by richvdh** [comment]
is anyone actively working on this? it feels unlikely that we're going to try and figure out what went wrong a month ago at this point.

**Comment by anoadragon453** [comment]
@richvdh does not seem like it.

**Comment by richvdh** [comment]
ok, I don't think there's anything we can do with this now.
