### ISSUE TITLE
Room directory member count is wrong and overcounts.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7461]
This must be a dup, but i can't find the original one.

Sounds like we increment the running total of the member count used by the room directory every time we see a m.room.member with membership join - i.e. counting nick changes as joins. We should only count if they were a transition from parted or null to join.

**Comment by KB1RD** [comment]
related https://github.com/matrix-org/synapse/issues/1294

**Comment by ara4n** [comment]
#1294 is a more generic problem with membership counts being out of sync between the member list on different servers and reality (possibly due to state resets).  Whereas this is very specifically the /publicRooms list.

(https://github.com/matrix-org/synapse/issues/7041 looks to be the original one i was looking for, which got lost by being merged into the more generic bug).

**Comment by richvdh** [comment]
state resets do not cause divergence between servers. I really think this is just #1294.
