### ISSUE TITLE
restore forbidden room

### ISSUE THREAD

**Issue by oeai** [matrix-org/synapse#7462]
i've made a room public, then i decided to clean it with new text and deleted the room,
it was riot.im and it was moved to history, then i press forget and it was removed.
But it was written in my community and the community room list is now stuck and not resolving.
Now i try to join the room - no luck

   > request failed: CORS request rejected:

i wanted to create the room once again to solve it - the room name is not free
i did relog, tried with html client - no way.

i want to restore the room and join it / change name or make the room name free somehow
i need my community room list working (is it resolving by name or UID?)

   > room previews are disabled (M_FORBIDDEN)

**Comment by anoadragon453** [comment]
Seems that querying the room list of a group which contains a room with 0 members in it causes Synapse to 500. This is partially documented already in https://github.com/matrix-org/synapse/issues/4891 and thus I'm closing this issue as a duplicate.

However, I've also submitted a potential fix for this here: https://github.com/matrix-org/synapse/pull/7465

**Comment by oeai** [comment]
is the group servlet means that the name of forbidden group will also be deleted from name_search for new group? i think it should also be nulled or modified with _deleted+group_name, so the admin will see it in history by uid and cname.
