### ISSUE TITLE
Enable Desktop notifications from homesever.yaml

### ISSUE THREAD

**Issue by Ismathena** [matrix-org/synapse#7485]
hi,
I need to enable desktop notifications from homeserver.yaml without do it from interface.

Thanks for help .

**Comment by anoadragon453** [comment]
Desktop notifications are configured in your matrix client. I would suggest asking for support in [#riot-web:matrix.org](https://matrix.to/#/#riot-web:matrix.org) if you are using that client.

Synapse related support questions should be asking in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org).

**Comment by Ismathena** [comment]
Thanks !
