### ISSUE TITLE
implement MSC2176: Update the redaction rules

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7488]
It would sure be nice to implement [MSC2176](https://github.com/matrix-org/matrix-doc/pull/2176) - maybe even in time to get it into [room v6](https://github.com/matrix-org/matrix-doc/pull/2240).

**Comment by anoadragon453** [comment]
This is now slated for room v7+.

**Comment by richvdh** [comment]
this is pretty easy and high-impact.

**Comment by richvdh** [comment]
(these changes need to go into an experimental room version, so that they can then be proposed for a real room version)
