### ISSUE TITLE
Presence disabled - but users are visible with api call and android clients?

### ISSUE THREAD

**Issue by Lighti123** [matrix-org/synapse#7499]
### Description

Hello!
The presence tracking is disabled in our closed down non-federated homeserver, but the visibility of users can be seen with an api call and with the old android client?

Is this a bug?

Thanks,

### Steps to reproduce

If the following is set:
```
# Set to false to disable presence tracking on this homeserver.
#
use_presence: false
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

With Riot Web, Riot Desktop, RiotX and Riot on iOS the presence is not visible, as it should be.

With old Riot for Android clients the presence is visible.

With the following api call the presence is visible of other user accounts:
curl -XGET 'https://homeserver-url/_matrix/client/r0/presence/@account:homeserver-url/status?access_token=<token>'

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

own closed down non-federated homeserver.

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

{
    "python_version": "3.6.9",
    "server_version": "1.12.4"
}

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

ubuntu - package manager

- **Platform**:

ubuntu 18.04.4 LTS

<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by anoadragon453** [comment]
Ah yes, I believe this is due to this little TODO:

https://github.com/matrix-org/synapse/blob/56b66db78a3a6a22f65b219f4dc12899111f742b/synapse/handlers/presence.py#L684-L685

Synapse will accept presence updates even if the server will not do anything with them. Funnily enough I actually fixed this exact thing on my personal homeserver, so I've created a PR with the fix here: https://github.com/matrix-org/synapse/pull/7508

**Comment by anoadragon453** [comment]
A fix for this has been merged in https://github.com/matrix-org/synapse/pull/7508 which should land in Synapse v1.14.0. Please let us know and reopen if you still experience presence updates being processed in that version :)

**Comment by Lighti123** [comment]
thank you very much :-)
