### ISSUE TITLE
Implement room version 6

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7500]
Will contain additional features:
* #6898
* https://github.com/matrix-org/synapse/pull/7381
* #7501

Do not enable by default just yet.

**Comment by clokep** [comment]
See matrix-org/matrix-doc#2240

**Comment by clokep** [comment]
I'll do this since I'm implementing the two remaining pieces of this.

**Comment by clokep** [comment]
Done in #7506, this will be in 1.14.0.
