### ISSUE TITLE
Building the snap on s390x fails

### ISSUE THREAD

**Issue by woutervb** [matrix-org/synapse#7509]
When building the snap on an s390x ubuntu bionic installation, this process fails.

To reproduce:
1. Start a clean vm with ubuntu 18.04 of a s390
2. checkout the git repo of synapse
3. execute the command: `SNAPCRAFT_BUILD_ENVIRONMENT=host snapcraft` will fail with the error that is was missing setuptools_scm
4. fixing the python file synapse/python_dependencies.py by adding a reference to setuptools_scm, will allow the build to continue, bit it will warn with the following list of libraries that are missing.

The 'matrix-synapse' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entries to the existing stage-packages for this part:
- libicu60
- libjpeg-turbo8
- libxml2
- libxslt1.1

Both these errors are fixed in PR #7468

**Comment by richvdh** [comment]
is this problem specific to s390?

**Comment by woutervb** [comment]
Hi,
No, I saw this error also on amd64, so I think it is specific for snaps for some reason. Think / suspect one of the dependencies, but lacked the time to trace it.

**Comment by richvdh** [comment]
ok I went to the effort of installing an ubuntu VM myself on amd64 and tested. it seemed to work just fine.

That was time I'd much rather have spent doing something else. We don't have the time or inclination to support the `snap` build and I'm inclined to remove it altogether if it's going to be a source of unclear bug reports and pull requests.

in short I guess this *is* specific to s390. To help us move forward, please can you better describe the problem you see: what is logged, and why do you think we need to add these libraries?

**Comment by richvdh** [comment]
log from building on ubuntu18.04/amd64: [snap.log](https://github.com/matrix-org/synapse/files/4752250/snap.log)

**Comment by maquis196** [comment]
out of interest, wouldn't it be easier to use a docker image for this? hopefully soon we'll have multiple architecture's supported, s390 won't be one of them but that should build out of the box for this.

**Comment by richvdh** [comment]
we don't have the info needed to pursue this.
