### ISSUE TITLE
Delete used devices after deactivate useraccount in ad

### ISSUE THREAD

**Issue by NDYIT** [matrix-org/synapse#7529]
Hello everyone,
I have a question and don't really know if there is already a solution for this, if not it would be very helpful for us.
We use Riot in our house and host it ourselves. We have connected Riot to the AD so that authentication runs over it. This works as well. The problem I have is that, once a user has logged in with a mobile device (IOS or Android), he is logged in here and never has to log in again and the password is stored. If I now deactivate this AD object and change the password, it has no influence on the login on the mobile device. The user can continue to use Riot normally although his account has been deactivated for a long time.

At the moment we do this via a detour, we log in with the user account in Riot (in the browser), go to the settings here and delete all listed devices under Security & Privacy, so that the app on the mobile device is logged out immediately.

Is there any better way to do this?

PS. this is my first entry at Github so please forgive me if I do something wrong or enter it in the wrong place

Kind regards 

Andreas

**Comment by anoadragon453** [comment]
If you won't ever use that user account again, it's possible to "deactivate" the account using the admin API: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#deactivate-account

This will invalidate all of the user's access tokens (log them out of all of their devices) and cause them to leave all of the rooms that they are a part of.

**Comment by anoadragon453** [comment]
Does this suit your usecase? And are you using the https://github.com/matrix-org/matrix-synapse-ldap3 plugin to accomplish this?

**Comment by NDYIT** [comment]
Hi, thanks for answering. I have already found this post (https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#deactivate-account), but I do not have this directory with me. Is that something that is there by default or do I have to add / install it first?

**Comment by anoadragon453** [comment]
It is there by default on whatever domain is serving your client requests. Try going to `https://<your_homeserver/_synapse/admin/v1/server_version`. If that resolves successfully then you have access to the admin API. Simply replace `/_synapse/admin/v1/server_version` with whatever admin API you want to use.

You'll need to provide an admin access token as well with each request, which is loosely described in https://github.com/matrix-org/synapse/tree/master/docs/admin_api#using-an-admin-access_token

If this API suits your needs then I must ask that we close this issue as this board is not for support requests. However, if you do require functionality that is not provided by the API then we can reshape this issue into a feature request.

**Comment by NDYIT** [comment]
Thanks a lot ;), I think you can close this issue.
