### ISSUE TITLE
Add info on how to set up worker metrics to metrics-howto.md

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7532]
In [metrics-howto.md](docs/metrics-howto.md) there is currently no information about how to set up metrics properly when you're in a worker-based environment.

As far as I understand it, one needs to set up a metrics resource (ideally on a non-public port) for each worker, and then configured prometheus to scrape each one individually.

Currently the community is setting up workers but only have the knowledge to monitor the master process.

**Comment by clokep** [comment]
@babolivier had written some good stuff about this in https://github.com/matrix-org/synapse/issues/7312#issuecomment-617826255

**Comment by babolivier** [comment]
Also there's some docs in `workers.md` as of https://github.com/matrix-org/synapse/commit/036fab5d8adc8fbafc6cdca5a29c7361b697a6e2

**Comment by anoadragon453** [comment]
Nope, that seems to pretty much cover what I wanted done!

> Also there's some doc about that in workers.md as of #7357.

That PR doesn't seem to touch `workers.md`?

**Comment by babolivier** [comment]
> That PR doesn't seem to touch workers.md?

That's just showing how difficult it is to remember what you've done in the past :'D
