### ISSUE TITLE
Change value of "group_creation_prefix" in sample_config

### ISSUE THREAD

**Issue by TheObserver6995** [matrix-org/synapse#7537]
**Proposed change**
I would like to suggest, that the value in the sample config for "group_creation_prefix" gets changed from "unoffical/" to something without a slash. For example "unofficial_".

**Reason**
The slash character causes issues in
- https://matrix.to
- Riots automatic group id detection in chats (if the id is withing a message, it doesn't get automatically converted to a link when it contains a slash)
- Admin API group deletion

For the admin API, the character can be escaped as "%2F", but an server admin might not think this is necessary.

**Conclusion**
The slash character in group ids causes numerous issues with the matrix ecosystem. This shouldn't be the case for an example value in official sample config, as these values are expected to work.

Furthermore, I think other characters (like an underscore) fill the purpose similarly well. Therefore I don't see a reason to leave it like that, but reasons to change it since other characters don't cause these issues.

**Comment by anoadragon453** [comment]
This sounds reasonable to me, and definitely an oversight. Thanks for reporting.
