### ISSUE TITLE
script to deactivate all accounts when decommissioning a server

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7551]
if you're decommissioning a server and don't want your federation listener to be spammed with traffic until the end of time, perhaps we should give a script that parts all your server's users from all their rooms and deactivates them, if you know you're killing off that server

**Comment by anoadragon453** [comment]
I imagine this would simply be a case of [listing all user accounts](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#list-accounts) via the admin api, and then [deactivating them](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#deactivate-account), saving the deactivation of the admin account itself til last (or optional entirely).

**Comment by Valodim** [comment]
please leave your :+1:s here: #3765

**Comment by richvdh** [comment]
yeah I'm going to close this as a dup of #3765.
