### ISSUE TITLE
Inaccurate copyright notices

### ISSUE THREAD

**Issue by joepie91** [matrix-org/synapse#7565]
### Description

Various files in the repository, such as https://github.com/matrix-org/synapse/blob/master/synapse/api/urls.py#L3, currently state something like "Copyright 2018 New Vector Ltd".

However, if I recall correctly, the IP for all the Foundation stuff including Synapse was donated by NV to the Foundation, which would make this copyright ownership header inaccurate (and, based on a question in Matrix HQ today, confusing to readers).

Perhaps a repository-wide search-and-replace of these headers is in order?

**Comment by ara4n** [comment]
So yeah, all public IP in github.com/matrix-org written by NV folks was assigned to the Matrix.org Foundation after it was set up in Oct 2018 (or a bit later; I think the actual assignment happened in Apr 2019 as part of the lead-up to the public launch of the Foundation alongside Matrix 1.0 in June 2019).

However, I'm not sure that a copyright assignment actually means that historical copyrights should get rewritten - I believe they're immutable, even if that IP is now owned by a different legal entity.  Going forwards, all changes to Synapse (and other public Matrix.org projects) should be (C) the Foundation, and it's a thinko if they're not.

**Comment by anoadragon453** [comment]
Going to close this now as it has received a response. Please re-open if you think there should be further discussion.

**Comment by joepie91** [comment]
Oops, forgot to respond to this. I do think further discussion is necessary here (but cannot reopen the issue myself).

I don't use copyright file headers myself, so I'm a bit fuzzy on the specifics, but as I understand it, it is meant to indicate of which changes the copyright belongs to whom, as a sort of more rudimentary "commit log". If that is the case, then if the ownership of the copyright changes, so should the headers.

However, even if it is intended to just log who controlled the IP during a given time period, the *existing* headers should be updated to reflect the handover, since right now various files are incorrectly declaring this.

In either case, the current situation is rather confusing for understanding who actually owns the IP, and things should probably be changed in *some* way to clarify this.

**Comment by richvdh** [comment]
we're waiting to hear back from the lawyers on this. we can keep it open until we do.

**Comment by richvdh** [comment]
well we heard back from the lawyers. You're right; the old copyright lines (for Openmarket/Vector Creations/New Vector) should be replaced with "The Matrix.org Foundation C.I.C.".

**Comment by ara4n** [comment]
yup, turns out that copyright is mutable, and if you assign it to someone else you update the statements - leading to the bizarreness that an organisation like the Matrix.org Foundation can claim copyright over works which predate its existence. 🤷‍♀️

**Comment by richvdh** [comment]
According to more recent words from @ara4n:

> When we set up the foundation in Oct 2019, we assigned all our existing copyrights to the foundation.
>
> Apparently, having checked with our lawyers, if you assign copyright to someone else like that, you're technically meant to go through rewriting all the (C) headers to the current owner, rather than them charting who the owner was at the date in question.
>
> However, I don't believe there is a serious legal reason to do this, and we prefer that we keep the historical headers to spell out which companies wrote this originally and that while everything is now under the aegis of the Foundation, all the early work was funded by New Vector (and before that Vector Creations, and before that OpenMarket).
>
> In other words please do not edit historical copyright headers (other than to update the daterange if needed).

Accordingly, we'll be leaving this alone.
