### ISSUE TITLE
master doesn't send replication traffic unless you have a TCP replication listener

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7566]
the TCP replication listener is unused if you have redis, so you'd expect to be able to remove it (indeed, the [docs](https://github.com/matrix-org/synapse/blob/85155654c52bb9999b6b4bcbcf84cd68505d4c82/docs/workers.md#experimental-support-for-replication-over-redis) say that you can). But if you do that, nothing builds the `ReplicationStreamer`, so no replication traffic ever gets sent.

**Comment by clokep** [comment]
Looks like this will be fixed for 1.14 from #7579. Closing this.
