### ISSUE TITLE
New join rule for rooms: public only for homeserver users

### ISSUE THREAD

**Issue by sephii** [matrix-org/synapse#7568]
I'm using Synapse in an organization where people log in using SSO with their organization account. We create most of the rooms as public so that everyone in the organization can easily join rooms. Sometimes we also have externs we need to invite in rooms. They can't login with SSO because they don't have an organization account, and apparently [Synapse/Riot doesn't support having both SSO and password authentication enabled](https://github.com/matrix-org/synapse/issues/7559). My workaround was to enable federation and ask externs to create an account on another homeserver so I can then invite them on rooms on my homeserver.

i noticed today, after several weeks of using this workflow, that everyone from any homeserver could join most of the rooms created on my homeserver, which isn't what I expected (it basically means that everything we post in rooms is public to the world). I think it would be nice to have a setting to make rooms discoverable and joinable (without an invite) only by people on the same homeserver, and be more explicit about what "public" means (but that's probably an issue for clients, not for Synapse).

I hope my request makes some sense. I was surprised I couldn't find any other request for such a feature, because it looks like a common scenario to me. Maybe I'm not using Synapse the way it was meant to be?

**Comment by anoadragon453** [comment]
> I think it would be nice to have a setting to make rooms discoverable and joinable (without an invite) only by people on the same homeserver

One thing you can do is lock down your public rooms list to only users on your own homeserver: https://github.com/matrix-org/synapse/blob/edd9a7214c467e96f5a694598b2fbcfae3ac2912/docs/sample_config.yaml#L79-L88

Additionally, rooms *can be created* an non-federatable, which means only users on your own homeserver can join and read/write content to the room. However, this can only be done on room creation. (You can "upgrade" existing rooms into a new room that's non-federatable. All users in the room will then get a notification to continue to conversation in the new room - though beware it is slightly technically involved to upgrade a room into one you've created previously). This means that others on other homeservers will not be able to join the room, though I realize you said that you wanted this for now as a workaround.

You could also employ a federation whitelist, which would allow users from another, specific homeserver to participate with your own, but nobody else: https://github.com/matrix-org/synapse/blob/edd9a7214c467e96f5a694598b2fbcfae3ac2912/docs/sample_config.yaml#L121-L130

Obviously it seems that solving #7559 would be the ultimate solution in your case, but in the meantime perhaps one of the mentioned options will help.

**Comment by ptman** [comment]
There have been proposals to make rooms freely joinable by users belonging to the same community as the room. But that probably depends on communities/groups being reworked.

**Comment by sephii** [comment]
> One thing you can do is lock down your public rooms list to only users on your own homeserver: 

This doesn't prevent people from joining by guessing room names, which can be quite easy, especially if you have a default channel set with a generic name.

> This means that others on other homeservers will not be able to join the room, though I realize you said that you wanted this for now as a workaround.

Exactly. Blocking federation would mean I couldn't have users that are not part of my organization anymore.

> You could also employ a federation whitelist, which would allow users from another, specific homeserver to participate with your own, but nobody else.

That's probably the best workaround, except it means I'll have to run 2 Synapse instances. I'll try that, hoping I can use a subdomain in the mxid and server_name so that I don't need to buy a new domain name.

**Comment by erikjohnston** [comment]
> I hope my request makes some sense. I was surprised I couldn't find any other request for such a feature, because it looks like a common scenario to me. Maybe I'm not using Synapse the way it was meant to be?

For what its worth what we've seen is that a lot of users who want this functionality tend to also be running with federation disabled (or running a trusted clique of servers). In that case you can use the third party rules plugin system for Synapse to add such custom behaviour on top of the existing auth rules, but it only really works if all the servers are trusted.


I think traditionally the answer to this has been to wait for the ability to use communities, but like @ptman said that is a bit blocked at the moment.

Alternatively we could add another join rule, but that requires an MSC and new room version. I had a quick look at https://github.com/matrix-org/matrix-doc and couldn't see an open issue for it, but feel free to create one (or write an MSC for it!)



I''m going to close this for now since there's nothing more Synpase can do here really without spec changes.
