### ISSUE TITLE
Login with QR code AND cross-signing in one shot

### ISSUE THREAD

**Issue by cyanlemons** [matrix-org/synapse#7571]
We currently have QR code cross-signing. You will typically perform the cross-signing immediately after you login on a new device.

Discord currently allows users to login with QR codes if they are already logged in on another device.

It seems like the obvious next step in terms of better UX is to kill two birds with one stone. I suggest that there be an option to login and cross-sign a new device simultaneously with one QR code.

In 99% of cases wherein you are verifying a new device, you will have just recently logged in anyway, so why not make it simpler & quicker?

**Comment by anoadragon453** [comment]
Good idea - may or may not be cryptographically possible, but nice from a UX perspective for sure.

This is more of a Matrix Specification issue though than a Synapse one - it will first need to designed at the spec level before we can implement it in Synapse. I suggest you open this same issue on the [matrix-doc](https://github.com/matrix-org/matrix-doc/) repository, and if you, or anyone you know, has the know-how to design how this would work, feel free to create a [Matrix Spec Change Proposal](https://matrix.org/docs/spec/proposals) and we'll take a look.

**Comment by cyanlemons** [comment]
[Sure thing!](https://github.com/matrix-org/matrix-doc/issues/2583)
