### ISSUE TITLE
Prebuilt packages for CentOS 8

### ISSUE THREAD

**Issue by florian2833z** [matrix-org/synapse#7573]
Hello,

Is there a prebuilt package for centos8 planned? Since CentOS has a pretty huge community/userbase, this would be very useful.

**Comment by anoadragon453** [comment]
The Matrix Synapse team only provides [PyPI](https://pypi.org) and [Debian packages](https://packages.matrix.org/debian). Packages for other distributions are handled by separate package maintainers of that distribution.

I recommend reaching out to a CentOS package maintainer and asking them to take on the task, or perhaps trying your own hand at it.

After talking to a maintainer of another distribution, they mentioned that packaging Synapse itself would likely not be *too* hard - the real gotcha will be in creating packages for all of the python dependencies that Synapse relies on.
