### ISSUE TITLE
Shard master process.

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#7593]
Follows on from: #6677

Now that Synapse supports writing events from a different process, we should look at supporting writing events from multiple processes at once, aka sharding of events stream.

**Comment by djschilling** [comment]
Is there a documentation how this can be achieved?

**Comment by erikjohnston** [comment]
https://docs.google.com/document/d/1xL1foUsHgcHdVTOAMSJIST04cH0ukHd-oCKFw3m9sxY has our current thoughts

**Comment by djschilling** [comment]
What i ment was the documentation of what is currently possible with `Now that Synapse supports writing events from a different process `

**Comment by erikjohnston** [comment]
Ah, right. There isn't any yet, but we're aiming to get some docs for the next release. Right now its quite experimental and hasn't been tested a huge amount, so we don't recommend anyone try it out on production quite yet (unless they really really know what they're doing)

**Comment by benlangfeld** [comment]
> Ah, right. There isn't any yet, but we're aiming to get some docs for the next release. Right now its quite experimental and hasn't been tested a huge amount, so we don't recommend anyone try it out on production quite yet (unless they really really know what they're doing)

Hey @erikjohnston. Did that documentation ever get written?

**Comment by erikjohnston** [comment]
> > Ah, right. There isn't any yet, but we're aiming to get some docs for the next release. Right now its quite experimental and hasn't been tested a huge amount, so we don't recommend anyone try it out on production quite yet (unless they really really know what they're doing)
> 
> Hey @erikjohnston. Did that documentation ever get written?

Yup, how to move event persistence off master is now at: https://github.com/matrix-org/synapse/blob/develop/docs/workers.md#stream-writers

**Comment by benlangfeld** [comment]
> > > Ah, right. There isn't any yet, but we're aiming to get some docs for the next release. Right now its quite experimental and hasn't been tested a huge amount, so we don't recommend anyone try it out on production quite yet (unless they really really know what they're doing)
> 
> > 
> 
> > Hey @erikjohnston. Did that documentation ever get written?
> 
> 
> 
> Yup, how to move event persistence off master is now at: https://github.com/matrix-org/synapse/blob/develop/docs/workers.md#stream-writers

Does that mean that this issue is complete? If not, what remains to be done?

Is there any documentation which clarifies why the master process still exists, and why it must be a singleton?

**Comment by benlangfeld** [comment]
Hey @erikjohnston , I wonder if maybe having skipped mentioning you meant you didn't see that question. I appreciate your time in helping understand this. We're evaluating Synapse for a use case that might justify our contributing or funding the contribution of improvements to HA.

**Comment by erikjohnston** [comment]
I'm afraid there isn't an authoritative list of what still remains on master, broadly we've been moving stuff of master whenever we start seeing it become a problem, but that does mean there are quite a few APIs and streams that remain on master simply because they're not high intensity. 

The way to figure out what is still on master is:

1. Look at the servlets only loaded on master
2. Look at replication streams on started on master
3. Look at the places in the code where we check if we're on master, usually: `worker_app is None:`.

**Comment by richvdh** [comment]
I'm going to close this, because the initial work is done. Remaining work includes:
* better documentation (https://github.com/matrix-org/synapse/issues/9072)
* getting rid of the differences between workers (#10441)
* Better testing (https://github.com/matrix-org/synapse/issues/10065)
