### ISSUE TITLE
Join command autocreate default config room

### ISSUE THREAD

**Issue by Belladona-c0re** [matrix-org/synapse#7598]
There are any configuration that enables auto create a room when a user use /join command and this room doesn't exist previously? Using a default config room creating parameters, like IRC.

this feature is possible?

Regards!

**Comment by erikjohnston** [comment]
There isn't at the moment. You might be able to do something with a custom spam module, but I don't think so.

This is probably a reasonable feature to have, though Matrix is not quite like IRC where rooms are more ephemeral. Some thought probably needs to go into what the defaults for new rooms are, and exactly what the UX is like for clients.

**Comment by reivilibre** [comment]
In my opinion, this would be better as a client-side feature — the server isn't in a good position to understand the user's intent (creating a blank room in response to a typo seems like a nasty fault, plus the server doesn't know whether the room should be public or private etc).
