### ISSUE TITLE
Add module to dockerized synapse

### ISSUE THREAD

**Issue by abdullasharapov** [matrix-org/synapse#7601]
I use synapse in docker container. How to add this module https://github.com/devture/matrix-synapse-shared-secret-auth?
I use the official image and do not want to manually install the module and make commit. Is it possible to forward shared_secret_authenticator.py to /usr/local/lib/python3.7/site-packages or specify the path to the module in homeserver.yaml?

**Comment by richvdh** [comment]
it should be possible to build your own docker image which adds any custom modules you like. this isn't really the place to get support for that.

**Comment by coisnepe** [comment]
@abdullasharapov Did you ever figure it out? I'm trying to achieve exactly the same thing but haven't succeeded so far. If @richvdh could kindly point out "the place to get support for that" (i.e. where the "local" file should be loaded within the docker container upon startup), that'd be great :-)

**Comment by abdullasharapov** [comment]
> @coisnepe I solved it as follows: mounted shared_secret_authenticator.py to the path /usr/local/lib/python3.8/site-packages/shared_secret_authenticator.py of the container

**Comment by coisnepe** [comment]
@abdullasharapov awesome, thanks! Exactly what I was looking for. Other things still not working as expected, I'll report back when everything works.
