### ISSUE TITLE
One way federation

### ISSUE THREAD

**Issue by ArchangeGabriel** [matrix-org/synapse#7605]
Hi there, and thanks for the great work on Matrix.

We are wondering for a specific setup if it would be possible to do only one-way federation: our local users would not be able to join rooms on other homeserver, but people from other HS should still be able to join federated rooms in our HS.

**Comment by ArchangeGabriel** [comment]
I was linked to https://github.com/matrix-org/synapse/pull/5783.

`complexity: 0.0` could likely achieve this, am I right?

**Comment by erikjohnston** [comment]
The room complexity stuff may work, I'm not 100% sure, but its not really want its designed for.

I think the correct way of doing this is using the `third_party_event_rules` plugin, which allows running arbitrary rules on new events generated by the server. In this case I think you could write a module that denies all joins by local users where there are no other users in the room. I'm not 100% sure that will work well, but if it doesn't then we should expand third party event rules to support this use case.

**Comment by erikjohnston** [comment]
I'm closing this for now. If it turns out that using `third_party_event_rules` doesn't work out then we can open more specific issues :+1:
