### ISSUE TITLE
Email registration always fails

### ISSUE THREAD

**Issue by Wangmmx** [matrix-org/synapse#7608]
I just want some WND to continue my test, but I can't register in Riot.

![image](https://user-images.githubusercontent.com/22836587/83382809-7e189f00-a416-11ea-9740-c9bd553656ea.png)

email-address:
wangmmx0725@163.com
I'm sure this is a working and normal mailbox, What kind of email format is available?

how can I contact Matrix homeServer admin? I don't know what homeServer is.

**Comment by erikjohnston** [comment]
What app/URL are you using to register?

**Comment by Wangmmx** [comment]
https://riot.w3f.tech/#/register

**Comment by erikjohnston** [comment]
You're attempting to create an account on web3.foundation server, who have likely (intentionally or unintentionally) set it to require you to register with an email account from a particular domain. If you have an email address associated with web3 I'd suggest trying to use that (or try leaving the email address blank).

Unfortunately there isn't currently a way of getting contact details for an admin of a given matrix server (though its a feature that would be useful to have https://github.com/matrix-org/synapse/issues/1267), so you will need to somehow contact them separately if you think you should have an account on that server.

If you just want a matrix account you can use register for a matrix.org one via https://riot.im/app/ (which you'll be able to use to talk to users on web3.foundation).

I'm afraid there isn't much we can do to help as this sounds like the server has been intentionally configured to require an address from a particular domain.
