### ISSUE TITLE
invites from unreachable hosts not deleteable

### ISSUE THREAD

**Issue by silvio** [matrix-org/synapse#761]
I rise this issue on github too, I don't have gain attention on my jira entry.
On [this page](https://matrix.org/jira/browse/SYWEB-384) I have described that a invitation could not deleted if the host is not reachable any more.

It would be nice to have the ability to delete invitations.

**Comment by devz3r0** [comment]
i have the same issue with emailadresses which didn't respond.

**Comment by richvdh** [comment]
believe this was fixed by #691.

**Comment by silvio** [comment]
Thanks @erikjohnston and @richvdh

**Comment by richvdh** [comment]
ohhkay. So, I'm not sure this was actually fixed for *unreachable* hosts. #691 only fixed it for hosts which are reachable, but return an error when you try to reject the invite. Furthermore, #991 appears to have regressed it for servers which return 500 errors too.

**Comment by richvdh** [comment]
this was fixed by https://github.com/matrix-org/synapse/pull/2145
