### ISSUE TITLE
Default End to end encryption slider position

### ISSUE THREAD

**Issue by keymous** [matrix-org/synapse#7626]
Hello,

Is it possible to make "Enable end-to-end encryption" slider be off by the default? 
I tried this: https://github.com/matrix-org/synapse/issues/4367 , but no results.
Maybe you could point me to the right direction?

![riot](https://user-images.githubusercontent.com/66371016/83644213-b73d4480-a5b9-11ea-894e-5339b712ff13.PNG)

**Comment by erikjohnston** [comment]
This is a client side issue in some ways, in that it would be perfectly possible for, say, a given riot web deployment to have this disabled by default (riot web may already have that option).

For a server side way of disabling encryption there is https://github.com/matrix-org/synapse/issues/4401.

Closing as I think this is either tracked by #4401 or is a client side issue.
