### ISSUE TITLE
prometheus_client 0.8.0 not supported

### ISSUE THREAD

**Issue by z3ntu** [matrix-org/synapse#7641]
### Description

Synapse doesn't with prometheus_client 0.8.0 installed. `synapse/python_dependencies.py` specifies `"prometheus_client>=0.0.18,<0.8.0",` so an error is thrown with version 0.8.0.

### Steps to reproduce

- install prometheus_client 0.8.0 from pypi
- try to start synapse

### Version information

- **Version**: 1.13.0

- **Install method**: Package manager

- **Platform**: Arch Linux

**Comment by Bubu** [comment]
FWIW after patching out the version check prometheus monitoring still works fine.

The archlinux bug tracking this is here: https://bugs.archlinux.org/index.php?do=details&action=details.addvote&task_id=66901

**Comment by z3ntu** [comment]
@Bubu You're linking to the 'addvote' page :wink: Maybe https://bugs.archlinux.org/task/66901 would be a better link. I've also patched out the version requirement from `/usr/lib/python3.8/site-packages/synapse/python_dependencies.py` and everything seems to work fine, but I don't use prometheus monitoring (as far as I know).

**Comment by richvdh** [comment]
> install prometheus_client 0.8.0 from pypi

I'm tempted to say "don't do that" :-p
