### ISSUE TITLE
no create event in auth events

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7642]
sometimes requests get rejected with `{"errcode":"M_FORBIDDEN","error":"No create event in auth events"}`. Not quite sure what causes this.

**Comment by richvdh** [comment]
some places this has been reported:

 * https://github.com/vector-im/riot-web/issues/8689
 * whenever trying to join `#trains:matrix.org`
 * in this test run: https://buildkite.com/matrix-dot-org/synapse/builds/9447#fcb142a2-3d35-4856-829f-2c9e404fbce4

**Comment by richvdh** [comment]
the fact that this happens sometimes during a sytest run suggests that there is a race condition of some sort (interesting that it happened with a monolith deployment: I'd expect races to be more likely with workers.)

**Comment by PureTryOut** [comment]
I just had this happen in `#synapse:matrix.org` and a few others. Some fixed themselves, but for `#synapse:matrix.org` I had to rejoin it (which was hard to do in itself).

What might've caused it for me is that I was moving Synapse to a different machine (but made it use the same database as on the previous machine).

**Comment by richvdh** [comment]
another instance in a test run: https://buildkite.com/matrix-dot-org/sytest/builds/960#655edd00-a2b4-4b0b-bee2-142ec753a994

**Comment by richvdh** [comment]
I suspect there's more than one cause for this issue. I've opened https://github.com/matrix-org/synapse/issues/7834 to track one of them, and will either add more issues to track other causes, or add reports to existing issues.

**Comment by richvdh** [comment]
for #trains, see #7835

**Comment by richvdh** [comment]
for vector-im/riot-web#8689, see #7838.

**Comment by richvdh** [comment]
#7139 is yet a fourth scenario, though related to some of the others.

**Comment by richvdh** [comment]
cause number five over at #7845.

**Comment by richvdh** [comment]
with the exception of #7838, which is a bit of a larger topic, I've now fixed all of the causes I found here. #8041 also adds a check which will give a more accurate error message.

So, I'm declaring this fixed.

**Comment by pkulak** [comment]
Can anyone tell me how to fix this? I've got a buggered room with three members. No one can leave it, I can't delete it because it has members, and all messages to it fail.

**Comment by pkulak** [comment]
> > Can anyone tell me how to fix this? I've got a buggered room with three members. No one can leave it, I can't delete it because it has members, and all messages to it fail.
> 
> For these sorts of support questions, it's best to try #synapse:matrix.org.
> 
> I'm guessing you've already tried the [admin API to delete a room](https://matrix-org.github.io/synapse/latest/admin_api/rooms.html#delete-room-api) ? Does using the `force_purge` option work?

Ah yeah, good call. I'll hop in the chat and see if anyone can help me out. Thanks!

I have tried pretty much every variation of that API I can think of; it always errors out, unfortunately.

**Comment by ktpx** [comment]
I ahve this problem with a channel too, no way to leave.. API doesnt help, it gives a server error saying users are still logged in...chicken or egg problem.  only me in there.

**Comment by ZhenyaPav** [comment]
Ironically, I am having this issue with #synapse:matrix.org right now.

**Comment by ZhenyaPav** [comment]
One solution I found is to run this SQL query:
`DELETE FROM room_memberships
WHERE room_id = '!ehXvUhWNASUkSLvAGP:matrix.org';` (replacing the room id with the one you have the issue with)
And then purging the room as usual (i'm using synadm)
Disclaimer: I've no idea if this may break something down the line or not, but I was able to rejoin the room normally.

**Comment by clokep** [comment]
We think we've fixed all the issues with this, but old rooms might still be broken in your database. The correct thing to do is to purge the room (you should not need to run any delete commands manually first and that is not recommended).

I'm going to lock this issue since it is quiet old. Please open *new* issues if you're still seeing problems.
