### ISSUE TITLE
Update default room to version 6

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#7646]
Synapse v1.14.0 included support for room version 6 (see #7500). At some point we'll want to make this the default once people have had time to upgrade to compatible homeservers.

**Comment by TheEvilSkeleton** [comment]
Just a suggestion, I personally think that it would be a better idea to fix the issues before making it the default:

https://github.com/vector-im/element-android/issues/1558
https://github.com/vector-im/element-android/issues/1879

**Comment by TheEvilSkeleton** [comment]
Awesome :) https://github.com/vector-im/element-android/pull/2010

**Comment by turt2live** [comment]
MSC: https://github.com/matrix-org/matrix-doc/pull/2788

**Comment by aaronraimist** [comment]
Fixed by #8461
