### ISSUE TITLE
Federation .well-known requests are sent without user agent header

### ISSUE THREAD

**Issue by tulir** [matrix-org/synapse#7653]
### Description
Synapse sends requests to `/.well-known/matrix/server` with no `User-Agent` header. This can cause problems when trying to host the file on a webserver that blocks empty user agents, such as Shopify.

### Steps to reproduce
- Set up a server with .well-known delegation that doesn't allow blank user agents
- Try to federate with that server

Expected result: federation works fine
Actual result: other servers will fail to fetch the .well-known and fall back to 8448, leading to federation not working

```
2020-06-07 18:28:45,826 - synapse.http.federation.well_known_resolver - 234 - INFO - POST-3484386- Fetching https://solokeys.com/.well-known/matrix/server
2020-06-07 18:28:46,126 - synapse.http.federation.well_known_resolver - 185 - INFO - POST-3484386- Error parsing well-known for b'solokeys.com': Non-200 response 403
2020-06-07 18:28:46,192 - synapse.http.federation.matrix_federation_agent - 242 - INFO - POST-3484386- Connecting to solokeys.com:8448
```

### Version information
- **Version**: 1.14

The problem seems to be [http/federation/well_known_resolver.py](https://github.com/matrix-org/synapse/blob/master/synapse/http/federation/well_known_resolver.py#L237): it uses its own twisted agent instead of the shared methods in `http/client.py`, and does not specify any headers. Twisted does not seem to have a default user-agent, which means no user agent header is sent.

**Comment by nickray** [comment]
Thanks @tulir. For context, we are having this issue on our solokeys.com instance, where the TLD is hosted on Shopify, which seems to accept any non-empty UA, but not the empty one.

**Comment by richvdh** [comment]
so should the matrix spec say that you must present a User-Agent header?

**Comment by auscompgeek** [comment]
FWIW, the HTTP RFCs say that [clients should send a User-Agent](https://stackoverflow.com/questions/24274789/is-lack-of-user-agent-in-http-request-valid#24274846).

**Comment by clokep** [comment]
> FWIW, the HTTP RFCs say that [clients should send a User-Agent](https://stackoverflow.com/questions/24274789/is-lack-of-user-agent-in-http-request-valid#24274846).

Seems reasonable to me to not bother putting it in the spec, if anything I think it would go into a "implementation guidance" section.

I think Twisted is the first framework I've used that doesn't set a default one...

**Comment by richvdh** [comment]
yeah I hadn't realised it was required by the HTTP RFCs.

>  anything I think it would go into a "implementation guidance" section.

agreed.
