### ISSUE TITLE
Profile the matrix.org master process

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#7670]
Then determine what else should be migrated away.

**Comment by clokep** [comment]
I threw py-spy at a the main process and was not able to find anything terrible obvious, but there were a few observations:

* 5 - 10% of samples were [pruning old IPs](https://github.com/matrix-org/synapse/blob/527f73d902001d7d4ba4df402866d7ccff3e9b6d/synapse/storage/databases/main/client_ips.py#L568).
* 3 - 5% of samples were [updating stats deltas](https://github.com/matrix-org/synapse/blob/b49a5b9307fbbc9032e28e532e9036db07555d3d/synapse/storage/databases/main/stats.py#L338-L358)

Additionally I spent some time looking at a dummy worker that wasn't working on anything (it was essentially sitting idle, but using ~20% CPU). I was able to profile that without the `--nonblocking` flag which gave slightly more interesting results:

* The "main" JSON encoder/decoder being used is still simplejson (see #7674).
* ~20 - 25% of samples were in the (Redis) replication code, [~15% here](https://github.com/matrix-org/synapse/blob/84d099ae1192af0f38d26f9a32e38bd4c0ad304e/synapse/replication/tcp/client.py#L130-L136) and [~8% here](https://github.com/matrix-org/synapse/blob/0f1afbe8dc853c8726de797ede10cad2fe336b16/synapse/app/generic_worker.py#L677-L698).

These numbers are all made worse if you look at only what has the gil.

**Comment by clokep** [comment]
> * 5 - 10% of samples were [pruning old IPs](https://github.com/matrix-org/synapse/blob/527f73d902001d7d4ba4df402866d7ccff3e9b6d/synapse/storage/databases/main/client_ips.py#L568).
> 
> * 3 - 5% of samples were [updating stats deltas](https://github.com/matrix-org/synapse/blob/b49a5b9307fbbc9032e28e532e9036db07555d3d/synapse/storage/databases/main/stats.py#L338-L358)

In addition to seeing something like the above it also seems that a decent amount of time is spent in:
* The `executemany` call in [`_rotate_notifs_before_txn`](https://github.com/matrix-org/synapse/blob/d4daff9b59bc2c837d60b132aaaea85d1c0f00b4/synapse/storage/databases/main/event_push_actions.py#L928-L945).
* [`_fetch_event_list`](https://github.com/matrix-org/synapse/blob/9f8abdcc3828e942f09cc62e29dff93dbaa01ec7/synapse/storage/databases/main/events_worker.py#L527-L529) shows up sometimes as well.

When including all threads, most of them are waiting in [`new_transaction`](https://github.com/matrix-org/synapse/blob/e35129844466ec5f63a744fa2181cd0f8691e49c/synapse/storage/database.py#L429).

**Comment by clokep** [comment]
The current work in flight from this is to move some background tasks out of the main process.

**Comment by richvdh** [comment]
I don't think we're planning to do any more profiling in the near future.
