### ISSUE TITLE
Shard Client Reader for registration

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#7672]

**Comment by erikjohnston** [comment]
We think that we can already do this now that sessions are persisted to the database, but we should test and double check this is true.

**Comment by richvdh** [comment]
to be clear: we already have multiple client readers; this task is to remove the rules in haproxy that pin registration requests to a single instance.

**Comment by clokep** [comment]
I believe that #7530 is related to this, although that's specific to using SAML.

**Comment by clokep** [comment]
@erikjohnston had a couple more thoughts on this:
> FYI on the client reader sharding the first step might be to look at the federation sharding test and steal the logic for running multiple workers, and then do a registration flow against them but change which worker you speak to each time
