### ISSUE TITLE
we should kill off registration fallback

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7676]
https://matrix.org/_matrix/static/client/register is a thing which exists, but as per #6709, is broken, and as per https://github.com/matrix-org/matrix-doc/issues/2411, is unspecced. I think we should remove it.

**Comment by bmarty** [comment]
I can confirm that it was working, but today it does not work anymore. At least Element Android still relies on it if a registration stage is unknown and can't be handled natively

**Comment by richvdh** [comment]
per https://github.com/matrix-org/matrix-doc/issues/2411#issuecomment-1048041146L: are you sure?

**Comment by richvdh** [comment]
for the record, the reason registration fallback is broken (and has been since at least #4334 / Synapse 0.34) is that it relies on the old `/_matrix/client/api/v1/register` endpoint, which no longer exists.

**Comment by MexHigh** [comment]
I know this is an old topic, but I searched for this as my server is using token registration, which is working in Element Web, but not Element Android. When trying to register a new user with Element Android, it uses the registration fallback (which now returns 404). This breaks token registration completely for me.

Has this been considered?

Of course, implementing https://github.com/vector-im/element-android/issues/8192 would also make my concerns go away :D

**Comment by clokep** [comment]
> Has this been considered?

Yes, these APIs are nonstandard and undocumented.
