### ISSUE TITLE
Auto_join don't work in OpenID registration

### ISSUE THREAD

**Issue by Belladona-c0re** [matrix-org/synapse#7719]
It's Possible that autojoin doesn't work in OpenID (Google) create account process?

without OpenID login process the new users join to #myroom:matrix.myserver.corp. 

```
auto_join_rooms:
  - "myroom:matrix.myserver.corp " 
```

This config works. BUT with OpenID register enable. The users don't join the configurated room. 

and yes, autocreate_auto_join_rooms: true is configurated.

Somebody more?

- **Version**:  v1.15.1

- **Install method**:
 pip install

**Comment by clokep** [comment]
@Belladona-c0re Are there any errors or useful logs? It should note whether auto-joins are being skipped, etc.

**Comment by clokep** [comment]
I looked a bit deeper into this and I see no reason it won't work, unless `user_consent_at_registration` is enabled? Do you have that as `true` in your config?

**Comment by clokep** [comment]
Closing due to lack of response. Please reopen if you're still seeing this.
