### ISSUE TITLE
VOIP call (TURN) won't work with Synapse

### ISSUE THREAD

**Issue by okias** [matrix-org/synapse#7726]
### Description
I did configured TURN according https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.md but sadly no connection between calling clients is created.

### Steps to reproduce

- configure & start coturn
- open firewall ports & apply
- restart matrix

```
2020-06-19 17:38:29,787 - twisted - 192 - INFO -  - Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=60488)
```
occasionally is something like that printed into log, which matches TURN UDP IP range

configuration
```
turn_uris: [ "turns:turn._our_server_dot_com:3478?transport=udp" ]
turn_shared_secret: "XXXXXXXXXXXXXXXXXXXXX"
turn_user_lifetime: 86400000
turn_allow_guests: true
```

### Version information

- **our homeserver**:

```
{
    "python_version": "3.6.10",
    "server_version": "1.15.0"
}
```

- **Install method**: pip

- **Platform**: Gentoo

That's generally all info I know, since I tried to debug it, but sadly I'm not much skilled in STUN/TURN etc. + haven't found much debugging approaches ref. https://github.com/matrix-org/synapse/issues/1519

**Comment by clokep** [comment]
I'd suggest asking in #synapse:matrix.org to see if anyone can help debug your STUN/TURN setup.
