### ISSUE TITLE
Push Rules aren't always enabled by default

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/synapse#7743]
As per the spec https://matrix.org/docs/spec/client_server/r0.6.1#put-matrix-client-r0-pushrules-scope-kind-ruleid

> When creating push rules, they MUST be enabled by default.

But in Synapse if you add a push rule, disable it, remove it and re-add a push rule with the same ID then it'll be disabled.

I guess the entry in the `push_rules_enable` table isn't getting cleared out
This will need to be fixed retroactively for already deleted push rules too. 
Looks to also be an opportunity to purge a bunch of stale data from that table for rules which no longer exist.

**Comment by richvdh** [comment]
the impact of this is that when somebody creates a new "keyword" to be notified on, it might not work.

**Comment by richvdh** [comment]
dup #1475
