### ISSUE TITLE
Room creation for guests

### ISSUE THREAD

**Issue by Arjanvanmaren** [matrix-org/synapse#7745]
A quick question: 

At our project we want to create rooms as guests. Is this possible or not?

Thanks

**Comment by clokep** [comment]
The features that guests can perform are detailed in [the specification](https://matrix.org/docs/spec/client_server/r0.6.0#id112).

Looking through that, I don't believe that guests can create rooms.

**Comment by Arjanvanmaren** [comment]
Thanks for the response, this clarifies some things for me :)
