### ISSUE TITLE
Missing event from #irc:matrix.org sent from matrix.org

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#7747]
Someone sent https://riot.im/app/#/room/!BAXLHOFjvDKUeLafmO:matrix.org/$I+LSUXi7Zh1aGD6YycXTxx5x4Xbq1/4k3EN3wxOFWF4 into the room, but my homeserver doesn't seem able to display the event. I would usually chalk it up to federation issues, but both half-shot.uk and matrix.org are federating normally.

I'd expect my homeserver to fetch the event if it was missing, so this is very odd. This is also not a case of history visibility, as it was sent long after I've joined.

**Comment by babolivier** [comment]
In your homeserver's database, can you see a row for the event in `events` and in `event_json`? Also, could you run:

```sql
SELECT internal_metadata FROM event_json WHERE event_id = '$I+LSUXi7Zh1aGD6YycXTxx5x4Xbq1/4k3EN3wxOFWF4';
SELECT * FROM rejections WHERE event_id = '$I+LSUXi7Zh1aGD6YycXTxx5x4Xbq1/4k3EN3wxOFWF4';
```

please?

**Comment by Half-Shot** [comment]
```
halfshotuk_synapse=> SELECT internal_metadata FROM event_json WHERE event_id = '$I+LSUXi7Zh1aGD6YycXTxx5x4Xbq1/4k3EN3wxOFWF4';
               internal_metadata
------------------------------------------------
 {"outlier": false, "stream_ordering": -153547}
(1 row)

halfshotuk_synapse=> SELECT * FROM rejections WHERE event_id = '$I+LSUXi7Zh1aGD6YycXTxx5x4Xbq1/4k3EN3wxOFWF4';
                   event_id                   |   reason   |  last_check
----------------------------------------------+------------+---------------
 $I+LSUXi7Zh1aGD6YycXTxx5x4Xbq1/4k3EN3wxOFWF4 | auth_error | 1585254888132
(1 row)

halfshotuk_synapse=>
```

**Comment by Half-Shot** [comment]
(Logs had rotated so I couldn't get the logs)

**Comment by babolivier** [comment]
Looks like the event has been rejected due to an error with auth. Logs would help us understand the exact reason it didn't pass auth checks, but as @Half-Shot says they have been rotated so we can't get them. I tried joining the room and loading the event, as it's a public room, and succeeding in doing so.

Seeing as there's nothing we can really do from here, I'm going to close this issue. Feel free to open a new one if this bug happens again.

**Comment by richvdh** [comment]
we *could* get some clues about why this event was rejected by looking at the state of the room at the event in question (or rather, HS's server's idea of the state of the room at that event).

I am minded to agree that this is likely to be a timesink which is unlikely to bear fruit, and to ignore it and move on.
