### ISSUE TITLE
matrix.org doesn't appear to believe that federated users have joined some rooms

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#7749]
Known cases:
* Matthew couldn't read me in matrix.to internal after I was invited.
* Ryan couldn't read Michael in room list internal after Michael was invited.
* Matthew can't read anoa in an internal room (presumably after being invited).

Common themes:
* matrix.org users can see EDUs (typing, receipts) but no messages
* the rooms are private
* only matrix.org users seem to be afflicted with the curse

It's possible this is a nasty client regression, however it looks like a server-side issue given the localized impact.

**Comment by babolivier** [comment]
Possibly related: https://github.com/matrix-org/synapse/issues/7744

**Comment by richvdh** [comment]
sounds very much like a dup of #7744. assuming it is for now.
