### ISSUE TITLE
master seems to be leaking memory

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7754]
![image](https://user-images.githubusercontent.com/1389908/86025146-c8953780-ba25-11ea-8ed2-6a0c2169260c.png)

**Comment by richvdh** [comment]
and the client reader seems to be doing something similar?

**Comment by benbz** [comment]
Client reader graphs: https://grafana.matrix.org/d/000000012/synapse?panelId=34&fullscreen&orgId=1&refresh=1m&from=now-30d&to=now&var-datasource=Prometheus&var-bucket_size=$__auto_interval_bucket_size&var-instance=matrix.org&var-job=synapse&var-job=synapse_client_reader&var-index=All

**Comment by richvdh** [comment]
federation_sender seems similarly afflicted.

**Comment by richvdh** [comment]
we believe this has been caused by an upgrade to `rust-jaeger-python-client`, specifically https://github.com/erikjohnston/rust-jaeger-python-client/commit/b80ae8421ed99427535f831b04ed4217676ace5c#diff-b4aea3e418ccdb71239b96952d9cddb6R424.

A memory leak in rust is consistent with the fact that we're not seeing huge GC times despite heap sizes of over 30GB.

Anyway, it's likely this is limited to matrix.org.

**Comment by richvdh** [comment]
have asked erik to look into this

**Comment by erikjohnston** [comment]
I've added some bounds to the various queues here: https://github.com/erikjohnston/rust-jaeger-python-client/commit/944645b7f117593898b01a1578bf35cfbc8159c3 and released a v0.1.14 with the fixes in. We should probably log or add metrics to these queues somehow though

**Comment by erikjohnston** [comment]
Looks like that fixed it
