### ISSUE TITLE
Add a "Running the unit tests" section to INSTALL.md

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7759]
Some people would like to run the unit tests after installing Synapse. Unfortunately, the platform dependencies listed on [INSTALL.md](https://github.com/matrix-org/synapse/blob/develop/INSTALL.md) are intended to set up a SQLite server, whereas if you're installing Synapse with `.[all]`, [as assumed by the unit tests](https://github.com/matrix-org/synapse/blob/2f6afdd8b45c27f30f91873ab3e42cf6ada7045a/synapse/python_dependencies.py#L98), then it will error on requiring native postgres libs.

To handle this, we could add a section to INSTALL.md (or another file) that specifically tells people how to run them from the perspective of a user, and what dependencies are necessary.

**Comment by babolivier** [comment]
We possibly could also couple that with a similar section to run with Postgres fwiw

**Comment by anoadragon453** [comment]
> We possibly could also couple that with a similar section to run with Postgres fwiw

We already link to postgres.md from install.md though?

**Comment by richvdh** [comment]
INSTALL.md is specifically meant to be used for *users*, not packagers. It's already more than complicated enough. :-1: from me to putting it there.

https://github.com/matrix-org/synapse/blob/develop/README.rst#synapse-development already recommends `.[all]`. I'm not convinced we need much more.

**Comment by anoadragon453** [comment]
After talking with the team, we have indeed decided to not inadvertently suggest this to users. If packagers would like to run the unit tests, they should also be aware that they need to package and install all necessary dependencies to do so.

If, for instance, they would not like to include postgres dependencies, it is recommended that they simply avoid running the unit tests that require postgres, as the functionality it tests will not be ran anyways.

We will continue to point people to the developer documentation if they would like to know more about running tests.
