### ISSUE TITLE
Ability to request a configuration test on the commandline

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#7767]
A commandline way of invoking synapse which does nothing except parse the config file, attempts to load modules as specified, but does not bind to any ports or open any database connections, emits a warning of any parameter in a config file is unused, and returns status code 0 if there were no errors or warnings, and status code 1 if there were any.

If you look at the options for high reliability services, we find things like` haproxy -c` or `nginx -t`, use of those flags has then been built into the automation tools that deploy them (eg ansible or systemd) so any change to config files can be checked to ensure that the service will at minimum restart before we shut down the old version and start downtime.

I'd suggest copying one of these existing behaviours in other applications in terms of what causes which status code to be returned, rather than making something up which is a combination of methods, just to make it easy to craft the automation.

I'm aware this is not easy within the current flow of synapses' configuration, but it is an important feature for a reliable application. We are able to currently generate an entire config file from scratch, so we should have enough information about parameters to be able to check for invalid ones in a config file.

**Comment by michaelkaye** [comment]
Also addresses #3513

**Comment by Half-Shot** [comment]
EMS would also like this, because we would like to check the config when the user modifies their authentication settings. It's useful to check the config as it means we can show a particular state to the user rather than a generic failure message.

**Comment by Half-Shot** [comment]
Turns out this pretty much exists as https://github.com/matrix-org/synapse/blob/develop/synapse/config/__main__.py which allows you to invoke `python -m synapse.config read your_key -c config_file.yaml`. You need to specify a key, but if you are just checking that the config is valid you can pass any key.

This probably solves our problem.

**Comment by babolivier** [comment]
So as Half-Shot says, we've had this for some time now, we had just forgotten about it. I've opened https://github.com/matrix-org/synapse/issues/8160 to get this feature documented (and maybe made a bit nicer), so I'm going to close this one.
