### ISSUE TITLE
Improve the PostgreSQL migration guide

### ISSUE THREAD

**Issue by ludwigbald** [matrix-org/synapse#7777]
I set up my homeserver using [this guide](https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi) and now want to do the upgrade to PostgreSQL.

While following the [PostgreSQL migration guide](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md), I ran into the following issues:
- Not having a default unix user called "postgres". I fixed this by running "apt upgrade postgres".
- When registering the database user "synapse_user" in homeserver.yaml, there is no example on how to do that.
- When registering the database user in pg_hba.conf, I did not know whether I had to create that file or whether it already exists somewhere.

... I have to give up for now. I'll expand the issue once I get any further.

**Comment by savyajha** [comment]
The guide does tell you how to do that. The guide provides you with this command: `createuser --pwprompt synapse_user`. This creates the user `synapse_user`. [This link](https://www.postgresql.org/docs/current/auth-pg-hba-conf.html) (linked to by the migration guide) tells you where the `pg_hba.conf` file is located. Quoting from the _first paragraph_ of that link:

> Client authentication is controlled by a configuration file, which traditionally is named pg_hba.conf and is stored in the database cluster's data directory. (HBA stands for host-based authentication.) A default pg_hba.conf file is installed when the data directory is initialized by initdb. It is possible to place the authentication configuration file elsewhere, however; see the hba_file configuration parameter.

Given that you are using Debian (or Ubuntu, for which the instructions should be the same), [this link on the Debian Wiki](https://wiki.debian.org/PostgreSql) tells you where postgres files are located. Again, quoting from the link:

> Configuration files: /etc/postgresql/[version]/[cluster]/
> Binaries: /usr/lib/postgresql/[version]
> Data files: /var/lib/postgresql/[version]/[cluster]

So you will find `pg_hba.conf` in `/etc/postgresql/11/main/`.

**Comment by babolivier** [comment]
Thanks @ludwigbald for your interest in Synapse, and thanks @savyajha for answering to this comment. Given it seems all the necessary details are effectively in the documentation, I'm going to close this issue.
