### ISSUE TITLE
No new messages, FederationSendServlet requests keep increasing

### ISSUE THREAD

**Issue by V02460** [matrix-org/synapse#7778]
### Description

I am running a small 3-person Synapse homeserver on a RPi2 and it got unusable for us since around v1.12. There are several symptoms:

- The last received messages in most rooms in Riot are from around a month ago.
- When running, logs are flooded with these warnings:
  ```
  synapse.http.site: [PUT-XXXX] Error processing request <XForwardedForRequest at 0xXXXXXXXX method='PUT' uri='/_matrix/federation/v1/send/XXXXXXXXXXXXX' clientprot o='HTTP/1.0' site=8010>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
  ```
- Prometheus reveals an ever increasing amount of requests in flight of `PUT FederationSendServlet`. These are rising until the machine starts swapping and grinds to a halt.
  ![requests in flight](https://user-images.githubusercontent.com/1291108/86443601-cbd34080-bd0f-11ea-8e66-c635e703df5d.png)

The HS worked reliably for two years straight (except for a change of SD-card once). Although the HS is quite resource constrained, it doesn't seem to be bottlenecked by CPU (10-20%, all cores in use) or disk IO (see image below), connections to clients are still flaky.

**Disk IO sample**
![synapse_io](https://user-images.githubusercontent.com/1291108/86370715-5b311300-bc80-11ea-9739-269ab10a006e.png)

### Steps to reproduce

- Start the homeserver :shrug: 

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

- **Homeserver**: nasnotfound.de

- **Version**: 1.16.0rc2

- **Install method**: RPM based on the Fedora package

- **Platform**: Raspberry Pi 2, 100/40 MB/s SD-Card, Fedora 32, Postgres, federation_sender as a separate worker

**Comment by richvdh** [comment]
it just sounds like it's overloaded. IIRC a pi2 has four cores so a CPU usage of 20% across all cores could mean that one CPU is almost saturated. Also I don't know what rooms you're in, but I suspect a pi 2 will struggle to handle anything but tiny rooms.

some things to try:
 * see https://github.com/matrix-org/synapse/wiki/Understanding-Synapse-Performance-Issues-Through-Grafana-Graphs
 * check the logs for the incoming `/v1/federation/send` requests and see if you can see any of them taking a long time to complete

We can't really offer custom support beyond this. Perhaps the community in `#synapse:matrix.org` might be able to help you.
