### ISSUE TITLE
deactivating users doesn't work

### ISSUE THREAD

**Issue by ptdel** [matrix-org/synapse#7783]
### Description

trying to deactivate a user via the admin API doesn't work
### Steps to reproduce

- make a curl call to the admin api
```
curl -X POST -H "Authorization: Bearer $TOKEN" -d '{}' "https://localhost:8448/_synapse/admin/v1/deactivate/@user:my.selfhosted.server"
```
returns the following error message
```
{
    "errcode": "M_UNKNOWN",
    "error": "No row found (users)"
}
```
the user is confirmed to exist in the server.  using postgres.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
```
{
    "python_version": "3.8.2",
    "server_version": "1.15.1"
}
```
running on ubuntu

**Comment by babolivier** [comment]
Hey, and thanks for your report. Could you please provide the Synapse logs around the time you made this deactivation attempt?

**Comment by ptman** [comment]
Can you use the v2 modify API to deactivate? https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#create-or-modify-account

**Comment by clokep** [comment]
Closing due to no response. Please reopen (with the requested info) if this is still an issue!
