### ISSUE TITLE
how to config libp2p-proxy with synapse? 

### ISSUE THREAD

**Issue by bitcard** [matrix-org/synapse#7787]
**Description:**

I found this project: https://github.com/matrix-org/libp2p-proxy/.   

Is there a guide to config with synapse? just like use nginx reverse proxy?  

how to set Riot client home server url? thanks.

**Comment by Half-Shot** [comment]
Hey there! Using p2p proxy isn't supported on Synapse, and as far as I'm aware that project didn't get very far.

The best way to use Matrix in a peer to peer context is to use Dendrite, by following it's [p2p.md](https://github.com/matrix-org/dendrite/blob/master/docs/p2p.md) guide or just using p2p.riot.im which will start a homeserver and connect it to Riot within your browser.

**Comment by bitcard** [comment]
> Hey there! Using p2p proxy isn't supported on Synapse, and as far as I'm aware that project didn't get very far.
> 
> The best way to use Matrix in a peer to peer context is to use Dendrite, by following it's [p2p.md](https://github.com/matrix-org/dendrite/blob/master/docs/p2p.md) guide or just using https://p2p.riot.im which will start a homeserver and connect it to Riot within your browser.

I got it, thanks for your reply.
