### ISSUE TITLE
Concurrent event linearizer doesn't work when using event creator.

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#7792]
We have a linearizer that (tries) to stop more than 5 events being created and persisted concurrently for a given room. This is to prevent the failure mode where if events are written at a greater rate than they can be persisted the forward extremities count balloons, resulting in further degradation in performance.

When running with event creators the limit is enforced on the individual event creators. However, the persist event replication request to the event writer process can time out, resulting in the event creator thinking that the event is no longer being processed even though it still is being processed by the writer.

We can't simply move the linearizer to the event writer process as it needs to be applied before we select the prev events.

**Comment by richvdh** [comment]
is this the same as #7086?

**Comment by erikjohnston** [comment]
Oh, maybe. We do do this correctly for non-worker mode

**Comment by richvdh** [comment]
also related: #7682

**Comment by richvdh** [comment]
Hopefully fixed by #8412? leaving open for now pending confirmation

**Comment by erikjohnston** [comment]
Yes, I'm hoping it'll fix it.
