### ISSUE TITLE
Config reload doesn't reload ratelimit config

### ISSUE THREAD

**Issue by Bubu** [matrix-org/synapse#7794]
### Description

Reloading synapse config doesn't seem to reload the ratelimit config

### Steps to reproduce

- update `rc_message` config in homeserver.yaml
- `kill -HUP $synapse_pid`
- send messages and still run into the same ratelimiting

The following was printed in synapse log which indicates that the config was indeed reloaded
```
Jul 06 20:57:34 bubu systemd[1]: Reloading Synapse Matrix homeserver.
Jul 06 20:57:34 bubu systemd[1]: Reloaded Synapse Matrix homeserver.
```
After actually restarting synapse afterwards the new ratelimits did apply

### Version information

- **Homeserver**: matrix.bubu1.eu

- **Version**: 1.16.0rc2

- **Install method**:archlinux package built for latest rc

- **Platform**: Archlinux

**Comment by richvdh** [comment]
`kill -HUP` does not reload the config.
