### ISSUE TITLE
Room Member Count Increments on Nickname change

### ISSUE THREAD

**Issue by NHAS** [matrix-org/synapse#7806]
### Description

When a user changes their nickname the 'joined_members' number increments, but the number of people in a room is the same. 

### Steps to reproduce

- Create room
- Change nickname
- In the 'explore rooms' dialog view the number of room members is now '2' rather than one

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
Below is an image of the room, with one nick name change. 
![image](https://user-images.githubusercontent.com/6820641/86990864-bbc8ce80-c1f1-11ea-8107-69f2a213eb2f.png)

API response of the above room with the 'joined_members' number incorrect due to nick change. 
```
 {
            "room_id": "!drsvVrFHHwfrRNQAbs:matrix.ais",
            "name": "dfghjkl",
             "canonical_alias": null,
             "joined_members": 2,
             "joined_local_members": 1,
             "version": "5",
             "creator": "@gbest:matrix.ais",
             "encryption": "m.megolm.v1.aes-sha2",
             "federatable": true,
             "public": false,
             "join_rules": "invite",
             "guest_access": "can_join",
             "history_visibility": "shared",
             "state_events": 9
 },
```
### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.16.0 (However has been present for some time)

- **Install method**: Package manager
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Ubuntu 18.04LTS
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

This is running in a VM with postgres, however this shouldnt be the cause of this issue.

**Comment by richvdh** [comment]
dup #1294
