### ISSUE TITLE
ERROR: Invalid value for encryption_enabled_by_default_for_room_type

### ISSUE THREAD

**Issue by rodolpheh** [matrix-org/synapse#7821]
### Description

When updating from 1.16.0 to 1.16.1, I stumbled upon an issue where my server wouldn't restart. The logs displays the following error :

```
ERROR: Invalid value for encryption_enabled_by_default_for_room_type
```

I previously set up `encryption_enabled_by_default` to `off` in my `homeserver.yaml`. Since it should be off by default, I just commented the line and the server started without any issue.

### Steps to reproduce

- set the parameter `encryption_enabled_by_default_for_room_type` to `off` in your `homeserver.yaml`
- recreate the container
- watch the logs

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: lunai.re

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.16.1

- **Install method**: docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: docker container in an Arch Linux set up
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by babolivier** [comment]
Hey @rodolpheh, and thanks for your report!

It looks like we weren't aware, when implementing this feature, that PyYAML (the parser we use for the configuration file) translates the string "off" into the boolean value `False`.

**Comment by babolivier** [comment]
Will be fixed in https://github.com/matrix-org/synapse/pull/7822
