### ISSUE TITLE
Remove -py3 docker tag

### ISSUE THREAD

**Issue by maquis196** [matrix-org/synapse#7825]
**Description:**

Basically, since master is running off python3 by default, the addition of a -py3 docker tag seems superfluous. Not sure what to do if anyone is using them, I guess a deprecation warning in the release notes? 

What does everyone think?

**Comment by richvdh** [comment]
we will do one more release with the -py3 tag, and announce that the -py3 tagged image will be removed.

We will then remove the -py3 tagged image a bit later. (Doesn't necessarily need to happen at the same time as a release).

**Comment by richvdh** [comment]
`latest-py3` image now removed from dockerhub.
