### ISSUE TITLE
[Accessibility?/UX] Default-generated user icons smehow feel unpleasant to look at

### ISSUE THREAD

**Issue by ell1e** [matrix-org/synapse#7826]
### Description

I don't know if it's just me, but I find the default-generated user icons are straining/painful to look at. I'm not a scientist so I am not sure why exactly this is, but I have identified a way to improve it:

*Current generated icon:*

![strain](https://user-images.githubusercontent.com/64124388/87298662-12881e00-c4fa-11ea-84f7-5047ac6146e0.png)

*Manual edit of mine that somehow feels way better for me (I just made the stripes 6px wide, from previously 1px):*

![strain1](https://user-images.githubusercontent.com/64124388/87299339-57f91b00-c4fb-11ea-8bbc-5ecd38a349b9.png)

I have no idea if it's just me, or why exactly these larger stripes are better. But at the chance that I'm not alone with this, I am hereby suggesting to collect more feedback from others and consider changing it because I find the current icons really very unpleasant to look at. So if I'm not alone, it definitely sounds like worth changing.

(Sorry if this is the wrong repo, I made a wild guess where these icons possibly are generated)

### Steps to reproduce

- 1. Open up riot and join any channel
- 2. Observe the unchanged default icons of other users or channels where a custom one wasn't set

### Version information

**Homeserver:** matrix.org

**Comment by auscompgeek** [comment]
Synapse doesn't generate default avatars.

**Comment by ell1e** [comment]
Ah ok, good to know! Where are they generated then? I'd be happy to recreate this issue in the correct place, I apologize for the ticket spam

**Comment by babolivier** [comment]
Heya, the right repo would be https://github.com/vector-im/riot-web (Riot's repo for desktop/web apps) :)
I'm going to close this issue now.
