### ISSUE TITLE
in-memory federation transaction transmission queues build up indefinitely for offline servers

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7828]
when a server is offline, any events that we would have sent to it stack up in memory indefinitely.

See, for example, this graph for matrix.org:

![image](https://user-images.githubusercontent.com/1389908/87312238-30647b80-c518-11ea-848f-5d10bd9bbc1d.png)

Apart from the memory usage concerns, this means that if a server goes offline for 1000 events, then when it comes back we will try to send it all those 1000 events in turn, rather than just sending it the most recent ones in a room.

**Comment by richvdh** [comment]
I suspect this was introduced way back in https://github.com/matrix-org/synapse/pull/2064.

I think we just need to clear the in-memory queues when handling a blacklisted server in `_transaction_transmission_loop`.

**Comment by richvdh** [comment]
I'm chucking this into the todo list as it appears an obvious precursor to #2528.

**Comment by deepbluev7** [comment]
This may be the reason for #7176 since it was reported shortly after #2064 was merged. For reference here's my federation_sender gc times graph:

![grafik](https://user-images.githubusercontent.com/16312324/87453304-d46e2580-c5f1-11ea-8c32-42e7335909e4.png)

**Comment by tulir** [comment]
This graph looks like the queue build-up was happening without causing any GC leak:

![image](https://user-images.githubusercontent.com/4224639/87454298-73078000-c60c-11ea-870e-7b221566983d.png)

**Comment by reivilibre** [comment]
Will land this in a less aggressive way, but will make more aggressive when #2528 is solved because it will be safe to do so.
