### ISSUE TITLE
critical error "write to closed file" in logs

### ISSUE THREAD

**Issue by Valodim** [matrix-org/synapse#7837]
### Description

From my logs:

```
2020-07-13 21:51:41,295 - twisted - 192 - CRITICAL - - Unhandled error in Deferred:
2020-07-13 21:51:41,438 - twisted - 192 - CRITICAL - - 
twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure builtins.ValueError: write to closed file>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
```

### Steps to reproduce

No idea. This happens multiple times a day on my homeserver, so I have quite a bunch of CRITICAL errors in my logs at all times. I can't see any pattern, and (on log level WARN) there are no log entries that come up consistently before or after this one. Sometimes this comes up twice consecutively. I only report this because it says CRITICAL.

Looking back at my logs, this has been coming up for quite a while. It doesn't seem to crash synapse or have any obvious adverse effects. (That said, my synapse does become unresponsive and restart several times a day for reasons I am unable to debug, with moderate time investment)

### Version information

- **Homeserver**: matrix.stratum0.org
- **Version**: 1.15.2, but this comes up in my logs as early as February so it's not new
- **Install method**: apt
- **Platform**: Debian

**Comment by anoadragon453** [comment]
Hmm, I'm afraid there's not a lot for us to go on here. If it's happening consistently (and please check whether this is still happening on v1.17.0) could you try bumping your log level to DEBUG for a bit and see if any clues arise?

**Comment by richvdh** [comment]
... or just INFO, as a starting point.

**Comment by richvdh** [comment]
(I'm a bit surprised it's logging exceptions at CRITICAL but not logging the stack trace?)

**Comment by clokep** [comment]
Closing due to lack of response. If you have a chance to look at this again please reply and we can reopen this.
