### ISSUE TITLE
Obvious indication for bots

### ISSUE THREAD

**Issue by TheEvilSkeleton** [matrix-org/synapse#7852]
**Description:**

Discord has an obvious way to indicate if a "user" is a bot or an actual user: ![image](https://user-images.githubusercontent.com/50847364/87504595-f2a94500-c634-11ea-80f2-1c28b139e9cc.png)

I would suggest implementing this feature as it will help everyone distinguish users and bots

**Comment by erikjohnston** [comment]
This would be great to be able to support, but requires changes to the matrix spec. I think there are a couple of (ancient) issues for tracking this at: https://github.com/matrix-org/matrix-doc/issues/425 and https://github.com/matrix-org/matrix-doc/issues/431

Closing this as there's not much we can do in Synapse without support of the spec
