### ISSUE TITLE
keyword patterns in push rules apply against apostrophised words

### ISSUE THREAD

**Issue by Torwegia** [matrix-org/synapse#7862]
### Description

Currently a regex is used to search for display and usernames to determine whether or not to notify the user that they were mentioned in a message. This regex however incorrectly will determine that usernames/displaynames are in things like urls or words containing appostrophes. This leads to cases where the notification system is unable to be used. 

The regex used to determine word boundaries is missing some cases where it should not be breaking. The regex in question can be [found here](
https://github.com/matrix-org/synapse/blob/35450519dee869e5641cff94ed35acd3bdaa8a42/synapse/push/push_rule_evaluator.py#L261).  The logic here breaks words on things like apostrophes meaning some words are incorrectly broken up.

The core of the issue from what I can tell is that \W causes the word boundary logic to be overly eager to split up words. Commonly used things like urls are considered to be many words by this logic.

### Steps to reproduce

- Use _re_word_boundary to wrap the string "Angelo"
- Compile resulting regex with flags=re.IGNORECASE
- Using the compiled regex search through a string like "D'Angelo rode the bus home yesterday."
- Observe a match.

In this example Angelo should not be matched. 

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

- **Homeserver**:

A modular.im hosted server. 

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
Versions:
Synapse version:1.17.0
Python version:3.7.8

- **Install method**:
Irrelevant

- **Platform**:
Irrelevant

**Comment by clokep** [comment]
Thanks for the report. Do you have any suggestions of how to improve this? Figuring out what is and isn't a word boundary isn't a trivial task unfortunately.

**Comment by richvdh** [comment]
I've also got to ask: where is this code used? In other words, what user-visible symptoms does this cause?

**Comment by Torwegia** [comment]
@richvdh This is used to determine if a username or display name is in a body of text. The user impact is mostly erratic notification behavior. I would imagine the worst cause would be a user with the username/display name of matrix being in a room with many people on the matrix.org home server.

@clokep I am unsure. Perhaps it can be reworked to handle contractions. I guess with unicode \W is much more than just [^0-9a-zA-F_].

**Comment by richvdh** [comment]
@Torwegia would you mind updating the issue summary so that it describes the symptoms rather than the cause? it'll help us establish how to prioritise it.

User mentions are due for a rework anyway; they are known to be brittle for many reasons. See also https://github.com/matrix-org/synapse/issues/2956.

**Comment by Torwegia** [comment]
Certainly I should have some time tomorrow!

Thank you both for your time!
