### ISSUE TITLE
Communities are unusable after the admins leave

### ISSUE THREAD

**Issue by TheEvilSkeleton** [matrix-org/synapse#7863]
*Issue was first suggested in https://github.com/vector-im/riot-web/issues/14518.*

---

**Is your suggestion related to a problem? Please describe.**

Yes. We have created a community, and the admin left the community, thus making it unusable. We were forced to create another community because of that.

**Describe the solution you'd like**

I would suggest making the community automatically delete once a community does not have an admin anymore.

**Describe alternatives you've considered**

If the above suggestion does get rejected, I would suggest having an issue template for those that want to delete non-admin communities

**Additional context**

The creator (admin) of the community and I got into a little conflict, in which made him leave the community, thus making it a non-admin community. We sorted everything out, but then realized that there were unfortunately no admins. We were then forced to create another community since the one we wanted was taken (and useless).

The adminless community is called `+reverseeagle:privacytools.io` and the new community is called `+reverse_eagle:privacytools.io`. If it is possible, we would appreciate if you can delete the old community (and also implement a way to delete communities), so we can use the old name.

**Comment by erikjohnston** [comment]
Would it suit you needs if admins could rejoin the community? I'm a bit hesitant about auto-deleting communities as that feels like it could be quite surprising and confusing. 

> The adminless community is called `+reverseeagle:privacytools.io` and the new community is called `+reverse_eagle:privacytools.io`. If it is possible, we would appreciate if you can delete the old community (and also implement a way to delete communities), so we can use the old name.

You'd need to talk to whoever runs privacytools.io homeserver

**Comment by TheEvilSkeleton** [comment]
> Would it suit you needs if admins could rejoin the community? I'm a bit hesitant about auto-deleting communities as that feels like it could be quite surprising and confusing.

That is already possible, only problem is that they won't be an admin anymore. If I am an admin of a community and I decide to leave, I won't become an admin anymore after I join, thus making it adminless.

>> The adminless community is called +reverseeagle:privacytools.io and the new community is called +reverse_eagle:privacytools.io. If it is possible, we would appreciate if you can delete the old community (and also implement a way to delete communities), so we can use the old name.
>
> You'd need to talk to whoever runs privacytools.io homeserver

Doing it right now

**Comment by erikjohnston** [comment]
> > Would it suit you needs if admins could rejoin the community? I'm a bit hesitant about auto-deleting communities as that feels like it could be quite surprising and confusing.
> 
> That is already possible, only problem is that they won't be an admin anymore. If I am an admin of a community and I decide to leave, I won't become an admin anymore after I join, thus making it adminless.

Ah, so maybe we should remember if they were an admin then

**Comment by TheEvilSkeleton** [comment]
That works

**Comment by n-himitsu** [comment]
> > > Would it suit you needs if admins could rejoin the community? I'm a bit hesitant about auto-deleting communities as that feels like it could be quite surprising and confusing.
> > 
> > 
> > That is already possible, only problem is that they won't be an admin anymore. If I am an admin of a community and I decide to leave, I won't become an admin anymore after I join, thus making it adminless.
> 
> Ah, so maybe we should remember if they were an admin then

There would also need to be behavior implemented for deleted accounts. Perhaps disallow account deletion if the account holder is the only admin of a community.

**Comment by anoadragon453** [comment]
I agree that groups should probably follow the same rules as rooms for consistency's sake, which do "remember" admins after they leave and rejoin.

> There would also need to be behavior implemented for deleted accounts. Perhaps disallow account deletion if the account holder is the only admin of a community.

This is an important edge case to consider, though I'm not a fan of prevent account deactivation for any reason, especially for GDPR reasons. Perhaps in this case the ability for a server admin to delete a group would be the way to go.

**Comment by aaronraimist** [comment]
Server admins can delete groups https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/delete_group.md

**Comment by clokep** [comment]
Maybe adding an admin API to set the admin of a group would be a reasonable way forward?

**Comment by anoadragon453** [comment]
@clokep That is true as well, though it's also worth noting how much time we want to invest into this before groups fundamentally change in the likely near future ala https://github.com/matrix-org/matrix-doc/pull/1772.

In that model, groups would be represented as rooms, and thus the admin of a group would need to be determined by power levels in a room, rather than a server administrator.

**Comment by jellykells** [comment]
Possibly worth noting that a server admin can also manually give a user admin permissions for a group

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
