### ISSUE TITLE
guest user registration fails with 'Unable to find a suitable guest user ID'

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7865]
This is happening on matrix.org, presumably as a result of us load-balancing registration across multiple client_reader workers; the logic for assigning guest user IDs assumes it will not be fighting with other processes.

**Comment by richvdh** [comment]
Possible solutions:

 * We have 12 client readers; hence, allocate user ids `12n` on client_reader 1, `12n+1` on client_reader 2, `12n+2` on client_reader 3, etc
 * use a postgres sequence doodah to allocate user ids

**Comment by erikjohnston** [comment]
The client readers don't know how many other client readers there are, so I'm not a huge fan of the former solution (wherever possible I think its good to not have to have workers know about each other, makes it easier to deploy more autmogically).

I'd vote a postgres sequence, you might be able to use `MultiWriterIdGenerator` which is backed by a postgres sequence? That way you could use a regular IdGen for SQLite, but I don't know if its easy to hook that in.

**Comment by richvdh** [comment]
Fixed by #7866
