### ISSUE TITLE
Ubuntu Eoan is now EOL

### ISSUE THREAD

**Issue by jryans** [matrix-org/synapse#7883]
According to the [Ubuntu mailing list](https://lists.ubuntu.com/archives/ubuntu-announce/2020-July/000257.html), Ubuntu Eoan is now EOL (as of 2020-07-17), so we should remove from build scripts for future releases.

**Comment by richvdh** [comment]
thanks for spotting that. I feel like I have to add or remove an ubuntu distro from the list every second week.

**Comment by gary-kim** [comment]
May I open a PR for this?

**Comment by clokep** [comment]
@gary-kim Please do! You can join #synapse-dev:matrix.org if you have any questions!
