### ISSUE TITLE
/_matrix/federation/v1/state_ids/ is heavy

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7893]
in a large room with long auth chains, each request to /_matrix/federation/v1/state_ids/ takes a lot of database time. The requesting servers tend to time out the requests, and then retry, compounding the problem.

**Comment by richvdh** [comment]
see https://github.com/matrix-org/synapse/issues/6597: it's not obvious that this data is even useful.

**Comment by anoadragon453** [comment]
It seems now that we do want to keep this behaviour, but optimize the performance of it as per https://github.com/matrix-org/synapse/issues/6597#issuecomment-660611800

**Comment by anoadragon453** [comment]
@richvdh Do you think it worth keeping this issue open if we have https://github.com/matrix-org/synapse/issues/6597?

**Comment by richvdh** [comment]
sorry, yes. This issue is about the database/CPU time taken on the server side; I've actually got a couple of patches which I need to PR to improve it.

#6597 is about handling the response on the client side.

**Comment by richvdh** [comment]
Hopefully this is improved by #7931 and #7930.

**Comment by richvdh** [comment]
this is still a problem; matrix.org's federation readers are still pinning the CPU and hammering the database regularly.

**Comment by richvdh** [comment]
This is exacerbated by rooms which have complex graphs. A single back-pagination request in `!YynUnYHpqlHuoTAjsp:matrix.org` on matrix.org introduced 51 new backwards-extremities, each of which required a state_ids request to kde.org, each of which takes 3 minutes of database time.

**Comment by richvdh** [comment]
(the above also highlights the fact that state_ids is returning way too much data: there will be a lot of duplication in the auth chains of those 51 backwards-extremities, which suggests we should spec an updated state_ids that returns less data.)

**Comment by richvdh** [comment]
> we should spec an updated state_ids that returns less data

or follow construct's example, and send the request with an `auth_chain_ids=0` query param, to indicate we don't need any of the auth chain ids at all.

**Comment by richvdh** [comment]
@erikjohnston also suggests adding a cache to the middle of `get_auth_chain_ids` and caching intermediate results.

**Comment by richvdh** [comment]
#9482 might help with this. I still feel like a lot of the problem here is that we tend to return a huge amount of redundant information, since the requesting server will have most of the `auth_events` already.

**Comment by callahad** [comment]
The [comment above](#issuecomment-661813582) stated:

> This issue is about the database/CPU time taken on the server side

![Screenshot of CPU utilization on matrix.org](https://user-images.githubusercontent.com/24193/111808653-1ca1be00-88cc-11eb-9e62-4a05a376dcdc.png)

#9482 improved CPU and DB utilization by an order of magnitude, and is shipping in 1.30.0rc1. Closing as resolved. 🎉
