### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [matrix-org/synapse#7894]
### Description

Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

### Steps to reproduce

```
./contrib/experiments/test_messaging.py:78: DeprecationWarning: invalid escape sequence \S
  m = re.match("^join (\S+)$", line)
./contrib/experiments/test_messaging.py:87: DeprecationWarning: invalid escape sequence \S
  m = re.match("^invite (\S+) (\S+)$", line)
./contrib/experiments/test_messaging.py:96: DeprecationWarning: invalid escape sequence \S
  m = re.match("^send (\S+) (.*)$", line)
./contrib/experiments/test_messaging.py:105: DeprecationWarning: invalid escape sequence \S
  m = re.match("^backfill (\S+)$", line)
```

**Comment by clokep** [comment]
Is there a particular way you've gone about finding these deprecation warnings? (Running the tests with specific flags or...?)

**Comment by tirkarthi** [comment]
Running the above command in project root should print the warnings.

**Comment by anoadragon453** [comment]
In my case (with python environments and tox directories hanging about), I needed to use the following slightly modified command:

```
find . -path ./env -prune -o -path ./.tox -prune -o -path ./build -prune -o -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
```

but regardless, this looks useful to run on the regular, and thank you for the PR cleaning it up.

I'm interested to know whether people think this should be part of CI?

**Comment by clokep** [comment]
> I'm interested to know whether people think this should be part of CI?

That was my thought. :) Might be worth filing an issue about.

**Comment by anoadragon453** [comment]
@clokep https://github.com/matrix-org/synapse/issues/7909
