### ISSUE TITLE
time.clock has been deprecated and removed in python 3.8 in favor of time.perf_counter/process_time

### ISSUE THREAD

**Issue by tirkarthi** [matrix-org/synapse#7896]
### Description

time.clock has been deprecated and removed in python 3.8 in favor of time.perf_counter/process_time . Reference : https://github.com/python/cpython/pull/13270

### Steps to reproduce

```
synapse/logging/utils.py
88:        start = time.clock()
95:            end = time.clock()
```

**Comment by anoadragon453** [comment]
As mentioned in the attached PR (thanks!) it seems as if the method that calls `time.clock` in Synapse is no longer used.
