### ISSUE TITLE
New User has Invites and a History

### ISSUE THREAD

**Issue by microsoft-sucks** [matrix-org/synapse#7898]
Creating a new user on matrix.org (with a name which was probably already used) shows in Element.io invites and a history of rooms.  
This is strange and very **confusing**. This **data should not be preserved** once a user deletes their account.

![Screenshot_2020-07-18 Element  5](https://user-images.githubusercontent.com/67187266/87859923-92fab480-c928-11ea-8f18-9b4eb415dac5.png)

**Comment by anoadragon453** [comment]
The invite spam was part of a recent spam wave. Some of those accounts were deactivated which would make the invite rooms appear under Historical.

The question here is whether we want to support the ability to send membership events about users that don't exist yet.

**Comment by microsoft-sucks** [comment]
For a new user it is very confusing and not understandable how there can be any kind of history. You would think matrix could leak data.

Also, **why are there devices shown?** The left one could be the current or an older session, but I did _not_ log this account into Android/IOS.
![Screenshot_2020-07-22 Element](https://user-images.githubusercontent.com/67187266/88194805-c2face00-cc2e-11ea-8d10-1dd262f06a6d.png)

**Comment by anoadragon453** [comment]
@microsoft-sucks those are *examples* of other devices you might have that could be used to verify this session, not your actual other devices. However this shows that that page can be mis-interpreted and perhaps could be redesigned in a way that makes things clearer - like showing a list of your other devices for instance.

That's a problem with [Element Web](https://github.com/vector-im/riot-web/) though, and I suggest you made a UI/UX issue about it there.

**Comment by richvdh** [comment]
this sounds like expected behaviour for now at least. @anoadragon453 suggest filing a new bug for "whether we want to support the ability to send membership events about users that don't exist yet."

**Comment by anoadragon453** [comment]
@richvdh the bug in question: https://github.com/matrix-org/synapse/issues/7937
