### ISSUE TITLE
Allow server admins to join too complex rooms

### ISSUE THREAD

**Issue by lugino-emeritus** [matrix-org/synapse#7901]
It would be great to have an option that allows synapse admins joining all remote rooms, independent of their complexity.

A non-admin user can ask an admin to join a specific, too complex room. After that the non-admin user can join the room (since it is local now). The admin may leave the room again.

It has the advantage that server admins always have an overview over large rooms.

**Comment by dklimpel** [comment]
Have a look at room admin API.
https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#list-room-api
There you can get all list of all rooms of your server. And you can see the complexity (state events).

**Comment by lugino-emeritus** [comment]
Yes, but this does not allow a server admin to join a too complex room. So this api is not helpfull.
The only way to join a complex room is to disable the complextiy checking in the config file, restart synapse, join room, enable complexity checking, restart synapse. And I do not want to allow all users to join all (large) rooms. This will overload my server.

**Comment by ptman** [comment]
Wouldn't a large room cause performance problems regardless if it was an admin joining it? The limit is there for performance reasons, IIRC.

**Comment by anoadragon453** [comment]
@ptman yes, though I could see the usecase for an admin wanting to allow specific large rooms (a community announcements room for instance) on the server, while simultaneously disallowing users from joining Matrix HQ.
