### ISSUE TITLE
Add Python deprecation checking to CI

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7909]
https://github.com/matrix-org/synapse/pull/7895 mentioned that we can use the following (or similar) command to check for Python deprecation warnings which may sneak up on us.

```
find . -path ./env -prune -o -path ./.tox -prune -o -path ./build -prune -o -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
```

However, I'm wary of the usefulness of this if the only thing it caught was an invalid escape sequence, which flake8 has been shown to catch as well (related: https://github.com/matrix-org/synapse/issues/7910).

**Comment by tirkarthi** [comment]
flake8 already supports this https://www.flake8rules.com/rules/W605.html

**Comment by tirkarthi** [comment]
```
flake8 contrib
contrib/experiments/test_messaging.py:78:34: W605 invalid escape sequence '\S'
contrib/experiments/test_messaging.py:87:36: W605 invalid escape sequence '\S'
contrib/experiments/test_messaging.py:87:42: W605 invalid escape sequence '\S'
contrib/experiments/test_messaging.py:96:34: W605 invalid escape sequence '\S'
contrib/experiments/test_messaging.py:105:38: W605 invalid escape sequence '\S'
```

**Comment by anoadragon453** [comment]
Indeed. If flake8 already handles deprecation warnings, then https://github.com/matrix-org/synapse/issues/7910 is probably the way to go here.

**Comment by anoadragon453** [comment]
Closing in favour of #7910.
