### ISSUE TITLE
User no longer able to chat if user level was set below 0 and back to 0

### ISSUE THREAD

**Issue by rombeller** [matrix-org/synapse#7940]
**THIS IS NOT A SUPPORT CHANNEL!**
**IF YOU HAVE SUPPORT QUESTIONS ABOUT RUNNING OR CONFIGURING YOUR OWN HOME SERVER**,
please ask in **#synapse:matrix.org** (using a matrix.org account if necessary)

### Description

User no longer able to chat if user level was set below 0 and back to 0
### Steps to reproduce
-set userlevel to -1
-set userlevel to 0
-get NaN

edit: sometimes it appears again as deault, next reaload as -1 again
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information
Current
<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:
both
If not matrix.org:

<!--
 What version of Synapse is running?
current
You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

server_version | "1.17.0"

python_version | "3.7.3"
-- | --



-- | --



(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
server_version | "1.17.0"

python_version | "3.7.3"
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
i don't know. i'm just a user who writes this report. because the admin said if you want the bot back write a bug report
- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by anoadragon453** [comment]
I'm afraid I'm unable to reproduce your issue with the steps provided with either a local user on a homeserver or a remote user on another homeserver. Both homeservers I tested are running v1.17.0.

Do you have any more detailed steps for reproducing the issue, or perhaps some server logs that may give a hint as to what is going wrong?

**Comment by rombeller** [comment]
I'll relay it to the admin of the server, the user muted was a bot maybe this helps.

**Comment by rombeller** [comment]
it is now working again but here some more informations about the steps the admin took.

> crunklord420
I didn't set it to 0
I deleted the number assuming it would be set to 0

crunklord420 changed the power level of @glowy:glowers.club from Custom (-1) to Default.
crunklord420
oh look maybe now that I refreshed my clinet it shows it
maybe it was a clientside issue

**Comment by anoadragon453** [comment]
Mm, yes, it looks like removing the number in [Element Web](https://github.com/vector-im/riot-web/issues/) and hitting the checkmark sends:

```
users: {
  "@bla:example.com": null
},
...
```

to the server. Synapse rejects this with a HTTP 400. This seems like a client side issue indeed. I recommend you raise it on the linked bugtracker if an issue doesn't already exist.
