### ISSUE TITLE
Failed to make_join via any server

### ISSUE THREAD

**Issue by sl5net** [matrix-org/synapse#7946]
i was invidet to 24 rooms ( @ MYNAME :tchncs.de )
and when i try accepting:

Failed to make_join via any server

i tried this from android. same errors.
i tried this from linux mint. same errors.

i have everywhere the newest app runnig

![image](https://user-images.githubusercontent.com/5634759/88396826-59f88f00-cdc3-11ea-819e-cce6737fe9ff.png)

**Comment by sl5net** [comment]
maybe related to: https://github.com/vector-im/riot-web/issues/14093

**Comment by richvdh** [comment]
apparently these are from `netzgemeinde.eu` which has been widely reported to be rejecting join requests.

to investigate further we'll need server logs from both sides.
