### ISSUE TITLE
get_relations_for_event and get_aggregation_groups_for_event caches are very low hit rate on matrix.org

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7957]
We seem to have 12 client reader workers on matrix.org atm, and each of them is doing ~10-30Hz of get_relations traffic (triggered by calls to /messages). However, we have a cache hit rate of 10-40%, and the cache size is only 1000 items(!).  Surely we should have a much bigger cache size, to avoid hammering the DB with requests to look for aggregations.

<img width="1848" alt="Screenshot 2020-07-25 at 19 19 44" src="https://user-images.githubusercontent.com/1294269/88463644-0a41c280-ceac-11ea-9100-dd0d8db7aae2.png">

**Comment by anoadragon453** [comment]
The cache eviction rate almost matching the request rate is also quite telling:

![image](https://user-images.githubusercontent.com/1342360/88594460-1fa81f80-d059-11ea-91b8-189b3924c7db.png)

**Comment by erikjohnston** [comment]
This is done, but doesn't seem to have made much of a difference.
