### ISSUE TITLE
Implement updated push rules

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7960]
https://docs.google.com/document/d/1pjYrGokTQGDZQLtagZvG4dY67RsjUdFDfpOzSiWtOBg/edit#heading=h.kdajkcd7g26w documents a number of minor changes we'd like to make to the default push rules. The task for this issue is to implement them (on a Synapse branch, or behind a feature flag) so that we can try them out in practice.

**Comment by babolivier** [comment]
I've got a branch with the new push rules, and a way to enable them only for some users (by inserting rows in a temporary database table): https://github.com/matrix-org/synapse/compare/babolivier/new_push_rules

I assume next step is to deploy that somewhere and trial the new rules.
