### ISSUE TITLE
Debian package not compatible with element app

### ISSUE THREAD

**Issue by benhartwich** [matrix-org/synapse#7972]
**THIS IS NOT A SUPPORT CHANNEL!**
**IF YOU HAVE SUPPORT QUESTIONS ABOUT RUNNING OR CONFIGURING YOUR OWN HOME SERVER**,
please ask in **#synapse:matrix.org** (using a matrix.org account if necessary)

### Description

Element (former riot) is not longer compatible with the debian 10 package of matrix synapse. 

### Steps to reproduce

- install matrix synapse on debian 10
- try to login on element (former riot) at android 10

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**: package manager
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian 10 / vm
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by anoadragon453** [comment]
If you are using the `matrix-synapse` package from stable (buster), then it will be woefully out of date.

Please use the package from Debian testing (sid) or our up-to-date package repo: https://github.com/matrix-org/synapse/blob/develop/INSTALL.md#debianubuntu

**Comment by benhartwich** [comment]
Thanks, upgrading to matrix-synapse-py3 worked and element is usable!
