### ISSUE TITLE
Nginx Reverse Proxy Server Setup

### ISSUE THREAD

**Issue by mkriegl** [matrix-org/synapse#7974]
Can anyone assist in setting up the reverse proxy in combination with synapse while both running on different machines. I tried to follow the setup for localhost by inserting the ip adresses, but I do not manage to access synapse: right now I get a 502
My current setup:
- 192.168.188.xxx: synapse
- 192.168.188.yyy: reverse proxy
reverse proxy nginx:
`
server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name matrix.myserver.com;
      location / {
        ssi on;
        proxy_pass http://192.168.188.xxx:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
    ssl_certificate /etc/letsencrypt/live/www.myserver.com-0002/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.myserver.com-0002/privkey.pem; # managed by Certbot
}
server {
      listen 8448 ssl default_server;
      listen [::]:8448 ssl default_server;
      server_name matrix.myserver.com;
      location / {
        ssi on;
        proxy_pass http://192.168.188.xxx:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
    ssl_certificate /etc/letsencrypt/live/www.myserver.com-0002/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/www.myserver.com-0002/privkey.pem; #  managed by Certbot
}
`

homeserver.yaml:
`server_name: "matrix.myserver.com"
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['192.168.188.yyy']

    resources:
      - names: [client, federation]
        compress: false`

Router Portforwarding for 443 and 8448 is already to 192.168.188.yyy

**Comment by clokep** [comment]
There are some docs for [setting up a reverse proxy](https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md). Please use #synapse:matrix.org for additional support.
