### ISSUE TITLE
psycopg2cffi compatibility: wrap `psycopg2.extras` import in a try block 

### ISSUE THREAD

**Issue by dzamo** [matrix-org/synapse#7985]
To run Synapse with pg under PyPy I've had to make use of psycopg2cffi and it's compat mechanism as a substitute for psycopg2.  It works but psycopg2cffi does not include `psycopg2.extras`.  To achieve compatibility, please consider wrapping the one use of `psycopg2.extras` (in synapse/storage/database.py) in a try block with a fallback:
```
try:
  from psycopg.extras import execute_batch
  # execute_batch call
except ImportError:
  # fall back to self.execute
```

**Comment by richvdh** [comment]
dup #5054
