### ISSUE TITLE
Is it possible to disable users on private server from joining a public room, thereby exposing the hostname?

### ISSUE THREAD

**Issue by samwalls** [matrix-org/synapse#8005]
I recently set up matrix-synapse on my own domain, and tested joining a public IRC using a test account on that server. It occurred to me then, that by doing so, my domain could be scraped from the room, just from the "user joined" messages, even if I leave immediately.

Is there any way around this? If having multiple accounts is part of the solution (i.e. a matrix.org account, and a personal one), then it might be a good idea to have a matrix-to-matrix bridge, whereby one can communicate in a particular room via a different account. Is this possible?

Or, is there a way to disable users from my matrix server from joining external rooms?

**Comment by erikjohnston** [comment]
You can disable federation entirely by setting `federation_domain_whitelist: []` and removing `federation` from the `resources` in the HTTP listener config?

**Comment by samwalls** [comment]
I've done that, I think it works as I can't contact riot-bot anymore. Just to be clear, will this disallow requests to view/join a room? For example, if a link to a public room is shared, and someone clicks on it.

**Comment by samwalls** [comment]
Issue in riot, relevant to the use-case of completely un-federated private servers (i.e. public and private servers could be viewed in one place, multiple accounts): https://github.com/vector-im/riot-web/issues/2320

**Comment by aaronraimist** [comment]
You can't have it both ways. Either you federate with other Matrix servers which lets you join rooms on those servers (and "leaks" your domain name), or you don't federate and you can't join rooms or communicate with users on other servers.

**Comment by samwalls** [comment]
@aaronraimist that's right. Just to clarify, I'm not asking to have it both ways, at least not inherently. I was asking about how to block outgoing (therefore incoming) communication 👍 

The part I mentioned about public bridges, or having multiple accounts visible in a riot session is a mitigation to the constraint which this causes a user.

**Comment by richvdh** [comment]
sounds like this is resolved.
