### ISSUE TITLE
restarting multiple workers at once risks applying database migrations multiple times

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8006]
each worker independently checks if the schema is up-to-date and applies the migrations if not. At best this fails with exceptions; at worst it could result in data corruption

**Comment by richvdh** [comment]
I thought we used to have a thing that stopped migrations from running on anything other than the main process. In any case empirically it doesn't work any more.

**Comment by richvdh** [comment]
if the solution to this ends up being any sort of database-level locking, it would be nice to consider https://github.com/matrix-org/synapse/issues/6467 at the same time.

**Comment by erikjohnston** [comment]
I think we should be able to just not run the prepare database step if we're on not-master?

**Comment by clokep** [comment]
> I think we should be able to just not run the prepare database step if we're on not-master?

Is there a risk of those workers starting and then error because the migrations haven't finished yet?

**Comment by erikjohnston** [comment]
Hmm, true. We (matrix.org) do try and ensure master starts up *first*, but I'm not sure that's documented anywhere

**Comment by richvdh** [comment]
> Is there a risk of those workers starting and then erroring because the migrations haven't finished yet?

that would be preferable to the current situation imho. But I also wouldn't object to the other workers going into a sleep/check loop until the db got upgraded.

> Hmm, true. We (matrix.org) do try and ensure master starts up first, but I'm not sure that's documented anywhere

I'm also not convinced it's true that we wait for the master to restart before we restart the workers on the other server.

**Comment by erikjohnston** [comment]
> > Hmm, true. We (matrix.org) do try and ensure master starts up first, but I'm not sure that's documented anywhere
> 
> I'm also not convinced it's true that we wait for the master to restart before we restart the workers on the other server.

We have historically said that we restart the server with master on before the other servers when upgrading. That advice has probably gotten a bit lost over time too

**Comment by richvdh** [comment]
@reivilibre suggests maybe we could lock the schema version table while we do the migration

**Comment by erikjohnston** [comment]
`applied_schema_deltas` has a unique index so applying the same delta concurrently *should* cause one of the transactions to fail (and thus rollback the delta changes).

**Comment by richvdh** [comment]
> applied_schema_deltas has a unique index so applying the same delta concurrently should cause one of the transactions to fail (and thus rollback the delta changes).

well this might be true if we actually made the upgrades respect transactions correctly (cf #6467)

**Comment by erikjohnston** [comment]
Well that feels like a prerequisite to this if we're not correctly wrapping things in transactions?

**Comment by richvdh** [comment]
depends, but sure it would be a good thing to fix :)

**Comment by richvdh** [comment]
Looking at this more closely, because psycopg starts a new transaction for every statement, concurrent attempts to upgrade the database will probably fail for the reason Erik gave [previously](https://github.com/matrix-org/synapse/issues/8006#issuecomment-677694157).

I still think it's confusing, though.

**Comment by richvdh** [comment]
fixed by #8266
