### ISSUE TITLE
federation sender doesn't work when invoked as synapse.app.generic_worker

### ISSUE THREAD

**Issue by maranda** [matrix-org/synapse#8015]
### Description

As in the title, I followed the documentation closely to setup the worker, but when a message is propagated through Federation servers will answer with 403s

If I leave federation sending to the master instance there're no issues.

### Steps to reproduce

- Send message in a room
- Message appears locally but is not replicated over the network
- Remote servers answer 403s to federation transactions

Messages appear locally but not remotely and in logs the following warnings appear:
`
2020-08-01 11:29:46,696 - synapse.http.matrixfederationclient - 536 - WARNING - federation_transaction_transmission_loop-4108 - {PUT-O-3160} [***] Request failed: PUT matrix://***/_matrix/federation/v1/send/1596280923582: HttpResponseException("403: b'Forbidden'")
`
### Version information

- **Homeserver**: aria-net.org

If not matrix.org:

- **Version**: 1.18

- **Install method**: Ubuntu packages

- **Platform**:
Hyper-V machine with 16GB of RAM and eight virtual processors
Synapse running with 1+3 workers (2 general, 1 federation sender) with Postgresql and Redis managed via systemd
OS: Ubuntu server 20.04

**Comment by maranda** [comment]
I found the issue.

Basically https://github.com/matrix-org/synapse/blob/develop/docs/systemd-with-workers/system/matrix-synapse-worker%40.service will only startup the generic worker I didn't really look inside the script so I didn't notice it.

I think that should be properly referenced in the documentation, that the script should be modified to use other worker typed e.g. synapse.app.federation_sender.

**Comment by erikjohnston** [comment]
Thanks for the bug report! Part of me feels like we just make everything use the same app to avoid this problem, but until then yeah let's just fix the documentation :+1:

**Comment by richvdh** [comment]
I'd so much rather fix the app than the docs...

**Comment by richvdh** [comment]
I'm confused by this. Why does the `service` file changing? Why doesn't it work when it starts `-m synapse.app.generic_worker` ?

**Comment by maranda** [comment]
@richvdh it's not that the worker didn't start it's that the generic worker didn't work at all for the federation sender role.

**Comment by richvdh** [comment]
yes; I'm asking why that is the case. AFAICT the code that gets run is identical.

**Comment by richvdh** [comment]
(that's mostly a question for the dev team!)

**Comment by clokep** [comment]
There's still some special-cased code that needs to get cleaned-up:

https://github.com/matrix-org/synapse/blob/19b15d63e80dd1d925ff78158f7a191427d6403f/synapse/app/generic_worker.py#L952-L966

**Comment by erikjohnston** [comment]
Hmm, actually starting it with `-m synapse.app.generic_worker` should worker? It needs `worker_app: synapse.app.federation_sender` set in the config though: https://github.com/matrix-org/synapse/blob/develop/synapse/app/generic_worker.py#L952-L963 . Maybe we're doing something cunning somewhere that ensure we're setting `worker_app` to the same as the started app?

**Comment by richvdh** [comment]
basically, I don't think this is a documentation bug. If it exists at all, it's an implementation bug.

**Comment by clokep** [comment]
We *think* that #9466 will fix this, which will be part of Synapse v1.29.0.
