### ISSUE TITLE
/displayname returns non-JSON body

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/synapse#8029]
### Description

An attempt to call `/profile/{}/displayname` with an empty body results (rightfully) in a 400 error, with plain text "Unable to parse name" in the response. The expected error payload is something about (could also be `M_NOT_JSON` instead of `M_BAD_JSON`):
```json
{
    "errcode": "M_BAD_JSON",
    "error": "Unable to parse name" 
}
```

### Version information

- **Homeserver**: matrix.org

**Comment by babolivier** [comment]
@KitsuneRal What's the request you performed? (i.e. what's the HTTP method you used?)

Both `PUT` and `GET` give me

```
{
    "errcode": "M_INVALID_PARAM",
    "error":"Expected UserID string to start with '@'"
}
```

on matrix.org

**Comment by babolivier** [comment]
Oh looks like `{}` is a placeholder for the MXID here.
In which case I can reproduce.

**Comment by KitsuneRal** [comment]
Ok, I wasn't clear: `{}` in the endpoint path is just a shortcut for `{userId}`. The problem (which, embarrasingly, I can't reproduce either) is that with _some_ (apparently invalid - I though empty but it seems not) payload _in the body_ I end up with the plain-text body in the 400 response.
