### ISSUE TITLE
/health returns 'No such resource'

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/synapse#8054]
No Such Resource

No such child resource.

While this page[1] says every http endpoint should have it.

[1]
https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md#health-check-endpoint

**Comment by auscompgeek** [comment]
@f1-outsourcing Are you running a commit at least as recent as 7620912d84f6a8b24143f1340dd653f44b13bf30?

**Comment by f1-outsourcing** [comment]
Oh that is very new, I am getting from pip install matrix-synapse

**Comment by f1-outsourcing** [comment]
Just rebuild my docker image, and still not there.  When is this available in pip?

**Comment by babolivier** [comment]
It will be released in 1.19.0. Given we usually release a new version of Synapse every ~2 weeks, I'd expect this new release to land at some point next week.
