### ISSUE TITLE
Allow docker to take multiple configuration files (e.g. for worker mode)

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/synapse#8065]
If I understood docs correctly - this feature is already working outside of docker and worker docs are written like it were available in every supported scenario - also in docker.
I managed to run workers in docker (after few days of fight with docs not being docker-ready - #8053).
Now I'm concatenating configs outside of docker, which is far from ideal solution, I need to remember to refresh configs after change in `homeserver.yaml` and in worker config itself.

**Comment by clokep** [comment]
I suspect what would be nice is if you can give the docker container multiple configuration files, which is what the worker docs assume is possible?

**Comment by JuniorJPDJ** [comment]
It's better approach of what I was thinking about, thank you for specification :)

**Comment by ptman** [comment]
Would that help help with https://github.com/matrix-org/synapse/issues/6662 as well?

**Comment by JuniorJPDJ** [comment]
@ptman It could ;D

**Comment by richvdh** [comment]
It sounds like this might just be a duplicate of #6662?

**Comment by clokep** [comment]
Sounds like a duplicate, yep!
