### ISSUE TITLE
API to validate Matrix credentials without logging in

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#8089]
The specific use case is a jitsi instance that is only made available to users with accounts on the homeserver.

It seems tractable to restrict Jitsi access when accessing it as a widget within Element through the use of the Synapse OpenID APIs.

If we want the Jitsi instance to be similarly restricted when accessing it directly (i.e. not via an Element widget), the OpenID APIs can't help (since you need to be authed to use them).

If Synapse could expose a simple API for validating Matrix credentials without logging in, Jitsi could prompt direct-acccess users for a Matrix username and password and check those credentials against the homeserver.

The drawback of this approach is it normalises entering your Matrix credentials into a nonstandard interface, which warrants some further thought.

**Comment by richvdh** [comment]
That approach would also restrict the interface to homeservers which authenticate using a simple username/password.

In general using a Matrix server as a generic authentication provider sounds like the wrong tool for the job. Wouldn't it make more sense to use Keycloak or similar and have both Synapse and Jitsi authenticate using it?

**Comment by bmarty** [comment]
Even if I agree with @richvdh about the restriction, such API would also allows a user to reset PIN code protection on a client by entering the account password. For the moment, we only can do a logout and a propose the user to login again, which has consequences regarding e2ee.

**Comment by richvdh** [comment]
I think toml wanted this for a specific usecase, which is being solved in a different way.
