### ISSUE TITLE
DETAIL:  Key (type, instance_name)=(federation, master) is duplicated.

### ISSUE THREAD

**Issue by helmut72** [matrix-org/synapse#8097]
# Description

After upgrading Synapse Docker image to the latest one, I get this error:

```
root - 257 - WARNING - None- ***** STARTING SERVER *****
root - 258 - WARNING - None- Server /usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.18.0
twisted - 192 - ERROR - - Traceback (most recent call last):
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
twisted - 192 - ERROR - -     "__main__", mod_spec)
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
twisted - 192 - ERROR - -     exec(code, run_globals)
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 687, in <module>
twisted - 192 - ERROR - -     main()
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 682, in main
twisted - 192 - ERROR - -     hs = setup(sys.argv[1:])
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 375, in setup
twisted - 192 - ERROR - -     hs.setup()
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/server.py", line 283, in setup
twisted - 192 - ERROR - -     self.datastores = DataStores(self.DATASTORE_CLASS, self)
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/__init__.py", line 54, in __init__
twisted - 192 - ERROR - -     db_conn, engine, hs.config, data_stores=database_config.data_stores,
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 90, in prepare_database
twisted - 192 - ERROR - -     data_stores=data_stores,
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 405, in _upgrade_existing_database
twisted - 192 - ERROR - -     executescript(cur, absolute_path)
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 542, in executescript
twisted - 192 - ERROR - -     execute_statements_from_stream(txn, f)
twisted - 192 - ERROR - -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 547, in execute_statements_from_stream
twisted - 192 - ERROR - -     cur.execute(statement)
twisted - 192 - ERROR - - psycopg2.errors.UniqueViolation: could not create unique index "federation_stream_position_instance"
twisted - 192 - ERROR - - DETAIL:  Key (type, instance_name)=(federation, master) is duplicated.
```

### Steps to reproduce

- upgrade from Docker image 2020-07-13 12:50:37 ("matrixdotorg/synapse:latest-py3") to latest one ("matrixdotorg/synapse:latest")
- start Docker Container

### Version information

- **Homeserver**:

> $ curl http://localhost:8008/_synapse/admin/v1/server_version
> curl: (56) Recv failure: Connection reset by peer

- **Install method**:
Docker

- **Platform**:
Linux/AMD64

### Additional Informations

1. Switch back to older image, Synapse runs fine again
2. About 5-6 months ago, I switched my installation from SQLite to Postgres

**Comment by clokep** [comment]
> upgrade from Docker image 2020-07-13 12:50:37 ("matrixdotorg/synapse:latest-py3") to latest one ("matrixdotorg/synapse:latest")

For reference, this seems to be upgrading from v1.17.0 to v1.18.0.

It looks like the index was added a very long time ago, so I'm unsure why the delta for it would be running now.

**Comment by clokep** [comment]
It shouldn't be possible to end up with duplicates there (since we only ever update those rows), but it should be safe to delete the duplicate row with the lower `stream_id`.

**Comment by helmut72** [comment]
Looks good now. There were 3x federation and events. I've delete 2 of them, updated to 1.18.0 ("matrixdotorg/synapse:latest") and it now starts.

But I wonder why this happens. Never changed anything and it's a system with low usage (under 5 users and few messages per week).

Thanks!

**Comment by clokep** [comment]
Glad that worked! Usually these sorts of issues occur when exporting and re-importing a database (since there wasn't previously a requirement at the schema level to enforce this uniqueness). We'll keep an eye out if others have this issue as well.

**Comment by xoddark** [comment]
Hello, I have the same problem with a matrix-synapse server on a Yunohost server.
Where and how I can know if I had duplicate/invalid federation and events and how delete them ?

Thanks!

**Comment by xoddark** [comment]
@helmut72 or @clokep As the bug is closed, I don't know if you saw my question.

**Comment by richvdh** [comment]
@xoddark I recommend opening a new issue rather than commenting on a closed one. Be sure to include the errors from the log file and details of your deployment.

**Comment by helmut72** [comment]
I've used Adminer to delete the table entries, because I'm a SQL noob. Sorry, don't know the name of the tables anymore and I'm on a limited dataplan. I guess the name of table is something like federation_stream.

Make a SQL dump to backup, take your time and search with Adminer. It's easier than you think.

My Synapse server still runs great.

**Comment by xoddark** [comment]
@helmut72 : I was able today, and it's seems to work, thank's.
I had two {"federation", -1] in table federation_stream_position
