### ISSUE TITLE
(feature request) : make automatic user registration and login via phone nr possible

### ISSUE THREAD

**Issue by Rik44444** [matrix-org/synapse#8099]
Hi, 
I love Matrix, esp the focus on bridges. I would like to start recommending it to friends and family, but the Element app is really only acceptable to them if it is possible to register and login automatically with their phone number, without a password, and with sms id confirmation. So like with WhatsApp and Signal. This is a feature request to make this possible on Matrix as well, perhaps add it as an option in the login screen. I think it should be feasible (but I'm no expert), to assign randomly generated new user names and passwords to new phone numbers, and allow users to register and login without ever having to see either, so that they can just login with their phone number.

**Comment by clokep** [comment]
I think that this would require a new login type in the specification (https://github.com/matrix-org/matrix-doc/) for passwordless logins. You could file an issue there.
