### ISSUE TITLE
Best way to delete event data

### ISSUE THREAD

**Issue by ehounake** [matrix-org/synapse#8114]
Hi, 

We are using matrix in production and because of our usage we ended up with an essential need.

**What I have:**
We have some rooms with bots that post data  each 15/30/60/ secs as state events (e.g. env1.metrics) with a key (e.g. api1).
The problem is that for each state_event/key, we have all the data from previous update of the event stacking in the database.
The database will eventually grow to reach the limit of allocated space. Deletion of row corresponding to the event in database make the room unusable.

**What I need:**
An enpoint for events/state_events deletion by id or between two date for a state_event/key, ensuring that the data and the entries are actually deleted in the database and in the room (at least when the room is not encrypted).

**Comment by clokep** [comment]
I think the [purge history](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst#purge-history-api) admin API will do what you want, but I'm not 100% sure.

**Comment by clokep** [comment]
I'm going to close this since I believe the API already exists for this. If that solution doesn't work please re-open it (or provide more information of why it doesn't).
