### ISSUE TITLE
Synapse allows empty localpart in a room ID over federation

### ISSUE THREAD

**Issue by jplatte** [matrix-org/synapse#8126]
### Description

`!:sorunome.de` is an existing room (made as an experiment using a patched Synapse). [MSC 1597](https://github.com/matrix-org/matrix-doc/blob/master/proposals/1597-id-grammar.md) specifies

> The opaque_id part must not be empty, and must consist entirely of the characters `[0-9a-zA-Z.=_-]`.

### Version information

- **Homeserver**: matrix.org

**Comment by richvdh** [comment]
I daresay it allows all sorts of malformed room IDs, and indeed events as a whole.

related: https://github.com/matrix-org/matrix-doc/issues/1646.

**Comment by richvdh** [comment]
actually, on closer inspection, this isn't yet in the spec. MSC1597 is not (yet) implemented, and probably never will be.

**Comment by jplatte** [comment]
> and probably never will be

What? What significance does a merged MSC have, then??

**Comment by richvdh** [comment]
@jplatte I refer you to the answer given last time you asked that question: https://github.com/matrix-org/matrix-doc/pull/1598#issuecomment-641335821.

**Comment by jplatte** [comment]
I don't get it, so stuff should land in the spec first and then in Synapse? What about all the things Synapse does first that later land in the spec?

**Comment by richvdh** [comment]
[this conversation moved elsewhere]
