### ISSUE TITLE
Replying to a message containing "@room" trigger noisy notification

### ISSUE THREAD

**Issue by bmarty** [matrix-org/synapse#8143]
Steps:
- A message containing "@room" is sent to a room
- A moderator reply to this message

Current behaviour:
- the moderator reply triggers a highlight notification because the message contains "@room" (from the previous message)

Expected behaviour:
- the highlight notification should only occurs if "@room" is in the reply itself

**Comment by richvdh** [comment]
as @lieuwex says, this is a dup of #6202 and an artifact of matrix-org/matrix-doc#2736. I don't think there's anything to be done on the synapse side for now: it's something we can look to sort out as part of the notifcations rework
