### ISSUE TITLE
Shadow Ban unit tests are flaky due to random sleep times

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#8150]
### Description

The [ShadowBanTestCase](https://github.com/matrix-org/synapse/blob/e259d63f73fd7599520d0c4a6f5082e5cd383d25/tests/rest/client/v1/test_rooms.py#L1979) is flaky:

* https://buildkite.com/matrix-dot-org/synapse/builds/11211#9f35c864-1cd1-4e2f-8322-b3b693fea6d5/2675-2747
* https://buildkite.com/matrix-dot-org/synapse/builds/11211#91d9b873-8574-41b1-8cb4-394ec97a99ed/85-1850
* https://buildkite.com/matrix-dot-org/synapse/builds/11195#cfddfa55-f5f4-4d57-bd91-6b453f44862b/54-1805

Likely due to requests sometimes being artificially slowed down to thwart malicious users:

https://github.com/matrix-org/synapse/blob/e259d63f73fd7599520d0c4a6f5082e5cd383d25/synapse/handlers/room_member.py#L316-L317

These tests seem to be hitting [this timeout](https://github.com/matrix-org/synapse/blob/f13061d5153eca9bd7054d5b89ade41f3a430f3b/tests/server.py#L221), which the containing function has an arbitrary timeout value of `100` (which I believe means 10.0s). That means if a request takes >1s and we had a random sleep of 9s, the request will timeout.

Solutions here I can think of:

1. Upping this limit to something slightly higher (not sure what else relies on this though)
1. Weaving the `timeout` value through a bunch of functions all the way up to `self.render` such that these tests can explicitly say they expect to take slightly longer
1. Having a decorator, `@override_timeout(150)` similar to `@override_config`. This would be nice, though I'm not sure how exactly to pull it off

**Comment by clokep** [comment]
Thanks for investigating this a bit! I'll take this since I'm still working on this code anyway. 😄

**Comment by clokep** [comment]
> Solutions here I can think of:
> 
> 1. Upping this limit to something slightly higher (not sure what else relies on this though)
> 2. Weaving the `timeout` value through a bunch of functions all the way up to `self.render` such that these tests can explicitly say they expect to take slightly longer
> 3. Having a decorator, `@override_timeout(150)` similar to `@override_config`. This would be nice, though I'm not sure how exactly to pull it off

Another option would be to patch `random.randint` to always return 0 for those tests or something. I think that's my running contender right now, unless we'd benefit from having the timeout be configurable anyway.

**Comment by anoadragon453** [comment]
@clokep Perhaps instead we should make a function that generates timeouts for ShadowBanned users and mock that during tests? Something may rely on `random.randint` now or in future.
