### ISSUE TITLE
deprecate `/_matrix/client/*/admin`

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8177]
Some of the admin API is exposed at various paths under `/_matrix/client` as well as `/_synapse/admin`. We should remove those paths to make it easier to lock down the admin api.

**Comment by richvdh** [comment]
the other paths are:

 * `/_matrix/client/api/v1/admin`
 * `/_matrix/client/unstable/admin`
 * `/_matrix/client/r0/admin`

**Comment by richvdh** [comment]
The first step here is to announce our intention to remove the old paths in a changelog.

**Comment by anoadragon453** [comment]
> The first step here is to announce our intention to remove the old paths in a changelog.

Should we do so in v1.20.0?

**Comment by turt2live** [comment]
note that at least one of those endpoints made it into the spec: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-admin-whois-userid

**Comment by richvdh** [comment]
> note that at least one of those endpoints made it into the spec: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-admin-whois-userid

feh. we should replace and deprecate that too.

**Comment by anoadragon453** [comment]
I've added the `release-blocker` label to remind us to do put a note about this in v1.20.0.

**Comment by clokep** [comment]
Note that this essentially means removing `historical_admin_path_patterns`, which is an easy way to find them all. 👍

**Comment by anoadragon453** [comment]
A deprecation warning for this has been added in the changelog for release v1.20.0: https://github.com/matrix-org/synapse/blob/v1.20.0/CHANGES.md#synapse-1200-2020-09-22

**Comment by clokep** [comment]
> A deprecation warning for this has been added in the changelog for release v1.20.0: [https://github.com/matrix-org/synapse/blob/v1.20.0/CHANGES.md#synapse-1200-2020-09-22](https://github.com/matrix-org/synapse/blob/v1.20.0/CHANGES.md?rgh-link-date=2020-09-22T16%3A55%3A50Z#synapse-1200-2020-09-22)

Thanks! Do we have any thoughts on how long before removing it? E.g. v1.21.0 seems fast?

**Comment by anoadragon453** [comment]
We're aiming to get v1.21.0 in the not-too-far future, so I'd leave it a bit longer.
