### ISSUE TITLE
Failed to leave room - CORS request rejected

### ISSUE THREAD

**Issue by the-moog** [matrix-org/synapse#8186]
### Description

I suspect this is because this server is very old and though running latest Synapse is not a new install.
There is probably just a configuration issue, though no idea what.

On clicking "Leave room" on room hosted on matrix.org

Dialog:

-#####
Failed to leave room

request failed: CORS request rejected: https://matrix.cambsac.org.uk/_matrix/client/r0/rooms/!HsxjoYRFsDtWBgDQPh%3Amatrix.org/leave
-#####

### Steps to reproduce

Click leave room in Element/Desktop

I found this aftery trying to re-join a room that had moved, with "This conversion continues here"
that link action also failed with "Failed to join the room", There was an error joining the room.

Clicking again gets "Failed to make_join"  Looking into it the server log has an exception.  Probably another issue.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

It used to just leave, now there is an error.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

matrix.cambsac.org.uk

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

python_version: 3.5.2
server_version: 1.19.0
Element version: 1.7.4
olm version: 3.1.3

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

Standard packages

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

Linux cloud VPS
Distributor ID: Ubuntu
Version:    18.04.5 LTS
Codename:       bionic

**Comment by babolivier** [comment]
Hi, and thanks for your report. Element web complaining about CORS issues usually means that the homeserver could not be reached. Did you have any networking issue around the time this happened? And do you have any error in the Synapse logs around that time (if you have access to them)?

**Comment by clokep** [comment]
I believe that matrix.org was having some issues ~an hour ago. Might be worth retrying.

**Comment by the-moog** [comment]
No issues with our homesever and yes I can see all logs/configs we have total ownership.

**Comment by the-moog** [comment]
Indeed it looks like my issues could be realted to matrix.org issues

**Comment by babolivier** [comment]
> Indeed it looks like my issues could be realted to matrix.org issues

Does this mean this issue is fixed now?

**Comment by the-moog** [comment]
Yes, leaving a room now works. But the room continuation is still a bit odd. Also found an Element bug.  The room I could not leave (Synapse Admins) which I was really trying to continue is now missing in the side panel in Element even though I actually managed to continue it. So I can view it only by using explore rooms. Odd...
