### ISSUE TITLE
Internal server error when using List Room API with no filtering

### ISSUE THREAD

**Issue by anthr76** [matrix-org/synapse#8188]
### Description

When requesting all rooms in your home server via admin API the following response is sent.

```
{
    "errcode": "M_UNKNOWN",
    "error": "Internal server error"
}
```

### Steps to reproduce

- Possibly federate rooms with emojis in room names
- Curl ` /_synapse/admin/v1/rooms`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

This seems like it's an issue having emojis in the room names. When using a search term to narrow down the results the issue doesn't show up.

A traceback in synpase logs show:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 233, in _async_render_wrapper
    self._send_response(request, code, response)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 295, in _send_response
    canonical_json=self.canonical_json,
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 536, in respond_with_json
    json_bytes = encode_pretty_printed_json(json_object) + b"\n"
  File "/usr/local/lib/python3.7/site-packages/canonicaljson.py", line 96, in encode_pretty_printed_json
    return _pretty_encoder.encode(json_object).encode("ascii")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10427-10428: ordinal not in range(1
28)
```

Some rooms not in my server but are federated by my server have emojis in the name. Which show up in the logs:

`...'name': '🔊 Audio Corner', 'canonical_alias': '#audiocorner:jupiterbroadcasting.com', 'joined_members': 39, 'joined_local_members': 1, 'version': '5', 'creator': '', 'encryption': None, 'federatable': True, 'public': ...`
 


### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:
matrix.rabbito.tech

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
```
{
    "python_version": "3.7.8",
    "server_version": "1.19.0"
}

```
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
matrixdotorg docker container

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Containerized on Ubuntu 20.04 LTS

**Comment by clokep** [comment]
This sounds like the same as matrix-org/python-canonicaljson#33 -- a workaround is to specify a user-agent which isn't curl.

**Comment by anthr76** [comment]
This workaround succeeded !

**Comment by clokep** [comment]
Glad that worked! We'll need to release a new version of canonicaljson at some point with the fix in it. 👍

**Comment by clokep** [comment]
FYI we released an update for python-canonicaljson which should fix this. You can install 1.4.0 and it should work fine!

**Comment by richvdh** [comment]
see also #8262 which adds a dependency on `canonicaljson` 1.4.0, so people upgrading to synapse 1.21.0 will automatically get this fix.
