### ISSUE TITLE
memory is cannibalized by synapse

### ISSUE THREAD

**Issue by rosbeef** [matrix-org/synapse#8211]
# Description

Memory is cannibalized by synapse
I didn't recorded memory usage before detecting that my server were so slow.
I tried to implement those 2 tips in the /etc/default/matrix-synapse config file:

    LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libjemalloc.so.1
    SYNAPSE_CACHE_FACTOR=1
    I tried to varies values from 0.1 to 128 and it just delay the canibalism of synapse.
I run lots of services mastodon, element, synapse, wordpress, nextcloud ... but all in family circle

Synapse memory is calculate with monitorix searching for all processes named synapse or containing synapse in their execution command line. (all brutal decrease are manual synapse restart)
![image](https://user-images.githubusercontent.com/29942937/91666670-a0c95b00-eacc-11ea-928f-ae05a495331a.png)

### Steps to reproduce

- install and run synapse 
- install and run element web
- use element web

### Version information

- **Homeserver**:
matrx.3cm.fr

- **Version**:
synapse : 1.18.0
element : 1.7.3

- **Install method**: yunohost install 
https://github.com/YunoHost-Apps/synapse_ynh

- **Platform**:
odroid hc1 
2GB memory 
1GB swap 
ssd evo850 250GB

**Comment by rosbeef** [comment]
I reduced the swapiness of my host from 100 to 20 and that make the system more responsive and synapse memory usage increase slower but it seems that it will reach the GB rapidly too.
![image](https://user-images.githubusercontent.com/29942937/91728398-0838e680-eb71-11ea-9600-0187d86ea8a5.png)

**Comment by babolivier** [comment]
Hi, unfortunately without more specific metrics it's difficult to figure out what is using the memory. Would you be able to setup Prometheus to scrape metrics off Synapse (we have some instructions here: https://github.com/matrix-org/synapse/blob/develop/docs/metrics-howto.md) and display them with this Grafana dashboard: https://github.com/matrix-org/synapse/tree/develop/contrib/grafana ? If so, looking at the "Cache Size" panel in the "Caches" section can help identify what's going on.
Also, is your homeserver federated, and does it have users in big federated rooms? Joining such rooms will likely result in high memory usage as Synapse needs to load a lot of data into its cache to perform state resolution and authentication of new events.

**Comment by rosbeef** [comment]
ok i will try that i will be back as soon as posible

**Comment by richvdh** [comment]
closing this for now, due to lack of data. a few hundred MB is about the expected level of usage for synapse currently.
