### ISSUE TITLE
Synapse_port_db does not check that file is a database

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#8228]
User ran `synapse_port_db` script with the wrong path to `--sqlite-database`. `synapse_port_db` showed error: `Pending background updates exist in the SQLite3 database. Please start Synapse again and wait until every update has finished before running this script.` even though no SQLite database had been provided. They let Synapse run for several days but kept getting the same error, not realizing they had provided the wrong path.

It would be nice if the script checked that an actual SQLite database was provided, or at least that the path provided actually led to a file.

**Comment by richvdh** [comment]
dup #3982

**Comment by harupiyo** [comment]
I found this page very helpful.
Here is my case.
```
NG! synapse_port_db --curses --sqlite-database                         homeserver.db.snapshot --postgres-config /etc/matrix-synapse/homeserver-postgres.yaml
OK! synapse_port_db --curses --sqlite-database /var/lib/matrix-synapse/homeserver.db.snapshot --postgres-config /etc/matrix-synapse/homeserver-postgres.yaml
```
thanks.
