### ISSUE TITLE
We have instructions telling people to run the bg job 'populate_stats_process_rooms', but it is a no-op

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#8238]
### Description

In [this delta file](https://github.com/matrix-org/synapse/blob/v1.19.1/synapse/storage/databases/main/schema/delta/58/12room_stats.sql) we converted `populate_stats_process_rooms` to a no-op and created `populate_stats_process_rooms_2` in order to get around some edge cases with older Synapse versions.

It seems that this was not necessary, and we could've kept the same name and simply purged the progress of and restarted background job in the delta file instead.

The chosen solution has problems as there are [places](https://github.com/matrix-org/synapse/blob/b257c788c0541b1116b65e007f47b4f3a1de7760/UPGRADE.rst#upgrading-to-v1130) that we tell people to use `populate_stats_process_rooms` to fix issues. These instructions now simply do nothing as the bg job is a no-op.

A `DELETE` was used to solve a similar problem in another delta file: https://github.com/matrix-org/synapse/blob/a7bdf98d01d2225a479753a85ba81adf02b16a32/synapse/storage/databases/main/schema/delta/56/stats_separated.sql#L31

The delta file should be updated to sort out this mess.

**Comment by reivilibre** [comment]
It seems to me that one could add a new delta and  `UPDATE` `_2` jobs to the old name (and of course modify the code to make the original name not a NOP).

(Fixing the existing delta file is not necessarily good as it has already gone out, and someone may be half-way through running the job when they upgrade to the version where we back out the `_2` job)

**Comment by anoadragon453** [comment]
@reivilibre I was planning to delete the progress again, but you're right in that I think we could keep the user's existing progress by just creating a new delta file. Thanks :)

**Comment by anoadragon453** [comment]
Oh, but we'll need to delete the progress anyways to cover the edge cases laid out in the [original problematic delta file](https://github.com/matrix-org/synapse/blob/v1.19.1/synapse/storage/databases/main/schema/delta/58/12room_stats.sql)...

**Comment by reivilibre** [comment]
You wouldn't need to delete the progress made by a `_2` job, right?

**Comment by anoadragon453** [comment]
@reivilibre After running through the possible upgrade paths through the notable versions (`<=v1.18.0`, `v1.19.0`, and `$next_version`), this suggestion seems to work in all cases. Thank you!
