### ISSUE TITLE
Alternative more privacy friendly Captcha

### ISSUE THREAD

**Issue by samuel-p** [matrix-org/synapse#8273]
**Description:**

Google is not very privacy friendly, so I would love to have an alternative captcha option, which is not based on Google services.

**Comment by erikjohnston** [comment]
This is something we'd be interested in supporting, perhaps as a configurable plugin, but it's not something that we're going to have time to put on our road map any time soon alas. Contributions welcome, however :)

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-doc/issues/1281
