### ISSUE TITLE
"User @mattcen:matrix.org not in room"

### ISSUE THREAD

**Issue by mattcen** [matrix-org/synapse#8277]
## Description

I (@mattcen:matrix.org) just experienced an odd failure mode.
I used to be in this room: #matrix-docker-ansible-deploy:devture.com.
I was just looking at this room in Element Web on (https://app.element.io), and it was naming the room "Annie E. and 182 others", with no title or description. When I tried to send a message to that room, it said

`User @mattcen:matrix.org not in room !PukFFdIcHgtaaHZflT:devture.com (<FrozenEvent event_id='$15976549421674349yLGYP:matrix.org', type='m.room.member', state_key='@mattcen:matrix.org'>)`

When I tried to leave the room, it said `@mattcen:matrix.org not in room !PukFFdIcHgtaaHZflT:devture.com.`.

So I wasn't in the room, but I couldn't enter the room, or remove it from my rooms list.

I then noticed that my Element Android client seemed to at least list the room with its correct name. When I saw this, I logged out of Element Web, and then logged back in. After I did this, the room was no longer visible in my list. When I then tried to join the room, it said:

```
You were kicked from Docker + Ansible = Matrix by @appservice-irc:matrix.org

Reason: Idle for 30+ days
```

So I guess I got kicked, but Element Web didn't handle that very gracefully?

### Steps to reproduce

I'm not sure if this can reliably be reproduced, but presumably if it can, the process would be to kick a matrix.org user from a room (possibly one *not* on matrix.org), and then see how Element Web handles that.

### Version information

- **Homeserver**:

I am on matrix.org, but the room I was dealing with was hosted on devture.com, which I don't control.

This bug report was created at the suggestion of @ara4n, as per https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org?via=matrix.org&via=privacytools.io&via=half-shot.uk

**Comment by ptman** [comment]
Does Settings -> Help & About -> Clear cache and reload help with the room name?

**Comment by mattcen** [comment]
Unfortunately, since I've already resolved the problem and haven't had the chance to reproduce it yet, I can't test that currently. But on the off chance that it recurs, I'll give that a shot; thank you!

**Comment by erikjohnston** [comment]
@mattcen so did you manage to join again in the end?

This failure mode usually happens when state has reset, as we have no way of signalling that down `/sync`, but that shouldn't happen if you were kicked by a matrix.org account. I think we'd need to look at the DAG at the room at the time to see if anything odd has happened, but off the top of my head this shouldn't happen.

**Comment by mattcen** [comment]
Yes, I did manage to rejoin the room.

**Comment by erikjohnston** [comment]
Thanks, then this definitely sounds like the client not being told that you'd left the room for some reason

**Comment by erikjohnston** [comment]
Looking at the DB it does appear to be the result of a series of state resets (mattcen got kicked, then state reset made him join again, then a state reset kicked him again).  State resets should be rare in newer room versions, and the client not being told about state resets is tracked here: https://github.com/matrix-org/synapse/issues/4508

**Comment by ptman** [comment]
What was the room version? I thought version > 1 should be *immune* to state resets.

**Comment by erikjohnston** [comment]
Ah, I got confused between different rooms, the room is v5 so must have gotten bitten by one of the bugs where the homeserver gets confused by the state, which I believe are mostly fixed now (the logs show that the resets happened over a while ago).
