### ISSUE TITLE
Admin API to query the topic and avatar of a given room

### ISSUE THREAD

**Issue by rxl881** [matrix-org/synapse#8300]
It would be useful for a server admin to be able to query the topic and avatar of rooms (without joining).

**Comment by tulir** [comment]
It seems like this was already added in #7317: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/rooms.md#draft-room-details-api

**Comment by rxl881** [comment]
I am probably being blind, but I can't see the room topic (not room name) or avatar in the list of fields returned in the JSON response body? Please do say if I'm just not seeing it.

e.g,  from the docs:

```
{
  "room_id": "!mscvqgqpHYjBGDxNym:matrix.org",
  "name": "Music Theory",
  "canonical_alias": "#musictheory:matrix.org",
  "joined_members": 127
  "joined_local_members": 2,
  "version": "1",
  "creator": "@foo:matrix.org",
  "encryption": null,
  "federatable": true,
  "public": true,
  "join_rules": "invite",
  "guest_access": null,
  "history_visibility": "shared",
  "state_events": 93534
}
```

**Comment by tulir** [comment]
Oops, sorry, I didn't read the issue carefully enough. It should be fairly trivial to add to that room details endpoint though. The implementation seems to use the `room_stats_state` table, which does contain `avatar` and `topic` fields

**Comment by rxl881** [comment]
Cool. Thanks
