### ISSUE TITLE
Deprecate python 3.5

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8347]
**Description:**

Python 3.5 has [reached End-Of-Life](https://endoflife.date/python) on the 13th of September, deprecating this could open up synapse to (for example):
- f-string literals (#8332)
- Variable typing annotations (#8351)
- Async generators
- Async list literals (or "comprehensions")

([3.6 release notes](https://docs.python.org/3/whatsnew/3.6.html))

**Comment by clokep** [comment]
Note that Debian Stretch comes with Python 3.5 and is in LTS support until June 2022. Does not mean we *have* to support Python 3.5, but is worth considering.

**Comment by callahad** [comment]
(Just learned about endoflife.date from this; thanks @ShadowJonathan!)

I did some cursory digging and it sounds like at least one supported customer may still be deploying on 3.5. Will dig further...

**Comment by richvdh** [comment]
I'm going to close this in favour of https://github.com/matrix-org/synapse/issues/8782.
