### ISSUE TITLE
Add (some) more shields

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8348]
**Description:**

Add some more shields to the `README.rst` from shields.io (to a level that's still sane);
- A licence shield: ![GitHub](https://img.shields.io/github/license/matrix-org/synapse?logo=synapse)
- A shield detailing python version support: ![PyPI - Python Version](https://img.shields.io/pypi/pyversions/matrix-synapse?logo=synapse)
- A shield like the current "support" shield, but instead "development" and pointing to `#synapse-dev:matrix.org`

**Comment by anoadragon453** [comment]
Nice idea - I've added it to our board for further team discussion.

**Comment by anoadragon453** [comment]
We're happy to include these on the README and accept a PR that does so.
