### ISSUE TITLE
build_debian_packages seems flaky

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#8352]
We've had to build debs twice over the past two days, and each time `debian:stretch` is failing with obscure logs ([see here](https://vector.modular.im/_matrix/media/r0/download/vector.modular.im/6dd8279e0f6776416cd7040d56eb43159e2418a2)) and succeeding when rerun.

On top of that, today, the `ubuntu:bionic` one failed with a different but also strange error ([see here](https://vector.modular.im/_matrix/media/r0/download/vector.modular.im/6753ff9c414be4165c66afe02067d9abe3d21855)).

FWIW I've only seen it fail when running the builds concurrently (`-jX`) but then I've been running that mode for 3/4 of my attempts so cases where I haven't ran it in that mode are clearly a minority and might not be of any significance.

**Comment by richvdh** [comment]
> each time debian:stretch is failing with obscure logs (see here) and succeeding when rerun.

signal 9 is SIGKILL. possibly an oomkill? That would be consistent with it working when run with lower `-jX`.

> today, the ubuntu:bionic one failed with a different but also strange error (see here).

that is odd: it seems to be failing to read from the synapse volume, within the docker container used for the build. It's presumably somewhat specific to the build machine.
