### ISSUE TITLE
[meta] Issue triage suggestions

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8355]
An thread of issues with suggested labels;

#8347: maintenance
#8348: enhancement

**Comment by anoadragon453** [comment]
The above have been completed.

**Comment by anoadragon453** [comment]
In order to not accidentally leave this open forever: please reopen if you add to this list.

**Comment by ShadowJonathan** [comment]
@anoadragon453 I can't seem to reopen this issue, but I also think this is an inefficient method to note some issues need to be labelled, maybe issues can have a "needs-triage" label that can be placed in a todo queue or something of the sort.
