### ISSUE TITLE
error on direct chat

### ISSUE THREAD

**Issue by ramtinsafadoust** [matrix-org/synapse#8360]
my server address is :
matrix.farmehr.com

when i download app from google play there is no problem

but when i clone android project there is problem

client cant start direct conversation and screen go white

and in android studio debugger can see nginx 404 error

if my server has problem => why google play version is ok

if server is ok  => why this error happen 

and if my server has problem => why i can start direct chat by google play version with clone version

im so tired and confuse 

any body can help me

please try to solve my issue

**Comment by anoadragon453** [comment]
I'm afraid this is not a support forum. Please use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) or perhaps [#element-android:matrix.org](https://matrix.to/#/#element-android:matrix.org), registering an account on matrix.org if necessary, instead.
