### ISSUE TITLE
synapse fails to start if wrong version of isort is installed

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8365]
This seems to be a recent regression.

Why does having the wrong version of isort installed prevent synapse from starting? Synapse doesn't use isort at runtime, so surely this makes no sense?

```
(env3)rav@fred:~/work/synapse (develop *$%=)$ python -m synapse.app.homeserver
ERROR:root:Needed optional isort==5.0.3, got isort==5.0.5
Missing Requirements: 'isort==5.0.3'
To install run:
    pip install --upgrade --force 'isort==5.0.3'
```

**Comment by clokep** [comment]
Regression from #8330, most likely.

**Comment by ShadowJonathan** [comment]
My apologies, I didn't know it would have this knock-on effect
