### ISSUE TITLE
[tracking issue] Validation through Invariance

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8376]
## Description

This is a tracking issue for PRs and issues related to [invariance](https://stackoverflow.com/questions/112064/what-is-an-invariant) in the synapse codebase, to ensure extra stability and reduce undefined behaviour.

The plan is two-fold:
1. Reduce dynamic behaviour to statically-verifiable behaviour, where behaviour is explicitly notated instead of implicitly processed.
2. Introduce static typing annotations everywhere, to make it possible to check for undefined or variant behaviour.

Small PRs will be introduced cleaning these up iteratively.

## To-Dos / Spotted Issues

- [ ] Convert [`synapse.server.HomeServer.__init__()`](https://github.com/matrix-org/synapse/blob/14b5b48a2285a43f655030ec242b92d217c1994a/synapse/server.py#L229-L230) from dynamic to static behaviour.
    (e.g. by adding `__init__()` signatures to subclasses, then disallowing receiving `**kwargs`)

**Comment by ShadowJonathan** [comment]
One thing I still want the core team's opinion on: What is the best way I could properly and idiomatically change some functions that build and return data? (so that passing around this data is still valid by type)

What I mean by this; How could I change e.g. [`synapse.handlers.stats.StatsHandler._handle_deltas()`](https://github.com/matrix-org/synapse/blob/5d92a1428ceb4077801afc1785a5472e89fd9df3/synapse/handlers/stats.py#L134) to stop building on a plain dict (`room_stats_delta`), and instead use `@attr.s` classes?

```py

@attr.s(slots=True)
class RoomStatsDelta:
  current_state_events = attr.ib(default=0)
  joined_members = attr.ib(default=0)
  invited_members = attr.ib(default=0)
  left_members = attr.ib(default=0)
  banned_members = attr.ib(default=0)
```

This allows the program pass around objects which are assured to have *those values*.

Later on, when sending this to the user, `attr.asdict()` can be used to transparently sterilize any (nested) `attr.s` class to a final dict. This upholds invariance of this data-building throughout the program until it is time to pass it off to the user. 

(This could also (maybe) be a very good candidate for #8361)

**Comment by clokep** [comment]
> Later on, when sending this to the user, `attr.asdict()` can be used to transparently sterilize any (nested) `attr.s` class to a final dict.

For this particular example I'm not sure if deltas are ever sent as JSON or if it is completely an internal data-structure. Note that in this case it seems like the `room_stats_delta` is actually a `Counter` instance, not just a raw dictionary.

**Comment by ShadowJonathan** [comment]
> Note that in this case it seems like the `room_stats_delta` is actually a `Counter` instance, not just a raw dictionary.

I do note that, but I wanted to pick an easy example for the moment. It seems like I cant subclass `Counter` here with an `attr.s` class, and i'd have to trace where abilities of `Counter` are actually used, and/or convert this class somewhere along the way if that is true, I'd have to look into it. 

Still, eliminating "blind keys" is the point here; to make sure the static linter can follow what's going on.

**Comment by ShadowJonathan** [comment]
I think #8351 covers most of this, the other part (making every class statically verifiable) should be hit at some point as well, but i'm going to close this as it's not exactly doing much good being open onto itself.
