### ISSUE TITLE
Workers on multiple servers

### ISSUE THREAD

**Issue by aliirezaaa** [matrix-org/synapse#8379]
Hi,

I read the document about workers. I'm eager to know how to setup synapse workers on multiple servers not only multiple processes.

**Comment by dklimpel** [comment]
The principle is exactly the same. You just have to change the IP addresses accordingly. The disadvantage is that you can't use systemd to map all the services and dependencies. You need a cluster software, script or do this manually.
I built synapse with pip on a server and copied it to all workers including the homeserver.yaml.

If there is an easier solution, I look forward to it.
Containers and/or ansible are certainly the solution here.
https://github.com/spantaleev/matrix-docker-ansible-deploy

**Comment by anoadragon453** [comment]
Thanks for the answer @dklimpel.

@aliirezaaa I suggest if you have more questions, take them to [#synapse:matrix.org](https://matrix.to/#/#syanpse:matrix.org) or [#synapse-dev:matrix.org](https://matrix.to/#/#syanpse-dev:matrix.org) :slightly_smiling_face: 

Closing this as it as the question has been answered.
