### ISSUE TITLE
Document that `/typing` requests should route to the instance configured as writer for `typing` stream.

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#8382]
This should be mentioned in [`docs/workers.md`](https://github.com/matrix-org/synapse/blob/master/docs/workers.md)

**Comment by dklimpel** [comment]
Is this already done?

https://github.com/matrix-org/synapse/blob/1c910e2216a2f7fa57971ffbdede509fd493ebb0/docs/workers.md#L372-L378

**Comment by erikjohnston** [comment]
Looks like it!

**Comment by clokep** [comment]
Done in #11599 FTR.
