### ISSUE TITLE
Warning message from `dpkg-statoverride` on deb installation

### ISSUE THREAD

**Issue by q-wertz** [matrix-org/synapse#8391]
### Description

During installation of synapse on a Ubuntu 20.04 from the provided package, the following warning message appears:
```shell
dpkg-statoverride: warning: deprecated --force option; use --force-all instead
```

### Steps to reproduce

- follow instructions on https://github.com/matrix-org/synapse/blob/master/INSTALL.md#matrixorg-packages
- on `sudo apt install matrix-synapse-py3` the following warning appears:
```console
user@host:/home$ sudo apt install matrix-synapse-py3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  sqlite3
The following NEW packages will be installed:
  matrix-synapse-py3
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 28.9 MB of archives.
After this operation, 165 MB of additional disk space will be used.
Get:1 https://packages.matrix.org/debian focal/main amd64 matrix-synapse-py3 amd64 1.20.0+focal1 [28.9 MB]
Fetched 28.9 MB in 1s (34.4 MB/s)             
Preconfiguring packages ...
Selecting previously unselected package matrix-synapse-py3.
(Reading database ... 116287 files and directories currently installed.)
Preparing to unpack .../matrix-synapse-py3_1.20.0+focal1_amd64.deb ...
Unpacking matrix-synapse-py3 (1.20.0+focal1) ...
Setting up matrix-synapse-py3 (1.20.0+focal1) ...
dpkg-statoverride: warning: deprecated --force option; use --force-all instead
dpkg-statoverride: warning: deprecated --force option; use --force-all instead
dpkg-statoverride: warning: deprecated --force option; use --force-all instead
Created symlink /etc/systemd/system/multi-user.target.wants/matrix-synapse.service → /lib/systemd/system/matrix-synapse.service.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
```

### Version information

- **Homeserver**:

If not matrix.org:

- **Version**:

- **Install method**:
package manager

- **Platform**:
```console
insadmin@automatix:/home$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by anoadragon453** [comment]
Related: https://github.com/matrix-org/synapse/pull/6224

It seems that bionic didn't support this (and presumably xenial either). EOL for bionic is 2021: https://help.ubuntu.com/community/EOL#Ubuntu_18.04_Bionic_Beaver

Do we know when `--force` is going to be deprecated?

**Comment by richvdh** [comment]
it's already deprecated :-p

**Comment by anoadragon453** [comment]
Whoops, "removed" I mean :smile:

**Comment by richvdh** [comment]
I think we can just replace `--force` with `--force-all` (or something like that) here.

**Comment by richvdh** [comment]
wait no, we still need this to support bionic. EOL for bionic is 2023, not 2021, but we'll have to drop support for bionic in December 2021 as python 3.6 goes out of support then.

**Comment by richvdh** [comment]
I don't really know why we need `--force` here at all. what are we forcing?

This appears to have originated in https://github.com/matrix-org/package-synapse-debian/commit/cc28c9be22a55ebef9fbf45c5abc7b4753e95dd0#diff-2db24480058f7aaaee957b463ec9c8bcb83c508aeac36a78f08c152fa50f622eR30, but there are no clues there.
