### ISSUE TITLE
Re-Activating account fails when using SSO/SAML (with local passwords disabled)

### ISSUE THREAD

**Issue by phewitt-uw** [matrix-org/synapse#8393]
### Description

Using a self-hosted server, and using SAML2/SSO for authentication with local password DB is disabled.  When you deactivate an account this works, but when you try to reactivate an account via API  `_synapse/admin/v2/users` by setting "deactivated" to "false" API returns error:

{
    "errcode": "M_UNKNOWN",
    "error": "Must provide a password to re-activate an account."
}

and when you try to include a password API returns error: 

{
    "errcode": "M_FORBIDDEN",
    "error": "Password change disabled"
}

### Steps to reproduce

- enable SSO
- disable local password db in config
- activate account
- deactivate account
- then try to re-activate account using API

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.20.0

- **Install method**: docker images from matrixdotorg
<!-- examples: package manager/git clone/pip  -->

- **Platform**: kubernetes & docker
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment]
Looks like the code around [here](https://github.com/matrix-org/synapse/blob/6fdf5775939100121ad9e6e3a8cb21192a5444d6/synapse/rest/admin/users.py#L244-L252) needs to be updated to handle the case of an account not needing a password. I'm unsure there's a good way to check if an account is an SSO account or not, although we do have a table of external IDs to internal IDs. Maybe existing in there is a reasonable solution?

**Comment by anoadragon453** [comment]
Note that this seems separate from https://github.com/matrix-org/synapse/issues/8359 in that it only affects SSO users.

**Comment by localguru** [comment]
Hi, anything going on here? Or is there a workaround?

**Comment by callahad** [comment]
No current plans to address this on the Element side; we would gladly accept patches.

**Comment by localguru** [comment]
@clokep Hi, have the same problem. I'm ussing SSO (Shibboleht) and want to reactivate a user. Error is
```
{"errcode":"M_UNKNOWN","error":"Must provide a password to re-activate an account."}
```
Is there a workaround like changing `deactivated` in postgres?

**Comment by localguru** [comment]
hmm ... it set `{"deactivated": false, "password": "foobar"}' via API, so that the user is reactivated. And then I set password_hash via SQL in users table to NULL: `UPDATE users SET password_hash=NULL WHERE name = '@user:example.org';`. BUT if I check the users data via API, the password is not NULL.

**Comment by anoadragon453** [comment]
@localguru `GET /_synapse/admin/v2/users/<user_id>` attempts to pull from a cache before it pulls from the database. If you queried that user via the Admin API before, and then changed something directly in Postgres, Synapse will be unaware of the change and continue to serve the cached content.

Try restarting Synapse and see if the results of the Admin API call are correct.

**Comment by localguru** [comment]
@anoadragon453 okay, I will try that, can't restart a live server now. Is there another way to NULL a users password? I tried 
```
POST /_synapse/admin/v1/reset_password/<user_id>

with a body of:

{
    "new_password": "<secret>",
    "logout_devices": true
}
```
but get an error (may be because of SSO config): `{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`.

And what I see is that the use is listed in `erased_users` table. How do I get the user removed from this table? SQL or is there an API?

**Comment by localguru** [comment]
Hmmm ... now the entry for that user in `erased_users` is gone. Strange. Took about an hour.

**Comment by clokep** [comment]
> Hmmm ... now the entry for that user in `erased_users` is gone. Strange. Took about an hour.

The cache timed out and the user got re-pulled from the database. This is what @anoadragon453 described above.

**Comment by localguru** [comment]
@clokep right, after a restart of synapse the password_hash is NULL via API too. Thanks. It would be nice to have a way to set password to NULL on SSO systems or better to reactivate an account without having to set a password, if SSO is used.
