### ISSUE TITLE
rip out tls_fingerprints option from homeserver.yaml

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8424]
this option has no use any more and we should get rid of it and any code that reads it.

**Comment by jerinjtitus** [comment]
In `tls.py`, do I have to remove this whole function or just a part of it?
https://github.com/matrix-org/synapse/blob/f2c1560eca1e2160087a280261ca78d0708ad721/synapse/config/tls.py#L229-L252

I am working on other parts of code where `tls_fingerprints` is mentioned too.

**Comment by richvdh** [comment]
any code that is no longer used should be removed.

In this case, `Config.tls_fingerprints` is only used in `synapse.rest.key.v2.local_key_resource.LocalKey`, where it only used to set a feild that is no longer required in the Matrix protocol. So it can be removed from there, and the code that sets it can also be removed.

`tls_certificate` is still used: why would you want to remove that code?

**Comment by jerinjtitus** [comment]
> `tls_certificate` is still used: why would you want to remove that code?

I was just confirming, due to the comment `# we only need the certificate for the tls_fingerprints. Reload it if we`. I wasn't sure if it was just reading that part of the certificate or whole of it.
