### ISSUE TITLE
Ubuntu 20.10 (Groovy Gorilla) should likely be added to distros

### ISSUE THREAD

**Issue by jryans** [matrix-org/synapse#8449]
Beta version was recently released: https://lists.ubuntu.com/archives/ubuntu-announce/2020-October/000262.html

**Comment by richvdh** [comment]
ah I guess we should do this for 1.21.0.

**Comment by anoadragon453** [comment]
Hopefully this is just added a line to https://github.com/matrix-org/synapse/blob/9c0b168cff3a225fe2506dd3a079f2a7ddaf62d2/scripts-dev/build_debian_packages#L20-L28?

**Comment by jryans** [comment]
Sounds correct based on previous changes of this type.

**Comment by richvdh** [comment]
https://gitlab.matrix.org/new-vector/internal/-/wikis/Synapse-Debian-Packages#adding-a-new-distribution

**Comment by erikjohnston** [comment]
Done by https://github.com/matrix-org/synapse/pull/8475
