### ISSUE TITLE
Missing public_baseurl validator test

### ISSUE THREAD

**Issue by danger89** [matrix-org/synapse#8471]
**Description:**

Currently the `public_baseurl` isn't validated, not by the Synapse instance itself or by the federationtester.matrix.org.

It took quite some time to figure out the public base URL was incorrectly configured on my Synapse instance. Maybe it's wise to add some validator/check to Synapse or the federationtester or both :+1: .

Related issue: #8469 

Debug logging wasn't helping either.

Will be appreciated by others. Thanks.

Regards,
Melroy van den Berg

**Comment by clokep** [comment]
Adding start-up validation for the config makes sense, but I'm unsure if we are able to for `public_baseurl`. I'm curious what you had it set to vs. what it needed to be set to in order to work appropriately?

I'm pretty sure this is supposed to refer to #8469.

**Comment by richvdh** [comment]
see https://github.com/matrix-org/matrix-federation-tester/issues/105 which concerns trying to validate this in the federation tester, as well as https://github.com/matrix-org/synapse/issues/6972

**Comment by danger89** [comment]
I tried to configure this public base url, which was a requirement for **enabling mail**. I didn't released this setting has so much impact. Again it wasn't required at all, at first. 

_Anyhow_, I accidentally configured this url to: https://server.melroy.org.

While of course it should have been: https://matrix.melroy.org 

Again, no warning or validator was triggered, everything seems OK initially. But I was getting very strange offline behavior.

Took quite some time to figured it out.

**Comment by danger89** [comment]
You can validate the public_baseurl with other settings like the client well-known, which should match. Just an idea to start with?

**Comment by richvdh** [comment]
I don't think there is a way for us to validate this setting without making HTTP requests at startup, which would prevent synapse restarting if you are having a temporary network outage. (It's also not a given that synapse can reach it's own `public_baseurl`).

I don't think there's much more we can do here.

**Comment by clokep** [comment]
I'm going to close this with matrix-org/matrix-federation-tester#105 probably being the best way to solve this.

**Comment by danger89** [comment]
> I don't think there is a way for us to validate this setting without making HTTP requests at startup, which would prevent synapse restarting if you are having a temporary network outage. (It's also not a given that synapse can reach it's own `public_baseurl`).
> 
> I don't think there's much more we can do here.

Add a test to the federation tester
