### ISSUE TITLE
[ Burn after reading]

### ISSUE THREAD

**Issue by mnxzyw** [matrix-org/synapse#8482]
**Description:**

Is it possible to add the function of burning after reading(The message will disappear after x seconds after being read), 
so that users do not have to proactively delete sensitive conversation content

**Comment by clokep** [comment]
This is not currently possible, but there are some ideas to add this to Matrix (at the protocol level). Check out matrix-org/matrix-doc#2228.

I'm going to close this since this would need to be speced first before implemented in Synapse.
