### ISSUE TITLE
Add note to manhole.md about address binding when using docker

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8508]
I recently came across this problem, where the manhole was binding to `127.0.0.1` within the container, it wasn't clear to me at first why docker immediately closed all connections then.

I think a note should be added to `manhole.md`, when using docker, that it has to be set to `0.0.0.0`, or else docker cant forward the port to it.

**Comment by maquis196** [comment]
PR added with note about the above.
