### ISSUE TITLE
Resetting signing keys doesn't work with SSO

### ISSUE THREAD

**Issue by sephii** [matrix-org/synapse#8509]
### Description

Users cannot use the "Reset cross-signing and secret storage" feature when using SSO auth.

### Steps to reproduce

- Log in with SSO
- Go to your security & privacy settings
- Click the "Reset cross-signing and secret storage" button
- Go through the process, you'll get an error message

The problem comes from /_matrix/client/unstable/keys/device_signing/upload which returns a 401 (because it lacks SSO information).

### Version information

- **Homeserver**: matrix.asso-pea.ch
- **Version**: 1.20.1
- **Install method**: pip
- **Platform**: Debian Buster

**Comment by jryans** [comment]
What version of Element Web are you using? It should be possible to reset with SSO accounts assuming Element is up to date.

**Comment by sephii** [comment]
I'm using Element Web 1.7.7, there's no SSO redirect like there's when deleting sessions for example.

**Comment by jryans** [comment]
@sephii That's a few versions old now, so I would first suggest updating to latest (1.7.9) or using develop.element.io. If it still fails, please send debug logs from Element.

An initial 401 response is not unusual: this is part of the standard flow of negotiating authentication in Matrix.

**Comment by clokep** [comment]
Closing due to lack of response. Please ensure you're using an up-to-date Element and Synapse and let us know if you're still seeing this issue.
