### ISSUE TITLE
Purge room API doesn't work.

### ISSUE THREAD

**Issue by PC-Admin** [matrix-org/synapse#8512]
### Description

Trying to use the purge api found here, command claims i have no token even though i do: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst

### Steps to reproduce

1) Ensure /synapse is mapped.
2) Open a terminal.
3) Drop in this command with your api token:

$ curl -X POST 'https://matrix.perthchat.org/_synapse/admin/v1/purge_media_cache?before_ts=<1599659116000>?access_token=MDAdefinitely_the_access_token_reeeeeeee'
{
    "errcode": "M_MISSING_TOKEN",
    "error": "Missing access token"
}

### Version information

- **Homeserver**: 

perthchat.org

- **Version**:

Synapse version 1.19.1

- **Install method**:

Spantaleev deploy script.

- **Platform**:

Debian 10

**Comment by auscompgeek** [comment]
As I mentioned in #synapse:matrix.org, the access token is indeed missing: you've specified a before_ts of `<1599659116000>?access_token=MDA...`

**Comment by PC-Admin** [comment]
My man. :D

**Comment by PC-Admin** [comment]
It worked this way:

$ curl -X POST --header "Authorization: Bearer MDAsd_very_long_token" 'https://matrix.perthchat.org/_synapse/admin/v1/purge_media_cache?before_ts=1599659116000'

**Comment by PC-Admin** [comment]
uhh xP

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

It might actually be working though.

**Comment by aaronraimist** [comment]
You probably used a recent timestamp on a room that you have years of history for. Try doing smaller sections of time.

**Comment by PC-Admin** [comment]
Server load has doubled and perthchat seems frozen, so i kind of feel like it's in progress. o.0

**Comment by clokep** [comment]
Seems like this is a conversation continuing from #synapse:matrix.org.
