### ISSUE TITLE
Push notifications for invites do not trigger across federated homeservers

### ISSUE THREAD

**Issue by alariej** [matrix-org/synapse#8531]
The base push rule ".m.rule.invite_for_me" (enabled by default in Element apps) correctly pushes notifications on mobile devices for invitations when both users (invitor and invited) are registered on the same homeserver.

However when users are not on the same server, notifications for invitations never get pushed to mobile devices.

This was tested using Element Android and Element iOS on matrix.org and two other homeservers running Synapse 1.20+.

Normal message notifications get pushed correctly, independently of the users homeservers.

I have also tested this using an own mobile client and an own instance of Sygnal, which showed that the notification gateway never receives any push requests from the homeservers for the missing cross-server notifications.

**Comment by clokep** [comment]
A good first step would be to check the logs of the homeservers and see if they're failing to send to the push server for some reason.

**Comment by alariej** [comment]
I was testing so far on publicly available homeservers, so I have unfortunately no access to logs. But I'm planning to install an own Synapse instance in the next days. Will certainly be doing more tests as soon as I'm up and running and post the results here.

I was also thinking this could possibly be a security feature, to prevent something like notification spamming coming from external homeservers. But I haven't seen any info on this in the matrix documentation.

**Comment by erikjohnston** [comment]
This is #8626
