### ISSUE TITLE
"_http.authedRequest" (invoked in  "uploadDeviceSigningKeys") seems not to work with password providers

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#8532]
synapse: v1.21.1
matrix-js-sdk: v8.5.0

Note: I already filed this issue in the matrix-js-sdk repo (here: https://github.com/matrix-org/matrix-js-sdk/issues/1505) because the SDK throws an exception and stops working correctly. @jryans suggested to further discuss this issue Synapse related.

Background:

I am trying to bootstrap cross-signing along with a 3pid login using a password provider, see below JS snippet:

```
    const _doBootstrapAuth = async (makeRequest) => {
        await makeRequest({
            type: 'm.login.password',
            identifier: {
                type: 'm.id.thirdparty',
                medium: 'email',
                address: userMail,
            },
            password: userPwd,
        });
    };

    try {
        await Client.get().bootstrapCrossSigning({
            authUploadDeviceSigningKeys: _doBootstrapAuth,
            setupNewCrossSigning: forceReset,
        });
    } catch (e) {
        console.error('Error bootstrapping cross-signing', e);
    }
```

The `authedRequest` looks fine, sending the auth dict with the 3 cross-signing keys. The user is authenticated successfully and the password provider returns the `user_id` upon authentication.

However, the following errors are shown in ...

-1- console
```
POST http://localhost:8008/_matrix/client/unstable/keys/device_signing/upload 400 (Bad Request)
crypt.js:400 Error bootstrapping cross-signing M_MISSING_PARAM: Unknown message
    at parseErrorResponse ...
    at Object.callback ...
    at on_end ...
    at XMLHttpRequest.on_state_change ...
```

-2- homeserver.log
```
2020-10-12 07:46:47,277 - synapse.http.server - 76 - INFO - POST-112 - <XForwardedForRequest at 0x7f5dda580b70 method='POST' uri='/_matrix/client/unstable/keys/device_signing/upload' clientproto='HTTP/1.1' site=8008> SynapseError: 400 - 
2020-10-12 07:46:47,277 - synapse.access.http.8008 - 311 - INFO - POST-112 - - - 8008 - {@testuser:localhost} Processed request: 0.486sec/-0.000sec (0.000sec, 0.000sec) (0.001sec/0.483sec/2) 40B 400 "POST /_matrix/client/unstable/keys/device_signing/upload HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38" [0 dbevts]
```

I guess that Synapse returns a different response when the authentication is done through a password provider. In this case Synapse seems to miss merging a parameter into the response of the `authedRequest` that is obviously needed/expected in the matrix-js-sdk.

**Comment by clokep** [comment]
@menturion Would it be possible to provide the body that is being sent to `device_signing/upload`?

I don't see anywhere in our code where we use `M_MISSING_PARAM` along with "Unknown message" though so something is a bit funny here.

Just to ensure we're on the same page, the above code works if you don't use a password provider and only breaks when a password provider is used?

**Comment by menturion** [comment]
@clokep 

Many thanks for your reply. Please find below:

```
{
  "master_key": {
    "user_id": "@testuser:localhost",
    "usage": [
      "master"
    ],
    "keys": {
      "ed25519:FzGHbQgWo+L3hSVKEerr4k2Rhr0nvAzOItC7MDjswro": "FzGHbQgWo+L3hSVKEerr4k2Rhr0nvAzOItC7MDjswro"
    },
    "signatures": {
      "@testuser:localhost": {
        "ed25519:ZATWSQGOIP": "E8TlpiUaNQF9JMZTplsrsqZtQqOuJ9O3XYnM16YI3+eoNQmu0KXJju6fteNGHI/gYVDd8/wg9BpLhvSYpjksCQ"
      }
    }
  },
  "self_signing_key": {
    "user_id": "@testuser:localhost",
    "usage": [
      "self_signing"
    ],
    "keys": {
      "ed25519:kgD1gwUoiv6JZtaeis9yHIKISwFQ6p9/9SIY57qhWuE": "kgD1gwUoiv6JZtaeis9yHIKISwFQ6p9/9SIY57qhWuE"
    },
    "signatures": {
      "@testuser:localhost": {
        "ed25519:FzGHbQgWo+L3hSVKEerr4k2Rhr0nvAzOItC7MDjswro": "8heWR2g+Y6tQi5B1dXIGrserHQWKAdkF5M3/3wXNZjkhXueh+iwRo7HWatXH4Pu2zGUmDQt2/f3WmdWLvEo6Dg"
      }
    }
  },
  "user_signing_key": {
    "user_id": "@testuser:localhost",
    "usage": [
      "user_signing"
    ],
    "keys": {
      "ed25519:kOJRTRLINsgUi7j/bswKo6y+pFt9hpSWkrjxcEN8BoM": "kOJRTRLINsgUi7j/bswKo6y+pFt9hpSWkrjxcEN8BoM"
    },
    "signatures": {
      "@testuser:localhost": {
        "ed25519:FzGHbQgWo+L3hSVKEerr4k2Rhr0nvAzOItC7MDjswro": "AFkjoPbJRlQW3OE/am2YKWkG0qzoPsf2gHlD5Eyuf+F4Pt7V0j63VQYLS0oszMrqGMpSf3qc4jWlSnX9//9UAg"
      }
    }
  },
  "auth": {
    "type": "m.login.password",
    "identifier": {
      "type": "m.id.thirdparty",
      "medium": "email",
      "address": "testuser@mymail.com"
    },
    "password": "myPWD"
  }
}
```

> Just to ensure we're on the same page, the above code works if you don't use a password provider and only breaks when a password provider is used?

Users can only be authenticated through a password provider based on the 3pid/email and the users's PWD. The password provider returns the `user_id `if the user is authenticated successfully.

So the following request (as used in the matrix react sdk) won't work and results in `M_FORBIDDEN: Invalid password`.
```
            await makeRequest({
                type: 'm.login.password',
                identifier: {
                    type: 'm.id.user',
                    user: MatrixClientPeg.get().getUserId(),
                },
                // TODO: Remove `user` once servers support proper UIA
                // See https://github.com/matrix-org/synapse/issues/5665
                user: MatrixClientPeg.get().getUserId(),
                password: this.state.accountPassword,
            });
```

I also tried to add the user's ID to the request (like below) because I saw in the `SigningKeyUploadServlet` that the request requires a user ID (`Auth/get_user_by_req` ). However, the below request will not hit the password provider, i.e.  `Auth/check_password_provider_3pid` isn't called and it results in a `M_FORBIDDEN: Invalid password` again.

```
        await makeRequest({
            type: 'm.login.password',
            identifier: {
                type: 'm.id.thirdparty',
                medium: 'email',
                address: userMail,
            },
            user: Client.get().getUserId(),
            password: userPwd,
        });
```

Do you have any idea what might cause this issue?

**Comment by clokep** [comment]
It looks to me like what you're trying to do should work if you add the `user` field:

https://github.com/matrix-org/synapse/blob/8b40843392e2df80d4f1108295ae6acd972100b0/synapse/handlers/auth.py#L812-L835

It looks to me like the `check_password_provider_3pid` is unrelated, that's used by login to verify an email address was valid, which I don't think is what you're trying to do here.

So I think things to try are:

* Include the `user` field.
* Implement `check_password` on your provider.

**Comment by menturion** [comment]
@clokep 

Good idea!!!
I just implemented the `check_password` in the password provider and it works. 

This, however, means that the `uploadDeviceSigningKeys` currently does not work with password providers that do not support `check_password`. This is due to the missing user field (i.e. `user_id`) in the `authedRequest`. Right?

**Comment by clokep** [comment]
If `uploadDeviceSigningKeys` is calling the APIs with the proper data then it should work. I'm not really sure what that does under the hood as I'm not familiar with the matrix-js-sdk.

**Comment by clokep** [comment]
Closing due to lack of response.
