### ISSUE TITLE
CPU spikes caused by `send_dummy_events_to_fill_extremities`

### ISSUE THREAD

**Issue by davidmehren** [matrix-org/synapse#8533]
### Description

Since upgrading to Synapse 1.21.1 we are experiencing irregular spikes (each for 15-30 seconds) in CPU usage of the main process (other workers are not affected).  
Prometheus metrics ("cpu usage by background jobs") show the job `send_dummy_events_to_fill_extremities` using all CPU (around 150%, but that seems to be a another bug?) at the time of the spike.

### Steps to reproduce

Sorry, not really reproducible. Happened 7 times in the 5 hours since the upgrade.

The only related log message I found was
```
matrix-synapse[39254]: synapse.handlers.message - 889 - WARNING - send_dummy_events_to_fill_extremities-0 - Denying new event <FrozenEventV3event_id='$yfeXUEgJ6XGNX3Kok8YoyN4gmRaDUGvSTC4qE7ugz6k', type='org.matrix.dummy_event', state_key='None'> because 403: You don't have permission to post that to the room. user_level (0) < send_level (50)
```
Other things I noticed happening at the time of the last hang
- The request and eviction rates of the `*getEvent*` cache skyrocket
- "per-block metrics" show `resolve_state_groups_for_events` and `state._resolve_events` each using ~150% CPU
- "Total DB usage by block" shows a spike in db usage from ` _fetch_event_list` about a minute before the CPU spike, then another spike from `resolve_state_groups_for_events` and `state._resolve_events` at the time of the CPU spike.

### Version information

- **Homeserver**: matrix.kif.rocks
- **Version**: 1.21.1
- **Install method**: deb Package
- **Platform**: Container (LXC) with Ubuntu 20.04.1 on a Proxmox host `Linux kif-matrix 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200) x86_64 x86_64 x86_64 GNU/Linux`

**Comment by clokep** [comment]
I don't believe we've changed how often / when that code runs, so this might be unrelated to the update.

It seems there's an `INFO` log that gives more info about the room / user:

https://github.com/matrix-org/synapse/blob/v1.21.1/synapse/handlers/message.py#L1245-L1248

**Comment by davidmehren** [comment]
I observed the metrics and logs over the last few days, but these CPU spikes did not appear again. So they really seem to have been random :thinking:
I'll close this for now and reopen if they appear again.
