### ISSUE TITLE
Jitsi slow more then 2 users

### ISSUE THREAD

**Issue by masterwotikar** [matrix-org/synapse#8540]
Recently upgraded to the latest version of matrix synapse op ubuntu 18.04. Everthing is working except when we join a room with more than 2 users with Jitsi it becomes terribly slow.

I've searched with google but could not find anything that could help me out.

What can we do about it?

**Comment by clokep** [comment]
Synapse doesn't directly integrate with Jitsi, so this seems unrelated to Synapse.

Jitsi does switch from P2P connections to using a video bridge when there's 3 or more users in the same call, however. So this likely means that the Jitsi in use is overloaded.
