### ISSUE TITLE
Reactivate account API request - endpoint address?

### ISSUE THREAD

**Issue by JOJ0** [matrix-org/synapse#8543]
Hi, I found this pull-request which is already merged into the synapse version I am using on my homeserver: https://github.com/matrix-org/synapse/pull/7908

What is the API endpoint to send the request to? It's pretty urgent as I accidentally deactivated my main-account on my homeserver while playing around with my API shellscripts. I still have another admin account to send the "reactivate-request" to the API though.

I tried curls against endpoint addresses like this but no luck so far. Couldn't find it in the code either....didn't search extensively though....

https://my-hs.fqdn/_matrix/client/r0/admin/activate/%40${USER}%3Amy-hs.fqdn?access_token=${TOKEN}"

https://my-hs.fqdn/_matrix/client/r0/admin/reactivate/%40${USER}%3Amy-hs.fqdn?access_token=${TOKEN}"

PS: Sorry for cross-posting (I sent to the original pull-request as well but then figured that probably it might not be the right place to ask questions like "how to use this new feature?"

**Comment by clokep** [comment]
@JOJ0 I already answered your question in https://github.com/matrix-org/synapse/pull/7908#issuecomment-708338470

Please see the documentation https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst?rgh-link-date=2020-10-14T11%3A22%3A48Z#create-or-modify-account and note how it tells you to set the access token: https://github.com/matrix-org/synapse/blob/master/docs/admin_api/README.rst

In general questions like this should go to #synapse:matrix.org.

**Comment by JOJ0** [comment]
thanks so much for your answer! I just found the correct docs a moment ago but was too unpatient, probably because of my stupid incident, and filed this issue.

yes it was kind of an emergency solution to ask for support via github issue as compared to accessing matrix.org with a newly created temporary user. that seemed tedious.  sorry for not taking the proper path! thanks again! I'll close this one.

also a hint for others:

the documentation for deactivation is here:

https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-account-deactivate

but the documentation for reactivation is found somewhere else:

https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst?rgh-link-date=2020-10-14T11%3A22%3A48Z#create-or-modify-account

the reason seems to be that deactivation can be done using the client-server api but also the admin api! reactivation of an account is done via the admin api and just modifying the account. there is no separate "reactivate" api command

**Comment by JOJ0** [comment]
Sorry for bothering again but it still is kind of an emergency situation. I successfully reactived my user-account on myhomeserver. I already joined #synapse:matrix.org but it seems it is unclear what deacitvation and reactivation actually does - thus we need a developers opinion/knowledge:

The issue is that when I rejoin encrypted rooms I can successfully join but then see a very empty room - all history is gone even though the room settings state that everybody should see history. And it is not the view everybody know when the keys for the room are missing "cannot decrypt message ......." - I just don't see any undecryptible messages. 

Somebody mentioned that my client "Element-Web" does just hide undecryptable messages - How could I force element to show undecryptable messages.

Second question: How could I rerequest all room-keys from other clients? 

Thanks so much in advance!

**Comment by clokep** [comment]
I didn't look too deeply, but you can [take a look at the code that runs when you deactivate an account](https://github.com/matrix-org/synapse/blob/629a951b49ae58af43323e6829cf49d7452ebf39/synapse/handlers/deactivate_account.py#L53-L141). It deletes various devices and access tokens and such but I'm not sure what impact that will have on previously encrypted messages. I think you should be able to recover them if you used key backup.

**Comment by JOJ0** [comment]
Update on this one:

Now that I asked some friends to reinvite me in some more encrypted rooms I can report that I could decrypt messages in those rooms flawlessly.

I still have the "empty room" problem in one room though - Thanks to #synapse:matrix.org I got some clues that maybe it is element-web that is just hiding rooms where it can't decrypt all (or just some?) messages and that I could try another client! I installed fluffychat on my ipad and immediately a lot of undecrypted messages showed up and I just had to press the re-request keys button and they decrypted properly After that also Element-iOS started to slowly show the messages in this room and they where successfully decrypted.

So the problem is: Element-Web - still I don't see any messages at all in this room, well except new ones of course that happened after my re-join.

I understand that this shouldn't be a matrix-synapse concern anymore, it's not it's fault but if you know it by heart give me some advice: Is there any configuration option to turn off Element-Web's "hiding of undecryptable messages"? I also recall that this behaviour was not always like this - element-dev's must have changed this at some point. To me this currently feels like doing more trouble than good so I think it's best to open an issue for element-web.

Something else: Thanks for pointing me to the deactivation code - At least now I found out what to look for in my homeserver.log - it clearly states all id's of the room's it kicked me from. this helps a lot but brings me to my next questions (I tried #synapse-admin already, with no luck and it now fits into this issue I think: How could I join all those rooms again if I am not a member anymore: The client-server api has invite and join methods but they only work for users that are members of those rooms already. I tried the admin api as well but also here the docs state that the admin user must be part of the room already (https://github.com/matrix-org/synapse/blob/master/docs/admin_api/room_membership.md).

Is it really the only way to ask people in those room to send me an invitation? No way doing it using an admin user?

thanks again!!!

**Comment by clokep** [comment]
> How could I join all those rooms again if I am not a member anymore: The client-server api has invite and join methods but they only work for users that are members of those rooms already.

I think you want the [join API](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-rooms-roomid-join).

> I tried the admin api as well but also here the docs state that the admin user must be part of the room already ([`master`/docs/admin_api/room_membership.md](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/room_membership.md?rgh-link-date=2020-10-15T17%3A25%3A25Z)).

There's no admin API to have a user join a room.

I'm going to close this. This isn't the right forum for support. Please use #synapse:matrix.org.

**Comment by JOJ0** [comment]
Hi, yes sure please close this. thanks. 

@synapse-admin matrix room: up to now i have the feeling that i'm  _not_ fixing my own problem but have helping others there ;-)))

anyway, just so other people that come accross this let's answer this usefully here (please correct me if i am wrong): neither by using the admin api nor by using the room join api it is possible to rejoin a room one was previosuly member of. this is what the room join api tells me:

```
{
    "errcode": "M_FORBIDDEN",
    "error": "You are not invited to this room."
}
```

so the only way to rejoin a room is by asking others to send an invitation. again: please correct me if this statement is wrong. thanks a lot!
