### ISSUE TITLE
Replace message events are not redacted

### ISSUE THREAD

**Issue by em0lar** [matrix-org/synapse#8552]
### Description

Remove a message that has been edited before only redacts the original events not the replace message events. This events can be seen when activating "Show hidden events" and may contain details that should have been removed (maybe secrets).

I expect that the replace message events are also redacted.

### Steps to reproduce

- (in element) Activate "Show hidden events in timeline"
- Write a message
- Edit this message
- Redact/Remove the message
- See that that the replace message event exists and is not redacted

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.labcode.de
<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.21.1

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian LXC Container
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/synapse/issues/5594
