### ISSUE TITLE
Add debian packaging to CI

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#8555]
We keep breaking the debian package builds, which is annoying when trying to release.

We may want to consider just running this on develop/release branches to save resource?

Presumably we don't want to use the debs built in CI, in case they get compromised?

**Comment by anoadragon453** [comment]
@richvdh mentioned an alternative which was to build debian packages on RC's as well - which would allow us to catch issues sooner on less important releases.

**Comment by richvdh** [comment]
not so much an alternative, as something that might be nice to do in addition

**Comment by richvdh** [comment]
(for links: https://github.com/matrix-org/synapse/issues/6116 is about packaging RCs)

**Comment by callahad** [comment]
For CI, which Debian / Ubuntu release do we want to build for?

Building for _all_ releases seems slow and wasteful.

The stable releases should be... stable. So I suspect building for `testing` in CI would be the best way to catch breakage. And in fact, *only* builds on `testing` failed for #9073

**Comment by richvdh** [comment]
counterpoint: we're more likely to accidentally introduce an incompatibility with an old distro.

suggested compromise: build for oldest-supported distro *and* `sid` ?

**Comment by callahad** [comment]
#9073 worked on `oldstable`, `stable`, and `sid`, but *not* on `testing`

So let's go with oldest supported + `testing` rather than `sid`?

**Comment by richvdh** [comment]
with the exception of that one datapoint, it feels like working on `stable` and `sid` but not `testing` would be more unusual than it working on `testing` but not `sid`, but I don't feel too strongly.
