### ISSUE TITLE
MAU prometheus metrics are broken

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#8573]
### Description

> uh, t2bot.io's MAU count was reset with a synapse upgrade
> it went from 1.20.0 to 1.21.2, and now there's only 38 active users apparently. 
> this is a big difference from the ~1 million it was before
> hmm... the stats are still in the database - did the metrics change?
> I've been using `synapse_admin_mau:current{job="synapse",instance="t2bot.io"}` as the query, which seems to be permanently stuck at 38?

### Steps to reproduce

Unclear.

### Version information

- **Homeserver**: t2bot.io

If not matrix.org:

- **Version**: now 1.21.2, up from 1.20.0 (with unrelated patches)
- **Install method**: pip
- **Platform**: differs

**Comment by turt2live** [comment]
because t2bot.io doesn't use MAU limiting, these are the settings as defined in `homeserver.yaml`:

```yaml
track_appservice_user_ips: true
mau_stats_only: true
```

**Comment by richvdh** [comment]
apparently this was a deliberate change due to #8404. It's... regrettable... that that didn't get called out in the changelog.

**Comment by turt2live** [comment]
This is intentional from the looks of it. https://github.com/matrix-org/synapse/pull/8404 changed how the metric works, breaking the new metrics that t2bot.io is looking for into `synapse_admin_mau_current_mau_by_service`.

Seems the `:current` metric used in the issue description is for non-appservice users now.
