### ISSUE TITLE
Prefer psycopg2-binary over psycopg2

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8579]
**Description:**

`psycopg2-binary` distributes far more wheels than `psycopg2`, it's both maintained by the same people, and has the same source tarball contents (except top-level package name changes in `PKG-INFO`, `setup.py`, and `.egg-info` files).

Allowing `pip` to access a far richer range of wheels to choose from when installing will make installing synapse from source more accessible to more platforms (because build errors or `python*-dev` dependencies will not be present).

**Comment by richvdh** [comment]
This has come up before, and at the time we noted that https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary advises sticking with the source distribution.

**Comment by ShadowJonathan** [comment]
Interesting, i'll close this issue then, because some notes there (library compatibility, especially `ssl`) are definitely good points why to use the source distribution over the binary one
