### ISSUE TITLE
Add note in CONTRIBUTING.md about ways to run the mypy type checker.

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#8601]
Per @clokep's [comment](https://github.com/matrix-org/synapse/pull/8583#pullrequestreview-512623006), maybe adding something along the following lines to `CONTRIBUTING.md` would be nice:

- Something about being able to use `tox -e mypy` to do a isolated lint check.

- Something about being able to do `pip install -e .[mypy]` to install the right mypy version in venv, to be able to execute `mypy` by itself (which can be faster than running it through `tox`)

**Comment by devanshushah1** [comment]
> Per @clokep's [comment](https://github.com/matrix-org/synapse/pull/8583#pullrequestreview-512623006), maybe adding something along the following lines to `CONTRIBUTING.md` would be nice:
> 
> * Something about being able to use `tox -e mypy` to do a isolated lint check.
> * Something about being able to do `pip install -e .[mypy]` to install the right mypy version in venv, to be able to execute `mypy` by itself (which can be faster than running it through `tox`)

i agree
