### ISSUE TITLE
[Issue] In a scenario where users only use web clients, the E2EE does not fully work.

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#8624]
matrix-js-sdk: v8.5.0
synapse: v1.21.2

In a scenario where users only use web clients, the E2EE does not fully work.

Decrypting messages in conversations only works if the recipients are online while the sender is sending the encrypted messages. If the receiver is offline while the sender is sending a message, the error below will be displayed:

`logger.js:50 Error in DecryptionError[msg: The sender's device did not send us the keys for this message, session:`

Meaning, the message could not be decrypted.

In the case of the Element Web Client, a user can request the key, but in a scenario where users use only Web clients that do not permanently store the key "locally", this message can never be read. Moreover, the sender does not know that his message could not be read by the recipients.

This is a user experience that is unacceptable to users especially in scenarios where these messages are critical. And you cannot force them to use mobile clients just to get it working. 

Are there any shortterm plans to fix this issue?

**Comment by clokep** [comment]
I believe that this will be fixed by matrix-org/matrix-doc#2697, which allows for an offline device to be used in E2EE if all devices are logged off.

**Comment by menturion** [comment]
@clokep 

Many thanks, I'm really happy to hear this. 

I hope that this will be implemented in such a way that this kind of fallback (dehydrating/rehydrating devices) will work out of the box for existing clients (here: based on the JS SDK).

**Comment by menturion** [comment]
@clokep 

Do you know whether device hydration is already fully implemented? 

I implemented some code to test device hydration. In my case setting the dehydration key is successfully done through "setDehydrationKey".

However, calling "rehydrateDevice" does not call the crypto callback "getDehydrationKey" which causes that the dehydration cache isn't set which is needed to unlock secret storage with the dehydration key. As a result device hydration seems not to work.

Is this an issue or simply not (fully) implemented yet?
