### ISSUE TITLE
We don't send push notifications for invites from remote servers (for rooms the local server isn't in).

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#8626]
The invite comes in via federation `/invite` and gets persisted as an outlier. This flow bypasses the `handle_push_actions_for_event` code.

```python
    def test_remote_invite_sends_email(self):
        fed_handler = self.hs.get_federation_handler()

        fake_invite = {
            "auth_events": ["$dfdjslfdkf", "$sdfdjflsjoiy"],
            "prev_events": ["$sdfdjflsjoiy"],
            "type": "m.room.member",
            "state_key": self.user_id,
            "content": {"membership": "invite"},
            "sender": "@test:remote.example.com",
            "room_id": "!soom_room:remote.example.com",
            "depth": 3872,
        }

        testkey = signedjson.key.generate_signing_key("ver1")

        invite_event = create_local_event_from_event_dict(
            self.clock,
            hostname="remote.example.com",
            signing_key=testkey,
            room_version=RoomVersions.V6,
            event_dict=fake_invite,
        )

        self.get_success(
            fed_handler.on_invite_request(
                "remote.example.com", invite_event, RoomVersions.V6,
            )
        )

        # We should get emailed about the invite
        self._check_for_mail()
```

Is a unit test failing, if added to `tests/push/test_email.py`

**Comment by richvdh** [comment]
is this the same as #8531?

**Comment by erikjohnston** [comment]
Oh, yes I think so (.. how did that not come up in my search :confused: )

**Comment by richvdh** [comment]
related: #8605 ?

**Comment by erikjohnston** [comment]
Ish, though it's a different bug with probably a different fix

**Comment by Bubu** [comment]
I've worked on [a solution](https://gitlab.com/famedly/company/backend/services/synapse/-/commit/ca4840383f7bcfe906914b9d6762c304a19648f9) to this a while back but wasn't happy enough with it to start the upstreaming process. 

My totally naïve approach to this was bypassing the database persistence for this narrow case of push notifications and triggering pushers directly as synapse receives the event over federation. I'm now wondering if this approach has any chance of being applicable for merging.

The current iteration also is restricted to http pushers, but I'm currently working on making it more general.
