### ISSUE TITLE
500 ISE when trying to join a room with a URL as the servername

### ISSUE THREAD

**Issue by joepie91** [matrix-org/synapse#8650]
### Description

When attempting to join `#!:http://matrix.org` (exactly as written), eg. after a botched copy-paste from something that auto-inserts `http://`, this results in a 500 M_UNKNOWN error rather than a validation error like I would expect.

### Steps to reproduce

- Go to 'explore public rooms'
- Enter `#!:http://matrix.org`
- Click 'join'

### Version information

- **Homeserver**: pixie.town

If not matrix.org:

- **Version**: Synapse 1.21.0

- **Install method**: Unknown, not my Synapse

- **Platform**: Unknown, not my Synapse

**Comment by richvdh** [comment]
I think this is basically the same as #1424

**Comment by anoadragon453** [comment]
Indeed, and closing as such. I've added a `validation` tag to the other issue so it doesn't get completely lost in the ether.
