### ISSUE TITLE
Add support for HTTPS proxy for federation requests

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#8660]
This will be helpful for certain use cases, but mainly I'd like to see if using one reduces CPU usage for small servers that end up making lots of connections at once.

**Comment by richvdh** [comment]
> but mainly I'd like to see if using one reduces CPU usage for small servers that end up making lots of connections at once.

I can't really see how it will help on that front. We can't offload the SSL to the proxy, thanks to the way SRV records and TLS certs interact, so my feeling is that the proxy will do nothing but add overhead.
