### ISSUE TITLE
Allow shutdowns of rooms using the admin api without replacement rooms

### ISSUE THREAD

**Issue by miterion** [matrix-org/synapse#8662]
**Description:**
Currently, the `/_synapse/admin/v1/shutdown_room/{room_id}` admin api moves all users to a new or existing room upon calling.
It is not possible to avoid this by simply omitting the `new_room_user_id` parameters, as can be done when using the `/_synapse/admin/v1/rooms/<room_id>/delete` endpoint.

Since the underlying code (`RoomShutdownHandler`) already supports the omission of `new_room_user_id` I think it is sufficient to just remove the restrictions currently in place and update the documentation to fix my issue.

**Comment by dklimpel** [comment]
Why do you not switch to the new API `/delete`?
There are all options what you looking for.

**Comment by miterion** [comment]
`/debug` does not work for me probably due to bug in either synapse or my configuration. I looked for alternatives and found the `/shutdown` endpoint and noticed the discrepancy between their parameters.
If it is intended to drop the `/shutdown` endpoint then please close this issue.

**Comment by anoadragon453** [comment]
@miterion We had a discussion in `#synapse-dev` from this issue, and yes, we've decided to do exactly that: https://github.com/matrix-org/synapse/issues/8663 :wink:
