### ISSUE TITLE
Decision Needed: Default to a newer Python in our Dockerfile?

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#8674]
This was raised as part of discussing #8665: We support Python 3.5 through 3.9, but our Dockerfile default is Python 3.7.

Is there any particular reason for this, or should we go full steam ahead with the latest supported Python version in our Dockerfiles since we effectively control that environment?

**Comment by ShadowJonathan** [comment]
it's a bit balanced between "which python versions are likely to be cached locally as images?" (deduplication) and "which versions do we trust the most/do we think have the most benefit with performance and the like?" (as effectively support and benefit of 3.5 through 3.9 is indistinguishable)

Imo: Latest python release - 1 minor version

**Comment by maquis196** [comment]
were only talking a few meg on that python layer tbh, debian-slim takes up the vast chunk of it (And didnt provide the precompiled wheels we were hoping for). Whatever version is stable, might as well (id argue keeping it at the same version as the latest ubuntu LTS or something as well, so at least any bugs would be global is how id see it - which in this case is 3.8)

**Comment by callahad** [comment]
> the same version as the latest ubuntu LTS or something

Ah, but _which_ something 😉

| Distro | Python |
| - | - |
| RHEL 8 | 3.6 |
| Debian 10 | 3.7 |
| Ubuntu 20.04 | 3.8 |

If the latest version of Python is _x.y_, I'm inclined to go with _x.(y-1)_. This gives us a very recent version of Python, but also one which has been around long enough for the broader ecosystem to adapt to any changes it introduces.

**Comment by maquis196** [comment]
Im in favour of 3.8 since that matches 20.04 and matches the y-1 rule. Seems a win all round to me :). Alas, ill leave that to the grown ups!
