### ISSUE TITLE
Rate limit key share requests

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#8677]
There is a bug in one of the clients that causes a lot of *cross user* key share requests, which then stacks up in the `device_inbox` for devices leading to issues on clients (potentially, maybe). These should be both relatively rare and safe to drop, so we should rate limit them.

We may also want to consider dropping key share requests to devices that already have a large (ish) number of device messages in their inbox.

We should back out https://github.com/matrix-org/synapse/pull/8675 after this is done.

**Comment by clokep** [comment]
I'm guessing the work is something like:

1. Add a new rate limiter for incoming federation EDUs.
2. Replace the patch in `federation_server.py` from #8675 with a check for the rate-limiter. If over the limit, drop the request.
3. Replace the patch in `devicemessage.py` from #8675 with a check for the rate-limiter, raising a 429 if over the limit?
3. Add tests.

Does something like that sound about right?
