### ISSUE TITLE
roles mapping with keycloak openid sso

### ISSUE THREAD

**Issue by makayabou** [matrix-org/synapse#8687]
### Description

I used doc to connect synapse users via keycloak openidconnect protocol.

users can connect and new users are created at first signin.

The problem is that roles from keycloak are not mapped to synapse. 

I tried also with saml connect (following https://edenmal.moe/post/2019/Matrix-Synapse-SAML2-Login/) and groups where mapped: user member of admin group in keycloak was granted admin in synapse.

I guess it's just a mapper to create in keycloak client but what would be groups identifier in synapse?

Thanks

### Version information
Server v 1.21.2
installation via ansible on Debian 10 amd64

**Comment by clokep** [comment]
I do not believe that any of our SSO solutions (OpenID, SAML, or CAS) have a way to automatically grant admin privileges to users.

**Comment by makayabou** [comment]
Oups, you're right, my bad.
