### ISSUE TITLE
Document bind_addresses for workers

### ISSUE THREAD

**Issue by zzottel** [matrix-org/synapse#8699]
### Description

If workers are configured according to https://github.com/matrix-org/synapse/blob/develop/docs/workers.md , they emit the following warning in the log:

`WARNING - - Failed to listen on 0.0.0.0, continuing because listening on [::]`

If synctl is used and thus a "worker" for the main process is required, the same warning is issued there, but Synapse is still listening on the configured IPv4 ports on all interfaces. However, there are no listeners on IPv4 ports for the actual workers.

### Steps to reproduce

- Configure workers with the example configuration in https://github.com/matrix-org/synapse/blob/develop/docs/workers.md

### Version information

Synapse 1.22.1 on Debian 10.6

### Solution

Add `bind_addresses: ['127.0.0.1']` or similar for IPv6 to the worker_listeners section of the example configuration.

**Comment by localguru** [comment]
I had the same problem like @zzottel and setting `bind_addresses: ['127.0.0.1']` in share configuration in homeserver.yaml and in each worker config is my workaround too.

**Comment by erikjohnston** [comment]
Sorry, I'm a bit confused what's happening here. The error:

`Failed to listen on 0.0.0.0, continuing because listening on [::]`

should imply that it's correctly listening on all interfaces, both IPv4 and IPv6 (normally if you fail to bind on `0.0.0.0` after binding on `[::]` its because you're running with dual stack support). Does `netstat -nltp` show the server listening on the expected ports?

**Comment by zzottel** [comment]
What do you mean by dual stack support? Dual stack in the OS or in Twisted or where?

The OS is running with both IPv4 and IPv6 active. I had looked with `lsof -i` which processes are listening on which ports. The main process was listening on both IPv4 and IPv6, but the worker processes only listened on IPv6.

**Comment by erikjohnston** [comment]
> What do you mean by dual stack support? Dual stack in the OS or in Twisted or where?

Dual stack is an OS thing where if you bind on `[::]` then it automatically binds to the IPv4 `0.0.0.0` address as well. 



> The OS is running with both IPv4 and IPv6 active. I had looked with `lsof -i` which processes are listening on which ports. The main process was listening on both IPv4 and IPv6, but the worker processes only listened on IPv6.

Huh, odd that it works for the main listener and not the worker listeners. Could you share your `listeners:` and `worker_listeners:` config options please?

**Comment by richvdh** [comment]
we seem to be lacking the information needed to pursue this.
