### ISSUE TITLE
Add a way to close/shutdown room as room admin

### ISSUE THREAD

**Issue by FanchTheSystem** [matrix-org/synapse#8717]
**Description:**
As suggested here https://github.com/matrix-org/synapse/issues/8663

Maybe synapse should allow to close/shutdown unused room. 

The use case are simple and very common: 
- Example 1: 
Two(or more) users create a room about the same topic/subject. One day they meet, and they decide to join their efforts.
So they would want to close one of the two room, and inform people that the chat continue in the other room.

- Example 2:
One community (maybe with user on distinct server) have a lot of room, they want to re-organize them, close some old one, and create some new one. They would want to disable message on the old one, and inform user where they can continue.

As you can see in both example, user would want to keep the history of old room, and redirect discussion to a new room.

Also, I think a lot of new user and/or new group of user who discover matrix will create a lot of useless room until they discover similar room exist elsewhere. We can see it every day :) Often they ask a way to "repair" their mistake. Ability to close created room may help for this.

Add a api call to allow to close a room, with following POST body : 
```
{
    "access_token": "ArOoMaDmInToKeN", 
    "new_room_id": "#newroom:example.com",
    "message": "This room is no more used, please follow the white rabbit"
}
```

where **access_token** is a room admin token, **new_room_id** is the id where you want to redirect the user, and **message** the message to show in the bottom banner of the old room

Maybe It should also disable message for normal user (set the according right), and auto transfer the room alias.

Maybe **new_room_id** could be optional. (if you have nowhere to redirect user)

It should be almost the same as the "upgrade" room command, but with a destination room which already exist.
https://github.com/matrix-org/matrix-doc/blob/master/proposals/1501-room-version-upgrades.md.

Another command which is similar is "shutdown" room https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/shutdown_room.md , it should be almost the same but with a room admin instead of a server admin.

**Comment by erikjohnston** [comment]
FWIW you can get a similar ish result for by changing the power levels so only admins can send messages and then use an `@room` bing to tell everyone what's going on.

To add an API to the spec you're probably better off first proposing it as part of the spec (at https://github.com/matrix-org/matrix-doc/), otherwise this would be a Synapse specific API, which clients tend not to implemnt.

**Comment by erikjohnston** [comment]
I'm going to close this for now, but feel free to open something in matrix-docs repo :+1:
