### ISSUE TITLE
Allow restriction of publishing to the room directory to server admins only

### ISSUE THREAD

**Issue by benbz** [matrix-org/synapse#8724]
**Description:**

I have a need to restrict publishing to the room directory to server admins only. The question was originally asked by @benparsons  about restricting room creation to server admins only and we were pointed in the direction of the Spam Checker API. For room creation, the spam checker API is [short circuited if the user is a server admin](https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/room.py#L611). For directory publishing, the spam checker is [always consulted](https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/directory.py#L412).

The `ModuleApi` that the spam checker receives doesn't appear to have direct, public access to `auth.is_server_admin` and #7331 suggests that I couldn't use the private [_auth](https://github.com/matrix-org/synapse/blob/develop/synapse/module_api/__init__.py#L50) in `ModuleApi` to do this as the spam checker isn't async. The other suggestion from #7331 to use `third_party_rules` also doesn't seem workable in this situation as [check_visibility_can_be_modified](https://github.com/matrix-org/synapse/blob/develop/synapse/events/third_party_rules.py#L126) (which is consulted late on in directory publishing) also doesn't know whether the user is an admin or not (unlike [on_create_room](https://github.com/matrix-org/synapse/blob/develop/synapse/events/third_party_rules.py#L79)).

Similarly [config.room_directory.is_publishing_room_allowed](https://github.com/matrix-org/synapse/blob/develop/synapse/config/room_directory.py#L134) doesn't know whether the user is an admin or not. I could update homeserver.yaml with a list of user ids that match the list of server admins, but that feels very redundant and not maintainable.

Am I reading & understanding this all correctly? If I submitted a PR to short-circuit the spam checker for admins in the case of directory publishing would that have a reasonable change of being accepted? Or is there another approach you'd prefer me to take?

Thanks

**Comment by erikjohnston** [comment]
I think it should be fine to always short circuit for the spam checker. I think we'd probably not want to do that for third party rules, though, since we probably don't want server admins to be able to bulldoze through any custom restrictions they've added (at least without doing so on purpose).

**Comment by babolivier** [comment]
Modules have evolved quite a bit since this issue was opened. Nowadays the spam checker callbacks include [`user_may_publish_room`](https://matrix-org.github.io/synapse/latest/modules/spam_checker_callbacks.html#user_may_publish_room) which allow controlling whether a given user can publish a given room to the room directory, and the module API offers a [`is_user_admin`](https://github.com/matrix-org/synapse/blob/8d317f6da5aa2efc030990c7036cdb4f384c704a/synapse/module_api/__init__.py#L548-L559) method. So this restriction can be implemented by a module, which seems to be the main request here.
