### ISSUE TITLE
FTUE: Too many requests have been sent (join rate limit)

### ISSUE THREAD

**Issue by vranki** [matrix-org/synapse#8735]
### Description

Rate limit for joins from other homeservers is way too tight in Synapse default configuration.

### Steps to reproduce

Real situation:
 - User registers to homeserver and joins a room via another homeserver.
 - User is given room pills to join a few more interesting rooms.
 - User tries to join rooms with pills and is greeted with "Too many requests have been sent" error.

This was discussed on Synapse Room and looks like these settings are to blame:

https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml#L828-L834

These limits are way too tight and as this affects FTUE, I'd take the issue seriously. 
I won't guess better values here but the "new user joining multiple rooms from remote server" 
scenario should not cause errors.

### Version information

Synapse 1.22.1

**Comment by clokep** [comment]
This was recently increased from a burst of 3 to a burst of 10. For the moment I'm going to say this is "done", but there might be more we can do besides just updating the default rate limits.
