### ISSUE TITLE
device list update for own user when sending first message in a room with given device

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#8737]
Whether in e2ee or non-e2ee rooms, I get see my own user in `device_lists.changed` every time I write for the first time in a room with a new login. It doesn't break anything, but seems unnecessary and causes clients to do excessive key queries.

**Comment by erikjohnston** [comment]
Was this causing actual issues? We have taken the view that spurious device lists updates are OK so long as they happen rarely, is that not the case?

Related: #6162

**Comment by bwindels** [comment]
It was not, thought it was still good to report as I wasn't aware of how these are handled. Closing accordingly.

**Comment by erikjohnston** [comment]
Ok, thanks. I think the spurious updates are tracked by the other issue :+1:
