### ISSUE TITLE
Help with local setup using Docker and Keycloak OIDC

### ISSUE THREAD

**Issue by lambdaclan** [matrix-org/synapse#8741]
## Description

Hello I am trying to setup a local development environment with matrix synapse and keycloak as OIDC through Docker. The OIDC setup is giving me some trouble. 

> Error sending request to  GET https://keycloak:8443/auth/realms/awesome/.well-known/openid-configuration: RequestTimedOutError 504: Timeout waiting for response from remote server

Any idea what might be causing the timeout?

All 3 services (**reverse proxy**, **keycloak** and **synapse**) are running in isolation and i use an external network to make them communicate . Both keylcoak and synapse are also running through https with self signed certs. Executing curl `https://keycloak.local/auth/realms/awesome/.well-known/openid-configuration` from the host or the synapse container with OIDC disabled returns the configuration as expected.

Initially I was also getting an SSL issue which I am assuming has been fixed by recent changes to the synapse docker image?

I have tried using [mkcert](https://github.com/FiloSottile/mkcert) to generate the certificates on my own as well as out of the box custom DNS servers like [traefik.me](https://traefik.me/) to avoid messing up with /etc/hosts.

The problem arises the moment I enable OIDC support in the synapse homeserver.yaml file but I am not sure if it is a synapse issue or a docker networking setup issue that is causing the errors.

### Keycloak setup:

![image](https://user-images.githubusercontent.com/47409392/98764932-3adc4680-2420-11eb-89fe-75d5a8139822.png)

![image](https://user-images.githubusercontent.com/47409392/98764969-4fb8da00-2420-11eb-95c2-dca58423973e.png)

![image](https://user-images.githubusercontent.com/47409392/98764993-619a7d00-2420-11eb-81ac-960ac4de1ffd.png)

![image](https://user-images.githubusercontent.com/47409392/98765014-6f500280-2420-11eb-80d6-92e5d4f6c0c7.png)

### Synapse setup (OIDC disabled)

![image](https://user-images.githubusercontent.com/47409392/98765164-cfdf3f80-2420-11eb-82e3-4b8f3a5b2a11.png)

![image](https://user-images.githubusercontent.com/47409392/98765173-d968a780-2420-11eb-981b-8c45cc690b4a.png)

![image](https://user-images.githubusercontent.com/47409392/98765202-f00efe80-2420-11eb-877d-fd204ca7d276.png)

enabling OIDC:

```yaml
oidc_config:
  # Uncomment the following to enable authorization against an OpenID Connect
  # server. Defaults to false.
  #
  enabled: true
  # issuer: "https://172.19.0.3:8443/auth/realms/awesome"
  issuer: "https://keycloak:8443/auth/realms/awesome"
  client_id: "synapse"
  client_secret: "ccac0277-2702-42f2-ac26-fe6a1f68a1c1"
  scopes: ["openid", "profile"]
```

```
synapse_1  | 2020-11-11 02:38:20,942 - synapse.http.client - 391 - INFO -  - Error sending request to  GET https://keycloak:8443/auth/realms/awesome/.well-known/openid-configuration: RequestTimedOutError 504: Timeout waiting for response from remote server
synapse_1  | 2020-11-11 02:38:20,942 - twisted - 250 - ERROR -  - Error during startup:
synapse_1  | 2020-11-11 02:38:20,942 - twisted - 250 - ERROR -  - Traceback (most recent call last):
synapse_1  | 2020-11-11 02:38:20,942 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
synapse_1  | 2020-11-11 02:38:20,943 - twisted - 250 - ERROR -  -     current.result = callback(current.result, *args, **kw)
synapse_1  | 2020-11-11 02:38:20,943 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
synapse_1  | 2020-11-11 02:38:20,943 - twisted - 250 - ERROR -  -     _inlineCallbacks(r, g, status)
synapse_1  | 2020-11-11 02:38:20,943 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
synapse_1  | 2020-11-11 02:38:20,943 - twisted - 250 - ERROR -  -     result = result.throwExceptionIntoGenerator(g)
synapse_1  | 2020-11-11 02:38:20,943 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
synapse_1  | 2020-11-11 02:38:20,944 - twisted - 250 - ERROR -  -     return g.throw(self.type, self.value, self.tb)
synapse_1  | 2020-11-11 02:38:20,944 - twisted - 250 - ERROR -  - --- <exception caught here> ---
synapse_1  | 2020-11-11 02:38:20,944 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 426, in start
synapse_1  | 2020-11-11 02:38:20,944 - twisted - 250 - ERROR -  -     await oidc.load_metadata()
synapse_1  | 2020-11-11 02:38:20,944 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/oidc_handler.py", line 245, in load_metadata
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -     metadata_response = await self._http_client.get_json(url)
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 521, in get_json
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -     body = await self.get_raw(uri, args, headers=headers)
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 603, in get_raw
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -     response = await self.request("GET", uri, headers=Headers(actual_headers))
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 374, in request
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -     response = await make_deferred_yieldable(request_deferred)
synapse_1  | 2020-11-11 02:38:20,945 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
synapse_1  | 2020-11-11 02:38:20,946 - twisted - 250 - ERROR -  -     current.result = callback(current.result, *args, **kw)
synapse_1  | 2020-11-11 02:38:20,946 - twisted - 250 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 694, in _timeout_to_request_timed_out_error
synapse_1  | 2020-11-11 02:38:20,946 - twisted - 250 - ERROR -  -     raise RequestTimedOutError("Timeout waiting for response from remote server")
synapse_1  | 2020-11-11 02:38:20,946 - twisted - 250 - ERROR -  - synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
synapse_1  | 2020-11-11 02:38:20,946 - synapse.handlers.presence - 327 - INFO - presence.on_shutdown-0 - Performing _on_shutdown. Persisting 0 unpersisted changes
synapse_1  | 2020-11-11 02:38:20,947 - synapse.handlers.presence - 338 - INFO - presence.on_shutdown-0 - Finished _on_shutdown
synapse_1  | 2020-11-11 02:38:20,948 - twisted - 250 - INFO -  - Main loop terminated.
synapse_1  | 2020-11-11 02:38:20,993 - twisted - 250 - CRITICAL -  - Unhandled error in Deferred:
synapse_1  | 2020-11-11 02:38:20,993 - twisted - 250 - CRITICAL -  - 
synapse_1  | Traceback (most recent call last):
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 426, in start
synapse_1  |     await oidc.load_metadata()
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/oidc_handler.py", line 245, in load_metadata
synapse_1  |     metadata_response = await self._http_client.get_json(url)
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 521, in get_json
synapse_1  |     body = await self.get_raw(uri, args, headers=headers)
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 603, in get_raw
synapse_1  |     response = await self.request("GET", uri, headers=Headers(actual_headers))
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 374, in request
synapse_1  |     response = await make_deferred_yieldable(request_deferred)
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
synapse_1  |     current.result = callback(current.result, *args, **kw)
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/http/client.py", line 694, in _timeout_to_request_timed_out_error
synapse_1  |     raise RequestTimedOutError("Timeout waiting for response from remote server")
synapse_1  | synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
synapse_1  | 
synapse_1  | During handling of the above exception, another exception occurred:
synapse_1  | 
synapse_1  | Traceback (most recent call last):
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
synapse_1  |     result = result.throwExceptionIntoGenerator(g)
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
synapse_1  |     return g.throw(self.type, self.value, self.tb)
synapse_1  |   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 441, in start
synapse_1  |     sys.exit(1)
synapse_1  | SystemExit: 1
matrix-synapse-keycloak-element_synapse_1 exited with code 0

```

Here is a [link](https://bin.privacytools.io/?4d61430de8e639c1#bqyWY9zqZVVopHrkcOACjqw/PbFIbNDIo7/suf3k2E4=) to my `homeserver.yaml` file.

I have posted the issue in the matrix channel multiple times (search for keycloak and my posts will pop up) but did not hear back so I decided to open this issue as last resort. Any pointers or feedback would be greatly appreciated. I will also be happy to share more information if necessary such as my docker compose files etc so please let me know.

**Comment by erikjohnston** [comment]
Hmm, it does rather look like Synapse is failing to talk to keycloak. Does executing `curl https://keycloak:8443/auth/realms/awesome/.well-known/openid-configuration` from the synapse container work? I note that you seem to have tested `keycloak.local` whereas synapse is configured with `keycloak:8443`?

**Comment by lambdaclan** [comment]
Hello @erikjohnston 

Thank you very much for following up.

Regarding your question:

>  Does executing curl https://keycloak:8443/auth/realms/awesome/.well-known/openid-configuration from the synapse container work? 

With OIDC disabled yes it does work although it complains about the self-signed certificate. Adding a -k to curl returns the configuration as expected. The image [here](https://user-images.githubusercontent.com/47409392/98765202-f00efe80-2420-11eb-877d-fd204ca7d276.png) is actually from the synapse container. Enabling OIDC makes synapse fail immediately so I cannot really play around with it.

> I note that you seem to have tested keycloak.local whereas synapse is configured with keycloak:8443?

Sorry that is because I have multiple setups. The keycloak.local was when using mkcert and messing up with my /etc/hosts.

I guess sharing a bit of info about my docker setup might clear things out. The reason synapse is configured with keycloak:8443 is because each service is running in its own container and they all share an external network. That way the services are accessible by the container name which happens to be keycloak. That is why from within the synapse container i can get ping keycloak or curl and it works as expected.

Do you want me to share my docker files? I have one for each service. 

- Reverse proxy via traefik and traefik.me to enable https 
- Keycloak
- Synapse

**Comment by clokep** [comment]
I wonder if something is going wrong with DNS on the container such that Twisted isn't resolving that correctly? (The mapping of keycloak to keycloak.local or whatever.) It could be interesting to try to put in an IP and see if that resolves the connectivity issue.

**Comment by lambdaclan** [comment]
Hello @clokep thanks for your input. I did try using an IP directly that is why I was launching each service in isolation so that I can easily control the order of execution.

I first launch the reverse proxy and then Keycloak. After that I use a command to obtain Keycloak's IP as follows:

```
 docker inspect -f "{{ .NetworkSettings.Networks.matrix-synapse-keycloak-element.IPAddress }}" id of custom network
```

Then I set the issuer in `homeserver.yaml` like so:

```
issuer: "https://172.19.0.3:8443/auth/realms/awesome"
# issuer: "https://keycloak:8443/auth/realms/awesome"
```

This results in the same issue as using the domain/container name. 

I am also inclined to believe that the issue might be with Docker networking but want to see if anyone else have managed to make it work somehow.

**Comment by clokep** [comment]
I agree that this smells like a Docker config problem. I'd suggest asking in #synapse:matrix.org and see if anyone else has setup a similar system to this before.

**Comment by lambdaclan** [comment]
Thank you for your feedback. I already tried asking in the #synapse:matrix.org channel multiple times but not luck. I will try again now that I can refer directly to this issue.

**Comment by maquis196** [comment]
the url keycloak, does that point directly at the container or via traefik? If you wanna ping me on matrix I'm happy to help out on this, and if we get it solved we can put the solution and/or write up a readme on it. 

@cmt:msg.maquis196.io

**Comment by lambdaclan** [comment]
Hello @maquis196 thank you for your support, your help is greatly appreciated. I will reach out to you in the synapse channel so that we can discuss further. 

> if we get it solved we can put the solution and/or write up a readme on it

Yes, I feel having a local setup section in the docs makes sense many times we want to try things out before rolling out a production server.

In terms of your question:

> the url keycloak, does that point directly at the container or via traefik?

I currently use traefik.me for DNS resolve and to enable https and the compose file is an adaptation of the example provided here:

https://gist.github.com/pyrou/4f555cd55677331c742742ee6007a73a

just replace app1 and app2 with keycloak and synapse containers.

**Comment by cmt** [comment]
> the url keycloak, does that point directly at the container or via traefik? If you wanna ping me on matrix I'm happy to help out on this, and if we get it solved we can put the solution and/or write up a readme on it.
> 
> @cmt:msg.maquis196.io

Could you please stop mentioning me in your comments? I don't know who you are, neither am part of your project.
Thanks!

**Comment by maquis196** [comment]
> > the url keycloak, does that point directly at the container or via traefik? If you wanna ping me on matrix I'm happy to help out on this, and if we get it solved we can put the solution and/or write up a readme on it.
> > @cmt:msg.maquis196.io
> 
> Could you please stop mentioning me in your comments? I don't know who you are, neither am part of your project.
> Thanks!

Apologies, that identifier is my login on matrix, didnt stop to think github would notify you, I'll try and remember to wrap my address next time on here so it doesnt ping you.

**Comment by benoitmartin88** [comment]
Hi,
Any news on this ?
I've been having the same issue in a kubernetes environment (traefik, keycloak, synapse).
My configuration goes something like this:

```
oidc_config:
  enabled: true
  discover: false
  issuer: "https://auth.gafuk.duckdns.org/auth/realms/master"
  client_id: "synapse"
  client_secret: "2975dbbe-78bd-45ae-8851-a99133e10e0b"
  #client_auth_method: client_secret_post
  scopes: ["openid", "profile"]
  authorization_endpoint: "https://<my.domain.com>/auth/realms/master/protocol/openid-connect/auth"
  token_endpoint: "https://keycloak.default.svc.cluster.local/auth/realms/master/protocol/openid-connect/token"
  userinfo_endpoint: "https://keycloak.default.svc.cluster.local/auth/realms/master/protocol/openid-connect/userinfo"
  jwks_uri: "https://keycloak.default.svc.cluster.local/auth/realms/master/protocol/openid-connect/certs"
```

And I get:

```
2020-12-16 16:22:00,694 - synapse.http.client - 386 - INFO -  - Error sending request to  GET https://keycloak.default.svc.cluster.local/auth/realms/master/protocol/openid-connect/certs: RequestTimedOutError 504: Timeout waiting for response from remote server
```

Note that I can `curl -k https://keycloak.default.svc.cluster.local/auth/realms/master/protocol/openid-connect/certs` this URI and get a jwks.

**Comment by richvdh** [comment]
I'm going to close this, because timeouts from keycloak are out-of-scope for synapse issues, whether they are due to problems in your docker setup or your keycloak installation.

**Comment by pluex1** [comment]
Hey, even if this is closed. We have a similar issue in synapse starting with version 1.26. Maybe this helps.
https://github.com/matrix-org/synapse/issues/9662
