### ISSUE TITLE
Synapse Docker container doesn't start due to prometheus_client version 0.9.0

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#8766]
Version v0.9.0 of the `prometheus_client` python module was [just released](https://pypi.org/project/prometheus-client/#history), and now our docker containers fail with the following:

```
❯ docker run --name synapse \                                                                                                                                                                                        
    --mount type=volume,src=synapse-data,dst=/data \
    -p 8008:8008 \
    matrixdotorg/synapse:latest
ERROR:root:Needed prometheus_client>=0.4.0,<0.9.0, got prometheus-client==0.9.0
Missing Requirements: 'prometheus_client>=0.4.0,<0.9.0'
To install run:
    pip install --upgrade --force 'prometheus_client>=0.4.0,<0.9.0'
❯ 
```

~~We need to investigate why the docker container is installing a version of a module outside of what's specified in [python_dependencies.py](https://github.com/matrix-org/synapse/blob/ceafb5a1c61f699d659b1b38577b1c2264721e28/synapse/python_dependencies.py#L71-L75).~~

Looks like this is due to us installing the library separately without consulting the version requirements: https://github.com/matrix-org/synapse/blob/3dc1871219f845954a4b7d31fc06739831d67d2e/docker/Dockerfile#L34-L46

Currently anyone that builds a Synapse container will be affected, but our release containers built earlier should be fine.

**Comment by anoadragon453** [comment]
A quick fix here is to remove `prometheus-client` from this list, but a longer term fix should somehow apply the version constraints to the items in this list.

**Comment by anoadragon453** [comment]
While we're in the area, we may want to make sure that all the dependencies here are actually still used.

**Comment by ddevault** [comment]
Did anyone consider, I dunno, addressing the breaking changes in Synapse and upgrading to the latest version of prometheus client?

**Comment by anoadragon453** [comment]
@ddevault this was brought up in the linked PR: https://github.com/matrix-org/synapse/pull/8767#issuecomment-728997738

**Comment by ddevault** [comment]
You should not institutionalize a habit of pinning your dependencies as a permanent solution. You should always be aiming to support the latest version of them, and ingrain this at a cultural level.

You're in for a world of hurt if you don't. When you're 6 versions behind on something, and suddenly it matters very much that you be on the latest version, but you have punted for long enough that you've ballooned your work 10x in the middle of a crisis.

**Comment by ddevault** [comment]
Personally, I would not have even merged a pull request like #8767 unless the submitter outlined a plan for upgrading and justified the **temporary** version pinning approach.

**Comment by callahad** [comment]
> You should not institutionalize a habit of pinning your dependencies as a permanent solution. You should always be aiming to support the latest version of them, and ingrain this at a cultural level. You're in for a world of hurt if you don't.

Acknowledged and agreed; we will not treat this as a permanent solution. There's some debt to unravel here, but we'll get there.

**Comment by amalon** [comment]
This now breaks the archlinux package, since python-prometheus_client has updated to 0.9.0 so synapse won't start since its too new.

Oddly when I downgrade prometheus_client to 0.8.0-2 it doesn't detect prometheus_client at all... still trying to figure that one out.

**Comment by clokep** [comment]
I think this can be closed with the follow-up of #8831 filed. @anoadragon453 does that sound correct?

**Comment by jordanbancino** [comment]
@amalon Yep, I just broke my synapse install on Arch too. A simple hack to get up and running again until this is fixed upstream is to change `/usr/lib/python3.9/site-packages/synapse/python_dependencies.py`. Just remove the upper pin on `"prometheus_client"`. Synapse will then start again, so it looks like 0.9.0 didn't break anything.

**Comment by anoadragon453** [comment]
@clokep Indeed this issue pertaining to the Docker container can be closed. Discussion will continue in #8831 for removing the upper pin and ensuring everything still works.
