### ISSUE TITLE
Rooms do not appear in the room directory immediately after they've been added

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#8775]
I bulk added 100 or so rooms to the IETF homeserver today (`trial1-matrix.ietf.org`) and found that after adding the rooms, they could not be searched for locally or externally. I can confirm that the endpoint I used to add them gave me a 200 OK. After joining the room manually via an alias (after leaving it), they then appeared in the listing.

Generally feels like the room directory cache is a bit too aggressive (or at least, certainly for smaller deployments) as I'd expect adding a new room to the directory would invalidate the cache. I've waited about 30 minutes and the rooms have yet to appear.

**Comment by richvdh** [comment]
it should be pretty quick. I suspect that this *wasn't* due to caching, and had some other cause.....

**Comment by Half-Shot** [comment]
I'll rephrase so as to not assume caching

**Comment by clokep** [comment]
> I bulk added 100 or so rooms to the IETF homeserver today (`trial1-matrix.ietf.org`) and found that after adding the rooms, they could not be searched for locally or externally.

Can you describe a bit more how you "bulk added" them? I'll try to reproduce this...

**Comment by Half-Shot** [comment]
I had a script that would iterate over 100 different aliases and would:
- Join the room
- Add the room to the directory with the PUT /directory/list API `visibility: public`.
- Leave the room.

One difference from normal rooms is that these have a canonical alias set, but do not seem to have a local address (`https://matrix-trial1.ietf.org/_matrix/client/unstable/org.matrix.msc2432/rooms/!pRuXVuvRBXmtbNcmFZ%3Amatrix.org/aliases` returns empty).

**Comment by clokep** [comment]
Talked to @Half-Shot a bit about this, it would be interesting to see the rows where of `rooms`, `appservice_room_list`, `room_stats_state`, and `room_stats_current` for a room where this is happening. This should help understand why [`get_largest_public_rooms`](https://github.com/matrix-org/synapse/blob/e8d08537394a49f3e66e9cbea3627e3c25818a7d/synapse/storage/databases/main/room.py#L207-L347) isn't find it in the search.

**Comment by clokep** [comment]
When investigating this further it seems the room isn't appearing due to `is_public` being false in the database. So I think everything is working OK here?

**Comment by Half-Shot** [comment]
I think we can close this for the meantime until I can prove otherwise. Thanks for humouring me @clokep
