### ISSUE TITLE
Docker healthcheck for workers with no http listener

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/synapse#8780]
appservice, fed sender and pusher doesn't listen on any ports on which I could do healthchecks for docker :<

**Comment by clokep** [comment]
Seems reasonable to have a healthcheck endpoint for each worker. Probably could do it via a `health` resource type in the config.

**Comment by JuniorJPDJ** [comment]
Bump?

**Comment by ShadowJonathan** [comment]
This issue is also triggered when the http listener port is non-"default"

See https://github.com/matrix-org/synapse/issues/11472 for a potential fix for this

**Comment by dklimpel** [comment]
An idea for a workaround.

Did you try enable a metrics endpoint? The metrics entdpoint also have an health-listener.
