### ISSUE TITLE
Admin list media API not working?

### ISSUE THREAD

**Issue by jahlives** [matrix-org/synapse#8783]
### Description
New Media API not working?

### Steps to reproduce

- install latest synapse 1.23
- get your admin access token
- use  curl call with access token for GET request /_synapse/admin/v1/room/!myroomid:example.com/media
```
 curl --header 'Authorization: Bearer MYTOKEN' 'http://127.0.0.1:8008/_synapse/admin/v1/room/!myroomID:matrix.example.com/media'
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
Should show a list of media files in the room but does not show any content
```
{
    "local": [],
    "remote": []
}
```


### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: another homeserver

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.23
```
{
    "python_version": "3.6.8",
    "server_version": "1.23.0"
}
```

- **Install method**: pip in virt-env
<!-- examples: package manager/git clone/pip  -->

- **Platform**: centos7
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment]
Was this working in a previous version or are you just trying it now in v1.23.0?

It doesn't look like this API has changed recently, so I'm not sure what could be causing an issue. Are you using a different media repo than the one built into Synapse?

**Comment by jahlives** [comment]
@clokep 
no idea if it worked in previous versions. I read in git that v1.23 will have that api and as soon as it was released I updated to test. We run our homeserver with quite default values, pretty sure we did not change anything related to media repo. I'll check our config to be sure.

**Comment by dklimpel** [comment]
This API is not one of the new APIs in Synapse 1.23.0
I did a test with 1.23.0. It works.
But I have to escape `!` in curl request.
Like: ` curl --header 'Authorization: Bearer MYTOKEN' 'http://127.0.0.1:8008/_synapse/admin/v1/room/\!myroomID:matrix.example.com/media'`

**Comment by dklimpel** [comment]
But it seems not working in encrypted rooms.

**Comment by clokep** [comment]
> But it seems not working in encrypted rooms.

This seems to be working as designed then since the events are encrypted it isn't possible to search them for media. We should probably mention this in the endpoint documentation though.
