### ISSUE TITLE
Synapse instance not reachable (outside of localhost) - set up with the sample/recommend Docker + Caddy config

### ISSUE THREAD

**Issue by QEDeD** [matrix-org/synapse#8794]
### Description

I've tried setting up a Synapse instance, using Docker and Caddy, following the official documentation, but the instance is not accessible outside of localhost. 

### Steps to reproduce
So I tried to set up Synapse on an entirely fresh ubuntu vm using docker and Caddy. It seems like things are working, no errors in the log `docker logs synapse`. The content of the log is available for a month at https://paste.ubuntu.com/p/PKfrP5J5GW/

To check if things were working I used wget on localhost:8008 to see if there was a populated index.html. There was: "Your Synapse server is listening on this port and is ready for messages". So far so good.

However, when I use Element to connect to https://matrix.thewrt.com or https://matrix.thewrt.com:8448
I get: "Cannot reach homeserver". Furthermore, https://thewrt.com/_matrix/static returns an empty page, which I believe it shouldn't?

The steps I've taken are the following, are there any mistakes?

- install docker, docker-compose, set caddy up with docker-compose. Caddy's docker-compose file:
```
version: "3.7"
services:
  caddy:
    image: caddy
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8448:8448"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK
```
Note that $DOCKER_MY_NETWORK is defined in an .env file as being `caddy_net` 

- get Caddyfile from synapse documentation (https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md#caddy-2):
```
matrix.thewrt.com {
  reverse_proxy /_matrix/* http://localhost:8008
  reverse_proxy /_synapse/client/* http://localhost:8008
}
thewrt.com:8448 {
  reverse_proxy http://localhost:8008
}
```
- create docker by running the following (as specified at https://hub.docker.com/r/matrixdotorg/synapse):
```
docker run -it --rm \
--mount type=volume,src=synapse-data,dst=/data \
-e SYNAPSE_SERVER_NAME=thewrt.com \
-e SYNAPSE_REPORT_STATS=yes  \
matrixdotorg/synapse:latest generate
```
- enable user registration in homeserver.yml
- run docker (as specified at https://hub.docker.com/r/matrixdotorg/synapse):
```
docker run -d --name synapse \
    --mount type=volume,src=synapse-data,dst=/data \
    --network=caddy_net \
    -p 8008:8008 \
    matrixdotorg/synapse:latest
```
- Docker network inspect caddy_nets lists synapse and caddy in the same container
- Checking ports 80, 443, 8448 from outside the local network shows they are open

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: thewrt.com


<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

```
➜  caddy curl http://localhost:8008/_synapse/admin/v1/server_version
{
    "python_version": "3.8.6",
    "server_version": "1.23.0"
}%      
```

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

As described above, docker as described here: https://hub.docker.com/r/matrixdotorg/synapse

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Ubuntu 20.04 VM running on Proxmox:
```
➜  ~ uname -a
Linux ubuntusynapsetest 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by clokep** [comment]
A good place to start is asking in #synapse:matrix.org! Many of the admins in there are using Docker to run Synapse.

Not that it offers much more info, but the federation tester can be useful too: https://federationtester.matrix.org/#thewrt.com

I suspect something is misconfigured in the reverse proxy or firewall.

**Comment by QEDeD** [comment]
I'll check out the federation tester tomorrow and report back with results. I've tried asking in the Synapse channel, but we didn't get further concluding that the issue probably was related to Caddy, as you also mentioned.

**Comment by QEDeD** [comment]
@clokep I ran the federation tester and got the following results:

For thewrt.com
> Got 0 connection report. This usually means at least one error happened.
> Connection Errors
> Non-200 response 502 from remote server

I also checked by going to https://federationtester.matrix.org/api/report?server_name=thewrt.com and https://federationtester.matrix.org/api/report?server_name=thewrt.com:8448, which does produce slightly different results. 

https://federationtester.matrix.org/api/report?server_name=thewrt.com reports:



Error | "Invalid server name 'thewrt.com:'"
-- | --
WellKnownResult |  
m.server | ""
DNSResult |  
SRVCName | ""
SRVRecords | null
SRVError | null
Hosts | null
Addrs | null
ConnectionReports | {}
ConnectionErrors | {}
Version | {}
FederationOK | true




While https://federationtester.matrix.org/api/report?server_name=thewrt.com:8448 produces: 



WellKnownResult |  
-- | --
m.server | ""
result | "No .well-known found"
DNSResult |  
SRVCName | ""
SRVRecords | null
SRVError | null
Hosts |  
thewrt.com |  
CName | "thewrt.com."
Addrs |  
0 | "86.52.122.38"
Error | null
Addrs |  
0 | "86.52.122.38:8448"
ConnectionReports | {}
ConnectionErrors |  
86.52.122.38:8448 |  
Message | "Non-200 response 502 from remote server"
Version |  
error | "msg=Failed to GET JSON to :  code=502 wrapped="
FederationOK | false

**Comment by QEDeD** [comment]
@clokep Could you specify what other information would be required?

**Comment by richvdh** [comment]
First step is to pick your [server name](https://github.com/matrix-org/synapse/blob/develop/INSTALL.md#choosing-your-server-name) - ie, the way your server will appear to other servers. I recommend `thewrt.com` rather than `matrix.thewrt.com`. Make sure that your `homeserver.yaml` is configured with that `server_name`.

Next, get connections from the clients working. The federation tester is unrelated here.

The final step is to get federation working.

This isn't a great forum to get support, so I'm going to go ahead and close this issue. If you need more help, I suggest asking in `#synapse:matrix.org`.
