### ISSUE TITLE
Release file missing in debian repo

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#881]
Hi, I'm testing synapse in a 16.04 ubuntu server container. Tried

```
add-apt-repository -s "https://matrix.org/packages/debian/"
gpg --keyserver pgp.mit.edu --recv-keys AD0592FE47F0DF61
apt-get update
```

and got 
```
...
Err:6 https://matrix.org/packages/debian xenial Release                                        
  404  Not Found
...
Reading package lists... Done                                                                               
E: The repository 'https://matrix.org/packages/debian xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Would you be so kind and update the repo? I'm not a regular ubuntu user so if there's a quick fix on my side, please let me know as well. thanks in advance

**Comment by ara4n** [comment]
Looks like we only have releases currently for:

jessie
sid
stable -> jessie
stretch
testing -> stretch
trusty
trusty-unstable
unstable -> sid
vivid
wheezy
wily

...so no xenial yet.  @erikjohnston - how easy is it to add new ubuntus?

**Comment by killua-eu** [comment]
exactly. since this is my first hello to matrix, i just forced "testing" as a replacement and will go on and see what happens. it at least installed without a fuss, not sure if i run into runtime problems though.

**Comment by erikjohnston** [comment]
Its relatively easy, just need to check what packages need to be added.

**Comment by erikjohnston** [comment]
xenial and yakkety have been added
