### ISSUE TITLE
Combine related admin API docs

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#8810]
Currently there is a separate file for the purge remote media API docs and the rest of the media APIs
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_remote_media.rst
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/media_admin_api.md

There is also separate files for the purge room API, shutdown room API, and then the rest of the room APIs 
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/shutdown_room.md
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/rooms.md

It probably makes sense for all of the media APIs to be in one file and all of the room APIs to be in another, rather than being spread out like this.

**Comment by dklimpel** [comment]
These should be deprecated and removed:
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md
https://github.com/matrix-org/synapse/blob/master/docs/admin_api/shutdown_room.md

**Comment by clokep** [comment]
Agreed! Would really appreciate someone taking a once over of those and seeing how they could be better organized. Some of them (e.g. the rooms.md file) could use a table of contents at the top -- similar to the [user_admin_api.md](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst).

**Comment by anoadragon453** [comment]
> These should be deprecated and removed:
> https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_room.md
> https://github.com/matrix-org/synapse/blob/master/docs/admin_api/shutdown_room.md

This is still to be done, and will be once https://github.com/matrix-org/synapse/pull/8829 lands.

**Comment by anoadragon453** [comment]
#8829 has now landed. Thanks @dklimpel!
