### ISSUE TITLE
Is there a way we could somehow detect people searching for suicide advice and suggest links to suicide prevention hotlines?

### ISSUE THREAD

**Issue by Yoric** [matrix-org/synapse#8814]
If someone is searching for suicide advice, we could suggest links to suicide prevention hotlines.

This might require both server- and client-side changes.

**Comment by callahad** [comment]
Closing this for now as we don't have anything _specific_ to implement in Synapse, yet, and we're trying to keep our newly opened issues to things that have a relatively clearly defined work associated with them.

Unfortunately, there also isn't a well-defined place for these kinds of open-ended questions to live. Maybe a meta-discussion in an internal repo for now?
