### ISSUE TITLE
Deb package configuration file differs to that generated by running python -m synapse.app.homeserver

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#882]
running 

```
python -m synapse.app.homeserver \
    --server-name machine.my.domain.name \
    --config-path homeserver.yaml \
    --generate-config \
    --report-stats=[yes|no]
```

sets, unlike the deb package:
- registration_shared_secret
- macaroon_shared_secret
- server_name

the deb package sets  idp_redirect_url to an unsable value "http://test/idp", also web_client bool is set differenty. I suggest syncing the resulting configuration so that only paths differ, not actual server defaults.

**Comment by erikjohnston** [comment]
Hi! Unfortunately, for various (somewhat spurious) reasons we use a static config file as the default in the debian package. This means that we cannot set those values as they need to be unique per installation. 

The server_name should be set either at install time or manually using `dpkg-reconfigure`.

The `idp_redirect_url` should very much *not* be set, and looks to be commented out? Which would match the default config?

**Comment by killua-eu** [comment]
sorry, the IDP was commented out. dpkg-reconfigure asks for the server_name, but doesnt really set it for some reason.

**Comment by killua-eu** [comment]
closing this ticket, thanks for the explanation
