### ISSUE TITLE
Community Membership Privacy

### ISSUE THREAD

**Issue by andrewperry** [matrix-org/synapse#8825]
**Description:**

Currently there is a warning provided by the Element client as described here:

https://github.com/vector-im/element-web/issues/15834#issue-751405754

"Warning: any person you add to a community will be publicly visible to anyone who knows the community ID"

There are numerous use cases where it would be beneficial for Community membership to only be visible to people already in, or invited to, the community.

It would seem that this is something that requires support in the server implementation and not just the client.

I just discovered that MSCS 1772? is proposing Spaces to replace Communities so hopefully this gets addressed in that.

**Comment by richvdh** [comment]
Yes, MSC1772 proposes replacing the current communities implementation, and allows for spaces where the membership list is not publicly visible, so I'm going to go ahead and close this.
