### ISSUE TITLE
Temporarily frozen processes

### ISSUE THREAD

**Issue by nesnera** [matrix-org/synapse#8826]
### Description
The events sometimes take place with a long delay or only when they are repeated. Symptoms/examples:
- file upload (response: "The file 'image.png' failed to upload.")
- unable to view incoming attachments (response: {"errcode":"M_UNKNOWN","error":"Failed to fetch remote media"}. With nginx timeout first.)
- login using the Element web client (our instance at https://riot.vesp.cz)
  - the first attempt (response: Invalid homeserver discovery response) - this always happens 🥴
  - the second and further attempts (response: Error: Problem communicating with the given homeserver.)
  - no messages are leaving the home server matrix.vesp.cz ([configuration](https://github.com/otevrenamesta/otevrenamesta-cz-configuration/blob/master/machines/matrix.nix)). At the same time, incoming messages are delivered immediately
    - internal users (home server matrix.vesp.cz) can communicate (without attachments)
    - SmsMatrix bot sends/receives messages..🙈

Without any external intervention, everything will start working correctly within x-tens of minutes or units of hours. (Unsent messages are delivered, second sign-in attempts are successful. In the wrong order of course.)

### Steps to reproduce
The [configuration](https://github.com/otevrenamesta/otevrenamesta-cz-configuration/blob/master/machines/matrix.nix) is [fully reproducible](https://nixos.org/) 🙊 (I know, too laborious.)

### Version information
- **Homeserver**: matrix.vesp.cz
- **Version**: 1.23.0
- **Install method**: Hydra - https://github.com/otevrenamesta/otevrenamesta-cz-configuration/blob/master/machines/matrix.nix
- **Platform**:
  - hosted at [vpsFree.cz](https://vpsfree.org/)
  - running in a container behind central [reverse proxy](https://github.com/otevrenamesta/otevrenamesta-cz-configuration/blob/master/machines/proxy.nix) (nginx)
  - NixOS

### Attachements
- login - first attempt: ![Synapse_login-first_attempt](https://user-images.githubusercontent.com/1737463/100333815-507e6e00-2fd3-11eb-8647-1a8b96165ab2.png)
- login - second/next attempt(s): ![Synapse_login-second_attempt](https://user-images.githubusercontent.com/1737463/100333811-4fe5d780-2fd3-11eb-99ea-582099b5df96.png)
- delayed delivery (:matrix.orx x :vesp.cz): ![Synapse-delayed_delivery](https://user-images.githubusercontent.com/1737463/100333820-51170480-2fd3-11eb-998a-82389d8833f5.png)

**Comment by anoadragon453** [comment]
I tried testing your homeserver against the [federation tester](https://federationtester.matrix.org/) and indeed received a timeout after 30s.

From what I can see from your `.nix` file (be warned: I've not used NixOS) you're running a monolith homeserver setup with a few different bridges. Depending on the amount of traffic coming from your bridges, as well as the rooms users on your homeserver participate in, your server performance can be affected. It is also possible that some other part of your network or system is misconfigured.

The first step would be to [set up monitoring](https://github.com/matrix-org/synapse/blob/develop/docs/metrics-howto.md) for Synapse to get an understanding of whether your homeserver is lacking in resources. Once that is set up, we can get a better idea of what is wrong.

I would also encourage at this point asking in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) (with a matrix.org account if necessary) if you see anything abnormal, as there are many users there with Synapse sysadmin experience. It is also a good idea to take a look at [the wiki](https://github.com/matrix-org/synapse/wiki/Understanding-Synapse-Performance-Issues-Through-Grafana-Graphs) for which metrics to look out for.

**Comment by nesnera** [comment]
Grafana/Prometheus - [Synapse](https://status.otevrenamesta.cz/d/000000012/synapse?orgId=1&refresh=5m&from=now-2d&to=now)
user/password: tmpUserForSynapseIssue / 7aURveUzURenUHq

**Comment by anoadragon453** [comment]
Hmm, looking at your graphs I actually don't see much in the way of silver bullets.

![image](https://user-images.githubusercontent.com/1342360/100613965-45964700-330d-11eb-8c22-0dd44b212e28.png)

Yes, some of your request responses are very slow, but those are for group-related features. I see the same slowness on these servlets on my own homeserver. While terrible that those servlets are that slow, that *shouldn't* block any other bit of the app. Note that Synapse isn't mentioning much slowness processing other servlets, yet you seem to be noticing exactly that on the client side.

Thus the problem may lie in your network config or reverse proxy. This is the most worrying graph:

![image](https://user-images.githubusercontent.com/1342360/100614425-07e5ee00-330e-11eb-97fb-52a925cf0550.png)

For reference, here's the same graph from my homeserver:

![image](https://user-images.githubusercontent.com/1342360/100614458-1502dd00-330e-11eb-9bf4-9e48593c089c.png)

This may imply that other servers are having difficulty sending federation traffic to you, and only after retrying many times are they able to get a transaction through. The spikiness of that graph seems to indicate that failures build up before something recovers (possibly the network) and all the transactions are processed in one go.

So, I'd have a look at your network and see if you can try and test for any network problems. Maybe run a continuous ping and check for packet drops or slow response times. I'd also try asking your provider and see if they're seeing anything weird from your server on their end.

**Comment by clokep** [comment]
I'm fairly certain you're both talking about the same server, so I'm going to close this. Please shout if that's wrong. 👍
