### ISSUE TITLE
Enabling url_preview_ip_range_blacklist engages against register_new_matrix_user calls

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#883]
I enabled the commented out sanely sounding defaults limiting the spiders access to local networks, nonetheless, with the blacklist enabled, adding new users from shell fails:

```
register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml https://$myipadress:8448
New user localpart [root]: ee
Password: 
Confirm password: 
Sending registration request...
Traceback (most recent call last):
  File "/usr/bin/register_new_matrix_user", line 154, in <module>
    register_new_user(args.user, args.password, args.server_url, secret)
  File "/usr/bin/register_new_matrix_user", line 102, in register_new_user
    request_registration(user, password, server_location, shared_secret)
  File "/usr/bin/register_new_matrix_user", line 55, in request_registration
    f = urllib2.urlopen(req, context=ssl.SSLContext(ssl.PROTOCOL_SSLv23))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

```

**Comment by killua-eu** [comment]
just noticed that the ip range blacklisted doesnt even has anything to do with this problem. Only url_preview_enabled: True is needed to fail register_new_matrix_user

**Comment by ara4n** [comment]
The error you've pasted here is just saying that the script is failing 
to connect to your synapse instance in order to register the user.  The 
thing you should be looking at is the error which is stopping synapse 
from running.

**Comment by killua-eu** [comment]
@ara4n, the thing is: 
with url_preview_enabled: True calling register_new_matrix_user works.
with url_preview_enabled: False calling register_new_matrix_user doesnt work.
I thought at first that there's a firewall problem, but a simple trial/error with telnet showed this isnt the case.

**Comment by erikjohnston** [comment]
@killua-eu So `register_new_matrix_user` works if url previewing is *enabled* but not when its *disabled*?

**Comment by killua-eu** [comment]
@erikjohnston my bad, sorry, 
with url_preview_enabled: True calling register_new_matrix_user doesnt work
with url_preview_enabled: False calling register_new_matrix_user works
dang ...

**Comment by waveyuk** [comment]
Hi.
I too am having this issue running a home server on Ubuntu 16.04 hosted on Digital Ocean. Is there a way to fix this as I'd really like URL previews to work?

**Comment by ara4n** [comment]
I suspect you need to install the url_preview dependencies.  On Ubuntu, this should be:

```
apt-get install libxml2-dev
pip install lxml netaddr
```

I'm going to guess this will fix the issue and close it - please yell if it doesn't.

**Comment by waveyuk** [comment]
Hi @ara4n 
The first command successfully ran, but the "pip" command says PIP isn't recognised. I have read in other forums about installing it can break python installs from third party python implementations, so any guidance welcomed
Dave

**Comment by erikjohnston** [comment]
If you're using the debian packages you'll want to install python-netaddr and python-lxml packages

**Comment by waveyuk** [comment]
Hi @erikjohnston 
Thanks for your help - that fixed the issue :) 👍 
Dave

**Comment by rgpublic** [comment]
Gee. What a nightmare. Fortunately I have found this issue. This should definitely be simpler! Either a decent error message or proper dependencies with the Debian package in the first place. At the moment this is just terrible because it is in no way apparent what is causing the issue.

**Comment by helmut72** [comment]
Just came across this thread because Synapse doesn't start at all if url_preview = True.
