### ISSUE TITLE
remove pin on prometheus-client <0.9.0

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8831]
we should check that prom-client 0.9.0 doesn't break anything, and then bump the pin.

Indeed, given it's now been a few years since prom-client 0.4.0 broke the world, maybe we should remove the pin altogether?

**Comment by jordanbancino** [comment]
I don't know what prometheus_client is, but I edited my `python_dependencies.py` file to see if I could run synapse with version 0.9.0, and everything appears to be working fine, so I could open a pull request for that if you'd like. But I'm not a synapse expert, I just run a small server, and all I know is that removing the pin worked so I can use synapse again. Is there any official tests that need to be done, or can we update `python_dependencies.py`?

**Comment by anoadragon453** [comment]
@jordanbancino If you could create a PR that removes the pin, having the CI run over it and pass would be a great start!
