### ISSUE TITLE
m.direct event sometimes contains "[object Object]" instead of a user ID as a key

### ISSUE THREAD

**Issue by jplatte** [matrix-org/synapse#8834]
### Description

Some `m.direct` events seen in the wild contain

```rust
"content": {
    "[object Object]": ["!someroomid:homeserver"],
}
```

### Steps to reproduce

Unclear, but @afranke has an account where this happens.

### Version information

- **Homeserver**: matrix.org

**Comment by richvdh** [comment]
`[object Object]` looks like something javascript would create: this suggests a client bug to me.

**Comment by richvdh** [comment]
indeed I'm going to close this in favour of https://github.com/vector-im/element-web/issues/7485.

**Comment by jplatte** [comment]
I was thinking the same. Still, is this not something Synapse should / could filter out?

**Comment by richvdh** [comment]
no, the homeserver is not responsible for checking the validity of account data. https://github.com/matrix-org/matrix-doc/pull/2801 goes into some detail as to why this isn't practical.

**Comment by jplatte** [comment]
I see, makes sense.
