### ISSUE TITLE
Unable to decrypt messages from matrix.org

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#8838]
Since a couple of days (or weeks already), it appears that all users on my homeserver `tchncs.de` are unable to decrypt messages from `matrix.org`. Some reported a delay of 1-2 days.

````
** Unable to decrypt: The sender's device has not sent us the keys for this message. **
````

I have switched the room with my fallback account on the `matrix.org`-side to encryption and am unable to read my messages on either side (while for a short moment, it worked on the matrix.org side) since more than two days. My current loglevel is `warning` - i have not found any entry with the eventids or roomids for this testroom.

Starting the verification process just triggers more of the errors above and states that it was cancelled by user after a while.

I am using this repository for the report because it ... seems to be the usual and expected place? I know there are various similar issues in this topic already, but in my case only one server but presumably all users are affected, which is kind of a big problem.

As suggested by @richvdh, i have asked my users to report this from their clients, some already did.

Recent event-ids in my testroom: `$1606253776323600JnZDO:matrix.org` and `$16062537373140YZSqA:tchncs.de`

**Comment by richvdh** [comment]
seems this was previously https://github.com/vector-im/element-web/issues/15817

**Comment by richvdh** [comment]
the e2e keys aren't being sent because `tchncs.de` isn't keeping up with federation, and https://github.com/matrix-org/synapse/issues/8691.

**Comment by richvdh** [comment]
suggest we close this in favour of #8691.
