### ISSUE TITLE
Registrations enabled, e-mail never received

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#885]
I'm not sure if this is a server or client problem so please excuse if this ticket is misplaced. Upon registering from vecor-web, i'm told to continue registering by checking my e-mail. Nothing arrived in my mailbox (i tried several different mail providers). homeserver.yaml enables registrations. Who's supposed to send the e-mails, vector or synapse? If synapse, do I have to setup an smtp server for synapse and let it know about it in the homeserver.yaml, or does synapse contain a builtin mailer thats used? How can I debug this further? Thanks in advance, P.

**Comment by ara4n** [comment]
Validation emails are done by sydent.  If you're not running a sydent 
and aren't using vector.im or matrix.org's one, then just leave the 
email address blank for now.  If you're using vector.im or matrix.org's 
sydents then PM me the email address (@ matthew:matrix.org) and I see 
where the email went.

**Comment by killua-eu** [comment]
thanks, for the explanation, works fine :)
