### ISSUE TITLE
3PID invites should include the configured web client instance / homeserver url in the email

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#8863]
Related https://github.com/vector-im/element-web/issues/5923

Some context in https://matrix.to/#/!oBWlVutBAdQYcYUsAc:sw1v.org/$pnwt-VMwwf3pC7_QET_e2jk_ojfRAPTNZ9fj2ag-Uio?via=jki.re&via=matrix.org&via=vector.modular.im

(This also applies to Sydent, but the work is 50/50 across both projects)

Synapse currently uses the identity server to send 3pid invites out to users (so it sends an email when an email address is invited to a room). However, [the templates](https://github.com/matrix-org/sydent/blob/master/res/invite_template.eml) do not include and do not have a way to include the target web client instance. Instead, all invites include app.element.io.

This is a problem if you are running your own custom Element / Synapse deployment and wish to send invited users to your specific instance, especially so if your instance is not federated. 

There are several ways to resolve this:
- Invites could be sent by Synapse (and thus, the template could be configured by the owner).
- Synapse could send the config value of `web_client_location` to sydent, and the template could use that.
- Synapse could send the homeserver URL to sydent, and sydent could include a parameter to target the right homeserver. This would require https://github.com/vector-im/element-web/issues/5469

**Comment by clokep** [comment]
> Synapse could send the config value of `web_client_location` to sydent, and the template could use that.

It seems like the [identity service spec](https://matrix.org/docs/spec/identity_service/latest#post-matrix-identity-v2-store-invite) would allow additional config to be sent:

> In addition to the request parameters specified below, an arbitrary number of other parameters may also be specified. These may be used in the invite message generation described below.

Given that, I think this is the easiest way forward. There *is* a config option for Synapse to know where to point to (`web_client_location`), but that is deprecated. So I'm not sure where this should be from instead.
