### ISSUE TITLE
Allow users to pick their own mxid after SSO

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8876]
For servers that support login via SSO, it would be nice to give users the option to pick their own userid, rather than assigning them one based on the attributes from the remote identity provider.

Obviously this would need to be configurable by the synapse sysadmin.

**Comment by maxkratz** [comment]
AFAIK there are implementations of MXID mappers that are able to do this.
Have a look at this one: https://github.com/chaos-jetzt/matrix-synapse-saml-mapper

**Comment by richvdh** [comment]
indeed. I wrote that one. The problem with it is that it only works for SAML and we also want to support OIDC. It's also a bit fragile in that it relies on not-really-supported mechanisms to escape the normal SSO flow.

**Comment by maxkratz** [comment]
> I wrote that one.

Ahm .. yes, I've should have seen that!

> The problem with it is that it only works for SAML and we also want to support OIDC. It's also a bit fragile in that it relies on not-really-supported mechanisms to escape the normal SSO flow.

I fully agree.
