### ISSUE TITLE
Pagination: prev_content  was not sent for m.room.member events

### ISSUE THREAD

**Issue by ganfra** [matrix-org/synapse#8877]
For some time I didn't get any prev_content for m.room.member events fetched by pagination. 
Now it seems to be back. Not sure what went wrong.

How I reproduced: 
Sent m.room.member event in room followed by 10 message events => the roommember event has prev_content
Then cleared cache which triggered initialSync followed by pagination => the roommember event hasn't prev_content

Server used: matrix.org, the room is not federated.

**Comment by anoadragon453** [comment]
Do you know whether `replaces_state` was also missing?

**Comment by richvdh** [comment]
going to close this pending more info.
