### ISSUE TITLE
Backfilled events marked as outliers break backfill

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#8894]
A homeserver backfilling from another homeserver was found to be raising an `AssertionError` at:

https://github.com/matrix-org/synapse/blob/30fba6210834a4ecd91badf0c8f3eb278b72e746/synapse/handlers/federation.py#L921-L923

It's currently unclear which event is problematic and why it might be marked as an outlier. The logs of the backfilling server also contained many instances of event signature validation failures. This was due to a remote server changing their signing key without also changing the key ID (or putting the old key in `old_signing_keys`). This may be a red herring however.

The `assert` and a similar assert at:

https://github.com/matrix-org/synapse/blob/30fba6210834a4ecd91badf0c8f3eb278b72e746/synapse/handlers/federation.py#L891-L894

both do not give any information about the failing event.

Thus the first step is to improve these assert statements and figure out why these backfilled events are marked as outliers. After that, we may want to make the backfill code drop these events instead of simple raising, similar to what was done in #8350.

**Comment by callahad** [comment]
@anoadragon453 Any chance you have a stack trace for this?

**Comment by anoadragon453** [comment]
The stack trace is quite unhelpful:

```
AssertionError: null
  File "synapse/handlers/federation.py", line 1097, in try_backfill
    await self.backfill(
  File "synapse/handlers/federation.py", line 920, in backfill
    assert not event.internal_metadata.is_outlier()
```

However you can see a little bit of surrounding logs and other metadata at https://sentry.matrix.org/sentry/synapse-modular/issues/194313/ and https://sentry.matrix.org/sentry/synapse-modular/issues/194314/ (for those that have access).

**Comment by callahad** [comment]
Deferring for now, as one of our quarterly goals is to tame our Sentry alert rate, we should return to this in due course.

**Comment by richvdh** [comment]
Looks like this was introduced in #8350.
