### ISSUE TITLE
Missing arm64 and armv7 docker builds

### ISSUE THREAD

**Issue by myxor** [matrix-org/synapse#8907]
### Description

Since v1.24.0rc2 build the `arm64` and `armv7` docker builds are missing.
Last one which contained both architectures was v1.24.0rc1: https://hub.docker.com/layers/matrixdotorg/synapse/v1.24.0rc1/images/sha256-ef74148191c38e2b00ab2e9012a1fb4ab4083583fd32342800b97610b1efa48b?context=explore

All newer builds miss these both architectures, see: https://hub.docker.com/r/matrixdotorg/synapse/tags?page=1&ordering=last_updated

### Steps to reproduce

- pull `matrixdotorg/synapse:latest` docker image on arm64 architecture
- see that it is not working as it is an `amd64` binary

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

I exptected to have the arm64 and armv7 docker builds as before.

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
fixed by #8906.  they are on their way now.
