### ISSUE TITLE
arm64 matrixdotorg/synapse:latest docker image disappears for two hours during releases

### ISSUE THREAD

**Issue by helmut72** [matrix-org/synapse#8908]
Subject says it all.

**Comment by richvdh** [comment]
see #8907. they are on their way now.

**Comment by helmut72** [comment]
Oh sorry, bad timing for me. But maybe it's better to upload all archs at the same time.

**Comment by richvdh** [comment]
Indeed. This is an artifact of the way we build the docker images: we don't really want to force amd64 users to have to wait while the arm build churns.

**Comment by helmut72** [comment]
> we don't really want to force amd64 users to have to wait 

That's ok, also for the future. But then it's better to rename other builds to eg. matrixdotorg/synapse-arm64:latest, matrixdotorg/synapse-armv7:latest ...

I guess you also don't want crazy containers ;)
