### ISSUE TITLE
search_term in List Room Admin API is case sensitive

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#8923]
It probably should be case insensitive

https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/rooms.md#list-room-api

**Comment by dklimpel** [comment]
The same problem for `name` in user list
https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#list-accounts

**Comment by MurzNN** [comment]
Maybe the source of this problem is same like in #3116 with room events search?
