### ISSUE TITLE
Media requests over federation aren't signed

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/synapse#8924]
### Description

Requests to /media from a homeserver are not signed. The specification requires [all requests from homeservers to be signed](https://matrix.org/docs/spec/server_server/r0.1.3#request-authentication). I understand that this is an open area of discussion in #2150, but how I read the spec currently, the requests should be signed today. One could argue, that signing requests only applies to the federation API, but requests to the media API are sent to the federation API location, not the client API location, i.e. port 8448 usually. Additionally they require `allow_remote` to be set to `false`. As such the content API is already slightly different for the federation side and in my opinion the spec text requires signatures for all requests anyway.

Signing requests to the media repository is one of the prerequisites to locking the media repository down and not allowing everyone to download media from it. While it may be useful to know, which user is requesting the media, locking out certain servers is already much more useful and probably the only feasible way to actually secure a media repo, since everything else can be circumvented by an admin anyway.

One could argue, that the spec needs clarification in these areas, but I think the current required behaviour is pretty clear. Any deviation would need an MSC. Feel free to close this, if you disagree with my interpretation of the spec or if you think the federation endpoint should not be handled differently than the client media endpoint.

### Steps to reproduce

- check the header logs, if any synapse requests media from your server

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: neko.dev, nheko.im, and probably any other server

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.24.0

- **Install method**: ebuild
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Gentoo
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
> One could argue, that the spec needs clarification in these areas, but I think the current required behaviour is pretty clear. 

Well, I certainly don't agree that your interpretation is correct. I can equally well say: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-media-r0-download-servername-mediaid says "Requires auth: No".

So at best, I think the spec is unclear, but in practice, where there is doubt, we're going to follow what synapse does, notwithstanding the fact that requiring requests to be signed have benefits as you suggest.

I'm going to go ahead and close this as you suggest. Feel free to raise an issue against the spec asking that it be clarified.

**Comment by deepbluev7** [comment]
Okay, I will raise a spec issue. Thanks!
