### ISSUE TITLE
Removing pushers doesn't work in all cases when using worker mode

### ISSUE THREAD

**Issue by manuroe** [matrix-org/synapse#8925]
### Description
Element-iOS disables its pusher when the user logs out from the app. It makes a request to `/pushers/set` to empty its pushers.
But it cannot do this when its session is logged out from another device.
The user is logged out but the app continues to receive pushes. As the iOS system forces us to display a notification for every received push, the app continues to display notifications with more or less data.

Synapse should disable pushers for any logged out sessions.

### Steps to reproduce
Steps to reproduce on iOS are described
https://github.com/vector-im/element-ios/issues/3718

**Comment by richvdh** [comment]
ironically, apparently for email we have the opposite problem: https://github.com/matrix-org/synapse/issues/3696

**Comment by erikjohnston** [comment]
It looks like we correctly call `pusher_pool.remove_pushers_by_access_token`, so I think this is a bug with workers where we don't correctly replicate the device deletion to the pusher? Maybe?

**Comment by clokep** [comment]
I think this was fixed by #9465.
