### ISSUE TITLE
Case insensitive Server Side Search by keyword in rooms with non-latin words not working

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#8953]
### Description

For words with Latin characters case insensitive Server Side Search by keywords works well: we can send two messages with `hello` and `HeLLo`content, and find both of them via `hello`, `HeLLo` and even `HELLO` search string.

But when we try same thing with non-Latin words, for example - Russian word "Привет" - search becomes case sensitive!

### Steps to reproduce

1. Send to room two messages with English words `hello` and `HeLLo`content.
2. Make a search in this room via keyword "HELLo" - you will find both messages.
3. Send to room two messages with Russian words `привет` and `приВЕТ`content.
4. Make a search in this room via keyword "Привет" - you will find nothing!

### Version information

- **Homeserver**: matrix.org or any other homeserver with default PostgreSQL database settings.

**Comment by clokep** [comment]
I think this is #3116?

**Comment by MurzNN** [comment]
Earlier this problem could have been solved via changing PostgreSQL database locale (Collate and Ctype) from `C` to something like `en_US.UTF-8` and reindexing tables.
But later this trick becomes deprecated via https://github.com/matrix-org/synapse/issues/6722 (at now - not so strict, it show only warning).

**Comment by MurzNN** [comment]
@clokep yes, thanks, this is a dupe of #3116
