### ISSUE TITLE
If a server reaches its MAU, it is no longer able to create appservice users.

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#8960]
Note, bridge users do not count against MAU. However if your homeserver reaches the MAU limit with real users and then an appservice tries to register ghost users, it will fail with `"errcode":"M_RESOURCE_LIMIT_EXCEEDED","error":"Monthly Active User Limit Exceeded"`

This may also be the case for other custom user types too.

**Comment by rxl881** [comment]
@danc86 -- Is there any chance that we would be able to get a hot-fix for this relatively quickly?

**Comment by Half-Shot** [comment]
Offending registration check:
https://github.com/matrix-org/synapse/blob/f14428b25c37e44675edac4a80d7bd1e47112586/synapse/handlers/register.py#L208-L210

More generally https://github.com/matrix-org/synapse/blob/f737368a26bb9eea401fcc3a5bdd7e0b59e91f09/synapse/api/auth_blocking.py#L40 should probably not block actions from appservice users.

**Comment by callahad** [comment]
With apologies to @danc86 -- I'm @callahad, he's someone else :)

**Comment by rxl881** [comment]
Whoops!! Sorry for the erroneous mention, I'm going to blame a combination of lack of coffee and over-dependence on auto-complete :( (thanks for catching that "the real" @callahad)
