### ISSUE TITLE
Implement LBRY protocol in synapse

### ISSUE THREAD

**Issue by irelativism** [matrix-org/synapse#8961]
**Implement the LBRY protocol as a media system, given it is a very active project and probably the replacement for BitTorrent: As an addition maybe such should also be kind of compliant with activityPub so then one can truly state matrix network is a truly decentralized/distributed system.**

**Comment by irelativism** [comment]
@aWeinzierl can you please describe what you though wasn't so good on such so I can improve and edit it.

**Comment by clokep** [comment]
This sounds like it should be a spec issue, not a Synapse issue.

**Comment by irelativism** [comment]
this has been continued in /matrix-doc/issues/2916 then @clokep
