### ISSUE TITLE
Option to hide bridge users from user directory

### ISSUE THREAD

**Issue by waclaw66** [matrix-org/synapse#8969]
Hello together.

I would like to ask for a new feature.
I use mautrix-facebook bridge and I would like to prevent from searching puppets of that bridge.
My synapse is currently configured like:
```
user_directory:
  enabled: true
  search_all_users: true
```
A possibility to filter them by `appservice_id` from `users` table would be helpful or just simply expose native users only.

Thanks for considering it.

Regards.

**Comment by erikjohnston** [comment]
This seems reasonable, I don't think the core team will have time to add it anytime soon but we'd be happy to accept a PR that does this.

**Comment by waclaw66** [comment]
Soved by https://github.com/matrix-org/synapse/pull/10789

**Comment by DMRobertson** [comment]
> Soved by #10789

I think the change responsible is actually https://github.com/matrix-org/synapse/commit/f7b034a24bd5e64f05934453fe7b072894e124db in https://github.com/matrix-org/synapse/pull/10960.

Note that this doesn't introduce the _option_ to configure whether bridge users are omitted or included in the directory. At present they're always omitted. I think the team was broadly amenable to the idea of allowing appservices to configure whether their users were exposed in the directory, but we don't have the time to work on that at present.
