### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#897]
With Recaptcha disabled

```
root@matrix-stack:/etc/matrix-synapse# cat homeserver.yaml  | grep captch
#recaptcha_public_key: 'YOURPUBLICKEYHERE'
#recaptcha_private_key: 'YOURPRIVATEKEYHERE'
# unless a captcha is answered. Requires a valid ReCaptcha
enable_registration_captcha: 'False'
# A secret key used to bypass the captcha test entirely.
captcha_bypass_secret: "prcame"
# The API endpoint to use for verifying m.login.recaptcha responses.
#recaptcha_siteverify_api: "https://www.google.com/recaptcha/api/siteverify"
```

and connecting to my own synapse installation, I still get a recapcha request from vector. I had my hopes up when seeing https://github.com/vector-im/vector-web/issues/1042, but since i'm not using matrix.org, I assume its something on synapse. I'm also at loss on how to debug this to figure out where the capcha gets inserted.

**Comment by kyrias** [comment]
Does this still happen for you?

**Comment by richvdh** [comment]
let's assume not

**Comment by killua-eu** [comment]
Sorry for the late reply, it does not.
