### ISSUE TITLE
Remove unused last_used column from access_tokens table

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#8972]
The `last_used` column on `access_tokens` is unused, we should remove it.

See https://github.com/matrix-org/synapse/issues/8970#issuecomment-747727281_

**Comment by clokep** [comment]
This is a bit more of a faff than expected since sqlite cannot drop columns directly, e.g. check out `synapse/storage/databases/main/schema/delta/46/user_dir_null_room_ids.sql`

**Comment by jerinjtitus** [comment]
So, it should dropped from the sql files, right? And is it just required to be removed for sqlite or also for postgres.

**Comment by clokep** [comment]
> So, it should be dropped from the sql files, right?

A new migration file needs to be added that drops the column.

> And is it just required to be removed for sqlite or also for postgres.

It should be done for both.

**Comment by jerinjtitus** [comment]
> A new migration file needs to be added that drops the column.
I was going through those files; I guess I have to create like a buffer table in the new migration file and copy the values from the previous one and then drop it. Then rename the new table. Am I right so far?

**Comment by clokep** [comment]
That's pretty much what is done in `synapse/storage/databases/main/schema/delta/46/user_dir_null_room_ids.sql`, so I think it is right.

**Comment by jerinjtitus** [comment]
![image](https://user-images.githubusercontent.com/72017981/103622467-cd025600-4f5c-11eb-8340-b38a1ef59b16.png)

Can you help me with understanding how exactly this classification works? And are all the migrations automatically made if directly added to the appropriate directory?

**Comment by richvdh** [comment]
Just add a new migration to the most recent `delta` directory, with a new number.

There is a bit of documentation about the system at https://github.com/matrix-org/synapse/blob/develop/synapse/storage/prepare_database.py#L288, but it needs an update to be honest.

**Comment by jerinjtitus** [comment]
> Just add a new migration to the most recent `delta` directory, with a new number.
> 
> There is a bit of documentation about the system at https://github.com/matrix-org/synapse/blob/develop/synapse/storage/prepare_database.py#L288, but it needs an update to be honest.

Thanks

**Comment by clokep** [comment]
Fixed in #9025.
