### ISSUE TITLE
User directory won't consider non-new users with stop words in their names

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#8974]
Users inserted in the user directory before https://github.com/matrix-org/synapse/pull/8959 is deployed will be inserted with a search vector using the `english` dictionary. This means it will exclude common english words - for example a user which display name is "Be Awesome" won't be included in the results when searching for `be`. See https://github.com/matrix-org/synapse/pull/8959#issuecomment-748031899 for more info.

https://github.com/matrix-org/synapse/pull/8959 fixes this for new insertions or updates, but the content from before that patch has been deployed will still have the issue. The solution is probably to rebuild the vectors from `user_directory_search` table in a background update, i.e. iterating over every user in there and updating their vector, but that's pretty costly.

**Comment by callahad** [comment]
Decision: WONTFIX for now. Should this become a larger issue in the future we can do a background update.
