### ISSUE TITLE
Matrix.org's alias `#discord:half-shot.uk` seems outdated

### ISSUE THREAD

**Issue by jaller94** [matrix-org/synapse#8981]
### Description

today I joined #discord:half-shot.uk but landed in different rooms on my two accounts.

I think matrix.org still links the alias to an old room (`!qPNOnUsNsZrToFZqxB:half-shot.uk`). My other account landed in the correct, new room (`!OluOzqbTJgecdDIuKn:half-shot.uk`). Both are v1 rooms.

Other matrix.org users seem to be having the same issue. The old room saw a few people joining and leaving since Oct 2018 when people stopped using it.

### Steps to reproduce

- Use an account on matrix.org.
- Join `#discord:half-short.uk`.

I expected to join `!OluOzqbTJgecdDIuKn:half-shot.uk` but instead joined `!qPNOnUsNsZrToFZqxB:half-shot.uk`.

### Version information

- **Homeserver**: matrix.org

**Comment by clokep** [comment]
Did you join via the room directory or `/join #discord:half-shot.uk`?

It seems that the old room (`!qPNOnUsNsZrToFZqxB:half-shot.uk`) had a canonical alias that pointed to `#discord:half-short.uk` but no longer does. `!OluOzqbTJgecdDIuKn:half-shot.uk` does not have a canonical alias set on it.

(The old room also has some *aliases* set, but those are deprecated so shouldn't be used?)

**Comment by jaller94** [comment]
I joined the old room via the room directory on Element Android.
On my other account I joined the new room via the text command on Element Web.

I didn't think this would make a difference.

**Comment by richvdh** [comment]
it does make a difference: the aliases shown in the room directory are just for information. 

I can't find either of the rooms mentioned in matrix.org's directory.

I don't think we can do much about this without clearer info about the repro steps.

**Comment by richvdh** [comment]
(sorry the ball got dropped on it)
