### ISSUE TITLE
Manhole password should be configurable

### ISSUE THREAD

**Issue by dkasak** [matrix-org/synapse#8995]
The manhole password is currently hardcoded. It would be nice to make it configurable so there's at least some access control.

**Comment by CreaTorAleXander** [comment]
@dkasak  What is to do here? Is it in the manhole.py, didn't see there something like a Password.

**Comment by aaronraimist** [comment]
The password appears to be set here https://github.com/matrix-org/synapse/blob/111b673fc1bbd3d51302d915f2ad2c044ed7d3b8/synapse/app/homeserver.py#L311

**Comment by dkasak** [comment]
That's correct. We should expose a password setting in the config file and use that for the password, if it is set.

Ideally we'd not use a default password at all and require it to be set explicitly, but since this would be a backward-incompatible change of the config file, just allowing the user to override the default one is good enough for now.

**Comment by CreaTorAleXander** [comment]
This means in the config file is an entry password. There you can set your password but at the beginning there is a default password and the homerserver.py reads in this password from the config file?

**Comment by dkasak** [comment]
@CreaTorAlexander, yes, that sounds about right.

**Comment by CreaTorAlexander** [comment]
And which config file is for the password?

**Comment by dkasak** [comment]
There's currently no such option in any file (that's the issue). But if such an option were implemented, it would go into `homeserver.yaml`.

**Comment by callahad** [comment]
This was fixed in 1.43.0
