### ISSUE TITLE
Self Destruct Messages & Self Destruct Chats

### ISSUE THREAD

**Issue by trymeouteh** [matrix-org/synapse#9004]
Many privacy chat apps like Signal support a feature which allow you to have messages delete itself. I think this can be useful feature in Matrix for a layer of privacy on your messages and chats. Here is how it can work.

- Any user can create a self destructing message
- Any admin of a chat can set all messages from here on to be self destructive (users cannot opt out)
- Self destructive messages can be set to expire after X amount of views,  amount of time, or until a certain date and time.
- If chats have self destructive messages enabled, the admin can choose the range of when a message will expire after X amount of views,  amount of time, or until a certain date and time

This is not a necessary feature but one that could be considered and discussed. If such a feature is added I think the options for when a self destructing message expires it should be plentyful for the user and the admins should be able to force all messages to self destruct in a chat if they wish and what conditions they will self destruct

**Comment by clokep** [comment]
See #6287 for current work on this. Any additional changes should be handled in the spec repo (probably at matrix-org/matrix-doc#2228, I couldn't find an issue there related to this).
