### ISSUE TITLE
user_ips records 127.0.0.1 extra for a session

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#9011]
Hi there, i have already asked in the synapse room, but we couldn't find a solution. I am not sure if i have configured something wrongly or if it could be a bug:

Each session records the local, 127*, ip adress along side the public one into `user_ips` for one session. They are not exactly on the same timestamp for `last_seen`, and the one, that is slightly newer, then is displayed in the session list (in the client) and in the `devices` table.

I am using delegation, but also a proxy on the main domain for compatibility with clients, logged in before the change. So far, the proxy does not seem to affect the problem*, as it behaves the same on each domain, configured in the client.

In nginx, for synapse and each worker, i am using something like
````
        proxy_pass http://localhost:8088;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
````
I have also tried `proxy_set_header X-Forwarded-For $remote_addr;` with no luck.... on the other hand, the public ip is usually* included, so i am not sure if i even am looking at the right place.

This seems to affect all clients (tested with element-web and element-ios... and element-desktop+android by a user)

````
synapse=> select ip,last_seen from user_ips where device_id = 'IRWOPFHXLO';
      ip       |   last_seen
---------------+---------------
 127.0.0.1     | 1609704431125
 <public ip>   | 1609704358965
(2 rows)
````
![sessions](https://user-images.githubusercontent.com/10698140/103488251-4e49d380-4e0b-11eb-9753-2da92424c318.jpg)
*this screenshot was a test with element-web in a private window*
****
*yesterday i have tried to track a nastly spammer down, who kept creating new accounts, but they only had the ipv4+ipv6+127 ip adress of the proxy host logged, i however was never able to reproduce this. but since then, i have updated the headers to upon example, so maybe i have fixed this particular problem this way
****
**Update:**
As suggested by another admin, i have tried to only use `proxy_set_header X-Forwarded-For $remote_addr;` excluding the other headers. This is because i know that my workers differed from the master process originally, but i wasn't 100% sure in which way exactly. Anyhow, it remains the same as above.

**Comment by clokep** [comment]
Is your setup using workers or a single monolith?

**Comment by richvdh** [comment]
also: did you set `x_forwarded: true` in the `listeners` configs?

**Comment by verymilan** [comment]
Thank you, after this question, i have added `x_forwarded: true` in my `homeserver.yaml` where it was missing, as it was only set for port `8008`. This did not fix it, what fixed it however was adding it to the worker configs. 
The most recent test at least only returns one row of my public ip adress for the session 👍
