### ISSUE TITLE
Mentions to you specifically vs implicitic mentions via @room should be shown differently

### ISSUE THREAD

**Issue by brendanheywood** [matrix-org/synapse#9012]
**Description:**

With a large number of channels you can get many channels with highlighted red counts which means you were mentioned:
![image](https://user-images.githubusercontent.com/187449/103490477-1de85080-4e70-11eb-97a2-b8de759b1738.png)

But there are many false positives as `@brendan` is treated identically to `@room`. A personal mention should be visually treated higher priority than a general one (we've just migrated from rocket which is how it behaves). This is tangential to how the notifications happen:

* [ ]  this is a visual change to the style of the comments depending on which mention type they contain, eg personal mentions remain red, and group mentions are something less urgent, maybe blue
* [ ]  and that same style should roll up to the channel indicator, so a channel which only contains group mentions will have a blue message count but any with a personal one will be red

**Comment by aaronraimist** [comment]
Synapse is server software. It has no UI. It looks like you are using the Element client https://github.com/vector-im/element-web.

**Comment by brendanheywood** [comment]
Thanks, I found an existing issue https://github.com/vector-im/element-web/issues/12769
