### ISSUE TITLE
Add table for ignored users to make calculating push rules faster for large rooms.

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#9022]
For large rooms we spend quite a lot of time figuring out if anyone ignores the user:

https://github.com/matrix-org/synapse/blob/5d34f40d494305bb32b3d57c18fb17d98d21a31f/synapse/push/bulk_push_rule_evaluator.py#L206-L213

which will look up the account data for each `uid` user. We can make this way more efficient by having a separate table for ignored users (updated when the account data is updated), which would allow us to do a single query to figure out everyone who ignores `event.sender`.

(The table should be quite small since few people are ignored)

**Comment by clokep** [comment]
This should be pretty straightforward to do for new data, but we would need to handle migrated current data into this form. We'll also need to figure out what to do with invalid account data, but likely we can just say that no one is ignored in that case.

**Comment by erikjohnston** [comment]
> We'll also need to figure out what to do with invalid account data, but likely we can just say that no one is ignored in that case.

That's what we do currently fwiw
