### ISSUE TITLE
The Delete Room API should use the http DELETE method, not POST

### ISSUE THREAD

**Issue by PaarthShah** [matrix-org/synapse#9032]
With roots in [this suggestion](https://github.com/matrix-org/synapse/pull/7613#discussion_r438859896) by @richvdh, the current Delete Room API uses `POST /_synapse/admin/v1/rooms/<room_id>/delete` instead of `DELETE /_synapse/admin/v1/rooms/<room_id>`, on the logic that DELETE should not have a request body.

This logic is incorrect, as better detailed by [this stackoverflow answer](https://stackoverflow.com/a/299696), but in short, the spec supports it, and the matrix APIs already have other instances of `DELETE` being used with a request body.
https://matrix.org/docs/spec/client_server/latest#delete-matrix-client-r0-devices-deviceid

**Comment by richvdh** [comment]
While you're probably right that the reasoning for making it `POST` rather than `DELETE` was bogus, is it a significant problem in practice? Changing it would mean breaking any applications that are using the API.

**Comment by PaarthShah** [comment]
I agree that it's not worth breaking any applications using the API, however:

- Element (web/desktop/mobile all) does not yet make use of this API at all
- I find it unlikely that any user-made scripts would depend on this API considering its nature (why would anyone need to systemically delete a room so regularly?)
- It would seem to be fairly trivial to just deprecate (but not disable) the API temporarily if either of the above were a major concern anyway.
- It is better to remain consistent with previously-established Matrix behavior _even if it is wrong_ for ease of learning; quite frankly, it makes Synapse/Matrix look really unpolished when different API paradigms are being used in this fashion. If the `POST /delete` were consistently used, then I probably wouldn't have even brought it up. And considering that this is a _synapse endpoint rather than a _matrix common one, it seems that the burden should be on Synapse to adjust to the greater-established API style, for v1.25 (where the old room purge etc APIs are being deprecated as well).

**Comment by richvdh** [comment]
I'm don't have strong opinions here. cc @dklimpel

**Comment by dklimpel** [comment]
I have no opinion on this.
I think that there should only be a consistent approach for Synapse, which is then documented.
There are much more delete APIs: group, devices, media, etc.

**Comment by ptman** [comment]
allow DELETE and deprecate POST?

**Comment by PaarthShah** [comment]
> allow DELETE and deprecate POST?

Would definitely be my suggestion.

**Comment by clokep** [comment]
> allow DELETE and deprecate POST?

This was going to be my suggestion as well.

Note also that this is an admin API so the spec is somewhat...unrelated.

We would accept a PR for this if it was backwards compatible, but the core team likely will not have a chance to work on this.

**Comment by PaarthShah** [comment]
I could definitely work on this sometime in this coming week, most likely, though I've never contributed to this particular project before :)

**Comment by ShadowJonathan** [comment]
Maybe allow `DELETE` and `POST` side-by-side for a while, making `on_POST` call `on_DELETE`, and then decide on deprecation later.

**Comment by shadowcat-mst** [comment]
Per the HTTP spec this is undefined behaviour and existing implementations - including proxies - are explicitly called out as potentially rejecting such a DELETE request.

See https://github.com/matrix-org/synapse/issues/11698#issuecomment-1006839240 for expansion on that /cc @PaarthShah
