### ISSUE TITLE
Regression in log context tracking

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#9048]
On both matrix.org and jki.re I'm seeing (on latest develop) a lot of:

```
2021-01-07 18:39:07,534 - synapse.util.metrics - 113 - WARNING - None - Starting metrics collection from sentinel context: metrics will be lost
```

which may mean a bunch of our metrics are inaccurate

**Comment by richvdh** [comment]
> which may mean a bunch of our metrics are inaccurate

I think the problem has existed for a while: we're just reporting it now.

It will have been introduced by #8935, and I feel like the increased log spam makes this a release-blocker for 1.25.

**Comment by richvdh** [comment]
scratch that, it will be #8939, which didn't make the release.

**Comment by erikjohnston** [comment]
Agreed. I think the first step is to get it to log *what* block is being ignored, since we have the name there that should be easy.

**Comment by richvdh** [comment]
(it's still a release-blocker, but for 1.26...)

**Comment by erikjohnston** [comment]
Clearly we need a `next-release blocker` label...

**Comment by erikjohnston** [comment]
Looks like it is in v1.25.0rc1

**Comment by erikjohnston** [comment]
Oh, ignore me somehow I opened the wrong PR....
