### ISSUE TITLE
email activation link response not redable on mobile

### ISSUE THREAD

**Issue by 6543** [matrix-org/synapse#9049]
If a user add a email, he get a link via email sent he has to open.
If he open this link via mobile (android in this case) the response is really hard to read

### Steps to reproduce

just open an activation link via android Firefox / Chrome

### Version information
- **Homeserver**: v1.24.0

**Comment by clokep** [comment]
Any chance you'd be able to provide a screenshot? I think by default most of the pages provided with Synapse are fairly unformatted (black text on a white/grey background).

**Comment by callahad** [comment]
Hello! This has been marked as "needs info" for a while without us hearing back from you.

Since we don't have enough information to proceed, I'm going to go ahead and close this issue. Please feel free to re-open it once you've addressed the request above. Thanks!
