### ISSUE TITLE
remove purge_room and shutdown_room

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9052]
v1.25.0 deprecated `/_synapse/admin/v1/purge_room` and `/_synapse/admin/v1/shutdown_room/<room_id>` (see #8829). We should remove them at some point in the future.

__Blockers:__

- [x] matrix-org/mjolnir#76

**Comment by richvdh** [comment]
(NB currently mjolnir is using shutdown_room: https://github.com/matrix-org/mjolnir/issues/76)

**Comment by dklimpel** [comment]
See PR: #8830

**Comment by richvdh** [comment]
We should set a deadline for this, so that we can wrap up #8830.

**Comment by callahad** [comment]
We'd like to do this by August, will discuss with Mjolnir owners
