### ISSUE TITLE
Whatsapp import/migration

### ISSUE THREAD

**Issue by june07** [matrix-org/synapse#9060]
With many (including myself) moving away from Facebook products like Whatsapp (also ig, etc), it would be great to be able to import the entire message database from Whatsapp to Synapse.  Is this currently possible?

I have both the Whatsapp bot installed and working however it seems that it's tightly integrated with Whatsapp Web and as such doesn't work when your phone with Whatsapp account is disconnected from the internet, much less Whatsapp removed all together.  The idea is to STOP USING WHATSAPP PERIOD.  Yet to be able to keep the history of messaging on the Whatsapp platform.

Apologies if this has already been addressed, I searched but didn't see anything...

**Comment by Half-Shot** [comment]
Hi there. Synapse doesn't offer features that let you migrate from one service to another, which is usually the role of other services (for instance, ems.element.io provide a system to migrate from Slack to Matrix). With this in mind, I'm going to close this issue as it's something the Synapse team will not be working on.

All this being said, I suspect that https://github.com/tulir/mautrix-whatsapp/'s bridge is the best place to talk about potentially migrating messages away from Whatsapp. Hopefully that's enough to get you started.
