### ISSUE TITLE
IPFS & Unstoppable Domains

### ISSUE THREAD

**Issue by trymeouteh** [matrix-org/synapse#9061]
Would be cool to see Matrix adopt next gen protocol IPFS and to support unstoppable domains for blockchain domain names that run on IPFS and this can be done and managed on synapse and the clients like Element will not need to add support for IPFS since the server can handle all of it.

**Comment by clokep** [comment]
Seems like this would need to be specified first before implementing in synapse, see matrix-org/matrix-doc#2706.
