### ISSUE TITLE
PID file is not created

### ISSUE THREAD

**Issue by sumpfralle** [matrix-org/synapse#9066]
### Description

After starting synapse, the configured `pid_file` (e.g. `/var/run/matrix-synapse.pid`) is not created.

### Steps to reproduce

1. start synapse: `su -s /bin/bash -c "/usr/bin/python3 -m synapse.app.homeserver --config-path /etc/matrix-synapse/homeserver.yaml --config-path /etc/matrix-synapse/conf.d/" matrix-synapse`
2. look up the location of the configured PID file: `grep -r pid_file /etc/matrix-synapse`
3. verify that the PID file does not exist

The documentation of the `pid_file` indicates, that it should be created, when *matrix-synapse* is started as a daemon. Since there is no specific *daemonize* argument, I assume, that this startup mode is the default.

### Version information

1.24.0

- **Platform**:

Debian (buster-backports)

**Comment by richvdh** [comment]
> Since there is no specific daemonize argument, I assume, that this startup mode is the default.

From `python3 -m synapse.app.homeserver --help`:

> ```
>   -D, --daemonize       Daemonize the homeserver
> ```

you can also specify `daemonize: true` in the config. 

It is *not* the default.

**Comment by sumpfralle** [comment]
Ah - my bad. I probably looked at the wrong place.
Thank you for correcting me!

**Comment by andrewshadura** [comment]
I believe the confusion arose due to a workaround to another issue having been applied:

https://bugs.debian.org/920339#67

> So it seems that matrix-synapse's --daemonize doesn't properly close
> file descriptors upon forking — which is likely an upstream issue.

**Comment by richvdh** [comment]
@andrewshadura could you open a new issue for that?

**Comment by andrewshadura** [comment]
Filed as #9099.
