### ISSUE TITLE
Support for https traffic to the proxy

### ISSUE THREAD

**Issue by Bubu** [matrix-org/synapse#9090]
**Description:**

Note: this is different from talking https via the proxy (via HTTPS_PROXY). This is about supporting https for the synapse -> proxy-server connection.

From what I understand this feature is not that widely supported yet (though the article below is from 2016). But for complete proxy support for synapse this might be worth adding.

Context: https://daniel.haxx.se/blog/2016/11/26/https-proxy-with-curl/

**Comment by Bubu** [comment]
There's a comment about this here: https://github.com/matrix-org/synapse/blob/develop/synapse/http/proxyagent.py#L187-L189

**Comment by Bubu** [comment]
I have a working commit for this now: https://git.bubu1.eu/Bubu/synapse/-/commit/d7c77ce51ed002af94316c1c277c0d020cd26368

Need to add tests, etc.

**Comment by anoadragon453** [comment]
This looks promising, thanks @Bubu! In-progress PR is here: https://github.com/matrix-org/synapse/pull/9119
