### ISSUE TITLE
Question about Synapse Server completly isolated

### ISSUE THREAD

**Issue by lunainvictum** [matrix-org/synapse#9094]
Hi!

First: I dont want a Matrix Account and dont want to use it. I dont accept the Data Policy from Matrix.org, so it isnt for me possible to ask for Information or Support there.  

Since Months im searching for a way to host a messagingservice at my place, where i have 100% control over it. Without any connection outside to other services or servers. 

I asked friends and searched online, and everybody says matrix-synapse is the way to go.

Then i dig deeper, and found out that it isnt possible to set up a matrix-synapse Server completly isolated. 

I found these Issuses:
github.com/matrix-org/synapse/issues/6401
github.com/matrix-org/synapse/pull/2820
github.com/matrix-org/synapse/issues/2917

And no solution. Until now i use a jabber server and clients for Android. But this isnt a practicable solution for a long term use. 

Is there a way or documentation how to set a server up like described? Or a another free open source project wich makes this possible?

Thanks for help & suggestions.

Sry for my bad english. Im a old german native speaker.

**Comment by clokep** [comment]
You can run a Synapse that is not federated with other servers. You can control what servers Synapse will talk to via the `federation_domain_whitelist`. There might be some other tweaks (as discussed in #6401 that would make this better), but it is possible to do that today.

**Comment by lunainvictum** [comment]
Thanks for your Answer.

Year like you see, i already found 6401.

But what means that:

"Setting the federation whitelist to an empty string,
Disabling the federation listener
Auditing all other cases where an outbound federation request might be made."

The first i understand i can do that with federation_domain_whitelist.
But how i disable the federation listener ?

And what means the third one?

**Comment by clokep** [comment]
>  Disabling the federation listener

The easiest way to do this is probably at the firewall, blocking all traffic to `/_matrix/federation` path.

I'd suggest asking in the #synapse:matrix.org channel to see if anyone has already done this!

**Comment by dklimpel** [comment]
You can block `/_matrix/federation` in your reverse proxy and do not enable `federation` listener.

https://github.com/matrix-org/synapse/blob/98a64b7f7f256b7afd4a1d735cb32d099e44831a/docs/sample_config.yaml#L229-L275
