### ISSUE TITLE
Login UX seems to have regressed a little

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#9101]
- The important elements for understanding which homeserver you're joining and how to change it seems to have been spread out
- The message copy in the (i) tooltip isn't very helpful

The title 'Homeserver' no longer appears associated with the value or the information tooltip, and the tooltip references 'custom server options' which is not a phrase that's visible elsewhere in the login UX. It also talks about using Element with an existing Matrix account on a different homeserver but you can use Element to register new accounts on different homeservers too.

Old:
![image](https://user-images.githubusercontent.com/1922197/104467804-a53f6d80-55ae-11eb-8402-73108dc84b60.png)

New:
![image](https://user-images.githubusercontent.com/1922197/104467778-9eb0f600-55ae-11eb-8e2c-b81df81aa5d4.png)

**Comment by richvdh** [comment]
@lampholder: this looks like an element-web issue?

**Comment by richvdh** [comment]
closing in favour of https://github.com/vector-im/element-web/issues/16297

**Comment by lampholder** [comment]
Indeed it clearly does - apparently my brain was not functioning well on Jan 13. Thanks @richvdh
