### ISSUE TITLE
LDAP / TLS triggering internal server error

### ISSUE THREAD

**Issue by Ekleog** [matrix-org/synapse#912]
Hello,

With the last release of synapse, I am setting up a connection using ldaps, and face an internal server error when running over tls. https://github.com/matrix-org/synapse/pull/838/files solved the internal server error for me, but for some reason his author closed it.

You may want to merge this PR, or a similar one.

Thanks for the good work!
Ekleog

**Comment by erikjohnston** [comment]
Can you see if it still fails on develop? A lot of changes were made to the LDAP part of the code (including backwards incompatible changes to LDAP config)

**Comment by Ekleog** [comment]
Sorry for being so slow to answer, I completely forgot to answer. On latest release everything seems to work fine, so I guess this issue is solved.

Thanks!
