### ISSUE TITLE
Mute notifications for a while in specific room by specific time: 1 hour, 8 hours, 2 days

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#9126]
**Description:**

Some messengers (WhatsApp, Telegram) have very useful feature to mute rooms for specific time (eg 1 hour, 8 hours, 2 days, etc). Will be good to have same feature in Matrix too. As I understand, this feature at first must be implemented on server side (next step - on client side), so post issue in Synapse queue.

**Comment by clokep** [comment]
I think this is a duplicate (of the poorly worded) #1356.

**Comment by MurzNN** [comment]
Thanks for finding duplicate, I also found https://github.com/matrix-org/matrix-doc/issues/2449 in matrix-doc
