### ISSUE TITLE
Wrong presence management

### ISSUE THREAD

**Issue by ylecollen** [matrix-org/synapse#913]
i still have some presence issues
The tests have been done around 07/08/2016 at 10:50 UK time.

@ylecollen:matrix.org and @ylecollen2001:matrix.org discussed in https://vector.im/beta/#/room/!HyEinSjhPKvSyHeSyz:matrix.org

-> each account uses 2 clients (one webclient and one mobile client)
The clients are in foreground

The following presences are the same on each client (web, IOS or android)

1 - ylecollen2001 backgrounds / debackgrounds his mobile client : the ylecollen2001 status is not "online"
2 - the ylecollen2001 presence is never seen online whereas ylecollen2001 is sending message

So, the presence seems bugged on server side.

**Comment by richvdh** [comment]
I don't think we can do anything with this
