### ISSUE TITLE
Encryption on metadata

### ISSUE THREAD

**Issue by trymeouteh** [matrix-org/synapse#9133]
Timestamps, emoji reactions, message sender, read receipts, and possibly files are not encrypted in encrypted DMs and rooms. Please have encryption cover all of these things and not just the message itself.

**Comment by richvdh** [comment]
there are a number of issues about this on the matrix-doc project, such as https://github.com/matrix-org/matrix-doc/issues/2318 and https://github.com/matrix-org/matrix-doc/issues/2678. It's a protocol-level feature so more appropriate on matrix-doc.
