### ISSUE TITLE
_matrix/push/v1/notify  No Such Resource

### ISSUE THREAD

**Issue by XSvr** [matrix-org/synapse#9136]
I is setuping up sygnal.
when i check 
    https://mydomain.com/_matrix/push/v1/notify
return No Such Resource 404
is my config error?
 nginx config:

location ~* ^(\/_matrix|\/_synapse\/client) {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 50M;
    }

location /_matrix/push/v1/notify {
      proxy_pass http://127.0.0.1:5000/;
      proxy_set_header X-Forwarded-For $remote_addr;
   }

**Comment by dklimpel** [comment]
Try to remove the slash:
`proxy_pass http://127.0.0.1:5000;`

**Comment by richvdh** [comment]
this is not a synapse bug. You might be able to find some help in `#sygnal:matrix.org`.

**Comment by XSvr** [comment]
location /_matrix/push/v1/notify {
proxy_pass http://127.0.0.1:5000/_matrix/push/v1/notify;
proxy_set_header X-Forwarded-For $remote_addr;
}

it is my solution。。
