### ISSUE TITLE
Always encrypt 1:1 DMs and private groups

### ISSUE THREAD

**Issue by trymeouteh** [matrix-org/synapse#9140]
Please have Matrix always encrypt 1 on 1 chats and always encrypt private group chats to ensure the user is always using encryption no matter what client they are using.

**Comment by leesalminen** [comment]
Perhaps https://github.com/matrix-org/synapse/blob/2de7e263ed0280b21fa0e165bf220b501e6e6d76/docs/sample_config.yaml#L2400 is what you're looking for?

**Comment by clokep** [comment]
The option specified above should help this -- it is up to the clients to decide whether a room is encrypted or not. I'm going to close this since it seems unrelated to Synapse, it might be a client issue though?
