### ISSUE TITLE
PyPi packages matrix-synapse[all] and matrix-synapse[redis] do not exist

### ISSUE THREAD

**Issue by joh-ku** [matrix-org/synapse#9141]
### Description

Installation of `matrix-synapse` as outlined [here](https://github.com/matrix-org/synapse/blob/master/docs/workers.md#setting-up-workers) using `pip install matrix-synapse[all]` or `pip install matrix-synapse[redis]` does not work. Pip claims `pip: No match.`

### Steps to reproduce

Install `matrix-synapse` from source and execute `pip install matrix-synapse[all]` or `pip install matrix-synapse[redis]`.

### Solution

Install dependencies manually (in this case redis dependencies):

```
pip install txredisapi hiredis
```

### Version information

| Software | Version |
| :------------: | ----------: |
| matrix-synapse | 1.25.0 |
| python | 3.9.1 |
| redis | 6.0.10 |

### Platform

**OS** in use is **FreeBSD 12.2-RELEASE-p1 GENERIC amd64**

**Comment by clokep** [comment]
It is possible that your shell is interpreting the brackets -- putting quotes around it might work: `pip install "matrix-synapse[all]"`

Otherwise I'm not sure what could be causing this as the options definitely exist. Are there longer logs? Maybe try including the `--verbose` option?

**Comment by joh-ku** [comment]
Sometimes you don't see the wood for the trees.. :laughing: without escaping, `[` is a candidate for filename substitution in [csh/tcsh](https://www.freebsd.org/cgi/man.cgi?query=csh). Thank you!

**Comment by clokep** [comment]
Glad that worked! I put up a pull request (#9151) to make the documentation clearer.

**Comment by joh-ku** [comment]
> Glad that worked! I put up a pull request (#9151) to make the documentation clearer.

This can not hurt in any case! :100:
