### ISSUE TITLE
Splash screen for rooms on join

### ISSUE THREAD

**Issue by ToastedAvocado** [matrix-org/synapse#9142]
I feel like it would be of great benefit to users for there to be a splash screen with the room description on join or join request. For example, to see rules, features, and other beneficial information for users.

**Comment by clokep** [comment]
I think this is either a spec issue or client issues, not a server issue. Some of this might be covered by matrix-org/matrix-doc#2875.

**Comment by ToastedAvocado** [comment]
How so? Maybe I'm missing something.
