### ISSUE TITLE
allow to disable room history completely

### ISSUE THREAD

**Issue by maichai** [matrix-org/synapse#9147]
**Description:**

For each given room there are already a lot of options available that influence the behavior of encryption keying. All of these options imply that there is a history kept. Keeping a history means that also the user session profiles are kept to be able to show a meaningful history.

It is good that all these options are available and they help tailoring rooms to their use cases.
However, some rooms would benefit more from data thriftiness than from keeping history and state indefinitely.
Some room admins would rather choose to keep no history at all, do reduce the data that is kept about the participants of the room. I have met a number of people who stick with IRC for the reason that Matrix keeps too much state data due to the history functionality.

I strongly advocate that room the history feature can be disabled for a room as one of the options, and that in this case, no data is retained that is needed for this room's history, i.e. also no user session data connected to that room (unless of course these users are also using rooms with history...).

**Comment by clokep** [comment]
I think the message retention settings in Synapse will support the sort of feature you're interested in. Note that this is currently experimental so there might be rough edges. (In particular #6832.)
