### ISSUE TITLE
Release 1.26.0rc1

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#9152]
# Release Candidate Checklist

I'm curious if it'd be easier / more consistent / less error-prone to work from an actual checklist.

If y'all could humor me for 1.26, I'd appreciate it.

This is cribbed from Element's internal notes at https://wiki.element.dev/Synapse#releasing-synapse

## 1. Pre-Flight

- [x] Verify there are [no open release blockers](https://github.com/matrix-org/synapse/issues?q=is%3Aopen+is%3Aissue+label%3A%22release+blocker%22)
- [x] Verify any applicable steps from the [Security Release Playbook](https://wiki.element.dev/Security-release-playbook) (Element internal link) have been taken

## 2. Branch Preparation

- For __rc1__ only:
    - [x] Pull Synapse's `develop` branch locally
    - [x] Create and push a branch called `release-vX.Y.Z` based on `develop`
        _Note: There is no `rc` part; the same branch is used for releases and candidates_
    - [x] Repeat the above two steps for Sytest

- For all release candidates:
    - [ ] [Deploy](https://wiki.element.dev/Synapse#redeploying-matrix-org-synapse) the Synapse release branch to `matrix.org` and ensure it does not fall over

## 3. Version Bump

- [x] Update `__version__` in `synapse/__init__.py` to `"X.Y.ZrcN"`
    _Note: There is __no separator__ before the `rc` part_

- [x] Set an environment variable for the release version in your shell

   ```sh
   ver=`python3 -c 'import synapse; print(synapse.__version__)'`
   ```

- [x] Run Towncrier: `python3 -m towncrier`

- [x] Commit and push

    ```sh
    git add -u \
        && git commit -m $ver -n \
        && git push -u origin $(git symbolic-ref --short HEAD)
    ```

- [x] Request review of the changelog

    ```sh
    python3 -m webbrowser -t "https://github.com/matrix-org/synapse/blob/$(git symbolic-ref --short HEAD)/CHANGES.md"
    ```

- [x] Review completed

## 4. Finalize Release

- [x] Create a signed tag for the release: `git tag -s v$ver`
    - For __rc1__ use the notes since the previous release, including the _"Synapse vX.Y.Z (date)"_ header. 
    - For __rc2__ and later, include only the changes since the previous release candidate.

- [x] Push the tag: `git push origin tag v$ver`

- [x] Download the `.whl` and `.tar.gz` file from [buildkite](https://buildkite.com/matrix-dot-org/synapse/builds?branch=release-*)
    _Note: These are found in the "Artifacts" tab of the "Build Distribution Files" step_

- [x] Upload the artifacts to PyPI:

    ```sh
     cd ~/Downloads
    twine upload matrix_synapse-$ver-py3-none-any.whl
    twine upload matrix-synapse-$ver.tar.gz
    ```

- [x] Create the Release on GitHub

    ```sh
    python3 -m webbrowser -t "https://github.com/matrix-org/synapse/releases/edit/v$ver"
    ```

    - [x] Set title to `vX.Y.ZrcN`
    - [x] Mark as pre-release
    - [x] Copy the description from the tag message
    - [x] Verify that all links in `CHANGES.md` work (esp. relative links)

## 5. Wrap Up

- [x] Merge the release branch into `develop`:

    ```sh
    git checkout develop
    git pull
    git merge v$ver
    git push
    ```

- [x] Notify [#homeowners:matrix.org](https://matrix.to/#/#homeowners:matrix.org) and [#synapse-dev:matrix.org](https://matrix.to/#/#synapse-dev:matrix.org); keep an eye out for bug reports.
- [ ] Tweet via [@matrix.org](https://twitter.com/matrixdotorg/)

**Comment by clokep** [comment]
This is done minus tweeting. I think @callahad will take care of that?

**Comment by callahad** [comment]
Yep! Will tweet tomorrow juuuust in case some of the earliest of early adopters turn up anything unexpected.

**Comment by callahad** [comment]
Not tweeting; we have a release blocker (#9187) which will require an rc2.
