### ISSUE TITLE
Nginx proxy confuguration in install docs is not working ( regex issue)

### ISSUE THREAD

**Issue by waleedsaud** [matrix-org/synapse#9155]
### Steps to reproduce

- install matrix synapse server from matrix debian repo
- install nginx from ubununt 20.04 repo
- use the the config for reverse proxy found in https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md#nginx

Nginx can't find the url part specified by this regex  `location ~* ^(\/_matrix|\/_synapse\/client)`   .

**Comment by clokep** [comment]
This was updated in #8227, maybe that had a bug. You should be able to do the same thing by specifying both `/_matrix` and `/_synapse/client` as locations with the same config.

I'd suggest asking in #synapse:matrix.org to see if anyone has thoughts.

**Comment by waleedsaud** [comment]
Thank you very much it is solved based 8227 and sorry for opening the ticket in the wrong repository .

**Comment by clokep** [comment]
@waleedsaud This is the correct repository. Can you describe a bit more about how you fixed this? I'm curious if there's a bug in our documentation!

**Comment by waleedsaud** [comment]
I used the / instead on the whole regex .
thank you again for the work you did in matrix it is very good to work with.

**Comment by seth586** [comment]
> I used the / instead on the whole regex .
> thank you again for the work you did in matrix it is very good to work with.

Can you post the whole nginx location {} block you are using that works?

Thank you!

**Comment by waleedsaud** [comment]
`server {
    listen 443 ssl;
    listen [::]:443 ssl;

    # For the federation port
    listen 8448 ssl default_server;
    listen [::]:8448 ssl default_server;

    include snippets/self-signed.conf;
    server_name notify.nic;

    location / {
        proxy_pass http://127.0.0.1:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 50M;
    }
}
`

**Comment by seth586** [comment]
The fix above exposes `/_synapse/admin`, I found a fix for the regex:
```
location ~ ^/(_matrix|_synapse/client)/ {
        proxy_pass http://127.0.0.1:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
        client_max_body_size 50M;
    }
```
