### ISSUE TITLE
Add maintenance vacuum

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#916]
On a configureable time, once a week the homeserver.db should go down vor maintenance to do a VACUUM to minimize the database size on the server.

It would be cool, if there was a maintenance mode, so the users see, they just have to wait some minutes.

**Comment by rubo77** [comment]
I tried vacuum on my 3.5GB homeserver.db, which took about 45minutes to finish, and in the end it was still 3.3GB, so it seems vacuum has no big effect. Maybe we can add some more maintenance, that scrinks the database file better?

**Comment by ara4n** [comment]
@erikjohnston has been working on precisely this.

**Comment by rubo77** [comment]
Do you mean this? 

https://github.com/matrix-org/synapse/blob/master/docs/admin_api/purge_history_api.rst

**Comment by rubo77** [comment]
I created a gist file here: https://gist.github.com/rubo77/458eb4808d665e619feeaf556476f73f

But I need some more help

**Comment by rubo77** [comment]
https://github.com/matrix-org/synapse/pull/911 added this 

so is there a `vacuum` needed after pruning old history?

**Comment by aperezdc** [comment]
FWIW, some databases may do additional work during a `VACUUM` which may result in improved performance, especially for very busy tables. In particular, for PostgreSQL [it is documented](https://www.postgresql.org/docs/current/static/routine-vacuuming.html) that vacuuming will make the query planner and index accessing work faster:

> PostgreSQL's VACUUM command has to process each table on a regular basis for several reasons:
>
> 1. To recover or reuse disk space occupied by updated or deleted rows.
>
> 2. To update data statistics used by the PostgreSQL query planner.
>
> 3. To update the visibility map, which speeds up index-only scans.
>
> 4. To protect against loss of very old data due to transaction ID wraparound or multixact ID wraparound.

Maybe it would be good idea to add a note to [postgres.rst](https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst) recommending automatic vacuuming in `postgresql.conf`, so Synapse does not need to it by itself (though it's something that maybe needs to be handled anyway in Synapse when using SQLite).

**Comment by richvdh** [comment]
postgres manages its own vacuums; it's not our job to sort it out.

**Comment by rubo77** [comment]
> Maybe it would be good idea to add a note to [postgres.rst](https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst) recommending automatic vacuuming in `postgresql.conf`

https://github.com/matrix-org/synapse/pull/8651
