### ISSUE TITLE
 "ongoing conference call" all the time

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#917]
since one day, I see the message  "ongoing conference call" all the time at the top in "Matrix HQ"

How do I get rid of this message? there seems to be a conference call stuck somehow

**Comment by ara4n** [comment]
This is caused by matrix-org/matrix-appservice-verto#4 and matrix-org/matrix-appservice-verto#5.  call state is now reset.

**Comment by user318** [comment]
I have the same issue in one of the chats. It lasts for several weeks already.

**Comment by rubo77** [comment]
So is there a workaround?

Maybe a call to the database?

**Comment by plinss** [comment]
Having the same issue. Trying to join the "ongoing conference" creates a new room FWIW (and doesn't seem to work).

**Comment by user318** [comment]
> Trying to join the "ongoing conference" creates a new room FWIW (and doesn't seem to work).

Me too. How to get rid of this "call"?
