### ISSUE TITLE
Federation senders fall behind after restart

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#9172]
If you have a bunch of federation senders and restart they will lag while the caches warm up due to calls to `get_hosts_in_room_at_events`. Adding more federation senders doesn't help as that gets called to figure out whether the current worker should handle the event, i.e. it gets called on every federation sender for every local event:

https://github.com/matrix-org/synapse/blob/921a3f8a59da0f8fe706a22627f464a74b54c992/synapse/federation/sender/__init__.py#L201-L209

This is quite a big issue as every restart federation will lag by ~10mins for ~10mins (or more)

We could pre-calculate which federation senders handle a particular event, e.g. on the event creators, but large rooms ─ which likely contribute the most to slow `get_hosts_in_room_at_events` ─ will often be handled on every federation sender anyway, so that might not help much.

**Comment by clokep** [comment]
@erikjohnston was this fixed by #9198?

**Comment by erikjohnston** [comment]
Oooh, yes!
