### ISSUE TITLE
make_room_admin admin API should check if a user is in the room before sending a PL event on their behalf

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#9175]
Currently it will indiscriminately pull the first user out of the power_level list that has a high enough PL, but it's possible for that user to not be in the room. Given we already pull the membership to check if the requester is in the room, we should check this too.

**Comment by y-pankaj** [comment]
Hi! I would like to work on this issue.
As far as I get it, I should use `room_state.get((EventTypes.Member, admin_user_id))` to check if the user is in the room and raise an error if the user not found below the line:
https://github.com/matrix-org/synapse/blob/a7882f98874684969910d3a6ed7d85f99114cc45/synapse/rest/admin/rooms.py#L434
Also, what error should I raise?
https://github.com/matrix-org/synapse/blob/a7882f98874684969910d3a6ed7d85f99114cc45/synapse/rest/admin/rooms.py#L431-L432
I guess it should be similar to this with the error statement changed. Also, what should be the error statement raised.

**Comment by clokep** [comment]
@y-pankaj That seems reasonable. I think we would want to only raise that error if none of the users in the power_level list are able to be used.

**Comment by clokep** [comment]
I believe this is fixed by #9235.
