### ISSUE TITLE
add_threepid email confirmation emails link to /unstable/ namespace

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9197]
When you add an email address to an account, you get an email which invites you to click on a link whose path is `https://<server>/_matrix/client/unstable/add_threepid/email/submit_token?token=...&client_secret=...`.

We should not be using an `unstable` prefix for stable features. The correct path for this would be something under `https://<server>/_synapse/client/...`.  Of course we'll have to support both for a while to avoid breaking the links in any emails that have already been sent.

(This was added in #6042, and probably should have been cleaned up as part of finalising https://github.com/matrix-org/matrix-doc/pull/2290)

**Comment by DMRobertson** [comment]
AFAICS no endpoint with `add_threepid` is specced. I'm not sure if this is a spec omission, or an implementation detail that should be kept under the `/_synapse` namespace.

**Comment by DMRobertson** [comment]
Patrick notes this and the related `/_matrix/client/unstable/add_threepid/msisdn/submit_token` on https://github.com/matrix-org/synapse/issues/8334.

I suggest we close this as superseded by that issue.

**Comment by clokep** [comment]
I think it would be more useful to make the results of #8334 actionable into separate issues.

I suggest we leave this open as a separate task.
