### ISSUE TITLE
Account data seems broken on develop/release-1.26

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#9201]
Account data is not taking effect on a homeserver configured to use the main process for handling account data. There are no errors in the logs. The server is running a separate synchrotron.

The sync stream position doesn't appear to be updating, and the account data is lacking from /sync responses.

**Comment by clokep** [comment]
Just to be clear -- this is on a server including the changes in #9193?

**Comment by erikjohnston** [comment]
(and https://github.com/matrix-org/synapse/pull/9195?)

**Comment by Bubu** [comment]
I just updated to release-v1.26.0 HEAD and that seemed to fix this problem for me.

**Comment by Bubu** [comment]
Well, on the other hand additional clients don't seem to get the account data updates... even after the update. :thinking:

**Comment by erikjohnston** [comment]
@turt2live issue appears to be the server wasn't actually running latest develop after all.

> Eek, that works now as well. Maybe it needed some more time to settle.

Yeah, it might have taken a while for all the sync streams to have caught up with all the account data it had missed.
