### ISSUE TITLE
Leaving a room as a group admin breaks the group roomlist

### ISSUE THREAD

**Issue by tari** [matrix-org/synapse#9211]
### Description

As a group admin, leaving a room that is associated with the group causes it to appear incorrectly for all users. This was originally reported as an Element bug (https://github.com/vector-im/element-web/issues/15375), but from inspecting the API responses this seems like it's a Synapse issue.

### Steps to reproduce

 * Create a group +foo:example.com
 * Create the room #foo-offtopic:example.com and add it to +foo:example.com
 * Leave #foo-offtopic:example.com

All users (including yourself) will now continue to see the room via `GroupRoomServlet` requests, but lacking any room information- it has no name or alias (even if published) so cannot be joined.

For instance, before leaving the room, the object returned looks like this (real response, lightly anonymized):

```
{
  "room_id":"!xCfjIbkGyBzlFQmuBg:nltrix.net",
  "num_joined_members":18,
  "m.federate":true,
  "name":"Some Room",
  "topic":"Topic goes here",
  "canonical_alias":"#someroom:taricorp.net",
  "world_readable":false,
  "guest_can_join":false,
  "is_public":true
},
```

After I leave the room, the group room response contains this room like this:

```
{
  room_id: "!xCfjIbkGyBzlFQmuBg:nltrix.net",
  num_joined_members: 0,
  is_public: true
}
```

Attempting to join the room in Element from the group's room list fails, and other users report the same behavior. Rejoining the room via its canonical alias works as expected.

### Version information

- **Homeserver**: taricorp.net
- **Version**: 1.25.0
- **Install method**: [nixos package](https://github.com/Vskilet/nixpkgs/blob/master/nixos/modules/services/misc/matrix-synapse.nix)
- **Platform**: NixOS Linux, x86 virtual machine

**Comment by anoadragon453** [comment]
Thank you for your report.

Groups in their current form are known to be buggy, and are due to be completely replaced by [Matrix Spaces](https://github.com/matrix-org/matrix-doc/pull/1772) soon. As such this is unlikely to get fixed before that lands.

**Comment by NonstickAtom785** [comment]
How is that supposed to function? Will you still be able to see old history? And also will the bridges be affected? Will they still be a thing in Matrix Spaces? (Our entire group is bridged to a discord server.)

**Comment by tari** [comment]
MSC1772 reconsiders the concepts of the existing groups API in terms of rooms that look a little different. It doesn't have any bearing on rooms that are not themselves groups (not entirely true; there are provisions for a room to declare its membership in a group, but that doesn't affect the room's functioning), so there should be no meaningful change beyond community identifiers as they currently exist (+foo:example.com) becoming obsolete.

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
