### ISSUE TITLE
OpenID Connect `client_secret` should be optional

### ISSUE THREAD

**Issue by tmortagne** [matrix-org/synapse#9212]
I'm surprised to see `client_secret` documented as required since it's not really the case in the OIDC protocol even if it's definitely a good practice especially for big public providers which often do require it.

**Comment by richvdh** [comment]
agreed. Happy to look at a PR which makes it optional.

**Comment by richvdh** [comment]
actually I can probably just do it as part of https://github.com/matrix-org/synapse/issues/9220
