### ISSUE TITLE
On Invitations neither accept nor reject works for specific rooms

### ISSUE THREAD

**Issue by a000a** [matrix-org/synapse#9214]
Hey!

The scenario: 
I invited a user from matrix.org to a room, created by mautrix-telegram bridge.
Bridge and my server are running on c.a2sc.eu

The user tries to accept:
```
Failed to join room
You are not invited to this room.
```

The user rejects:
```
Failed to reject invite
@matrixuser:matrix.org not in room !kjsafksaldlsad:my.homeserver.
```

The error occurs very fast. Therefor, I don't think my server is even been connected from matrix.org - my serverlogs also don't show anything.

Clearing the cache before and after in Element does not help

If I invite s.o. from my homeserver to this group, no issues occur.
If I invite a user from matrix.org directly to another room, it works as well.

**Comment by anoadragon453** [comment]
Looks like matrix.org didn't properly store the invite, and thus any attempts to join will be met with "you are not invited", and any attempts to leave will be met with "you don't have an existing membership event in this room. You can't leave a room you're not in".

So why did matrix.org not store the invite? I dug into the `events` table for this room and indeed do not see any membership events regarding the invited user.

More interestingly, almost all events in there (including the create event!) are marked as outlier. The only non-outlier is a join to the room from a local matrix.org user.

I'm a little confused how we ended up in this state, but can see why matrix.org is reporting errors now. You're right in that it won't be contacting your server to accept/reject an invite as matrix.org doesn't think the user has anything to do with that room.

Can you try resending an invite to the user? I may be able to track down what's happening to it.

**Comment by a000a** [comment]
Just did the invite again. thank's for helping

**Comment by a000a** [comment]
It worked with the latest server update of matrix.org (`1.29.0rc1`).
I could reject the invitation. after getting a new invite it worked and I could join the room without any problems

**Comment by anoadragon453** [comment]
Hey, sorry for the late response here. I'm glad to hear the issue was resolved.

I don't see anything particularly relevant in [synape's changelog](https://github.com/matrix-org/synapse/blob/develop/CHANGES.md) that looks like it could have fixed the issue, but perhaps it was something subtle. Or perhaps it was something related to the bridge.

Regardless, happy it's fixed.
