### ISSUE TITLE
make_room_admin is really slow

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/synapse#9215]
make_room_admin is really slow. I think it depends on the number of users in the room. But it's in the order of 5 minutes to one that's now been running for more than 30 minutes.

**Comment by anoadragon453** [comment]
@erikjohnston would you happen to know off the top of your head why this might be/what might be a good candidate for optimisation?

**Comment by erikjohnston** [comment]
I can't see why it would be terribly slow compared with anything else, unless the process is at 100% CPU or something?

**Comment by anoadragon453** [comment]
@kroeckx do you notice this request being an exceptionally slow task compared to others?

If not, setting up [some metrics](https://github.com/matrix-org/synapse/blob/develop/docs/metrics-howto.md) could shed light on what the bottleneck be and whether it's related to this endpoint specifically.

**Comment by kroeckx** [comment]
I did have lots of issues, but not that large. I run my own IRC
bridge. When there was a little activity, like more than a few
messages per minute, CPU usage goes to 100%, and I lost various
messages between IRC and matrix. You saw people reply to messages
before the other person said something, talking to people not in the
room and so on. It sometimes takes minutes before element would
update the screen. If I send a message, it would sometimes take more
than a minute before it changes from grey to black, and other
people's message got in between.

My experience with matrix has been really bad the past 4 years. I
left 20 or 30 rooms, and that made it a little better, but really
still not usable, I was almost at the point where I only use matrix
to talk to people on IRC in a very crappy way, and was considering
just quitting with matrix.

Messages really never took 55 minutes, the delays where something
in the order of minutes. So yes, it was taking 100% CPU usage at
that time.

But I've used the make_room_admin to make myself admin in the
rooms for which I run the IRC bridge, and then upgraded the rooms
from v1 to v6. Since then everything is much faster, it's not
using 100% CPU.

**Comment by anoadragon453** [comment]
So it sounds like `make_room_admin` isn't the problem, but that the CPU was saturated while running it. I'm glad to hear that the new rooms are much faster. Likely reason being that rooms with lots of state modifications in them (such as many join/parts, as is common in IRC rooms) can cause quite a load on the server as it resolves state. Upgrading the rooms created new rooms with a clean slate for state events.

Speeding up state resolution is one of the primary focuses of the team right now, and IRC rooms are right up at the top of the biggest targets for speedup.

I think we're all set to close this issue about `make_room_admin`. Feel free to open another one if performance suffers anywhere else. Thanks!
