### ISSUE TITLE
Config is missing macaroon_secret_key

### ISSUE THREAD

**Issue by doomspace** [matrix-org/synapse#9219]
good afternoon!
i have checked the service status? and hove found notes about macaroon secret key.

=========================================
root@ccc:~/synapse$ systemctl status matrix-synapse
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-01-25 13:30:55 +04; 5h 19min ago
    Process: 454 ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys (code=exi>
   Main PID: 678 (python)
      Tasks: 2 (limit: 4468)
     Memory: 124.0M
     CGroup: /system.slice/matrix-synapse.service
             └─678 /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/

ينا 25 13:30:43 cis systemd[1]: Starting Synapse Matrix homeserver...
ينا 25 13:30:54 cis matrix-synapse[678]: This server is configured to use 'matrix.org' as its trusted key server via the
ينا 25 13:30:54 cis matrix-synapse[678]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
ينا 25 13:30:54 cis matrix-synapse[678]: server since it is long-lived, stable and trusted. However, some admins may
ينا 25 13:30:54 cis matrix-synapse[678]: wish to use another server for this purpose.
ينا 25 13:30:54 cis matrix-synapse[678]: To suppress this warning and continue using 'matrix.org', admins should set
ينا 25 13:30:54 cis matrix-synapse[678]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
ينا 25 13:30:54 cis matrix-synapse[678]: --------------------------------------------------------------------------------
ينا 25 13:30:54 cis matrix-synapse[678]: **### Config is missing macaroon_secret_key**
ينا 25 13:30:55 cis systemd[1]: Started Synapse Matrix homeserver.
lines 1-20/20 (END)

=========================================

but if I check nano ~/synapse/homeserver.yaml   - macaroon_secret_key is enabled and it is present!
**is it a bug?**

**Comment by richvdh** [comment]
> /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/

and then...

> but if I check nano ~/synapse/homeserver.yaml

you're checking the wrong homeserver.yaml
