### ISSUE TITLE
Display name limit doesn't apply to per-room display names

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#9236]
As per [discussion](https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$iPQbTIcztGWabBc-pibIGP4E-6tFtN4Zcmk-dRYsQUI?via=matrix.org&via=privacytools.io&via=dendrite.matrix.org) in Matrix HQ, it seems like [Synapse's limit to display name length](https://github.com/matrix-org/synapse/blob/7a2e9b549defe3f55531711a863183a33e7af83c/synapse/handlers/profile.py#L43) doesn't apply to per-room display names.

**Comment by anoadragon453** [comment]
This would just be adding a length check to `update_membership_locked` that would fail the request if the length was too long. Similar to where we prevent per-room profile changes entirely:

https://github.com/matrix-org/synapse/blob/6633a4015a7b4ba60f87c5e6f979a9c9d8f9d8fe/synapse/handlers/room_member.py#L358-L365

**Comment by b-thebest** [comment]
Can I work on  this issue ??

**Comment by anoadragon453** [comment]
@b-thebest Of course!

**Comment by b-thebest** [comment]
Please assign this task to me

**Comment by arya2331** [comment]
is someone still working on it? or I can do this?

**Comment by b-thebest** [comment]
I am working on it

**Comment by richvdh** [comment]
@b-thebest do you have any idea of when you expect to make some progress on it? I don't think it's a big job and if others are ready to pick it up it might be nice to let them do so.

**Comment by b-thebest** [comment]
It was not in list of task assigned to me, that's why I was unable to do
it. I will do it now asap

**Comment by anoadragon453** [comment]
Hey @b-thebest, have you been able to make any progress on this?

**Comment by b-thebest** [comment]
Yes I was working on it. Sorry for being late, during past days my health conditions were not good that's why I was unable to complete it. From today I will take it on and try to complete it as soon as possible

**Comment by richvdh** [comment]
As is normal in open-source projects, we don't generally "assign" issues to individual contributors, and you shouldn't consider this a prerequisite to start work on it.

**Comment by lukasdenk** [comment]
@Azrenbeth Should this issue still be open? According to #10654 the issue is solved.
