### ISSUE TITLE
ui_auth.session_timeout config should allow standard duration formats

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9239]
most durations in the config can be specified in terms of number of seconds/hours/etc (search for `parse_duration`). `ui_auth.session_timeout` seems to have missed the memo.

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/5584#issuecomment-509284013

**Comment by arya2331** [comment]
Hey @richvdh, I wanted to work on this issue. Can I go ahead? How can I start with this?

**Comment by richvdh** [comment]
yes, absolutely. We welcome any contributions - no need to ask permission!

To get started, I suggest you read through https://github.com/matrix-org/synapse/blob/develop/CONTRIBUTING.md if you haven't already, and get yourself a copy of Synapse running on your development machine. Then just find where this setting is parsed, and update the parsing code to allow more duration formats!

If you have any questions, feel free to ask in `#synapse-dev:matrix.org`.

**Comment by arya2331** [comment]
@richvdh what more duration formats are to be allowed  in `parse-duration`?

**Comment by richvdh** [comment]
`parse_duration` itself is fine. The problem is that it's not being called for `ui_auth.session_timeout`.

**Comment by arya2331** [comment]
@richvdh I have written the code for calling parse_duartion for `ui_auth.sessionn_timeout`. Is that ok? and how should I test it?

**Comment by richvdh** [comment]
To test it:
* do the existing unit tests pass?
* you could try manually configuring Synapse with different duration formats and checking that it starts ok
* you could add a new `AuthConfigTestCase` that checks the setting is parsed correctly (look at `tests.config.test_ratelimiting.RatelimitConfigTestCase` for an example of testing config parsing)
* you could also maybe update `tests.rest.client.v2_alpha.test_auth.UIAuthTests.test_can_reuse_session` to use a formatted duration for `session_timeout` instead of an integer.

**Comment by arya2331** [comment]
@richvdh all existing unit tests passed and I am all set to raise a PR. Now I have a doubt, should I push only changes related to calling `parse_duration' or also push changes for `tests.rest.client.v2_alpha.test_auth.UIAuthTests.test_can_reuse_session'.

**Comment by clokep** [comment]
> @richvdh all existing unit tests passed and I am all set to raise a PR. Now I have a doubt, should I push only changes related to calling `parse_duration` or also push changes for `tests.rest.client.v2_alpha.test_auth.UIAuthTests.test_can_reuse_session'.

You'll want to push both changes so that we can test the new code.

**Comment by clokep** [comment]
Fixed by #9426.
