### ISSUE TITLE
SynapseError: 403 - Federation denied with matrix.org

### ISSUE THREAD

**Issue by ufo56** [matrix-org/synapse#9248]
### Steps to reproduce

- Fresh install avhost/docker-matrix docker. Configure nginx proxy. Change server_name on homeserver.yaml. 

- I can send direct messages from matrix.org user to homeserver user and vice versa, matrix.org user can't join my homeserver channel by browsing my server. 

- "Cant find this server or room list" if i try to add new server on "Explore rooms". _See error below_

- matrix.to invite link redirects to channel with error "Failed to join room. No known servers"

- Only way federated user can join my server is  "/invite @username:matrix.org"

Im not using any white/blacklists, commented out on homserver.yaml file.

https://domain.link/.well-known/matrix/server

    {"m.server": "matrix.domain.link:443" }

https://domain.link/.well-known/matrix/client

    {"m.homeserver": {"base_url": "https://matrix.domain.link"}}

Domain

    server_name: "domain.link"

Listeners
      
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
        bind_addresses: ['0.0.0.0']
    
        resources:
          - names: [client, federation]
            compress: false

Federation test all green

`2021-01-28 14:04:42,049 - synapse.http.server - 74 - INFO - GET-63 - <XForwardedForRequest at 0x1511d0201d68 method='GET' uri='/_matrix/federation/v1/publicRooms?include_all_networks=false&limit=1' clientproto='HTTP/1.1' site='8008'> SynapseError: 403 - Federation denied with matrix.org.`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:



<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

{"server_version":"1.26.0","python_version":"3.7.3"}

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
avhost/docker-matrix docker
- **Platform**:
Docker container behind nginx proxy.
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
this isn't the best place to get support. I suggest trying `#synapse:matrix.org`.

**Comment by tsmethurst** [comment]
Heya, I just spent an afternoon looking into it before finding this:

https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml#L156

Just posting it here for future peeps

**Comment by selimb86** [comment]
I have the same problem, I can't get help from the Synapse Admins channel

**Comment by DMRobertson** [comment]
> I can't get help from the Synapse Admins channel

You can register an account on the `matrix.org` homeserver to do so.

**Comment by azmeuk** [comment]
> Heya, I just spent an afternoon looking into it before finding this:
> 
> https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml#L156
> 
> Just posting it here for future peeps

For the record, since the file has change since 2021, the configuration line is:

https://github.com/matrix-org/synapse/blob/a743bf46949e851c9a10d8e01a138659f3af2484/docs/sample_config.yaml#L156
