### ISSUE TITLE
Phone home stats don't include encrypted messages

### ISSUE THREAD

**Issue by jcgruenhage** [matrix-org/synapse#9249]
### Description

Three metrics sent by Synapse to Panopticon are based on `m.room.message`:
 - `daily_messages`
 - `daily_sent_messages`
 - `daily_active_rooms`

The easy way out would be to just change the queries, to include encrypted messages, however, this means that the definition of these metrics changes all of a sudden, meaning you really can't do any statistics based on data from before *and* after that change.

So, as an alternative, I'd suggest adding three metrics, which include `m.room.encrypted` instead of `m.room.message`:
 - `daily_encrypted_messages`
 - `daily_sent_encrypted_messages`
 - `daily_active_encrypted_rooms`

Later, when someone wants to look at the combined stats, that can still be done in the SQL query sent to Panopticons DB.

If that sounds good to you, you'll receive PRs to Synapse and Panopticon sometime early next week for implementing this.

**Comment by clokep** [comment]
@callahad @neilisfragile -- Any thoughts on this? My gut is that having them separate probably makes the most sense.

**Comment by neilisfragile** [comment]
Yes, separate is good because the ratio is important, especially as it changes over time.

**Comment by jcgruenhage** [comment]
fixed in #9283, panopticon PR in matrix-org/panopticon#20.
