### ISSUE TITLE
Getting old room state when using timeline filter 

### ISSUE THREAD

**Issue by manuelbaez** [matrix-org/synapse#9252]
Hi, 

I'm trying to use a filter to get only messages in my room timeline, my filter looks like this:

```json
{
    "room": {
        "timeline": {
            "limit": 1,
            "types": [
                "m.room.message",
                "m.room.encrypted",
            ]
        }
    }
}
```
The problem is that when I'm using this filter I only get old state events even though I haven't specified a filter on them, for example when I update the ```m.room.power_levels```, the change takes effect but I don't get the updated state when I'm using that filter so I tried explicitly specifying the state filter and got the same result, then I thought it might be the limit and tried that too but it was the same.

My filter ended up looking like this:
```
{
    "room": {
        "state": {
            "limit": 9007199254740991, (Yes, I know it's absurd)
            "types": [
                "*",
                "m.room.create",
                "m.room.power_levels",
                "m.room.name",
                "m.room.member",
            ]
        },
        "timeline": {
            "limit": 1,
            "types": [
                "m.room.message",
                "m.room.encrypted"
            ]
        }
    }
}
```

I'm using a Synapse Homeserver, Installed using pip version 1.25.0

**Comment by erikjohnston** [comment]
So you *are* wanting to see updated `m.room.power_levels`? If so then you need to add it to the `timeline` types section. Note that the `state` block contains the state at the *start* of the chunk, and new state appears in the `timeline section. (For incremental syncs the `state` section actually only contains any state that happened between the previous sync and the start of the timeline for the current sync, and so is always empty unless the `limited` flag is set).

Does that clarify things or are you still seeing weirdness?

**Comment by manuelbaez** [comment]
Hi @erikjohnston, thanks for you answer, I understand but I don't get why shouldn't I be able to get the updated states on the state property of the room without receiving it in the room timeline? 

For more context my scenario is the following: 
I'm trying to order the rooms in my client by using the date of the last message in the room, so I just want to receive certain event types in the timeline when I do the initial sync but not to loose access to the updated room state by doing so. The main problem with using the states events in the timeline is that I load a very small amount of events at the start and in some scenarios I only get state events and no messages.

**Comment by richvdh** [comment]
First the information to be returned is split into `state` and `timeline`, according to the `limit` given for the timeline. In this case, the limit is 1, so only the most recent event will ever be returned in the timeline.

Next, the filter `types` are applied and any events that do not match the filter are removed from the response. If an `m.room.power_levels` event has been placed in the timeline, it will be removed if  you do not list `m.room.power_levels` in the filter.

It sounds like you're seeing expected behaviour, so I'm going to go ahead and close this issue. If you need more help with the `/sync` API, `#matrix-dev:matrix.org` is probably the best place.
