### ISSUE TITLE
Feature request: automatically reject invitations

### ISSUE THREAD

**Issue by Bandie** [matrix-org/synapse#9261]
**Description:**
With the amount of users growing on the matrix fediverse, people more and more receive unwanted invitations for groups or direct messages. 
**Possible approach:**
To approach this problem, users should get additional settings to automatically reject invitations for groups and, if wished, for direct messages. The inviter should be informed about the automatic rejection.
**Useful side effect:**
At the same time, the inviter's homeserver could monitor the failed inviting attempts to offer a measurement for fighting spam.

**Comment by erikjohnston** [comment]
This sounds like a valuable thing to have, but I think it needs to be added to the spec as it requires co-ordination between clients and servers. If you could raise an issue (or seeing if anyone else has) in https://github.com/matrix-org/matrix-doc that would be helpful.

> At the same time, the inviter's homeserver could monitor the failed inviting attempts to offer a measurement for fighting spam.

This sounds like a useful metrics to track, and obviously can be done without a spec change. Do you think it'd be helpful by itself?

**Comment by Bandie** [comment]
Thanks @erikjohnston.
I found [SPEC-96](https://github.com/matrix-org/matrix-doc/issues/491) about that.

You mean the number of invitation rejections? Sure! As usual, spam fighting could be valued like `number_of_rejections/time` (something like a max_invitation_rejection_per_hour) which could be set in the homeserver.yaml to automatically refrain to send more invitations or suspend the user and inform the hs admins. (yes, the last point is an own story, ik. :) )

**Comment by richvdh** [comment]
I'm not really following what this is asking for:

> users should get additional settings to automatically reject invitations 

Are you saying that all invitations would be rejected?

**Comment by richvdh** [comment]
closing this due to lack of info.
