### ISSUE TITLE
Trying to set a password during UI Auth while also failing to authenticate during a stage will result in the password not being saved

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#9263]
Related: https://github.com/matrix-org/matrix-doc/issues/2907, https://github.com/matrix-org/synapse/pull/8009

CC: @clokep 

DINUM were finding after upgrading to Synapse v1.23.0 that email registration was no longer working due to "Missing params: password". Their flow consisted of the following requests.

Check with the homeserver what the required flows to register are:
```
POST /register

{}

# get back a sessionID
```

Request a validation token from Synapse (no Sydent involved here):
```
POST /register/email/requestToken

{some client_secret and email address info}

# get back a sid (session ID for validating the email)
```

Request /register again, this time **with a password** which we want to save. We're doing to do a `m.login.email.identity` here even though we know that it's going to fail. Note that `m.login.email.identity` is the only flow the server gives us. We just want to save the password.

```
POST /register

{
  "auth": {
    "threepid_creds": { threepid_validation stuff that won't succeed because the link in the email hasn't been pressed yet },
    "session": "what_we_got_from_the_first_request",
    "type": "m.login.email.identity"
  },
  "password": "please_save_this_password123"
}

# Get back a 401. Fair, I expected this. But my password_hash has been recorded, right?
```

The client got a 401 one, but not from a `InteractiveAuthIncompleteError` exception, but a `LoginError` coming from here:

https://github.com/matrix-org/synapse/blob/c9c0ad5e204f309f2686dbe250382e481e0f82c2/synapse/handlers/ui_auth/checkers.py#L191-L192

Now unfortunately, the code that stores `password_hash` in `ui_auth_sessions` for subsequent UI Auth requests will only do so if a `InteractiveAuthIncompleteError` is raised, *not* `LoginError`:

https://github.com/matrix-org/synapse/blob/789d9ebad3043b54a7c70cfadb41af7a20ce3877/synapse/rest/client/v2_alpha/register.py#L513-L536

So uh oh. A `password_hash` never got saved. In the case of DINUM, a user now clicks the link in their email and is brought to a *completely separate client* which doesn't know what the password is supposed to be.

That client (having validated the threepid) then makes a final request to `/register`:

```
POST /register

{
  "auth": {
    "threepid_creds": { threepid_validation stuff that won't succeed because the link in the email hasn't been pressed yet }
  }
}

# Gets back a 400! Missing params: password
```

And thus registration fails.

---

I think a simple solution here would be to catch `LoginError` in addition to `InteractiveAuthIncompleteError` where we store the pasword_hash:

https://github.com/matrix-org/synapse/blob/789d9ebad3043b54a7c70cfadb41af7a20ce3877/synapse/rest/client/v2_alpha/register.py#L513-L536

That way the client would still get the same exact error, but now we're storing the hash when a `LoginError` is raised. If we go with this, we should also do it in `/account/password`, which does the same:

https://github.com/matrix-org/synapse/blob/7a2e9b549defe3f55531711a863183a33e7af83c/synapse/rest/client/v2_alpha/account.py#L196

Additionally, the client could just send the password without attempting to complete an auth step, though this isn't really clear from the perspective of the client developer.

**Comment by anoadragon453** [comment]
Alright, so just catching `LoginError` where we want to store the password will *not work* as we require pulling a session ID from the Exception. And you can't store a session ID on `LoginError`:

https://github.com/matrix-org/synapse/blob/789d9ebad3043b54a7c70cfadb41af7a20ce3877/synapse/rest/client/v2_alpha/register.py#L531-L535

Instead, I realised that a `LoginError` is only raised by `AuthHandler.check_ui_auth` if you fail a `m.long.email.identity` check, due to this 4 year old tech debt:

https://github.com/matrix-org/synapse/blob/02070c69faa47bf6aef280939c2d5f32cbcb9f25/synapse/handlers/auth.py#L569-L578

If we just remove that conditional, `check_ui_auth` will never raise `LoginError` and thus the password will be saved.

...I assume it's not controversial to remove that at this point? The [issue](https://github.com/vector-im/element-web/issues/2447) was fixed in Riot 0.7.4 (released Oct 12, 2016).

**Comment by anoadragon453** [comment]
The solution of removing the tech-debt indeed solved the issue for DINUM, and the one I recommend we go for. Commit: https://github.com/matrix-org/synapse-dinsic/commit/d36bfdd64d8aad417454a787548f4d458b8a0fec

**Comment by clokep** [comment]
I haven't fully looked at the code again but I think the issue is that they should provide the password in the first step instead of a "get auth session step".

**Comment by clokep** [comment]
So I think the changes in #9265, but I think the client is still doing something unexpected here (and will essentially end up with a second session?).

**Comment by anoadragon453** [comment]
@clokep The session ID from the first "dummy" request is re-used in subsequent requests, and thus they'll only ever have one session. But you're right in that if the password were provided in the first request then it would be saved and the registration would succeed.

Patching in the server in addition to the client is preferable for DINUM however, so that every client does not need to be updated immediately..
