### ISSUE TITLE
power_level event lack of validation of numeric input

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#9267]
### Description

This event was accepted and federated:
```json
 { ...
  "state_key": "",
  "type": "m.room.power_levels",
   "users": {
      "@2016:grin.hu": 8,
      "@2038:grin.hu": "8",
      "@2048:grin.hu": 8,
      "@2069:grin.hu": 8,
   ...
```

Accepting string in numerical position causes completely random behaviour, users may or may not be send any kind of events to the room.

May be related to #8445 in general?

### Steps to reproduce

Send an invalid power_level event. Random users can't send messages anymore.

### Version information

- **Homeserver**:  v1.25.0-1, non E debian package

**Comment by richvdh** [comment]
dup #1237
