### ISSUE TITLE
how to konw push message type?

### ISSUE THREAD

**Issue by XSvr** [matrix-org/synapse#9269]
on homeserver.yaml 
include_content: true

thirdparty push service can not konw is text message or voip message when open e2e function?

{"notification": {"content": {"algorithm": "m.megolm.v1.aes-sha2", "ciphertext": "AwhcEtAb+F2nkYjPVgP7NX6QYnR4DRF943zIpOfeBA7gQKIeBrWNABNQc82mzenH7hp0mJM5AK3pQyQDhuVTpfD5NZlrgoL48jN0FTrBN+n2ZJ2gaMVynvCTWY5wQumpejksui/G1AUhF5uQAKEn8nWpkz0F52XQn5JIfNTiRILf03qWmCavhmDKCQmXlrtz026hQ4o4S7glIw7jE57jm4xzMdIPe2eVUa8jgNZLWAmqvOQpPHA73ze+fb43cgzJnGO9Bbi8Na61rfw/aZUg83l3f7j9+wxy/rK3Yhx6GAvZ/FIR7FzH4CbLaB78PkrKNTj9WhIaMyjlHRxwmWuiHIUVQkBMbeWiKkXsMyU1Og5d+8fdSqJcCgLmkJlDSGrV+HqiBOWub3zYSqmsXRECTJT1TzZuyTZgg1LkLS97d73fDr3wxtvweJc8zZP6ALnq8dmUBBwKqL4eb7rOj3BMcOZ5SjBPg59pGG3CvWLbtlag/qw4gwELCqMd3zEbzovrLm5BLByQg+nVv33eo/AXhkuxjbi+GA92VhVqNKTobqtZ6iIiIYD/G0wXhGOx6FDqJZYWIIEC+84FsVtQxHiCTxu3UAuIh70IPfoMzFqdwH5/YUQfakOLEdGFlWea/pNK8xqHihYGBVIT9xfTbNAy+NZoWjb0iOM38DErAcZGZJCJVcxg73OWwKUout1sSxnJbQAV0QHA8yh15PjgIfJfmtIJ2nvpsoYHG2JsnrM4oFJa7765MZpCnzhA2x8UZWWf4RI3pBlNcRGnD6Za7zJVMdHmH1D3cBY1rniA6n58xxLuB3lMYzUVg9+OnM+sgmmwtj153XhsEaOCGiLRaAsqsmgoqzIgdjVhZqq+3c6OB7cDnsnrB8uIZkscDkPxjzVwQsOBNjlZIV9EM0dq3FS8mF6zAo4ntx/sssic2PbHEMfEKetAJG3D+iDzsohmPtZMogwxYOmpNhgYKfnZayzOGlqCLVtFCdfKywyGhPYmKt6ILSDKkmAiYd6z3Dy5TIU1+mjcGQEorymWUj0jOwPpcuc4MtcZnmsfuBO/XEUdby+Go0PmyORXYDoIpRwyP2Nt41dXg9vRw/SIowgeXchryPnXze+0MPs8MGG8hRD7YazFXsBJjSLFkLYzezhf6C/5RKhB9QYXLfvj5shF25pPMf5ysa+Ufbyiw1JpBUzEIg3Q62Vs6mGa109NLbuIO7bUC4zHVZfZZKYHqv+NrllKOCxn9D8R76sCrCnHSNkOSJxAbVkApbiqAPzKu0wpOYBHQd1RZoST60VFDEKOu9ukT0CGEU8+TzAVVjp6dnSnCw2KSlo60/de754u/UH2iRj3yomNJB+ugK1E+cppS+Rf1aeJPRCWNeOnHIOCpvx9+lG3BsJsXiJ18nVjpWbjEq4nXaVkZyFKgL0ZayqdnLLH1w6eS1GT7/XrvEGZP8HZmd8t8x95loh/vo9QTI5GXBaODwtzCpeY+wr6VpDoDopbukrIDu+vFa0OLfvsMQdlMbC5EH4+eHlecBkUH1IyYLUQszjL5kcHmC2jukpVxEFM9IewVpFeSEz4lcGTcsHWfAsPIuKOu6zxSxSD4Gtseb3XQ8r2tkTC7Kkf53PYGBs6wY2A7PsQvMTYB+u4eTK7wp1BfF/KEZ1P++B6Ed0W6AtrAEwBl/mDeyJrV5UoHGWZskVBn+NoRJRuequVgeEjcYWOAHvh+w8wvJXD4ndqpUUoH0M2Q78p0S1XOHoslg01h6e5sptf1GFgJGuVP/to9mOep4wkMxRcH3lObf4DCSnjP3Sp2GHRC3bViB7plFNFYkUM9o5nSB8cyeN6MDymmrWhA8nCzR50wEGKuEA1nKTzEhCt8j7ZrWSQuKHIoWMsVNqdV9sY2ZnQi0VjQjHOpVmGtBWwm8lttWf5NGzjjwkKD1WnBqWAB/HxXQVhAYUxFlC5YO2FE4OSJO7SEvDmqXhyfeKw9Odin6kxJOaxhc7OzbQuWvyNikCAEK0hvpcb/Y4uv4Pg0c9epjWx1h0sOc1RRge97/X4+XCdwEa3c3rzzKKeHbfHm2mT/ro49vO9keidwDi+htKAvOlBxLT/I/hfuzX9Yc6pOFnZyfip1xkPdQZqBq7twNVSp3kAqmoqBL0Tv+nuZfnf/mcuRwwG0wl2WIhICl1waAjkaJniUiCV+wZicnlWca3nycbn7zEm3oRlKPt+ife7+3Fbh/6RPd2VbslTULPsgckud3MGTSa0qY2A+MELKjB+NI4XsMXY2s29BgR5zmiggefb6uKkY3r/ohjPt13Hm2fkb1MfAh0Gdya8nbqEmY5RmgUmJ3ySyWLdTuHSUA5YsWSGeRlCPOGa9yqU4hhAKw9TpsnsYCO7JHf/u4OO29QssWpmEwxgVtY9zPQEEQu7meZ1dZCRqaTj014y3fVvyIUSomMwLCtwGJZIpa8C8hraZN82pm7xHUN6//c+zAcz3JB6aIRCKD/mTO1kej7adeMAh0HnZKqRrDyvPpHVa0WSwxCIzOJ8lWC5QjPw9QOzqWsAuk54cvPNHj2aphvNLUU", "session_id": "bGH/UVI3vSP7s8m9CxRGiQO9iwBj2UPg9tlK8b21SM"}, "counts": {"unread": 2}, "devices": [{"app_id": "im.vector13021": false, "sound": "default"}}], "event_id": "$2dY-beFyngSVGsp0j8mlz_dFskheDc2gPV9kTRFhHaA", "id": "$2dY-beFyngSVGsp0j8mlz_dFskheDc2gsplay_name": "\u4f23", "type": "m.room.encrypted"}}

is any way to get message type?

**Comment by richvdh** [comment]
that's somewhat inherent in *end-to-end* encryption: nobody can decrypt the message except for the receiving client. It's up to the receiving client to decrypt the message and act accordingly.
