### ISSUE TITLE
Multiple Identity server for same home server

### ISSUE THREAD

**Issue by IbrahemSabbah** [matrix-org/synapse#9278]
I would like to ask if I can have 3 identity servers connected to the same home server.

My Case :
We have 3 clients using the same home server, but we need to make contact discoverable based on the client.
Can I make every client use the same home server with a different identity server?

Thanks.

**Comment by erikjohnston** [comment]
Clients can choose whatever identity server they want, Synapse shouldn't care at all what they're using.

Synapse supports responding to `.well-known/matrix/client` requests to change clients default identity server, and that *doesn't* support specifying multiple servers.

Let use know if that doesn't work.
