### ISSUE TITLE
New Shadow banning merge - #9209 - clarification on particulars

### ISSUE THREAD

**Issue by tallship** [matrix-org/synapse#9314]
I had some questions about the mechanics of the new shadow banning merge from issue #9209 

Actually, only one question, but that issue was closed because apparently, folks just can't coherently discuss the technical aspects of some particular features on the technical merits of those features alone. So here's my question.

When a server admin (because it's not available to room admins) affects this feature on say, a spammer or list bully that has proven that they're just not going away and continues to create new accounts to abuse a particular, or multiple rooms, does this retroactively ghost, or make invisible, or shadow (whatever terminology is being used) the abuser's previous posts as well, or does the shadow ban merely cover posts from that point forward?

Thanks :)

**Comment by callahad** [comment]
Hi :) Thank you for taking the time to ask this, and to understand the context (e.g., that this is an optional capability for Synapse server admins, but *not* room admins). We also only expect it to be used / useful in extreme circumstances against automated abuse, not against normal humans.

> does this retroactively ghost, or make invisible, or shadow (whatever terminology is being used) the abuser's previous posts as well

Shadowbanning is not retroactive. It only effects actions taken after the ban has been applied.

**Comment by RandomErrorMessage** [comment]
> We also only expect it to be used / useful in extreme circumstances against automated abuse, not against normal humans.

Under this context we are assuming the attacker is

1. Automated
2. Has access to many accounts
3. Has access to many IPs

Understanding this I don't see how shadow-banning would have any affect on them, since they are automated, with many accounts and many IPs they can simply do a heartbeat. The only argument for shadow banning in this context is that it would require adding a heartbeat feature, which is trivial.

I only see shadow-banning as being useful for abusing legitimate users.

**Comment by dontfwiththestream** [comment]
What possible use would it serve? if you have a persistent issue with spam etc anyone that persistent is also capable of having a sock puppet account. 

So, what use case does this feature have besides moderation?

 Also, deciding to censor the community on the merge post is a bad look. Especially when almost all the comments were negative

**Comment by callahad** [comment]
I believe we've sufficiently answered your questions, but to reiterate: we have found shadowbanning a useful tool of last resort in combating extreme and unambiguous cases of malicious behavior.

I understand that you do not find that answer satisfactory, and that you do not believe that we have a valid use case for this API, but we must respectfully disagree.

I'll ask you to please refrain from re-raising this question; as stated in the previous issue, we know how strongly some members of our community feel about this, and we agree with concerns over misuse of the API, but we do not intend to revert this commit.

> then the project needs to be forked

While I'd hate to see a fork occur over this, that is a fundamental freedom afforded to you by our open source license. If you believe that is the best course of action, we cannot stop you, nor will we attempt to.

Similarly, the Matrix protocol itself is developed in the open, and we actively welcome independent implementations: that diversity and competition *strengthens* the ecosystem, even if it may be to Synapse's detriment.

> Taking code from the community while ignoring their input on the project is not a healthy development practice

If you have code in the Synapse project that you would like for us to remove over this concern, I'm happy to facilitate that; I sincerely do not want you or anyone else to feel misled in your contributions. I was unable to find any commits searching ` git log --author dontfwiththestream`, but if you've contributed under a different alias please let me know.

I'm going to close this issue as the original poster's question has been answered, and there is limited value in rehashing concerns which have already been addressed and a decision reached.
