### ISSUE TITLE
Add 'raise X from e' in more places

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9318]
While working on #9279 i noticed that a lot of exceptions raised often don't re-use the exception when raising;
```py
# this
try:
  # yada
except Exception:
  raise CustomException()

# instead of this
try:
  # yada daba doo
except Exception as e:
  raise CustomException() from e
```
The latter adds more context and a longer and more detailed traceback to look at.

The request;
- Add more of these in a lot of places (either `raise X from e`, or putting them into twisted `Failure` objects that're thrown somewhere)
  - If it won't be added to the re-raised exception, put down a message why in the comment (sensitive information, etc.)

~~- (Maybe) Make it a coding policy/find a linter to enforce raised exception usage, unless explicitly suppressed.~~

**Comment by ShadowJonathan** [comment]
(im putting this here as an earmark for *maybe* myself to work on this after the PR for #9279 is finished and merged (or closed))

**Comment by erikjohnston** [comment]
This happens automatically most of the time, from https://docs.python.org/3/tutorial/errors.html#exception-chaining:

> Exception chaining happens automatically when an exception is raised inside an except or finally section.

Though there are a bunch of places where we have a `try/except` within an `except`, where we probably *do* want to be explicit about which exception we're chaining from (i.e. we usually want to ignore any nested exception)

**Comment by ShadowJonathan** [comment]
:thinking: Hmmm, I didn't know that.

Still, I think a thorough check should be done to see the messing about with `Failure`s I see sometimes, but i'll make a separate issue for that.

Note: I still think an explicit `from e` syntax is cleaner than letting it happen automatically, especially as sometimes the actual raising of exceptions isn't that idiomatic in this codebase, but i agree it shouldnt be a "hard and fast" rule then.

**Comment by ShadowJonathan** [comment]
Just checked the twisted API docs, it looks `Failure` also works with capturing current exceptions, so I won't open an issue for that, but I still personally think explicit > implicit.
