### ISSUE TITLE
Permission denied for appservice files on after upgrade to 1.26

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/synapse#9327]
Hi,

After an upgrade from `1.25.0-1~bpo10+1` to `1.26.0-1~bpo10+1`, synapse failed to start with:
2021-02-04 19:30:11,914 - synapse.config.appservice - 90 - ERROR - None- Failed to load appservice from '/home/matrix-irc/matrix-appservice-irc/my_registration_file.yaml'
2021-02-04 19:30:11,914 - synapse.config.appservice - 91 - ERROR - None- [Errno 13] Permission denied: '/home/matrix-irc/matrix-appservice-irc/my_registration_file.yaml'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/config/appservice.py", line 67, in load_appservices
    with open(config_file, "r") as f:
PermissionError: [Errno 13] Permission denied: '/home/matrix-irc/matrix-appservice-irc/my_registration_file.yaml'

The matrix-synapse user which is used to run synapse has access to that file, it wouldn't have worked with a previous version if it didn't. I've moved the file to /etc/matrix-synapse/ with the same permissions, and now it works.

Is this some security feature that was added?

**Comment by clokep** [comment]
@kroeckx Can you include information about the install method and platform?

**Comment by kroeckx** [comment]
I'm using Debian, it's the package from buster-backports

**Comment by erikjohnston** [comment]
> Is this some security feature that was added?

I don't believe so, nor can I think of any changes that would cause this. The only thing that I can think of is something, e.g. the IRC bridge, has made the `matrix-appservice-irc` directory non world readable (or world executable). Did you try reading the file as the synapse user (there are some non-obvious edge cases with linux permissions)?

**Comment by richvdh** [comment]
given that this is the package from downstream Debian, it might be worth checking if there have been any changes to that packaging.

Indeed I believe Debian's position is that issues should be reported on the Debian bug tracker in the first instance.

**Comment by andrewshadura** [comment]
The reason for this is that the package enforces sandboxing and restricts access outside of a limited set of directories. In particular `ProtectHome=yes`, makes directories `/home`, `/root`, and `/run/user` inaccessible and empty for Synapse. In your case, not only the files is not under `/etc/matrix-synapse`, but it is in fact in a home directory of another user.

With the current package version, you can either:
 * move the file into `/etc/matrix-synapse/conf.d`
 * set `ProtectHome=read-only` for the Synapse unit e.g. by creating `/etc/systemd/system/matrix-synapse.d/override.conf` with the following contents:
   ```
   [Service]
   ProtectHome=read-only
   ```
   (This can be done by running `systemctl edit matrix-synapse`.) Don’t forget to `systemctl daemon-reload` afterwards.

@richvdh:
1. Should the upstream build also introduce this to make sure we don’t grow a delta?
2. Should maybe `ProtectHome` default to `read-only`?
3. In any case, maybe this should be documented in `application_services.md`? At the moment, the example there suggests placing the file into home directory of an hypothetical *matrix* user, but maybe this should be clarified (e.g. *place the registration config under `/etc/matrix-synapse/conf.d`*)?

**Comment by auscompgeek** [comment]
Putting a registration config in `/etc/matrix-synapse/conf.d` would be a bad idea, as then Synapse would read that registration as part of the homeserver.yaml.

Keeping them _somewhere_ in `/etc/matrix-synapse` could make sense though.

**Comment by andrewshadura** [comment]
In practice though, Synapse seems to ignore unknown keys in those file, as I get no warnings or anything (my registration files are in conf.d).

**Comment by richvdh** [comment]
> 1\. Should the upstream build also introduce this to make sure we don’t grow a delta?

maybe? Honestly people seem to have enough difficulty getting Synapse going that I'm not entirely sure I want to throw extra obstacles like this in their way.

> 3\. In any case, maybe this should be documented in `application_services.md`? At the moment, the example there suggests placing the file into home directory of an hypothetical _matrix_ user, but maybe this should be clarified (e.g. _place the registration config under `/etc/matrix-synapse/conf.d`_)?

This is where we start to touch on the problem that there are different ways of installing Synapse, and hence different ways of installing config files. The [default installation](https://github.com/matrix-org/synapse/blob/develop/INSTALL.md#installing-from-source) recommends installing things into a home directory.

I certainly agree that the documentation is a bit lacking here, but I'm not sure how we can keep the docs clear whilst also covering various installation methods. Possibly we could talk about a "synapse configuration directory" in the abstract.

**Comment by andrewshadura** [comment]
Okay, I’ve landed this change relaxing the protection: https://salsa.debian.org/matrix-team/matrix-synapse/-/commit/7a9bf75b4112be25ef62acc7720b35d90914ad5f

**Comment by jo-so** [comment]
@kroeckx You should better use /srv ([3.17. /srv : Data for services provided by this system](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s17.html)) for services. /home is meant for human users.

**Comment by richvdh** [comment]
given the original problem here is fixed, I'm going to close this.
