### ISSUE TITLE
Jitsi homeserver path

### ISSUE THREAD

**Issue by dm-msk** [matrix-org/synapse#9328]
Hello. Is any solution to setup jitsi homeserver path for windows, android and ios element client from server side? For example throughout .well-known folder. By default use https://jitsi.riot.im/

**Comment by EdGeraghty** [comment]
https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi

**Comment by dm-msk** [comment]
> https://matrix.org/blog/2020/04/06/running-your-own-secure-communication-service-with-matrix-and-jitsi
> 
> > Finally, and this is the cool new bit: you can now point Riot to use the new Jitsi by going to its config.json at /var/www/riot.dangerousdemos.net/riot/config.json and changing the preferredDomain of the jitsi block from https://jitsi.riot.im to your own self-hosted https://jitsi.dangerousdemos.net.

It is a web client. I need solution for android app and windows desktop

**Comment by erikjohnston** [comment]
This is more of a spec or client issue than a Synapse issue. https://github.com/matrix-org/matrix-doc/issues/2488 is relevant here, and indeed it seems as if at least element web looks for `im.vector.riot.jitsi` in the `/.well-known/matrix/client` config. I'm not sure if this is supported in element iOS or element android, I'd suggest asking in their respective Matrix rooms (or searching the code/issues/PRs of their repos).
