### ISSUE TITLE
un-merge https://github.com/matrix-org/synapse/pull/9209

### ISSUE THREAD

**Issue by dontfwiththestream** [matrix-org/synapse#9332]
This is an antifeature that will ruin adoption. The only alternative is for the community to fork your code. The community clearly doesn't want this non feature rammed down our throats

**Comment by clokep** [comment]
Please see https://github.com/matrix-org/synapse/pull/9209#issuecomment-772776294.

**Comment by dontfwiththestream** [comment]
You censored the discussion there. I started an issue here because of that
