### ISSUE TITLE
Shadow banning is a violation of the matrix manifesto

### ISSUE THREAD

**Issue by dontfwiththestream** [matrix-org/synapse#9334]
"People should have full control over their own communication."

admins being able trick users into believing they are communicating when they are not is a direct violation of this principle. 
Either you should remove the code, or change your manifesto to read

"server admins should have full control over everyone else's communication"

**Comment by dontfwiththestream** [comment]
Also, it would be appreciated if you actually allowed the community to discuss the issue instead of closing any thread that brings it up.

People should have full control over their own communication, remember? That means not censoring people when they disagree with you en masse

**Comment by ShadowJonathan** [comment]
There's a difference between censoring and respectfully disagreeing, censoring is the actual deliberate suppression of any debate or acknowledgement of such existence, respectful disagreement (in this case between you and the project) is where either side has an opinion and just doesn't reach an agreement on it, and then moves on.

Not every disagreement has to reach a conclusion, I disagree with matrix on a lot of places in the case of focus areas, but i don't blow up about it and see it as a black-and-white right-and-wrong issue.

"People should have full control over their own communication." is not based on the premise of individualism, if you're on a server which is owned and maintained by someone else, then of course you're gonna fall under their moderation.

Don't like it? You can leave, *that is what the manifesto is talking about*, the ability to pack up, leave, and go somewhere else, while having the same fundamental treatment from the protocol. [MSC915](https://github.com/matrix-org/matrix-doc/issues/915) and [MSC2787](https://github.com/matrix-org/matrix-doc/pull/2787) are currently working on making this *even* more easier, by making users able to seamlessly interact for their own user with multiple servers.

[The shadow-ban admin API docs](https://github.com/matrix-org/synapse/blob/4a55d267eef1388690e6781b580910e341358f95/docs/admin_api/user_admin_api.rst#id36) says the user has to be *local*, this thus only affects anyone on the local server.

If you genuinely believe the manifesto means individual people without the regard of where they have what kind of access, in which way, then you're mistaken, and missing the bigger picture, as it is a statement against the current ecosystem of instant-messaging apps, *which nearly all of them only allow you to connect to one centralised service, often manned by a faceless moderation crew, acting in a detached manner to your interests.*

And if you genuinely believe that this is as bad as it gets, I implore you to set up your own server, keep an eye out on [conduit](https://conduit.rs/) for an easy deployment (as synapse can get quite heavy), maybe have a gander at dendrite, or one at construct, but trust me, this is genuinely not an issue of "omg they're taking away our rights!!!1!!", matrix.org is not The matrix server, you can make your own.

**Comment by callahad** [comment]
> it would be appreciated if you actually allowed the community to discuss the issue instead of closing any thread that brings it up.

This is a bug tracker, not an open forum.

You may continue to disagree, but you must do so elsewhere.

This is the third time you've raised this issue today, and the second time you've opened a new issue explicitly to circumvent a prior issue's closure. Continuing to do so is in violation of the [Matrix Code of Conduct](https://matrix.org/legal/code-of-conduct), and further disruption will be addressed as such.

**Comment by dontfwiththestream** [comment]
> There's a difference between censoring and respectfully disagreeing, censoring is the actual deliberate suppression of any debate or acknowledgement of such existence, respectful disagreement (in this case between you and the project) is where either side has an opinion and just doesn't reach an agreement on it, and then moves on.

So, what side is threatening consequences, shutting down discussions and threatening sanctions with your CoC? Its not respectfully disagreeing. My concerns have not been addressed, they have been ignored. Your actions are not in line with your stated goals.  Its very telling how concerned you are with ending all discussion to the contrary. Those with nothing to hide generally don't try to censor or stifle discussion

**Comment by dontfwiththestream** [comment]
also 
"This is the third time you've raised this issue today, and the second time you've opened a new issue explicitly to circumvent a prior issue's closure. Continuing to do so is in violation of the Matrix Code of Conduct, and further disruption will be addressed as such." 


free to discuss elsewhere, as long as nobody involved in this project can see it, which is why you are threatening me to continue to discuss it, and why you locked the original topic.

**Comment by neilalexander** [comment]
> My concerns have not been addressed, they have been ignored.

They have been addressed many times in many different places and you are choosing to ignore that. To reiterate:

* When you are on someone else's homeserver, you are subject to their rules, which is really no different to anywhere else on the internet
* You have the freedom to select a homeserver operated by someone you trust, or avoid servers that are operated by people you don't trust
* You aren't actually obliged to use someone else's homeserver or to trust anyone! If you don't want to follow someone else's rules, you have the freedom to host your own homeserver instead and be king of your own castle
* If you run your own homeserver, if you spam in someone else's room, you can still find yourself kicked/banned from those rooms, or your homeserver blocked altogether in that room (via server ACLs), by the room moderators
* Shadow-banning is not designed to be an everyday moderation tool, but is rather designed to help us stop spammers from responding to bans and taking evasive action so quickly, and it has been *effective* in the past
* Less spam is better for everyone — no one likes spam!

These tools have been developed in response to real active spammers on the Matrix network in the past. Yes, it's a terrible shame that we need tools like this, but here we are, and this is just another defensive strategy. Server administrators *have the choice* on whether or not to use it against their own users.

This is not a "violation of the Matrix manifesto". This is about giving homeserver operators choices too.

So please, stop opening more issues about it. It's been discussed more than enough in existing issues and PRs.

**Comment by blueForestIcarus** [comment]
Is there info on how the shadow-banning feature interacts with E2E encrypted rooms?

**Comment by jcalfee** [comment]
Shadow-banning may cause a loss of someones time.  Time has value and, in law, can be seen as property (property is a very broad term)..  It is provably intentional too, I can see a judge issuing a subpoena for the admin to answer if that feature was used.  Anything intentionally miss-leading that causes the loss of property it is is trespass and a common law tort.  I would not want to put my name on that feature.

I think he is right, you would have to make it clear up front that the user's agree that they can be shadow-banned without their knowledge.  This is a liability in my view if it is really as was described..
