### ISSUE TITLE
Please consider using UnifiedPush for notifications as a Push Provider

### ISSUE THREAD

**Issue by emorrp1** [matrix-org/synapse#9337]
I would like to be able to use android without google services. Currently notifications must use FCM unless each app developer hosts a notification gateway which drains battery. I suggest using [UnifiedPush](https://unifiedpush.org/), the community successor to [OpenPush](https://bubu1.eu/openpush/). Although UnifiedPush is (really) brand new, I'm not aware of any other app-independent implementation.

The only currently available UnifiedPush app is FluffyChat, but there is a request for [Element](https://github.com/vector-im/element-android/issues/2743) support and it would be neat if the user didn't have to host yet another personal server. I believe the technical approach would be for synapse to act as a Push Provider, since it's already an always-online service and then a "distributor" app could use the homeserver url as a backend.

**Comment by tulir** [comment]
This doesn't sound like a Synapse issue. If the existing [push gateway](https://matrix.org/docs/spec/push_gateway/latest) system doesn't work, there needs to be a spec proposal before Synapse can be changed.

**Comment by reivilibre** [comment]
This seems more like something for Sygnal or perhaps another push gateway implementation still.

**Comment by Sorunome** [comment]
The push gateway can already be anything, see https://github.com/matrix-org/matrix-doc/pull/2970 as proposal to remove the path requirement.

**Comment by emorrp1** [comment]
Ah yes, since Matrix already has a defined notifications endpoint, this isn't actually needed. Thanks @tulir
