### ISSUE TITLE
send/{eventType}/{txnId} works if txnId is empty

### ISSUE THREAD

**Issue by erdnaxeli** [matrix-org/synapse#9340]
### Description

The `/_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}` accepts an empty txnId even if the spec says it is required. Actually is works only once, it seems to use an empty string (`""`) as the txnId, then work as expected with an already used txnId if you try again.

### Steps to reproduce

```
HS_URL=
ROOM_ID=
ACCESS_TOKEN=
curl "https://$HS_URL/_matrix/client/r0/rooms/$ROOM_ID/send/m.room.message/" -X PUT H 'Content-Type: application/json' -H "Authorization: Bearer $ACCESS_TOKEN" --data-raw '{"msgtype":"m.text","body":"test"}'
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: cloud.cervoi.se

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.26.0

- **Install method**: apt
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian10
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment]
Thanks! Looks like we should add some additional validation to the transaction ID. Note that there's other endpoints that take a transaction ID, so we'd probably want to create some sort of helper to do this.

The only thing I could find in the spec about this is:

> The transaction ID for this event. Clients should generate an ID unique across requests with the same access token; it will be used by the server to ensure idempotency of requests.

Which doesn't really preclude an empty transaction ID, although it seems a bit silly to do that. Was there a tighter definition I'm not seeing?

**Comment by Shubhankaroad** [comment]
@clokep is this issue still open? Can i work on this?

**Comment by richvdh** [comment]
Given there's nothing in the spec that says an empty transaction id is forbidden, clients have a right to expect it should work, even if it's a pretty weird thing to want to do. Accordingly, I think this is working correctly at present.

(Related: https://github.com/matrix-org/matrix-doc/issues/666 which notes that there is no grammar specified for txn ids)

**Comment by erdnaxeli** [comment]
I am not happy with this :D
But I can understand why.
