### ISSUE TITLE
synapse first user registration error

### ISSUE THREAD

**Issue by bereska** [matrix-org/synapse#9343]
https://gist.github.com/bereska/4d59fb81fc1f8cafab5d5941458a3431

**Comment by erikjohnston** [comment]
That looks like something else is responding to the registration http request with something that isn't JSON? Do you have something other than synapse listening on 443?

**Comment by richvdh** [comment]
related: https://github.com/matrix-org/synapse/issues/3672

**Comment by bereska** [comment]
@erikjohnston @richvdh thank you, the issue has been resolved with http://127.0.0.1:8008, my bad, there was a different server name set on my vps

**Comment by erikjohnston** [comment]
Good to hear it works now! I've filed an issue for making the error message more friendly, so I'll close this issue :slightly_smiling_face:
