### ISSUE TITLE
Redis connections stop reconnecting if they time out while authenticating

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#9351]
If txredisapi gets an exception while waiting for the reply to `AUTH`, it will close the connection and disable reconnections (likely the idea is that if you get a wrong password it shouldn't keep trying). However, since any exception triggers this it can cause Synapse to permanently stop talking to redis even if the failure is transient (e.g. if the synapse process wedges at 100% CPU the `AUTH` request can time out).

This leads to failure modes where workers can silently stop receiving updates, or message sending stops working, etc. The only way to fix it is to manually restart the process. Not all cases will trigger alerts, so this is a fairly terrible thing to occur.

Probably the easiest way, but hacky, way of fixing this is making the `continueTrying` attribute on our factories ignore attempts to set it to `False`.

c.f. https://sentry.matrix.org/sentry/synapse-matrixorg/issues/198649/

**Comment by callahad** [comment]
We believe this has been resolved.
