### ISSUE TITLE
verfication hangs and is loading forever at login

### ISSUE THREAD

**Issue by localguru** [matrix-org/synapse#9352]
### Description

I upgraded from 1.1.25 to 1.26.0 (Ubuntu packages from matrix.org, no workes) . Since then I can't verfiy the login for my user anymore. After entering the passphrase in element browser client (1.7.20 firefox/chrome) or desktop client (1.7.20) "**Verify this login" is loading for ever** (tested on different plattforms). If I skip verification at login and do a "Connect this session to key backup" afterwards I can load the keys from the backup with my passphrase and can decrypt encrypted messages. So the passphrase must be right. The strange thing is, that this happens only with my userid, other userids seem not to be affected. I don't see any errors in synapse log, nor in nginx log. Any ideas?

**Comment by erikjohnston** [comment]
That is very strange. Can you try again with the JS console open? I'd be interested in a) there is any obvious errors in the console, though it can be a bit spammy, and b) if there are any stuck/repeated/etc requests.

**Comment by erikjohnston** [comment]
If you do `mxSendRageshake("debug stuck verification", true);` in the console after it hangs then that will send us a copy of your logs, though not the requests.

**Comment by richvdh** [comment]
this sounds like the same problem as https://github.com/matrix-org/synapse/issues/9264 to me.

**Comment by localguru** [comment]
@erikjohnston I sent the report. This is what I see in console:

![Bildschirmfoto_2021-02-09_14-22-33](https://user-images.githubusercontent.com/8544984/107370548-6afcb980-6ae3-11eb-9b65-ae11bb693a54.png)

@richvdh yes, I set `public_baseurl: https://matrix.domain.com/` in homeserver.yaml, because first I ran into CORS errors.

**Comment by erikjohnston** [comment]
I've talked to the element web gang and it sounds like it may be a client side issue. Could you open an issue with the details at https://github.com/vector-im/element-web, referencing this issue, please? I would but they would quite like details of versions and browsers and whatnot. Thanks!

**Comment by callahad** [comment]
This is a client-side issue; closing here.
