### ISSUE TITLE
Please tell me the required server specifications.

### ISSUE THREAD

**Issue by kenjinote** [matrix-org/synapse#9355]
We are trying to build an instance of synapse in Japan.
The number of simultaneous unique users is assumed to be 30,000.
Please tell me server specs should I prepare to build a Synapse server?
I would like to know more about CPU, memory, network bandwidth, etc.

Please let us know if you have any public information about the Synapse server in operation.
Please let us know if you have any other useful information.

**Comment by richvdh** [comment]
dup #6367
