### ISSUE TITLE
Document estimates of Synapse resource requirements by usecase

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#9363]
We get a lot of questions from people asking what the resource requirements of running Synapse is, with a variety of intended use cases. It would be nice to document a number of common use cases and a rough guess of the CPU/Memory/disk space/workers one would need to provide a comfortable user experience.

Such use cases may be:

* Friends and Family (small number of users, light federation)
* Small number of users, lots of federation in big rooms
* Small company (50 people), some federation
* etc.

It's important to note that the performance of a Synapse instance is less dependent on the number of users it has, and more on what those users actually do. Heavy operations include joining and participating in rooms with a large number of remote homeservers, rooms with lots of state events (i.e IRC rooms) and rooms with lots of general message traffic.

For now this should live in either the `docs/` directory, or the Wiki tab, in order to keep it on our radar as Synapse's performance continues to improve in various areas. Though one day we may want to move it to somewhere on matrix.org.

**Comment by richvdh** [comment]
I think this is a dup of #6367.

**Comment by richvdh** [comment]
... so am closing it accordingly.
