### ISSUE TITLE
media repo workers use an awful lot of memory

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9365]
A lot of it gets cleaned up when we eventually do a gen 2 GC, but 44G seems a bit insane for a process which is essentially a glorified web server:

![image](https://user-images.githubusercontent.com/1389908/107452202-bdb88e80-6b40-11eb-8677-4e10e6ae5501.png)

It would be good to find out what is using that memory, with a view to either not using it in the first place, or making it easier to free so that it gets removed in a gen 0 or gen 1 GC.

**Comment by richvdh** [comment]
(this tends to cause the box to go into swap, which is obviously bad)

**Comment by benbz** [comment]
FYI the media repo's memory profile seem to change after a deploy on 18th Jan:
![image](https://user-images.githubusercontent.com/1325121/107482942-4868b000-6b78-11eb-80c1-8b26d7678306.png)

**Comment by erikjohnston** [comment]
Previous issue: https://github.com/matrix-org/synapse/issues/8653, though the situation seems to have changed somewhat

**Comment by richvdh** [comment]
I don't think it's minor.

**Comment by michaelkaye** [comment]
So we have a tactical cronjob in place on matrix.org for this ; are we going to be able to look into this soon or should we make the automatic restarting more robust?

**Comment by clokep** [comment]
This might be a regression from #9108 or one of the earlier PRs updating that code.

**Comment by clokep** [comment]
From @richvdh doing a bit of research:

> it's mostly discovered by introspection of the heap; but `treq.client._BufferedResponse` is where the response gets buffered in memory

Looking a bit at this I think setting `unbuffered=True` on the call to `treq.request` "fixes" this. I'm not sure of the other ramifications of this though, so looking into that.

**Comment by clokep** [comment]
Hopefully the changes in #9421 will help out with this, but I guess it'll be a few days before we know.

**Comment by clokep** [comment]
After this change it seems that the huge spikes in memory allocation are gone:

![image](https://user-images.githubusercontent.com/517124/108731191-50224000-74fa-11eb-91ce-18d7f1df840b.png)

It also seems that nothing is being allocated into gen2 anymore:

![image](https://user-images.githubusercontent.com/517124/108732079-38978700-74fb-11eb-9e31-f2f78fa6cc32.png)

Due to the above I'm going to call this complete. But @richvdh or @benbz please let me know if I'm missing anything here!
