### ISSUE TITLE
Unignore and enforce check E203 ("Whitespace before colon")

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9368]
(`E203` checks "Whitespace before ':' ")

According to [`setup.cfg`](https://github.com/matrix-org/synapse/blob/fb0e14ee9a8cfc9962b2e583cf4837e655d9ca5d/setup.cfg#L17), `E203` is partly ignored because it's 'contrary to PEP8'. After a bit of research i found out that it is due to colons in slice indexes, which [*is* covered](https://www.python.org/dev/peps/pep-0008/#id27) under PEP8.

Going down the rabbithole a bit further, I found https://github.com/PyCQA/pycodestyle/issues/373 and https://github.com/PyCQA/pycodestyle/pull/914, so I suggest tracking those issues and removing `E203` once these are resolved, merged, and shipped.

**Comment by clokep** [comment]
This sounds more like we'd just let black handle where to put that whitespace and not really worry about flake8 here?

**Comment by erikjohnston** [comment]
Yup, it feels like `black` is covering this case and so we can safely turn off the flake8 checking of it. I don't think its worth digging into if that's the case
