### ISSUE TITLE
support for SSO via twitter

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9389]
Twitter use OAuth1, so this is a pain.

**Comment by clokep** [comment]
> Twitter use OAuth1, so this is a pain.

Note that Twitter does support OAuth 2.0 now:

* https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token
* https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code

We need some changes on our side to handle it (mostly RFC7836 support). I'll take a look at this.

**Comment by clokep** [comment]
This also has the same issues as #8511 where the userinfo endpoint puts everything under a `data` map.
