### ISSUE TITLE
we shouldn't ratelimit joins too aggressively

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#9409]
it's not unreasonable for a user to want to join a bunch of rooms - especially with rooms as spaces etc on the horizon

**Comment by anoadragon453** [comment]
Related: https://github.com/matrix-org/synapse/issues/8735

**Comment by ara4n** [comment]
Coincidentally:

<img width="924" alt="Screenshot 2021-02-16 at 11 55 57" src="https://user-images.githubusercontent.com/1294269/108059833-fa5b1d00-704d-11eb-8d86-1feb271a7bf2.png">
