### ISSUE TITLE
No public DNS for matrix federation servers

### ISSUE THREAD

**Issue by cavemandaveman** [matrix-org/synapse#9419]
### Description

**Symptom**:
When attempting to federate with matrix.org by trying to browse it's list of rooms in Element, I get a `401 Unauthorized` in the synapse logs, and `Failed to find any key to satisfy VerifyJsonRequest` in the Element UI. After troubleshooting with @anoadragon453 we determined the issue is firewall related.

**Cause**:
The current matrix URLs don't resolve to the correct federation server IPs. In my firewall, whitelisting the IPs of **`matrix.org`** and **`matrix-federation.matrix.org`** (currently resolving to `104.20.20.236` and `104.20.21.236`) still prevents matrix from federating with my homeserver. It turns out that **these are the reverse proxy IPs** and are not the same as those of the federation servers.

**Solution**:
Attach a public DNS name to `matrix.org`'s federation servers so that those with a strictly firewalled synapse server can properly whitelist them and successfully federate.

Or, route the matrix federation servers outbound traffic through the existing IPs tied to the DNS of `matrix.org` and `matrix-federation.matrix.org` so that whitelisting these will allow proper federation. 

### Version information

- **Version**: Synapse 1.27.0

- **Install method**: package manager

- **Platform**: Ubuntu 18.04

**Comment by tulir** [comment]
Whitelisting is only for private federations where all servers have the same whitelist. Either federate with everyone, or don't federate with anyone except your own servers, i.e. don't try to whitelist matrix.org.

**Comment by cavemandaveman** [comment]
People should be able to choose who they federate with though. Is it not a justified use case to allow a homeserver to federate with well known public servers, while denying federation with unknown/undesired servers?

**Comment by tulir** [comment]
No, not really. Matrix is currently full mesh, so you have to federate with all servers that are in the rooms you're in. If you don't, messages between you and all the other servers will be delayed until someone from the whitelisted server talks. There might be non-full-mesh routing in the future (e.g. as a part of the ongoing p2p work), but that doesn't really exist yet

**Comment by richvdh** [comment]
`federation_domain_whitelist` can be used to whitelist individual homeservers, though as tulir says this isn't particularly recommended.

Whitelisting by IP address really isn't a supported thing.
