### ISSUE TITLE
Active Directory based account can still login after AD Account has been disabled (LDAP based auth)

### ISSUE THREAD

**Issue by m1ndgames** [matrix-org/synapse#9435]
### Description

We run a matrix server which is connected to the companies AD server. An employee has left the company so we disabled his AD
Account. We would expect that he would now be unable to access the companies matrix server, but that's not the case. He is still online and we don't see a way to make sure people don't have access anymore after leaving the company.

### Steps to reproduce

- Configure synapse to allow AD access
- Create AD user
- Login with AD user Account
- Disable AD User on AD Server
- Login with AD user Account

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: our companies internal matrix server which i don't want to disclose.

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
{"server_version":"1.24.0","python_version":"3.7.3"}

matrix-synapse/unknown 0.34.0.1-0matrix2 all
matrix-synapse-ldap3/stable 0.1.3-4 all
matrix-synapse-py3/unknown 1.26.0+buster1 amd64 [upgradable from: 1.24.0+buster1]

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
Debian package manager
deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ buster main

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Debian 10 (Buster)

**Comment by clokep** [comment]
Please don't make duplicate issues. matrix-org/matrix-synapse-ldap3#113.
