### ISSUE TITLE
Add m.room.create to invite_room_state

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9448]
for spaces work, we want `m.room.create` to be included in the state that gets included with an invite (ie, the `invite_room_state`). In theory there is a config option for this, but @t3chguy tried setting it and it didn't work.

This work is to investigate and fix the config option not working.

**Comment by t3chguy** [comment]
It worked when inviting over federation but with some light testing and not much digging did not work for local users.

**Comment by richvdh** [comment]
fixed by #9710
