### ISSUE TITLE
Please expose more information about the room being created to the antispam room

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#9451]
I would like `user_may_create_room` to have visibility on:
- preset 
- invite list

Thanks!

**Comment by clokep** [comment]
@babolivier Is this essentially solved via the same suggestion as https://github.com/matrix-org/synapse/blob/develop/docs/upgrade.md#deprecation-of-the-user_may_create_room_with_invites-module-callback (calling the [get_room_state](https://github.com/matrix-org/synapse/blob/872f23b95fa980a61b0866c1475e84491991fa20/synapse/module_api/__init__.py#L869-L876) module API)?

**Comment by babolivier** [comment]
Preset would be a bit difficult to assert just by using `get_room_state`. However, it sounds like [`on_create_room`](https://matrix-org.github.io/synapse/latest/modules/third_party_rules_callbacks.html#on_create_room) fits the bill perfectly, so let's close this issue.
