### ISSUE TITLE
synapse 1.28rc1 breaks compat with SAML portal

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9452]
one of our customers has a saml portal which expects synapse to respond to saml callbacks on `/_matrix/saml2/authn_response`. Since #9434, it doesn't.

**Comment by callahad** [comment]
We can partially revert #9434 easily enough to provide a transition period, but we shouldn't maintain that indefinitely.

Let's arbitrarily say we'll re-apply the change with Synapse 1.32, which will be our first full release in April and coincide with Python 3.5 deprecation.
