### ISSUE TITLE
Warning: int_from_bytes is deprecated, use int.from_bytes instead

### ISSUE THREAD

**Issue by karthanistyr** [matrix-org/synapse#9454]
### Description

While using synapse to generate a config file, the following warning is thrown out:
```
/usr/lib/python3.8/site-packages/twisted/conch/ssh/common.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes
```

### Steps to reproduce

Build synapse v1.27.0 then
```
python3 -m synapse.app.homeserver \
		--server-name draak.fr \
		--config-path synapse.config.yaml \
		--generate-config
```
It looks like a sliding issue with a dependency chain that is not addressing the deprecation (synapse <= twisted <= cryptography)

My guess is that it's an upstream bug with twisted which depended on `cryptography >= 2.6` for ages (now 3.4.6), and the deprecation was introduced a few months ago in cryptography 3.4 (see: https://github.com/pyca/cryptography/commit/5528a3182fdd6ed1c44c126d451a87bcf39e79de), automatically picked up by twisted but not addressed.

### Version information

- **Homeserver**: draak.fr

- **Version**: v1.27.0

- **Install method**: `pip3 install matrix-synapse[all]==1.27.0`

- **Platform**: alpine linux 3.13

**Comment by karthanistyr** [comment]
I could not find an upstream bug for this though, but I hope we are aware of this here.

**Comment by tacerus** [comment]
Hi! I just encountered this issue, whereas I installed another Synapse instance just two days ago without any issues. Do you think this is a new bug, or does this machine I am working on today just happen to have a different set of dependencies installed?

**Comment by tacerus** [comment]
Installing the slightly newer pre-release versions of twisted and matrix-synapse did not help, and neither did an older version of twisted.

**Comment by karthanistyr** [comment]
To work around it, you need to pin an older version of cryptography, e.g. `cryptography<3.4`, that will satisfy twisted's dependency and not throw deprecation warnings. That means you should install `cryptography<3.4` into your environment *before* you install Synapse, and this version of cryptography should be picked up.

**Comment by karthanistyr** [comment]
Actually, the new (problematic) version of cryptography is much more recent than I thought and it must now be creeping into builds everywhere :thinking: : https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#34---2021-02-07

**Comment by tacerus** [comment]
@karthanistyr Thanks a lot! I had `pip uninstall`'d `matrix-synapse twisted cryptography bcrypt cftp`, then `pip install`'d `cryptography==3.3`, and afterwards `matrix-synapse[all]`.

**Comment by clokep** [comment]
Just to be clear -- this is just throwing a warning, it isn't causing any issues, correct?

This is an upstream issue (Synapse does not manually use `int_from_bytes` directly). I filed a ticket against Twisted: https://twistedmatrix.com/trac/ticket/10097

**Comment by karthanistyr** [comment]
I did not take the chance to deploy it as it is, and personally I did the workaround to use cryptography 3.3.2 instead. However, judging from the cryptography codebase, it looks like the call is simply deferred to int.from_bytes internally and that this is indeed, just a warning. Therefore, I don't expect adverse effects, I mostly wanted to make the synapse team aware of the situation.

Thank you for reporting upstream.

**Comment by tacerus** [comment]
It seems to prevent Synapse from starting up.

**Comment by clokep** [comment]
> It seems to prevent Synapse from starting up.

I think the issue you're seeing might be something else. There's probably additional errors in your logs somewhere.

**Comment by clokep** [comment]
I put up a PR to fix the deprecation warning in Twisted: twisted/twisted#1522.

**Comment by clokep** [comment]
This was merged so should be fixed upstream. Thanks for the report!

**Comment by karthanistyr** [comment]
Thank you for following up
