### ISSUE TITLE
How Synapse Uses GitHub Labels

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#9460]
Hello! Welcome to Synapse, the reference implementation of a [matrix.org](https://matrix.org/) homeserver.

## Label Taxonomy

We have several categories of [labels](https://github.com/matrix-org/synapse/labels), generally denoted by a shared prefix.

### Core Labels

We strive to completely cover all applicable issues with these core labels:

1. __Type__ — Every issue is assigned a type:

   - __[T-Defect](https://github.com/matrix-org/synapse/labels/T-Defect):__ Bugs, crashes, hangs, vulnerabilities, or other reported problems.
   - __[T-Enhancement](https://github.com/matrix-org/synapse/labels/T-Enhancement):__ New features, changes in functionality, performance boosts, user-facing improvements.
   - __[T-Task](https://github.com/matrix-org/synapse/labels/T-Task):__ Refactoring, enabling or disabling functionality, other engineering tasks.
   - __[T-Other](https://github.com/matrix-org/synapse/labels/T-Other):__ Questions, user support, anything else.

2. __Severity__ — All issues labeled `T-Defect` are also assigned a severity:

   * __[S-Critical](https://github.com/matrix-org/synapse/labels/S-Critical):__ Prevents work, causes data loss, affects many users, and/or has no workaround.
   * __[S-Major](https://github.com/matrix-org/synapse/labels/S-Major):__ Severely degrades major functionality or product features, with no satisfactory workaround.
   * __[S-Minor](https://github.com/matrix-org/synapse/labels/S-Minor):__ Impairs non-critical functionality, or suitable workarounds exist.
   * __[S-Tolerable](https://github.com/matrix-org/synapse/labels/S-Tolerable):__ Purely cosmetic or low / no impact to users.

3. __Priority__ — All issues which are not `T-Other` are assigned a priority:

   * __[P1](https://github.com/matrix-org/synapse/labels/P1):__ ASAP — As soon as possible.
   * __[P2](https://github.com/matrix-org/synapse/labels/P2):__ Soon — Within the next few releases.
   * __[P3](https://github.com/matrix-org/synapse/labels/P3):__ Approved — Not yet scheduled; will accept patches.
     ⋮
   * __[P5](https://github.com/matrix-org/synapse/labels/P5):__ Dubious — Will not schedule; would consider patches.

   _The omission of P4 represents the gap between things we agree on and things we're unsure about._

### Other Common Labels

We have a handful of other labels which are added on an as-needed basis, and not expected to be exhaustive:

* __Exceptions__ — Special flags for issues and pull requests:
  * __[X-Needs-Discussion](https://github.com/matrix-org/synapse/labels/X-Needs-Discussion):__ The Synapse platform team needs to discuss this before further action is taken.
  * __[X-Needs-Info](https://github.com/matrix-org/synapse/labels/X-Needs-Info):__ This issue is blocked pending further information from the reporter.
  * __[X-Regression](https://github.com/matrix-org/synapse/labels/X-Regression):__ Denotes things breaking which previously worked.
  * __[X-Release-Blocker](https://github.com/matrix-org/synapse/labels/X-Release-Blocker):__ Issues which must be resolved before making a release.
* __[Good First Issue](https://github.com/matrix-org/synapse/labels/Good%20First%20Issue)__ / __[Hacktoberfest](https://github.com/matrix-org/synapse/labels/Hacktoberfest)__ — Well-defined issues which are suitable for folks new to the Synapse codebase.
  * _Note:_ If you're looking to contribute, we would appreciate solutions to _any_ issue labeled __[P3](https://github.com/matrix-org/synapse/labels/P3)__!
* __[Security](https://github.com/matrix-org/synapse/labels/Security)__ — Issues which may present security concerns.
* __[Sponsored](https://github.com/matrix-org/synapse/labels/Sponsored)__ — Used internally by Element to denote issues with external funding.

### Ad Hoc Labels

We have reserved the `Z-` prefix for ad hoc labels.

Any member of the Synapse team is welcome to create labels beginning with `Z-` for any purpose, such as tracking personal areas of interest or providing a common way to label cross-repo initiatives. The prefix ensures avoids interference with the project's main labels.

### Issues

An issue is considered triaged when it has both a __Type__ and a __Severity__ (for defects).

Once triaged, issues are separately assigned a __Priority__.

The intent is for Type and Severity to be objective and static, while Priority is fluid and changes dynamically in response to the needs of the Matrix.org Foundation and Element's business context.

### Pull Requests

Pull requests are not routinely labeled.

Like issues, pull requests may have various __Exception__ labels applied where relevant.

**Comment by callahad** [comment]
(Closing and locking. Though the label process is still being developed, this particular issue intended as a reference; discussion can happen in `#synapse-dev:matrix.org`)

**Comment by richvdh** [comment]
I removed the `P-` labels from the above, which are no longer used.
