### ISSUE TITLE
Proposal: Add Area labels (A-) to GitHub

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#9461]
The labeling scheme described in #9460 is focused on very coarse-grained categorization of Synapse bugs, primarily for use within Synapse itself.

Increasingly often, work in Synapse is part of larger, cross-repo efforts. For example, improving social login required coordination of work by Element's "User Delight" project team across many repos including Synapse, the Matrix Spec, and all Element clients.

While an ad hoc label (say, __Z-Delight-Social__ or __Z-Social-Login__) could tie together issues for that initiative writ large, @jryans has convincingly suggested that we could all also benefit from Area labels such as __A-Docs__ or __A-SSO__ to further narrow down related issues.

Should we adopt Area labels, and if so, which areas would make sense for Synapse?

cc: @jryans + @richvdh + @nadonomy for input.

**Comment by callahad** [comment]
I can immediately imagine uses for:

- A-Docs
- A-Packaging (Covering everything from Debs to Docker to ARM builds)
- A-Tests
- A-Auth (or A-SSO, A-Social-Login, etc.)

My main desire is to limit the number of Area labels so that they represent areas of work that are sufficiently broad, clearly defined, and generally non-overlapping as to be useful and consistent in their application.

...but what are those, for Synapse?

**Comment by ShadowJonathan** [comment]
I could suggest labels like;
 - A-Internal (though a bit broad imo)
 - A-Consistency (mostly relating to typing, code cleanup, and other misc pythonic enhancements)
 - A-Pythonic (basically above, but with a different name)

**Comment by ShadowJonathan** [comment]
Actually, i suggest `A-Process`, after [some discussion](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$lFk28OAztpMkM_Yy22k2ntKdjueYZuq7NNRqR2-dyxM?via=matrix.org&via=vector.modular.im&via=envs.net) in `#synapse-dev:matrix.org`, i think that's a good tag for any "meta" issues or PRs that might come up.

**Comment by richvdh** [comment]
I think we've done this, so the issue can be closed.
