### ISSUE TITLE
MAU limit alerts are not removed when the host is no longer over the limit

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#9468]
There is a whole conversation about how you do this, but as it stands if a host goes over it's MAU limit then the client is sent an alert. However if the host is reconfigured with a higher limit, the clients are not informed and will continue to show a MAU limit banner. I think it would be wise to check the state of an alert in the server notice room on startup, and if MAU < limit, rescind it.

**Comment by Half-Shot** [comment]
So this is implemented in https://github.com/matrix-org/synapse/blob/0a00b7ff14890987f09112a2ae696c61001e6cf1/synapse/server_notices/resource_limits_server_notices.py#L57-L120, so maybe this is an Element bug.

**Comment by clokep** [comment]
Let us know if you think this ends up being a bug in Synapse!

**Comment by Half-Shot** [comment]
This is a bug in Element, you are off the hook! (Ref: https://github.com/matrix-org/matrix-react-sdk/pull/5678)
