### ISSUE TITLE
[meta] Rate-limiting room joins and invites

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9485]
With the advent of spaces, it looks like we probably need to rethink how we do room joins/invites. Doing this would probably be fairly tricky, as it'd be hard for a server to discern between legitimate quick-joins (e.g. Spaces' `auto_join` feature), quickly clearing a list of invites with "accept", and spam accounts joining a bunch of rooms to start spamming in them.

Below issues are overlapping in interest, but related to this bigger issue.

- #8735
- #8736
- #9409
- #8309
- #9487

cc @ara4n, @erikjohnston

**Comment by ShadowJonathan** [comment]
"Invalidating" a `/join` request if it's based on an invite would be easy enough, but I don't know how to properly do this with spaces. Maybe make client logic for joining rooms smarter? As in; Make the client acknowledge a backoff and retry at that point. Though that sorta transcends this repo.

**Comment by richvdh** [comment]
also related #8309

**Comment by callahad** [comment]
Spaces is likely to bring this forward in prominence... letting this issue sit as is until the team working on Spaces starts hitting it enough to provide concrete motivations and constraints for a solution

**Comment by clokep** [comment]
I'm not sure of the value of keeping this open, it seems to be a grab-bag of vaguely related issues. I'm going to close this.
