### ISSUE TITLE
Default space creation task always gets throttled

### ISSUE THREAD

**Issue by BillCarsonFr** [matrix-org/synapse#9487]
**Description:**

When creating a simple public space, the client will create 4 rooms in total (the space room + 3 default rooms)

Actual:
The 3rd room creation call will error with 
`{"errcode":"M_LIMIT_EXCEEDED","error":"Too Many Requests","retry_after_ms":8060}`

=> As a consequence the creation experience is very slow

**Comment by ShadowJonathan** [comment]
We got a meta-issue for this (just) now, thanks for notifying tho :+1:

**Comment by jaywink** [comment]
This also happens when adding rooms to an existing space - on my homeserver 10 is the most I can add at a time (v1.31.0) and the rest silently fail as the rate limiter kicks in. It doesn't look like Element retries the rate limited additions (v1.7.24.1).

**Comment by clokep** [comment]
As mentioned above, I believe this should be better in Synapse v1.31.0 where the burst rate limits were increased from 3 -> 10 in #9674. So I think from my POV this is done (as creating 4 rooms at once should be fine)?

**Comment by clokep** [comment]
I'm going to close this since the default should work fine now.
