### ISSUE TITLE
Include "synapse-s3-storage-provider" in the .deb package

### ISSUE THREAD

**Issue by wioxjk** [matrix-org/synapse#9494]
Hi,

I have tried getting S3-storage to work on my synapse-server that I installed with the .deb package. 
But the lack of documentation regarding how I enable this is frustrating:

`ModuleNotFoundError: No module named 's3_storage_provider'`

I would love having this module included in the .deb package.

**Comment by clokep** [comment]
Thanks for the feedback! This seems to be a duplicate of #6002.
