### ISSUE TITLE
mypy failing on Twisted 21.2.0

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#9513]
The mypy check is failing on 21.2.0, which adds significantly more type hints internal to Twisted.

There's currently 196 errors, but hopefully it isn't too bad to clean them up!

**Comment by clokep** [comment]
Filed Shoobx/mypy-zope#34 about an issue I'm having...

**Comment by clokep** [comment]
> Filed [Shoobx/mypy-zope#34](https://github.com/Shoobx/mypy-zope/issues/34) about an issue I'm having...

It seems that mypy-zope has an issue with using the mypy cache, not sure if there will be a solution, but for now runnig `rm -r .mypy_cache` removes some spurious errors.

**Comment by clokep** [comment]
This is all "fixed" now, minus the issue with the mypy cache. I'm not sure what to do about this. We can:

* Leave it and ignore the issue.
* Add a `rm .mypy_cache` to the `lint.sh` script.

I don't have other ideas. 😄

**Comment by callahad** [comment]
Decision:

1. Apply the `rm` hack to `lint.sh` as a stopgap
2. (Briefly) look into upstream code to scope how difficult it would be to supply a patch
