### ISSUE TITLE
Feature to disable push notifications entirely

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#9524]
I'm looking at the Gitter homeserver, and we could probably afford to make some savings by not bothering to calculate push actions:

`2021-03-02 00:01:10,260 - synapse.storage.databases.main.event_push_actions - 785 - INFO - rotate_notifs-233- Rotating notifications, handling 8343 rows`

I imagine there are situations where push isn't important, so some sort of config flag (maybe push.enabled?) that just exits early when calculating push actions?

**Comment by clokep** [comment]
Maybe setting `start_pushers: False` will help with this (see https://github.com/matrix-org/synapse/blob/master/docs/workers.md#synapseapppusher)? I'm not sure this is really supported to just disable push though.

**Comment by Half-Shot** [comment]
I think that will stop sending push notifs, but I think we still queue them in the DB? This is mostly about trying to save work involving push.
