### ISSUE TITLE
Incorrect pagination behaviour at start of timeline

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#9534]
### Description

When doing an initial sync for `@bruno1e2ee:matrix.org`, a user with at the time only 2 rooms with no other members and less than 10 events. Both rooms have a `prev_batch` in their room response even though there is nothing to paginate back to, but ok.
Now, when I do /messages?dir=b with this token, it returns me the same messages as in the initial sync (but reversed). So it basically did a forward fill, sort off.

Attached is a HAR of the initial sync and back-pagination.
[pagination-edge.zip](https://github.com/matrix-org/synapse/files/6072100/pagination-edge.zip)

This partially caused https://github.com/vector-im/hydrogen-web/issues/160 and has been fixed by special-casing these circumstances.

**Comment by richvdh** [comment]
dup #1509
