### ISSUE TITLE
Synapse accepts "user" instead of "username" in application service /register 

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/synapse#9547]
### Description

When an AS registers a user in Synapse, it seems happy to accept `"user"` instead of the specced `"username"` in the request body.

This is related to matrix-org/sytest#1017.

### Steps to reproduce

Up until matrix-org/sytest@ab7b8f00d0781bfef240b6b6b420291e7f13aa4d, Sytest was testing this way and the tests passed.

### Version information

- **Version**: Seemingly all versions

**Comment by anoadragon453** [comment]
This may be related to old client behaviour, in which case changing it would be **hard**.

**Comment by richvdh** [comment]
possibly, but it would have to be very old clients, and tbh we should be doing a better job at deprecating and sunsetting these things.

**Comment by clokep** [comment]
I'm assuming that this accepts both since sytest still passes? So this is really a matter of deprecating the old `user` field?

**Comment by anoadragon453** [comment]
@clokep Yep. We need to do a similar thing to https://github.com/matrix-org/synapse/pull/9559 / https://github.com/matrix-org/synapse/pull/9548 here.

**Comment by clokep** [comment]
Note that #927 seems to have added a fallback to "username". I think this is really Synapse accepts "user" in addition to "username" FWIW.

**Comment by clokep** [comment]
@Half-Shot / @tulir Any idea if we can deprecate and remove this (similar to the legacy AS paths)?

**Comment by clokep** [comment]
This is deprecated and can be removed in v1.88.0. Since this was never specced I think we can just remove it.
