### ISSUE TITLE
Delete device 

### ISSUE THREAD

**Issue by dm-msk** [matrix-org/synapse#9551]
Hello. I need a mechanism to deny mobile client for some user. I tried to delete unexpected Android device by script

Fist I get device list 
sqlite3 /mnt/database/homeserver.db 'select user_id,device_id,ip,user_agent,last_seen from user_ips;' | grep 'Android'

Then I take Device ID and follow instruction
https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-delete-devices

curl -X DELETE 'http://localhost:8008/_matrix/client/r0/devices/$DEVICE?access_token='$TOKEN''
where $DEVICE is variable from user_ips tables and $TOKEN from 

curl -XPOST  -d '{"type":"m.login.password", "user":"@username:DOMAIN", "password":"password"}' "http://localhost:8008/_matrix/client/r0/login

AND NOTHING HAPPENED
{"session":"OTYGvoepxcKsSVqlLsBHxgEG","flows":[{"stages":["m.login.password"]}],"params":{}}

**Comment by dm-msk** [comment]
https://github.com/matrix-org/synapse/issues/7330

**Comment by dm-msk** [comment]
HTTP/1.1 401 Unauthorized
< Transfer-Encoding: chunked
< Server: Synapse/1.26.0
< Date: Fri, 05 Mar 2021 12:02:52 GMT
< Content-Type: application/json
< Cache-Control: no-cache, no-store, must-revalidate
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, Date
<

Connection #0 to host localhost left intact
{"session":"aeZTcowjWyGbgukGRxdJNzHm","flows":[{"stages":["m.login.password"]}],"params":{}}

**Comment by bahur142** [comment]
try to update your account to administrator level:
`update users set admin = 1 where name = '@your_name:server.net'`
and then try to delete the device

**Comment by anoadragon453** [comment]
[`POST /_matrix/client/r0/delete_devices`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-delete-devices) uses the [User-Interactive Authentication API](https://matrix.org/docs/spec/client_server/r0.6.1#user-interactive-authentication-api) to delete a device. So you need to go through the steps of authenticating yourself after you'd got a 401 back from the server.

As @bahur142 says you can also use the [Delete Device Admin API](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#delete-multiple-devices) with the access token of an administrator user to delete devices as well if you'd like to avoid the User-Interactive Authentication API.

Please keep support questions to [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org).
