### ISSUE TITLE
How to delete local media for a specific user ?

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/synapse#9565]
How to delete local media for a specific user ?

**Comment by anoadragon453** [comment]
Currently you can only use the admin API to *quarantine* media by uploader user ID: https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/media_admin_api.md#quarantining-all-media-of-a-user. This prevents your server from serving the media to anyone anymore, and is typically used to combat abusive material (while allowing you to inspect it before blasting it away).

There isn't currently an equivalent endpoint for deleting media by user ID, however you can get all IDs of media uploaded by a given user with the following database query:

```sql
SELECT * FROM local_media_repository WHERE user_id = '@alice:example.com';
```

And then use the [Delete Local Media](https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/media_admin_api.md#delete-local-media) Admin API to remove each one.

**Comment by clokep** [comment]
> however you can get all IDs of media uploaded by a given user with the following database query:
> 
> ```sql
> SELECT * FROM local_media_repository WHERE user_id = '@alice:example.com';
> ```

There's an admin API for this: https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#list-media-of-a-user
