### ISSUE TITLE
Some dependencies are missing

### ISSUE THREAD

**Issue by suliuzh** [matrix-org/synapse#9570]
**Description:**

Hi
I am wondering if some dependencies should be listed in requirements,txt even as extra dependencies in sub-folders?
they are

- pydot
- srvlookup
- BeautifulSoup
- grequests
- gevent
- josepy

As an example, srvlookupis used in scripts-dev/federation_client.py. Other dependencies are also used in different files. To make dependency management clear, should these dependencies be listed explicitly?
![image](https://user-images.githubusercontent.com/27858725/110487433-8aa9f080-8128-11eb-9bfa-17645bc26b2c.png)

**Comment by suliuzh** [comment]
It seems that more dependencies are not documented properly.

- sentry_sdk
- constantly
- typing_extensions

- authlib
- txredisapi
- frozendict
- Jinja2
- sortedcontainers
- bcrypt
- cryptography
- pysaml2
- bleach
- phonenumbers

**Comment by squahtx** [comment]
We did a similar fix for Sygnal in the past: https://github.com/matrix-org/sygnal/issues/289

**Comment by clokep** [comment]
> It seems that more dependencies are not documented properly.
> 
>     * sentry_sdk
> 
>     * constantly
> 
>     * typing_extensions
> 
>     * authlib
> 
>     * txredisapi
> 
>     * frozendict
> 
>     * Jinja2
> 
>     * sortedcontainers
> 
>     * bcrypt
> 
>     * cryptography
> 
>     * pysaml2
> 
>     * bleach
> 
>     * phonenumbers

I'm pretty sure most of these are listed in `synapse/python_dependencies.py`.

**Comment by squahtx** [comment]
> I'm pretty sure most of these are listed in `synapse/python_dependencies.py`.

Only constantly, typing_extensions and Jinja2 appear to be missing. I think we should split these out into a separate issue and leave this one for missing contrib dependencies.

**Comment by clokep** [comment]
> > I'm pretty sure most of these are listed in `synapse/python_dependencies.py`.
>
> Only constantly, typing_extensions and Jinja2 appear to be missing. I think we should split these out into a separate issue and leave this one for missing contrib dependencies.

I see `Jinja2` in there.

`typing_extensions` gets installed from mypy. (And would be added to `setup.py`.)
`constantly` gets installed from Twisted.

**Comment by squahtx** [comment]
> we shouldn't need to declare every single one of transitive dependencies

To clarify, my view is that since we directly import typing_extensions and constantly in synapse code, we should list them as dependencies in python_dependencies.py, even if they happen to be transitive dependencies, because there's no guarantee that future versions of twisted or mypy will pull them in. I think this is the bit we disagree on?
Once dependencies are locked it becomes far less important of course.

Transitive dependencies that we do not directly import should not be listed in python_dependencies.py. This part isn't controversial I think.

**Comment by clokep** [comment]
> To clarify, my view is that since we directly import typing_extensions and constantly in synapse code, we should list them as dependencies

TIL that we use `constantly` directly. It looks like we should just replace that with an enum TBH.

I suppose for `typing_extensions` since we do import it directly it might make sense, but we should be careful to not conflict with what `mypy` provides.

**Comment by richvdh** [comment]
I'm going to go ahead and close this, since it seems to be mostly about (a) not listing dependencies for things in `contrib`, which is somewhat expected, or (b) not listing things which we absolutely do.
