### ISSUE TITLE
Let the Spam Checker know whether the registration came from an SSO provider

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#9572]
Right now we call `spam_checker.check_registration_for_spam` with both native, local, Synapse registrations _and_ with the "first login" of SSO users.

If a homeserver is running with both native and SSO-provided logins, it'd be good to expose to the spam checker the nature of the registration - perhaps by passing in `auth_provider_id` to the `check_registration_for_spam` call?

**Comment by anoadragon453** [comment]
@richvdh how would you feel about passing `auth_provider_id` to SpamChecker modules? Or should we try to pass some sort of opaque constant instead (AS vs. SSO vs. Native)?

**Comment by richvdh** [comment]
seems reasonable enough to me
