### ISSUE TITLE
oidc `allow_existing_users` fails for users created before 1.27

### ISSUE THREAD

**Issue by Rafaeltheraven** [matrix-org/synapse#9584]
### Description

All the users on my homeserver are using our self-hosted Keycloak instance with OIDC. These users were initially created manually in synapse and then ported over to `user_external_ids` using the method described in #7633. As a result, their `auth_provider` field was set to `oidc`.

Ever since 1.27, the ability for multiple oidc providers was added and with it the `auth_provider` value has changed for most instances (in my case it is now `oidc-keycloak`). The values in the database, however, haven't changed, which leads to the problem where users will try to login over oidc and get assigned a new user instead of the old user they were expecting.

This is (relatively) easily solved by going into the database and running `UPDATE user_external_ids SET auth_provider = 'oidc-keycloak'`, but this isn't mentioned anywhere in the upgrade notes (and it would probably be nicer if this happened automatically somehow)

### Steps to reproduce

- Have a homeserver with oidc users prior to 1.27
- Update to 1.27 and modify config accordingly
- Try logging in

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: private

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.28.0 (though logic dictates the issue started in 1.27.0)

- **Install method**: apt
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian 10
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by Rafaeltheraven** [comment]
You are correct, it is, might be good to mention this in the upgrade steps (though it might be too late now)

**Comment by rtest12** [comment]
I have the same problem as #9514
I migrated to a new server, no upgrade, just latest version to latest.
Users1-2-3 began to be created
I changed the old value idp_id from 
```
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
   - idp_id: keycloak
     idp_name: "keycloak"
```
For new
```
matrix_synapse_configuration_extension_yaml: |
  oidc_providers:
   - idp_id: oidc
     idp_name: "keycloak"
```

I restarted the entire installation, but nothing has changed, still when I log in I get "User1:example.com" 
I don't understand what else I missed?
