### ISSUE TITLE
Remove the `presence` database table

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#9592]
The "presence" database table does not look to be used at all currently, even with presence enabled. It looks like its functionality has been replaced by `BasePresenceHandler.user_to_presence_state`.

We should probably delete it via a DB migration.

**Comment by ritikBhandari** [comment]
Hi,
Since I'm contributing for the first time in matrix-org, it seems to be a fairly understandable issue. Can I take up this issue if nobody is working on it?

**Comment by anoadragon453** [comment]
@ritikBhandari Nobody is working on it as far as I'm aware. Go for it :)
