### ISSUE TITLE
Synapse broken with LibreSSL

### ISSUE THREAD

**Issue by davehayes** [matrix-org/synapse#9599]
### Description

I upgraded from 1.24 to 1.27, and then to 1.28. After the upgrade from 1.24, synapse federation broke for me and has not since recovered.

I believe but am not certain that the relevant log lines are:

```
2021-03-10 20:06:05,486 - synapse.federation.sender.per_destination_queue - 417 - WARNING - federation_transaction_transmission_loop-14- TX [matrix.org] Failed to send transaction: Failed to send request: RequestTransmissionFailed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ST_CONNECT', 'tlsv1 alert unknown ca'), ('SSL routines', '(UNKNOWN)SSL_internal', 'certificate verify failed')]>]
2021-03-10 20:06:05,487 - synapse.logging.context - 70 - WARNING - federation_transaction_transmission_loop-14- Re-starting finished log context federation_transaction_transmission_loop-14

2021-03-11 13:46:56,989 - synapse.crypto.keyring - 623 - WARNING - PUT-2532- Key lookup failed from 'matrix.org': Not retrying server matrix.org.
```

The first log line there is the first log I found with `[matrix.org]` in it after the upgrade. There are more than hundreds of that last log line. 

### Steps to reproduce

- Upgrade server from 1.24 to 1.27
- Restart the server

### Version information

- **Homeserver**:

matrix.jetcafe.org

- **Install method**:

From FreeBSD ports tree through poudriere. 

- **Platform**:

FreeBSD 12.2
Ports tree 2021Q1

**Comment by davehayes** [comment]
I have since discovered there is some interaction between LibreSSL 3.2.[34] and Synapse that causes this issue. I built Synapse against the base openssl and everything started working. I won't close this because I believe that interaction needs to be fixed, but any dev is welcome to close this if this issue is in twisted or py-openssl.

**Comment by ShadowJonathan** [comment]
(Maybe rename issue name to "Synapse doesn't properly work with LibreSSL"?)

**Comment by clokep** [comment]
Note that we think this is an issue in py-openssl, Twisted, and/or LibreSSL. I'm going to leave this open, but I don't think it is an issue in Synapse. (Synapse does use some bits of that directly though so it could be...)

**Comment by davehayes** [comment]
While I had a horrible time dealing with this, I honestly don't want to jump to any conclusions. That's why I left the title at "unable to federate", which also describes the symptoms so people googling can find this. 

I and others are in the process of investigating this at a deeper level. I will provide updates here.

**Comment by davehayes** [comment]
I'm curious. [This link](https://pypi.org/project/pyOpenSSL/) suggests that pyca/cryptography be used over py-openssl. I am so not a python dev, but was this idea considered at all?

**Comment by clokep** [comment]
> I'm curious. [This link](https://pypi.org/project/pyOpenSSL/) suggests that pyca/cryptography be used over py-openssl. I am so not a python dev, but was this idea considered at all? (I'm sure it was, but this question can likely lead to more information.)

They're actually both used in a few places. Some of the Twisted APIs expect OpenSSL primitives, so not really possible to just switch I think?

**Comment by davehayes** [comment]
So if you note that issue I mentioned above and look into my test results, there is this:

```
>       raise exception_type(errors)
E       OpenSSL.SSL.Error: [('SSL routines', 'ST_CONNECT', 'tlsv1 alert unknown ca'), ('SSL routines', '(UNKNOWN)SSL_internal', 'certificate verify failed')]
```

**Comment by davehayes** [comment]
Ok. Closing this as the issue was a missing certificate bundle from a package that claimed to install it. For future googling reference, `${PREFIX}/etc/ssl/cert.pem` must be present from the ca_root_nss package. 

The test failures I noted above are still worrisome, but perhaps a different issue.
