### ISSUE TITLE
Enabling SSO w/ username picker and existing accounts "conversion"

### ISSUE THREAD

**Issue by olmari** [matrix-org/synapse#9607]
Background: currently SSO and local accounts can both even coexist peacefully, Synapse even has username picker for SSO side when new user SSO "in" and has no synapse account yet. Then separately SSO flow allows to use existing accounts, but in that scheme SSO has to tell the localpart, which our SSO does'nt have any clue about. Those two functions currently doesn't work together; if "first time SSO user" gives existing localpart in Synapse username picker it says it is already taken and no further can be done about that in this stage.

Proposal: By enabling both (with possibly another setting allowing the proposal function) when "first time SSO login" user pics existing local username, Synapse would ask the local PW and after successful local auth bake it into SSO-login ever after. This would enable easy migration path from old local login to SSO-login, without needing to admins do DB knifing, which is always at least scary.

**Comment by richvdh** [comment]
I think this is a dup of #9441.
