### ISSUE TITLE
Media_cache broke after federation resync

### ISSUE THREAD

**Issue by davehayes** [matrix-org/synapse#9614]
### Description

So as some of you know, my homeserver was unable to federate because of some SSL issue. After this occurred  and after the recovery, my media cache is completely broken. I consistently see these in the logs:

```
2021-03-14 12:39:46,894 - synapse.http.server - 94 - ERROR - GET-642836- Failed handle request via 'ThumbnailResource': <XForwardedForRequest at 0x8288658d0 method='GET' uri='/_matrix/media/r0/thumbnail/hacklab.fi/tZgWieQreLCOTSubZtidKenz?width=16&height=16&method=crop' clientproto='HTTP/1.1' site='8448'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 254, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 282, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 85, in _async_render_GET
    request, server_name, media_id, width, height, method, m_type
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 260, in _respond_remote_thumbnail
    media_info = await self.media_repo.get_remote_media_info(server_name, media_id)
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 282, in get_remote_media_info
    server_name, media_id
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 351, in _get_remote_media_impl
    server_name, media_id, file_id, media_info["media_type"]
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 675, in _generate_thumbnails
    FileInfo(server_name, file_id, url_cache=url_cache)
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/media_storage.py", line 247, in ensure_media_is_in_local_cache
    raise Exception("file could not be found")
Exception: file could not be found
```
I took what I reasoned as proper steps to save my old cache (rsync) but the new hashes (i.e. 'tZgWieQreLCOTSubZtidKenz') are completely unlike the old ones. 

### Steps to reproduce

I am not sure how reproducible the following steps are, but here's what I did, in general terms. If you need intense specifics, database queries, etc. ... feel free to ask me. 

- First somehow stop an existing federated server from validating SSL certificates.
- Shutdown this server
- Create a new server in a FreeBSD jail, but hook it to the same postgres database and the same reverse proxy.
- Before you start the server, rsync the media cache from the old area to the new area (I used `rsync -av` to keep it simple)
- Start up the new server.

### Version information

- **Homeserver**: matrix.jetcafe.org

- **Version**: 1.28

- **Install method**:  From FreeBSD ports tree 2021Q1 via poudriere

- **Platform**: FreeBSD 12, using postgres as backend, and nginx as reverse proxy.

**Comment by davehayes** [comment]
More data on this. My media cache "unbroke" (as evidenced from the reappearance of thumbails, the above error message still occurs tho) when I moved synapse back out of the jail to where it was before.

**Comment by clokep** [comment]
Is Synapse unable to read from that path when in the jail? (Is it a file permission issue?)

**Comment by davehayes** [comment]
I checked file permissions and paths.  They are all correct. 

What I was noticing is that the "hash" is different and you folks implemented the cache by taking the first two characters of the hash and making that into a directory. So the first two characters are different in the log messages for every site that had an error.

**Comment by erikjohnston** [comment]
> I took what I reasoned as proper steps to save my old cache (rsync) but the new hashes (i.e. 'tZgWieQreLCOTSubZtidKenz') are completely unlike the old ones.

FWIW those aren't hashes, they're just random IDs we generate when we fetch the remote media, we then keep a mapping in the database in `remote_media_cache` between `(origin, media_id) -> filesystem_id` (for local media the `media_id` and `filesystem_id` are effectively the same, we generate a new filesystem ID for remote media as we don't know if the remote media ID is safe to use as a path). We also have a table `remote_media_cache_thumbnails` for recording what thumbnails we have.

For the remote media in question (`hacklab.fi, tZgWieQreLCOTSubZtidKenz`) can you look at the entries in both `remote_media_cache` and `remote_media_cache_thumbnails` and fetching the filesystem IDs (they should be the same). Then use the filesystem ID (splitting it into the three parts) and checking for files/folders in `$media_store/remote_content/hacklab.fi/` and `$media_store/remote_thumbnail/hacklab.fi/`. If those paths exist can you check that all the entries listed in `remote_media_cache_thumbnails` also appear in the thumbnails folder?

It's also possible there was an error generating the thumbnails for that file it was first downloaded. After getting the above data you could try deleting/moving the content away and refetching it, checking for any errors/warnings in the logs about failing to generate thumbnails.

**Comment by richvdh** [comment]
closing this due to lack of info.
