### ISSUE TITLE
Missing event down /sync for some devices, but not others

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#9624]
@AmandineLP found that an event (`$8W1KwdbJnRJkpkt_iIWKJt5Sr-Q620_fcBCc6BjsGfg`) failed to come down sync on her Element Web, as well as another user's Element Web. The event *did* come down sync on @AmandineLP's Hydrogen and iOS clients however.

From my initial investigation, the event exists in `events` and `events_json`, is not rejected and is not an outlier. The event was sent at `2021-03-15 14:44 Z`, or `1615819475637`, with stream ordering `1878538882`.

Next step is to investigate the sync requests from each device.

Reported by @dbkr.

**Comment by bwindels** [comment]
Related/dupe of #9424

**Comment by anoadragon453** [comment]
@bwindels thanks.
