### ISSUE TITLE
Supports the ability to get access_token for new users when m.login.password=false

### ISSUE THREAD

**Issue by Ais8Ooz8** [matrix-org/synapse#9625]
When I do PUT /_synapse/admin/v2/users/<user_id> it is possible to set password as a body parameter

https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#create-or-modify-account

Then I should do POST /_matrix/client/r0/login to create access_token for any new user

But how can I get access_token without m.login.password=true ?

**Comment by clokep** [comment]
Are you trying to get an access token for the user as an admin? Or having the user login? If you have password logins disabled, how are you having users login?

**Comment by Ais8Ooz8** [comment]
As an admin I take access tokens for tech users (bots, services) https://t2bot.io/docs/access_tokens

People use OIDC login so for security reasons I would prefer to turn off .login.password

**Comment by dklimpel** [comment]
Have you seen? https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#login-as-a-user

**Comment by Ais8Ooz8** [comment]
Oh, just what I need. How could I not have noticed.
