### ISSUE TITLE
Do federation catchup in "buckets"

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9632]
When trying out `v1.30.0rc1` when fixing my federation stall (which was fixed by #9561), I set the `stream_id` to `0`, which means the federation senders are now trying to send all events since the beginning of my homeserver history.

To me, this is not a huge deal, federation will restore eventually (eventual consistency), but I noticed that each caught-up event is being sent individually, while with the batching nature of matrix, you could send up to 100 (sanity-limited to 50) events at a time to a server.

Would it be possible to allow for the federation sender to take "chunks" of events (about a 100) which turn out to be send-able, and send these in batches at a time? This could increase catch-up speeds, and allow higher throughput even when the federation sender "stumbles" and gets into catch-up mode.

**Comment by reivilibre** [comment]
so you're saying that the transactions leaving the server only have 1 event in them? That's not what was intended; it was meant to send the latest event from up to 50 rooms at once…

**Comment by ShadowJonathan** [comment]
That's not what's happening in `_process_event_queue_loop`, which is what I'm referring to.

**Comment by richvdh** [comment]
to be clear: it sends the most recent event for each room. Only one event per room. I'm absolutely certain that if more than one room is "behind", it will send more than one event in each catchup transaction.

**Comment by richvdh** [comment]
> Yup, thats what's not happening in `_process_event_queue_loop`, which is what I'm referring to.

I don't think `_process_event_queue_loop` is particularly relevant during federation catchup.

**Comment by ShadowJonathan** [comment]
Yeah i just found out about the actual behaviour of federation senders in #9635, it's grabbing batches of 100 and then queueing them into transmission loops.

I guess the reason why it's not so fast us because it's doing database accesses for each of them, meaning that giving events go the transmission loops will be a tad slow.
