### ISSUE TITLE
Stream stream_id events per destination

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9633]
Tangentially related to #9632, but would it be possible to (and keep track of) the per-destination `stream_id`? Then federation senders can stream/queue events to these destinations independently of other hosts (something i see happening where federation PDU sending takes as long as the slowest host).

**Comment by reivilibre** [comment]
Is this different from what's in the `destinations` table already — `last_successful_stream_ordering`?
If so, mind elaborating on it a little bit? I'd like to follow along a bit with this stuff but I'm not active in the codebase…

**Comment by ShadowJonathan** [comment]
Oh, wait, i just recognised and saw that my proposed behaviour is exactly how transmission loops send events, it's just that processing for it appears to go a little too slow to actually get to those 50 events for my federation sender, hmm...
