### ISSUE TITLE
Missing Apache Conf

### ISSUE THREAD

**Issue by synexTG** [matrix-org/synapse#9656]
**Description:**

The mentioned Apache Sites conf ist not working anymore. I would be happy to see a complete working guide on how configure synapse for Apache. 

https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md

**Comment by richvdh** [comment]
please could you explain what is wrong with the example config?

**Comment by synexTG** [comment]
If you just paste it you will notice that after the ServerName attribute the ";" is wrong also if you use this you will still land on the homepage. If you want to look deeper into that i will reinstall it on my server and send you all information.

**Comment by erikjohnston** [comment]
Thanks! If you could include everything you know needs to be changed, that'd be really useful

**Comment by synexTG** [comment]
So i installed all with the install.md instructions, i am using the following apache conf:

```
<VirtualHost *:80>
    ServerName mydomain.com
        Redirect permanent / https://mydomain.com

</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    ServerName mydomain.com
    SSLCertificateFile /etc/letsencrypt/live/mydomain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.com/privkey.pem
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    AllowEncodedSlashes NoDecode
    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
    ProxyPass /_synapse/client http://127.0.0.1:8008/_synapse/client nocanon
    ProxyPassReverse /_synapse/client http://127.0.0.1:8008/_synapse/client
</VirtualHost>
```

I am still landing on the default apache site (default index.html in the web root folder). The apache server is reloaded successfull, all needed modules are enabled (proxy_http, headers, ssl).

**Comment by synexTG** [comment]
psh

**Comment by richvdh** [comment]
this isn't a great place to come for support. If you need help getting set up, please go to `#synapse:matrix.org`.

**Comment by synexTG** [comment]
Following information: The configurations works but it doesn't show the matrix home site. 
The only task todo, if the home site doesnt matter, is to remove the simocolons (;) in the doc.
