### ISSUE TITLE
Do not rate limit invites if an appservice has `rate_limited: False` set

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#9663]
At the moment we are having issues with an EMS script that creates rooms en masse for customers looking to migrate. However calls made to /createRoom will fail due to a recent change to rate limit the number of invites allowed at room creation time. It would be good if the rate_limited: False flag could be respected here, and the limiting be disabled for users attempting to create rooms inside the AS namespace.

**Comment by Half-Shot** [comment]
(Goes without saying that this used to work before the invites were rate limited, so this is a recent breakage)

**Comment by rxl881** [comment]
@Half-Shot -- Thanks for flagging this.

@callahad is it intentional that the rate limiting flag isn't being respected in this case? If not, is it possible to get a fix scheduled relatively quickly? It is currently breaking the EMS migration tools :(

**Comment by Half-Shot** [comment]
This will also be impacting any bridges that need to invite users to "admin rooms" to a degree, although there is an argument that the bridge should retry on 429 when inviting. 

This will also break the use case where the bridge will try to create a channel with a prefilled invite list of users of more than 5 users (by default), which we do when doing a migration or as part of the Slack bridge's group DM system. I'm sure there are other bridges out there that run a createRoom with an invite list of >5 too.

**Comment by callahad** [comment]
We think we can fix the immediate issue in short order (this time next week), but also expect similar one-off issues to continue cropping up with the current design of our rate limiting.

Until we manage to more deeply refactor our implementation, just let us know when you hit another one of these and we'll knock that down, too. :)

**Comment by Half-Shot** [comment]
Happy to holler when things break :)
