### ISSUE TITLE
Drop backwards-compatibility support for "outlier" in the database

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#9670]
Since #9411, Synapse no longer makes use of the `outlier` flag in the `internal_metadata` column. Once we are satisfied that nobody will need to roll back to Synapse 1.30 or earlier, we should stop populating that flag.

**Comment by richvdh** [comment]
@callahad: Synapse 1.31 has been out since March, so I think we should be good to do this asap.

**Comment by callahad** [comment]
Agreed, this could go in any time.
