### ISSUE TITLE
SSO fail ( ERR_TOO_MANY_REDIRECTS )

### ISSUE THREAD

**Issue by OmmyZhang** [matrix-org/synapse#9680]
After I upgrade synapse, I find I can no longer login with oidc. It jumps to <my_homeserver>/_matrix/client/r0/login/sso/redirect?redirectUrl=<my_web/element>, then 302 to itself agina and agin.

I have rewritten the `oidc_providers` part as the https://github.com/matrix-org/synapse/blob/master/docs/openid.md says (it used to be `oidc_config`), but this problem still happened. 
It even never jump to issuer url so I think this problem is not related to the list of permitted "redirect URIs" at the identity provider.(v1.27.0)

Can anyone give me some hints? Is there any other breaking change related to oidc?

**Comment by richvdh** [comment]
check your logs, there may be messages about "not canonical" URLs

if so, make sure you have set `public_baseurl` correctly and check https://github.com/matrix-org/synapse/blob/develop/UPGRADE.rst#requirement-for-x-forwarded-proto-header.

**Comment by OmmyZhang** [comment]
It's solved after I change my reverse-proxy configuration. Thank you!

**Comment by trogeat** [comment]
> It's solved after I change my reverse-proxy configuration. Thank you!

Hi @OmmyZhang, can you give more details on the reverse proxy configuration ?

Thanks :-)

**Comment by OmmyZhang** [comment]
@trogeat Hi, here is my Nginx configuration

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    listen 8448 ssl http2;
    listen [::]:8448 ssl http2;

    server_name sub1.example.com sub2.example.com;

    location ~* ^(\/_matrix|\/_synapse\/client) {
        proxy_pass http://localhost:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        client_max_body_size            500M;
    }
}
```

mainly follow this https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md .

Hope this help.
