### ISSUE TITLE
Dialog for legal agreement

### ISSUE THREAD

**Issue by leviathan009** [matrix-org/synapse#9687]
**Description:**

In the EU a service provider processing and storing person related data is enforced by law of DSGVO to provide a declaration of privacy protection (in german: Datenschutzerklärung). Under certain circumstances a user even has to actively agree to them and as a provider you sometimes have to prove that consent.

To make this possible synapse would have to provide an REST endpoint where such a declaration customized by the provider of the homeserver could be stored. Then a matrix client like element would be able to query and display it to the end user and also aks for consent. That consent could then be stored by synapse.

Cheers!

**Comment by leviathan009** [comment]
Oh, and also the user needs to be able to find that declaration of privacy protection again afterwards!

**Comment by clokep** [comment]
Have you seen the user consent framework that's built in? https://github.com/matrix-org/synapse/blob/master/docs/sample_config.yaml#L2596

I'm not sure a link is easily available in clients afterward, but it might be.

**Comment by richvdh** [comment]
sounds like the functionality required is already available.
