### ISSUE TITLE
/thirdparty/protocols API returned an empty object for an appservice that wasn't ready

### ISSUE THREAD

**Issue by jaller94** [matrix-org/synapse#9694]
### Description
`/thirdparty/protocols` returned 
```
{ irc: {} }
```

The `irc` object is missing a few required values.

https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-thirdparty-protocols

### Steps to reproduce

- I set up my IRC bridge but the pingback port wasn't working yet (I had set it to the wrong port in the appservice file) and the IRC server on localhost wasn't connecting yet.

Synapse-config, Bridge config and logs (look around the time 2021-03-25 20:44):
https://gateway.pinata.cloud/ipfs/QmTbjP9PwfaTELkYQQ1HmznR4n8GNusveE6BwpZXw5tjk4

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
- Synapse 1.29.0 with Python 3.8.8
- https://registry.hub.docker.com/layers/matrixdotorg/synapse/latest/images/sha256-67a507a29e0406a0e93a9040617380f7310f625e86adb5652ef24cd1ce39db48

- **Install method**:
- DockerHub's `matrixdotorg/synapse:latest`

- **Platform**:
- Manjaro Linux (based on the repo of Arch Linux)

### Additional notes:

The API response caused an issue in Element Web because it's not spec-compliant.

https://github.com/vector-im/element-web/issues/16789

https://user-images.githubusercontent.com/10872136/112535146-3a7b9100-8dac-11eb-9270-a7f4746d6300.mp4

**Comment by cremesk** [comment]
@jaller94 You can delete the `protocols` section of the registration file, if you are running your own irc bridge.

**Comment by Half-Shot** [comment]
The bug here is that synapse shouldn't return results for bridges it can't reach on this endpoint, rather than a bug in the bridges themselves.

**Comment by skepticalwaves** [comment]
Looks like https://github.com/Half-Shot/matrix-appservice-discord currently returns an empty protocol as well
