### ISSUE TITLE
Our Debian build scripts do not respect DEB_BUILD_OPTIONS=nocheck to skip running unit tests

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#9706]
By convention, scripts to build Debian packages should skip running unit tests if the environment variable DEB_BUILD_OPTIONS contains the string "nocheck"

For example, dh-virtualenv [specifies](https://github.com/spotify/dh-virtualenv/blob/1.2.2/bin/dh_virtualenv#L51-L54)

```python
if 'nocheck' in os.environ.get('DEB_BUILD_OPTIONS', ''):
    do_test = False
else:
    do_test = options.setuptools_test
```

But Synapse doesn't respect this.

In our `debian/build_virtualenv` file we [always run the tests](https://github.com/matrix-org/synapse/blob/v1.30.1/debian/build_virtualenv#L53-L61):

```sh

# we copy the tests to a temporary directory so that we can put them on the
# PYTHONPATH without putting the uninstalled synapse on the pythonpath.
tmpdir=`mktemp -d`
trap "rm -r $tmpdir" EXIT

cp -r tests "$tmpdir"

PYTHONPATH="$tmpdir" \
    "${TARGET_PYTHON}" -m twisted.trial --reporter=text -j2 tests
```

It would be good if that was conditional and skipped if `DEB_BUILD_OPTIONS` included `nocheck`.

It may be that this should go in our `debian/rules` file under `override_dh_auto_test:` or similar, instead of in the `debian/build_virtualenv` file.

**Comment by richvdh** [comment]
Looks like this was fixed in #9793.
