### ISSUE TITLE
Bugfixes on v1.31.0 repos  [cryptography]

### ISSUE THREAD

**Issue by AnonymousWebHacker** [matrix-org/synapse#9722]
I noticed that it is a bug that is fixed in v1.31.0rc1. https://github.com/matrix-org/synapse/releases/tag/v1.31.0rc1
- Bugfixes [Fix a bug introduced in Synapse 1.30.1 which meant the suggested pip incantation to install an updated cryptography was incorrect. (#9699)]

Upgrade to 1.31 and it gave me that error. ;(
I tried to update the crypto version, but I don't know which version cryptography I should use with synapse 1.31
I read some issues but nothing clear, unless the cryptography had not been updated.

I am using repositories.
  So? If it is only up to v1.30 for repos, am I going to have to wait until the update comes out?

**Comment by AnonymousWebHacker** [comment]
@richvdh How can I see the version of Cryptography I can install so that it works with synapse v1.31 until it gets fixed in the repos?
 
 https://github.com/paramiko/paramiko/issues/1369#issuecomment-456940895

**Comment by AnonymousWebHacker** [comment]
```Apr  1 00:30:48 nodex systemd[1]: Starting Synapse Matrix homeserver...
Apr  1 00:30:50 nodex matrix-synapse[3335]: /opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/conch/ssh/common.py:14: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Apr  1 00:30:50 nodex matrix-synapse[3335]:   from cryptography.utils import int_from_bytes, int_to_bytes
Apr  1 00:30:53 nodex matrix-synapse[3343]: /opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/conch/ssh/common.py:14: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
Apr  1 00:30:53 nodex matrix-synapse[3343]:   from cryptography.utils import int_from_bytes, int_to_bytes
Apr  1 00:30:53 nodex systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Apr  1 00:30:53 nodex systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Apr  1 00:30:53 nodex systemd[1]: Failed to start Synapse Matrix homeserver.
```
`common.py:14: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead` and `from cryptography.utils import int_from_bytes, int_to_bytes`

**Comment by richvdh** [comment]
> common.py:14: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead and from cryptography.utils import int_from_bytes, int_to_bytes

this is a warning, not an error. Your problem lies elsewhere; check the homeserver log. If that doesn't help, try running synapse direct from the commandline rather than via systemd.

I'm going to close this issue as I think it is invalid; please use `#synapse:matrix.org` for support in getting Synapse set up.

(The `CryptographyDeprecationWarning` will be suppressed in Synapse 1.31 by #9698).

**Comment by AnonymousWebHacker** [comment]
Fixed @richvdh
`pip install -U cryptography`
What happened is that they can be registered without problems, but for example, if I tried to enter from another section, it told me a cryptography error.

I had read your comments, and I know that this error that appears in the logs is a precaution and not an error in itself. Only that it did not let others start section, due to cryptography problems and the connection to the DB
