### ISSUE TITLE
Add support for Ubuntu’s Hirsute Hippo (21.04)

### ISSUE THREAD

**Issue by jryans** [matrix-org/synapse#9732]
Hirsute is on the way to release: https://lists.ubuntu.com/archives/ubuntu-announce/2021-April/000267.html

**Comment by clokep** [comment]
> with the final release expected on April 22nd, 2021.

Looks like we'll need this for Synapse v1.33.0 then?

**Comment by richvdh** [comment]
now released

**Comment by callahad** [comment]
Will be fixed by #9909

**Comment by babolivier** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/9909
