### ISSUE TITLE
Add arm64 package to repository 'https://packages.matrix.org/debian focal InRelease'

### ISSUE THREAD

**Issue by A-R-M** [matrix-org/synapse#9737]
**Hardware:**
Raspberry Pi 4 Model B
**Operating System:**
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1032-raspi aarch64)

Attempted to install the prebuilt Debian/Ubuntu package for the latest stable version of Synapse following the instructions [here](https://github.com/matrix-org/synapse/blob/master/INSTALL.md#prebuilt-packages). However, after running `sudo apt update`, `apt` returns the following message:

`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://packages.matrix.org/debian focal InRelease' doesn't support architecture 'arm64'`

**Comment by richvdh** [comment]
dup https://github.com/matrix-org/synapse/issues/1496

**Comment by marcdraco** [comment]
Same issue @richvdh per #1496 - more details there but definitely not working. Are you able to offer any assistance?
