### ISSUE TITLE
MyPy-lint the whole codebase

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/synapse#9741]
This is a bit of a "sentinel" issue, to be able to mypy-check the *whole* of `synapse/` and `tests`/, at the very least.

While working on #9682 i noticed that mypy is missing a *lot* of corners, so im making this issue to work towards.

---

Simply; the goal is to reduce the `[mypy]` -> `files=` key in [this file](https://github.com/matrix-org/synapse/blob/develop/mypy.ini) down to `synapse/,`, so that one mypy pass goes over the entire database unequivocally.

**Comment by clokep** [comment]
Is this essentially #8351?

**Comment by ShadowJonathan** [comment]
No, that issue calls for `var: Type` instead of `var = [...]  # type: Type`, it also calls for *more* variable annotations.

What this issue is about is to make [these lines](https://github.com/matrix-org/synapse/blob/4609e58970a95768170ca8c8ab52abc1998b866c/mypy.ini#L18-L77) effectively only be `synapse/,`, so to speak, to have mypy check the entire `synapse/` codebase instead of a subset of subdirectories and files.

**Comment by clokep** [comment]
Closing in favor of #11271.
