### ISSUE TITLE
Enable spaces summary (MSC2946) tests in complement

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#9756]
(Making this here, not the complement repo, since it probably requires some implementation changes?)

We should run the Spaces Summary tests in complement with Synapse. They do not currently pass, however.

Things to do:

* [ ] Enable spaces in the homeserver config.
* [ ] Enable the `msc2946` build tag for `complement.sh`
* [ ] Fix broken tests:
    * [ ] query whole graph
    * [ ] max_rooms_per_space
    * [ ] limit
    * [ ] redact link

Related to #9446

Note that the federation tests do pass, it is just a few of the client tests which fail.

**Comment by clokep** [comment]
@richvdh was there any other context for this? I failed to record in my notebook what you thought the issue was? From looking into this a bit I think it is the extra link that goes back up to the root that Dendrite and Synapse are handling differently. If you remember any context I'd love to hear it, but if not that's OK!

**Comment by clokep** [comment]
Ah, if I recall it was something about the Dendrite implementation looking both "up" and "down" the tree when generating the summary, but Synapse only looking "down"? Do we think the solution is to match the Dendrite implementation or update the tests?

**Comment by richvdh** [comment]
sorry, just found this. As discussed earlier: I think we probably want to update the tests to match the latest thinking on the behaviour for the API... then at some point Dendrite will probably have to be updated too.
