### ISSUE TITLE
url_preview should check for cache expiry on previews

### ISSUE THREAD

**Issue by skepticalwaves** [matrix-org/synapse#9775]
**Description:**

We've run into a situation where a page had one image embedded for a preview and now has another, however since synapse has already cached the image it doesn't fetch a new image.

I think some combination of file size/cache expiry/age and other cleverness could be added to make synapse re-fetch the image preview.

**Comment by anoadragon453** [comment]
From looking at the code it appears that Synapse will refetch URL previewed content, including images, after one hour. Expired previews are culled from the cache every 10 seconds (that seems a bit fast actually):

https://github.com/matrix-org/synapse/blob/44bb881096d7ad4d730e2dc31e0094c0324e0970/synapse/rest/media/v1/preview_url_resource.py#L180-L183

Images should be refetched, but expired images aren't actually deleted until 2 days later (unless a client with old state tries to refetch it):

https://github.com/matrix-org/synapse/blob/44bb881096d7ad4d730e2dc31e0094c0324e0970/synapse/rest/media/v1/preview_url_resource.py#L628-L632

It's noted that we could probably be smarted about the 1 hour expiry time:

https://github.com/matrix-org/synapse/blob/44bb881096d7ad4d730e2dc31e0094c0324e0970/synapse/rest/media/v1/preview_url_resource.py#L521-L526

But 1 hour sounds sensible as a default. Other than that I think Synapse already does what you want @skepticalwaves, you'd just need to wait at most 1 hour before both clients were in sync?

**Comment by skepticalwaves** [comment]
Cool. So this works. Is this actually in the documentation anywhere? I tried finding it in the code but github's search is just awful.

**Comment by anoadragon453** [comment]
> Cool. So this works. Is this actually in the documentation anywhere? I tried finding it in the code but github's search is just awful.

I don't think so... [documentation for URL previews](https://github.com/matrix-org/synapse/blob/develop/docs/url_previews.md) does exist, but it's more of a rationale of the technical design that sysadmin facing...

**Comment by skepticalwaves** [comment]
I fully endorse this, being primarily a sysadmin for matrix server and only secondarily a dev.
