### ISSUE TITLE
Limit upload capacity for all users on the server

### ISSUE THREAD

**Issue by githuberyt** [matrix-org/synapse#9784]
Limiting every user to specific capacity for uploading files like 1 GB per user or such would increase servers effectivity and fight spammers

**Comment by anoadragon453** [comment]
@githuberyt To be clear you're talking about limiting the maximum amount of storage a user could upload in total?

I think a pre-requisite to this might be first allowing users to delete uploaded media: https://github.com/matrix-org/matrix-doc/issues/790

**Comment by richvdh** [comment]
think this is a dup of https://github.com/matrix-org/synapse/issues/3339
