### ISSUE TITLE
Generalize check_media_file_for_spam

### ISSUE THREAD

**Issue by Yoric** [matrix-org/synapse#9806]
It is my understanding that the current implementation of `check_media_file_for_spam` doesn't work on all configurations of Synapse. It would be nice if we could make it work everywhere.

**Comment by clokep** [comment]
Can you describe a bit more about the conditions in which it doesn't work? I'm pretty sure it should work regardless of the configuration...

**Comment by Yoric** [comment]
It is my understanding that it will work e.g. on matrix.org but not on EMS.

@erikjohnston knows more than me about that.

**Comment by clokep** [comment]
I think this is because EMS doesn't use the media repo from Synapse?

**Comment by erikjohnston** [comment]
Yeah, EMS uses https://github.com/turt2live/matrix-media-repo
