### ISSUE TITLE
Federation signatures of own messages fail if DNS of HS resolves to 127.0.0.1 / ::1

### ISSUE THREAD

**Issue by mguentner** [matrix-org/synapse#9831]
### Description

`@alice.matrix.example.com` invites `@alice:matrix.federated.com` to an invite-only room.

The hostname was set to `127.0.0.1` / `::1` for the `matrix.example.com` in `/etc/hosts` on the server that hosts `matrix.example.com`,
e.g.

```
127.0.0.1 matrix.example.com
::1 matrix.example.com
```
This was useful to resolve reverse proxy issues with the acme client for lets encrypt.

matrix.example.com has a valid A and AAAA record and is green @ https://federationtester.matrix.org/
matrix.federated.com has a valid A and AAAA record and is green @ https://federationtester.matrix.org/

An invite shown the to the invited user `@alice:matrix.federated.com` but the room cannot be joined with the error
```
403 - You are not invited to this room.
```

Logs on `matrix.example.com`:

`synapse.http.client`:

```
[None] Dropped 127.0.0.1 from DNS resolution to matrix.example.com due to blacklist
[None] Dropped ::1 from DNS resolution to matrix.example.com due to blacklist
```
This breaks `synapse.http.federation.matrix_federation_agent`:

```
Failed to connect to matrix.example.com:8448: DNS lookup failed: no results for hostname lookup: matrix.example.com
```

More error messages follow, all connected to this issue:

```
synapse.crypto.keyring: Error looking up keys {'ed25519:a_ZZZZ': 16133713373877} from matrix.example.com: Failed to send request: DNSLookupError: DNS lookup failed: no results for hostname lookup: matrix.example.com:
```

I believe that the blacklist should not apply if the domain_to_be_resolved == this_hs_domain

### Steps to reproduce

HS1 hosts `matrix.example.com`
HS2 hosts `matrix.federated.com`

- set matrix.example.com to `127.0.0.1` / `::1` in `/etc/hosts/` on HS1
- invite `@alice:matrix.federated.com` from `@alice.matrix.example.com`
- the invite appears at `@alice:matrix.federated.com` but she won't be able to join the room

- **Platform**: Linux / NixOS

**Comment by richvdh** [comment]
I think this is essentially a dup of https://github.com/matrix-org/synapse/issues/4024

**Comment by mguentner** [comment]
Most probably. Closing #4024 would fix this issue, however this causes silent failures for users.
They can invite and the invitee even receives them but they do not work. Quite an unexpected behavior for both users and administrators.
