### ISSUE TITLE
User directory search can't be disabled

### ISSUE THREAD

**Issue by privuser** [matrix-org/synapse#9836]
### Description

According to the documentation, setting:

> user_directory:
>    enabled:false

should disable user directory search by users. However this does not seems to work as advertised.

### Steps to reproduce

- Fresh installation with aforementioned configuration used
- Setup several users using synapse-admin
- Connect with a user on element and search other users
- After typing '@', element return a list of every user on the server

Expected behavior: element should not list the user list.

### Version information

Issue verified on a private homeserver
Synapse version: 1.31.0
Install method: Ansible playbook
Platform: VPS running Archlinux

**Comment by tulir** [comment]
This doesn't sound related to Synapse. I think the playbook defaults to redirecting user directory queries to ma1sd for some reason.

**Comment by privuser** [comment]
Thank you for the hint. Disabling ma1sd identity server from the playbook gives the expected behavior hence the problem is not synapse related.
