### ISSUE TITLE
Log out / delete all sessions of a user

### ISSUE THREAD

**Issue by jacotec** [matrix-org/synapse#9837]
**Description:**

I've played around with Matterbridge on my Nexcloud in January to have a Nextcloud Talk room connected to my Matrix account on my homeserver.

What I did not know: Matterbridge was opening a new session every few minutes. So from January to now I've ended with thousands of open sessions in my Synapse list, rendering my account pretty unusable.

There is no chance to check all these sessions in Element-Web and delete them here as even checking a single item in the list takes seconds. I guess this would take a day or more.

What is really missing is a "log out all sessions" button which deletes all active sessions. Such a thing is present in most projects for securlty reasons, we should have this in Synapse / Element as well.

Meanwhile, if someone could help with a database command to delete all the sessions it'll be helpful as a workaround.

**Comment by ShadowJonathan** [comment]
(relevant previous discussion, linking here for history: https://github.com/matrix-org/synapse/discussions/9790)

**Comment by dklimpel** [comment]
There is a `/logout/all` API: https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#login-as-a-user

**Comment by jacotec** [comment]
The question is if the /logout/all will also delete all >2000 devices which were created in my list

**Comment by dklimpel** [comment]
Why not? Also here: https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-logout-all
Try it.

**Comment by jacotec** [comment]
I'll do once I found out how to "issue" this command to the server ...

**Comment by jacotec** [comment]
@dklimpel Awesome! That worked! :-)

My host was around 10 mins nearly blocked due to datastore latency, the command timed out - but after that all devices are gone.

Thanks a ton!

**Comment by xelayz** [comment]
Hello. I have the same problem. I want to logout a user and I checked already the api docs. But I do not know how to use the api. Can someone tell me the command for my console? It is even possible to logout a user via one simple command? Thank you very much...
