### ISSUE TITLE
reverse proxy / forward proxy

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/synapse#9842]
I have sort of setup the reverse proxy. But I assume synapse is connecting to other servers for this identity lookup or rooms not configured on the local server. How/where do I configure the forward proxy so the synapse knows how to connect to the internet?

[1]
https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md

**Comment by richvdh** [comment]
dup #9844
