### ISSUE TITLE
Could the SpamCheck API's `check_event_for_spam` return `shadowban`?

### ISSUE THREAD

**Issue by Yoric** [matrix-org/synapse#9851]
Would there be any blocker to extending this API into something that would cause the spammer to believe that their action has succeeded while making sure that users don't see anything?

**Comment by ShadowJonathan** [comment]
No, I think shadowbanning for a spam measure is a bit heavyhanded, see some discussion in #9334, i think shadowbans should be given *explicitly* manually via the admin API in this regard, then.

**Comment by anoadragon453** [comment]
I'm not sure if @Yoric is talking about *shadowbanning* the user automatically, but rather treating the user as if they were shadowbanned (return a success but don't persist the event) specifically while sending an event that's determined to be spammy.

**Comment by Yoric** [comment]
> I'm not sure if @Yoric is talking about _shadowbanning_ the user automatically, but rather treating the user as if they were shadowbanned (return a success but don't persist the event) specifically while sending an event that's determined to be spammy. But not for any subsequent, valid requests.

Absolutely.

After thinking a bit more, though, I'm not certain that it's the right solution to any of the problems I'm looking at.
