### ISSUE TITLE
Message didn't show up in the recipient's client

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#9872]
I (on vector.modular.im) was talking to @bwindels (on matrix.org) in a DM (`!IIjQEpRLMKKEPNNcTw:vector.modular.im`) and one of the events (`$TC2N5KGHsJO_e-EeQ75s9e3UvzD_wlouRXDOV-VVbPU`) didn't show up on his client. He says it happened in both Element Web and Hydrogen, so imho the likeliest explanation is that for some reason Synapse didn't send it down sync responses.

I replied to the message and the reply apparently showed up fine in Bruno's client (instead of telling him the original message can't be displayed) so I'm not ruling out a client/SDK bug but my client dev foo isn't good enough to conclude on where the issue happened, and this issue could probably use a quick investigation to check whether it went missing on the server side of things.

**Comment by bwindels** [comment]
I checked Hydrogen's storage for the event id, and couldn't find it, also pointing towards having never received it.

**Comment by bwindels** [comment]
Possible dupe of https://github.com/matrix-org/synapse/issues/9424

**Comment by bwindels** [comment]
Checking on Hydrogen on my phone some minutes after, the event does show up while back-paginating.

**Comment by babolivier** [comment]
> Possible dupe of #9424

It looks like the symptoms are similar except that in my Element Web the message didn't get stuck at the bottom of the timeline.

**Comment by babolivier** [comment]
Closing this as it's actually probably #9424
