### ISSUE TITLE
Limit how often we do a GC.

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#9890]
We support configuring the GC thresholds via the [`gc_thresholds`](https://github.com/matrix-org/synapse/blob/develop/docs/sample_config.yaml#L151-L153) config option, however the default can lead to a lot of GC churn on busier instances. This can easily lead to a) a CPU usage by GC of ~20% and b) multiple multi second GC pauses in quick succession.

Since we manually run the GC we could add limits to ensure we don't run the GC e.g. gen 0 no more than once a second, gen 1 no more than once every 10s and gen 2 no more than once every 30s. This a) enforces that we don't repeatedly do gen2 really frequently and b) stops objects getting promoted to gen2 far too quickly.

**Comment by ShadowJonathan** [comment]
How does letting python trigger the GC automatically fare to this? Does python itself have a smart algorithm (or the sorts) that makes it able to "back off" in such a fashion? #9813

**Comment by erikjohnston** [comment]
We use the exact same algorithm as python already, the only thing we do is ensure they happen after a reactor tick, but as per the issue that shouldn't make any difference.
