### ISSUE TITLE
Investigate elevated CPU use on matrix.org synchrotrons

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#9924]
Looks like CPU use on synchrotrons went up significantly on May 1st (Saturday):

![Screen Shot 2021-05-04 at 23 15 27](https://user-images.githubusercontent.com/24193/117076689-b6afaf80-ad2e-11eb-9161-5cb725edd3eb.png)

Did we deploy anything on Friday? Are there other events we can correlate with this?

We deployed fe604a022a7142157da7e90a40330beb2a11af7a on the evening of Thursday, April 27th

@anoadragon453 Do you know what was deployed prior to that? Have there been any deploys since?

**Comment by callahad** [comment]
Un-stacking the CPU graph doesn't reveal any obvious outliers:

![Screen Shot 2021-05-04 at 23 25 42](https://user-images.githubusercontent.com/24193/117077536-35f1b300-ad30-11eb-99bd-067b850fa46f.png)

**Comment by erikjohnston** [comment]
What graphs are those? Stacking the process CPU usage on the synapse dashboard gives me:

![Screenshot from 2021-05-05 09-56-44](https://user-images.githubusercontent.com/8428120/117118112-4afa3080-ad88-11eb-83ba-e02b9cdf5c88.png)

**Comment by callahad** [comment]
https://grafana.matrix.org/d/000000012/synapse?viewPanel=120&orgId=1&from=1614446247840&to=1620133795315&var-datasource=default&var-bucket_size=$__auto_interval_bucket_size&var-instance=matrix.org&var-job=synapse_synchrotron&var-index=All

**Comment by callahad** [comment]
This, with near certainty, is a rendering artifact in Grafana.

**Comment by richvdh** [comment]
I've opened https://github.com/grafana/grafana/issues/33742 with Grafana.  TL;DR: the stacked-graphs don't work right if some of the series contain null values.

**Comment by callahad** [comment]
Setting "null value: null as zero" seems to fix the rendering issues:

![Screen Shot 2021-05-05 at 13 08 58](https://user-images.githubusercontent.com/24193/117138695-47c06e00-ada3-11eb-859a-32bc686d02c0.png)
