### ISSUE TITLE
Can't success to send files in some conditions

### ISSUE THREAD

**Issue by GodGoldfish** [matrix-org/synapse#9925]
Hi,
i'm really confused, i don't success to send mp4 file, pdf file and sometimes image file (by selecting it or pasting it or by dropping the file on the window) i have this problem on the element client but also on the others (android & linux), it shows «the message can't be sent» i tried to change the upload limit (even if the problem was no that) from 50M to 200MB but it didn't change anything.

i'm currently dying for help,
please help this poor goldfish.

Thanks !

**Comment by GodGoldfish** [comment]
![test](https://user-images.githubusercontent.com/78706835/117105302-023d7a00-ad7e-11eb-86fa-da6a65cc2aa8.png)

**Comment by babolivier** [comment]
Could you have a look at the upload request that is being sent please? To do so, open the developer tools in your browser by hitting F12 (or finding them in your browser's menu), selecting the "Network" tab, and looking for a request on a path that ends with `upload` - then click on it and click on the "Response" tab. There should be more information in there about why the server is rejecting your upload.

**Comment by GodGoldfish** [comment]
![image](https://user-images.githubusercontent.com/78706835/117141896-6167b280-adaf-11eb-9695-f2d9289bd10c.png)


Access to XMLHttpRequest at 'https://MATRIX.EXEMPLE.ORG/_matrix/media/r0/upload' from origin 'https://app.element.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

http-api.js:332 POST https://MATRIX.EXEMPLE.ORG/_matrix/media/r0/upload net::ERR_FAILED

**Comment by babolivier** [comment]
Right, this seems to mean there is something wrong in the way your homeserver is setup. Like your other issue, this seems to be more into support territory than bug, so I'd recommend asking in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) for help with your setup.

**Comment by GodGoldfish** [comment]
i comment the answer to the problem for people that would have the same problem.

in my case the problem was the nginx configuration file, it needs this to work properly :
` client_max_body_size 50M;`

**Comment by michaelnew** [comment]
@GodGoldfish You're a hero for coming back and posting that solution. Might not have been related to Synapse, but I had no way of knowing that and it really helped me out to find that here. Thanks :)
