### ISSUE TITLE
Error during PostgreSQL synapse conversion from SQLite synapse

### ISSUE THREAD

**Issue by GodGoldfish** [matrix-org/synapse#9926]
Hi,
i already tried the documentation "https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md" but once i start the command `synapse_port_db --sqlite-database homeserver.db.snapshot \
    --postgres-config homeserver-postgres.yaml` i have this message appearing : «Database must use the 'psycopg2' connector.»

**i installed matrix synapse in a python virtualenv**

if someone can explain me how to use PostgreSQL at the place of SQLite please it would be cool !
i'm currently dying for help,
please help this poor goldfish.

Thanks !

**Comment by babolivier** [comment]
It looks like the database config included in `homeserver-postgres.yaml` points to the SQLite database. The documentation you have linked to says:

> Edit the database section as described in the section _Synapse config_ above

So you need to replace the `database` section of the configuration file as described at https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md#synapse-config

Also heads up that we mostly use github issues for bug reports; for support requests like this one you'll get quicker answers if you ask them in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org) or in the [Discussions tab](https://github.com/matrix-org/synapse/discussions).

**Comment by GodGoldfish** [comment]
i fixed the problem by doing this :
`ubuntu@hostname:~$ sudo -u postgres bash
postgres@hostname:/home/ubuntu$ createuser --pwprompt synapse_user
postgres@hostname:/home/ubuntu$ psql
postgres=# CREATE DATABASE synapse
 ENCODING 'UTF8'
 LC_COLLATE='C'
 LC_CTYPE='C'
 template=template0
 OWNER synapse_user;
"CREATE DATABASE"
postgres=# exit
postgres@hostname:/home/ubuntu$ exit
ubuntu@hostname:~/synapse$ cd synapse/
ubuntu@hostname:~$ source env/bin/activate
(env) ubuntu@hostname:~/synapse$ synctl stop
(env) ubuntu@hostname:~/synapse$ cp homeserver.yaml homeserver-postgres.yaml
(env) ubuntu@hostname:~/synapse$ nano homeserver-postgres.yaml
(env) ubuntu@hostname:~/synapse$ synapse_port_db --sqlite-database homeserver.db.snapshot \
    --postgres-config homeserver-postgres.yaml --curses
(env) ubuntu@hostname:~/synapse$ mv homeserver.yaml homeserver-old-sqlite.yaml
mv homeserver-postgres.yaml homeserver.yaml
`
