### ISSUE TITLE
Re-introduce "Leave out optional keys from /sync"

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#9941]
The changes from #9919 were backed out in #9940 as it broke notifications on Element iOS.

We should re-introduce #9919 as soon as we're able.

Blockers:

- [x] Fix Element iOS vector-im/element-ios#4309
- [x] Wait for a fixed Element iOS release to gain sufficient adoption

**Comment by richvdh** [comment]
I think we should set a target on doing this work, otherwise it's never going to happen.

@manuroe: I'm going to assume it is realistic that we will be able to do this in three months (ie, by 6th August). Please let us know if you think that is too ambitious.

**Comment by manuroe** [comment]
The fix will be available in the release we will make in 2 weeks. 95% of people update their app within 1 week.

**Comment by deepbluev7** [comment]
Also related: https://github.com/vector-im/hydrogen-web/pull/343 https://github.com/poljar/matrix-nio/commit/6097f2c48fca0c3802199c4998dc4883b513e758

Although those are merged already at least.

**Comment by deepbluev7** [comment]
FTR, this is now fixed in iOS. Not released yet though.

https://github.com/matrix-org/matrix-ios-sdk/pull/1100

**Comment by tulir** [comment]
The release seems to have hit app store 9 days ago, so I guess 95% of people should have updated by now. Can we get this into 1.37? :3
