### ISSUE TITLE
Synapse consume all the server’s RAM

### ISSUE THREAD

**Issue by Toniob** [matrix-org/synapse#9969]
### Description

I’m running a medium sized matrix server (1650 users currently). For a few weeks now, the server is unstable. The reason is Synapse is eating all the RAM until the OOM triggers its death. Then, systemd restarts the process and it goes on and on like this. I’ve tried to clean my database, reindex it, compact it, nothing is working. It’s the same issue with or without workers.

The hardware is ok, as I have 32GB of ram and a quad core xeon. The database and synapse are running on an ssd raid.

Here is a screenshot of the RAM monitoring. That’s the last 6 hours. When the RAM usage drops, that’s when the main process is killed, so it’s quite often.

![Screenshot_2021-05-11 matrix 6clones net - system - Grafana](https://user-images.githubusercontent.com/113461/117830674-257f9200-b274-11eb-9e18-363eb96efae5.png)

Any idea ? Someone else with the same issue ?

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: converser.eu

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.31.0

- **Install method**: debian package (sid)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian bullseye
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by babolivier** [comment]
There are some tips on optimising Synapse's memory consumption here: https://github.com/matrix-org/synapse#help-synapse-is-slow-and-eats-all-my-ram-cpu

You should also ask in [`#synapse:matrix.org`](https://matrix.to/#/#synapse:matrix.org), which is our preferred channel for community support, especially given we don't use github issues for this (as stated in the issue template). People in this room may be able to help you fine tune your homeserver's configuration to better optimise its memory footprint.
