### ISSUE TITLE
Make typing_extensions just optional dependency

### ISSUE THREAD

**Issue by mcepl** [matrix-org/synapse#9994]
`typing_extensions` package doesn’t have to be dependency for Python 3.8 and newer. [This patch](https://github.com/matrix-org/synapse/files/6478927/stdlib-typing_extensions.patch.txt) makes the dependency just optional.

**Comment by ShadowJonathan** [comment]
Can you maybe submit this as a PR? Also, there's `synapse.typing` which is often used for these cross-version import compatibilities.

**Comment by mcepl** [comment]
I am sorry, I am a co-maintainer of over 2000+ Python packages in openSUSE, I cannot afford to checkout out all of them. Please, apply this yourself (and I don't care about any recognition or anything from this).

**Comment by sumnerevans** [comment]
The patch doesn't apply to the latest `develop`

```
$ git apply ~tmp/stdlib-typing_extensions.patch.txt
error: patch failed: synapse/handlers/presence.py:29
error: synapse/handlers/presence.py: patch does not apply
error: patch failed: synapse/util/caches/lrucache.py:27
error: synapse/util/caches/lrucache.py: patch does not apply
```

**Comment by richvdh** [comment]
I don't really understand why we need this. It seems to add complexity to our codebase; the whole point of `typing_extensions` is to hold this backwards-compatibility code so that it doesn't need to be repeated in every single project.

Thank you for the patch but I don't think we can take it in its current form. If you'd like to see it included, we will need it submitted as a PR in accordance with our contribution policy in `CONTRIBUTING.md`.

**Comment by mcepl** [comment]
> I don't really understand why we need this. It seems to add complexity to our codebase; the whole point of `typing_extensions` is to hold this backwards-compatibility code so that it doesn't need to be repeated in every single project.

The package `typing_extensions` is completely useless for Python since 3.8. I would like to eventually get rid of it in openSUSE, and for that we have to patch it out of many packages.

> Thank you for the patch but I don't think we can take it in its current form. If you'd like to see it included, we will need it submitted as a PR in accordance with our contribution policy in `CONTRIBUTING.md`.

Yeah, sorry for trying to help you. We just have to carry on our patch because somebody is too lazy to apply one patch manually. Oh well.
