### ISSUE TITLE
Bring sample_config.yaml in line with actual generated config

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/synapse#9999]
### Description

https://github.com/matrix-org/synapse/blob/66609122260ad151359b9c0028634094cf51b5c5/docs/sample_config.yaml#L1-L2

### Steps to reproduce

- generate new config as detailed in INSTALL.md
- compare to doc

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

Config options appear in different order, while others do not appear at all in one or the other. It is so confusing that I stopped investigating advanced and updated config options at this point.

Perhaps synapse could benefit from a more modular ("conf.d") approach.

### Version information

- **Version**: 1.33.2

- **Install method**: pip into venv

- **Platform**: debian/pyenv/python 3.9
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by erikjohnston** [comment]
We enforce in CI that the sample config matches what is produced when we generate the config, so I'm confused you'd be seeing a difference. Are you comparing a sample config from a different version of Synapse? 

I manually run the steps from INSTALL.md and the only differences were: a) the header, b) the paths to the config files and c) we generated some default secrets.

**Comment by HarHarLinks** [comment]
Hello erik, thanks for your friendly answer. It seems the latest pyenv broke my workflow in such a way that I ended up calling some old Synapse version from the ether. The diff when calling it properly turned out like you described, so I'm sorry to have bothered you. Might I suggest the addition of a comment `# generated by synapse x.yy.z, arguments:` to the generated config?

My Synapse config is on the old side, it was first set up early 2017 and I took over administration a bit after. How do you suggest I keep the config updated properly? I read the UPGRADING notices, but there are a lot of options in the new conf I have never seen before.

Might it still be a good idea to support a `conf.d` approach? I can imagine synapse providing it's default config by means of `sample_config.yaml` split into a file per paragraph `conf.d/00-server.conf.sample`, and admins can override single options by putting a line into `conf.d/00-server.conf` making things easier to stay on top of. I'm sure you know what I'm talking about.

**Comment by erikjohnston** [comment]
> My Synapse config is on the old side, it was first set up early 2017 and I took over administration a bit after. How do you suggest I keep the config updated properly? I read the UPGRADING notices, but there are a lot of options in the new conf I have never seen before.

We try very hard to give sensible defaults and to maintain backwards compatibility, so you shouldn't need to do anything to keep your config up to date (unless you use an option that becomes deprecated, which we shout about in the upgrade notes). The majority of the new options are only useful for advanced or non standard use cases, so I wouldn't expect many of them to be of interest to most Synapse admins. indeed, my own server is still running on old config which I've barely touched in the last few years.

Unfortunately there isn't an easy way of taking your existing config and merging in the new changes, though it wouldn't change what Synapse did it would be nice to be able to merge in the documentation of all the options at least. TBH though, my own config is very bare bones and I just refer to the sample config as documentation if I want to add/modify the config.



> Might it still be a good idea to support a `conf.d` approach? I can imagine synapse providing it's default config by means of `sample_config.yaml` split into a file per paragraph `conf.d/00-server.conf.sample`, and admins can override single options by putting a line into `conf.d/00-server.conf` making things easier to stay on top of. I'm sure you know what I'm talking about.

We do support `conf.d` style approach when running Synapse, you can pass in multiple `--config-path` options and they can reference directories. Doing so for the sample config is a bit of a trade off though, as it's very nice to be able to search in a single file for what you are after (especially given our sections are often fairly arbitrary).
